### ISSUE TITLE
Instructions text error

### ISSUE THREAD

**Issue by mattfish** [FreeCodeCamp/FreeCodeCamp#10085]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instruction reads:
"Ensure that your stylesheet h2 declaration is valid with a semicolon and closing brace."

Issue: the word semi-colon here should be "colon"

**Comment by BKinahan** [comment]
Hi @mattfish, thanks for reporting. The test text is correct, as per this line in the instructions:
>Finally, be sure to add the semicolon to the end of each of your element's styles.

The semicolon goes before the closing brace, as such: `h2 {color: red;}` (from the example code in the instructions). Its purpose is to terminate a style so that multiple styles can correctly be applied to a single selector (here, `h2`).

There is also a colon in the style declaration, but that is not what this test checks for.

Please visit the [Help chat](https://gitter.im/FreeCodeCamp/Help) if you need any further assistance or explanation.

Happy coding!
