### ISSUE TITLE
"Check for palindromes" passes with full uppercasing as well

### ISSUE THREAD

**Issue by qualitymanifest** [FreeCodeCamp/FreeCodeCamp#10094]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20str%20%3D%20str.toUpperCase().replace(%2F%5CW%7C_%2Fg%2C%20'')%3B%0A%20%20return%20str%20%3D%3D%3D%20str.split('').reverse().join('')%3B%0A%7D%0Apalindrome(%22eye%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  str = str.toUpperCase().replace(/\W|_/g, '');
  return str === str.split('').reverse().join('');
}
palindrome("eye");
```

A minor issue, but since the instructions state it should be lowercased, a test for lowercasing should be added. Currently it works as long as the case is the same throughout.

**Comment by raisedadead** [comment]
Yup. while this is trivial, a simple check can be added.

**Comment by alistermada** [comment]
Does it need to be lower cased? I thought the point was simply that the palindrome check is case insensitive, so the choice between changing the letters to upper case or lower case should be irrelevant.

Perhaps the instructions should be changed instead to allow for both.

**Comment by BKinahan** [comment]
I agree with @alistermada. There are already quite a few tests on this challenge (they seem to be multiplying every time I look at them!) and I don't think it needs more.

I think it's simpler and more permitting to adjust the instructions rather than the tests, particularly since the beginning of the instructions indicate "... ignoring punctuation, case, and spacing."

The change required would be from:
> and turn everything lower case in order to check for palindromes.

to:
> and turn everything into the same case (lower or upper case) in order to check for palindromes.

I'd also say that while `String.prototype.toUpperCase()` on MDN *could* be added to the useful links, it doesn't need to be as it is covered elsewhere and may mislead the user to think both are necessary. Most users will probably use toLowerCase() and those who use toUpperCase() will still be able to pass as they can now.

Plus then we can make this a first-timers-only issue 😄

**Comment by raisedadead** [comment]
Cool. I am okay with it.

**Comment by BKinahan** [comment]
Great! 👍 

**To potential contributors**: 
This issue can be resolved by opening a pull request that changes line 171 of [this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-bonfires.json) as detailed above. Please follow the [Contributor's Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and remember to visit the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you need any assistance. We're here to help!

**Comment by weejimmy** [comment]
I can do this one.
