### ISSUE TITLE
The website is completely stuck 

### ISSUE THREAD

**Issue by crisz** [FreeCodeCamp/FreeCodeCamp#10105]
#### Challenge Name

https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description

The website is completely stuck after I ran a snippet. The snippet didn't contain any endless loop, I had have tried it in my workspace and it worked without problems.
I can't use the whole website since when I go to www.freecodecamp.com I get redirect to the challenge, then it looks like the snippet get ran automatically and everything is stuck, and I'm not able to prevent it in any way.
#### Browser Information

* Browser Name, Version: Chrome 51.0.2704.103 but it happens also on Firefox
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
function permAlone(str) {
  return permute(str.split(""));
}
var permArr = [],
  usedChars = [];

function permute(input) {
  var i, ch;
  for (i = 0; i < input.length; i++) {
    ch = input.splice(i, 1)[0];
    usedChars.push(ch);
    if (input.length === 0) {
      permArr.push(usedChars.slice());
    }
    permute(input);
    input.splice(i, 0, ch);
    usedChars.pop();
  }
  return permArr;
}
permAlone('aab');
```

**Comment by BKinahan** [comment]
Hi @crisz. The structure of your code is causing the page to stop working, likely due to your use of global variables which are not cleared between function calls. You can see this in your own workspace if you run multiple tests at once instead of one test at a time.

You can follow these steps to prevent the code from running so that you can make the necessary changes: [Disable Code Auto Run on Free Code Camp](http://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511)

If you need any further assistance, please visit the [Help chat](https://gitter.im/FreeCodeCamp/Help).

Happy coding!
