### ISSUE TITLE
Error messages and initial text have different suggestions for variables 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#10112]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;
var a = 5;
var b = 10;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by BKinahan** [comment]
Hi @marienhof. Your code works correctly so it seems that you have understood the challenge, though you do not need to use the `var` keyword twice for each variable.

Could you please explain in more detail what you mean by your issue title?

**Comment by marienhof** [comment]
Hi! See mistakes page. Now see what you need to do. It's not that I have a bug. It's inconsistency between "mistakes" page and the main text.

**Comment by marienhof** [comment]
For example, in mistakes page you have values 6, 15. But you actually need to write 5, 10.

**Comment by BKinahan** [comment]
Those test messages are correct. The lines at the bottom of the editor (under the line `// Do not change code below this line`) add to each variable `a`, `b`, and `c` so that they will have the correct values required by the text only after a camper initializes each variable in the first lines of code with the correct values.

E.g. `a` should be `6`, which requires initializing `a` with the value `5` so that it is assigned the value `6` when the line `a = a + 1;` is evaluated.

**Comment by marienhof** [comment]
Aw! Gotcha. Sorry for bothering.

**Comment by erictleung** [comment]
Closing this issue as it appears resolved. Happy coding all!
