### ISSUE TITLE
Time mismatch

### ISSUE THREAD

**Issue by osenvosem** [freeCodeCamp/freeCodeCamp#10154]
I made one challenge (Word Blanks) several minutes after 00:00 according the local time and found the time mismatch:

![screen shot 2016-08-11 at 00 20 10](https://cloud.githubusercontent.com/assets/6762673/17571680/e339af2e-5f59-11e6-8865-d3cee92ccdd1.png)
![screen shot 2016-08-11 at 00 20 27](https://cloud.githubusercontent.com/assets/6762673/17571681/e33de1d4-5f59-11e6-8548-124094ab6f2d.png)

**Comment by dwd2010** [comment]
What is your timezone?  if your time is pass after midnight. it will be August 11, 2016. 

Do you mean Word Blank challenges suppose to on August 11?

**Comment by osenvosem** [comment]
@dwd2010 +3 Moscow time. On the first screenshot it is August 11, but in the list of challenges it still August 10.

**Comment by osenvosem** [comment]
Now it's clear. List of challenges uses GMT +0 time, but graphical representation — local time (GMT +3 in my case). And this seem to be a bug.

**Comment by raisedadead** [comment]
I have seen this a couple of times too earlier, any one up for looking into this?

**Comment by Locheed** [comment]
I'm no pro with this, but FreeCodeCamp uses old moment.js (from last year) and moment-timezone.js's, specially moments.js has gotten huge amount of fixes. This might have been already fixed there. Update?

**Comment by BerkeleyTrue** [comment]
@raisedadead Isn't this a duplicate bug?

**Comment by dhcodes** [comment]
This could have something to do with #7925 which I have experienced lately and also may be timezone related. I did see in the codebase that there is an err that references https://github.com/moment/moment-timezone/issues/294 that is since fixed in version 0.5.1 of moment-timezone. FCC is currently on version 0.5.0 and the most current version of it is 0.5.5. That may fix this issue, though I have not tested it in this particular case. 

Regarding #7925, I wonder if [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/87ef97f59e2a2f4dc425982f76f14a57d0900bcf/server/utils/user-stats.js#L5):
`const daysBetween = 1.5;`
in [/server/utils/user-stats.js](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/87ef97f59e2a2f4dc425982f76f14a57d0900bcf/server/utils/user-stats.js) has something to do with the streak issues. 

The way I read it, the determining factor of the streak is a completed challenge in the 1.5 days, but a typical user may work on something early in the morning (ex. 7 a.m.) and then jump back on the next evening at 10 p.m. and see that as still completing a challenge each day and thus, continuing the streak, even though those times are > 1.5 days apart (in this case, 39 hours). 1.5 days being 36 hours.

That's my reading, though, which is still rather green behind the ears and could be wrong.

**Comment by r1chard5mith** [comment]
fwiw, I have this precise issue. My experience agrees with @dhcodes suggestion. I was filling in the little boxes every day, but my streak got broken because I worked in the morning one day and the evening the following day. I am in Australia.
![screen shot 2016-09-01 at 10 08 57 pm](https://cloud.githubusercontent.com/assets/7539224/18166898/1e729a90-7091-11e6-9385-afcf1966410b.png)

**Comment by MohanL** [comment]
Hello, I'd like to work on this issue.

**Comment by porjolovsky** [comment]
agreeing with @r1chard5mith & @dhcodes here, came looking for this. Seemed off for it to be a timezone issue, given that the display works ok and separates challenges done correctly by day to the hour (I've mostly coded at or around midnight, so I've seen this live). I think it could be solved by using a 48 hour period (2 days instead of 1.5, if that's where the error was) and get the user timezone involved in the checking to see if it fits the "streak" conditions.

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/7925
