### ISSUE TITLE
Output not consistent in "Escape Sequences in Strings" for JavaScript

### ISSUE THREAD

**Issue by fox20002** [FreeCodeCamp/FreeCodeCamp#10166]
In one of the challenges introducing escape sequences, it has you write: 
myStr = "I am a \"double quoted\" string inside \"double quotes\".";

and this shows as the following in the black output box:
"I am a "double "quoted" string inside "double quotes."

but on this challenge it shows as
"I am a \"double quoted\" string inside \"double quotes\"."

this doesn't make sense, the output box isn't really useful if it doesn't show the actual output from your string.  d

Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%27FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%27%3B%20%2F%2F%20Change%20this%20line%0A%0A%2F%2FmyStr%3D%22hi%20how%20%5C%22are%20you%5C%22%22%3B%20%0A%0A%2F%2FmyStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = 'FirstLine\n\\SecondLine\\\rThirdLine'; // Change this line

//myStr="hi how \"are you\""; 

//myStr = "I am a \"double quoted\" string inside \"double quotes\".";

```

**Comment by BKinahan** [comment]
It does seem that simply mirroring the string that the user has assigned to `myStr` is not very useful here.

Having the output display the string as three separate lines would make more sense, and reinforce the purpose of escaped characters.

This would be a simple case of removing the call to `JSON.stringify()` in the challenge's `tail` and replacing it with a simple concatenation of `myStr` as used in the other character escaping challenges.

cc @FreeCodeCamp/issue-moderators Thoughts?

**Comment by Jamezslim90** [comment]
Am having similar issues too, what do i do? am stuck

**Comment by Jamezslim90** [comment]
This is my code 
                  var myStr= "FirstLine\n\\SecondLine\\\rThirdline";

but its tell to use encoded text with proper escape sequence and no spacing

**Comment by Jamezslim90** [comment]
This is my code 
var myStr= "FirstLine\n\\SecondLine\\\rThirdline";

but its tell to use encoded text with proper escape sequence and no spacing

**Comment by dwd2010** [comment]
@Jamezslim90, Did you ask help at FreeCodeCamp Chat Room or Forum? they could help you. This place is not for ask help.

**Comment by BKinahan** [comment]
Update: I have a local branch that makes the change, but I'm not able to test it properly against `staging` since the output display does not work the same way it currently does due to upcoming changes.

@FreeCodeCamp/issue-moderators Is this a known Beta issue / being worked on? Couldn't find any issues or PRs with a quick search. And in that light, what should be the fate of issues related to challenge outputs such as this one?

**Comment by raisedadead** [comment]
@BKinahan Yes, it is a known issue, all challenge log statements now need to be explicitly wrapped in `console.log` statements.

In your case just wrap your output in a `console.log`, and you should be good to go!

**Comment by BKinahan** [comment]
@raisedadead Oh, so that will have to be changed individually in all relevant challenges, then? Might be a good idea to track which challenges have had their output updated rather than just handling them one at a time as they come up... Or is that being tracked somewhere already? 😄 

Either way I'll take care of this one for now 👍

**Comment by raisedadead** [comment]
@BKinahan https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9363
