### ISSUE TITLE
`var` should be discouraged.

### ISSUE THREAD

**Issue by piq9117** [FreeCodeCamp/FreeCodeCamp#10199]
Challenge [Global Scope and Functions](https://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%0A%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declare your variable here
var myGlobal = 10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

We need to start using es6 `let` and `const`. `var` variable declaration is a potential for a bug.

**Comment by BKinahan** [comment]
ES6 features including `let` and `const` will be covered in detail in new curriculum topics which are currently being developed (see [here](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/34)). These challenges will also go over the problems which can be caused by scoping/hoisting when using `var`.

For now this challenge serves as an introduction to scoping and some of the issues to look out for when `var` is used, and still contains useful information as campers are likely to come across code from other (older) sources which do use `var` (eg legacy code, etc), and so it is a useful introduction to the issues discussed.

There might be an argument for removing the line
> You should always declare your variables with var.

or altering it with some caveat regarding learning about `let` and `const` later on, but I think this challenge is fine for a first introduction to the topic.

cc @FreeCodeCamp/issue-moderators Thoughts?

**Comment by BerkeleyTrue** [comment]
@BKinahan Well put.

When to use and not use `var` is not always up to the individual developer but most of the time it depends on the team. 

While I have not found a time where `var` could not be replaced with `let` or `const` I have spoken to an engineer at OpenTable, which had recently refactored their whole codebase to use ES2015, and he did mention there was one case where `let` or `const` was the cause of a bug and `var` had to be used but he could not remember the exact details of why that was.

I don't think `var` should be discouraged. Better to explain the way `var` works and let the developer choose once they are further along on their journey towards enlightenment.

There are also some weirdness with `let` and `const` that if you are not aware of it can through you through some loops (see: [temporal dead zone](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/)). This does not disqualify `let` and `const` from being used, even though it is an annoyance. It just means that grokking a thing is as important as knowing a thing.

**Comment by piq9117** [comment]
I guess this is all opinion based. However, I would stand by my statement, and I would go as far as to preach to use immutable.js or mori for immutable data. ✌️
