### ISSUE TITLE
Padding should require unit specified with value used

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1019]
Challenge http://www.freecodecamp.org/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

CSS spec requries the unit for the value provided.
Check here: http://jigsaw.w3.org/css-validator/#validate_by_input
Give it this as an example: .green-box { padding: 40 20 20 40;
    }
Result is this: Value Error : padding only 0 can be a length. You must put a unit after your number : 40 20 20 40
Example of what will pass: .green-box { padding: 40px 20px 20px 40px; } 
Same applies if you do padding-top: 40; as well... it needs a unit as well to pass specification
![waypoint-add-different-padding-to-each-side-of-an-element](https://cloud.githubusercontent.com/assets/3256176/8266362/4b8023ec-16e0-11e5-8fa0-0a3c08f82377.png)

**Comment by BerkeleyTrue** [comment]
While technically true we are limited to testing output from jQuery. Even though this does not fit spec most browsers will automatically fill in the dots. Since the browser does this for us we don't test for exact compliance but we explicitly tell users to use px units (as opposed to em or rem). It is the same issue with the last semicolon. While leaving off a semicolon is incorrect css, browser automatically correct for this if it is the last property in a selector block.


Happy Coding!
