### ISSUE TITLE
Further Clarification could be used when submitting an issue

### ISSUE THREAD

**Issue by oalhait** [FreeCodeCamp/FreeCodeCamp#10222]
While fixing issues, I've noticed that adding the challenge alone helps in identifying where to find the issue in the actual git repository, but I think adding the section the challenge is in would also help. i.e. 

> In the Basic JavaScript section of Front End Development Certification

is more helpful than 

> In the Basic JavaScript section

Thoughts on this?

**Comment by BerkeleyTrue** [comment]
@oalhait Sorry, the varCi bot is responding to the inclusion of `help` in your issue. This is a valid discussion point. Please feel free to reopen.

Happy Coding

**Comment by oalhait** [comment]
I realized it takes a long time to find the challenge an issue is regarding when looking through the actual code, given the way the whole repository is set up. It would help if we added another question in the issue submission form that helps narrow down where the challenge is. 
For example, when submitting an issue for a javascript challenge, it would help if the user also clarified that it was in basic-javascript (which is in 01-front-end-development-certification).

**Comment by erictleung** [comment]
@oalhait I agree that it would be nice if people specified where in the repository that needs changing but usually most people won't know where it is.

For a `first-timers-only` issue I've labeled personally, I always specify where in the repository needs changing.

I added in the challenge name into the Issue Template. This was supposed to help (or at least for me) navigate through the code base because you can always copy-paste the challenge name up in GitHub's search box above to find where in the code base needs changing. Those are my two cents on the matter.

**Comment by oalhait** [comment]
@erictleung that makes sense. It never really occurred to me to search for the name on github, so that solves my problem. However, I think it would be worthy to add a note in the contributor's guide that makes people who don't know of github's search function aware. I know I'll save some time because of it now hahah
