### ISSUE TITLE
Error in the 4th condition

### ISSUE THREAD

**Issue by husamp** [FreeCodeCamp/freecodecamp#1025]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-many-elements-within-a-single-div-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

When I create the div tag and assign it an ID, it gives an error for the 4th condition of the challenge.

**Comment by digitaldak** [comment]
So I tried it this morning and this will work:
<div>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
</div>


But this:
<div > <--- Note the space after div *****
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
</div> 

Results in;
Cannot read property 'length' of null

If you put an ID on it as mentioned  by the reporter it will the same result as above. It's the space after the word div before the ending > that causes the error condition.  Looks like it's because the  last test is trying to do an exact match  and trying to use length when there isn't an dom object that matches causing it to error out.

**Comment by BerkeleyTrue** [comment]
This challenge has since been removed.

Happy Coding!
