### ISSUE TITLE
Test fails even with correct output

### ISSUE THREAD

**Issue by balugeorge** [FreeCodeCamp/FreeCodeCamp#10285]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=var%20split%20%3D%20%5B%5D%3B%0Avar%20com%20%3D%20%5B%5D%3B%0Afunction%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%20%20for%20(var%20i%20%3D%200%2C%20j%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B%2C%20j%20%2B%3D%20size)%7B%0A%20%20%09if%20(arr.slice(j%2C%20j%20%2B%20size).length%20%3E%200)%20%7B%0A%20%20%20%20split%5Bi%5D%20%3D%20arr.slice(j%2C%20j%20%2B%20size)%3B%0A%20%20%20%20com%5Bi%5D%20%3D%20split%5Bi%5D%3B%0A%20%20%7D%0A%20%20%7D%0A%20%20return%20com%3B%0A%7D%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%5D%2C%204)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.

The test `chunkArrayInGroups([0, 1, 2, 3, 4, 5], 4);` shows the status as failure even though it produces the desired output(see attached screenshot).

My code:
```javascript
var split = [];
var com = [];
function chunkArrayInGroups(arr, size) {
  for (var i = 0, j = 0; i < arr.length; i++, j += size){
  	if (arr.slice(j, j + size).length > 0) {
    split[i] = arr.slice(j, j + size);
    com[i] = split[i];
  }
  }
  return com;
}

chunkArrayInGroups([0, 1, 2, 3, 4, 5], 4);
```
![cm](https://cloud.githubusercontent.com/assets/10348085/17830421/5172f2f8-66e8-11e6-889e-ca1d7df8132a.png)

**Comment by BKinahan** [comment]
Hi @balugeorge.

Your code doesn't work due to the way that tests are run for the challenges, by calling the function multiple times in a row, because your `split` and `com` variables are in the global scope and not reset between function calls.

Your code works perfectly if the `split` and `com` declarations are moved within the function, and will work for multiple calls in a row 😄 

In this particular case only one test fails because your code will only produce an error when the length of the resulting array is shorter than the length of the result of the previous call to the function, and this only happens once in the tests sequence. As an exercise in debugging, see if you can work out why that is true 😄 

Also remember to visit the [HelpJavaScript chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) or the forum when you have a problem in your code before raising an issue, since it might be a similar problem rather than a bug with the challenge. 

Happy coding!

**Comment by balugeorge** [comment]
Thank you @BKinahan
