### ISSUE TITLE
Challenge [Symmetric Difference] syntax

### ISSUE THREAD

**Issue by tertiaryidentifier** [FreeCodeCamp/FreeCodeCamp#10280]
It is unclear in the prompt whether the test function ```sym(A, B, C, D, E, F)``` is requesting the user to create a function that accomplishes:

```return A △ B △ C △ D △ E △ F```
OR 
```return ((((A △ B) △ C) △ D) △ E) △ F```

The syntax difference is important. For the following test case:

``` A = [3, 3, 3, 2, 5]
 B = [2, 1, 5, 7]
C = [3, 4, 6, 6]
D = [1, 2, 3], 
E = [5, 3, 9, 8]
F = [1] 
should return [1, 2, 4, 5, 6, 7, 8, 9] ```

The first version I mentioned (the symmetric difference of ALL ARRAYS) would return 
``` [4, 7, 8, 9]```

Whereas the second returns 
```[1, 2, 4, 5, 6, 7, 8, 9] ```.

I'm just wondering if we could make this clearer in the instructions? **Technically**, the instructions

```Create a function that takes two or more arrays and returns an array of the symmetric difference (△ or ⊕) of the provided arrays.```

actually ask for the first version, not the second version, and according to my limited programming and mathematics knowledge, the test cases are wrong ... 

Maybe someone can clarify this?

**Comment by BKinahan** [comment]
I think the second paragraph of the instructions is quite clear that the symmetric difference of multiple sets can be determined by taking the symmetric difference of two sets (`A` and `B` in the example from the challenge instructions, with their symmetric difference named as `C`), and finding the symmetric difference of `C` and an additional set `D` (and so on for the remaining sets).

I'm not sure how you have arrived at a result of `[4, 7, 8, 9]` for `A △ B △ C △ D △ E △ F`, but it should provide the same result as your grouped input, or any other groupings of sets. For example, these three lines should all return the same result (that is, a set of the same numbers, though the elements may be in different orders):
`sym(sym(sym(sym(sym(A, B), C), D), E), F);`
`sym(sym(sym(sym(sym(F, E), D), C), B), A);`
`sym(A, B, C, D, E, F);`

Mathematically, you can think of each set being merged simultaneously rather than in steps, as is demonstrated well in the [video](https://www.youtube.com/watch?v=PxffSUQRkG4) linked in the challenge instructions, though it's simpler in JavaScript to merge two sets at a time rather than all at once 😄 

Let me know if this clarifies things, or if you have some more input about why the challenge instructions might be ambiguous or if they can be improved.

**Comment by tertiaryidentifier** [comment]
Yeah. I understand it now. The video doesn't really give a good explanation as to why the merged sets include their central overlap as part of the symmetric difference ... I guess I thought of the mathematical technique more as "find any unique value in these arrays, do not return duplicates", but upon reviewing how mathematics defines symmetric difference, I am realizing that this is not what is going on. 

... You can close this issue! Thanks for putting up with my nonsense.
