### ISSUE TITLE
Override Styles in Subsequent CSS

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#10293]
Same issue as previous submission.....................
[FireShot Capture 43 - Override Style__ - https___www.freecodecamp.com_chall.pdf](https://github.com/FreeCodeCamp/FreeCodeCamp/files/428509/FireShot.Capture.43.-.Override.Style__.-.https___www.freecodecamp.com_chall.pdf)
![fireshot capture 44 - override style__ - https___www freecodecamp com_chall](https://cloud.githubusercontent.com/assets/21107653/17833942/672d1e5c-66f2-11e6-8d90-eafb5dae9aa4.png)
[FireShot Capture 45 - HTML - http___www.littlewebhut.com_html_.pdf](https://github.com/FreeCodeCamp/FreeCodeCamp/files/428510/FireShot.Capture.45.-.HTML.-.http___www.littlewebhut.com_html_.pdf)
![fireshot capture 46 - html - http___www littlewebhut com_html_](https://cloud.githubusercontent.com/assets/21107653/17833949/70ab2cd0-66f2-11e6-850e-b65ea4b618c5.png)
calling bullshit on this site, this is ridiculousness.......

```
<html>
		
<head>
<title>HTML Test</title>
</head>

<body>


	
</body>

</html>

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="blue-text" class="pink-text">Hello World!</h1>
```

the above worked/functioned just fine on two separate trials and meet the specified criteria, this is again aggravating

**Comment by qmikew1** [comment]
Multiple classes in one tag take the form ```class="class1 class2"``` - *not* in separate invocations like in your code - ```<h1 class="blue-text" class="pink-text>Hellow World!</h1>``` - Correct form would be 
```<h1 class="pink-text blue-text">Hello World!</h1>```.  A lot of things will render (like in the site you used) as fallback when encountering something, weird. (doesn't make stuff correct). [Help](https://gitter.im/FreeCodeCamp/Help) is a great place for questions like this.

**Comment by courtjester71** [comment]
Then why did it oporate correctly with the correct result on the "school"
text editor as well as the site I use to test the code?.......worked on
both.......others encountered similar trouble, pluss all research sites I
visit  vary greatly from whats being exampled on your site. All I ended up
doimg was deleating what was on the editor and re-pasting, then everything
was complete. Worked. I unfortunately didnt get a schreenshot of that
particular one, would be helpful...but the system is buggy.......

On Aug 20, 2016 16:59, "Serenity" <notifications@github.com> wrote:

Multiple classes in one tag take the form class="class1 class2" - *not* in
separate invocations like in your code - <h1 class="blue-text"
class="pink-text>Hellow World!</h1> - Correct form would be
<h1 class="pink-text blue-text">Hello World!</h1>. A lot of things will
render (like in the site you used) as fallback when encountering something,
weird. (doesn't make stuff correct). Help
<https://gitter.im/FreeCodeCamp/Help> is a great place for questions like
this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10293#issuecomment-241226143>,
or mute the thread

**Comment by courtjester71** [comment]
Help is not a good place to go, its a total cluster.........

**Comment by qmikew1** [comment]
Again, the instructions do state that the following:
> Applying multiple class attributes to a HTML element is done with a space between them like this:
```class="class1 class2"```
This is convention (additional links: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Common_CSS_Questions#Assigning_multiple_classes) - [stackoverflow](http://stackoverflow.com/questions/5482677/how-to-apply-two-css-classes-to-a-single-div-span) - Whether something renders in whatever fiddle/learning site/etc., is a product of either the environment of the site, or basic fallback rendering (because browser has to *do something* when it encounters something odd) - But given that there is objective convention to this. It's not a site issue, but simply not following directions. Additionally, here's a [fiddle](https://jsfiddle.net/4y67yp2b/11/) demonstrating what happens if you do that. - Honestly though, it's going to be a struggle if conventions aren't a given.

**Comment by erictleung** [comment]
@courtjester71 as @qmikew1 has pointed out, your code is incorrect. The challenge instructions have clearly laid out how to correctly add multiple classes to an HTML element.

> Applying multiple class attributes to a HTML element is done with a space between them like this:
> 
> `class="class1 class2"`

Even if your code renders correctly, you have to think about the purpose of the challenge and what it is trying to teach you. Again, there's not an issue with the site. Please be patient with the help rooms if asking a question there. there are *lots* of people willing to help. You just need to be patient. Coding and learning take effort and time. Happy coding!

**Comment by TinaLittlemoon** [comment]
here the right code!

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="blue-text pink-text">Hello World!</h1>

**Comment by texas2010** [comment]
@TinaLittlemoon 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by waterburyr** [comment]
This is my first 'Help' issue and I'm hoping someone can provide me guidance. I just attempted this challenge and the rendering came out correct with the 'Hello World!' text changing to the color blue. However, I do question the validity in the following statement ..."Note: It doesn't matter which order the classes are listed in the HTML element." I say this because it does appear the color indicated first in the HTML element does take precedence. I kept flipping them back and forth and was never able to get the text to remain blue when in the second position in the HTML element. Additionally, the challenge won't let me pass because it is stating the following tasks are not satisfied: "Your h1 element should have the class pink-text" and "Both blue-text and pink-text should belong to the same h1 element". They clearly are. Is this a bug in the challenge?
![challenge 65 screenshot](https://cloud.githubusercontent.com/assets/16363862/18418937/508359c2-7850-11e6-9a33-7818908fbea6.jpg)

**Comment by texas2010** [comment]
@waterburyr, your code is incorrect. you could ask help. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by louisprogramming** [comment]
<style>
  
  body {
    background-color: black;
    font-family: monospace;
    color: green;
  }
  .blue-text {
color: blue; 
  }
  .pink-text {
    color: pink;
  }
  

</style>

<h1 class="blue-text">Hello World!</h1>

<h1 class="pink-text">Hello World!</h1>

<h1 class="blue-text pink-text">Hello World!</h1>

**Comment by louisprogramming** [comment]
This needs to go within the body

""<h1 class="blue-text">Hello World!</h1>""

""<h1 class="pink-text">Hello World!</h1>""

""<h1 class="blue-text pink-text">Hello World!</h1>""
