### ISSUE TITLE
Doesn't pass the last test

### ISSUE THREAD

**Issue by JCollison** [FreeCodeCamp/FreeCodeCamp#10295]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=%0Afunction%20factorialize(num)%20%7B%0A%20%20var%20numArray%20%3D%20%5B%5D%3B%0A%20%20for(var%20i%3D0%3Bi%3Cnum%3Bi%2B%2B)%7B%0A%20%20%20%20numArray%5Bi%5D%3Di%2B1%3B%0A%20%20%7D%0A%20%0A%20%20return%20numArray.reduce(function(previousValue%2CcurrentValue)%7B%0A%20%20%20%20return%20previousValue*currentValue%3B%0A%20%20%7D)%3B%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function factorialize(num) {
  var numArray = [];
  for(var i=0;i<num;i++){
    numArray[i]=i+1;
  }
 
  return numArray.reduce(function(previousValue,currentValue){
    return previousValue*currentValue;
  });
}

factorialize(5);

```
This doesn't pass the last test. I understand why, but why is the last test expecting a value of 1? If 0 is factorialized it should be 0 should it not?

**Comment by Jaskaranbir** [comment]
0 factorial is 1. So what last test is expecting is true value; not some mistake or bug.

**Comment by erictleung** [comment]
@JCollison thanks for the issue. As @Jaskaranbir has pointed out, `0!` is equal to `1`. At some point in the curriculum, we want students to develop some critical thinking skills along the way so that is why we didn't explicitly tell you in the instructions. 

A quick Google search may land you at this page https://www.zero-factorial.com/whatis.html where it shows you `0!` equal to 1.

Also, here's a fun video on what zero factorial is https://www.youtube.com/watch?v=Mfk_L4Nx2ZI.

There's no issue with the challenge so I'll be closing this issue. Happy coding!
