### ISSUE TITLE
Prioritize One Style Over Another

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#10292]
#### Challenge Name

https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?
Prioritize One Style Over Another
according to the criteria to the left all bullets were met/accomplished, and actually several different ways, these are the only two I had on my clipboard for testing on "little web hut" website: http://www.littlewebhut.com/html/style_tag/

```
<style>
  .pink-text {
    color: pink;
  } 
 h1 {color: pink;}
  
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }

</style>
<h1>class="pink-text">Hello World!</h1>
```

the above worked but wont move on/ so also tried the below;
for a try just to see;

```
<style>
 
 body { 
          background-color: black; font-family: Monospace; 
         color: pink; 
        .pink-text { color: pink; {
         color: pink;
   } 
   }
</style>
 <h1 class="pink-text">Hello World!</h1>
```

seems there might be a bug or quirk, of which I've discovered several but found a remedy

**Comment by tertiaryidentifier** [comment]
The challenge is asking you to create two different styles which conflict. I imagine the error arises from `h1 {color:pink}` being set as such in your first example. In the second example, the error is probably the `body { color: pink }` attribute. Try removing this style attribute in each case and see what happens.

**Comment by dhcodes** [comment]
The first solution you provided worked when I visited the challenge assuming your h1 line is `<h1 class="pink-text">Hello World!</h1>`. Sometimes the editor has an error due to copying/pasting from another site. If you reset the code and then re-enter it, it should work.

**Comment by erictleung** [comment]
@courtjester71 thanks for the issue. Learning to code, or anything else for that matter, will be frustrating at times. You'll have to be humble and either ask for help in the chat rooms or stay calm and try to figure out why your code is not accepted.

I was able to look at the code you had and it looked like this in the editor

![image](https://cloud.githubusercontent.com/assets/2754821/17835228/1eed709a-6717-11e6-8146-0d117000ae23.png)

We've set up the editor on FreeCodeCamp to do some syntax highlighting and if you look carefully, you'll notice that 1) the text "Hello World!" along with the `class="pink-text">` are all in white and 2) the text in the phone emulator on the right shows the text `class="pink-text">` as well. 

Stopping to think about what your code has done will also help in your learning journey. The challenge was to change the color of your text but your code has accidentally added new text. So if may prompt you to think why did that happen?

The first block of code is incorrect, but the second block of code you have is correct. Your second block of code looks a bit different in the editor.

![image](https://cloud.githubusercontent.com/assets/2754821/17835243/ab4ddf66-6717-11e6-8924-722ff210fd66.png)

The syntax highlighting is there to help indicate any issues you may have in your code. 

The chat rooms may not be ideal but for a free resource, those chat rooms are teaming with people willing to help. That is something you might not otherwise be around.

I hope this experience will not deter you from continuing to learn how to code. Closing this issue but there is no bug with the site. Best of luck and happy coding!
