### ISSUE TITLE
Image's non-shortened URL not accepted by tests

### ISSUE THREAD

**Issue by fr0d0202** [FreeCodeCamp/FreeCodeCamp#10306]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fs3.amazonaws.com%2Ffreecodecamp%2Frelaxing-cat.jpg%22%20alt%3D%22kitten%20image%22%2F%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<img src="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg" alt="kitten image"/>
```

**Comment by muzz00ka** [comment]
Hi,

You forgot to add the image at the top of the code, above the link.

See below,

`**_<img src="https://bit.ly/fcc-relaxing-cat" alt="Relaxing cat.">_**

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
`

Cheers.

**Comment by muzz00ka** [comment]
Hi, 

You need to add the image source to the top of the code, above where the link is located. 

<img src="https://bit.ly/fcc-relaxing-cat" alt="Relaxing cat.">

Cheers.

**Comment by BKinahan** [comment]
The issue is that the shortened URL `https://bit.ly/fcc-relaxing-cat` points to the image at `https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg`, but a user can add the latter URL as the value of the `src` attribute of the `img` element and be told by the test message that they have not pointed to the correct image.

This could be a common initial point of failure for users who visit the link to see the image before including it in the HTML code, so perhaps either the test message should be adjusted or the test itself updated to also accept the images true URL.

cc @FreeCodeCamp/issue-moderators Thoughts?

**Comment by raisedadead** [comment]
Yup. Makes sense.

**Comment by dhcodes** [comment]
Not a mod, but I recommend we consider using the real link (https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg). It would be more reliable longterm and is only 23 characters longer. I would wager many users are likely copying/pasting the src link anyway.

**Comment by tertiaryidentifier** [comment]
Would like to try my first pull request for this issue. Assuming I'm proposing a change to line 1131 in FreeCodeCamp/seed/challenges/01-front-end-development-certification/html5-and-css.json, correct all? Confused as to how the regex is created. 

```         "assert(new RegExp(\"\\/\\/bit.ly\\/fcc-relaxing-cat\", \"gi\").test($(\"img\").attr(\"src\")), 'message: Your image should have a <code>src</code> attribute that points to the kitten image.');", ```

If someone wants to explain how I would go about making a RegExp that would target the full amazonaws link, I'd be happy to try to do it.

**Comment by dhcodes** [comment]
@tertiaryidentifier ultimately you would need to rewrite the part in the paratheses after RegExp in the line you referenced to accept either the bit.ly link OR the amazon link as part of the test. You can use a bar (`|`) to denote 'or' in Regex. Note that since the file is JSON, slashes need to be escaped with an extra `\` compared to standard regex. 

To read more about regex, checkout [RegexOne](https://regexone.com/) or [Regexr](http://regexr.com/). RegexOne can help you learn the concepts of Regex and Regexr allows you to test out your expressions to see if they catch your test cases.

You might wait a bit longer though to see if others agree this is the route to be taken before setting out to make the PR.

**Comment by tertiaryidentifier** [comment]
Thanks @dhcodes , I'll wait and see, and in the meantime, refresh my regexp knowledge. :)

I think that the regular expression should accept the bit.ly OR the full amazon link.

**Comment by BlauFeuer** [comment]
The test constraint doesn't state your image tag needs the correct link, so why does the test look for it?

**Your img element should have the class smaller-image.**

**Comment by BlauFeuer** [comment]
Anyway, I got stuck on this one, too. What drew me to this issue was the fact that I couldn't see the image in the browser, and figured that something was up with the `href`

**Comment by tertiaryidentifier** [comment]
@BlauFeuer, the test actually does state:

```Your image should have a src attribute that points to the kitten image.```

We can't alter the test to accept any link, because then someone could put in any image. The challenge is asking for this specific cat image, but currently only accepts one. I think the correct modification should be for the test to accept both, not all.

**Comment by BlauFeuer** [comment]
**"Size your Images"** is the only HTM5 and CSS challenge that I have not completed. I skipped this one.
I happily went through the challenges imagining an image there, but `https://bit.ly/fcc-relaxing-cat` shows nothing and `https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg` shows nothing - so no matter what you _want_ to test for, it is neither displayed for me, nor is the specific image part of the ✘ or ✔ listed criteria.

e.g. If it's criteria for success, it should be listed, otherwise it seems unimportant, more so because I have never seen this image when using either link.  As far as I can testify, the test criteria is _mysterious_, and it shouldn't be.

If we can't alter the test to accept any link, maybe you'd consider altering the test to include a criteria element that mentions using a specific link, and maybe one that's hosted in the FreeCodeCamp github repository instead of relying on a third-party to forward to a fourth party, or however it goes.

**Comment by raisedadead** [comment]
Yes, that is correct the test should accept both the bitly link as well as the full link.

**Comment by dhcodes** [comment]
@tertiaryidentifier you want to tackle this? If not, I'll try it

**Comment by tertiaryidentifier** [comment]
Working on it. I'll post my solution here before initiating a pull request.

**Comment by dhcodes** [comment]
@tertiaryidentifier cool, if you have any questions, jump into the [Help Contributors room](https://gitter.im/FreeCodeCamp/HelpContributors)

**Comment by tertiaryidentifier** [comment]
Argh ... I think this is above my skill level. Sorry! One day I will
contribute robust regular expressions for testing, but today is not the
day. :(

**Comment by dhcodes** [comment]
@tertiaryidentifier jump on Gitter if you want to talk through it.

**Comment by FarisWorld** [comment]
<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

THIS IS THE ANSWER TO YOUR Q
JUST COPY IT AND PAST IT AFTER
