### ISSUE TITLE
almost passes by default

### ISSUE THREAD

**Issue by WRyan78** [FreeCodeCamp/FreeCodeCamp#10332]
Not sure if it's a bug but by default without changing a single piece of code it automatically passed 6 of the 7 checkpoints on this exercise as soon as the page loaded. 

Seemed really strange when I got to this challenge (Introducing Else If Statements), 6 of the 7 checkmarks/circles were already green.  

Here's an imgur link to a screenshot:
http://imgur.com/TfkpVLF

Hope I'm not looking at this the wrong way and wasting anyone's time. I know you guys are really busy. 

I'm loving FCC and just want to help if I can.  

Challenge [Introducing Else If Statements](https://www.freecodecamp.com/challenges/introducing-else-if-statements#?solution=%0Afunction%20testElseIf(val)%20%7B%0A%20%20if%20(val%20%3E%2010)%20%7B%0A%20%20%20%20return%20%22Greater%20than%2010%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Smaller%20than%205%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Between%205%20and%2010%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElseIf(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  }
  
  if (val < 5) {
    return "Smaller than 5";
  }
  
  return "Between 5 and 10";
}

// Change this value to test
testElseIf(7);


```

**Comment by WRyan78** [comment]
well Mr. Bot I guess it isn't really an issue or a big deal because you still have to do the exercise so I guess I'll close this. 
A lot of the exercise/challenges have a couple checks marked green but this was the first time I saw almost all of them green by default so I thought something was wrong.

**Comment by dhcodes** [comment]
@WRyan78 don't mind the bot. I think it's a valid question that is ultimately brought about by the function running on page load. I think many are checked because multiple if statements work almost like else if, but it's mostly just the ease of the challenge and the autorun that results in this outcome.

**Comment by BKinahan** [comment]
More to the point, the function works correctly right away because it is written correctly, and the point of the challenge is to write it correctly in a different way. So it's only natural that the tests of function correctness should pass with the original code, and users can tell that they have done something wrong if these tests no longer pass after they have made some changes 😄

**Comment by WRyan78** [comment]
that's a good point, hahaha. _"Now I broke it!"_
