### ISSUE TITLE
Unnecessary "else" required for "else if" challenge

### ISSUE THREAD

**Issue by BlauFeuer** [FreeCodeCamp/FreeCodeCamp#10351]
Challenge [Introducing Else If Statements](https://www.freecodecamp.com/challenges/introducing-else-if-statements#?solution=%0Afunction%20testElseIf(val)%20%7B%0A%20%20if%20(val%20%3E%2010)%20%7B%0A%20%20%20%20return%20%22Greater%20than%2010%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20if%20(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Smaller%20than%205%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Between%205%20and%2010%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElseIf(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  }
  
  else if (val < 5) {
    return "Smaller than 5";
  }
  
  return "Between 5 and 10";
}

// Change this value to test
testElseIf(7);


```
This code passes all but "You should have at least two else statements ", yet the instruction that accompanies the challenge never mentions that requirement, and adding an additional "else" does not contribute to "Introducing Else If" and is just additional code against best practices.

The issue here is if best practices and the specific topic are what is being challenged, why add additional constraints to the test such as "You should have at least two else statements" that degrade the quality of the code the student is being asked to produce?

**Comment by BlauFeuer** [comment]
To further illustrate the issue, this code passes:
```javascript
function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  }
  
  else if (val < 5) {
    return "Smaller than 5";
  }
  else {}
  return "Between 5 and 10";
}

// Change this value to test
testElseIf(7);
```

**Comment by BlauFeuer** [comment]
A latter challenge regarding ordering (_Logical Order in If Else Statements_) passes with this code:
```javascript
function orderMyLogic(val) {
  if (val < 5) {
    return "Less than 5"; }
  else if (val < 10) {
    return "Less than 10";
  }
  return "Greater than or equal to 10";
}

// Change this value to test
orderMyLogic(7);
```

**Comment by Mongues** [comment]
Will do

**Comment by erictleung** [comment]
@BlauFeuer thanks for the issue. I can see an argument for leaving out the "unnecessary" `else` statements from the code in this case where it is possibly less important. 

---

> ...adding an additional "else" does not contribute to "Introducing Else If" and is just additional code against best practices.

Can you point to any references saying adding extra `else` statements is against best practices? 

In the "Introducing If Else Statements" case, the `else` statement coincidentally covers the remaining cases the `val` variable can/should take, thus not being "necessary" here. However, generally speaking, this might not be the situation.

[Here's a discussion](http://stackoverflow.com/questions/1780384/should-if-statement-always-have-an-else-clause) on whether all `if` statements should have `else` statements. It sounds like they agree that if the `else` statement is empty then remove it.

---

> ...why add additional constraints to the test such as "You should have at least two else statements" that degrade the quality of the code the student is being asked to produce?

Learning about the conditional `if` statement should come with learning the `else`. And because this is a beginning programming environment, leaving these nuances might be best and less confusing.

All in all, I think it depends on the situation of your code. If I wanted to change the value of just one variable if it equals a certain value, then I think I would put one `if` statement without the `else` statement. 


cc/ @FreeCodeCamp/issue-moderators comments on the matter?

**Comment by raisedadead** [comment]
I agree with @erictleung , it's completely upto you to leave out the last else. But having said that best practices are relative terms. As a beginner I should have a focus on learning the concepts if a if else if chain than that of confusing the core concept with additional practices.

Please note I am not saying that the best practices should not be followed at all, but then this challenge at this stage is not having the scope for that, and in an honest opinion beyond what Free Code Camp's objective for beginners at this stage is.

Closing as bikeshedding.

**Comment by aroojmumtaz** [comment]
i see the issue has still not been fixed.

**Comment by skellmob** [comment]
I got the same issue as well.

**Comment by abelsmoker** [comment]
takeout-20170111T123346Z.zip
<https://drive.google.com/file/d/0B7U75xuxFkvdX0dUQlhKNi03UE15UC04YzBPNWF3NTk2QjE4/view?usp=drivesdk>



On Feb 2, 2017 5:36 AM, "Anders" <notifications@github.com> wrote:

I got the same issue as well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/10351#issuecomment-276958152>,
or mute the thread

**Comment by AckeT35** [comment]
Hi guys, I randomly something send messege, sorry!

2 фев 2017 г. 4:35 PM пользователь "Anders" <notifications@github.com>
написал:

**Comment by texas2010** [comment]
@AckeT35 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
