### ISSUE TITLE
Invalid hex color in instructions

### ISSUE THREAD

**Issue by tjgerot** [FreeCodeCamp/FreeCodeCamp#10367]
#### Challenge Name
[Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors)

#### Issue Description
The hex value for dodger blue is noticeably different, and quite far from the established dodger blue. It should be changed from `#2998E4` to `#1E90FF` to represent the true web standard for dodger blue.

#### Browser Information

* Browser Name, Version: Google Chrome 52.0.2743.116 (Official Build) m (64-bit)
* Operating System: Microsoft Windows 10 Home
* Mobile, Desktop, or Tablet: Desktop

**Comment by atjonathan** [comment]
**To First Timer:**
You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4797) line, [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4828) line and [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4829) line, replacing `#2998E4` with `#1E90FF`. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by mjsiu** [comment]
Hello, I'm a fairly junior developer who recently started working full time. I'm looking to get more involved in the open-source community and since I'm a huge proponent of self-learning, I thought this would be a great project contribute to. I've heard a lot about FreeCodeCamp in podcasts and look forward to contributing!

I just submitted a PR to fix this issue (and my branch passed all the npm tests :)). 

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10372

**Comment by sergey-zhuravel** [comment]
The color was updated in the challenge, but now the challenge is broken, it don't accept any dodger blue colors
