### ISSUE TITLE
Settings page button color change issue

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10458]
#### Issue Description

On the settings page, after clicking the ghost buttons to toggle options off, the ghost button should immediately become empty (switched off). Currently they stay full (green) until you click something else.
#### Screenshot

![](http://i.imgur.com/BcGQXJ6.gif)

**Comment by ivantedja** [comment]
It is because after clicking a button, the button will get a "focus" and there is a styling for "focus" which makes it darkgreen. Probably the purpose is to make it looks good when navigating with keyboard? See attachments

![focus](https://cloud.githubusercontent.com/assets/1907854/18964196/02455df4-86a2-11e6-8e27-eb215057ff3c.png)

![focus-on](https://cloud.githubusercontent.com/assets/1907854/18964198/06a565a6-86a2-11e6-8853-be0d58c8bf09.gif)

**Comment by QuincyLarson** [comment]
@ivantedja can we clear the focus on click?

**Comment by ivantedja** [comment]
@QuincyLarson yes we can blur it on click but it is still hovered so the button stay green. I'll submit a PR for you to take a look. I'm still new with react though so need a lot of review for best practice and suggestion for more efficient way.

**Comment by QuincyLarson** [comment]
@ivantedja Great! would it be possible to disable the hover animation for on-off switch buttons like these as well? We could create a separate class that just applies to them with no hover effect and a blur on click. This is how Medium and many other sites seem to do this.
