### ISSUE TITLE
Size your image issue even though browser zoom is 100% 

### ISSUE THREAD

**Issue by balaaster** [FreeCodeCamp/FreeCodeCamp#10460]
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  .smaller-image{
    width: 100px;

  }
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image"     src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by erictleung** [comment]
@balaaster thanks for the issue. Please do not ignore the issue template that is provided for you. Filling out the template gives us information about your issue so that we may help you.

You code passes the challenge for me. Some things I can recommend is that you try submitting the challenge on another computer/device. That may help any issues you're having with the browser not being formatted correctly.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Re-open this issue only after you have trouble shooted using the help room and have some clues as to why you're having issues. Happy coding!
