### ISSUE TITLE
cursor problem

### ISSUE THREAD

**Issue by bennyboy22** [FreeCodeCamp/FreeCodeCamp#10462]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment]
Hi @bennyboy22. Could you please provide some more information about your issue? Your post doesn't have much in it 😄

**Comment by erictleung** [comment]
I'm assuming he's referring to the problem found in this issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. Please confirm if you're having the same issue as them.

**Comment by erictleung** [comment]
@bennyboy22 closing as stale. I believe your issue is what I linked to above. I would advise you to look at the conversation over there to get some ideas of getting around your cursor issues. If it is different than the issue I've linked to, feel free to reopen this issue or make another. Happy coding!
