### ISSUE TITLE
New line character is required before third line

### ISSUE THREAD

**Issue by tauheedkhan** [FreeCodeCamp/FreeCodeCamp#10485]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line



```

**Comment by dhcodes** [comment]
@tauheedkhan Could you provide some more information? If you're curious about why there isn't a new line before the third line, it's because it uses a carriage return which is quite similar. You can read about the differences here: http://stackoverflow.com/questions/1761051/difference-between-n-and-r

**Comment by erictleung** [comment]
@dhcodes I think the issue comes from the instructions

> Assign the following three lines of text into the single variable myStr using escape sequences.
> ```
> FirstLine
> \SecondLine\
> ThirdLine
> ```

Because when you print out the correct string, you don't get that new line.

![image](https://cloud.githubusercontent.com/assets/2754821/18261599/e4873d7e-73ae-11e6-828f-bf95a3e1769f.png)

We can either add the `\n` requirement on top of the carriage return or we can replace the carriage return for the `\n` requirement. 

Although I liked having carriage return in the challenge so that you're able to try different escape characters, practically, we'd probably want to use `\n` as it'll more commonly be used. So I'd go for replacing the carriage return with a new-line, but I'm open to either.

**Comment by tauheedkhan** [comment]
@erictleung In either case, expected result should be changed as carriage return will not give you a new line. Although I agree, using as many escape sequence in the problems is good for better understanding.

**Comment by BKinahan** [comment]
Ah, when I wrote this string for the challenge I tested it in repl.it and the FCC console, but not in browser consoles. In the former `\r` does introduce a line break but not in the latter.

I'd suggest replacing the `\r` requirement with a second `\n`, but also changing one of the escaped backslashes to a different character to maintain the diversity of escaped characters used. Perhaps this: `"FirstLine\n\t\\SecondLine\nThirdLine"`
```
FirstLine
    \SecondLine
ThirdLine
```

It loses some symmetry but should resolve the issue 😄

**Comment by BariqFitri** [comment]
i got it guys
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

**Comment by BariqFitri** [comment]
I got it guys
![tuto2](https://cloud.githubusercontent.com/assets/21375993/18336994/37732202-75bf-11e6-8662-9d06d38f6a81.PNG)

**Comment by erictleung** [comment]
@BKinahan sounds good compromise to me! 👍

**Comment by ktajpuri** [comment]
Can I work on fixing this one please?

**Comment by dhcodes** [comment]
@ktajpuri 👍  go for it :). If you have any problems, you can ask for help in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by systimotic** [comment]
@ktajpuri Are you still working on this?

**Comment by elisecode247** [comment]
I'd like to work on it if it's open

**Comment by Waseemarif** [comment]
It's not working 
var myStr = "FirstLine\n\\SecondLine\\\n\t\rThirdLine";

**Comment by Waseemarif** [comment]
It's not working
var myStr = "FirstLine\n\SecondLine\\n\t\rThirdLine";
same Error: There should be a newline character between SecondLine and ThirdLine

**Comment by StepanBohdan** [comment]
RESOLVE
var myStr = 'FirstLine\n\t\\SecondLine\nThirdLine';
'FirstLine\newline\tab\backslashSecondLine\newlineThirdLine'

**Comment by dogomeodenzoy** [comment]
Try this one: works for me,

![image](https://user-images.githubusercontent.com/42873851/46726915-02eafe00-ccb2-11e8-9687-b31403cd779a.png)

**Comment by neofito777** [comment]
var myStr = "FirstLine\n\t\\SecondLine\nThirdLine";
This is what solve this challenge
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings/

**Comment by tarunmanchukonda** [comment]
var myStr = "\nFirstLine\n\t\\SecondLine\nThirdLine"; 
This gave me the solution.

**Comment by alphaAashish** [comment]
"\nFirstLine\n\t\SecondLine\nThirdLine";
not working

**Comment by RandellDawson** [comment]
I am locking this because this issue has been closed and the other comments I am seeing should be addressed on the forum.
