### ISSUE TITLE
Bad coding practice used in example (Tribute Page)

### ISSUE THREAD

**Issue by MoleManMike** [FreeCodeCamp/FreeCodeCamp#10515]
#### Challenge Name
https://www.freecodecamp.com/challenges/build-a-tribute-page

#### Issue Description
Codepen.io example for the Tribute Page challenge uses ```<image>``` instead of ```<img>```, which is technically incorrect and could lead to compatibility issues in some cases. Given, most browsers recognize ```<image>```, but using it all the time would be a bad habit to get into, given that some fringe cases may throw errors based on it's usage.
It should certainly not be used in an example piece of code.
https://codepen.io/FreeCodeCamp/pen/NNvBQW
 
#### Screenshot
http://puu.sh/r4iDK/86186ed93e.png

**Comment by erictleung** [comment]
@MoleManMike thanks for the issue. Because the code shouldn't be looked at anyways and it still renders through Codepen, then I don't see too big of a problem. Plus, it appears that the [HTML parsing spec](http://stackoverflow.com/a/11929639) maps `<image>` elements to `<img>` in the tree construction. Still haven't been able to confirm that, though.

However, yes I agree that `<img>` tags should be used anyways.

@raisedadead do you approve? If so, can you change this in the FCC example of the project?

**Comment by MoleManMike** [comment]
Yeah, not a huge issue, just thought that since it was an example, and I'm sure people take sneak peaks at it, best not to accidentally form bad habits in new developers. 
Thanks

**Comment by hallaathrad** [comment]
Fixed 💃 Thanks for noticing this, @MoleManMike

**Comment by vaibhqv** [comment]
do u even know who is he 

he is Quincy the founder of freecodecamp
