### ISSUE TITLE
Code recovery function sometimes overwrites your new code

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10629]
When you fail to pass tests on a challenge, then modify your code and try again, the system deletes all your modifications and resubmits the previously failed code.

@p1xt - can you add additional detail and/or steps to reproduce?

**Comment by P1xt** [comment]
@QuincyLarson Did some fixes already get pushed live this morning. I went back to a couple of the places where I was able to reproduce this last night, and it's not reproducible now. However, I have no way of knowing if the difference is that I've refreshed the page since then or not (there are widespread reports that spamming refresh fixes a number of issues).

**Comment by QuincyLarson** [comment]
@P1xt yes - @BerkeleyTrue has been continually pushing fixes. I think we need a way to force a reload of a client's the JavaScript. If refreshing is fixing problems, that's probably the best way to fix this. I am closing this issue since you're currently unable to reproduce, as it sounds like this has either already been fixed or will be fixed once we can force a refresh.
