### ISSUE TITLE
VarCI-bot is overzealous

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#10638]
Over the past 12 hours @VarCI-bot has consistently fussed campers who reported legitimate bugs, telling them that to not bug report when they just need help solving a challenge.

**Comment by P1xt** [comment]
Heh, overzealous bot remains overzealous - it hit this report within 2 seconds.

**Comment by BerkeleyTrue** [comment]
This is by design. We get over 30 issues a that are requests for help. A small percent are actually bug issues.

> it hit this report within 2 seconds.

Yes. It is a bot. It has none of our human failings.

Happy Coding.

**Comment by P1xt** [comment]
I'm not saying using a bot is bad.

I'm saying the bot is heavily weighted towards false positives and that it's flailing around telling people "that's not a bug, learn to report right" on dozens of legitimate bug reports - in a condescending manner guaranteed to discourage further bug reports in the future - on a day when a bug-ridden mess of obviously non-tested code was just dumped into production with no warning.

@QuincyLarson It is counterproductive to bot "stop posting bug reports you noob" on a day when an unholy mess was tossed into production and you actually want people to report the bugs they find.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue you said "We get over 30 issues a that are requests for help" - did you mean 30 issues a day?

We might want to consider changing the UI to make it a more deliberate process in order to report a bug. For example, we could replace the existing buttons with a single "help" button that leads to a menu:

- Get a hint
- Open help chatroom
- Report a bug

This would simplify our UI a bit and make it an extra click to report a bug. 

@P1xt what do you think of this solution?

It's in no one's interest to have help-related questions submitted as issues.

**Comment by P1xt** [comment]
@QuincyLarson I like that solution, gently guiding folks to the appropriate place beforehand would help train in good practices.

In the meantime - I really would turn off that bot until the the site is actually reliably working again. Fussing people who are reporting legitimate bugs is a pretty shoddy idea.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Yes, this is the reason why our issue count is so high.

> We might want to consider changing the UI to make it a more deliberate process in order to report a bug

We discussed this early on and we landed on "We shouldn't put up barrier to opening issues" but I'm all for make it a deliberate process instead of two clicks.

@P1xt The VarCi is working as intended.

Looking through the issues it has tagged, most are duplicates which have been closed. The only open one is also a duplicate.

> Reprimanding people who are reporting legitimate bugs is a pretty shoddy idea.

That is hyperbole, I'd hardly call VarCI's comment a reprimand. It asks kindly to consider whether the issue is actually an issue and to search for help in the appropriate places. The bot does not close the issue. It is up to the user to close the issue.

**Comment by jdbarras** [comment]
@BerkeleyTrue  I opened a legitimate issue yesterday and it had me self-conscious to the point that I almost closed the issue myself because I felt stupid. You can call it hyperbole if you want to, but I would at least call that a negative effect. The bot's text is weighted toward making the OP think he's doing something wrong. 

You say it asks kindly. Its manners aren't the issue. The issue is whether those who report legitimately are led to believe they posted in error.

**Comment by P1xt** [comment]
@QuincyLarson closed issue or not, "working as intended" or not, "hyperbole" or not, I still believe the solution you suggested above is a much more productive means of both getting campers help if they need it, and getting legitimate issues bug reported. Last night after production was reverted, the first report of the legitimate issue of blanked out lines on camper portfolios was closed by the same camper who opened it when the bot "kindly" suggested they do so.
