### ISSUE TITLE
The Dodger Blue Hex code is not being recognized as the correct value.

### ISSUE THREAD

**Issue by Hazami** [FreeCodeCamp/FreeCodeCamp#10708]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**When entering the provided hex code for Dodger Blue, the color value will not be recognized as correct.**

```html
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```

**Comment by d-m-h** [comment]
Hi Hazami,

The hex code for dodger blue is: 2998E4.

Can you change your CSS and give it a shot?

**Comment by Hazami** [comment]
Tried changing it to the provided hex code and it did not work either. Attaching a screenshot.
![dodgerblue](https://cloud.githubusercontent.com/assets/22108928/18450641/aec8c57e-78e8-11e6-8bc3-cd6880b50443.JPG)

**Comment by ChrisD1986** [comment]
Copy and paste the dodger blue he code.

**Comment by energizerpiggy** [comment]
I have no idea what that even is!-------- Original Message --------Subject: Re: [FreeCodeCamp/FreeCodeCamp] The Dodger Blue Hex code is not being recognized as the correct value. (#10708)From: Damien Hawes To: FreeCodeCamp/FreeCodeCamp CC: Hi Hazami,

The hex code for dodger blue is: 2998E4.

Can you change your CSS and give it a shot?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeCodeCamp/FreeCodeCamp","title":"FreeCodeCamp/FreeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeCodeCamp/FreeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@d-m-h in #10708: Hi Hazami,\r\n\r\nThe hex code for dodger blue is: 2998E4.\r\n\r\nCan you change your CSS and give it a shot?"}],"action":{"name":"View Issue","url":"https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10708#issuecomment-246452544"}}}

**Comment by erictleung** [comment]
@Hazami thanks for the issue. This issue has been fixed with the recent PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10650. The changes will be added with the next push of updates. Happy coding!

**Comment by Miglenova** [comment]
Hello,
I have the same issue. Hex code #1E90FF is not accepted. Can't continue to the next challenge.
Please advice. 
Thank you!

**Comment by LissaNgSang** [comment]
Hi,

Im having same issue here, tried both #2998E4 and  #1E90FF . Can you please fix this? Thanks!

**Comment by aa95** [comment]
Hey guys, I was able to solve similar problems by simply pasting correct code given in the description rather than typing it in myself. Hope this helps! :)
