### ISSUE TITLE
Make Streak more lenient (due to time zone confusion)

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#1075]

**Comment by metasean** [comment]
In addition to more appropriate time zone tracking, it would also be nice to have more than just bonfires included in the streaks.

Specifically, I would include Waypoints, Bonfires, Ziplines, and Basejumps in the count.  It would also be nice to see what a day's streak is composed of (like Github's streak shows pushes, merges, issue updates, e.g. https://github.com/QuincyLarson?tab=contributions&from=2015-03-30).

Along the same lines, it be awesome if this data was in an API so it could be aggregated.  For example, I want to do something code related daily, but it doesn't matter if it's recorded on FreeCodeCamp, Github, Gitlab, http://www.codewars.com, etc.  (If I wasn't already massively over-committed, I would absolutely sign up to do this, :worried: but hopefully there's a FreeCodeCamper out there looking for a project :wink: )

**Comment by metasean** [comment]
As for which timezone, I'd say the local time of the machine on which the assignment is completed.  It looks like that shouldn't be too difficult to grab with JS  - http://stackoverflow.com/a/8984850/4285306

**Comment by CJEhmke** [comment]
I think grabbing the timezone is over-complicating the issue a bit, as you'd have to go and fix the checks to now include the timezone and make a few extra calculations.

I propose to instead send the full local time on the machine and using that to replace the times the server uses to check, that way you don't have to go messing with the algorithms which perform the checks. Fixing the problem at the source as it were rather than fixing it while checking.

**Comment by BerkeleyTrue** [comment]
I think I've found a solution while refactoring progressTimestamps.
