### ISSUE TITLE
test passed, but still bugged

### ISSUE THREAD

**Issue by cafruv** [FreeCodeCamp/FreeCodeCamp#10797]
Challenge Record Collection has an issue.
```js
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};

var collectionCopy = JSON.parse(JSON.stringify(collection));

function updateRecords(id, prop, value) {
  if (prop != "tracks" && value !== "") {
    collection[id][prop]= value;
  }
 if (prop=="tracks" && typeof collection[id].tracks==="undefined"){
    collection[id].tracks=[];collection[id].tracks.push(value);}
 if (prop=="tracks" && typeof collection[id].tracks!=="undefined") {
      collection[id].tracks.push(value);}
 if (value==="") {
     delete collection[id][prop];
  }
 return collection;
  }
```
with this code, I can pass this test. But the output after 
>updateRecords(5439, "tracks", "Addicted to Love"); '

 is [...      "Addicted to Love",
      "Addicted to Love"...] so repeated values are found.

**Comment by cafruv** [comment]
the output is [...
      "Addicted to Love",
      "Addicted to Love"...] i think is wrong.

**Comment by texas2010** [comment]
@cafruv, Did you ask a help first in [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) ?

**Comment by erictleung** [comment]
@cafruv the "bug" comes from your code

```js
...
 if (prop=="tracks" && typeof collection[id].tracks==="undefined"){
    collection[id].tracks=[];collection[id].tracks.push(value);}
 if (prop=="tracks" && typeof collection[id].tracks!=="undefined") {
      collection[id].tracks.push(value);}
...
```

These two `if` statements are run consecutively. This is because the first condition is satisfied because initially, `tracks` is undefined. Going through that `if` statement, your `tracks` condition now has something there, satisfying the second `if` statement above, thus pushing the contents again.

We could test for these but I'm not sure how much value this would bring relative to the work put into it. This challenge isn't a required on for certifications. 

@FreeCodeCamp/issue-moderators bikeshedding or something to pursue?

**Comment by dhcodes** [comment]
@erictleung fwiw, I remember having something similar when I first approached this challenge and it was helpful to learn that if-statement order matters so I don't know that it's worth more tests.

**Comment by Bouncey** [comment]
Closing as code help
