### ISSUE TITLE
"Smallest Common Multiple" challenge - test fails for correct code

### ISSUE THREAD

**Issue by internetbird** [FreeCodeCamp/FreeCodeCamp#10837]
#### Challenge Name
[https://www.freecodecamp.com/challenges/smallest-common-multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple)

#### Issue Description
The following correct code fails for the last test : smallestCommons([23, 18])

#### Browser Information

* Browser Name, Version: Chrome, Version 53.0.2785.116 m (64-bit) 
* Operating System:  Windows 10 64bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
 function smallestCommons(arr) {
  
  arr = arr.sort();
  
  var from = arr[0];
  var to = arr[1];
  
  var smallestCommon = to;
  
  while(!isDevisibleByAll(smallestCommon, from , to)){
    smallestCommon++;
  }  
  return smallestCommon;
}

function isDevisibleByAll(num, from , to){
  
  for(var i=from; i<= to; i++){
    if((num % i) !== 0){
      return false;
    }
  }
  
  return true;
}


smallestCommons([1,5]);
 
 
```

**Comment by dhcodes** [comment]
@internetbird this is more of a problem caused by the loop-protect feature of the editor that helps to prevent infinite loops and browser crashed caused by them. If you copy the failing test into the code editor, you'll see that it recommends adding `// noprotect` as the first line to override the loop-protection. If you do that, it will pass.

**Comment by internetbird** [comment]
@dhcodes  cool. thanks. I will close this issue

**Comment by GeniaT** [comment]
Hi, I see this issue as closed but I spent an hour trying to figure out why I the editor didn't pass the 5th test. Maybe include the // no protect information in the instruction?
