### ISSUE TITLE
Get GitHub to correctly detect our license

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10869]
GitHub recently introduced a new feature where it automatically lists the repo's license: https://github.com/blog/2252-license-now-displayed-on-repository-overview

@mgattozzi is working on this (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10842)

**Comment by mgattozzi** [comment]
So I've looked into this some more. Unless we split the licenses and make one of the LICENSEs non mark down Github won't recognize it with their code and the repo won't display the badge.

This means if the feature is wanted the License file must be split up unfortunately. That or a ticket is submitted to Github to patch their feature to recognize the license based on it having all of the contents of one license in a file and then ignoring the rest. I'm not sure why they didn't design it this way but those seem to be the only options available unfortunately.

**Comment by QuincyLarson** [comment]
@mgattozzi were you able to get the gem working locally?

**Comment by mgattozzi** [comment]
I was looking all over and couldn't find it. However after researching I
found what gem they use buried in the docs. Let me retry again and I'll
keep you posted.

**Comment by marhyorh** [comment]
@mgattozzi Can it be done [this way](https://github.com/marhyorh/FreeCodeCamp). Having a main license, and a provisional license... or perhaps something else.

**Comment by mgattozzi** [comment]
I had suggested splitting it but I don't think @QuincyLarson really wants that. I think the next solution would be to patch licensee the gem used by github upstream to detect other file names and things. A lot harder and it depends on when Github updates it if they do use it. Otherwise, splitting seems to be most viable at this time unless I figure something else out.

**Comment by marhyorh** [comment]
Okay. I'll also try looking into other ways as well.

**Comment by raisedadead** [comment]
@QuincyLarson The gem results with the below:

```
raisedadead:~/workspace/FreeCodeCamp (staging) $ gem install licensee
Fetching: rugged-0.24.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rugged-0.24.0
Fetching: licensee-8.7.0.gem (100%)
Successfully installed licensee-8.7.0
2 gems installed
raisedadead:~/workspace/FreeCodeCamp (staging) $ licensee 
License file: LICENSE.md
License hash: ac19042dbde4fcfd6b2b2838272d4710a7dc8005
Attribution: Copyright (c) 2016 Free Code Camp.

Here's the closest licenses:
* CC-BY-4.0 similarity: 86.67%
raisedadead:~/workspace/FreeCodeCamp (staging) $ 
```

**Comment by raisedadead** [comment]
The gem detects our current LICENCE.md as closer to **CC-BY-4.0**, if we want it to be BSD-3 then the text would have to be updated as such in the LICENCE.md

**Comment by QuincyLarson** [comment]
@raisedadead wow - thank you for installing this and running this. I will look into this and get back to you on how we should proceed.

**Comment by QuincyLarson** [comment]
@raisedadead OK - here's @kemitchell recommended we do: 
-  Move curriculum license to a separate file if you like.
-  Mention both sets of terms (and corresponding files) in README.

@mgattozzi or @raisedadead would you be interested in doing the honors?

**Comment by raisedadead** [comment]
@mgattozzi since you already have had made a PR, I feel you should take the credit for this contribution ... 😃 !

- Create a LICENCE or LICENCE.md file with BSD for the code base.
- Create a LICENCE-Free-Code-Camp-Curriculum.md file for the curriculum with text from the existing CC-BY-4.0 type text.
- Update the readme to reflect links to both.

In case you are not available, I will be glad to take it up.
