### ISSUE TITLE
Test is ok but sould faill 

### ISSUE THREAD

**Issue by erivancerqueira** [FreeCodeCamp/FreeCodeCamp#10891]
#### Challenge Name

My code pass on test, but I think that should fail because i test if value !==false for all elements it shouldn't return false.
 
* Browser Name, Version: Firefox
* Operating System: windows 8
* Desktop 

#### Your Code
```js
function bouncer(arr) {
  
 var arrFilter = arr.filter(function(value){
   
    console.log("before test " + value);
   
    if(  value !==false ){
      
     console.log("after test " +  value); 
     return value;
      
    }
  });
  
  return arrFilter;                     
}

bouncer([false, null, 0, NaN, undefined, ""]);
```

**Comment by Bouncey** [comment]
@erivancerqueira the instructions for that challenge ask that you return an array with all falsely values removed, which is what your code does. 

From what I can see, the challenge and your code are working correctly.

**Comment by ChBernat** [comment]
What if I tell you that your code is messed up?

You're returning an empty array as an arrFilter - if that's okay is up to you, but your check whether value is true or false is wrong.

Why? Let me explain.

You're using an identity operator so your code is checking for types first and if those are wrong (in your case those are different!) than it returns false. Else, of course it will compare values and return a proper output. Following this statement things you're trying to achieve are impossible because only `false` in your case will be a valid value.

The second problem is the fact that it seems like you do not understand how `Array.prototype.filter` really works. You're trying to return values that are not strictly equal to false and that would be okay if your check was valid. Just by now you're returning false values that are reprocessed by `filter` function and as result you are gaining an empty array.

If it would be not a `filter` function - your array would looke like so: `[null, 0, NaN, undefined, ""]`.

Hope that helps. :)

**Comment by Bouncey** [comment]
@ChBernat this challenge suggests the use of the array.filter() method. The instructions state that you are given an array of values, and you are to return an array with no falsely values. 

@erivancerqueira 's code is correct. Sure it could be smartened up a little but that comes with experience. 

@erivancerqueira is testing his code with one of the test cases that requires a return of an empty array. I hope this clears this up for you

**Comment by ChBernat** [comment]
Yeah, I was just writing this comments before even I could have looked at yours.

That's from where the confusion may comes from.

**Comment by erictleung** [comment]
I'm not sure how we would check for this kind of "loop hole." You could even run the following to pass.

```js
function bouncer(arr) {
  return arr.filter(function(val) { return val; });
}
``` 

So this might be a "feature" you're exploiting to complete the challenge.

**Comment by Bouncey** [comment]
@erictleung there is no loophole, that is a feature of the language. Some see it as an advantage over statically typed languages

That's basically saying if val it true, return val.

**Comment by Bouncey** [comment]
If you wanted to return all the falsely values, you would do

return !val;

**Comment by Bouncey** [comment]
Closing as there is no issue that I can see. 

If I have misunderstood your issue, feel free to open this issue again

Happy coding!

**Comment by erivancerqueira** [comment]
@Bouncey Exactly!! It's  saying if val it true, return val.I thought that this condition should apply only to the elements! == false that undefined and others should returned, but all it are treated as false and all are ignored which causes the code passes the test. But I understand that this is so that javascript is these values, [false, null, 0, NaN, undefined, ""], all as false.
