### ISSUE TITLE
Kilometers/meter confusion

### ISSUE THREAD

**Issue by neva78** [FreeCodeCamp/FreeCodeCamp#10907]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The earth's radius is given in km.
The [Wikipedia formula for calculating the orbital period](https://en.wikipedia.org/wiki/Orbital_period) says the semi-major axis should be measured in meters.
However, in the code below, which passes this challenge, I calculate the semi-major axis using 'obj.avgAlt + (earthRadius)'
Shouldn't the correct code be '(obj.avgAlt * 1000) + (earthRadius * 1000)', in order to convert to meters?
Thanks.

My code:
```javascript

function orbitalPeriod(arr) {
  let convertedArr = arr.map(getOrbital);
  return convertedArr;
}

let getOrbital = obj => {
  let GM = 398600.4418,
  earthRadius = 6367.4447,
  aTemp = obj.avgAlt + (earthRadius),
  a = Math.pow(aTemp,3),
  b = a / GM,
  c = Math.sqrt(b),
  d = 2 * Math.PI,
  e = Math.ceil(d * c) - (d * c) > 0.5 ? Math.floor(d * c) : Math.ceil(d * c);
  delete obj.avgAlt;
  obj.orbitalPeriod = e;
  return obj;
};

orbitalPeriod([{name: "iss", avgAlt: 413.6}, {name: "hubble", avgAlt: 556.7}, {name: "moon", avgAlt: 378632.553}]);
```

**Comment by hgdsraj** [comment]
Because the radius, altitude, semi-major axis ans gravitational parameter are all exprssed in kilometers, the division of aTemp/GM provides the same ratio as if aTemp and GM were in meters. 

Note: GM in meters is 3.986004418(9)×10^14 meters cubed per centisecond.
You will note that simply dividing this value by 1000 does not yield the given kilometers cubed per centisecond value from the problem statement.
Because it is cubed, converting from meters cubed to kilometers cubed per centisecond is not as simple as a single multiplication. The substeps allow us to express the semi major axis in kilometers when the standard gravitational parameter is in kilometers cubed / s^(-2).

For a very simple example imagine the equation 
X^3/Y^3 = 1 where X and Y are in meters. Now imagine Y^3 = Z. Let B = [ (cbrt(Z)*1000) ^ 3]

Given X^3/B = 1, with X defined in km is now confusing, but as you see from above, there were substeps to allow X to be in km and B was transformed to keep all ratios the same.


Hope this helped!

**Comment by neva78** [comment]
Many thanks for the explanation. One other aspect that puzzled me was I
thought the semi-major axis would equal (avgAlt * 2) + radius, to account
for the altitude at each of the two points above the earth that marked the
extremities of the ellipse.
I appreciate your help and understand if you don't have time to address
this point as well.

**Comment by hgdsraj** [comment]
As we are adding to the radius, and not the diameter, there is no need to
multiply by two. The radius is the distance from the center of the sphere
(the inner core) to the outer crust. This is not the distance across the
entire sphere.  Adding the avgAlt gives us the total radius, from the
center of the sphere to the object. We would only multiply by two of we
were considering the diameter.

Raj

**Comment by neva78** [comment]
Ah, of course. I confused radius and diameter. Thanks again.
Best wishes,
Nick

**Comment by dhcodes** [comment]
Closing as seems to be resolved
