### ISSUE TITLE
Where do I belong not marking correct answers as correct.

### ISSUE THREAD

**Issue by gsuxlzt** [FreeCodeCamp/FreeCodeCamp#10911]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20res%20%3D%20arr.sort(function(a%2Cb)%7B%20return%20a-b%3B%7D)%3B%0A%20%20for%20(var%20x%20in%20res)%20%7B%0A%20%20%20%20if%20(res%5Bx%5D%20%3E%3D%20num)%20%7B%20return%20x%3B%7D%0A%20%20%7D%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  var res = arr.sort(function(a,b){ return a-b;});
  for (var x in res) {
    if (res[x] >= num) { return x;}
  }
}

getIndexToIns([40, 60], 50);

```

My code is returning the right answer. However, it is still marked as wrong in the checker. 

![screenshot](https://cloud.githubusercontent.com/assets/19965890/18813725/d331a0fe-8336-11e6-8928-2b8b5a1a88ae.png)
I tried hard-refresh, local storage clearing, and cache clearing, still no use.

**Comment by DavOnGit** [comment]
Actually your code don't pass the last test: infact if `num` is greater than the max value in `arr` your if condition is not true and the code exit.

**Comment by shubham1996** [comment]
As pointed out @DavOnGit your code isn't taking care of an edge case present in the last test case.
But the test cases are not being shown evaluated because you have overlooked the fact that a for-in loop is generally used to iterate over object properties, and the type of variable x in your loop will not necessarily be an number. Since the asserts in the test cases of this question expect it to be a number, your code will fail the test cases. 
I would suggest you to read about the <code>parseInt</code> method, which will help you to complete this challege.
If you are still stuck, head over to the gitter chat room and ask.

Have a good day!

**This is not an issue, and can be closed.**

**Comment by gsuxlzt** [comment]
Yes I realized that and changed my code accordingly. Thank you for your answers! This thread can be closed now.
