### ISSUE TITLE
Doesn't see my comments

### ISSUE THREAD

**Issue by tsalexey544** [FreeCodeCamp/FreeCodeCamp#10925]
Challenge [Comment your JavaScript Code](https://www.freecodecamp.com/challenges/comment-your-javascript-code#?solution=%2F%2F%20d%20regularly%20add%20comments%20to%20clarify%20the%20function%20of%20parts%20of%20your%20code.%20Good%20commenting%20can%20help%20communicate%20the%20intent%20of%20your%20code%E2%80%94both%20for%20oth%0A%0A%2F*%20d%20regularly%20add%20comments%20to%20clarify%20the%20function%20of%20parts%20of%20your%20code.%20Good%20commenting%20can%20help%20communicate%20the%20intent%20of%20your%20code%E2%80%94both%20for%20oth%20*%2F%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// d regularly add comments to clarify the function of parts of your code. Good commenting can help communicate the intent of your code—both for oth

/* d regularly add comments to clarify the function of parts of your code. Good commenting can help communicate the intent of your code—both for oth */


```

**Comment by ivantedja** [comment]
it appears that the test is not allowing word `function`

cc @FreeCodeCamp/issue-moderators

**Comment by ktajpuri** [comment]
This is intresting ! :+1:  @ivantedja you are correct. It appears this has occurred due to [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6fdf5c61a7a6ec88053cfcf6e9195160b5071e1e/client/commonFramework/detect-unsafe-code-stream.js#L36-L43) line in `detect-unsafe-code-stream.js` of `commonFramework`

It appears , currently the test checks if you have a word function in the code it must be a function declaration. **The fun part is**, not only this challenge every challenge is failing even for a valid use of word function. I suggest either we  modify the exception to say `Error: SyntaxError: Unsafe or unfinished function declaration. use of word function is not allowed in content for safety reasons.` or we improvise the regular expression to detect such cases.

**Comment by dhcodes** [comment]
The message isn't too bad as-is in my opinion. It's just that at this point in the curriculum, campers might not know what a function is. What do others think? cc@FreeCodeCamp/issue-moderators

**Comment by ktajpuri** [comment]
We should suggest in some way that use of word function might be causing the issue.

**Comment by Bouncey** [comment]
I had a PR somewhere for this that was reverted and I never got round to re submitting it. I'll dig it out tonight
