### ISSUE TITLE
Improve CSP based on Google's guidance

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10930]
Google recently released a [CSP evaluator tool](https://csp-evaluator.withgoogle.com/). I ran our CSP through it and got this:
![](https://www.evernote.com/l/Ar9oJryDJw9FYJ1ItdU-Qtk6PNCMIlEuBrAB/image.png)

Note that this will require a lot of QA, as edge cases can be difficult to foresee.

**Comment by alexanderholman** [comment]
The best way to achieve this is via a HTTP header, or it can be done via a `<meta>` tag:

**Comment by alexanderholman** [comment]
I wouldn't mind taking a look at this, though I imagine it would be easier to configure on your server (setting HTTP headers as oppose to getting the meta tag), but if you would rather the meta route, i could look at it this weekend?

**Comment by QuincyLarson** [comment]
@alexanderholman Sure - we would welcome your help. This is relatively low-priority, so this weekend is fine :)

**Comment by charlottetan** [comment]
Hi there, I was taking a look at this, and wondered if we could use [helmet](https://www.npmjs.com/package/helmet), it seems like that's the [common go-to](http://lollyrock.com/articles/content-security-policy/) for CSP protection. Helmet also takes care of a number of other security concerns, including removing the `X-Powered-By` header. This header is currently being [manually removed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/server.js#L40). Otherwise if we are concerned about keeping code lean, we could just set the header in [server.js](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/server.js).

**Comment by charlottetan** [comment]
I'll like to give this one a shot

**Comment by atjonathan** [comment]
@charlottetan, go ahead ❗️

**Comment by QuincyLarson** [comment]
@charlottetan we started using Helmet about 18 months ago. If you want to tweak the Helmet settings to optimize our CSP for Google, it's located here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middlewares/csp.js

**Comment by charlottetan** [comment]
Thanks @QuincyLarson and @atjonathan! I've been working on this today and it's getting [pretty hairy](https://github.com/FreeCodeCamp/FreeCodeCamp/compare/staging...charlottetan:fix/csp), mainly because in order to get it not-red, script-src needs to not have "unsafe-inline". I set about converting inline scripts to non-inline, but it's getting a little complicated, especially with [react involved](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/server/views/layout-react.jade#L11). I'm wondering if I should continue extracting inline js out as my branch is gathering lots and lots of commits. The alternative would be to use a [nonce](https://developers.google.com/web/fundamentals/security/csp/). Google highly discourages using the nonce, but it looks like it might be necessary for some of these.

**Comment by QuincyLarson** [comment]
Hi @charlottetan thanks for your patience with my slow response.

Reading the documentation you linked to, I am inclined to agree with Google. There must be a better way.

@BerkeleyTrue what are your thoughts on this?

**Comment by BerkeleyTrue** [comment]
We can't change `unsafe-inline`.

We can't change `object-src` to none as we do use embeded youtube videos.
