### ISSUE TITLE
Field guide error

### ISSUE THREAD

**Issue by benflinn** [FreeCodeCamp/freecodecamp#1094]
http://www.freecodecamp.com/field-guide/how-can-i-stream-my-live-coding-sessions-on-free-code-camps-twitch-tv-channel

"Contact Jason Ruekert - he's @jsonify in Slack."

Since freecodecamp is now using Gitter again, I believe that should say "Contact Jason Ruekert - he's @jsonify in Gitter."

**Comment by NatashaHaggard** [comment]
Fixed, started a pull request - https://github.com/NatashaHaggard/freecodecamp/pull/1

**Comment by benflinn** [comment]
Thanks! by the way I found a lot of errors in the field guide while reading it. Should I continue making lots of requests to fix each of them? I'm very new to github and freecodecamp.

**Comment by NatashaHaggard** [comment]
Posted the wrong link before, here's a new one - https://github.com/FreeCodeCamp/freecodecamp/pull/1101

I'm new to Github too, still figuring it out; I'd say continue posting whatever errors you find as new issues:)

**Comment by LumenTeun** [comment]
This, as well as some other Slack/Gitter issues, is being fixed in my #1096 (or #1101 if they pull that first :) ) You could probably close this since we know a fix will be in production soon.

Since most of these errors are quite simple, usually just a grammatical error or a missing test, you guys could always learn to fix them yourselves. The grammatical errors doesn't really *need* you to get an entire local FCC instance up and running, you just need to clone the staging branch, edit the appropriate file in seed/, and create a pull request. Hit me up on Gitter if you need help :)
