### ISSUE TITLE
No mention about document type, html, body and head tags in the 

### ISSUE THREAD

**Issue by nhquiroz** [FreeCodeCamp/FreeCodeCamp#11050]
#### Challenge Name
[HTML5 and CSS track](https://www.freecodecamp.com/map-aside#nested-collapseHTML5andCSS)

#### Issue Description
Every HTML tutorial I read started with the `!DOCUMENT`, `html`, `body` and `head` tags. There's no mention about them in the current HTML track (and I don't see any changes in that direction in the Expansion). 

Why is that? Anything related to the tests engine?

Thanks

**Comment by mooseworx** [comment]
One of these things is not like the other

**Comment by karuppiah7890** [comment]
@nhquiroz I think it's all included behind the scenes, since the tags `!DOCUMENT` , `html` , `body`, `head` are all just a repetition in all the html code challenges. 

And some more stuff are included behind the scenes, like the link tag to add Bootstrap CSS, and then the link tag to add FontAwesome CSS (see image).

So, this is no bug.

![eg](https://cloud.githubusercontent.com/assets/12808424/19077377/0741c218-8a6a-11e6-9312-7daaf8e9ca31.png)

**Comment by nhquiroz** [comment]
I know this is not a technical bug and the tags are implicit, but it's a teaching bug. 

You can't teach HTML to someone and ignore that.

**Comment by karuppiah7890** [comment]
Well, I should agree. But for a newbie, if you stress too much on these tags, they will lose patience and leave before you teach them the actual cool stuff. So, I think, they can wait and be taught later. 

And yeah, I see that it's not mentioned anywhere(not even at a later part), like you said, so, may be you could chat with the moderators in the Gitter FreeCodeCamp chatroom and discuss about this, or ping Quincy Larson directly. 

But I am sorry, repo issues is only for bugs in the code of the site.

**Comment by dhcodes** [comment]
@nhquiroz open a new issue over in https://github.com/FreeCodeCamp/CurriculumExpansion because it's worth a conversation.

**Comment by nhquiroz** [comment]
Thanks, I'll open a new issue in the correct place then!
