### ISSUE TITLE
Suggestion: Reorder the instructions to follow: top, right, bottom, left

### ISSUE THREAD

**Issue by SherylHohman** [FreeCodeCamp/FreeCodeCamp#11059]
This Is Technically correct.

However, in the instructions, and in the code, I recommend that you instruct the student to set the borders in the following order: top, right, bottom, left.

currently you instruct and list tests in the order top, left, ..

Reason for suggestion is that the shortcut method runs top, right, bottom, left. 
Clockwise starting at the top.

If the material is always presented in that order, students will always be thinking in that order, and thus subconsciously, and naturally pick up the mentality of thinking of border/margin, etc in this order.
This will enable Many to automagically , naturally, think of these items in that order, and will have no trouble "remembering" the order later. 

As it is, the first intro sets the mind, though process, and coding exercise in a different order.
Now there are more than one ordering in the student's mind, resulting in a conflict, or an unlearning, or at least more of an effort to remember which is the default.

thanks for taking this consideration into account.

Simply reordering the text of the directions can achieve this subtle memory enhancement.

Challenge [Add Different Padding to Each Side of an Element](https://www.freecodecamp.com/challenges/add-different-padding-to-each-side-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding-top%3A%2040px%3B%0A%20%20%20%20padding-right%3A%2020px%3B%0A%20%20%20%20padding-bottom%3A%2020px%3B%0A%20%20%20%20padding-left%3A%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding-top%3A%2040px%3B%0A%20%20%20%20padding-right%3A%2020px%3B%0A%20%20%20%20padding-bottom%3A%2020px%3B%0A%20%20%20%20padding-left%3A%2040px%3B%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding-top: 40px;
    padding-right: 20px;
    padding-bottom: 20px;
    padding-left: 40px;
  }

  .green-box {
    background-color: green;
    padding-top: 40px;
    padding-right: 20px;
    padding-bottom: 20px;
    padding-left: 40px;  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by karuppiah7890** [comment]
@SherylHohman The instructions like that just to reduce the redundancy in the sentence. It's easier to say 

>Give the green box a padding of 40px on its top and left side, but only 20px on its bottom and right side.

instead of

>Give the green box a padding of 40px on its top side, 20px on its right, 20 on it's bottom and 40px on it's left side.

However, these challenges : [Use Clockwise Notation to Specify the Padding of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-padding-of-an-element) and [Use Clockwise Notation to Specify the Margin of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-margin-of-an-element), ensure that the camper memorizes the clockwise notation which is "top, right, bottom, left" , the correct order. But again, even in these challenges, the instructions use words to reduce redundancy in the sentence. But the explanation in the challenge will be noted and be memorized by the camper.

So, I think, this is not a teaching problem. Please close the issue.

**Comment by Bouncey** [comment]
@karuppiah7890 This issue is perfectly valid in this repo.

@SherylHohman personally I think the challenge instructions are clear enough, and the sentence structure is purely for brevity, as noted by @karuppiah7890 . 

I am open to suggestions on how we can improve the instructions, so that they are presented in a clear and concise manner.

Happy Coding :tada:

**Comment by karuppiah7890** [comment]
@Bouncey Oh, sorry. I mistook it. And yes, even I think the instructions are clear enough.

**Comment by SherylHohman** [comment]
Perhaps I mis-named the section I was intending to refer to.
My apologies for incorrect terminology:  I'm not familiar with FreeCodeCamp setup.

Now that I think about it, it's probably the order the Tests are run in the Test Runner (?). 
(Perhaps still wrong terminology, maybe closer though..?)
I agree, the "instructions" are fine..
But the section down below, where each of the (challenges, points, to-do items) are listed
- students, after reading the instructions, will refer to that list and attempt to knock each item off, one by one.
It is Here that I believe the order of the items in the list should be changed.

This is where thinking about, and executing the items in the order that needs to be memorized will make a difference. Doing so in TRBL order from the get to will make a subtle difference in the long run.

It is in this location that students will keep referring to while they are actively coding, and the order will stick. It is also in larger font, and in bullet list format. Perfect for learning.
This location is necessarily redundant in its wording.

My apologies for the confusion,

Simply swapping; the order the tests are ran would improve comprehension of the order they should be learned.

If my guess is correct (that it's the order of the tests, rather than the text description), then I believe this is the proper location to keep the issue open.

I'm new to FreeCodeCamp, so please continue to update me if I am wrong in these assumptions.
I'm happy to learn your platform! :-)

Thank you again for (re-)considering.

**Comment by karuppiah7890** [comment]
@SherylHohman Oh, okay, so you meant the order of the Test cases. And you are right about the terminology this time, and it's fine if you didn't know the terminology, now you do. :smile: 

> As this would involve touching the code, I believe this is the proper location to keep the issue open.

Yes, this is the right place to keep the issue open. I m sorry that I mistook it earlier. I just thought changing the instructions in the code would first require some discussion which can be done in the Curriculum repository, since it's very important to have clear instructions. Some similar issue was dealt like that before. But then Bouncey said we could discuss here itself. 

Back to the issue. Now, you want us to change the order of the Test Cases. I think your reason for it is valid  and doing this change, won't cause any problems, so we could do it . @Bouncey Your comments ?

**Comment by Bouncey** [comment]
Ok, the tests for the challenge are held in an array [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a8cdb4eb6f74b741b1dc9f141bead3c625b37888/seed/challenges/01-front-end-development-certification/html5-and-css.json#L3846). 

They need to re-ordered so they follow the top-right-bottom-left notation of the padding shortcut syntax. 

This is for first-timers only, be sure to read and follow CONTRIBUTING.md. Any questions should be directed to the Crontibutors chat room on gitter

Happy coding and thanks for contributing 😄

**Comment by vgvenkat** [comment]
Hey guys, I would like to take this one.

**Comment by karuppiah7890** [comment]
@vgvenkat Sure! Go ahead!

**Comment by SherylHohman** [comment]
Thanks!

The same issue less in the next two challenges (correct term?).

If no-one minds, I'd like to do the contribution for the other two instances..

:-)

**Comment by karuppiah7890** [comment]
@atjonathan The change has to be made even in this challenge https://www.freecodecamp.com/challenges/add-different-margins-to-each-side-of-an-element . @SherylHohman wants to take it up.

**Comment by atjonathan** [comment]
@karuppiah7890, cool!

**Comment by karuppiah7890** [comment]
@atjonathan Uh, you closed it again. Is it gonna be a new issue ?

**Comment by atjonathan** [comment]
@karuppiah7890. was this not already solved in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11144 ?

**Comment by karuppiah7890** [comment]
@atjonathan  I am sorry. Didn't know a new issue #11111 had been created for it and was solved and closed.

**Comment by Bouncey** [comment]
This issue relates to the *padding* challenge, which still requires a PR

**Comment by Bouncey** [comment]
Sorry, #11138 fixed this, This
PR relates to the padding
