### ISSUE TITLE
would not pass the test if there is a spce between reusableFunction & (

### ISSUE THREAD

**Issue by ssathya** [FreeCodeCamp/FreeCodeCamp#11081]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20ourReusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AourReusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction%20()%20%7B%0A%20%20console.log(%22Hi%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction () {
  console.log("Hi World");
}

reusableFunction();



```
Took me couple of attempts but the test should ignore any space between function name and parenthesis.  Accepts reusableFunction() but not reusableFunction ().
Though "reusableFunction ()" is not standard coding practice the compiler will ignore the " ". Its a coding style and not an error.

**Comment by Deadpool37** [comment]
@ssathya Your code passes all tests irrespective of the whitespaces between the function and its parentheses. I would suggest you to try again and if you get stuck, then also provide screenshots.
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, only then you should post here.

**Comment by erictleung** [comment]
@ssathya thanks for the issue. Your code passes the challenges so I'm assuming the issue you've faced was in the calling of the function after you defined it, not in the definition of the function. In other words, calling `reusableFunction ();` failed the tests. 

And yes, this is on purpose because having a space between the function call and the parentheses is highly unusual, even taking different styles into account. So although it is a style that we are enforcing throughout the curriculum, I don't think it is super unreasonable to enforce it.

**Comment by ssathya** [comment]
okay

**Comment by AndreiLuca99** [comment]
I'm also suck here and I think the solution is not to use function separately.
There must be a smart way, but I'm not sure what it is for now.
I'd rather consult google and share idea about it with friends here.
