### ISSUE TITLE
No explanation what anti-pattern is

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11104]
Challenge [Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isLess(a, b) {
  // Fix this code
  if (a < b) {
    return true;
  } else {
    return false;
  }
}

// Change these values to test
isLess(10, 15);

```

**Comment by tourn171** [comment]
It explains everything that it needs to. Anti-pattern is a literary device used to describe a pattern of doing something that is not efficient or ineffectual. The point in the lesson is that there is no need to add the entire if else statement because comparison operators return true false in the first place. It's why things like  
  
`var a = true;  
if(a){ return b;}` 
  
work. So instead of using the whole if else statement you can just directly return the result of the comparison.

**Comment by QuincyLarson** [comment]
@marienhof I agree, there is no reason to use anti-pattern, which is jargon. A simpler way to say this would be to say "Sometimes people use an if/else statement to do a comparison, like this:" 

"But there's a better way to do this. Since === returns true or false, we can return the result of the comparison:"

**Comment by anu0012** [comment]
@QuincyLarson I would like to take this.

**Comment by QuincyLarson** [comment]
@anu0012 Great! It's yours. Please keep us posted on your progress :)

**Comment by anu0012** [comment]
@QuincyLarson I have already made a PR. See if it is appropriate.

**Comment by jamesbaudelaire** [comment]
don't us ===
us <= to compare


function isLess(a, b) 
{
 return a<=b;
}
isLess(10, 15);
