### ISSUE TITLE
Mistake 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11101]
It should be <10 and >5.

Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val) {
    return "Outside";
  }

  if (val) {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```

**Comment by dna113p** [comment]
I am not sure if this is talking about the problem itself or the example text. The example text is:

```will return "Yes" only if num is between 5 and 10 (5 and 10 included). The same logic can be written as:```
```
if (num > 10 || num < 5) {
  return "No";
}
return "Yes";
```
Which is certainly correct.

The problem Instructions don't even deal with 5 and 10 but rather 10 and 20 so maybe there is a confusion between the example and the instructions for the problem.

**Comment by dhcodes** [comment]
The instructions read correctly to me as well as the statement returns "No" if < 5 or > 10.

**Comment by erictleung** [comment]
@marienhof can you elaborate on what the issue is?

**Comment by Dayfiri** [comment]
![screenshot at 2016-10-08 10 29 42](https://cloud.githubusercontent.com/assets/16082563/19211672/391f5a0e-8d42-11e6-8d5e-20da3914b7bf.png)

I think here comes confusion on the first sight. 
```
if (num > 10) {
return "No";
}
if (num < 5) {
return "No";
}
return "Yes";
```
Example says only numbers that are between 2 if's will return "Yes" string. 
Numbers [6,7,8,9] will return yes because (>, <) operators do not include numbers 5 and 10.

@marienhof I think you mean that it need to be `>5 && <10` so it would return [5,6,7,8,9,10] numbers in between which is true but not used in this example.

Another example of what is bugging...
```
if(num < 10){
return "Yes";
}
if(num > 5){
return "Yes";
}
return "No";
```

**Comment by raisedadead** [comment]
Closing as stale.
