### ISSUE TITLE
You should have a total of two images appears as a problems because whenever I put two images, other areas are marked wrong

### ISSUE THREAD

**Issue by dlbonilla02** [FreeCodeCamp/FreeCodeCamp#11116]

**Comment by erictleung** [comment]
@dlbonilla02 thanks for the issue but please use the issue template when making issues. Can you give us information about the code challenge and your code? This sounds more of a coding question rather than an issue on the site. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by dlbonilla02** [comment]
<a href="#"><<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
<image class = "img-responsive" src = "https://bit.ly/fcc-running-cats"></a>

According to these lines of code I do NOT have a total of two images, and Yes I will use the issue template when making issues in the near future If you can Please direct me to the ISSUE TEMPLATE

**Comment by dlbonilla02** [comment]
<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
  <image class = "img-responsive" src = "https://bit.ly/fcc-running-cats"></a>

According to this, I do NOT have a total of two images and I'm doing my best to resolve the problem but I need extra assistance

**Comment by erictleung** [comment]
@dlbonilla02 the issue template should have autopopulated as you were opening the issue. In terms of your issue, you're using the wrong image tag. Use `<img>` instead. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
