### ISSUE TITLE
Need to Update Contributing.md

### ISSUE THREAD

**Issue by BhaveshSGupta** [FreeCodeCamp/FreeCodeCamp#11164]
#### Issue Description
Hey, 
Contributing.md needs to be updated, I think we should add tips for each step or something like If your struck at this step u can do following things this could be helpful for newbies. I was recently trying to setup it locally, it took me a lot of time to setup locally and lot of help from fellow campers

**Comment by erictleung** [comment]
@BhaveshSGupta thanks for the feedback. We're already working on updating the CONTRIBUTING.md document here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11006. Please add your feedback to the conversation over there. Happy coding!

**Comment by systimotic** [comment]
Hey @erictleung and @BhaveshSGupta! That issue you were referencing was just solved and closed. It seemed like that was just on the topic of merging a forum page into the CONTRIBUTING.md. I talked to Bhasvesh on Gitter for a bit. To add to his original description, the idea is to add a section with some troubleshooting steps. I've been in the Gitter room for about a week, and I've seen many people have the exact same issues, especially on Windows.  My PR #11172 aims to fix one of those issues. I'll be opening an issue for a conversation about the other one. One example of something that would be left to add: for me and Bhasvesh, Mongo doesn't connect sometimes. This can be solved by restarting nodemon (typing rs in the console and pressing enter), or just restarting gulp. Solving the root cause of this issue would be the best thing to do, but I don't think that we can really do that in this case. It doesn't seem like there's an issue on our side, rather on the driver or Mongo itself. Having a section in the CONTRIBUTING.md with things like this could help some new contributors and safe them some headaches. I'm a proponent of anything that reduces the barrier of entry to an open source project, because it can be a really daunting thing. If a new issue or a different issue is a better place to talk about this, I'd be happy to move this conversation over there.
