### ISSUE TITLE
The code only runs the last line, not allowing me to finish the exercise. Help? 

### ISSUE THREAD

**Issue by Dhouglas** [FreeCodeCamp/FreeCodeCamp#11167]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20fahrenheit%20%3D%20-10*9%2F5%20%2B%2032%3B%0A%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  
  fahrenheit = -10*9/5 + 32;
 
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);

```

**Comment by LoganS1** [comment]
I am not to good with Java, but is it because you never use the celcius variable in you equation for finding fahrenheit? I believe the code is running completely, but if simply returns the result of -10*9/5 + 32 everytime. Since this equation does not use the celcius variable. No matter what you put the celcius variable as, it well never be put into the equation. Try replacing the -10 with celcius and I think it will work.

**Comment by texas2010** [comment]
@Dhouglas 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding..
