### ISSUE TITLE
Wording and grammar errors

### ISSUE THREAD

**Issue by JC713** [FreeCodeCamp/FreeCodeCamp#1116]
Firstly, in the fourth paragraph of "Waypoint: Use the Bootstrap Grid to Put Elements Side By Side", I think the wording should be changed. I do not think "we" is appropriate because Bootstrap is not owned by FreeCodeCamp. I think "Note that in this illustration, we use the col-md-* class. Here, "md" means "medium", and "*" is a number specifying how many columns wide the element should be. In this case, we're specifying how many columns wide an element should be on a medium-sized screen, such as a laptop." should be rewritten like this: "Note that in this illustration, the col-md-* class was used. Here, "md" means "medium", and "*" is a number specifying how many columns wide the element should be. In this case, how many columns wide an element should be on a medium-sized screen, such as a laptop, is being specified."

This issue most likely continues in other waypoints so a fix will not be very quick.

Secondly, in the third paragraph of "Waypoint: Create a Custom Heading", there is an apostrophe error: "Most of Bootstrap's classes can be applied to a div element" should be "Most of Bootstraps' classes can be applied to a div element".

Sorry for the pickiness. I just think this is important to fix :).

**Comment by LumenTeun** [comment]
I had a bit of trouble reading the first part because of the many quotes, but I've edited this in a way I found appropriate and I will be creating a pull request shortly. I don't feel like looking through all the waypoints for similar errors, so if you find any, please post them here or in separate issues if appropriate.

Regarding your second concern, I'm going to have to disagree with you; since `Bootstrap` is singular, denoting possession would be done by putting the apostrophe before the `s`, even if the object is in plural.

**Comment by benschenker** [comment]
Seems to have been fixed in #1161
