### ISSUE TITLE
Google font text 'Lobster' doesn't turn blue like other CSS elements, in editor.

### ISSUE THREAD

**Issue by Pratikshagit** [FreeCodeCamp/FreeCodeCamp#11173]
#### Browser Information

* Google Chrome, Version : 53 
* OS X Yosemite 10.10.5
* Laptop

#### Your Code

```js
 <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  h2 {
    font-family: Lobster;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
 
 
```
#### Screenshot

![screen shot 2016-10-12 at 10 50 58 am](https://cloud.githubusercontent.com/assets/22732698/19314909/d2ffe010-9069-11e6-9476-9f6367bdeb8c.png)

**Comment by Pratikshagit** [comment]
Though, it doesn't affect the output. :)

**Comment by marhyorh** [comment]
It shouldn't be logged as an issue since you're just curious to know why the imported font don't change color in the editor. You should've just google that :smile:

**Comment by systimotic** [comment]
As far as I know, the color only changes for known values. Because you could give a font any name you want, there's no way to check whether the value is right or wrong. The highlighting will only work for the default values. This is common behavior across every editor I know about. I understand your confusion though, I hope you understand the reason behind it now.

**Comment by dhcodes** [comment]
I'm not able to replicate this. If I use your code @Pratikshagit, and change the color attribute in `.red-text` to blue instead of red, the text turns blue in the editor.

**Comment by Dayfiri** [comment]
@dhcodes He is probably setting color to `h2` element but it can't be outputted because `h2` has a class `red-text` that overrides any color value set in `h2` css element. By the way, code works fine.
![screenshot from 2016-10-13 15-42-23](https://cloud.githubusercontent.com/assets/16082563/19351468/3d572f5c-915c-11e6-84df-9c39bae4b19b.png)

**Comment by systimotic** [comment]
@Dayfiri @dhcodes I think Pratiksha is talking about the syntax highlighting of the font-family. `Lobster` stays white where `Monospace` turns blue/purple.

**Comment by dhcodes** [comment]
Oh, then yes, @systimotic's earlier statement is true. Also, non-standard fonts are typically written in quotes like `font-family: 'Lobster', serif;` where serif is standard, serves as a fallback font for Lobster, and doesn't need quotes.

**Comment by dhcodes** [comment]
Closing as resolved.

**Comment by Pratikshagit** [comment]
@systimotic and @dhcodes  ..thanks for your response, my confusion is clear now. :)

**Comment by martincossani** [comment]
it doesn't affect the output
