### ISSUE TITLE
Ability to show random codepens using "editor's fav list" for the different challenges

### ISSUE THREAD

**Issue by mpaluru** [FreeCodeCamp/FreeCodeCamp#11207]
**New Feature Request:**
Currently the example codepen shown for a particular Project is fixed/hard coded. It would be nice to have a "Editor's Favorite List" or a "Top Voting List" and pick one randomly from this list and present it on the Project page. This feature creates a healthy competition among the FCC users and it's quite motivating/encouraging/rewarding to aim for a good design.

Here is the conversation history:
**Justin Richardsson:**
Hey guys, random question. This very active camper in _____ is asking if we could use his wikipedia viewer as the example.
Personally, I like it a lot for being very clean. What do you say?

**Murali Paluru:**
another suggestion, we can have a list of “editor picks” for all of the challenges and they show up randomly for different people, that way others can also get benefitted/motivated?

**Justin Richardsson**
ahhh cool!
I really like the idea

**Jonathan:**
Yeah same!

**Justin Richardsson:**
having people sort of vote and compete to build better projects

**Jonathan:**
can you make an issue for that?

**Comment by abohay** [comment]
great dudes

**Comment by QuincyLarson** [comment]
Rather than build this into the challenges, I think we should have an "editor's picks" section somewhere else. 

Our goal is actually to use extremely bare-bones implementations of these projects. A lot of campers see polished versions and get intimidated. They will complain that they haven't been adequately prepared for these projects and that theirs looks vastly inferior.

I've opened a lot of issues for these here: https://github.com/FreeCodeCamp/CurriculumExpansion/issues

**Comment by abohay** [comment]
we can select from those who complete the full cirriculum
small number and it will be easy to pick

**Comment by QuincyLarson** [comment]
We can discuss building this feature later once we finish the curriculum overhaul. I am closing this issue for now. Thanks to @mpaluru for suggesting this cool idea :)
