### ISSUE TITLE
My Code is not Correct, But it passes the challenge

### ISSUE THREAD

**Issue by harshtomar6** [FreeCodeCamp/FreeCodeCamp#11201]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20args%20%3D%20Array.from(arguments)%3B%0A%20%20return%20args%5B0%5D.filter(function(val)%7B%0A%20%20%20%20return%20val!%3Dargs%5B1%5D%20%26%26%20val!%3Dargs%5B2%5D%20%26%26%20val!%3Dargs%5B3%5D%3B%0A%20%20%7D)%3B%0A%7D%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function destroyer(arr) {
  // Remove all the values
  var args = Array.from(arguments);
  return args[0].filter(function(val){
    return val!=args[1] && val!=args[2] && val!=args[3];
  });
}
destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
Function destroyer will only filter elements not more than 3.
What if a total of 5 arguments are passed to the function.

**Comment by erictleung** [comment]
@harshtomar6 thanks for the issue. I agree that you are able to brute force the algorithm like your code does. I'm not sure how you would test for any number of arguments possible because you would not only add tests, but you could always write to the tests. In other words, we could add five arguments and you could modify your code to just handle five. Why not six? It seems like a slippery slope to me.

So I would say to just keep the challenge the way it is. Firstly, the challenge already has a variety of input sizes (one through three). Secondly, this challenge is only in the Basic Algorithm Scripting section. There are more difficult algorithm challenges ahead.

@FreeCodeCamp/issue-moderators second opinions?

**Comment by Bouncey** [comment]
@harshtomar6 I second @erictleung 's comments on this

**Comment by abhisekp** [comment]
I once saw a nice talk about testing in which the speaker says about testing for
- 0 input (or no inputs)
- 1 input
- 3 inputs (small number of inputs) 
- 5 inputs (small number of inputs)
- 50 or more inputs (or similar large number of inputs)

Considering the limitation of the platform, **I suggest to at least add a 8 input test.**
But still as @erictleung says, one can bypass that by hard coding the cases.

**Comment by Bouncey** [comment]
## First-timers Only

Add another test case with a minimum of 8 inputs.

The code for this challenge is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/df2e2b55482741fe30c32bbab5538feb582117da/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L668)

Reading [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) will help you set up your testing environment.

If you run in to any issues, got to the [Contributiors Chat Room](www.gitter.im/freecodecamp/contributors).

Happy Coding :+1:
