### ISSUE TITLE
Cheating on challenge

### ISSUE THREAD

**Issue by 3rdp** [FreeCodeCamp/FreeCodeCamp#11232]
#### Challenge Name
[Reverse a string](https://www.freecodecamp.com/challenges/reverse-a-string)

#### Issue Description
You can cheat on the test like this. It shouldn't be like this, it makes the whole challenge pointless.

#### Your Code
```js
function reverseString(str) {
  if (str === 'hello') return 'olleh';
  if (str === 'Howdy') return 'ydwoH';
  if (str === 'Greetings from Earth') return 'htraE morf sgniteerG';
}
```

**Comment by erictleung** [comment]
Thanks for the issue. Yes, you are able to brute force this challenge. This is possible with a lot of the basic challenges, unfortunately. However, I'm not sure if there's any way around it. We could write many more tests but you can always brute force them. 

I think our philosophy is to keep the challenge tests open for you to know what to work towards. If you as a programmer cheat the challenge into brute forcing an algorithm like this, then you're ultimately cheating yourself. Thank you for the concern that this could happen but I'll be closing this issue because we aren't going to gain much from adding more tests and also this challenge is in the *basic* algorithms section. I hope you understand. Happy coding!
