### ISSUE TITLE
 Object lookup: What Did I do wrong ? 

### ISSUE THREAD

**Issue by cherokeestewarthart** [FreeCodeCamp/FreeCodeCamp#11237]
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  
  
  var lookup = {
    alpha : "Adams",
    bravo : "Boston",
    charlie:"Chicago",
    delta: "Denver",
    echo : "Easy",
    foxtrot : "Frank"
  };
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by Bouncey** [comment]
@cherokeestewarthart Please read the instructions again. 

If you are still stuck, use the `Help` button under the `Run tests` button. This will take you to a dedicated code help chat room.

GitHub issues are for issues with freeCodeCamp itself, not for code help. This is so that our issues log remains clear enough to read, and is not swamped with countless coding issues. 

I hope you understand.

Many thanks and Happy Coding! :+1:
