### ISSUE TITLE
ff

### ISSUE THREAD

**Issue by razaqfatiu** [FreeCodeCamp/FreeCodeCamp#11250]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr = "Hello World"; // Fix Me
myStr[0] = "H";


```

**Comment by Manish-Giri** [comment]
@razaqfatiu Your code isn't right. Since strings are immutable, you cannot change individual characters. Please read this instruction
>For example, the following code:
var myStr = "Bob";
myStr[0] = "J";
cannot change the value of myStr to "Job", because the contents of myStr cannot be altered

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you're still stuck on this.
