### ISSUE TITLE
Seek and Destroy. From the beginning the function destroyer has one argument to pass. But when we call this function we pass 3 values in it.  

### ISSUE THREAD

**Issue by Venikeee1** [FreeCodeCamp/FreeCodeCamp#11271]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript

function destroyer(arr,val1,val2,val3) {
  // Remove all the values
  //alert('sum=' + val1 +'another val2='+val2);
  function identic(value){

    return (value !== val1 );

  }
  function identic1(value){

    return (value !== val2 );

  }
  function identic2(value){

    return (value !== val3 );

  }


   arr = arr.filter(identic);
   arr = arr.filter(identic1);
  arr = arr.filter(identic2);
  return arr;

}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

**Comment by Dayfiri** [comment]
Your code works and it passes all the tests.
In your `destroyer` function you have 4 arguments and you don't need 1 of them.
`arr` is assigned to represent `[1,2,3,1,2,3]` array,
`val1` is assigned to represent number `2`,
and `val2` is assigned to represent number `3`.
`val3 is undefined` in this case.
You don't need `val3` and it's value is `undefined` but it passes the assignment because you've made 
a comparison `value !== val3` which is true because value is **not** undefined and it passes the test but all in all `val3` is undefined and does pretty much nothing useful in this assignment.

**Comment by karuppiah7890** [comment]
@Venikeee1 Your code will only work for 4 arguments max. The challenge actually wants you to create a function, which can tackle any number of arguments, other than the array, which is the first argument,

**Comment by Bouncey** [comment]
Passing this challenge in this way will no longer be possible after the next update. Please see #11235 for more details.

Maybe we can clear this up for campers by removing the `arr` argument in the function?

**Comment by Bouncey** [comment]
cc/ @FreeCodeCamp/issue-moderators 

Shall we remove the `arr` argument from the function, as a gentle nudge towards the `arguments` object?

**Comment by abhisekp** [comment]
:+1: campers then have to do the following
```js
var arr = arguments[0];
var restparams = [].slice.call(arguments, 1);
```

or that maybe pre-filled in the challenge seed.

**Comment by systimotic** [comment]
I think explicitly mentioning that you're supposed to use the arguments object would be sufficient. 
Currently, the link to the MDN page is there, but campers know from challenges before that you don't always _have_ to use the content from the links. Adding this to the description could help clear up a lot of confusion while still having campers come up with the actual solution themselves.
