### ISSUE TITLE
link-to-external-pages-with-anchor-elements (training info incomplete)

### ISSUE THREAD

**Issue by dt-freecodecamp** [FreeCodeCamp/FreeCodeCamp#11273]
#### Challenge Name

https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements

#### Issue Description

The supplied training info is incomplete.

#### Currently it states:
a elements, also known as anchor elements, are used to link to content outside of the current page.

#### Reality:
a elements can link to content inside or outside of the current page

**Comment by dhcodes** [comment]
Technically true, but the title of the challenge is called "Link to External Pages with Anchor Elements". Should we make a new challenge for internal links? There are a lot of questions in the chat about how to do internal anchor links. cc @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
Yeah that sounds like a good idea.

**Comment by HKuz** [comment]
I think that's a good idea. For what it's worth, we've been keeping track of reordering and new challenge suggestions for HTML and CSS over in [this curriculum expansion issue](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74). If a camper wants to create the new challenge, I can help get them set up for the format and requirements. Otherwise, I can create something when I get to that section.

**Comment by dhcodes** [comment]
@HKuz I'd like to learn how. I'll try to catch you on gitter tomorrow.

**Comment by HKuz** [comment]
@dhcodes excellent! I'll be around 👍

**Comment by Manish-Giri** [comment]
Sorry to spam, but @dhcodes once you get to know, I'll hit you up on Gitter to learn about this process.

**Comment by dhcodes** [comment]
Closing this as I'm writing a new challenge for the curriculum update. Thanks for the issue @dt-freecodecamp
