### ISSUE TITLE
Nesting an img to an a element

### ISSUE THREAD

**Issue by ccobol92** [FreeCodeCamp/FreeCodeCamp#11275]
#I've been trying to nest an img to an a element on lesson 29, I've asked to the community but they keep giving me the same answer.

This is the code I currently have:
<a href="#"><img src="https://bit.ly/fcc-running-cats" alt="Three kittens running towards the camera"></a>

Challenge Name
Turn an Image into a Link

* Browser: Safari
* Operating System: Mac 
* Mobile, Desktop, or Tablet: Desktop

 
<img width="1100" alt="screen shot 2016-10-19 at 10 15 06 am" src="https://cloud.githubusercontent.com/assets/22889512/19522374/f8b5d4b0-95e4-11e6-8292-51abcfade259.png">

**Comment by dhcodes** [comment]
@ccobol92 your approach is fine but you're using the example img instead of the one that was originally in the editor. Reset your code and you'll see that the nested img for the challenge has a different src than the one you are using. In the future, please consider asking for help in the chat room by clicking the help button on the challenge.
