### ISSUE TITLE
CSRF authentication problem

### ISSUE THREAD

**Issue by yasserhussain1110** [FreeCodeCamp/FreeCodeCamp#11325]
I tried to set up the FCC server locally in my machine, following the instructions given here - https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

> ...

edit(@berkeleyTrue):

Looks like #11058 is going to be delay a bit, so I've move this to confirmed again and added a help wanted tag.

The issue lies with a typo [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/index.js#L32)

csrfToken should be just token. Please check first that you can replicate the issue, then make your change. Then verify that the issue has been resolved.

**Comment by raisedadead** [comment]
@yasserhussain1110 just curios did you also run `npm run only-once` if first time or `node seed` to actually feed the database with the challenges?

**Comment by yasserhussain1110** [comment]
@raisedadead yup did that.

**Comment by raisedadead** [comment]
This is bit strange, mind sharing your environment details like Browser, OS, etc. Not sure, but I don't believe that completing the challenge should require any authenticated requests at all.

Which it seemingly needs in your case in the logs above (403).

**Comment by yasserhussain1110** [comment]
@raisedadead 
My dev environment -

OS - Ubuntu 14.04
Browser - Google Chrome.

**Comment by raisedadead** [comment]
Okay, I can reproduce this one. I am not sure of the reason yet. But, having said that its not breaking any functionality, that I could see. Or is it?

**Comment by systimotic** [comment]
I talked about this issue with @yasserhussain1110 on Gitter before. I thought I was doing the same thing, but I couldn't reproduce the issue. I now did manage to reproduce it. Here are my steps:
- Make sure you are logged in
- Go to any challenge

Both of these steps seem essential in order to reproduce. Although this is not breaking functionality, it does show an error toast to the user. If you load on a challenge page you will not immediately git this issue, only when you navigate to one.
I'm on Windows, with up to date dependencies. As far as I remember, I wasn't having this issue a week ago. It must've been introduced by a recent change.

Here's another interesting log output I have found that both Yasser and I get: 
```
304 GET 98.934 ms - /services/map;lang=en?_csrf=undefined&returnMeta=true
304 GET 100.827 ms - /services/user?_csrf=undefined&returnMeta=true
```
This log output is also there regardless of whether a user is logged in, and regardless of what page you're on. It only seems to be there on initial page load.

**Comment by shojaala** [comment]
304 GET 98.934 ms - /services/map;lang=en?_csrf=undefined&returnMeta=true
304 GET 100.827 ms - /services/user?_csrf=undefined&returnMeta=true

**Comment by Bouncey** [comment]
I can confirm also

Ubuntu 16.04
Node 6.4
Chrome latest

On completing a challenge, brownie points do not increment with xhr 304 in the console.

If I navigate back to the challenge,

`state.challengesApp.isComplete: false  // this is from memory, could be elsewhere in state`

Previous code is loaded from local storage.

**Comment by raisedadead** [comment]
I could reproduce this on OSX without a user login.

**Comment by Bouncey** [comment]
Blocking as resolved, depending on #11058

**Comment by BerkeleyTrue** [comment]
hmmm... waffle.io should move things with a PR to QA.

**Comment by BerkeleyTrue** [comment]
Looks like #11058 is going to be delay a bit, so I've move this to confirmed again and added a help wanted tag.

The issue lies with a typo [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/index.js#L32)

csrfToken should be just token. Please check first that you can replicate the issue, then make your change. Then verify that the issue has been resolved.
