### ISSUE TITLE
TaroEntarpries

### ISSUE THREAD

**Issue by chayano** [FreeCodeCamp/FreeCodeCamp#11338]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@chayano please fill in the issue template if you have a bug. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Closing as the title is not descriptive and the issue template is not filled out. Please comment on this issue if you really have an issue. Otherwise, please use the chat rooms for coding help. Happy coding!
