### ISSUE TITLE
System wants you to enter code incorrectly.

### ISSUE THREAD

**Issue by Sp00kyDan** [FreeCodeCamp/FreeCodeCamp#11343]
#### Challenge Name

Use Responsive Design with Bootstrap Fluid Containers

#### Issue Description

This particular page is requiring you to place your open `<div>` above style when it should be below it, and thus confused me as to why I wasn't allowed to run the test properly.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@Sp00kyDan what do you mean by "place your open"?

**Comment by Dayfiri** [comment]
@Sp00kyDan 
If you read the assignment again, you can see that what needs to be done is:
`we should nest all of **our HTML** in a div element with the class container-fluid.`
Note that we need to put our whole HTML code inside `<div class = "container-fluid></div>`.
**Not** including `<style></style>` tags because style is for CSS and we *only* need HTML. 
![screenshot from 2016-10-25 10-53-38](https://cloud.githubusercontent.com/assets/16082563/19679240/5ec2f5f6-9aa1-11e6-837a-e24252b701fd.png)
Look for comments in code `//opened div` and `//closed div`. Maybe this clears out your problem with the code. For future help with code, please refer to [FCC help page](https://gitter.im/FreeCodeCamp/Help). There are many people willing to help you out.
Happy coding :)

@dhcodes Code is alright and working. No problems with it.

**Comment by dhcodes** [comment]
@Dayfiri seems to have laid it out nicely. Please reopen if we misunderstood the issue.
