### ISSUE TITLE
Smallest Common Multiple's tests not validifying correct code

### ISSUE THREAD

**Issue by nikeinikei** [FreeCodeCamp/FreeCodeCamp#11362]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20return%20arr%3B%0A%7D%0A%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.

I thought I had this code right, but the tests tell me otherwise: https://gyazo.com/c45db2dadf635e4c7b095d44ec17f5fa. 

If I try to run this personally, (with nodejs or with https://repl.it/languages/javascript) I get the expected results.
https://gyazo.com/4fba823600954d883412961f139c0fd9 
https://gyazo.com/cc8b7a882e58af7a4a177ee9e32ccba8

My code:
```javascript
function smallestCommons(arr) {
	var divs =[];
	arr = arr.sort(function(a,b){
		return a-b;
	});
	for(var i = arr[0]; i<=arr[1]; i++){
		divs.push(i);
	}
	var smallestCommon;
	var counter = divs[divs.length-1];
	while(true){
		var temp = arr[1]+counter;
		var divides = true;
		for(var j = 0; j<divs.length; j++){
			if(temp%divs[j]!==0){
				divides = false;
				break;
			}
		}
		if(divides===true){
			smallestCommon = temp;
			break;
		}
		else{
			counter++;
		}
	}
	return smallestCommon;
}
```

**Comment by Dayfiri** [comment]
```
// noprotect
function smallestCommons(arr) {
    var divs =[];
    arr = arr.sort(function(a,b){
        return a-b;
    });
    for(var i = arr[0]; i<=arr[1]; i++){
        divs.push(i);
    }
    var smallestCommon;
    var counter = divs[divs.length-1];
    while(true){
        var temp = arr[1]+counter;
        var divides = true;
        for(var j = 0; j<divs.length; j++){
            if(temp%divs[j]!==0){
                divides = false;
                break;
            }
        }
        if(divides===true){
            smallestCommon = temp;
            break;
        }
        else{
            counter++;
        }
    }
    return smallestCommon;
}
smallestCommons([1,13]);
```
This worked for me in assignment. When I entered the code at first, with arr values of `1 and 13` it told me there might be infinite loop on `line 12` and that I should use `// noprotect` at the beginning of the code. After I did that, as you see in the code, the assignment let me pass.
![screenshot from 2016-10-25 09-54-47](https://cloud.githubusercontent.com/assets/16082563/19677337/264dc0f0-9a99-11e6-858f-043b3a5eb46a.png)

**Comment by Bouncey** [comment]
If you leave the function call at the bottom of your code, loopProtect will display an error to you in the output window and in the dev console. It also terminates your code from running to save you from infinite loops, and to give you a chance to check that the code is ok to run.

The thing that is triggering loopProtect is:
- A long running loop, I'm not sure of the exact timings, but if you are looping for more than 10-20 milliseconds, loopProtect tries to find out why and let you know
- It finds `while(true)` in your code and nothing to change this state anywhere. If your loop fails to hit the `break;` statements before all the memory is tied up in loops, the window will crash. 

Doing `smallestCommons([1, 23]);` with `// noprotect` runs for a very long time with your code ,I have managed to wright this reply waiting for it to return a number.

loopProtect is there to help us, and the challenges are seeded with a function call at the end so that loopProtect can do it's job.

You have solved the challenge, it's just that we have a nanny looking over your code for you to check that you are not going to break anything :wink:

**Comment by Bouncey** [comment]
The reason the last two tests didn't pass is because loopProtect terminated the function call (which then returned undefined), but it could't let you know about it because there was no function call in your editor window.

**Comment by Bouncey** [comment]
If I have not understood the issue properly, please feel free to open the issue again with more information

**Comment by nikeinikei** [comment]
Thanks it works now, gonna keep this in mind when I encounter a similar issue, for sure.
