### ISSUE TITLE
Element not detected as blue when written in blue? 

### ISSUE THREAD

**Issue by millennialtraveller** [FreeCodeCamp/FreeCodeCamp#11391]
I have been trying to pass this lesson multiple times and believe there is an error. I don't know why the blue is not turning up! 

My code is identical to the CSS style example:
<style> h2{color:blue;} CatPhotoApp</style>

**Comment by millennialtraveller** [comment]
<style> h2{color:blue;} CatPhotoApp</style>

**Comment by millennialtraveller** [comment]
I also used style tags open and closing,  but they're not showing up here. Cheers!

**Comment by Manish-Giri** [comment]
@millennialtraveller Your code is incorrect. Please visit the [help room](https://gitter.im/FreeCodeCamp/Help) if you need assistance on this.

**Comment by erictleung** [comment]
@millennialtraveller as it was pointed out, your code is wrong. Please reread the instructions for how to complete the challenge.

> Change your `h2` element's style so that its text color is red.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding! (FYI, the style tags don't show up because GitHub uses Markdown for its forms. HTML is rendered as HTML and style tags by themselves do not display anything, hence you don't see them.)

**Comment by millennialtraveller** [comment]
I was actually referring to the following challenge with the blue text.The red text was the previous one... I don't understand why the h2 element isn't reading blue when I literally copied the example. 


Thanks for the html explanation as well! 




Get Outlook for Android






On Thu, Oct 27, 2016 at 2:59 PM +1100, "Eric Leung" <notifications@github.com> wrote:












@millennialtraveller as it was pointed out, your code is wrong. Please reread the instructions for how to complete the challenge.




Change your h2 element's style so that its text color is red.




If you get stuck or have questions with a challenge in the future, please first ask questions to the Help Room. Happy coding! (FYI, the style tags don't show up because GitHub uses Markdown for its forms. HTML is rendered as HTML and style tags by themselves do not display anything, hence you don't see them.)
