### ISSUE TITLE
Incorrect Validation in Repeat a String Repeat a String Project

### ISSUE THREAD

**Issue by Iregress** [FreeCodeCamp/FreeCodeCamp#11412]
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=function%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20if(num%20%25%202%20%3D%3D%3D%200)%7B%0A%20%20%20var%20newStr%20%3D%20%22%22%3B%0A%20%20%20for(x%3D1%3B%20x%3C%3Dnum%3Bx%2B%2B)%7B%0A%20%20%20%20%20newStr%20%2B%3D%20str%3B%0A%20%20%20%7D%20%0A%20%20%20return%20newStr%3B%20%20%0A%20%7Delse%7B%0A%20%20%20return%20%22%22%3B%0A%20%7D%0A%7D%0ArepeatStringNumTimes(%22abc%22%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.

The scenario provided states that, if the 'num' variable is "not a positive number", you are to return an empty string. Such as in the code provided below.

When the code is validated, however, it is ignoring this requirement and to get credit for the project, you have to modify the code so that the str' variable is repeated 'num' times, whether 'num' is positive or negative.
 '
![repeat_a_string_issue](https://cloud.githubusercontent.com/assets/8534342/19786588/b46693a6-9c6c-11e6-9779-25f6b9a50973.png)

My code:
```javascript
function repeatStringNumTimes(str, num) {
  // repeat after me
 if(num % 2 === 0){
   var newStr = "";
   for(x=1; x<=num;x++){
     newStr += str;
   } 
   return newStr;  
 }else{
   return "";
 }
}
repeatStringNumTimes("abc", 3);

```

**Comment by Bouncey** [comment]
@Iregress 3 is greater than 0, so I don't understand what you mean by non-positive?

3 is an odd number though, and your code suggests that you are checking for even numbers...

**Comment by erictleung** [comment]
@Iregress thanks for the issue but I think you might be misinterpreting the instructions. The first test provides a positive number, 3. Three (3) is a positive number because it is greater than 0 on a number line. 

The last challenge test

> `repeatStringNumTimes("abc", -2)` should return `""`

is the test that actually points out the test of "if the 'num' variable is 'not a positive number', you are to return an empty string" that you point out because the provided number is -2, which is a negative number i.e. "not a positive number". Thus, the resulting output string is empty.

And as @Bouncey has pointed out, it looks like you may have mistaken even/odd with positive/negative.

Nonetheless, if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by Iregress** [comment]
You're 100% correct. I completely misinterpreted the requirements.

I was trying to figure out why such an obvious issue had not been
reported...now I know :/

Thank you.
