### ISSUE TITLE
Strange behaviour when submit the last Question of Quiz of Computer Basic Series

### ISSUE THREAD

**Issue by computerluca** [freeCodeCamp/freeCodeCamp#11445]
When I submit correctly the last question of a quiz of computer Basic Series It seems like It appears a question but this question disappear in seconds and it returns to new video of the series

**Comment by systimotic** [comment]
Hi @computerluca! I think this issue was missed because it was closed for a while, so it appeared down the list when you reopened it.
To get a couple things straight, is this the last challenge you're talking about? https://www.freecodecamp.com/videos/computer-security
When I complete this challenge, it works as expected.
Can you share the details of your browser, the exact challenge you're on, your operating system, and any other information you think could be useful in finding the cause of this bug?
A screencast of what's happening would also be very helpful, if you could do that, that would be great.
