### ISSUE TITLE
Symmetric Difference - incorrect test case

### ISSUE THREAD

**Issue by AlimacsMusings** [FreeCodeCamp/FreeCodeCamp#11514]
I feel that the following test case is incorrect.

sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]

Should this really return a 5 in the results if 5 is present in all 3 arrays?

**Comment by KonSal** [comment]
@AlimacsMusings please post an Issue on Github only if you need to address a specific bug and not get help for a challenge.

Apart from that, from the definition of Symmetric Difference, 5 should be indeed in the symmetric difference of the 3 arrays, so this is not an Issue and should be closed.

**Comment by erictleung** [comment]
@AlimacsMusings thanks for the issue, but the challenge test you pointed out is correct. Please take a look at the example in the instructions. It shows you why. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by mxschumacher** [comment]
Hey @erictleung and @KonSal  I believe @AlimacsMusings is on to something.

The explanation in  https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-find-the-symmetric-difference/301611 says that for odd numbers of arrays, elements that are present in all arrays will be part of the Symmetric difference. 

In my understanding, this is due to an implementation error: two arrays that include the same element are compared, so their symmetric difference doesn't include the element. Then this intermediary result is compared to the third array, which once again contains the element. It's the included in the final result.

From a set theory point of view this doesn't make any sense, if you compare the sets by hand, you wouldn't include an element that is present in all sets. **We have to compare all sets simultaneously**

The flaw becomes apparent, because there is no test case with an even number of sets where every set includes the same element - here it would suddenly not be included. This is nonsensical !

**Comment by mxschumacher** [comment]
Okay, I also see the discussion here: https://github.com/freeCodeCamp/freeCodeCamp/issues/12598
