### ISSUE TITLE
Bug in Sorted Union Challenge

### ISSUE THREAD

**Issue by lordcase** [FreeCodeCamp/FreeCodeCamp#11533]
#### Sorted Union
https://www.freecodecamp.com/challenges/sorted-union#?solution=function%20uniteUnique(arr)%20%7B%0A%20%20resArr%20%3D%20%5B%5D%3B%0A%20%20console.log(arr)%3B%0A%20%20for%20(var%20a%20in%20arr)%20%7B%0A%20%20%20%20for%20(var%20v%20in%20varr)%20%7B%0A%20%20%20%20%20%20if%20(!resArr.includes(arr%5Ba%5D%5Bv%5D))%20resArr.push(arr%5Ba%5D%5Bv%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20resArr%3B%0A%7D%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B%0A

#### Issue Description
In the test function calls you give separate arrays as arguments, so the function is called with varying number of arguments. Instead it should be called by grouping all the arrays in one single array (basically adding square breackets around them, inside the parentheses.

This is not cool: uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
This is cool: uniteUnique([[1, 3, 2], [5, 2, 1, 4], [2, 1]]);

Of course we could handle variable number of arguments but i think this is not scope of the challenge :)

Thanks,
Krisz

**Comment by dhcodes** [comment]
@lordcase The algorithms are designed to simulate programming challenges you might come across in real life. They are like puzzles. Whoever designed this challenge decided to do so by including the need to use arguments. This is an intermediate challenge and an earlier challenge (Seek and Destroy) in the basic section uses arguments. 

You're correct that it could be made easier via your suggestion but in real-world programming situations, you may not have that options.

**Comment by lordcase** [comment]
Oh, so it is on purpose :) Ok, sorry for being a smart alec then :) I was sure it's just a mistake as this challenge has had quite a few bug reports earlier.

Thx for the reply,

Best,
KRisz

**Comment by dhcodes** [comment]
No problem. Yes, I'm fairly certain it's that way on purpose, especially since one of the help links is to the MDN page on arguments. Closing as resolved.

**Comment by raphey** [comment]
I love this site! I hope I'm not out of line by trying to reopen something that's been closed, but I agree with Krisz that this ought to be tweaked. Part of this hinges on a question I'm unqualified to answer: for a function that takes a variable number of arrays, is it a common/advisable practice to give the function one single parameter "arr" that only refers to the first array?

My suspicion is that the answer is no, which would mean that something should be changed. Otherwise, after getting past the "gotcha" aspect, the learner is potentially left confused or mistaken about best practices.

Perhaps a better setup would be to write the function as `function uniteUnique() { }`. That would still require the learner to use arguments, and presumably that would also model a desirable way to set this up.

**Comment by lordcase** [comment]
Well to be honest, since I posted this question, i have stumpled upon many
instances on the official Mozilla Developer Network site where they do
exactly this. All the function callbacks of Array.prototype are explained
lie this. Stuffl like .map() and .reduce(). They take 3 or 4 arguments, but
in the exampes they usually use one.

So now i kinda understand better nad think that these gotcha experiences
are really helpful in keeping you sharp and showing you all the different
possibilities that you can use in your code.

2016-11-10 7:58 GMT+01:00 raphey <notifications@github.com>:

**Comment by raphey** [comment]
Interesting...I think that you're totally right about gotcha experiences being helpful. But the stuff on the MDN site is actually different, right? There, they list quite clearly which arguments are required and optional, and what the distinct role of each is. 

I'll leave it be, since it sounds like I'm on my own here, but I do think that it differs from all other challenges thus far. In addition to leaving the learner with some positive new knowledge relating to arguments/apply/reduce/etc, it also leaves the learner wondering if this was a trick or a demonstration of a counterintuitive but desirable way to set this up.

**Comment by lordcase** [comment]
i obviously agree with your second paragraph, as it is the reason i wrote
the "bug report", thinking it must be a mistake, after spending 10 minutes
on figuring out what the problem was with my solution :)

the most confusing thing is the one single parameter in the function
definition... I don't even know what to think anymore :) but it was a cool
challenge :)

2016-11-10 18:32 GMT+01:00 raphey <notifications@github.com>:
