### ISSUE TITLE
Even though answers are correct not even a single test case pass

### ISSUE THREAD

**Issue by gsb-gurpreet** [FreeCodeCamp/FreeCodeCamp#11539]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20arr%20%3D%20arr.sort((x%2Cy)%3D%3Ex-y)%3B%0A%20%20for%20(var%20i%20in%20arr)%20%7B%0A%20%20%20%20if%20(arr%5Bi%5D%20%3E%3D%20num)%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%7D%0A%7D%0A%0AgetIndexToIns(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2035)%3B%0AgetIndexToIns(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2030)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function getIndexToIns(arr, num) {
  arr = arr.sort((x,y)=>x-y);
  for (var i in arr) {
    if (arr[i] >= num)
      return i;
  }
}

getIndexToIns([10, 20, 30, 40, 50], 35);
getIndexToIns([10, 20, 30, 40, 50], 30);
```

**Comment by erictleung** [comment]
@gsb-gurpreet Thank you for reporting this issue. Your code doesn't complete follow all the requirements of the challenge. Please carefully reread the first paragraph of the challenge again.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by gsb-gurpreet** [comment]
Thanks for helping I found out and corrected what I was doing wrong.
