### ISSUE TITLE
Test done but cant move on

### ISSUE THREAD

**Issue by assanfulp** [FreeCodeCamp/FreeCodeCamp#11557]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3C!h1%3E%20comment%3E%0A%3Ch2%3E%20uncomment%3C%2Fh2%3E%0A%3C!p%3EHello%20Paragraph%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!h1> comment>
<h2> uncomment</h2>
<!p>Hello Paragraph>

Done with this assignment but just cant get a positive test run on it for me to move on to the nest test.

**Comment by systimotic** [comment]
Hi @assanfulp! Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
