### ISSUE TITLE
How i want to solve it Logical Or

### ISSUE THREAD

**Issue by Mohamedsalmaan** [FreeCodeCamp/FreeCodeCamp#11567]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20%0A%0A%20%20if%20(val%3E10%20%7C%7C%20val%3C20)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(21)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  

  if (val>10 || val<20) {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```

**Comment by erictleung** [comment]
@Mohamedsalmaan Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
