### ISSUE TITLE
Stacy bridges

### ISSUE THREAD

**Issue by robertxxx** [FreeCodeCamp/FreeCodeCamp#11579]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by sludge256** [comment]
Please provide details when posting issues. Edit your post before re-opening.

If you need help with one of the challenges click the help button and ask in the one of the [help rooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or visit the [forum](http://forum.freecodecamp.com/c/free-code-camp) instead of opening an issue on the repo. Thank you.
