### ISSUE TITLE
Bug. It does not recognize the changes made in the code

### ISSUE THREAD

**Issue by harimogili** [FreeCodeCamp/FreeCodeCamp#11608]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20%22%3Ca%20href%3D%5C%22http%3A%2F%2Fwww.example.com%5C%22%20target%3D%5C%22_blank%5C%22%3ELink%3C%2Fa%3E%22%3B%0A%0AmyStr%20%3D%20'%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%22%20target%3D%22_blank%22%3ELink%3C%2Fa%3E'%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "<a href=\"http://www.example.com\" target=\"_blank\">Link</a>";

myStr = '<a href="http://www.example.com" target="_blank">Link</a>';


```

**Comment by erictleung** [comment]
@harimogili Thank you for reporting this issue. Please read the instructions again.

> **Change the provided string** from double to single quotes and remove the escaping.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by harimogili** [comment]
I did what was required but the interface does not let me pass the test. Please check my answer and see if I have missed what was asked in the question

**Comment by harimogili** [comment]
I am not asking for help with coding. I am saying there is a bug in the interface that does not pass the run test even though you have made the correct changes to the given code.

**Comment by Dave1089** [comment]
@harimogili Hi, You are not supposed to create another line of code with correct solution, you just need to make changes in the line provided to you as @erictleung quoted

**Comment by harimogili** [comment]
ok that cleared it. Thanks!
