### ISSUE TITLE
Mistake in the function

### ISSUE THREAD

**Issue by aseelsky** [FreeCodeCamp/FreeCodeCamp#11615]
There is a mistake in the function, extra if statement exist.
https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
if (val) {
  if (val) {
    return "Yes";
  }
}
<!-- should be this way: -->
if (val) {
  return "Yes";
} 
 
```

**Comment by erictleung** [comment]
@aseelsky Thank you for reporting this issue. Yes, there should only be one `if` statement, which goes along with what is asked for in the instructions.

> **Combine the two `if` statements into one statement** which will return "Yes" if `val` is less than or equal to `50` and greater than or equal to `25`. Otherwise, will return `"No"`.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
