### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by kerenkayyy** [FreeCodeCamp/FreeCodeCamp#11625]
Challenge:using a CSS class to style an element

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Issue Description
I have tried and tried to make the text red but it didnt work even when i typed the code correctly.I alao consulted the forums and chats and they have said my code was correct

#### Browser Information

* Browser Name, Version: chrome
* Operating System: android
* Mobile, Desktop, or Tablet: mobile

#### Your Code

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by kerenkayyy** [comment]
Ohh I see,so how do I delete this?😂

**Comment by Bouncey** [comment]
@kerenkayyy Thanks for the issue, unfortunately this is a know bug in the current production site. Issue #7753 refers.

For some reason, some android devices use `&nbsp;` (non-breaking space) instead of the conventional space character. 

The good news is, the issue has been resolved in the next release of freeCodeCamp.

I'm really sorry for the time you have spent on this challenge.

In order for you to pass this challenge, you will need to remove all the spaces from between the `style` tags:

`<style>.red-text{color:red;}</style>`
