### ISSUE TITLE
Update Disable Code Autorun Wiki

### ISSUE THREAD

**Issue by cuent** [FreeCodeCamp/FreeCodeCamp#11636]
The information provided in the wiki ([wiki page](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Disable-Code-Autorun)) to disable autorun code is outdated. The information there suggests that the problem is solved by adding `run=disable`, but it doesn't work. In addition, that wiki page is deprecated since August 19.

**Comment by erictleung** [comment]
@cuent thanks for the issue. The extra code still works for me to stop the code from running. The Wiki suggests for `run=disabled` and even `run=disable` works as well, as shown in my screenshot. 

![image](https://cloud.githubusercontent.com/assets/2754821/20244113/ba75c9f6-a928-11e6-915a-c77b521f6408.png)

Can you copy-paste the URL that doesn't stop the code from working?

The fact that it hasn't been updated since August isn't too big of a deal because we don't suggest using it. We have moved the Wiki over to the [forums](https://forum.freecodecamp.com/c/wiki).

**Comment by cuent** [comment]
@erictleung  Yes, you're right. It works in all the other challenges, but I came up with a recursive solution in *Sum all odd fibonacci numbers* and the browser crashes. When you execute, you cannot prevent the browser of crashing. So, I tried copying and pasting the URL with the variable `run`, so it worked. The thing is that I have to write everything again and make use of an iterative solution. It should be explained in the exercise because many people is facing the same problem.

Finally, If anyone is facing the same problem, do not open the challenge because that web page will be frozen. Just copy and past this URL: 
`https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?run=disabled`
