### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by hneufville** [FreeCodeCamp/FreeCodeCamp#11638]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%20%20%0A%20%20.pink-text%20%7B%0A%20%20%20%20%20%20color%3A%20pink%3B%0A%20%20%20%20%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Can somebody kindly look at my code and see what's wrong with it?
My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
    
  .pink-text {
      color: pink;
    }

</style>

<h1 class="pink-text">Hello World!</h1>

```

**Comment by erictleung** [comment]
@hneufville Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by skywalker212** [comment]
@hneufville if you really want the answer, you forgot to clost the bracket in body

**Comment by hneufville** [comment]
Thanks!!!
