### ISSUE TITLE
TWITCHTV ISSUE "NOT FOUND" ERROR.

### ISSUE THREAD

**Issue by SylvioGiubine** [FreeCodeCamp/FreeCodeCamp#11649]
https://wind-bow.hyperdev.space/twitch-api
Its not working, "not found"

#### Challenge Name

Twitchtv not found.

https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description

{"status":404,"error":"not found"}

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by SylvioGiubine** [comment]
Follow the link: 
https://wind-bow.hyperdev.space/twitch-api

**Comment by raisedadead** [comment]
@Em-Ant mind taking a look? Refering : https://github.com/FreeCodeCamp/FreeCodeCamp/commit/ec782cb07101d26e65b0f46c054d9536ef8a6119

**Comment by Em-Ant** [comment]
@SylvioGiubine look at what I wrote as instructions on the main page of https://wind-bow.hyperdev.space/. To prevent abuses the app serves only the routes /users/:user, /channels/:channel, and /streams/:stream. For example if you try https://wind-bow.hyperdev.space/twitch-api/streams/RobotCaleb, You get correct results.

Anyway sometimes Hyperdev apps may be down because of too much traffic, or problems not related to client's implementation. Before reporting new issues please wait a  couple of hours and see if the server starts working again.

**Comment by raisedadead** [comment]
thanks @Em-Ant
