### ISSUE TITLE
cannot proceed! system shows red X for dodger-blue although all hew data correct.

### ISSUE THREAD

**Issue by martkar** [FreeCodeCamp/FreeCodeCamp#11648]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23ff0000%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%2300ff00%3B%0A%20%20%7D%0A%20%20.dodger-blue-text%20%7B%0A%20%20%20%20color%3A%20%23299BE4%3B%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23ffa500%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodger-blue-text%22%3EI%20am%20dodger%20blue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20orange!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36 OPR/41.0.2353.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #ff0000;
  }
  .green-text {
    color: #00ff00;
  }
  .dodger-blue-text {
    color: #299BE4;
  }
  .orange-text {
    color: #ffa500;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```

**Comment by erictleung** [comment]
@martkar Thank you for reporting this issue. Your code has a typo and that is preventing your from passing.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
