### ISSUE TITLE
I have problem with the course 119 - "Build a Personal Portfolio Webpage"

### ISSUE THREAD

**Issue by AndreiLuca99** [FreeCodeCamp/FreeCodeCamp#11646]
Hello, everyone.
I started the course 119, but I don't know how to start.
Can anyone give me any advice to help me finish this course?

**Comment by erictleung** [comment]
@AndreiLuca99 Thank you for reporting this issue. Here's [a forum post](https://forum.freecodecamp.com/t/feeling-overwhelmed-to-start-personal-portfolio/35998) that might help you get started.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
