### ISSUE TITLE
Can I export my freecodecamp stats using gitstats?

### ISSUE THREAD

**Issue by cmal** [freeCodeCamp/freeCodeCamp#11650]
https://github.com/IonicaBizau/git-stats provides us a way of exporting git stats for human visualization.
And I found that FreeCodeCamp also have some github-like stats visualizer.
So the question is : Can I export the git stats of FreeCodeCamp as a standard git stats output for the usage of git-stats?
Thanks!

**Comment by raisedadead** [comment]
Hi @cmal , thanks for the issue.

The short answer is that we do not have a mechanism right now to export stats for your streak.
Mainly because while UX wise it may look similar, the way we store the stats is not related to how git does it. So yeah we can't use the same approach.

BUT, we do have the stats. All this would need is an API that not just gives current brownie points (which is given by an "about user" api), but a more specific streak stats api.

That said it my be an interesting feature, but as you know with so many things going on including some great overhauls to the infrastructure this might take a while.

You are welcome though to keep discussion on here with ideas here and maybe solutions? Let us know if you need any help with that.

Hapy coding!

**Comment by cmal** [comment]
ok. Thanks for your answer. I'll soon take a deep search into your api and the git-stats, hopefully I will provide the feature for FreeCodeCamp which I loved so much.

**Comment by raisedadead** [comment]
@cmal awesome! looking forward to it. thanks. :smiley:
