### ISSUE TITLE
Target Elements by Class Using jQuery

### ISSUE THREAD

**Issue by deepakloyola** [FreeCodeCamp/FreeCodeCamp#11669]
#### Challenge Name
Target Elements by Class Using jQuery

#### Issue Description
First, let's target your div elements with the class well by using the $(".well") selector.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
  });
  $(".text-primary").addClass("animated shake");
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center well">jQuery Playground</h3>
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by Pasayadaan** [comment]
@deepakloyola The test is asking you to add classes "animated" and "shake" to the elements that have class "well".
Instead of "button" and ".text-primary" class mentioned in your code, you need to
1. get class "well". Hint: Note that, just like with CSS declarations, you type a . before the class's name.
2. then use .addClass() function to add the classes animated and shake.

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
