### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by RubanzaMichael** [FreeCodeCamp/FreeCodeCamp#11684]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

```

**Comment by systimotic** [comment]
Hi @RubanzaMichael! Welcome to Free Code Camp!
Your code appears to be working for me. Can you please clarify what your issue is?

**Comment by RubanzaMichael** [comment]
it seems that i can't

**Comment by systimotic** [comment]
@RubanzaMichael Can you elaborate please? What can't you do? Does the red cross not turn green when you click the button to run the tests? Does using a different browser solve the problem?

**Comment by RubanzaMichael** [comment]
I dont know what is the problem

**Comment by systimotic** [comment]
@RubanzaMichael Not knowing what the problem is, is no problem 🙂
You reported a bug. A bug is an issue report, indicating that you think there is something wrong with the way Free Code Camp works. If you believe this challenge doesn't work the way it's supposed to, this is the place to be. Always make sure to let us know what the problem is, what you expected it to do, what it did do, what the code you used was, and the specifics of your browser and operating system.
If you're looking for coding help, please use the "Help" button in the challenge instead. Always make sure to explain what you're trying to do and what you've tried so far.
If you're not sure if something is a bug or not, go to the help room first. If everyone else in there also thinks this is a bug, please report it.

Please let me know what you're next step is going to be.
Happy coding!

**Comment by raisedadead** [comment]
@RubanzaMichael here are the links to [Help Chat Room](https://gitter.im/FreeCodeCamp/Help), and the [forum](http://forum.freecodecamp.com/c/free-code-camp).

Please proceed as suggested by @systimotic.

Happy Coding.

**Comment by Davediw** [comment]
i am facing the same problem.

**Comment by queenly111** [comment]
Helloworld

**Comment by AmonRA40** [comment]
You should just add World, after Hello.
