### ISSUE TITLE
Your h2 should be red

### ISSUE THREAD

**Issue by Pantera09** [FreeCodeCamp/FreeCodeCamp#11694]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Ch2%20style%3D%22color%3A%20red%22%3ECatPhotoApp%3C%2Fh2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
copy n paste the code, substitute blue for red, error - your h2 should be red. 
reset code, my code goes away, but your h2 should be red remains. 
I have signed back in, logged off, reset, but I cannot progress I am locked in.

![2016-11-17](https://cloud.githubusercontent.com/assets/16930183/20413707/46b053b0-ace3-11e6-8607-37e1b71c273c.png)
My Code:
```html

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<h2 style="color: red">CatPhotoApp</h2>
```

**Comment by erictleung** [comment]
@Pantera09 Thank you for reporting this issue. You don't need a new element. Just change the exiting `h2` element.  Please reread the instructions.

> **Change your** `h2` element's style so that its text color is red.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
