### ISSUE TITLE
API for Image Search Abstraction Layer example being retired

### ISSUE THREAD

**Issue by danielehrlich** [freeCodeCamp/freeCodeCamp#11698]
Example for the Image Search Abstraction Layer I believe uses the [Bing.Search API](https://www.npmjs.com/package/bing.search). Unfortunately, [this API will be shutdown](https://datamarket.azure.com/dataset/bing/search) as of March 31st, affecting projects already submitted, and also eventually the example app itself.

#### Challenge Name
https://www.freecodecamp.com/challenges/image-search-abstraction-layer

#### Issue Suggestion
This example I think will need to be ported over to the new [Azure Cognitive Servers Bing API](https://www.microsoft.com/cognitive-services/en-us/bing-web-search-api/documentation). Perhaps this API should also be suggested on the assignment page?

**Comment by raisedadead** [comment]
thanks for the issue @danielehrlich and the alternate API as well. 
we might port the entire application over to HyperDev.

/cc @Em-Ant what do you think?

**Comment by Em-Ant** [comment]
The whole back-end curriculum will be ported on Hyperdev, and the microservices challenges will have slightly different requirements, in order to be automatically testable (see https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10816 for more details ).

About this particular challenge, I think we should recommend an free and reliable API in the project description. The new bing API looks like a valid option.

**Comment by systimotic** [comment]
This challenge has been removed in the beta, so I'm closing this issue.
