### ISSUE TITLE
What's wrong

### ISSUE THREAD

**Issue by davaahoo** [FreeCodeCamp/FreeCodeCamp#11714]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3Ekitty%20ipsum%20text%20aa%3C%2Fp%3E%0A%3Cp%3EKitty%20Ipsum%20text%20aa%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2>CatPhotoApp</h2>

<p class="red-text">kitty ipsum text aa</p>
<p>Kitty Ipsum text aa</p>

```

**Comment by erictleung** [comment]
@davaahoo Thank you for reporting this issue. Please reread the instructions. It asks for specific text to be in the new `p` element.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
