### ISSUE TITLE
Palindrome function doesn't run on one of the test case

### ISSUE THREAD

**Issue by aryan00011** [FreeCodeCamp/FreeCodeCamp#11729]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%0A%20%20let%20resultStr%20%3D%20str.replace(%2F%5B%5Ea-zA-Z%5D%2B%2Fg%2C%20%22%22).toLowerCase()%3B%0A%20%20let%20bool%20%3D%20true%3B%0A%20%20let%20numCompare%20%3D%20Math.floor(resultStr.length%20%2F%202)%3B%20%0A%0A%20%20for(let%20i%20%3D%200%3B%20i%20%3C%20numCompare%3B%20i%2B%2B)%20%7B%0A%20%20%09if(resultStr%5Bi%5D%20!%3D%3D%20resultStr%5BresultStr.length%20-%20(i%20%2B%201)%5D)%20%7B%0A%20%20%09%09bool%20%3D%20false%3B%0A%20%20%09%09break%3B%0A%20%20%09%7D%20%0A%20%20%7D%0A%20%20return%20bool%3B%0A%7D%0A%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!

  let resultStr = str.replace(/[^a-zA-Z]+/g, "").toLowerCase();
  let bool = true;
  let numCompare = Math.floor(resultStr.length / 2); 

  for(let i = 0; i < numCompare; i++) {
  	if(resultStr[i] !== resultStr[resultStr.length - (i + 1)]) {
  		bool = false;
  		break;
  	} 
  }
  return bool;
}




palindrome("eye");

```

**Comment by erictleung** [comment]
@aryan00011 Thank you for reporting this issue. Please read the `Note` in the challenge for why your code doesn't pass that one test.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
