### ISSUE TITLE
It has instructed me to create a style element using CSS that defines the h2 element as being blue. I have done this, but it says otherwise, which prevents me from fully completing my course. 

### ISSUE THREAD

**Issue by akebede295** [FreeCodeCamp/FreeCodeCamp#11722]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%20CatPhotoApp%20%0A%3C%2Fstyle%3E%0A%0A%3Cp%3E%0AKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%0A%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {color: blue;} CatPhotoApp 
</style>

<p>
Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.
</p>

```

**Comment by erictleung** [comment]
@akebede295 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
