### ISSUE TITLE
Round brackets "convertToF(30);" was not covered in previous tasks.

### ISSUE THREAD

**Issue by oswee** [FreeCodeCamp/FreeCodeCamp#11720]
Newbie cant figure out what is `convertToF(30);` and how to extract 30 as variable because it was not covered in previous tasks.

#### Challenge Name

https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20fahrenheit%20%3D%20b%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(30)%3B%0A%0Aa%20%3D%209%20%2F%205%3B%0Ab%20%3D%20convertToF%20*%20a%3B%0Ab%20%2B%3D%2032%3B%0A%0A

#### Browser Information

* Browser Name, Version: Chrome 54.0.2840.99 m
* Operating System: W10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

**Comment by no-stack-dub-sack** [comment]
@oswee Hey Owsee, do you use the Gitter chat rooms at all? Since this is not really a bug, a question like this might be better suited to the [Javascript Help](https://gitter.im/FreeCodeCamp/HelpJavaScript) FCC chatroom where you can expect more immediate feedback. 

But since you have asked - the value within the `()` on line 12, in this case `30`, is being passed into the `convertToF` function that is defined above. `convertToF(celsius)` is letting you know that the function expects to receive an argument that is a temp represented in C, and when you see `convertToF(30)` on line 12, that is calling or 'activating' that function with an actual value. So in this case, `celsius` is actually equivalent to `30`, but if you did `convertToF(60)` - `celsius` would be equivalent to `60` instead. Now you can operate on `celsius` as if it were an actual number. So if within the function you did: `fahrenheit = celsius * 2` (assuming you called the function with `convertToF(30)`), the function would return a value of `60`. 

Hope this makes sense and helps some. But yes, in the future - coding questions can be more quickly answered on the forum on in the Gitter chat rooms, while opening new issues should be reserved for bugs, for example if you've tested code elsewhere and it works, but does not work in FCC or pass FCC tests.

Thanks!
