### ISSUE TITLE
Returning Boolean Values from Functions

### ISSUE THREAD

**Issue by trinath503** [FreeCodeCamp/FreeCodeCamp#11727]
#### Challenge Name

Returning Boolean Values from Functions

#### Issue Description

return a===b showing error, 

#### Browser Information

its working only return a<b?true:false;
* Browser Name,chrome  Version: 54.0
* Operating System: Windows10
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
 
 return a==b;
 
```
#### Screenshot

![codecampd](https://cloud.githubusercontent.com/assets/19545163/20463706/2f8a302e-af5f-11e6-80ed-8e2e6e701e9e.png)

**Comment by Manish-Giri** [comment]
@trinath503 I believe your code should check if a number is **lesser** than another number, not test if they are equal, as is evident by the function name `isLess`.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first for help with challenges, in future!

**Comment by erictleung** [comment]
@trinath503 the `a === b` was just an example for how you can just return a boolean value without the if/else statements. This challenge requires you to think about the original code and modify it yourself. Please think about how you can make

```js
  if (a < b) {
    return true;
  } else {
    return false;
  }
```

into just a one line `return` statement. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
