### ISSUE TITLE
Clarify instructions for "Understand String Immutability"

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#11735]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr[0] = "H"; // Fix Me

```

## Current Instructions

The current instructions 

> Correct the assignment to `myStr` to achieve the desired effect.

are a bit vague, as pointed out [in this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9335#issuecomment-260647466).

Challenges should require some level of critical thinking but even so, these instructions are still too unclear.

## Suggested Change

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/395b62e4c67fd36aec459c5681783c3cea83a7e2/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1538) needs to be changed to something like this:

> Correct the assignment to `myStr` to achieve the desired effect that is intended by `myStr[0] = "H";`.

**Comment by mridulnagpal** [comment]
I am new to FreeCodeCamp can I work on this issue

**Comment by moi238** [comment]
Perhaps something like "Correct the assignment to myStr so that the myStr value is in correct English, by editing the code below the line"
I haven't got to this assignment yet, but I get the impression that the point is to test error correction through coding rather than just editing what is above the line to correct it.

**Comment by Jeff-Shapiro** [comment]
Thank you for reporting this issue. 

The point of this challenge is to teach about Immutability and what it is. By people making a mistake and trying to use an index assignment and finding they have the wrong answer is exactly what is aimed to be achieved. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by raisedadead** [comment]
Reopening per comment from OP.

**Comment by LoveRoseGoddess** [comment]
My issue with this problem is that it won't let me submit my answer and the to-do list isn't showing up. Is this a bug?

**Comment by raisedadead** [comment]
@LoveRoseGoddess please reach out to the [help chat](https://gitter.im/FreeCodeCamp/HelpChat), if it indeed is a bug, please log a fresh issue on the tracker.
