### ISSUE TITLE
CSS Add border test

### ISSUE THREAD

**Issue by kingmansah** [FreeCodeCamp/FreeCodeCamp#11734]
Give your image a border width of 10px.

#### Add Borders Around your Elements

https://forum.freecodecamp.com/t/challenge-add-borders-around-your-elements/16630

#### Issue Description
The problem I am having is that the run test button isnt working. Someone suggested perhaps instead of creat a whole new line for   shed everywhere shed ev , that perhaps I add it to the previous.

#### Browser Information

* Chrome, 54.0.2840.98: 
* Mac: 
* Laptop: 

#### 

 Give your image a border width of 10px.
       Give your image a border style of solid.
```js
 
 
 
```

**Comment by erictleung** [comment]
@kingmansah Thank you for reporting this issue. I see you've made and closed an earlier issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11732 and found your code there. Your code doesn't satisfy the challenge tests. Please read the instructions for how to complete the challenge.

> Create a class called `thick-green-border` that puts a 10-pixel-wide green border with a style of `solid` around an HTML element, and apply that class to your cat photo.

The forum post you've linked should help you complete the challenge.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
