### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by ahlanbkey** [FreeCodeCamp/FreeCodeCamp#11772]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0 Mobile/14B100 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style> h2 { color: blue; } </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@ahlanbkey Thank you for reporting this issue. You've removed too much of the code. Reset the code and read the instructions again. Please take a look at the help rooms for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by Azayzel** [comment]
You're suppose to leave the
``` 
<h2> CatPhotoApp</h2>
```
intact. They want you to remove the inline-styling and use CSS Selectors to target all <h2> elements.
