### ISSUE TITLE
Array with null values passing the testcases

### ISSUE THREAD

**Issue by PetrusStarken** [FreeCodeCamp/FreeCodeCamp#11798]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays) has an issue.

My solution for this algorithm is not correct yet, but the test cases are passing.

For this test:
```
["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]
```
Should return:
```
["pink` wool"]
```
I'm getting:
```
[null,null,null,null,null,null,null,null,null,null,"pink wool"]
```
My code:
```javascript

function diffArray(arr1, arr2) {
  var newArr = arr1.concat(arr2).sort();
  
  // Same, same; but different.
  newArr.filter(function(value, index, arr) {
    if (value === arr[index + 1]) {
      delete arr[index];
      delete arr[index + 1];
      return false;
    }
    return true;
  });
  return newArr;
}

diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);

```

**Comment by Bouncey** [comment]
We need to add checks for `newArr.length` to make sure the correct array is being returned

**Comment by Manish-Giri** [comment]
@Bouncey Can I take a crack at this?

**Comment by johnnyqbui** [comment]
@Manish-Giri Hey are you working on this? If not, I'm going for it.

**Comment by Manish-Giri** [comment]
@johnnyqbui  Yes, I am.

**Comment by wjhurley** [comment]
I believe where PetrusStarken is getting the array with nulls is from doing a console.log in the middle of the filter function:

`function diffArray(arr1, arr2) {
  var newArr = arr1.concat(arr2).sort();
  
  // Same, same; but different.
  newArr.filter(function(value, index, arr) {
    if (value === arr[index + 1]) {
      delete arr[index];
      delete arr[index + 1];
      console.log(newArr);
      return false;
    }
    return true;
  });
  return newArr;
}

diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);`

This is returning an array with null values because before the filter function completes, the array is still using the original indexes, so an array with only 'pink wool' leftover with an index of 10 leaves the JavaScript console to fill those empty slots with the 'null' value. I'm not sure why you would use delete statements inside of the filter function as the filter function is only meant to run a function on each index in the array and return either true or false, keeping the indexes that evaluated to true and removing the rest.

**Comment by PetrusStarken** [comment]
@wjhurley, the result I've posted here I copied from problem output, not from browser console. About the delete inside a filter, I was just testing, how I said, it isn't my final solution for this problem. 

If you execute this code at FreeCodeCamp, you'll see the result with null values, see:

![image](https://cloud.githubusercontent.com/assets/11821650/20884199/fb2a01a6-bad0-11e6-93a8-6f5b8789c650.png)

But, if you run this function at browser's console, the result was showing without null values, but the array length will be the original length.

![image](https://cloud.githubusercontent.com/assets/11821650/20884298/8ebdb94e-bad1-11e6-8c01-e39e69876cc4.png)

**Comment by wjhurley** [comment]
I'm sure the contributors could chime in on this, but I believe the delete statements are what is causing the null values in the array. The filter method should only return either true or false, it should not edit the array it is called upon.

**Comment by erictleung** [comment]
@wjhurley agreed. The `delete` statements seems to be causing weird output, along with it being within a callback function. I guess a fun "feature" of JavaScript 😄
