### ISSUE TITLE
A test case is wrong, right?

### ISSUE THREAD

**Issue by tidus89** [FreeCodeCamp/FreeCodeCamp#11793]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code gets every test case correct except one, "palindrome("1 eye for of 1 eye.") should return false".
But I think palindrome("1 eye for of 1 eye.") should return true. It's just as much a palindrome as "never odd or even" or "race car" if you take away the ones and the punctuation (which you are supposed to do). I really can't see why "1 eye for of 1 eye." is not a palindrome, so I think the test case is wrong.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  if(str.length <= 1) {
    return true;
  }
  
  var aString = str.replace(/[^a-zA-Z]+/g, "").toLowerCase();  
  var first = aString.substring(0, 1);
  var last = aString.substring(aString.length - 1);
  
  if(first !== last) {
    return false;  
  } else {
    return palindrome(aString.substring(1, aString.length - 1));
  }
}

palindrome("1 eye for of 1 eye");

```

**Comment by raisedadead** [comment]
Hi @tidus89 thanks, however for this challenge numbers are inclusive.
> You'll need to remove all non-**alphanumeric** characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

Unless any particular reason they can't be otherwise, the test case is correct, right?

**Comment by abhisekp** [comment]
@tidus89 as @raisedadead said, the test case is correct.

Please use [![**`FreeCodeCamp/HelpJavaScript`**](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/HelpJavaScript_⮭-006400.svg?style=flat-square&maxAge=2592000 "FreeCodeCamp/HelpJavaScript")](https://gitter.im/FreeCodeCamp/HelpJavaScript) room for help related to JavaScript challenges.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our `[full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)`.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by tidus89** [comment]
Ooo...I missed out on the numeric bit. Sorry!! Of course, in that case the
test case is absolutely correct!

Thanks, and again, sorry.

2016-11-24 14:32 GMT+01:00 Mrugesh Mohapatra <notifications@github.com>:
