### ISSUE TITLE
Can't proceed to the next step is there something wrong with my .smaller-image { width: 100px; }

### ISSUE THREAD

**Issue by SoniaAguilar** [FreeCodeCamp/FreeCodeCamp#11791]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js 
 <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
.smaller-image {
  width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

 
 
```

**Comment by raisedadead** [comment]
Have you reached out to the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge?

Which challenge are you talking about? Please specify the exact issue? If this is a challenge help please close the issue and seek assistance in the chat rooms and the forum.

Thanks and happy coding.

**Comment by abhisekp** [comment]
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our `[full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)`.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
