### ISSUE TITLE
Insufficient information in Aggregate exercise

### ISSUE THREAD

**Issue by sw-yx** [FreeCodeCamp/FreeCodeCamp#11822]
Challenge [Store Data in MongoDB](https://www.freecodecamp.com/challenges/store-data-in-mongodb) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```
var mongo = require('mongodb').MongoClient
var age = process.argv[2]

var url = 'mongodb://localhost:27017/learnyoumongo'
var doc = {firstName:process.argv[2],lastName:process.argv[3]}
mongo.connect(url, function(err, db) {
  if (err) throw err
  var parrots = db.collection("prices")
  parrots.aggregate([
     { $group: {
        _id: 'total' // This can be an arbitrary string in this case
       ,total: {
          $avg: 'price' // <---- I have NO IDEA what the name of the field is
        }
      }}
    ]).toArray(function(err, results) {
      // handle error
      if(err) throw err
      console.log(Number(results).toFixed(2))
    })
  db.close()
})
```

this is what i have. the problem is the instructions dont tell us what the name of the field is and there is no way to investigate what the schema of the collections is according to my googling around. please provide better instructions

**Comment by sw-yx** [comment]
(as in, i went with 'price' for now but it doesnt work. neither does 'prices' or '$price' or '$prices' or 'value')

**Comment by systimotic** [comment]
Hi @sw-yx!
This is from the description of the challenge:
> Say you have a collection named prices. Each price document is modeled like so:
```
   {
      "name": "Tshirt",
      "size": "S",
      "price": 10,
      "quantity": 12
      "meta": {
        "vendor": "hanes",
        "location": "US"
      }
    }
```
> In this exercise, we need to calculate the average price for all documents in prices
that have the size that will be passed as the first argument to your script.

It does show the price field. Because of the way aggregate works, you have to put a $ in front of the field name. I believe the challenge shows it sufficiently. You seem to have tried this as well, and it's the correct value.
The reason it doesn't pass for you is because the way you're logging it in the console is incorrect. I recommend logging `results` in it's entirety to find out what part you need to log.

Next time, please hit us up in the HelpBackend chat room first. 🙂

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!
