### ISSUE TITLE
Editor not working on local staging

### ISSUE THREAD

**Issue by dhcodes** [FreeCodeCamp/FreeCodeCamp#11823]
#### Issue Description
I'm experiencing an issue with my local install. I've rebased staging with a `git pull --rebase upstream staging` and ensured everything is installed by re-running the setup commands (`npm install`, `bower install`, etc.). When I run `gulp` the code-mirror editor is an input box (like a `textarea` and the Run Tests button doesn't work). Any ideas?

I asked in the Contributors room, but haven't heard anything.

#### Browser Information

* Browser Name, Version: Chrome 54.0.2
* Operating System: macOS Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![FCC screen](https://i.imgur.com/LG2fJFq.png)

**Comment by systimotic** [comment]
Hi @dhcodes!
I can not reproduce your issue (Windows 10, Firefox and Chrome, just rebased and updated). 
From what I know, CodeMirror creates a textarea by default, then converts that to the editor it displays (I believe what it's actually doing is even more magical, but I'm not 100% sure).
The fact that you're seeing the textarea with the code means that the JS is loaded. Could it be that the execution stopped at some point, because of an error? Does the console tell us anything?
I suspect this might have something to do with #11758, which updated `react-codemirror`. If that is what caused the issue though, I don't understand why I'm not able to reproduce.

**Comment by dhcodes** [comment]
Thanks @systimotic. I should've known to look for a recent update. Rolling back to react-mirror `0.2.6` fixed my local install. I then reinstalled `0.3.0` and it still worked. Weird. Closing for now.

**Comment by systimotic** [comment]
That is really weird 😕 I'm glad things are working for you again!
