### ISSUE TITLE
Challenge [Search and Replace]: Cannot assign to read only property '0' of string 'leaped'

### ISSUE THREAD

**Issue by vasadhananjay** [FreeCodeCamp/FreeCodeCamp#11834]
Challenge [Search and Replace](https://www.freecodecamp.com/challenges/search-and-replace) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.

Running the code below results in the following issue. I've validated that this function executes fine.

    TypeError: Cannot assign to read only property '0' of string 'leaped'

JSBin: http://jsbin.com/tegiwaseti/edit?html,js,output

My code:
```javascript

function myReplace(str, before, after) {
  // Capitalized
  if (before.charCodeAt(0) < 97) {
    after[0] = after[0].toUpperCase();
  }
  else {
    after[0] = after[0].toLowerCase();
  }
  str = str.replace(before,after);
  return str;
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```

**Comment by systimotic** [comment]
Hi @vasadhananjay! Thank you for reporting this issue.

You can not edit a string with that syntax (although it would be cool if you could). This challenge explains it https://www.freecodecamp.com/challenges/understand-string-immutability

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!

**Comment by vasadhananjay** [comment]
Agreed that it shouldn't work. But it shouldn't throw an error either should it?

**Comment by systimotic** [comment]
@vasadhananjay That's how Javascript works, we can't really influence it. 
I like that it throws an error. If it doesn't work, but it doesn't throw an error, it would take me way longer to figure out what went wrong.
I'm genuinely curious, what do you think it should do?
