### ISSUE TITLE
Bonfire: Exact Change suggestion

### ISSUE THREAD

**Issue by Chrysallis** [FreeCodeCamp/FreeCodeCamp#1186]
I suggest allowing the change array to return values in any order, or at least in reverse or original order. 

In its current form, it allows only reversed order which is counter-intuitive though slightly easier to implement. Since it's already reversed from the input order presumably for convenience, it seems reasonable that the order actually is not and should not be important.

**Comment by LumenTeun** [comment]
I'm on mobile, so researching this is a bit af a hassle, but if this should be implemented, I think either Chai.js' `assert.deepEqual` or `assert.sameDeepMembers` methods would be helpful.

**Comment by hando1818as** [comment]
Who is this send a pic

**Comment by 1hella** [comment]
I'm not quite sure what you're suggesting, @Chrysallis. The way it's set up now is it needs to be reversed from the original array, and only including the values being given as change. I'm sure it's set up that way as a bit of an extra challenge.

**Comment by LumenTeun** [comment]
Looking at the challenge I found this line: `Otherwise, return change in coin and bills, sorted in highest to lowest order.` so I'm sure it's intended.
It makes sense since cashiers tend to give the change back counting larger values first, and even if you end up with an array with the correct values in the wrong order, you should just be able to make a call to Array.prototype.sort() to fix that.

**Comment by benschenker** [comment]
Closing this as stale
