### ISSUE TITLE
Says theres spaces where there are no spaces. Am I missing something.

### ISSUE THREAD

**Issue by shanemmay** [FreeCodeCamp/FreeCodeCamp#11890]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cr%5C%5CSecondLine%5C%5C%5CnThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\r\\SecondLine\\\nThirdLine"; // Change this line



```

**Comment by erictleung** [comment]
@shanemmay Thank you for reporting this issue. Your code is incorrect and is preventing you from passing the challenge. It is more about the special characters than the spacing that is preventing you from passing. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
