### ISSUE TITLE
jou tube om in te loggen kan niet krijg mijn code niet van google telefoon code,s gr karel

### ISSUE THREAD

**Issue by kareltjen** [FreeCodeCamp/FreeCodeCamp#11894]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@kareltjen could you go into more detail about what you're experiencing. Logging into Youtube?

**Comment by systimotic** [comment]
The title of this issue seems like it is written in Dutch, which happens to be my native language.
Here's my attempt at translating the title: "I can't use YouTube to log in because I'm not getting my code" (I'm guessing this is a two factor authentication code).
Free Code Camp does not have an option to log in with a YouTube account. Perhaps we're talking about a Google account here?

@kareltjen I'm afraid we can't help out without more information. We'd appreciate if you could keep the conversation in English, so everybody knows what we're talking about. If you need help translating, feel free to hit me up on Gitter [@systimotic](https://gitter.im/systimotic)

(Translated back to Dutch) 👇 
@kareltjen Als je hulp nodig hebt bij het vertalen, kan je mij vinden op Gitter [@systimotic](https://gitter.im/systimotic)

**Comment by atjonathan** [comment]
@kareltjen, this issue is not related to FreeCodeCamp. This repository's issues are for bugs and feature requests only.
