### ISSUE TITLE
Refactor required for update of redux-form

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11919]
`redux-form v6.2.1` promises performance boost's amongst other things.

See #11876 for details

We need to refactor every instance of `redux-form` in our app. Handily, there is a [migration guide](http://redux-form.com/6.0.1/docs/MigrationGuide.md) here.

Many thanks and Happy Coding!

**Comment by BerkeleyTrue** [comment]
We will be moving away from redux-form in the future as the current version breaks with hot reloader.

**Comment by Bouncey** [comment]
There is a note on the redux-form site about hot reload, they have an issue
with v1.x but it is resolved with hot loader v3, we would need to wait for
v3 to come out of beta though.

**Comment by BerkeleyTrue** [comment]
Yes, that is what I remember as well. For now redux-form gets the job done in its current state. It's upsetting that they haven't fixed the issue with hot-reload v1 since this is the version that is still widely used. I'm not happy about that or the api of the new version so we will peg it on v5 for now.
