### ISSUE TITLE
Value doesn't change after the change in line has been done.

### ISSUE THREAD

**Issue by ppatel1604** [FreeCodeCamp/FreeCodeCamp#11939]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = myVar++;


```

**Comment by erictleung** [comment]
@ppatel1604 Thank you for reporting this issue. Your code is incorrect. Please read the note in the instructions for additional help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by ppatel1604** [comment]
@erictleung Yeah, I have noticed it afterward. I was not following the instructions properly.
