### ISSUE TITLE
issue on style blue

### ISSUE THREAD

**Issue by anweshd** [FreeCodeCamp/FreeCodeCamp#11956]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cstyle%3E%0A%20%20h2%20%20%7Bcolor%3Ablue%3B%7D%0A%20%20%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color: blue">CatPhotoApp</h2>

<style>
  h2  {color:blue;}
  </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@anweshd Thank you for reporting this issue. Your code does not meet the requirements for the challenge. Please read the instructions once more or head to the Gitter chat rooms for more help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by AngelC88** [comment]
this is my code and its not working as suggested on gitter
<style>
      <h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by AngelC88** [comment]
this is my code and its not working as suggested on gitter
<style>
     h2  {color:   blue;}
</styles>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff</p>

**Comment by AngelC88** [comment]
this is my code and its not working as suggested on gitter.
`<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>`

**Comment by homedefense** [comment]
<style>
  
  h2 {color: blue;}
  
</style>

the blue color is not working...how can I proceed? please let me know thank you.
