### ISSUE TITLE
1 eye for of 1 eye. it is a palindrome, test mark it as false.

### ISSUE THREAD

**Issue by Crizstian** [FreeCodeCamp/FreeCodeCamp#11957]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20pattern%20%3D%20%2F(%5CW)*(%5Cd)*(_)*%2Fg%3B%0A%20%20var%20rep%20%3D%20str.replace(pattern%2C%20'').toLowerCase().split('')%3B%0A%20%20%0A%20%20for(var%20i%20%3D%200%2C%20j%20%3D%20rep.length%20-%201%3B%20i%20%3C%20rep.length%3B%20i%2B%2B%2C%20j--)%20%7B%0A%20%20%20%20if(rep%5Bi%5D%20!%3D%3D%20rep%5Bj%5D)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  var pattern = /(\W)*(\d)*(_)*/g;
  var rep = str.replace(pattern, '').toLowerCase().split('');
  
  for(var i = 0, j = rep.length - 1; i < rep.length; i++, j--) {
    if(rep[i] !== rep[j]) {
      return false;
    }
  }
  
  return true;
}



palindrome("1 eye for of 1 eye.");

```

**Comment by erictleung** [comment]
@Crizstian Thank you for reporting this issue. `1 eye for of 1 eye` is not a palindrome.

```js
var notPalindrome = "1 eye for of 1 eye";
notPalindrome.split("").reverse().join(""); // Returns "eye 1 fo rof eye 1"
```

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by Crizstian** [comment]
My mistake, i didn't read well the exercise, in the regex pattern i was taking out the numbers to.

with the numbers included in fact is not a palindrome.

thanks.
