### ISSUE TITLE
Bootstrap Grid to Put Elements Side by Side question

### ISSUE THREAD

**Issue by wheelhot** [FreeCodeCamp/FreeCodeCamp#11966]
Challenge [Use the Bootstrap Grid to Put Elements Side By Side](https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

> The tutorial did mention that col-xs-4 needs to be in a div but I can't find any sources on why placing 'col-xs-4' into the button class doesn't work? Why must `<button>` be nested in a `<div>` for 'col-xs'-4' to work?

Thanks

My code:
```html

<!--This works-->
  <div class="row">
    <div class="col-xs-4"><button class="btn btn-block btn-primary">Like</button></div>
    <div class="col-xs-4"><button class="btn btn-block btn-info">Info</button></div>
    <div class="col-xs-4"><button class="btn btn-block btn-danger">Delete</button></div>
  </div>

<!--This doesn't work-->
  <div class="row">
    <button class="btn btn-block btn-primary col-xs-4">Like</button></div>
    <button class="btn btn-block btn-info col-xs-4">Info</button></div>
    <button class="btn btn-block btn-danger col-xs-4">Delete</button></div>
</div>

```

**Comment by erictleung** [comment]
@wheelhot Thank you for reporting this issue. Great question. Yes, you can add grid classes to buttons. However, in the context of the challenge, we ask to nest your `<button>` element in `<div>` elements because generally, you will probably be working with `<div>` elements that will vary in size, rather than whole buttons. If you have other questions, please ask within one of the Gitter chat rooms.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by wheelhot** [comment]
@erictleung I did try adding grid classes to button but it doesn't line up the buttons in a horizontal row as opposed to placing it in individual div `<div>`. And as mentioned, I tried searching around on why doesn't col-xs-4 work if placed in a button vs in its own div while having the button nested but to no avail.
 
See line 38-40
![screen shot 2016-12-08 at 2 38 28 pm](https://cloud.githubusercontent.com/assets/12379413/21000164/3d565bf8-bd54-11e6-951c-d1258f4804a5.png)
![screen shot 2016-12-08 at 2 39 33 pm](https://cloud.githubusercontent.com/assets/12379413/21000163/3d062ffc-bd54-11e6-818d-8b6531390e9e.png)

I did asked before on Gitter and some people asked me to post it up as an issue at GitHub
