### ISSUE TITLE
Falsy bouncer

### ISSUE THREAD

**Issue by frogo123** [FreeCodeCamp/FreeCodeCamp#11976]
Hi, below is my code for the Falsy Bouncer project which returns the expected value into the black console screen. 

The problem I have is that all the challenges fail except the (["a", "b", "c"]) one which out of the 4 is the only one that returns all the original values.

I have spent some time on the Falsy Bouncer and I'm unsure what to do next as the code I have returns the answers I been looking for so I would appreciate any advie.
Thanks
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don%27t%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20if%20(arr%20!%3D%3D%20false)%7B%0A%20%20return%20arr%3B%0A%20%20%7D%0A%7D%0Avar%20items%20%3D%20%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D%3B%0A%20items.filter(bouncer)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  if (arr !== false){
  return arr;
  }
}
var items = [7, "ate", "", false, 9];
 items.filter(bouncer);
```

**Comment by erictleung** [comment]
@frogo123 Thank you for reporting this issue. You code is incorrect and doesn't satisfy the requirements of the challenge. Hint: ask yourself, do you understand what a "falsy" value is in JavaScript?

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
