### ISSUE TITLE
Heroku deploy fail - GitHub Wiki Article is Deprecated

### ISSUE THREAD

**Issue by JohnnyBizzel** [FreeCodeCamp/FreeCodeCamp#11980]
#### Challenge Name
https://www.freecodecamp.com/challenges/url-shortener-microservice

#### Issue Description
After using these  instructions https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Heroku-Deployment-Guide I get:
"Heroku | Welcome to your new app!

Refer to the documentation if you need help deploying."

#### Your Code
https://github.com/JohnnyBizzel/url-shortener-jb

**Comment by JohnnyBizzel** [comment]
The bug is you need to update your instructions!

**Comment by raisedadead** [comment]
@JohnnyBizzel apologies the wiki is deprecated. Please head over to our forum:
https://forum.freecodecamp.com.

You can look for updated guides to deploy, and also seek assistance from fellow campers on this.

~~~
@Rafase282 we need a bit of a help here, the wiki is deprecated, but @QuincyLarson had to keep it on because we kept getting requests from users with broken links.

At this point, we need to update the GitHub wiki's pages to have a notice on all of its pages. 
I am not sure if this can be done via a Script. But I would like to try a hand at it, or would love someone comes up with one. 

Also updating the Main page on the wiki to a notice and link would be nice.

Please advise.

**Comment by QuincyLarson** [comment]
@raisedadead OK - I've added this warning, which will show up on every page of the GitHub wiki: https://forum.freecodecamp.com/c/wiki
