### ISSUE TITLE
Divide one Decimal by Another with JavaScript

### ISSUE THREAD

**Issue by alexalexson143** [freeCodeCamp/freeCodeCamp#11986]
Challenge [Divide one Decimal by Another with JavaScript](https://www.freecodecamp.com/challenges/divide-one-decimal-by-another-with-javascript#?solution=%0Avar%20quotient%20%3D%200.0%20%2F%202.0%3B%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var quotient = 0.0 / 2.0;


```

Problem is solved by leaving the original code as is and adding:

```javascript
quotient = 2.2;
```

I believe this should not be a valid answer, unless this is intended?

**Comment by laukcoder** [comment]
It is asking you to use the '/' operator. By adding quotient = 2.2; underneath the already given code, you are  assigning the value of 2.2 to quotient. This means that when your code is checked for the correct answer, 2.2, it will pass. The platform checks to make sure you arrived at the correct answer, it doesn't check to make sure that you arrived there the way that you were intended to. quotient is checked for its value and the value you assigned matches the value it is looking for, so you pass. It also appears to check that there exists a '/' operator in your code somewhere. It doesn't seem to check that it is used to get the value you are submitting. I would recommend trying to do the puzzle in the way it asks you too because you learn more that way.

**Comment by alexalexson143** [comment]
Thanks for the reply laukcoder.

I agree that learning should be the number one priority in doing these exercises. Initially, I couldn't figure out how to return the value 2.2 from 0.0 / 2.0 (lol) so I just tried assigning 2.2 to the variable and I was surprised that it worked. Anyway I know this is trivial, just wanted to point it out anyway.

**Comment by dhcodes** [comment]
I think we can write the tests in a way that require the camper to use the `/` for division. Confirmed this is a bug on staging too. I'll take this one.

**Comment by rmdawson71** [comment]
On the Beta site, I can not get the 3rd test to pass.  See the screenshot.
![image](https://cloud.githubusercontent.com/assets/5313213/22447543/ef5bf1be-e707-11e6-8185-1455141bdd4a.png)
