### ISSUE TITLE
Code is correct but freecodecamp is not accepting it

### ISSUE THREAD

**Issue by nitdutt** [FreeCodeCamp/FreeCodeCamp#11997]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%20%0A%20%20%20var%20newStr%3Dstr.replace(%2F%5B%5EA-Z0-9%5D%2Fig%2C%20%22%22).toLowerCase()%3B%0A%20%20var%20revStr%3DnewStr.split(%22%22).reverse().join(%22%22)%3B%0A%20%20if(revStr%3D%3D%3DnewStr)%0A%20%20%20%20return%20%22true%22%3B%0A%20%20else%20%0A%20%20%20%20return%20%22false%22%3B%0A%7D%0A%0A%0A%0Apalindrome(%22five%7C%5C_%2F%7Cfour%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
This code accurately checks whether a string is palindrome or not. Even the inputs mentioned there are being correctly evaluated.
![capture](https://cloud.githubusercontent.com/assets/16055207/21078425/a2b27a76-bf94-11e6-9db9-f82901e7c09c.JPG)

My code:
```javascript

function palindrome(str) {
  // Good luck!
   
   var newStr=str.replace(/[^A-Z0-9]/ig, "").toLowerCase();
  var revStr=newStr.split("").reverse().join("");
  if(revStr===newStr)
    return "true";
  else 
    return "false";
}

palindrome("five|\_/|four");

```

**Comment by erictleung** [comment]
@nitdutt Thank you for reporting this issue. Hint: check your return type. Please check the help chat rooms for more help. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
