### ISSUE TITLE
Why it is showing undefined  error  with var c ?  plz  help 

### ISSUE THREAD

**Issue by krishgarg** [FreeCodeCamp/FreeCodeCamp#12020]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%205%3B%0Avar%20b%3D%2010%3B%0Avar%20c%20%3D%20%22%20I%20am%20a%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a = 5;
var b= 10;
var c = " I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by erictleung** [comment]
@krishgarg Thank you for reporting this issue. Your code is incorrect. Hint: check your spacing.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
