### ISSUE TITLE
Counting Cards challenge - code passes individual tests but does not pass challenge

### ISSUE THREAD

**Issue by dsottimano** [FreeCodeCamp/FreeCodeCamp#12021]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards) has an issue.

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.

If I test an individual line from the testing requirements, like cc(10);cc('J');cc('Q');  cc('K');cc('A'); , my code returns the correct result:  "-5 Hold", but I can't pass the challenge.

My code:

```js
var counter = 0;
var advice;

function cc(card) {
  
  
  // Only change code below this line
  
    if (card > 1 && card < 7) {
      counter ++;
      

    } else if ( card == 10 || card =="J" || card =="Q" || card =="K" || card =="A") {
      counter --;

    } 

  console.log(" this is my counter:" + counter + " my card is: " + card + " I should be: " + advice );
  
  
    if (counter > 0) {
      advice = " Bet"; 
    return counter + advice;
    } else {
       advice = " Hold";
    return counter + advice;
    }
  
  
 
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
//cc(2);cc(3);cc(4);cc(5);cc(6);
//cc(7);cc(8);cc(9);
cc(10);cc('J');cc('Q');  cc('K');cc('A');
//cc(2);
//cc(7);cc('Q');cc(8);cc('A');
//cc(2);cc(2);cc(10);
```

**Comment by erictleung** [comment]
@dsottimano Thank you for reporting this issue. Hint: please adhere to the editor comments such as `// Only change code below this line` and you should only have one global variable `count`. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by dsottimano** [comment]
@erictleung thanks for responding. I made the changes you've recommended (removed 2nd global variable, changed other global variable back to count vs counter), commented out the test lines at the end, removed the console.log line and it passed. Weird.

**Comment by jbbpatel94** [comment]
var count = 0;

function cc(card) {
  // Only change code below this line
  if(card==2 || card==3 || card==4 || card==5 || card==6){
  count++;
  return count +" Bet";
  }
  if(card==10 || card=='J' || card=='Q' || card=='K' || card=='A'){
  count--;
  return count+" Hold";
  }
   if(card==7 || card==8 || card==9){
 
  return count+" Hold";
  }
 
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');
