### ISSUE TITLE
Storing values with the assignment operator

### ISSUE THREAD

**Issue by Sungho1214** [FreeCodeCamp/FreeCodeCamp#12060]
#### Storing values with the assignment operator
https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator

#### Issue Description
I just answered to the question, but it was incorrect. I still don't understand why my code does not work no matter what I tried.

#### Your Code
var a = 7;
var b = 2;

b = a;

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/23018910/21237767/53ed3452-c2ce-11e6-8028-d744a8598aba.png)

**Comment by dhcodes** [comment]
@Sungho1214 please ask for code help in the chat room, by clicking the Help button on the challenge. In this case, it's because you need to assign the value of `7` to variable `a` below the line that read `//Only change code below this line`. The goal of the challenge is to show you can reassign a variable after it's been created.
