### ISSUE TITLE
Type error: arr.shif is not a function?

### ISSUE THREAD

**Issue by sltcode** [FreeCodeCamp/FreeCodeCamp#12061]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr%20%3D%20arr.push(item)%3B%0A%20%20var%20removed%20%3D%20arr.shift()%3B%0A%20%20return%20removed%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I had the following issue showing arr.shift is not a function. but .shift() is a standard array function. So, I believe this is a bug, right?

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  arr = arr.push(item);
  var removed = arr.shift();
  return removed;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```
![screenshot 4](https://cloud.githubusercontent.com/assets/24396343/21239958/308a177e-c2d7-11e6-9ea3-ac9d695af78e.png)

**Comment by Bouncey** [comment]
@sltcode you are reassigning arr to something other than an array, and `.shift()` will only work on arrays. Read [this article on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/push), paying particular attention to the return value of the `.push()` method.

Closing because this is for code help.

If you have any further questions, please you the `Help` button in the challenge that you are stuck with. :+1: 

Happy Coding!

**Comment by sltcode** [comment]
@Bouncey Thank you for pointing that out, I initially thought it was a bug. I got it now!
