### ISSUE TITLE
Solution accepted does not correctly account for case where num < arr[0]

### ISSUE THREAD

**Issue by aliceafriedman** [FreeCodeCamp/freecodecamp#1206]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue.

The Bonfire will accept a solution as correct that doesn't work in cases where num < arr[0]. 

This accepted solution will give you the wrong answer in such a case (1, instead of 0).

![screen](https://cloud.githubusercontent.com/assets/11845817/8513368/1fcc133e-2336-11e5-8214-c74a2279184e.png)

**Comment by benmcmahon100** [comment]
This is not a bug as mentioned in issue #1205 . For example let's examine the initial test. We have an array [40, 60] the challenge asks where should the number logically be placed. In this case the answer is [40, 50, 60] 50 has been put at the index 1. If what you are saying is true that the answer should be 0 then the array looks like this [50,40,60].(https://en.wikipedia.org/wiki/Zero-based_numbering) Please in future check these kinds of problems in  https://gitter.im/FreeCodeCamp/Help or previous (closed and open) pull requests. We're just trying to keep the number of unnecessary pull requests down as they obscure larger bugs. Thanks you though for point out that maybe the challenge isn't explained enough! If you have any other issues with the challenge my explanation please do not hesitate to ask! :relaxed:

**Comment by aliceafriedman** [comment]
Hi Ben, 

I'm not sure what I'm saying is the same... 

All of the tests in this challenge give a number where the argument is greater than at least one of the numbers in the array. 

It's possible to write a code that successfully meets all the tests (like in my example), but will give an incorrect answer if "num" input into the function actually does belong at index 0 (i.e. where ([10,20,30],5)). 

I guess that's not really a bug, but it might make sense to also test for cases where the second argument should be inserted at the beginning or end.

**Comment by benmcmahon100** [comment]
Ah yes i see what you mean. I think you're the first person I've every seen to use do while loops in js let alone for that bonfire! :p I will go and see if this is already patched in the next update or otherwise I'll go and create a fix myself. Thank you for highlighting this problem with the bonfire! I'll be sure to post back here once if find / create the fix.

**Comment by aliceafriedman** [comment]
Cool! :)

**Comment by benmcmahon100** [comment]
The issue is related to the fact that a do while executes at least once so at the very start your do causes num to be 1. This the difference between the do while and all other loops which is why the error never showed up. So any other loop or recursion or even setting num to -1 would make your code satisfy the 0 index issue but I wouldn't recommend it! Over it's just a quirk of using do while.
