### ISSUE TITLE
All answers are already set.

### ISSUE THREAD

**Issue by taylerRamsay** [FreeCodeCamp/FreeCodeCamp#12075]
Not sure if this is the write way to submit this but all the answers are already filled in on the last 6 tests

**Comment by raisedadead** [comment]
@taylerRamsay thanks.

Which challenges are we talking about? Please do fill the Issue Template that was presented when you opened this issue.

- Is this shared computer, and someone already solved the challenges? We store the solutions in cookies which is why it may be filled.
- Have you visited someone's solution page? In that case, it may be filled.

Try cleaning up your cache and cookies for FreeCodeCamp.com on your browser. This may resolve your issue.

**Comment by QuincyLarson** [comment]
@raisedadead thanks for closing this. I was literally about to do so myself :) 

@taylerRamsay if you can't figure it out, you can manually fix your browser by deleting the solution from your browser's local storage: http://forum.freecodecamp.com/t/clear-specific-values-from-your-browser-local-storage/19128
