### ISSUE TITLE
Javascript "Write Reusable JavaScript with Functions" Not accepting answer

### ISSUE THREAD

**Issue by soomitt** [FreeCodeCamp/FreeCodeCamp#12077]
#### Challenge Name: Write Reusable JavaScript with Functions

https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20ourReusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AourReusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction()%20%7B%0A%20%20colsole.log(%22Hi%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B

#### Issue Description

It will not accept the answer.

#### Browser Information

* Browser Name, Version: Chrome, Version 55.0.2883.95 (64-bit)
* Operating System: macOS
* Mobile, Desktop, or Tablet: MacBook Pro

#### Your Code

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  colsole.log("Hi World");
}

reusableFunction();

#### Screenshot

![12-16-2016 fcc 166](https://cloud.githubusercontent.com/assets/24259767/21273541/0aaf1c0a-c392-11e6-8b5d-db4081224b33.png)

**Comment by raisedadead** [comment]
You have a typo in your code.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by erictleung** [comment]
@soomitt Thank you for reporting this issue. Hint: you have a typo.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by meizaifeng** [comment]
```
function reusableFunction(x, y) {
  var sum = x + y;
  console.log("Hi World");
}

reusableFunction();
```
