### ISSUE TITLE
Over Full Stack Curriculum (following advice benmcmahon100)

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#1210]
Comments about a discussion over the curriculum
participants: evaristoc, Lightwaves,  benmcmahon100

After following a discussion in Gitter commenting my personal experience with the FCC education programme, here additional suggestions to the curriculum:
Personal experience so far (certain level of preliminary experience with programming but not with web-dev; previous training with nodejs and express (backend)):
--- focus on FCC seems to be on front-end at the moment
--- finishing the ziplines could not be enough to prepare for the full-stack
--- the suggested backend training seemed to me poor to get into the full-stack level
--- all required basic topics are there but scattered
--- information on Internet consisting in many possible sources and code styles that could bring some confusion
--- in Lightwaves' words: "gap between backend and front-end development: how do you make an all encompassing full stack solution that uses your front-end knowledge to create a view that consumes a backend api"
--- it took me 3 weeks to realise that I was doing wrong with all my basejump projects because the lack of guidance and help

Suggestions:
--- in general, avoid frustration by encouraging success: leave people to select the path that suit a fast development whenever possible;  encourage a step-by-step development; also, work assertively on the expectations of the participants (for example so far, no-one understand the 800 hours learning time); at this stage, better guidance with introduction about the theory is my opinion required but the emphasis should be over the how to do things rather than the why, as the profile of the participants is in general not of a CS, but more technical...
--- introduction about web development theory and models
--- introduction about what frontend, backend and full-stack development involves; an introduction of the technical description and requirements of each could be beneficial; also professional profile descriptions and job markets would be helpful
--- encourage and supply information about technical strengths and weaknesses of the different languages and tools to be confronted during the programme in an impartial manner; this will help to understand what the participant needs to stress on
--- introduction about tools in frontend, backend and full-stack and trends, not limited to MEAN stack but also js (eg. MEEN) as well as non-js solutions; leave the people to find an initial good path (personally, I think that emphasising a particular stack is correct for any programme of this kind but letting people to find a suitable path that allows them to quickly produce something is certainly valuable)
--- tutorial about full stack practices in a "Now let's assemble all these bits" fashion: good materials about this are MISSING on the Internet for new comers (really!)
--- a more in-depth tutorial about starting basejumps
--- understanding the api; understanding the different full-stack integrations; understanding the importance of organising the file system
--- propose some type of waypoint to bridge the information gaps on how to consume JSON, JSONP and other resources
--- from easy to difficult (as with bonfires)

Other topics to think about:
--- debugging and testing are no waypoints, are BONFIRES! Better debugging/test tools and strategies should be included
--- for the pairing to work the best, I think suggesting some projects to be worked in teams could be helpful

**Comment by FFX01** [comment]
>tutorial about full stack practices in a "Now let's assemble all these bits" fashion: good materials about this are MISSING on the Internet for new comers (really!)

This!

The main reason I started FCC was because this was(and still is, really...) the missing puzzle piece for me. Actually writing the code isn't the problem, it's how it all fits together.  Admittedly, I am still not past all of the bonfires, but I have started a little resume website that I have developed using an Apache2 server on my machine for local testing. I did this because I wanted to try and design a file system that would allow me to organize my scripts, templates, and data in separate directories in order to create dynamically generated web pages. I basically just figured out how to do this through googling.

It would be great if FCC had a section dealing with server setup, stack selection, and directory organization.

**Comment by BerkeleyTrue** [comment]
These are great ideas! We shortly be including a ton of NodeSchool classes, but I feel like we will definitely need to create our own curriculum around these topics. 

I can recall my struggle with full stack when I first struggle and remember how little there is out there about connecting the dots (at least back when I started doing this).

You definitely given me something to think about. May have to write an outline for 'connecting the dots' curriculum sometime after a couple of other things are resolved.

**Comment by QuincyLarson** [comment]
@evaristoc Sorry it took me so long to personally respond to this excellent GitHub issue. We have essentially frozen code on Master until later this week when we merge in a boat load of code.

The main thing I want to convey is Free Code Camp will focus on practice going forward, not theory. Theory is freely available in books and great courses through Coursera and EdX. Practice, on the other hand, is in much shorter supply. We plan to focus on helping adults learn practical application of code and leave the theory to our optional theory curriculum being built by @brianamarie and a collection of resources like these: http://blog.freecodecamp.com/2015/06/25-free-resources-for-new-javascript-developers.html

You have a lot of great points here, which I'll address one-by-one:

--- focus on FCC seems to be on front-end at the moment

We are focused on the basic stuff, which is generally the front end. Our theory is that it's better to start strong and have a ton of coverage and support early, since the further along campers get, the less likely they will become discouraged.

--- finishing the ziplines could not be enough to prepare for the full-stack

Yes, this is a known issue. We've partially addressed this with https://github.com/clnhll/guidetobasejumps by @clnhll. We plan to significantly improve this in the future.

--- the suggested backend training seemed to me poor to get into the full-stack level

We are including more Node School courses, as @BerkeleyTrue mentioned.


--- all required basic topics are there but scattered

I'd love more elaboration on this.

--- information on Internet consisting in many possible sources and code styles that could bring some confusion

We are getting rid of external resources other than NodeSchool. This is taking some time, but it's almost finished.

--- in Lightwaves' words: "gap between backend and front-end development: how do you make an all encompassing full stack solution that uses your front-end knowledge to create a view that consumes a backend api"

Our new jQuery/Ajax curriculum will cover this.

--- it took me 3 weeks to realise that I was doing wrong with all my basejump projects because the lack of guidance and help

Sorry about that. Please share your realization to prevent future campers from going down this path.

RE your suggestions:

--- in general, avoid frustration by encouraging success: leave people to select the path that suit a fast development whenever possible; encourage a step-by-step development; also, work assertively on the expectations of the participants (for example so far, no-one understand the 800 hours learning time); at this stage, better guidance with introduction about the theory is my opinion required but the emphasis should be over the how to do things rather than the why, as the profile of the participants is in general not of a CS, but more technical...

We plan to stick with one rigorous, focused curriculum. The 800 hours is an estimate. Where do you think we should emphasize that this is an estimate?

--- introduction about web development theory and models

Again, we can push this to our theory curriculum.

--- introduction about what frontend, backend and full-stack development involves; an introduction of the technical description and requirements of each could be beneficial; also professional profile descriptions and job markets would be helpful

Again, theory. I think we could include a meta-analysis of the job market for these different titles.

--- encourage and supply information about technical strengths and weaknesses of the different languages and tools to be confronted during the programme in an impartial manner; this will help to understand what the participant needs to stress on

We could blog more about this, but I'm not sure it belongs in our curriculum per-say. 

--- introduction about tools in frontend, backend and full-stack and trends, not limited to MEAN stack but also js (eg. MEEN) as well as non-js solutions; leave the people to find an initial good path (personally, I think that emphasising a particular stack is correct for any programme of this kind but letting people to find a suitable path that allows them to quickly produce something is certainly valuable)

We plan to keep our Zipline and Basejump challenges open ended - you can solve them with whichever technologies you want.

--- tutorial about full stack practices in a "Now let's assemble all these bits" fashion: good materials about this are MISSING on the Internet for new comers (really!)

Would you be interested in helping us script such a tutorial? This would be great fodder for @brianamarie

--- a more in-depth tutorial about starting basejumps

Is this in-depth enough, if we made it into a video? https://github.com/clnhll/guidetobasejumps

--- understanding the api; understanding the different full-stack integrations; understanding the importance of organising the file system

Yes - these would also be good theory videos from @brianamarie.

--- propose some type of waypoint to bridge the information gaps on how to consume JSON, JSONP and other resources

Again, this will be covered in the new jQuery curriculum.

--- from easy to difficult (as with bonfires)

Not sure what you mean here

Other topics to think about:
--- debugging and testing are no waypoints, are BONFIRES! Better debugging/test tools and strategies should be included

We plan to create a debugging and testing challenges in our new JavaScript (bonfire-like) waypoints.

--- for the pairing to work the best, I think suggesting some projects to be worked in teams could be helpful

We want to keep things casual and groups/pair programming sessions spontaneously formed, not scheduled. We're open to ideas on how to do this.

Thanks for your candor. This is really useful feedback!

**Comment by tjl1113** [comment]
I'm new to code camp and not a programmer by training in anyway but I have a PhD and spend a lot of time teaching others in the area where I am an expert. What surprises me about this course is that it really lacks examples for new users to "see it". Instead it tells you a concept and then you are left often using trial and error to figure it out. This looks like what I often see when advanced college students teach new students. They are good at their subject of study but have not broken down or mastered the teaching concepts. Think of it this way, if you wanted to teach a new immigrant to write in English would you tell them about syntax and tell them to try to figure it out or give them many examples until they can start entering the logic stage? The stages of learning are grammar, logic and rhetoric. As someone who is "green" to programming, this course grealty lacks the "grammar" stage  for newbies. "look", "copy", "repeat" is the first stage in any clourse, languages especially. This may be the reason so few are finishing the course. 

Hope this helps.

**Comment by mistamadd001** [comment]
To give another view, I myself have only just started the bonfires, and although I managed to complete the codecademy items and the regexone waypoint, I found that several elements (namely objects) were not referenced individually until AFTER they were used in another codecademy example ( I think it was calling a specific parameter out of an object ). If this were to be addressed the waypoints would be much easier to understand.

Another thing that I believe should be addressed is more regex before the bonfires begin. Showing examples of how to use regex in code will help understanding more, at this stage it feels a bit like someone has realised that in order to start the bonfires they need to know a bit of regex so theyve just tacked a snippet to the end of the waypoints.

Hope this helps guys

**Comment by evaristoc** [comment]
Thanks everyone for the attention to this message! I am glad to know that somehow I am making a small contribution to this excellent project!

In fact, as already mentioned above, some of my points have been already addressed or they will be in the future. Summarising the points mentioned above by @QuincyLarson and @BerkeleyTrue:
* **Inclusion of a jQuery/Ajax section to handle resources**  should help to understand how to work the link between backend and frontend
* **Free selection of tools to solve Ziplines and Bonfires**, to allow participants to explore their strengths
* **Improving the material for the full stack curriculum** by adding new material and revising the previous one
* **Debugging** training (still as Waypoint, though)
* **Blogging about technical strengths and weaknesses of the different languages and tools to be confronted during the programme** as well as the usual discussions at Gitter are helping a lot. In particular, the problem with Gitter (the same with any other chat room) is that although it is a really good place to discuss and socialise, it is constrained by the large volume of participation: some relevant discussions or interesting solutions get missed in past posting: currently there is no easy way to access the archived information to make that persistent and accessible - wondering if some Text Mining could help here.... So blogging and if possible blogging over hot or key points that appear in Gitter is always useful - even blogging about ways to solve problems could prove useful

@QuincyLarson: thanks again. Resuming some of the points that you would like me to elaborate on:
* *all required basic topics are there but scattered*: I think the post above by @BerkeleyTrue makes a better elaboration on this point when talking about his experience; what I wanted to say is that FCC offers the basic building blocks to start the full stack track, but by the time of my previous post there was no clear way on how to link them. I personally went through a difficult time trying to get how to bind all the elements: front-end + back-end; again, the material on the Internet about how to work all this, although plenty, is confusing because of the diversity
*  *from easy to difficult (as with bonfires)*: this is something FCC got well when working on the Bonfires: a suggested level of difficulty. Then the student can go step by step from easy to difficult when working on the Bonfires. I think a similar suggested path could be applied for Ziplines and Basejumps, with additional links on how to solve the problems

I think it is also worth clarifying that I absolutely agree with the practical approach, but an introductory base allows the student to get a sense of direction as well as facilitates the communication. I don't think that a full training about (for example) what full-stack means when compared to front-end should be included, but a good introductory material highlighting the different challenges, trends, and skills required for each path, probably at the start of the programme, could help a lot to decide how to get there. Furthermore, FCC could make an excellent point by offering some professional guidance: anything that mentions the general challenges as well as the typical profile that it is expected by the different functions (i.e. front-end, back-end and full-stack), broadly as well as specifically for the JavaScript path, would allow the student to plan much better her/his resources, time and goals as well as decide what suits her/his skills and interests the best. FCC should, as always, suggest external material that could guide the student to fulfil her/his goals when FCC is still not ready to offer enough material to complete the path or when additional material is beneficial. You mentioned **I think we could include a meta-analysis of the job market for these different titles.**: and I think this could be a good first step!

I think I can understand @tjl1113 and @mistamadd001 concerns: the order might not be the correct one considering the skills required by some of challenges. I won't make any discussion about this: I come with some programming background and this is something that, although was not ideal, didn't prevent me to go further. But they might have a point. On the other hand, I see FCC is working hard to make this right.

Finally, thanks again for the opportunity to bring forward our concerns. We just hope that we can help to improve the training, based on our experiences along the way.

I will make contact with @brianamarie soon to see if she can profit from my experience when trying the full-stack material. I will be very happy to help!

The best!

**Comment by BerkeleyTrue** [comment]
Closing as stale.

Exciting news coming in the next few weeks!

Happy Coding
