### ISSUE TITLE
Misleading hint when using a border radius value greater than 50 percent

### ISSUE THREAD

**Issue by vanden** [FreeCodeCamp/FreeCodeCamp#12107]
[Make Circular Images with a Border Radius](https://www.freecodecamp.com/challenges/make-circular-images-with-a-border-radius)

If you try to set the style for the challenge as
`  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 90%;
  }`
the hint when the html fails the test is 

>  Be sure to use a percentage instead of a pixel value.

This is not a good hint message; the problem is not that a pixel value was used, but an inappropriate percentage value was used.

It is unlikely to be relevant, but:
Firefox 47.0 on an obscure desktop Linux distro

**Comment by dhcodes** [comment]
Thanks @vanden. Confirmed, there must be something with how the tests are written. The second test (that @vanden references) is not actually testing what it's suggesting it's testing. 

We need to make sure the test message reflects the test so whoever tackles this one should either update the message based on the current test or update the test to match the current message.

Clear as mud? Good. 👍

**Comment by dhcodes** [comment]
cc @FreeCodeCamp/moderators @Manish-Giri has done what I originally asked (thanks!) but looking at this more, I think we should just get rid of the second test and improve the first test. The current tests are:
```
"assert(parseInt($(\"img\").css(\"border-top-left-radius\")) > 48, 'message: Your image should have a border radius of <code>50&#37;</code>&#44; making it perfectly circular.');",

"assert(code.match(/50%/g), 'message: Be sure to use a percentage instead of a pixel value.');"
```

The first does the job, but should be `== 50%`, right?

The second test essentially tests the same thing, but lacks specificity since it tests all the code in the editor and per this issue, the message does not reflect the test. Thoughts?

**Comment by erictleung** [comment]
@dhcodes IMO, the second test is to ensure the percentage use of the radius. I'm guessing it can be modified using other ways so that is why its there.
