### ISSUE TITLE
jQuery:  <b> != <em> in tests 

### ISSUE THREAD

**Issue by schwartzadev** [FreeCodeCamp/FreeCodeCamp#12124]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<b>#target4</b>")
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

`$("#target4").html("<b>#target4</b>")` : although I use `<b>` tags, the tests fail since they are expecting `<em>` tags. IMO these should both work since they achieve the same thing and are just an issue of style preference.

**Comment by dhcodes** [comment]
I'm not sure they achieve the same thing as they have different uses. See the first usage note (in the yellow box, here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b

**Comment by erictleung** [comment]
@dhcodes agreed 👍 

@schwartzadev thanks for the issue. However, I agree on there shouldn't be any change. First, the `<b>` tag does not place any semantic weight on the content around it. Plus, `<b>` tags just style the text differently. Second, emphasis is generally styled as italics rather than a bold weight. Third, the [W3C recommends not using `<b>` or `<i>` tags](https://www.w3.org/International/questions/qa-b-and-i-tags) for more descriptive and relevant tags. I hope that makes sense. Closing as no changed needed. Happy coding!

**Comment by schwartzadev** [comment]
Gotcha. Thanks!
