### ISSUE TITLE
Escape sequences

### ISSUE THREAD

**Issue by EricL2001** [FreeCodeCamp/FreeCodeCamp#12134]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5Cn%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I ran in my console through Dev Tools and it worked

![image](https://cloud.githubusercontent.com/assets/16734428/21364334/627bf24e-c6be-11e6-9135-8b04905d5dc6.png)

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\n\rThirdLine"; // Change this line



```

**Comment by raisedadead** [comment]
@EricL2001 thanks for the report but the correct and expected sequence is written out in the challenge instructions. 

> FirstLine`newline` `backslash`SecondLine`backslash` `carriage-return`ThirdLine

Your code doesn't match the same.

Please double check and visit the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by RomingArt** [comment]
I am not sure, but I think I found a bug because the console states that I have the correct answer but it does not show exactly the answer I was suppose to have in the yellow boxed answer.
<img width="1229" alt="screen shot 2017-01-02 at 2 06 12 am" src="https://cloud.githubusercontent.com/assets/19600363/21587346/14a6916a-d090-11e6-969f-42d7c8e9cc91.png">



`var myStr="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line`
