### ISSUE TITLE
Record Collection: xx should not be set. never pass

### ISSUE THREAD

**Issue by MMrYYx** [FreeCodeCamp/FreeCodeCamp#12160]
#### Challenge Name

https://www.freecodecamp.com/challenges/record-collection

#### Issue Description

xx should not be set requirment is never passed even no modification on target item. Please see code part.

#### Browser Information

* Browser Name, Version:  Google Chrome Version 55.0.2883.87 m (64-bit)
* Operating System: windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 function updateRecords(id, prop, value) {
  //console.log(collection[id]);
  if (value) { 
    console.log(id + " AAAAAAA");
    if (prop === "tracks") {
    if(!collection[id].hasOwnProperty(prop)){
      tracks = [];
      collection[id][prop] = tracks;
      collection[id][prop].push(value);
    } else {
      collection[id][prop].push(value);
    }
  } else {
    collection[id][prop] = value;
  }
  }

  return collection;
}
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/19357184/21411895/fd2bc80e-c7b9-11e6-8d7e-c3470e2d54ee.png)
![image](https://cloud.githubusercontent.com/assets/19357184/21411899/0617f7bc-c7ba-11e6-9ace-d938a5663b73.png)

As you see, when value is empty, target item is not modified but it still fails the test.

**Comment by Marmiz** [comment]
Just to clarify, your issue is that you fail the test cases when values are empty, right?

Well the challenge description clearly states that:
> If value is empty (""), delete the given prop property from the album.

So the program expect that if an empty value is passed, that property needs to be removed from the object; and nowhere in your code you're handling this case.

Next time you are having difficulties with a code, try asking for help into the [help chat room](https://gitter.im/FreeCodeCamp/Help), the [help JS](https://gitter.im/FreeCodeCamp/HelpJavaScript), or even the [forum](https://forum.freecodecamp.com/).
 
Happy coding ✨

**Comment by raisedadead** [comment]
@MMrYYx thanks for the issue and @Marmiz is correct, please proceed to the chat room or the forum for coding assistance.

Happy coding!
