### ISSUE TITLE
Does not change color

### ISSUE THREAD

**Issue by marysja** [FreeCodeCamp/FreeCodeCamp#12175]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.0; P001 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by marysja** [comment]
Please check it

**Comment by IsaacAbrahamson** [comment]
Something is buggy. Your code is correct and works if you reset and paste in.

@FreeCodeCamp/moderators anyone know what is going on?

**Comment by erictleung** [comment]
@marysja this is a duplicate issue of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753, but this was fixed with a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11472. These changes haven't been pushed up to the production site. I would advise you to use a desktop/laptop if possible when completing the challenge. Closing as should be resolved in staging. Happy coding!
