### ISSUE TITLE
help me?

### ISSUE THREAD

**Issue by nechii** [FreeCodeCamp/FreeCodeCamp#12188]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%7B%0A%20%20%20%20color%3Apink%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{
    color:pink
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by Manish-Giri** [comment]
@nechii You haven't completed the css statement `color:pink` with `;`. 

For issues like these, please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) in future, first. This is a place to report bugs with the website itself. Happy Coding!

**Comment by erictleung** [comment]
@nechii thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
