### ISSUE TITLE
Find the Length of a String

### ISSUE THREAD

**Issue by Loquito95** [FreeCodeCamp/FreeCodeCamp#12218]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%200%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0AlastNameLength%20%3D%20lastName.length%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AlastNameLength%20%3D%20lastName%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 0;
var lastName = "Lovelace";
lastNameLength = lastName.length;
// Only change code below this line.

lastNameLength = lastName;



```

**Comment by erictleung** [comment]
@Loquito95 Thank you for reporting this issue. Please adhere to the comments such as `// Only change code below this line.` in the editor. You've added code in the wrong place.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
