### ISSUE TITLE
unknown error, maybe a bug??

### ISSUE THREAD

**Issue by tony-kunliu** [FreeCodeCamp/FreeCodeCamp#12212]
Challenge [Manipulate Arrays With push](https://www.freecodecamp.com/challenges/manipulate-arrays-with-push#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.push(%5B%22happy%22%2C%20%22joy%22%5D)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%2C%20%5B%22happy%22%2C%20%22joy%22%5D%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.push%20%3D%20(%5B%22dog%22%2C%203%5D)%3B%0A%2F%2FArray.prototype.push.apply(%20myArray%2C%20%5B%22dog%22%2C%203%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.push(["happy", "joy"]); 
// ourArray now equals ["Stimpson", "J", "cat", ["happy", "joy"]]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
myArray.push = (["dog", 3]);
//Array.prototype.push.apply( myArray, ["dog", 3]);


```
Hi, all. Dont know why it is wrong. Anyone can help???

**Comment by tony-kunliu** [comment]
Manipulate Arrays With push
An easy way to append data to the end of an array is via the push() function.

.push() takes one or more parameters and "pushes" them onto the end of the array.

var arr = [1,2,3];
arr.push(4);
// arr is now [1,2,3,4]
Instructions
Push ["dog", 3] onto the end of the myArray variable.

**Comment by erictleung** [comment]
@tony-kunliu Thank you for reporting this issue. Your code is incorrect.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
