### ISSUE TITLE
Instructions for this module and the check points beneath the instructions have different values. Both should agree on the values of a, b, and c, respectively

### ISSUE THREAD

**Issue by masters-george** [FreeCodeCamp/FreeCodeCamp#12243]
#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Linux
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

Instructions
Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.

Run tests (ctrl + enter)
Reset	Help	Bug

a = 7, b = 20, c = 'I am a String!'

a should be defined and have a value of 6
b should be defined and have a value of 15
c should not contain undefined and should have a value of "I am a String!"
Do not change code below the line

**Comment by erictleung** [comment]
@masters-george Thank you for reporting this issue. The instructions are consistent. The tests are the results of running all of the code. Please consult the help rooms for more help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
