### ISSUE TITLE
 Word Blanks ,why this writing code ,reason?

### ISSUE THREAD

**Issue by siguniang** [FreeCodeCamp/FreeCodeCamp#12258]
![6](https://cloud.githubusercontent.com/assets/24384921/21541333/5bfdbb58-cdf0-11e6-9bc9-0f521428fbd2.png)

#### Issue Description

why need add +"  "+?
result=myNoun+" "+myAdjective+" "+myVerb+" "+myAdverb;

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result=myNoun+" "+myAdjective+" "+myVerb+" "+myAdverb;
  //result="dog, big, ran ,quickly";
  //result="cat, little, hit ,slowly";
  
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
wordBlanks("cat", "little", "hit", "slowly");
 
 
```

**Comment by Dayfiri** [comment]
@siguniang 
Implementation of ` + " " + ` is there so that your output would be more tidy and readable.
output using ` + " " + ` --> `'cat little hit slowly'`
output without using it --> `'catlittlehitslowly'`

For future help please use FCC [help chat](https://gitter.im/FreeCodeCamp/Help) room. This forum is only for submitting bugs. 
Thanks and happy coding ;)

**Comment by dhcodes** [comment]
@Dayfiri is correct. The goal is for the end result to appear as a sentence would. Closing as resolved. Thanks @Dayfiri
