### ISSUE TITLE
Create Bootstrap Wells

### ISSUE THREAD

**Issue by ejang** [FreeCodeCamp/FreeCodeCamp#12277]
Challenge [Create Bootstrap Wells](https://www.freecodecamp.com/challenges/create-bootstrap-wells#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%20well%22%3E%0A%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%20well%22%3E%0A%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6 well">

    </div>
    <div class="col-xs-6 well">

    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@ejang Thank you for reporting this issue. Your code is incorrect. 

> Nest one `div` element with the class `well` within each of your `col-xs-6` `div` elements.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by lxl1001** [comment]
yes, I need

**Comment by bartzet** [comment]
@ejang you are missing this part
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6 well">**<div class="well"></div>**</div>

    
    <div class="col-xs-6 well">**<div class="well"></div>**</div>
  </div>
</div>

**Comment by texas2010** [comment]
@bartzet 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!
