### ISSUE TITLE
not letting run test?

### ISSUE THREAD

**Issue by jonluvcodes** [FreeCodeCamp/FreeCodeCamp#12311]
In html under Change the Color of Text
im change the color of h2 to blue and I did it but it not letting me run test I'm using a Galaxy S4 Mini

**Comment by erictleung** [comment]
@jonluvcodes this is a duplicate issue of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753, but this was fixed with a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11472. These changes haven't been pushed up to the production site. I would advise you to use a desktop/laptop if possible when completing the challenge. Closing as should be resolved in staging. Happy coding!
