### ISSUE TITLE
Counting Space Characters instead of Non Space

### ISSUE THREAD

**Issue by sunshinescj** [FreeCodeCamp/FreeCodeCamp#12327]
Challenge [Invert Regular Expression Matches with JavaScript](https://www.freecodecamp.com/challenges/invert-regular-expression-matches-with-javascript#?solution=%0A%2F%2F%20Setup%0Avar%20testString%20%3D%20%22How%20many%20non-space%20characters%20are%20there%20in%20this%20sentence%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2F%5CS%2B%2Fg%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20nonSpaceCount%20%3D%20testString.match(expression).length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testString = "How many non-space characters are there in this sentence?";

// Only change code below this line.

var expression = /\S+/g;  // Change this line

// Only change code above this line

// This code counts the matches of expression in testString
var nonSpaceCount = testString.match(expression).length;

```

**Comment by systimotic** [comment]
Hi @sunshinescj! Thank you for reporting this issue.

There is an issue in your code. Please reread the instructions and try again. Note that lower case `s` matches space characters, while upper case `S` matches non space characters.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
