### ISSUE TITLE
HELP!!! Pretty sure my code is correct I just can't run a test, or possibly a bug. Any help would be great thanks.

### ISSUE THREAD

**Issue by Kennneth** [FreeCodeCamp/FreeCodeCamp#12330]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  red-text {
    color: red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Kennneth** [comment]
@VarCI-bot 
This issue isn't with the challenge. There is a bug it won't let me run test. I've already did a hard refresh also. It brings the same code up every time and doesn't reset when I ask.

**Comment by felipeklafke** [comment]
.red-text
class="red-text"

**Comment by erictleung** [comment]
@Kennneth Thank you for reporting this issue. The "bug" is actually that your code is incorrect. If you've implemented the code right, you should see that the `<h2>` element turn red, but it isn't. Please ask questions in the Gitter chat rooms if you still need help. GitHub issues are not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
