### ISSUE TITLE
App

### ISSUE THREAD

**Issue by ramiksa11** [FreeCodeCamp/FreeCodeCamp#12331]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by getoutb1** [comment]
Stop

**Comment by erictleung** [comment]
@ramiksa11 please fill out the template and reopen this issue if there is a bug with the site. Closing issue because there is no information.

@getoutb1 Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
