### ISSUE TITLE
Filter succes when we didn't shift the first ARG out

### ISSUE THREAD

**Issue by xiangyu-sun** [FreeCodeCamp/FreeCodeCamp#12353]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20arg%20%3D%20Array.from(arguments)%3B%0A%20%20arg.shift()%3B%0A%0A%20%20return%20arr.filter(function(val)%7B%20return%20(arg.indexOf(val)%20%3D%3D%3D%20-1)%3B%7D)%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function destroyer(arr) {
  // Remove all the values
  var arg = Array.from(arguments);
  arg.shift();

  return arr.filter(function(val){ return (arg.indexOf(val) === -1);});
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
if we comment out   arg.shift();
this will still works.

**Comment by suhussai** [comment]
I don't think this is an issue with the challenge itself.

The `shift()` command removes the first element of a given array. In your case, it is applied to `arg` which is equal to `[[1, 2, 3, 1, 2, 3], 2, 3]` before the function call. After the function call, `arg` is equal to `[2, 3]`. The filter command then removes all elements inside `arr`, which is equal to `[1, 2, 3, 1, 2, 3]`, that are present in the array `arg`. 

Now if you decide to not apply the shift function to the `arg` array, the filter command will do what it did before except with an extra element to compare each value in `arr` with. That extra element is the entire `arr` array. Including that makes no difference because none of the values inside of the array `arr` will ever be equal to the array `arr`.

Hope that makes sense.

**Comment by systimotic** [comment]
Good investigation work @suhussai.
@xiangyu-sun The last line summarises it: It works fine if that first element is in the array, because none of the items inside of the array are ever going to be equal to the array.

I'm closing this issue as resolved. If you think I'm wrong in closing this issue, please comment and reopen.
Happy coding!
