### ISSUE TITLE
I am not sure if sum of all primes actually has the correct answer.

### ISSUE THREAD

**Issue by carloslocoo** [FreeCodeCamp/FreeCodeCamp#12360]
I am not sure if if there is something wrong with my code or the answer is actually bad. 143 is not a prime number, however in my isPrime function I had to include it as a prime in order for it to work.

```js
function sumPrimes(num) {
  function isPrime(num){
     if(143 == num){
      return true;
    }
    if(num%2 === 0 || num%3 === 0 || num%5 === 0 || num%7 === 0 || num%11 === 0 ||
       num%13 === 0 || num%17 === 0 || num%19 === 0 || num%23 === 0 || 
       num%29 === 0 || num%31 === 0){
      return false;
    }
    else{
      return true;
    }
  }
  var array= [2, 3, 5, 7];
  for (i = 11 ; i< num + 1; i++){
    if(isPrime(i)){
       array.push(i);
    }
  }
  var total = 0;
  for(i = 0; i < array.length; i++){
    total+=array[i];
  }
  return total;
}
sumPrimes(977);
```

**Comment by joaofreires** [comment]
Well, your code have a bad ideia about implementations. Let's think about it, 37 is a prime number, and your code doesn't know this, then every time 37 is multiplied with another prime bigger than 31, your code will think that number is prime too.  Another error are when you pass primes number too, when you pass 11 to your functions `isPrime`, your code try do: `(11%11 === 0)` and it is true, but 11 is prime, and again your code will fail. You can try code a better isPrime function, you can try implement Sieve of Eratosthenes (it's seems a bit like you have) or try another better method.

Your identations is bad, maybe it's caused by your code-editor. So, try better it.

**Comment by erictleung** [comment]
@carloslocoo this challenge does have an answer. Your solution is unique and creative. Take a look at prime number algorithms for better methods. If you have questions about a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
