### ISSUE TITLE
Updating Object Properties

### ISSUE THREAD

**Issue by siguniang** [FreeCodeCamp/FreeCodeCamp#12393]
Challenge [Updating Object Properties](https://www.freecodecamp.com/challenges/updating-object-properties#?solution=%0A%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%0A%7D%3B%0A%0AourDog.name%20%3D%20%22Happy%20Camper%22%3B%0A%0A%2F%2F%20Setup%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AmyDog%5B%22name%22%5D%20%3D%20%22Happy%20Camper%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

ourDog.name = "Happy Camper";

// Setup
var myDog = {
  "name": "Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"]
};

// Only change code below this line.

myDog["name"] = "Happy Camper";


```

**Comment by siguniang** [comment]
![image](https://cloud.githubusercontent.com/assets/24384921/21710449/ae41e5e0-d423-11e6-8d1d-c3897cf1871c.png)

**Comment by Marmiz** [comment]
The instruction states:

> Update the myDog object's name property. Let's change her name from "Coder" to **"Happy Coder"**.

This tracker is fo bugs only, if you have problem with your code please consider asking for help on
[Help Chatroom](https://gitter.im/FreeCodeCamp/Help) or [Help JS](https://gitter.im/FreeCodeCamp/HelpJavaScript), alternatively look on our [official forum](https://forum.freecodecamp.com/)

----
Happy coding 👍

**Comment by siguniang** [comment]
@Marmiz why the symbols being given,my code is correct,the output is fight!

**Comment by siguniang** [comment]
@Marmiz why the symbols being given,my code is correct,the output is right!

**Comment by erictleung** [comment]
@siguniang the editor we use gives JS suggestions on how to write your code. The symbol over your code is a suggestion to use dot notation rather than brackets because you don't need spaces in the property name.

![image](https://cloud.githubusercontent.com/assets/2754821/21711376/837a9a30-d3a3-11e6-984f-a2058ae13666.png)

Your code isn't correct according to the instructions. The use of `"Happy Camper"` is just an example.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by siguniang** [comment]
@Marmiz @erictleung has been thought to be quotation marks being given,did nont see the word is wrong,has now been resolved.thank you!
