### ISSUE TITLE
Waypoint: Mobile Responsive Images Has An Issue

### ISSUE THREAD

**Issue by forevermelody** [FreeCodeCamp/FreeCodeCamp#1240]
From what I can tell I've completed the challenge but it's not letting me move on...

I have two img-responsive items... not sure what I'm doing wrong.

![responsive image](https://cloud.githubusercontent.com/assets/13261948/8610301/48c21310-2665-11e5-94a7-dece7a62b59a.JPG)

**Comment by faizanmobh** [comment]
I have completed this waypoint yesterday. First remove all class from second image. Second image need only one class"img-responsive"

**Comment by faizanmobh** [comment]
Your code should be like this :

<img class='img-responsive' src='https://bit.ly/fcc-kitten2' />

**Comment by keuz37** [comment]
This is a real pain indeed.    The parser is expected a particular string in a particular order and that seems to be something that is not intuitive to us at all.    Copy the other one and change the src would be the natural response and yet it doesnt work.    This could kill the interest of many that are trying out the challenge if it failed because of syntac check strictness of the program.     Tried many ways and it still doesnt work.    Last one was <a href='#'><img src='https://bit.ly/fcc-kittens2' class='img-responsive'/></a>.

Can someone share how they got thru this one.     Frustration.

**Comment by keuz37** [comment]
Oops ..   image is better.

![screen shot 2015-07-10 at 17 57 55](https://cloud.githubusercontent.com/assets/13271760/8616366/43ecb5de-272d-11e5-8de9-68c19c8ea055.png)

faizanmobh, can you share your solution again?    Cant see the link.

**Comment by keuz37** [comment]
Fixed it.   Found the solution from the other discussion group.

Removed the "s" from "https://bit.ly/fcc-kittens2" and it will pass you through.      Well, why such a stickiness for the difference?    Couldnt the instruction use "https" instead of "http" and couldnt the solution accept both "http" as well as "https".     Argggggggghhhhhh....

**Comment by BerkeleyTrue** [comment]
Yes @keuz37 is correct, please use `http` not `https`. It is stated twice in the instructions now for clarification.

Happy Coding!
