### ISSUE TITLE
Need more test for Escape Sequences in Strings.

### ISSUE THREAD

**Issue by M1L2** [freeCodeCamp/freeCodeCamp#12410]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondline%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; AskTbORJ/5.15.9.29495; BRI/2; GWX:QUALIFIED; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
var myStr = "FirstLine\n\\Secondline\\\rThirdLine"; // Change this line

```javascript

var myStr = "FirstLine\n\\Secondline\\\rThirdLine"; // Change this line



```

**Comment by raisedadead** [comment]
This challenge keeps popping up every now and then, should we just over-haul this?
/cc @FreeCodeCamp/moderators

**Comment by ooade** [comment]
@raisedadead it works after resetting but that shouldn't be happening :cold_sweat:

**Comment by ooade** [comment]
If you guys take it down, new folks might not know anything about escape characters because that's the only challenge about escape characters.

**Comment by systimotic** [comment]
@M1L2 The reason your code didn't work was because your `l` in `Secondline` was lower case, while it should be upper case 🙂 I wrote this a few hours ago, by now Dylan also said this in your duplicate issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12411

@raisedadead There was an issue with the return carriage, but that has been changed ([commit](https://github.com/FreeCodeCamp/FreeCodeCamp/commit/ac1e3d249bba0665e4b2921ddcf951e1ef2157c8)).
Looking through issues about this challenge, I can spot three different categories:
1. Typo's, like in this issue.
2. People who don't understand that the words they use matter (for example, they use "hey" instead of "FirstLine")
3. Miscellaneous

The first item seems hard to solve. I can't come up with anything to help that.
Some modifications to the description might help with the second item.
Most of the miscellaneous issues have to do with the escaped characters being placed in the wrong spot. Most users getting this wrong seem to be confused about the error message here (see https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11792). I think this could be improved by having tests that look at smaller sections of the variable. If they check for each escaped character individually, we can have more precise error messages.

I think we can use https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12411 for item 3.
We can work on item 2 in this issue.

**Comment by raisedadead** [comment]
@systimotic thanks a ton for your deep and in-depth insights on this.

> I think this could be improved by having tests that look at smaller sections of the variable. If they check for each escaped character individually, we can have more precise error messages.

This is particularly interesting and I guess would state clearly for going about this issue.

Yup, we can't do much about the Typos.

Thanks again for your suggestions, am tagging this as help wanted for the tests, and I agree we can handle the third problem with the separate issue that we already have for it.

**Comment by systimotic** [comment]
@raisedadead My formatting was a bit messy, I think that may have confused you. I edited it to hopefully make more sense.
The third problem, the one that is handled in the other issue, is the problem that needs more tests.

**Comment by billy-reilly** [comment]
Hi guys, I had a think about this and thought maybe it could be resolved by splitting the first test into two parts and then having a separate test for each special character which specifies where it should be placed: 

1) <code>myStr</code> should contain no spaces
2) <code>myStr</code> should contain the strings <code>FirstLine</code>, <code>SecondLine</code> and <code>ThirdLine</code> (remember it's case sensitive)
3) <code>FirstLine</code> should be followed by the newline character <code>\n</code>
4) <code>SecondLine</code> should be preceded by the backslash character <code>\\\\</code>
5) <code>SecondLine</code> should be followed by the backslash character <code>\\\\</code>
6) <code>ThirdLine</code> should be preceded by the carriage return character <code>\r</code>

I think the following code should do the job?
1) `assert(myStr.match(/\s/g).length == 0, 'message:`...
2) `assert((function(){if((myStr.match(/FirstLine/g).length ==1 ) && (myStr.match(/SecondLine/g).length == 1) && (myStr.match(/ThirdLine/g).length == 1)){return true;}else{return false;}}))(), 'message:`...
3) `assert(myStr.match(/FirstLine\n/g).length == 1, 'message:`...
4) `assert(myStr.match(/\\SecondLine/g).length == 1, 'message:`...
5) `assert(myStr.match(/SecondLine\\/g).length == 1, 'message:`...
6) `assert(myStr.match(/\rThirdLine/g).length == 1, 'message:`...

We could also have a test for the final correct answer to ensure that people aren't adding in extra characters between the phrases checked above but that seems unnecessary to me.

I'm new to contributing but would be keen to submit a pull request for this if you think it's correct?

**Comment by raisedadead** [comment]
@billy-reilly thanks for taking a dig at this. I guess, this is a very clear breakup of going at this issue, waiting for @systimotic's confirmation, and I guess we can go forth.

**Comment by QuincyLarson** [comment]
@billy-reilly that looks like a comprehensive set of tests!

**Comment by systimotic** [comment]
@billy-reilly Thanks a lot for taking a look at this!
Your suggested changes look great!
Since the live version, this challenge has changed a bit. You can check out the updates here on the beta: https://beta.freecodecamp.com/en/challenges/basic-javascript/escape-sequences-in-strings

A pull request would be awesome!

A couple of notes on your tests:
The tab and newline character would both count as whitespace under the `\s` test. In this case, testing for a space character (` `) would probably be the best solution.
You may already be aware of this, but for the actual test files, every backslash will have to escaped itself.

The tests for this challenge are [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L1182). If you run into any problems, feel free to go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by Egidijus-Ezerskis** [comment]
var myStr = "FirstLine\n\t\SecondLine\n\ThirdLine"; // Change this

**Comment by Mishi22** [comment]
what about when it also says "myStr should contain a tab character \t which follows a newline character"
