### ISSUE TITLE
User experience mods

### ISSUE THREAD

**Issue by lllNuggetslll** [FreeCodeCamp/freecodecamp#1244]
Hi! I have a few suggestions that might make user exp better.

  -  add camper# to camper profiles.

- add an optional 'ladders' scheme that campers can participate in to see how far they've made it compared to others that want to participate in the 'race'

- add ranks on camper profiles depending on their participation and progress (scout, group leader, fire starter, etc.) These would be useful when trying to pair up with others that have made similar progress, possible make a 'pair up page' with open time schedules

- add a time log to help keep track of how much time is put in, i do it via an app.  maybe add a planning app that the camper will display when they will code so others can maybe join each other, or help set personal goals.  I've planned everyday when to learn, and it would help if the site had a planner that i could fill out that will help hold me to completing my goals

- 'camper of the week' kinda like an honor roll, displays the coder that has made the most strides within a week

- 'fire of dedication' symbolic camp fire pic on the camper profile, the longer the streak of work you put it, the larger the fire. dies down the longer you put off progress.

 - badges for completion of the different sections

**Comment by LumenTeun** [comment]
By `camper#` do you mean where in the order the user joined freeCodeCamp? I like the idea, but with my very limited knowledge of MongoDB, I don't think it's possible since I can't find any information relating to when users joined. I might be wrong though.

Some sort of badge system is being discussed in #604, I suppose this would also be somewhat of an equivalent to what you call ranks, at least in functionality.

In my opinion, adding planning functionality to FCC seems excessive. Like you said, there are apps out there that allow you to plan and keep track of how much time is spent on tasks, and since this is not something that everyone would like to use, it seems unnecessary to implement it. You know, dotadiw.

I don't really have any input on the other stuff. I'm not too much about competition elements like "racing" and "ranks" myself, but if others like it, go ahead.

**Comment by lllNuggetslll** [comment]
I'm just shotgunning ideas, if it takes, it takes.

**Comment by LumenTeun** [comment]
Yeah, that's great :) I'm just providing as much info as I can.

**Comment by BerkeleyTrue** [comment]
> add camper# to camper profiles.

There is no practical way for us to accomplish and I don't see the value unless you are camper < 100

> add ranks on camper profiles depending on their participation and progress (scout, group leader, fire starter, etc.) These would be useful when trying to pair up with others that have made similar progress, possible make a 'pair up page' with open time schedules

We had something similar and found it encouraged elitism so we will not be implementing this again.

> add an optional 'ladders' scheme that campers can participate in to see how far they've made it compared to others that want to participate in the 'race'

Not really sure about this one.

> 'camper of the week' kinda like an honor roll, displays the coder that has made the most strides within a week

I like this idea. 

> add a time log to help keep ...

This is outside FCC's scope.

> 'fire of dedication' symbolic camp f...

This is exactly what the heat map is for.

The badging system is discussed else where.


I'm closing this for triage. I'm going to mull over `camper of the week`. Practically it might be easy to create but will take some thought. We will eventual make moves that will allows us to better identify campers who have accomplished.

Happy Coding.
