### ISSUE TITLE
HELP. Can´t finish task-

### ISSUE THREAD

**Issue by rmurcia75** [FreeCodeCamp/freeCodeCamp#12450]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%3Cstyle%3E%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Cimg%20class%3D%22smaller-image%22%20src%3D%20%22http%3A%2F%2Fwww.w3schools.com%2Fcss%2Fparis.jpg%22%20alt%3D%22image_error%22%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style> 
  .smaller-image {
    width: 100px;
  }
</style>
<img class="smaller-image" src= "http://www.w3schools.com/css/paris.jpg" alt="image_error">



```

**Comment by Marmiz** [comment]
Dear @rmurcia75 as @VarCI-bot suggested I strongly suggest you to ask for help on an official channel, instead of opening an issue on Github.

---
That said I can hint you the fact that the challenge, to check its correctness, will look for a specific pictures and all the previous code you have implemented prior to this channel.

So instead of deleting and inserting "custom" code, works with what you have been given at the beginning of the lesson.

Happy coding 👍

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!
