### ISSUE TITLE
will not pass - the code is right. what do i need to do

### ISSUE THREAD

**Issue by rkentmc** [FreeCodeCamp/freeCodeCamp#12453]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Ca%20href%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E%0A%3Cp%3EView%20more%20%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>
<p>View more <a href="http://freecatphotoapp.com">cat photos</a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Marmiz** [comment]
Hi @rmurcia75

The issue tracker is for reporting bugs only. If this is a request for help with a challenge, please use the [help](https://gitter.im/FreeCodeCamp/Help) chat room or try looking through the forum for help with a specific challenge.

---
That said your code is not correct, but there is as a matter of fact an error.
HINT: why are there two `<a>` elements on your page?

The challenge expect only one, with the exact text and URL as asked!


Feel free to reach fellow campers on chat (you can always PM me there if you prefer a one-to-one conversation) for further assistance.

Happy coding 👍

**Comment by rkentmc** [comment]
There is a bug on this page or the directions are not specific enough. I deleted the other anchor tag and got more errors. I moved the view more <a>element before the default anchor and it passed. It is illogical to have a "view more" before you have even viewed a photo. Surely that was not the intention of the lesson's designer.

**Comment by rkentmc** [comment]
This works:
```
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<a href="http://freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>```

but the above doesn't. That is a bug your parsing algorithm is off.

**Comment by JosephLivengood** [comment]
It looks like the error was arising from missing this key instruction _"Now nest your **existing a element** within a new p element"_. By creating a new anchor it messed with the tests.

Should we create a new test to ensure campers use the existing anchor only to test for that instruction (and help them see this error easier) and do not add a new anchor? If so I'll take it 👍

**Comment by Marmiz** [comment]
Dear @rkentmc removing the first link created more error mainly because your (supposed-to be) correct one had the wrong url referenced to it.

That's why I suggested you to
> The challenge expect only one, with the *exact text and URL* as asked!

---
Also as pointed by @JosephLivengood the challenges states to work with your **existing a element**, so makes sense to proceed from there.

If we are talking about designing reasons and more specifically as you stated:
> It is illogical to have a "view more" before you have even viewed a photo

I can agree with you, but remember that this is an exercise many focused on `nesting`, which will come handy later.
And not a lesson about "proper designing workflow".

As always Free Code Camp community is open for discussion ,so if you strongly feel that this lesson was confusing/ difficult to grasp we are open for suggestion on how you'd improve it!

Happy coding ✨

**Comment by raisedadead** [comment]
@rkentmc thanks for the report, and what you state here is correct that we are not checking for the design of the page, it's literally tedious and somewhat expensive to keep a check for all the tags in the code that a camper has written in the editor.

In your case, just by moving the tag above we find that its correctly nested and do not bother to check if there is one more, and for that matter any no of `<a>` tags.

Yes, @JosephLivengood we might have more tests, but again arguments like this will break them, only to have a long list of test cases confusing beginners.

freeCodeCamp aims to teach basics, and not best practices thru the challenges, we have video series for that, feel free to check them out, or look up resources that are better and we will definitely recommend them. IMHO the challenge already does what's intended in its scope.

Please feel free to suggest otherwise if you would like to make this challenge better, but IMO we will be closing this as bikeshedding.

**Comment by rkentmc** [comment]
@Marmiz What do you mean it has the wrong URL referenced to it?

```<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<a href="http://freecatphotoapp.com">cat photos</a>```

**Comment by rkentmc** [comment]
@raisedadead That's how I got the error

**Comment by raisedadead** [comment]
Yup, toggling / switching the statements lets you pass the challenge. I agree, but testing such cases is kind of an overhead for the infrastructure, there can potentially lots of such combinations.

Hence our justification to not add more test cases.

**Comment by Marmiz** [comment]
What I mean @rkentmc , and the reason that switching statements works is because:

your original nested `a` url attribute is incorrect: **it's missing the www.**

Original:
```
<p>View more <a href="http://freecatphotoapp.com">cat photos</a></p>
```

Working solution:
```
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
```

---
If I'm not mistaken @raisedadead and @rkentmc , this challenge is checked against a regex to check for the entire string to match exactly what the challenge wants you to implement.

And the challenge specifically ask you to implement an `a` elements that link to:
> "http://www.freecatphotoapp.com"

(and not `http://freecatphotoapp.com`)

---
I do also believe that adding extra test cases could potentially overhead this challenge with obnoxious tests.
In the end the challenge are quite specifics and ask you for an exact url and paragraph.

Since in the beginning both the `a` were missing one or the other, the first was missing the paragraph, the second the url; I believe there's nothing wrong in the challenge.

Here's your original code that caused you troubles:
```
<a href="http://www.freecatphotoapp.com">cat photos</a> 
// missing paragraph --> INCORRECT
<p>View more <a href="http://freecatphotoapp.com">cat photos</a></p>
// wrong url --> INCORRECT

```

Happy coding everyone 👍

**Comment by HRcat** [comment]
I passed with the following syntax:
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a>.</p>

**Comment by mdiasrtt** [comment]
I need help

**Comment by texas2010** [comment]
@mdiasrtt 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
