### ISSUE TITLE
Steamroller challenges.   i did it right . but it does not let me go through it. 

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [FreeCodeCamp/freeCodeCamp#12452]
#### Challenge Name

Steamroller

#### Issue Description

do not know why it does not let me through this challenge . 

#### Browser Information

every result is right . 

* Browser Name, Version:  chrome . 
* Operating System:  mac os 
* Mobile, Desktop, or Tablet:  Desktop 

#### Your Code

```js

function steamrollArray(arr) {
  // I'm a steamroller, baby
  
  for(var i=0;i<arr.length;i++){
    if(!Array.isArray(arr[i])){
      retArr.push(arr[i]);
    }else{
      retArr.concat(steamrollArray(arr[i]));
    }
  }
  return retArr;
}

var retArr = [];

steamrollArray([1, [2], [3, [[4]]]]);

 
 
```

**Comment by erictleung** [comment]
@xiaomingfuckeasylife thanks for the issue. This is very similarly related to https://github.com/FreeCodeCamp/freeCodeCamp/issues/9199. Closing as duplicate. To complete the challenge, do not use global variable because the tests call your function over and over, which will modify any global variables you may have. Happy coding!
