### ISSUE TITLE
Grammatical Error in Challenge

### ISSUE THREAD

**Issue by paddyofurniture** [freeCodeCamp/freeCodeCamp#12464]
#### Challenge Name

https://www.freecodecamp.com/challenges/count-backwards-with-a-for-loop

#### Issue Description

The word "backwards" appears 3 times in the challenge, but the correct word is "backward". (Minor, yes.)

**Comment by suhussai** [comment]
I'm not so sure about that. According to http://english.stackexchange.com/questions/2426/backward-versus-backwards-is-there-any-difference: 

> As an adverb, either word will do: “put the shirt on backward” or “put the shirt on backwards.” However, as an adjective, only “backward” will do: “a backward glance.” When in doubt, use “backward.”

In the case of the challenge, I believe the word `backwards` is being used to describe the verb `count`. As such, it is an adverb and in that case it doesn't matter which form is used.

According to http://grammarist.com/usage/backward-vs-backwards/
>  In British English, the use of either backward or backwards is technically correct, however the overwhelming preference is to use backward when in need of an adjective and backwards when in need of an adverb.

As such, the use of the word `backwards`, according to the above link, is correctly used in the challenge as it is being used as an adverb.

**Comment by erictleung** [comment]
Thanks @paddyofurniture for bringing up the issue!

@suhussai thanks for the links! And thanks for your points on the matter. I was okay with changing it to just `backward` but I can see the argument for keeping it `backwards`. Nonetheless, there are inconsistencies with the challenge description because there is a use of `backward` and `backwards` used in similar contexts.

I vote for going with `backward` because `backwards` appears to be used more in British English context http://dictionary.cambridge.org/dictionary/english/backwards. But I'm open other opinions.

**Comment by suhussai** [comment]
Ah, I did not see the inconsistency. In that case, I do agree that the inconsistency should be fixed. As for which form to use, I vote for `backwards` because that sounds smoother to me 😛

**Comment by valishah** [comment]
Hi @erictleung , @paddyofurniture . Can i make this change ?

**Comment by no-stack-dub-sack** [comment]
@erictleung - while I'm not a first time FCC contributor, I've actually never taken on a challenge fix since most of my work has been related to the testable projects - so, that said, I'd love to take this on. What's the verdict?

**Comment by valishah** [comment]
Hi @no-stack-dub-sack : NP, You can work on this. I will find some other one.

**Comment by erictleung** [comment]
@valishah @no-stack-dub-sack thanks to both of you for wanting to help fix this! First thing's first is we need to decide on `backward` or `backwards`. Even though I voted for `backward` solely on British vs American English, `backwards` actually sounds more natural to me 😄  

It looks like @valishah got to it first, but I'm fine with whoever wants to go at it 👍

**Comment by no-stack-dub-sack** [comment]
@valishah If that's cool with you, then thanks! We were certainly cutting it close, I think it was actually by 4 seconds!

@erictleung hmmm, I'm a bit torn. Honestly, I think "backwards" sounds more natural for the first 2 occurrences, and "backward" sounds more natural for the 3rd... i.e. the way it already is.

But if we need to keep things consistent, I would say "backward" is probably the better choice to cover all 3 occurrences.

**Comment by shashank7200** [comment]
Hey @paddyofurniture,

> Backwards

 In the Problem discussed above, the keyword '**backwards**'  fits right ,because in the [Challenge](https://www.freecodecamp.com/challenges/count-backwards-with-a-for-loop), we are dealing with a series of numbers which are counted & represented continuously (without any break).

Here every number is a **predecessor** of the next number in **descending** order. So, for continuous crawling of numbers, **backwards** fits right.

**Comment by paddyofurniture** [comment]
From everything that I've read, "backward" is appropriate usage in the United States in this instance, and "backwards" in typical usage in the UK. 

http://www.quickanddirtytips.com/education/grammar/backward-versus-backwards
http://grammarist.com/usage/backward-vs-backwards/
http://www.gingersoftware.com/english-online/spelling-book/confusing-words/backward-backwards

I'm fine with whatever you all decide.

**Comment by no-stack-dub-sack** [comment]
@paddyofurniture @shashank7200 @erictleung It seems like there's still no clear consensus here - maybe I should loop in @HKuz and let her make the call as she's our resident language expert and has QA'd the majority of the language in our curriculum update. 

Heather, what do you think?

**Comment by HKuz** [comment]
Wow, 'resident language expert' is a generous description @no-stack-dub-sack, not sure I would quite put it that way. (But I'm printing that out and looking at it every time I feel my writing is garbage 😜). 

I guess I haven't fully appreciated the nuances between `backward` and `backwards` until now, so thank you for those links @suhussai, and all the input from everyone else. To recap the discussion so far, looks like each reference in the challenge is an adverb (tied to the verb 'count'), and American English allows either usage in that case. I don't feel strongly either way, but if I were speaking those lines, I think I would say `backwards`. If you want me to make the call, go with that, and I'll take full responsibility if the Grammar Police crack down on us... :shipit: 🚓

**Comment by no-stack-dub-sack** [comment]
@HKuz Well, it seemed like we needed an arbitrator, so I figured - who better? Looks lie we've got a couple of thumbs up on your decision, so I'm going with that!

**Comment by no-stack-dub-sack** [comment]
I am still on this, but having trouble with something - I just made a PR for another issue on a different branch (PR not yet accepted or I would not be having this issue), and in making the change for this issue, the branch I've created has the changes I made for the other issue as well. I'm thinking it makes more sense for this PR to only have the changes needed for this fix, so I'm trying to figure out how to push only that commit...

**Comment by HKuz** [comment]
@no-stack-dub-sack - you may have accidentally created the branch to do this change when you were still on your other PR branch (instead of checking out `staging` and branching from there). You'll want to start fresh off of `staging` for this PR, then you can rebase this new branch if that other PR is accepted first. You have a couple options, but if you haven't done a ton of work, the easiest is to probably re-create the branch and re-do your changes (commands included for completeness). You can go back to your local `staging` branch (`git checkout staging`), rebase so it's the latest from fCC (`git pull --rebase upstream staging`), then create your new branch (`git checkout -b fix/newbranchName`) and do your edits for this.
