### ISSUE TITLE
wont accept answer

### ISSUE THREAD

**Issue by brenanabread** [freeCodeCamp/freeCodeCamp#12484]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%208%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AlastNameLength%20%3D%20%22Lovelace%22.length%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 8;
var lastName = "Lovelace";

// Only change code below this line.

lastNameLength = "Lovelace".length;



```

**Comment by erictleung** [comment]
@brenanabread Thank you for reporting this issue. Your code is almost correct. Please use variables rather than strings themselves.

>Use the `.length` property to count the number of characters in the `lastName` variable and assign it to `lastNameLength`.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
