### ISSUE TITLE
Manipulate Arrays With pop - 

### ISSUE THREAD

**Issue by Riverino** [freeCodeCamp/freeCodeCamp#12520]
Hi, I'm going through the "Manipulate Arrays With pop" and the test gives discordant information.

my code is:

var myArray = [["John", 23], ["cat", 2].pop()];
var removedFromMyArray = myArray.pop();

Now, the test gives me the green light for: 

myArray should only contain [["John", 23]].
Use pop() on myArray

but it still states:

removedFromMyArray should only contain ["cat", 2].

But if "myArray should only contain [["John", 23]]", it tells me that with my code I have taken "["cat", 2]" out .

Can someone explain to me?

Many thanks

https://www.freecodecamp.com/challenges/manipulate-arrays-with-pop#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%0A%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D.pop()%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D.pop()%5D%3B%0Avar%20removedFromMyArray%20%3D%20myArray.pop()%3B%0A%0A%0A

#### Browser Information

* Browser Name, Version: google
* Operating System: Os
* Mobile, Desktop, or Tablet: desktop

 
 
![image](https://cloud.githubusercontent.com/assets/24432581/21951727/a122d40e-da5f-11e6-81c7-57f83e715ea7.png)

**Comment by WederPachecoSilva** [comment]
Hello, Riverino. I hope you can understand my english without any issue. This issue you are talking about is due to a simple syntax error on line 12 of your code. This is how you did it:
**var myArray = [["John", 23], ["cat", 2].pop()];**
Notice that you should close the array entirely before you call the POP method. Besides, there was no need to copy and reinstantiate myArray. If you remove the line 12 of your code you should be able to succeed.
This is how I did:
// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray= myArray.pop();

**Comment by Riverino** [comment]
Hi Weder, thanks for your explanation. 
I have tried it again with this code:
var removedFromMyArray = myArray.pop();

and it worked. It is strange, because it's the code I used the first time I attempted to solve the challenge. Am I wrong, or sometimes the test simply doesn't work, so that you are led to question your answer?
Anyway, thank you again!

Happy coding!

**Comment by raisedadead** [comment]
@Riverino @WederPachecoSilva thanks guys, but the issue tracker is for reporting bugs only, please seek and provide all coding assistance in chat rooms and the forum.

**Comment by OgunniyiOwamamwen** [comment]
THE CODE ANSWER
Manipulate Arrays With pop


// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();

**Comment by raisedadead** [comment]
@OgunniyiOwamamwen please do not post solutions on the tracker, it would be best if you could guide users on chat and in the forum
