### ISSUE TITLE
this part does not run properly

### ISSUE THREAD

**Issue by Jean1981** [freeCodeCamp/freeCodeCamp#12531]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<P>Hello Paragraph</P>

```

**Comment by OFFLlNE** [comment]
The issue tracker is for reporting bugs only.

Please use the [chatroom for help](https://gitter.im/FreeCodeCamp/Help)

Currently you need to have lowercase `p`, not uppercase P

**Comment by no-stack-dub-sack** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
