### ISSUE TITLE
Sum All Odd Fibonacci Numbers - Crashing with creation of For loop.

### ISSUE THREAD

**Issue by alexytlee** [freeCodeCamp/freeCodeCamp#12534]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=var%20arr%20%3D%20%5B%5D%3B%0A%0Afunction%20sumFibs(num)%20%7B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20arr.push(i)%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0AsumFibs(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr = [];

function sumFibs(num) {
  for (var i = 0; i < num; i++) {
    arr.push(i);
  }
  return arr;
}

sumFibs(4);

```

In the for loop, when you enter a value in the test expression i.e. 5, it doesn't crash. But once you enter "num" variable in the test expression part of the for loop as shown above, it crashes.

I have tested it on my desktop, and my MacBook and the issue replicates.

**Comment by no-stack-dub-sack** [comment]
@alexytlee This is because some of the numbers being passed in by the test suite are comparatively very large next to a number as small as 5. As I'm sure you realize, the solution for this challenge will have a bit more going on with it than what you've posted above - right now, when you run this code, the browser is trying to create several new arrays, some which are as long as `4000000` elements - this is too much for it to handle. So I would say, try to get a bit more code going before testing the solution.

That said, @FreeCodeCamp/moderators, has this come up before does anyone know? Creating a simple `for` loop is a natural step working towards the solution of this challenge. I feel like I may have seen this issue before - is there something we can do to prevent this? Maybe just as simply as editing the test cases to have smaller numbers?

**Comment by alexytlee** [comment]
@no-stack-dub-sack Ah, that makes sense, I was doing my usual work through of the problem. I typed in 7000 and it was still ok. I didn't notice that it was going to be as long as 4000000 elements.

I managed to solve the solution without using arrays, but I was wondering why it wouldn't work! Thanks!

**Comment by no-stack-dub-sack** [comment]
@alexytlee No prob! Actually this issue did pop up recently, I just checked, and it looks like it's been fixed in staging if I'm not mistaken... so you are def not the only one experiencing this issue.
