### ISSUE TITLE
In Sum All Numbers in a Range, remove Reduce as a helpful link.

### ISSUE THREAD

**Issue by SeanGallen** [freeCodeCamp/freeCodeCamp#12547]
#### In all the solutions provided, reduce is not used.

If a helpful link is given, it should be used as a possible solution.  People spend hours studying and trying to use these helpful functions to solve a problem.  If we don't even use them in the 3 solutions given in the [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Sum-All-Numbers-In-A-Range). Is it really helpful?  

Even in the wiki, it refers to a "for loop" as a helpful link and not reduce.  I would make a pull request but I am unsure if I have a right to do so.  Thank you.

**Comment by SeanGallen** [comment]
Well, I think it is a bug if we are offering them a misdirected route.

**Comment by raisedadead** [comment]
@SeanGallen the wiki you are pointing to is out of date, and has been since deprecated. There is a notice at the right and the bottom as well.

We have moved it our forum, please proceed there and have a look. If the solution doesnt look apt to you, you can always comment on the article in the forum, or edit it too.

Thanks and happy coding!

**Comment by SeanGallen** [comment]
Thank you for addressing my concern.  The forum uses the same solutions as the wiki and the issue with the lack of a reduce solution is mention by a few commenters on the forum.  I will address my opinion there and hopefully find an agreeable solution.  I only mention this because I think it will help students. Again thank you, @raisedadead
