### ISSUE TITLE
Making the H2 Blue

### ISSUE THREAD

**Issue by MakeCodeOrDie** [freeCodeCamp/freeCodeCamp#12559]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20.blue-text%20%7B%20%0A%20%20%20%20color%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%20%20%3Ch2%20class%3D%22blue-text%22%3ECatPhotoApp%3C%2Fh2%3E%20%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .blue-text { 
    color: blue;}
</style>
  <h2 class="blue-text">CatPhotoApp</h2> 
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by erictleung** [comment]
@MakeCodeOrDie Thank you for reporting this issue. Your code is incorrect. Please reread the last paragraph of the challenge for help.

> Delete your `h2` element's `style` attribute and instead create a CSS style element. Add the necessary CSS to turn all `h2` elements blue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
