### ISSUE TITLE
Size your images problem

### ISSUE THREAD

**Issue by rohgaj6809** [freeCodeCamp/freeCodeCamp#12564]
Hi,
   I am having some trouble with the "Size your Images" challenge. The challenge is to create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.
I have done the following:
    
    .smaller-image {
    width: 100px;
  }  

and I placed this within the elements <style> and </style>, but I am getting an error message and am unable to move on to the next challenge. Am I doing something wrong?
                      

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by no-stack-dub-sack** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

P.S. If that is the only place you added code, then yes, you are missing something 😉 . Good luck!
