### ISSUE TITLE
[beta] Night mode should be active on page load

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#12560]
We're on a roll with improving the night mode! 👍 

#### Issue Description

When the page has to load (when coming from a page that is not reactified, first opening the page or reloading), it takes a bit for the night mode to active. This flash of light can be a bit annoying I must say ⚡️ 😅

I'm not certain about the cause, or what a solution would be.

https://github.com/freeCodeCamp/freeCodeCamp/issues/12538#issuecomment-272866305
/cc @Bouncey

**Comment by Bouncey** [comment]
We would need to look at the difference in how the production site does `night mode` and how to implement it into the react version so that `night mode` persists correctly between sessions

The delay on first load/reload is probably caused by the eval time of our bundle, which is HUGE! The time to first interaction (and night mode activating) is held up by the time it takes for react to take over from the server-side rendered html page. In this period, you might notice some 'jank' or juddering of the codemirror skeleton animation.
