### ISSUE TITLE
Suggestion: Allow use of ⌘+Enter on OS X to advance

### ISSUE THREAD

**Issue by mocxd** [FreeCodeCamp/FreeCodeCamp#1256]
This would be much more intuitive / ergonomic for mac users imho as opposed to ctrl-enter, and mimics gmail keystroke behavior on mac browsers. :)

**Comment by LumenTeun** [comment]
That sounds like a good idea, but since I don't have a Mac, the Ctrl+Enter code is spread out all over the place, and [the cmd key has different keycodes in different browsers](http://stackoverflow.com/a/3922353), I'm going to let someone else have at it.

Shouldn't be too hard technically though, just a lot of testing and searching required.
