### ISSUE TITLE
Profile is logging challenges for the wrong date. 

### ISSUE THREAD

**Issue by zanetagrant** [freeCodeCamp/freeCodeCamp#12589]
Challenge [Declare JavaScript Variables](https://www.freecodecamp.com/challenges/declare-javascript-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

I'm on the East coast of the US at 10:15PM EST on 01/17/2017, and I am completing my challenges for today, but they are logged on my profile as being completed on 01/18/2017. This restarted my streak, and I would like to keep it going :'(. Can anybody help, please? Thank you!

**Comment by no-stack-dub-sack** [comment]
@zanetagrant Thanks for reporting this. This is an interesting issue.

@freeCodeCamp/moderators has this come up before? I feel like I may have seen a similar issue in the past, but just ran a quick search and couldn't find a closed issue that was similar. I'm guessing challenge completions are being logged based on West Coast time? 

Anyone have any thoughts?

**Comment by sludge256** [comment]
We've had a few PRs in regards to this and similar issues before. I'm not sure what the current status or plan is on dealing with the discrepancies.

**Comment by no-stack-dub-sack** [comment]
@raisedadead I believe you were looking at one of the issues mentioned above ☝️ 
Do you recall what, if anything, was decided?

**Comment by raisedadead** [comment]
Well, mostly other priority issues took over that particular one, and it's still an open issue. 

The whole  point being there is an obvious difference when the user is logged in and when they are not. The whole trouble is mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/7468#issuecomment-196556171

That is still the case to the best of my knowledge.

At the best this being a huge UX issue, needs a major refactor in the way we store the progress points and plot them on the streak graph. This can now be more viable because, we are moving to react, and will being doing lesser things server side.

I think @Bouncey can guide on what's needed more. But at the best this is the birds-eye view of the current status.

**Comment by Bouncey** [comment]
Alas, the profile page has not been reactified, so it is all still being
done on the server.

I don't know if there any plans to reactify this section any time soon.

Refactoring the streak to use only UTC as a reference should fix it, but
this could effect legacy streak counts. It would be worth a forum post
explaining the change to the streak and brownie point allocation change if
they go ahead.

**Comment by raisedadead** [comment]
I'll close this in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/12589
