### ISSUE TITLE
Escaping Literal Quotes in Strings 

### ISSUE THREAD

**Issue by tim12302** [freeCodeCamp/freeCodeCamp#12601]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ="\"I am a \"double quoted\" string inside \"double quotes\"\"." ;



```

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
In your case [JS Helproom](https://gitter.im/FreeCodeCamp/HelpJavaScript)

If you think I'm wrong please add further clarification. 
Thank you, and happy coding.

**Comment by dhcodes** [comment]
@tim12302 thanks for the issue. I've taken a look at your code and believe you have an error there. Someone in the help chat will be glad to assist you. Closing this for now.
