### ISSUE TITLE
Console is returning correct string but still being marked as incorrect 

### ISSUE THREAD

**Issue by sashat14** [freeCodeCamp/freeCodeCamp#12642]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3E%3D%20par%20%2B%203)%20%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%20%0A%20%20else%20if%20(%20strokes%20%3D%3D%20par%20%2B%202)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if%20(%20strokes%20%3D%3D%20par%20%2B%201)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20%26%26%20par%20%3E%202)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20-%20par%20%2B%201)%20%7B%0A%20%20%20%20return%20%22Hole-in-One!%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20-%201)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3C%3D%20par%20-%202)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(1%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes >= par + 3) {
    return "Go Home!";
  } 
  else if ( strokes == par + 2) {
    return "Double Bogey";
  }
  else if ( strokes == par + 1) {
    return "Bogey";
  }
  else if (strokes == par && par > 2) {
    return "Par";
  }
  else if (strokes == par - par + 1) {
    return "Hole-in-One!";
  }
  else if (strokes == par - 1) {
    return "Birdie";
  }
  else if (strokes <= par - 2) {
    return "Eagle";
  }
 
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(1, 1);

```

**Comment by chawes13** [comment]
The test is case sensitive. Change "Hole-in-One!" to "Hole-in-one!" to pass the challenge.

**Comment by erictleung** [comment]
@sashat14 Thank you for reporting this issue. Yes, the output is case sensitive, as @chawes13 mentions.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
