### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by tgitari** [freeCodeCamp/freeCodeCamp#12641]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%3D%20%22I%20am%20a%2C%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr= "I am a, \"double quoted\" string inside \"double quotes\"."; // Change this line

```

**Comment by erictleung** [comment]
@tgitari Thank you for reporting this issue. You're almost there. There's no comma within the string. Please take a look at the required string once more.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
