### ISSUE TITLE
Size your Image

### ISSUE THREAD

**Issue by LucasVenancio** [freeCodeCamp/freeCodeCamp#12648]
Challenge [Size your Images]
My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }
 p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
I have checked another post regarding the same issue, I have checked the code, I have changed the browser and I can´t find the solution, its not working

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

Your code is wrong. You need to apply smaller-image class to your image too
Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Thank you, and happy coding.

**Comment by himasagarsai** [comment]
you should apply class to your image also so code will be like this
 <img class="smaller-image"src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
hope this works!!!!
Happy coding:)

**Comment by raisedadead** [comment]
@himasagarsai we strongly recommend you to provide help in chat rooms and forum only, this tracker if for bugs only.
