### ISSUE TITLE
Javascript not compiling in ES6 challenges (Beta site)

### ISSUE THREAD

**Issue by Ilyes-Hammadi** [freeCodeCamp/freeCodeCamp#12667]
The javascript is not compiling or have any syntax highlighting in ES6 challenges.

#### Challenge Name
[ES6 challenges](http://beta.freecodecamp.com/en/map#ES6)

#### Issue Description
The issues happen when starting the ES6 coding challenges 

#### Browser Information

* Chrome, 55.0.2883.95 (64-bit): 
* MacOS Sierra 10.12.2: 
* Desktop: 

#### Screenshot
![screenshot](https://farm1.staticflickr.com/392/32390010106_5c77ab049b_b.jpg)

**Comment by systimotic** [comment]
This looks like an issue with the wrong challenge type in the seed to me. From looking at the seed, I can't quite tell what the correct type would be.

These challenge use `challengeType: 0`. The basic data structures also use this type and have the same issue.
The basic Javascript challenges use `challengeType: 1`, they do work and look fine. The debugging, regular expression, OOP and functional programming challenges also use this type. They do have some linting problems because of ES2015.
The algorithm challenges use `challengeType: 5` and work fine.

My guess is that these challenges should use `challengeType: 1` as well. The linting problems should probably be handled in a separate issue.

@freeCodeCamp/moderators Could somebody confirm that this is the correct change? I'd be happy to make a PR if that's the case.

**Comment by HKuz** [comment]
Good detective work, @systimotic - you're right about the `challengeType`. Type 0 is for the HTML/CSS challenges that use the mobile phone output. I quickly checked on a local branch that making the change to `challengeType: 1` for a handful of challenges fixes the syntax highlighting and the tests passed. If you want to make that change for both ES6 and Basic Data Structures in a PR, would be awesome! Those sections were just seeded and haven't been QA'd at all, so the more people that can work through them, the better!

**Comment by systimotic** [comment]
@HKuz Awesome, thanks for confirming! PR is on the way...

**Comment by Ilyes-Hammadi** [comment]
@HKuz @systimotic Thanks for your help guys, it's my first issue on FCC and i hope it will not be the last one, i am so excited to contribute and i hope to push some PR in the future !! 👍

**Comment by raisedadead** [comment]
@Ilyes-Hammadi 👏 looking forward to it.. 👍

**Comment by systimotic** [comment]
@Ilyes-Hammadi Awesome! Thanks a lot for reporting this issue. With the new curriculum there's a lot of work to be done, and people checking out the challenges is extremely helpful! You should definitely hang around on GitHub and our contributors chatroom on Gitter.
