### ISSUE TITLE
i feel like iam doing the right thing but its still wont let me go to the next challenge

### ISSUE THREAD

**Issue by miyako10** [freeCodeCamp/freeCodeCamp#12666]
```

**Comment by OFFLlNE** [comment]
@miyako10  Thank you for reporting this issue.

Your code was wrong. I presume that you found the mistake if you deleted all your text
Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Thank you, and happy coding.
