### ISSUE TITLE
[Beta] Basic css tells to do something we have not learned yet

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#12682]
#### Challenge Name
[Basic Css: Specify How Fonts Should Degrade](http://beta.freecodecamp.com/en/challenges/basic-css/specify-how-fonts-should-degrade)

#### Issue Description
Instructions: 
Now comment out your call to Google Fonts, so that the Lobster font isn't available. Notice how it degrades to the Monospace font.

But commenting comes in Basic HTML and HTML5, which is After basic CSS on the map.

Suggestion for solution. We could tell the user to delete the call to Google for the font.

**Comment by HKuz** [comment]
@OFFLlNE - thanks for reporting this issue. Yes, the ordering of the sections was off so Basic CSS was displaying before Basic HTML and HTML5. There's a pending PR ( #12663 ) that fixes the ordering, so the Comment HTML challenge will come before you're asked to comment the fonts in this one. I'm going to close this issue because there's a pending fix. Thanks for your help reviewing the Beta site!
