### ISSUE TITLE
it is not running

### ISSUE THREAD

**Issue by atulsingh378** [freeCodeCamp/freeCodeCamp#12691]
Challenge [Target HTML Elements with Selectors Using jQuery](https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {    $("button").addclass("animated bounce");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by systimotic** [comment]
Hi @atulsingh378! Thank you for reporting this issue.

There's a small issue with your code. Keep in mind that Javascript is case-sensitive, meaning that where you place UPPER and lower case letters matters.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by atulsingh378** [comment]
could you please highlight issue in this code...

**Comment by atulsingh378** [comment]
because i tried my best to resolve it and checked every case-sensitive issue and i didn;t find any issue

**Comment by atulsingh378** [comment]
thankyou i fix it
