### ISSUE TITLE
[beta] Backend challenges do not work

### ISSUE THREAD

**Issue by Cyclokitty** [freeCodeCamp/freeCodeCamp#12694]
Challenge [using-packagejson-the-core-of-any-nodejs-project-or-npm-package](https://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

"author": "Jane Doe",


```

I tried the code with "author": "Laura Veee", and it did not work. I reset the challenge as well.

**Comment by Y4T9Code** [comment]
Me too

**Comment by systimotic** [comment]
Hi @Cyclokitty! Thank you for reporting this issue.

The new backend challenges do indeed not work yet. I believe this is waiting for https://github.com/freeCodeCamp/freeCodeCamp/pull/11058

**Comment by systimotic** [comment]
If you're reading this, you saw that the issue was closed, which means that this issue has been fixed! 🎉

**Comment by nealthom** [comment]
I tried it today and it didn't work for me.

**Comment by systimotic** [comment]
@nealthom Hi! There were some more issues with them, so that's absolutely possible. I think they have been resolved but need to be deployed to the beta. They should be working on the next deploy 👍 
Do keep in mind that this is the beta, so there may still be broken tests and other bugs, even after the deploy. If you do stop any, please let us know!
