### ISSUE TITLE
Issue with explanation of challenge "Iterate Through an Array with a For Loop"

### ISSUE THREAD

**Issue by Rahul22587** [freeCodeCamp/freeCodeCamp#12702]
I just want explanation of the challenge 'Iterate Through an Array with a For Loop'
will you explain that I already complete this challenge but I wanna know how its come "20" and how much time loop work?

**Comment by systimotic** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
