### ISSUE TITLE
[Beta] Testcase not working for challenge "Convert strings to url slugs"

### ISSUE THREAD

**Issue by taltmann42** [freeCodeCamp/freeCodeCamp#12703]
Challenge [apply-functional-programming-to-convert-strings-to-url-slugs](http://beta.freecodecamp.com/en/challenges/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

The following code doesn't pass the `" Winter Is Coming"`-testcase, but when run in the dev-tools, it correctly returns "winter-is-coming"

```js
    
    
// the global variable
var globalTitle = "Winter Is Coming";

// Add your code below this line
function urlSlug(title) {
  return title.toLowerCase().trim().split(" ").join("-");
};
// Add your code above this line

var winterComing = urlSlug(globalTitle); // Should be "winter-is-coming"

```

**Comment by systimotic** [comment]
Hi @taltmann42! Thank you for reporting this issue.

There is indeed a problem with this test, but your solution will still not pass if the tests are fixed. 😄 
The tests for this challenge are [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/functional-programming.json#L1498). The problem is that there is a double space between `Is` and `Coming`. HTML does not display double spaces.
To work around this, I think using `&nbsp;` in the message should do the trick.

@taltmann42 If you want to take this on, you're more than welcome to! If not, no problem, please let us know and I'll open it up to everybody.

**Comment by taltmann42** [comment]
HI @systimotic thanks for letting me know. Right, with a whitespace-regex in split, the tests all succeed.
Well that would be the first time I'm contributing to freecodecamp or an open source-project in general so I'd have to read through the guidelines and how to actually do a pull-request ;)

**Comment by systimotic** [comment]
@taltmann42 Awesome! If you need help, you can pop over to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by taltmann42** [comment]
@systimotic okay so I managed to setup the local version, tested my changes and made a (hopefully) correct pull-request. Can you review it?

**Comment by systimotic** [comment]
@taltmann42 Wow, that was fast! I'm looking at your pull request now...
