### ISSUE TITLE
[beta] Use a Pre-defined Scale to Place Elements

### ISSUE THREAD

**Issue by Renestl** [freeCodeCamp/freeCodeCamp#12716]
Challenge [use-a-predefined-scale-to-place-elements](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/use-a-predefined-scale-to-place-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The challenge does submit as is, just wanted to alert that it starts up with a small piece missing code. I placed a comment in the snippet below.

n the 

```html
     
     
<body>
 <script>
      
   svg.selectAll("text")
      .data(dataset)
      .enter()
      .append("text")
      .text((d) =>  (d[0] +  // 2 plus signs but ", " missing in this line
+ d[1]))

 </script>
</body>

```
     
![screenshot_5](https://cloud.githubusercontent.com/assets/13346359/22178883/104748a2-e009-11e6-8a75-dc7fca3c37ef.png)

**Comment by systimotic** [comment]
@Renestl Thanks for QA'ing and reporting this issue!
Since you reported it, you get dibs on fixing it if you want. 🙂 If you don't want to, please let us know and we'll open it up to first timers. 👍 

The seed for this challenge is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/04-data-visualization/data-visualization-with-d3.json#L2107). Remember to escape the quotes with a backslash.
To get your local development environment set up, check out our [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).
If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

Happy coding! 😄
