### ISSUE TITLE
.pink-text is a class right?

### ISSUE THREAD

**Issue by tonygreene** [freeCodeCamp/freeCodeCamp#12717]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3Apink%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color:pink
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by ChrisD1986** [comment]
Which level of abstraction has precedence?

**Comment by ananaymital** [comment]
@tonygreene you have a small error in your code. Missing a semi-colon are we?
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.

Happy Coding :)

**Comment by ChrisD1986** [comment]
pink;

**Comment by erictleung** [comment]
@tonygreene Thank you for reporting this issue. You're missing a semi-colon as other have pointed out.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
