### ISSUE TITLE
[beta] When new challenge loads, sidebar scrolling does not return to top

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#12710]
If you've scrolled down the instructions area on a challenge and then complete that challenge, the next one that loads does not jump back to the top of the instructions area.

This means the user is required to scroll back to the top to start reading the directions of the new challenge.

I found a suggestion on StackOverflow to add the following lines. It may not be the right approach for fCC but could point in the right direction:
```
componentDidUpdate() {
  ReactDOM.findDOMNode(this).scrollTop = 0
}
```

**Comment by mitron6** [comment]
This more critical than it appears because the failure to scroll back to the top can cause students to miss important information. For some challenges, when a new challenge loads, there are no visual clues that the instructions displayed are not the beginning of the challenge text. So the student starts to work the challenge in the middle of the instructions potentially creating confusion, mistakes, and frustration.

**Comment by dhcodes** [comment]
Closing in favor of #13726
