### ISSUE TITLE
Declare the Doctype of an HTML Document not completing

### ISSUE THREAD

**Issue by randallfine** [freeCodeCamp/freeCodeCamp#12718]
![declare the doctype of an html document](https://cloud.githubusercontent.com/assets/17617833/22181021/d2203b1c-e047-11e6-870a-576655b86996.png)
Challenge [declare-the-doctype-of-an-html-document](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/declare-the-doctype-of-an-html-document) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    <!DOCTYPE html>

<html>
<h1>Test</h1>
</html>




    ```

**Comment by ChrisD1986** [comment]
What's the issue? doctype.htm+wrap=?

**Comment by randallfine** [comment]
I guess I didn't leave comments. The last case is failing (see attached pic)

**Comment by systimotic** [comment]
@randallfine Thank you for reporting this issue!

I just checked this out, and got really confused, because using the test from the seed files locally worked fine. 😕 
Turns out this has already fixed! 🎉 The fix has been done, but has not been deployed to the beta yet. You'll see it appear the next time beta is updated.

Thanks again for reporting this issue, and happy coding!
