### ISSUE TITLE
Add "New" and "Required" flags to reactified challenge map

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12721]
#### Issue Description
Currently, our reactified challenge map does not show the "New" flag next to new challenges.

It does show a * next to required challenges, but this necessitates us having a description at the top of the challenge map explaining what these *'s mean:

![](https://www.evernote.com/l/Ar_TtL8RNCVNWbyHJBcPLATubM4e4kYDcwMB/image.png)

I propose that instead of using the *, we just use the words "Required for Certificate" Even though this is longer, it is unambiguous.

**Comment by ChrisD1986** [comment]
/unambiguous!


On Jan 22, 2017 3:16 AM, "Quincy Larson" <notifications@github.com> wrote:

Challenge Name Issue Description

Currently, our reactified challenge map does not show the "New" flag next
to new challenges.

It does show a * next to required challenges, but this necessitates us
having a description at the top of the challenge map explaining what these
*'s mean:

<https://camo.githubusercontent.com/a0c3870cffe82d50225c2eabb02b46edd7c73164/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41725f54744c38524e43564e576279484a4263504c415475624d3465346b594463774d422f696d6167652e706e67>

I propose that instead of using the *, we just use the words "Required for
Certificate" Even though this is longer, it is unambiguous.
Browser Information

   - Browser Name, Version:
   - Operating System:
   - Mobile, Desktop, or Tablet:

Your Code



 Screenshot

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/12721>, or mute the
thread

**Comment by tommygebru** [comment]
Very cool thanks @dhcodes
