### ISSUE TITLE
This is a hot mess

### ISSUE THREAD

**Issue by olddognewtrix123** [freeCodeCamp/freeCodeCamp#12740]
Challenge [using-packagejson-the-core-of-any-nodejs-project-or-npm-package](http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instructions read "Add your name to the author-field in the package.json of your HyperDev project."

WHAT HYPERDEV PROJECT??????

I am testing this using this particular project as a starting point. I am not aware of any"HyperDev" project.

This leads me to ask who exactly did the designers have in mind when writing this? Other designers? Software professionals who already speak these languages fluently? What about students who might be a little lost already??? 

Please please please provide better direction to this and all of the beta testing resources.

After nine months of steadily working through all of the original Front End and Data Vis challenges, earning both certs, feeling my way through the extremely obscure node and mongo tutorials, then tackling the first three microservice projects,  I am now about ready to give up on FCC entirely if this is how things are going to go.

**Comment by raisedadead** [comment]
> This leads me to ask who exactly did the designers have in mind when writing this? Other designers? Software professionals who already speak these languages fluently? What about students who might be a little lost already???

The entire platform is 100% free and is developed and designed by very dedicated, and hard working, contributors who dedicate their time and effort in bringing this to learners for free. I must say that these contributors have done an amazing job in this as well. This needs no justification at all.

Yes, this does bring in a few issues, but that's the reason we have "beta" where we are under quality checking of the challenges and remove issues and bugs that have crept in over long development cycles and multiple hard-working contributors.

HyperDev (a platform that we use) was renamed to Gomix only recently, and the challenges were drafted even before that. We are in the process of updating this.

Thanks a lot for having a look at our curricula, but rest assured, when we have it on the main website, these bugs would have been resolved.

We request you not to try the beta website and keep on the main website at https://freecodecamp.com.

Since this is an Open Source voluntary effort, we cannot guarantee you timelines, but we can guarantee you that when the challenges do go live they will be free of basic issues as this, thanks to the voluntary contributors who keep the contributions coming to make this available to you for free.

Happy coding and thanks for your feedback.

**Comment by olddognewtrix123** [comment]
Thank you for the response. Please remember that anyone who is at the stage
I am at with the FCC challenges has a very specific goal in mind: to get to
the point where they can contribute to the open source projects. To that
end, a lot of time has been committed, a lot of work has been done, and
personal sacrifices have been made.

**Comment by saracarlile** [comment]
I was coming here to add that I couldn't find specific instructions on how to create a HyperDev project as well,  and wanted to make sure I wasn't missing anything.   It looks like these instructions need to be added prior to the section Managing Packages with Npm: Using Package.json, The Core of Any Node.js Project or npm Package.

It would also be helpful to change the reference of HyperDev on all the challenges that use this name to Gomix.  

Thanks to all the contributors.

**Comment by raisedadead** [comment]
@saracarlile we are in the process of updating these, and should be fixed when we release the challenges into production.

The migration is tracked via https://github.com/freeCodeCamp/freeCodeCamp/issues/12071

**Comment by Em-Ant** [comment]
@olddognewtrix123 sorry. The back-end challenges are still under development. 

The view (elements of the page, and how they are placed on the screen ) that you see now is not the final one. It still needs to be released. There should be the url of a boilerplate project hosted on hyperdev (now https://gomix.com they renamed it) to be forked, and a form where you can insert the url of the cloned project after you completed it.

**Comment by Em-Ant** [comment]
@raisedadead it's not the same issue as https://github.com/freeCodeCamp/freeCodeCamp/issues/12071. In this case a special view all for the back-end projects is missing. @BerkeleyTrue is working on it. Should I reopen this ?

**Comment by raisedadead** [comment]
@Em-Ant we have freeCodeCamp/freeCodeCamp#12694  for the backend view already.

**Comment by raisedadead** [comment]
Let's continue on the original open threads instead. Thanks a lot for chiming in.
