### ISSUE TITLE
Updating Object Properties answer without semi colon

### ISSUE THREAD

**Issue by kuwood** [freeCodeCamp/freeCodeCamp#12749]
#### Updating Object Properties

https://www.freecodecamp.com/challenges/updating-object-properties#?solution=%0A%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%0A%7D%3B%0A%0AourDog.name%20%3D%20%22Happy%20Camper%22%3B%0A%0A%2F%2F%20Setup%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyDog.name%20%3D%20%22Happy%20Coder%22%3B%0A%0A

#### Issue Description

When submitting the answer without a semi colon: `myDog.name = "Happy Coder"`
it produces a type error: `TypeError: "Happy Coder" is not a function`

#### Browser Information

* Browser Name, Version: Google Chrome Version 54.0.2840.90 (64-bit)
* Operating System: Manjaro 16.10 Fringilla
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

`myDog.name = "Happy Coder"` does not work.
`myDog.name = "Happy Coder";` works

#### Screenshot

![screenshot from 2017-01-22 12-54-00](https://cloud.githubusercontent.com/assets/6320220/22185866/f85caf36-e0a1-11e6-9761-c06a07c26543.png)

**Comment by raisedadead** [comment]
Agreed we should not be checking for semi colons and probably need a better parsing for the script.
/cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
> Agreed we should not be checking for semi colons and probably need a better parsing for the script.

We are not checking for semicolons. This is not a failure of our parsing script but how the browser interprets JavaScript.

The tail of this challenge (code added after users code) is an Immediately Invoked Function Expression (IIFE). Without the semicolons and because white space is meaningless in JavaScript, the browser interprets the IFFE  following `"happy coder"` as a function call instead of an expression to evaluate (`myDog.name = "Happy Coder"()`). This, of course, is not a function so it cannot be called like a function. This is why semicolons are required and good practice.

This is also why you see the lint error without the semicolons. We do not wrap the error you see because this is a common JavaScript error and campers should get used to seeing it.

While coding on the freeCodeCamp site we encourage the use of semicolons. You are free to omit them on your own projects, though.

Happy Coding.
