### ISSUE TITLE
<!-- FreeCodeCamp Issue Template -->  <!-- Please provide as much detail as possible for us to fix your issue --> <!-- Remove any heading sections you did not fill out -->  #### Challenge Name <!-- Insert link to challenge below -->   #### Issue Description <!-- Describe below when the issue happens and how to reproduce it -->   #### Browser Information <!-- Describe your workspace in which you are having issues-->  * Browser Name, Version:  * Operating System:  * Mobile, Desktop, or Tablet:   #### Your Code <!-- If relevant, paste all of your challenge code in here --> ```js       ``` #### Screenshot <!-- Add a screenshot of your issue -->

### ISSUE THREAD

**Issue by artityod** [freeCodeCamp/freeCodeCamp#12775]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
