### ISSUE TITLE
BETA - define the HEAD and BODY of  HTML

### ISSUE THREAD

**Issue by timotheap** [freeCodeCamp/freeCodeCamp#12777]
#### Challenge Name
Basic Html and Html5: Define the Head and Body of an HTML Document

#### Issue Description
The "example of a page's layout" doesn't show up at all for me - sorry if it's silly to report it.

#### Browser Information

* Browser Name, Version: Google Chrome 55
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop (11')

#### Screenshot
![bug1](https://cloud.githubusercontent.com/assets/23510378/22209160/c0f49f88-e185-11e6-9474-44715a5f6990.png)

**Comment by erictleung** [comment]
Thanks for the issue. There seems to be an issue with the `<blockquote>` tag, as seen on [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L2323).

**Comment by HKuz** [comment]
Hi @timotheap - thanks for raising this issue. The code that's running on Beta wasn't using escape characters for the angle brackets in the example HTML, but that's fixed on staging right now:

 
![screen shot 2017-01-23 at 12 47 37 pm](https://cloud.githubusercontent.com/assets/9591826/22215665/315b7ad8-e16a-11e6-91d6-e66a622296eb.png)


I'm going to close this issue because a fix is ready, you'll see it next time `staging` is pushed to the Beta site. Thanks so much for helping run QA on the new challenges!
