### ISSUE TITLE
"Use CSS Selectors to Style Elements" h2 disappears instead of turning blue

### ISSUE THREAD

**Issue by jlazea** [freeCodeCamp/freeCodeCamp#12784]
#### Challenge Name

Use CSS Selectors to Style Elements

#### Issue Description

"Use CSS Selectors to Style Elements" h2 disappears instead of turning blue

I tried to add in the CSS style code and it seems as though it made my h2 disappear instead of turning it blue. 

#### Browser Information

I am using Google Chrome on a MacBook Pro

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 <style>
<h2>CatPhotoApp</h2> {color: blue;}</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

 
 
```
#### Screenshot

I am using Google Chrome.

**Comment by jlazea** [comment]
![screen shot 2017-01-23 at 11 50 12 am](https://cloud.githubusercontent.com/assets/25304749/22220317/36fc4da2-e17c-11e6-8e88-f91a5e0829b8.png)

**Comment by jlazea** [comment]
![screen shot 2017-01-23 at 2 51 32 pm](https://cloud.githubusercontent.com/assets/25304749/22220320/3e429792-e17c-11e6-8da7-48cd3393e630.png)

**Comment by jlazea** [comment]
![screen shot 2017-01-23 at 2 57 33 pm](https://cloud.githubusercontent.com/assets/25304749/22220335/4c860a46-e17c-11e6-9e16-7703ff23f004.png)

**Comment by OFFLlNE** [comment]
@jlazea Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by jlazea** [comment]
Ok how is it wrong...? i followed the directions
