### ISSUE TITLE
Text missing in description. Also, cannot be completed.

### ISSUE THREAD

**Issue by jake-steele** [freeCodeCamp/freeCodeCamp#12788]
Challenge [introduction-to-html5-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/introduction-to-html5-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**This challenge has text missing in the challenge text. Also, I attempted to complete this challenge and could not due to what I believe to be a bug. I added a <main> opening and </main> closing tag and submitted but the challenge did not complete.**

```html

<h2>CatPhotoApp</h2>
<main><p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p></main>
```

**Comment by no-stack-dub-sack** [comment]
@HKuz - this issue is being addressed in #12688, correct? If so, I think we can safely close this issue for now.

**Comment by HKuz** [comment]
@jake-steele - thanks for opening this issue. Your code is correct, but this challenge has caused some grief for QA-ers because the third test had a regex escape issue. (And as you noted, the challenge text formatting was all wonky, too).

@no-stack-dub-sack - the formatting and test were fixed and merged to staging in PR #12663   which closed the original issue of #12653. I think we can close this as a duplicate of #12653 (I know it's not obvious from that issue's title).

@jake-steele - hang tight, I'm not sure when staging gets pushed to Beta to show the fix. Thanks for your help going through the new challenges 👍!

**Comment by jake-steele** [comment]
@HKuz Thank you! I'll keep going through and send in bugs as I see them. Sorry for the duplicate post! I'll try to be better about it in the future.

Keep up the good work!

**Comment by Nerajno** [comment]
Ran it today but it won't pass. It keeps telling me that my paragraph doesn't contain the required text.
(http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/introduction-to-html5-elements)

 
![untitled1](https://cloud.githubusercontent.com/assets/18251846/22856810/523cf0ea-f067-11e6-97cb-4ca8d7d2eb9c.jpg)
