### ISSUE TITLE
Chunky Monkey

### ISSUE THREAD

**Issue by mjczyt** [freeCodeCamp/freeCodeCamp#12804]
#### Chunky Monkey

https://www.freecodecamp.com/challenges/chunky-monkey#?solution=%20%20var%20lefted%2Csliced%20%3D%20%5B%5D%3B%0A%0A%20%20function%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%20%20%20%20%20%20sliced.push(arr.slice(0%2C%20size))%3B%0A%20%20%20%20%20%20lefted%20%3D%20arr.slice(size%2C%20arr.length)%3B%0A%20%20%20%20%20%20if%20(lefted.length%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20sliced%3B%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20chunkArrayInGroups(lefted%2C%20size)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%5D%2C%202)%3B

#### Issue Description

I got the correct output but can't pass the challenge.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
   var lefted,sliced = [];

  function chunkArrayInGroups(arr, size) {
      sliced.push(arr.slice(0, size));
      lefted = arr.slice(size, arr.length);
      if (lefted.length === 0) {
          return sliced;
      } else {
          return chunkArrayInGroups(lefted, size);
      }
  }


chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6, 7, 8], 2);
 
```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.(You call var outside the function, so all the tests run with that initial variable value)
Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by mjczyt** [comment]
thanks a lot
