### ISSUE TITLE
Require hidden test

### ISSUE THREAD

**Issue by dimahali** [freeCodeCamp/freeCodeCamp#12800]
Challenge [Binary Agents](https://www.freecodecamp.com/challenges/binary-agents#?solution=function%20binaryAgent(str)%20%7B%0A%20%20if(%2201000001%2001110010%2001100101%2001101110%2000100111%2001110100%2000100000%2001100010%2001101111%2001101110%2001100110%2001101001%2001110010%2001100101%2001110011%2000100000%2001100110%2001110101%2001101110%2000100001%2000111111%22%20%3D%3D%20str)%7B%0A%20%20%20%20return%20%22Aren't%20bonfires%20fun!%3F%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if(%2201001001%2000100000%2001101100%2001101111%2001110110%2001100101%2000100000%2001000110%2001110010%2001100101%2001100101%2001000011%2001101111%2001100100%2001100101%2001000011%2001100001%2001101101%2001110000%2000100001%22%20%3D%3D%20str)%7B%0A%20%20%20%20return%20%22I%20love%20FreeCodeCamp!%22%3B%0A%20%20%7D%0A%7D%0A%0AbinaryAgent(%2201000001%2001110010%2001100101%2001101110%2000100111%2001110100%2000100000%2001100010%2001101111%2001101110%2001100110%2001101001%2001110010%2001100101%2001110011%2000100000%2001100110%2001110101%2001101110%2000100001%2000111111%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function binaryAgent(str) {
  if("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111" == str){
    return "Aren't bonfires fun!?";
  }
  
  if("01001001 00100000 01101100 01101111 01110110 01100101 00100000 01000110 01110010 01100101 01100101 01000011 01101111 01100100 01100101 01000011 01100001 01101101 01110000 00100001" == str){
    return "I love FreeCodeCamp!";
  }
}

binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111");

```
this returns true and i can submit solution which is not the correct way... need some kind of hidden test i guess...

**Comment by raisedadead** [comment]
@dimahali 

Thanks a lot for the report.

We have had discussed this in the past and we will not be implementing any system to automate checking for user's intended malpractices as illustrated by your example above.

This is because, we have an open code base, and its a matter of looking up such "hidden tests" and solving them,

If someone wants to flunk thru the challenges, it's completely fine, but there is zero gain because they would ultimately not learn and any future objective of getting a job, cracking an interview needs those skills learn while actually solving a challenge.

That said we have an academic honesty policy to award certifications. And can flag users based on explicit reports of dishonesty.

Thanks once again, apologies, but will have to close this as a wontfix as decided earlier.
