### ISSUE TITLE
Platform refusing to accept correct response to excersise

### ISSUE THREAD

**Issue by kazoo135** [freeCodeCamp/freeCodeCamp#12819]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22Firstline%5Cn%5C%5CSeondline%5C%5C%5CrThirdline%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "Firstline\n\\Seondline\\\rThirdline";



```

**Comment by erictleung** [comment]
@kazoo135 Thank you for reporting this issue. Your code is almost there. Take a look at the text you need to type out more closely. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
