### ISSUE TITLE
Platform refusing to accept the correct answer

### ISSUE THREAD

**Issue by kazoo135** [freeCodeCamp/freeCodeCamp#12820]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSeondLine%5C%5C%5CrThirdLine%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SeondLine\\\rThirdLine";
When running this in my web dev console i receive 
"FirstLine
\SecondLine\ThirdLine"
```
However when I run this code with `\n` rather than `\r`
```
var myStr = "FirstLine\n\\SeondLine\\\nThirdLine";
"FirstLine
\SecondLine\
ThirdLine"
```
which I believe is what we're after - That being said neither runs in the platform

**Comment by raisedadead** [comment]
`SeondLine ` check that its not a typo that is causing it to fail?

**Comment by raisedadead** [comment]
Please clarify more as requested.

**Comment by abhi4singhal** [comment]
The platform is refusing to accept my answer too. I tried 
var myStr='FirstLine\n\\SecondLine\\\nThirdLine'; 

and the output being shown is 
myStr="FirstLine\n\\SecondLine\\\nThirdLine"

instead of the expected output. I asked for help in the chat room and people told me that my code gives the expected result when they run it.
