### ISSUE TITLE
[beta] FCC Test Suite sets all checkbox'es to the left top

### ISSUE THREAD

**Issue by Gardemarin** [freeCodeCamp/freeCodeCamp#12837]
FCC Test Suite sets all checkbox'es to the left top

#### Issue Description

FCC Test Suite sets all checkbox'es to the left top with position attribute and hides it with opacity: 0
```
input[type=checkbox] {
    height: 24px;
    width: 25px;
    position: fixed;
    top: 7px;
    left: 20px;
    border: 1px solid black;
    opacity: 0;
    cursor: pointer;
    z-index: 99999;
}
```

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Screenshot

![screen shot 2017-01-25 at 15 48 56](https://cloud.githubusercontent.com/assets/24617345/22298185/880dcad0-e317-11e6-9a28-b6812544cb6f.png)

**Comment by Greenheart** [comment]
@Gardemarin I'm not sure I understand what you mean. Could you please clarify? :blush:

@freeCodeCamp/moderators I've never seen these test suites before. Are these the official ones that in the future will be integrated with freecodecamp.com?

**Comment by dhcodes** [comment]
@Greenheart each project now has a test-suite to make sure the user-stories are met. Ex. http://codepen.io/FCC_test_suites/pen/JbgXab

**Comment by Gardemarin** [comment]
My example:
http://codepen.io/Gardemarin/pen/wgqYWZ

**Comment by Greenheart** [comment]
@dhcodes Thanks! I thought these should be integrated with freecodecamp.com - but it makes sense plan that for the upcoming multi-file editor release.

@Gardemarin I understand your issue now after experimenting a bit. But I'm not sure how to fix it :confused:

**Comment by thomlom** [comment]
I'm experiencing the issue too. 

It seems that all the `input` of type `checkboxes` don't have the checkbox because of the test suite.

With the test-suite imported : 

<img width="1440" alt="capture d ecran 2017-01-26 a 10 56 23" src="https://cloud.githubusercontent.com/assets/16003285/22327280/b9e97d34-e3b6-11e6-9f52-11808c289de3.png">

Without the test-suite imported : 

<img width="1440" alt="capture d ecran 2017-01-26 a 10 58 28" src="https://cloud.githubusercontent.com/assets/16003285/22327301/c9d0fb0a-e3b6-11e6-9a45-01a7390c6b07.png">

It seems that it's the test_suite_skeleton that causes the bug : 
https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/assets/test_suite_skeleton.js

In fact, one of the CSS rules modify all the checkboxes input `input[type=checkbox]`, 
Replace `input[type=checkbox` with `#toggle` might fix the bug.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack should we refactor the test suite's CSS so that none of its styles pollute a project's own CSS?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @raisedadead sorry, I missed this until now, been finding it a tad tricky to keep up with all the notifications! 

Yes, this was a good catch, and @weezlo and I had been discussing a way to keep the test suite CSS from polluting the project CSS and vise versa, and I can certainly make it a bit higher priority now that they are in much more frequent use. Also, saw @thomlom's PR on the repo and am going ahead and merging it in.

I'll also open an issue there to keep track of this. Thanks for the input @thomlom & @Gardemarin!

**Comment by no-stack-dub-sack** [comment]
This issue has been resolved via the above PR on the testable projects repo. Closing.
