### ISSUE TITLE
[beta][UI] Border-top for instruction

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12843]
All challenges already have a **hr** tag that comes after the title of challenge in the h4 element, with class="challenge-instructions-title" in the left-side panel or column of the page.

http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text

However there is no **hr** tag that comes before the Instruction.

Codecampers need to be able to distinguish the introduction for the challenge, from the instruction of the challenge.
```

<i  am title>
<i am hr>
<i am introduction>
<i am hr>
<i am instruction>


```

**Comment by HKuz** [comment]
@tommygebru - your suggestion has great timing! There was a recent discussion about how to show "Instructions" in each challenge, and folks decided on using an `<hr>` tag to visually split the challenge text from the instructions. You can read the comments [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/12688#issuecomment-274316858). We're currently working on getting this into all the seed files, so it's reflected in some of the sections on the latest `staging` branch, but not on beta yet.

We don't have an issue to track this progress, since it was discussed in the comments of another issue. We can keep this one open, and next time `staging` is pushed to beta, check out the challenges and see if that's what you were thinking. (Also, there's a screenshot in the comments I linked to above, if you want a preview).

Thanks!

**Comment by tommygebru** [comment]
@HKuz For sure, that looks good!

**Comment by dhcodes** [comment]
Closed as resolved?
