### ISSUE TITLE
[beta][UI] Missing challenge in Map, Slice and Splice

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12842]
Both in normal and night mode, the challenge Slice and Splice is missing from the Map page.

The text is missing in this path 
p>anchor>span "Missing text here"</-----react-text --->

**Comment by no-stack-dub-sack** [comment]
@tommygebru Thanks for reporting this - would you like to fix it? 

Looks like this issue was also reported in #12673. Since we are getting a MASSIVE number of new issues since releasing the beta curriculum, it would be more helpful than ever if you could check if issues already exist before opening new ones.

**Comment by QuincyLarson** [comment]
Thanks everyone. We've now fixed this on staging.

**Comment by tommygebru** [comment]
My apologies, I actually didnt see this thread!
