### ISSUE TITLE
[beta] bug in "Quoting String with Single Quotes" challenge

### ISSUE THREAD

**Issue by strongdan** [freeCodeCamp/freeCodeCamp#12865]
Challenge [quoting-strings-with-single-quotes](http://beta.freecodecamp.com/en/challenges/basic-javascript/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8872.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.105 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';

```

**Comment by tommygebru** [comment]
Im seeing the same.
MBP using Google Chrome.

**Comment by strongdan** [comment]
Weird. I was using Chrome on a Chromebook.

Is it better for me to simply state the nature of the bug or should I attempt to fix the testing files and create a pull request?

**Comment by tommygebru** [comment]
I believe its good to share as an issue first and get feedback...
also its pretty important to consistently provide screenshots also its easier to explain this way!

**Comment by strongdan** [comment]
Okay, I will do that in the future. I'm very new to all of this. I re-ran this challenge and got the same result - failed second test but passed first.

**Comment by tommygebru** [comment]
yeah - its an issue for sure

![screen-shot-2017-01-25-at-10 45 25-pm-compressor](https://cloud.githubusercontent.com/assets/7606025/22322355/47e8c912-e350-11e6-821d-b38c25d8a92f.png)

**Comment by marvellousdesign** [comment]
I'm having this error too and mines doesn't see the back slashes been removed.

![screen shot 2017-01-26 at 3 57 11 am](https://cloud.githubusercontent.com/assets/24817921/22330580/cb762966-e37b-11e6-9eee-385f5d378d0a.png)

**Comment by no-stack-dub-sack** [comment]
Ok, this challenge def has an issue - confirmed. Funny because the same challenge works in production and actually has one more test case.

**Comment by no-stack-dub-sack** [comment]
Ok, so the issue with this is similar to what we're seeing in [this](https://github.com/freeCodeCamp/freeCodeCamp/issues/12722#issuecomment-275217533) issue... what's happening is that there's a multi-line comment that is invisible to users, and this test is counting all the quotes that are found in the `code` variable, which is now including the multi-line comment: 
```js
assert(code.match(/\"/g).length === 6 && code.match(/'/g).length === 4, 'message: You should have two single quotes <code>&#39;</code> and four double quotes <code>&quot;</code>');
```
So I can make a quick PR to fix this issue as I already fixed locally when I was playing around to see what the issue was

**Comment by rmdawson71** [comment]
I am having the same problem with the correct solution, but if I exit the challenge and re-enter using the Map and submit, it passes the tests fine.
![image](https://cloud.githubusercontent.com/assets/5313213/22448023/33a6c364-e70b-11e6-9d61-52795ac7958c.png)

**Comment by no-stack-dub-sack** [comment]
@rmdawson71 this pull request should fix this issue! It should be updated and working on the beta site within the next couple of days!

**Comment by rmdawson71** [comment]
Hi Peter,

 

How would I have known not to comment or create a new “ticket” for a bug that has a fix but has not been implemented.  It seems you all maybe getting numerous repeat notifications about bugs that already have a fix for them.  I am not sure If it was this challenge or another one, I first checked github for  previously reported issues on the challenge.  If it still showed “Open” and someone already commented with same problem I saw, I did nothing.  However, if there was not report of my issue or there was but the status was “Closed”, I made another comment on it and posted my screenshot and comments.

 

Am I approaching this correctly? 

 

Randell Dawson

One Path Technologies

Phone: 408-475-7785

Email: rdawson@onepathtech.com

**Comment by rmdawson71** [comment]
Not sure if you got my other message, but why is it marked close if the fix has not been put in place?

**Comment by Greenheart** [comment]
@rmdawson71 Thanks reporting this! You've done everything correctly - this problem might still exist for a few days since it usually takes some time before a submitted fix is live on the site.

If you still experience this issue in a few days, even after a hard refresh (`CTRL`+`SHIFT`+`R`) and press the **"Reset"** button in the instructions panel (to make sure you're using the latest challenge data), then please comment here.

Otherwise, thanks for contributing to freeCodeCamp and happy bug hunting! :blush:

**Comment by cecilebertin** [comment]
This challenge is still bugged on Safari on the beta. I had the same issue as @marvellousdesign. I had to do a couple of hard refresh before it worked.

**Comment by gulptech** [comment]
Still a problem. Refreshing page fixes the problem.

**Comment by Python-git** [comment]
freecodecamp was great before all this beta nonsense came about. its been about a month now since released an yet you think all these basics would have been fixed. i am all for knew stuff added to the knew diet of code on the camps site but they really screwed up a lot of stuff that was working just fine an teaching people a solid way to learn an implement knew information to there brains. i noticed they brought back the hint button which i rarely ever used but on occasion had to. but yet that doesn't work either.
