### ISSUE TITLE
[beta] the first flexbox challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12866]
The flexbox challenges I assume have inappropriately large div heights...
starting with 

Css Flexbox: Using display: flex with Two Boxes
http://beta.freecodecamp.com/en/challenges/css-flexbox/using-display-flex-with-two-boxes

**Comment by ajain17** [comment]
@tommygebru what do you mean it assumes you have inappropriately large div heights? We are setting height to 500px for each div. Can you please elaborate your issue?

**Comment by HKuz** [comment]
@tommygebru - thanks for pointing this out. I consolidated a number of the Flexbox issues over in #12803, and propose to size the `divs` with a `width: 200px;` and `height: 200px;`. This will show both boxes in their entirety in the mobile phone screen output area, so campers can see the result more clearly. We'll also make the fix for challenges `Using the Flex-direction Property to Make a Row` and `Using the Flex-direction Property to Make a Column` (as you pointed out in #12870). 

@ajain17 - thanks for taking these changes on, much appreciated!

**Comment by ajain17** [comment]
@HKuz  I think instead of hardcoding the pixel value, we should set width to 100% and set height to 50%. What do you think?

**Comment by ajain17** [comment]
This is how it will look.
![screen shot 2017-01-26 at 2 50 25 pm](https://cloud.githubusercontent.com/assets/5581487/22347662/cc715b78-e3d6-11e6-9106-258f428a8b01.png)

**Comment by HKuz** [comment]
@ajain17 - that looks good and work, too!

**Comment by tommygebru** [comment]
@ajain17 I would suggest even small blocks that make it very easy to distinguish a layout or orientation of the child elements before any flexbox code is introduced or changed
