### ISSUE TITLE
[beta] Flexbox challenge 5 issue - similar to issue #12866

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12870]
[beta] similar to issue #12866
This is an important issue, because **the divs are too large** you can only see one color in the Solution Window (the phone).... and thus cannot discern that there are other boxes (or child elements).

Because the challenge ends and a modal pops up, you cannot learn from the Solution and see the difference between a `flex-direction:row` or a `flex-direction: column`

Css Flexbox: Using the Flex-direction Property to Make a Column
http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-flexdirection-property-to-make-a-column

![screen-shot-2017-01-25-at-10 24 26-pm-compressor](https://cloud.githubusercontent.com/assets/7606025/22322124/94e88f38-e34e-11e6-8d18-2e2140d0ade6.png)

**Comment by no-stack-dub-sack** [comment]
@tommygebru Hey man! Wow, you are killing it in reporting these issues, appreciate your hard work. 

However, since many of these issues are very similar and related to the same section, do you think you would be able to perhaps condense all of these into one issue (at least all of the related ones) and create a checklist so that they can be better organized and easier to attack once we start getting PRs in for these? 

A good example of this would be an issue like #12698. This would be super helpful if you're up to it (as I realize you've already done a bunch of work by reporting these in the first place), especially since we have so many other issues coming in as well. 

What do you think? Thanks again for helping out with beta!

**Comment by tommygebru** [comment]
Wow very cool @no-stack-dub-sack as you can see I tired myself out and decided to spend the day tackling personal projects, I will be back tomorrow to contribute, after some good sleep!

**Comment by no-stack-dub-sack** [comment]
@tommygebru sounds great! thanks!
