### ISSUE TITLE
Mobile bug

### ISSUE THREAD

**Issue by jdubbz1113** [freeCodeCamp/freeCodeCamp#12903]
Create a border challenge
My code won't to through. It keeps saying for me to have a border around image

#### Browser Information

* Browser Name,Google chrome Version: 5.5
* Operating System: android
* Mobile, 

#### Your Code

 link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
.thick-green-border
  {
    border-color: green;
    border-width: 10px;
    border-style: solid; }
      h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="thick-green-border smaller-image"  src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by jdubbz1113** [comment]
<img class="thick-green-border smaller-image"  src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

**Comment by jdubbz1113** [comment]
I am sorry. I am trying to post the code for my image. I am on mobile at the moment and I'm having trouble. 😶

**Comment by IAshishSrivastava** [comment]
No opening bracket in line link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

**Comment by OFFLlNE** [comment]
@jdubbz1113 Thank you for reporting your issue.

This is common, that programming on Android, it won't let it pass correct code. Because android puts whitespaces/tabs the wrong way, so editor does not see the code sometimes because of that.
Next time try to use the ***Help*** button which takes you to Help room chat, where people could solve this problem for you. Check for other [Offical FCC rooms here](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)

For now, I will throw you this helpline, but next time, come to the help chat ;)
Take this:
```
.thick-green-border{
  border-color: green;
  border-width: 10px;
  border-style: solid;
  }
```

Good luck coding!
