### ISSUE TITLE
It is not specified how many arguments will be given along with an array, so we cannot determine how to write the code for number of arguments not known.

### ISSUE THREAD

**Issue by okaysidd** [freeCodeCamp/freeCodeCamp#12906]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0Afunction%20destroyer(arr%2C%20a%2C%20b)%20%7B%0A%20%20arr%20%3D%20arr.filter(function(val)%20%7B%0A%20%20%20%20return%20val!%3D%3Da%3B%0A%20%20%7D)%3B%0A%20%20arr%20%3D%20arr.filter(function(val)%20%7B%0A%20%20%20%20return%20val!%3D%3Db%3B%0A%20%20%7D)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B2%2C%203%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function destroyer(arr, a, b) {
  arr = arr.filter(function(val) {
    return val!==a;
  });
  arr = arr.filter(function(val) {
    return val!==b;
  });
  return arr;
}

destroyer([2, 3, 2, 3], 2, 3);

```

**Comment by okaysidd** [comment]
I have used two extra arguments here a and b, but that is temporary solution, because the number of extra arguments is not specified.

**Comment by mh453Uol** [comment]
Hello,

JavaScript functions have a built-in object called the arguments object.
The argument object contains an array of the arguments used when the function was invoked.

Some Code:
` fooBar(1, 123, 500, 115, 44, 88);

function fooBar() {
    for (var i = 0; i < arguments.length; i++) {
        console.log(arguments[i]);
    }
}

Output:
1
123
500
115
44
88
`
fooBar() does not define any parameter however we can insert them since Javascript does not check the number of arguments. To access the arguments you need to access arguments object.

Have a play with the code. :)

**Comment by Greenheart** [comment]
I understand the frustration because I remember having trouble with this one as well.

However, I don't believe there is any problem with this challenge. My tip is that you read the links provided in the final part of the instruction. There are ways to handle an unknown number of arguments.

In the future, please click the **"Help"** button on the challenge on freeCodeCamp instead of asking for help here. This button will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by okaysidd** [comment]
Thank you for the answer as well as the advice.
Big help!
