### ISSUE TITLE
The comment line is on the wrong place I guess, it should be below return statement. 

### ISSUE THREAD

**Issue by mayurdw** [freeCodeCamp/freeCodeCamp#12911]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20alpha%3A%20%22Adams%22%2C%0A%20%20bravo%3A%20%22Boston%22%2C%0A%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20delta%3A%20%22Denver%22%2C%0A%20%20echo%3A%20%22Easy%22%2C%0A%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = {

  // Only change code below this line
  alpha: "Adams",
  bravo: "Boston",
  charlie: "Chicago",
  delta: "Denver",
  echo: "Easy",
  foxtrot: "Frank"
  };
  
  // Only change code above this line
  return result[val];
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by Greenheart** [comment]
@mayurdw It looks like you've changed code both above and below the lines you were given.

After looking at the seed code given after pressing **Reset**, I don't think this is an issue.
My suggestion is that you reset your code, read the instructions again and only change code on the given lines.

In the future, please click the "Help" button on the challenge on freeCodeCamp instead of asking for help here. This button will take you to the help chatroom for that specific challenge. You can also view our full list of official chatrooms.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
