### ISSUE TITLE
won't let me complete challenge 

### ISSUE THREAD

**Issue by codemasteroba** [freeCodeCamp/freeCodeCamp#12916]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
