### ISSUE TITLE
word blanks / javascript 

### ISSUE THREAD

**Issue by Ghareebovich** [freeCodeCamp/freeCodeCamp#12918]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20myNoun%20%3D%20%22dog%22%3B%0A%20%20myAdjective%20%3D%20%22big%22%3B%0A%20%20myVerb%20%3D%20%22ran%22%3B%0A%20%20myAdverb%20%3D%20%22quickly%22%3B%0A%20%20result%20%3D%20%22the%20%22%20%2B%20myAdjective%20%2B%20%22%20%22%20%2B%20myNoun%20%2B%20%22%20%22%2B%20myVerb%20%2B%20%22%20%22%20%2B%20myAdverb%3B%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%20%20%20%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%20%22cat%22%2C%20%22liitle%22%2C%20%22hit%22%2C%20%22slowly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
the 3rd objective to complete the challenge doesn't work and i didn't know why !
My code:

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  myNoun = "dog";
  myAdjective = "big";
  myVerb = "ran";
  myAdverb = "quickly";
  result = "the " + myAdjective + " " + myNoun + " "+ myVerb + " " + myAdverb;
  // Your code above this line
  return result;
}
   
// Change the words here to test your function
wordBlanks( "cat", "little", "hit", "slowly");

```

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
