### ISSUE TITLE
Failing to pass Introduction to Basic CSS

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#12927]
#### Challenge Name
[Introduction to Basic CSS](http://beta.freecodecamp.com/en/challenges/basic-css/introduction-to-basic-css)

#### Issue Description
When trying to complete this challenge, it throws me "Something went wrong, please try again later"

#### Browser Information

* Browser Name, Version: Chrome 52.0.2743.116
* Operating System: OS X v.10.10
* Mobile, Desktop, or Tablet: MacBook

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/8721312/22389677/88839a9c-e4ef-11e6-8577-1c718a0dc7e8.png)
![image](https://cloud.githubusercontent.com/assets/8721312/22389783/17c0bfa0-e4f0-11e6-8200-ec0f93b94669.png)

**Comment by Greenheart** [comment]
I can confirm this issue. Doesn't seem to be browser specific as I can reproduce in both Chrome and Firefox.

**Comment by RoniqueRicketts** [comment]
I have the same issues.

**Comment by padulam** [comment]
@Greenheart I took a look at this one and found that it's failing when trying to store the id for this challenge (either upon completion or when trying to store the last accessed challenge). Here's the error:

`Error: 597d7790367517u2y2517ab2 is not a valid ObjectId
    at updateMyCurrentChallenge `

When I queried the local fcc challenge database I noticed that the id for this challenge is stored as a string as opposed to an ObjectId.

**Comment by HKuz** [comment]
@padulam thanks for narrowing that down! Yes, that's not a valid ID because the 'u' and 'y' aren't hex digits. For example, if I change the 'u' to a 7, and the 'y' to a 3 so the entire number is `597d77903675177232517ab2`, the challenge saves when I run it locally (here's my terminal output):

![screen shot 2017-01-30 at 8 49 27 am](https://cloud.githubusercontent.com/assets/9591826/22425444/15802912-e6c9-11e6-926f-9a963e147a1f.png)


If you're referencing that the IDs are strings in the basic-css.json file, that's ok - all the info about a section and its challenges are stored in giant JSON structures for the database.

Would you like to open a PR with this change?

**Comment by padulam** [comment]
@HKuz Thanks for the additional information! I'll take care of this tonight.

**Comment by Greenheart** [comment]
@padulam @HKuz Excellent triaging! Looking forward to a PR :smile:
