### ISSUE TITLE
something wrong 

### ISSUE THREAD

**Issue by than2042** [freeCodeCamp/freeCodeCamp#12939]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23FF0000%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%2300FF00%3B%0A%20%20%7D%0A%20%20.dodgerblue-text%20%7B%0A%20%20%20%20color%3A%20%232998E4%3B%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23FFA500%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodgerblue-text%22%3EI%20am%20dodgerblue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20orange!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #FF0000;
  }
  .green-text {
    color: #00FF00;
  }
  .dodgerblue-text {
    color: #2998E4;
  }
  .orange-text {
    color: #FFA500;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodgerblue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>
 I think there might be something wrong. I could not submit this subject 
```

**Comment by Manish-Giri** [comment]
@than2042 The default code for the challenge starts out with the class name `"dodger-blue-text"`.  Why did you change it to `"dodgerblue-text"`?

**Comment by than2042** [comment]
thank you. A bit challenge.

Thank you very much.

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
