### ISSUE TITLE
I think there are some Bugs

### ISSUE THREAD

**Issue by chaturanga836** [freeCodeCamp/freeCodeCamp#12938]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {
  var gear;
  
  this.getGear = function(val){
    gear = val;
  };
  
  this.setGear = function(){
    return gear;
  };
  
  // Only change code below this line.

};

var myCar = new Car();

var myBike = new Bike();



```

**Comment by Manish-Giri** [comment]
@chaturanga836 Please read the instruction - 

> Modify the Bike constructor to have a private property called gear and two public methods called getGear and setGear to get and set that value

Instead, your `getGear` sets a value, and `setGear` returns a value.

Please visit the [HelpJS Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help with the challenge.

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
