### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hackbook001** [freeCodeCamp/freeCodeCamp#12948]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourTrueOrFalse(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20var%20result%20%3D%20%22Yes%2C%20That%20was%20%22%3B%0A%20%20return%20result%20%2B%3D%20wasThatTrue%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(true)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue) {

  // Only change code below this line.
  
  // Only change code below this line.
  var result = "Yes, That was ";
  return result += wasThatTrue;
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(true);

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by hackbook001** [comment]
Help me out in my code
