### ISSUE TITLE
[Bug?] Challenge: Learn how Script Tags and Document Ready Work

### ISSUE THREAD

**Issue by Shunthrope** [freeCodeCamp/freeCodeCamp#12973]
Challenge [Learn how Script Tags and Document Ready Work]

Hi,

When I insert a normal script element, and close it, the first task is sufficiently completed. When I insert the function proper, the other two tasks are completed and the first is nullified. Am I dumb?

Cheers.

Code:
html

<script $(document).ready(function() {
        });>
  
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@Shunthrope Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by katzie4** [comment]
@erictleung  I am getting the same issue as @Shunthrope  - 
Here is the completed code completed for the challenge: 
<script $(document).ready(function(){});></script>

When clicking Run tests - the condition _Create a script element making sure it is valid and has a closing tag._ remains red. Either both of us have done some wrong here or this is a defect.
