### ISSUE TITLE
[beta] Applied Visual Design: Add a Box-shadow to a Card-like Element | Hover issue

### ISSUE THREAD

**Issue by ipreira** [freeCodeCamp/freeCodeCamp#12979]
#### Applied Visual Design: Add a Box-shadow to a Card-like Element

http://beta.freecodecamp.com/en/challenges/applied-visual-design/add-a-boxshadow-to-a-cardlike-element

#### The camper must add a property when the id is on its hover state whereas this hasn't been studied yet

In this part, it is required to add a box-shadow property for the thumbnail id on its hover state.
The problem is that at this stage, campers are not supposed to know how to do that, because none of the previous challenges tackle this hover issue.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.95 (64-bit)
* Operating System: OX ElCapitan 10.11.6
* Mobile, Desktop, or Tablet: iMac

**Comment by ipreira** [comment]
Basically this challenge should be before the one mentioned before :  Adjust the Hover State of an Anchor Tag

http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag

**Comment by HKuz** [comment]
@ipreira thanks for raising this point - you're right about the pseudo-class selectors not having been introduced yet. I think we can improve this challenge by removing the requirement that the box shadow effect needs to be on the `hover` state. (The challenge is really about how to use the `box-shadow` property, anyway).

I hesitate to reorder the challenges so `Adjust the Hover State of an Anchor Tag` challenge comes first, because that one isn't using the "card" example like the others in this series.

The changes to `Add a Box-shadow to a Card-like Element` would be:
- Re-word the instructions part of the challenge text (last paragraph) to say:
> The element now has an id of `thumbnail`. With this selector, use the example CSS values above to place a `box-shadow` on the card.
- Remove the hint
- Update the first test and its message to remove the `hover` requirement

For anyone who would like to work on this, please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and feel free to ask any questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). Thank you! 🎉 💻 🏅

**Comment by Manish-Giri** [comment]
@HKuz I'd like to take this one up!

**Comment by HKuz** [comment]
Great, thanks @Manish-Giri 🎉 👍

**Comment by Atomk** [comment]
@Manish-Giri I think you forgot to fix this -> "This technique can be used on any state of an element, but here you'll apply it on hover."

**Comment by Greenheart** [comment]
@Atomk Nice catch! I apparently missed that when I reviewed this fix.

Feel free to open a PR for this, since you spotted it! :blush:

**Comment by Atomk** [comment]
@Greenheart Working on it, I'm also removing :hover from the next challenges until :hover is introduced. I'm sorry it is taking so much time, I'm just making sure I understand the contributor guidelines and Git from command line is less user-friendly than expected.

**Comment by Greenheart** [comment]
@Atomk No problem, take your time! The commandline can be pretty daunting at first, but over time it will become your best friend to get things done :relaxed: 

If you have any questions, feel free to come chat with us in the [Contributors room](https://gitter.im/FreeCodeCamp/Contributors) :smile:

**Comment by smehta1023** [comment]
@Manish-Giri We should add a link to id selectors as a refresher.

**Comment by enchill** [comment]
i'm trying to figure out how to work this;
The element now has an id of thumbnail. With this selector, use the example CSS values above to place a box-shadow on the card.

this is the css values;
box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);

and this is the code i used;
 .thumbnail {
    box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
 but it's mot working on the fcc site.

**Comment by RandellDawson** [comment]
@enchill You should ask questions related to the challenges on the forum.  GitHub is used to report bugs with the challenge (i.e incorrect tests, incomplete instructions, etc.).  If forum members conclude there is a bug in the actual challenge, they will refer you here to create a new issue.
