### ISSUE TITLE
"Error Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%."

### ISSUE THREAD

**Issue by kauej** [freeCodeCamp/freeCodeCamp#12998]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20text.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%20text.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
   p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum text.</p>

<p>Kitty ipsum text.</p>

```

I`m trying also

My code:
```html

<style>
  .red-text {
    color: red;
  }
   .p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum text.</p>

<p>Kitty ipsum text.</My code:
```html


It`s not accept.

**Comment by archit99** [comment]
are you following instructions ?
it says

> Create a second p element after the existing p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by AntwuanJ** [comment]
You have to write out the whole paragraph statement.

**Comment by graphetes** [comment]
Why can't people actually help here, not many people to no one is in the chat.

**Comment by RandellDawson** [comment]
@graphetes If you need help with a curriculum challenge, please use [our forum](https://freecodecamp.org/forum) for the fastest response.
