### ISSUE TITLE
Confirm the Ending

### ISSUE THREAD

**Issue by Rickgonnz** [freeCodeCamp/freeCodeCamp#13023]
hi guys i think i found an issue or something i doing wrong please check

function confirmEnding(str, target) {
 
  for (var i = 0; i < str.length; i++){
    for (var j = 0; j < target.length; j++){
      if (str.substr(-1) == target.substr(-1)){
        return true;
      }else {
        return false;
      }
    }  
  }
}
confirmEnding("Bastian", "n");

and this point should say true not false 

confirmEnding("Walking on water and developing software from a specification are easy if both are frozen", "specification") should return false.

**Comment by abelsmoker** [comment]
On Jan 31, 2017 9:37 PM, "Ricardo González" <notifications@github.com>
wrote:

hi guys i think i found an issue or something i doing wrong please check

function confirmEnding(str, target) {

for (var i = 0; i < str.length; i++){
for (var j = 0; j < target.length; j++){
if (str.substr(-1) == target.substr(-1)){
return true;
}else {
return false;
}
}
}
}
confirmEnding("Bastian", "n");

and this point should say true not false

confirmEnding("Walking on water and developing software from a
specification are easy if both are frozen", "specification") should return
false.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/13023>, or mute the
thread

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. What is the reason of your for-loops if you are doing the same stuff over and over..
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
