### ISSUE TITLE
Use the Bootstrap Grid to Put Elements Side By Side 

### ISSUE THREAD

**Issue by ahsan3296** [freeCodeCamp/freeCodeCamp#13039]
#### Challenge Name

please see the red highlighted box in the screenshot 

 hi please look on the heading I've highligted I have completed my task but I was having a doubt that why does the three buttons (LIKE) (INFO) and (DELETE) have spaces between them when we are consuming are 12 grids while dividing them in row

![issue](https://cloud.githubusercontent.com/assets/25439887/22524347/e8463b14-e8d3-11e6-897f-ac87f98e2ee7.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
