### ISSUE TITLE
false evaulates to true, since Trump's election :|

### ISSUE THREAD

**Issue by micheal-adrian** [freeCodeCamp/freeCodeCamp#13041]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements

#### Issue Description
 arguments false and 0 pass the challenge

#### Your Code
 
function trueOrFalse(wasThatTrue) {
  if (wasThatTrue) { 
    return "Yes, that was true";
  } 
  return "No, that was false";
}
trueOrFalse(false);

**Comment by Manish-Giri** [comment]
@michael-krebs could you elaborate? If a value is not truthy, like `false`, you'll be returned `"No, that was false";`, and the challenge will pass.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. In your case the tests would kind of work, but it does want a different solution. If the input would be trueOrFalse(2<3); then it returns a wrong thing.

Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by micheal-adrian** [comment]
Hi, my code is intentionally wrong. To demostrate. It fails below the
console yet passes the challenge.

On Feb 1, 2017 6:04 PM, "Manish Giri" <notifications@github.com> wrote:

@michael-krebs <https://github.com/michael-krebs> could you elaborate? If a
value is not truthy, like false, you'll be returned "No, that was false";,
and the challenge will pass.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/13041#issuecomment-276811662>,
or mute the thread

**Comment by micheal-adrian** [comment]
Yes,
I know my code is wrong, intentinally. Thats for the feed back. It returns
false but yet th challenge is passed. Was just bring that to the attention
of he test writer

**Comment by micheal-adrian** [comment]
Yikes, I'm mentally challenged.  Thanks M-G :D
