### ISSUE TITLE
Add .vscode to .gitignore

### ISSUE THREAD

**Issue by robbawebba** [freeCodeCamp/freeCodeCamp#13059]
I was wondering if we could add `.vscode`, the directory created by Visual Studio Code for editor settings, to the .gitignore file? This would both prevent people from accidentally committing their editor settings, and make working with git a little easier by not having to worry about that file accidentally being tracked by git. 

I wouldn't mind creating a PR for this one, I just thought I should follow convention and create an issue on GitHub first. 😁 It's a simple fix, so if it's easier for an admin or moderator to do it, that's also fine! 😄

**Comment by raisedadead** [comment]
@robbawebba instead lets open this up to first time contributors.

**Comment by vcapretz** [comment]
Hey, I'm working on it!

**Comment by abelsmoker** [comment]
On Feb 2, 2017 4:35 AM, "Vitor Capretz" <notifications@github.com> wrote:

Hey, I'm working on it!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/13059#issuecomment-276945704>,
or mute the thread

**Comment by vcapretz** [comment]
Pull request here: https://github.com/freeCodeCamp/freeCodeCamp/pull/13074
Let me know if I need to change something
