### ISSUE TITLE
Find the Lenght of a String

### ISSUE THREAD

**Issue by AndreiBolog** [freeCodeCamp/freeCodeCamp#13076]
#### Issue Description

The console will not accept the correct version of the code and/or won't work for the function .lenght even if i add or delete characters of the string "Lovelace"

#### Browser Information

* Browser Name, Version: Chrome 55
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 0;
var lastName = "Lovelace";

// Only change code below this line.

lastNameLength = lastName.lenght;
 
 
 
```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. You have a typo in your length
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
