### ISSUE TITLE
[beta] Night mode applies to profile based on other user's setting

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#13082]
#### Issue Description
I've turned on night mode on my beta account. If another user visits my public profile, they will see that profile in night mode regardless of if their account has night mode enabled and regardless of if they even have an account.

I sanity-checked this in incognito mode. 

In other words, regardless of your setting, you will see my profile in night mode.

#### Browser Information

* Browser Name, Version: Chrome 54+
* Operating System: Mac
* Mobile, Desktop, or Tablet: 

[My Profile](http://beta.freecodecamp.com/en/dhcodes)
[Non-night mode profile](http://beta.freecodecamp.com/en/diomed)

**Comment by hudsontaylor** [comment]
That seems rather obnoxious. Does this happen on the current Freecodecamp site or just Beta? I hope someone addresses this!

**Comment by Ayushpandey80** [comment]
When I turn on the night mode, it says Authorization requires, although I am logged in my a/c.

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 12 ก.พ. 2017 09:14 "Ayushpandey80" <notifications@github.com> เขียนว่า

When I turn on the night mode, it says Authorization requires, although I
am logged in my a/c.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/13082#issuecomment-279190969>,
or mute the thread
