### ISSUE TITLE
[beta] change all instances of "HyperDev" to "gomix" (or GoMix?)

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13092]
In addition to #13091 regarding HyperDev, apparently HyperDev is no longer HyperDev. Our codebase should be updated to reflect the new name GoMix (or gomix). Otherwise, campers will be running around like developers with their heads cut off trying to find something that does not exist. 

The current references to HyperDev are in the APIs and Microservices section primarily

**Comment by Greenheart** [comment]
@no-stack-dub-sack Good idea! `GoMix` would probably be the way to go except for URLs

**Comment by Manish-Giri** [comment]
@Greenheart @no-stack-dub-sack I'd be interested in doing this, if no one else is..

**Comment by raisedadead** [comment]
This is already being discussed in #12071 , consider closing as a duplicate.

**Comment by Greenheart** [comment]
@raisedadead Thanks for the reference. After reading the other issues, I feel like they are more geared towards *using Gomix as a development platform* while this issue is about *updating the name across our codebase*.

So I'd say we continue.

@no-stack-dub-sack @Manish-Giri They seem to use "Gomix" so that's probably what we want.

**Comment by dhcodes** [comment]
Sorry @Manish-Giri; I submitted a PR for this before I realized it was an open issue already! I should've searched :(
