### ISSUE TITLE
Run tests doesn't work

### ISSUE THREAD

**Issue by meli94** [freeCodeCamp/freeCodeCamp#13109]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var range=[];
function sumAll(arr) {
  var val0=arr[0];
   var val1=arr[1];
  var max= Math.max(val0, val1);
  var min= Math.min(val0, val1);
  for (var i=min; i<=max; i++)
    {range.push(i);}
  
  range=range.reduce(function(a,b){return a+b;},0);
  
  return range;
}

sumAll([2,4]);

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

You define a global variable, which fCC tests don't like. because you change the global variable with the first test and it won't get reset for the next test.
Just throw that variable inside the function and you are good ;)
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
