### ISSUE TITLE
Basejump setup broken by new scaffolding script

### ISSUE THREAD

**Issue by AVanVlack** [FreeCodeCamp/freecodecamp#1310]
While this may be more of an issue of angular-fullstack (or some other part of the basejump setup?), version 2.1.0 of angular-fullstack crashes the heroku server and throws off the setup for basejumps. 

After trying several times I was unable to get an untouched scaffolding to boot on heroku. After using angular-fullstack@2.0.13 I was able to get it to boot.

Heroku logs gave a h10 and r10 with the 2.1.0 scaffolding.

**Comment by benmcmahon100** [comment]
The h10 is an app crash and the cause of the h10 should reveal the issue. The r10 is a boot timeout which according to https://devcenter.heroku.com/articles/error-codes is a timeout tirggered due to it taking longer than 60 for you app to bind to it's port. It sounds to me like something was hanging and the h10 should give insight into what was hanging and why

**Comment by AVanVlack** [comment]
Default port was scaffold to 'localhost', should have been '0.0.0.0'. Angular-fullstack script fixed and will now start on heroku.

**Comment by leesharma** [comment]
It's fixed on GitHub, but I don't think it's fixed on npm yet; the latest version is still 2.1.0. I'd guess that the 2.1.1 release will fix the bug for new users.

It was an easy fix for me though (like @AVanVlack said, just change 'localhost' to '0.0.0.0' in /server/config/environments/index.js), so hopefully those who encounter the issue before the next version is released on npm will ask for help!
