### ISSUE TITLE
Please help. thanks

### ISSUE THREAD

**Issue by Dew007** [freeCodeCamp/freeCodeCamp#13117]
Challenge [Add ID Attributes to Bootstrap Elements](https://www.freecodecamp.com/challenges/add-id-attributes-to-bootstrap-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default target" id="left-well"></button>
        <button class="btn btn-default target" id="left-well"></button>
        <button class="btn btn-default target" id="left-well"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default target" id="right-well"></button>
        <button class="btn btn-default target" id="right-well"></button>
        <button class="btn btn-default target" id="right-well"></button>
      </div>
    </div>
  </div>
</div>

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
