### ISSUE TITLE
"Zipline: Show the Local Weather" Issue

### ISSUE THREAD

**Issue by NatashaRocha** [FreeCodeCamp/FreeCodeCamp#1312]
Challenge http://www.freecodecamp.com/challenges/zipline-show-the-local-weather has an issue. 

When I try to open the Local Weather App on CodePen all I see are three empty boxes.
http://codepen.io/AdventureBear/full/yNBJRj
![capture](https://cloud.githubusercontent.com/assets/5845648/8730064/1e45f4a2-2bc5-11e5-8d79-4baccab9fb5a.PNG)

**Comment by benmcmahon100** [comment]
This is an error due to amount of times the example has been loaded.
![image](https://cloud.githubusercontent.com/assets/10749142/8736612/fb9e4ed4-2c11-11e5-80fd-e1f482aeaad6.png)
There's no real fix for this I'm afraid but if you're to use this API in your own app it should still work.

**Comment by MarufSarker** [comment]
Generally this happens when your browser prevents any site to load external data from different websites.
If you're using Chrome as your browser, Click the Shield icon on right side of the address bar and select "Load unsafe scripts". 
![load_script](https://cloud.githubusercontent.com/assets/10809140/9150691/d1c3df16-3e09-11e5-92cb-4f53b9eaf744.png)

This will refresh the tab and load the scripts for that tab (only).

This is a default setting on browsers due to security reasons. 
But as we can see the code on codepen.io and know where it is calling its requests (here openweathermap.org and ipinfo.io), so we can explicitly allow the permissions.

**Comment by benschenker** [comment]
Closing as stale/fixed
