### ISSUE TITLE
I can't run tests when i completed --> "Replacing If Else Chains with Switch"  ???

### ISSUE THREAD

**Issue by okngay** [freeCodeCamp/freeCodeCamp#13136]
Replacing If Else Chains with Switch

#### Challenge Name

Replacing If Else Chains with Switch
https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch
#### Issue Description

I can't run tests to check my answer!

#### Browser Information

* Browser Name, Version:  Chrome 56
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  Laptop

#### Your Code

```js

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
 switch(val) {
  case "bob": 
     answer = "Marley"; 
     break;
  case 42 : 
     answer = "The Answer";
     break;
  case 1 :
     answer = "There is no #1"; 
     break;
  case 99 :
     answer = "Missed me by this much!";
     break;
  case 7 : 
     answer = "Missed me by this much!"; 
     break;
  default : 
     answer = "";
}
  
}

// Change this value to test
chainToSwitch(7);


```
#### Screenshot

![5f01cb74aaf5451f988e44692c807ee6](https://cloud.githubusercontent.com/assets/13285988/22619617/0519f2c2-eb2b-11e6-8678-e7e7ed07fe08.png)

**Comment by okngay** [comment]
Nothing happened when i click "Run tests" ???
pls tell my why?

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. You are not returning anything
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
