### ISSUE TITLE
Unable to complete challenge 185, possible bug??

### ISSUE THREAD

**Issue by afterlife72385** [freeCodeCamp/freeCodeCamp#13172]
I'm pretty sure there is a bug with challenge 185 Comparisons with the Logical And Operator https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator#?solution=%0Afunction%20testLogicalAnd(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val)%20%7B%0A%20%20%20%20if%20(val)%20%7B%0A%20%20%20%20%20%20return%20%22Yes%22%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22No%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalAnd(10)%3B%0A

Given code is 

function testLogicalAnd(val) {
  // Only change code below this line

  if (val) {
    if (val) {
      return "Yes";
    }
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);

My code is 

function testLogicalAnd(val) {
  // Only change code below this line

 
    if (val >= 25 && <= 50) {
      return "Yes";
    }
  

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);

I've tried a few different ways and no matter what I get the following error "SyntaxError: expected expression, got '<='

Is there a solution for this?
 Also the things on the left that show what you got right and wrong change sometimes with the same code, but no matter what I never get credit for having && or only 1 if statement.

**Comment by fonsecapontes** [comment]
Is't an bug.

You forget use variable val in if statement after &&

The correct code is:
`if (val >= 25 && val <= 50) {
  return "Yes";
}`

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Comparsion operators such as `<=` or `>=` follow the form `value1 <operator> value2`. Your second operator (`<=`) doesn't have a value on it's left side (`value1`)

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding :smile:

**Comment by afterlife72385** [comment]
Thank you I can't believe I missed that
