### ISSUE TITLE
Pig Latin Challenge - Tests not passing for first vowel words

### ISSUE THREAD

**Issue by tjsiledar** [freeCodeCamp/freeCodeCamp#13188]
#### Challenge Name

https://www.freecodecamp.com/challenges/pig-latin

#### Issue Description

Test case for words with first letter as vowel not passing even though the console shows the right expected output.

#### Your Code

```js

var c=0;
function check(arr)
{
  var count=0;
  var vowels = ["a","e","i","o","u"];
  for(i=0;i<vowels.length;i++)
    {
      if(arr[0]==vowels[i]){
        count++;
      }
    }
  c++;
  if(count==1)
    return 1;
  else
    return 0;
}

function translatePigLatin(str) {
  var arr = str.split("");
 
  while(check(arr)===0)
    {
      var k=arr.shift();
      arr.push(k);
    }
  if(c===1)
    {
      arr.push('w',"a","y");
    }
  else
    {
      arr.push("a","y");
    }
  arr=arr.join("");
  return arr;
}

translatePigLatin("algorithm");


```
#### Screenshot

![screenshot 16](https://cloud.githubusercontent.com/assets/25153728/22652376/3c18fa5c-ecac-11e6-9ba2-ba8872b14ac9.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. fCC tests don't like global variables
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
