### ISSUE TITLE
[beta][UI] Change image size on following challenges

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13206]
link to challenges:

- http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-images-to-your-website
- http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-external-pages-with-anchor-elements
- http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements

these pages should include `img{width:100%;}`

**Comment by HKuz** [comment]
@tommygebru - thanks for going through these challenges is such detail! So, we don't want to show any CSS in the seed code for this section, since it comes before campers have learned it. Unfortunately, the output ends up looking a little rough...

@freeCodeCamp/moderators - the cat image that's used here is a bit bigger than the phone's width. Should we look into making it a touch smaller (behind the scenes), so it fits better, or is it okay as is? 🐱 📸

**Comment by tommygebru** [comment]
Yeah - the list of challenges include any with the CatPhotoApp. I would suggest only changing the image itself **or if its easier** we can include the image width be 100%

The website looks good.

I hope that we can change 2 things before release:

- wider instructions panel (easier to read lengthy posts)
- a single notification system (absolving the modal toast)

* maybe brighter text and green color for the Night Mode UI

**Comment by QuincyLarson** [comment]
I would add that we might want to move the preview down below the code input so it can become wider (a switch to toggle between phone and landscape iPad view might be nice, for example). 

This way the directions and code could be wider. 

We could also potentially remove the fixed height from these elements and let users scroll up and down as necessary. 

There is a lot of room for experimentation here imho.
