### ISSUE TITLE
tests with value 5 and 8 work incorrect 

### ISSUE THREAD

**Issue by TeriVolta** [freeCodeCamp/freeCodeCamp#13218]
Challenge [Chaining If Else Statements](https://www.freecodecamp.com/challenges/chaining-if-else-statements#?solution=%0Afunction%20testSize(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(num%20%3C%205)%0A%20%20%20%20return%20%22Tiny%22%3B%0A%20%20else%20if(num%20%3C10)%0A%20%20%20%20return%20%22small%22%3B%0A%20%20else%20if(num%20%3C15)%0A%20%20%20%20return%20%22Medium%22%3B%0A%20%20%20else%20if(num%20%3C%2020)%0A%20%20%20%20%20return%20%22Large%22%3B%0A%20%20%20else%20if(num%20%3E%3D%2020)%0A%20%20%20%20%20return%20%22Huge%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestSize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testSize(num) {
  // Only change code below this line
  if(num < 5)
    return "Tiny";
  else if(num <10)
    return "small";
  else if(num <15)
    return "Medium";
   else if(num < 20)
     return "Large";
   else if(num >= 20)
     return "Huge";
  // Only change code above this line
}

// Change this value to test
testSize(5);

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. You have a typo in that if else statement what has to return "Small"
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
