### ISSUE TITLE
[beta][UI] inconsistent hr tags per challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13213]
there should be 3 `hr` tags per challenge but some have only 2 in the instructions panel.

3 hr tags is preferable for the instructions layout

**Comment by erictleung** [comment]
3 `<hr>` tags per challenge? I'm only familiar with just two `<hr>` per challenge. Can you clarify? Or maybe I'm missing something. The two I'm getting are one from the top and another right before the instructions for the challenge.

![image](https://cloud.githubusercontent.com/assets/2754821/22702687/5a11dff0-ed16-11e6-9cfb-b373ca7e296b.png)
...
![image](https://cloud.githubusercontent.com/assets/2754821/22702705/69800f98-ed16-11e6-97d2-51fe63718f06.png)

**Comment by tommygebru** [comment]
@erictleung the third one separates the buttons on the bottom from the paragraphs preceding it

So far i have only done the first chapter of the first certificate on HTML,
there you will find that every other challenge has 2 or 3, therefore inconsistent

**Comment by tommygebru** [comment]
also 
>The two I'm getting are one from the top and another right before the instructions for the challenge.

should be 
>The two I'm getting are one from the top and another right before the introduction of the challenge.

**Comment by sergiorojasa** [comment]
Is anyone working on this issue?

**Comment by raisedadead** [comment]
@tommygebru Can please provide screenshots of the inconsistency? Or identify a list of the challenges?

**Comment by tommygebru** [comment]
So the entire list of the curriculum or is the first course on FCC beta just fine? - HTML

(which is where i saw the issue, but possible it is the same for the entire curriculum)

**Comment by no-stack-dub-sack** [comment]
@raisedadead @tommygebru I don't have a screenshot handy, but I can confirm this, I was in the Basic DS section when I first noticed it - it only seems to happen when you are working through multiple challenges in a row. Two `<hr>`s should be the standard, but now and again a third will pop up right above the "run tests" button. 

EDIT: Actually @tommygebru, does this happen when you're running FCC locally or is this actually on beta? Because now that I think of it, I've only ever noticed this locally, and I just tried to reproduce it in both places, reproduced it very quickly locally, but couldn't on beta (in the same section)

**Comment by tommygebru** [comment]
@no-stack-dub-sack thanks for sharing this is on [beta] i havent run FCC locally

**Comment by tommygebru** [comment]
Also im not sure what the preference is - either way looks really good!

I will say that the first 2 are necessary because it separates the introduction from both the title and the instructions of the challenge.
Its the third one that needs to be discussed - i like that it separates the instructions from the 4 buttons below it
