### ISSUE TITLE
[beta][UI][UX] Way too many scrollbars, I count 4

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13224]
![screen shot 2017-02-07 at 10 12 25 am](https://cloud.githubusercontent.com/assets/7606025/22704932/601d7af0-ed1e-11e6-8467-21793805a1bb.png)

The easiest change would be to have a the size of the cat photo become 
`width:100%` that should remove 1 scrollbar

I made an issue for this previously #13206

Another quick fix would be to change the width and height of the instrucitons panel

I made an issue for this as well #13209

**Comment by raisedadead** [comment]
How is this different than one reported by you https://github.com/freeCodeCamp/freeCodeCamp/issues/13121

Consider discussing everything related to scroll bars in one thread, its tedious to track otherwise.

Please move your comments to the same, and edit the previous issue to be more relevant, feel free to add bullet points if it caters to sub-issues.
