### ISSUE TITLE
Creat a Headline Bootstrap

### ISSUE THREAD

**Issue by Bruninha310** [freeCodeCamp/freeCodeCamp#13220]
Creat a Headline Bootstrap

 O texto jQuery Playground não vai para o centro e não muda de cor.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```
#### Screenshot
<!-- <h3 classe= "text-primary text-center" >jQuery Playground</h3>-->

**Comment by erictleung** [comment]
@Bruninha310 Thank you for reporting this issue. You've misspelled "class" in your `<h3>` element.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
