### ISSUE TITLE
Missing Semi-Colons Producing Odd Errors

### ISSUE THREAD

**Issue by jodylecompte** [freeCodeCamp/freeCodeCamp#13234]
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulate-arrays-with-push

#### Issue Description

When semi colons are missing from the end of a line in this challenge, rather than throwing an error for a missing semi-colon, it throws an error that the myArray.push() function does not exist.

This may be an issue with the editor, but I thought it might be somehow related to the FCC tests since the editor shows a missing semi-colon error. 

#### Browser Information

* Browser Name, Version: Google Chrome 55.0.2883.95 (64-bit)
* Operating System: OSX Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```javascript
var myArray = [["John", 23], ["cat", 2]];
myArray.push(["dog", 3]);
// ^ Passes

var myArray = [["John", 23], ["cat", 2]];
myArray.push(["dog", 3])
// Rather than missing semi colon error, throws error myArray.push is not a function
```

**Comment by BrendanSweeny** [comment]
Hey @jodylecompte! Nice catch. I can reproduce this error and I think I know what the problem is. After many of the challenges there is a "tail" block of code that is appended to the code submitted. I believe it's used primarily to log values in the freecodecamp console as it does in this challenge. In this challenge, the tail is `(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);` so your code actually looks like this:

```
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.push(["happy", "joy"]); 
// ourArray now equals ["Stimpson", "J", "cat", ["happy", "joy"]]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
myArray.push(["dog", 3])


(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);
```

But since there's no semicolon, we get the expression, `myArray.push(["dog", 3])(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);` which tries to invoke `myArray.push(["dog", 3])` as a function, but its a number, so it throws a TypeError.

Weirdly, I could not reproduce the issue on the beta site, so maybe it's already fixed?

**Comment by mayur95** [comment]
I have not understand.
Can you elaborate..?

**Comment by raisedadead** [comment]
@BrendanSweeny thanks a lot for the insight. Yes, we have a new challenge evaluation mechanism on beta site to handle this. This will be available on the main website in the next release. 

@jodylecompte Untill then please consider using semicolons.
