### ISSUE TITLE
General Bug on all Lessons

### ISSUE THREAD

**Issue by Marvive** [freeCodeCamp/freeCodeCamp#13269]
Currently using Safari Version 10.0.3 (12602.4.8) on macOS 10.12.3 (16D32)

Every time you complete a lesson, the next lesson loads the result from the previous lesson. It stays that way until you hit "run" the first time on the current lesson. It has occurred to me on every lesson consistently.

Please forgive me if I'm reporting this bug in the wrong place!

Challenge [use-headings-to-show-hierarchical-relationships-of-content](http://beta.freecodecamp.com/en/challenges/applied-accessibility/use-headings-to-show-hierarchical-relationships-of-content) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h1>How to Become a Ninja</h1>
<main>
  <h2>Learn the Art of Moving Stealthily</h2>
  <h5>How to Hide in Plain Sight</h5>
  <h5>How to Climb a Wall</h5>

  <h2>Learn the Art of Battle</h2>
  <h5>How to Strengthen your Body</h5>
  <h5>How to Fight like a Ninja</h5>

  <h2>Learn the Art of Living with Honor</h2>
  <h5>How to Breathe Properly</h5>
  <h5>How to Simplify your Life</h5>
</main>

```

**Comment by AaroniusH** [comment]
I've been seeing the same issue on chrome Version 56.0.2924.87.

It would be best if the results were automatically updated when the code changes, including when the new challenge loads. I know for me personally, I have to click "Run Tests" in order to render the new changes. If I get it right, the success pop-up comes up and asks to take me to the next challenge, when I really just want to review the changes I made before moving on. It makes the learning process a little clunky at the moment.

**Comment by raisedadead** [comment]
@Marvive @AaroniusH thanks for the issue report and feedback. Closing in favor of earlier report https://github.com/freeCodeCamp/freeCodeCamp/issues/12923
