### ISSUE TITLE
[beta] No visual evidence flex-grow property expanded #box-2

### ISSUE THREAD

**Issue by cdrainxv** [freeCodeCamp/freeCodeCamp#13274]
Challenge [using-the-flexgrow-property-to-expand-items](http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-flexgrow-property-to-expand-items) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

```html


<style>
  #box-container {
    display: flex;
    height: 500px;
  }
  #box-1 {
    background-color: dodgerblue;
    flex-basis: 10em; /* See next challenge! */
    height: 200px;
    flex-grow: 1;
  }

  #box-2 {
    background-color: orangered;
    flex-basis: 10em; /* See next challenge! */
    height: 200px;
    flex-grow: 2;
  }
</style>

<div id="box-container">
  <div id="box-1"></div>
  <div id="box-2"></div>
</div>

```

The tests pass, but there is no visual evidence that #box-2 grew in size in the iphone frame (they both have the same dimensions as prior to the addition of the flex-grow property):

![screen shot 2017-02-10 at 04 02 14](https://cloud.githubusercontent.com/assets/18746599/22824609/d74ae7ce-ef45-11e6-9fb5-4a3a4f0984fe.png)

This might be due to the flex-basis property and its rather large value for the iphone frame. Lowering the value to `2em` visually shows the size differences between #box-1 and #box-2, but removing the flex-basis property altogether visually ***and*** dimensionally shows #box-2 (176 x 200) is twice as large as #box-1 (88 x 200).

Here is the result with the removal of the flex-basis property:

![screen shot 2017-02-10 at 04 49 52](https://cloud.githubusercontent.com/assets/18746599/22825938/044b4726-ef4d-11e6-99de-833ead416bca.png)

Since flex-basis is introduced in the following challenge anyways, I think the flex-basis property should be removed from this challenge, unless there is an underlying reason for its presence.

**Comment by HKuz** [comment]
@cdrainxv - first off, apologies for the super-delayed response to your issue. Thanks for noting this, I think this is a great suggestion. Your changes really illustrate the concept, and has the added bonus of removing the part that isn't covered until the next challenge.

I say we make your change to this challenge (remove the `flex-basis` property rows completely from the CSS for both boxes). Also, in the next challenge "Use the flex-basis Property to Set the Initial Size of an Item", delete the first sentence of the challenge text ("The previous example included flex-basis to help demonstrate how the flex-grow property works.") since it's no longer relevant.

For anyone wanting to help, please refer to the [Contributor's guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). You can find the code for these changes [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-flexbox.json#L947), [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-flexbox.json#L954), and the next challenge's [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-flexbox.json#L980). Thank you 🎉 🍔 :1st_place_medal:

**Comment by cdrainxv** [comment]
@HKuz: Thanks for following up on this issue. I'll take this up.
