### ISSUE TITLE
Incorrect description of the 2nd test in challenge Inventory Update

### ISSUE THREAD

**Issue by MagiaSN** [freeCodeCamp/freeCodeCamp#13277]
#### Challenge Name

Inventory Update
https://www.freecodecamp.com/challenges/inventory-update

#### Issue Description

The description of the 2nd test:
```
updateInventory(...).length should return an array with a length of 6. 
```
should be:
```
updateInventory(...) should return an array with a length of 6. 
```

#### Browser Information

Not relevant

#### Your Code

Not relevant

#### Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/15558746/22830421/74a4b266-efe1-11e6-8e93-aa4d0fed20c5.jpg)

Would it be ok if I open a pull request? :)

**Comment by raisedadead** [comment]
@MagiaSN What a catch! :tada: :open_mouth: 

We would love a pull request, and since you found it you should get the credit! Thanks a lot.
Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), please have a read.

Let us know in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need any assistance.

**Comment by MagiaSN** [comment]
@raisedadead Thanks for your quick reply! I have opened a pull request :) #13279

**Comment by raisedadead** [comment]
@MagiaSN this issue will be closed automatically when the PR is merged, thanks a lot for your contribution!

**Comment by MagiaSN** [comment]
@raisedadead Thanks again. Learned a lot today!
