### ISSUE TITLE
[beta] Unclear description in Applied Visual Design: Create Visual Balance with the Height of an Element

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13288]
Challenge [create-visual-balance-with-the-height-of-an-element](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-with-the-height-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

---

The description says "This challenge changes the layout **of the links** by stacking them to look more like a list.", but we're just changing the height of an h4 element, not the links'. Also I don't think "keep everything balanced" will be clear for someone new to graphic design, I'd clarify that. Why should I care about balance? Why should I arrange the elements like a list? The height property was already introduced, if the goal of this challenge was to explain what balance is, it is not a good explanation in my opinion.

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 12 ก.พ. 2017 00:45 "Marco Fras" <notifications@github.com> เขียนว่า

**Comment by HKuz** [comment]
Hi @Atomk - thanks for pointing out the issues with this challenge. That first sentence about the links being in a list definitely shouldn't be there, it's probably an artifact from the pre-Beta QA process (there were multiple iterations through this section). Since there's little detail about visual balance and it's re-using the `height` property right after it was taught, I'd say we should remove this challenge entirely.

Since the seed code flows through all the 'Google Card' challenges in this section, we should also edit the instructions and tests in the prior challenge "Applied Visual Design: Adjust the Height of an Element Using the height Property" so it applies a `height` of `25px`. This way, we don't need to edit all the following challenges' seed code.

For anyone that wants to work on this, please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors). Thank you! 🎉 👍 💯

**Comment by Manish-Giri** [comment]
I'll take this up.
