### ISSUE TITLE
Issue for:"Turn an Image into a Link"

### ISSUE THREAD

**Issue by Sashokmd** [freeCodeCamp/freeCodeCamp#13298]
Ok, so this is my code: 

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a></p>

<a><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<a href="#"><img
                 src="https://bit.ly/fcc-relaxing-cat" alt="Three kittens running towards the camera. "></a>
```

Everything is correct. I did it how it tells me to do, but everytime i run the tests there is this problem: 
"Your a element should be a dead link with a href attribute set to #." Can you fix it please?

**Comment by erictleung** [comment]
@Sashokmd Thank you for reporting this issue. Your code does not satisfy the requirements of the challenge. Please take a look at the instructions again.

> Place the existing image element within an anchor element.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
