### ISSUE TITLE
[beta] Additional test required for "Coding Interview Data Structure Questions: Remove from a Set"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13312]
Challenge [remove-from-a-set](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/remove-from-a-set) has an issue.

I think this challenge needs an additional test to verify that the `remove()` method can handle cases where it's passed items not present in the `Set`. This would require one additional check in the solution:

```js
this.remove = (x) => {
  if (!collection.has(x)) return;
  
  // remove x from collection
}
```

This would make the implementation a bit more robust. What do you think?

**Comment by Greenheart** [comment]
Note that the `challengeSeed` of the next challenge uses this check.

**Comment by Manish-Giri** [comment]
@Greenheart I'd like to do this, but I have a question. I'm guessing you're proposing that this be added to the `challengeSeed`, as the starter code - 
```
this.remove = (x) => {
  if (!collection.has(x)) return;
  
  // remove x from collection
}
```
In that case, the instructions would also need to be amended to make it clear that the task is to **complete** the implementation of `this.remove`, as opposed to creating it from scratch, because now `this.remove()` would already exist in the `challengeSeed`. Did I get it right?

**Comment by Greenheart** [comment]
@Manish-Giri I mean that we add a test that tries to remove an item that doesn't exist, and then assert that it can handle that case.

An example test case could be
```js
assert.deepEqual((function(){ var test = new Set(); test.add('a'); test.add('b'); test.remove('c'); return test.values(); })(), ['a', 'b'] , 'message: Your <code>remove</code> method should only remove items that are present in the set.');
```
The final sentence(s) of the instructions also need to be changed.
