### ISSUE TITLE
Get back end boilerplates into version control

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#13327]
I propose we get all of the back end boilerplates into version control so that issues can be raised against them and we can patch them.

**Comment by QuincyLarson** [comment]
@JosephLivengood you are currently the most knowledgable person on our back end challenges and projects. Would you be interested in exporting these boilerplates from GoMix into as few GitHub repos as necessary and giving them proper names? 

We can then hop on a Skype call and transfer these repos to freeCodeCamp organization's GitHub account. Then when we make changes to these, we can update the boilerplates from these repos. What are your thoughts on this?

I'm also mentioning @Em-Ant on this thread in case he has any ideas.

**Comment by JosephLivengood** [comment]
@QuincyLarson I can definitely take this issue, was about to volunteer to :+1: 


**At first glance there are a few options:**

- Keep them in **this** repository _(which could aid in maintaining them and raising/fixing issues)_ like:
```
externals/
  gomixboilerplates/
    apismicroservices/
      *
    infosecqualityassurance/
        finalprojects/
        infoSec/
        qualityassurance/
          {boilerplatetopic/orig challenge name referenced in}/
            *.js(project files)
```
_(with better package names)_

- Do the same (keeping them all in 1 repo with good packaging) but just in a fcc-boilerplates repo instead of this one

- Splitting up into a few repos by certification

- Other?

**Comment by QuincyLarson** [comment]
@JosephLivengood I'd also love for these to all be in the same repo, but by having them in separate repos, we significantly simplifying things for campers who just want to clone a repo: 
![](https://www.evernote.com/l/Ar_rK5U1TR1FgKV3UCGwobhLPmwJdbTA4nAB/image.png)

This will be the case with campers building these locally. Then instead of telling campers to use a specific boilerplate, we can instead tell them to clone a specific repo. This makes our boilerplates more platform agnostic. We would no longer have to maintain the boilerplates on GoMix itself.

**Comment by JosephLivengood** [comment]
@QuincyLarson Would that mean users wanting to build on gomix will instead of remixing just import?

If we keep gomix users remixing and local users get a quick lesson on _sparse clones_ it may work as well. Either way I'm good, would the many repos needed by on a new freecodecamp account as to not spam this one?

**Comment by QuincyLarson** [comment]
@JosephLivengood my thinking is these would all be under the freeCodeCamp organization. We might even be able to ask GoMix if they could create a URL that creates a project from a GitHub project - sort of a "GoMix this" URL. Then we could have the best of both worlds - a single source of truth, and a quickly deployable boilerplate.

**Comment by JosephLivengood** [comment]
@QuincyLarson Got it- fully behind!

I can start creating them working backwards and hopefully transfer the ownership tomorrow

_Also, great interview today!_

**Comment by QuincyLarson** [comment]
@JosephLivengood Thanks! :) It was awesome talking with Haseeb! 

OK - I'll reach out to GoMix and request this feature.

**Comment by JosephLivengood** [comment]
@QuincyLarson Looks like a total of 20 boilerplates. I've created them all and imported to each. We can connect on Skype later to transfer them over


Im going to look at merging all the microservice project boilerplates into 1 (most are nearly identical at this point already except the readmes have the user stories which will be on fcc already anyways). Also a couple sections use a couple boilerplates because development such as the infosec uses a new one when you get to BCrypt, and so I'll look at merging some and making those couple sections not require a new boilerplate unless necessary.

As far as the ISQA final projects, there is not a way to merge them into 1 boilerplate as some structure is needed for each to help use test certain concepts heavily like unit testing a handler.

_These changes, if you agree they'll help, wont be able to be made in the next week most likely however due to a busy schedule._

**Comment by QuincyLarson** [comment]
@JosephLivengood sounds good! I've reached out to GoMix and asked them about the "create a project from a GitHub repo" URL.

If the readmes are similar, we should try to figure out a way to collapse some of them into the same boilerplate. That way we won't have to maintain as many projects. We can talk about this when we skype. I'm available at your convenience.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue we've shifted all the boilerplates over to freeCodeCamp's organization. We can now one-click create GoMix projects from a GitHub repo using a URL.

@JosephLivengood is going to update all of the backend challenges in the seed file to communicate which boilerplates each challenge should use and provide one-click links to create these GoMix projects.

**Comment by Greenheart** [comment]
I really like what I can see in this thread - This definitely has many benefits!
