### ISSUE TITLE
escape sequence chalenge

### ISSUE THREAD

**Issue by fatoucha** [freeCodeCamp/freeCodeCamp#13338]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FisrtLine%20newline%20backslash%5C%5Cn%20SecondLine%20backslash%20carriage-return%5C%5Cr%20%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FisrtLine newline backslash\\n SecondLine backslash carriage-return\\r \rThirdLine"; // Change this line



```

**Comment by erictleung** [comment]
@fatoucha Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
