### ISSUE TITLE
Smallest Common Multiple works in browser but won't pass last test @ freecodecamp

### ISSUE THREAD

**Issue by LFri** [freeCodeCamp/freeCodeCamp#13348]
#### Challenge Name
https://www.freecodecamp.com/challenges/smallest-common-multiple

#### Issue Description

The freecodecamp challenge description is:
-----------------
Find the smallest common multiple of the provided parameters that can be evenly divided by both, as well as by all sequential numbers in the range between these parameters.

The range will be an array of two numbers that will not necessarily be in numerical order.  

e.g.  for 1 and 3 - find the smallest common multiple of both 1 and 3 that is evenly divisible by all numbers between 1 and 3.

This function code below gives all of the correct answers when I run it in my browser, but it won't pass the last test @ freecodecamp.com.  Below are the 4 tests at freecodecamp:

smallestCommons([1,5]); -- works in browser and also @ freecodecamp
smallestCommons([5,1]); -- works in browser and also @ freecodecamp
smallestCommons([1,13]);  -- works in browser and also @ freecodecamp
smallestCommons([23,18]); -- works in browser, not @ freecodecamp

#### Browser Information

* Browser Name, Version: Google Chrome Version 56.0.2924.87
* Operating System: Windows 10 Home

#### Your Code

    function smallestCommons(arr) {
      //find smallest common multiple between the range of two numbers
      var newarr = []; // lower and upper limit in order
      var newarr2 = []; // range between lower and upper limit
      var firstValue = 0; // firstValue of newarr2[];
      var nextValue = 0; // firstValue + 1 
      var lastValue = 0; // lastValue of newarr2[]
      var leastCommon = 1;
      var numToLoop = 0; // lastValue of newarr2[]*number of loops
      var leastCommonArr = []; //array to hold true, false
      var leastCommonArrTrue = []; //array of all true for compare
      var foundIt = false;  // trigger to stop trying
      var upperLimit = 1;  // all values in newarr2[], multiplied together
	
	//1 put the numbers in order
	if (arr[0] < arr[1]) {
	 newarr.push(arr[0]);
	 newarr.push(arr[1]);
	} else {
	 newarr.push(arr[1]);
	 newarr.push(arr[0]);
    }
	console.log("sorted newarr[] is: " + newarr);
    
	//2 add array of numbers from newarr[0] to newarr[1]
	firstValue = newarr[0];
	console.log("firstValue is: " +firstValue);
	lastValue = newarr[1];
	console.log("lastValue is: " +lastValue);
	nextValue = firstValue;
	console.log("nextValue is: " +nextValue);
	
	for (var i = 0; nextValue <= lastValue; i++ ) {
	  newarr2.push(nextValue);
	 // console.log(newarr2);
	  nextValue = nextValue + 1;
	 // console.log("nextValue is: " +nextValue);
	  }
	  console.log("newarr2 with incremental #s is: " + newarr2);
	  
	//2.5 create array of false values for leastCommonArr
	for (var p = 0; p < newarr2.length; p++ ) {
	  leastCommonArr.push(false);
	  }
	//  console.log("leastCommonArr  is: " + leastCommonArr);
	  
	//2.6 create array of true values for leastCommonArrTrue
	for (var q = 0; q < newarr2.length; q++ ) {
	  leastCommonArrTrue.push(true);
	  }
	//  console.log("leastCommonArrTrue  is: " + leastCommonArrTrue);
 
	//2.7 find upperlimit by multiplying all values in the array
	for (var s = 0; s < newarr2.length; s++){
	upperLimit = upperLimit * newarr2[s];
	console.log("upperLimit is: "+ upperLimit);
	}
	//3  find least common multiple by working through the multiples of the last number
	lastValue = newarr2[newarr2.length - 1];
	//4 test to see if leastCommon is divisible by the other values in the array
	//leastCommon starts as lastValue
	leastCommon = lastValue;
	numToLoop = newarr2.length;
	console.log("numToLoop: " + numToLoop);
      var n = 2;
      while( n <= upperLimit) {
      for (var m = 0; m < numToLoop; m++) {
	   if(leastCommon % newarr2[m] === 0) {
		leastCommonArr[m] = true;
		   }
	//	console.log("n is: " + n + " and m is: " + m);
	//	console.log("leastCommon is : " + leastCommon);
	//	console.log("newarr2[m] is: " + newarr2[m]);
	//	console.log("leastCommon % newarr2[m] is :" +  leastCommon % newarr2[m]);
	//	console.log("leastCommonArr is : " + leastCommonArr);
	//	console.log("---------");
		}
     for (var x = 0; x < leastCommonArr.length; x++ ){
			if (leastCommonArr[x] === leastCommonArrTrue[x]) {
			foundIt = true;
			}
			else {
			foundIt = false;
			break;
			}
		  }
		  
	if (foundIt === true) {
	break;
	}
      //reset leastCommonArr and increment n
      for (var y = 0; y < newarr2.length; y++ ) {
        leastCommonArr[y] = false;
        }
      //  console.log("leastCommonArr reset is: " + leastCommonArr); 
        leastCommon = lastValue * n;
         n = n + 1;
      } 
      console.log(leastCommon);
      return leastCommon;
      }

**Comment by OFFLlNE** [comment]
@LFri Thank you for reporting your issue.

Your code did work for me, you might try the following:
Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
Try the challenge in incognito mode. A plugin might be interfering with the tests.
Try the challenge in a different browser. There may be an issue with your version of Chrome.

**Comment by LFri** [comment]
Thanks OFFLINE.  I tried your three suggestions, and the code works in all three situations in my browser, but freecodecamp will still not pass the function for this test:  
smallestCommons([23,18]); -- works for all three suggestions, but still not @ freecodecamp.com

**Comment by raisedadead** [comment]
@LFri 

> the code works in all three situations in my browser, but freecodecamp will still not pass the function for this test

I am bit unclear when you state that it works in all three situations, but not on freeCodeCamp.com

To be sure:

- You are on a mobile device as per your opening post.
- Did you try the challenge on a desktop where it works but, fails on a mobile.
- Can you clarify what you mean exactly when you say it works on browser and fails in freecodecamp.com?

**Comment by raisedadead** [comment]
Can you please share screen shots of the challenge to help us better understand your issue?
Thanks a lot.

**Comment by LFri** [comment]
raisedadead, The "three situations" are in OFFLINE's first reply to me.  

The challenge works for all tests on my desktop browser, Chrome, as stated in my first posting.   The last test, smallestCommons([23,18]); works in my browser, but fails @ freecodecamp's window.

**Comment by raisedadead** [comment]
> Can you please share screen shots of the challenge to help us better understand your issue?

**Comment by LFri** [comment]
@raisedadead, you need to be working on this challenge @ freecodecamp to understand this issue.

**Comment by raisedadead** [comment]
@LFri 

Hey Lisa,

This issue is going no where, unless we have the clarification that are needed on queries we have. So once again I request you to kindly:

1. State the difference between the your browser and freeCodeCamp? Do you mean you run the challenges on the freeCodeCamp website which fails your code but you are able to pass it somewhere else in the browser? 

2. Can you share the screenshots of the issue that you are facing?

Unless you can provided detailed clarification of the exact issue you are facing, I am afraid we wont be able to analyze it.

**Comment by LFri** [comment]
I guess I assumed that the folks who would respond to this posting understood the basics of how freecodecamp works, and would want to know about this potential glitch in that system.  Instead, the responses (except for @OFFLINE who showed good knowledge of the situation and some very wise suggestions, tyvm!!) have not shown an understanding of the freecodecamp challenge system.
To reproduce this exact issue, all you would have to do is copy/paste my code into the freecodecamp window for the identified challenge and compare that to how the script works in any browser.  Screen shots of the same would be a waste of time.  I have also clearly identified which tests pass and which ones fail. Done.

**Comment by raisedadead** [comment]
@LFri 

Hey Lisa,

My sincerest apologies, but as a matter of fact we get hundreds of issues everyday, and tens of changes as pull requests to the codebase everyday. So YES, we need very precise issue descriptions to help us help you. This is a voluntary effort which keeps getting back to you.

I have gone through the issue at least three times over to understand your query.

Screenshots maybe a waste of your time, but they surely are essential for the volume of requests we get every day. 

Your opening post states that device used was a mobile browser. Hence my need for more specificity in the issue's root cause.

Now coming back to your query, the last test that is not passing because of a check that we have on the code for potential infinite loop.

Just add `//noprotect` on top of your code. It should pass all the challenges.

Please search the [Forum](https://forum.freecodecamp.com) and seek further assistance in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by minhtinh885** [comment]
I write it with "// noprotect" 
`// noprotect
function smallestCommons(arr) {
  var sum = 1, pre = 0, last = 0, re = 0;
  var array = [];
  if(arr[0] <= arr[1]){
    pre = arr[0];
    last = arr[1];
  }else{
    last = arr[0];
    pre = arr[1];
  }
  
  var flagOuter = true, flagInner = true, k = 1;
  
  while(flagOuter === true){
    sum = pre * k;
    flagInner = true;
    for(var i = pre; i<=last; i++){
      if(sum % i !==0) flagInner = false;
    }
    
    if(flagInner === true) flagOuter = false;
    
    k++;
  }
  return sum;
}


smallestCommons([1,13]);`

**Comment by LFri** [comment]
OK, thank you.  Here's a link to freecodecamp's discussion of **// noprotect**.  My gut tells me that this would NOT be a best practice in the real world because you'd never want to intentionally allow any browser to just keep processing what it thinks may be an infinite loop, but at freecodecamp's site, I understand that this statement was necessary given it took a very long time for my function to calculate the correct answer for the last test. smallestCommons([23,18]); 

https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550  

For what it's worth, google tells me that // noprotect is needed at a few other online learning sites as well in similar situations.   In a very quick search, I can find no documentation that identifies an appropriate place to use // noprotect in the real world.... but there's probably some very rare case, so it's always good to know about these things.  Thanks.

**Comment by raisedadead** [comment]
@LFri 

From the same article on forum and the very first line of the article:

> The Free Code Camp code runner has a built in Infinite Loop Protect feature, leveraged from JSBin's Loop Protect. The loop protect injects some code into user created loops to allow a safe exit if more than ~500ms has passed without exiting the loop. Loop protect will catch many, but not all infinite loop issues

This is a feature that we specially have developed based on a feature on JSBin (A web IDE for developers).

It's unlikely you will find any documentation because its not a standard tool. But its very much well documented in its use on freeCodeCamp via the same article.

The bottom line here being the solution you have for the last test case triggers this protection. 

I suggest that you can either submit the solution with `//noprotect` with your code as it is,  while sure is not a good practice, which means you may want to refactor your code to not trigger the protection.

You may refer the article on how to work with the `//noprotect` flag.

Thanks and happy coding!

**Comment by marekjedlinski** [comment]
Yes, it is a loop protection false positive. Please note: the problem described by the OP occurs even when you copy+paste some of the **official solutions** from https://forum.freecodecamp.com/t/freecodecamp-algorithm-challenge-guide-smallest-common-multiple/16075

I have scrapped my two initial solutions which - it turns out - were algorithmically correct, but triggered the protection. When my third solution didn't work either, I came here looking for a bug. Turns out, all three of my solutions were fine. I'd say it is **definitely a bug in FCC code to fail correct solutions without a slightest indication that the problem may be somewhere else** (a message such as "we could not test your solution, because it took too long to execute").
