### ISSUE TITLE
According to Reddit, the Arguments Optional text is confusing

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1335]
https://www.reddit.com/r/learnprogramming/comments/3d59uj/js_return_a_function_that_expects_another_argument/

We should probably tighten up the copy.

**Comment by BerkeleyTrue** [comment]
Seems ok with me. Maybe some campers can chime in?

**Comment by destroyme** [comment]
I can see part of the issue being with the second sentence of the problem:

"If only one argument is provided, return a function that _expects one additional argument and will return the sum_."

This isn't the easiest thing to digest.

**Potential copy:**
If only one argument is provided, **then** return a function that expects one ~~additional~~ argument and ~~will~~ return**s** the sum.


Some more potential confusion _could_ be in the example:

"For example, add(2, 3) should return 5, and add(2) should return a function that is waiting for an argument so that var sum2And = add(2); return sum2And(3); // 5"

**Potential copy:**
"For example, add(2, 3) should return 5, and add(2) should return a function**. This function should be** waiting for an argument so that var sum2And = add(2); return sum2And(3); // 5"

**Comment by BerkeleyTrue** [comment]
Discussing it with @benmcmahon100 the wording here definitely needs to change. Possibly splitting the tests. These changes will show up when we move over the beta into production.

for instance, this:
```js
expect(add(2)(3)).to.equal(5);add(...) is not a function
```
should split into two tests:
```js
expect(add(2)).to.be.a.function; // add(2) should return a function
expect(add(2)(3)).to.return(5); // add(2)(3) should return 5
```

and so forth.

plus @destroyme 's suggestion
If only one argument is provided, then return a function that expects one argument and returns the sum.


cc @EllieAdam


DFTBA
