### ISSUE TITLE
Quote escape

### ISSUE THREAD

**Issue by pamela113** [freeCodeCamp/freeCodeCamp#13373]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%20%5C%22string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; // Change this line

var myStr = "I am a \"double quoted \"string inside \"double quotes\".";

```

**Comment by erictleung** [comment]
@pamela113 Thank you for reporting this issue. You're almost there. Watch your spacing to match exactly what is asked in the challenge.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by mbabaian** [comment]
I am having the same issue that Pamela mentioned in Issue # 13373. My code is:

var myStr = "I am a \"doubled quoted\" string inside \"double quotes\".";

The console.log() window prints: 
myStr = I am a "double quoted" string inside "double quotes."

So it looks it's marking me wrong is because "myStr" is being printed, but that's not an error on my part. I've done a hard refresh and cleared browser history yet I'm still having the same issue. 

Thank you!

**Comment by texas2010** [comment]
@mbabaian 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by johngarcia9110** [comment]
@texas2010 This particular challenge does hang even when the correct code is entered. Took multiple browser refreshes in order for it to accept my answer. 

Code/solution for reference:

`var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line`

Test hangs on:

You should use two double quotes (") and four escaped double quotes (\").

Even though test passes on:

Variable myStr should contain the string: I am a "double quoted" string inside "double quotes".

**Comment by pamela113** [comment]
Thanks John!

**Comment by texas2010** [comment]
@johngarcia9110, this challenge dont have an issue.  she almost got it.

Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by GreatestDane** [comment]
There was definitely something wrong with this challenge, I am just breezing through these lessons as a quick refresher and I submitted the same answer several times before it was finally accepted. Very frustrating.
