### ISSUE TITLE
Right or wrong

### ISSUE THREAD

**Issue by refriga5** [freeCodeCamp/freeCodeCamp#13371]
Using CSS:

```html
<style>

  H2 { color: blue;}
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by duper101** [comment]
Wrong.

<style>
  .blue-text {
    color: blue;
  }
</style>

**Comment by refriga5** [comment]
It didn't paste correctly when it posted. 
<style>
H2 {color: Blue;}
</style>

**Comment by refriga5** [comment]
It did it again! Excuse me, I will get the the Github.

**Comment by erictleung** [comment]
@refriga5 Thank you for reporting this issue. Please do fill out the issue template when making an issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
