### ISSUE TITLE
binaryAgent challenge -- freecodecamp won't pass the function, but it works in my browser

### ISSUE THREAD

**Issue by LFri** [freeCodeCamp/freeCodeCamp#13384]
The following function works in my browser for both freecodecamp tests for the binaryAgent challenge....but will not pass in the freecodecamp window.

The tests are:
binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111");

and

binaryAgent("01001001 00100000 01101100 01101111 01110110 01100101 00100000 01000110 01110010 01100101 01100101 01000011 01101111 01100100 01100101 01000011 01100001 01101101 01110000 00100001");

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

function binaryAgent(str) {
  var i = 0;
  var position = 0;
  var code = "";
  var newstring = "";
  
  for (i = 0; i < str.length; i++){
  if (str[i] === " ") {
    //newstring = newstring.concat(" ");
    position = i;
	//console.log(position);
	code = str[i-8]+str[i-7]+str[i-6]+str[i-5]+str[i-4]+str[i-3]+str[i-2]+str[i-1];
	//console.log(code); // 8-digit
	code = parseInt(code,2); 
	//console.log(code); // integer
	code = String.fromCharCode(code);
	//console.log(code); // letters
	newstring = newstring.concat(code);
	//console.log(newstring);
   } 
  }
  console.log(newstring);
  return newstring;
}

**Comment by cdrainxv** [comment]
@LFri: Your code doesn't output the expected string for the test cases. For instance, instead of `Aren't bonfires fun!?` and `I love FreeCodeCamp!`, your outputs are: `Aren't bonfires fun!` and `I love FreeCodeCamp`.

Note: This page is for posting issues related to the direct functionality of the site. Challenge related issues and concerns is best suited for the various [help rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or even the forum itself. I highly recommend the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) for javascript related questions. Thanks!

**Comment by LFri** [comment]
@cdrainxv: thanks.  I thought it was a glitch with freecodecamp's functionality, hence posted here.  You are correct. Thanks!

**Comment by Greenheart** [comment]
I'm closing this as resolved. Thanks @cdrainxv for triaging and happy coding to you both! :blush:
