### ISSUE TITLE
Local Scope and Functions issue with commented code.

### ISSUE THREAD

**Issue by lukashanak** [freeCodeCamp/freeCodeCamp#13409]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope(myVar)%20%7B%0A%20%20myVar%20%3D%205%3B%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%20%0A%2F%2Fvar%20myVar%20%3D%20300%3B%20%20%0A%2F%2F%20line%207%20is%20what%20I%20am%20%20talking%20about..%20If%20I%20commend%20it%2C%20I%20succesful%20finish%20the%20challenge..%20but%20when%20I%20delete%20line%207%2C%20so%20it%20doesn%27t%20work...%20and%20if%20I%20UnComment%20it%2C%20so%20it%20doesn%27t%20work%20too..%20That%27s%20a%20bug%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope(myVar) {
  myVar = 5; 
  
  console.log(myVar);
} 
//var myVar = 300;  
// LINE 7 IS WHAT I AM TALKING ABOUT.. IF I COMMENT  IT, I SUCCESFUL FINISH THE CHALLENGE.. BUT IF I DELETE LINE 7, IT DOESN'T WORK... and if I UnComment it, so it doesn't work too.. That's a bug
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope

// Now remove the console log line to pass the test


```

**Comment by raisedadead** [comment]
We do have an issue with commented code not working. This is also the case on beta.

**Comment by Greenheart** [comment]
Sorry, but I'm not sure I understand the issue here.

Given the following challenge seed code:
```js

function myLocalScope() {
  'use strict';
  
  
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);

// Now remove the console log line to pass the test
```

to pass this challenge:
1. add a local `myVar`
2. remove the `console.log()` call outside of the function.

Then the following code passes the tests
```js

function myLocalScope() {
  'use strict';
  var myVar = 'totally a variable'
  
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope

// Now remove the console log line to pass the test
```

**Comment by Greenheart** [comment]
@lukashanak I think the issue with your code above is that the `'use strict'` option is disabled, which causes your code to behave differently.

Without strict mode, variables declared without for example `var` in front will be turned into global variables, which should prevent the tests from passing.

What I find strange though is that the commented line actually makes the challenge pass. Since you neither used `'use strict'` or `var` in front of `myVar`, your code shouldn't pass as I explained above.

@raisedadead I've noticed this behavior earlier as well.

**Comment by raisedadead** [comment]
Yup and I notice that this is the case in the beta as well. I guess adding `using strict;` in the seed is one way to go. But that's gonna lead to unwanted issues, all together.

**Comment by Greenheart** [comment]
@raisedadead Maybe we could add a hidden `'use strict'` in the `head`-section of the challenge?

**Comment by Marmiz** [comment]
>add a hidden 'use strict' in the head-section of the challenge?

@Greenheart  In my opinion this will only teach bad behavior since a camper can remove the tag, submit a wrong code and still pass it giving them the false impression to have done the right thing.
Or in other word we are actually teaching (or perhaps not-teaching) a valuable lesson: why strict is important and why globals aren't always a good thing.

I would rather add some comment line (and maybe change the CSS associated) to `use strict` to inform the user to never remove that line

```
"use strict"    //NOT remove this line
```
Or add a test cases that will look for strict mode and prompt fail if removed.

**Comment by raisedadead** [comment]
@Greenheart 

The thing is I can pass the challenge with completely incorrect code like this:

```js
function myLocalScope() {
  'use strict';
  
  
  console.log(myVar);
}
myLocalScope();
var myVar;
// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);

// Now remove the console log line to pass the test
```

You will notice that both the test cases should have been false with the above code.

**Comment by Greenheart** [comment]
@Marmiz @raisedadead Good points!

I'm not so sure what to do about this. What's your ideas? :blush:

**Comment by systimotic** [comment]
Hey everyone! There's a couple of things going on here.

To understand why things are happening, looking at the tests is really helpful here
https://github.com/freeCodeCamp/freeCodeCamp/blob/f373eca1aaf963671dcafcd96f199214df7a2077/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L2527-L2530
  
This explains why @raisedadead's sample passed. The text `var myVar` was in the code (passing the first test), but because it was not set to anything, it was still undefined (passing the first test).

It also explains why @lukashanak's original code only worked with the comment there. The text `var myVar` was only present within the comment (passing the first test). Because it was in a comment, even though the text was there, the variable was still undefined (passing the second test). If the comment was removed, the text `var myVar` was no longer anywhere in the code (failing the first test).

It is currently possible to pass this challenge with the following as the entire code:
```js
// var myVar
```

### Potential solution
Requiring `myVar` to be set to a specific value will make sure incorrect solutions like the one @raisedadead shared won't work. We could also check whether the line that contains the `var myVar` declaration doesn't start with `//`. Checking for multiline comments seems to complicated for a regex, but the chance of that happening seems low.

**Comment by QuincyLarson** [comment]
@systimotic Great detective work here, and thanks for resurrecting this old (but unresolved) issue.

Yes - I agree with your potential solution. Could you create a PR for this?

Regarding removing commented code before processing, this sounds like it would be a good long-term solution for this kind of situation, but would involve changes to the platform itself. So I'll CC @BerkeleyTrue on this.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
