### ISSUE TITLE
missing; before statement

### ISSUE THREAD

**Issue by suresh2291** [freeCodeCamp/freeCodeCamp#13402]
Challenge [Introducing Else Statements](https://www.freecodecamp.com/challenges/introducing-else-statements#?solution=%0Afunction%20testElse(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3E%205)%20%7B%0A%20%20%20%20result%20%3D%20%22Bigger%20than%205%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20(val%20%3C%3D%205)%20%7B%0A%20%20%20%20result%20%3D%20%225%20or%20Smaller%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElse(4)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) {
    result = "Bigger than 5";
  }else (val <= 5) {
    result = "5 or Smaller";
  }
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(4);


```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. else does not want (statement) there. so remove the (val <= 5) after else
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by suresh2291** [comment]
Thank you
After posting the issue here,  i have tries as you mention above.It worked.
