### ISSUE TITLE
add image to webpage lacks valid path (extension)

### ISSUE THREAD

**Issue by smkatz** [freeCodeCamp/freeCodeCamp#13419]
add image to webpage lacks valid path (extension)

#### Challenge Name
Add Images to your Website

#### Issue Description
"Try it with this image:

https://bit.ly/fcc-relaxing-cat" needs an extension.
https://www.freecodecamp.com/challenges/add-images-to-your-website

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
@smkatz 
`https://bit.ly/fcc-relaxing-cat` is a shortened URL for `https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg` 

That said, I can understand your confusion when you see this in the instructions, well the shortened URL should work in any case, but can be confusing for some.

./cc @freeCodeCamp/moderators thoughts?

**Comment by Greenheart** [comment]
I guess we could maintain a set of redirection links, so campers see `https://freecodecamp.com/public/images/relaxing-cat.png` instead of the bit.ly link. But I doubt it would be worth the effort of maintaining the redirects.

Another idea is to clarify what the link stands for - **Note: the exact contents of the link is not important - all you need to know is that the `src` attribute allow us to tell the browser from where it should get images**

**Comment by smkatz** [comment]
I love FCC. However, as someone who has some familiarity with HTML and CSS,
and some difficulty with certain elements of syntax, I notice that
sometimes things are not explained as completely as a book would do. I
understand all of the above and what I would suggest is at some point
talking about paths -- relative paths, absolute paths, and supported file
extensions. Uploading a .psd is not going to render inline, and they need
to know that. I once had someone make a Dreamweaver site completely of
absolute paths. Needless to say, that didn't go well. Thanks for this great
tool.

**Comment by Greenheart** [comment]
@smkatz Thanks for your thoughtful feedback! :+1:

I really like the idea of adding a challenge (to the Basic HTML section?) explaining how links work by giving a couple of examples.

#### Here's a few types of links I can think of from the top of my head:
* Relative - `/some/nice/image.png`
* Absolute - `https://example.com/some/nice/image.png`
* Using the protocol that was used to get the current website - `//example.com/some/nice/image.png` [Explanation of how they work](https://blog.wikimedia.org/2011/07/19/protocol-relative-urls-enabled-on-test-wikipedia-org/)

@smkatz Since you came up with the idea, would you like to help create a challenge to teach this highly valuable concept? Me and other contributors would be happy to guide you through the process :smile:

**Comment by Greenheart** [comment]
Like your example with the `.psd` file, we could also add a challenge to explain different image (or file-) formats. Then we could explain why some images don't work on the web, even though they work in other environments outside of the browser.

**Comment by smkatz** [comment]
I have always been a believer in open source... and would be happy to
contribute in this way. I was trying to master some shell stuff today which
is what delayed me. I'll forgive you for having the same name as me.

**Comment by Greenheart** [comment]
@smkatz Glad to hear that! :smile:
I think a good work flow could be to create an outline for the challenge as a comment in this issue. Then me and other contributors can 1. give feedback and 2. help you get the challenge added to the website.

So don't worry about having a local environment for the moment - let's focus on how to structure the challenge. Here are some [guidelines to help with the structure the challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md). Feel free to ask if you need anything! :blush:

**Comment by QuincyLarson** [comment]
@smkatz Thanks for your feedback. Extensions aren't required for image paths. And since it would significantly increase the length of the URL - and the likelihood of a camper mistyping someone, I'm in favor of leaving this as is.

I like @Greenheart's suggestion of covering relative VS absolute path. If that's something you're interested in pursuing, please open a new issue specific to that, or create an issue and create a PR. I think late in the HTML section would be a good place for it, if we can make it reliably work.

**Comment by smkatz** [comment]
Image paths do not require extensions? I recognize short URLs work because
they redirect but they do require extensions in the standard.

I came up with the rel vs. Absolute path idea.

Bootstrap is awesome.

**Comment by Greenheart** [comment]
@QuincyLarson Yeah, that was @smkatz's idea! :blush:

[Image paths doesn't seem to require extensions](http://stackoverflow.com/a/5110673)
