### ISSUE TITLE
[Beta]Certificate is not accessible/profil public same thing

### ISSUE THREAD

**Issue by Parad0xJ** [freeCodeCamp/freeCodeCamp#13432]
Hi all,

I have finished all challenges until "Your Responsive Web Design Certificate" .
But I can't see my certificate  "Responsive Web Design Certificate"
 And I can't acces to my profile Public, them problem of this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/13075

#### Issue Description

 Each time I click on " Show me my profil public" I have this Alert : "Oops! Something went wrong. Please try again later"
and more I can't see where is my certificate.

#### Browser Information

* Google Chrome Version 56.0.2924.87/ for test Firefox 5.0.1(idem)
* windows 10 
And I have tested with My iphone 6
on ios 10
and google for ios
exactly them problem.

Ps : it's my first certificate with freeCodeCamp and I can't see him it's too bad.

 Thanks

**Comment by Greenheart** [comment]
@Parad0xJ Thanks for reporting this issue!

I tried to get my JS algorithms certificate and it didn't work either. To be honest, I think this has to do with how the beta version of the site is set up. I suspect we need to wait until the new curriculum is released to the main site (https://freecodecamp.com) before we can get our certificates.

I'd recommend you to continue working through the next sections - **but please keep in mind that your progress won't be saved on the beta site.**

To earn certifications, you technically only need to complete projects (and challenges marked with a * on the map). Save the links to these projects, and save for example JavaScript algorithms **so that you can re-post them to the main site once it's updated.**

Your progress of coding challenges (the shorter lessons done in the freeCodeCamp) editor aren't required to earn certificates. They are merely there for your own learning (and brownie points! :smile:)

Happy coding!

**Comment by Parad0xJ** [comment]
Hi @Greenhart
why you said that :  "but please keep in mind that your progress won't be saved on the beta site."
are you sure of that, so I work for nothing with beta version !?

**Comment by texas2010** [comment]
freeCodeCamp site and beta site have the separate database. that is why in fcc site will not have your process if you work on a challenge at beta site.

**Comment by Parad0xJ** [comment]
@texas2010 
Hi

What is the relationship with the non-saving of my progress in beta?

**Comment by Greenheart** [comment]
@Parad0xJ As @texas2010 said, we run two separate versions of the site. The beta-database gets reset every once in a while (~1 month).

If there's one thing I want you to take away from this thread, it's the following:
> Working through the Beta curriculum will not save your progress, but will give you access to a lot of new content.

Most people who work through the beta site do so because they want to learn the things that the new curriculum teach. By completing coding challenges, they learn new skills that they then can use to build projects. And more valuable than the progress, is the knowledge you gain by learning.

So don't fear working through the beta curriculum. The progress you make on for example projects (like the ones you did for the responsive web design certificate) will not be in vain as you easily can save the links to the projects - and submit them to the main site once it's been updated.

That way, you get access to new content and can start working on the projects that will be required for the new certificates **before they even are released**. If you want to help make freeCodeCamp better, you will also have a great opportunity to get open source contributions!

I hope that helps. Feel free to ask any further questions! :blush:

**Comment by Parad0xJ** [comment]
@Greenheart 
Ok thanks for all this information, I don't know that.

**Comment by Greenheart** [comment]
@Parad0xJ Did you start with the beta site?

**Comment by Parad0xJ** [comment]
No with fcc no beta in first https://www.freecodecamp.com/parad0xj until 12 february or 13

**Comment by Greenheart** [comment]
@Parad0xJ Ah, ok. Just remember to save your project links + JavaScript algorithm solutions (That you can see by visiting the challenge page).

Good luck and happy coding! :smile:

**Comment by Parad0xJ** [comment]
Thanks for all

**Comment by systimotic** [comment]
Certificates in the beta will be handled in https://github.com/freeCodeCamp/freeCodeCamp/issues/12794
@Greenheart Do you think this can be closed?
