### ISSUE TITLE
[beta] "ES6: Mutate an Array Declared with const" passes test 3 without the array being sorted

### ISSUE THREAD

**Issue by elrolfe** [freeCodeCamp/freeCodeCamp#13437]
#### Challenge Name
[ES6: Mutate an Array Declared with const](http://beta.freecodecamp.com/en/challenges/es6/mutate-an-array-declared-with-const)

#### Issue Description
To begin with, I added `"use strict";` to the top of the code, and commented out the second assignment of s so the code would compile.  I expected the third test (Test s is sorted) to fail, but it passed.

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87 (Official Build) (64-bit)
* Operating System: Mac OS X El Capitan 10.11.6
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

"use strict";

const s = [ 5, 7, 2 ];
// change code below this line

//s = [2, 5, 7];
// change code above this line
// Test your code
console.log(s);

```
#### Screenshot

![screen shot 2017-02-18 at 8 02 06 pm](https://cloud.githubusercontent.com/assets/25251/23098151/36308a7a-f615-11e6-91fd-26b498c54fab.png)

**Comment by Greenheart** [comment]
@elrolfe Thanks for reporting this issue!

We currently have some issues testing the transpiled ES6 code, and because of that the ES6 challenges don't work properly. In this case though, there are no tests - just comments explaining what we should test for once the test framework is updated.

But despite that, feel free to work through the challenges and give feedback! :blush:

**Comment by pocahontas123** [comment]
Hello, i write it:
"use strict";

const s = [5, 7, 2];
// change code below this line
s[0] = 2;
s[1] = 5;
s[2] = 7;
// change code above this line
console.log(s);

But it doesn't work
