### ISSUE TITLE
[beta] Test error: Intermediate Algorithm Challenge - Missing Letters

### ISSUE THREAD

**Issue by fixtheelvis** [freeCodeCamp/freeCodeCamp#13431]
The test  fearNotLetter("abcdefghjklmnopqrstuvwxyz") is supposed to return undefined because there's supposed to be no letters missing in the string. However, the letter "i" is very clearly missing. My solution is correct and passes all tests and returns undefined when the string above has the missing i. 

I hope this helps you guys catch this error

**Comment by Greenheart** [comment]
@fixtheelvis Thanks for reporting this - What a catch! :open_mouth: 

Don't mind the bot, we haven't taught it proper manners yet! :smile:

Here's the assertion for the test case you are refferring to:
```js
assert.isUndefined(fearNotLetter('abcdefghijklmnopqrstuvwxyz'), 'message: <code>fearNotLetter(\"abcdefghjklmnopqrstuvwxyz\")</code> should return undefined.');
```

As you can see, each test case concists of an assertion with something that evaluates to true/false and a message. In this case, the message is supposed to show the full sequence - but as you pointer out, it's missing the letter i. Since it's part of the message-string, it's visible to campers (at least those who catch it!), but it won't affect the assertion. That's why the test still passes.

Since you caught this error, would you like to make a contribution and fix it? Me and other contributors would be happy to guide you through the process! :smile:

**Comment by Quinn-H** [comment]
Hi, @Greenheart @raisedadead Can I fix this issue ?

**Comment by Greenheart** [comment]
@Quinn-H Thanks, that would be awesome!

See [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) for help getting started and come chat with us in [the contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you have any questions. 

Happy coding! :smile:
