### ISSUE TITLE
Portfolio contact form - sending email

### ISSUE THREAD

**Issue by mare011rs** [freeCodeCamp/freeCodeCamp#13452]
#### Issue Description
Hey guys, I made it to the "make a portfolio" part and now I'm struggling on making a contact form. No matter what I do it always opens "New Mail" in outlook when I hit submit. Is it possible to have it just send an email to a predetermined (my) email?

#### Browser Information

* Browser Name, Version:  Chrome 56.0.2924.87 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

  <div id="contact" class="container-fluid">
    
    <h3 id="message" class="section-heading text-center">Send me a message</h3>
    
    <form class="form-horizontal" action="mailto:mare011rs@gmail.com"
 method="post" name="contact-me">
   
<div class="row">
  <div class="col-md-4">
  <div class="container-fluid">
    <input class="form-control input-lg" type="text" placeholder="Name" required>
      
    <input class="form-control input-lg" type="text" placeholder="Email" required>
  </div>
  </div>
     
  <div class="col-md-8">
  <textarea class="form-control input-lg" rows="5" cols="30" placeholder="Your message..." required></textarea>
  </div>
</div>
      
       
      <input class="btn btn-primary" type="submit" value="Send">
      
      
      
    </form>
   
  </div> 
    

```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by ingochris** [comment]
I would use server-side scripting. 
Alternatively, pass with `window.open('mailto:mare011rs@gmail.com?subject=subject&body=body');`

**Comment by erictleung** [comment]
@mare011rs Thank you for reporting this issue. GitHub issues are for bugs on the site, not programming help. Please use the chat rooms for more help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
