### ISSUE TITLE
I am getting errors? saying its not red

### ISSUE THREAD

**Issue by tibbitson** [freeCodeCamp/freeCodeCamp#13454]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(225%2C0%2C0)%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C0%2C225)%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
   .red-text {
    color: rgb(225,0,0)
  }
  .orchid-text {
    color: rgb(218,112,214)
  }
  .sienna-text {
    color: rgb(160,82,45)
  }
  .blue-text {
    color: rgb(0,0,225)
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by imcodingideas** [comment]
I think it's because you don't have the ; there. I just went to test this and it worked perfectly for me.

**Comment by cdrainxv** [comment]
@tibbitson: You are using the wrong rgb() values for both the red-text and blue-text classes. You are currently using `225` instead of the actual value of `255`. Also make sure to affix a `;` at the end of the rgb() values.

Note: This page is only for reporting issues. Challenge related questions should be asked in the [help](https://gitter.im/FreeCodeCamp/Help) room.

**Comment by erictleung** [comment]
@tibbitson 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
