### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by imcodingideas** [freeCodeCamp/freeCodeCamp#13455]
Challenge [catch-off-by-one-errors-when-using-indexing](http://beta.freecodecamp.com/en/challenges/debugging/catch-off-by-one-errors-when-using-indexing) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Its throwing an error: "Cannot read property 'length' of null" however; in my browser this works as expected.

```js


function countToFive() {
  let firstFive = "12345";
  
  for (let i = 0; i < firstFive.length; i++) {
    console.log(firstFive[i]);
  }
  
  return firstFive;
}

countToFive();

```

**Comment by erictleung** [comment]
@imcodingideas you've removed too much code (`len` variable) and it is causing the tests errors. This challenge needs to be updated.

Here are some suggestions, but not limited to:

- Put some comments in the seed code so that it guides the camper to edit the appropriate code.
- The test messages should be simpler to understand. They seem a bit vague in describing what is expected of the camper.

**Comment by Manish-Giri** [comment]
@erictleung I'll take this up..
