### ISSUE TITLE
Help, I don't understand it

### ISSUE THREAD

**Issue by mosessaleh** [freeCodeCamp/freeCodeCamp#13479]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0Avar%20studlyCapVar%20%3D%2010%3B%0Avar%20properCamelCase%20%3D%20%22A%20String%22%3B%0Avar%20titleCaseOver%20%3D%209000%3B%0A%0A%2F%2F%20Assignments%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;
var studlyCapVar = 10;
var properCamelCase = "A String";
var titleCaseOver = 9000;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
