### ISSUE TITLE
Beta: Typo ES6: Destructuring Function Parameters

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#13486]
#### Issue Description
```
This removes some extra linees and mainly a syntactic sugar.
```
linees should be lines.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by JosephLivengood** [comment]
Good catch! 💯

**Comment by ading25** [comment]
Hi I'm a first time contributor I'd like to fix that typo if no one's working on it already!

**Comment by JosephLivengood** [comment]
@ading25 Great!

[CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) can help you get started.

If you have any questions, please come chat with us in the [Contributors Chat] Room(https://gitter.im/FreeCodeCamp/Contributors).

**Happy Coding!** :1st_place_medal:

**Comment by ading25** [comment]
I'm looking for the typo and can't seem to find "linees". Could I get some help locating the typo? Thanks!

**Comment by JosephLivengood** [comment]
@ading25 Sorry! Upon looking [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L510) it appears to have been fixed in staging and I did not notice!

---

This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I'm closing this issue. When staging will be pushed to production again, your issue will be resolved.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
