### ISSUE TITLE
hex code

### ISSUE THREAD

**Issue by dwarren96** [freeCodeCamp/freeCodeCamp#13500]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23ff0000%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%2300ff00%3B%0A%20%20%7D%0A%20%20.dodger-blue-text%20%7B%0A%20%20%20%20color%3A%20%232998e4%3B%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23ffaf00%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodger-blue-text%22%3EI%20am%20dodger%20blue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20orange!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #ff0000;
  }
  .green-text {
    color: #00ff00;
  }
  .dodger-blue-text {
    color: #2998e4;
  }
  .orange-text {
    color: #ffaf00;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```
Maybe someone else has had this problem; the challenge wont check off that I've completed turning my h1 "orange-text" to orange using hex code. I don't think there's anything wrong with my code because it comes up on the practice screen as orange.

**Comment by JosephLivengood** [comment]
Thank you for reporting this issue.

Your hex for `.orange-text` is not the hex for orange provided by us in the challenge description

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
