### ISSUE TITLE
My Challenges code is changing to someone else solution!! 

### ISSUE THREAD

**Issue by akampoori** [freeCodeCamp/freeCodeCamp#13518]
#### Challenge Name
Return Largest Numbers in Arrays (243)

I have complete challenge 243 with my code using for loop but when i come back to it to review my code. i noticed it is different solution code. 

#### Browser Information

* Browser Name, Version: chrome v 56.0.2924.87 with %100 zoom
* Operating System: windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code
```js
function largestOfFour(arr) {
  // You can do this!
  var largeNum = 0;
  var newArray =[];
  for (var i = 0; i < arr.length; i++){

    for (var j = 0; j < arr[i].length; j++){
       if (largeNum < arr[i][j]){
         largeNum = arr[i][j];
       }
       newArray[i] = largeNum;
    }

    largeNum = 0;
  }

  return newArray;
}

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

and when i revisit this challenge it come with the following code:

```js
function largestOfFour(arr) {
  // You can do this!
  var newArr = [];
  for (var i = 0; i < arr.length; i++) {
    newArr.push(Math.max.apply(null,arr[i]));
    
  }
  
  return newArr;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

PS I just notice that most of my basic algorithm challenges code has change to someone else code. please notify me whats going on.
Thank you

**Comment by akampoori** [comment]
Hi @raisedadead, thank you for your advice, i thought that but i do submit my work and just view others solution without submitting. The only thing it my be possible that i login in my other laptop but still i don't see why getting others solution as i just view it without submitting their solution. I just submit mine. I will try to clear my browser cache and cookies. Thanks.

**Comment by raisedadead** [comment]
@akampoori Thanks for the describing the flow that you followed. I now have a better idea to what might be happening.

- You solved one challenge.
- You then visited some one else's challenge for reviewing their code.
- You went on with solving more challenges.
- Then you came back to the previous challenge (via the map).

If this is the case then yes, you would see the solution for someone else in the previous challenge, because that was the last solution that was cached in your browser.

BUT, that said, if you go to your profile, and then open the challenge from there (not from the map), you would ideally see your solution.

The whole point is what you see on your profile page, is what you submit.

Let us know if this helps in the understanding.

Thanks and happy coding.
