### ISSUE TITLE
[beta] Error - loopProtect is not defined

### ISSUE THREAD

**Issue by gelbelle** [freeCodeCamp/freeCodeCamp#13532]
Challenge [catch-arguments-passed-in-the-wrong-order-when-calling-a-function](http://beta.freecodecamp.com/en/challenges/debugging/catch-arguments-passed-in-the-wrong-order-when-calling-a-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function positivePowers(b, e) {
  let result = 1;
  if (e <= 0) return result;
  for (let i = 1; i <= e; i++) {
    result *= b;
  }
  return result;
}

let base = 2;
let exp = 3;
let power = positivePowers(base, exp);
console.log(power);

```

I corrected the error of the arguments in calling the function. I'm getting the error message "loopProtect is not defined" "loopProtect is not defined"

**Comment by cdrainxv** [comment]
This error is also only found in firefox not Chrome or Safari. The current fix is just refreshing the page upon the `loopProtect is not defined` console message, although an outright fix would be preferred.

----
Also, upon looking at the challenge code, the positivePowers() function does not seem to account for powers that are positive **fractions**. This function currently doesn't support the definition of a power: "A number obtained by raising a base to an exponent". Maybe instead of using a limited for loop it can be updated to use Math.pow(), which would also require the replacement of the very strict and unmalleable first test. Another benefit of this is that campers will be able to test this function with their own bases and exponents, while still keeping the overall purpose of this challenge unchanged.

Proposed challenge code:
```js
function positivePowers(b, e) {
  return Math.pow(b, e);
}

let base = 2;
let exp = 3;
let power = positivePowers(exp, base);
console.log(power);
```
with an inclusion of the purpose of the Math.pow() function and it parameters in the description (can be borrowed straight from mdn docs).


The additional tests that will need to written to assert that function returns positive powers: 
1. A positive base (either a whole number or fractional) results in a positive power. (Exponent value does not matter).
2. A negative base (either a whole number or fractional) results in a positive power only when the  exponent (either negative or positive whole number) is a multiple of 2.
3. the function doesn't return `NaN` or if it does, the message should be what caused it. (Although this test is not required if a reference to the `Math.pow()` mdn doc is included as it has examples and the reason for such cases.)

Note: With the above changes this line will also need to be reworded:
> The following function positivePowers raises a base to a positive exponent. Unfortunately, it's not called properly - fix the code so the value of power is the expected 8.


I realize the above changes to the challenge might be extensive, but mathematics is a subject of absolute definitions (in almost all cases). 
---
All the above can be considered moot by including in the description field a note stating that by "positive" powers the scope of this function is not considering combinations of bases and exponents that result in positive **fractional** powers. Nevertheless, I believe that the above  suggestions (which can be added to or refactored) seems to be a better fix, in my honest opinion, than just adding a note listing a restriction of the function.

Reference: [Math.pow()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow)

**Comment by HKuz** [comment]
@cdrainxv - thanks for the feedback about the challenge example. You're right in that the example `positivePowers` doesn't cover all cases as it's written and we should re-factor this a bit. I think we can take your suggestion to replace the function body entirely with `return Math.pow(b, e);`, and just rename the function to something generic, like `raiseToPower`. `Math.pow()` makes the example even easier to follow, which is great since these challenges deliberately use simple coding examples so campers can focus on understanding the bug, vs. the implementation.

We don't have to change the tests because the challenge is checking that the camper fixes the order of the arguments in the function call.

Finally, the instructions should use the new function name `raiseToPower` instead of `positivePowers`.

New seed code:
```js
function raiseToPower(b, e) {
  return Math.pow(b, e);
}

let base = 2;
let exp = 3;
let power = raiseToPower(exp, base);
console.log(power);
```
For anyone who would like to make this fix, please read the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and feel free to ask questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). The code for this challenge can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/debugging.json#L251). Thank you! 💯 🎁 🎆
