### ISSUE TITLE
jQuery Waypoint Instructions Are Not Clear for Code Academy "Sections" to Complete

### ISSUE THREAD

**Issue by angiecan** [FreeCodeCamp/freecodecamp#1353]
For example, what's confusing is that Step 5 of "Waypoint: Get Started with jQuery" says, "Go to http://www.codecademy.com/courses/web-beginner-en-bay3D/0/1 and **complete the first section**." 

The definition of "first section" is not clear to the user. As a result, user clicks the Code Academy link, goes to "Introduction to jQuery" step 1/13, but user does not know if step 1 is the "first section," some subset of the 13 steps, or if all 13 steps are the first section.

My suggestion is that FreeCodeCamp makes the instructions for Code Academy "sections" very clear by using the Code Academy heads and subheads, e.g., "Go to "Introduction to jQuery," and complete the "Manipulating HTML" section, which is made up of the following lessons: 
* See it to Believe It
* The Document Object Model
* Changing Targets
* What is jQuery

Thank you for considering this change. It will save users some unnecessary thinking so they can focus on the content.

**Comment by bugron** [comment]
I absolutely agree with you!
I remember when I was confused about that instructions. I "did" all jQuery Waypoints (first lessons of Codecademy jQuery course) and in first jQuery Waypoint there was something like "we're going to learn jQuery well" and I thought "Is that all"? And only then I returned to Codecademy and saw 1/13. That was nice )). So I finished jQuery course only today, hehe.

**Comment by lyelle** [comment]
I agree that it wasn't clear, but I followed them all just to make sure and be thorough. However, that's not my problem with it. My problem is:

Unlike the CatPicApp, it is not always clear what we are trying to accomplish with the code, ESPECIALLY when more than one chapter is required to show the end result, meaning that the "fruits of labor" are completely invisible, often causing me to simply *attempt* to copy code without knowing what I am doing.

*Attempt* is the appropriate word, because it copies your code from one chapter to the next, which can seriously compound problems if your code was good enough to pass through their filters, but not quite correct. EVEN WORSE: you can't just use the "Reset Code" button to undo all changes-it simply resets it to the last point it was autosaved, meaning it could have been your incorrect code. 

With the CatPicApp, it was possible to "cheat" by looking ahead to the next Waypoint, where the correct code was already inserted into the document. I found this to be very helpful, because:

1. I could see what the correct version looked like.
2. I could see the results of my work.

So, here is my request/suggestion:

FCC needs to make it's own jQuery tutorials. I know that might be a lot to ask of a free resource, but to be perfectly honest, I learned just as much from this 2 minute intro as I did from the 8 hours or so I was messing around at Codecademy!

http://www.codecademy.com/courses/web-beginner-en-JwhI1/0/1

**Comment by BerkeleyTrue** [comment]
Closing as all codecademy courses will be removed in next iteration of curriculum.

Happy Coding!
