### ISSUE TITLE
confusion 

### ISSUE THREAD

**Issue by akshanshshrivastava** [freeCodeCamp/freeCodeCamp#13545]
after the instruction first it says "Remove all the backslashes ( \ )"
and on the 3rd it says "Only remove the backslashes \ used to escape quotes."
That doesn't make sense to me. 

#### Challenge Name

https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0A%0A%0Avar%20myStr%20%3D%20%22%22%3Ca%20href%3D'http%3A%2F%2Fwww.example.com'%20target%3D%5C%22_blank%5C%22%3ELink%3C%2Fa%3E%22%22%3B%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A
#### Screenshot

![issuecode](https://cloud.githubusercontent.com/assets/21341620/23265010/5a12f4d0-fa09-11e6-8328-a874548a8631.png)

**Comment by JosephLivengood** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
