### ISSUE TITLE
Change the Font Size of an Element - Zoom 100 % Issue?

### ISSUE THREAD

**Issue by kbaniqued** [freeCodeCamp/freeCodeCamp#13549]
#### Challenge Name

https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element

#### Issue Description

It doesn't let me pass this challenge even though browser is currently 100%.

#### Browser Information

* Browser Name: Chrome Version: 56.0.2924.87
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scrached sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18409231/23273028/5566876e-f9b2-11e6-8e08-d08e61623d37.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by mnedariya** [comment]
<style>
  .red-text {
    color: red;
  }
  p {
font-size 16px;
  } 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>




this is right code yet i get issue
