### ISSUE TITLE
Symmetric Difference Independent of Order

### ISSUE THREAD

**Issue by CrockAgile** [FreeCodeCamp/freecodecamp#1358]
I have a potential issue with the [Symmetric Difference Bonfire](http://www.freecodecamp.com/challenges/bonfire-symmetric-difference). I do not believe symmetric difference should be order dependent, but the current tests rely upon a deep equality implementation that seems to care about order. For instance with the code below I get the following error: "expected [ 3, 4, 5 ] to deeply equal [ 3, 5, 4 ]"

```javascript
function sym() {
  var count = Object.create(null); // hash object
  var sets = Array.prototype.slice.apply(arguments); // array of sets
  sets.forEach(function(set) {
    // filter not unique elements
    set.reduce(function(prev,curr) { 
      if (prev.indexOf(curr) === -1) {
        prev.push(curr);
      }
      return prev;
    },[]).forEach(function(el) {
      count[el] = !count[el];
    });
  });
  return Object.keys(count).filter(function(el) {
    return count[el];
  }).map(function(el) {
    return +el;
  });
}
sym([1, 2, 3], [5, 2, 1, 4]);
```

**Comment by SaintPeter** [comment]
Watch this video:
https://www.youtube.com/watch?v=PxffSUQRkG4

Order of operation does matter. 
A &#916; B &#916; C &ne; C &#916; B &#916; A

**Comment by CrockAgile** [comment]
A good explanation! Thank you, issue closed.

**Comment by davidkwan95** [comment]
I'm sorry, but order of operation doesn't matter in Symmetric Difference. As stated in Wikipedia:
>The symmetric difference is commutative and associative (and consequently the leftmost set of parentheses in the previous expression were thus redundant):
AΔB = BΔA,
(AΔB)ΔC = AΔ(BΔC).

**Comment by alf808** [comment]
Is there a way to reopen this? because according to wikipedia:

The symmetric difference is commutative and associative (and consequently the leftmost set of parentheses in the previous expression were thus redundant):
AΔB = BΔA,
(AΔB)ΔC = AΔ(BΔC).

the youtube video presented above does not demonstrate at all that
A Δ B Δ C ≠ C Δ B Δ A

I think the equality of sets is independent of order. {1,2,3} = {3,2,1}
see more here: http://www.cs.odu.edu/~toida/nerzic/content/set/basics.html

**Comment by SaintPeter** [comment]
It may no be the case that order does not matter.  The important take away is that you must do either:
(A Δ B) then apply Δ C 
or
(B Δ C) then apply Δ A

The naive solution, which I attempted at first, was to combine all of the arrays and remove duplicate elements. In particular, my first intuition was that the following result would not include a 5 as the output:
```javascript
//      A         B         C
sym([1, 2, 5], [2, 3, 5], [3, 4, 5])
```
However, when you apply A Δ B, you get [ 1, 3 ], which you then apply [ 1, 3 ] Δ C to get [ 1, 4, 5 ].
Conversely, you could do:
B Δ C = [ 2, 4 ] Δ A = [ 1, 4, 5 ]

It's counter-intuitive, but I believe the video illustrates it well with the overlapping venn diagrams.

**Comment by alf808** [comment]
commutativity AΔB = BΔA and associativity (AΔB)ΔC = AΔ(BΔC) are not relevant to ordering of set elements. Sorry about that it was 3am and my eyes were tired. But order is NOT important just with this statement:
Two sets are equal iff they contain the same elements: ∀x:(x∈A⟺x∈B)⟺A=B

**Comment by alf808** [comment]
it's not important to take away to apply the operation serially i.e. (A Δ B) then apply Δ C 
or (B Δ C) then apply Δ A . That to me is elementary. It is however important that if FCC is doing set theory that they also do a proper test for set equivalence or set equality.

**Comment by SaintPeter** [comment]
FCC is limited by the ability of Javascript to do assertions.  As far as I know it is not possible to do an array comparison that disregards order.  I suppose they could do a .sort() operation on your answer . . .

You can take it as an unwritten requirement of the test that you retain the element order when applying the difference.

**Comment by alf808** [comment]
That defeats the purpose of doing set theory at all. They either do set theory concept with symmetric difference or not at all. FCC can redefine and redesign the challenge without calling it symmetric difference. Set equality is fundamental in set theory. Why do set theory and not do set theory? it's contradictory.

**Comment by SaintPeter** [comment]
> That defeats the purpose of doing set theory at all.

While I can't speak for the FCC team, I personally don't think that the purpose of the challenge is to do "set theory" at all.  I don't even know what set theory is, but I was able to solve the problem.  The Bonfires are basic coding and algorithm practice, not advanced or theoretical mathematics.  The accepted solution is perhaps a subset of the theoretically acceptable solutions, but is at least partially correct.

The "Map the Debris" Bonfire uses orbital mechanics in an overly simplified way that, I'm sure, an astrophysicist would wince at.  That doesn't reduce its value as a *programming* problem.  Bonfires are programming practice, not mathematics practice.

Assuming that you were only going to accept the solutions as described in the test cases, how would you rename and rewrite the problem description to retain the fundamental coding challenge while assuaging your concerns about violations of set theory?

**Comment by alf808** [comment]
The bonfire challenge is not designed and tested properly. set theory is not "advanced theoretical mathematics". I believe it's taught in elementary school.

For some reason, I thought you were part of the FCC team. Is there a way for you to bring up the simple case of set equality to the team. I know many people have been making much ado about unions, intersections, and complements. And yet equality is ignored.

**Comment by SaintPeter** [comment]
>  I believe it's taught in elementary school.
Must be part of "Common Core" - either that, or just another case of the American school system failing me.  ;)

These issues are the best place to bring up concerns you have with the curriculum.  You can also, as I have, make changes to the problem descriptions and submit them via a Pull Request.  You can also tweet @freecodecamp.

> And yet equality is ignored.
As I've been trying to point out, I don't think it's being ignored, *per se*, it's being simplified.  This is due to the limitations of javascript and computer programming in general.  

This is the test case that I presume you're having trouble with:
```javascript
assert(sym([1, 2, 5], [2, 3, 5], [3, 4, 5]), [ 1, 4, 5] )
```
Javascript only allows you to say that one thing is literally equal to another.  I don't believe that it's possible to say "Equal to the permutations of the following array" - at least not without writing a bunch of code.  As a *simplification* of the general case, we can say that [ 1, 4, 5 ] is the preferred presentation of the solution.

So, I ask again:
Since we can't make Javascript into a magical set solving machine, how do you propose that the problem be rewritten to work with the current test cases and not undermine all of set theory?

**Comment by alf808** [comment]
May be the easiest is to say is something like the following. "The next part of is not part of set theory. But please sort your results to pass the test case." Of course, FCC also has to sort its results.

**Comment by alf808** [comment]
HAHAHA. I don't know about the common core but I was in the elementary school in the early 1960s. The NUNS taught us sets very early. set equality is fundamental. Incidentally, it is also true that
 {1,2,3} = {1,1,1,3,2,3} . it meets the AXIOM ∀x:(x∈A⟺x∈B)⟺A=B . I had to capitalize axiom because it truly is axiomatic.

**Comment by labiej** [comment]
Well there exist objects known as multisets.
Here {1,2,3} =/= {1,1,1,3,2,3} thinking of those I was able to solve the problem.

**Comment by alf808** [comment]
I can "solve" the problem too. I've been doing this for a week now. Some of my code has been hacky so I can "solve" the problem or pass the test cases. But it's not my point. Why go through the pretense of doing a set theory concept? why bother with this symmetric difference corollary S∗T=(S∪T)∖(S∩T) and not bother with a set equality axiom ∀x:(x∈A⟺x∈B)⟺A=B ? If symmetric difference is not the point of the problem, then I think it should be redesigned and it not be labelled symmetric difference. If symmetric difference is the point, then set equality is fundamental and axiomatic.

**Comment by bitgrower** [comment]
fwiw, the solution provided in the wiki does not pass because, where there are duplicate numbers, they are duplicated in the answer (in the wiki solution, but not in the test case anwers...)

**Comment by SaintPeter** [comment]
@bitgrower You can file an issue on the Wiki Repo and we'll take care of it.
