### ISSUE TITLE
Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.

### ISSUE THREAD

**Issue by darkshadow4578** [freeCodeCamp/freeCodeCamp#13620]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Ethan-Arrowood** [comment]
@darkshadow4578 Please fill out the rest of this issue or close it. If you need help with a challenge go to the public gitter channel: https://gitter.im/FreeCodeCamp/Help

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
