### ISSUE TITLE
[GitHub Workflow for Contributors]: Improve use of labels for reviewing PRs

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13626]
This is a continuation of [this discussion](https://gitter.im/FreeCodeCamp/Contributors?at=58b459bc4150746b151525c9) about how to use labels for PRs.

Instead of using the `blocked` label for PRs that have been reviewed but need further changes, we concluded that something like `changes requested` could be more friendly towards contributors than the `blocked` label.

If we want to make this change, we probably want to add this to the moderator guidelines or labeling guide.

@freeCodeCamp/moderators What do you think?

**Comment by no-stack-dub-sack** [comment]
@Greenheart Where is the labeling guide located? I was thinking about this just the other day actually, so funny that you should bring this up. I think labeling in general could use some work, and a guide that explains how to appropriately label, both for PRs and for issues, should be more readily available. Perhaps I am missing something, but I have never come across the guide. 

And to address your question, yes, I think the "blocked" label gets a little ambiguous. In fact, I thought it meant that, as well as something else entirely. I thought it was most appropriately used when a PR should not be merged for one reason or another because another PRs changes will affect it, and so that other PR should go first. I think your suggestion for a new label is good, reserving "blocked" for use cases like these.

**Comment by erictleung** [comment]
I also agree that the `blocked` label could be unfriendly and ambiguous. Maybe we should have a separate or add-on to the labels to be PR specific. We should definitely have something along the lines of `in progress` (which exists already) and create the `changes requested`. Status labels will be great signs for contributors and us triaging PRs.

**Comment by Manish-Giri** [comment]
Speaking of `changes requested`, isn't there already a Github default `changes requested`? Like I see [on this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/13618).

![234](https://cloud.githubusercontent.com/assets/11348778/23390582/18eebebc-fd3d-11e6-82e0-59b8f6bd8366.png)

What do you think?

**Comment by erictleung** [comment]
@Manish-Giri good point. You can filter for those now on GitHub. Maybe we can just add `in progress` for those for easy visual recognition.

**Comment by Greenheart** [comment]
Thanks for your feedback! :smile:

This is how I see the workflow after reading your comments:
* Avoid the `blocked` label - rather use a GitHub review to leave a `changes requested` status (which mods easily can see).
* Replace `QA` with `in progress`

I'm unsure about the next steps though. Maybe we don't need a more formal process than the above two steps - An easier process is more fun to work with :stuck_out_tongue: 

Possibly:
* When the PR is ready, either do another review or swap `in progress` for `QA` to show that another mod needs to step in.
