### ISSUE TITLE
Had to change line below where stated not to. 

### ISSUE THREAD

**Issue by JacobMcCall2** [freeCodeCamp/freeCodeCamp#13623]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
    "alpha":"Adams",
    "bravo":"Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo":"Easy",
    "foxtrot":"Frank"
  };

  // Only change code above this line
  return lookup[val]; <--- had to change this line even though it is below the //only change code above this line. Slightly confusing.
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by Ethan-Arrowood** [comment]
@JacobMcCall2 This isn't an FCC issue. If you have questions regarding challenges please ask them here: https://gitter.im/FreeCodeCamp/Help 
F.Y.I you can solve this challenge without editing the return line by assigning result := lookup[val];

**Comment by texas2010** [comment]
@JacobMcCall2  Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

by the way, you are not supposed to touch this code
```
// Only change code above this line
  return result;
```

**Comment by TantienHime** [comment]
I had the same issue, but the code will only work when you change that line. I've looked through the forum and this is the only solution that has allowed it to pass. The instructions given on the initial code should be changed as stipulated above.
