### ISSUE TITLE
Having problem to style my tribute page

### ISSUE THREAD

**Issue by Rmanzo94** [freeCodeCamp/freeCodeCamp#13640]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
i cannot style my tribute page any classes i am using on html aren't working i don't know what's going on 
![2017-02-27 1](https://cloud.githubusercontent.com/assets/24912113/23393171/d92c0b06-fd35-11e6-83ad-0a22ddb38027.png)

**Comment by voidfare** [comment]
Did you set your codepen up to use bootstrap? Click the "Settings" tab at the top right and double check.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
