### ISSUE TITLE
bug @ escape sequence or issue with instructions or both

### ISSUE THREAD

**Issue by hathcode** [freeCodeCamp/freeCodeCamp#13652]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\r\nThirdLine"; // Change this line



```
The code I have written above satisfies the requested output, but does not display correctly and is judged incorrectly in the codechecker in the lesson.  I have tested it on other platforms, and it ouputs exactly as requested.  BTW, the instructions:

> Here is the text with the escape sequences written out.
> 
> "FirstLinenewlinebackslashSecondLinebackslashcarriage-returnThirdLine"
> 
are also misleading because that implies \n is not needed before the carriage-return and results in line three overwriting line two.  

Why does my code work on a standard platform, but not here?

**Comment by hathcode** [comment]
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

the above code passes (finally, pretty sure I had that at one point), but it DOES NOT produce ...

> FirstLine
> \SecondLine\\
> ThirdLine

...which is the stated desired outcome.  The result of the code that passes is ...

> FirstLine
> \SecondLine\ThirdLine
> 

or

> Firstline
> Thirdlinene\
> 

...where Thirdline overwrights the SecondLine as you would expect with \r but no \n.

**Comment by raisedadead** [comment]
Two issues with your code:

- The link that you have provided shows that you have typos in the `l` vs `L`.
-  Ignoring that if I use the code in the opening post of the the thread you have an extra `\n` before the `ThirdLine`

Please try once again, closing as not an issue with code base.

Thanks and happy coding!

**Comment by hathcode** [comment]
I had fixed that particular typo and got it passing as I mentioned.  The rest of my post still follows and holds true.  Did you read the rest of the post?  Perhaps it is a browser issue?  Even when I pulled up the devtools in Chrome and checked the console there, the output of the "passing" string is NOT what was requested in the challenge.  Maybe it is works in some browsers (as I have read that different browsers treat \n and \r differently.  That said, I tried it in my IDE and still had same outcomes.  The codechecker is only checking that you have the string written a certain way, but it is apparently not checking the output.  This issue needs to be reopened and addressed.  Here's a SO post that discusses n vs r and highlights my points:
http://stackoverflow.com/questions/10282314/what-is-a-r-and-why-would-one-use-it-with-a-n

**Comment by raisedadead** [comment]
My apologies, I missed on understanding the second comment on the thread.

**Comment by raisedadead** [comment]
The SO post surely helps. We have had this issue pop up quite a few times with issues such as the typos and unwanted chars.

What you explain sure is a case that needs to be handled.

Thanks for the report.

/cc @freeCodeCamp/moderators

**Comment by raisedadead** [comment]
@hathcode Just FYI, while we look at this once again. Different browsers have different implementations for the `\r` carriage return.

Chrome for instance chooses to ignore `\r` for a render on new line and while it renders `\n` on a new line.

**Comment by systimotic** [comment]
We recently made some changes to this challenge in the beta, as there were a lot of problems like this. 
First, we changed the sequence to something without `\r\n`, because as you noted, it acts weird. 
Then we changed the tests to test each part more specifically, hoping to reduce the amount of people confused by typo's they made. 

You can check out the [updated challenge](https://beta.freecodecamp.com/en/challenges/basic-javascript/escape-sequences-in-strings) on the beta site.
@raisedadead @hathcode Could you please take a look at the new version, and see if it resolves this issue?

**Comment by hathcode** [comment]
Thanks @raisedadead for diving back into this.  I did notice that there were quite a few issues related to this  lesson.  Perhaps a rewrite is in order?  The issue did make me dive into the nuances of /r and /n, and I learned quite a bit!  But I'm sure y'all don't want this to keep popping up either.  Maybe just keeping it simple, clarify /r and /n a little more (maybe a link to the SO for more info), and it seems to me the convention of having /n with /r is more standard across browsers than /r alone for rendering a new line  (Considering where they come from, it makes more sense to me that way, I actually learned to type on a typewriter), and changing the test requirements?  My two cents worth (which maybe 1 cent ;-) ).

**Comment by hathcode** [comment]
@systimotic I think that's much better!  Seems to accomplish the desired goal and is much more straightforward.  May I still recommend a link to some clarification on /n vs /r?  Reason being the first time I learned them elsewhere I really didn't understand them very well, and this issue made me think about it in a different way and dive deeper.  They also seem to pop up in interview questions from time to time, though I can't say how often they are used by professional programmers since I'm still looking for my first programming job :-).  Again, my pennysworth!

**Comment by systimotic** [comment]
@hathcode I get where you're coming from. I'd be open to adding a link if you could find a good resource.

One big advantage that the new version of the challenge has is that it no longer suggests that a carriage return creates a new line. We currently don't elaborate on the carriage return, backspace and form feed characters. I think that makes sense, as they are quite a bit more complicated to understand, and rarely used. 
A carriage return is sometimes used in combination with a linefeed, because _Windows_, but not in Javascript.

If there is a good resource that explains these in an easy to understand way, I think adding it would be fine. However, I think the Stack Overflow post might confuse and scare campers more than it helps them. In that case, I think leaving those characters unexplained is a better option. We could potentially even remove them from the table.

**Comment by raisedadead** [comment]
Maybe a forum wiki article (re-worded) one based on the SO post should be a way to go?

**Comment by systimotic** [comment]
@raisedadead That sounds like a great idea to me!

**Comment by systimotic** [comment]
@hathcode Would you be willing to create a [forum](https://forum.freecodecamp.com/) article to explain these escape characters?
Here are our guidelines for creating a wiki article https://forum.freecodecamp.com/t/guidelines-and-rules-for-wiki-articles/51920
If you don't yet have the trust level and aren't in for browsing around on the forum, but you would like to write the article, you can share the draft here and we'll make sure it ends up in the wiki.

**Comment by Chucqui** [comment]
i think the right one would be=
 "FirstLine\n\\\Secondline\\\\rThirdLine";  
but with this code i get 3 error messages back, but when i use the "carrage return" before the "backslach escape"=
"FirstLine\n\\\Secondline\r\\\ThirdLine";
 i get only one (myStr should have encoded text with the proper escape sequences and no spacing). Somebody help please...

**Comment by hathcode** [comment]
@systimotic Sorry so long in getting back on here.  I'd be glad to create an article!  I'll look at the wiki and either post on the  forum or here with the draft as you mentioned.  Might take me a bit, but I'll get it done as soon as possible.

**Comment by systimotic** [comment]
@hathcode Awesome, I'm looking forward to it! Don't worry, there's no hurry.

**Comment by mohamedwahshey** [comment]
Here it is::

**var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line**

You welcome.

**Comment by texas2010** [comment]
@mohamedwahshey 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by QuincyLarson** [comment]
@hathcode We're planning to create guide articles for all the challenges that don't already have one. Would you be interested in creating a guide article for this challenge and adding a brief explanation about /r vs /n in that article? You could model it after the other articles here: https://forum.freecodecamp.com/c/guides

Since this is fixed in beta, I'm going to go ahead and close the issue.
