### ISSUE TITLE
[beta] possible mistake, FCC: Test Suite

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13663]
I decided to work the projects on beta just to test everything out, it seems that the projects test suite, checks for almost every html element to have an id....

I think that is a mistake for class instead...

**Comment by tommygebru** [comment]
Also I am having a hard time getting this test to pass...

Layout #2 
The <img> element should be centered within its parent element.

For the project: Tribute page

**Comment by no-stack-dub-sack** [comment]
@tommygebru please follow the "Report Bug" link within the test suite and report this issue there if you don't mind. That is the correct repo for opening test suite related issues. Also, it is not a mistake that the test suite checks for IDs. This is an essential part of how the test suite works - we are singling out specific elements using IDs in some cases, where appropriate. 

When you open the issue on that repo - please also include a link to your project (if it's in CodePen) or additional code, so that we are able to diagnose the problem.

Also, please be sure to share your browser info - if you saw the alert when you first opened the suite - the app is currently optimized for chrome, and their may be issues in other browsers.

Thanks. Please close this issue once you open it in the correct place.

**Comment by no-stack-dub-sack** [comment]
@tommygebru Also, not sure where the actual issue is here - sounds like you were able to follow the directions and got the test to pass
