### ISSUE TITLE
[beta] Console output formatting of % character

### ISSUE THREAD

**Issue by onpikono** [freeCodeCamp/freeCodeCamp#13696]
Challenge [make-circular-images-with-a-border-radius](http://beta.freecodecamp.com/en/challenges/basic-css/make-circular-images-with-a-border-radius) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The console output displays characters &#37 instead of % character. Not a biggie but still.

```html


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 25%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by raisedadead** [comment]
![image](https://cloud.githubusercontent.com/assets/1884376/23513354/b39c5124-ff89-11e6-9021-ee06b661a434.png)

**Comment by donniereese** [comment]
Looking into this, I can confirm that I get the same error as @onpikono with the provided code.  I am using the same version of chrome on Mac and can reproduce on a current local build of freecodecamp.

It looks as though the console prints out the literal characters and not the ascii code equivalent.

**Comment by donniereese** [comment]
Okay.  So, from what I found at [Stackoverflow: Displaying unicode characters in codemirror](http://stackoverflow.com/questions/19217531/displaying-unicode-characters-in-codemirror) and it's linked threads, Codemirror will display litteral html-code characters unless you specifically set up for decoding them.  It doesn't look as though there are many instances of them, if more than this test at this moment.

I tested using just literal '%' and ',' characters, since that is what the html-codes represent for and they render correctly.

To the more experienced Contributors:  Is there a problem that I am unaware of using these characters or should we work out the function to decode the characters before inserting the string into codemirror?
