### ISSUE TITLE
Not really a bug but suggestion

### ISSUE THREAD

**Issue by ametthey** [freeCodeCamp/freeCodeCamp#13694]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
   result = "The " + myNoun + " is " + myAdjective + " and it " + myVerb + " " + myAdverb;

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

Hi, i'm not complaining about the exercise, but the thing that confuse me and get me to the wrong path is that the

 **var result = "";** 

The fact that the var result is equal to a string without anything inside is a bit confusing. Why not rather set it like

**var result;**

without any output(is it really an output?) it's perhaps a better way to understand it =)

Thanks in advance,

Albin.

**Comment by erictleung** [comment]
@ametthey thanks for the issue. The reason why the variable is set to an empty string is because of how the function is initialized, which is as

```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  

  // Your code above this line
  return result;
}
```

As you can see, there is also a return statement of `result`. If you have just `var result;`, there will be an error. This challenge is within the Basic JavaScript challenges and have not formally covered functions until eleven challenges later in [Write Usable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions).

I hope that makes sense. This is set up so that it is supposed to allow the coder to just focus on their code i.e. the stuff between the comments, rather than focus on what a function is and how it works. We're trying to strike a balance between teaching new concepts and showing how powerful programming is. If you have suggestions on how to improve this, we always welcome suggestions. Thanks!

**Comment by annemvelez** [comment]
I was stuck on this challenge for so long because I didn't know I was supposed to write result = 
      result = "The " + myNoun + " is " + myAdjective + " and it " + myVerb + " " + myAdverb;
I kept writing
     ("The " + myNoun + " is " + myAdjective + " and it " + myVerb + " " + myAdverb);
or    (myNoun + myAdjective + myVerb + myAdverb);
or     ("I hate this assingment" + myNoun + myAdjective + myVerb + myAdverb");
plus a lot of other things that I can't even remember.

**Comment by pamela113** [comment]
I'm still stuck on it now.  It's confusing and doesn't flow well as the next step from the previous assignment.

**Comment by texas2010** [comment]
@pamela113, if you got stuck, you could ask help at the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Happy Coding.

**Comment by pamela113** [comment]
finally passed after working on spacing.  Thanks!

**Comment by ametthey** [comment]
Thanks @erictleung for your inside ! =) I'll try to contribute with my thoughts without troubleling too much.

**Comment by anitawoodruff** [comment]
I agree this exercise is confusing - both students I mentored doing Free Code Camp javascript exercises got stuck on it. I think they were mostly confused because it comes before any explanation of how functions and arguments work. I advised they complete 'Write Usable Javascript with Functions' first. So I would suggest that either this exercise is moved to a later point so it comes after that one, or perhaps there's a way to adapt it so it doesn't use functions at all?

**Comment by erictleung** [comment]
@anitawoodruff thanks for the feedback and sharing your experience with mentoring students on these challenges.

@freeCodeCamp/moderators should we move this to somewhere after "Write Useable JavaScript with Functions"? In my opinion, the purpose of this challenge is to review the string concatenation concepts that were learned about 5 or so challenges previously. I like the idea of review or synthesis challenges, but I'm conflicted on whether to just "randomly" introducing concepts like functions without much information. 

My suggestion on fixing this issue would be to ideally move this challenge later on and somehow create another challenge in its current place that serves to review the concepts from earlier on. Maybe we can implement the slideshow sort of review like in [this introduction for regular expressions](http://beta.freecodecamp.com/en/challenges/regular-expressions/introduction-to-the-regular-expression-challenges), but instead of an introduction, it'll be more of a review checkpoint. Thoughts?

**Comment by QuincyLarson** [comment]
@erictleung yes - functions need to be more properly introduced first. I'm talking with a contributor, @edorado93, who's interested in expanding our function-focused challenges in the JavaScript section, and we could then move this challenge behind that.
