### ISSUE TITLE
Arguments Optional when page is loading Chrome opens printer 

### ISSUE THREAD

**Issue by DeanDro** [freeCodeCamp/freeCodeCamp#13708]
Challenge [Arguments Optional](https://www.freecodecamp.com/challenges/arguments-optional) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I am clicking to test my code the printer page is popping up and asks me to print the page. This is not happening when I am using Safari. 

My code:
```javascript

function addTogether() {
  
  var arg1 = arguments[0];
  var arg2 = arguments[1];
  
  function take_second(){
    print("Give me the second value");
    document.getElementByName('arg2');
    return arg2;
  }
  
  if (arg2===undefined){
    take_second();
  }
  return (arg1+arg2);
}

addTogether(2,3);

```

**Comment by erictleung** [comment]
@DeanDro thanks for the issue. The [`print()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) command is what is triggering your print popup. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Also, this isn't an issue with the site but with the code you're using. Thank you, and happy coding!
