### ISSUE TITLE
Won't grade code

### ISSUE THREAD

**Issue by cedmist** [freeCodeCamp/freeCodeCamp#13729]
I don't know if my code is right but my main issue is that it isn't being graded. All it says is "TypeError: Assignment to read-only properties is not allowed in strict mode"
I am pretty sure I didn't do anything unusual to cause this but I just really want to figure out how to get my code graded so that I can keep learning. 

Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%3D%22Hello%20World%22%3B%20myStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr="Hello World"; myStr[0] = "H"; // Fix Me



```

**Comment by Manish-Giri** [comment]
@cedmist While you got the code right, with - `myStr="Hello World";`
You're still trying to change a letter of the `myStr` string - `myStr[0] = "H";`, which is not right, because strings are immutable. 

The `// Fix Me` comment was there so you could edit the line and replace it with your new code. If you now delete this line - `myStr[0] = "H"; `,  it should work!

**Comment by erictleung** [comment]
@cedmist as @Manish-Giri has pointed out, you almost got it but are still trying to edit an immutable string, which is the subject of the challenge. Remove your code that tries to edit the string and you'll be fine.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
