### ISSUE TITLE
3rd sub-challenge is not completing

### ISSUE THREAD

**Issue by jigar786** [freeCodeCamp/freeCodeCamp#13748]
#### Challenge Name
hstand in line solution.

#### Issue Description
3rd subchallenge is not complementing and i think there is a issue

#### Browser Information
Chrome,firefox

#### Your Code
https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(6)%3B%0A%20%20var%20removed%20%3D%20testArr.shift()%3B%0A%20%20return%20removed%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C6))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/25462330/23581215/074392ee-0136-11e7-9642-51b8ffcbec4e.png)

**Comment by BhaveshSGupta** [comment]
Hi @jigar786,

There are few small issue with your code, I would recommend you to discuss this over [here](https://gitter.im/FreeCodeCamp/HelpJavaScript). Tests are work fine as of now.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by jigar786** [comment]
Yup its done!!
