### ISSUE TITLE
[Return Largest Numbers in Arrays] I've gotten same result, however I failed to pass

### ISSUE THREAD

**Issue by z16844** [freeCodeCamp/freeCodeCamp#13750]
#### Challenge Name

Return Largest Numbers in Arrays

#### Issue Description

As I mentioned on the title, I've gotten same result, however I failed to pass.

#### Browser Information

* Browser Name, Version: Safari 10.0.3(12602.4.8)
* Operating System: Mac OS X Sierra 10.12.3
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
function largestOfFour(arr) {
  var largest = [];
  arr.map(function(inner){
    var tmp = 0;
    $(inner).each(function(){
      if(this > tmp) tmp = this;
    });
    largest.push(tmp);
  });
  return largest;
}

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```
#### Screenshot

![2017-03-04 3 14 27](https://cloud.githubusercontent.com/assets/7421967/23581958/651b69c6-00ed-11e7-89eb-b14d844d57b9.png)
![2017-03-04 3 14 41](https://cloud.githubusercontent.com/assets/7421967/23581960/68f0f0c0-00ed-11e7-832f-97e7877d0ac1.png)
![2017-03-04 3 14 51](https://cloud.githubusercontent.com/assets/7421967/23581961/6904a660-00ed-11e7-90f9-49f2e84d30e4.png)

**Comment by Gardemarin** [comment]
Probably similar issue in "Basic JavaScript: Access Multi-Dimensional Arrays With Indexes". 
![screen shot 2017-03-04 at 21 21 08](https://cloud.githubusercontent.com/assets/24617345/23582383/d1feeb16-0120-11e7-8273-1fff970fc295.png)

**Comment by hay-dee** [comment]
@z16844 
For the [Return Largest Numbers in Arrays](http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/return-largest-numbers-in-arrays) challenge, the <code>this</code> variable in the <code>$(inner).each</code> loop refers to a Number object. This results in your largestOfFour function returning an array of Number objects. The current test checks for equality with an array of primitives, thus returning an error. 

As for the last test, initialising the tmp variable at 0 forces your largestOfFour function to only consider values greater than 0, thus ignoring the negative values.

@Greenheart @systimotic I feel that the current test can be updated to include a map function which converts array elements to primitives before testing. i.e. ( largestOfFour().map(function(x) {return x.valueOf();}) ) Any suggestions? 😄

**Comment by Gardemarin** [comment]
http://beta.freecodecamp.com/en/challenges/basic-javascript/shopping-list
It doesn't work too .. 
![screen shot 2017-03-06 at 16 33 57](https://cloud.githubusercontent.com/assets/24617345/23619247/fe10dbae-028a-11e7-8aab-e056d3a5fc49.png)

**Comment by systimotic** [comment]
@Gardemarin The challenges you shared work fine for me. Can you try it again? Perhaps they got fixed since the last time you tried them.

@hay-dee Nice debugging! Interesting suggestion. To me, this raises the question of whether we should allow instances of the Number object as a valid answer. I'm not sure about this.

From the jQuery docs:
> The .each() method is designed to make DOM looping constructs concise and less error-prone.

You're not supposed to use jQuery's .each for looping over anything that isn't DOM, that's what [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) is for.

I can't think of any other way that a camper would return a Number instance rather than a primitive. If we work around the case where it might happen behind the scenes, this may only cause more problems when the camper is on their own.
```js
var numbers = [1, 2, 3];
var specialNumber = 4;
var newNumbers = [];
$(numbers).each(function() {
  newNumbers.push(this * 2);
});

console.log(newNumbers[1] === specialNumber); // false
```
I expect things like that would happen if we work around this.
I think the we should close this as an issue with the solution. It returned Number instances, which is not the expected result, so the tests failed correctly.

**Comment by hay-dee** [comment]
@systimotic Thanks for the assistance! You are right that it might be better for them to learn to seek help on this matter instead of classifying as a bug, which would encourage the usage of <code>.each</code> in this manner 😄

**Comment by systimotic** [comment]
👍 Closing as an issue with the solution. Thanks @hay-dee for looking into this!

@Gardemarin If these issues persist, please open separate issues for them. Thanks!

**Comment by Greenheart** [comment]
@hay-dee Yeah thanks for looking into this, we need more discussions like this to help move the curriculum forward :blush:
