### ISSUE TITLE
Send from repository.

### ISSUE THREAD

**Issue by Myscript2010** [freeCodeCamp/freeCodeCamp#13759]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%0AGood) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>

Good
```

M-2010

**Comment by Myscript2010** [comment]
![m2010](https://cloud.githubusercontent.com/assets/15964890/23588899/2f732ab6-0179-11e7-9a88-685202ee0847.jpg)

**Comment by Myscript2010** [comment]
Learn to edit Script

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by Myscript2010** [comment]
Thanks for the explanation
