### ISSUE TITLE
Not sure why my code was blocked by the last two test?

### ISSUE THREAD

**Issue by junnanzhang** [freeCodeCamp/freeCodeCamp#13752]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%09arr.sort(function%20(a%2C%20b)%20%7B%0A%09%09return%20a%20-%20b%3B%0A%09%7D)%3B%0A%0A%09var%20num%20%3D%20arr%5B1%5D%20-%20arr%5B0%5D%3B%0A%09var%20x%20%3D%20arr%5B1%5D%3B%09%0A%09var%20b%20%3D%200%20%3B%0A%09var%20flag%20%3D%20true%3B%0A%09while%20(flag)%20%7B%0A%09%09flag%20%3D%20false%3B%0A%09%09for(var%20i%20%3D%200%3B%20i%20%3C%20num%2B1%3B%20i%2B%2B)%7B%0A%09%09%09b%20%3D%20arr%5B0%5D%20%2B%20i%3B%0A%09%09%09if%20(x%20%25%20b%20!%3D%3D%200)%20%7B%0A%09%09%09%09flag%20%3D%20true%3B%0A%09%09%09%7D%0A%0A%09%09%7D%0A%0A%09%09x%2B%2B%3B%0A%09%7D%0A%20%20return%20x-1%3B%0A%7D%0A%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
	arr.sort(function (a, b) {
		return a - b;
	});

	var num = arr[1] - arr[0];
	var x = arr[1];	
	var b = 0 ;
	var flag = true;
	while (flag) {
		flag = false;
		for(var i = 0; i < num+1; i++){
			b = arr[0] + i;
			if (x % b !== 0) {
				flag = true;
			}

		}

		x++;
	}
  return x-1;
}


smallestCommons([1,5]);

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. There is some infinite loop in the code as the console tells me
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
