### ISSUE TITLE
My code would not run

### ISSUE THREAD

**Issue by obusorezekiel** [freeCodeCamp/freeCodeCamp#13767]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0Aa%20%3D%206%3B%0Ab%20%3D%2015%3B%0Ac%20%3D%20%22I%20am%20a%20String!%22%3B%0A%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;

a = 6;
b = 15;
c = "I am a String!";


// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by Manish-Giri** [comment]
@obusorezekiel Your code isn't quite right. Please visit the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help with this challenge. The issue tracker is for reporting bugs with the website itself. 

Happy Coding.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by obusorezekiel** [comment]
This code was gotten from Number 123 in freecodecamp. I am finding it difficult to progress to the next page
