### ISSUE TITLE
Override Styles in Subsequent CSS: text is blue but it should be pink

### ISSUE THREAD

**Issue by Osorkonwow** [freeCodeCamp/freeCodeCamp#13775]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22blue-text%20pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text{
    color: blue;
  }
</style>
<h1 class="blue-text pink-text">Hello World!</h1>

```
As the result i can see blue text on the screen. But as we know - it should be pink, cuz the " the browser will use whichever CSS declaration came last."

**Comment by Osorkonwow** [comment]
![image](https://cloud.githubusercontent.com/assets/26163598/23615283/f462a108-0296-11e7-95f7-5270fd0a874c.png)

**Comment by Osorkonwow** [comment]
![image](https://cloud.githubusercontent.com/assets/26163598/23615345/23419204-0297-11e7-9308-2f03b30de1d2.png)

**Comment by Osorkonwow** [comment]
In the exercise result must be blue - so it passed. I made a mistake and it gives pass through, but it shouldn't.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
