### ISSUE TITLE
the target "nextInLine([5,6,7,8,9], 1) could return 5 by this code, but it still shows error. Is it bug?

### ISSUE THREAD

**Issue by jimmyyang886** [freeCodeCamp/freeCodeCamp#13784]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(item)%3B%0A%20%20item%20%3D%20testArr%5B0%5D%3B%0A%20%20testArr.shift()%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0A%2F%2Fvar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C1))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  testArr.push(item);
  item = testArr[0];
  testArr.shift();
  return item;  // Change this line
}

// Test Setup
//var testArr = [1,2,3,4,5];
var testArr = [5,6,7,8,9];
// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr,1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by Manish-Giri** [comment]
@jimmyyang886 Your code is incorrect. Please visit the [HelpJS Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance with the challenge.

**Comment by systimotic** [comment]
Hi @jimmyyang886! Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

I would agree that this is a confusing issue, it took me longer to spot than it should have 😅 

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by jimmyyang886** [comment]
Thank you very much, I will use help if I meet other issues in the future.
