### ISSUE TITLE
Code checker accepted a closing tag on a void element.

### ISSUE THREAD

**Issue by patrickMulligan** [freeCodeCamp/freeCodeCamp#13793]
#### Challenge Name
[Make Images Mobile Responsive](https://www.freecodecamp.com/challenges/make-images-mobile-responsive)

#### Issue Description

When adding a new image, I incorrectly added a full closing tag for the img element. The code checker accepted it as valid code and passed the challenge.  
The checker should have flagged the closing tag as invalid for a void element.

#### Browser Information

* Browser Name, Version: Chrome, Ver 56.0.2924.110 (64-bit) 
* Operating System: Chrome OS
* Mobile, Desktop, or Tablet: Chromebox

#### Your Code

```js
<img class="img-responsive" src="https://bit.ly/fcc-running-cats" alt="kittens running on the grass."></img>
```

**Comment by systimotic** [comment]
Hi @patrickMulligan! Thank you for reporting this issue.

While per [the HTML5 spec](http://w3c.github.io/html/syntax.html#void-elements) this is indeed invalid, because of the forgiving nature of HTML (and the browser in general), this is accepted. As you can see, it does work fine. A closing image tag is valid XHTML.

We do focus on teaching HTML5, and we try to use best habits in all the code we show, but we accept any working solution.

I hope this clears things up. I'm closing this, as I don't think this is a bug.
Happy coding!
