### ISSUE TITLE
Number all challenges

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#13809]
How about we add numbers to the challenges?

Problem: So many people come to the chat and say that they are stuck on XX-challenge, which actually does not tell helpers anything.

Solution: Add actual numbers to challenges ;)

**Comment by Manish-Giri** [comment]
A solution would be to **not** display brownie points by each challenge, which leads them to think that it is the challenge number.

**Comment by erictleung** [comment]
I agree that quick identification of challenges would be convenient with challenge numbers. However, I think the appeal of freeCodeCamp is that you can just jump around wherever you want. Having challenge numbers may indirectly make someone think that they have to go in order, which they don't. It's a small thing, but I think it's worth noting.

Another reason by people might be just saying I'm stuck without any other details is because they can have that chat window sidebar within the challenge window. So it might be hard for people to realize people can't read their minds on which challenge they are on.

I think just changing how the brownie points are displayed may help.

Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/12460

**Comment by OFFLlNE** [comment]
Yea, fair point eric. I think I will close this as a duplicate of #12460
Just no progress there for a month :)
