### ISSUE TITLE
Target Even Numbered Elements Using jQuery

### ISSUE THREAD

**Issue by haydennorthcott** [freeCodeCamp/freeCodeCamp#13833]
The challenge asks: "Try selecting all the even-numbered elements and giving them the classes of animated and shake."

The end result required $(".target:even").addClass("animated shake"); to pass. This resulted in targets 1,5 and 6 shaking.

These are not all even numbers.

**Comment by erictleung** [comment]
@haydennorthcott Thank you for reporting this issue. TPlease take a look at the challenge description once more:

> Note that jQuery is zero-indexed, meaning that, counter-intuitively, `:odd` selects the second element, fourth element, and so on.

Also, the challenge tests make it a little clearer

> All the target elements that computer considers even should shake.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
