### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nathan5226** [freeCodeCamp/freeCodeCamp#13840]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C-%0A--------------%3E--) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.0; RCT6303W87DK Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1>
-->
<h2>CatPhotoAp<p>Hello Paragraph</p
<-
-------------->--
```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. It clearly is NOT commented out
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
