### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by InquisitiveDev2016** [freeCodeCamp/freeCodeCamp#13846]
Challenge  Escaping Literal Quotes in Strings  https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%20var%20myStr%20%20%20I%20am%20a%20double%20quoted%20string%20inside%20double%20quotes%20.%20%3B%3B%2F%2F%20Change%20this%20line%20%20%20has%20an%20issue.%20User%20Agent%20is%3A%20code%3EMozilla%2F5.0%20%20Windows%20NT%2010.0%3B%20WOW64%3B%20rv%3A51.0%20%20Gecko%2F20100101%20Firefox%2F51.0%20%2Fcode%3E.%20Please%20describe%20how%20to%20reproduce%20this%20issue%2C%20and%20include%20links%20to%20screenshots%20if%20possible.%20My%20code%3A%20%20%20%20javascript%20var%20myStr%20=%20I%20am%20a%20double%20quoted%20string%20inside%20double%20quotes%20.%20%3B%3B%2F%2F%20Change%20this%20line%20%20%20%20%20

**Comment by erictleung** [comment]
@InquisitiveDev2016 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
