### ISSUE TITLE
Increment not happens in JavaScript

### ISSUE THREAD

**Issue by Robiussani152** [freeCodeCamp/freeCodeCamp#13853]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = myVar++;


```

**Comment by aaronang** [comment]
Hi @Robiussani152,

I definitely do not want to spoil the answer, but I would definitely recommend you to join the Gitter channel for help 😄 I can assure you that this challenge does not contain a bug.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
