### ISSUE TITLE
[Beta] Use CSS Animation to Change the Hover State of a Button - Wrong reference on challenge's introduction

### ISSUE THREAD

**Issue by nativedone** [freeCodeCamp/freeCodeCamp#13869]
Challenge [use-css-animation-to-change-the-hover-state-of-a-button](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-css-animation-to-change-the-hover-state-of-a-button) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi guys, the challenge's introduction says:

> Here's an example of changing the `height` of an image on hover:

```html

<style>
  img:hover {
    animation-name: width;
    animation-duration: 500ms;
  }
  @keyframes width {
    100% {
      width: 40px;
    }
  }
</style>
<img src="https://bit.ly/smallgooglelogo" alt="Google's Logo" />

```

But, I think it should refer to `width`, rather than height.

Let me know if is the case, and if I can submit a quick PR to fix it.

**Comment by cdrainxv** [comment]
Yes, good catch! I would also suggest these visual changes in addition to what you suggested above:

For the example:
```html
<style>
  img:hover {
    animation-name: width;
    animation-duration: 500ms;
  }
   
  @keyframes width {
    100% {
      width: 40px;
    }
  }
</style>
  
<img src="https://bit.ly/smallgooglelogo" alt="Google's Logo" />
```

For the challenge code:

```html
<style>
  button {
    border-radius: 5px;
    color: white;
    background-color: #0F5897;
    padding: 5px 10px 8px 10px;
  }

  button:hover {
    animation-name: background-color;
    animation-duration: 500ms;
  }
  

</style>

<button>Register</button>
```

And lastly:
```diff
- Note that ms stands for milliseconds, which are 1/1000 of a second.
+ Note that ms stands for milliseconds, where 1000ms is equal to 1s.
```
as comparison ratios are easier to visual than an outright fraction.

**Comment by HKuz** [comment]
@nativedone - thanks for pointing this out. Yes, that should say `width` in the text, instead of `height`. All good suggestions @cdrainxv - the extra spacing in the example and seed code will make them easier to read, and good point with the fraction vs. ratio in the text.

For anyone that wants to work on this, please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors). Thank you! 🌵 🌹 :shark:

**Comment by SebastianPetak** [comment]
I'll work on these changes.
