### ISSUE TITLE
Can't complete "Local Scope and Functions" 

### ISSUE THREAD

**Issue by dh4nR** [freeCodeCamp/freeCodeCamp#13863]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0A%0Afunction%20myLocalScope()%20%7B%0A%20%20myVar%20%3D%20%228%22%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0A%0AmyLocalScope()%3B%0A%0Avar%20myVar%20%3D%200%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.7 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


function myLocalScope() {
  myVar = 'use strict';
  
  
  console.log(myVar);
}

myLocalScope();

var myVar = 0;

// Run and check the console
// myVar is not defined outside of myLocalScope

// Now remove the console log line to pass the test


```

I am not sure what is going on here. I'm hoping this is not something I am doing wrong. 

Although I have created the global variable `var myVar = 0;` placed outside my function, the exercise won't allow me to move forward indicating that I haven't created a global variable called myVar.

**Comment by texas2010** [comment]
@dh4nR 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
