### ISSUE TITLE
??

### ISSUE THREAD

**Issue by dk0r0y333** [freeCodeCamp/freeCodeCamp#13867]
Challenge [Inherit Styles from the Body Element](https://www.freecodecamp.com/challenges/inherit-styles-from-the-body-element#?solution=%3Ch1%3E%20Hello%20World%20%3C%2Fh1%3E%0A%3Cstyle%3E%0A%20%20body%20%0A%20%20color%3A%20green%3B%0A%20%20font-family%3A%20Monospace%3B%0A%20%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1> Hello World </h1>
<style>
  body 
  color: green;
  font-family: Monospace;
  {
    background-color: black;
  }

</style>

```

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by dk0r0y333** [comment]
i found my own problem lol.. i didn't open them in the right place with these {
