### ISSUE TITLE
This Code Fills Out All the Requirements, but the Website Does Not Register Them as Correct 

### ISSUE THREAD

**Issue by iCodeCoolStuff** [freeCodeCamp/freeCodeCamp#13876]
![screenshot 19](https://cloud.githubusercontent.com/assets/25804565/23835123/203d4904-0738-11e7-9903-cfacd2cee758.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/25804565/23835124/22ce24b8-0738-11e7-96cc-bb503fc06ed2.png)

Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=%0Afunction%20mutation(arr)%20%7B%0A%20%20return%20arr%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Step 1: Copy the code from the box below.
Step 2: Go to freecodecamp.com and go to the "mutations" challenge
Step 3: Copy and paste the code from the box below into the code editor.
Step 4: Replace the method at the bottom of the editor with a few of the challenge requirements 

You should get the result I am getting in the screenshots above.

My code:
```javascript
var newArr = [];

function mutation(arr) {
  
  for (var i = 0; i < arr.length; i++) {
    
    newArr.push(arr[i].toLowerCase());
    
  }
  
  var letters = [];
  letters.push(newArr[1]);
  letters = letters.toString();
  letters = letters.split('');
  
  
  
  for (var j = 0; j < letters.length; j++) {
    
    if (newArr[0].indexOf(letters[j]) == -1) {
      
      return false;
      
    }
    
  }
  
  return true;
  
}

mutation(["hello", "hey"]);
```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. This is why you do not use global variables. If this program is ran multiple times it only calls out function called mutation. But this does not clean the newArr. So when running 2nd test, it is not [ ] but already has something inside of it

Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
