### ISSUE TITLE
Bug in conditional statement in for loop

### ISSUE THREAD

**Issue by engrfaisal90** [freeCodeCamp/freeCodeCamp#13898]
while giving condition in for loop, when someone gives space between "<" and  "=" it gives error.
 forexample if i write "< =" with space between them it gives error. ideally it should not give an error.  

#### Challenge Name

https://www.freecodecamp.com/challenges/iterate-odd-numbers-with-a-for-loop#

#### Issue Description

i wrote the statements like this
for (var i = 1; i < =9; i += 2) {
  ourArray.push(i);
}
space in the conditonal statement between < and = sign is clearly visible and it gives error. 

#### Browser Information

* Mozilla firefox 
* windows 10: 
* Desktop: 

#### Your Code

```



```
#### Screenshot
picture with error
![capture](https://cloud.githubusercontent.com/assets/22293348/23871458/4d3c5d4a-084c-11e7-9a1f-b85a58b9da69.JPG)
picture without error
![capture](https://cloud.githubusercontent.com/assets/22293348/23871489/75d093a2-084c-11e7-80bf-952eaba8e699.JPG)

**Comment by erictleung** [comment]
@engrfaisal90 thanks for the issue but this is expected behavior. The [operator `<=`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) is very specific and you can't separate it with a space. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by engrfaisal90** [comment]
Thank you for your response. As i haven't seen such kind of issue in other compilers that's why i raised this issue. In  most compilers white spaces doesn't matter. Thank you by the way.
