### ISSUE TITLE
Advertisement on Facebook page

### ISSUE THREAD

**Issue by imam** [freeCodeCamp/freeCodeCamp#13893]
![2017-03-13_202308](https://cloud.githubusercontent.com/assets/8213031/23856124/f38e8406-082a-11e7-81ee-05ab26c7afc4.png)

A startup in Indonesia uses Jakarta Free Code Camp fan page to advertise their business (Which is a commercial javascript Bootcamp). Is it legal to do so?

-- Sincerely, ads hater.

**Comment by erictleung** [comment]
@imam thanks for the issue. This has come up before and if I remember correctly, this is "acceptable" because each of the campsites is separate entities and can advertise, although inconvenient. I think all you can do is to ask politely that their ad is unwanted and if it continues, you can probably flag it as inappropriate. I'll tag Quincy and Justin on their input on the matter.

cc/ @QuincyLarson @hallaathrad

**Comment by imam** [comment]
@erictleung 

Thank you for the response.

I do not necessarily hate ads. I never use adblock because I want to support the content creator, either in youtube, google, anywhere else. But this case is different. The ad isn't supporting FCC.

They should at least have to ask for permission or more they should donate to FCC. Because it's a misuse of the platform and can make others businesses come to FCC just to advertise, not to learn, nor to support FCC. I hope there will be a strict rule about how to manage FCC community and the fan page. Because I'm not a newbie on web development, and I only come here because I love what you guys are doing, and I believe this issue should be addressed for the convenience of the students.

**Comment by raisedadead** [comment]
Hi @imam 

While we understand your frustration and appreciate your love for the community, the campsites are driven by complete autonomous authority of their own.

You should reach out to the admins of the page, for any complaints that should you have.

Unfortunately, we have to close this issue, because it's not related to the codebase, feel free to reach out to us over the support channels as listed on the https://freecodecamp.com/about for further assistance.

Thanks and happy coding!
