### ISSUE TITLE
Cannot pass this step:missing something here

### ISSUE THREAD

**Issue by emanusobga** [freeCodeCamp/freeCodeCamp#13918]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%3Ch2%20%7Bcolor%3A%20blue%3B%7D%3ECatPhotoApp%3C%2Fh2%3E%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  <h2 {color: blue;}>CatPhotoApp</h2>
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by jsw324** [comment]
Your code is incorrect.  Your supposed to be removing the style element from the h2 element and creating CSS in the style tags.  Try the below code:

`<style>
  h2 {color: blue;}
</style>

<h2>CatPhotoApp</h2>`

**Comment by emanusobga** [comment]
let me try that and see

**Comment by emanusobga** [comment]
@jsw324  it works and thank you so much

**Comment by emanusobga** [comment]
![image](https://cloud.githubusercontent.com/assets/26414315/23924567/2d6a467a-08d9-11e7-8ba0-1fbc7c8a650d.png)

it is not passing the test.

**Comment by emanusobga** [comment]
![image](https://cloud.githubusercontent.com/assets/26414315/23924652/78a7bf8c-08d9-11e7-8597-0706bd275de7.png)

changed in blue, still, nothing is happening

**Comment by emanusobga** [comment]
I was missing semicolon near "blue"

**Comment by jsw324** [comment]
You're missing the semicolon after the word 'blue'. Get that in there and you should be all set!


________________________________

**Comment by erictleung** [comment]
@emanusobga Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by CodeSpyce** [comment]
<style>
h2 {color:blue;}
</style>
CatPhotoApp </h2>

What is wrong with my code, I can't pass this stage yet
