### ISSUE TITLE
watijar66@gmail.com

### ISSUE THREAD

**Issue by JARWATI** [freeCodeCamp/freeCodeCamp#13916]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by JARWATI** [comment]
Yes code issue

**Comment by erictleung** [comment]
@JARWATI Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
