### ISSUE TITLE
"div elements has a closing tag" bug

### ISSUE THREAD

**Issue by KarimBenKarim** [freeCodeCamp/freeCodeCamp#13929]
Challenge [Line up Form Elements Responsively with Bootstrap](https://www.freecodecamp.com/challenges/line-up-form-elements-responsively-with-bootstrap) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.6.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
pls the output zone is showing me this error "div elements has a closing tag" but there's no div tag without a closing tag 

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
            <div class="row">
              <div class="col-xs-6">
                <label><input type="radio" name="indoor-outdoor"> Indoor</label>
              </div>
              <div class="col-xs-6">
                <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-4">
                <label><input type="checkbox" name="personality"> Loving</label>
              </div>
              <div class="col-xs-4">
                <label><input type="checkbox" name="personality"> Lazy</label>
              </div>
              <div class="col-xs-4">
                <label><input type="checkbox" name="personality"> Crazy</label>
              </div>
            </div>
            <div class="row">
                  <div class="col-xs-7">
                        <input type="text" class="form-control" placeholder="cat photo URL" required>
                  </div>
                   <div class="col-xs-5"> 
                      <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"> 
                       </i> Submit</button>   
                   </div>
            </div>
  
   </form>


```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. Simple CTRL+F shows that you have 18 `<div` and 17 of `</div

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.`

**Comment by PeteSEC** [comment]
Remove the <div class="container-fluid"> 
Remove it completely and should be fine. I think they forgot to use that line

**Comment by t4ddei** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
<div class="row">
  <div class="col-xs-6"><label><input type="radio" name="indoor-outdoor"> Indoor</label></div>
  <div class="col-xs-6"><label><input type="radio" name="indoor-outdoor"> Outdoor</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Loving</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Lazy</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Crazy</label></div>
</div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
what is the problem here?

**Comment by t4ddei** [comment]
`
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
<div class="row">
  <div class="col-xs-6"><label><input type="radio" name="indoor-outdoor"> Indoor</label></div>
  <div class="col-xs-6"><label><input type="radio" name="indoor-outdoor"> Outdoor</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Loving</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Lazy</label></div>
  <div class="col-xs-6"><label><input type="checkbox" name="personality"> Crazy</label></div>
</div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>`
