### ISSUE TITLE
setting the object property using dot notation to the variable did not yield a passing result...only using bracket notation did

### ISSUE THREAD

**Issue by elcat9091** [freeCodeCamp/freeCodeCamp#13923]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20alpha%3A%20%22Adams%22%2C%0A%20%20bravo%3A%20%22Boston%22%2C%0A%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20delta%3A%20%22Denver%22%2C%0A%20%20echo%3A%20%22Easy%22%2C%0A%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20result%20%3D%20lookup.val%3B%0A%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
  alpha: "Adams",
  bravo: "Boston",
  charlie: "Chicago",
  delta: "Denver",
  echo: "Easy",
  foxtrot: "Frank"
  };
  result = lookup.val;

  

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by erictleung** [comment]
@elcat9091 Thank you for reporting this issue. This is expected in this case. Please review dot notation vs bracket notation.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
