### ISSUE TITLE
Find the Longest Word in a String

### ISSUE THREAD

**Issue by bikkua** [freeCodeCamp/freeCodeCamp#13934]
https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=%0Afunction%20findLongestWord(str)%20%7B%0A%20%20%0A%20%20array%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20max%3D0%3B%0A%20%20%0A%20%20for(var%20i%3D0%3Bi%3Carray.length%3Bi%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if(array%5Bi%5D.length%3Emax)%0A%20%20%20%20%20%20%20%20max%3D%20array.length%3B%0A%20%20%20%20%7D%0A%20%20return%20max%3B%0A%20%20%0A%7D%0A%0AfindLongestWord(%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22)%3B%0A

function findLongestWord(str) {  
  array = str.split(" ");
  var max=0;
  
  for(var i=0;i<array.length;i++)
    {
      if(array[i].length>max)
        max= array.length;
    }
  return max;
  
}

findLongestWord("The quick brown fox jumped over the lazy dog");

Its failing for all the test cases. Anyone can tell me the problem?

![error](https://cloud.githubusercontent.com/assets/16547978/23951448/11d7a4c6-09b4-11e7-8e5a-d29dd0dbba63.png))

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by bikkua** [comment]
thanks..got it..typo error..will post in help chatroom next time

**Comment by hassangamal** [comment]
max=array[i].length;
