### ISSUE TITLE
Pig Latin Challenge (Issue with test case)

### ISSUE THREAD

**Issue by ssinghal1989** [freeCodeCamp/freeCodeCamp#13969]
Below is my Code 

function translatePigLatin(str) {
  str = str.toLowerCase();
  var isVowel = false;
  
  if(str[0] == 'a' || str[0] == 'e' || str[0] == 'i' || str[0] == 'o' || str[0] == 'u')    {
    isVowel = true;
  }
  
  if(isVowel){
    str = str + "way";
  }else{
    var str1 = str[0];
    var str2 = str.substring(1);
    str = str2 + str1 + "ay";
  }
  return str;
}

translatePigLatin("consonant");

Its working fine for all test. but having issue when passing "glove" as parameter. System expecting "oveglay". But according to the question it should be "lovegay".  

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by JoolsMcFly** [comment]
Quoting rules found on Wikipedia:

> For words that begin with consonant sounds, all letters before the initial vowel are placed at the end of the word sequence.

So in the case of *gl*ove you have to move both `g` and `l` after `ove` and then add `ay` which does give `oveglay`

If you try with `thrust` you should get `ustthray`

Have fun!

**Comment by JoolsMcFly** [comment]
And as a quick code review, you can simplify the first step like this:
```
  if(['a', 'e', 'i', 'o', 'u'].indexOf(str[0]) !== -1) {
    return str + 'way';
  }

  // rest of your code here, not need for else
```

**Comment by erictleung** [comment]
@ssinghal1989 thanks for the issue. The instructions do say 

> Pig Latin takes the first consonant **(or consonant cluster)** of an English word, moves it to the end of the word and suffixes an "ay".

which explains why the test behaves as it should. Please take a look at the Wikipedia link for more information or ask help in the chat rooms first.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
