### ISSUE TITLE
concatenating strings doesnot work

### ISSUE THREAD

**Issue by heenabegum167** [freeCodeCamp/freeCodeCamp#13961]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + "This is the end.";



```

**Comment by erictleung** [comment]
@heenabegum167 Thank you for reporting this issue. Take a look at the strings once more. You're almost there.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
