### ISSUE TITLE
Can't go past this stage

### ISSUE THREAD

**Issue by CodeSpyce** [freeCodeCamp/freeCodeCamp#13963]
Hey All,

I can't see what is wrong with my code
![image](https://cloud.githubusercontent.com/assets/26460128/24030180/6c8df6ca-0aec-11e7-9626-7cd74325e37d.png)

**Comment by erictleung** [comment]
@CodeSpyce Thank you for reporting this issue. You code is incorrect. Please use the Gitter chat rooms linked below for asking for help. GitHub issues are not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
