### ISSUE TITLE
Test Cases appears to be wrong. Because the number of arguments for the function keeps varying

### ISSUE THREAD

**Issue by arsubbu** [freeCodeCamp/freeCodeCamp#14009]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr%2C%20a%2C%20b)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20%0A%20%20return%20arr%5B3%5D%3B%0A%20%20%0A%20%20%0A%20%20%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr, a, b) {
  // Remove all the values
  
  return arr[3];
  
  
  
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

**Comment by erictleung** [comment]
@arsubbu Thank you for reporting this issue. The test cases are correct. Please take a look at the [objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) linked on the challenge description to learn how to deal with them.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
