### ISSUE TITLE
*SPOILERS* challenge finished but don't understand something 

### ISSUE THREAD

**Issue by juansalvatore** [freeCodeCamp/freeCodeCamp#14019]
#### Challenge Name: 

Caesaras Cipher

#### Issue Description:

I've finished this challenge, but I don't understand completely why the first for loop is ignoring the !?. and " ".  I know is ignoring it, because in the second loop the ascii number left for those characters is the original, it's not subtracting nor adding 13. 

#### Your Code

```js

function rot13(str) { // LBH QVQ VG!
  var arrayStr = [];
  
  for(var i = 0; i < str.length; i++) {
      if (str.charCodeAt(i) <= 77){
        arrayStr[i] = str.charCodeAt(i) + 13;
      }
      else {
        arrayStr[i] = str.charCodeAt(i) - 13;
      }           
  }
  
  for(var j = 0; j < arrayStr.length; j++) {
    if (str.charCodeAt(j) == 32) {
      arrayStr[j] = " ";
    }
    else if (str.charCodeAt(j) == 33){
      arrayStr[j] = "!";
    }
    else if (str.charCodeAt(j) == 63){
      arrayStr[j] = "?";
    }
    else if (str.charCodeAt(j) == 46){
      arrayStr[j] = ".";
    }
    else {
      arrayStr[j] = String.fromCharCode(arrayStr[j]);
    }
    
  }
  
  arrayStr = arrayStr.join('');
  
  return arrayStr;
}

// Change the inputs below to test
rot13("SERR CVMMN!");




```

**Comment by erictleung** [comment]
@juansalvatore Thank you for reporting this issue. Run through your second `for` loop closely and slowly to find your issue and actually understand what that `for` loop is doing. If you are still unable to find the answer, please ask your questions in the Gitter chat rooms linked below.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
