### ISSUE TITLE
colour

### ISSUE THREAD

**Issue by akira10** [freeCodeCamp/freeCodeCamp#14032]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%7Bcolor%3Ablue%7D%22%0A%3C%2Fstyle%3E%20%0A%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attact%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code doesnt display blue,only the color button turns green help/
My code:
```html
<style>
{color:blue}"
</style> 


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attact your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@akira10 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
