### ISSUE TITLE
Code doesn't work! Can you please help me? 

### ISSUE THREAD

**Issue by idilarg** [freeCodeCamp/freeCodeCamp#14030]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyStr%20%3D%20%22Hello%20World%22%3B%0A%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World";

myStr[0] = "H";



```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by happycraigles** [comment]
The problem with this is that the description is very misleading and unclear. By having the square brackets--without stating that they themselves should take any part--displayed, can be misconstrued to imply that something should occur with multiple lines.
It took me a while to get through this--and it was a waste of time--but I did it. Ignore the segment with the square brackets and just focus on the final little example and use that. 
(Not to be too rude, but maybe FCC should have a program evaluator do a qualitative--not quantitative--review of some of these. Many of the intentions are very unclear of the exercises. And make sure that the evaluator is objective in regards to coding-world.)
