### ISSUE TITLE
please help my challenge guys

### ISSUE THREAD

**Issue by romercoder** [freeCodeCamp/freeCodeCamp#14112]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/26372086/24340693/cba6065a-12e6-11e7-9192-fd50f747e87d.png)
![jerome](https://cloud.githubusercontent.com/assets/26372086/24340769/39b22e80-12e7-11e7-974c-e5c38462cea4.jpg)

**Comment by romercoder** [comment]
thank you!!!

**Comment by erictleung** [comment]
@romercoder Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
