### ISSUE TITLE
Basic CSS: Change the Color of Text - empty space issue

### ISSUE THREAD

**Issue by Dejay86** [freeCodeCamp/freeCodeCamp#14116]
#### Challenge Name
http://beta.freecodecamp.com/challenges/basic-css/change-the-color-of-text

#### Issue Description
Getting an error with the empty spaces between the equality sign and rest of a code. 

![image](https://cloud.githubusercontent.com/assets/25308074/24353954/60fcd2f2-12f0-11e7-8451-23262aad2197.png)
#### Browser Information

* Browser Name, Version: Google Chrome, Version 56.0.2924.87
* Operating System: Windows 10 Home Single Language 64-bit (10.0, Build 14393)
* Mobile, Desktop, or Tablet: Desktop

**Comment by no-stack-dub-sack** [comment]
@Dejay86 Well, while that's probably considered poor syntactic style, I agree that it should probably still pass the test, seeing as the `h2` still gets colored red. This is a regex issue with the way we are testing the code. 

This is the line of code in question:
```js
assert(code.match(/<h2\\s+style=\"color:\\s*rgb\\(255,\\s*0,\\s*0\\)\\;?\">\\s*CatPhotoApp\\s*<\\/h2>/) || code.match(/<h2\\s+style=\"color:\\s*red\\;?\">\\s*CatPhotoApp\\s*<\\/h2>/), 'message: Your <code>h2</code> element should be red.');
```
So, we are not allowing spaces after or before the assignment operator, and now that I look at it, I see another couple of issues as well. If someone used a hex value, the test would fail, even though the header would still be red. 

@freeCodeCamp/moderators any thoughts on this? Should we fix just the issue surrounding the `=` or should we also allow for hex values or should both be considered bikeshedding since this has not really come up until now? (unless it has)
