### ISSUE TITLE
hi guys help my issues

### ISSUE THREAD

**Issue by romercoder** [freeCodeCamp/freeCodeCamp#14125]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/26372086/24390303/a88b2aea-13ba-11e7-8ef1-9dda63a6a80a.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
