### ISSUE TITLE
Error while process words that are captalized but function is running fine !

### ISSUE THREAD

**Issue by vinodkumartheking** [freeCodeCamp/freeCodeCamp#14127]
Challenge [Search and Replace](https://www.freecodecamp.com/challenges/search-and-replace#?solution=%0Afunction%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20str%20%3D%20str.split('%20')%3B%0A%20%20str%5Bstr.indexOf(before)%5D%20%3D%20after%3B%0A%20%20return%20str.join('%20')%3B%0A%7D%0A%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myReplace(str, before, after) {
  str = str.split(' ');
  str[str.indexOf(before)] = after;
  return str.join(' ');
}


myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```

**Comment by JoolsMcFly** [comment]
Challenge has no issue, your code has one. :)

Hint:
> NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

As @JoolsMcFly mentioned.. your code is wrong
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
