### ISSUE TITLE
cannot get USING OBJECTS FOR LOOK UP (205) to pass

### ISSUE THREAD

**Issue by Deryckaus** [freeCodeCamp/freeCodeCamp#14130]
#### Challenge Name
Using Objects for Lookups 205

#### Issue Description
when i am writing the code , when i get to line 7  and 8 it gives an error:

i have tried to reload the page, cut and repaste the code etc

#### Browser Information

* Chrome: 
* win 10 
*laptop: 

#### Your Code

```js
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
  "alpha"   :  "adams"
  "bravo"   :  "Boston"
  "charlie" :  "Chicago"
  "delta"   :  "Denver"
  "echo"    :  "Easy"
  "foxtrot" :  "Frank"  
 
  };

  // Only change code above this line
  return Lookup[val];
}
return result;
// Change this value to test
phoneticLookup("charlie");




```
#### Screenshot
<!
![image](https://cloud.githubusercontent.com/assets/26110246/24415039/78bd1460-13e0-11e7-9cff-565620d986f3.png)

-- Add a screenshot of your issue -->

**Comment by isafrus5** [comment]
@Deryckaus You need to add commas between each _property_. Like this:

```sh
var lookup = {
  "alpha"   :  "adams",
  "bravo"   :  "Boston",
  "charlie" :  "Chicago",
  "delta"   :  "Denver",
  "echo"    :  "Easy",
  "foxtrot" :  "Frank" ,
 
  };

**Comment by erictleung** [comment]
@Deryckaus Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
