### ISSUE TITLE
First test failing, code returns correct solution... help or i quit coding and become and artist.. at least paint doesn't fight you when you try to use it.. 

### ISSUE THREAD

**Issue by AndrewScri** [freeCodeCamp/freeCodeCamp#14152]
Challenge [Accessing Nested Arrays](https://www.freecodecamp.com/challenges/accessing-nested-arrays#?solution=%0A%2F%2F%20Setup%0Avar%20myPlants%20%3D%20%5B%0A%20%20%7B%20%0A%20%20%20%20type%3A%20%22flowers%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22rose%22%2C%0A%20%20%20%20%20%20%22tulip%22%2C%0A%20%20%20%20%20%20%22dandelion%22%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20type%3A%20%22trees%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22fir%22%2C%0A%20%20%20%20%20%20%22pine%22%2C%0A%20%20%20%20%20%20%22birch%22%0A%20%20%20%20%5D%0A%20%20%7D%20%20%0A%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20secondTree%20%3D%20myPlants%5B1%5D.list%5B1%5D%20%2B%20%22%20%22%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants[1].list[1] + " "; // Change this line


```

**Comment by Marmiz** [comment]
@AndrewScri thanks for reporting this issue.

Unfortunately your code does not return the correct solution:
the test expect `pine` while your code returns `pine ` (notice the empty space?).

The reason is that in your code you are attaching an empty space yourself here.
```
+ " ";   // --> this means add a space after my string
```

Next time you're having difficulties with a challenge please consider asking for help in chat or on the official forum.
Good luck and happy coding 👍

**Comment by erictleung** [comment]
@AndrewScri Thank you for reporting this issue. You've added an extra space to the return statement as @Marmiz has pointed out. Please ask coding questions in Gitter chat rooms linked below. Hang in there, learning to program takes time and patience.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
