### ISSUE TITLE
not able to get green check when running correct code

### ISSUE THREAD

**Issue by CoderInTraining32** [freeCodeCamp/freeCodeCamp#14157]
Trying to code an ID Attribute to Style an Element: #cat-photo-form {
                                                                                       background-color: green;
                                                                                    }

This does not work at all. I've tried refreshing my browser and resetting the code

**Comment by erictleung** [comment]
@CoderInTraining32 Thank you for reporting this issue. Please ask coding questions first to the Gitter chat rooms before posting an issue here. Additionally, please fill out the issue template if you're creating an issue on GitHub. It helps us help you.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
