### ISSUE TITLE
Challenge gives an error even if correct parameters are passed for [golfScore(4, 7),golfScore(5, 9)]

### ISSUE THREAD

**Issue by ukirderohit** [freeCodeCamp/freeCodeCamp#14161]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20par-2)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par-1)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par%2B1)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par%2B2)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20par%2B3)%20%7B%0A%20%20%20%20return%20%22Go%20Home%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%209)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes === 1) {
    return "Hole-in-one!";
  } else if (strokes <= par-2) {
    return "Eagle";
  } else if (strokes == par-1) {
    return "Birdie";
  } else if (strokes == par) {
    return "Par";
  } else if (strokes == par+1) {
    return "Bogey";
  } else if (strokes == par+2) {
    return "Double Bogey";
  } else if (strokes >= par+3) {
    return "Go Home";
  } else {
  
  return "Change Me";}
  // Only change code above this line
}

// Change these values to test
golfScore(5, 9);
```

**Comment by ukirderohit** [comment]
Test Cases for golfScore(4, 7) and golfScore(5, 9) does not pass even if the console shows the correct output!!

**Comment by erictleung** [comment]
@ukirderohit Thank you for reporting this issue. Your code is almost there! Please take a look at the table one more time. There is nothing wrong with the tests.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by MattyHale** [comment]
Get rid of: 
else{
 return "Change Me";}

**but remember to keep the functions closing bracket

**Comment by gulpasa** [comment]
Instead of

else {
return "Go Home";
}

You should write

else {
return "Go Home!";
}

The "!" character causes the problem...
