### ISSUE TITLE
Steamroller issue.

### ISSUE THREAD

**Issue by Freelancer-98** [freeCodeCamp/freeCodeCamp#14167]
#### Challenge Name

[https://www.freecodecamp.com/challenges/steamroller](url)

#### Issue Description

The tab freezes and I can't even reset the code on opening the problem again, it seems there is auto-compilation or something going on. Even after waiting for 10 minutes, no response and I have to kill the page.
I somehow bypassed it, by logging in with Firefox and typing out a new code there, not that the earlier code wasn't there by default, and it was just a template when I logged in with Firefox, so there was no freeze.

#### Browser Information

Google Chrome Version 56.0.2924.87
Windows 7 Professional 64-bit
Desktop

#### Your Code

```js

> var final=[];
function steamrollArray(arr){
	for(i=0;i<arr.length;i++){
		if(Array.isArray(arr[i])){
			steamrollArray(arr[i]);
		}else{
			final.push(arr[i]);
		}
	}
	return final;
}

steamrollArray([1,[2],[3,[[4]]]]);
```
Note that, when I ran the sam above code on other online IDE it was smooth and gave an output-
[http://prntscr.com/eqn3x9](url)

#### Screenshot

[http://prntscr.com/eqn2fz](url)
This is my first post here, and I am just an amateur.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Firstly all your links are broken and do not work for me :/
But I can see from your code that you are using a global variable. Programs, that have multiple tests, cannot have global variables. Since the tests test only the function, not the whole code. The final variable won't be empty on the second test, it will have array of the first test inside of it.

So your code is wrong and try to redo it so you are using variable inside a function


Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
