### ISSUE TITLE
Submit button should only have the text "submit"

### ISSUE THREAD

**Issue by bdbradley** [freeCodeCamp/freeCodeCamp#14162]
Code challenge:
Add a submit button to your form

I have no idea what's wrong, it doesn't clear the "Submit button should only have the text "Submit" .

I've tried Submit, submit, "Submit", "Submit" . to no avail. I even looked at the code on the next exercise to make sure I wasn't missing anything.

**Comment by erictleung** [comment]
@bdbradley Thank you for reporting this issue. Please take coding questions first to the Gitter chat rooms linked below first before bringing up issues on GitHub. GitHub issues are only for bugs on the site.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by tcarroll34** [comment]
I'm having the same issue.

**Comment by texas2010** [comment]
@tcarroll34 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
