### ISSUE TITLE
<!--h1>Hello World</h1-->  <!--h2>CatPhotoApp</h2-->  <!--p>Hello Paragraph</p-->

### ISSUE THREAD

**Issue by chaitanyas8371** [freeCodeCamp/freeCodeCamp#14171]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%0A%3C!--h2%3ECatPhotoApp%3C%2Fh2--%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<!--h1>Hello World</h1-->

<!--h2>CatPhotoApp</h2-->

<!--p>Hello Paragraph</p-->


```

**Comment by Mrprofessor** [comment]
Save the screenshot somewhere then
```
[IMG](link)
```

**Comment by Mrprofessor** [comment]
And bdw what issue..??

**Comment by chaitanyas8371** [comment]
i solve it !thanks for u r reply

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
