### ISSUE TITLE
 function chainToSwitch(val) {   var answer = "";   // Only change code below this line    switch(val){      case "bob":       answer="Marley";       return;     case 42:       answer = "The Answer";       break;     case 1:        answer = "There is no #1";       break;     case 99:        answer = "Missed me by this much!";       break;     case 7:         answer = "Ate Nine";       break;      }   // Only change code above this line     return answer;   }  // Change this value to test chainToSwitch("7");

### ISSUE THREAD

**Issue by sohail333** [freeCodeCamp/freeCodeCamp#14178]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by erictleung** [comment]
@sohail333 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
