### ISSUE TITLE
Ninjas

### ISSUE THREAD

**Issue by barkinet** [freeCodeCamp/freeCodeCamp#14185]
![img_2283](https://cloud.githubusercontent.com/assets/2127162/24572059/855f99ba-166d-11e7-97e5-5484d747c019.PNG)
Challenge [improve-accessibility-of-audio-content-with-the-audio-element](http://beta.freecodecamp.com/en/challenges/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<body>
  <header>
    
    <h1>Real Coding Ninjas @barkinet</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    
    
    
  </main>
</body>


```

**Comment by erictleung** [comment]
@barkinet Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
