### ISSUE TITLE
Incorrect description for Challenge.

### ISSUE THREAD

**Issue by prateekgoel** [freeCodeCamp/freeCodeCamp#14207]
#### Challenge Name

https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery

#### Issue Description

In the challenge description, it says not to use single-quote selectors.

"single-quote selectors will not pass our tests."

But they pass the tests correctly.

So, either the tests should not pass or the description should be changed.

#### Browser Information

* Browser Name, Version: Google chrome Version 57.0.2987.133
* Operating System: Windows
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js


<script>
  $(document).ready(function() {
    $('button').addClass('animated bounce');
  });
</script>

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/8016566/24585572/ebecaf30-17ab-11e7-8a4a-a84703f22534.png)

**Comment by techstonia** [comment]
Solution with single quotes is also passing on my machine with Chrome/Firefox. But it might be that it's not passing on some machines so I think the solution is to just make the wording a bit "softer".

**Comment by erictleung** [comment]
@prateekgoel thanks for the issue and thanks @techstonia for writing up a PR to try and fix this. As I mentioned in the PR, this still doesn't change the test which requires no single quotes in your code.

This single quote requirement came from this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/9303, which essentially states that jQuery prefers double quotes. However, I'm not aware of any limitation in the challenge tests to detect single quotes. I think that requirement was just so that it is easier to detect a specific type of quote, rather than build in searching for both double and single quotes. Plus, I think stylistically, double quotes are preferred.

cc/ @freeCodeCamp/moderators I'm not sure if I'm missing anything, but I think both single and double quotes should be acceptable for this challenge? Correct me if I'm wrong. Otherwise, I vote for just modifying the tests and description to accept both single and double quotes.

**Comment by techstonia** [comment]
I think if we try to enforce style guides then it should be done for all the jQuery challenges. 

I thought that this double quote requirement came from some browser specific quirk and since I didn't find any evidence I just made the requirement a bit softer.

**Comment by Greenheart** [comment]
I agree, the description should be changed to remove the last paragraph. The tests works fine though :)

**Comment by shreyasminocha** [comment]
I am willing to take this up.

**Comment by dhcodes** [comment]
Thanks @Manish-Giri for the PR, but I've yet to find where jQuery suggests double-quotes vs. single and while it'd be more tedious, I think modifying all the tests to accept either (where necessary) may be a better route. cc @freeCodeCamp/moderators

**Comment by QuincyLarson** [comment]
@dhcodes if we're not going to enforce the use of double quotes, we should remove all mention of it from the challenge. Otherwise we're overloading campers with useless style opinions. They can choose whether to use single or double quotes for themselves, then when contributing to open source can use whatever that project's linting requires.

@Manish-Giri would you be interested in removing this line from the instructions and its corresponding test?

**Comment by Manish-Giri** [comment]
@QuincyLarson Yes, I'll do that.

**Comment by QuincyLarson** [comment]
@Manish-Giri Awesome - thanks for your help with this!
