### ISSUE TITLE
[Beta]Sorting Algorithms - test passes without using correct algorithms.

### ISSUE THREAD

**Issue by Marmiz** [freeCodeCamp/freeCodeCamp#14204]
Challenge [implement-bubble-sort](https://beta.freecodecamp.com/en/challenges/coding-interview-algorithm-questions/implement-bubble-sort) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

 ---
[EDIT] 
I Reported this originally for Bubble sort, but then went ahead and used the same function on all the sorting algorithms challenges and passed them all.

---

I was able to pass the challenge using [Array.sort()](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) method.

Since the result is a sorted array, the challenge is marked as completed.
However I don't believe this is a correct solution for the sorting algorithms.

Now I'm not a JS guru nor the highest expert in writing algorithms so I might be wrong, but I feel that the one I've implement is technically not a correct implementation of:

 - Bubble sort
 - Selection sort
 - Insertion
 - Quick sort
 - Merge sort

I was able to simply use this function to sort the array and pass all the above challenges.

Should the test cases made more specific?
```js

function sort(array) {
  array.sort(function(a, b){
    return a - b;
  });
  return array;
  
}

```

**Comment by hay-dee** [comment]
Using the Array.sort() method is indeed a loophole in the challenges, as the challenge tests only check the end result of our code. It might be a little crude, but it seems that checking for and preventing the use of the Array.sort() method might be the best way to deal with this.

**Comment by no-stack-dub-sack** [comment]
@Marmiz Thanks for pointing this out, I actually just noticed the same thing and came to open up an issue and saw that you already did! I've been chatting a bit with another member who wrote the challenge and we are going to make this fix with each of these challenges, plus a couple of other fixes that will make the section a bit stronger.

**Comment by Marmiz** [comment]
@no-stack-dub-sack Let me know If I can be of any help; I've wrote my fare share of sorting algorithms in C back in the day 😄 

Thanks for your effort in solving this!

**Comment by bonham000** [comment]
@no-stack-dub-sack and @Marmiz this issue was just closed when I merged the PR. However, it's worth mentioning that the current tests do not verify that any of the solutions actually use the correct sorting method. They just check to see that the function sorts an array properly. It's easy to prevent against using a built-in method like `.sort` but it's harder to verify that the user implements the correct sorting method (e.g. bubble vs. selection vs. merge etc).

Tests with more specificity would be possible, however. Some of the methods are 'in-place' whereas others are not and I've seen the more efficient sorting methods (merge, quick-sort) tested with larger inputs that the ordinary inefficient methods will be too slow for. So the tests could be improved and we could potentially reopen this if it's worth it to keep tracking for anyone else who wants to work on it.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Yeah, I agree that this sounds like a serious undertaking. The issue is technically separate, so I would say a second issue which references this one would be appropriate. We could just leave it open for when this issue inevitably comes up in the future, but at least they are a bit more strict now than they were.
