### ISSUE TITLE
how to do h2 element<style>  h2{color:red;} </style> <h2 "red-text">CatPhotoApp</h2>

### ISSUE THREAD

**Issue by chaitanyas8371** [freeCodeCamp/freeCodeCamp#14209]
[Challenge]([url](url)) [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20h2%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if 
Your h2 element should be blue.
<style>
 h2{color:red;}
</style>
<h2 "red-text">CatPhotoApp</h2>

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
