### ISSUE TITLE
Can't move to the next stage even after writing correct code

### ISSUE THREAD

**Issue by Adeyeha** [freeCodeCamp/freeCodeCamp#14225]
Hello, 
I use this code, but h2 element won't change to red. Hence I can't move to next stage. 

<style>
 .red-text {
    color: blue;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

**Comment by Dayo0077** [comment]
![code](https://cloud.githubusercontent.com/assets/25178706/24601598/65dde91c-1851-11e7-82be-7e4dfba36264.PNG)
 
Please i need help on this code

**Comment by Marmiz** [comment]
@Adeyeha 
>I use this code, but h2 element won't change to red. Hence I can't move to next stage.

```
 .red-text {   color: blue; }
```

It's hard that an element becomes red when you're explicitly declaring it to be blue. 😄 

-----

Also please @Adeyeha  and @Dayo0077 consider that github is a place for reporting issues, for asking and receiving help we have a list of [official chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
In alternative you can always look in the [forum](https://forum.freecodecamp.com/) for a specific challenge.

Happy coding 👍

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
