### ISSUE TITLE
RGB Challange not working

### ISSUE THREAD

**Issue by ATJohnson83** [freeCodeCamp/freeCodeCamp#14221]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(225%2C0%2C0)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C0%2C225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(225,0,0);
  }
  .orchid-text {
    color: rgb(218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
    color: rgb(0,0,225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by ATJohnson83** [comment]
Hi, I am getting the correct out put, but is it showing my values for Red and Blue text to be wrong, even they are colored using the correct corresponding rgb values.

**Comment by ATJohnson83** [comment]
![screencapture-freecodecamp-challenges-use-rgb-to-mix-colors-1491186782906](https://cloud.githubusercontent.com/assets/24866008/24593760/6f0995b6-17f4-11e7-83e3-eab47e00be9a.png)

**Comment by erictleung** [comment]
@ATJohnson83 Thank you for reporting this issue. Your RGB is not correct. Although it looks "red", it isn't full on "red" as required. Take a look at the RGB code again. Next time, please ask questions to the Gitter chat rooms first.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by ATJohnson83** [comment]
Got it, sorry about that, thanks!

**Comment by esd15** [comment]
wait but the instructions say that red is (255, 0 , 0)
