### ISSUE TITLE
why is NaN==NaN;///false

### ISSUE THREAD

**Issue by Suyash2724** [freeCodeCamp/freeCodeCamp#14227]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by erictleung** [comment]
@Suyash2724 Thank you for reporting this issue but GitHub issues are for bugs on the site, not coding help. Please use search around elsewhere for an answer to your question. A place to start might be http://stackoverflow.com/questions/19955898/why-is-nan-nan-false. Please chat in one of the chat rooms linked below if you have more questions.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
