### ISSUE TITLE
Add Elements within your Bootstrap Wells

### ISSUE THREAD

**Issue by architwrox** [freeCodeCamp/freeCodeCamp#14228]
Challenge [Add Elements within your Bootstrap Wells]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well" button button button>

      </div>
    </div>
    <div class="col-xs-6">
      <div class="well" button button button>

      </div>
    </div>
  </div>
</div>

```

**Comment by ThoresenPride** [comment]
You can obviously not add button like this ? what is your intention,  WHy have you startet vis 2 closin gidvs ? and then 2 opened one? this is so unlogic, what are you trying to do ?

**Comment by ThoresenPride** [comment]
if you want to add the class btn from jquery to all your button elements within a div, your would do something like this. ( btn-primary is just another class from jquery wich i assume your going to use in this challene) 
<div class="well btn btn-primary">
->Put your buttons here<-
</div>

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
