### ISSUE TITLE
My progress is not saved between two computers

### ISSUE THREAD

**Issue by pierresisson** [freeCodeCamp/freeCodeCamp#14232]
Hey,

I have two computers : 
-> 1 macbook pro on Sierra
-> 1 on windows 10

When i work on my macbook, my progress are saved on this computers mais when i open freecodechamp on my windows, it does not appears.  And the opposite is the same, when i'm on my windows, the work i did on it does not appears on my macbook. (i use Google Chrome on both computers)

What can I do ?

I did the javascript basic 2 times, same for the html lessons. So if u guys does not find something to help me, i guess i will stop the adventure here :(

Thank you !
(and sorry for my english!)

Pierre

**Comment by pierresisson** [comment]
Anybody can help me ? :(

**Comment by PetervBijsterveldt** [comment]
Sign in so you can save your progress.

**Comment by pierresisson** [comment]
Hello,

i already sign with my 2 computers with github (same account)
I still lost my works :(

**Comment by erictleung** [comment]
@pierresisson hi there. You can find your solutions on your freeCodeCamp page if you append your username to the end of the site. Something like `freecodecamp.com/usernamehere`, where `usernamehere` is where you'd replace your username. For example, my page is `https://www.freecodecamp.com/erictleung`. The solutions to be readily retrieved are stored in cache I believe so that is why it seems like your progress isn't saved. Let us know if that clears any confusion.

**Comment by pierresisson** [comment]
hi @erictleung !
thanks for your answer,i did what you said and it's actually working. I still dont understand why it didnt work, i did 2 times the job but it is ok now !!
Thank you very much :) (sorry for my english ;))

**Comment by erictleung** [comment]
@pierresisson no problem. It can be odd, but your work is saved somewhere! Glad this clears up some confusion. I'll be closing this issue as it appears resolved. In the future, if you get stuck or have questions with a challenge, ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
