### ISSUE TITLE
alqass

### ISSUE THREAD

**Issue by Mohammedabuqass** [freeCodeCamp/freeCodeCamp#14242]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by Mohammedabuqass** [comment]
aaa

**Comment by texas2010** [comment]
@Mohammedabuqass 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
