### ISSUE TITLE
Go home! not tested correctly.

### ISSUE THREAD

**Issue by richymel** [freeCodeCamp/freeCodeCamp#14244]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(strokes%20%3C%3D%200)%20%7B%0A%20%20%20%20return%20%22Come%20on!%20play%20something.%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(par%20%3E%207%20%7C%7C%20par%20%3C%3D%200)%20%7B%0A%20%20%20%20return%20%22Do%20you%20play%20golf%20in%20Mars%3F%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%20if%20(strokes%20%3D%3D%201)%20%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20(par%20%2B%203))%20%7B%0A%20%20%20%20return%20%22Go%20home!%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20(par%20%2B%202))%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20(par%20%2B%201))%20%7B%20%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(%20strokes%20%3C%3D%20(par-2))%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20(par%20-1))%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%20%20%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%209)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  
  if (strokes <= 0) {
    return "Come on! play something.";
  }
  
  if (par > 7 || par <= 0) {
    return "Do you play golf in Mars?";
  }
  
   if (strokes == 1) {
    return "Hole-in-one!";
  } else if (strokes >= (par + 3)) {
    return "Go home!";
  } else if (strokes >= (par + 2)) {
    return "Double Bogey";
  } else if (strokes >= (par + 1)) { 
    return "Bogey";
  } else if ( strokes <= (par-2)) {
    return "Eagle";
  } else if (strokes <= (par -1)) {
    return "Birdie";    
  } else {
    return "Par";
  }
  
  // Only change code above this line
}

// Change these values to test
golfScore(5, 9);

```

**Comment by erictleung** [comment]
@richymel Thank you for reporting this issue. Your code is almost there. Please look at the failing test once more and try to see why your code is slightly wrong given what is asked. The challenge test is working perfectly fine. If you're still stuck, please check out the Gitter chat rooms linked below.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
