### ISSUE TITLE
Incorrect Code Passes Challenge

### ISSUE THREAD

**Issue by Margaret2** [freeCodeCamp/freeCodeCamp#14288]
Challenge [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target1%22).prop(%22disabled%22%2C%20true)%3B%0A%20%20%20%20%24(%22%23target4%22).remove()%3B%0A%20%20%20%20%24(%22%23target2%22).appendTo(%22%23right-well%22)%3B%0A%20%20%20%20%24(%22%23target5%22).clone().appendTo(%22%23left-well%22)%3B%0A%20%20%20%20%24(%22%23target1%22).parent().css(%22background-color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23right-well%22).children().css(%22color%22%2C%20%22orange%22)%3B%0A%20%20%20%20%24(%22.well%3Anth-child(2)%22).children().addClass(%22animated%20bounce%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.138 Safari/537.36 Vivaldi/1.8.770.54</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $(".well:nth-child(2)").children().addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

Hi, was in the Help Room and someone pointed out that this code will pass the tests: 
`$(".well:nth-child(2)").children().addClass("animated bounce");`

What this does is make all the `.target` elements bounce, rather than only 2 specific ones... Which kind of defeats the purpose of the lesson (Target a *Specific* Child).

**Comment by Dayfiri** [comment]
@Margaret2 
I was just checking what is going on and why your code is not like it should be.
The reason for that is not understanding what exactly the code you're writing does.
The assignment asked you to:
1. `Make the second child in each of your well elements bounce. You must target the children of element with the target class.`
If you google about the `jquery` and `:nth-child()` function, you can see that it works like:
*Quote from webpage about it*
**Select each <p> element that is the third child of its parent**
The code to do that -> `$("p:nth-child(3)")`

As the assignment said and seen from the example above, you need to use `.target` class that is included with every child of `#well-right` and `#well-left` parent Id's.

I would usually give you a link and tell you to check FCC Help room but because you were already there I'm gonna show you here the solution.

`$(".target:nth-child(2)").addClass("animated bounce");`

This code makes every 3. element in a `div` bounce ( it is 3. because elements are numbered from 0, so `:nth-child(2)` is applying class to 3. element in a `div`. 

Screenshot that assignment works.
![screenshot from 2017-04-07 19-02-13](https://cloud.githubusercontent.com/assets/16082563/24811066/e61cfcbe-1bc4-11e7-86aa-bf1a31b914b8.png)

**Comment by Margaret2** [comment]
Lol @Dayfiri I already earned the Front End cert, I know how to solve this challenge and how `nth-child` works. My issue is that this line of code: 

`$(".well:nth-child(2)").children().addClass("animated bounce");`

is not the intended solution, and does not do what the challenge asks you to do, but it passes all the tests. I am suggesting that it be fixed.

**Comment by Dayfiri** [comment]
@Margaret2 
Ha ha, yeah I totally missed what your main point was. When I read that you were in a help room + when I saw the example code I immediately concluded you need some help with finishing the assignment.

My bad about that answer but I'm with you about the bug. Both `div` elements + 2. element in each div are bouncing for me and the code is passing.
So the code is passing but the code did all it was asked to do.

 `The second element in your target elements should bounce.` - 2. element in each div is bouncing
`You should use the :nth-child() function to modify these elements.` - this function is used
`Only use jQuery to add these classes to the element. ` - jQuery is used too

So by this 3 things that need to be done, they are all succeed by the code.

Extras:
1. .children() function is additionally added
2. `#left-well` and `#right-well` are bouncing too

So maybe the code is passing because after it checked for 3. assignments and they are all in use, it lets you pass and doesn't mind any additions.
