### ISSUE TITLE
code passes but people said it shouldnt in chat help

### ISSUE THREAD

**Issue by disc233** [freeCodeCamp/freeCodeCamp#14290]
#### Challenge Name

Accessing Objects Properties with Variables

#### Issue Description

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%2F%2F%20Change%20this%20Line%0AtestObj%5BplayerNumber%5D%0Avar%20player%20%3D%20%22Montana%22%3B%20%20%20%2F%2F%20Change%20this%20Line%0A

#### Browser Information

* Browser Name, Version: latest firefox browswer
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;// Change this Line
testObj[playerNumber]
var player = "Montana";   // Change this Line



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/25807078/24818654/0148d33c-1ba7-11e7-9066-9fe22d63a19c.png)

**Comment by Manish-Giri** [comment]
It's passing because you're assigning the value `"Montana"` to the variable `player` directly, which ultimately has the same result as using bracket notation to assign the value. The [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/533e496f9b7bea21bbb3f77acba5923743ded280/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L4327) checks the conditions that the variable has the right value and that `[ ]` notation was used, both of which are satisfied in your code.

Needs stricter tests, imo.

**Comment by erictleung** [comment]
@Manish-Giri agreed. We should make some stricter tests. Maybe like, "Don't assign player 'Montata' directly" or something.

**Comment by Manish-Giri** [comment]
@erictleung I'll take a crack at this 👍
