### ISSUE TITLE
Title Case Sentence >> Puzzled As to Why It Fails

### ISSUE THREAD

**Issue by seobrat** [freeCodeCamp/freeCodeCamp#14308]
This is the code that was written. I am unclear as to why it is failing. The output looks the same to me:

#### Challenge Name

Title Case A Sentence

https://www.freecodecamp.com/challenges/title-case-a-sentence
#### Browser Information

* Browser Name, Chrome: 
* Operating System: Yosemite
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```

function titleCase(str) {
  str = str.toLowerCase();
  str= str.split(" ");
  
  
  var holder = " ";
  var rest = "'";
  var newString = " ";
 // str = str.split(" ");
  for(var i = 0; i < str.length; i++){
    holder = str[i];
     holder = holder.toString();
    rest = holder.substring(1, holder.length);
    holder = holder.charAt(0).toUpperCase();
    holder = holder + rest + " ";
   
     newString+=holder;
    
  } 
  var string = newString.trim( );
   return string +".";
}
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");



```

**Comment by erictleung** [comment]
@seobrat Thank you for reporting this issue. You're almost there. Your code doesn't complete the challenge _precisely_, but it is close. Please take a look at the challenge closely and what the tests require. Good luck. And please ask coding help in the Gitter rooms linked below first. GitHub is not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by seobrat** [comment]
Thank you for your kind assistance and the notification of the rules.
