### ISSUE TITLE
Use RGB values to Color Elements

### ISSUE THREAD

**Issue by mrshabi** [freeCodeCamp/freeCodeCamp#14305]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by JoolsMcFly** [comment]
Could you provide less information please? :)

**Comment by erictleung** [comment]
@mrshabi Thank you for reporting this issue. You've provided no information so far. I'll be closing this as there's no information but if you can reply back with more information about your issue, we'll open this back up.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
