### ISSUE TITLE
Unable to submit and complete challenege 

### ISSUE THREAD

**Issue by ikellog** [freeCodeCamp/freeCodeCamp#14315]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/22954156/24834643/cc213820-1ca0-11e7-8856-9a6cce614da1.png)

**Comment by erictleung** [comment]
@ikellog thanks for the issue. It is difficult to debug your issue without more information. Can you fill out the issue template above to help us understand your issue? These kind of issues are something because of certain browser plugins interfering with the site. You can try turning some of them off to see if they help. But without more information, we can't really help you. Please comment back with more information.

**Comment by ikellog** [comment]
It's okay. Did a refresh and it's good now

**Comment by amandeepmittal** [comment]
@ikellog if your issue has resolved, can you please consider closing this issue?

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
