### ISSUE TITLE
Google Chrome freezes when open Challenge

### ISSUE THREAD

**Issue by Sebastian627** [freeCodeCamp/freeCodeCamp#14311]
When i open the Challenge Slasher Flick, not only the tab, but complete google chrome needs has problems and i need to close it with the task manager.
Ich coded something, that cant be right, but i pressed enter, just to see what the outcome would be, and since than, i cant work on this challenge anymore

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Blauelf** [comment]
I would not consider this to be a bug in the site, so better use the "Help" button rather than the "Bug" button. Also, by using the search button, you could have found that there have been many reports of that "bug".

Your solution, which probably contains an infinite loop, is saved in `localStorage`, and will be loaded and run on opening the challenge.

As this happens to other people, too, there is a wiki entry on that:
[Disable Code Auto Run on Free Code Camp](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Disable-Code-Autorun)
or on forum:
[Disable Code Auto Run on Free Code Camp](https://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511)

Alternatively, you can clear your local storage, deleting solutions stored in your browser. This will not affect already submitted solutions, which you can still load from your profile.
