### ISSUE TITLE
Issue in Comment out HTML

### ISSUE THREAD

**Issue by rdcrj** [freeCodeCamp/freeCodeCamp#14312]
If I follow the instruction to comment all <h1> and <p> content, then the last check "do not change order of h1 h2 p will be flag as an error".
And if I keep h1 h2 and p without comment, the last check will be fine. 

#### Challenge Name

https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!----%3E%0A%3C!--h1%3E%3CHello%20World%3E%3C%2Fh1--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A%3C!----%3E%0A

#### Issue Description

Case 1: comment h1 and p as instruction but last check is flagged (do not change order of h1 h2 and p)

<h2>CatPhotoApp</h2>

Case 2:  last check is fine, but didn't comment h1 and p as instruction

<h1><Hello World></h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/11785894/24834293/e894630c-1cae-11e7-8827-c5ccdee2a3dd.png)

**Comment by Manish-Giri** [comment]
@rdcrj Thank you for reporting this issue. Your code is incorrect. Please use the Gitter chat rooms linked below for asking for help. GitHub issues are not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
