### ISSUE TITLE
Run tests 

### ISSUE THREAD

**Issue by blentz8012** [freeCodeCamp/freeCodeCamp#14327]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch1%3ECatPhotoApp%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>
<h1>CatPhotoApp</h1>
```

**Comment by blentz8012** [comment]
i am not able to run test on cat app. Please help.

**Comment by erictleung** [comment]
@blentz8012 Thank you for reporting this issue. Please read the instructions again to see why your code isn't running.

> Add an h2 tag that says "CatPhotoApp" to create a second HTML element below your "Hello World" h1 element.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
