### ISSUE TITLE
Using a css style on html element

### ISSUE THREAD

**Issue by eirholvhan428** [freeCodeCamp/freeCodeCamp#14330]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element

#### Browser Information

* Browser Name, Version: chrome 53.0.2785.124
* Operating System: android 5.0
* Mobile, Desktop, or Tablet: mobile

#### Your Code

```js



```

**Comment by heyDante** [comment]
Visit [help](https://gitter.im/FreeCodeCamp/Help) section first before creating a new issue.

**Comment by neerajpal16** [comment]
ITS PRETTY SIMPLE !!
<style>
  .red-text {
    color: red;
  }
  </style>

<h2 class="red-text" >CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by texas2010** [comment]
@eirholvhan428 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
