### ISSUE TITLE
Bug here.

### ISSUE THREAD

**Issue by AndresAL86** [freeCodeCamp/freeCodeCamp#14373]
Challenge [Passing Values to Functions with Arguments](https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunctionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunctionWithArgs(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20functionWithArgs(b%2Cc)%20%7B%0A%20%20%20%20console.log(b%20%2B%20c)%3B%0A%7D%0A%0AourFunctionWithArgs(18%2C%205)%3B%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(b,c) {
    console.log(b + c);
}

ourFunctionWithArgs(18, 5); 


```

**Comment by Manish-Giri** [comment]
@AndresAL86 There's no bug. You're calling the sample function `ourFunctionWithArgs(18, 5);` instead of calling the one you're meant to - `functionWithArgs`.

For future issues, instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

**Comment by erictleung** [comment]
@AndresAL86 as @Manish-Giri has pointed out, you haven't completed the challenge yet. Please reread the instructions once more or take a look at the Gitter chat rooms for help. Happy coding!
