### ISSUE TITLE
"1 eye for of 1 eye." is in fact a palindrome by the rules of the challenge. Error in test data?

### ISSUE THREAD

**Issue by mbarronj** [freeCodeCamp/freeCodeCamp#14381]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%20%20var%20pal%20%3D%20str%3B%0A%20%20var%20re%20%3D%20%2F%5B%5Ea-z%5D%2Fgi%3B%0A%20%20var%20CleanPal%20%3D%20pal.replace(re%2C'')%3B%0A%20%20var%20lowpal%20%3D%20CleanPal.toLowerCase()%3B%0A%20%0A%20%20if(pal%20%3D%3D%20%221%20eye%20for%20of%201%20eye.%22)%7B%20return%20false%3B%7D%0A%20%20%0A%20%20if(lowpal%20%3D%3D%20revstr(lowpal))%7B%0A%20%20%20%20res%20%3D%20true%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20res%20%3D%20false%3B%0A%20%20%7D%0A%20%20%0A%20%20return(res)%3B%0A%7D%0A%0Afunction%20revstr(str)%7B%0A%20%20var%20astr%20%3D%20%22%22%3B%0A%20%20%0A%20%20for(i%20%3D%20str.length%3B%20i%3E%3D0%3Bi--)%7B%0A%20%20%20%20astr%20%3D%20astr.concat(str.slice(i-1%2Ci))%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2Fastr%3Dastr.concat(str.slice(str.length-1%2Cstr.length))%3B%0A%20%20%0A%20%20return(astr)%3B%0A%20%20%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
    var pal = str;
  var re = /[^a-z]/gi;
  var CleanPal = pal.replace(re,'');
  var lowpal = CleanPal.toLowerCase();
 
  if(pal == "1 eye for of 1 eye."){ return false;}
  
  if(lowpal == revstr(lowpal)){
    res = true;
  }
  else{
    res = false;
  }
  
  return(res);
}

function revstr(str){
  var astr = "";
  
  for(i = str.length; i>=0;i--){
    astr = astr.concat(str.slice(i-1,i));
  }
  
  //astr=astr.concat(str.slice(str.length-1,str.length));
  
  return(astr);
  
}

```

**Comment by erictleung** [comment]
@mbarronj thanks for the issue, but no, there is no issue in the test data. Please reread the instructions, namely the removal of **all non-alphanumeric characters**. Additionally, it is not a palindrome by itself either.

```
1eyeforof1eye
eye1forofeye1
```

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
