### ISSUE TITLE
style class should declare a red-text? and have its class set to red?

### ISSUE THREAD

**Issue by Tudie-Tudie** [freeCodeCamp/freeCodeCamp#14388]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/27300219/25014880/6ce3159a-202e-11e7-8562-8922adc9d8c5.png)

**Comment by texas2010** [comment]
@Tudie-Tudie 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
