### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cshubhamrao** [freeCodeCamp/freeCodeCamp#14396]
Challenge [Constructing Strings with Variables](https://www.freecodecamp.com/challenges/constructing-strings-with-variables#?solution=%0A%2F%2F%20Example%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20ourStr%20%3D%20%22Hello%2C%20our%20name%20is%20%22%20%2B%20ourName%20%2B%20%22%2C%20how%20are%20you%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myName%20%3D%20%22Shubham%20Rao%22%3B%0Avar%20myStr%20%3D%20%22My%20name%20is%20%22%20%2B%20myName%20%2B%20%22%20and%20I%20am%20well!%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.6 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName = "Shubham Rao";
var myStr = "My name is " + myName + " and I am well!";



```
It should be "well"in the problem statement, right?!

**Comment by epfuhl** [comment]
While "well" is the grammatically correct form as opposed to the word "good" when asked "how are you?", "swell" means you are doing well as well and is a less formal and sometimes for cheery response. Grammatically, either works. For the challenge, I imagine "swell" is what the course is asking for.

**Comment by erictleung** [comment]
@cshubhamrao thanks for the issue. As @epfuhl has pointed out, ["swell"](https://www.merriam-webster.com/dictionary/swell) (see the third definition) is a word similar to "well". Due to the international audience of freeCodeCamp, this change makes sense. Luckily, this has [already been changed in the development branch](https://github.com/freeCodeCamp/freeCodeCamp/blob/533e496f9b7bea21bbb3f77acba5923743ded280/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L1270) of freeCodeCamp. I'll be closing this issue as resolved. Happy coding!

**Comment by cshubhamrao** [comment]
@epfuhl TIL, new meaning to a word. Thanks!
