### ISSUE TITLE
my code is giving correct result but it is not passing the test. Why??

### ISSUE THREAD

**Issue by gitbhupesh** [freeCodeCamp/freeCodeCamp#14392]
Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%0Afunction%20sumPrimes(num)%20%7B%0A%20%20var%20sumPrime%20%3D%200%3B%0A%20%20var%20n%20%3D%202%3B%0A%20%20while(n%20%3C%3D%20num)%7B%0A%20%20%20%20if%20(isPrime(n))%7B%0A%20%20%20%20%20%20sumPrime%20%2B%3D%20n%3B%0A%20%20%20%20%7D%0A%20%20%20%20n%20%2B%3D1%3B%0A%20%20%7D%0A%0A%20%20return%20sumPrime%3B%0A%7D%0A%0Avar%20primeNumbers%20%3D%20%5B2%5D%3B%0A%0Afunction%20isPrime(n)%7B%0A%20%20if%20(n%20%3D%3D%202)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7Delse%20%7B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20primeNumbers.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20if%20(n%25primeNumbers%5Bi%5D%20%3D%3D%3D%200)%7B%0A%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20primeNumbers.push(n)%3B%0A%20%20return%20true%3B%0A%20%20%7D%0A%7D%0AsumPrimes(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sumPrimes(num) {
  var sumPrime = 0;
  var n = 2;
  while(n <= num){
    if (isPrime(n)){
      sumPrime += n;
    }
    n +=1;
  }

  return sumPrime;
}

var primeNumbers = [2];

function isPrime(n){
  if (n == 2){
    return true;
  }else {
    for (var i = 0; i < primeNumbers.length; i++){
      if (n%primeNumbers[i] === 0){
        return false;
      }
    }
  primeNumbers.push(n);
  return true;
  }
}
sumPrimes(10);

```

**Comment by Manish-Giri** [comment]
@gitbhupesh Try not to have any global variables in your code.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
