### ISSUE TITLE
facebook log on

### ISSUE THREAD

**Issue by rstreeter76** [freeCodeCamp/freeCodeCamp#14391]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range#?solution=%0Afunction%20sumAll(arr)%20%7B%0A%20%20return%201%3B%0A%7D%0A%0AsumAll(%5B1%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/57.0.2987.137 Mobile/14E304 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sumAll(arr) {
  return 1;
}

sumAll([1, 4]);

```

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
