### ISSUE TITLE
Fill in the blank with placeholder test

### ISSUE THREAD

**Issue by pallujain** [freeCodeCamp/freeCodeCamp#14393]
Challenge [Fill in the Blank with Placeholder Text](https://www.freecodecamp.com/challenges/fill-in-the-blank-with-placeholder-text#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ispum%20dolor%20sit%20amet%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Kitty ispum dolor sit amet</p>

```

**Comment by texas2010** [comment]
@pallujain 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
