### ISSUE TITLE
  Specify How Fonts Should Degrade

### ISSUE THREAD

**Issue by 100katl** [freeCodeCamp/freeCodeCamp#14408]
I'm going through the Specify How Fonts Should Degrade Challenge and having lots of trouble passing with correct code, I've commented the Google font code correctly a few times I'm sure but it want let on the next section, and its flopping from wrong to right! I may need some help.

Specify How Fonts Should Degrade

* Browser Name, Version: Chrome
* Operating System: iOS
* Mobile, Desktop, or Tablet: Desktop

  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<img width="1184" alt="screen shot 2017-04-14 at 8 01 42 pm" src="https://cloud.githubusercontent.com/assets/24835904/25058961/64cee3b4-214d-11e7-81ec-682cd040469e.png">

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. You also commented out your style tag
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
