### ISSUE TITLE
Codepen.io or Notepad++

### ISSUE THREAD

**Issue by Dwwop** [freeCodeCamp/freeCodeCamp#14414]
#### Issue Decription
I've been programming with Notepad++. Then I started learning Web Development via FreeCodeCamp and it advises me to use Codepen. Now I want to ask if it is a neccesary to write code via Codepen.io. Does it have any key features, which I can't find in Notepad++?

**Comment by OFFLlNE** [comment]
Hi @Dwwop 

Github is for reporting issues only. You can view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390). Feel free to ask advice and help there.

But it is not necessary to write in codePen, feel free to use notepad++.
Codepen is comfortable so you can see the changes fast and all the code is right there for you easily accessible.

Instead of Norepad++ I would suggest using sublime text editor.

Good luck and happy coding
