### ISSUE TITLE
Task 56: Both blue-text and pink-text should belong to the same h1 element.

### ISSUE THREAD

**Issue by tashdaddy** [freeCodeCamp/freeCodeCamp#14417]
Your h1 element should have the class pink-text.
Both blue-text and pink-text should belong to the same h1 element.

<img width="945" alt="screenshot 1946" src="https://cloud.githubusercontent.com/assets/19886188/25063300/9a12df2e-21ae-11e7-8909-27f41b694e50.png">
 
I don't know what I'm doing wrong - or haven't done....

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by BHSfifas15** [comment]
You committed a syntax error here is your code: <h1 class="blue-text" "pink-text">Hello World</h1>
try this remove the double quotes of pink-text class and include it inside the blue-text class :
<h1 class="blue-text pink-text ">Hello World</h1>

**Comment by BHSfifas15** [comment]
<h1 class="blue-text pink-text">
