### ISSUE TITLE
Cannot solve the Specify How Fonts Should Degrade challenge in Firefox 52 on Linux

### ISSUE THREAD

**Issue by maticahacic** [freeCodeCamp/freeCodeCamp#14415]
#### Name of challange

https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade

#### Issue Description
When I try to solve the challenge in Firefox it doesn't correctlly show that I solved the issue. I checked in Google Chrome and I could finish it with same code as in screenshot. I asked for help on gitter and everycode I tried didn't solve the puzzle.

#### Browser Information

* Browser Name, Version: Firefox  52.0.2 (64-bit)
* Operating System: Arch Linux
* Mobile, Desktop, or Tablet: Desktop

#### Sample Code

```
<!--
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->
<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum dolor sit amet....</p>
<p class="red-text">Purr jump eat the grass rip....</p>
```

#### Screenshot
http://i.imgur.com/WqFCXvg.png

**Comment by erictleung** [comment]
@maticahacic thanks for the issue, and sorry to hear you're having issues. I'm unfortunately unable to reproduce your issue on Firefox with the same version. However, I'm using Linux Mint rather than Arch Linux.

![image](https://cloud.githubusercontent.com/assets/2754821/25068862/19548ba4-2225-11e7-8500-6c2d703bda83.png)

Some troubleshooting tips are to Reset the challenge and try again. Otherwise, I'm not sure how this could be a browser-specific bug. I'll leave this open for others to comment in case this can be reproduced.

**Comment by maticahacic** [comment]
@erictleung Yeah it's totally wierd. I tried reseting challenge and browsers cache but still doesn't work. I don't mind this being an issue just posted to see if some other combination of browser and OS will have same issue.

BTW I haven't finished this challenge (in chrom I tried as Guest) so I can try to troubleshoot somemore. If that doesn't work I'll just login with Chrome and finish it. So as such is not a problem at all.

**Comment by Mougassa** [comment]
I had the same issue.  I eventually tried in Chrome and it worked fine.  Went back to Firefox (53.0.2) and it still doesn't work.  Firefox does not seem to be getting the Lobster font.  When I tried in Chrome, I was surprised to see what the Lobster font actually looked like.

**Comment by lobscouse** [comment]
Confirmed on Firefox 52.0.2 on Debian
