### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by zhew117** [freeCodeCamp/freeCodeCamp#14412]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20%2B%2BmyVar%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = ++myVar;


```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by X-T-G** [comment]
this is my code,and i have passed this course,just like this :
var myVar = 87;

// Only change code below this line
myVar ++;
var myVar;

**Comment by texas2010** [comment]
@X-T-G 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
