### ISSUE TITLE
helloworld

### ISSUE THREAD

**Issue by Jessamarie18** [freeCodeCamp/freeCodeCamp#14429]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>


```

**Comment by erictleung** [comment]
@Jessamarie18 hi there! Thanks for the issue, but GitHub issues are only for reporting bugs on the site. Your code passes the challenge, so congrats! If this is an actual bug on the site, please comment back with clarification. Otherwise, please take a look at our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) for other places to share your coding success. If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
