### ISSUE TITLE
I can't find the problem,please help me

### ISSUE THREAD

**Issue by WUJIUMEN** [freeCodeCamp/freeCodeCamp#14435]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%3Cp%3EI'm%20a%20%20p%20tag!%3Ch2%3EHello%20Paragraph%3C%2Fh2%3E%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<p>I'm a  p tag!<h2>Hello Paragraph</h2></p>
```

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
