### ISSUE TITLE
jQuery_and_Bootstrap

### ISSUE THREAD

**Issue by Emmanueldlams** [freeCodeCamp/freeCodeCamp#14472]
Challenge [Create a Bootstrap Headline](https://www.freecodecamp.com/challenges/create-a-bootstrap-headline#?solution=%3Ch3%3EjQuery%20Playground%3C%2Fh3%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h3>jQuery Playground</h3>




```

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
