### ISSUE TITLE
Cursor is not moving beyond line number 69

### ISSUE THREAD

**Issue by shubhamivane** [freeCodeCamp/freeCodeCamp#14488]
#### Challenge Name

https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls
#### Issue Description

When I was adding class form-control to the input element at that time this issue occur.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```



```
#### Screenshot

![screenshot 1](https://cloud.githubusercontent.com/assets/18081108/25165404/fc7a7896-24f3-11e7-8d25-ec9dff1df06a.png)

**Comment by johnnyjp2070** [comment]
The same issue for me :(

**Comment by erictleung** [comment]
@shubhamivane sounds like you're experiencing a similar issue to https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. I'll be closing this as it sounds similar enough. Please head over to that thread for some workarounds. If it turns out not to be your issue, please comment back with more details that make it different enough from that issue. Happy doing!

**Comment by rasz19** [comment]
follow the step men

**Comment by Haiderkamel** [comment]
First, you need to Give your form's text input field a class of form-control
so before you add the class,your code look like this :  _<form action="/submit-cat-photo">_
after you added the class, this what your code looks: _<form class="form-control" action="/submit-cat-photo">_ Then complete your challenge....
