### ISSUE TITLE
Technically incorrect code passes

### ISSUE THREAD

**Issue by deaninous** [freeCodeCamp/freeCodeCamp#14499]
Challenge [specify-upper-and-lower-number-of-matches](http://beta.freecodecamp.com/en/challenges/regular-expressions/specify-upper-and-lower-number-of-matches) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The below code passes. However the instructions seem to as to only capture the appropriate sequence of h(s).
I included the "O" and the platform was happy with it. Attached a screengrab.
![screenshot from 2017-04-19 16-08-56](https://cloud.githubusercontent.com/assets/12078887/25200023/ea8cc248-251a-11e7-9c9c-102725609b10.png)

```js

"use strict";
let ohStr = "Ohhh no";
let ohRegex = /O{1}h{3,6}\b/; // Change this line
let result = ohRegex.test(ohStr);

```

**Comment by JoolsMcFly** [comment]
I don't think that's an issue.

What was asked was for you to use `h{3,6}` which you did. You then went on to add `O{1}` which ensures there's an O before all h's. That's fine, it's just extra precaution and shows you know how to use quantity quantifiers.

Since it's all good, can you close this issue pls? Thanks.

**Comment by deaninous** [comment]
Closing right away. Sorry for the false alarm
