### ISSUE TITLE
Hey guys im really stuck here!Need some help with responsive design!

### ISSUE THREAD

**Issue by Joelveggie** [freeCodeCamp/freeCodeCamp#14502]
#### Browser Information

* Browser Name, Version: Google
* Operating System: Windows
* Mobile, Desktop, or Tablet:Laptop 

#### Your Code

```js



```

**Comment by erictleung** [comment]
@Joelveggie Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
