### ISSUE TITLE
Add items to array won't accept single quotes

### ISSUE THREAD

**Issue by deaninous** [freeCodeCamp/freeCodeCamp#14504]
Challenge [add-items-to-an-array-with-push-and-unshift](http://beta.freecodecamp.com/en/challenges/basic-data-structures/add-items-to-an-array-with-push-and-unshift) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I chose not to include my work, thinking ithat it would be easy to reproduce the issue
This challenge as I tried it, won' t accept single quotes. It does pass with double quotes

```js


//code edited out



```

**Comment by JoolsMcFly** [comment]
It would definitely help if you showed some code as I got it to work with single and double quotes.

**Comment by erictleung** [comment]
@deaninous thanks for the issue, but as @JoolsMcFly has mentioned, showing your code that you think produces the bug is crucial for us to investigate the bug. Especially, when I put in my code for this challenge and I got it to pass.

```js
function mixedNumbers(arr) {
  // change code below this line
  arr.push(7, 'VIII', 9);
  arr.unshift('I', 2, 'three');
  // change code above this line
  return arr;
}
```

Please share your code which doesn't pass so that we can investigate this further. This may be a browser issue as well so please share that information as well. I'm on Chrome Version 58.0.3029.81 (64-bit).

**Comment by deaninous** [comment]
I tried but could not reproduce it.
It was probably browser relater.
