### ISSUE TITLE
Error with Case

### ISSUE THREAD

**Issue by brianfurrer** [freeCodeCamp/freeCodeCamp#14522]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
case 1:
answer = "alpha";
break;
case 2:
answer = "beta";
break;
case 3:
answer = "gamma";
break;
case 4:
answer = "delta";


  
  // Only change code above this line  
  return answer;  
  }
}
```
![freecodecamp](https://cloud.githubusercontent.com/assets/12480000/25286880/28458af2-2674-11e7-9e90-0384d19abe0f.PNG)

FreeCodeCamp says the above code does not produce the correct output (see attached PNG file). However, testing at https://www.w3schools.com/js/tryit.asp?filename=tryjs_output_dom shows that it works (see test.PNG).

![test](https://cloud.githubusercontent.com/assets/12480000/25287008/91e914d8-2674-11e7-82a6-474ebd0a33b0.PNG)

**Comment by texas2010** [comment]
@brianfurrer 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only. 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by dogtoothdigital** [comment]
Hi there,

That's not a bug; your code is wrong.

If you had correctly included *var answer = "";* instead of omitting the
*var* keyword, your code would not work.

Your code as written only happens to work because of a technicality related
to the fairly flexible way that JavaScript variable scoping works; by
eliminating the *var* keyword you've declared *answer* as a global variable
inside your function so your code only shows the correct output string
because *answer* is still within scope when the DOM call is fired after the
*caseInSwitch* function call.

If you do the correct thing and use the *var* keyword to restrict the
variable scope to the function, the code fails to produce the desired
output because (1) the return statement is incorrectly nested inside case 4
so only val == 4 should yield any return value ("delta"); any other input
will cause the function to execute without a return value, and (2)
*answer* will
be undefined when the DOM call is made because *answer* is no longer
globally scoped.  Btw, it's a bad habit not to indent cleanly; this makes
it harder to spot syntax errors such as statements included at the wrong
level (like your *return* statement).  But the parentheses should clue you
in.

So you've basically managed to (presumably accidentally) stumble across a
way to technically produce the correct output by writing faulty code.  This
is far easier to do in JavaScript because it's a very flexible language
with lax typing, scoping, etc.

-meg

**Comment by brianfurrer** [comment]
Thanks for the explanation.

**Comment by dogtoothdigital** [comment]
Sure thing.  JavaScript can be a pain to debug actually; I really need to
look up good techniques/approaches/tools bc I'm so used to using text files
<-> browsers rather than IDEs/sandboxes/etc.

* edit: parentheses -> curly braces {}

Happy coding...

-meg
