### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hilaryoleh** [freeCodeCamp/freeCodeCamp#14528]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the first sentence.";
myStr += "This is the second sentence.";



```

**Comment by Manish-Giri** [comment]
@hilaryoleh Thank you for reporting this issue. Your code is incorrect. Please use the Gitter chat rooms linked below for asking for help. GitHub issues are not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

**Comment by JoolsMcFly** [comment]
Also, read more carefully the *Notes* section, especially the last sentence. Should help you get green.

Can you close this issue please?
Thanks.

**Comment by texas2010** [comment]
@hilaryoleh 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by fatbacker** [comment]
The chat rooms are worthless for most issues.
