### ISSUE TITLE
:-|

### ISSUE THREAD

**Issue by sajadk16** [freeCodeCamp/freeCodeCamp#14530]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20test%3DtestArr%5B0%5D%3B%0A%20%20testArr%5B0%5D%3DtestArr%5B1%5D%3B%0A%20%20testArr%5B1%5D%3DtestArr%5B2%5D%3B%0A%20%20testArr%5B2%5D%3DtestArr%5B3%5D%3B%0A%20%20testArr%5B3%5D%3DtestArr%5B4%5D%3B%0A%20%20testArr%5B4%5D%3Ditem%3B%0A%20%20item%3Dtest%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  test=testArr[0];
  testArr[0]=testArr[1];
  testArr[1]=testArr[2];
  testArr[2]=testArr[3];
  testArr[3]=testArr[4];
  testArr[4]=item;
  item=test;
  return item;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by erictleung** [comment]
@sajadk16 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
