### ISSUE TITLE
Extra test really needed for Truncate a string challenge

### ISSUE THREAD

**Issue by taw** [freeCodeCamp/freeCodeCamp#14540]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string) has an issue.

You really need to test something like `truncateString("A", 3)`, as it's not clear if it should return `"A"` or `"A..."`.

**Comment by Abdifatah25** [comment]
It should return `"A"` 

This is because you only add `"..."` if the string (first argument) is longer than the max string length (second argument). 

In your example `string = "A"` and the `max string length = 3`. Thus string can fit within the maximum, hence no need to add `...`.

Hope this helps!
