### ISSUE TITLE
urlSlug challenge failing a test

### ISSUE THREAD

**Issue by deaninous** [freeCodeCamp/freeCodeCamp#14550]
Challenge [apply-functional-programming-to-convert-strings-to-url-slugs](http://beta.freecodecamp.com/en/challenges/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// the global variable
var globalTitle = "Winter Is Coming";

// Add your code below this line
function urlSlug(title) {
 return title.trim().toLowerCase().split(/\W/).join("-")

  
  
}
// Add your code above this line

var winterComing = urlSlug(globalTitle); // Should be "winter-is-coming"
console.log(winterComing ===  "winter-is-coming")//true but I am still not passing the test

```
feedback:
```html
// running test
"message: urlSlug(" Winter Is  &nbsp;Coming")</code> should return <code>"winter-is-coming"."
```

**Comment by erictleung** [comment]
@deaninous thanks for the issue, but your code doesn't fulfill the challenge tests. The test you're failing at has extra spaces in it. When I run your code I get this

```js
function urlSlug(title) {
 return title.trim().toLowerCase().split(/\W/).join("-"); 
}
urlSlug(" Winter Is  Coming"); // Returns "winter-is--coming"
```

Closing as a non-bug. Happy coding!

**Comment by knight2** [comment]
@erictleung This is still a bug. The OP's code does not pass that test case because it their code doesn't handle the extra space, my code handles the extra space, yet still fails that test case.
`
// the global variable
var globalTitle = "Winter Is  Coming";

// Add your code below this line
function urlSlug(title) {
  let strArray = title.split(/\W+/);
  let hyphenStr = strArray.join("-");
  hyphenStr = hyphenStr.toLowerCase();
  return hyphenStr;
}
// Add your code above this line

var winterComing = urlSlug(globalTitle); // Should be "winter-is-coming"
console.log(winterComing);`

My code returns 
`"winter-is-coming"` for the string "Winter Is  Coming" (With extra space)

and the failed test case is
`urlSlug(" Winter Is  Coming") should return "winter-is-coming".
`

**Comment by SoyketHM** [comment]
My Solution Is

return title.toLowerCase().split(/\s/).filter(x => x !== "").join("-");
