### ISSUE TITLE
The space after the first string! This is a bug.

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14567]
Note
Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

var myStr = "This is the start. " + "This is the end.";

This a bug issue. This is supposed to be a tutorial, not a guessing game. The instructions do not tell us to use the space after the first string. We have to guess. How are we supposed to trouble shoot if we do not know what is necessary for coding? The need for a space between the last string word in the first string and the close quotation is needed information and you do not make that clear. This is a bug issue.

**Comment by jason54178** [comment]
It's not a bug, if you paid attention to what's required to pass the test it states that the string needs to be "This is the first sentence. This is the second sentence."

There is a space there.

**Comment by fatbacker** [comment]
I did pay attention. It says nothing about the spaces needed between the quotes and the last word in the string. Your wording is wrong and confusing. If it was clear then there would not be so many questions for this lesson.

**Comment by Manish-Giri** [comment]
@fatbacker 
This is the instruction -
>Build myStr from the strings "This is the start. " and "This is the end." using the + operator.

There's clearly a space at the end of `start. ` -  
![space](https://cloud.githubusercontent.com/assets/11348778/25318370/2074c37c-285b-11e7-9da7-182f1a155c6a.png)

This, along with the `note` up top -
>Note
Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

is as specific as things can be.

You need to pay attention to the details in programming -

>It says nothing about the spaces needed between the quotes and the last word in the string.

**Comment by fatbacker** [comment]
I did pay attention I even post the" watch out for spaces" the issue is that it does not say that there has to be spaces. For a complete beginner like me that makes no sense. I should be informed in this segment that there needs to be the space. Like I said before this is a tutorial, not a guessing game to figure things out.

**Comment by fatbacker** [comment]
Again, it does not tell me where the spaces are supposed to be. It only says watch out for them. For someone new to this it makes no sense. The wording on where the spaces needs to be specific. This is a tutorial, not a guessing game.

**Comment by raisedadead** [comment]
@fatbacker thanks for your report, I see that you have opened up a couple issues and are finding it difficult in going through the challenges. Trust me I share your frustration and understand how it feels to be a beginner at something.

But, I would humbly suggest that this issue tracker is not going to help.
Please reach out to the chat rooms and the forums.

> Like I said before this is a tutorial, not a guessing game to figure things out.

Yes, and you would be 100% correct in saying so. I agree. But I humbly would point that the challenges do not aim to give you step by step instruction of each line. 

Please do not take this otherwise.

Here's a tip that might help:

1. Do not lose your calm.
2. If you get stuck, re-read the instructions.
3. Repeat steps 1-2 at least 3 times.
4. Reach out to the chat rooms.
5. Reach out to the forums.

I am sure somebody has already faced the same challenges as you and have already explained how to get through the challenge. Remember we all are beginners here.

Thanks a lot. Goodluck and happy coding!
