### ISSUE TITLE
I have no spaces! 

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14563]
```
var myStr="FirstLine\n\\SecondLine\\\rThirdline";
```

I have no spaces and it is still wrong. I have tried spacing and it is still wrong. It also does not show the double \\ when I update my comment.

**Comment by erictleung** [comment]
Thank you for reporting this issue. Check that you're using the correct case. You're one character off.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
