### ISSUE TITLE
Regex help needed: Capitalize first letter of each word is also capitalizing I'M

### ISSUE THREAD

**Issue by 2akurate** [freeCodeCamp/freeCodeCamp#14560]
#### Title Case a Sentence
[Challenge link](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20%0Avar%20result%20%3D%20str.toLowerCase().replace(%2F(%3F%3A%5E%5Cw%7C%5BA-Z%5D%7C%5Cb%5Cw)%2Fg%2C%20function(letter%2C%20index)%20%20%20%7B%0A%20%20%0A%20%20%20%20return%20letter.toUpperCase()%3B%0A%20%20%0A%20%20%7D)%3B%0A%20%20%0A%0A%20%20return%20result%3B%20%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A)

#### Issue Description
I'm capitalizing the first letter of each word through a regex expression, it looks like this:

/(?:^\w|[A-Z]|\b\w)/g

However this is also capitalizing the M in the word I'm. So it looks like I'M. How do I account for this discrepancy in regex form? \b\w says the engine should grab each letter after a word boundary, so usually this is space. However apparently it is also a single quote.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

var result = str.toLowerCase().replace(/(?:^\w|[A-Z]|\b\w)/g, function(letter, index)   {
  
    return letter.toUpperCase();
  
  });
  

  return result; 
}

```

**Comment by erictleung** [comment]
@2akurate Thank you for reporting this issue. GitHub issues are for bugs, not coding help. Please refer to the link of Gitter chat rooms for help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
