### ISSUE TITLE
Run Tests Button Not Working on Google Chrome; any fixes/suggestions?

### ISSUE THREAD

**Issue by baconandchips** [freeCodeCamp/freeCodeCamp#14591]
Challenge [Style the HTML Body Element](https://www.freecodecamp.com/challenges/style-the-html-body-element#?solution=%0A%3Cstyle%3E%0A%20%20background-color%3A%20black%3B%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  background-color: black;
</style>

```

**Comment by erictleung** [comment]
@baconandchips Thank you for reporting this issue. Your code is incorrect. Please reset your code and try again. Take a look at the example code in the instructions for some help. Otherwise, please consult the Gitter chat rooms linked below.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
