### ISSUE TITLE
Use IO.js for es6 supercalifragilisticexpialidociousness

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#146]
@QuincyLarson @terakilobyte 

Use of IO.js would be awesome here as it would mean being able to use es6 features, newest version of Googles V8, and not to mention all the bug patches that come with that.

The downside here would be for new users trying to learn by running the site here. This could potentially raise the barrier to use here. There are great options for switching between Node and IO.js(n and nvm both support switching), and All node scripts will run in IO.js (for the most part).

@QuincyLarson I think this would be a great addition code-wise, but I understand one the reasons for this code base is to allow new Campers to play with the site. I just wanted to put it out there.

What do the campers that contribute or want to contribute or may in the near future contribute think about it? 

@terakilobyte What do you think?

**Comment by brndnb** [comment]
I think this is a great idea. You mention a potential barrier to entry, but if someone can't figure out how to switch between Node and io.js, how much contribution will they really be offering anyway? If anything, it is another small learning opportunity for anyone that isn't already using nvm or similar.

**Comment by terakilobyte** [comment]
I feel that since 99.9% of the current code would run on io.js (may well be 100%) that there's not a huge barrier to entry. Additionally, getting used to es6 is definitely the way forward I think.

I vote io.js and react/flux/rxjs all the way. This is excellent to proof so we can teach in the future considering es6 **is** the future and react will have a native library so campers in the future will be able to write apps for ios and android as well as the web.

Win Win.

**Comment by BerkeleyTrue** [comment]
Just heard from @QuincyLarson he is in favor.
