### ISSUE TITLE
Chaining If Else Statement

### ISSUE THREAD

**Issue by anoora17** [freeCodeCamp/freeCodeCamp#14644]
Please fix the chaining if Else Statement. The code run test, runs perfectly but for some how the challenge will not submitted  

My code:
```javascript

function testSize(num) {
  // Only change code below this line
   if (num <5){
    return "Tiny";
  } else if (num <10){
     return"Small";
  }else if (num<15){
    return "Medium";
  } else if (num <20){
    return"Large";
  } 
  else if (num >=20) {
    return" Huge";
  
  
  } else
  
  
  return "Change Me";
  // Only change code above this line
}

// Change this value to test
testSize(25);

```

**Comment by erictleung** [comment]
@anoora17 Thank you for reporting this issue. Look at the last tests you're failing and take a look at your code to find out why your code is not passing. You have one extra character somewhere.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by Renitstark** [comment]
function testSize(num) {
  // Only change code below this line
  if( num < 5)
    {
      return "Tiny";
    }
  else if (num < 10)
    {
     return "Small";
    }
  else if (num < 15)
    { return "Medium";
    }
  else if (num < 20)
    {
      return "Large";
    }
  else if (num >=20)
  return "Huge";
  else
    return " change me ";
  // Only change code above this line
}

// Change this value to test
testSize(25);
