### ISSUE TITLE
I can't seem to get this to work

### ISSUE THREAD

**Issue by spottedwolf** [freeCodeCamp/freeCodeCamp#14653]
#### Issue Description

![image](https://cloud.githubusercontent.com/assets/18464411/25565933/19d545b8-2d8e-11e7-8d84-a778f2388d63.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18464411/25565938/248276e8-2d8e-11e7-8361-1c34a845ac1f.png)

**Comment by erictleung** [comment]
@spottedwolf Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
