### ISSUE TITLE
Game Of Life - Demo App Bug

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#14674]
#### Challenge Name

[Game Of Life demo app](https://codepen.io/freeCodeCamp/full/reGdqx) 

#### Issue Description

1. Open up the URL, the game starts playing
2. Change the board size using the controls below
3. Click "run" at the top, nothing happens

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac OSX 
* Mobile, Desktop, or Tablet: Desktop

**Comment by honmanyau** [comment]
@Manish-Giri I don't think it's a bug exactly—I had a quick look and it appears that the code just isn't written to do that at all.

The solution is to add the following lines to the click event handlers for each of the buttons ([fork](https://codepen.io/honmanyau/pen/dWRayN?editors=1010) on CodePen with fixes):
```
    initialSet();
    running = 1;
    runIt();
``` 
Potentially silly question (am new to this!)—should I start a separate issue about how the board is not getting displayed properly (rows getting pushed down presumably beacuse of spacing around the last cell of each row, which can be fixed with ```box-sizing: border-box``` and readjusting the cell sizes for each board manually)?

In addition, does it seem strange that all React components and ```ReactDOM.render()``` are wrapped in functions and called with JavaScript/jQuery? Instead of having the component wrapping the logic?

For example, I was under the impression that the rendering should ideally by done, which would also be handled by React automatically, with a change in the state of the board with ```this.setState()``` in the component that is holding the board.  At the moment ```ReactDOM.render()``` is wrapped inside a functio called ```drawBoard()```, which is explicitly called in several other functions and once inside a React component that is wrapped inside ```createBoard()```.

**Comment by no-stack-dub-sack** [comment]
@Manish-Giri @honmanyau This won't matter a whole lot once the beta curriculum is shipped, there's a new version of the game of life demo that does not have this same feature:  https://codepen.io/freeCodeCamp/full/BpwMZv/. 

And it's now an "extra credit" project rather than required.
