### ISSUE TITLE
Title Case A Sentence 

### ISSUE THREAD

**Issue by PaulNewman-M** [freeCodeCamp/freeCodeCamp#14709]
Title Case a Sentence 

https://www.freecodecamp.com/challenges/title-case-a-sentence#?

#### Issue Description

I got an exact   answer but still it showing red mark.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

function titleCase(str) {
  
   var array=[],a=[];
  array=str.split(" ");
  for(i=0;i<array.length;i++){
  var small=array[i].toLowerCase().split("");
  small[0]=small[0].toUpperCase();
  a += small.join("");
  a +=" ";
  }
  var b=a;
  return b;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

<img width="859" alt="screenshot" src="https://cloud.githubusercontent.com/assets/26643538/25688127/0d5b7bca-3042-11e7-8605-3a63fdb28698.png">

**Comment by Manish-Giri** [comment]
@PaulNewman-M In times like these, it is often helpful to use a site like JSBin to help debug your code. I did that, and looks like your code returns an extra space at the end of the converted string, which is why it doesn't pass - https://jsbin.com/yayabimapi/edit?js,console

Also, please visit the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) first for help with challenges, in future.

**Comment by raisedadead** [comment]
Hi @PaulNewman-M 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

P.S: Thanks @Manish-Giri
