### ISSUE TITLE
CSS color challenges always fail in Firefox

### ISSUE THREAD

**Issue by yergi** [freeCodeCamp/freeCodeCamp#14714]
#### Challenge Name
This occurs in all challenges related to setting colors in CSS, such as [Basic CSS: Use Hex Code for Specific Colors](http://beta.freecodecamp.com/en/challenges/basic-css/use-hex-code-for-specific-colors)

#### Issue Description
This is related to issue #14460, which was incorrectly closed as being related to using a mobile browser. As you can see from my User Agent, I am on a macOS laptop using the desktop version of Firefox. Any and all challenges that require setting specific colors in CSS fail in Firefox, whereas the exact same code will pass when using Safari. This occurs whether setting colors using hex codes, rgb values, or hsl values.

#### Browser Information
User Agent is: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0`.

#### Screenshot
Here is a screenshot from another Basic CSS challenge showing the failure, despite the code being correct (and the lesson passing when I pasted the exact same code into Safari).
![](https://cloud.githubusercontent.com/assets/7504815/25588409/2c5bff36-2e76-11e7-8054-1b62377e2e55.png)

**Comment by systimotic** [comment]
@yergi Hi! Thanks for reporting this issue.

Those are indeed to separate issues, both difficult and open for quite a while. The main difference is that the CSS tests problem only happens on the beta, and the space problem only on production.

This bug report is great, you really figured out exactly what was wrong. Thanks a lot for that, it makes it a lot easier to fix the problem.

This issue is also already known, and is being discussed in #10749.
I'm closing this as a duplicate. Happy coding!
