### ISSUE TITLE
Error in update of the value at myStr

### ISSUE THREAD

**Issue by vineethkasula** [freeCodeCamp/freeCodeCamp#14733]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the First sentence. "+ " ";

myStr += "This is the second sentence.";



```

**Comment by erictleung** [comment]
@vineethkasula Thank you for reporting this issue. Please take a look at the strings you're supposed to have in this challenge. It doesn't match exactly what the challenge is asking for.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by toscanoGithub** [comment]
Yes there is a problem with this issue:
So unlike what the message say, the two sentences are on the same line with a space separating them.(may be cause I am on a small screen and it happens to put the second sentence on the next line).
The result of myStr should be like this:
"This is the first sentence. This is the second sentence."
How to proceed?
var myStr = "This is the first sentence. ";

myStr += "This is the second sentence.";
