### ISSUE TITLE
console.log() doesn't appear to be working. Console goes blank after running once with no message appearing.

### ISSUE THREAD

**Issue by davmey** [freeCodeCamp/freeCodeCamp#14730]
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=%0Afunction%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20alert(%22hello%22)%3B%0A%20%20console.log(%22starting...%22)%3B%0A%20%20if(num%3C0%7C%7C!isNaN(num))%20return%20%22%22%3B%0A%20%20var%20test%3B%0A%20%20alert(num%20%25%202)%3B%0A%20%20return%20%22%22%3B%0A%7D%0A%0ArepeatStringNumTimes(%22abc%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function repeatStringNumTimes(str, num) {
  // repeat after me
  alert("hello");
  console.log("starting...");
  if(num<0||!isNaN(num)) return "";
  var test;
  alert(num % 2);
  return "";
}

repeatStringNumTimes("abc", 3);

```

**Comment by erictleung** [comment]
@davmey Thank you for reporting this issue. When it says "return", that means to return that value as a string, not an alert.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by davmey** [comment]
Yeah, I don't think you read my comments at all, but whatever...

**Comment by erictleung** [comment]
@davmey apologies if I missed it, but you're focusing on the output of `console.log()`, correct? If so, the "console" on the site doesn't behave as your browser's console. If you want a full look at all `console.log()` outputs, I would use your browser's developers console.
