### ISSUE TITLE
Error in updating the value at myStr

### ISSUE THREAD

**Issue by vineethkasula** [freeCodeCamp/freeCodeCamp#14732]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22%20This%20is%20the%20end.%20%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + " This is the end. ";



```

**Comment by erictleung** [comment]
@vineethkasula Thank you for reporting this issue. You have an extra space in your string.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by RenevandenHeuvel** [comment]
I have the same answer and tried to get help in two chatrooms.
In the Javascript chatroom i was told to put in another space, but at the left and the right of the code i allready have a space.

var myStr = "This is the start."  +  "This is the end.";

I don't know where to ask for help now but here.

**Comment by huyenltnguyen** [comment]
Hi @RenevandenHeuvel! 
The correct answer must be:
`This is the start. This is the end.`
Your code is missing a space after the period of the first string. Here is the result of your code:
`This is the start.This is the end.`

**Comment by RenevandenHeuvel** [comment]
Thanks, i had to a break by the way, because I also was referring to another challenge in the chatrooms :)
