### ISSUE TITLE
error while using code pen with bootstrap and pug

### ISSUE THREAD

**Issue by frazer92** [freeCodeCamp/freeCodeCamp#14746]
While using Code pen website i was creating a page i have created a navigation bar but the toggle button does not toggle my navigation 
![screenshot 495](https://cloud.githubusercontent.com/assets/24915334/25771394/55689cfe-326d-11e7-9afd-ad301d47cc6f.png)

is this a bug or am i doing something wrong

**Comment by Margaret2** [comment]
Github Issues are for reporting bugs with the FCC website only, not Codepen or Bootstrap. If you need help with something, try asking in the [Help Room](https://gitter.im/FreeCodeCamp/Help) or on the [Forum](http://forum.freecodecamp.com)

**Comment by erictleung** [comment]
@frazer92 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
