### ISSUE TITLE
string issue

### ISSUE THREAD

**Issue by jtaptso** [freeCodeCamp/freeCodeCamp#14754]
Challenge [escape-sequences-in-strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr ="FirstLine\n\t\\SecondLine\nThirdline"; // Change this line



```

![unbenannt](https://cloud.githubusercontent.com/assets/10279251/25773287/629f76dc-327b-11e7-9c4e-37451e7a60b9.PNG)

**Comment by Margaret2** [comment]
Your code is incorrect. You need to capitalize the L in `ThirdLine`. Make sure to ask for help in the [JS Help Room](https://gitter.im/freecodecamp/helpjavascript) rather than posting an issue on Github.

**Comment by erictleung** [comment]
@jtaptso Thank you for reporting this issue. Please take a look at @Margaret2's comment on your code and it should help you solve the challenge.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by jtaptso** [comment]
@erictleung I'm really sorry. I did not pay attention
