### ISSUE TITLE
Bug in challenge Factorialize a Number

### ISSUE THREAD

**Issue by gimmieCarrot** [freeCodeCamp/freeCodeCamp#14752]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=%0Afunction%20factorialize(num)%20%7B%0A%20%20return%20(num%20!%3D%3D%200)%20%3F%20num%20*%20factorialize(num%20-%201)%20%3A%201%3B%0A%7D%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
This code outputs correct answer, but FreeCodeCamp doesn't approve it.

My code:
```javascript

var array = [];
var factorial = 0;
function factorialize(num) {
  if (num !== 0) {
  for (i = 1; i <= num; i++) {
      array.push(i);
      factorial = array.reduce(function(previousVal, currentVal) {
      return previousVal * currentVal;
        });
      } return factorial;
    } else {
      return 1;
  }
}
factorialize(0);


![bug factorialize fcc 1](https://cloud.githubusercontent.com/assets/26068629/25772653/097e3024-3281-11e7-9511-5e0be7d7508a.png)
![bug factorialize fcc 2](https://cloud.githubusercontent.com/assets/26068629/25772654/0988569e-3281-11e7-8ee0-673731336b1b.png)
![bug factorialize fcc 3](https://cloud.githubusercontent.com/assets/26068629/25772652/09792f34-3281-11e7-9c69-994e6f5f07d0.png)


```

**Comment by Margaret2** [comment]
@gimmieCarrot Your code is not correct. If you need help fixing it, ask in the [JS Help Room](https://gitter.im/freecodecamp/helpjavascript) or on the [forum](http://forum.freecodecamp.com). Github issues are for reporting bugs only.

**Comment by erictleung** [comment]
@gimmieCarrot Thank you for reporting this issue. As @Margaret2 has mentioned, don't use global variables because your function is reused.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
