### ISSUE TITLE
replace is not working

### ISSUE THREAD

**Issue by RaggedQuark** [freeCodeCamp/freeCodeCamp#14757]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20str.replace(%2F%5CD%2Fg%2C'')%3B%0A%20%20return%20str.toLowerCase()%3B%0A%20%20%2F*%0A%20%20var%20a%3D0%3B%0A%20%20for%20(var%20i%3D0%3Bi%3Cstr.length%3Bi%2B%2B)%0A%20%20%7B%0A%20%20%20%20if%20(str%5Bi%5D%3D%3D%3Dstr%5Bstr.length-1-i%5D)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20a%2B%2B%3B%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if%20(a%3E(str.length%2F2)-1)%0A%20%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%0A%20%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20*%2F%0A%7D%0A%0A%0A%0Apalindrome(%22_eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  str.replace(/\D/g,'');
  return str.toLowerCase();
  /*
  var a=0;
  for (var i=0;i<str.length;i++)
  {
    if (str[i]===str[str.length-1-i])
    {
      a++;;
    }
  }
  if (a>(str.length/2)-1)
  {
    return true;
  } else
  {
    return false;
  }
  */
}



palindrome("_eye");

```

**Comment by valeriecodes** [comment]
@RaggedQuark `replace` will not actually modify the string, if you want to keep the string with replacements, you'll need to do something like:
`str = str.replace(/\D/g,'');`

**Comment by erictleung** [comment]
@RaggedQuark Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
