### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by khamp19** [freeCodeCamp/freeCodeCamp#14761]
Variable not defined error: says reverse is not defined. Also says "loopProtect is not defined"

Challenge [reverse-a-string](http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/reverse-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

function reverseString(str) {
  let letters = str.split('');
  for(let i = letters.length - 1; i >= 0; i--){
    let reverse = [];
    reverse += letters[i];    
  }
  str = reverse.join('');
  return str;
}

reverseString("hello");
```

**Comment by erictleung** [comment]
Thank you for reporting this issue. There are several issues with your code which are making your function not pass the tests. Please review your code and ask questions in the help room if you have coding questions.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
