### ISSUE TITLE
Hex color not working in this problem

### ISSUE THREAD

**Issue by wikiwiggs** [freeCodeCamp/freeCodeCamp#14796]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20%2300f%3B%0A%20%20%7D%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .blue-text {
    color: #00f;
  }
  .red-text {
    //color: red;
    color: #f00;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Margaret2** [comment]
The tests aren't checking, "Does the h2 element look red?" 

They're checking, "Does the CSS `.red-text` class have the `color` property set to the value `red`?" - which is what the instructions say to do. 

The challenges don't allow for every possible solution that might work on your own project, they have specific instructions and tests that need to be followed.

**Comment by wikiwiggs** [comment]
I guess I won't report bugs any more, because I feel (IMHO) like my honest, & valid report (with the intent of just trying to help improve things) is just a way to get chastised.

Here's my explanation of it anyway, just in case it helps:

It passes when I pass the literal "red" value. However on many previous exercises (_not even related nor in the context of my own projects_), I was just using the hex and it was working fine. After all, **red** is just a name reference to these values. Anyway I was just noticing the inconsistency, and figured that it would be helpful to point it out.

I believe that the misunderstanding comes down to this:
When you say: 

> "Does the CSS .red-text class have the color property set to the value red?"

This does NOT say **type** the keyword **red**; hence the instructions are still being followed, because the reference keyword **red** is completely equal to #F00/#FF0000/rgb(255,0,0)/etc...

So when you say: 

> The tests aren't checking, "Does the h2 element look red?"

I kind of take offence to it, because I never implied that the element was some variant shade of **red**, but the **ACTUAL** equivalent value.

I also have a bit of a problem thinking this way, because CSS color properties are equal & valid in many different forms unlike HTML if someone typed <image src="#" /> instead of <img src"#" />, then your argument would make a lot more sense to me; because the <image src"#" /> would not be recognized or equivalent.

According to authoritative sources such as [MDN - Their definition of how to set color uses the idea of equality](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).

Quote from the link:

> The <color> CSS data type denotes a color in the sRGB color space. **A color can be described in any of these ways**:
> 
> using a keyword
> using the RGB cubic-coordinate system (via the #-hexadecimal or the rgb() and rgba() functional notations)
> using the HSL cylindrical-coordinate system (via the hsl() and hsla() functional notations)

**Comment by erictleung** [comment]
@wikiwiggs thanks for the issue. And you are correct that colors can be described in multiple ways. The reason why the challenge will only take it in this certain way is because our curriculum is designed for people who have never coded before, thus will not know of different ways to encode color. For someone who doesn't know how to code, just using the color words themselves is easier to understand. Using hex codes and other ways of encoding colors come later on in the curriculum.

So I'm not sure if we want to account for other colors in this challenge. But one thing we could do is to specify to use the word `red` within the style tags, rather than assume that the user will input the word itself.

cc/ @freeCodeCamp/moderators thoughts?

**Comment by wikiwiggs** [comment]
@erictleung I'm not trying to hi-jack the efforts here if that's the preferred way to deal with things. I personally believe that no matter what - when you are teaching CSS, and a user enters something valid, this should pass, when you teach other methods specifically later on great (the one doesn't take away from the other). 

I just know that frustrating users is just encouragement for them to give-up. 
If my math teacher told me to write a problem "(2*1) = 2" and I wrote "2 = (1*2)" should I fail? 
I personally say no, but obviously others would disagree. 

I also want to point out that people come from other backgrounds (even if that background is not programming) such as computer graphics where they see color in paradigms like hex/rgb/hsl/cmyk/etc... So if `red` to them is `#FF0000`, and CSS allows for them to enter it that way, then why would you want to get in the way of that (this is their process, and if it's valid, they should be able to reinforce their validity by getting the correct answer)?

[Source of Quotes](http://blog.ampli.com/2012/03/albert-einstein-quotes-education-15-of.html)

> The only source of knowledge is experience. 
> Albert Einstein

> The only thing that interferes with my learning is my education. 
> Albert Einstein

I would propose a different way of checking the answer, that's for certain.

Anyway, way too painful of a process over an observation with the intent to be helpful.

As far as I'm concerned do what makes sense to you, and I'll silently move along.

**Comment by raisedadead** [comment]
@Margaret2 @erictleung thanks.

@wikiwiggs thanks for the feedback and the pointers to the documentation. Here is our [code of conduct](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md) in support of the fact if you feel dissatisfied with the way, mods have responded to your request. 

Now coming, back to your query, please understand that:
 1. This particular challenge is NOT aimed to be a perfect code interpreter to handle all the possible ways to handle colors in the tests. I confirm that it's NOT the intention.
2. We aim to teach concepts, in small bits that are easy enough to grasp for newcomers.
3. We have challenges, that fulfill the gaps that you have CORRECTLY pointed.

Finally, we are not going to implement the change that is requested here, because of the additional complexity, it adds without adding value than that already is being delivered in this particular challenge.

Thanks. Happy coding!
