### ISSUE TITLE
I don't want to waste any more time answering a question I don't understand and want to move onto the next task but it won't let me. This is a terrible question to give to a beginner. How am I meant to even understand what's going on?

### ISSUE THREAD

**Issue by SusieTech** [freeCodeCamp/freeCodeCamp#14809]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20celsius%20%2B%3D%209%2F5*%20%2B%2032%3B%0A%20%20fahrenheit%20-%3D32*%205%2F9%20%3B%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%20%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  celsius += 9/5* + 32;
  fahrenheit -=32* 5/9 ; 
  // Only change code above this line
  return fahrenheit; 
}

// Change the inputs below to test your code
convertToF(30);

```

**Comment by diomed** [comment]
Apparently , you have an issue with task, task itself doesn't have an issue.

Sorry to break it down to you, but things don't get any easier from here, 
only tougher and more complicated. Welcome to the world of real coding.
Fight or flight. Or use proper helproom to ask for guidelines:
https://gitter.im/FreeCodeCamp/HelpJavascript

**Comment by dasdecoder** [comment]
Please read the question again, my friend. Happy coding.

**Comment by Margaret2** [comment]
Maybe this will help, maybe not...

One sentence needs to be converted into one line of code: 
Celsius is Fahrenheit times 9/5, plus 32. 

It's barely hard enough to call it algebra, more like basic math. 

When you're learning JS, you have to build up your ability to think logically. It takes a lot of study and time to solve the JS algorithms.

**Comment by NeeksGit** [comment]
You can't skip over basic things like this. As others have mentioned, the logic you're having trouble grasping here only will only compound going forward. 

Take things through step by step. This issue should be closed because it is not an issue.

**Comment by SusieTech** [comment]
Thanks everyone!! 

Much apprecited... I know it gets harder but for my first time using JS, I don't think it's possible to put  a logical hat on I've only been studying for a few weeks. But will take all advice on board and get used to coding!!

**Comment by SusieTech** [comment]
neeksgit: It's an issue for me therefore I will keep it open any help and advice I can get I will most certainly take. Kind of unfair to make that type of statement.

**Comment by erictleung** [comment]
@SusieTech thanks for the issue. As you found in another issue https://github.com/freeCodeCamp/freeCodeCamp/issues/14143, this challenge has been questioned many a time before and has been moved to another section due to its sudden introduction of multiple topics. So I'll be closing this issue as its been resolved in our development code.

GitHub issues are more for noticing bugs, rather than for coding help. For help, you can view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) for help and also the [forum](forum.freecodecamp.com). Both of which can be useful for beginners. The chat rooms can be helpful for somewhat real-time feedback, while the forums allow more long, threaded discussions. Hang in there! :+1: It is a difficult path to go on, but rewarding when you keep at it. Feel free to tag me in the chat rooms if you have any questions. Others there are more than willing to help as well. Happy coding!
