### ISSUE TITLE
Inconsistent Spelling and styles

### ISSUE THREAD

**Issue by amritpalnagrame** [freeCodeCamp/freeCodeCamp#14811]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.96 Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here is third paragraph's html :
```html
<p class="wrappable">Use an <code>in-line style</code> to try to make our <code>h1</code> element white. Remember, in line styles look like this:</p>
```
Which seems to me to be like :
```html
<p class="wrappable">Use an inline <code>style</code> to try to make our <code>h1</code> element white. Remember, in line styles look like this:</p>
```

**Comment by erictleung** [comment]
@amritpalnagrame thanks for the issue. It appears you're pointing out that `in-line` has a hyphen in one sentence but not the other?

**Comment by amritpalnagrame** [comment]
@erictleung yes, but it is also given styling of code.

**Comment by erictleung** [comment]
@amritpalnagrame oh I see now. You're also comparing it to what is styled in the first paragraph, correct? Because `style` is stylized in the first paragraph but then has `in-line style` in the third paragraph?

If so, this was on purpose. `in-line style` is specific and we also add this kind of formatting to new words that we introduce. It should have different tags around it though. I do agree that it should be `in-line style` with a hyphen within it.

**Comment by amritpalnagrame** [comment]
@erictleung Ok thanks
