### ISSUE TITLE
Twitter account can't be linked or relinked

### ISSUE THREAD

**Issue by JackSewell-Git** [freeCodeCamp/freeCodeCamp#14812]
#### Issue Description

I created my FCC account a few weeks ago. Since then my GitHub account has been deleted and recreated. I originally linked my Twitter account with my old GitHub account, however, with my new GitHub account being used on FCC I can't link nor relink to my Twitter account.

#### Browser Information

* Browser Name, Version: Firefox 53.0
* Operating System: Ubuntu 17.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/28600290/25911395/90ff0546-35ab-11e7-991d-9c3be8a0def8.png)

**Comment by raisedadead** [comment]
Hi @JackSewell-Git, I understand that you cannot add twitter to your new account. Can you check if this article applies to your case?

https://forum.freecodecamp.com/t/how-to-delete-twitter-account-from-free-code-camp/14991/3

If the above does not help, please drop us an email at team@freecodecamp.com and provide all the details, so that we can get back to you privately and help you through troubleshooting the info about your account.

Thanks, happy coding!
