### ISSUE TITLE
The test is completed without writing the arrow function. 

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14833]
Challenge [write-higher-order-arrow-functions](http://beta.freecodecamp.com/en/challenges/es6/write-higher-order-arrow-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

"use strict";
const realNumberArray = [4, 5.6, -9.8, 3.14, 42, 6, 8.34];
// change code below this line

var squaredIntegers = realNumberArray;
// change code above this line
// test your code
console.log(squaredIntegers);

```

**Comment by MiloATH** [comment]
I have written all the tests for this challenge except for the "Test user did replace var keyword" and "Test squaredIntegers is const". I don't know how to write these tests with the current way tests are written. The problem is that `code.match()` won't work since the `code` is parsed to only have `var`s.  Any suggestions?
