### ISSUE TITLE
Golfcode output

### ISSUE THREAD

**Issue by eshu14** [freeCodeCamp/freeCodeCamp#14837]
#### Golf Code

https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction golfScore(par%2C strokes) {%0A %2F%2F Only change code below this line%0A %0A if(strokes %3D%3D 1)%0A {%0A return "Hole-in-one"%3B%0A }%0A else if(strokes <%3D (par-2))%0A {%0A return "Eagle"%3B%0A }%0A else if(strokes <%3D (par-1))%0A {%0A return "Birdie"%3B%0A }%0A else if(strokes <%3D par)%0A {%0A return "Par"%3B%0A }%0A else if(strokes <%3D (par%2B1))%0A {%0A return "Bogey"%3B%0A }%0A else if(strokes <%3D (par%2B2))%0A {%0A return "Double Bogey"%3B%0A }%0A else if(strokes >%3D (par%2B3))%0A {%0A return "Go Home"%3B%0A }%0A %0A else %0A {%0A return "Change Me"%3B%0A }%0A %2F%2F Only change code above this line%0A}%0A%0A%2F%2F Change these values to test%0AgolfScore(4%2C7)%3B%0A
![2017-05-12_13h11_35](https://cloud.githubusercontent.com/assets/26653145/25997605/97d2f98a-3714-11e7-8c92-d0e953ac0486.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by texas2010** [comment]
@eshu14 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by matheusscardoso** [comment]
Hi @eshu14 !

Write this.
"Hole-in-one!"
and 
"Go Home!"

[https://github.com/freeCodeCamp/freeCodeCamp/issues/14804]

**Comment by eshu14** [comment]
Thank you for the help. I finally got through.
Regards,

Eshu
