### ISSUE TITLE
Correct solution fails without correct boilerplate HTML - Nest an Anchor Challenge

### ISSUE THREAD

**Issue by danjumaharjan** [freeCodeCamp/freeCodeCamp#14845]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EView%20More%20%3Ca%20href%3D%20%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3E%20cat%20photos%3C%2Fa%3E%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%22%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View More <a href= "http://www.freecatphotoapp.com"> cat photos</a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">


```

**Comment by rajibmp** [comment]
This is issue with test cases or not enough infromation about that is being tested. 

I tried editing your phase with the content from my solution and it passes the test while replacing your HTML with following:

```html
<h2 class="red-text">CatPhotoApp</h2>
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere  shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">


<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

Your test cases are different than mine but as the above HTML solves the issue this is a bug.

**Comment by LukeGeneva** [comment]
The initial code has two `<p>` elements pre-filled. The test cases are expecting these to still be present, but they appear to be missing from your solution code.

```
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by no-stack-dub-sack** [comment]
@danjumaharjan it looks like @LukeGeneva is correct, the test cases are expecting the 2 `<p>` tags that you removed to still be there. Other than that your code is right. 

@freeCodeCamp/moderators this is interesting. Anyone want to weigh in on this? I think either we should let the tests pass even if other non-required elements are deleted, or have an an additional test case that says no other code should be modified.

**Comment by kommalapatisuhas** [comment]
I'm unable to pass this challenge:
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>view more <a href="http://freecatphotoapp.com "> cat photos</a></p>
<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>




Here's an example:
<p>Here's a <a href="https://freecodecamp.com"> link to Free Code Camp</a> for you to follow.</p>
Nesting just means putting one element inside of another element.
Now nest your existing a element within a new p element (just after the existing h2 element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain
 
You need an a element that links to "http://www.freecatphotoapp.com". 

 
Your a element should have the anchor text of "cat photos" 

 
Create a new p element around your a element. 

 
Your a element should be nested within your new p element. 
{THIS CONDITION IS THE ERROR}
 
Your p element should have the text "View more " (with a space after it). 

 
Your a element should not have the text "View more". 

 
Make sure each of your p elements has a closing tag. 

 
Make sure each of your a elements has a closing tag.

**Comment by muguira-james** [comment]
Interesting...

I refreshed the page and did the assignment from scratch.  

<link...
<style...
<h2...
<p>View more <a...></a></p>
<p..
<p...

I guess the test app froze for this page.  The refresh solved it

**Comment by Margaret2** [comment]
It passes for me if I put in two empty `p` elements, so apparently the tests are just looking for at least 3 `p` elements, with or without the kitty ipsum text. So maybe some text could be added that says:
`There should be 3 p elements total.`

**Comment by danjumaharjan** [comment]
Thank You everyone for the help. I wrote it again from the scratch and now it passes. Its the same code, but this time it passes. I do not know what the issue was. But I really appreciate everyone for your help. Thank You.

**Comment by no-stack-dub-sack** [comment]
@danjumaharjan Glad you got this resolved, however, I'm going to reopen this issue as there is still a problem with the challenge here.

**Comment by no-stack-dub-sack** [comment]
@raisedadead This may be a silly question, but if Staging is now Beta - if we wanted to fix this on current production FCC, how would we do that? Make a PR to master branch instead?

I just realized I haven't changed anything in production since Beta went live since most efforts have been focused there.

**Comment by no-stack-dub-sack** [comment]
To summarize the problem, this code passes:

```html
<h2>CatPhotoApp</h2>
<main>
  
  <p>View more <a href="http://freecatphotoapp.com" target="_blank">cat photos</a></p>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  <p></p>
  <p></p>

</main>
```
while this code does not:
```html
<h2>CatPhotoApp</h2>
<main>
  
  <p>View more <a href="http://freecatphotoapp.com" target="_blank">cat photos</a></p>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">

</main>
```

Only difference being that the 2 `<p>` tags present in the original boilerplate have been removed in the version that fails the tests. 

This is the line causing the problem as it is looking for > 2 `<p>`s: 
```js
"assert($(\"p\") && $(\"p\").length > 2, 'message: Create a new <code>p</code> element around your <code>a</code> element.');",
```

I think we can solve this just by adding  `(there should be at least 3 `<p>` tags total)` to the same test case's message as @Margaret2 pointed out. 

I think we can open this up to beginners only to solve the problem in beta, but would like to hear @raisedadead's input first before doing so to see how this would be solved in prod.

**Comment by raisedadead** [comment]
@no-stack-dub-sack thanks for the tag. 

For fixes to production website (freecodecamp.com), you could open a PR against `backup/staging`, but keep in mind that we are keeping such changes only for critical show-stopper issues (something that breaks the site for all users alike or security issues, etc.), and may or may not be fixed in `staging` already.

Any changes to codebase should be pushed to `staging` first and if above is valid too, to backup as well after confirming.

Also note, that changes to backup branches are likely to be overwritten when beta, is shipped.
If the change is not present on staging and it's not a show-stopper, then we should be making a PR against `staging` instead, so that it's guaranteed to be present in the codebase even in the future, when we push beta to production.

Now coming, to your specific case, I can confirm that issue exists on the `staging` site too but is not a show-stopper. So this should be tagged for opening a fix against `staging` only.

**Comment by no-stack-dub-sack** [comment]
@raisedadead thanks! You answered all of my questions, and that totally makes sense!

I think this could also be first timers only since it's a pretty easy fix - the specific task to change this test case from:
```js
"assert($(\"p\") && $(\"p\").length > 2, 'message: Create a new <code>p</code> element around your <code>a</code> element.');",
```
to:
```js
"assert($(\"p\") && $(\"p\").length > 2, 'message: Create a new <code>p</code> element around your <code>a</code> element (there should be at least 3 total <code>p</code> tags in your HTML).');",
```
Please see the [Contributing Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) or ask if you have any questions!

**Comment by infinityl00p** [comment]
hi @no-stack-dub-sack, first-timer here! If its okay with you i'd like to take on this issue :) 💯

**Comment by infinityl00p** [comment]
hi @no-stack-dub-sack, i followed the guidelines and created a PR. :)

**Comment by no-stack-dub-sack** [comment]
@infinityl00p Great! Let me check it out

**Comment by rajibmp** [comment]
Oops, I realized was bit late in the party. I didn't realize the PR was made for this, feel free to close mine if earlier PRs fixes the issue.
