### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Asaplolmazo** [freeCodeCamp/freeCodeCamp#14862]
Challenge [Make Unique Objects by Passing Parameters to our Constructor](https://www.freecodecamp.com/challenges/make-unique-objects-by-passing-parameters-to-our-constructor#?solution=%0Avar%20Car%20%3D%20function(wheels%2C%20seats%2C%20engines)%20%7B%0A%20%20%2F%2FChange%20this%20constructor%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.seats%20%3D%205%3B%0A%20%20this.engines%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2FTry%20it%20out%20here%0Avar%20myCar%3Dnew%20Car(3%2C1%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = 4;
  this.seats = 5;
  this.engines = 1;
};

//Try it out here
var myCar=new Car(3,1,2);

```

**Comment by Asaplolmazo** [comment]
Seems I have done right, but it is nut running, not excepting. Please Help!

**Comment by texas2010** [comment]
@Asaplolmazo 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
