### ISSUE TITLE
Passing "Empty" Values to Functions with Arguments - tests still pass

### ISSUE THREAD

**Issue by JoeEarly** [freeCodeCamp/freeCodeCamp#14863]
Challenge [Passing Values to Functions with Arguments
](https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunctionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunctionWithArgs(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20functionWithArgs%20(word1%2C%20word2)%7B%0A%20%20console.log(word1%20%2B%20word2)%3B%0A%7D%0A%0AfunctionWithArgs()%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
function functionWithArgs (word1, word2){
  console.log(word1 + word2);
}

functionWithArgs();


```
Tests are passing when no values are passed into function, variable/parameter name is of no affect 
<img width="1384" alt="fcc-bug" src="https://cloud.githubusercontent.com/assets/5208459/26029030/ca1c8432-3823-11e7-851e-d6f71479b8b6.PNG">

**Comment by Margaret2** [comment]
@JoeEarly You don't have to call each test yourself, the test functions are called one after the other when you click "Run Tests".

**Comment by texas2010** [comment]
@JoeEarly 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
