### ISSUE TITLE
Something Went Wrong, Please Try Again Later (Error Message)

### ISSUE THREAD

**Issue by tobi10** [freeCodeCamp/freeCodeCamp#14883]
Challenge [selecting-from-many-options-with-switch-statements](https://beta.freecodecamp.com/en/challenges/basic-javascript/selecting-from-many-options-with-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Hello, I am not able to submit my task and proceed. I get the message "Something went wrong, please try again later" when I click on 'Run Test'. I had a similar issues this morning, and then went to do the exercise on Mozilla, but right now it's not working on both Mozilla and Chrome. Also the task before this (Golf code) has similar issues, I couldn't get pass it for the same reason.
P:S Something might be wrong with my code, but i cant even run it to check what i should correct.

```js


function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  case (1):
   answer = "alpha";
  break;
  case (2):
   answer = "beta";
  break;
  case (3):
   answer = "gamma";
  break;
  case (1):
   answer = "delta";
  break;
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);


```

**Comment by texas2010** [comment]
@tobi10 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

by the way, you didn't finish this challenge. that is why it won't work because you forget to add more code.

Happy Coding.
