### ISSUE TITLE
Still an issue with Challenge [Quoting Strings with Single Quotes]

### ISSUE THREAD

**Issue by mistermayo** [freeCodeCamp/freeCodeCamp#14897]
challenge is to Change the provided string from double to single quotes and remove the escaping. 
but only shows var myStr = '<a href=\"http://www.example.com\" target=\"_blank\">Link</a>';

```

**Comment by raisedadead** [comment]
Please provide details, as requested in the issue template.

**Comment by seacolt** [comment]
Hello! I too am having the same problem. Even after created the correct output, there is still a notification at the bottom of the page saying 'Only remove the backslashes used to escape quotes. Since the whole original input has to be deleted in order to complete the task, there's no way of making this go away. Please consider fixing this! Thanks.

**Comment by raisedadead** [comment]
@seacolt please provide your code and a few screenshots of the problem, to better assist you. Thanks.

**Comment by seacolt** [comment]
![fcc-error](https://cloud.githubusercontent.com/assets/25558381/26267341/948b71c8-3cb7-11e7-9e43-c28f63a9aeb4.png)

Any help would be appreciated! It's possible that this is just user error; if so, please let me know ;)

**Comment by raisedadead** [comment]
@seacolt your code is incorrect. 
@mistermayo Your code is incorrect as well. 

Please get in touch with the chat room or try looking through the forum for assistance.

Happy coding!
