### ISSUE TITLE
sitemap.xml is messed up

### ISSUE THREAD

**Issue by dcsan** [FreeCodeCamp/freecodecamp#1490]
http://www.freecodecamp.com/sitemap.xml

![image](https://cloud.githubusercontent.com/assets/514002/9050691/a6e37b92-3a05-11e5-8540-36b8096290d3.png)

**Comment by BerkeleyTrue** [comment]
@QuincyLarson I'm looking into this.

**Comment by BerkeleyTrue** [comment]
The only thing I can thing I can think of that could have screwed this up is the stories url's might no parse as correct xml. I don't see any recent changes to this file.

@QuincyLarson I can create a separate service to do sitemap for us (I'd prefer to move this into a separate repo all together) since we wanted to move away from doing this on our main servers anyways. I'm not going to be available till late tonight to do this. Give me a call when you can.

**Comment by BerkeleyTrue** [comment]
@dcsan Thanks for finding this(have no idea what you where doing to find this :) )
We suspect it was a story with a malformed URL that was throwing off the xml. It is fixed now.

**Comment by dcsan** [comment]
I was just chatting over some SEO ideas for FCC with someone and they pointed it out. you probably have some good people in the community who are learning to code but know a lot about SEO!
