### ISSUE TITLE
answer to Swtich case

### ISSUE THREAD

**Issue by Pulkit219** [freeCodeCamp/freeCodeCamp#14924]
```
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
switch (val) {
  case 1:
    answer= "alpha";
    break;
  case 2:
    answer= "beta";
    break;
  case 3:
    answer= "gamma";
    break;
  case 4:
    answer= "delta";
    break;

  default:
    console.log('Sorry');
}
return answer;
}
caseInSwitch(1);

```

**Comment by Pulkit219** [comment]
answer for those having trouble

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
