### ISSUE TITLE
Use of higher-order functions not being taught

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#14932]
#### Challenge Name
Higher-order functions challenges, e.g. https://www.freecodecamp.com/challenges/filter-arrays-with-filter

#### Issue Description
The code in the screenshot below lets the learner pass the challenge simply by reading "create a new array with all the values from oldArray which are less than 6", seeing `val !== 5` and changing it to `val < 6`, without having to understand that the higher-order function is passing each of the array's elements to the callback function (as `val`), and the syntax for that. I've helped a learner on Gitter with this lack of knowledge, which prompted me to create this issue.

I suggest the callback function is changed to `/* your function here */`.

#### Screenshot
![screen shot 2017-05-18 at 12 47 56](https://cloud.githubusercontent.com/assets/8081877/26200892/55723142-3bc8-11e7-9174-7381bae8157e.png)

**Comment by willnwhite** [comment]
@VarCI-bot This is not a question.

**Comment by willnwhite** [comment]
How can I make a pull request against this code? I've followed the Contributor's Guide up to [Make Changes](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#make-changes).

**Comment by no-stack-dub-sack** [comment]
Hi @willnwhite, before making a PR, please allow the FCC team to verify there is an issue that warrants a change. Per the contributors guidelines, an issue needs to be "confirmed" and labeled "help wanted" before a contributor is assigned and a PR is submitted. 

To clarify this issue, are you suggesting that the example shown in the side-panel be removed so that the user does not have such a clear example to base their own code off of? If so, I see the reason for your argument, but at the same time, examples are very helpful, and users need to be able to supplement their learning with additional resources, such as a google search, reading documentation, and asking for help as someone did in the gitter chat rooms when you helped them. 

Changes like these will likely not be made to the production version of freeCodeCamp at this time, as the priority is shipping the beta curriculum, in which challenges such as these have been improved, removed, or changed. If there is going to be a change made, it would be there. 

Although, this is FCCs model of teaching in general, and there are many many challenges that follow this model. A change like this would be tantamount to changing the entire way FCC teaches, and I am not sure we are ready to make that kind of change.

**Comment by willnwhite** [comment]
Hi @no-stack-dub-sack. The Contributor's Guide is worded as though the reader was looking to work on an issue they hadn't raised themselves: "Find an issue that needs assistance by searching for the Help Wanted tag." So I didn't think about that as I didn't think it was intended for me. I'm happy to propose a change to the wording.

As we've both spent time finding out for ourselves, the issue doesn't apply in the development version of the website. I hope having two versions of the website will be avoided in future, to minimise hurdles for more casual contributions. I've raised this on the discussion forum: https://forum.freecodecamp.com/t/have-one-single-version-of-fcc-not-a-beta-too/117837.

For interest's sake, I wasn't suggesting the example be removed. I suggested the example be:
```
array = array.filter(/* your function here */);
```
