### ISSUE TITLE
Limited Free Heroku Apps

### ISSUE THREAD

**Issue by wewark** [freeCodeCamp/freeCodeCamp#14940]
#### Issue Description

Heroku limits the deployment of free apps to 5, while the backend projects need more than that. I don't think I should delete any of the previous as they have to be online to be reviewed when requesting a certificate.

**Comment by raisedadead** [comment]
As per this [page](https://devcenter.heroku.com/articles/limits) it's the limit for their `performance` dynos and not the hobby (free) dynos, correct? I have registered more than 5 apps (hobby) on my account, although mine is an older account, unsure if they have rolled out the limits you mention only recently.

We are using Glitch.com on our beta site and would be using them for foreseeable future, replacing both the need for C9.io and Heroku.

**Comment by QuincyLarson** [comment]
@wewark I recommend you use Glitch.com instead of Heroku. We are moving to Glitch.com for these challenges with our beta curriculum, but haven't yet updated backup/master's backend challenges to recommend it. Would you be interested in helping us do so? I've created the issue here: https://github.com/freeCodeCamp/freeCodeCamp/issues/15044
