### ISSUE TITLE
Probleme on "make instances of ..." javascript

### ISSUE THREAD

**Issue by Andre-Sonkeng** [freeCodeCamp/freeCodeCamp#14964]
Challenge [Make Instances of Objects with a Constructor Function](https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%205%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%3Dnew%20Car()%3B%0AmyCar.turboTye%20%3D%20%22145%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The "make instances of object with a constructor function" challenge isn't accepting to validate my code meanwhile i'm sure it's correctly written.
My code:
```javascript

var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 5;
};

// Only change code below this line.

var myCar=new Car();
myCar.turboTye = "145";
```

**Comment by AL2016** [comment]
@Andre-Sonkeng the myCar instance needs to have a nickname property, not a turboType property.
So myCar.nickname = "145"; fixes your problem.
Also FCC has a chat room for help regarding these type of problems. [https://gitter.im/FreeCodeCamp/Help](url)

**Comment by donica376** [comment]
I read the instructions with the same understanding as Andre-Sonkeng.  The instructions are a little ambiguous- "nickname" is written the same exact way "constructor" and "instance" are written. Easy to misunderstand.

It would be helpful if the color-coding was extended so that terms/jargon don't read the same as the verbiage we're supposed to use in the editor.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
