### ISSUE TITLE
[UX][UI][Enhancement] Adding a horizontal line to separate the challenge from explanation/example

### ISSUE THREAD

**Issue by AL2016** [freeCodeCamp/freeCodeCamp#14973]
#### Challenge Name

[Challenge](https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%205%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%3Dnew%20Car()%3B%0AmyCar.turboTye%20%3D%20%22145%22%3B)

**Suggestion**
In this [post](https://github.com/freeCodeCamp/freeCodeCamp/issues/14964). The user(@Andre-Sonkeng) missed the challenge outlined in the last two lines. And another user(@donica376) found the instructions ambiguous as well, and suggested using different colors. Even in my experience I have gotten lost in large block of instruction texts regarding what the challenge actually was. While going through the beta version of FCC, I saw an [example](http://beta.freecodecamp.com/en/challenges/basic-data-structures/use-an-array-to-store-a-collection-of-data) where the challenge and explanation/example was separated by a horizontal line(screenshot below). I thought it looked very neat and easy to understand. So I'm suggesting if it's possible to add a horizontal line separating the challenge and explanation/example in the challenge listed above. I think this could help with better readability and user experience. Thanks. 

![example](https://cloud.githubusercontent.com/assets/16605693/26281628/38f0c7cc-3dcb-11e7-833f-009b3054bcc7.png)

**Comment by no-stack-dub-sack** [comment]
Hi @AL2016, thanks for reporting this. For now, we will not be making these kinds of changes to the production version of freeCodeCamp, however, this will be the new standard in beta moving forward. When the new curriculum is shipped to production, most challenges should be organized like this. Though it is a lot of new content so there is no guarantee that this will be the case right off the bat. We will be working towards the goal of making everything as consistent as possible. 

For now, I am closing this issue since this isn't an actual bug. Be aware, though, your suggestion has been noted and we appreciate the input!
