### ISSUE TITLE
Passing this challenge is very tricky - this can cause confusion

### ISSUE THREAD

**Issue by owususamuel** [freeCodeCamp/freeCodeCamp#15012]
Challenge [create-a-more-complex-shape-using-css-and-html](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-more-complex-shape-using-css-and-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
.heart {
  position: absolute;
  margin: auto;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: pink;
  height: 50px;
  width: 50px;
  transform: rotate(-45deg);
}
.heart:after {
  background-color: pink;
  content: "";
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: 0px;
  left: 25px;
}
.heart:before {
  content: "";  // when you add any extra space outside the empty string will not pass this challenge
  background-color: pink;
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: -25px;
  left: 0px;
}
</style>
<div class = "heart"></div>

```

**content: "";  // when you addany extra space outside the empty string will not pass this challenge. Can't you add any whitespace?**

**Comment by jodylecompte** [comment]
I believe this is by intention, rather than being a bug. 

You can, but you would do so using a few different means such as margin, padding, or positioning depending on the situation and what you are trying to accomplish. The content attribute of the :before and :after attributes would not interpret arbitrary white space in the way I believe you are asking.

**Comment by ahmadabdolsaheb** [comment]
@owususamuel I see what you mean, the tests are too strict. I could fix this a moderator approves that tests need to be changed. @BerkeleyTrue

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb @owususamuel We just launched the new curriculum and learning platform. Please take a look at it: learn.freecodecamp.org

Do you still think this challenge is confusing or overly hard? If so, we would welcome improvements to this challenge.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson I look into the tests tomorrow.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb You're the man. Thanks! Please keep us posted 👍

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, I will prepared this and a couple of others for first timers. If the issue is not taken in a couple of days, I will come back and fix them. Let me know if you want me to fix them immediately

The location of the test that needs to be changed:
https://github.com/freeCodeCamp/freeCodeCamp/blob/6d7092928e852755fa0d4d9489b3c8748b466a94/seed/challenges/01-responsive-web-design/applied-visual-design.json#L2483

the new line should be           
 "testString": "assert(code.match(/\\.heart:before\\s*?{[\\s\\S]*content:\\s*?\\"\\"\\s*?;/gi), 'The <code>content</code> of the <code>heart:before</code> selector should be an empty string.');"

**Comment by ahmadabdolsaheb** [comment]
FYI @QuincyLarson, on the issues page it encourages fist timers to search for the "good first issue" label which does not exist. It should say "first timers welcome"
![screen shot 2018-06-04 at 17 13 42](https://user-images.githubusercontent.com/4591597/40922527-176eadaa-681b-11e8-940b-76154e42843d.png)

**Comment by prateek3255** [comment]
Does the issue still exist if not then I would like to work on it?

**Comment by ahmadabdolsaheb** [comment]
@prateek3255 sorry for the late response. Yes it is open.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb could you link me to the page where you're seeing this? 

![](https://user-images.githubusercontent.com/4591597/40922527-176eadaa-681b-11e8-940b-76154e42843d.png)

Then I can update it.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, https://github.com/freeCodeCamp/freeCodeCamp/issues
It is on the issues page when I sign in with my moderator account.

**Comment by prateek3255** [comment]
@ahmadabdolsaheb please review my PR #17571 regarding this issue.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb OK - thanks for letting me know - I still can't see it for some reason so you would be a better person to QA this.
