### ISSUE TITLE
The My code is correct and does not pass.

### ISSUE THREAD

**Issue by senseoki** [freeCodeCamp/freeCodeCamp#15021]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%20%20return%20val%20%3E%205%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val > 5;
});

```

**Comment by erictleung** [comment]
@senseoki sorry, but your code is incorrect based on what is asked.

> Use `filter` to create a new array with all the values from `oldArray` **which are less than 6**. The `oldArray` should not change.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
