### ISSUE TITLE
The test criteria is wrong.

### ISSUE THREAD

**Issue by fqf2009** [freeCodeCamp/freeCodeCamp#15020]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20var%20a%20%3D%20arr%5B0%5D%2C%20b%20%3D%20arr%5B1%5D%3B%0A%20%20while%20(a%20!%3D%20b)%7B%0A%20%20%20%20if(a%20%3C%20b)%7B%0A%20%20%20%20%20%20a%20%2B%3D%20Math.ceil((b%20-%20a)%20%2F%20arr%5B0%5D)%20*%20arr%5B0%5D%3B%0A%20%20%20%20%7D%20else%7B%0A%20%20%20%20%20%20b%20%2B%3D%20Math.ceil((a%20-%20b)%20%2F%20arr%5B1%5D)%20*%20arr%5B1%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20a%3B%0A%7D%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0AsmallestCommons(%5B4%2C5%5D)%3B%0AsmallestCommons(%5B12%2C9%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
  var a = arr[0], b = arr[1];
  while (a != b){
    if(a < b){
      a += Math.ceil((b - a) / arr[0]) * arr[0];
    } else{
      b += Math.ceil((a - b) / arr[1]) * arr[1];
    }
  }
  return a;
}

smallestCommons([1,5]);
smallestCommons([4,5]);
smallestCommons([12,9]);

```
Below is the test criteria which causes my code to fail:
smallestCommons([1, 5]) should return a number.
smallestCommons([1, 5]) should return 60.
smallestCommons([5, 1]) should return 60.
smallestCommons([1, 13]) should return 360360.
smallestCommons([23, 18]) should return 6056820.

**Comment by erictleung** [comment]
@fqf2009 the challenge is a little more nuanced than what the challenge name suggests.

> Find the smallest common multiple of the provided parameters that can be evenly divided by both, **as well as by all sequential numbers in the range between these parameters**.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
