### ISSUE TITLE
Help with Tribute page

### ISSUE THREAD

**Issue by lmsutter** [freeCodeCamp/freeCodeCamp#15025]
#### Challenge Name

Build a Tribute Page

#### Issue Description

I am trying to correctly size the image in the document without resorting to defining pixel sizes so that it adjusts to whatever screen it's on. When I do this using object-fit, the card element that the image element is placed in has a lot of white space on the top and the bottom (I'm guessing it somehow fills the space in where the image would be if I didn't have image-fit:contain")

How do I have the image in the correct aspect ratio, but also have the card that it is nested in take up a normal amount of space that is the size of the image.  

Thank you!

I am just getting into coding and there is some probably easy solution!

#### Browser Information

Chrome, 58, Windows 10, Laptop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

<div class="container-fluid">
  <div class="row">
    <div class="col-md-1">
    </div>    
    <div class="col-md-10">
      <div class="card" style="background-color:#f2efde;">
        <h1 class="text-center" style="padding-top: 20px"> NT Wright </h1>
       
      
        <div class="card" style="margin:20px; height:auto; ">
        <img style="margin: 5px; Object-fit:contain" 
        src="https://juicyecumenism.com/wp-content/uploads/NT-Wright-Full-BW.jpg"><code>img-responsive</code>
        </div>
      
      
      <div class="text-center">
        <h4> Interesting Facts</h4>
      </div>
        <div class="col-md-6" style="margin:20px 100px 20px 100px">
          
        <ul>
          <li>Is bald</li>
          <li>Look at that smolder</li>
        </ul>
        </div>      
      </div>
  </div> 
    <div class="col-md-2">
         </div>
    </div>
    </div>


```

**Comment by erictleung** [comment]
@lmsutter Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
