### ISSUE TITLE
Add 'Cmd + Enter' or 'Ctrl + Enter' support for Mac OSX on Safari for FreeCodeCamp

### ISSUE THREAD

**Issue by iamutkarshtiwari** [freeCodeCamp/freeCodeCamp#15027]
#### Challenge Name
All challenges

#### Issue Description
There is no support for ```Command + Enter``` or ```Ctrl + Enter``` for Mac OSX in challenges to Run and move to next challenge.

#### Browser Information

* Safari, 10.0: 
* Mac OS X (Sierra): 
* Desktop:

**Comment by faraco** [comment]
Hi @iamutkarshtiwari,

This lacking may be annoying to you(apparently).

I don't use Mac, but so far, I found this that could be a workaround to this issue - https://discussions.apple.com/message/29420056#message29420056. Please give this a try?

**Comment by iamutkarshtiwari** [comment]
@faraco Thanks for the suggestions. Unfortunately, that solution doesn't work :(

**Comment by BerkeleyTrue** [comment]
ctrl + enter works fine for me. I believe the ctrl key is part of the spec and not specific to an environment.

**Comment by raisedadead** [comment]
Cannot reproduce as well. Yup, I do believe that we could update the label on the Run test button to be consistent to OS, i.e. <kbd>Ctrl</kbd> + <kbd>Enter</kbd> on non-macOS and <kbd>Cmd</kbd> + <kbd>Enter</kbd> on macOS

**Comment by raisedadead** [comment]
@iamutkarshtiwari Please revert if this is still an issue.

**Comment by edmechem** [comment]
> Cannot reproduce as well. Yup, I do believe that we could update the label on the Run test button to be consistent to OS, i.e. Ctrl + Enter on non-macOS and Cmd + Enter on macOS

After puzzling & trying different browsers (Firefox, Brave, Chrome) & searching and finding various forum posts & Github commit comments, I eventually found this – and came here to echo this.

The keyboard shortcut description on the `Check Your Code ` button should be platform specific.
It currently isn't – and is thus frustratingly incorrect, on Macs.

It should stay the same, i.e. `Check Your Code (Ctrl + Enter)` on Windows (and presumably Linux), because... this is true, that's the key combo that clicks that button.

But on Macs, it should read: `Check Your Code (Cmd + Enter)` – because... it's not Ctrl-Enter on Mac, it's Cmd-Enter (or, Cmd-Return).
