### ISSUE TITLE
Issue with Make a Person

### ISSUE THREAD

**Issue by znicholasbrown** [freeCodeCamp/freeCodeCamp#15033]
Make A Person
https://www.freecodecamp.com/challenges/make-a-person

Issue Description:

> bob.getFullName() should return "Haskell Curry" after bob.setLastName("Curry").

This requirement to complete the challenge is wrong. Since the object in the challenge is created using 'Bob Ross', the `firstName` is initially set to 'Bob', and the `lastName` is initially set to 'Ross'. Therefore calling `bob.setLastName("Curry")`, with no previous callings on `setFirstName` or `setFullName` which included 'Haskell', would only change the `lastName` property and not the  `firstName` property. 

The only way to address this problem and pass the challenge is to attach 'Haskell' to the `lastName` 'Curry'. My code snippet below does so and passes the challenge, but tailoring the code to fit that particular userstory doesn't seem in the spirit of the challenge. 

Browser Information:

* Browser: Google Chrome v58.0.3
* Operating System: Windows 10 Home (64-bit)

Code: 

```js
  this.getFullName = function () {
    if (!this.fullName) {
      this.setFullName(firstAndLast);
    }
    if (this.lastName == "Curry") {
      this.setFirstName("Haskell");
    }
    return this.fullName;
  };

  this.setFullName = function(firstAndLast) {
    var split = firstAndLast.split(" ");
    this.setFirstName(split[0]);
    this.setLastName(split[1]);
    this.fullName = this.firstName + " " + this.lastName;
  };
  this.setFirstName = function(first) {
    this.firstName = first;
    this.fullName = this.firstName + " " + this.lastName;
  };
  this.setLastName = function(last) {
    this.lastName = last;
    this.fullName = this.firstName + " " + this.lastName;
  };
  this.getFirstName = function () {
    if (!this.firstName) {
      this.setFullName(firstAndLast);
    }
    return this.firstName;
  };
  this.getLastName = function () {
    if (!this.lastName) {
      this.setFullName(firstAndLast);
    }
    return this.lastName;
  };

```
Screenshot: 
![fcc - make a person challenge](https://cloud.githubusercontent.com/assets/27291717/26416548/3f679fca-4084-11e7-874f-4ac1f9c3c2e9.PNG)

Hopefully I'm not crazy and missing something!

**Comment by MiloATH** [comment]
Could you please give all the code in your editor.  I don't know how you got `Object.keys(bob).length` to be 6. It should be 9 since you assign variables using the `this` keyword. As for the test cases, they are all achievable with the correct code. No special cases needed. You can see [someone else's answer here](https://www.freecodecamp.com/challenges/make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20%2F%2F%20Properties%0A%20%20var%20first_name%20%3D%20(firstAndLast.split(%27%20%27))%5B0%5D%3B%0A%20%20var%20last_name%20%3D%20(firstAndLast.split(%27%20%27))%5B1%5D%3B%0A%0A%20%20%2F%2F%20Getters%0A%20%20this.getFullName%20%3D%20function()%7B%0A%20%20%20%20return%20(first_name%2B%27%20%27%2Blast_name)%3B%0A%20%20%7D%3B%0A%20%20this.getLastName%20%3D%20function()%7B%0A%20%20%20%20return%20last_name%3B%0A%20%20%7D%3B%0A%20%20this.getFirstName%20%3D%20function()%7B%0A%20%20%20%20return%20first_name%3B%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Setters%0A%20%20this.setFirstName%20%3D%20function(name)%7B%0A%20%20%20%20first_name%20%3D%20name%3B%0A%20%20%7D%3B%0A%20%20this.setLastName%20%3D%20function(surname)%7B%0A%20%20%20%20last_name%20%3D%20surname%3B%0A%20%20%7D%3B%0A%20%20this.setFullName%20%3D%20function(firstAndLast)%7B%0A%20%20%20%20first_name%20%3D%20(firstAndLast.split(%27%20%27))%5B0%5D%3B%0A%20%20%20%20last_name%20%3D%20(firstAndLast.split(%27%20%27))%5B1%5D%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person(%27Bob%20Ross%27)%3B%0Abob.getFullName()%3B%0A) if you want.

**Comment by raisedadead** [comment]
Hi @znicholasbrown 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by raisedadead** [comment]
@znicholasbrown please revert if you are still stuck with this.
