### ISSUE TITLE
Anyone did solve this issue and figure it out? How this challenge work? Please help!

### ISSUE THREAD

**Issue by rabinrai44** [freeCodeCamp/freeCodeCamp#15045]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by jonathanihm** [comment]
Hi,

Please use the forums or chatroom for help!

https://forum.freecodecamp.com/t/how-to-report-a-bug/19543

Cheers!

**Comment by texas2010** [comment]
@rabinrai44 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by rabinrai44** [comment]
Okay. I got that solution. Thank you for reply 👍
