### ISSUE TITLE
Unable to set border width and style from CSS block

### ISSUE THREAD

**Issue by yoss** [freeCodeCamp/freeCodeCamp#15106]
#### Challenge Name

https://www.freecodecamp.com/challenges/add-borders-around-your-elements

#### Issue Description

Even though I provided correct css code for border width and style in the challenge the tests and preview did indicate incorrect solution.

Correct code was marked as 'unknown property name' in google chrome

#### Browser Information

Browser 1: Microsoft Edge 40.15063.0.0
Browser 2: Google Chrome 58.0.3029.110
OS: windows 10 pro 

#### Your Code

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
    .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px;
  }
  
  .thick-green-border{
    border-width: 10px;
    border-color: green;
    border-style: solid;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border"  src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
#### Screenshot

![przechwytywanie](https://cloud.githubusercontent.com/assets/1525820/26532713/6850d14e-4409-11e7-94ca-e456367afb12.JPG)

![border](https://cloud.githubusercontent.com/assets/1525820/26532724/982a8af4-4409-11e7-966e-2796b3ee9c35.JPG)

#### Workaround
I managed to continue with the task by providing css properties inline, not in block as was intened in the challenge.
```html
<img class="smaller-image thick-green-border" style="border: 10px solid green " src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
```

**Comment by GuptaPalki** [comment]
This problem is coming because you have written border-width first instead of border-style . so please do try this method .

**Comment by yoss** [comment]
@GuptaPalki I have never heard that order of style properties influence whether border is displayed or not.

Even the freeCodeCamp instructions suggest writing border-width before border-style:
```css

  .thin-red-border {
    border-color: red;
    border-width: 5px;
    border-style: solid;
  }
```

What is more, I've changed the order as you suggested, and it still do not work - see attachment. 
![przechwytywanie2](https://cloud.githubusercontent.com/assets/1525820/26546120/a84af8a6-4468-11e7-830d-c8eb8f6fd43b.JPG)

**Comment by mrbaker1917** [comment]
Do you have a class = "thin-red-border" in the html tag? I do not see one.

**Comment by yoss** [comment]
@mrbaker1917 I have class "thick-green-border" in ing tag, and .thick-green-border in style tag.

```html
<style>
 .thick-green-border{
    border-width: 10px;
    border-color: green;
    border-style: solid;
  }
</style>
<img class="smaller-image thick-green-border"  src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
```
.thin-red-border is an example provided by freeCodeCamp. I've mentioned it because @GuptaPalki suggested that the order of my css properties might be incorrect.

**Comment by mrbaker1917** [comment]
I am using chrome on a windows 7 pc, and this CSS works fine:
.thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }

**Comment by rjkmurray** [comment]
All from Android and window 


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: "Mark R. Baker" <notifications@github.com> Date: 2017-05-29  8:14 AM  (GMT-03:30) To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [freeCodeCamp/freeCodeCamp] Unable to set border width and style from CSS block (#15106) 
I am using chrome on a windows 7 pc, and this CSS works fine:

.thick-green-border {

border-color: green;

border-width: 10px;

border-style: solid;

}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrbaker1917 in #15106: I am using chrome on a windows 7 pc, and this CSS works fine:\r\n.thick-green-border {\r\n    border-color: green;\r\n    border-width: 10px;\r\n    border-style: solid;\r\n  }"}],"action":{"name":"View Issue","url":"https://github.com/freeCodeCamp/freeCodeCamp/issues/15106#issuecomment-304631749"}}}

**Comment by rjkmurray** [comment]
Good job,  but I just likes the look, but it is hard to mixs functionality with looking different 


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: yossarian <notifications@github.com> Date: 2017-05-29  7:50 AM  (GMT-03:30) To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [freeCodeCamp/freeCodeCamp] Unable to set border width and style from CSS block (#15106) 
@GuptaPalki I have never heard that order of style properties influence whether border is displayed or not.
Even the freeCodeCamp instructions suggest writing border-width before border-style:
  .thin-red-border {
    border-color: red;
    border-width: 5px;
    border-style: solid;
  }
What is more, I've changed the order as you suggested, and it still do not work - see attachment.



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yoss in #15106: @GuptaPalki I have never heard that order of style properties influence whether border is displayed or not.\r\n\r\nEven the freeCodeCamp instructions suggest writing border-width before border-style:\r\n```css\r\n\r\n  .thin-red-border {\r\n    border-color: red;\r\n    border-width: 5px;\r\n    border-style: solid;\r\n  }\r\n```\r\n\r\nWhat is more, I've changed the order as you suggested, and it still do not work - see attachment. \r\n![przechwytywanie2](https://cloud.githubusercontent.com/assets/1525820/26546120/a84af8a6-4468-11e7-830d-c8eb8f6fd43b.JPG)\r\n "}],"action":{"name":"View Issue","url":"https://github.com/freeCodeCamp/freeCodeCamp/issues/15106#issuecomment-304627305"}}}

**Comment by yoss** [comment]
I'm using Win 10 pro and MS Edge and Google Chrome.

Google is a vanilla version (no extensions) and it still produces incorrect results, see attached:
![przechwytywanie3](https://cloud.githubusercontent.com/assets/1525820/26547239/50c03b18-446e-11e7-83b3-9982731e6171.JPG)
For me it looks like there is some other CSS code somewhere within freeCodeCamp that overrides code from the challenge editor. 

I can insert correct CSS properties inline and it works:

```html
<img class="smaller-image" style="border: 10px solid green " src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
```

**Comment by xRahul** [comment]
I am using Ubuntu 14.04 and Chrome 58. I haven't seen this issue yet. I have tried both orderings

**Comment by yoss** [comment]
@GuptaPalki I've recreated this exercise in plain html and it worked as expected. - attachment 1
![przechwytywanie4](https://cloud.githubusercontent.com/assets/1525820/26549856/52021fc0-447b-11e7-9e17-06b21c9acd91.JPG)
 
But it still do not work on freeCodeCamp, so I presume there is some CSS code here that overrides CSS from exercise - attachment 2
![przechwytywanie3](https://cloud.githubusercontent.com/assets/1525820/26549929/b2dbdbb0-447b-11e7-87b7-c3c80e78fdcb.JPG)

**Comment by yoss** [comment]
What is even more interesting, Chrome has no problem with borders style provided by next and later exercises -attachment of the next challenge
![przechwytywanie5](https://cloud.githubusercontent.com/assets/1525820/26559500/5abe1a6c-44b0-11e7-9986-a0aff58c94e2.JPG)

**Comment by DivaWeb** [comment]
I am having the same issue. I would think that it has something to do with the test itself. I don't understand why border: 10px solid green won't just work as well.

**Comment by DivaWeb** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .thick-green-border{
    border-width: 10px;
    border-color: green;
    border-style: solid;
    
    
  }
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img class="smaller-image" class ="thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

**Comment by texas2010** [comment]
@DivaWeb you need to go chat room for ask help. I could see your code is incorrect.  sorry about that.
