### ISSUE TITLE
Pressing Ctrl + Z on a challenge takes you back to the last challenge's code

### ISSUE THREAD

**Issue by ApCoder123** [freeCodeCamp/freeCodeCamp#15100]
Challenge [catch-misspelled-variable-and-function-names](http://beta.freecodecamp.com/en/challenges/debugging/catch-misspelled-variable-and-function-names) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>

Please describe how to reproduce this issue, and include links to screenshots if possible.

Once you change the code of a challenge, if you press `Ctrl + Z` too many times it will bring back the code from the last challenge. This is only an issue on beta as it doesn't do that on the live FreeCodeCamp. 

I pressed `Ctrl + Z` twice to change my edits to that challenge's code, but upon `Ctrl + Z` the third time it brings the previous challenge's code back

![fccbetaerror](https://cloud.githubusercontent.com/assets/20560218/26530675/74b18d12-43d1-11e7-973c-1ed40d17393d.gif)

**Comment by xRahul** [comment]
I'm assuming this is happening because the textarea isn't getting refreshed after each challenge and the code is getting changed. Is there any wiki on how the project is structured?
Also, to fix this, we would have to destroy and recreate a new textarea after each submission. Let's discuss if there are any alternatives.

**Comment by raisedadead** [comment]
This is now fixed. 

Happy coding!
