### ISSUE TITLE
challenge 27 bug

### ISSUE THREAD

**Issue by DriftingPandaa** [freeCodeCamp/freeCodeCamp#15146]
https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements
![screenshot 2017-05-31 at 4 36 42 pm](https://cloud.githubusercontent.com/assets/29084032/26658984/5761ee8e-4622-11e7-8488-a48a7ad85020.png)
it is saying that i still need an a element to link the catphotoapp.com 
pretty sure i have the right code 
any help will be appreciated thank u!

**Comment by erictleung** [comment]
@DriftingPandaa Thank you for reporting this issue. You're almost there. Please look at the link you've inserted more carefully to make sure you have the write link.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
