### ISSUE TITLE
each test working fine,  but it wont let me pass

### ISSUE THREAD

**Issue by Mohamed-fawzy7** [freeCodeCamp/freeCodeCamp#15154]
https://www.freecodecamp.com/challenges/symmetric-difference

#### Challenge Name
when i call each test alone it works fine and it passes the only test i called but others wont work althought they work when i call them
code
```js
var arr = [];
function sym(args) {
	if (arr[0] === undefined){arr = Array.prototype.slice.call(arguments);}else{arr = arr;}
	// arr = arr || Array.prototype.slice.call(arguments);
	if (arr.length == 1){console.log("a");console.log(arr[0].sort());return arr[0].sort();}
	console.log(arr);
	newArr = [];
	for (i = 0; i < arr[0].length; i++){
		if (!(arr[1].indexOf(arr[0][i]) > -1)){newArr.push(arr[0][i]);}
	}
	// console.log(newArr);
	for (i = 0; i < arr[1].length; i++){
		if (!(arr[0].indexOf(arr[1][i]) > -1)){newArr.push(arr[1][i]);}
	}
	// console.log(newArr);
	for (i = newArr.length - 1; i >= 0; i--){
		if (newArr.indexOf(newArr[i]) != i){newArr.splice(i,1);}
	}
	console.log(newArr);
	arr = [newArr].concat(arr.slice(2));
	for (i = 0; i < arr.length; i++){
		if (Array.isArray(arr[i])){
			break;
		}else {console.log('a');return arr;}
	}
	return sym(arr);
}

sym([1, 2, 3], [5, 2, 1, 4]);
```

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet:

**Comment by raisedadead** [comment]
Hi @Mohamed-fawzy7 

You are using global variables in the code, please refactor the code to have a solution without using them.

Our test infra on the main website does not support globals because the tests are run concurrently on the same code.

We are planning to check this in the beta, I believe.
You can refer to the articles on the wiki in our forum if you need hints on how to do so.

Happy coding!

**Comment by raisedadead** [comment]
Closing with the earlier comments, please feel free to continue though.
