### ISSUE TITLE
[beta] Tribute page doesn't include User Stories

### ISSUE THREAD

**Issue by Staxed** [freeCodeCamp/freeCodeCamp#15178]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page

#### Issue Description

On opening the page
There are no criteria/user stories listed on the challenge page.  Required user stories need to be listed.

~~Also, the youtube video does not play, link may be incorrect?~~

#### Screenshot

**Edit by mod:**
The youtube videos are getting replaced by images.
Refer #15187

**Comment by PedroCSilva** [comment]
I'm getting the USs but the link does seem broken. What's your browser?

**Comment by raisedadead** [comment]
We are removing the youtube videos and have planned a separate section on video tutorials. 
Refer https://github.com/freeCodeCamp/freeCodeCamp/issues/12753

Please search for issues (including closed) while reporting.

**Comment by Ellyria** [comment]
The video is still present in the http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page page, and clicking on it causes an error.

Also, the instructions say: **"Fulfill the user stories by getting all of the tests to pass."** There are no user stories in the instructions, and there's no immediate mention of them at the [working example](http://codepen.io/freeCodeCamp/full/zNqgVx) link. If the visitor visits the the [working example](http://codepen.io/freeCodeCamp/full/zNqgVx) page, clicks the **OK** button on the alert that automatically loads, then clicks the **Run tests** button, then clicks the **Tests n/n** button, then looks in the **Unit tests** results that are displayed, they will see what's being tested for. The visitor might not do that, though.

**Comment by raisedadead** [comment]
@Ellyria thanks for pointing out. My apologies in closing this pre-mature.

**Comment by Ellyria** [comment]
Any time. I would have reopened it, but I couldn't see an obvious way to do so, and asking in the **Contributors** channel didn't get any responses (it's the weekend, after all). Is that something us ordinary users can do, or do you need special power to do that?

**Comment by padulam** [comment]
@raisedadead None of the projects in beta have user stories located on the page. #14258 references a similar issue. Are you proposing to add them for all of the other projects? If so, I can help with this effort.

**Comment by no-stack-dub-sack** [comment]
@Staxed @raisedadead @Ellyria @padulam when @QuincyLarson and I were brainstorming about the best way to present these new projects, it was a deliberate choice to leave the user stories off of the challenge page itself. Though I can't quite remember why we felt that was the best move at the time - @QuincyLarson do you happen to remember?

I believe the idea was to get the user to click the link and explore the test suite. As @Ellyria mentioned, when you click the "working example" link, and run the test suite, you can see the unit tests by hitting the "tests" button. 

I don't think it would be such a bad idea to add them though, but curious to hear @QuincyLarson's opinion before we ask anyone to do so since there may have been some other reason to leave them off. 

For the time being, I can go ahead and edit the boilerplate pen so that instructions for seeing the test cases are more obvious. However, these projects are about resourcefulness in some ways, so while it shouldn't be _too_ difficult, a bit of digging around and figuring something out can't hurt! 😄 

Another option I can look into is that when you follow the link to the working example, we can perhaps arrange for the unit test modal to already be open.

**Comment by Ellyria** [comment]
Thanks for the detailed reply, @no-stack-dub-sack. I'm sure the plans you and @QuincyLarson have will be wonderful. It already looks quite exciting with freeCodeCamp hosting our pages(!) and with the ability to test code that's anywhere(!).

Now, as to these projects, leaving user stories off of the instructions should be handled elegantly. It would be fine if you didn't test for them, but since you do, the user should be told that in some way in advance.

In the challenges, there are instructions, examples, and sometimes links on the left. The user has a clear idea of what's expected of him or her.

I understand that you'd like to see the users be resourceful when it comes to the projects, but that might be better handled by holding a discussion (some sort of break between challenges and projects) in which you let it be known that exploration and resourcefulness will be required to not only complete projects, but to figure them out to begin with. That way, at least, the user has some idea of what's coming and what will be expected of them.

My two cents.

**Comment by no-stack-dub-sack** [comment]
I have added the following instructions to the boilerplate pen to help this along: 
![image](https://cloud.githubusercontent.com/assets/18563015/26799389/6e07496a-4a03-11e7-8087-6d2f0e645033.png)

**Comment by no-stack-dub-sack** [comment]
@Ellyria I think this could probably be solved by just adding one-size-fits-all instructions to the page that say something like:
> To view the test cases that you must fulfill, one you have loaded the test suite into your preferred environment, select the project from the dropdown menu, then click "Run Tests" to run the tests against your blank project, then click the "tests" button to view your test cases. **Remember, that it is ideal for you to build the projects with the test cases in mind, rather than to build the project first and then retrofit it to pass the tests. 

Or, an intro section to the projects with a feature video showing how to use the test suite. One or the other should hopefully suffice, and still allow us to keep the user stories themselves off the page (because in some cases there are quite a few, and this would get quite messy).

**Comment by raisedadead** [comment]
Hi @no-stack-dub-sack I believe that if we are asking the users run a test suite to view test cases, which theoretically are the user stories, then that defeats the whole point of abstraction.

IMHO, we should expect this to be more annoying to the users.

That said, I would suggest, we create a better UX by changing the workflow of the project challenges like so:

Step 1 : Show users a working example. This would be better implemented as an codepen embed without the test suite on the challenge page.
Step 2 : Click on some next button on the challenge to reveal some expected test cases.
Step 3 : Ask user to the setup and create the project as you suggested already, a video or GIF would be great too.
Step 4 : Evaluation.

**Comment by no-stack-dub-sack** [comment]
@raisedadead this sounds good to me! makes sense and would certainly be an improvement. 

However, before we ask someone to invest a significant amount of time into making this happen (or before I take it on myself) I think there is one other important piece to cover. That is, the test suites themselves. Our goal when making these, was for the test suites to be as "implementation agnostic" as possible. BUT, now that they have been out there for a while, issues are continuing to get opened on the [testable-projects-fcc](https://github.com/freeCodeCamp/testable-projects-fcc) repo which show that this goal was not attained too well. The projects are best and most easily solved with vanilla JS and React, as that's how most of the examples were built, but as people start to attempt them with more obscure libraries (and even less obscure ones like Vue), or start to incorporate css libraries that achieve things like making a navbar fixed with just a class name, we are seeing that the test cases are not always passable even when the requirements are met. 

Here's a perfect example: https://github.com/freeCodeCamp/testable-projects-fcc/issues/99 
This camper built a working project that fulfills every test case, but since a scrolling library was used, one of the unit tests fails.

Another example: https://codepen.io/no_stack_dub_sack/pen/jmgoNv
I forked this one to preserve it. His CSS library prevents one of the test cases from passing.

I think overall they work fairly well, but that it is going to be next to impossible for the unit tests to cover every possible implementation of doing something. Possibly with a greater set of eyes on the test suite we could come up with better solutions, but as is, we'd be releasing a test suites that are not possible in many cases. So before putting and more time into them, I propose that we have a closer look at this and be sure that this is the direction we want to go in...

**Comment by Ellyria** [comment]
I like the new instructions in the boilerplate pen, @no-stack-dub-sack. I would change one thing, though. Before the "As you fulfill each test case..." section, there should probably be a mention that you can click the "TESTS" button as often as you like to check your coding progress. You hinted at that at the bottom, but it might go well a bit more solidly higher up as well.

I'll take your word for it on the messy page from lengthy user stories. I have yet to see one that looked bad, but I'm wordy by nature, so even the long ones look pretty to me, which makes me a bad judge of prettiness.

Also, in response to your mention of the use of libraries, I'm curious why the intent is to be as "implementation agnostic" as possible. I realize this probably isn't the place for such a discussion, but I've wondered from the beginning why vanilla JavaScript and vanilla CSS aren't insisted upon. Although the libraries can be fun and convenient, I'd think it would be most important for the user to understand the underlying languages that make them possible, thus making the user capable of writing libraries of their own if they like, or revelling in the fact that they don't even need one. In my opinion, the "I did it myself" feeling beats the "Bootstrap/jQuery/[insert library here] did it for me" feeling every time.

**Comment by no-stack-dub-sack** [comment]
@Elyria 
> Although the libraries can be fun and convenient, I'd think it would be most important for the user to understand the underlying languages that make them possible, thus making the user capable of writing libraries of their own if they like, or revelling in the fact that they don't even need one. In my opinion, the "I did it myself" feeling beats the "Bootstrap/jQuery/[insert library here] did it for me" feeling every time.

I couldn't agree with this sentiment more (although I do love me some React), however, with the sheer amount of campers that use FCC every day, especially considering most of them only ever get as far as the front end projects, we don't want to limit people in how they can or cannot do something. While this sentiment is great, it's also a tad idealistic. The fact is, people will often be relying on libraries, and if we try to tell them they can't use them, they likely won't be all that happy about it. Although, I think it actually may be the best approach in this case &mdash; i just don't know that it's one we'll be willing to consider.

**Comment by Ellyria** [comment]
It makes sense to learn the libraries in addition to vanilla CSS/JavaScript, since they're out there and we may need to be able to work with them if they're required for a job. I have yet to experience React, @no-stack-dub-sack, but I must confess to taking some guilty pleasure in playing around with Bootstrap. I don't take it seriously, though, and much prefer to code stuff myself.

I suppose there are three ways libraries can be addressed on freeCodeCamp:
* Leave them the way they are, with the user being left to decide which tools to use to complete a project.
* Leave them the way they are, but create a new site, just like freeCodeCamp, which only accepts vanilla code.
* Require one vanilla completion of each project, but offer the opportunity for additional completions with any preferred libraries.

**Comment by no-stack-dub-sack** [comment]
@Ellyria with where we are right now in the Beta curriculum, I would see this not even as being a point that's up for discussion. IMHO, Leaving things the way they are is really the only option, and the only one that I think Quincy would go for anyway.

My main concern is whether or not the testable projects will allow this of users and still work. Like you mentioned, this discussion's scope goes beyond this issue, however, they are closely related, and again, I think it is an important point to raise before additional work gets put into the testable projects.

**Comment by QuincyLarson** [comment]
We hope to replace these projects with our new in-browser multi-file editor. So campers can build the project right on freeCodeCamp. We will have simple instructions that basically tell them to get the project's tests - which will be loaded in - to pass.

I am closing this issue for now since we won't be listing user stories but rather have the tests and user stories present built into the challenge page.
