### ISSUE TITLE
I have a problem with nav bar 

### ISSUE THREAD

**Issue by AbdullahMuhammed5** [freeCodeCamp/freeCodeCamp#15191]
My nav bar doesn't work .. it shows like this 
![capture](https://cloud.githubusercontent.com/assets/29069500/26755109/0184ebc6-4887-11e7-8a07-bd124a1e6cd4.PNG)
I am including bootstrap

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by AbdullahMuhammed5** [comment]
Okay no problem, Thank you for commenting.
