### ISSUE TITLE
Tribute Page issues

### ISSUE THREAD

**Issue by bradk54** [freeCodeCamp/freeCodeCamp#15198]
I can't get the column system in bootstrap to work for the tribute page.  I can definitely take the example and modify it (lets say from .col-xs-12 to .col-xs-4) in chrome using the inspect feature.  But i can't get that to work in mine.  I've definitely loaded bootstrap in codepen

![screen shot 2017-06-03 at 8 13 58 pm](https://cloud.githubusercontent.com/assets/24926471/26757860/4483f6f8-4899-11e7-966c-1c5ff24914eb.png)

**Comment by texas2010** [comment]
@bradk54 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
