### ISSUE TITLE
I have a problem with nav bar

### ISSUE THREAD

**Issue by AbdullahMuhammed5** [freeCodeCamp/freeCodeCamp#15195]
My nav bar doesn't work .. it shows like this 
![capture](https://cloud.githubusercontent.com/assets/29069500/26755948/32dc3fd8-4898-11e7-822b-218d9d89e198.PNG)

And I don't know how to fix it, i tried a lot to copy and paste code from bootstrap site, but nothing changed it's still as you see it in that image .
I really want a help.

**Comment by texas2010** [comment]
@AbdullahMuhammed5 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
