### ISSUE TITLE
Not sure why it won't change to blue? css

### ISSUE THREAD

**Issue by Norma64** [freeCodeCamp/freeCodeCamp#15225]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Manish-Giri** [comment]
@Norma64 Thank you for reporting this issue. Your code is incorrect. Please use the Gitter chat rooms linked below for asking for help. GitHub issues are not for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

**Comment by maya813r** [comment]
Still having the same issue, please help.

**Comment by McBiggos** [comment]
You should only remove `style` attribute from `h2` tag - not whole `h2` tag

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by Norma64** [comment]
@Manish-Giri It doesn't do anything when I click the Help button.

**Comment by raisedadead** [comment]
Please visit the forum and post your query there:
https://forum.freecodecamp.com/

Happy coding! :smile: !
