### ISSUE TITLE
the part where you test you code doesn't work 

### ISSUE THREAD

**Issue by simekhakhatima** [freeCodeCamp/freeCodeCamp#15253]
in not able to get the test code function after on lesson 100. i tried skipping it but then the next section 
had the same issue i wasn't able to run that function eve though i wrote down the code correctly. Then i 
went back to the previous lessons and i didn't have any issue running the test your code function 

#### Challenge Name

Target HTML elements with selectors using JQuary

#### Issue Description

I'm not able to use the test the code function in order to move on to the next lesson and challenge

#### Browser Information

* Browser Name, Version:  Google chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

<script>
  $(document).ready(function() {
$("button").addclass("animated bounce"); 
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```js



```

**Comment by Margaret2** [comment]
Hi, you have a typo in your code - uppercase and lowercase matter in jQuery! If you need help fixing it, please ask in the [Help chat](https://gitter.im/freecodecamp/help).

**Comment by erictleung** [comment]
@simekhakhatima as @Margaret2 has pointed out, capitalization is important. 

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
