### ISSUE TITLE
CODE QUESTION #24

### ISSUE THREAD

**Issue by robo21** [freeCodeCamp/freeCodeCamp#15266]
CODE QUESTIONS # 24 is broken. I entered it exactly how the directions say but it says it's wrong. I'm using Google Chrome browser from my desktop it is the updated version.  Here is my work

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by erictleung** [comment]
@robo21 Thank you for reporting this issue. Please use the issue template when creating an issue. I'm assuming you're on challenge "Size Your Images". If so, your code is incorrect. 

> Create a class called `smaller-image` and **use it to resize the image** so that it's only 100 pixels wide.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
