### ISSUE TITLE
The splice function act differently compared to what says W3School

### ISSUE THREAD

**Issue by johnisgood** [freeCodeCamp/freeCodeCamp#15264]
Hi,
while on W3School, this code give this result :
var arr=[1,2,3]
arr.splice(0,2) ==>result : 3

On FCC, same code give the following output : [1,2]

**Comment by erictleung** [comment]
@johnisgood if you're talking about [this demo](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_splice), you need to assign the `fruits.splice(2, 0)` part to the variable again. Otherwise, it doesn't save the results and just returns the elements that were removed. Take a look at the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) resource and read the "Return value" section. Closing as not an issue with the site. 

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
