### ISSUE TITLE
I created  a CSS class called pink-text that gives an element the color pink.It doesnt complete the challenge though.what might be wrong with the code?

### ISSUE THREAD

**Issue by TonyNgeno** [freeCodeCamp/freeCodeCamp#15271]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%20%20.pink-text%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
    .pink-text{
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by Upioorny** [comment]
maybe close the body?

2017-06-09 8:50 GMT+02:00 TonyNgeno <notifications@github.com>:

**Comment by jamesjpk123** [comment]
Hi @TonyNgeno 

The issue tracker is for reporting bugs only. After looking at your issue, I concluded that this was a bug with your code, and not with freeCodeCamp. To request help, you can use the [help chat room](https://gitter.im/FreeCodeCamp/Help), or look to see if your issue is on [the forum](https://forum.freecodecamp.com/).

Because this is not an issue with freeCodeCamp, you can close the issue. For help in how to close the issue, see [this page](https://help.github.com/articles/closing-issues-via-commit-messages/).

Happy Coding.
jamesjpk

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
