### ISSUE TITLE
Scroll bar on right of code panel done not scroll

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/FreeCodeCamp#1531]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not sure why, but if I click on it and try to drag it, it gives a big circle/slash aka no with a smaller pic of the app window.. clicking the up/down arrows does nothing

**Comment by eabedrapo** [comment]
The same is occurring when attempting to scroll bar for the code area in http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work

Attached screenshot when trying to scroll down the code using the mouse to drag the scroll bar
![image](https://cloud.githubusercontent.com/assets/1670763/9295179/e0bbd988-443a-11e5-8b6b-cd198e052143.png)

**Comment by eabedrapo** [comment]
It's actually occurring in all waypoints because the iphone image overlaps the code area as shown in this screenshot below, but only noticeable for those in which the code area has a scrollbar as people  drag the transparent part of the image when trying to scroll down the code.

Steps:
1. Open any waypoint with scroll bar (like the URLs given above).
2. Open DevTools or similar to inspect the iphone image.
3. Hover over iphone img element in the HTML and the actual width displayed by DevTools.
4. Click on the code area's scrollbar and drag it to the bottom to scroll down the code area.

Results: the code area isn't scrolled down and the iphone image looks like is going to be dragged instead. But it is just because the image is overlapping the scroll bar.

Screenshot with DevTools:
![image](https://cloud.githubusercontent.com/assets/1670763/9309349/76e81620-44df-11e5-9495-97b44b11697f.png)

**Comment by BerkeleyTrue** [comment]
Closing as fixed. Please feel free to re-open if issue still persists.

**Comment by DarrenfJ** [comment]
Tested it just now on a waypoint. Seems to be working fine now.

Thanks!
