### ISSUE TITLE
Example Pen fails to load

### ISSUE THREAD

**Issue by mcolynuck** [freeCodeCamp/freeCodeCamp#15311]
Challenge [Show National Contiguity with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-national-contiguity-with-a-force-directed-graph) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The example Pen link opens a page with a black panel but no content, and Chrome generates the following error messages:

Failed to load resource: net::ERR_INSECURE_RESPONSE
www.cs.mun.ca/~h65ped/Public/country%20data%20for%20force%20directed%20graph/countries.json Failed to load resource: net::ERR_INSECURE_RESPONSE

**Comment by abkunal** [comment]
The error is shown because the pen is trying to load the json data over HTTP (Not Secure) source instead of HTTPS (Secure) source.
Codepen now allows to request data over HTTPS only so you can request the data from the following source [countries.json](https://gist.githubusercontent.com/abkunal/1d961844990ad50a28347c019ff4400f/raw/2d318fbe193850da01796ec899149d5d4685a2fa/countries.json).
Have fun!

**Comment by raisedadead** [comment]
Yes, @abkunal is correct. Please test with https.
