### ISSUE TITLE
Program States If/Else Statements are Still Present When They Are Not

### ISSUE THREAD

**Issue by ellsee** [freeCodeCamp/freeCodeCamp#15334]
![bugfreecodecamp](https://user-images.githubusercontent.com/29243623/27054579-0fe6ccbe-4f87-11e7-837f-23930d7879d0.PNG)
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line

  case: "bob" 
    answer = "Marley";
    break;
   case: (42) 
    answer = "The Answer";
    break;
   case: (1) 
    answer = "There is no #1";
    break;
   case: (99) 
    answer = "Missed me by this much!";
    break;
   case(7); 
    answer = "Ate Nine";
 
}  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);


```

**Comment by siseer11** [comment]
switch(val){
    case "bob":
       answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
  }


you are missing the start of the switch statement

**Comment by ellsee** [comment]
@siseer11 Yes, but it wasn't the switch statement that solved it. I had to add a curly brace outside of the editable text zone to prevent chaintoswitch(7); from being deeemed unreachable due to the command "return". This was still a glitch, and while the challenge was overall functional, I had to ignore a parameter to accomplish the task.

**Comment by raisedadead** [comment]
@ellsee thanks for the report. 

While your code is NOT correct, and your report that the test cases are reporting use of `else` statements even when they are not their is buggy, is an right argument.

but, from the screenshot that you posted:

![image](https://user-images.githubusercontent.com/1884376/27082691-6005423e-5063-11e7-8c1c-66e28fd41d6e.png)

There is a clear notification that the syntax is not valid. 

The test cases fail, because they fail to run the code in editor which is NOT right in the first place. Hence you should fix the code (check for errors in the console) and then consider the results that the tests say.

Closing, as at the moment this is the best way that we have to point errors.
