### ISSUE TITLE
checked and rechecked x5

### ISSUE THREAD

**Issue by kyleworldd** [freeCodeCamp/freeCodeCamp#15409]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1)
  {return "Hole-in-one";}
 
  else if (strokes <= (par-2))
  {return "Eagle";}
  
  else if (strokes == (par-1))
    {return "Birdie";}
    
  else if (strokes == par)
    {return "Par";}
  
  else if (strokes == (par+1))
    {return "Bogey";}

  else if (strokes == (par+2))
    {return "Double Bogey";}
  
  else if (strokes >= (par+3))
  {return "Go Home!";}
       
  // Only change code above this line
}

// Change these values to test
golfScore(4, 1);

```

**Comment by tommygebru** [comment]
@kyleworldd  have you tried sharing your work with the helpJavascript chatroom, for tips and guidance in solving this challenge - https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by erictleung** [comment]
@kyleworldd Thank you for reporting this issue. You're really close. Take a look at the comment above for some help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by kyleworldd** [comment]
thanks !
