### ISSUE TITLE
why  thiis code doesnt  work

### ISSUE THREAD

**Issue by a7n007** [freeCodeCamp/freeCodeCamp#15429]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
for(var i=0;i<4;i++){
  if(contacts[i].firstName==firstName&&contacts.hasOwnProperty(prop)==1)
    return i;
  else if(contacts[i].firstName!=firstName&&contacts.hasOwnProperty(prop)==1)
    return "No such contact";
  else if(contacts[i].firstName==firstName&&contacts.hasOwnProperty(prop)==0)
return "No such property"
    }
    // Only change code above this line
}

// Change these values to test your function
lookUpProfile("Bob", "number");

```

**Comment by erictleung** [comment]
@a7n007 Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
