### ISSUE TITLE
Will only pass if defined as a local variable, not a global variable.

### ISSUE THREAD

**Issue by jwong92** [freeCodeCamp/freeCodeCamp#15438]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var newNum = 1;
function factorialize(num) {
  for (var i=1; i<=num; i++) {
    newNum = newNum * i;
  }
  return newNum;
}

factorialize(10);
```

**Comment by nmdoliveira** [comment]
Only the first test passes with this code because the global variable is "dirtied" in between tests. `newNum` should be 1 in the beginning of each `factorialize` call, but since it's global, it will have the last factorial result in it instead of 1.

You can see what happens if you put
```
factorialize(2);
factorialize(3);
```
in the end.

The result will be 12, because `2! = 2`, which ends up as the initial value of `newNum` when `factorialize(3)` is run, producing `2 * 1 * 2 * 3 = 12` instead of `1 * 1 * 2 * 3 = 6` as result.

This is one of the dangers of using global variables: they might be changed outside of your scope (in this case, in the previous test) and change your results in unexpected ways.

So I don't think it's a bug in freeCodeCamp, and you can fix your code by making `newNum` local to `factorialize`, or by setting it to 1 inside `factorialize` instead of outside.

**Comment by nmdoliveira** [comment]
Only the first test passes with this code because the global variable is "dirtied" in between tests. newNum should be 1 in the beginning of each factorialize call, but since it's global, it will have the last factorial result in it instead of 1.

You can see what happens if you put

factorialize(2);
factorialize(3);
in the end.

The result will be 12, because 2! = 2, which ends up as the initial value of newNum when factorialize(3) is run, producing 2 * 1 * 2 * 3 = 12 instead of 1 * 1 * 2 * 3 = 6 as result.

This is one of the dangers of using global variables: they might be changed outside of your scope (in this case, in the previous test) and change your results in unexpected ways.

So I don't think it's a bug in freeCodeCamp, and you can fix your code by making newNum local to factorialize, or by setting it to 1 inside factorialize instead of outside.

**Comment by jwong92** [comment]
Thank you! you are absolutely right, I totally missed that.
