### ISSUE TITLE
Pass allowed with wonkey result, Add Font Awesome Icons to our Buttons(76)

### ISSUE THREAD

**Issue by just1witness** [freeCodeCamp/freeCodeCamp#15440]
This is just a PSA, since I can pass now.

On challenge 76  Add Font Awesome Icons to our Buttons, I created one thumbs up in the like button, with the word like beside it and couldn't pass. The screen shot below shows what was required to advance. As you can see, there are two thumbs up in the like button... weird. 

I just made this since I figured you would want to know.

#### Challenge Name
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons

#### Issue Description
On challenge 76  Add Font Awesome Icons to our Buttons, I created one thumbs up in the like button, with the word like beside it and couldn't pass. The screen shot below shows what was required to advance. As you can see, there are two thumbs up in the like button... weird. 

As I said, I originally had it set up so there was only one thumbs up in the like button, it seemed very correct, but it wouldn't register that there was a thumb in the button. 

#### Browser Information
Firefox

#### Your Code

      <button class="btn btn-block btn-primary fa fa-thumbs-up">
        <i class="fa" "fa-thumbs-up"></i>
           Like
      </button>

**JUST FOR REFERENCE** Here is what the code looked like to get just one thumbs-up. I know it's wonkey too,(too many parentheses) but it looks better in practice!! : D

The real issue is why did I pass with two thumbs up? (since I know I did something wrong, in retrospect I know it was adding "fa fa-thumbs-up" to both the first and second class...)

![screenshot_codecamp](https://user-images.githubusercontent.com/29514150/27286236-66de04ec-54cd-11e7-9877-5dd33114787d.png)

MORE INFO:

**Comment by nmdoliveira** [comment]
I believe the problem was that you added the Font Awesome classes to the `button` element. That **does** make the icon appear, but the challenge asks you to add those classes to the `i` element, not the `button`. If you add them only to the `i`, the tests should pass with only one icon appearing.

The reference code you showed does have too many quotes, and because of that, does not add the class `fa-thumbs-up` to the `i`, and that is why only one icon appears.

You kinda did something wrong adding the classes to both elements, but since you did add to the element that the challenge asked, I think it's right that your code passes the tests, even if it looks weird.

**Comment by just1witness** [comment]
Yeah, I figured all that eventually. I just created the report in case someone would want to create a contingency to address this very minor loophole. : )

**Comment by dhcodes** [comment]
Closing for now as wontfix. If this becomes an issue, we'll look at solutions.
