### ISSUE TITLE
what  is wrong  with my  code

### ISSUE THREAD

**Issue by a7n007** [freeCodeCamp/freeCodeCamp#15445]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
 var a=str.split('');
  a.reverse();
  a.join('');
  return a;
}

reverseString("hello");

```

**Comment by erictleung** [comment]
@a7n007 Thank you for reporting this issue. Hint: after you do each method on your string `a`, where does that transformation go?

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by a7n007** [comment]
thanks
