### ISSUE TITLE
Delete HTML Elements: The show won't leave me move on once it is completed

### ISSUE THREAD

**Issue by computer590** [freeCodeCamp/freeCodeCamp#15454]
Challenge [Delete HTML Elements](https://www.freecodecamp.com/challenges/delete-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

Hello World

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by n-tran** [comment]
@computer590  you're supposes to delete the whole line...

**Comment by CosmicDog2000** [comment]
Yeah, delete "Hello World" and it will pass. I think the confusion is based the meaning of "element" when it comes to HTML. An element is a section of code enclosed by an opening tag and a matching closing tag. It's content (the text and everything) between the tag, not just the tag itself. I hope this helps, Happy Camping!

**Comment by erictleung** [comment]
@computer590 Thank you for reporting this issue. As others have pointed out, you need to delete the entire line.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
