### ISSUE TITLE
Filter Arrays with filter

### ISSUE THREAD

**Issue by CSE13124** [freeCodeCamp/freeCodeCamp#15453]
Challenge (https://www.freecodecamp.com/challenges/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val>5;
});

```

**Comment by n-tran** [comment]
@CSE13124  please describe your problem?

**Comment by CosmicDog2000** [comment]
According the instructions, your new array should contains all the values from the old array that are "less than" 6. Your code will return values greater than 5. That's a good place to start looking.

**Comment by erictleung** [comment]
@CSE13124 Thank you for reporting this issue. You're close, but not there yet. Run your code and see if the array you get back numbers that are less than 6.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
