### ISSUE TITLE
Img Element Should Have A Smaller-Class Image Code not working...

### ISSUE THREAD

**Issue by Teddi86** [freeCodeCamp/freeCodeCamp#15468]
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
}
  
.smaller-image{
width: 100px;
} 
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

What am I missing?I've spent a few hours and I just can't figure out what I'm doing wrong?

**Comment by erictleung** [comment]
@Teddi86 Thank you for reporting this issue. Please fill out the issue template next time. Looking at your code and going by my memory of the challenge, you need to use your newly defined class `.smaller-image` on an image element.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by n-tran** [comment]
@Teddi86 this doesn't sound like a bug issue. please use the "help" button. I would give you a hint on where to start troubleshooting, but you didnt provide all your code or the exercise.

**Comment by Teddi86** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
}

.smaller-image{  
width: 100px;
} 
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class= smaller.image src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
