### ISSUE TITLE
In description word "Array" is used instead of "Object"

### ISSUE THREAD

**Issue by agilekac** [freeCodeCamp/freeCodeCamp#15479]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In description you can find:

"This is an **array** which contains one object inside. The object has various pieces of metadata about an album. It also has a nested "formats" array. If you want to add more album records, you can do this by adding records to the top level array."

Probably it should be "This is an object..." not array

**Comment by SHoar** [comment]
I don't see the issue. Because it is an array, it can hold multiple elements. This array holds one object.  If you want to add another "album" object to the array, you would simply add a comma after the `}` and add a new object, surrounded by `{` and `}`. Then, the multiple objects are still contained in the array by brackets `[]`.

If you were to use `{}` instead of `[]`, it would then be a single Object with nested, or child, objects. While this is definitely complex,  however much more complex than the scope of this challenge .

**Comment by erictleung** [comment]
@agilekac thanks for the issue, if you look carefully, it is actually an array with one element. I do agree that the one element *is* the object. But this object is enclosed within an array. Closing as a non-issue. Happy coding!
