### ISSUE TITLE
its not going further i wrote the code right

### ISSUE THREAD

**Issue by surya304** [freeCodeCamp/freeCodeCamp#15477]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>view more  <a href="http://www.freecatphotoapp.com">cat photos</a>cat photos</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by codemzy** [comment]
That code passes the challenge when I submit it in Chrome. Maybe try reseting the challenge though since you seem to be missing the <main> tags etc that should still be there.

Then you have two spaces before your nested a tag, and none after, should be one before one after so your link looks right in the sentence.

Try that, and you could also try in a different browser or clear the cache if you still have problems. It's a good idea to go into the chat or on forum if your having problems with challenges as you will get a much quicker response 👍

**Comment by dhcodes** [comment]
Closing as resolved.

**Comment by dhcodes** [comment]
Closing as resolved.
