### ISSUE TITLE
A tribute page to Don Moen

### ISSUE THREAD

**Issue by Flamew** [freeCodeCamp/freeCodeCamp#15486]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
