### ISSUE TITLE
Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by PaulWalt74** [freeCodeCamp/freeCodeCamp#15491]
#### Challenge Name

Concatenating Strings with Plus Operator

#### Issue Description

Im am using Linux Mint
For some reason it won't work proper

#### Browser Information

* Browser Name, Version: Firefox,Recent?
* Operating System: Linux Mint Serena
* Mobile, Desktop, or Tablet: PC Desktop

#### Your Code

```js
var myStr = "This is the start."+"This is the end.";



```
#### Screenshot

/home/roarke/Pictures/Concatenating Strings with Plus Operator.png

**Comment by PaulWalt74** [comment]
I'm having issues regular I get so far than this happens. Any ideas what it might be

**Comment by cdrainxv** [comment]
In English sentences are separated by a space. You need a space between the first and second sentence. Reference how it is done in the example.

**Comment by erictleung** [comment]
@PaulWalt74 Thank you for reporting this issue. But as another has mentioned, you need spaces. Please take a look at the note in the challenge itself.

> Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by PaulWalt74** [comment]
/home/roarke/Pictures/Concatenating Strings with Plus Operator.png
not working

**Comment by PaulWalt74** [comment]
It's a bug or for some reason it is not working in mint serena
