### ISSUE TITLE
BUG: on Filter Arrays with filter chanllenge

### ISSUE THREAD

**Issue by yjoon45** [freeCodeCamp/freeCodeCamp#15499]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function (v) {
  return v > 5;
});
My output is: [6,7,8,9,10]
```

**Comment by JaredLGillespie** [comment]
I believe you're using the wrong comparison in your filter.  The filter function returns only the elements that pass the test (see [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)). In this case, `[6, 7, 8, 9, 10]` are indeed `> 5`.

Try using a `<` instead of a `>`.

**Comment by yjoon45** [comment]
Thanks for the solution it works my bad..
