### ISSUE TITLE
where is problem ?

### ISSUE THREAD

**Issue by ashishjiit** [freeCodeCamp/freeCodeCamp#15492]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for(var i=0;i<arr.length;i++)
    for(var j=0;j<arr[i].lenth;j++)
      {
        product =product*arr[i][j];
        
      }
  
  
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);
//multiplyAll([1,2]);

```

**Comment by Vishwajeetsinh98** [comment]
```
function multiplyAll(arr){
  var product = 1;
  for(var i in arr){
    for(var j in arr[i]){
      product *= arr[i][j];
    }
  }
  document.write(product);
}
multiplyAll([[1,2],[3,4],[5,6,7]]);
//multiplyAll([[1],[2],[3]]);
```
![untitled](https://user-images.githubusercontent.com/15571326/27467952-45494a5a-5804-11e7-8a87-a4038218a581.png)

**Comment by Manish-Giri** [comment]
@ashishjiit Your code has a typo. 

For coding help, please click on the help button from the challenge page.

**Comment by texas2010** [comment]
@ashishjiit 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
