### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by KeldenDorji** [freeCodeCamp/freeCodeCamp#15503]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

<p>
  <a herf="http://freecatphotoapp.com">
    link to cat photos</a>
  for you to follow
</p>

```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by erictleung** [comment]
@KeldenDorji Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
