### ISSUE TITLE
Basic JavaScript: Golf Code: Mistaken logic

### ISSUE THREAD

**Issue by anthonytranDev** [freeCodeCamp/freeCodeCamp#15537]
Challenge [golf-code](https://beta.freecodecamp.com/en/challenges/basic-javascript/golf-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function golfScore(par, strokes) {
  // Only change code below this line
  
  var score = par - strokes;
  
  if(strokes === 1){
    return "Hole-in-one!";
  }
  else if(score >= 2){
    return "Eagle";
  }
  else if(score == 1){
    return "Birdie";
  }
  else if(score === 0){
    return "Par";
  }
  else if(score == -1){
    return "Bogey";
  }
  else if(score == -2){
    return "Double Bogey";
  }
  else{
    return "Go Home !";
  }
  // Only change code above this line
}

// Change these values to test
golfScore(4, 7);

```

**Comment by erictleung** [comment]
@anthonytranDev Thank you for reporting this issue but please ask in the help rooms first when you have an issue. Your code is slightly incorrect. It has an extra space for the `Go Home!`, so that is why it is failing.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
