### ISSUE TITLE
Target HTML elements with selectors using JQuery

### ISSUE THREAD

**Issue by Happynappy1975** [freeCodeCamp/freeCodeCamp#15544]
Challenge Name- Target HTML elements with selectors using JQuery

Question- Use the jQuery addClass() function to give the classes animated and bounce to your button elements. 

#### Issue Description
Target HTML Elements with Selectors Using jQuery

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
<script>
  $(document).ready(function() {
 $("button").addclass ("animated bounce");
  });
</script><script>
  $(document).ready(function() {
 $("button").addclass ("animated bounce");
  });
</script>
```js



```
#### Screenshot
<script>
  $(document).ready(function() {
 $("button").addclass ("animated bounce");
  });
</script>

**Comment by erictleung** [comment]
@Happynappy1975 Thank you for reporting this issue, but GitHub issues are not for coding help. Your code is almost there. Check your capitalization and spacing. Please reach out to the Gitter help rooms for coding help. Feel free to tag me there if you're having a hard time getting a response.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
