### ISSUE TITLE
Beta - Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by pieterdeville** [FreeCodeCamp/freecodecamp#1554]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The description is wrong in the validations:
<blockquote>Your "target1" element should have red text.</blockquote>
should be:
<blockquote>Your "target1" element should have red background.</blockquote>

This code is validated correctly:
```
<script>
  $(document).ready(function() {
    $('#target1').parent().css('background-color','red');
  });
</script>
```
<img width="1280" alt="screen shot 2015-08-05 at 14 16 31" src="https://cloud.githubusercontent.com/assets/13466453/9085378/89ced36c-3b7c-11e5-97a1-4066eb5b821d.PNG">

**Comment by danrhumphries** [comment]
<img width="1428" alt="screen shot 2015-08-19 at 6 51 31 am" src="https://cloud.githubusercontent.com/assets/13267128/9358018/ddc871fe-463e-11e5-819c-80230a7282f1.png">
The instructions say "Give the parent of the #target1 element background-color of red." but the check mark asks for "Your left-well element should have a red background."

**Comment by danrhumphries** [comment]
<img width="1432" alt="screen shot 2015-08-19 at 6 54 06 am" src="https://cloud.githubusercontent.com/assets/13267128/9358065/1dccd146-463f-11e5-840c-7bec6ba06d4f.png">
Even after updating the code to change the left-well to inherit a red background from the parent the check still isn't taking.

**Comment by catfish68** [comment]
i found this is the correct code. 

$("#target1").parent().css("background-color","red");

**Comment by MechoLed** [comment]
The thing is that, **this is not correct**----> $("#left-well").parent().css("background-color","red");
Because, when you use .parent() you gonna take the direct parent of the class, id or selector that you are using, so if **#left-well (the parent)** is what has to be red, we have to take **#target1 (wich is the son)**, so by using **.parent()**, #left-well gonna be red, as it's suppose to. 

the right code is **$("#target1").parent().css("background-color","red");** ...here's a better explination...XD 
http://www.w3schools.com/jquery/traversing_parent.asp

**Comment by majestic82** [comment]
Here's what worked for me
![fcc jquery challenge](https://cloud.githubusercontent.com/assets/19704374/15877428/8c2f3910-2cc8-11e6-97ee-b52dac563a17.png)

**Comment by squat-that-fly** [comment]
the right answer is 
$("#left-well").css("background-color","red");
    $('#target1').parent().css('background-color','red');
