### ISSUE TITLE
Stand In Line, Type Error bug

### ISSUE THREAD

**Issue by DheerajVislavath** [freeCodeCamp/freeCodeCamp#15551]
Stand In Line code throwing the Type Error, as show below. 

####My Code
```js
function nextInLine(arr, item) {
  // Your code here
 arr = arr.push(item);
 var firstElement = arr.shift();
  return firstElement;  // Change this line  
}
  
var testArr = [1,2,3,4,5];
// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
```
#### Screenshot
![capture](https://user-images.githubusercontent.com/15828219/27604017-abf9c66c-5b3d-11e7-9d74-7262f32d9d3e.PNG)

`

**Comment by erictleung** [comment]
@DheerajVislavath Thank you for reporting this issue, but your code is not correct. Please take a look at your code carefully and double check your understanding of the methods you are using. There is something incorrect about them. The type error you're getting is a hint.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by myrindaman** [comment]
i was trying like this :

function nextInLine(arr, item) {
  // Your code here
 arr.push(item);
 var Output = arr;
  return Output.shift();  // Change this line  
}

**Comment by Asjas** [comment]
@myrindaman This repo is for reporting issues with the codebase. If you need any help with a challenge you can view our [list of chatrooms](https://forum.freecodecamp.org/t/free-code-camp-official-chat-rooms/19390) where someone can help you with your code.

Thank you and happy coding!
