### ISSUE TITLE
Use RGB to Mix Colors

### ISSUE THREAD

**Issue by ianlennymatthews** [freeCodeCamp/freeCodeCamp#15550]
Use RGB to Mix Colors

https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors

#### Issue Description

Still being throw an error for this particular exercise. My code is likely incorrect but iv'e also tried setting the color declarations in the style class to be null.

#### Browser Information

* Browser Name, Version:  Chrome 59.0.3071
* Operating System: Windows
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```html
<style>
  .red-text {
    color: #000000;
  }
  .orchid-text {
    color:  #000000 ;
  }
  .sienna-text {
    color: #000000;
  }
  .blue-text {
    color: #000000;
  }
</style>

<h1 class="red-text" style ="color: rgb(225, 0 , 0);">I am red!</h1>

<h1 class="orchid-text" style ="color: rgb(218, 112, 214);">I am orchid!</h1>

<h1 class="sienna-text" style ="color: rgb(160, 82, 45);">I am sienna!</h1>

<h1 class="blue-text" style ="color: rgb(0, 0, 225);">I am blue!</h1>
```

#### Screenshot

![image](https://user-images.githubusercontent.com/29735316/27597471-64965ae0-5b30-11e7-9188-42a9dddbd367.png)

**Comment by CosmicDog2000** [comment]
You are not following the instructions of the challenge. You should not be changing the colors inline, but within the <style> tags.

**Comment by erictleung** [comment]
@ianlennymatthews Thank you for reporting this issue. As it was pointed out above, please take a look at the challenge instructions again. You need to edit the code between the `<style>` tags, not make any inline styles.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
