### ISSUE TITLE
word blanks

### ISSUE THREAD

**Issue by zahrajoulaei** [freeCodeCamp/freeCodeCamp#15553]

**Comment by erictleung** [comment]
Thank you for reporting this issue. Please fill out the issue template if you have found a bug on the site. If you're asking for coding help, please refer to the linked chat rooms below.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
