### ISSUE TITLE
waypoint #60 no green check mark on second task on completion

### ISSUE THREAD

**Issue by Gildara** [FreeCodeCamp/FreeCodeCamp#1557]
![waypoint60](https://cloud.githubusercontent.com/assets/13068082/9086797/a57945b6-3b54-11e5-8a47-b5211a884331.png)
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When you make the background gray 808080 only the first task gives a green checkmark and you don't get credit for completing the task.

**Comment by flota113** [comment]
It's working for me - probably fixed already :)

**Comment by Shifthawke** [comment]
It is not working for me either. Same exact problem. Did you get it worked out?

**Comment by flota113** [comment]
I checked it for the second time and still works but I think I know why it didn't work for You. Did you use '#' before color? It's necessary - even though that it seems to work in this editor, given code doesn't include it either(I'll change it today) and the first mark is ticked - in browsers (at least in mine) it won't work without the hashtag ;)

**Comment by Shifthawke** [comment]
Yeah I had the hashtag. I'm also using Edge, I wonder if that is also part of the problem.  


     On Sunday, August 9, 2015 1:08 AM, flota113 <notifications@github.com> wrote:
   

 I checked it for the second time and still works but I think I know why it didn't work for You. Did you use '#' before color? It's necessary - even though that it seems to work in this editor, given code doesn't include it either(I'll change it today) and the first mark is ticked - in browsers (at least in mine) it won't work without the hashtag ;)—

**Comment by flota113** [comment]
Although You are going to suffer some troubles with bonfires/ and other JavaScript challenges when using Edge (I read somewhere that FCC is working on it), this challenge works fine on Edge - I tested it myself - @Gildara didn't have hashtag as I can see in screenshot - that's why I thought that it could be also your trouble -but maybe it e.g. wrong color or space between hashtag and color code(numbers)? To be sure I just checked the tests and don't see anything wrong with them. Please try again and if the trouble repeats include the screenshot ;)

**Comment by BerkeleyTrue** [comment]
Edge does not support shared web workers, which we require. In the future, this may change but for now we do not support IE/Edge.

closing as stale. Please feel free to reopen if issue still persists.
