### ISSUE TITLE
Modal heading color scheme

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15588]
Maybe this has already been discussed but I did a quick search and didn't find anything.

Regarding the success modal on the default color scheme (not night mode), I think the modal heading text should be white instead of dark-gray. Thoughts on this @freeCodeCamp/moderators? Screenshot below:

 ![Modal](http://i.imgur.com/7uKrMit.jpg)

**Comment by hallaathrad** [comment]
No need for debate. You're a 100% right. Let's do it, I'll audit.

**Comment by hallaathrad** [comment]
hmm on second thought, do we want this to be a first timers'?

**Comment by dhcodes** [comment]
First-timers is fine by me.

**Comment by GeoDoo** [comment]
Hi there! How are you?

I am a first-timer! :)

Can I help with this please? 

Thanks in advance

**Comment by dhcodes** [comment]
Sure thing @GeoDoo. Just follow the [Contributing Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md). If you have questions, you can ask for help in the Contributors chat room on Gitter.

**Comment by GeoDoo** [comment]
That was quick! I was just checking the guide out! 

I will get to it as soon as possible! 

Thanks!

**Comment by raisedadead** [comment]
@GeoDoo 
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/less/main.less#L1078
The modal pops up when you successfully submit a challenge. Any challenge.

However, there is a catch.

You would have to deviate from the regular instructions here. Because this modal is deprecated on the staging (beta) branch.

Considering If the below instructions look too daunting to you, please feel to reach us on the chat.

On to some fixing:

1. Check out the production branch.
    ```
    git checkout backup/master
    ```
2. Purge the `node_modules`
    ```
    rm - rf node_modules
    ```
3. Install dependencies 
    ```
    npm install
    ```
4. Seed the database
    ```
    node seed
    ```
5. Fire up freeCodeCamp
    ```
    gulp
    ```

Make your changes and make pull request as per rest of the guidelines pointed earlier but the branch that you would make the pull request against should be `backup/master`. Its as simple as changing the same on the dropdown on the GitHub when you are making the PR.

This issue is simple, but the setup is bit tricky especially if you are new to this codebase.

Please ping us in the chat, we will be happy to assist.

**Comment by raisedadead** [comment]
When you work on any of the other issues that are going into our regular staging branch, you can switch back to the usual instructions.

Just remember to purge the `node_modules` and installing them again.
Alternatively, keep two clones of the repo locally if you want to avoid purging and installing.

**Comment by GeoDoo** [comment]
@raisedadead You rock!!

Thanks for the instructions! I will try to follow them and get in touch if I get into trouble! :)

**Comment by QuincyLarson** [comment]
@GeoDoo have you had a chance to start working on this?

**Comment by GeoDoo** [comment]
@QuincyLarson

I started working when suddenly it got more complicated! The thing is now I am in the middle of relocating to another country so I do not have the time to finish what I started quickly.. 

If you are in a rush please feel free to assign it to someone else! I might be able to start again in two weeks! Sorry for the delay.

So far it s been a rewarding and insightful experience! Thanks

**Comment by QuincyLarson** [comment]
@GeoDoo OK - thanks for your fast response, and good luck with your move. We'll hope for future contributions from you once you get settled down :)

This challenge is now unclaimed. Anyone want to tackle it?

**Comment by dhcodes** [comment]
PR submitted.

**Comment by GeoDoo** [comment]
@QuincyLarson Thanks for your time and efforts too. 

I am looking forward to finally contribute to your codebase! 

@dhcodes I think there is a variable with this color! I saw in your commit you hardcoded it! 

In general, thanks for the ride so far! Very rewarding feeling you are part of something bigger than you!

**Comment by dhcodes** [comment]
@GeoDoo what do you mean by "a variable with this color"?

**Comment by GeoDoo** [comment]
I mean instead of #f9f9f9 maybe you should have used a LESS variable! 

@dhcodes I am not saying this offensively!! :)

**Comment by dhcodes** [comment]
No offense taken. The `main.less` file uses `#f9f9f9` so it will probably be okay.

**Comment by GeoDoo** [comment]
Perfect then! Thanks for the clarification!
