### ISSUE TITLE
Use a Mixin Under Object Oriented Programming FCC Beta

### ISSUE THREAD

**Issue by MikeIke24** [freeCodeCamp/freeCodeCamp#15591]
Challenge [use-a-mixin-to-add-common-behavior-between-unrelated-objects](https://beta.freecodecamp.com/en/challenges/object-oriented-programming/use-a-mixin-to-add-common-behavior-between-unrelated-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The condition to solve the challenge requires the mixin to be named "Mixing", but it was said that the name should be "Mixin". Just a typo in the assert probably.

let bird = {
  name: "Donald",
  numLegs: 2
};

let boat = {
  name: "Warrior",
  type: "race-boat"
};

// Add your code below this line
let glideMixing = function(obj){
  obj.glide = function(){
    return"I'm soaring!";
  };
};

glideMixing(bird);
glideMixing(boat);

```

**Comment by dhcodes** [comment]
It works with `glideMixin` as well. The issue here is that the first test is not working correctly. It needs to be updated to check that a `glideMixin` function is defined. As it is, it passes without defining the function.

**Comment by MikeIke24** [comment]
I see that now, thanks for the correction 👍

**Comment by Manish-Giri** [comment]
I'll take a look at this.

**Comment by ltegman** [comment]
This comment was left in the Contributor chat room, but not in this issue: the problem is not with the test (the first test does check that a function named `glideMixin` exists) but that if you declared a `glideMixin` in a previous test run and then change the name or something different that should not pass the tests will still pass. It appears variables from old test runs are being leftover and influencing current test runs.

**Comment by Khez** [comment]
@QuincyLarson this issue appears to be fixed.
