### ISSUE TITLE
Word Blanks challenge is too hard or unclear

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15617]
According to Google Analytics, the [Word Blanks challenge](https://www.freecodecamp.com/challenges/word-blanks) is way too hard, and is taking campers an average of 6 minutes and 31 seconds to finish (if they finish - a lot of them seem to give up). 

According to this table, campers spend more time on it than they do on the algorithm challenges.

![](https://www.evernote.com/l/Ar_-arzICANPuaTBet9Y8_Yp9qLthAvqa-QB/image.png)

We need to either reword this or simplify the challenge so it can be completed in closer to 3 minutes. Otherwise, we should move it back to the algorithm section.

**Comment by Manish-Giri** [comment]
@QuincyLarson IMO - This challenge is relatively easy, it's just missing an explanation of some core concepts like function parameters and arguments. A similar idea was posted in this issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/15388. 

But as far as I'm aware, a new challenge hasn't been created so far. I can work on creating a new challenge which explains this concept, if that's okay. 

This new lesson can be introduced before "Word Blanks", which would simplify the challenge to a good extent.

**Comment by Margaret2** [comment]
I think the challenge itself is not too hard, the instructions just need to be reworded. Besides the things @Manish-Giri mentioned, I think a lot of people struggle because they don't have a cultural context for what Mad Libs is, what a fill-in-the-blank game is. Once you tell them, "Oh, they want you to add the words together to make a sentence," that clears up a lot of the misunderstanding.

**Comment by QuincyLarson** [comment]
@Margaret2 @Manish-Giri Yes - that sounds great. If you think it's a matter of people misunderstanding the challenge, then we should make try to make the instructions more clear. Then we can revisit the challenge after a week and see whether time to complete went down.

**Comment by Manish-Giri** [comment]
@QuincyLarson I recently went over what you suggested here about an article on `.hasOwnProperty()` - https://github.com/freeCodeCamp/freeCodeCamp/issues/15616#issuecomment-316771712

Would it be better if I create an article for this challenge as well, instead of creating a new challenge altogether?

**Comment by QuincyLarson** [comment]
@Manish-Giri I think there is already an article about this challenge ([currently it's on the forum](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-word-blanks/18377), and it has been transferred over to Guides. We'll redirect campers to the Guides version of the article when they click the "Hint" button, once Guides is live. 

So even with the hint article, this challenge is taking much longer than it should. I think instead we should try and re-word it in a way that is less ambiguous, or figure out some other way to make this challenge less difficult - especially for campers unfamiliar with the concept of a Mad Lib.

Do you have any ideas as to how we could make this challenge clearer or simpler?

**Comment by shubhshrma** [comment]
@QuincyLarson I remember being stuck at this challenge for like more than ten minutes although it was trivial.The problem was first getting my head around the Mad Libs game as I had never heard the name before.Secondly I thought that the resultant sentence was to be meaningful but it was difficult to make meaningful sentence for multiple inputs.
So I think if the user gets the idea that they just have to include all provided inputs along with  any non-empty strings (even whitespace) between all inputs in the result,it will be a lot easier.

**Comment by QuincyLarson** [comment]
@shubheksha OK - would you be interested in trying to reword the instructions, seed code, and tests to make this less ambiguous? More than half of campers are outside of the US, where Mad Libs are well known, and we don't want to put them at a disadvantage.

**Comment by Manish-Giri** [comment]
@QuincyLarson I've made some modifications to the challenge already. I'll be submitting the PR soon for you to review.

**Comment by Manish-Giri** [comment]
@QuincyLarson Hi! I've made some changes to the challenge description, but I thought posting a screenshot would be better (and faster) to get some feedback, instead of submitting a PR directly. 

As the updated description and instructions requires the user to scroll, I've added the new content in 2 screenshots - 

![1](https://user-images.githubusercontent.com/11348778/28846555-e8d91436-76d9-11e7-8dce-502fb5108d73.png)

<hr>

![2](https://user-images.githubusercontent.com/11348778/28846572-f5c3d528-76d9-11e7-9b13-233717865bde.png)

I think the new description gives a brief overview of what *Mad Libs* essentially is, and at the same time, makes it very clear what the challenge actually expects you to do. Both these parts are currently missing from the challenge, which is what, I think, makes it so difficult for new campers.

One last thing - earlier I had thought of including a small paragraph on the use of `function arguments` and `function parameters`, but since the articles on the guides will be live soon and/or there will be a new challenge about parameters vs arguments, I've left it out. Although, I can add it if you think it would be beneficial here.

Please let me know your thoughts.

**Comment by Manish-Giri** [comment]
@QuincyLarson Any feedback on this?

**Comment by QuincyLarson** [comment]
@Manish-Giri thanks for your patience. 

This is definitely more clear. But it's a bit long. Is there a way we can cut this down to a few paragraphs? Also, we shouldn't use code formatting for non-code.

**Comment by systimotic** [comment]
The PR above was submitted to `backup/master`. I think we want this change on `staging` as well. @Manish-Giri Can you submit a new PR for that? After that, I think this can be closed.

**Comment by QuincyLarson** [comment]
@Manish-Giri I agree with @systimotic - would you be interested in applying this change to staging as well?

**Comment by Manish-Giri** [comment]
@systimotic @QuincyLarson Done!
