### ISSUE TITLE
Invisible Challenge in Basic Algorithm Scripting (Beta)

### ISSUE THREAD

**Issue by njanne19** [freeCodeCamp/freeCodeCamp#15626]
#### Challenge Name
Unconfirmed, but believed to be Slice and Splice --> Challenge can be found under [Basic Algorithm Scripting](http://beta.freecodecamp.com/en/map)

#### Issue Description
The challenge under the ``Title Case a Sentence`` challenge is missing. This could be a bug or it could be something that's worked on, but I'd rather bring something already known to attention rather than leave it there. When inspected, there appears to be an ``<a>`` tag to slice and spice.

#### Browser Information
* Browser Name, Version: Chrome 59.0.3071.115 
* Operating System:  MacOSX Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![image](https://user-images.githubusercontent.com/24515342/28071024-d08399e2-661c-11e7-9225-5f8b97e28cb8.png)
![image](https://user-images.githubusercontent.com/24515342/28071220-4c73bb54-661d-11e7-933f-42fd09491dd7.png)

**Comment by MiloATH** [comment]
I believe it is because isBeta is set to true in the seed. The same is for challenge New Backend Format http://beta.freecodecamp.com/en/challenges/api-and-microservice-projects/new-backend-format. I will check this out.

**Comment by MiloATH** [comment]
[This code](https://github.com/freeCodeCamp/freeCodeCamp/blob/ef64c55f29647dc44241f22184f535afae65128a/server/services/map.js#L15) determines not to show the challenge because in [this]( https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json#L719) "isBeta" is set to true. So it just leaves the bullet without any words.

**Comment by dhcodes** [comment]
Closing in favor of #15705
