### ISSUE TITLE
Make the "Reset your code" modal tab-accessible for Screen Reader users

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#15639]
#### Issue Description

Using Mac, Safari, and VoiceOver or PC running  Windows 10 with Firefox and NVDA, enter a challenge on the site and press the Reset Code button.

The result is that the content appears that asks the user to confirm that they want to reset the code, but the screen reader user cannot read normally to the control that resets the edit window nor can the user tab to the control and activate it with the keyboard without using screen reader reading keys (arrows, PageUp, etc. for PC, and Option-CTRL-arrows on Mac for Voiceover).

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by QuincyLarson** [comment]
This is an important accessibility issue. Anyone want to help fix this?

**Comment by P-WM** [comment]
@QuincyLarson I'm looking to do my first (non-documentation) PR and am interested in accessibility. Can I take this?

**Comment by fonsecapontes** [comment]
@P-WM if you'll working in this case, be sure that modal have "role" ARIA, cause I looked for in the chrome tools and don't find.

**Comment by jhomme** [comment]
It is always better to use semantic HTML if possible than to use ARIA unless you know what you are doing. I suspect this to be a tabindex issue.

On Sep 4, 2017, at 9:55 AM, Lucas Fonseca de Pontes <notifications@github.com> wrote:

@P-WM if you'll working in this case, be sure that modal have "role" ARIA, cause I looked for in the chrome tools and don't find.

**Comment by P-WM** [comment]
My naive reading of the situation is that this is a problem with the toasts, in general, being unreachable. It is a particular problem here as in order to reset code the toast must be clicked.

I can think of a couple of solutions:
1. altering toasts with actionable content (e.g. "reset my code") to modals which may be overkill but should make them clear to screen readers and also removes the timeout;
2. adding the alert role to toasts, although this may be intrusive for users of screen readers (having someone bellow "Keep trying" at them each attempt).

Any thoughts on how best to proceed? @jhomme Is this a problem with other toast notifications that you're aware of?

**Comment by jhomme** [comment]
Hi,
At this point in my development knowledge—why I am going through FCC—I don’t know how toasts work. I know how accessibility works. Maybe this answer will help. For accessibility, anything you can do with the mouse, you must be able to do with the keyboard. Translation: if you can hover over a control with the mouse, you must be able to tab to it and put keyboard focus on it, and see it has fofuc. If you can click it with the mouse, you must be able to press SPACE or ENTER on it with the keyboard and activate it. In my experience, if tab index is set to anything other than 0 on an element, that tends to mess with the ability of the keyboard to do what it needs to do. We always ask folks to get rid of tab order, then put values there very judiciously.

Hopefully this helps.

Thanks.

Jim

**Comment by QuincyLarson** [comment]
@jhomme OK - that is very helpful. I think you're right - there is probably some aspect of Bootstrap's modals that makes them unreachable by tabbing - which may be caused by code that's altering the tab index.

@P-WM would you be interested in taking a look at this? Ideally, we could solve this problem for all Bootstrap modals - we might even be able to contribute this code back to Bootstrap itself at some point.

**Comment by P-WM** [comment]
Sorry for the delay @QuincyLarson and @jhomme.

There was a slight mixup with my last message, and the modals seem fine: NVDA reads out their contents, and they're navigable with the keyboard as well as 'clickable' using SPACE or ENTER (re: Jim's helpful tips). Resetting code, however, produces a toast which is both unreachable by NVDA (only gets read out if you hover over it with a mouse) and has a link to reset the code that can't be pressed with the keyboard.

I could do a PR with a modal for reset but I'm unsure if they may not fit the 'style' of the rest of the site--is checking for confirmation of code reset sufficient cause for adding a new modal? I'm also happy to take a stab at working on the react-notifications that make the toasts, but I may be biting off more than I can chew with that.

**Comment by BrandonDH** [comment]
Hi @QuincyLarson and @jhomme,

I am currently taking a look at the markup for the "Clear my code" and "Cancel" buttons in the "Clear your code" modal, and noticed the `aria-hidden="true"` attribute on both `<a>` tags. Are these attributes being added by JS working in the background? if not, removing those attributes should allow the button text labels to be announced via screen reader (happy to take a crack at that). I'll continue to take a deeper dive into how this modal works. -Brandon

**Comment by jhomme** [comment]
Hi,
Hi,
I am still a new person wen it comes to Git. If someone wants to hold
my hand a bit and help me get my local version of the site back in
sync, and help me find the code, I may be able to at least steer you
in the right direction, if I can't tell you the exact code to write. I
know a lot about the accessible parts of the code that need to be
written, even though I am just a dangerous JavaScript person, and have
just started JavaScript on the site.

Thanks.

Jim

On 10/27/17, Brandon Herford <notifications@github.com> wrote:
> Hi @QuincyLarson and @jhomme,
>
> I am currently taking a look at the markup for the "Clear my code" and
> "Cancel" buttons in the "Clear your code" modal, and noticed the
> `aria-hidden="true"` attribute on both `<a>` tags. Are these attributes
> being added by JS working in the background? if not, removing those
> attributes should allow the button text labels to be announced via screen
> reader (happy to take a crack at that). I'll continue to take a deeper dive
> into how this modal works. -Brandon
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/15639#issuecomment-340066752


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme

**Comment by JazzBrotha** [comment]
Any progress on this? Otherwise, I can give it a stab.

**Comment by JimHomme** [comment]
Hi,
None that I am aware of. I can tell you the screen reader symptoms if you want. I definitely can’t tell you how to fix it yet. I’m just learning about using objects for lookups instead of switch statements. 😊

Thanks.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by JazzBrotha** [comment]
@jhomme Yes, that would be great thanks!

**Comment by JimHomme** [comment]
Hi,
If you would like me to walk you through what is happening, I can do this later this evening US Eastern Time, if you have a Skype ID, you can send it to me privately and we can talk, or if you are in the US, we can talk on the phone.

Thanks.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by JazzBrotha** [comment]
I don't live in the US, but Skype would be fine. Unfortunately, I'm not available today. I will have a look at the issue tomorrow and let you know my thoughts, and then we can set up a time to Skype. @jhomme Sounds good?

**Comment by JimHomme** [comment]
Hi,
Maybe it would be helpful to know that I suspect that somewhere the tabindex is set to something other than 0. It’s acting like it to me. I know this because accessibility testing is my day job. Usually, if you have NVDA turned on, and you are arrowing through text, and then try to tab to a link you haave previously read, this is the case, when focus misses the link or button. NVDA also hates it when you use something like a span or div or paragraph tag and try to add an ARIA role of something like button or any other control type and put in your own TABINDEX. It seems to look for semantic HTML, then give up if it can’t get focus to go where the site is trying to make it go just by using TABINDEX.

Hope this makes sense. Bottom line is that it is always safest touse tags instead of ARIA whenever possible, and totally get rid of TABINDEX.

Thanks.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by JazzBrotha** [comment]
Great, thanks! I will start working on this and let you know my progress.

**Comment by JazzBrotha** [comment]
Now, I have done some research into this issue and I have found a few different problems. First off, as you said, after pressing the "reset your code" `button` the notification `element` is not focusable by tabbing through the `DOM`. Secondly, the notification information gets totally lost to the screen reader user since it does not receive focus immediately after pressing the "reset your code" `button` or is treated as a live region. There is also an issue with the structure of the notification, making the screen reader read "This will restore your code editor to its original state. clear my code" as one sentence.

There are a few different ways to go here, but I agree with you that native HTML 5 elements usually are the cleanest route. However, If I understand the code correctly, the `DOM` structure of the notifications is set through the `react-notification` library which makes it harder to manipulate. An alternative is to programmatically set focus on the notification element through JavaScript immediately after the screen reader user presses the "reset your code" `button`. We could also communicate this information using `aria-live`. Accessing the notification by tabbing might be easiest by programmatically changing the `tabindex` with JavaScript.

@jhomme Let me know your thoughts!

**Comment by JimHomme** [comment]
Hi,
Before I answer, how is the React library doing this? I don’t mean in code, but from a user point of view, for example, is it inserting content into the DOM, making it visible, what tags is it using? Etc.? And I’m asking because I’m not confident enough in my ability to read the code and figure this out just yet. I’m willing to try, though.

Thanks.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by JazzBrotha** [comment]
The notification `element` is inserted into the `DOM` when clicking on the "reset your code" `button`. This is the `html` structure of the notification `element`:

```html
<div class="notification-bar notification-bar-active" style="position: fixed; bottom: 4rem; width: auto; margin: 0px; color: rgb(250, 250, 250); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 2rem; line-height: normal; font-family: &quot;normal Roboto&quot;, sans-serif; border-radius: 5px; background: rgb(33, 33, 33); box-shadow: rgba(10, 10, 11, 0.125) 0px 0px 1px 1px; cursor: default; transition: 0.5s cubic-bezier(0.89, 0.01, 0.5, 1.1); transform: translateZ(0px); right: 1rem;">
  <div class="notification-bar-wrapper">
    <span class="notification-bar-message">This will restore your code editor to its original state.</span>
     <span class="notification-bar-action" style="padding: 0.125rem; margin-left: 1rem; color: rgb(244, 67, 54); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 2rem; line-height: 1rem; font-family: &quot;normal Roboto&quot;, sans-serif; letter-spacing: 0.125ex; text-transform: uppercase; border-radius: 5px; cursor: pointer;">clear my code</span>
  </div>
</div>
```

Some of the style attributes you see are inherited from the `react-notification` `module` and some are set manually. The style attributes are what make the notification `element` visible immediately for non-screenreader users.

**Comment by JimHomme** [comment]
Hi,
What creates the controls, such as the X that closes the div and the Reset button?

Thanks.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by JazzBrotha** [comment]
Hey,

That is created in the `Tool-Panel.jsx` file:
```html
<Button
   block={ true }
   bsStyle='primary'
   className='btn-big'
   onClick={ this.makeReset }
>
Reset your code
</Button>
```

```javascript
  makeReset() {
    this.props.makeToast({
      message: 'This will restore your code editor to its original state.',
      action: 'clear my code',
      actionCreator: 'clickOnReset',
      timeout: 60000
    });
  }
```

**Comment by jhomme** [comment]
Hi,
In case this is helpful, I stumbled upon it.

https://reactjs.org/docs/accessibility.html

**Comment by JazzBrotha** [comment]
The imported notifications from the `react-notification` module are the real enemy  here as they don't contain any `role` or `aria` attributes or a semantic HTML structure. Even if you manage to `focus` the notification, you can't trigger the functionality for resetting the code via keyboard. The reason being that the HTML element for triggering that functionality is a `span` and not a `button`. I hacked together a vanilla JavaScript solution to be able to access the notification through keyboard and changed the "reset your code" element to a `button` and the proper functionality was called. However, that solution does not fit in very well with the rest of the code structure of the application and it broke the styling of the notifications. I'm not sure how to further approach this, sorry.

**Comment by JimHomme** [comment]
Hi,
Thank you so much for working on this. I really appreciate it. This means so much.

Jim



==========
Jim Homme
Team Lead
Digital Accessibility Group
Bender Consulting Services
412-787-8567
https://www.benderconsult.com/our%20services/hightest-accessible-technology-solutions

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38370)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNO-0005FP-6y
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:58 -0400
Received: from out-1.smtp.github.com ([192.30.252.192])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUMJ-0006D9-Ac
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:51:51 -0400
Date: Sun, 03 Jun 2018 07:51:50 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037510;
	bh=nBR98gh2qITsneQ1czW/cmCX4gH6B3YFgN9eL81rU2s=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1JAVIpmqfZp6f2r1G1yWq/69rqWZRq58gGiSLPeNMNVKd73bOT7byLl+ugYmvVKVA
	 mFWEBo3vYYLx8TKvRUGQuIilxkJmNRWTASjEMwdXoE2bAwCvh6qtrqjaceCrBh8HS2
	 efBdqZ6c2kMFS4qfWHF370GI11J8wgdTXsaRU4Gc=
