### ISSUE TITLE
Remove Elements from a Linked List -- this.size is not defined

### ISSUE THREAD

**Issue by TSNelson** [freeCodeCamp/freeCodeCamp#15630]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/remove-elements-from-a-linked-list

#### Issue Description

On line 11 of the provided code for the challenge, 'this.length' needs to be changed to 'this.size'. The test(s) call a this.size method. A correct implementation of remove won't be able to pass these tests without changing the provided code.

**Comment by MiloATH** [comment]
Hi @TSNelson,
Thanks for reporting the issue. I can confirm this issue. This explains an insolvable issue someone on gitter was having. The reason the solution passes the test is because the solution implements a size method.
I think instead of the current solution, a better solution would be:
```js

function LinkedList() { 
  var length = 0; 
  var head = null; 

  var Node = function(element){ 
    this.element = element; 
    this.next = null; 
  }; 

  this.length = function(){
    return length;
  };

  this.head = function(){
    return head;
  };

  this.add = function(element){
    var node = new Node(element);
    if(head === null){
        head = node;
    } else {
        currentNode = head;

        while(currentNode.next){
            currentNode  = currentNode.next;
        }

        currentNode.next = node;
    }

    length++;
  }; 

  this.remove = function(element){
    // Only change code below this line
      if (head === null) return;
      let previous;
      let current = head;
      while (current.next !== null && current.element !== element) {
          previous = current;
          current = current.next;
      }
      if (previous) {
          previous.next = current.next;
      } else {
          head = current.next;
      }
      --length;
    // Only change code above this line
  };
}
```

However, I will leave the current solution except for renaming size() to length(). Also, I will update the test to check length().
