### ISSUE TITLE
Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by NielEXXCRO** [freeCodeCamp/freeCodeCamp#15645]
Concatenating Strings with Plus Operator
https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator

When typing the notion still doesn't pull the check mark when the code written is correct. I believe this is because the output screen isn't reading the text accordingly. 

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr;

**Comment by wflambeth** [comment]
I just gave it a go and it worked fine - make sure you're not forgetting the trailing space on the first string!  (Totally something I would do.)

**Comment by erictleung** [comment]
@NielEXXCRO Thank you for reporting this issue. I don't have your code so I can't critique it. The challenge should be well vetted at this point so most likely, you're missing a space or so. Please check out the chat rooms for coding help before reporting here.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
