### ISSUE TITLE
isBeta challenges should be hidden entirely from map

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15705]
The following empty entries in our challenge map seem to be caused by a challenge with the `isBeta` flag set to true. We should instead hide these entirely so there isn't an empty line next to the bullet.

![jquery__target_html_elements_with_selectors_using_jquery___freecodecamp](https://user-images.githubusercontent.com/985197/28831660-d3048b5c-769f-11e7-812c-fff6a1455baa.png)

**Comment by dhcodes** [comment]
@QuincyLarson pretty sure this is caused by the `isBeta` designation in the seed being `true`. Shall I remove all `isBeta` tags?

**Comment by QuincyLarson** [comment]
@dhcodes Interesting. Thanks for figuring this out. 

We should instead figure out a way to hide the bullet entirely when `isBeta` is true. I'll open a new issue for this.

**Comment by mariusespejo** [comment]
Hey @QuincyLarson I looked at the code a bit and figured out what's wrong. 

Beta challenges are being filtered out by `filterComingSoonBetaChallenge` in `/common/app/redux/utils.js` as expected but the `Challenge` component is handed all dashed names regardless if it is beta or not. So during the state selection you sometimes end up with a challenge that can't be found in the map (because it was filtered out as mentioned above) so you end up with a psuedo challenge enough to render a bullet but without a title.

I have an quick easy fix if no one else has picked this up yet.
