### ISSUE TITLE
New challenge id generator

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15749]
There have been a few questions in the last week about how to make new challenges for freeCodeCamp. Typically, when making a new challenge, we suggest that one manipulates a few digits in one of the existing challenge ids and hope it doesn't clash. I think it'd be more user-friendly in the long-term to have a command-line tool that generates a suggested new challenge id after first running through the current list of ids to ensure it is not already in use. 

Is it a pressing issue? No. Would it be neat-o? I think so.

**Comment by dhcodes** [comment]
Per @erictleung this can be solved by:
(after running mongod in one terminal), have another terminal open running mongo and within that terminal type in ObjectId(). That should spit out a unique ID to use in a new challenge.

**Comment by adityaparab** [comment]
@dhcodes : I undeestand this issue is closed however, I ran into similar issue while creating new PR #15757 

Using `ObjectId()` from Mongo terminal worked for me. This process seems tidious and your original idea of challenge id generator seems feasible to get rid of this processing.

So I did some investigation on this and what I found is putting `id` field for new challenge is completely pointless. Whenever a new record is inserted, Mongo will implicitly assign a unique id `_id` to the document.

I tried a couple of things as follows.

1) Removed id field from all the challenges in es6.json and ran `node seed` again. A unique id was assigned to each challenge (and the command didn't fail) Upon restarting the server, the functionality was in place and nothing was broken.

2) Put `delete challenge.id` at line 72 in `seed/index.js` to make sure no challenge as an `id` property. Run `node seed` and restart the server. Again the functionality was in place.

Running `npm test` after implementing both these approaches resulted in success and that makes me wonder if manually putting `id` in challenge json files is even required.

I think we should remove id fields from json files so that we don't run into this confusion again.
(That is, unless, there some requirement in the code that id attributes must be present, that I am unaware of.)

@erictleung : Any thoughts?

Proposed solution:
(a simple script written to parse json files to json objects, removing id attrubute and rewriting the json file should get rid of all the ids)
PSUEDO code

```
const path = require('path');
const nfs = require('node-fs-extra');
const fse = require('fs.extra');

function getAllChallengeFiles(){
    return new Promise( (resolve, reject) => {
        const challengeFiles = [];
        const challengesPath = path.join(__dirname,'challenges');
        console.log(challengesPath)
        const walker = fse.walk(challengesPath);

        walker
        .on("file", function (root, stat, next) {
            if(stat.name.endsWith('.json')){
                challengeFiles.push(path.join(root, stat.name));
            }
            next();
        })
        .on('errors', reject)
        .on('end', () => {
            resolve(challengeFiles);
        });
    });
}

function rewriteChallengeFiles(challengeFiles){
   challengeFiles.forEach( file => {
       const jsonContent = nfs.readJsonSync(file);
       jsonContent.challenges = jsonContent.challenges.map(c => { delete c.id; return c});
       nfs.writeJsonSync(file, jsonContent);
   });
   return 'All Files Changed';
}

function begin(){
    return new Promise( (resolve, reject) => {
        getAllChallengeFiles()
        .then(rewriteChallengeFiles)
        .then(resolve)
        .catch(console.error);
    })
}

begin().then(a => console.log(a)).catch(console.error);
```
