### ISSUE TITLE
Can't use `<!--h1>foobar</h1-->` comments

### ISSUE THREAD

**Issue by cprn** [freeCodeCamp/freeCodeCamp#15815]
#### Challenge Name

https://www.freecodecamp.org/challenges/comment-out-html

#### Issue Description

The code is valid but doesn't validate saying:

    Do not change the order of the h1 h2 or p in the code.

#### Browser Information

* Browser Name, Version: Firefox, 55
* Operating System: Linux
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<!--h1>Hello World</h1-->
<h2>CatPhotoApp</h2>
<!--p>Hello Paragraph</p-->
```
#### Screenshot

![2017-08-28-194312_1267x1400_scrot](https://user-images.githubusercontent.com/6132708/29786093-20a226b8-8c2a-11e7-8de2-da300392acac.png)

**Comment by vivek28111992** [comment]
I think this is not an issue, you are not commenting properly. It should be something like this

<h2>CatPhotoApp</h2>


This issue should be closed.

**Comment by texas2010** [comment]
@cprn 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by SenamelaMabotja** [comment]
Not an issue

**Comment by cprn** [comment]
Well, if you say. I'm just highlighting it's a correct comment and validator didn't catch it. Thanks for looking at it anyway.

**Comment by PerryChalmers** [comment]
No, your commenting in the HTML code is wrong, the comment tags should be outside and separate from the element tags.

**Comment by cprn** [comment]
Okay, just to clarify. I understand you don't want to support this because it's a beginning level tutorial and not worth more sophisticated validation algorithm. I get it. That's fine with me. I'm not asking you to fix it.

I opened this issue because the way I used comment markup is [perfectly within HTML5 standard](https://www.w3.org/TR/html5/syntax.html#comments). Please, don't say it's wrong or shouldn't be used - you're misleading people. Comment can wrap anything including malformed HTML tags.

**Comment by PerryChalmers** [comment]
It can wrap the malformed tags, but those tags can not be part of the comment tag. Go read the second line of your source, then look very carefully at the code you posted. The first > after your first h1 tag stops your code dead.  is the proper way to wrap an element in html.

The issue being closed has nothing to do with this being a beginner lesson.

**Comment by cprn** [comment]
> [...] the comment may have text, [...] the text must **not start** with a single ">" [...]

The text part in comment `<!--h1>...</h1-->` is `h1>...</h1`. It doesn't start with a `>` character, it starts with `h`. It **is** a valid HTML5 comment, I wouldn't open an issue if it wasn't. I'm not trying to be a smart-ass, I'm simply stating a fact so that the subject could be fully understood by all potential readers.

**Comment by PerryChalmers** [comment]
The comment tag from [W3](https://www.w3schools.com/tags/tag_comment.asp).

It won't work the way you tried it.

**Comment by cprn** [comment]
What are you talking about?? Of course it works! It's a perfectly valid
comment... I'm sorry but at this point it's ridiculous and probably
annoying for everyone involved. I unsubscribed.

**Comment by cprn** [comment]
What are you talking about?? Of course it works! It's a perfectly valid
comment... I'm sorry but at this point it's ridiculous and probably
annoying for everyone involved. I unsubscribed.

![img_20170829_010855_078](https://user-images.githubusercontent.com/6132708/29797457-70021cae-8c57-11e7-945f-b66b6b342952.JPG)

**Comment by systimotic** [comment]
Hi! I'd like to add some comments to this issue for people running into this in the future.

According to [the official HTML5 specification](https://www.w3.org/TR/html5/syntax.html#comments), there is no question that @cprn's comment is a valid comment. This was already shown in the screenshots in the message above. I actually think the way you commented this out is quite smart, it saves you from typing a few characters. I'm used to editor hotkeys commenting things out for me, so this is normally not an issue for me, but I like your creative thinking 👍

There is also some truth to @PerryChalmers' statements, and especially @vivek28111992's original comment. The challenge specifically says to "Comment out your `h1` element and your `p` element." @cprn's comments do not contain a valid `h1` and `p` element, so you could argue that that's why the solution is incorrect.

Here's my point of view: I don't think this solution should pass, because there are no valid elements inside the comments. However, I think there is still an issue with the tests. What doesn't make sense to me is that the first and third tests pass. I believe they shouldn't pass because there are no comments containing a valid `h1` and `p` element. I think it makes sense that the last test shouldn't pass with this solution, because there are no valid `h1` and `p` elements.

Looking at [the tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/cf436f34bc245bab772336fc4378dd3bc5179bfc/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L434-L440), I can understand why it does what it does. These first and third tests aren't looking for comments, they are making sure that the elements are not present on the page. I think has been done this way because it is significantly easier than looking for a comment with the element inside of it. If anybody wants to have a go at improving these tests to handle edge cases like these, we'd happily welcome your contribution!

I hope this gives everyone a better understanding of what's going on. If you have any further questions about this, feel free to ask me. 

Happy coding!
