### ISSUE TITLE
The file client/main.js is seemingly never executed

### ISSUE THREAD

**Issue by markusenglund** [freeCodeCamp/freeCodeCamp#15818]
#### Issue Description

I put a bunch of console.logs in the file, but they are never called when using the website. It seems like at least some of the functionality of this file has been taken over by other parts of the app. I would appreciate it if someone could confirm that this file should indeed be deleted.

#### Browser Information

* Browser Name, Version: Chrome 60
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: Desktop

**Comment by DavOnGit** [comment]
Can i get this?

**Comment by chiefoleka** [comment]
I'd look over the file now and see what I find

**Comment by ResamVi** [comment]
The only reference to `main.js` is in `script.jade`
```jade
script.
    (function(i,s,o,g,r,a,m){ i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-55446531-1', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
// Leave the below lines alone!
script.
  (function(global) {
    global.main = global.main || {};
    global.main.isLoggedIn = !{JSON.stringify(!!user)};
    global.main.userId = !{JSON.stringify(user && user.id || false)};
  }(window))
script(src=rev('/js', 'vendor-main.js'))
script(src=rev('/js', 'main.js'))
```

I added some ```console.log``` statements like you did to ```main.js``` without any success. However if I added those ```console.log``` statements to ```vendor-main.js``` it worked.

So the problem lies in a line of code that terminates the execution of ```main.js```.

This is what happens on my machine with Chrome (I'm asking you if you get the same error)

![screenshot from 2017-10-06 15-02-04_preview](https://user-images.githubusercontent.com/6261556/31279004-993b3e2a-aaa7-11e7-925f-bc0e163d57e6.png)

So babel transpiles this ES6 import

```js
import { aboutUrl, donateUrl } from '../common/utils/constantStrings.json';
```

into this

```js
var _constantStrings = require('../common/utils/constantStrings.json');
```

but Chrome does not understand it and terminates. I think there lies the problem

**Comment by BerkeleyTrue** [comment]
Yes, main.js is no longer used in the current app.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
