### ISSUE TITLE
No DOM related material in course

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#15820]
I can't see any DOM-related material in the entire course. I think this is too important topic to skip. What do you think about expanding the program or it's the thing that you should learn by yourself?

http://javascript.info has good chapter related to DOM.

**Comment by erictleung** [comment]
@w96k thanks for the issue. I agree that learning about the DOM is important. However, freeCodeCamp's challenges are focused on interactive challenges and I'm not sure how to make learning about the DOM very interactive (I could be wrong). IMO, it might be better to have these as YouTube videos or wiki articles. 

cc/ @freeCodeCamp/moderators

**Comment by QuincyLarson** [comment]
@w96k I agree with @erictleung, so I'm closing this. If you can come up with a good way to teach these interactively within our platform, please reopen this.

**Comment by w96k** [comment]
Thank you for the answer, will think about that.

**Comment by cacarr-pdxweb** [comment]
If you cannot conceive of a way to teach the DOM within the interactive platform, then it needs to be made **_abundantly_** clear somewhere in the course that the DOM is a thing -- a critical thing -- that you must learn elsewhere, because one can't be a web developer without understanding it. 

I would suggest a section in the curriculum, containing links to free resources elsewhere, e.g.:

https://mena.udacity.com/course/javascript-and-the-dom--ud117
