### ISSUE TITLE
[challenge]Accessing Nested Arrays has no hint link

### ISSUE THREAD

**Issue by odv** [freeCodeCamp/freeCodeCamp#15879]
#### Challenge Name

https://www.freecodecamp.org/challenges/accessing-nested-arrays

#### Issue Description

When you click the 'Get a hint' button it returns a forum page with the following message **Oops! That page doesn’t exist or is private.**

#### Browser Information

* Browser Name, Version: Chrome, Version 61.0.3163.79 (Official Build) (64-bit)
* Operating System: Ubuntu 17.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![bug](https://user-images.githubusercontent.com/5067625/30323495-1ae0f8c4-97c6-11e7-8196-f5df89608e97.jpg)

**Comment by qmikew1** [comment]
Can confirm this as well (chrome 60, linux - 64) - I initially thought this was a login issue (because log in button/confirm is present in camper's screenshot), however, independent of login status same message is displayed. Though, a different challenge, this might be similiar to what's described in #15609 _(maybe the forum page needs to be updated)_

**Comment by systimotic** [comment]
Thanks for reporting @odv and looking into this @qmikew1!

@m-henderson In #15609 you mentioned the link should be changed. However, this broke because the challenge names were changed. The titles of the forum posts need to be updated to match the challenge names (removing the JSON parts). Is it possible to also update the URL?

**Comment by raisedadead** [comment]
Fixed.

**Comment by tstikic** [comment]
The problem happened again on the Google Chrome version 66.0.3359.181 (Official version) (64-bit) and Mozilla FireFox (59.0.3) (64bit)
**OS:** Windows 7 64-bit
