### ISSUE TITLE
Should be able to link directly to a topic

### ISSUE THREAD

**Issue by evaristoc** [freeCodeCamp/freeCodeCamp#15908]
#### Challenge Name
General; navigating through the Map using direct links.

#### Issue Description
Found behaviours when using direct links that suggest that the possibility of users navigating through the Beta curriculum using direct links by copying/pasting hasn't been tackled? I might be wrong and the plan to tackle that might have been postponed, but in case not I suggest to consider revising the impact of using direct links?

Example:
I was using the links of the beta to see if they could take me to some desired sections I wanted to visit. 
https://beta.freecodecamp.org/en/challenges/basic-css/
One thing I found was that the link opens the introduction page correctly but the map is not expanded.

Or for example this: I tried this link
https://beta.freecodecamp.org/en/challenges/basic-javascript
It should have taken me to the introduction. Instead it took me to a Javascript Object challenge (?).

#### Browser Information
* Browser Name, Version: Chrome, 
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
N/A

#### Screenshot
**Example 1**:
After using https://beta.freecodecamp.org/en/challenges/basic-css/ (no expansion of the menu when using a direct link to a specific subject):
![example1](https://user-images.githubusercontent.com/5592713/30735705-3dd7c4ae-9f80-11e7-8480-92b264d34d31.png)

**Example 2**:
After using https://beta.freecodecamp.org/en/challenges/basic-javascript (wrong landing page):
![example2](https://user-images.githubusercontent.com/5592713/30735759-6b788704-9f80-11e7-9316-1f8311234d18.png)

#### Additional Comments:
* relates to https://github.com/freeCodeCamp/freeCodeCamp/issues/12778
* The other thing that I am not sure if ok is that the high level section name (eg. Responsive Web Development) is not referenced in the link and can't be used to land an specific section of the curriculum.

**Comment by QuincyLarson** [comment]
To clarify, I should be able to navigate to: https://beta.freecodecamp.org/en/challenges/basic-css

When I do, it should: 
1. automatically send me to the first challenge in that block (which is almost always an introduction step challenge)
2. show the map expanded to that section.

So going to https://beta.freecodecamp.org/en/challenges/basic-css should show me this:

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34327948-cf9e7904-e897-11e7-9715-5c287e2584c4.png)

**Comment by iabrenne** [comment]
I would like to give this one a try, if that's OK? Also, it looks like something may have changed since this issue was created, as navigating to https://beta.freecodecamp.org/en/challenges/basic-css/ or https://beta.freecodecamp.org/en/challenges/basic-javascript gets to the "404 Oops we couldn't find that page error".

**Comment by QuincyLarson** [comment]
@iabrenne Yes - that would great! We would welcome your help with this.

To answer your question, I don't think the https://beta.freecodecamp.org/en/challenges/basic-css/ URL ever worked. It was giving a 404 when we created this issue. Enabling that sort of URL pattern will address this issue :)

**Comment by iabrenne** [comment]
@QuincyLarson - yes, I will give this one a try!

**Comment by QuincyLarson** [comment]
@iabrenne Awesome! It's all yours. Thanks for keeping us posted on your progress. Let us know if we can do anything to help :)

**Comment by iabrenne** [comment]
@QuincyLarson  I may need a little guidance. I believe I need to get familiarized with react/redux routing here. I'm going through this tutorial [An Introduction to the Redux-First Routing Model](https://medium.freecodecamp.org/an-introduction-to-the-redux-first-routing-model-98926ebf53cb) and also looking through the code in the common/apps/routes folder. Am I on the right track? Are there any other resources you would recommend that would be helpful for this issue?  Thank you!

**Comment by QuincyLarson** [comment]
@iabrenne Thanks for your extreme patience. I hope the tutorial is going well. Yes - I believe that's correct, but we should ask @BerkeleyTrue about this. He is the most familiar with the routing logic in there.

**Comment by Bouncey** [comment]
@iabrenne The routing is already there, what you need to make this happen is check `this.props.params` in the [Challenges/Show component](https://github.com/freeCodeCamp/freeCodeCamp/blob/9f034f4f790b786256121845c9c2321381a4a725/common/app/routes/Challenges/Show.jsx#L73).

If `this.props.dashedName` is undefined and `this.props.block` is defined, then you are on a block index route and should display as requested by @QuincyLarson 

Hope this helps 👍

**Comment by iabrenne** [comment]
Thank you, @Bouncey. Very helpful! I will look through the code, make sense of it, and (hopefully) submit a PR soon.

**Comment by iabrenne** [comment]
Just wanted to check in and let everyone know that I am still working on this. It is taking no me a while to get familiarized with the codebase, but am making good progress in understanding how the app is put together. Thank you.

**Comment by QuincyLarson** [comment]
@iabrenne OK - thanks for the heads-up. I'm thrilled to hear that you're getting more familiarized with the codebase. Thank you for your help with this, and for keeping us posted on it :)

**Comment by iabrenne** [comment]
Still looking into it. I am making progress. Taking me a while to thift through all the reducers, observers, observables, million next functions, etc :)  But learning a lot, hopefully giving me enough background to help out with future issues. I think I finally found the spot where update is needed to get the dashedName of the first challenge in the block, block being provided by the user in the URL. Will keep the FCC team posted. Thank you!

**Comment by iabrenne** [comment]
Still working on it. Plan on having a PR ready by end of next week. Thank you!

**Comment by iabrenne** [comment]
Hi Quincy and team.  Wanted to provide an update - sorry for the delay in doing so. 

I *kind of* got this working. It wasn't perfect. For example - I wanted to dynamically pull  the name of 1st challenge of each block from the database so that users request could be rerouted accordintly. However fetch from the database happens after the routing/redirect logic which determines the url path. So I ended up hardcoding a list of 1st challenges in the block into the redirect logic. Challenge dashedName  that didn't follow the "introduction to the " { block name } " challenges" pattern, was pulled from a variable I plopped right into freeCodeCamp/common/app/utils/redux-first-router.js. I was going to keep tinkering with it for a while to see if I could make this more dynamic, and reach out for help ( eventually ) if I couldn't figure this out.  The part where accordion gets expanded to the first challenge of the block - I also got to work after ...what felt like forever :). Code may not have been very clean / efficient, but it did what requirements in the issue description stated.  

However, I did not keep my code up to date with the repo as I should have. Was just tinkering on the master branch. Finally stashed my changes yesterday,  pulled down latest code from the fcc repo, and got a few conflicts after I tried to reapply my stashed changes. Looks like repo has changed quite a bit in the last two months after I started working on this issue. Of course it did, what was I thinking. Well, I guess I wasn't thinking  that parts of code I was working on would significantly change, leading to conflicts :) Now I need to see how to modify my stashed updates to make them work with the new code.  

Also I'm receiving "Invalid Fetchr Access" when trying to run the new code I pulled from upstream - so need to work through that too. Sorry this is taking me so long, but I am determined to get this done. Eventually.

**Comment by iabrenne** [comment]
Hi @Bouncey , @QuincyLarson 
I was wondering if you have any concerns if I stick with my original approach of hardcoding a map of names of first challenge in each block rather than pulling those dynamically from a database. Per my note below in contributors chat - I seem to be running into a "cart before the horse" scenario trying to issue a redirect after challenges data is fetched from the database.

 
![image](https://user-images.githubusercontent.com/24214306/38186174-33f0f2ac-3617-11e8-9097-405dcb7221aa.png)

Thank you!

**Comment by iabrenne** [comment]
Hello @QuincyLarson , @Bouncey and the rest of the FCC team.

I went ahead and submitted a PR. I went with the hardcoding approach to get the name of the first challenge in the block, rather than fetching data using a Fetchr service.

Also, appears that PR by @vbelolapotkov took care of  auto-expanding super block and block of the current challenge, therefore I did not need to put logic that I initially planned for that piece.

Sorry this took me so long. But I learned a lot, and hopefully my next contribution won't take 2 months :)

**Comment by QuincyLarson** [comment]
@iabrenne Awesome! Thank you so much for your hard work on this PR! Even though it took a long time, I imagine you learned quite a bit from the process!

I'm tagging @Bouncey to take a look at your PR, since he is the most knowledgable of this part of the codebase and best-equipped to QA it.

**Comment by QuincyLarson** [comment]
@iabrenne We decided to completely rewrite the learning platform to run as a static web app on Gatsby.js, and @Bouncey was able to implement this there. Take a look when you get a moment: https://learn.freecodecamp.org

Even though we didn't end up using your code, I want to thank you for the time and energy you put into this.
