### ISSUE TITLE
Bonfire: Mutations - tests not running

### ISSUE THREAD

**Issue by TheAtomicGoose** [FreeCodeCamp/freecodecamp#1602]
When I run my code on Bonfire: Mutations, it returns `false`, which makes sense, but none of the tests actually run. I'm assuming this is because of something in my code, but I can't figure out what. Here's my code: 

```javascript
function mutation(arr) {
    var str1 = uniq(arr[0].toLowerCase().split("").sort().join(""));
    var str2 = uniq(arr[1].toLowerCase().split("").sort().join(""));

    if (str1.substring(str1.indexOf(str2), str1.indexOf(str2 + str2.length)) === str2) {
        return true;
    }
    return false;
}

function uniq(str) {
    arr = str.split("");
    for (var i = str.length - 1; i >= 0; i--) {
        if (arr.lastIndexOf(arr[i]) === i) {
            arr.push(arr[i]);
        }
    }
    return arr.reverse().join("");
}

mutation(['hello', 'hey']);
```

Thanks!

**Comment by catapixel** [comment]
@TheAtomicGoose There are a lot of issues with this code and I would recommend using one of the rooms on Gitter to help sort them out but short story you are only seeing "false" as a result of running your code because your code isn't completing the tests due to the conditions you've set up. Once you sort out the issues with your code the tests will complete and you will see their results.
