### ISSUE TITLE
Recursion all but required for many Intermediate Algorithms, but it has not yet been introduced

### ISSUE THREAD

**Issue by JB-Walker** [freeCodeCamp/freeCodeCamp#16107]
#### Challenge Name
https://www.freecodecamp.org/challenges/steamroller

Hint 3 states: "You will definitely need recursion...." However, there has not yet been any mention of recursion in the lessons. Recursion needs to be taught (or at the very least mentioned) in the lessons no later than Steamroller.

(The last few lessons have been grueling to solve without recursion.)

**Comment by JB-Walker** [comment]
Fixing issue #16111 should provide an indirect fix to this issue as well,

**Comment by TylerDelRosario** [comment]
I did this challenge a while back, and there used to be a link called 'Recursion' on the helpful links section.

**Comment by travelkris** [comment]
Thank you for opening this issue. Recursion was used as the best solution at least as far back as [https://www.freecodecamp.org/challenges/factorialize-a-number](https://www.freecodecamp.org/challenges/factorialize-a-number), but has not been mentioned in the lessons up to that point (at least as far as I can find).

**Comment by QuincyLarson** [comment]
@JB-Walker @TylerDelRosario @travelkris We just launched the new curriculum and learning platform. Would any of you be interested in helping design some recursion-focused challenges to introduce these concepts interactively, with tests? If so, where in the new JavaScript curriculum do you think these belong? https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript

**Comment by RyanWillDev** [comment]
@QuincyLarson If this is something you'd still like to add to the curriculum. I'd be interested in picking it up.

How many challenges were you thinking would need to be added? As far as where in the curriculum the new challenges should go, I would suggest adding them after iteration is introduced since the concepts are similar.

**Comment by thecodingaviator** [comment]
@RyanWillDev Are you still interested in doing it?

**Comment by rns350** [comment]
Hi there everyone.  If no one is working on this issue, I would like to claim it and work on the recursion challenges

**Comment by RyanWillDev** [comment]
I would love to help, but I don't know how much time I'd have to dedicate to it right now. @rns350 it's all yours! 😄

**Comment by thecodingaviator** [comment]
@rns350 Go ahead with it

**Comment by rns350** [comment]
Awesome, thanks guys!

**Comment by RandellDawson** [comment]
@rns350 Do you have anything to show yet?

**Comment by rns350** [comment]
I'm just about done now.  Have been trying to figure out a good way to test the number of calls that a function makes with chai and have been having some trouble.  Other than that, all test cases and sections are written up

**Comment by RandellDawson** [comment]
@rns350 Why don't you go ahead a create a PR (mark it is Draft), so we can see what direction you have taken.  Then, we can give you some advice on how to write the necessary tests.  Make sure to reference this issue in the PR as (Closes #####)

**Comment by rns350** [comment]
Just submitted the draft.  The set up for the challenge was to fill an array recursively, which I thought made sense since the loop tutorials followed a similar structure, and I wanted to show how recursion can solve iterative problems.  I'm having trouble figuring out a way to test recursive calling.  I though maybe about requiring that only one .push() is used, but would like to find a more concrete way to test for recursive calling.  Thank you for the help and advice Randell!  I'm still new to open source and I appreciate the guidance
