### ISSUE TITLE
[beta] Misleading Comment in "Match Characters that Occur Zero or More Times" Challenge

### ISSUE THREAD

**Issue by blairfrandeen** [freeCodeCamp/freeCodeCamp#16119]
#### Match Characters that Occur Zero or More Times
https://beta.freecodecamp.org/en/challenges/regular-expressions/match-characters-that-occur-zero-or-more-times

#### Issue Description
The challenge description includes sample code with a comment that states:
`let sRegex = /s.*/; // Searches for words starting with s`,
This comment is misleading, because the above regular expression will match any word that includes s but does not start with s, e.g. 'horse'. Either the comment should be changed, or the carat should be introduced for this challenge.

#### Your Code
A more accurate version:
```
let hWord = "horse";
let sWord = "squire"
let sRegex = /^s.*/; // Searches for words starting with s

console.log(sRegex.test(hWord)); // false;
console.log(sRegex.test(sWord)); // true
```

**Comment by scissorsneedfoodtoo** [comment]
These are all good points.

I also noticed that the challenge can be solved without using the * character at all. If we want to keep with the Star Wars title element of the challenge, I could rework it to require both the * and . characters, since the latter was introduced in an earlier lesson. But I'm thinking it might be better to try and introduce the concept of the * character by itself. However, I'll still try to stick the the Star Wars theme.
