### ISSUE TITLE
//noprotect not working for me

### ISSUE THREAD

**Issue by samil19** [freeCodeCamp/freeCodeCamp#16136]
#### Challenge Name
https://www.freecodecamp.org/challenges/smallest-common-multiple

#### Issue Description
I got the problem described on this post https://github.com/freeCodeCamp/freeCodeCamp/issues/13348, so i try to use //noprotect but for some reason it didn't work for me.

#### Browser Information
I tried on Chrome, Opera, Explorer and Edge.

Desktop

Also i tried on my phone, Samsung Browser and Chrome.

#### Your Code
```
//noprotect
var mcm=1;

var counter=0;

function bigger(y,z){
  
  var m = [];
  if(y>z){
    m[0]=y;
    m[1]=z;
    }
  else{
    m[1]=y;
    m[0]=z;
    
  }
  
  return m;
  
  }
function smallestCommons(arr) {

var b = bigger(arr[0],arr[1]);
  
  if ((b[0]-b[1])>2){
    
    for(var x=b[1];x<=b[0];x++){
      
    mcm=((mcm*x)/euclid(mcm,x));
      
  }
    
    return mcm;
    
  }
  else {
    
  return (arr [0]*arr [1])/euclid (arr [0],arr [0]);
    
    }
    
    }
  
function euclid(a,b){
  
  var c;
  
    while(a%b!=0){
     
      c=a%b;
      a=b;
      b=c;
      
    }
  
    return b;
    
}

smallestCommons([1,5]);



```
#### Screenshot
![problem](https://user-images.githubusercontent.com/16728981/33409985-81e82cb0-d554-11e7-9b79-81a98b3539fe.JPG)

**Comment by raisedadead** [comment]
Hi @samil19 

Thanks for reporting, this is an different issue that we are looking at. The problem here is those global variables that have been defined in the code you shared:

```js
var mcm=1;
var counter=0;
```

Your code, and logic themselves are correct. And Its a Okay to have globals. But these lead to unpredictable side-effects.

Our test runner, executes the test cases one after another in series. Hence the last used global data is not purged. We do not have support for global variables because of this complexity. You should set your globals to their initial values within your logic as a cleanup step.

Alternatively, I would recommend you should refactor your code like so, to avoid this altogether:

```
//noprotect

function smallestCommons(arr) {
  var mcm = 1;
  var counter = 0;

  // utility helper functions
  function bigger(y, z) {
  //  ...
  }

  // rest of your logic
  // ...
}

smallestCommons([23, 18]);
```

This is basically writing called functions independent of globals which are prone to mutations outside of their scope while keeping the intended functionality same.

Happy coding!

**Comment by samil19** [comment]
Thaank youu very much, counter was a variable that i was using in another solution to this problem and i forgot to delete, just put mcm inside the main function and that's it

**Comment by raisedadead** [comment]
@samil19 sure, happy to help. 

Also, please note that you can get answers when you are stuck over at our [Forum](https://forum.freecodecamp.com) and the chat rooms.
