### ISSUE TITLE
Moore's law question is not addressed in the lesson

### ISSUE THREAD

**Issue by DovidM** [freeCodeCamp/freeCodeCamp#16160]
#### Challenge Name

https://www.freecodecamp.org/videos/computer-basics-chips-and-moores-law

#### Issue Description

Question 3: "Moore's Law has slowed down in recent years." according to the video would be "false", as it says in the video and in the text accompanying it that "Moore's Law is the observation that the amount of transistors fit on each chip has doubled **every** two years since 1965." (emphasis mine), but the correct answer is "true". It gives the source for the answer in the hint. Basically, the question and answer is correct but it says differently/doesn't mention it in the lesson

**Comment by systimotic** [comment]
Good catch @DovidM! This is no longer an issue in the beta, because these quizzes were removed. In a case like this one, the ideal solution would be to update the video to mention that progress has slowed down, but updating video's is really hard. That's the main reason for removing the quizzes.

@raisedadead Can this be closed?

**Comment by raisedadead** [comment]
Thanks @systimotic
