### ISSUE TITLE
Syntax Highlighting makes text illegible

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16208]
#### Challenge Name
Responsive Style Radio Buttons

#### Issue Description
When you accidentally make a typo in your code, the text is highlighted in a bright pink. unfortunately this makes the text illegible and hard to locate the error. 

FCC is configured to use dark mode
Browsers are in light mode
#### Browser Information

* Browser Name, Version:  Edge 11, Chrome v63 (all 64-bit browsers) 
* Operating System: Windows 10 with latest patches
* Mobile, Desktop, or Tablet:  laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34089407-c9aaee5c-e37d-11e7-848b-e621e1e353ae.png)

**Comment by Ayush-Rawal** [comment]
If nobody is working on it, I'd like to take this issue.

**Comment by Ayush-Rawal** [comment]
@mstellaluna , I've been unable to recreate the issue, 

FCC is in night mode while my browser (Chrome v 63 x64) is in light mode.
Can you provide further details to recreate the issue?

**Comment by systimotic** [comment]
Related: #16319 #16243

**Comment by raisedadead** [comment]
This should rather be fixed using this approach https://github.com/freeCodeCamp/freeCodeCamp/issues/16243#issuecomment-354718194

> Is there a way to tie these CodeMirror theme changes to switching between light and dark mode?
> ~ @QuincyLarson 

Yes, it will be an additional code fix. When a user toggles night mode in settings, currently we are changing the CSS classes for our UI elements (background, buttons, etc.)

But it should be simple enough to improve that logic to toggle the theme of the CodeMirror component to corresponding light / dark i.e (default / dracula) themes.

Since these themes are well maintained for very many languages with a11y colors, we should have to worry only about our UI and not the syntax highlighting scheme.

**Comment by raisedadead** [comment]
Closing in favor of the technical discussion in #16243

**Comment by systimotic** [comment]
@raisedadead Did you mean https://github.com/freeCodeCamp/freeCodeCamp/issues/16319? The issue you mentioned has already been closed 😅

**Comment by raisedadead** [comment]
Oh yes, thanks for catching that @systimotic !
