### ISSUE TITLE
Search Component

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16219]
Behaviour:
- [ ] Currently the search opens challenge links from the result in new tabs. Do we want that? 
- [ ] It displays description, which is bit over whelming, can we hide it or suppress it with a expand (+) icon?

Bug:
- [ ] Search does not clear the placeholder test when clicked upon. Its cleared when typing starts. 
- [ ] Search results are not grouped together correctly.
       <details>
       https://user-images.githubusercontent.com/1884376/34172351-c1279c26-e517-11e7-95e2-b37a0f7afa1e.gif
      </details>

**Comment by Bouncey** [comment]
@raisedadead please see #16218 re grouping and description. 

I'm pretty sure the placeholder behaviour is default. I certainly don't remember it being any other way? 

There is scope to make the `challenge` results use the `Link` component from react-router, but that, at the moment, would require us the build out an individual results UI for freecodecamp, much like we have in guides. 

I went with rendering results with `target='_blank'` so that the component could render results without a care to which context it was being used in.

**Comment by raisedadead** [comment]
Oh, yes I am just taking a note of all the things, and will strike off the things so that nothing is missed that we notice.

>  please see `#16218` re grouping and description.

Perfect. Thanks for the information.

> I'm pretty sure the placeholder behaviour is default. I certainly don't remember it being any other way?

I think that the input field should blank out when we click inside it, just like it does, when we start typing. Of course, its not a huge issue, just a small UX feedback of a click inside the area. 

> There is scope to make the challenge results use the ...

I agree, we can come and fix this up later after further discussion. Not a show stopper either.

Thanks.

**Comment by anhtran1906** [comment]
I wonder if anyone's been working on this because I'm interested in contributing to some of the feature/fix listed above.

**Comment by QuincyLarson** [comment]
@raisedadead I believe @Bouncey is completely overhauling this functionality. The new search will just be a simple drop-down with plain text results, and clicking one will take you to a separate search results page. This is how search works on Amazon, Facebook, and other common consumer webapps.
