### ISSUE TITLE
Add isNewDataVisCert property

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16237]
#### Issue Description
On the user object, we will need both a `isDataVisCert` and an `isNewDataVisCert` property.

`isDataVisCert` should refer to what we will call the "Legacy Data Visualization Certificate" and is `isNewDataVisCert` should refer to the "Data Visualization Certificate".

**Comment by raisedadead** [comment]
This is already the case, we are missing the routes. 
Refer discussion on https://github.com/freeCodeCamp/freeCodeCamp/issues/16246#issuecomment-353406672

**Comment by cpheimbach** [comment]
Hi guys,

I can offer to decorate the existing description of Data Vis Cert with a (Legacy) and put a commented out button for the new one in. Once you have the route that is an easy fix.

code or it didn't happen:

`if isDataVisCert
                        .button-spacer
                        a.btn.btn-primary.btn-block(href='/' + username + '/data-visualization-certification') View My Data Visualization Certification (Legacy)
                    //- if isNewDataVisCert
                        .button-spacer
                        a.btn.btn-primary.btn-block(href='/' + username + '/data-visualization-certification') View My Data Visualization Certification`

**Comment by raisedadead** [comment]
@cpheimbach this issue is about something else, please proceed with the original thread instead. Also we would not need any commented code, which can be added later.

**Comment by raisedadead** [comment]
@QuincyLarson @jonathan-grah 

Just to add that the Cert PR has some significant changes to the backend code which needed QA before a merge, I was hoping to do so, but I guess we went ahead with the merge.

This is fine since we are pressing for shipping beta, but I sincerely advice from my experience that we should not let the UAT(user acceptance test) fall behind.

The last thing we want is users complaining X is not working, Y is broken, and then doing hot-fixes etc.

While a PR is open all the QA that goes into is actual contribution work in checking that the original contributor did not unknowingly miss out on something.

> That is why, we want to have 2-3 sets of eyes at the code, which is of huge impact.

P.S: 
Please take this in good faith and me speaking frankly as a Dev for a quite a bit now, I am not trying to complain or being mean, I love all of the hard work done by everyone here, and hence would like to see that its reaches to fruition with our users appreciating it rather than complaining (which is easy ironically), when we fall short.

**Comment by jonathan-grah** [comment]
Hey, this will be addressed in an upcoming pull request. Thanks for the report 👍
