### ISSUE TITLE
Re-apply GitHub, Settings labels and email re-subscribe

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16240]
Please see the following commits: 

- [x] Add label changes from commit 9142aec8ad118fa4881a82a731e5d5c3ffc9752f
- [ ] Add email re-subscribe from commit 505778acbf4b6ecf4b79941590714c854b2cf78c

These were applied to backup/master branch, but not staging. If any of this code needs to be added to staging, we should do so. Otherwise we can close this issue.

@raisedadead may I defer to you on this? I believe you're the most familiar with our authentication and linking logic.

Edit:
Update to reflect the stories for this issue.

**Comment by raisedadead** [comment]
Sure, I'll take care of these. Thanks for looping me in.

**Comment by raisedadead** [comment]
@QuincyLarson quick query, can you guide with the verbiage that you would want from here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/505778acbf4b6ecf4b79941590714c854b2cf78c/server/views/resources/unsubscribed.jade#L5-L10

Obviously this one from production is no longer relevant/updated, for beta.

**Comment by raisedadead** [comment]
I am back porting other code logic. PR is WIP.

**Comment by raisedadead** [comment]
@QuincyLarson @BerkeleyTrue 

We are now defaulting to a toast message after unsubscribe, on the current challenge, instead of a static landing page showing the link to resubscribe.

Do you want me to add back the static page, with the a link, in the toast is self? Or update the route to hit the static page?

Also, I would need you to help me with copy for the message on the static page (code snippet in previous comment).

**Comment by BerkeleyTrue** [comment]
> Do you want me to add back the static page, with the a link, in the toast is self?

Can you elaborate on this?

**Comment by raisedadead** [comment]
Yes, sure.

When the user lands on the website from the email, they get a react toast that says they are unsubscribed.

I am proposing, to add a link in that toast message (similar to our reset code toast), which takes them to the static `unsubscribed.jade` view.

They have the option as the production to re-subscribe.

Or,

We can route them directly to the static page instead of landing on the challenge/app view.

**Comment by raisedadead** [comment]
The former is a better UX in my opinion. The later is well a bit rude.

**Comment by BerkeleyTrue** [comment]
Sounds good, @raisedadead. Let's go with the former.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
