### ISSUE TITLE
Update beta lesson buttons to match production

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16258]
We need to update beta's lesson buttons to match production's. Here's a screenshot with additional detail:

![generate_random_whole_numbers_with_javascript___freecodecamp_and_learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34286606-4e10b68c-e6a7-11e7-9d93-1e1d41b3f03f.png)

**Comment by KhaledSamir** [comment]
@QuincyLarson I'll work on this one.

**Comment by QuincyLarson** [comment]
@KhaledSamir Awesome - thanks for grabbing this one! Please keep us posted and let me know if I can do anything to help :)

**Comment by KhaledSamir** [comment]
@QuincyLarson Sure ... I'll keep you posted!

**Comment by KhaledSamir** [comment]
Hey @QuincyLarson, I'm done with the required changes and get the html exactly matches the production but I have a question. When we click on " Ask for help on the forum " , the modal that will pops-up is still different So, do you wanna fix this as part of this issue or open a new one specifically for the modal?

This is in Local ( Check the buttons also :) ) 

![screen shot 2017-12-22 at 7 16 38 pm](https://user-images.githubusercontent.com/4302544/34315870-154fb9a0-e74d-11e7-914b-708129b7613e.png)

This is in Production

![screen shot 2017-12-22 at 7 20 17 pm](https://user-images.githubusercontent.com/4302544/34315872-3172dca2-e74d-11e7-8fe4-ad4181e58551.png)

**Comment by QuincyLarson** [comment]
@Kalcode Yes - good catch! Can you also update that modal?

**Comment by KhaledSamir** [comment]
@QuincyLarson sure, I'll give it a try tomorrow morning.

**Comment by Kalcode** [comment]
Wrong user mention :)

Thought you were randomly asking me to update something. I was like sure I'll look into it lol.

**Comment by QuincyLarson** [comment]
@Kalcode Woops. You are super active on GitHub - I guess that's why it auto-completed to you. We'd welcome your help in general though :)

@KhaledSamir OK - thanks for your help with this!

**Comment by KhaledSamir** [comment]
@QuincyLarson GM! , I checked the changes that should be done and I'd say it's better to have separate issue for changing the modal and here's why.

There is a file called " ns.json " in this path " Common/app/routes/Challenges " and we load the name of the classes "css classes I mean " with the value of this file which is currently " Challenges "
and if we just change it to " Challenge " the head would turn green like the production but since this change is gonna impact other files " not just Bug-Modal " so, I'll prefer to open another issue to fix that and make sure that other views didn't impact this change.

Second reason is : the content of the modal seems like changed as well so we'll need also to address that. 

Let me know what you guys think.

**Comment by QuincyLarson** [comment]
@KhaledSamir Awesome! I agree with your reasoning here. Would you be interested in opening that second issue, and then opening a second pull request as well?

**Comment by KhaledSamir** [comment]
@QuincyLarson Yup, I'll open another issue and put my findings there. I'll work on the other issue tomorrow.
