### ISSUE TITLE
Delete FCC Account - Confirmation Text Popup - cannot read in Dark Mode

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16282]
#### Challenge Name

My Profile -> Update My Settings -> Reset Progress/Brownie Points

#### Issue Description

The confirmation popup window, the text is not readable.
Either the background is too dark because its in dark mode
or the buttons should be filled in and the text be in white

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316777-d14d7994-e76b-11e7-8ebb-d1224e6714af.png)

**Comment by vkWeb** [comment]
@raisedadead I can work on this. 
**Before:**
![capture](https://user-images.githubusercontent.com/22984739/34316777-d14d7994-e76b-11e7-8ebb-d1224e6714af.png)

**After:**
I changed the background color of the modal footer to `#E0E0E0` because changing text or border color will not be a good idea. 
![capture](https://user-images.githubusercontent.com/26724128/34900021-96b24860-f822-11e7-8979-6cf49cd70d62.PNG)

**Comment by raisedadead** [comment]
Sure thing, please make a pull request. Thanks.

**Comment by vkWeb** [comment]
@raisedadead On the way.
