### ISSUE TITLE
React Challenges: "Something went wrong, please try again later" incessant flash messages 

### ISSUE THREAD

**Issue by trothaar** [freeCodeCamp/freeCodeCamp#16305]
![screenshot 5](https://user-images.githubusercontent.com/8755099/34322572-8864a080-e7f8-11e7-90ca-03f4ee5e45d5.png)
#### Challenge Name

It appears to be a problem with all of the React Challenges, but I screenshot the first one:
https://beta.freecodecamp.org/en/challenges/react/create-a-simple-jsx-element

#### Issue Description

When I attempt to do a challenge, I get an error message on the far right that reads, "JavaScript is disabled. Execute code to enable," as well as the "Something is not right; try again later" popup. I am unable to complete the challenge or submit it.

#### Browser Information

* Browser Name, Version:  Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet:  Laptop

![screenshot 4](https://user-images.githubusercontent.com/8755099/34322568-7d0d95de-e7f8-11e7-920e-44f8fd11d3e8.png)

**Comment by no-stack-dub-sack** [comment]
@trothaar @Bouncey @QuincyLarson If I'm not mistaken, the "JavaScript is Disabled" message is intentional, which appears until you unlock and run the code, to prevent malicious code from being run until the camper is sure they want to run their code. @BerkeleyTrue can confirm this. 

The "Something Went Wrong" banner has been present consistently throughout the development of these challenges, and I cannot speak to. Whenever you type something it seems to come up.

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack yes that is intentional. The errors are also due to babel attempting to transpile on each edit. This requires some addition to the preview logic to disable this pipeline

**Comment by no-stack-dub-sack** [comment]
@BerkeleyTrue Ok, so renaming the issue, since we've established that's intentional. How about these stackable flash messages? I was thinking that this was also due to babel trying to retranspile on each edit, and complaining because until the edit is complete, there's syntax errors (e.g. unclosed tags). If you watch the whole gif, you can see that we end up with a whole stack by the end:

![image](http://recordit.co/PUEW6KNfPe.gif)

**Comment by no-stack-dub-sack** [comment]
@trothaar @Bouncey Ok, so JavaScript is Disabled is intentional, but the "Something went wrong" flash messages are still a problem. Opening an issue specific to this and closing this one.

**Comment by BerkeleyTrue** [comment]
> How about these stackable flash messages

The renaming makes it seem like the flash messages are the issue. The stacking of flash message is a feature, the bug is that we still try to transpile code when js is disabled.

I suggest we focus our efforts in disabling the transpile pipeline when js is disabled and to provide a better error message when babel fails to transpile.
