### ISSUE TITLE
Basic JavaScript: Divide one Decimal by Another with JavaScript - Still Failing

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16329]
#### Challenge Name
Basic JavaScript: Divide one Decimal by Another with JavaScript
https://beta.freecodecamp.org/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript

#### Issue Description
Previous Issues: 
https://github.com/freeCodeCamp/freeCodeCamp/issues/13400
https://github.com/freeCodeCamp/freeCodeCamp/issues/14635

The issue is still happening even with suggested refresh and/or reset. 
Cannot pass this challenge states "The quotient variable should only be assigned once"
I had other campers verify in case of a local issue, but they are reporting the same error on this challenge.

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34366438-7e3a33a4-ea69-11e7-9590-8c971fa34bdc.png)

**Comment by systimotic** [comment]
Thanks for reporting this @mstellaluna!

Previously, the `tail` code from the seed was included in the `code` variable used in the tests. This was a new change in the beta that previously broke this test. This has been reverted, the `tail` is no longer included in the `code`. Because of that, the test can also be reverted to what it was before.

I opened a PR to fix this (#16343) and I'm opening an issue for the other instance that was found. There might be more of these, hopefully we can uncover them before the beta release.
