### ISSUE TITLE
Profile page - some project links are broken

### ISSUE THREAD

**Issue by JacksonBates** [freeCodeCamp/freeCodeCamp#16337]
#### Issue Description

On the profile page, the links to some of the old project information pages are broken - they simply link to https://beta.freecodecamp.org/challenges/undefined/undefined.

The affected projects on my profile are:
* Build a Nightlife Coordination App
* Build a Voting App
* Build a Personal Portfolio Webpage

My profile: https://beta.freecodecamp.org/en/jacksonbates

#### Browser Information

* Browser Name, Version: Chrome 60
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

Screenshot shows me hovering over the Nightlife app, the link's url is in the bottom left corner.

![bug bad links](https://user-images.githubusercontent.com/4337740/34378463-073c2690-eb4a-11e7-91d0-0a653549015c.png)

**Comment by saurishkar** [comment]
@JacksonBates I thought beta.freecodecamp.org does not save user progress. How is that happening here ?

**Comment by mstellaluna** [comment]
@JacksonBates Some campers (such as myself) had logged into and started working on Beta before the logins were disabled. So we have a some challenges already completed.

**Comment by JacksonBates** [comment]
@saurishkar Logins were enabled for a test group for further QAing about a week ago.

**Comment by saurishkar** [comment]
@JacksonBates  Ohh ok, thanks for the heads up. 
@mstellaluna Even if they were disabled, the links should not go undefined because they point to general challenges not to the user's code to that particular challenge as i checked (or maybe i checked after they were disabled so that's what i am getting). Also, only a couple of links are receiving undefined data so it's worthwhile to have a look i guess. 
I am still checking the source of the problem, got pretty close but not close enough yet.

**Comment by raisedadead** [comment]
Login is now enabled for all. But the progress maybe purged as we are re-deploying every now and then.

**Comment by QuincyLarson** [comment]
@JacksonBates @raisedadead This will be fixed once we've fixed https://github.com/freeCodeCamp/freeCodeCamp/issues/16858 - I'm closing this as a duplicate.
