### ISSUE TITLE
Beta: Waypoint: Use Responsive Design with Bootstrap Fluid Containers

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1634]
Creating the container div causes a scroll bar to appear on the phone output which kind of screws the styling a bit for the rest of the CatPhotoApp tutorial

![image](https://cloud.githubusercontent.com/assets/4687812/9129671/2161241c-3d1e-11e5-9806-8f903eccad9a.png)

**Comment by Greenheart** [comment]
@richyvk  This is probably the default behavior for non-mobile browsers since they don't have touch controls.
It's pretty simple to remove the scrollbar [without losing the ability to scroll](http://stackoverflow.com/questions/16670931/hide-scroll-bar-but-still-being-able-to-scroll) but I don't know if it would improve the user's experience of this waypoint since many users rely on the scrollbars and aren't that used to scrolling without that kind of visual feedack. 

But this could definitely make this app's UI feel more like an actual app!

**Comment by richyvk** [comment]
Fair point. I only added as an issue as I don't remember it happening in the current live version of the catphotoapp waypoints??

**Comment by benschenker** [comment]
Closing as stale, please reopen if you still see the issue
