### ISSUE TITLE
Basic Algorithm Scripting: Truncate a String - Not Accepting Wiki/Production Hint Code

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16377]
#### Challenge Name
Challenge Link:
https://beta.freecodecamp.org/en/challenges/basic-algorithm-scripting/truncate-a-string

Wiki Link:
https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-truncate-a-string/16089

#### Issue Description

The truncate a string challenge is not accepting the Wiki resource code for the challenge if a camper
uses the Wiki for help in solving the challenge.
Unsure if the challenge was updated or if this is the original challenge from production FCC. 
Please verify the challenge so it either:

1) Passes using the existing Wiki page code for this challenge 
2) Update the Wiki page code for this challenge accordingly 

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
`function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num - 3)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }

}`


```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34456709-79068a86-ed6b-11e7-8d75-21226c260fdc.png)

**Comment by andyguo1023** [comment]
I investigated the issue. I suspect the challenge was updated, or perhaps the issue was inherently there due to the misleading explanations provided. 

`function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num - 3)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }

}`


the issue lies in the line `return str.slice(0, (num - 3)) + '...';`
The explanation says 

> if num is larger than 3, we must factor in the three dots to our total length, and thus we end our slice at num-3.

This does not seem to match the description of the challenge. From the many solution posts by campers on the forum, most of them did factor in the three dots. Hence the suspicion of an update in of the challenge in the past. Now from a camper's perspective, many may find the description ambiguous, as in whether to factor in the three dots for the maximum length of the string or not. 


I suggest that we update the wiki hint code, and perhaps clarify the description of the challenge. 


Here is a passing solution. 
`function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }

}`

**Comment by systimotic** [comment]
I can confirm that the challenge requirements have been updated, which is why the previous solutions no longer work. Looking into it, I found out I was the one who made this change, one year ago 😄. More details on why it was changed can be found here: #12712

Once the beta is pushed to the live site, the forum and/or Guide article will have to be updated.

Happy coding!

**Comment by Ali1968** [comment]
Hi my solution
function  truncateString(str, num){
//clear out that junk in your trunk
var truncat = "";
if (str.length>num){
truncat = str.slice(0,num) + "...";
return truncat;
}
return str;
}

**Comment by jetstreet** [comment]
Hi ! 
function truncateString(str, num) {
return str.length > num ? str.slice(0, num) + '...' : str;
}

**Comment by mandrei100** [comment]
Try this; it is short and simple (and correct):
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num) {
    return str.slice(0, num) + "...";
  }
  else {
    return str; 
  }
}

**Comment by sameekadam** [comment]
Yes this work perfectly

**Comment by Zakaria1986** [comment]
this works for me: 

function truncateString(str, num) {
  // Clear out that junk in your trunk
  if( str.length >num && num > 3){
    return str.slice(0, num) + '...';
  }else if(num <= 3){
    return str.slice(0, num) + "..."; 
  }
  return str; 
}

**Comment by RandellDawson** [comment]
@ZacharyKearns Please do not add comments to closed issues unless you are reporting a bug.  This is not the place to just post a code solution for a challenge for the sake of posting it.

Thank you.
