### ISSUE TITLE
Update docs about generating ID for New Challenges

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16373]
We need to update the [Challenge Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md) and refer to it prominently from the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

The update should be along the lines of:

----
To generate a new one in a shell (assuming MongoDB is running separately):

1. Run `mongo` command
2. Run `ObjectId()` command

Output:

```sh
$ mongo
MongoDB shell version v3.6.1
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.10
...
$ ObjectId()
ObjectId("5a474d78df58bafeb3535d34")
```

The result is a new id, for example `"5a474d78df58bafeb3535d34"` above.

----
Refers: https://github.com/freeCodeCamp/freeCodeCamp/pull/16369#issuecomment-354534248

**Comment by saurishkar** [comment]
May i take this one and raise a PR with proper updates ?

**Comment by mathagician** [comment]
@raisedadead Please help me in understanding the issue. So far, I understand that the above code should be added to [Challenge Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md). Please give clarity.

**Comment by saurishkar** [comment]
@mathagician If you check out the reference Issue given at the bottom of the comment, it will give more clarity to the task at hand.
It relates to the situation when you have to add new challenges to the open source, a primary guideline should be followed in generating a unique id for this record (since the challenge data will be stored as seed json data). 
So, in order to do that the commands mentioned in the comment have to be run, to make sure that the id generated does not collide / clash with any existing id's in the database.
Finally, the contributor's guide should be updated with the primary details about how to generate a new id in mongodb (with the steps mentioned in the comment).

**Comment by raisedadead** [comment]
Hi @saurishkar @mathagician sincerest thanks for the interest in working on this. 

We are in middle of consolidating and enhancing all the documentation around freeCodeCamp's code base. We want to get this done with some restructuring and simplification to the guide.

Also, it would have to be opinionated from what or plans and need are. Since this is of critical importance to all, I plan to do the restructure myself. 

Please expect a PR from soon. 

With that said you guys are more than welcome to share your feed backs on what you would like to see in the guide.

Happy contributing.

**Comment by alexch** [comment]
I will take this on and add those instructions to either `challenge-style-guide.md` or `seed/README.md` while @raisedadead is working on a more comprehensive docs PR. And maybe even make a gulp script for it, if I'm feeling ambitious!

**Comment by alexch** [comment]
I've added these instructions on my branch and they should appear as part of #16511 momentarily
