### ISSUE TITLE
Decide behavior for when all panels are closed

### ISSUE THREAD

**Issue by sachinlamba** [freeCodeCamp/freeCodeCamp#16382]
![fcc](https://user-images.githubusercontent.com/19946593/34460499-453b7a56-ee36-11e7-81a9-bde94f9f7e43.gif)
We should have atleast one panel in window to look at. User should not be able to hide all panels.
and one more thing, should we change css for hidden panels?
Plz check and tell if I can work on these?

**Comment by vkWeb** [comment]
@sachinlamba There's no problem in hiding all the panels. Users can always toggle them back on :). So, according to me working on this will just increase some conditional statements. I don't think it's worth the time you gonna spend on it. 
If you're willing to contribute. We have a lot of [outstanding issues](https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted) you can look at. 

@QuincyLarson, @systimotic  I think this should be closed.

**Comment by zelite** [comment]
I think this should be further discussed instead of dismissed beacause of "too much work" or "it's good enough". The current interface with navigation links in the top bar having the function to show/hide panes is not intuitive. Some extra visual cue should better indicate their function.

Additionally the name of the panes on the react challenges (as seen in the OP post) is not clear. One of the panes is called "index". What does this mean? Yeah, if we think about it is probably the file name "index.js", but is is not intuitive and does not make sense to have the file name in this context.

**Comment by vkWeb** [comment]
@zelite This issue is about allowing users **not** to hide all the panes.
 
The issue you're referring to is totally different. It's about the intuitiveness of the workspace. I request you to please open another issue where this discussion will be directed and please mention the changes you would like to see in the workspace. Screenshots will be helpful. Thanks ;).

**Comment by zelite** [comment]
I think it's all part of the same issue that the panes hiding behaviour is not intuitive. Hiding all panes without an intuitive way to make them reappear seems confusing. That's why I said it should be discussed. I don't know what the ideal solution is. I am by no means a UX expert (or even UX amateur), but I feel there should be made an effort to find a better solution.

**Comment by vkWeb** [comment]
@zelite Okay - If you want to discuss it here. We'll do. What kind of behavior would you like to see?

**Comment by QuincyLarson** [comment]
Instead of forcing one panel to be visible, we should just have a "no panels are visible" graphic. Kind of like how you look at a document and it says "this page is intentionally blank."

Here's what JSBin looks like if you close all its panels:

![js_bin_-_collaborative_javascript_debugging](https://user-images.githubusercontent.com/985197/34463338-4a5347ca-ee1e-11e7-864a-f04f8901c2ff.png)

I've updated the title of this issue to reflect this.

**Comment by QuincyLarson** [comment]
One thing I've thought about adding is some sort of motivational quote that changes on every challenge. That way if campers get stuck, they can close the tabs, see it, and get a boost of motivation :)

We could load this the same way we load "challenge completed" quotes: https://github.com/freeCodeCamp/freeCodeCamp/blob/c6487c6dabd4a678ce8256444a913ab228949a37/server/utils/resources.json

**Comment by vkWeb** [comment]
@QuincyLarson Amazing Idea - We should do that quote thing. It'll be kind of an easter egg for our campers. ;)

**Comment by QuincyLarson** [comment]
@vkWeb Agreed! A motivational easter egg! Would you be interested in helping with this? We need to build a list of good motivational quotes, and then write the logic to display them in a large font in the background when all panels are closed.

**Comment by vkWeb** [comment]
@QuincyLarson I'm willing to help but as you know I'm not at all experienced with JS, I'll start learning it next year after my high school exams and then I'll never stop contributing to freeCodeCamp codebase :).

**Comment by AustinTice** [comment]
@QuincyLarson I can pick this issue up if need be. Any particular quotes you're looking for? Like an API of some sorts, or would you prefer we just make an array of quotes and display a random one whenever no tabs are open?

**Comment by sachinlamba** [comment]
@AustinTice I think that static list will not look good. If u r familiar with the code, u can try to implement dynamic list (if possible, with localisation dependent language).

**Comment by QuincyLarson** [comment]
@vkWeb OK - sounds good. We will find someone else to tackle this then. Thanks for all your contributions so far!

@AustinTice Yes - we'd welcome your help. I can come up with the list of quotes. For now, please use a placeholder array of quotes. Here's one you can use first for the purpose of getting the styling right: 

"Never, never, never, never, never, never give up." - Winston Churchill

@sachinlamba We want to use a simple static list for performance, and we can go in and add quotes in different languages later. We won't launch localization features until after we've launched beta.

**Comment by AustinTice** [comment]
@QuincyLarson I can absolutely get this done tonight or the following day; however, I'm quite new to this repo, where exactly is the html and js files that need to be edited for this particular project? Thanks in advance!

**Comment by AustinTice** [comment]
I made this locally and would be quite simple. I just need a hint of instruction on where the folder is to get the panes. I see the panes.jsx & pane.jsx, but do not fully understand where to begin in the file. I am hoping to just write a function that grabs some random index of a given"motivationalQuote"
array and then spits it into a given html tag whenever all the panes are closed.
![fcc vid](https://user-images.githubusercontent.com/16217050/34599525-72833cf8-f1b8-11e7-8a1f-bae9fa28044b.gif)

**Comment by QuincyLarson** [comment]
@AustinTice That looks solid! 

@BerkeleyTrue Do you know how we could show this quote component when all panes are closed? Where would we put such a component?

**Comment by BerkeleyTrue** [comment]
The logic would go in panes.jsx. This is where panes are rendered.

**Comment by raisedadead** [comment]
@AustinTice how is it going?

**Comment by AustinTice** [comment]
@raisedadead I haven't been able to produce the correct functionality for this as of yet. I am struggling with understanding some of the syntax and have been doing some investigating into the issue. I don't want to hinder any part of the project due to my lack on knowledge in this area, but I will continue to work on this. Feel free to ask others to work parallel to me. Thanks for checking in!

**Comment by raisedadead** [comment]
Sure thing @AustinTice please take your time, and drop your queries should you need any guidance on the code-base in here, we are there to help you help us!

**Comment by vkWeb** [comment]
@AustinTice How is everything going?

**Comment by jfines** [comment]
It would be super cool to have a real easer egg. Something totally freaky but educational related. Something not easy to find that would spread through the grapevine like wildfire once someone did catch it.  (Strange combination of keys, clicking a certain area of the screen with a particular key or two held down at the same time, etc).  The easter egg could be something cool like a fireworks animated graphic, something scary like a creepy monster that zooms in and goes boo in your face, or something cool like the ability to change the color scheme just for your account.  What about randomizing it so when people find out there's something they have to hunt for the exact spot to click but they know it's there? Simple enough to find it but not the same every time. Hope that's not too off topic but I saw vkWeb idea about an easter egg and it made me think of the stuff I heard about from back in the day (space invaders easter egg in some program I hear one time).

**Comment by QuincyLarson** [comment]
@AustinTice Have you had a chance to work on this? Your concept looks solid - are you planning to implement it?

**Comment by AustinTice** [comment]
@QuincyLarson, @vkWeb: Forgive me for my late reply. I have up to this point not been able to figure out how to implement this functionality. I would suggest that it be taken on by another member. My studies have kept me quite busy during this time, and I have not had as much time as I wished to thoroughly dive into react. I don't mind to continue working on it, but due to the fact it has been a considerable amount of time, I don't see myself finding the solution without a bit of help.

**Comment by QuincyLarson** [comment]
@AustinTice OK - thanks for confirming. This is now open for anyone who's seriously interested in tackling it. Please leave a note here so we know you're working on it.

We'd like to implement this like in @AustinTice's mockup here: 

https://user-images.githubusercontent.com/16217050/34599525-72833cf8-f1b8-11e7-8a1f-bae9fa28044b.gif

**Comment by scissorsneedfoodtoo** [comment]
Hi all, I really like this idea and would like to take a crack at implementing it. I'll do my best to follow @AustinTice's mockup, and will reach out if I run into any problems along the way!

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Awesome! Great to hear from you. Yes - we would love for you to take a crack at implementing this!

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, great to hear from you too! Looking forward to working on this and getting some feedback soon.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Great! Please keep us posted on your progress :)
