### ISSUE TITLE
Panes do not maintain state when clicking on challenges in map

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#16407]
Related to #16367 & #16249 

@Bouncey fixed the issue with the map as described in #16249, however, for other panes, state is not maintained when a user clicks on a challenge via the map, or when moving to the next challenge: 

- **When moving to the next challenge** (`challenges.submitChallenge`): "Index" and "Side Panel" should be open by default, but if the user closes the "Preview" pane, perhaps this state should persist after this action fires? 
- **When clicking on challenges via the map** (`map.clickOnChallenge`): state is automatically reset, and each pane defaults back to `isHidden: false` (except for the map, which obviously has to remain open for a user to navigate this way).

To illustrate this last point:
 ![image](http://recordit.co/UwB9eclDMA.gif)

To attempt to achieve the same results for the "Preview" pane, I followed @Bouncey's lead from #16367 to recreate the logic that allowed the "Map" to remain closed, but after `challenges.submitChallenge` fires, it ends up reopening, so the other panes must need slightly different treatment (I'll leave a separate comment below showing what I tried). 

Using the Redux dev tools I was able to pinpoint, after both actions, that `panes.panesMapUpdated` is the first step where the panes revert back to hidden, but I couldn't figure out what was going on there to prevent it. 

I'd be interested in taking this on, @Bouncey &mdash; would you be willing to provide a little guidance?

**Comment by no-stack-dub-sack** [comment]
[Here's a gist](https://gist.github.com/no-stack-dub-sack/527a37ab2d4cc9a805fe8877a59d1607) showing what I tried. 

Where there are multi-line comments, I changed no code. I've just deleted other lines in the gist to make it easier to digest since this is quite a large file. [Here's the current file](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/Panes/redux/index.js) as it is now.

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack it seems like the prevailing winds are towards keeping the state of the panes between challenges. 

@Bouncey 's initial change was a compromise as it tightly couples state of panes to the content of those panes. 

I propose we remove the logic added to keep the map pane open and instead add logic to keep the panes open state between paneMap transitions. 

This logic can be added where the panesMap is updated between transitions. here: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/Panes/redux/index.js#L172

There is a panesMap created here https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/Panes/redux/index.js#L184

Here, instead of adding new state to track map pane hidden, we can instead use the old state.panesById to pull the value of isHidden.

Probably something like this
```js
 isHidden: state.panesById[name].isHidden || false; 
```

I'd also make use of lodash's `get` method to prevent errors.

**Comment by no-stack-dub-sack** [comment]
@BerkeleyTrue Ok, that makes sense. Thanks for pointing me in the right direction. I'm on it.

**Comment by BerkeleyTrue** [comment]
closed in 62e079c7215fc13296e934ff304b6894e4a45dca
