### ISSUE TITLE
Facing Issue related to completing challenges. Getting something went wrong error. 

### ISSUE THREAD

**Issue by chethanbhat** [freeCodeCamp/freeCodeCamp#16468]
#### Issue Description

Not able to go to next challenge or visit challenges in map. 

Map is totally unresponsive. Cannot visit any links.   Cannot complete and go to next challengesas well by pressing Ctrl-Enter or Clicking Modal. 

I get **Something went wrong** error everytime. Attached screenshots for better understanding. 

#### Browser Information

* Browser Name, Version: Firefox - 58.0b7 (64-bit), Chrome - 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Ubuntu 17.10, 64bit 
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![fcc-beta-0](https://user-images.githubusercontent.com/14086840/34812002-c35e3ed2-f6c9-11e7-9a98-3af1ac5f1e08.png)
![fcc-beta-1](https://user-images.githubusercontent.com/14086840/34812006-cc224f40-f6c9-11e7-8d5e-e844e4a1803a.png)
![fcc-beta-2](https://user-images.githubusercontent.com/14086840/34812009-d030339a-f6c9-11e7-9c6e-f8263a78e4cf.png)
![fcc-beta-3](https://user-images.githubusercontent.com/14086840/34812012-d33568f8-f6c9-11e7-9727-ac5329e9893a.png)
![fcc-chrome-scrshot](https://user-images.githubusercontent.com/14086840/34812145-72e8ffd6-f6ca-11e7-8a1c-c31cf4ef5a76.png)

**Comment by Asjas** [comment]
Hi @chethanbhat 

I reported the same problem in Issue #16433. I am also "stuck" and cannot move through the map. I also tried to clear my Freecodecamp progress but it seems even that fails with a `Something went wrong, please try again later`.

**Comment by chethanbhat** [comment]
Hi @Asjas 

Its really frustrating. Everyday i think of making some progress but not able to do so. Hope fcc teams fixes this !

**Comment by raisedadead** [comment]
Hi @chethanbhat @Asjas thanks for reporting, 

As you maybe aware, we are ironing out issues on the beta platform.
While, we do that the beta website will be unstable, as a consequence. 

You are more, than welcome to try out the platform, but please bear with us as the instability is expected.

Happy coding!

**Comment by dhuber666** [comment]
Hi I have the exact same problem. 
Another thing I found out in the Chrome Debugger Console. 
Every time I click on `Submit and go to next challenge`, I get this error in Console:

`TypeError: Cannot read property 'challenges' of undefined`

Screenshot:

<img width="425" alt="screenshot at jan 16 22-32-05" src="https://user-images.githubusercontent.com/15130832/35013283-29413b2c-fb0d-11e7-88cd-d1b9650d711e.png">

**Comment by raisedadead** [comment]
Update: 

**We have merged a couple of changes and these should make the platform much stable and usable.**
Hopefully we will be deploying them on beta, in a couple days.

Thanks for your patience again.

**Comment by LiteSoul** [comment]
The issue still persists! So it should be an open issue

**Comment by Asjas** [comment]
@LiteSoul Both issues are open. No-one has closed either issue

**Comment by kdesCode** [comment]
Hi All
Agreed still seems to be an issue.
Get the same error. Base in South Africa.
Interestingly on a 4Mbps Fiber connection i get the issue. On a 10Mbps +- 3G connection i do not get the message.  Perhaps some sort of time out setting some where not allow lower bandwidth connections to download all. Just a guess.

**Comment by raisedadead** [comment]
Hi @BerkeleyTrue @Bouncey 

From what I understand the only way to cleanly get around this is to have a pre-loading animation while the bundle is available.

The issue, is that actions done while the bundle is in flight, break due to the RX pipeline. I am not an expert, so do not have a pin point cause. And this subsequently results in the exception being thrown. Post which everything is blocked.

What I mean is that that if we let the intial download / render go through without any interuption, our app performs much better.

Now, I am not saying we should ignore the underlying errors in anyway. They should be fixed. 
But, I think one way to go would be to not perform actions while the app is not ready.

Berkeley's previous fix, on reducing and lazy loading seems to have improved this performance quite good, but, I am afraid even with CDN, a majority of user's behind slow networks (average 3G like speeds) or VPNs are still needing quite a bit before the bundle is available.

I would love some thoughts on the approach here?

**Comment by BerkeleyTrue** [comment]
@raisedadead I'm going to add source maps to beta so we can pinpoint where the error is happening. Hopefully we can find it without having to resort to loading icons, which would remove all the work we are doing make ssr happen.

**Comment by BerkeleyTrue** [comment]
Testing locally it appears the first initial error (the xhr timeout) is the map service. 

<img width="693" alt="rosetta_code_problems__comma_quibbling___freecodecamp" src="https://user-images.githubusercontent.com/6775919/35885704-925bf8ea-0b43-11e8-95e0-c3780d7ade15.png">

This is most likely leading to the other errors but I'm not able to replicate. Adding source maps should help illuminate the problem. The map is definitely a problem, since we've added so many challenges it has ballooned up to several hundred challenges in dozens of blocks. We'll need to optimize this before beta launch. 

A possible solution is to make this a static file but this has the draw back of needed to build for every updated. 

I know this is something that could be solved with graphql, but I'd rather not add more complexity (moving the goal post) to an already hugely delayed project. 

I'm open to other suggestions as well.

cc @Bouncey

**Comment by Bouncey** [comment]
How about splitting the map service into two separate services. 

- map service: provides data for rendering the map UI only
- challenge service: provides data relevant to the current block/superblock only. Provides other blocks/superblocks on request.  I.e the user finishes a block and moves on to the next block. Logic for this could be `when executing a challenge, check to see if the current challenge is the last in the current block. If so, request the next block in anticipation`

**Comment by BerkeleyTrue** [comment]
That could be done, the map service would just deliver the map tree. We then use the rest api (which has limit/skip) to get the rest of the information. This would add some complexity but it wouldn't be so bad.

**Comment by Bouncey** [comment]
Would you even need to skip/limit? We could just request by block name. If my current challenge is in the ES6 block, I don't need the redux block, or any of the others. Only the ES6 block. 

If I click on a challenge outside of my block and the data is not in the store, I could have a loader rendered while the challenge service brings me the data for that block.

We could even take it as far as caching the blocks in local storage, but that would be down the line

**Comment by BerkeleyTrue** [comment]
We could just pull a block and all it's challenges, but keep in mind that some blocks have dozens of challenges.

**Comment by Bouncey** [comment]
That's what I was trying to say. One block's worth of challenges in a single payload is a lot lighter than all of the challenges from every block. If the user doesn't need it right away, we shouldn't send it.

**Comment by BerkeleyTrue** [comment]
Agreed

**Comment by kdesCode** [comment]
I am no expert and know very little. Just started the journey to learn all this.
But just another guess, is there no where one can change the timeout limit? Perhaps make it higher to allow lower bandwidth connections time to download.

**Comment by Bouncey** [comment]
@kdesCode Whilst that would help in alot of cases, the simple fact is we are sending around 6MB of challenge data to everyone, even when they don't need it. The fix suggested is to send selected chunks of challenges that are relevent to the user.

This will reduce the amount to be downloaded, which will have the side effect of reducing the time required for the request to complete.

**Comment by jkao1** [comment]
The direction of this issue's discussion is apparent: Apollo client with GraphQL/Express server. This is just something I wanted to propose, but a migration would definitely delay the release greatly.

**Comment by LiteSoul** [comment]
Well, anything is better that the current state which is virtually unusable.
Me learning GraphQL is just months away, sorry I can't contribute right now... but maybe Bouncey suggestion is simpler

**Comment by Bouncey** [comment]
@BerkeleyTrue 
![A graphiql view of the mapUi](https://user-images.githubusercontent.com/18572518/36146133-89c11248-10ab-11e8-84ad-c68b419321ad.png)

**Comment by raisedadead** [comment]
Sweeeet!

**Comment by jkao1** [comment]
Amazing! If you need any help with Apollo I'm down

**Comment by LiteSoul** [comment]
@chethanbhat , @dhuber666 , @kdesCode do you still experience the issue? It may have been fixed. I have it sometimes, but not all the time.

**Comment by Bouncey** [comment]
Cross-posting so that you can still keep working on the challenges until we get this fixed

>What you could do to keep the challenges coming is navigate directly to the challenges themselves. Hovering over the challenge in the map will show you the address of the next challenge.

![hover for url](https://user-images.githubusercontent.com/18572518/36533311-1200926c-17bb-11e8-8b88-513b546df09e.png)

>I know this is not ideal, I should have a PR ready today.
