### ISSUE TITLE
Conflicting instructions on Waypoint: Target a Specific Child of an Element Using jQuery 

### ISSUE THREAD

**Issue by TwoScoop** [FreeCodeCamp/freecodecamp#1646]
In the instructions it states to make the first child in each of your well elements bounce.  This conflicts with the first checkpoint which states that the second element in each of your "well" elements should bounce.

![screenshot 3](https://cloud.githubusercontent.com/assets/7795750/9141852/b8a5f95c-3d09-11e5-9837-c74ad485cf47.png)

**Comment by BerkeleyTrue** [comment]
this is being tracked in #1713

**Comment by bbhanda2** [comment]
use  the following code, misleading info on mine also

$('.target:nth-child(2)').addClass('animated bounce');

this worked on mine.. took half hour to do this one. Yes the info is misleading

**Comment by Saladg** [comment]
Thanks @bbhanda2

**Comment by 1985michel** [comment]
@bbhanda2 it's a bug.

**Comment by naveenlb** [comment]
Thanks guys. I am really enjoying the camp.

**Comment by egossick** [comment]
So what does the "2" do? Don't understand that and why it needed to be changed from "3". Thanks!

**Comment by MixRadu** [comment]
Why we use .target ? Why i can't use 
`   $('.well:nth-child(2)').addClass('animated bounce');`

**Comment by jch1n** [comment]
I have 3 #target5 button.. can someone help?


[image](https://cloud.githubusercontent.com/assets/23186465/21548679/be1a92e2-ce28-11e6-82bc-d837f39d9254.png)

**Comment by trustyaxe** [comment]
I also, initially, used this: $(".well:nth-child(2)").addClass("animated bounce");
Why is this not correct? It would target the .well for both and animate the second button in each well. Can someone please explain this?

**Comment by trustyaxe** [comment]
After looking at it for a while, I believe they had us add the target class to every button solely for pinpointing them with jQuery. Each button has these classes (separated by a space): btn btn-default target. The word target is a class as well as btn btn-default. They had us use target in the $(".target:nth-child(2)").addClass("animated bounce"); and then use the :nth-child(2), which should select the second button for each well (right-well, left-well). I suppose we could have used the word "elephant" in place of target, since the word is there only for us to use with jQuery. It is independent of any CSS. This is how I understand it to be and I welcome any feedback or advice. I hope this helps in some way.

**Comment by trustyaxe** [comment]
After looking at it, it dawned on me. Here is some text from the challenge: jQuery uses CSS Selectors to target elements. target:nth-child(n) css selector allows you to select all the nth elements with the target class or element type. We gave all of our buttons these classes, separated by spaces: "btn btn-default target". So, the jQuery command we are using is specifying the second instance of target in each well. How? I don't know, because it looks like it should be $(".well:nth-child(2)").addClass("animated bounce);, since the exercise is calling for you to target children and not pinpoint directly.  I think there should be a more detailed explanation on the exercise page about this. Very confusing and I hate not knowing something before I move to the next lesson, lol.

**Comment by mithun2017** [comment]
$(".target:nth-child(2)").addClass("animated bounce");

**Comment by gouserizvi** [comment]
$(".target:nth-child(2)").addClass("animatted bounce");
is the answer 
 ityped the same code earlier but it doesnt worked but after a long struggle it worked 
swwms like a bug to me
