### ISSUE TITLE
High latency when accessing beta.freecodecamp.org

### ISSUE THREAD

**Issue by capozzic1** [freeCodeCamp/freeCodeCamp#16469]
#### Issue Description

I am located in Daegu, South Korea, and have been trying to attempt the interview data structure questions, but I have high latency on a 50mbps download connection. When I use a VPN, I still have high latency. Sometimes the page just times out. I'm not sure how I could show this to you guys. Is there a way you could check your hosting to see if non-US countries are somehow set to a lower priority for traffic? 

Example url: https://beta.freecodecamp.org/en/challenges/coding-interview-data-structure-questions/delete-a-leaf-node-in-a-binary-search-tree

#### Browser Information

* Browser Name, Version: Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: ASUS GL552VW laptop

#### Your Code

```js



```

**Comment by raisedadead** [comment]
> Is there a way you could check your hosting to see if non-US countries are somehow set to a lower priority for traffic?

All traffic is served over CloudFlare's CDN in front of DigitalOcean. We have no special geo-setting that should block you from accessing the content.

We will take a look, but while we do, we recommend, you should lookup about issues from these providers in the location and the network you are on.

Note: If you are on the beta, site we are definitely seeing some spikes in the response times, most notably, because of the stability of the beta code-base, that said there is no error rates as such.

**Comment by raisedadead** [comment]
Hi @capozzic1 is this still an issue for you?
