### ISSUE TITLE
[beta] Question 1 code gets appended to every other subsequent question.

### ISSUE THREAD

**Issue by saurishkar** [freeCodeCamp/freeCodeCamp#16483]
#### Challenge Name

[System Design and Concept Questions](https://beta.freecodecamp.org/en/challenges/system-design-and-concept-questions/arrayprototypemap)

#### Issue Description

The code of Question 1 gets appended to all the other Questions.

#### Browser Information

* Browser Name, Version: Firefox 57.0.4 64-bit
* Operating System: Mac OSX Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![Image](https://user-images.githubusercontent.com/19742306/34896577-518441b0-f810-11e7-8b18-6251b80fea5b.png)

References #16229

**Comment by raisedadead** [comment]
We need help in investigating the root cause for this.

**Comment by warborn** [comment]
I took a look and i found that the problem is due to the dangerouslySetInnerHTML behaviour inside the Quiz component (common\app\routes\Challenges\views\quiz\Quiz.jsx)
```jsx
<p dangerouslySetInnerHTML={{ __html: question.question }} />
```

"I think this could be related to React's diffing algorithm that might not properly treat a component with a dangerouslySetInnerHTML statement if that component gets rerendered multiple times with different inner content." https://github.com/facebook/react/issues/377#issuecomment-100676012

I tried the proposed solution in the above issue, i defined a unique key for the paragraph but it didn't work, so i placed the key in the root level element as follows:

```jsx
<div key={currentIndex.toString()} >
```

With this the first question isn't appended to subsequent questions anymore, leaving the code like this:

![image](https://user-images.githubusercontent.com/10677789/34910935-790a3c7a-f884-11e7-91cc-4f1356110e10.png)

@raisedadead If you think this is an optimal solution i can make the PR

**Comment by raisedadead** [comment]
Hi @warborn nice work, and thanks for taking the time analysing this. Seems, fine to me. I think you should make a PR and we can proceed from there.

Happy contributing
