### ISSUE TITLE
Modern Challenges: unwanted bracket renders at end of async test messages

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#16528]
As first raised by @r1chard5mith in #16312, any `async` test in the modern challenges (React, Redux, React-Redux) has an unwanted closing bracket that renders as text at the end of the test case message:

<image src="https://user-images.githubusercontent.com/18563015/35129506-f0292204-fc89-11e7-9aba-76db67503135.png" height="300px" />

@BerkeleyTrue this seems to be new since we changed the async test syntax. Any idea what's going on here?

@r1chard5mith did you ever have any luck figuring this out?

**Comment by r1chard5mith** [comment]
Thanks @no-stack-dub-sack - I'll just add that part of the changes I made that ended up in https://github.com/freeCodeCamp/freeCodeCamp/pull/16515 fixed a similar issue with some non-async tests that was having a similar result.

` +        "assert.strictEqual(Enzyme.mount(React.createElement(MagicEightBall)).children().childAt(0).name(), 'input', 'message: <code>MagicEightBall</code>&apos;s first child should be an <code>input</code> element.');", `

Before I changed the delimiters on the message string, these were also outputting the remaining chars `);` to the screen. 

So it seems that for whatever reason, when the message string isn't properly formed it outputs everything to the end of the line. In the case of the async tests, I couldn't find a way to form them properly. Removing }; from the end would raise an error that the function wasn't closed and putting them back would both close the function AND output those chars to the screen.

My guess is this is something to do with how the tests are being interpreted, since afaict the tests are properly formed.

**Comment by no-stack-dub-sack** [comment]
Thanks @r1chard5mith, hopefully @BerkeleyTrue will be able to shed some light on this, as he's much more familiar with the inner workings of how these tests are interpreted, executed, rendered. I've seen the other problem you mentioned before as well, and I too was unable to figure out how to correctly form these to fix the issue. 

There's a lot of other higher priority issues going on now, to be fair, so don't be too surprised if this one ends up taking a back burner, unless there's a super simple fix for it, which there may be. 

Believe it or not, before the current async syntax, we were using something like: 

`(async () => { ... })(); // message: MagicEightBall's first child should be an <code>input</code> element.`

...wait... test message as a comment?? And it actually worked! So not quite sure how this is working, but thanks for raising the concern, it's def a valid one.

**Comment by BerkeleyTrue** [comment]
The logic that pulls the message happens here https://github.com/freecodecamp/freecodecamp/blob/staging/common/app/routes/Challenges/utils/index.js#L121

`('' + test).split('message: ').pop().replace(/\'\);/g, '')`

**Comment by no-stack-dub-sack** [comment]
ahh, got it. Should be an easy enough fix from here. 

@r1chard5mith are you interested in taking this on? Let me know, otherwise I'm happy to do it.

**Comment by ninadingole** [comment]
@no-stack-dub-sack I will correct these typos I have done similar changes to other challenge.

**Comment by no-stack-dub-sack** [comment]
@ninadingole nice job! I hate regexp, so I commend you for taking this on 😄
