### ISSUE TITLE
"str2 not defined" - es6: declare-a-readonly-variable-with-the-const-keyword

### ISSUE THREAD

**Issue by raiden357** [freeCodeCamp/freeCodeCamp#16584]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/declare-a-readonly-variable-with-the-const-keyword

#### Issue Description
the problem occurs because of this line of code(line 9): 
`console.log(str2)`. 

The console tries to log **str2** but the parameter doesn't exist.

solution: i just removed the 2 and made it **str** and it solves the problem, because it references the correct paramater.

#### Browser Information

* Browser Name, Version: Firefox 57.0.4, Chrome 63.0
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

**Comment by ninadingole** [comment]
I can resolve this issue if anyone approves that the str2 in the seed is not right.

**Comment by raisedadead** [comment]
In this challenge, we ant these below changes:
https://github.com/freeCodeCamp/freeCodeCamp/blob/0e6feee1381b67efc55ea3682321f077a9d781ba/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L127

`str2` to `str`

and
https://github.com/freeCodeCamp/freeCodeCamp/blob/0e6feee1381b67efc55ea3682321f077a9d781ba/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L133

`FreeCodeCamp` to `freeCodeCamp`

**Comment by ninadingole** [comment]
Ok I will make the changes and raise a PR, thanks for the confirmation.

**Comment by raiden357** [comment]
Should I close this issue now ?

**Comment by yoizfefisch** [comment]
I think it should be: `console.log(sentence);` and it should test for "freeCodeCamp is cool!" to confirm that the user updated this line to all-caps as well. Otherwise, the constant in this function has no use and thus creates confusion.

@raiden357 @raisedadead @ninadingole Agree?
BTW, I have a feeling that this is what bothered @Bouncey  in #16619:

Additionally, information in [the next challenge](https://beta.freecodecamp.org/en/challenges/es6/mutate-an-array-declared-with-const) is important for users before they can do this one because at first it seems odd to declare `sentence` as a constant since it is being mutated by the `str` variable.

**Comment by raisedadead** [comment]
Hi @yoizfefisch thanks for reporting. If you could raise a fresh issue, it would be awesome! We can discuss on how to improve the challenge.
