### ISSUE TITLE
BETA: Online fonts alternative to Google

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16647]
#### Challenge Name
Basic CSS: Import a Google Font
https://beta.freecodecamp.org/en/challenges/basic-css/import-a-google-font

#### Issue Description
1) You reference the Google fonts site, which is a good place to get fonts, but you know that some countries block Google.  Why not choose an alternative, such as one of these:
www.1001fonts.com/
www.fontspace.com/category/handwriting
https://www.cssfontstack.com/
https://www.fontsquirrel.com/

or any of the other free font sites?  Then you won't have to worry about learners having to skip specific challenges.  And, if Google is that important (the NSA loves them!), then you can reference them (and other resources, if you like) within the challenge.

3) This challenges teaches about multiple fonts being listed, but it doesn't accept it if I add an extra font.  Why not, since it's already been introduced?

3) (For all challenges) One thing I don't like about your challenges is the complete lack of links to external resources that are relevant.

#### Screenshot
![image](https://user-images.githubusercontent.com/35181004/35823958-e4894474-0a76-11e8-9963-280ecbb9f4c7.png)

**Comment by zk433** [comment]
Hi @ReveurGAM ,
thank you for your post.
As for other free fonts, I quickly looked through them but from what I can see, you need to download them to your computer in order to use them. The advantage of Google fonts is that you can link to it without having to download it. Please correct me if I'm wrong and I missed the option to link to the fonts on the sites you mentioned.

As for the lack of external resources, I think the approach freeCodeCamp takes is to Read, Search, Ask method. Instead of hand-feeding the campers every single piece of information, it is encouraged that campers learn to search themselves, a skill that is more than useful in the world of coding.

**Comment by raisedadead** [comment]
Hi @ReveurGAM thanks for the feedback. 

There is a basic, philosophy that we follow, curate content from the community contributions and keep it as simple as possible.

Here is our challenge style guide if you are very keen on why:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md

We urge, you to keep the issue reports succinct if possible, which will help us triage, and decide the course of action.

Now, coming to your queries:

> 1. You reference the Google fonts site, which is a good place to get fonts, but you know that some countries bloc...

Yes, we are very aware of this fact. But that said we have to keep is as close to the relevance of the challenge as possible, support like CDN, alternative resources, etc, are all discussed on our forums, chat rooms, and community resources. 


> This challenges teaches about multiple fonts being listed, but it doesn't accept it if I add an extra font. Why ...

That's what precisely projects are for. You are free to play with any resources at your disposal. Challenges, are for teaching one concept, a small one at a time, and not adding all related information, just because it can be done. 

>  One thing I don't like about your challenges ...

I agree to some extent on this, but to augment we do have guides for those, which are again community curated. They may not be exhaustive, but we do welcome PRs for that.

----

That said, I would have to close this as there is no actionable changes here, please re-open if you have any further suggestions. 

Thanks a lot for the feedback.

Happy coding!
