### ISSUE TITLE
it won't accept closed audio element

### ISSUE THREAD

**Issue by milosrancic** [freeCodeCamp/freeCodeCamp#16721]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element

#### Issue Description

It keeps asking me to close audio element, even though i closed it. Tried to reset code, even refreshed the page, still the same. 

#### Browser Information

* Browser Name, Version: Google Chrome, Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System: macOS High Sierra
* Mobile, Desktop, or Tablet: MacBook Pro 13"

#### Your Code

```js

<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiaxs screen reader in action.</p>
    
    <audio controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" />
    </audio>
    
  </main>
</body>



```
#### Screenshot

<img width="1280" alt="screen shot 2018-02-15 at 23 44 53" src="https://user-images.githubusercontent.com/25804447/36285018-4c29f494-12aa-11e8-9892-3c82314868d0.png">

**Comment by jkao1** [comment]
Could you provide a screenshot of the tests section? It would be helpful to know which test broke and what error it spouted out.

**Comment by jkao1** [comment]
Strange...this was an issue about a week ago (#16645) and it was fixed by pull request #16653. Yet, I replicated this error (`"Cannot read property 'length' of null"` in the tests console) on <https://beta.freecodecamp.org>. However I've tested your code on my local staging branch and everything works fine.

#16653 was merged early last week, supposedly fixing the troublesome test we're encountering now. The snippet that follows is the code for the current test on the `staging` branch:

```js
assert(
  code.match(/<\\/audio>/g) && 
  code.match(/<audio controls>/g) && 
  code.match(/<\\/audio>/g).length === code.match(/<audio controls>/g).length, 
  'message: Make sure your <code>audio</code> element has a closing tag.'
)
```

JavaScript has [short-circuit evaluation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators), and it is apparent from this code that the `length` property can never be taken from a null value.

@raisedadead perhaps you could weigh in on this difference between `staging` and <https://beta.freecodecamp.org>?

**Comment by raisedadead** [comment]
Hi @jkao1 yup, we deploy staging branch to the beta.freecodecamp.org once every couple days, it is possible that the fix has not been deployed yet.

**Comment by raisedadead** [comment]
Yes, I just confirmed that we need to deploy a fresh release on the beta, sorry about the delay. I'll check with @BerkeleyTrue if it supposed to be done soon. 

Closing as fixed.

**Comment by Jd536** [comment]
Still the same issue. 
<audio></audio>
I still  have the error message"Make sure your audio element has a closing tag."

**Comment by jkao1** [comment]
@Jd536 could you provide your cocde?

**Comment by francodelera** [comment]
I've got the same issue, and rechecked everything lot of times, but it keeps telling me the same: "Make sure your audio element has a closing tag." Anybody solved it?

**Comment by camachado** [comment]
Just came across this issue as well.

![image](https://user-images.githubusercontent.com/2438129/41331818-05b21d9c-6ea9-11e8-98db-9d197cd156c1.png)

**Comment by raisedadead** [comment]
Can someone please report a fresh issue on the tracker.
