### ISSUE TITLE
Beta does not work in Internet Explorer

### ISSUE THREAD

**Issue by pachniakj** [freeCodeCamp/freeCodeCamp#16756]
#### Issue Description
Hello All,

I am having browser issues with the Beta version of FreeCodeCamp on my work PC and am wondering if you know if there are settings that I may need to change. None of the links in the webpage seem to be working for me and the area where you normally type your code is a black box that has a vertical white line that moves horizontally across it from left to right. Let me know if you have any thoughts why this is happening. As an FYI, the none Beta version of FreeCodeCamp works fine on my PC and the Beta version works on my Iphone.

Thanks!

#### Browser Information

* Browser Name, Version: Internet Explorer
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![beta freecodecamp issue](https://user-images.githubusercontent.com/36675471/36442228-f1b9737e-166c-11e8-9eb4-669c69065c6f.png)

**Comment by jkao1** [comment]
A persistent skeleton on the code mirror and the broken links usually mean something broke in React and the virtual dom flipped a table. Could you post a screenshot of the error console?

**Comment by pachniakj** [comment]
I am really new to coding so what is the best way to get to the error console?

Thanks!

**Comment by pachniakj** [comment]
Is this what you are looking for?

![error console](https://user-images.githubusercontent.com/36675471/36452382-2d19e092-168c-11e8-88d4-fffc29d262f9.png)

**Comment by systimotic** [comment]
@pachniakj Thank you for testing out the beta!

The new version of freeCodeCamp does not work on Internet Explorer. It's also a broken (although not quite as much) in Edge. I believe we do intend to support Edge, but not Internet Explorer. Chrome and Firefox work fine, can you try one of those?

**Comment by Ishtmeet-Singh** [comment]
@systimotic Those beta challenges are supposed to work alright? They seem not to be working. Whenever I try to expand the map, it's showing error "Something went wrong". I've been seeing this error for more than 2 days now. In console, it's throwing an error "require not defined". Maybe, you could check that?

**Comment by alysabax** [comment]
I am having the same issue as OP. except i am using a mac and am on chrome! its been like this for the last 48 hours! I am also unable to navigate away from this page once in. i.e unable to click to move to map or press the get help from the forum - just nothing happens! 
<img width="1280" alt="screen shot 2018-02-21 at 10 00 47 am" src="https://user-images.githubusercontent.com/35865223/36454902-f60fb7be-16f1-11e8-8f9a-abb19c9b796f.png">

**Comment by jkao1** [comment]
Can you send a screenshot of any potential error in the console?

**Comment by alysabax** [comment]
<img width="1280" alt="screen shot 2018-02-21 at 10 38 53 am" src="https://user-images.githubusercontent.com/35865223/36455261-7a636578-16f3-11e8-86f5-00ec19d717c3.png">

is this what you're after?
thanks for your help!!

**Comment by alysabax** [comment]
<img width="1280" alt="screen shot 2018-02-21 at 10 47 35 am" src="https://user-images.githubusercontent.com/35865223/36455543-ac8f01f0-16f4-11e8-8a95-3838d81ae64e.png">
this is what it says when i follow the link!

**Comment by vkWeb** [comment]
@jkao1 @systimotic @pachniakj Confirmed. I cleared all my browsing data i.e. cookies and cache and made a new account but still, I'm not able to proceed after the third step and the map is not responding to my clicks.

![2018-02-21 4](https://user-images.githubusercontent.com/26724128/36470247-2fce5136-1710-11e8-87e3-afff908c8c45.png)

**Comment by Ishtmeet-Singh** [comment]
@alysabax I am using mac too and on chrome.

**Comment by systimotic** [comment]
Thanks for all of the extra information everybody! I've determined that there are at least three separate issues here:

1) The original issue with Internet Explorer reported by @pachniakj. Due to the error below, it does not run at all, regardless of which challenge you're currently doing.
![20180221_15-22-30_iexplore](https://user-images.githubusercontent.com/7262039/36485092-92caeb9a-171b-11e8-9b01-6d571be5db29.png)
2) The challenge loading issue reported by @alysabax. I originally could not reproduce this either (like @jkao1), but I figured out that I only got this issue when I refreshed the page. This problem is specific to the "Change the Color of Text" challenge and is caused by a change made 8 days ago. I've opened a new issue about this: #16762. Please leave further comments on this problem on that issue.
3) The step challenge finishing problem @vkWeb is experiencing. I can not reproduce this issue. If I had to guess, I'd say it's a network issue (the error says a request timed out). @vkWeb Can you try going to the "Network" tab in the devtools, reloading the page, going to the point where it throws the error, taking a screenshot of the network tab and sharing both the current and the new screenshot in a new issue with any other information you have?
4) I'm not sure what issue @Ishtmeet-Singh is experiencing. @Ishtmeet-Singh Are you able to tell if your problem is the same as one of the issues mentioned above, or is it a different problem? If it's a different problem, please open a new issue with more info (where does the error happen, screenshots of the page and console, browser version, anything else that could help).

This issue is only for `#1`, the Internet Explorer problem. If you're experiencing a different problem, please open a new issue with as much information as possible.

---

I believe we don't support Internet Explorer anymore, but I thought we did support Edge (neither works). @raisedadead Can you confirm this? 
We might want to show a message in browsers we don't support.

**Comment by Bouncey** [comment]
@systimotic a fix for the issue that @vkWeb reported has just this moment been pushed to beta, please have another look :+1:

**Comment by raisedadead** [comment]
> I believe we don't support Internet Explorer anymore, but I thought we did support Edge (neither works). 

We should ideally support all latest LTS browsers, just like major platforms. 

Example:
https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else > Scroll to bottom for a list.

**Comment by vkWeb** [comment]
@systimotic My issue is fixed. Now, I'm able to sign-in and everything works fine. Thanks to @Bouncey.
