### ISSUE TITLE
[Beta] Passwordless Auth is not working for existing users

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16753]
### Issue Description
Passwordless auth is not working for me, I'm unable to sign-in. Showing error: `ERR_TOO_MANY_REDIRECTS`. 

### Browser Information
* Browser Name, Version: Chrome & Firefox (latest).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by raisedadead** [comment]
> Browser Name, Version: Chrome & Firefox (latest).

Please share the version you are on at time of reporting, `latest` can mean anything.

Also, please add some screen shots, preferably of the browser DevTools as well.

**Comment by tchaffee** [comment]
I am seeing this same error when running a copy of the software locally. Here is what I'm seeing in the server logs:

```
0|server   | 302 GET 35.993 ms - /en/passwordless-auth/?email=xxx==&token=xxx
0|server   | 302 GET 9.026 ms - /passwordless-auth/?email=xxx==&token=xxx
0|server   | 302 GET 7.014 ms - /en/
0|server   | 302 GET 20.112 ms - /en/challenges/current-challenge
0|server   | 302 GET 388.736 ms - /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate
0|server   | 302 GET 218.667 ms - /en/
0|server   | 302 GET 13.142 ms - /en/challenges/current-challenge
0|server   | 302 GET 252.020 ms - /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate
0|server   | 302 GET 7.647 ms - /en/
0|server   | 302 GET 18.510 ms - /en/challenges/current-challenge
0|server   | 302 GET 345.841 ms - /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate
0|server   | 302 GET 5.400 ms - /en/
0|server   | 302 GET 7.454 ms - /en/challenges/current-challenge
0|server   | 302 GET 297.468 ms - /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate
0|server   | 302 GET 13.136 ms - /en/
0|server   | 302 GET 9.062 ms - /en/challenges/current-challenge
0|server   | 302 GET 262.304 ms - /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate
```

I cannot find anywhere in the code why it is trying to go to `responsive-web-design-certificate` for the current challenge.

**Comment by tchaffee** [comment]
This is happening on multiple browsers. Confirmed Safari on Mac and Chromium on Ubuntu.

**Comment by raisedadead** [comment]
I am unable to reproduce on local, and the beta monitoring page does not have any such indication, leading me to the understanding that this is not happening on the beta site itself?.

Comments from OP or @tchaffee do not confirm if its the case for the beta site.

If at all this is reproduced at your end on local then this can be isolated to code changes within the last 4 weeks (since last deploy on the beta site), going by the status page.

Looping in contributors who have made commits during the time frame, to the related areas.

@Bouncey @BerkeleyTrue

**Comment by vkWeb** [comment]
@tchaffee Please log out and try signing in to the beta live site and tell if you're facing the same problem as I'm facing. 

@raisedadead There's nothing in the console.

**Chrome[Version 64.0.3282.167 (Official Build) (32-bit)]**

![2018-02-21](https://user-images.githubusercontent.com/26724128/36468158-43c16622-1708-11e8-892b-79cdb4ab7c6c.png)

**Firefox[58.0.2 (32-bit)]**

![2018-02-21 1](https://user-images.githubusercontent.com/26724128/36468462-7379df92-1709-11e8-9ff6-c57100409aa9.png)

**Comment by Bouncey** [comment]
@raisedadead @tchaffee @vkWeb I can confirm this and I have a fix for it. I found it yesterday and implamented it in a PR I am working on. I thought it was due to a unique set of circumstances I found myself in. But then I saw this comment from @tchaffee in  Contributors chat

>  I am running fCC on my own server and I have passwordless sign-in with Amazon SES working. But when users sign out and then go back to the site they are getting a redirect loop warning. Looking at the logs the /en/challenges/current-challenge is sending them to /en/challenges/responsive-web-design-certificate/responsive-web-design-certificate. Which doesn't seem right. Any ideas?

I will have a patch submitted shortly

**Comment by vkWeb** [comment]
@Bouncey Great! I'll be waiting for the fix.
