### ISSUE TITLE
[Beta][Discussion] Do we really need preview, lesson and editor panel toggle controls? 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16824]
### Issue Description
I was thinking about all the possible ways of making the panel UI more interactive. @QuincyLarson suggested me to make it look like JSBin.com's panel controls but one question stuck my mind yesterday that "Do we really need the preview, lesson and editor panel toggle controls?". I really don't think so. 

We should think as a camper in this case and I realised that a camper will never use preview, lesson and editor toggle controls in their journey. I know in future we'll be adding multiple file support (HTML, CSS, JS in each pane) but that's a totally different route. 

If you think we need them then please tell me one instance in which it'll be helpful or it'll be of good use. 

Tagging core team members for input: 
@QuincyLarson, @BerkeleyTrue, @Bouncey, @raisedadead, @systimotic, @tchaffee.

Before making any decision please ask yourself once "Why do I (as a camper) will need to toggle editor, lesson or preview panels?". The answer will be "I'll need them always!".

**Comment by jfines** [comment]
If you're referring to a tiled type view or something like split panes?  Personally, I like seeing certain things at the same time rather than flipping back and forth between them. When I work in my editor I always use spit panes. I often place an html file in one pane then css and js in its own pane. I can flip back and forth between the latter but will always have my main file (html) open along with either of them.  Personally, I do need to see things together at the same time (it helps me reference things in the 'other' file easily so I don't end up flipping back and forth more than necessary).

I hope that wasn't off base. Did I understand the question correctly?  I am a camper btw. And have been getting set up to contribute these last couple days. Not sure if my opinion counts but that's what I think about it.

Peace  :)

**Comment by vkWeb** [comment]
@jfines No, it's not off base. 
So, shouldn't we remove the toggle controls of the panel, editor and lesson panes from the beta? As you said you work in split panes that's how fcc beta is designed too. So, toggling doesn't make sense to me. Anyways, there must be some thinking about why this functionality was implemented which core team members will tell.

Btw Even I'm a camper and everyone's opinion is counted. :)

**Comment by moT01** [comment]
@vkWeb I see a specific case toggling the lesson panel... I have a small screen and the editor panel wraps the code onto new lines which I find annoying - so I can close the lesson and see the editor more clearly.
There's a somewhat similar discussion here https://github.com/freeCodeCamp/freeCodeCamp/issues/16382 - I see you're active there. Also, probly a separate topic, but I think that editor panel shouldn't wrap the code and there should be a horizontal scroll bar - when that panel gets a little narrow it gets real messy fast.

**Comment by jfines** [comment]
**@vkWeb**

I can't really imagine another way of doing it. That doesn't mean there isn't one - just that I may not be creative enough to think of one. At any rate, shouldn't there be a way to control what you have to deal with or not? Having more control can be a double edged sword really. I can provide more flexibility (which is great) but than it can add complexity also. For what's being talked about here I don't think it can get complex enough to be a problem.

What about having horizontally aligned tabs (like browsers do) and then be able to drag then out to make split panes in various layouts (horizontal or vertical splits with possibility of up to 2 tabs in one pane). Maybe even an item in a context menu to "split window".  This would be a way to teach campers by way of use how to use split panes in their editors / real life projects and keep it simple enough to that it won't be overwhelming. So a choice of all tabs or any combination of a 1 x 2 split window were you get two panes with 2 tabs in one pane and one tab in the other and you can arrange the tabs in any 1 x 2 combination you want? Or add to that a third option of 3 dedicated panes? Sounds challenging to program though.

Idk, that's what I got.

:)

**Comment by QuincyLarson** [comment]
The main reason we need control of the different panes is that we plan to add additional panes in the future. Right now, we just have a single code editor, but we plan to split it out into HTML, CSS, and JavaScript (and potentially even multiple files of each) - so we want to be able to control which is visible.

Also, many people are using different device sizes. It would probably only be practical to view a few panes on an 11" monitor, but if you're on a large 4k monitor, you might be able to comfortably have 5 or 6 open at once. We want to give the user full control, rather than only trying to optimize for their viewport width.

JSBin.com faced this problem a long time ago and I think they've come up with an elegant and time-tested solution to it with their pane toggle bar.

**Comment by mstellaluna** [comment]
Personally, I like being able to control the environment in which I am working in. Definitely the map is never open for me. I prefer to have only the lesson and the editor open. The preview pane I only open before running the tests for the lesson. I don't think it wise to enforce a certain view or layout on campers as each person works in their own comfort level.

**Comment by vkWeb** [comment]
@moT01, @jfines, @QuincyLarson, @mstellaluna Yes - I see a point in all of your opinions, panel toggle gives a lot of flexibility. Thank you so much for the response 😄. 

Closing this issue since I've understood the reason "why this functionality was added".
