### ISSUE TITLE
Legacy Authentication needs better error handling

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16855]
If you attempt to sign in using a legacy authentication method and it fails, beta will currently redirect you to `http://localhost:3000/auth/[social auth method]` and gives you a cryptic message.

![profile___freecodecamp](https://user-images.githubusercontent.com/985197/37182412-cf5726be-22f6-11e8-853f-e713188dfad0.png)

Instead, it should redirect you back to /deprecated-signin and tell you "We couldn't find a freeCodeCamp account associated with that [social auth method] account."

**Comment by raisedadead** [comment]
Looks like something has changed in the routing. I'll take a look. @Bouncey would you have an idea on this?

**Comment by Bouncey** [comment]
It looks like the react routes are picking this up as a request for a profile page. Could boot script order mitigate this?

**Comment by raisedadead** [comment]
```
200 GET 713.087 ms - /auth/github
  fcc:services:challenge sourcing challenges for the basic-html-and-html5 block +2s
304 GET 81.571 ms - /api/users/get-messages
200 GET 42.734 ms - /services/user?_csrf=.......&returnMeta=true
  fcc:services:mapUi generating mapUi for auth +140ms
200 GET 449.941 ms - /services/challenge;blockName=basic-html-and-html5;lang=auth?_csrf=.......&returnMeta=true
304 GET 75.086 ms - /api/users/get-public-profile?username=github
200 GET 542.880 ms - /services/map-ui;lang=auth?_csrf=.......&returnMeta=true
```

Here is a sample log.

I tried changing the boot order of scripts, and I guess I am missing something.

On that note, why are we hitting all the three services for user anyway? Is it intended?

**Comment by raisedadead** [comment]
In any case, I strongly believe something in the routing is the culprit. The page from where this is triggered is a static page.

Hence for my understanding the request should have trickled down the express middleware list, unless I am mistaken.

**Comment by BerkeleyTrue** [comment]
The problem here is the /:username route. A long time ago, I discussed with @QuincyLarson about changing this to /user/:username, but he veto'd in favor of better SEO. This has caused me huge headaches ever since. For instance, we have a [blacklists](https://github.com/freecodecamp/freecodecamp/blob/staging/server/utils/constants.js#L1) of usernames that cannot be used or the /:username express endpoint would break the site in many ways.

It also seems the logic for lang routes is confusing `auth` as a possible lang tag, which should not be the case we support only a subset of langs (two ATM).

These logic circuits work fine in express, so we need to make sure they are replicated faithfully in the react app. 

We also have to do add special routes that should not hit our express [endpoints](https://github.com/freecodecamp/freecodecamp/blob/staging/server/utils/lang-passthrough-urls.js) (These two files should be consolidated).


If we could change this it would solve a lot of issues for us, but I don't think we should be moving the goal posts any longer, beta is long overdue.

Maybe some combination of checking the passthrough urls and adding a blacklist service with an async hook to the route might solve the problem.

**Comment by raisedadead** [comment]
Hmm I see that this is a more complicated problem than I initially thought, could just be a minor oversight. 

I am not sure how the SEO is even affected, considering the user profiles have been dynamic routes from the very outset. But, I should be wrong if the analytics prove otherwise.

In any case, I agree regarding the routing, there should be just a single source of truth.

But coming to the current status, this is indeed a show stopper for shipping, because we have the legacy login completely broken.

> Maybe some combination of checking the passthrough urls and adding a blacklist service with an async hook to the route might solve the problem.

Can you elaborate on this part a little more, if you have some time? I'll keep digging for future proof solution, and in the worst case we can have the stop gap patch in my linked PR (which now I agree is not good at all).

**Comment by raisedadead** [comment]
Okay I didn't have much time, but I am dumping my observations here. So any pointers to consolidate will be appreciated:

This below check is never called:

https://github.com/freeCodeCamp/freeCodeCamp/blob/8145a9ceb1ebbb1f64320b208eab5ec1d50e0f06/server/middlewares/add-lang.js#L17-L22

because what I think is this bit

https://github.com/freeCodeCamp/freeCodeCamp/blob/8145a9ceb1ebbb1f64320b208eab5ec1d50e0f06/server/middlewares/add-lang.js#L64-L66

handing over the flow to the next middleware?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @raisedadead I understand that having the usernames right off the root is a headache. This has become a convention, though, and GitHub, Twitter, and most consumer websites do this. If we were to change this at this point, it would break thousands of backlinks from campers' personal websites, LinkedIn, etc. So we should stay the course here.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @raisedadead @Bouncey Our reasons for not having a /user/ path have less to do with SEO (/user/ would actually be better for SEO) and more to do with convention. 

GitHub, Twitter, and most consumer websites follow this pattern.

If we were going to change this to /user/ or better yet /portfolio/ we  to change this at this point, it would break thousands of backlinks from campers' personal websites, LinkedIn, etc. 

If we are going to do this, there is no better time to do this than right now. The reason is that we are already going to have to communicate a lot of changes to campers.

If we make this change, would it also make sense to update the /certificates/[user]/[certificate] path to /portfolio/[user]/[certificate]?

**Comment by raisedadead** [comment]
Hi @QuincyLarson 

Ok, so here is what I have though should be a way to address this issue:

From @Bouncey 's proposal https://github.com/freeCodeCamp/freeCodeCamp/pull/16882#pullrequestreview-103361118

> This could be mitigated with a catch-all on the server that does a User.doesExist on the req.baseUrl and then redirect if required to the new endpoint.
>
> That way, we can support depreciated sign-in and the 'legacy' /:username

This is an expensive call, but I think, this is the only way we are able to keep the backlinks from breaking for existing users.

I'll add the `/:portfolio` routing for profiles, with the above lookup. 

That is `https://freecodecamp.org/quincylarson` will redirect to `https://freecodecamp.org/portfolio/quincylarson`

But it will not solve what @BerkeleyTrue has correctly pointed out, which is much large of a problem.
and hence we will also need to implement:

> Maybe some combination of checking the passthrough urls and adding a blacklist service with an async hook to the route might solve the problem.

I am looking into how this can be unified, but any ideas are appreciated.

**Comment by QuincyLarson** [comment]
@raisedadead OK - great. Please go ahead and create that fallback and the new URL paths for `/portfolio/:username` and `/course` (this is also related to https://github.com/freeCodeCamp/freeCodeCamp/issues/16858)

**Comment by mabras** [comment]
I can't login with my legacy method (Facebook):

> New accounts can only be created using an email address. Please create an account below

**Comment by raisedadead** [comment]
Hi @mabras please log a fresh issue, its most likely that you have had different emails on facebook and us. Also, you can send us an email at team@freecodecamp.org
