### ISSUE TITLE
Bad email address in authentication form should display validation errors

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16856]
On the /signin page, if I enter an invalid email address like "test@test" it will crash the app. 

![sign_in_to_freecodecamp_using_your_email_address___freecodecamp](https://user-images.githubusercontent.com/985197/37182922-45b507de-22f9-11e8-9ea6-0fb7df9dcb21.png)

**Comment by raisedadead** [comment]
Its actually not crashing the app, and the backend is throwing the error correctly.
```js
fcc:middlewares:error-reporter Email is not a valid email address. +5s
{ Error: Email is not a valid email address.
...
...
{ type: 'errors',
     message: 'Email is not a valid email address.',
     redirectTo: '/email-signup',
     status: 400 } }
```
I think this needs, investigation to check why the error message isn't displayed as a flash message.

**Comment by JacobPie** [comment]
What if you were to give the input part of it the type of "email". Doesn't HTML5 come with a way to ensure that the input is a valid email?

**Comment by raisedadead** [comment]
I think its already the case.

**Comment by JacobPie** [comment]
So then wouldn't that be enough of an alert? Or am I missing something

**Comment by raisedadead** [comment]
Yes, the issue is its not triggered for some reason. Here is view if you are interested in debugging
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/account/email-signin.jade

Reach out to [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance in contributing.

Thanks.

**Comment by Radlerz1** [comment]
Was this issue resolved? The flash message seems to be working fine for me.

**Comment by raisedadead** [comment]
Hi @Radlerz1 thanks for reporting. Yes indeed.

Just to clarify for future reference:

1. The native HTML validation is fine, turns out I completely missed the fact the `test@test` is actually a valid email just like `test@localhost` 
2. We were not getting the server side validation messages, for a reasons unknown to me. But this has now been resolved in some recent changes merged within the last day.

Closing.
