### ISSUE TITLE
In some situations 404 flash message is too wide

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16860]
![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/37191456-6076029a-2325-11e8-9ea0-c2307a0150ec.png)

The URL I visited to cause this was `http://localhost:3000/en/challenges/javascript-algorithms-and-data-structures-projects/palindrome-checkers` but any invalid challenge URL should produce this effect.

**Comment by vkWeb** [comment]
@QuincyLarson I'll take care of this.

**Comment by vkWeb** [comment]
@QuincyLarson When I was working on this, I realized that clicking on `your current challenge` takes me to an unexpected page. It should direct me to the challenges. Adding the lang `en` on the URL fixed it. 
Patching this with my incoming PR.

**Comment by anhtran1906** [comment]
I was the person who submitted a PR (#16720) to add this NotFound page when users access an invalid challenge. Wonder if this is still an issue so that I can jump on help?
Also, for the "your current challenge" link, right now the code take me to another Not-Found page
![wronglandingpage](https://user-images.githubusercontent.com/20694114/37632016-90d5213c-2bc2-11e8-9d6f-5feadf5733a3.gif)
But when I changed my code with added language path like this: 
<img width="583" alt="screen shot 2018-03-19 at 10 13 06 pm" src="https://user-images.githubusercontent.com/20694114/37632083-da27ac24-2bc2-11e8-8c02-0c286b314485.png">, the code works (clicking on 'your current challenge' leads me to the current challenge I'm on).
Please suggest me a way to fix this and I can submit a PR.

**Comment by QuincyLarson** [comment]
@anhtran1906 I QA'd and merged this before I saw your comment. Does the current functionality that @vkWeb created in his pull request address your point?

**Comment by anhtran1906** [comment]
@QuincyLarson Yes it does. The PR looks great! Thanks!
