### ISSUE TITLE
"array variable name"

### ISSUE THREAD

**Issue by NAAG1999** [freeCodeCamp/freeCodeCamp#16868]
#### Issue Description
Why am i getting different output if i use different variable   ##names.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
var oreo = ['Nilesh', 'Ne', 'Na', 'da', 'ma'];
for(var i = 0; i<oreo.length ; i++)
{
    console.log(oreo[i]);
}

var name = ['Nilesh', 'Ne', 'Na', 'da', 'ma'];
for(var i = 0; i<name.length ; i++)
{
    console.log(name[i]);
}


```
#### Screenshot

![with anyother var name](https://user-images.githubusercontent.com/29707979/37257318-21228918-258e-11e8-84f2-47d8b91be24c.jpg)
![with name](https://user-images.githubusercontent.com/29707979/37257319-215b91e0-258e-11e8-8454-74d90e94582f.jpg)

**Comment by joker314** [comment]
What's happening here is that `name` is a little special in the global scope, because [`window.name`](https://developer.mozilla.org/en-US/docs/Web/API/Window/name) will *always* convert whatever you set it to into a string.

For example, if you do

```
oreo = 5;
console.log(typeof oreo);
```

Then you'll get `number`. But if you do

```
name = 5;
console.log(name);
```

You'll get a `string`.

In your case, `['Nilesh', 'Ne', 'Na', 'da', 'ma']` gets converted to a string, `Nilesh,Ne,Na,da,ma`, and as you take each index of that string, you'll be logging each character.

Basically, it's because `name` is special.

If you really really really want to use the variable name `name`, then you'll need to hop out of the global scope through a closure. Be sure to use the `var` keyword (or `let`, or `const`). Check this out!

```
(function() {
    var name = 5; // this no longer means "window.name = 5;"
    console.log(typeof name); // number
})()
```

**Having said all that, questions about general JavaScript coding would be more appropriate in the [Gitter Chatroom](https://gitter.im/FreeCodeCamp/FreeCodeCamp) or the [FreeCodeCamp forums](https://forum.freecodecamp.org), and I encourage you to ask any future questions there. Hope you have fun doing some more coding, and good luck!**

**Comment by raisedadead** [comment]
@NAAG1999 this issue tracker is for reporting issues in the freecodecamp.org platform only. Please reach out to forums and chat rooms in future.

@joker314 thanks for your comment.

**Comment by NAAG1999** [comment]
am not getting that, how is 'name' special?? is it special for my IDE or the JavaScript??
