### ISSUE TITLE
Challenge buttons don't work on smaller screens

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1686]

**Comment by BerkeleyTrue** [comment]
Is this still an issue?

**Comment by BerkeleyTrue** [comment]
This issue arises from one of the divs pushing itself over the rest of the page making it impossible to click to the underlying elements. This may be due to the div pointed to in the image below not having the correct classes. This should be an easy fix for a Camper.

![fullscreen_9_15_15__5_24_pm](https://cloud.githubusercontent.com/assets/6775919/9893646/8cc85c46-5bcf-11e5-8a6c-807eac737b92.png)

**Comment by formap** [comment]
Is this still an issue? I couldn't reproduce it on any screen size.

**Comment by BerkeleyTrue** [comment]
Nope, this was fixed. @formap Thanks for point it out!

Happy Coding!
