### ISSUE TITLE
[Beta] Coding Interview Algorithm Questions section - Something went wrong

### ISSUE THREAD

**Issue by a7mam7ma** [freeCodeCamp/freeCodeCamp#16906]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/coding-interview-algorithm-questions/inventory-update

#### Issue Description

Loading any challenge from the Coding Interview Algorithm Questions section gives Something went wrong message and checking the browser console shows:
`Failed to load resource: the server responded with a status of 500 ()`

```
Error: {"output":{"message":"Cannot read property 'isComingSoon' of undefined"},"meta":{}}
    at Object.callback (http.client.js:199)
    at n (index.js:62)
    at XMLHttpRequest.i (index.js:129)
    at XMLHttpRequest.o [as __zone_symbol___onload] (zone.js:1064)
    at e.invokeTask (zone.js:424)
    at t.runTask (zone.js:191)
    at XMLHttpRequest.invoke (zone.js:486)
```

#### Browser Information

* Browser Name, Version: Google Chrome 64.0.3282.186 (Official Build) (32-bit)
* Operating System: windows 7 32-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

**Comment by mstellaluna** [comment]
confirmed. the lesson does not load but produces the error(s) mentioned above. 
Lesson Screenshot:
![image](https://user-images.githubusercontent.com/22984739/37656229-d60b83b2-2c1d-11e8-9c35-81c2ba8f95f1.png)


Dev Console:
![image](https://user-images.githubusercontent.com/22984739/37656196-c0a66672-2c1d-11e8-8542-ca2c1d061f83.png)

**Comment by scissorsneedfoodtoo** [comment]
I was playing around with this and found a temporary workaround.

For some reason, the error has something to do with the title of the Symmetric Difference challenge. When I change the title to something like Test it loads without issue. Perhaps for the time being we could simply add a space to the end of the challenge title so it reads "Symmetric Difference ".

**Comment by scissorsneedfoodtoo** [comment]
I believe I found the issue while digging around in mongo.

It turns out that both the Coding Interview Algorithm and Rosetta Code Problem sections have problems named Symmetric Difference. It seems like the titles are different in terms of capitalization, but have the same dashed name, causing the error.

What do you all think? Should we rename the challenge in the Coding Interview Algorithm section? Or go with the workaround by adding a space?

**Comment by Bouncey** [comment]
Are they the same challenge? Could we just remove one?

**Comment by scissorsneedfoodtoo** [comment]
They're not the exact same challenge, but are pretty similar. The one in this Coding Interview section uses arrays of numbers to test, and the Rosetta Code one uses arrays of name strings. Removing one could work, though I'd be hesitant to remove this one because it seems to have been around for such a long time. I guess renaming the problem here could also be troublesome for the same reason.

**Comment by raisedadead** [comment]
Okay, so this highlights a larger problem that we should strengthen the tests to check for uniqueness of the challenge title.

The URL slug was made to have `/challenges` for better SEO I guess @QuincyLarson 

In this case the simplest solution is to add tests in the seed to check for title's uniqueness.

**Comment by raisedadead** [comment]
Hi @scissorsneedfoodtoo I think we should expand the tests here https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/test-challenges.js and also rename one of the challenges to preserve uniqueness.

**Comment by scissorsneedfoodtoo** [comment]
@Bouncey and @raisedadead, thank you for your help! I'll start working on expanding the tests and will submit a PR to rename the challenge in the coding interview section.
