### ISSUE TITLE
Basic Algorithm Scripting: Convert Celsius to Fahrenheit, Giving Error: Something went wrong

### ISSUE THREAD

**Issue by dipjul** [freeCodeCamp/freeCodeCamp#16913]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-algorithm-scripting/convert-celsius-to-fahrenheit

#### Issue Description

While submiting ,showing ERROR: Something went wrong.

#### Browser Information

* Browser Name, Version: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System: Windows 10 pro 64-bit
* Mobile, Desktop, or Tablet: Acer Predeator

#### Your Code

```js
function convertToF(celsius) {
  var fahrenheit;
  fahrenheit = (celsius * (9/5)) + 32; 
 return fahrenheit;
}

convertToF(30);


```

**Comment by joker314** [comment]
Hi, thanks for the report @dipjul !

I had a go at getting the error you described, but I failed to do so in the following environment

 - Version 64.0.3282.167 (Official Build) (64-bit) _slightly older_
 - Windows 10 Home 64-bit
 - Laptop (HP).

I am updating my browser to see if I can reproduce the issue. Did you try reloading the page and resubmitting, perhaps the issue is just temporary (I get that error message from time to time, seemingly randomly)?

**Comment by raisedadead** [comment]
Can't reproduce. Please log a fresh request if you are getting this.
