### ISSUE TITLE
Text Injection (payload taken from URL) could lead to phishing on Beta Site

### ISSUE THREAD

**Issue by joker314** [freeCodeCamp/freeCodeCamp#16914]
#### Issue Description

Text from the URL bar is reflected back into the page as text. This content can then be used to perform phishing attacks which extract a user's credentials.

Here is a proof of concept.

https://beta.freecodecamp.org/en/guest%22.%20It%20looks%20like%20you're%20still%20using%20our%20old%20version%20of%20the%20site,%20and%20that's%20the%20reason%20why%20the%20user%20wasn't%20found!%20Please,%20instead,%20visit%20%22freecodecamp.evil.co.uk

Please note that the URL can be padded with percent-encoded zero-width unicode characters to mask the words in the URL.

This works because the page spits back

```
We could not find a user by the name of "{{injected text}}"
```

Setting the payload to

```
guest". It looks like you're still using our old version of the site, and that's the reason why the user wasn't found! Please, instead, visit "freecodecamp.evil.co.uk
```

Leads to the following

`We could not find a user by the name of "`**`guest". It looks like you're still using our old version of the site, and that's the reason why the user wasn't found! Please, instead, visit "freecodecamp.evil.co.uk`**`"`

This is a potential security issue with a potentially high impact. I've decided to report this here because the likelihood of a successful attack is low; and it's still on beta.

##### Rendered content as image

![image](https://user-images.githubusercontent.com/18113170/37570969-a25c4bd0-2aee-11e8-8662-23d1eb9610af.png)

##### Transcript

Within a blue rounded box, dark-blue text is enclosed which reads

> We could not find a user by the name of "guest". It looks like you're still using our old version of the site, and that's the reason why the user wasn't found! Please, instead, visit "freecodecamp.evil.co.uk"

Below this is a green button which read

> Take me to the Challenges

#### Browser Information

* Browser Name, Version: Version 64.0.3282.167 (Official Build) (64-bit) 
* Operating System: Windows 10 Home (64-bit)
* Mobile, Desktop, or Tablet: HP Laptop

#### Your Code

```js



```

**Comment by ojongerius** [comment]
Nice find, and thank you for reporting this!

I'm not sure what to make of this. As far as I can see it's not an XSS attack, its plain text being displayed back to the user. At the same rate, pulling that data from a param does not seem super awesome either.

@Bouncey AFAICS you introduced this in 3131c5578299fb845c49b315589293a33874a147 . Any thoughts?

From a quick look at the React docs it sounds like the React DOM will escaping for ([1](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks)), unless we use `dangerouslySetInnerHtml`. AFAIT that's not the case here.

1 - https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks

**Comment by joker314** [comment]
You're right, this isn't XSS, this is plain content injection. My mitigation strategy would be to use `encodeURIComponent` which would make spaces and quotes appear very strange when reflected, thus thwarting a phishing attempt, Better yet, the content could be filtered so that invalid usernames aren't reflected back.

/cc @BerkeleyTrue, you told me I could contact you about potential security issues

On a broader level, I suggest freeCodeCamp adopts a vulnerability disclosure policy which makes it clear that ethical security researchers are safe reporting security issues, and a clear contact address. For instance, I suggest that freeCodeCamp adds a [`/.well-known/security.txt`](https://securitytxt.org/) file.

**Comment by ojongerius** [comment]
Those are good suggestions. Thanks! 

Makes sense to pull @BerkeleyTrue in, I'll let him handle this one.

**Comment by raisedadead** [comment]
hi @joker314 thanks a lot for reporting this, I agree to the idea of having a policy around this. Traditionally we have done so by asking us (core team) to be notified via an email.

But you are correct and it makes sense to make this more clear. 

That said, we are working on possible solutions for this.

Just to let you know, here is what we have discussed so far regarding this usecase:

---

This is because the react view for the user not component, does not have sanitisers, before generating the view. It would not be reliable to do so as well client side.

I think we should just do this, with a server rendered view like this:

https://beta.freecodecamp.org/en/challenges/some%20random%20text

And even further tighten it with sanitizers if needed.

Personally, I would avoid any rendering of user provided string.

I think, it would much straight to just show an error like:

“We could not find what you were looking for. You should try the search box, on this page, or head back to challenges.”

That’s it.

And this should be consistent for anything that’s not found (user, challenges, etc.), currently we have atleast three such error pages.

**Comment by joker314** [comment]
This appears to be resolved. Can anyone confirm that this is the case?

**Comment by raisedadead** [comment]
Hi @joker314 you can add team+security@freecodecamp.org to it.
