### ISSUE TITLE
[BETA]: Debugging: Differences b/w FCC & Browser Console (Lesson doesn't match output, one test might be passing erroneously)

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#16958]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console

#### Issue Description
1. The lesson states (excerpting for brevity):
>When you load and run an ordinary JavaScript file in your browser the console.log() statements will print exactly what you tell them to print to the browser console the exact number of times you requested. 

>This lends itself to some interesting behavior and might trip you up in the beginning, because a logged value that you expect to see only once may print out many more times depending on the number of tests and the values being passed to those tests.

The editor text says:
```
// Open your browser console
let outputTwo = "This will print to the browser console 2 times";
// Use console.log() to print the outputTwo variable
console.log(outputTwo);
```

However, Firefox & Chrome browser consoles both exhibit the same behavior, only printing the line once (see screenshots). I specifically left out the `clear.console()` line to see the duplicated console output, but it doesn't work.

2. The tests pass whether `clear.console()` is written in the editor or not. (screenshot below)

#### Browser Information
* Browser Name, Version: Firefox 59.0.1 && Chrome 65.0.3325.181
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
// Open your browser console
let outputTwo = "This will print to the browser console 2 times";
// Use console.log() to print the outputTwo variable
console.log(outputTwo);

let outputOne = "Try to get this to log only once to the browser console";
// Use console.clear() in the next line to print the outputOne only once

// Use console.log() to print the outputOne variable
console.log(outputOne);
```
#### Screenshot
PROBLEM#1:
Firefox Console:
![image](https://user-images.githubusercontent.com/36994955/37877184-1275ca0a-3025-11e8-93a7-9da85fdc8f90.png)

Chrome Console:
![image](https://user-images.githubusercontent.com/36994955/37877204-58c4e39c-3025-11e8-8bce-3f3e1c51872b.png)

PROBLEM#2
![image](https://user-images.githubusercontent.com/36994955/37877266-6dfaa728-3026-11e8-91d6-61883502ccbc.png)

**Comment by ahmadabdolsaheb** [comment]
@vipatron @raisedadead I confim the followings. 

1. The browser console behaves normally. 
 (it prints the number of console logs and clear them accordingly to the editor.)
2. The freecodecamp in-browser console neither displays output nor prints console.log.
(it only displays the test related messages. To test the in-browser console, I have have tried to console.log in the following challengs with no success:
https://beta.freecodecamp.org/en/challenges/regular-expressions/match-single-character-with-multiple-possibilities
https://beta.freecodecamp.org/en/challenges/es6/declare-a-readonly-variable-with-the-const-keyword
https://beta.freecodecamp.org/en/challenges/basic-javascript/multiply-two-numbers-with-javascript)

3. The third test should be modified. Currently it passes because it finds the string (/console\\.clear\\(\\)/g) in a comment.

Browser info : Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by iabrenne** [comment]
I agree with @ahmadabdolsaheb on all three points.

1. Browser console is behaving as expected - output is showing up once with the number of times indicated right after the output. So I don't think there are any issues there.

2. FCC in browser console is not showing any output from console.log(). In other words, 2nd sentence of:
![image](https://user-images.githubusercontent.com/24214306/39098994-700309a2-4638-11e8-975c-c3878e18983a.png)

is not happening. 

So I think either a fix would need to be made so that console.log messages are displayed in the FCC In Browser console as advertised, or that verbiage should be removed. 

3. 3rd test is passing even when console.clear() is not uncommented.

I can take on #3 and take a look into #2.

**Comment by iabrenne** [comment]
Also, looks like this issue / behavior carried over to the learn repo https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console , so I'm assuming it is still worth looking into / fixing this issue. @raisedadead - please let me know if you disagree. Thank you!

**Comment by raisedadead** [comment]
@iabrenne you are correct, this will be carried over to the gatsby based learn repo once again. But you are correct in fixing it here. So, that we can sync up the curriculum.

**Comment by raisedadead** [comment]
Reopening for addressing points raised by @ahmadabdolsaheb !

**Comment by iabrenne** [comment]
Thank you, @raisedadead .  I am looking into the console.log issue now to see if we can get FCC browser console to show console.log output, as advertised :)

**Comment by raisedadead** [comment]
@iabrenne sure.. we all have been there. Thanks a lot for taking the time to look at this. 

As for which repo to make a PR against:

- All of the challenge execution logic is now moved to the learn repo. That is to say, it has become our challenge platform. Its based on Gatsby, and is a simple static app.
- The challenge themselves (just the content, instructions, and the tests) are on the main repo. They are now published as an npm package. And used on learn as a dependency.

- The main repo, will just serve the welcome page, user settings and portfolio.

**Comment by profoundhub** [comment]
BTW, this challenge will throw an _error_ when using **Firefox** but not when you are using **Chrome**. If you get an _error_ about _regex_, try again in **Chrome**.

**Comment by RandellDawson** [comment]
@raisedadead Is this still an issue which needs to be resolved?

**Comment by raisedadead** [comment]
@ojeytonwilliams did some fixes o this recently, which are live on staging. Can you check and confirm?

**Comment by raisedadead** [comment]
My bad, I mistook this for a client implementation of the same. Ignore my last.
