### ISSUE TITLE
[beta] : Static Page Menu is broken

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16950]
On certain viewports the static nav menu is broken.

![2018-03-24 17 39 31](https://user-images.githubusercontent.com/1884376/37863831-dfbc3350-2f8a-11e8-8960-85274d221ed1.gif)

**Comment by YogeshSharma0201** [comment]
This issue is because bootstrap.js doesn't get loaded also other libraries like jquery etc are also not loaded.  vendor-main.js which gets loaded with home.jade runs into an error ("require not defined") so nothing gets loaded. I was able to  fix this by removing "opbeat-react" from vendor-main.js. This is probably because "opbeat-react" needs to be compiled (it uses require) therefore it cannot be directly passed to the browser.

**Comment by YogeshSharma0201** [comment]
This issue is related to #15818

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
