### ISSUE TITLE
Make Open Data initiative even more clear in privacy policy

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#16963]
I know that the privacy policy says that FCC can gather and publish statistics, but some campers don't realize that the contents of their community posts will be shared (especially associated with their usernames).  In the spirit of transparency, should there be some information about this clearly laid out in the privacy policy? It seems consistent with FCC's values to do so.

**Comment by ArielLeslie** [comment]
By "community posts" I meant activity in the Gitter rooms or the forum. (I'm not sure whether the forum activity is included in the open data project or not - another thing that should probably be made clear.)

I've seen a few complaints like [this one](https://forum.freecodecamp.org/t/poop-please-purge-all-my-posts-from-the-forums-invite-others-when-did-this-happen-why-did-p1xt-leave/118959) since the Medium article was published about our chat data.

**Comment by erictleung** [comment]
@ArielLeslie thanks for the clarification. And your concerns make sense. Although avenues such as Gitter rooms and the forum are public places (which can be indexed by search engines), making it clear that data can be shared would be true to being transparent.

cc/ @freeCodeCamp/moderators @QuincyLarson second opinions?

**Comment by IsaacAbrahamson** [comment]
Think it's fair to link to p1xt's full letter know that the posts are deleted from forum:

https://medium.com/p1xts-blog/an-open-letter-to-freecodecamp-aff93113e55c

I think she overreacted, but it never hurts to be transparent.

**Comment by ArielLeslie** [comment]
I've seen some less outspoken reactions along the same lines previously. I had always thought that the recording and releasing of chat data was disclosed somewhere because I've known about it, but I guess that was only from announcements that you had to be part of the community at the time to know about.

**Comment by raisedadead** [comment]
Hi @ArielLeslie @IsaacAbrahamson @erictleung thanks for discussing this.

Yes, while we should update our privacy policy to reflect what we are doing with the data-sets that we have, its actually more concerning on what we lack user education & awareness of such policy.

It should be made clear on the intent here. I would be great if we can come up with ideas, or even PR to our privacy policy which is open source. https://github.com/freeCodeCamp/privacy-policy

> The privacy policy is NOT there to protect freeCodeCamp, but to protect its users.

Unfortunately the verbiage in it, and as with any other platform is usually is TL;DR and people click though it, only to get outraged like these instances that you have pointed.

Sure we can and will delete the any information that is requested to be deleted upon confirmation of the user. But that will just divulge us from what we are working on to help the community learn. So such requests will be processed at their own pace.

Looking forward to your thoughts, and thanks a lot for taking the time to bring this to our notice.

**Comment by huyenltnguyen** [comment]
I'd propose adding a short, simple version of the policy to the Terms and Privacy pages.
For reference:
- Startpage: https://www.startpage.com/eng/privacy-policy.html#hmb
- WeTransfer: https://wetransfer.com/legal/privacy

**Comment by QuincyLarson** [comment]
@ArielLeslie So far we have only re-packaged publicly accessible data, so that it can be more easily studied by academics and data scientists:
- the public freeCodeCamp activity of about 100,000 campers, taken from their freeCodeCamp code portfolios
- the public gitter.im/freeCodeCamp/freecodecamp chat room's conversation log (this is also indexed by Google and other search engines, as are all public Gitter rooms)

And then there are the 2 New Coder Surveys that we've conducted, which are semi-anonymous (even we don't know who submitted the survey responses). Both of these surveys were clearly labeled as their results being publicly released as open data.

We haven't released as open data anything from the freeCodeCamp forum - even though it's public. I'm not sure if we'll release any data from it in the future.

We view our contributions to open data as a public service to academics around the world who need data for their research. There isn't much good open data out there - especially not related to education.

Our current privacy policy is a slightly modified version of [WordPress's creative commons privacy policy](https://automattic.com/privacy/). It reserves rights that we don't intend to use, related to advertising and sharing of private data. 

We could come up with a new privacy policy that's simpler and clearer, though we'd probably need legal help with this.

**Comment by raisedadead** [comment]
Requesting contributors, to have a copy to reflect the above thoughts here and if possible PR on the below repos:

https://github.com/freeCodeCamp/privacy-policy

and

https://github.com/freeCodeCamp/terms-of-service

**Comment by sourabh1031** [comment]
i would like to work on this issue.Please guide me the necessary things since i am a newbie to open source

**Comment by sourabh1031** [comment]
I would like to work on this issue.As i am newbie to open source please provide me some help

**Comment by QuincyLarson** [comment]
I am completely rewriting our privacy policy.

At this point, we only plan to release open data where:
- the data is completely public (like the Gitter chat logs were) or
- it's data from a survey or something where the participant clearly opted in.

At this point, we do not plan to release freeCodeCamp.org user data as open data in the future.
