### ISSUE TITLE
Typeof Challenge requirements fulfilled only on passing empty array and object 

### ISSUE THREAD

**Issue by Parama92** [freeCodeCamp/freeCodeCamp#16994]
#### Challenge Name

https://www.freecodecamp.org/challenges/using-typeof

#### Issue Description

The following two requirements are only fulfilled only on passing an empty array and an empty object although the console output is exactly the same:
1. You should console.log the typeof an array.
2. You should console.log the typeof an object.

#### Browser Information

* Browser Name, Version: Chrome Version 64.0.3282.186
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

**Screenshot with empty array and object:**

![image](https://user-images.githubusercontent.com/30025212/38164432-50728bfc-3522-11e8-9aac-a436b3af5e16.png)

**Screenshot with non-empty array and object:**

![image](https://user-images.githubusercontent.com/30025212/38164468-fa1651ca-3522-11e8-8834-47ff0943d559.png)

**Comment by raisedadead** [comment]
Can someone help us if we have the same challenge and the same issue as above in the beta version of this as well?

**Comment by scissorsneedfoodtoo** [comment]
Just checked the beta version of this challenge here: [https://beta.freecodecamp.org/en/challenges/debugging/use-typeof-to-check-the-type-of-a-variable](https://beta.freecodecamp.org/en/challenges/debugging/use-typeof-to-check-the-type-of-a-variable)

The tests have changed so that the user just needs to log a couple of declared variables to the console, which are a string and a number, avoiding the problem of the tests failing like they do in production. Instead, there are examples given of the expected output when using typeof on a string, number, array, and object in the item description.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo awesome. Thanks a lot for the analysis

**Comment by raisedadead** [comment]
Hi @Parama92 we have a different approach to this challenge on beta. It will be available when its launched.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, no problem! Happy to help.

**Comment by Parama92** [comment]
Hey @raisedadead just checked it out in the beta version. Thanks for the heads-up!
