### ISSUE TITLE
Beta - Data Visualization with D3: Add Axes to a Visualization passes challenge with y axis incorrectly placed

### ISSUE THREAD

**Issue by swayman01** [freeCodeCamp/freeCodeCamp#17026]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/data-visualization-with-d3/add-axes-to-a-visualization

#### Issue Description
The y axis did not intersect the origin and I passed the challenge

#### Browser Information
* Browser Name, Version: Safari
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 <script>



    const dataset = [
                  [ 34,     78 ],
                  [ 109,   280 ],
                  [ 310,   120 ],
                  [ 79,   411 ],
                  [ 420,   220 ],
                  [ 233,   145 ],
                  [ 333,   96 ],
                  [ 222,    333 ],
                  [ 78,    320 ],
                  [ 21,   123 ]
                ];
    
    const w = 500;
    const h = 500;
    const padding = 60;
    
    const xScale = d3.scaleLinear()
                     .domain([0, d3.max(dataset, (d) => d[0])])
                     .range([padding, w - padding]);
    
    const yScale = d3.scaleLinear()
                     .domain([0, d3.max(dataset, (d) => d[1])])
                     .range([h - padding, padding]);
    
    const svg = d3.select("body")
                  .append("svg")
                  .attr("width", w)
                  .attr("height", h);
    
    svg.selectAll("circle")
       .data(dataset)
       .enter()
       .append("circle")
       .attr("cx", (d) => xScale(d[0]))
       .attr("cy",(d) => yScale(d[1]))
       .attr("r", (d) => 5);
    
    svg.selectAll("text")
       .data(dataset)
       .enter()
       .append("text")
       .text((d) =>  (d[0] + "," + d[1]))
       .attr("x", (d) => xScale(d[0] + 10))
       .attr("y", (d) => yScale(d[1]))
    
    const xAxis = d3.axisBottom(xScale);
    
    svg.append("g")
       .attr("transform", "translate(0," + (h - padding) + ")")
       .call(xAxis);
    
     const yAxis = d3.axisLeft(yScale)    
    svg.append("g")
//    .attr("transform", "translate("+(w + padding) + ", 0")
//TODO - post bug on github

       .call(yAxis);


  
  </script>


```
#### Screenshot

//Sorry, I wasn't diligent about separating my code from course code
<img width="539" alt="screen shot 2018-04-04 at 3 11 27 pm" src="https://user-images.githubusercontent.com/25989875/38329259-568a4c4a-381b-11e8-960e-dbf49f75a0c4.png">
<img width="539" alt="screen shot 2018-04-04 at 3 11 27 pm" src="https://user-images.githubusercontent.com/25989875/38329277-648f98cc-381b-11e8-9c57-34714721ae13.png">

**Comment by absolitudo** [comment]
The test that checks this task is:
```js
"assert($('g').eq(1).attr('transform').match(/translate\\(60\\s*?,\\s*?0\\)/g), 'message: The y-axis <code>g</code> element should have a <code>transform</code> attribute to translate the axis by (60, 0).');",
```
This test looks at all the "g" elements then selects the 2nd one in the list to look at the attributes.
By default the challenge has the xAxis applied already. The d3 axis functions make "g" elements to display the ticks. So by default there are already 10 "g" elements in the dom and the 2nd that is being selected is a tick of the xAxis and it happens to have the transform attribute that the challenge requires you to apply. I think there should be a better way to select the yAxis and look at it's attributes but I can't think of anything myself. One hacky way to do this would be to look at the 11th "g" element which is going to be the yAxis if there are no other "g" elements applied by the camper.

11th because the first "g" is the xAxis that applies 9 other "g" as ticks. So the next one would be the yAxis potentially but it could be anything else if the camper doesn't closely follow the instructions but still comes up with a solution.

for example: 
```js
"assert($('g').eq(10).attr('transform').match(/translate\\(60\\s*?,\\s*?0\\)/g), 'message: The y-axis <code>g</code> element should have a <code>transform</code> attribute to translate the axis by (60, 0).');",
```

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by swayman01** [comment]
I agree that there are better places to invest our resources.
