### ISSUE TITLE
Submit changes without reloading page after updating the settings

### ISSUE THREAD

**Issue by abaracedo** [freeCodeCamp/freeCodeCamp#17168]
#### Issue Description
The page is reloaded after updating, for example, the email preferences. I think it could be a better an user experience to do it without reloading the page and showing the notice under the Email settings heading.

I think this change can improve the UX because the page will not reload and the user will not scroll again to update any other settings.

**Comment by raisedadead** [comment]
Hi there since you did not include if this is something you are interested in on the production, I can see some of the same things maybe there on the new beta that we are about launch.

Can you confirm that this need is on https://beta.freecodecamp.org ?? We are going to replace our main production site with this real soon.

**Comment by abaracedo** [comment]
I have checked the beta version and the Settings page has changed a lot, all the updates are done without reloading the page and if this version will be in production soon, the issue can be closed.

I only noticed that after update any field, at the top of the page appears the notice with the result message.
