### ISSUE TITLE
Linking GitHub in a new account shows history from the first one account

### ISSUE THREAD

**Issue by abaracedo** [freeCodeCamp/freeCodeCamp#17167]
#### Issue Description
I created the first account two years ago and I linked the account to my GitHub. Now, I created a second account on freeCodeCamp and I linked it to the same GitHub account.

When I go to my profile I can see that I have the brownie points from the first account and the history of the tasks done, but the brownie points shown in the header are from the new account.

The map does not shows the tasks from the first account as completed.

#### Browser Information

* Browser Name, Version: Firefox 60
* Operating System: MacOS 10.13.4
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
<img width="1209" alt="captura de pantalla 2018-05-15 a las 11 05 40" src="https://user-images.githubusercontent.com/9487675/40030834-123402b8-5830-11e8-9561-a074f969c2c5.png">

**Comment by bigkatspence** [comment]
@raisedadead am interested in doing analysis on this, do you know if this is related to some of the prior changes that were done on recent commits?

**Comment by raisedadead** [comment]
@bigkatspence thanks for taking the interest in this. Just so that you know this is on the production version of the codebase.

You will need to setup the `backup/master` and checkout its relative contributing guide.

Now, coming to the commits. You should look at what we did (and possibly introduced a bug), when we chose to disable the account creation with GitHub and other social accounts.

I'll warn you though that this may not be a trivial analysis. 😅 So, let us know if you need any thing. 

P.S: Reach out to us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) if you would like.

**Comment by raisedadead** [comment]
We have removed linking of account and GitHub. You can still use sign in with GitHub. But This is tied to the email on records with GitHub.
