### ISSUE TITLE
Beta: Can't view other campers' public profile

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17264]
**I'm curious how I (or other campers) would view the 'public profile' of other campers**

**In the current live FCC I can view other campers' progress and projects by going to the `url/campers name` (not super obvious, but findable) - In beta, to view a profile, I have my id in the url which is a giant string of random characters, which makes impossible to view other profiles**

**Comment by raisedadead** [comment]
A few things:

1. The user profiles will now become available at `/portfolio/user-name`
2. The long id which you are talking about is actually your username and is very much customiszable, by the user.
3. When rolling over beta to production your old username will be retained, you will not see that long username if not already set to one of your choice.
4. Only the new signups will have a unique UUID like username, which again is Point 2 above. 

Finally we never had discoverability other than in the chat rooms and forums where users would share their profiles with their fellow campers.

We would keep it that way, the user profile belongs to the user and it will be highly customizable, and can only be made known to others, when the choose to.

**Comment by raisedadead** [comment]
I have closed this because there is not much to be done here in terms of the UX. The settings page already has all the options that new users will be able to use and customize their profiles.

Returning campers with a username will not face this and even they can update the username now, if they wish to (and a ton of other stuff in their bio, if they choose to).
