### ISSUE TITLE
Give hint button missing, solution button missing, lost submitted code/streak , 

### ISSUE THREAD

**Issue by JakeShelterwin** [freeCodeCamp/freeCodeCamp#17303]
1. the “give hint” button is not longer there
2. the profile page is no longer easly reachable from the top right corner
3. the portfolio page is missing the “solution” button to re-read the previously submitted solutions (I used that button to go back and read the comments explaining what I have done to reach that solution)
4. I’ve lost my Streak! I was at over 115 days, now i’m only at 2 :frowning: (I’m sure I didn’t interrupt the streak, and anyway the “longest streak” now is 14 instead of 115 :frowning: )
5. Linked to point 3 and 4 I’ve lost all my previous solutions :frowning: If i go back to the lessons that I have already completed my code is no longer there :frowning:
6. The funcion “map” is now replaced with “view the curriculum”… but Map was already placed on the lesson you where following while “view the curriculum” starts always from the beginning of the entire course)

* Browser Name: Chrome
* Browser Version: Latest
* Operating System: macOS latest update

**Comment by raisedadead** [comment]
Hi @QuincyLarson can you please point them to a FAQ about common issues. 

I am thinking the announcement should include a link a page to an FAQ that has granular details of all the changes that may come as a surprise to a subset of users. Its not clear for many users what's the difference between `map` and `curriculum` for example.

I believe instead of responding to thousands of supports requests its best we should consolidate as much as we can on a FAQ.

I understand that many will simply not read the FAQ and we will still answer queries. But that we can enforce a policy around support requests.

From my experience this is some what same as the 'Read-Search-Ask' which has proven to be a great way to handle requests and faster for users and maintainers.

**Comment by aditijoshi14** [comment]
Just wanted to note that the first issue has been solved. Duplicate issue #17431 was posted on June 4, which was closed on July 27. Also, there are duplicates (#17822 , #17743 ) for the fourth issue. Lastly, the fifth issue is a known issue which is currently being worked on as mentioned in a comment on #17317. 

We could potentially make new issues for the second and third issue.

**Comment by QuincyLarson** [comment]
@aditijoshi14 Awesome! Thanks for digging through and confirming most of these were duplicates. 

@JakeShelterwin regarding points 2 and 3, these are intentional, and are not issues.
