### ISSUE TITLE
Spelling mistake in the console.

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#17325]
#### Describe your problem and - if possible - how to reproduce it
I was doing the CSS tutorial and when did a mistake on assinging the value of a css variable I got an error on the console and the message on the console is "penguin class should declar the --penguin-skin variable and assign it to gray." and you can see the there is a spelling mistake. 'declar' should be 'declare'.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here
![screenshot 9](https://user-images.githubusercontent.com/39026437/40775688-7a6892ce-64ea-11e8-8de4-77b50239d93b.png)

**Comment by mstellaluna** [comment]
@Twaha-Rahman  Hi Twaha, the spelling of grey as gray is not a spelling mistake, it is a valid way of spelling the color as depending if you are using UK English (grey) or US English (gray). Both are accepted by W3 standard and in the lessons US spelling is used.

**Comment by emdashv** [comment]
@mstellaluna I think @Twaha-Rahman was referring to the typo in "declar" not "gray". 

> 'declar' should be 'declare'.

**Comment by huyenltnguyen** [comment]
@clarkngo Sorry, looks like someone fixed it already (https://github.com/freeCodeCamp/freeCodeCamp/pull/17355)
\cc @ahmadabdolsaheb

**Comment by wildhamster26** [comment]
I think I've found it, but someone had beat me to it (especially as mentioned above). 
As a learning experience, though, I wonder if I did the right thing:
I opened the link to the page with the error, went to the dev tools, looked at the sources and figured where it's called from, generally.
Than I found a json file corresponding to that name and found the exercise as an object.

I think I found the right place (responsive-web-design-01/basic-css,json), but am I right? If so, is there a better way to go about it?

Thanks!!

**Comment by huyenltnguyen** [comment]
@wildhamster26 I'm not sure whom you were asking, but I'm going to answer anyway.

Yes, if I'm totally new to the app, that's what I would do, too,.

However, if you setup the app on your local machine, looking things up will get easier and cooler.
I got this repo running locally already, all I need to do is to use the `git grep <string>` command, it will find all the files that contain the string and give them to me (I used the `-w` option to match the exact word, otherwise, it'll look for `declare` too):

![untitled](https://user-images.githubusercontent.com/25715018/40868783-b44754ac-663a-11e8-95fd-c6fe88cc728c.png)

Neat huh?

Anyway, I love your learning spirit! Thanks for taking the time to investigate the issue. As the curriculum has grown significantly, I'm sure there are still plenty bugs and typos waiting for us to catch. Hope you can get a chance to contribute soon!

**Comment by clarkngo** [comment]
oh that's fine :) i'll have my chance sooner or later. @huyenltnguyen

**Comment by diskandarnerd** [comment]
then this issue should be closed since already solved?

**Comment by anku255** [comment]
@Bouncey @raisedadead @ahmadabdolsaheb Please close this issue. It has been fixed for a long time.

**Comment by Bouncey** [comment]
Thanks @anku255
