### ISSUE TITLE
Links to internal sections open a new website page instead

### ISSUE THREAD

**Issue by Colcoction** [freeCodeCamp/freeCodeCamp#17332]
#### Describe your problem and - if possible - how to reproduce it
In the lesson "Basic HTML and HTML5 - Link to Internal Sections of a Page with Anchor Elements", clicking on the "Jump to Bottom" link after correctly editing the code does not move the output preview to the bottom of the preview page (which would demonstrate the effect the lesson is trying to teach), but instead opens a new browser tab with the URL "https://learn.freecodecamp.org/#footer".

#### Add a Link to the page with the problem

[Basic HTML and HTML5 - Link to Internal Sections of a Page with Anchor Elements](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome (the problem persisted in Microsoft Edge, as well)
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by planetofcode** [comment]
Same problem.

**Comment by saifazmi** [comment]
+1

**Comment by Nirajn2311** [comment]
It doesn't work in the preview but when you make your own webpage it works perfectly.

**Comment by mattipr89** [comment]
on own webpage or w3 simulator works perfect but for achieving this task it is impossible

**Comment by RandellDawson** [comment]
This does not appear to be an issue any more, because following the current challenge instructions and clicking on the link takes the focus to the bottom of the preview section.

I am closing this for now.  If you are still experiencing trouble, please post all of your editor code here as a reply.  Please use three backticks on the lines before and after any code you post, so that it formats properly and users can read the code.

Thank you.
