### ISSUE TITLE
Unable to use some keys of the iPad smart keyboard on lessons

### ISSUE THREAD

**Issue by seekingcat** [freeCodeCamp/freeCodeCamp#17386]
#### Describe your problem and - if possible - how to reproduce it
When using the site on Safari and Chrome on an iPad pro, I am no longer able to use some keys like arrow keys to navigate the lesson pane, which means I am stuck touching the screen to position my cursor, which isn't incredibly accurate. I also cannot use the 'press to move the cursor' action on the lesson pane so can't place my cursor where needed, so it depends on having to touch the screen on the exact place I need to place the cursor. I also can no longer use ctrl + enter to submit the lesson. I used to be able to use the arrow keys and the ctrl + enter to submit previously.

#### Tell us about your browser and operating system

* Browser Name: Chrome and checked on Safari
* Browser Version: 
* Operating System: iPad OS 11.4

**Comment by raisedadead** [comment]
Hi @seekingcat 

Thanks a lot for the issue report, and we are sorry to hear about the bad UX.
We currently have almost no support for Mobile devices other than those with standard Keyboard, Mouse/Touchpad 

I understand this is an annoyance. But there might be a while before we can support our platform on all devices. Until then I would recommend you to be using the platform on a desk device.

I am tagging this as help wanted for further investigation and fix.

**Comment by seekingcat** [comment]
Hi, thank you for your response. It really was just a curiosity as the keyboard arrow keys worked in the previous platform. I asked Quincy on Twitter and he said to raise it as an issue. Hopefully this will get a look in, but I appreciate there are other more urgent issues. Thanks again.

**Comment by MoonCWang** [comment]
For anyone who wishes to look into this, another developer found and resolved the issues by changing their keyboard.js file.  https://github.com/processing/p5.js/pull/3286/files

**Comment by emmawinston** [comment]
> For anyone who wishes to look into this, another developer found and resolved the issues by changing their keyboard.js file. https://github.com/processing/p5.js/pull/3286/files

To be clear - FCC doesn’t use p5.js, does it? Do you just mean that the bug is similar in terms of UX? I would also love to be able to use FCC with an external keyboard on iPad (I can confirm the p5 editor works great for me), and realise it’s a fairly niche issue. I might try at looking at this myself if nobody else is currently tackling it, but am absolutely novice-level with FCC’s entire tech stack so can’t promise anything ;)

**Comment by ahmadabdolsaheb** [comment]
**Additional info**
On mobile devices, the keyboard does not show up when the code editor is clicked
This is an issue on both .org and .rocks

**To Reproduce**
Steps to reproduce the behavior on mobile phone:
1. Go to https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method
2. Click on the code editor to enter the the answer to the challenge.


**Expected behavior**
The keyboard should pop up when user clicks on the code editor on mobile.

**Screenshots**
![Uploading Screen Shot 2019-05-08 at 8.56.55 AM.png…]()
<img width="322" alt="Screen Shot 2019-05-08 at 9 05 35 AM" src="https://user-images.githubusercontent.com/4591597/57353252-8dc0a800-7170-11e9-8775-89ab10b36525.png">


**Smartphone (please complete the following information):**
 - Device: iphone 5S

**Comment by ahmadabdolsaheb** [comment]
@emmawinston I don't think we are using p5. however, I believe a similar solution to trigger the keyboard could work. I was wondering if you are still interested in this issue?

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb even if they're no longer interested, it still is a bug which needs fixing

**Comment by emmawinston** [comment]
Hello, yes, I am still interested! I'm also pretty swamped with work hence the very slow response, sorry. If nobody else wants to take a look I will add it to my to do list, but it might be a while before I get to it! :)

**Comment by Dineshchitta** [comment]
Any update on this? @raisedadead

**Comment by raisedadead** [comment]
> Any update on this?

A pull request is welcome if you are interested.

**Comment by Dineshchitta** [comment]
Hi @raisedadead,

I am not aware of the codebase and how much effort it would take to submit PR

I am interested if someone could guide me on how to fix this
