### ISSUE TITLE
We shouldn't use vague error messages anymore

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17413]
We're a community of developers, and I think we should surface more of what the error is actually happening in cases where it isn't a likely security risk. If feel like error messages like "oops - something went wrong" are kind of insulting to users' intelligence.

Would anyone be interested in auditing the codebase and going through to make the error messages a bit more specific?

**Comment by thecodingaviator** [comment]
@QuincyLarson where are we still seeing this? Maybe I can have a look

**Comment by QuincyLarson** [comment]
@thecodingaviator One place we're still seeing the "Oops something went wrong" message is when one of the unsubscribe link fails from my email blasts. This usually happens if there is a duplicate account with the same email address (this is a corner case that our code should address anyway). But even so, we shouldn't have "oops" type messages. 

Rather, we should have more transparent issues like "We had a problem with the unsubscribe request. We are working to fix this. In the meantime, reply to Quincy's email if you want to be unsubscribed." or something like that.

Would you be interested in going through the codebase looking for the word "oops" and seeing whether we can give more specific error messages?

**Comment by thecodingaviator** [comment]
Yes, I'd pick that up, I'm gonna go through the codebase today and search for all instances of Oops I can find

**Comment by thecodingaviator** [comment]
There are four files which come up on a repo wide search of 'Oops', the list below excludes curriculum or guide files, since the usage of oops there is for coding purposes and not an error message:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/common/models/User-Identity.js
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/middlewares/error-handlers.js
3. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/boot/authentication.js
4. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/boot/user.js

**Comment by 1LISA2** [comment]
!
![images (3)](https://user-images.githubusercontent.com/103248540/188255923-d60abe68-1c87-4038-a2d6-1d73ac9efbb7.jpeg)
[Uploading 下载.jpeg…]()

**Comment by 1LISA2** [comment]
Black people are ugly and scary

**Comment by 1LISA2** [comment]
I am afraid when I see black people, why do black people exist, black people still have a lot of AIDS, scaring people to death
