### ISSUE TITLE
Extra padding at the bottom of the editor page after moving to the next challenge.

### ISSUE THREAD

**Issue by cj-sv** [freeCodeCamp/freeCodeCamp#17411]
#### Describe your problem and - if possible - how to reproduce it

Extra padding seems to appear at the bottom of the page after finishing a challenge and moving on to the next. The extra padding disappears when the page is refreshed. Occurs and reproducible on some challenges.

Used screen resolution is 1366x768. 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Firefox Nightly
* Browser Version: 62.0a1
* Operating System: Kubuntu 18.04

#### If possible, add a screenshot here

![screenshot_20180603_221133](https://user-images.githubusercontent.com/11567756/40887475-10d87966-677c-11e8-80d0-60f6d4129175.png)
![screenshot_20180603_221235](https://user-images.githubusercontent.com/11567756/40887490-41ac90d6-677c-11e8-895a-bb4ded48247c.png)

**Comment by moT01** [comment]
Is this still a problem @cj-sv?

**Comment by cj-sv** [comment]
Yep, still present.  
  
Tested on Manjaro,  Firefox Nightly 67.0a1 and Firefox 65.0 in safe mode and on different profiles.

**Comment by RandellDawson** [comment]
@cj-sv Can you checkout our [beta site](https://freecodecamp.rocks) which has many changes which may have resolved this issue.  If it is still present, then we can label it as such.  Thank you.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, can confirm this still happens on freecodecamp.rocks. Seems like the completion modal causes the text in the description to shift by a pixel or two.

**Comment by ojeytonwilliams** [comment]
Steps to reproduce:

- Use Firefox
- Go to https://www.freecodecamp.rocks/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
- Currently you can scroll to the bottom and see no white padding
- Click on line 2 of the editor and hit Ctrl-Space to get suggestions and then Ctrl-Enter to run the tests
- Now scroll to the bottom and see that the padding is visible

![ScrollbarAppears](https://user-images.githubusercontent.com/15801806/55956144-8edee200-5c63-11e9-98f1-00df754f633a.gif)

This is caused by the `monaco-aria-container` div which should be visually hidden, but is actually sitting at the bottom of the page.  I'll submit a PR fixing this shortly.
