### ISSUE TITLE
Night mode not available on learn.freecodecamp.org

### ISSUE THREAD

**Issue by conradkay** [freeCodeCamp/freeCodeCamp#17412]
#### Describe your problem and - if possible - how to reproduce it
If I click on my avatar(and get redirected to freecodecamp.org settings page) and activate night mode, the night mode will not transfer over to learn.freecodecamp.org, I'm not sure if there is the code for a dark mode on the curriculum website, but even just simply changing the background and text color, and adding a editor theme such as one-dark or any other dark theme would be greatly appreciated.

#### Tell us about your browser and operating system

* Browser Name: Chrome and Firefox, but it most likely still occurs on all browsers.
* Browser Version: Happens on all supported browser versions.
* Operating System: Ubuntu 18.04, but most likely happens on all OS.
Screenshots:
https://user-images.githubusercontent.com/24818636/40887609-55c95314-6719-11e8-8982-cd18cb233002.png

https://user-images.githubusercontent.com/24818636/40887597-389ed8ae-6719-11e8-9412-e7a8778e1f8b.png

**Comment by LarioStax** [comment]
I have the same problem. I have selected night mode on the settings page, and it remembers that, so every time I go back to my profile/settings, it activates night mode. When I click on Curriculum and get transfered to learn.freecodecamp, the night mode is disabled. 

I assume the night mode should transfer over to the coding pages as well, since that is where it's most useful.

Tried Firefox and Chrome, happens on both of them.

**Comment by Flemo7** [comment]
Hi, its not just you, the same for me too.

Night-mode isn't available on learn.freecodecamp.com at the moment yet, its a bug.

**See:**
Known bugs we’re working on fixing this week:
Night Mode doesn’t work on the learning platform yet. We’re working on fixing this

https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130

Thanks.

**Comment by moT01** [comment]
I think it would be best if we could have the dark mode follow you around to all the FCC pages - when you open the forum you have to set the dark mode on there separately - it would be better if it was already set to dark since you changed it on your settings page

**Comment by digilou** [comment]
I was just about to report this, too, but glad to see a ticket is open for it. Night mode is critical for me.

**Comment by frank-rui** [comment]
The dark theme has been pushed to the client, Amazing!! Although, the code snippet area and promotes CSS doesn't match well with the background.  I am on MacOs and tested using Safari.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/27864196/42099261-8ef80e88-7bef-11e8-86a6-da25ca608f2d.png">

<img width="840" alt="image" src="https://user-images.githubusercontent.com/27864196/42099291-a0029496-7bef-11e8-967b-d0da3848d1cf.png">

**Comment by TadashiCZ** [comment]
On Windows on Opera it's the same. And also when I try to highlight something in the code editor I can't see what I highlighted because of the colour of the hightlight. (It's stays the same dark colour.)

**Comment by conradkay** [comment]
Issues all seem fixed. Night mode seems stable

**Comment by frank-rui** [comment]
The font color of the tutorial section feels too bright as its set to pure white. Its might help to ease the eyes that slightly lower the brightness.

As the font color of the coding column is more gray, if I dim the screen until the tutorial is less burning, the coding column could become too dark to distinguish the code.

Similar for the top navigation pan, which are too bright in contrast to the content. As the padding is small between the top-nav and the instruction-panel or coding panel, so that, the pure white search bar can be very distractive.

**Comment by huyenltnguyen** [comment]
This issue has been resolved so I'm going to close this issue thread. Thank you for reporting and happy coding!
