### ISSUE TITLE
Settings Page Broken

### ISSUE THREAD

**Issue by newnewb** [freeCodeCamp/freeCodeCamp#17426]
#### Describe your problem and - if possible - how to reproduce it

My whole settings page is bugged, I can't even switch between light and dark mode, as soon as I open the page, it was working before as I was able to switch it into dark mode and check a couple of other things.

Currently, no button is working I've tried changing any of the settings or the text fields but nothing is changing or saving, somethings result in JS errors, somethings just don't have any feedback, this happened after I completed a couple of challenges to claim the algo. certificate.

I have noticed a lot of people have raised issues regarding certificates, but I'm not sure if anyone has raised about the whole page just not working.

I've also tried Microsoft Edge but it had the same result

 Edit: Additionally, I log in using GitHub login

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: W10 Pro

#### If possible, add a screenshot here

![settings](https://user-images.githubusercontent.com/19394906/40893486-8aade16e-67b2-11e8-8517-3f2680f3b083.PNG)
![new](https://user-images.githubusercontent.com/19394906/40893489-8de8cbdc-67b2-11e8-8e25-7665e592d207.PNG)
![buttons](https://user-images.githubusercontent.com/19394906/40893495-91c8c07c-67b2-11e8-91ed-47bfe18afb8b.PNG)

**Comment by Chrono79** [comment]
I'm experiencing the same problem.

**Comment by Viceriel** [comment]
Me too. I'm unable to agree with Academic Honesty Policy. After  click on Agree button nothing happened. Different computers/browsers doesn't help.

**Comment by techtiger7** [comment]
Confirmed, I am unable to change between light/dark mode, accept the Academic Honesty Policy, or save any settings changes.

**Comment by NocteArmy** [comment]
I am also experiencing this issue. None of the toggle buttons within the profile settings are working, I cannot update my profile information nor can I see the section that is meant to be for claiming certificates.

**Comment by lngchn** [comment]
Same with my settings page. Sometime it doesn't load at all, just the navigation bar and the body is empty. None of the toggle buttons work, and the accept button for Academic Honesty Policy doesn't do anything.

**Comment by mvravn** [comment]
Same here - I just finished a certificate, but I can't claim it, since my settings page is broken.

Just when freeCodeCamp was updated, I could actually see all the certificates and change settings in the settings menu, but that has changed now. 

None of the toggle buttons work, the academic honesty doesn't work and none of the certificates show on the page. They don't work in different ways, however.

The Night Mode does shift from side to side when toggled, but the background colour remains while. The Privacy buttons highlight green on both sides and become unresponsive.

I haven't checked if the Danger Zone buttons works ;-)

The "Show me my public portfolio" button does work, however. Also, I finished a project after the new site went live and it has registered normally.

I cannot return to the "Settings" page from the "Public Portfolio" page.

If you have any questions or things you'd like me to try or do, please send and E-mail, I'd love to help in any way possible.

**Comment by Chrono79** [comment]
Probably the same problem as #17278

**Comment by newnewb** [comment]
@johnkennedy9147 Thanks for the update, most issues listed specific sections not working. I wanted to make it clear that not a single button was responsive or had any effect on top of the fact that the page had missing sections
