### ISSUE TITLE
Navigating back to previous challenge, reset all the submitted code

### ISSUE THREAD

**Issue by StubRavi** [freeCodeCamp/freeCodeCamp#17432]
#### Describe your problem and - if possible - how to reproduce it
It is happening after the update: When I go back to the previous challenge, it reset all the code even if I have submitted it already.

#### Add a Link to the page with the problem
No specific page because It is happening with all challenges.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Latest
* Operating System: Windows 7

**Comment by raisedadead** [comment]
I think you mean: You submitted and successfully passed a challenge. Then navigated away to a different challenge. And then you came back to the original challenge?

**Comment by StubRavi** [comment]
exactly

**Comment by raisedadead** [comment]
This is an expected behaviour. We are not storing the challenge solution on a localStorage or on the Database once it has been completed and submitted successfully.

Although you do have the option to download your solution if you needed to on the completion modal. Thanks for reporting. I am going to close this.
