### ISSUE TITLE
Sass - Apply a Style Until a Condition is Met with @while correct code can not pass!

### ISSUE THREAD

**Issue by C0nst4nt1ne85** [freeCodeCamp/freeCodeCamp#17479]
#### Describe your problem and - if possible - how to reproduce it
Despite having the correct code:

<style type='text/sass'>
  
  $x:1;
  @while $x<11 {
    .text-#{$x}{font-size:5px*$x;}
    $x: $x+1;
  }
  
  
</style>

The tests do not pass! And I know is correct because I asked on fcc forum and people copy pasted my code to check and they passed the test. Then tried again and failed then reset and worked again. Neither of this solutions works for me.
Forum thread:
https://forum.freecodecamp.org/t/sass-while-issue/196876

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10

#### If possible, add a screenshot here

![capture](https://user-images.githubusercontent.com/32928319/41083859-fcd4d718-6a3a-11e8-8eed-2d1e4714cbde.PNG)

**Comment by Bouncey** [comment]
@C0nst4nt1ne85 Thank you for reporting this issue.

Your code works for me in FireFox, but not in Chrome, which is weird. It is normally the other way around.

**Comment by C0nst4nt1ne85** [comment]
@Bouncey It worked for me to firefox also: 

Firefox
Developer Edition
61.0b9 (64-bit)

**Comment by ayerik** [comment]
I've noticed a lot of the SASS curriculum is bugged.  The explanation code in many lessons has typos with the variable names where the $ is being interpreted for something font related, and many of the tests are not passing even when the code is correct, like this one.

I'm willing to try to take on fixing this, but I'm a new contributor and new to SASS.  I've already tried looking online for other SASS tutorials for getting a handle on the syntax and haven't found much that's more than a brief few lines.  I'm also going to be without my laptop for a few days because of a repair needed, but can dive into it when I get it back.

**Comment by Nirajn2311** [comment]
@Bouncey Tested it in Chrome(67.0.3396.87) and firefox(60.0.1) and it didn't work in both places. Both are 64-bit.

**Comment by mattszcz** [comment]
#12699 root issue

**Comment by alexpedroza** [comment]
still having this issue: 
checked latest versions of Chrome & Firefox as well as IE edge on windows 10 OS
tried clearing cache & cookies & verified that the Element inspector reported correct font-sizes for each element!

**Comment by dariatkachuk** [comment]
I have the same issue in Chrome and Opera.

**Comment by MelinaRentzi** [comment]
Hello, I had the same problem today and ended up here. What worked for me is I tried submitting the code with a space between some of the variables with the "$" symbol like so:
`$ x = $x + 1;`
which of course didn't submit, then removed all spaces and success! Might have been an one-time event though. Before the success, I had the same issues as the previous people.
Thank you.

**Comment by jfitzsimmons** [comment]
I had the same issue about a month ago, went back to the challenge today, and it passed without issue.  Has someone fixed this?  I also recently updated chrome to:

Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by alexpedroza** [comment]
Thanks for the update, it looks like it might have been fixed, it passed for me!

**Comment by thecodingaviator** [comment]
@C0nst4nt1ne85 please check if its fixed for you too, if not try add ?run=disabled at the end of the link and then trying, if that works, please close this issue

**Comment by C0nst4nt1ne85** [comment]
@thecodingaviator yes it is fixed.

**Comment by enmcewan** [comment]
Did not work on Win 10 Chrome Version 70.0.3538.67 (Official Build) (64-bit)
Worked on Firefox Quantum 62.0.3 (64-bit)

**Comment by HarplingeTom** [comment]
Not working on win 10, Chrome Version 70.0.3538.102 (Official Build) (64-bit)
The odd thing is that it passes all tests except the the one for .test-1
I inspected the element using Chrome dev tools and saw that it had the correct font-size being applied.

**Comment by HarplingeTom** [comment]
Thanks for the prompt reply! Will do.

**Comment by HarplingeTom** [comment]
I tried it, [ctrl-enter] that is, fast, slow, random patterns; still no
dice.

**Comment by kalzimonium** [comment]
This still hasn't been fixed. First I thought it was my browser since I was using brave, then changed to chrome and the same. Then came to this thread and read that it is working for some people on firefox, tried it and it literally broke the brower everytime I typed my code. Firefox keeps giving me an error message that "this page is slowing down your broswer" and it gives me the options of "wait or stop it". I have even copied and pasted the correct solution to the test page and nothing. I always get the same result in the screenshots of this post.

**Comment by thecodingaviator** [comment]
The changes have not yet been pushed to production. They will soon be

**Comment by 0tho** [comment]
Just had this issue on Chrome
