### ISSUE TITLE
Code editor + console output not loading in IE11.0.9600.18163

### ISSUE THREAD

**Issue by bjorno43** [freeCodeCamp/freeCodeCamp#17499]
#### Describe your problem and - if possible - how to reproduce it
Open any challenge on https://learn.freecodecamp.org with IE11.0.9600.18163. Both the Code editor and the console output refuse to load.

#### Add a Link to the page with the problem
Tested pages:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/chaining-if-else-statements/
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

#### Tell us about your browser and operating system

* Browser Name: Internet Explorer
* Browser Version: 11.0.9600.18163
* Operating System: Windows 7 64Bit

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/29444287/41141262-a6a4a3d4-6af1-11e8-9c99-5692708d4d24.png)
![image](https://user-images.githubusercontent.com/29444287/41141273-ad7849a4-6af1-11e8-8a46-99a1e84f8b80.png)

The first screenshot is giving a syntax error. The second one is giving 2 access denied errors.

**Comment by dlaub3** [comment]
I'll investigate this issue. If it still exists I'll submit a PR.

**Comment by dlaub3** [comment]
I'm not sure if this issue is worth fixing. 

I made it as far as identifying line 378 of ReflexContainer.js uses Array.includes which is not supported in IE11 
https://caniuse.com/#search=includes

`return !_this4.isSplitterElement(child) && resizedRefs.includes(child.ref);`

If anyone else wants to look into this further it's worth noting that running IE11 as an administrator can help with permissions issues.
