### ISSUE TITLE
CSS variable doesn't working on IE.

### ISSUE THREAD

**Issue by adsingh14** [freeCodeCamp/freeCodeCamp#17546]
#### Describe your problem and - if possible - how to reproduce it
From CSS variable lesson, I just want to inform that IE doesn't supports [CSS variables ](https://caniuse.com/#feat=css-variables) as well as it's fallback value. 
It'd be great if your team will curate those lessons/challenges or add alternate CSS property with that.

```
background: black;  // IE & un-supported browsers
background: var(--var-name, black);
```

#### Add a Link to the page with the problem
Started from [this](https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once) lesson.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67+
* Operating System: Windows 10

**Comment by johnkennedy9147** [comment]
@adsingh14 Thanks for raising this. 

Fallbacks as described in this lesson are not for older browsers that lack CSS variable support, they are for when the variable has not been defined yet, or otherwise not able to be resolved.

The technique you mention of using a preceding more broadly supported CSS rule is also referred to as a fallback.

Ideally, I think there should be two lessons, one describing each.

@raisedadead whats the situation with adding additional lessons?

**Comment by moT01** [comment]
@johnkennedy9147 what did you have in mind for additional lessons? How about just a message in the first variable lesson that `CSS variables may not be supported in older browsers` or something

**Comment by johnkennedy9147** [comment]
In my opinion:
1. Lesson [attach-a-fallback-value-to-a-css-variable](https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable) needs corrected 
2. An additional lesson should be added after the lessons in screenshot below, lesson to show how to use this principle to form resilient css - ie fallback behaviour for css rules not understood by browser

![image](https://user-images.githubusercontent.com/26827682/44175049-ec269180-a0dc-11e8-9596-8d14de6589a3.png)

**Comment by joshalling** [comment]
I'd like to work on this.
