### ISSUE TITLE
404 Not Found - Javascript Record Collection

### ISSUE THREAD

**Issue by RenaudGagne** [freeCodeCamp/freeCodeCamp#17605]
#### Describe your problem and - if possible - how to reproduce it

In https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection 

1.
> Use bracket notation when accessing object properties with variables.

The link https://learn.freecodecamp.org/accessing-objects-properties-with-variables is a 404 Not Found.

2. 
> You may refer back to Manipulating Complex Objects Introducing JavaScript Object Notation (JSON) for a refresher.

The link to https://learn.freecodecamp.org/manipulating-complex-objects is a 404 Not Found.

#### If possible, add a screenshot here

![screenshot-learn freecodecamp org-2018 06 16-14-16-07](https://user-images.githubusercontent.com/14856170/41501296-db06aefe-716f-11e8-86e9-b7c0e95a44b6.png)

**Comment by Nirajn2311** [comment]
This issue should be moved to curriculum module and I will work on the fix in the meantime.

**Comment by haydaralrikabi** [comment]
You can access the missing links here:
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables/](Accessing Object Properties with Variables)
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects/](Manipulating Complex Objects)

**Comment by Bouncey** [comment]
Hi @RenaudGagne, thanks for the issue. The reason they are 404 is because the route does not exist. We changed the challenge routes to help with SEO and there was no easy way of mapping them on learn as learn is a static site hosted on netlify.

If you had gone to `https://www.freecodecamp.org/accessing-objects-properties-with-variables`, you would have been redirected to the corresponding page on learn.

I am closing this as not an issue with the learn repo.
