### ISSUE TITLE
Set the font-size for multiple heading elements

### ISSUE THREAD

**Issue by aydinulusoy** [freeCodeCamp/freeCodeCamp#17613]
What's wrong with this lesson ,I added the font-sizes for all the elements but it keeps telling me that my h5 and h6 font-sizes are wrong

https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by mpmaan** [comment]
@aydinulusoy I am able to pass this test. I will be helpful if you can attach a screenshot containing your code and the test result.

**Comment by Asjas** [comment]
Hi @aydinulusoy

There is nothing wrong with this challenge. I was able to pass this challenge.

Please either attach a screenshot of your code here or post your code here.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
