### ISSUE TITLE
Button on Homepage returns Error

### ISSUE THREAD

**Issue by supuun** [freeCodeCamp/freeCodeCamp#17610]
after clicking 'Go to the coding curriculum' button on the homepage
![screenshot_2018-06-17 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/11631221/41508907-c2cc1354-725c-11e8-98de-d03e8070cf04.png)
I get this message
![screenshot_2018-06-17 https learn freecodecamp org](https://user-images.githubusercontent.com/11631221/41508911-ca4b76b0-725c-11e8-927f-16c2fbad30b5.png)

**Comment by supuun** [comment]
I'm using Firefox Nightly, but I tried this in chrome, too

**Comment by thatnini** [comment]
Clicking on the button takes you to [https://www.freecodecamp.org/challenges/current-challenge](https://www.freecodecamp.org/challenges/current-challenge) which then redirects you to your current challenge. This will be different for every person.

What is the link in your address bar as its not in your screenshot?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I’m closing this issue. When staging will be pushed to production again, your issue will be resolved.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

https://github.com/freeCodeCamp/freeCodeCamp/pull/17528
