### ISSUE TITLE
Code example incorrectly displaying wrong text in RegEx challenge: Use Capture Groups to Search and Replace

### ISSUE THREAD

**Issue by kamphare** [freeCodeCamp/freeCodeCamp#17620]
#### Describe your problem and - if possible - how to reproduce it
Heya! Sorry, I'm very new to this so I'm not sure how it works. There seems to be a bug with the example text for using $ to access capture groups. 

Here's what appears for me:
![image](https://user-images.githubusercontent.com/177903/41541971-142f0fc8-7314-11e8-8a9b-8dc5c3d79b75.png)
Though it's supposed to say: "Code Camp".replace(/(\w+)\s(\w+)/, '$2 $1');

The first number is some sort of "mathjax" thing(?). When I refresh the page the text briefly appears correctly, before it changes to the incorrect one. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/use-capture-groups-to-search-and-replace/

#### Tell us about your browser and operating system
* Browser Name: Chrome
* Browser Version:  Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by anku255** [comment]
By looking at the [challenge file](https://github.com/freeCodeCamp/freeCodeCamp/blob/ec63a2fff09cf1e45c2a6f9ae31af1b352039ead/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L1636) I can that the challenge text does indeed say `"Code Camp".replace(/(\w+)\s(\w+)/, '$2 $1');` 

The reason it doesn't show up like that is because `MathJax` interferes with it because of `$` sign. 

I can try to fix it. My only confusion is that should I correct the file in `freecodecamp` repo or `curriculum` repo?
