### ISSUE TITLE
continued login issues

### ISSUE THREAD

**Issue by wesgray76** [freeCodeCamp/freeCodeCamp#17636]
#### Describe your problem and - if possible - how to reproduce it
I try to login and get this: 

![image](https://user-images.githubusercontent.com/28853982/41599218-2465ceca-7398-11e8-88d5-b5e52236c4a2.png)

I try to login through twitter and get this:

![image](https://user-images.githubusercontent.com/28853982/41599283-507dcc88-7398-11e8-9834-c51116d1cbb4.png)

I am able to login through my android app.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.87
* Operating System: windows 10

**Comment by raisedadead** [comment]
Hi @wesgray76 

The twitter error that you get is valid. This is expected, because we do not have a twitter account associated on records with your profile https://www.freecodecamp.org/wesgray13

I have already sent you an email, and lets discuss there. Unfortunately, opening fresh GitHub issues is not going to expedite this any further.

This looks like an isolated case with your user account, which we are looking into.

We appreciate your patience.

Thanks.

**Comment by wesgray76** [comment]
Looks like this is on my end. I was able to login on my wife’s computer just fine and I am able to login from my Android phone. However, I cannot login onto my own PC. Thanks for your help, but it looks like if I want to get on FCC, I can’t do it on my machine. Thanks for your help.

Wes Gray

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
