### ISSUE TITLE
CSS Flexbox: Use the align-items Property in the Tweet Embed

### ISSUE THREAD

**Issue by virgilt** [freeCodeCamp/freeCodeCamp#17724]
#### Describe your problem and - if possible - how to reproduce it

The challenge (Use the align-items Property in the Tweet Embed) is using the property incorrectly.

h3 and h4 should be using “align-self” instead of “align-items”

If I use use “align-items” on h3 and h4 is does nothing because “align-items” is meant for the flex container (the parent of the flex items)

“align-items” should be used for “header .profile-name” which is the flex container for h3 and h4

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed

#### Tell us about your browser and operating system

* Browser Name:  Opera
* Browser Version:  Opera 53
* Operating System:  Windows 10

**Comment by anku255** [comment]
@virgilt I agree with you that `align-items` is a property of a `flex` container and setting it on `h3` and `h4` element doesn't make any sense.

However, I am not sure if we want to set `align-items: center` to the `header .profile-name` because it's already vertically centered by 

```css
  header .profile-name {
    display: flex;
    flex-direction: column;
    justify-content: center;
  }
```

Setting `align-items: center` would center things horizontally which is probably not what we want. 

I think we should only keep the first test in this challenge as the rest 2 of the tests don't make any sense.

I will make a PR if you agree with this.

**Comment by virgilt** [comment]
@anku255 I agree about not setting align-items: center, if anything it should be align-items: flex-start, which is also unnecessary since it will only replicate what is already happening. 

I was only trying to explain that align-items: center will not work for the h3 and h4 but would work for header. Whether it's visually better or not is up to the individual, although like I said I agree with you that it is unnecessary.

Go ahead and make the PR.

Cheers

**Comment by anku255** [comment]
@virgilt I have created a PR. Let's see what happens :)
