### ISSUE TITLE
Gateway 502 Error - Responsive Web Design Certificate

### ISSUE THREAD

**Issue by GMradu** [freeCodeCamp/freeCodeCamp#17722]
Hi Guys,

There was this issue last days when none of us could claim the certificate for Responsive Web Design. 
It was fixed and now you can claim it. 
But after this, the button that was used to claim the certificate has a new role, to see the certificate. When you press the button to see your certificate, it opens a new tab and displays a Gateway 502 error. 

#### Add a Link to the page with the problem
https://www.freecodecamp.org/certification/fcc8277aca2-a0ec-403c-9f15-f61e8cc2d103/responsive-web-design

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10. 

#### If possible, add a screenshot here
![capture](https://user-images.githubusercontent.com/40537994/41908722-a378d58a-794d-11e8-84c5-595fb4cec06b.JPG)

Do you have any thoughts on this? 
First I thought that maybe there is a simple connection issue with the server but this last for 10 hours ( at least that's the time I know of).

Thank you!

**Comment by Asjas** [comment]
It might be a connection issue. I just tested mine and it now opens the certificate.

**Comment by GMradu** [comment]
I just tested from my phone which is using another provider and I got the same gateway 502 error.

**Comment by johnkennedy9147** [comment]
@Asjas can you confirm if you opened @GMradu certificate using above link, or you viewed your own?

My certs are working on real and test ids. 
The link @GMradu provided above gives bad gateway.  
However, I cannot open his profile either.
Eventually the request to get public profile will timeout.

![image](https://user-images.githubusercontent.com/26827682/41916942-229ff4bc-7951-11e8-8439-7294546237da.png)

@GMradu Can you try:
Logging out and back in.
Verify the link you provided is correct one - same username?
Check the status of your profile, what privacy settings for example.

I think this will be specific to your id, rather than a general issue.

**Comment by GMradu** [comment]
@johnkennedy9147  thank you for the advice.
I had figured out what was the issue. So I discovered a new bug.
While my profile settings were in night mode it seems that has it's own profile privacy. I don't think this is how it supposed to work but when I changed my profile to day mode I was able to get my certificate and I was able to change the privacy from public mode to private and vice-versa.

**Comment by johnkennedy9147** [comment]
closing as issue was resolved
@GMradu if you think you have found a new issue could you please create an issue and provide details of the problem and how to recreate it , thanks
