### ISSUE TITLE
Wrong Accepted Answer in Regular Expressions: Restrict Possible Usernames

### ISSUE THREAD

**Issue by abnogueira** [freeCodeCamp/freeCodeCamp#17733]
#### Problem:
The following code was accepted as a resolution of Regular Expressions: Restrict Possible Usernames
`let userCheck = /[a-zA-Z][a-zA-Z][a-zA-Z]+[0-9]*$/; // Change this line` 
Obs.: no modifications were applied to the other lines.

This code works for the test cases but it's not the correct answer to the challenge of Restrict Possible Usernames, due to the fact that usernames have to be at least two characters long.
After submitting this answer I realized how wrong it was, it should be (or some variation of):
`let userCheck = /[a-zA-Z][a-zA-Z]+[0-9]*$/;`

#### Link to the page with the problem
Page: [Restrict Possible Usernames][1]

#### Browser and operating system:
* Browser Name: Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

[1]: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

**Comment by bikingbadger** [comment]
I came across this issue too, I was able to pass the challenge using this:
`let userCheck = /^[a-zA-Z]./;`
which is not the required answer, although I think the challenge might need re-phrasing or thinking about the logic. 
If the username can end with zero or more numbers there's not really a way to validate this, they either use the numbers or not at the end. Might be better to state that the username can't include numbers in the name itself and only at the end.

**Comment by bikingbadger** [comment]
There also seems to be an open PR #18696 for this

**Comment by RandellDawson** [comment]
@abnogueira , @bikingbadger This issues referenced here have been resolved on the `master` branch and can be verified on our beta site at https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

There actually is another PR open right now that improves the tests even more, but for now I am closing this one due to the beta site showing your two solutions would not correctly fail.

@abnogueira Based on the current tests (not sure if they are the same as what you saw when you first opened this issue), but your `let userCheck = /[a-zA-Z][a-zA-Z]+[0-9]*$/;` would fail the last test of `Your regex should not match BadUs3rnam3` based on the 1st instruction requirement of:
```
1) The only numbers in the username have to be at the end. There can be zero or more of them at the end.
```
