### ISSUE TITLE
Bug in ES6: Create Strings using Template Literals with Err Msg: Invalid regular expression flags

### ISSUE THREAD

**Issue by frank-rui** [freeCodeCamp/freeCodeCamp#17788]
#### Describe your problem and - if possible - how to reproduce it
The Challenge, ES6: Create Strings using Template Literals, return an error message Invalid regular expression flags.

My solution is,
```
arr.map(a=>`<li class="text-warning">${a}</li>`);
```
where the console log shows the correct solution,
```
["<li class="text-warning">no-var</li>", "<li class="text-warning">var-on-top</li>", "<li class="text-warning">linebreak</li>"]
```

And the full code is,
```
const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray = arr.map(a=>`<li class="text-warning">${a}</li>`);
  // change code above this line

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
 **/
const resultDisplayArray = makeList(result.failure);
console.log(resultDisplayArray);
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Win10

**Comment by zeb-stephen-downs** [comment]
I can confirm that this and the related issue (https://github.com/freeCodeCamp/freeCodeCamp/issues/16358) has been preventing completion of this since December 2017.

**Comment by alhazen1** [comment]
This "Invalid regular expression flags" error appears to be a recent development. Solutions that did not use bracket notation were passing tests without problem as recently as 6/30/2018. 

 #16358 as mentioned by @zeb-stephen-downs has been an issue with that challenge for a while. The workaround for that - use map, forEach or for...of - is no longer an option though.

**Comment by fr4p** [comment]
I'm a new learner and ran into this one about an hour ago, been driving me mad.  Glad to see it's a bug!  Looks like you guys are all over it.

**Comment by vonalogue** [comment]
I, too, have encountered this problem when using the map function exactly as people have shown.

**Comment by AndrewJBateman** [comment]
I have encountered this problem when using the map function just like everyone else.

**Comment by 2series** [comment]
Invalid regular expression flags. Solution??????

**Comment by kevinsmithwebdev** [comment]
At the risk of putting my foot in my mouth (sorry, new to open source)...

This issue is a recent one. Many have had problems on this test, usually because they hard code the answer instead or loop/map.  But for a few days now, answers that worked are no longer working. In the other repo, I see this is the test:

        {
          "text": "Template strings were used",
          "testString":
            "getUserInput => assert(getUserInput('index').match(/`<li \\s*class\\s*=\\s*(\"\\s*text-warning\\s*\"|'\\s*text-warning\\s*')\\s*>\\s*\\$\\s*\\{(\\s*\\w+\\s*|\\s*\\w+\\s*\\[\\s*[\\w]+\\s*\\]\\s*)\\}\\s*<\\s*\\/li\\s*>`/g), 'Template strings were used');"
        }

That was changed a few days ago from this:

     "getUserInput => assert(getUserInput('index').match(/\\`<li class=\"text-warning\">\\$\\{\\w+\\}<\\/li>\\`/g), 'Template strings were used');"

Sorry, my regex isn't good enough to spot the issue.

**Comment by hbar1st** [comment]
I wonder if the problem is that the last backtick is not escaped in the new code?
(Noticed that the first backtick is escaped but not the last)
I also notice that the double quotes are escaped but no the single quotes. Not sure why. 

I also wonder if all the extra (double) backslashes are needed. Once I removed them (and some space matchers that seemed too much) and tested the regex on an external regex test engine, it worked fine for me. That is this: 
```
 /`<li \s*class\s*=\s*("\s*text-warning\s*"|'\s*text-warning\s*')\s*>\s*\$\{(\s*\w+\s*|\w+\s*\[\s*[\w]+\s*]\s*)\}\s*<\s*\/li\s*>`/g
```
matched for eg:
`<li class="text-warning">${arr[i]}</li>`
it also matched:
`<li class="text-warning">${arr}</li>`

Notice I didn't escape the back-ticks etc. but here's another version with some escaping (for backticks and quotes) that still works:
\`<li \s*class\s*=\s*(\"\s*text-warning\s*\"|\'\s*text-warning\s*\')\s*>\s*\$\{(\s*\w+\s*|\w+\s*\[\s*[\w]+\s*]\s*)\}\s*<\s*\/li\s*>\`

I would also say that it looks like this change was not adequately unit-tested. It seems  a simple unit-test would have caught a few of these issues.

**Comment by alhazen1** [comment]
@kevinsmithwebdev @hbar1st  I think this is just the latest of a couple changes in past day or so. 
They seem to be having problems with escaping the last few characters.

This is what I saw recently (yesterday?) with / before li not escaped
```<\\s*/li\\s*>\\`/g)```

Now you are seeing with last backtick not escaped
```<\\s*\\/li\\s*>`/g```

I would think that 
```<\\s*\\/li\\s*>`\\/g```
might fix things

@hbar1st The reason for the doubly escaped characters is that in addition to the normal escaping for regex the test is wrapped in quotes too. It is delivered as a very long string.

**Comment by zeb-stephen-downs** [comment]
Yeah, if you remove the double backslashes and insert a backslash to escape that forward slash on the last li, it matches; I checked it with a regexp matcher online against the code I had written for the exercise. This is the last obstacle preventing me from completing my certificate.

`<li \s*class\s*=\s*(\"\s*text-warning\s*\"|\'\s*text-warning\s*\')\s*>\s*\$\s*\{(\s*\w+\s*|\s*\w+\s*\[\s*[\w]+\s*\]\s*)\}\s*<\s*\/li\s*>`

**Comment by scissorsneedfoodtoo** [comment]
Hi all, thank you for reporting this and coming up with different solutions. You're right, this is a recent problem that was caused by updating the regex to account for different solutions, but unfortunately we didn't escape that last forward slash. This was fixed recently and will hopefully be on the production site soon.

**Comment by davidsimoes** [comment]
@scissorsneedfoodtoo When will the fix roll out? Just to let you know it keeps showing the same error for my solution too:
`const resultDisplayArray = arr.map(el => `<li class="text-warning">${el}</li>`);`

**Comment by scissorsneedfoodtoo** [comment]
@davidsimoes, I'm sorry, I can't say for sure. I'm not able to do it myself, so we'll have to wait for one of the main team members to trigger the build of a new NPM package, then update the learn platform to use that rather than the current curriculum package.

Another member is working to further improve the challenge. You can follow his progress here: https://github.com/freeCodeCamp/curriculum/issues/135

**Comment by KDCinfo** [comment]
Just hit this as well. First with `.map()`, then tried a normal `for` loop while `.push()`ing the literals. 

**Error:** `Invalid regular expression flags`

**Comment by emmanuel19264** [comment]
I also encountered the same problem,  even tho my browser is up-to-date, chrome actually!
Thanks...

**Comment by cj-sv** [comment]
Can confirm, still having the issue as well. Hopefully gets pushed soon.

**Comment by Johnny2136** [comment]
Still buggy... My solution, (though I tried the looping solution and some listed above)
**No luck** 
```javascript
// change code below this line
  const resultDisplayArray = arr.map(obj => `<li class="text-warning">${obj}</li>`);
// change code above this line
```
yeilds:
```
// running test
Invalid regular expression flags
// tests completed
````
I hate leaving assignments undone, does anyone have a workaround? 🐞

**Comment by salva73** [comment]
Same here

**Comment by mrvkv** [comment]
Still getting the same error while my code is right. Kindly fix the bug.

**Comment by blazk0** [comment]
this was driving me mad even tho my solution was correct 
i even copied one of solutions and still no hope lol

**Comment by Szlavicsek** [comment]
problem still up, super annoying

**Comment by walmello24** [comment]
there is no way to get past from this exercise?

**Comment by emmanuel19264** [comment]
Yah, I hope so too.

**Comment by eklavyus** [comment]
This works for me for today: 21-08-2018
No Bugs for: template strings were used
const resultDisplayArray = arr.map(err => `<li class="text-warning">${err}</li>`);

**Comment by Johnny2136** [comment]
Worked for me as well! Way to go FCC! ✨

**Comment by mrvkv** [comment]
passed the test case. Now I think issue is solved. Thanks
