### ISSUE TITLE
Write Concise Object Literal Declarations Using Simple Fields - Function output is not checked

### ISSUE THREAD

**Issue by PortableStick** [freeCodeCamp/freeCodeCamp#17784]
#### Describe your problem and - if possible - how to reproduce it

1) Add any code into the challenge field (other than a valid solution) that will not result in a syntax error. 
2) Run the tests

Expected result: 
The test should fail

Actual result:
The test passes

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-concise-object-literal-declarations-using-simple-fields/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version:  61.0
* Operating System: 10.12.6 

#### If possible, add a screenshot here

![fcc_challenge_test](https://user-images.githubusercontent.com/6478756/42134245-b83ffa32-7d05-11e8-9122-0c1c80295035.gif)

**Comment by oliverjam** [comment]
The problem is this test in the [seed file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/write-concise-object-literal-declarations-using-simple-fields.english.md):

```js
assert(() => {
  const res = { name: "Zodiac Hasbro", age: 56, gender: "male" };
  const person = createPerson("Zodiac Hasbro", 56, "male");
  return Object.keys(person).every(k => person[k] === res[k]);
}
```

It returns true if `createPerson` returns an object with no keys, or just not-an-object.

I assume we should really be using something like `assert.deepEquals()` to check the expected object and the user's output object are the same.

**Comment by ezioda004** [comment]
Working on a fix.
