### ISSUE TITLE
Stop displaying my public portfolio

### ISSUE THREAD

**Issue by MonikaPatelIT** [freeCodeCamp/freeCodeCamp#17793]
#### Describe your problem and - if possible - how to reproduce it
I can't see my public portfolio from "Show me  my public portfolio" button even though all my privacy setting is public. 

#### Add a Link to the page with the problem
https://www.freecodecamp.org/monikapatelit

#### Tell us about your browser and operating system

* Browser Name: Crome
* Browser Version: 67.0.3396.99
* Operating System: windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/9668906/42140357-82bc7f50-7df2-11e8-9fc8-c9a3bf904a8b.png)

![image](https://user-images.githubusercontent.com/9668906/42140341-48c35da0-7df2-11e8-88d9-33cfadb376cd.png)
when i changed all the public to private and change back to public give this 
![image](https://user-images.githubusercontent.com/9668906/42140334-365727a0-7df2-11e8-8085-61776a7c2f7c.png)

**Comment by huyenltnguyen** [comment]
@MonikaPatelIT I think there was a change recently that set our profile completely private by default.

The funny thing is, the colors of the toggle buttons in night mode are the other way around, which means the selected options are in grey instead of green 🙃 I will report this issue later.

So if you want to make your profile public, you would need to manually set it back. I would suggest you switch to day mode before toggling those buttons, just for sanity 😄

**Comment by theREALaltoid** [comment]
Would adding a different color to the buttons fix this issue?

**Comment by moT01** [comment]
Thank you for reporting this issue.

    It looks like you figured this out so I am closing this issue.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
