### ISSUE TITLE
Feature Request : Esc key hides the donation popup

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/freeCodeCamp#17834]
#### Describe your problem and - if possible - how to reproduce it
Pressing `Esc` key should disable/hide the donation popup. This way users won't have to scroll the page just to close the popup if they don't wish to donate.

**Comment by scwong93** [comment]
When and where does the donation page pop up?

**Comment by mpmaan** [comment]
@scwong93 It pops up randomly after a challenge has been submitted successfully on [learn.freecodecamp website](https://learn.freecodecamp.org)

**Comment by RandellDawson** [comment]
@raisedadead Has something like this already been implemented on freecodecamp.rocks?

**Comment by raisedadead** [comment]
We do not have a Hot key mapped to the modal. We may do so in future, depending on what @QuincyLarson thinks of it.

**The modal is shown only once per session (each browser tab).** 

This will become more better in the next release, because we would not have as many subdomains. User's will have more of a single page application navigation for all things freeCodeCamp!

**Comment by raisedadead** [comment]
We have decided to take a different approach. As of now, the modal is going to be disabled for a while. We will revisit the modal in future.

**Comment by raisedadead** [comment]
Thanks for commenting. I have requested Quincy to address this.
