### ISSUE TITLE
Mistake in ES6 - Destructuring Nested Objects

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17855]
#### Describe your problem and - if possible - how to reproduce it

> We can similarly destructure nested objects into variables.
> Consider the following code:
>
>     const a = {
>       start: { x: 5, y: 6},
>       end: { x: 6, y: -9 }
>     };
>     const { start : { x: startX, y: startY }} = a;
>     console.log(startX, startY); // 5, 6
>
> **In the example above, the variable start is assigned the value of a.start, which is also an object.**

Is the bold text correct? because when I want to console.log start variable, it's not defined.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects/

**Comment by mpmaan** [comment]
@jooji-san Yeah, it seems correct to me.
For example 
>var o = {p: 42, q: true};
var {p: foo, q: bar} = o;
console.log(foo); // 42 
console.log(bar); // true

>var o = {p: 42, q: true};
var {p, q} = o;
console.log(p); // 42
console.log(q); // true

In the second case, you can access `p` and `q` because the values corresponding to `p` and `q` have assigned to `p` and `q`. However, in the first case, those values have been assigned to `foo` and `bar` so `p` and `q` can't be accessed.
Find more info at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
You can always ask for help/feedback on [Gitter](https://gitter.im/FreeCodeCamp/YouCanDoThis?source=orgpage) as well.
If you have no further problem, then please close this issue.

**Comment by nathanhannig** [comment]
You are correct @jooji-san 

start is never defined and this is a huge typo

startX and startY are defined
