### ISSUE TITLE
ES6: Constructor Function - note about Capitalization

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17864]
#### Describe your problem and - if possible - how to reproduce it
They are named with capital letter first after convention and I think this should be noted in this challenge.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function

**Comment by ezioda004** [comment]
We have a note on [function constructor lesson](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/define-a-constructor-function/).
I think it's fine to add a note since we do have it in the above challenge (and this challenge comes before above mentioned one)
@RandellDawson thoughts?

**Comment by RandellDawson** [comment]
@ezioda004 I reviewed the note.  I think it is fine, but I think it needs to be on a separate line (like a new paragraph).
