### ISSUE TITLE
ES6: Understand the Differences Between import and require

### ISSUE THREAD

**Issue by roshad** [freeCodeCamp/freeCodeCamp#17866]
require() is not a plain JS function, it is in Node.js. Should mention it.

**Comment by alanpaulprice** [comment]
@ezioda004 How about:

**Note**
You must have [Node.js](https://nodejs.org/) installed in your project to use `require()`, as it is not a native JavaScript function.

**Comment by ezioda004** [comment]
@alanpaulprice You don't really "install node.js" in your project, you run your project in node run-time/environment.
I think something along the lines of 
>require() is only available in Node.js environment and isn't available in browsers.

Verbiage can be improved.

Tagging @cmccormack for input.

**Comment by cmccormack** [comment]
I think it's worth stating that it's built in to Node, while being available outside of node through installed packages.

**Comment by ezioda004** [comment]
Sounds good to me.

**Comment by alanpaulprice** [comment]
I'm not sure how to word this one. As a start, maybe:

**Note**
`require()` is not a native JavaScript function. To use it, you must run your project in a Node.js environment or install a relevant package(?), such as ...(?).

It'd be great if someone could iron it out.

**Comment by ezioda004** [comment]
Do we need to give an example? On second thought - should we really mention that `require()` can be used in browser? Since modern browsers already support ES6 modules out of the box.

**Comment by alanpaulprice** [comment]
>Do we need to give an example?

It's not essential, for sure.

Could we get away with just stating that it isn't a standard JS function? I feel like the extra detail might not be worthwhile. This challenge is basically telling the user that `require()` is obsolete and they should be using `import` instead?

**Comment by ezioda004** [comment]
@alanpaulprice That seems fine. Since all modern browsers now support ES Modules, we should be advocating people to use those instead of any 3rd party libraries.

**Comment by RandellDawson** [comment]
Is anybody interested in working on this issue?

**Comment by ritute** [comment]
I think the consensus here is to add a note saying that `require` is not a standard JS function. The 2nd note on this challenge could be a good location to add this:

> The lessons in this section handle non-browser features. import, and the statements we introduce in the rest of these lessons, won't work on a browser directly. However, we can use various tools to create code out of this to make it work in browser.

However, this challenge assumes you're already familiar with what `require` is, so I'm not even sure this is a worthy add on its own. It'd be better to point to a challenge/guide/article that explains the use of `require`, so that this challenge solely focuses on the ES6 `import` and the differences to `require`.

---
A slight diversion, but still pertaining to this challenge (might be more appropriate for a new issue?): I think the expected solution to this challenge is wrong - the instructions state that the `string_functions` file lives in the _current_ directory, and there's a note right above stating that node will look into the node_modules directory unless the relative ./ path is specified; one would think the solution should import "./string_functions", but this doesn't pass the test (it expects "string_functions" instead).

> In most cases, the file path requires a ./ before it; otherwise, node will look in the node_modules directory first trying to load it as a dependency.

**Comment by moT01** [comment]
fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/36144
