### ISSUE TITLE
Uploaded wrong project as solution - accepted

### ISSUE THREAD

**Issue by fgspechti** [freeCodeCamp/freeCodeCamp#17907]
I hope I haven't overseen if there is already an issue reported. I started the challenge for Responsive Web Design and was working on the projects for this. After uploading the second project (the Survey Form) I could see that it wasn't accepted. So I refreshed the Curriculum page and could see that it was accepted - for the Product Landing page. It doesn't meet the specifications for that. Unfortunately I don't have more information about this. Only - that the Survey Form also shows up in my Settings as project for the Product Landing page.

https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page

* Browser Name: Mozilla Firefox
* Browser Version: 61.0.1 (64-Bit)
* Operating System: Windows 10 Pro

**Comment by nathanhannig** [comment]
We will have to check the issue you mentioned occurring from the Challenge page.

**To fix:**
On the Settings page, the website requires a valid URL for these fields once you have changed them. 

In order to remove the URL for Product Landing page, you will have to specify another URL since a "blank value" will not be saved.

I recommend leaving the value and just update it with the correct URL once you know what it will be for Product Landing Page.

---
I do also recommend that fCC allow "blank value" to be saved for URLs in case a mistake is made and a user needs to reset the value. However, the one issue I found is once all values are URLs the setting page changes the Save button to Claim Certificate button and saving/changing of URLs can no longer occur.

**Comment by thecodingaviator** [comment]
@fgspechti We do not check each project and so we have no way to tell if the student has submitted the correct project. All you can do is wait before submitting and then correct the URLs before submitting for claiming certification.
Rest info has been given above by @nathanhannig 
Please close the issue.

cc: @ezioda004

**Comment by fgspechti** [comment]
Thank you both for your help - and my apologies that I missed to close the case!
