### ISSUE TITLE
Semicolon after inline style declarations is not consistent

### ISSUE THREAD

**Issue by nlakritz** [freeCodeCamp/freeCodeCamp#17909]
1.) Here, it is suggested to follow the semicolon convention for inline style declarations (see below): https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text

```<h2 style="color: blue;">CatPhotoApp</h2>```
Note that it is a good practice to end inline style declarations with a ; .

2.) However, it is not maintained here (see below): https://learn.freecodecamp.org/responsive-web-design/basic-css/override-class-declarations-with-inline-styles

Remember, in line styles look like this:
```<h1 style="color: green">```

**Comment by ByronCoder** [comment]
Hello,

I am new to Github and contributing to Open source! I am confused on the different repos for freeCodeCamp. I have this repo (freeCodeCamp) and the curriculum repo.  I see the curriculum files are in the curriculum repo but this repo no longer has the seed files that the contributing doc says is where to edit challenges,  so I am trying to figure out where this change needs to be made. I made it in my fork of the curriculum repo, but I am not sure because this issue is in the freeCodeCamp repo.

**Comment by nathanhannig** [comment]
It looks like the PR was submitted to fix the issue. But you are correct Byron that the change would be in Curriculum repo. I am actually not sure what seed is for at the moment.

FCC is undergoing heavy changes to split the codebase into separate parts to increase maintainability.

For faster help I recommend you join the Gitter chatroom for FCC  :)
