### ISSUE TITLE
No link to "about" page

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#17915]
Hey team

https://www.freecodecamp.org does not have a link to the "about" page, which is at https://about.freecodecamp.org . I would expect it to live at the bottom of the page.

/cc @QuincyLarson

**Comment by raisedadead** [comment]
I have been long thinking about having a footer on all pages that link to all our services. But @QuincyLarson you will have to sign off on this first.

**Comment by migben** [comment]
Given the style of our website and story, we should place 'About' back in the nav bar. @ojongerius + @QuincyLarson ?

**Comment by ojongerius** [comment]
I think in the long term a footer would be beneficial. For now adding an `about` link to the nav bar sounds like a pragmatic solution to me 👍

**Comment by linkinmedo** [comment]
I would be happy to add about to the nav bar, let me know if you want me to do it.

**Comment by ojongerius** [comment]
Would someone be willing to create a small PR with the about link in the nav bar? 

@QuincyLarson would you be happy with that? In the meanwhile a footer could be discussed in a separate issue.

**Comment by QuincyLarson** [comment]
We don't want a footer or any nav links that distract from the core functionality (the curriculum and the forum).

Instead we want to integrate things into both the Settings page and the Welcome page.

Soon we will have important stories / videos / podcast episodes from the community on the welcome page, as well as upcoming events based (based on the user's geolocation). 

As for the other pages (about, donate, etc) people can google it. These aren't that important in the grand scheme of things.

**Comment by ojongerius** [comment]
I disagree.

I understand linking in the top is a little distracting. However, I think from a user experience perspective, having a small footer all the way down, which allows users to find things like "about" and "contact" in the page without distracting from the contents is better. It is *way* below the fold.

**Comment by QuincyLarson** [comment]
@ojongerius Thanks for your feedback. My experience has been that footers are ugly and don't get used that much.

Also the SEO value of footers [now seems to be negligible](https://moz.com/blog/links-headers-footers-navigation-impact-seo).

When you have a 3-column layout like we do with independently scrolling columns, where would we put a footer, and in what situations would it be visible?

Rather than have a footer, I'd argue we should have a drop down menu in the navigation where we could put additional links (we used to have a "Community" tab that did this). 

But then the question becomes: which links are worth including? Every link you include distracts from all the other links, so you only want to include the most important links - this keeps your navigation simple and unintimidating, and makes everything that does show up in the navigation stand out as important.

In the end, my conclusion was that we should have a few explicit links that people will actually click on and find value in. Currently those are "curriculum" and "forum" and in the future they will include "news" and "events" as well. When you consider the importance of those things, an "about" link seems pretty insignificant.

**Comment by Nirajn2311** [comment]
@QuincyLarson I agree for not including the footer as from the reviews of my own site, many of them didn’t like a footer. Also I had read in a article somewhere that the amount of users who actually scroll down a long website decreases with increase in length.
But I think there should be an About page as it provide an insight as to who the main people are behind this project.

**Comment by ojongerius** [comment]
Personally I'm only interested in a footer. That way I can find "contact" or "about" by using my browsers find function. If it would be hidden in a menu, I'd probably revert to using Google instead.

Different strokes for different folks, I guess I'm not a visual person 😺 And certainly not the average visitor.

**Comment by QuincyLarson** [comment]
@ojongerius Yes - it would be cool if we had a way to surface those links for control+f without cluttering the UI. We've tried a lot of approaches in the past to address this but just haven't been able to find something that both worked and didn't over-complicate the UI. My hope is people will use our built in search bar that now takes up a good chunk of the navbar, but time will tell :)
