### ISSUE TITLE
Minor grammar mistake in CSS Grid: Create Flexible Layouts Using auto-fill

### ISSUE THREAD

**Issue by dicoderr** [freeCodeCamp/freeCodeCamp#17990]
#### Describe your problem and - if possible - how to reproduce it
The first sentence says: "The repeat function comes with a option called auto-fill." The article "a" is incorrect. Should be "an option".

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/css-grid/create-flexible-layouts-using-auto-fill

#### Tell us about your browser and operating system

* Browser Name: Chromium
* Browser Version: 68.0.3440.75
* Operating System: Linux Mint 18.3 Sylvia

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/42048727/43828240-957c911e-9b04-11e8-99fd-51f72be53812.png)

**Comment by dicoderr** [comment]
Thank you! The contributor's guide is quite long. Also, I guess Egghead's course about contributing to an open source project is worth watching. Hope it won't take much time :-)

**Comment by dicoderr** [comment]
@Ashera138 "up for grabs".

**Comment by alpkoseoglu** [comment]
I am fixing the typo right now, is that ok?

**Comment by dicoderr** [comment]
@alpkoseoglu OK.

**Comment by Ashera138** [comment]
I'm struggling with git, so don't feel like you have to wait on me haha. @alpkoseoglu

**Comment by alpkoseoglu** [comment]
I failed so bad and stop trying, I think you can do it ! @Ashera138

**Comment by Ashera138** [comment]
So from what I can tell (bear with me - I'm very new to this), is that the file that this grammar mistake is in (freeCodeCamp/node_modules/@freecodecamp/curriculum/dist/challenges/01-responsive-web-design/css-grid.json) is generated or added after running `npm install` in git. I can obviously just go in this file, edit the change, and save it, but here's the problem I'm seeing:

That css-grid.json file is not in my git repo (since it was added after running that command), and even if it was, if it's something that's generated, you would need to change whatever creates that file upstream. That's beyond me. 

Please correct me if I'm wrong about anything. This is where I am stuck. :)

**Comment by moT01** [comment]
when you run `npm install` it will install all the things in the `package.json` file - included in this repos `package.json` file is this line - https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/package.json#L49 - this (`@freecodecamp/curriculum`) is the freecodecamp package that holds all the information for the challenges and it gets created from this repo - https://github.com/freeCodeCamp/curriculum - so to fix the typo you need to change in that repository - there's also a link to the exact file and line in the comment I made earlier

**Comment by Ashera138** [comment]
Alright, pull request submitted. Let's see how I did. 👍 https://github.com/freeCodeCamp/curriculum/pull/233
