### ISSUE TITLE
Simon Game Zipline marked as complete instead of Tic Tac Toe Zipline after update.

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#1800]
I had finished the Tic Tac Toe Zipline before the update. After the update the new Simon Game Zipline is showing as complete and the Tic Tac Toe Zipline is showing as not complete.

![image](https://cloud.githubusercontent.com/assets/6580703/9295565/c89a3b9c-4426-11e5-883c-9de80d0c01a7.png)

**Comment by SaintPeter** [comment]
I experienced this as well.

**Comment by denmch** [comment]
Same here.

**Comment by benschenker** [comment]
Any ideas @QuincyLarson or @benmcmahon100?

@1hella @SaintPeter @denmch is this still an issue for you?

**Comment by SaintPeter** [comment]
Yes, my map is still incorrect:
![image](https://cloud.githubusercontent.com/assets/553494/9702712/ae2f1ad0-541f-11e5-97b9-86ea2179791c.png)

My profile, though, does show my tic-tac-toe completion:
![image](https://cloud.githubusercontent.com/assets/553494/9702720/e41c37ae-541f-11e5-901b-5540b9f09deb.png)

**Comment by awesomeaniruddh** [comment]
I had the problem too.

**Comment by QuincyLarson** [comment]
Hi everyone, sorry I just now saw this issue (I need to go through these more often). Here's what happened: when I added the Simon challenge, I copied the Tic Tac Toe challenge and accidentally changed the Tic Tac Toe challenge's ID instead of the Simon challenge's ID.

For most campers, this was of no consequence. But for those who had already completed the Tic Tac Toe challenge, it ended up with the mixed up state it's in currently. I can fix it manually. Please respond to this issue telling me which of these challenges you've completed:

Simon 
Tic Tac Toe
or both

**Comment by SaintPeter** [comment]
I have completed Tic Tac Toe but not Simon.

**Comment by denmch** [comment]
I completed Tic Tac Toe. Almost done with Simon, but not quite there.

**Comment by 1hella** [comment]
Same. Tic tac toe but not simon.

**Comment by Em-Ant** [comment]
I have completed both. Thank you.

**Comment by alistermada** [comment]
I completed Tic Tac Toe. Still working on Simon.

**Comment by chuah48263** [comment]
I completed Tic Tac Toe. Still working on Simon.

**Comment by bugron** [comment]
@QuincyLarson @BerkeleyTrue any updates on fixing this issue?

**Comment by bugron** [comment]
Closing this issue. If you still have problems, please, feel free to reopen or left a comment here, thanks.
