### ISSUE TITLE
Ask for Help - Learn app to Forum Post URI length exceeds limit

### ISSUE THREAD

**Issue by nischaldutt** [freeCodeCamp/freeCodeCamp#18005]
#### Describe your problem and - if possible - how to reproduce it
Hi
I’ve found a bug in the given page. When I click on the “Ask for Help” Button and try to create help post in the forum, it gives a data transmission error as follows:

![3c51d48a0b8cdd296aee2f1dd16ca3cd0ae27c6a png](https://user-images.githubusercontent.com/25385285/43991822-20b53a76-9d92-11e8-836b-3eeaf6d0d82f.png)

I’ve tested this in Chrome and Mozilla Firefox. 

#### Add a Link to the page with the problem
Link to the challenge:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome and Mozilla Firefox Quantum
* Browser Version: Chrome version- Version 68.0.3440.84 (Official Build) (64-bit)
                               Firefox version-  Version 61.0.1 (64-bit)
* Operating System: Windows 10 and Ubuntu 16.04 LTS

**Comment by Nirajn2311** [comment]
In IPad, Safari, the error was 

> 414 Request-URI Too Large

**Comment by RandellDawson** [comment]
@raisedadead Not sure if this is a nginx or Discourse issue, but I did find [this thread on the Discourse forum](https://meta.discourse.org/t/error-414-when-posting-updating-via-api/98186/6) which might help.

**Comment by raisedadead** [comment]
Hi @RandellDawson 

Thanks for pointing me to the suggested thread on discourse. 

This is happening because the payload to the API is unable to handle the the length of the URI constructed by the learn app. Its simply large than the limit set on discourse side.

However, I am of the opinion that increasing the buffer for large URIs may not be the solution long term. Surely it will be a quick fix to this challenge, but down the lane when we have challenges that have larger URI's we will have to tweak it again. Also not to mention. It may be enabling external spam bots / scripts etc. on forum which we do not want.

This feature is there just to enable user's with the ability to create a post in a pre-filled template to help them. IMHO it's a nice to have and does not justify the need to tweak the config.

I think we should strip off the strings to the length required by removing the seed and solution part. User's will just copy paste it there. And we can do this for solutions that exceed a certain limit. 

We are creating the URI here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/fbc53ea257733a99bea7475f4b89a1c5b3242205/client/src/templates/Challenges/redux/create-question-epic.js#L50

i.e this method needs to sanitize strings above a char limit:

https://github.com/freeCodeCamp/freeCodeCamp/blob/fbc53ea257733a99bea7475f4b89a1c5b3242205/client/src/templates/Challenges/redux/create-question-epic.js#L11-L32

**Comment by RandellDawson** [comment]
> IMHO it's a nice to have and does not justify the need to tweak the config.

As a forum mod, it is not just "nice to have", it is extremely beneficial so we have the full code the user is working with.

>I think we should strip off the strings to the length required by removing the seed and solution part. User's will just copy paste it there. And we can do this for solutions that exceed a certain limit.

Where would this copy/paste take place?  On the forum, once the post has already taken place or somewhere in the modal popup window?  I would hope in the modal popup window somehow, because many users struggle with adding formatted code (after the fact) in their posts.  I would say formatting code posted in a user's post is one of the top 3 things the mods have to fix on a daily basis. 

If that is not possible, then maybe modify the existing forum help markdown template by modifying the current **Your code so far** section (as seen below).
````md
**Your code so far**

<h3>Warning</h3>

The challenge seed code and/or your solution exceeded the maximum length we can port over from the challenge.  You will need to take an additional step here so that we can view the code you wrote in a forum-friendly format. Please copy/paste all the editor code showing in the challenge from where you just linked.  into the section below marked accordingly and click the **Save Edit** button when finished.

```js

Replace these two sentences with your copied code. 
Please leave the ```js line above and the ``` line below,
because they allow your code to properly format in the post. 

```
````

**Comment by raisedadead** [comment]
The fix should only strip the seed section (by calculating the remaining chars in advance of the API request/URI Encoding). 

Everything else will still be there. Feel free to test it on any challenge from you local for the workflow to understand this better.

Again **this is a feature**, that we would love to support. And will work for most challenges, baring a few that have really large seed code. 

I would not like to reduce the best-practice limits for a server. We could bump the limit to something that works today, but will only break in future.

There will always be tradeoffs. IMHO we are in favor of an inconvenience on some challenges than bumping the limits of the entire forum.

A more elegant solution is more than welcome though.

**Comment by RandellDawson** [comment]
So what about my second option above?  Wouldn't that work for the challenges which are stripped of the code section which is too long?

**Comment by raisedadead** [comment]
Yes, I am in favor of something along that lines.

**Comment by jragard** [comment]
@raisedadead @RandellDawson @freeCodeCamp/dev-team 

We should be using a POST request to transmit the necessary data instead of encoding it into the URI as a super long query parameter.  Currently, after the URI is constructed, we are making a GET request by opening a new window with the specified URI.  

https://github.com/freeCodeCamp/freeCodeCamp/blob/fbc53ea257733a99bea7475f4b89a1c5b3242205/client/src/templates/Challenges/redux/create-question-epic.js#L60-L68

However, large blocks of data like this should be sent with a post request.  I actually checked and the URI for this particular issue is over 13,000 characters, while most clients/browsers have a default limit of 2,083 characters.

We would need to tweak the endpoint for the forum that handles requests at that route, as it is currently not handling POST requests.  Are the server endpoints for the forum somewhere within this repo's codebase, or is the forum a separate thing?  I poked around and couldn't find any endpoints dealing with the forum.  If anybody knows where those are, or if we can access them, I can take a crack at trying to fix this.

**Comment by jragard** [comment]
@raisedadead @RandellDawson

After playing with this a little more, I discovered that the character limit for the URI is currently set to 8,138...it appears that this problem has occurred in the past, and the limit was simply lifted.  While this is definitely not a good long term solution, especially if modifying the necessary forum endpoint proves trivial, I went ahead and implemented Randell's second option above....if the URI length is greater than 8000 characters, an alternative URI is used, which populates the forum post with the content Randell posted above.  The pull request is here

https://github.com/freeCodeCamp/freeCodeCamp/pull/36323

**Comment by raisedadead** [comment]
> We would need to tweak the endpoint for the forum that handles requests at that route, as it is currently not handling POST requests.

That is by design, and we are unable to open up the post endpoints. We are using a managed instance from the discourse team, and this is extremely involving coordination between our and their teams.

We are unfortunately going to be accepting the tradeoff of inconvenience on a few challenges, than having to deal with maintenance.

Thanks for your alternative solution on the PR. We will have this QA'ed and deployed in our next release.

**Comment by jragard** [comment]
> That is by design, and we are unable to open up the post endpoints. We are using a managed instance from the discourse team, and this is extremely involving coordination between our and their teams.

Ahh, that makes sense.  I suspected it might be some kind of situation like this.
