### ISSUE TITLE
Nasdaq Stock Price Checker Glitch Example not working

### ISSUE THREAD

**Issue by arblalock** [freeCodeCamp/freeCodeCamp#18023]
The current glitch example  (https://giant-chronometer.glitch.me/) for the [Information Security and Quality Assurance  - Stock Price Checker](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/stock-price-checker) project is not currently working.

I have not looked too deeply into the project yet, but this [FCC forum thread](https://forum.freecodecamp.org/t/stock-price-checker-project-with-testable-user-stories-guinea-pigs-needed/72753/6) indicates it may have to do with google blocking the stock api that is suggested in the instructions for the project:  https://finance.google.com/finance/info?q=NASDAQ

This project may need to be updated with a new suggestion for a free stock api to use

**Comment by numoonchld** [comment]
Linking a relevant resource from the forum discussion that might be helpful in fixing that project:
https://www.freecodecamp.org/forum/t/nasdaq-stock-price-checker/219399/8

**Comment by Em-Ant** [comment]
@QuincyLarson it's not one of the project that I built, but I had a quick look and it really seems that the problem is google blocking the api. We need a new api. If the project is under camperbot glitch account I can try to quickly fix it with the suggested new api. But the project seems to be owned by @JosephLivengood

**Comment by scissorsneedfoodtoo** [comment]
@Em-Ant, yes, it seems that the Google Finance API is no longer supported. Someone suggested using the [IEX Cloud API](https://iexcloud.io/) as an alternative in another thread. I'll see if I can get a copy of the original project over into the cpamberbot glitch account now.

**Comment by QuincyLarson** [comment]
@Em-Ant Have you had a chance to dig into this? Let me know if you need any help gaining access to this, or if you need me to create any new API keys.

**Comment by Em-Ant** [comment]
@QuincyLarson it seems that the camperbot credentials that i have are old and not valid anymore. Anyway the recommended new api requires an api key, it's not open.

**Comment by scissorsneedfoodtoo** [comment]
@Em-Ant, let me see if I can set you up with new credentials and configure some of the API keys. Took a closer look at the project and it seems like a Mongo Atlas plan and keys are also required.

**Comment by Em-Ant** [comment]
@scissorsneedfoodtoo i have access now, thanks. let me know if you find a free/open api to use

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Glad you got access.

Unfortunately it doesn't seem like there's a totally free API. Alpha Vantage might be our best bet, thought the default limits are really, well, limiting. Only 500 per day. As educators we could email them and see about getting that increased, though. I left a key for IEX Cloud just in case, though.

**Comment by Em-Ant** [comment]
ok. this one should be a working example, right ? Because there are also content security policy settings problems. front-end scripts are not executed. I'll try to fix that, let me know what you decide for the api. we could make a proxy with cache, like i did for the twitch api in the past.

**Comment by scissorsneedfoodtoo** [comment]
Yes, that's right, this is just the working example. Thank you again for digging into this, @Em-Ant.

As for the API, I'll send Quincy a message and ask for his input. Hopefully we'll be able to get in touch with the Alpha Vantage team to get those limits lifted.

**Comment by Em-Ant** [comment]
no problem.It's always a pleasure to help.  Let me know what you decide

**Comment by scissorsneedfoodtoo** [comment]
After going back and forth between the two, I think it's best we go with IEX Cloud for this project. Their free rate limits are the most generous, and we're unlikely to hit the limit with this example project. Since all we need are the most up-to-date stock NASDAQ stock prices, IEX Cloud should fit the bill. We should also be able to query multiple tickers easily with this format: `https://cloud.iexapis.com/v1/stock/market/batch?&types=quote&symbols=aapl,fb,tsla&token=API_TOKEN`.

Will this be alright on your end?

**Comment by Em-Ant** [comment]
@scissorsneedfoodtoo now https://glitch.com/edit/#!/sphenoid-crater is working with your provided api key (and one of my mLab sandox dbs). 

If we want to avoid that students need to create their own api key, we can build a proxy like i did for twitch, but we need to take into account the risk of somebody finding and using the 'open' edpoint for their purposes. 

Also the requirements are slightly wrong, since one user story is to allow scripts only from your server, but the front'end is loading jQuery from a CDN. I had to change the CSP settings to make it work. I deally we should remove the dependency on JQuery.

What do you think ?

**Comment by scissorsneedfoodtoo** [comment]
@Em-Ant, thank you for your patience and for fixing this project so quickly. It's working really well! I can make sure we switch out your mLab db string for one tied to an fCC account.

By this point in the curriculum learners should be able to find a suitable service and create their own API keys. I don't think we need to worry about a proxy for this one.

Great catch with the mismatch between the requirements and the implementation. You're right, it would be better to remove jQuery altogether. I messed around with the `/public/script.js` file and tried to replicate what the old project was doing with jQuery here: https://glitch.com/~bottlenose-mojoceratops. But please feel free to go with another implementation if there's a better one. Another contributor in https://github.com/freeCodeCamp/boilerplate-project-stockchecker/pull/5 changed the way the forms are handled in the `index.html` file, and it seems to pass all of the tests.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo I would recommend we do create a proxy like we did for the twitch API. This will save thousands of people time that they would otherwise have to spend getting set up for a service they may never use again.

And yes, @Em-Ant I agree about removing jQuery. We are removing it from Version 7.0 of our curriculum anyway, so it will be best to not have it here either. Thanks again for all your help with these projects.

**Comment by scissorsneedfoodtoo** [comment]
@Em-Ant, awesome, thank you again for all of your help with this. I'll create an empty project and label it right away.

About removing jQuery, I'll was doing some testing on a fork of your updated example project. Seems to be working, so I'll copy over the changes to sphenoid-crater.

**Comment by Em-Ant** [comment]
@scissorsneedfoodtoo  check the proxy at https://repeated-alpaca.glitch.me , it's simple but it should be ok.  Check if there is something missing.

**Comment by scissorsneedfoodtoo** [comment]
@Em-Ant, thank you for taking care of this so quickly. Everything seems to be working fine on my end.

I'll update the description for this project with the addresses for the new sample project and the proxy.
