### ISSUE TITLE
Won't run tests

### ISSUE THREAD

**Issue by Horcrux-Saniya** [freeCodeCamp/freeCodeCamp#18050]
I am trying to use freeCodecamp but the tests won't run. It happens on any and every challenge

Browser Name: UC Browser
Browser Version: 7.0.185.1002
Operating System: Windows 7 Ultimate

If I press ctrl+shift+J
The following window appears

![ghprob](https://user-images.githubusercontent.com/27635126/44594217-2382f580-a7e3-11e8-82ea-d738f57f799b.png)

**Comment by Horcrux-Saniya** [comment]
@randelldawson Chrome, Chromium these browsers are not working on my system.
I have tried to use internet explorer too but in vain

**Comment by huyenltnguyen** [comment]
@Horcrux-Saniya I'm not sure about UC Browser, but I have seen a number of reports of FCC behaving unexpectedly or not working at all on IE / Edge and Safari.

FCC works best on latest versions of Chrome and Firefox. So if Chrome doesn't work for you, give Firefox a try maybe?

**Comment by kundankumar26** [comment]
is your pc/laptop old?

**Comment by Horcrux-Saniya** [comment]
@huyenltnguyen Thanks for the help but even firefox is not working on my system.

**Comment by kundankumar26** [comment]
then use windows in a virtual box  and then install chrome in it. That will work for you.

**Comment by huyenltnguyen** [comment]
@Horcrux-Saniya Sorry it's still not working for you, but by 'not working', do you mean it showed an error during the installation? It would be great if you could provide some screenshots.

**Comment by Horcrux-Saniya** [comment]
@huyenltnguyen No there isn't any problem during installation, It gets installed successfully. But after that even the google.com page doesn't open in that browser.
Browsers not working are: Firefox, Chrome, Chromium, Opera.

**Comment by huyenltnguyen** [comment]
@Horcrux-Saniya Could you upload a screenshot of Firefox or Chrome user interface when accessing google? A screenshot of the browser console would also be helpful.

It's also worth a try to check if your firewall is blocking the browsers from accessing the internet.

**Comment by raisedadead** [comment]
Hi @Horcrux-Saniya 

Thanks a lot for reaching out. We are really sorry about the issues that you have been facing in getting the platform to work on your system.

From the screenshot, something is blocking some of the scripts that are needed to make the site work. This could be due to some extension, or simply the browser that you are using.

Unfortunately, we can't help much with regards to your configuration. We as a standard practice can only support OS and Browsers that are *popular*, current and stable.  These are usually listed in the compatibility tables on top developer resources like MDN for example.

You should try launching an incognito/private tab with all extensions disabled, and check if the site is working. This will isolate if it's some extension is causing the issue.

Other than that, I highly recommend using a stable popular OS and browser.

Thanks, and happy coding.
