### ISSUE TITLE
[NEXT] Gatsby unable to serve static page with pretty url

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#18093]
This is an issue against the `next` branch.

We may have uncovered a bug in gatsby v2 where we cannot serve a static page on a pretty url, meaning give a directory in that shape of 
```sh
/public
 | page-one.html
  /page-two
    | index.html
```

The URL for page one would be `/page-one.html`, and the URL for page two would be `/page-two/index.html`.

There is a previous issue in the gatsby repository referencing this issue and proposing a fix, but it has been closed as stale

Please see gatsbyjs/gatsby#2352 for more details

**Comment by Yurickh** [comment]
I've submitted a PR there, but I am not sure if it solves your troubles. What exactly are you calling a pretty url?

With my fix, for the directory shape you described, the available routes would be:
- /page-one.html
- /page-two
- /page-two/
- /page-two/index.html

It doesn't create `/page-one`, tho. 

I don't know if the gatsby team would want this behaviour, but it is actually just a one line change to add it as well , since there's an option for `express.static` to append extensions when trying to find files.

**Comment by Bouncey** [comment]
@Yurickh what you have would be great and makes sense. Thanks 👍

**Comment by Bouncey** [comment]
Congrats @Yurickh, go grab that gatsby swag!
