### ISSUE TITLE
Create New Middleware challenge still broken

### ISSUE THREAD

**Issue by mattszcz** [freeCodeCamp/freeCodeCamp#18103]
#16967 

This issue should not be Closed as the issue still exists. The only way to pass the challenge is to find the secret solution on the forum or issue tracker.

**Comment by Em-Ant** [comment]
The tests for this challenge expect that the text  `Home page` is in the `index.pug` template. We should update the challenge description specifying this requirement. 

@mattszcz do you want to open a PR for this ? It should be only  text changes so not so hard, and if you need help I can guide you. If you cannot do it, please let me know, and I will try to open the PR myself.

**Comment by im-danwu** [comment]
Not sure how these tests run, but adding that requirement seems a little brittle. You'd have to change the description for all languages too.

Maybe the test can just check the browser location?
Or add an ID to the pug homepage template and look for that?
Check the HTTP request for a 302 redirect to `/`?

**Comment by brimarq** [comment]
This is still a problem. I just amended the description meta tag in `head` of `index.pug` to be
`meta(name='description', content='Home page')`.  That seemed like a good place to put the 'Home page' text that the test expects. I suspect that the test will pass as long as that text is *somewhere* in the rendered HTML of the homepage. 

So... I suppose that a quick, "band-aid" fix could be to simply update the [boilerplate repo](https://github.com/freeCodeCamp/boilerplate-advancednode/). That said, there happens to be a similar test [in the first challenge of this series](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/set-up-a-template-engine.english.md#tests) that works just fine by matching `/pug-success-message/gi` in the `id` of that name on the homepage. The test in this challenge means to work in the same way; but, it fails because the text 'Home page' is nowhere to be found in the rendered HTML from `index.pug`. Maybe someone meant to include that text in the boilerplate and forgot to add it? Who knows? IMHO, it seems like targeting the `id` would make more sense (and be more reliable).

**Comment by SkipHendriks** [comment]
Used @brimarq's `meta(name='description', content='Home page')` suggestion to update the boilerplate repo. Didn't feel the `id` route would be better (or worse) so just made a fix. I'd be happy to make a different pull request though if people want to see the `id` targeted instead.

**Comment by thecodingaviator** [comment]
Since we've released the changes, this issue should have been fixed. I am, therefore, closing this issue. Please add more information if this still persists and we'll have it reopened.

**Comment by joshuous** [comment]
Hi, I encountered this issue today while attempting the Create New Middleware challenge, and only realized that the title needs to be explicitly set to "Home page". However, no such instruction is shown on the challenge notes.

Requesting to re-open this issue.

**Comment by joshuous** [comment]
### Problem
The **Create New Middleware** challenge fails even if users fulfill the given requirement:

- _A Get request to /profile should correctly redirect to / since we are not authenticated._

### Cause of problem
The [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/create-new-middleware.english.md) assumes that the index route '/' contains the **Home page** phrase:

`testString: getUserInput => $.get(getUserInput('url')+ '/profile') .then(data => { assert.match(data, /Home page/gi, 'An attempt to go to the profile at this point should redirect to the homepage since we are not logged in'); }, xhr => { throw new Error(xhr.statusText); })`

However, the earlier [**Use a Template Engine's Powers** challenge](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/use-a-template-engines-powers) requires the user to set the title to 'Hello':
`{title: 'Hello', message: 'Please login'}`

As such, 'Home page' would never be found if users had been following the instructions in the challenges up till **Create New Middleware**.

### Possible solutions
1. The test should match a different unique phrase that already exists in the '/' page, such as "**A cool thing made with HyperDev**" in the page's meta:
`<meta name="description" content="A cool thing made with HyperDev">`

2. Change the requirements in the [**Use a Template Engine's Powers** challenge](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/use-a-template-engines-powers) from setting a title of 'Hello' to 'Home page' instead:
`{title: 'Home page', message: 'Please login'}`

-------
I would be keen to know whether there are other better solutions to this issue.

**Comment by thecodingaviator** [comment]
I think either solution is good enough. But, I haven’t done that section so someone else might be able to give a better opinion. 

cc’ing: @freeCodeCamp/moderators

**Comment by nhcarrigan** [comment]
This challenge error is still occurring.
Changing the `{title: "Hello}` to `{title: "Home page"}` passed the test, so I think @joshuous's proposed solution #2 is the most effective.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, this is a longstanding issue. @Sky020's PR #39080 will close this once it's reviewed and deployed.
