### ISSUE TITLE
Feature Req. -  Convert the Portfolio page in a resume.pdf

### ISSUE THREAD

**Issue by pandaa880** [freeCodeCamp/freeCodeCamp#18158]
I was going through my freecodecamp profile page & I have an idea. In the profile, it shows your certifications and your outside projects as well, if you have added them. So, it will be really helpful if we can convert that information into a job ready resume.
I think we have enough information available and it will be also helpful for beginners who are struggling with making a good resume.
So, what do you think ?

**Comment by randelldawson** [comment]
> I think we have enough information available and it will be also helpful for beginners who are struggling with making a good resume.
So, what do you think ?

Can you elaborate more how you think **the information** currently available would be able to create a good resume?  Can you make a rough sketch of what information would go where on the resume?  Maybe use your own profile information as an example?

**Comment by pandaa880** [comment]
We have freecodecamp projects which i think one can fetch it's data, then for the education section may be we need to take input from user. There are some other details which user need to give but can be done or may be i can build something like that in future. 

I have these sections in my resume for now.

**Basic Details (with codepen & github links)**, **Education**, **Work Experience**, **Personal Projects**, **Open Source Contribution (If any)**, **Skills**, **Certifications** & **Interests**.

In the FCC Profile we have, **Bio**, **Internet Presense**, **Personal Projects & FCC Projects** & **Certifications**. 

So, I think we have almost all the details. So, that's why i had the thought of generating a resume. Now, i don't have idea about how you guys make resume, what things you include. I am from Ahmedabad, India and this is pretty much it that i include in my resume.

**Comment by randelldawson** [comment]
@pandaa880 It would seem in addition to Education, the feature would need to take user input for Work Experience, Open Source Contribution,  Skills, Certifications & Interests.  Plus, depending on what country you are from, you may or may not want to include Interests.  That would be a negative feature in the USA.  I personally would not list someones skills as a separate section.  The skills someone has should be evident from the projects completed.  Each project should have a description and a list of the skills used to complete it.  The problem is, these are not currently collected on the FCC project links section, so that would have to be updated too.

You have an interesting idea, but many people would have to sign off on this, because it involves modifying the core site (the additional input fields on the profile and projects sections) and not just adding an additional feature.
