### ISSUE TITLE
Custom CSS Variable-Test

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#18170]
#### Issue

Can the tests be made in some way that even the following way as given in the screenshot also works in addition to the way it is already working, i.e. defined separately for each class? Maybe just check if it has the property rather than checking for the code?

#### Link

https://learn.freecodecamp.org/responsive-web-design/basic-css/use-a-custom-css-variable

#### Browser and OS

* Browser Name: Google Chrome
* Browser Version: 69.0.3497.100 (Official Build) (32-bit)
* Operating System: Windows 7

#### Screenshot

![image](https://user-images.githubusercontent.com/34807532/45941697-ff425080-bffc-11e8-8b49-e7fb44ceb8bb.png)

**Comment by ArielLeslie** [comment]
It's not really a good pattern.

**Comment by thecodingaviator** [comment]
@raisedadead / @Bouncey can you have a look?

**Comment by raisedadead** [comment]
@thecodingaviator that's an anti-pattern for us trying to teach something.

Here is the analogy:

I understand that maybe convenient by the looks of your suggestion:

```css
.selectorClass1, .selectorClass2, .selectorClass3, .selectorClassN {
   property-name: value;
}
```

And maybe even helpful, when you are for example creating themes for a site, where its simple to update one line to change a `color` property for instance.

But,

When we are teaching these to users, who are especially new to coding its very easy for them to get side tracked from the core concepts. 

Here, they are learning to modify a `property` of different `class` objects?

Now, that you have put this shorthand in my thought, I feel this challenge could have been made better, by making it so that they update different values to the different `class` objects, like `background` in one could be `gray` and `orange` in another or something.

The crux of the challenge should be that they understand they are mutating different `class` objects.

**Comment by raisedadead** [comment]
Coming to your specific query, which I will rephrase to make it generic: 

"Can tests be made lenient to accept multiple valid code solutions?" 

Yes. But if there is a conflict that makes someone misinterpret the instructions in the challenge to write a solution that although valid is not conceptually correct, then No. We are quite opinionated on this as a learning platform especially for users who are new to coding.

**Comment by thecodingaviator** [comment]
> Yes. But if there is a conflict that makes someone misinterpret the instructions in the challenge to write a solution that although valid is not conceptually correct, then No.

@raisedadead I'm not sure hoe using multiple selectors with a `,` could make the code 'conceptually wrong'.

**Comment by raisedadead** [comment]
As I said in the analogy:

> Here, they are learning to modify a property of different class objects?

**Comment by thecodingaviator** [comment]
@raisedadead Ahh okay!
