### ISSUE TITLE
Contibutor Access

### ISSUE THREAD

**Issue by Lebura** [freeCodeCamp/freeCodeCamp#18187]
Add me as a contributor

**Comment by erictleung** [comment]
@Lebura welcome! And thanks for your interest in being a contributor. You can be a contributor in various ways listed here https://contribute.freecodecamp.org/. Otherwise, feel free to join the conversation on ongoing developments in our Gitter chat room https://gitter.im/FreeCodeCamp/Contributors. Happy coding!
