### ISSUE TITLE
Port over Mission statement and google analytics to `next`

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#18184]

**Comment by dlaub3** [comment]
I can work on this. A little confused though, since it appears to be there already. https://github.com/freeCodeCamp/freeCodeCamp/blob/next/client/src/analytics/index.js

Does the mission statement go here? https://github.com/freeCodeCamp/freeCodeCamp/tree/next/client/src/resources

Please provide instructions, thanks.
