### ISSUE TITLE
% do not add up to a 100 in the live results of the survey

### ISSUE THREAD

**Issue by Nunuvin** [freeCodeCamp/freeCodeCamp#18180]
#### Describe your problem and - if possible - how to reproduce it
Which of these careers are you interested in? has others tab adding up to 132%. The major options are also adding up to 100+ %

#### Add a Link to the page with the problem
https://freecodecamp.typeform.com/report/S3UeD9/fGdr8J7eJUPyxwFB

#### Tell us about your browser and operating system

* Browser Name:  mozilla firefox
* Browser Version: 62.0.2
* Operating System: Win10

**Comment by ArielLeslie** [comment]
I believe that people were allowed to select more than one option for some questions, since many people may be interested in more than one career or have more than one major. The different responses should be viewed independently.

**Comment by thecodingaviator** [comment]
The survey does not load for me, other people, please include screenshots

**Comment by icatat** [comment]
I checked out  the survey. The problem in the description of the issue adds up to 100%, so that one looks fine.

 
![image](https://user-images.githubusercontent.com/16485007/52527498-49b82700-2c97-11e9-8988-dd4d16f646c6.png)

However, there are a few others that do not add up to 100%, but they add up to 99% or 101%. I screen-shoted them below:


![image](https://user-images.githubusercontent.com/16485007/52527506-6d7b6d00-2c97-11e9-86ed-ec932af2efd6.png)
