### ISSUE TITLE
Forum is very unstable and returning lots "Error code: 500 error"

### ISSUE THREAD

**Issue by shimphillip** [freeCodeCamp/freeCodeCamp#18213]
#### Add a Link to the page with the problem
https://www.freecodecamp.org/forum/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Latest
* Operating System: Windows

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/36323994/46294446-6ad77100-c55b-11e8-8133-0d876f552721.png)

**Comment by vipatron** [comment]
It's not just the forum. The settings page was getting 500 errors, but is now failing to load and showing this loading symbol in an endless loop:
![image](https://user-images.githubusercontent.com/36994955/46297489-d07f2980-c56a-11e8-9111-6a7baad9e62d.png)

The curriculum was 500'ing as well previously, but is currently not loading my settings (I think the session was wiped, because it slowly loaded the sign-in button eventually).

**Comment by ArielLeslie** [comment]
FCC has communicated that their experiencing latency issues that are causing 500 errors. They also have had a banner up on the forum warning that it would be moving and going down for maintenance.

**Comment by vipatron** [comment]
Okay. I didn't know how to communicate to whomever should know that there was a problem, which is why I hopped on GitHub. As a baby webdev with a tiny speck of knowledge about how to set up a web server, I didn't know if downtime alerts were sent to the appropriate person's cell phone, or whether that was even a thing for FCC.

**Comment by ArielLeslie** [comment]
The FCC Twitter is usually the best way to be updated when there is a known or planned outage.

**Comment by RaspberryLime** [comment]
The forum is up and running again now.
