### ISSUE TITLE
Cash Register Result Final Test

### ISSUE THREAD

**Issue by bgq007** [freeCodeCamp/freeCodeCamp#18284]
#### Describe your problem and - if possible - how to reproduce it

Cases when register status is closed (giving all money in drawer to customer) and specifically the final test case:

> checkCashRegister(19.5, 20, [["PENNY", 0.5], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 0], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return {status: "CLOSED", change: [["PENNY", 0.5], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 0], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]}.

It is illogical to return the entire cid array. 1 - If we are returning the entire array, why are we not returning the entire array when the register remains open? We still looped through and identified that we can't give any of that denomination back. Thus we leave that amount off the return array. (See first case example where we start with 20). 2 - If we aren't actually giving any change back, then we don't say "Here you go ma'am... You get zero ONE HUNDREDS, zero TWENTY's, etc." 

We either return the entire currency array or we return the change owed. Not both depending on the case. 

The answer to the quoted case should be 

{ status: 'CLOSED', change: [['PENNY', .5 ]] }

Why? Because, once again, it's the only money we are returning, just like in the status OPEN cases. The status of the register has nothing to do with the denominations in the register, other than if there is no money remaining, the register can't be open. 

#### Add a Link to the page with the problem

(https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register/)

#### Tell us about your browser and operating system

* Browser Name: Not Sure This Matters - Chrome
* Browser Version: Why?
* Operating System: MacOs

**Comment by randelldawson** [comment]
What you may not understand, is the test suite needs to know what the cash-in-drawer looks like, in order to validate your solution in various ways.  This challenge is not intended to be a "real-life" solution you would create for a real transaction.  I understand why you would like to be the way you want, but the tests have been designed to check the entire cash-in-drawer object,, so you have no choice what to return.  Plus, you have to learn to write code to solve problems where you are given very specific constraints on how to output the data.  You may not always agree with the constraints, but you must still create a solution within those constraints.

**Comment by bgq007** [comment]
I really don't know why anyone attempts to address issues.... Why are we returning only denominations we are giving back if the register is open but returning everything if the register is closed regardless of whether or not the amount is 0? 

But forget it. Im tired of trying to address stuff. You guys never want to listen to what people are saying.

**Comment by randelldawson** [comment]
> But forget it. Im tired of trying to address stuff. You guys never want to listen to what people are saying.

I was listening and trying to explain why it is the way it is currently.  That does not mean it can not be changed.  When you post something as an issue, you create a conversation where everyone gets to put their two cents in.  I have no preference which way the challenge is presented and have not claimed your idea was bad at all.  You have made your suggestion, so just wait and see what others may have to say about your idea.  I am sure the tests could be changed, but someone will first have to modify the existing verbiage of the challenge to explain what you be returned differently than it is currently worded.  Also, someone will need to rewrite the tests to be able to test for such changes.  Most everything here is volunteer driven, so it may take a bit before someone agrees to take up such a request and implement it.    Just keep in mind, that since the challenge is already well written and works for all intended purposes, it probably will be lower in priority compared to a challenge which has a bug or poor wording.

Don't give up on Free Code Camp yet.  There is a process by which things are changed and the process involves others discussing and agreeing to which changes should be made to the existing curriculum.  It is a give and take process, but for the most part it seems to be a collaborative process.

**Comment by bgq007** [comment]
Well, when you guys respond, you always sound like you are taking the position that you have to defend FCC from comments. I laid out the difference in how we are returning the change. 

You claimed:

> the tests have been designed to check the entire cash-in-drawer object,, so you have no choice what to return.

but if you really read and took what I wrote seriously, you would see that is not true. If we were testing the entire drawer, we would always return all of the denominations with 0 for values if they are not being given back as part of the change. 

Rather than saying something like "I see what you are saying. Im not sure if that was considered or not. We will need to check to see if your result should also be added to the acceptable results or if we really want you to return the entire array." 

To which I might reply once again, "So why are we returning the entire array here but not elsewhere?" and I would then expect a response to that question which might have to come from someone that knows the logic behind the challenge. Which is fine. But you MODs rarely take an approach that tries to understand the question and lend the slightest amount of validity. Typically the responses jump right into why our thinking is wrong.

> What you may not understand

Just starts the whole thing off on the wrong foot. It shouts "your wrong" ... At least it does to me.

**Comment by randelldawson** [comment]
> Just starts the whole thing off on the wrong foot. It shouts "your wrong" ... At least it does to me.

You seem very defensive here.  You are the only one making generalizations about others.  I never said you were wrong.  

> But you MODs rarely take an approach that tries to understand the question and lend the slightest amount of validity. Typically the responses jump right into why our thinking is wrong.

I am not a MOD on github.  I am just a volunteer giving feedback which is part of the collaborative process in open source or real life project is all about. 

Below was my comment to you in my previous, so I do not understand why you think I have stated your wrong or that I am not understanding your question.
> I have no preference which way the challenge is presented and have not claimed your idea was bad at all.
