### ISSUE TITLE
[translation]: Update translations for contributing documentations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18312]
We need your help in translating the contributing documentations for Arabic, Chinese, Portuguese, Russian and Spanish.

There are the individual issues that you can help on, if you speak any of these:

- [x] Arabic: #18311
- [ ] Chinese: #18310
- [ ] Portuguese: #18309
- [ ] Russian: #18308
- [ ] Spanish: #18307

Please reach out to us in [Forum](https://forum.freecodecamp.com) or [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any queries.

Happy contributing.

There is still work pending on this. When you make a PR for this particular issue, do not tag it with `Closes #XXXXX` instead just reference it with `#XXXXX`

**Comment by fernandoamz** [comment]
i want to help you to translate in spanish, but i cannot see the issue

**Comment by chaomt** [comment]
Chinese: #18310
I want to help you translate the contributing documentations for Chinese.

**Comment by scissorsneedfoodtoo** [comment]
@Alhern, you did a great job translating the Guide README to French [here](https://github.com/freeCodeCamp/guide/pull/9004). Maybe you could help us translate the Contributing Doc to French if you have some time?

**Comment by Alhern** [comment]
Hey @scissorsneedfoodtoo ! I'd love to help with translating the Contributing Doc to French, I'm going to start working on it.

**Comment by lindakovacs** [comment]
I'd love to help with translating the FreeCodeCamp Curriculum in Italian and Romanian, Do you know when we can start working on it and when it will be open to work on?

**Comment by raisedadead** [comment]
Hi,

@Alhern and @lindakovacs thanks a lot for taking the time to contribute to freeCodeCamp.org

At the minute we are focused to have translations only in the 5 additional languages as you see on the contributing doc. This is primarily because of the operational logistics involved in maintaining the separate platforms. We want these languages to be ready and stable before going firth with other languages.

We will definitely consider additional languages in future, however we do not have any timeline on these.

We will make an announcement when that happens.

Thanks.

**Comment by lindakovacs** [comment]
Hi Mrugesh,Thank you for getting back to me.I didn't know all of this and I just sent 2 pull requests for Creating the Romanian and Italian translation for the Contribution Guidelines.Mostly I did it after I read Quincy's article "I just got my free Hacktoberfest shirt. Here’s a quick way you can get yours.".At this point, I don't know if I should continue up to 5 pull requests as it says in the article and you just put it on the side until you are ready to go with the Romanian and Italian versions or I should try other modifications for the pull requests.I'm new myself to all of this stuff and I'm trying to learn as fast as possible.Please let me know how you like me to proceed or what works best in your interest.Thank you,Linda Kovacs

I just got my free Hacktoberfest shirt. Here’s a quick way you can get yours.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
I just got my free Hacktoberfest shirt. Here’s a quick way you can get y...

Quincy Larson

Note: this article is now up-to-date for getting a 2018 Hacktoberfest shirt.
 |

 |

 |



-- 
Linda KovacsRemote Freelancer Web Developer, Web Designer, and Graphic Designer

lindaprovenza@yahoo.com
http://www.lindakovacs.x10host.com/


    On Friday, October 12, 2018, 6:27:35 PM EDT, mrugesh mohapatra <notifications@github.com> wrote:  
 
 
Hi,

@Alhern and @lindakovacs thanks a lot for taking the time to contribute to freeCodeCamp.org

At the minute we are focused to have translations only in the 5 additional languages as you see on the contributing doc. This is primarily because of the operational logistics involved in maintaining the separate platforms. We want these languages to be ready and stable before going firth with other languages.

We will definitely consider additional languages in future, however we do not have any timeline on these.

We will make an announcement when that happens.

Thanks.

**Comment by lindakovacs** [comment]
@raisedadead I just closed my PR #18661 and #18632.
Thank you for your help.

**Comment by Ahmed-Elbessfy** [comment]
I can help with Arabic #18311 translation but I have a problem with Document Direction as Arabic is RTL Language. Is there a solution for this issue ?

**Comment by 3CatMax** [comment]
I don't have any translation skills, but I fixed the links in the READMEs to go to the correct language documents that everyone is doing such an awesome job translating. #28207

**Comment by raisedadead** [comment]
Thanks for working on the translations for the "Contributing to freeCodeCamp". Here on we are making contributing to translations for contribution docs *ad hoc*. 

You are free to make pull-requests for improving these translations. We are closing the issue as these do not need tracking per se.

You can raise a fresh issue if you find something incorrect in the existing docs.
