### ISSUE TITLE
Sass @while challenge

### ISSUE THREAD

**Issue by MarkMcDaniels** [freeCodeCamp/freeCodeCamp#18321]
**Describe your problem and how to reproduce it:**
When you type in @while, and begin to create the conditions, it starts an infinite loop.
I was able to pass it by creating the code in an html comment, and then deleting the comment.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

**Tell us about your browser and operating system:**
* Browser Name: 
Chrome
* Browser Version: 
Version 69.0.3497.100
* Operating System: 
Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by cmccrea23** [comment]
I am also experiencing this issue. I bypassed it by typing my code into my editor and then copy/pasting to the browser.


Tell us about your browser and operating system:

Browser Name:
Chrome

Browser Version:
69.0.3497.100 (Official Build) (64-bit)

Operating System:
macOS High Sierra, version 10.13.6

**Comment by ArielLeslie** [comment]
The problem arises if the user types the closing `}` before correctly creating the contents of the loop. Since this is a common syntax-error-avoidance habit formed by coders, we see campers run into this problem on a regular basis. It would be helpful if autorun could be disabled on these challenges.

**Comment by yuenwailok** [comment]
Same issue here
