### ISSUE TITLE
R is not defined

### ISSUE THREAD

**Issue by alexzkazu** [FreeCodeCamp/freecodecamp#185]
I try to submit my answer on http://www.freecodecamp.com/bonfires/check-for-palindromes and it gives me this error in the console to the left when I press Run Code:

```
R is not defined

Program Execution Failure No user tests were run.
```

This happens on Chrome 41.0.2272.89, Safari 8.0 (10600.1.25.1), and the run button doesn't work on Firefox 35.0.1.

**Comment by BerkeleyTrue** [comment]
Can't replicate on my end. @terokilobyte, can you confirm?

**Comment by terakilobyte** [comment]
Getting R is not defined at the console or the test output?  What browser?
What extensions? I also can't replicate.

**Comment by alexzkazu** [comment]
Sorry, I just updated my original comment with the browser versions. Getting R comes out in the test output.
![screen shot 2015-03-10 at 7 12 41 pm](https://cloud.githubusercontent.com/assets/4003324/6589204/85eb074e-c759-11e4-9e32-c3b24348fd99.png)

**Comment by terakilobyte** [comment]
Any extensions?

**Comment by alexzkazu** [comment]
I've disabled all extensions on all browsers and it still gives me this error. Firefox run button works now though.

**Comment by alexzkazu** [comment]
Oh it's working fine now for some reason! Weird.

**Comment by BerkeleyTrue** [comment]
@terakilobyte Do we support FF for Bonfires? I thought webworkers are fubar on FF.

**Comment by terakilobyte** [comment]
FF works on bonfires as long as you don't submit too many times. It appears
FF doesn't properly release the memory when the worker is destroyed so will
eventually hang up.  This is a feature discussion at this point, but the
way to support all browsers is to move the evaluations to the server. This
may be the way forward anyway as part of making bonfire itself an
observable.

I'm going to mark this issue closed. It really sounds like your browser or
something in the middle was failing to connect to the cdn to pull ramda
into the plugin. Because of the sandbox architecture it can't be included
server side without a big rewrite of the original author's source code.
