### ISSUE TITLE
Bonfire Friendly Date Ranges Test Inconsistencies

### ISSUE THREAD

**Issue by slooptb** [FreeCodeCamp/FreeCodeCamp#1886]
Challenge http://freecodecamp.com/challenges/bonfire-friendly-date-ranges has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I know this has been debated before, and I understand that if the dates are within 11 months it can be inferred that it is the following year, but test 4 (below) should require a year given that this is a requirement: "Secondly, if the starting year is the current year, and the ending year can be inferred by the reader, the year should be omitted."

As the 4th test is 2016/2016, it can't be inferred the year is 2016 unless there is assumed all dates are in the future, it could have been in 2015.

Could either the test condition, or the task description be changed to reflect this?

**Comment by mhurwicz** [comment]
I agree.  I would suggest 
```assert.deepEqual(friendly(['2016-03-01', '2016-05-05']), ['March 1st, 2016','May 5th'], 'dates in the same year in the future can be inferred it is the same year');```

I would not say "one month apart can be inferred it is the same year" since these dates are more than two months apart.

**Comment by soulchainer** [comment]
+1 for this. It makes all the sense, @slooptb & @mhurwicz 
I just get here because other thing I don't see clearly and, after reading you, more lack of precission issues arise.

I mean, in the explanation of this challenge, we got:
> Secondly, **if the starting year is the current year**, and the ending year can be inferred by the reader, the year should be omitted.

Well... `2016` isn't the current year. Why is it omitted? (I realized this after reading you).

But then, forget about that for a second. If we suppose that with **starting year** they're only refering to the year in the first position of the array, we get that:

`assert.deepEqual(friendly(['2016-03-01', '2016-05-05']), ['March 1st','May 5th'], 'dates in the same year in the future can be inferred it is the same year');` ← the year could be infered, so we omit the year. Fine.

But:

`assert.deepEqual(friendly(['2022-09-05', '2023-09-04']), ['September 5th, 2022','September 4th, 2023']);
expected [ '2022-09-05', '2023-09-04' ] to deeply equal [ Array(2) ]

There, the year can also be infered if the omit the year. Or any of you think that `September 4th` comes after `September 5th`?

This challengue is **so simple**, but it turns **hard** because isn't clear at all. And I can't do it good if I need to guess all the time. Challenge explanations and test should be a little more clear/straighforward an cover all the cases well. I can deliver the exercise even when I can make it pass the tests, if I don't fully understand the real intended way of working of the script.

**Comment by bheavner** [comment]
Add me to the list of people confused by this one. But beside the current confusion, will these tests have to be touched up when we enter 2016 as well?

**Comment by DuckyDisciple** [comment]
This bonfire definitely needs to be updated now. It was already confusing when it was expecting the year to be blank for some 2015 and some 2016, but not all. Now that it is 2016, there should be a new set of test conditions.

**Comment by bheavner** [comment]
I really don't understand the " friendly(["2017-03-01", "2017-05-05"]) should return ["March 1st","May 5th"] " test case. Why isn't it expecting ["March 1st, 2017", "May 5th"] ? If the argument is that 2017 is redundant information, so shouldn't be displayed at all, wouldn't the same be true of the Month in the last test case (friendly(["2022-09-05", "2023-09-04"]) should return ["September 5th, 2022","September 4th, 2023"].)?

What is the easiest way to clean this up? 

I'd suggest the problem statement be changed from 
"Secondly, if the starting year is the current year, and the ending year can be inferred by the reader, the year should be omitted."
to 
"Secondly, if the ending year can be inferred by the reader, the year should be omitted."

And then following tests satisfy the problem statement:
friendly(["2016-07-01", "2016-07-04"]) should return ["July 1st","4th"].
friendly(["2016-12-01", "2017-02-03"]) should return ["December 1st","February 3rd"].
friendly(["2016-12-01", "2018-02-03"]) should return ["December 1st, 2016","February 3rd, 2018"].
friendly(["2017-03-01", "2017-05-05"]) should return ["March 1st, 2017","May 5th"]
friendly(["2018-01-01", "2018-01-01"]) should return ["January 1st, 2018"].
friendly(["2022-09-05", "2023-09-04"]) should return ["September 5th, 2022","September 4th"].

If the problem statement isn't changed, that last test shouldn't be changed, and should remain 
friendly(["2022-09-05", "2023-09-04"]) should return ["September 5th, 2022","September 4th, 2023"]. (since the starting date isn't the current year)

**Comment by bheavner** [comment]
I'm happy to submit a pull request with my proposed fix (change problem statement, and change the 4th and 6th tests). I'll start working on that now.

**Comment by bugron** [comment]
@bheavner OK, this issue is yours.
