### ISSUE TITLE
Translation to any language

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#18966]
I was thinking of how could we get a language introduced for FCC being translated to that?
I think there would be a big Hindi-speaking audience from India and I would love to work with that.

@QuincyLarson @raisedadead

**Comment by thecodingaviator** [comment]
Wkipedia demographics suggest that around 422,000,000 people speak Hindi as a first language, even if we can improve for 0.001% of those, we would have 4220 new people learning through FCC

**Comment by kontramot** [comment]
I can translate to Russian.

**Comment by QuincyLarson** [comment]
@thecodingaviator If we were to create a Hindi-language version, would you be interested in helping maintain it?

**Comment by QuincyLarson** [comment]
@kontramot Awesome - please open some pull requests helping us improve our existing Russian translations here: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/russian

**Comment by ezioda004** [comment]
@QuincyLarson I'd be happy to help out as well. 😃

**Comment by thecodingaviator** [comment]
> @thecodingaviator If we were to create a Hindi-language version, would you be interested in helping maintain it?

I would be!

**Comment by esnufkin** [comment]
I'll do Chinese!

**Comment by KeiVanIndo** [comment]
@QuincyLarson  Is it possible to have an Indonesian language version also?
I'd like to help with the translation...

**Comment by raisedadead** [comment]
Hi Everyone,

Thanks for the issue. Right now we are planning for the 5 languages that we have mentioned in the README.

You are more than welcome to contribute to more languages, however please note that we do not have an ETA on when those will go live into production.

The best way would be to generate user feedback on the community forum and other social channels.

We are closing this thread, because its mostly opinionated in nature and does not have any actionable user stories for development. Once the interest has picked up so as much that we can justify the cost of maintaining enough servers, etc. we will be happy to move to further steps.

Please continue the discussion (closure, is for workflow only) as it's still relevant.

Thanks.

Happy contributing.

**Comment by b3u** [comment]
Can i do hebrew?

**Comment by thecodingaviator** [comment]
@b3u , @ezioda004 I had a talk with @QuincyLarson and the decision was that for now we will only focus on the 5 languages we have and only after they are completed will we start any other language.
