### ISSUE TITLE
ES6: Use getters and setters to Control Access to an Object private variable

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#19057]
**Describe your problem and how to reproduce it:**
In this task description about getters and setters that they are used to avoid direct private variable manipulation. "Getter functions are meant to simply return (get) the value of an object's private variable to the user without the user directly accessing the private variable."
But in fact defining variable like this doesn't make it private. You still can directly access.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

**Comment by Bob-Thomas** [comment]
This is because javascript doesn't support real private variables yet.
There are some proposals for defining private variables inside classes https://www.sitepoint.com/javascript-private-class-fields/.

But for now there no standard ways of creating private variables so most choose to use the underscore syntax as other languages that don't support private variables like python do.

**Comment by arnas** [comment]
Yes, and because of that there shouldn't be the mention about private variable.

**Comment by Manish-Giri** [comment]
People coming from other languages like Java & C++ might wonder about private variables in JavaScript, so, IMO, rather than not mentioning about private variables at all, it might be better to add that JS doesn't support the notation of private variables yet, which is why one should make use of getters and setters.

**Comment by ezioda004** [comment]
Well, yes and no. You can certainly create "private" variables via closures in function constructors.
I agree that adding a note on the `_` notation would be a good idea.

**Comment by alanpaulprice** [comment]
I've made a PR to add an explanation of the _ notation [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/24362):

**Comment by RandellDawson** [comment]
@ezioda004 Can we close this issue due to https://github.com/freeCodeCamp/freeCodeCamp/pull/24362 being merged?

**Comment by ezioda004** [comment]
Closed via https://github.com/freeCodeCamp/freeCodeCamp/pull/24362
