### ISSUE TITLE
Your left-well element should have a red background - it does but i can't pass 

### ISSUE THREAD

**Issue by MelissaManning** [FreeCodeCamp/FreeCodeCamp#1934]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/13456308/9315819/77aa556c-44ff-11e5-8e79-6ed7feb47721.png)

**Comment by apositivejam** [comment]
This is not a bug.

In your code you are targeting the **PARENT** of the div with the ID left-well. Thus, you are targeting the div with the class col-xs-6. 

Since you're targeting the **left-well** ID using the parent() selector, you'd want to target one of the children within that ID.

For example, the code: 

```javascript
$("#target1").parent().css("background-color", "red")
```

should (and does) work.

**Comment by mohmmadasim** [comment]
thanks for the help

**Comment by rupeshshitole** [comment]
Correct Answer is,

$("#left-well").css("background-color","red");
$('#target1').parent().css('background-color','red');
