### ISSUE TITLE
User profile URL is case sensitive

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#19346]
When trying to view a users profile, the URL is case sensitive.

https://www.freecodecamp.org/mot01 - works
https://www.freecodecamp.org/moT01 - doesn't work

It would be nice if it could ignore the case sensitivity somehow, if possible.

**Comment by thecodingaviator** [comment]
In my opinion, that's a bad idea. would allow for less usernames that are not complex

**Comment by mwaz** [comment]
Best practices call for usernames to be unique, however, given that people already have duplicate usernames, it would be quite a task to migrate to a new system altogether

**Comment by ezioda004** [comment]
Not sure how usernames are stored, but seems like they are all stored in lowercase.
If possible, perhaps we can lowercase the letters before querying the database?

**Comment by Nirajn2311** [comment]
@ezioda004 but that could be a problem for some people who have same usernames but the letters cases are different 
For example

> NirajN would be stored as nirajn
But
> Nirajn will also be stored as nirajn

**Comment by ezioda004** [comment]
@Nirajn2311 That shouldnt be a problem, fcc doesnt allow 2 same usernames with different case sensitivity.
If `NirajN` exists then one cannot take `Nirajn` or `nirajn`, you can test this out in the settings menu (change username validator).
So, it does look like the names are indeed stored as lowercases, so querying the DB with lowercase shouldn't be a problem.

**Comment by dkcr7** [comment]
There's no point doing so. As if you wanted to use the username in capital letters, then lowercase won't be supported and vice-versa.

**Comment by moT01** [comment]
@dkcr7 I don't understand what you are getting at, no point in doing what?

**Comment by RaspberryLime** [comment]
I'm sure I signed up as RaspberryLime, but fCC displays it in lowercase instead. I think that when checking to see if a username is available when signing up or changing a username that it should be a case insensitive search (so there isn't RaspberryLime and raspberrylime), but otherwise the user should be able to choose the capitalisation they want.

**Comment by addv12345** [comment]
I completely agree with @RaspberryLime . I would like to contribute to this issue! I am planning on taking the input URL (doesn't matter whether the username is correctly capitalized or not) and if the username case doesn't match, then redirect it to the correct URL only if there is a matching username. However, if the username doesn't exist, then the current behaviour will stay in effect. 

What do you think @QuincyLarson ?

**Comment by QuincyLarson** [comment]
@moT01 Thanks for pointing this out. Yes - I agree - we should fix this.

@addv12345 Yes - we would welcome your help with this!

We want for the database query to be case-insensitive. We also want to store the case-sensitive version of usernames for display both in the URL and on the profile itself. This is how GitHub, Twitter, and many other services operate.

Twitter example: 
<img width="461" alt="bri_bri_ _on_twitter___someone_sent_me_a_thank_you_note_for_helping_to_inspire_them__she_comes_to_the_javascript_study_group_every_thursday__this_just_made_my_day_ _https___t_co_aiuapfmtgf_" src="https://user-images.githubusercontent.com/985197/51850165-29fe3600-235c-11e9-89f6-4cf98fae422a.png">

**Comment by QuincyLarson** [comment]
@addv12345 I can't assign it to you through GitHub (I think you have to have write permissions for me to do that) but I've set it to "in progress". Please keep us posted and if you need any help, we're here for you in https://gitter.im/freecodecamp/contributors

**Comment by raisedadead** [comment]
Hi @QuincyLarson 

Some of the requirements here are not trivial, because of our legacy user model schema. That is somethings about the model if not planned from the beginning always make your system resistive to change.

Anyways I will leave some pointers for anyone working on this:

- I think while we want this do this, its best approach is to take the way others are handling it. The URL for example should always be lowercase and resolve like that automatically for example:

	https://github.com/freeCodeCamp will always resolve to https://github.com/freecodecamp 

	**That's simply a safer way to handle a complex lookup.** 

- The URL `/moT01` to `/mot01` to  will have to happen in the client side interceptor. You should look into [`/client`](/client). @Bouncey maybe able to expand this pointer better.

- Currently we have all the usernames lowercase-ed. This happens as a part of validation step. https://github.com/freeCodeCamp/freeCodeCamp/blob/d11bb33f56cf7f47c5d0297e14b7014f404e1ca0/api-server/common/models/user.js#L267

- Also see the schema in user.json
   ```js
	{
	...
	"properties": {
	    ...
	    "username": {
	      "type": "string",
	      "index": {
	        "mongodb": {
	          "unique": true,
	          "background": true
	        }
	      },
	      "require": true
	    },
    ...
	```
    Check [ LoopBack 3 docs](https://loopback.io/doc/en/lb3/) if you need any additional help.

While this is fixable, major changes like this may not be the best for the larger scope of the project. So, this needs extensive testing unless we want to end up with hundreds of support emails for the way a username appears.

**Comment by Bouncey** [comment]
This saga handles the profile request:
https://github.com/freeCodeCamp/freeCodeCamp/blob/db02d1c479812d6cc18e9c31094d5dde434a91be/client/src/redux/fetch-user-saga.js#L30-L42

The `maybeUser` argument should be enforced to be lower case.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for the details. Since this is a relatively low priority, I'll add it to the roadmap and we can tackle it later.

**Comment by icatat** [comment]
Hi! @QuincyLarson My friends @addv12345 are still potentially interested in this issue. However, we are new to this project. Would it still be worth investigating this particular problem?

**Comment by raisedadead** [comment]
> Would it still be worth investigating this particular problem?

Yes, sure. We are interested in fixing this. However, as I said before this needs extensive testing and the solution has to be elegant enough to play well with our current schema. We have put up all the pointers in the previous comments. 

Please feel free to dig in, and let us know if you need additional information on working thru this.

Thanks.

**Comment by icatat** [comment]
Sounds good! We were looking into it earlier. The issue we ran into was that we could not find a way to test the code or access a user's public profile (or a mock user's profile - not sure how that part is structured yet). Can you please point us in the right direction?

**Comment by raisedadead** [comment]
Sure. 

Once you setup freeCodeCamp locally, you should have already seeded (a.k.a populated) the database  using the guide.

The current way of reaching the user profile page is bit tedious (because we have Gatsby's dev server taking over in local development).

Here is what you should do:

<img src='https://user-images.githubusercontent.com/1884376/52650951-48922e80-2f11-11e9-9eee-360a25ad28ad.gif'>

Then on, I would recommend using a GUI DB tools like [Robo 3T](https://robomongo.org/download), and tweak your user(s) / add more user objects etc. as you please.

Feel free to hit us up on [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) or DM me as well.

Thanks for working on this and goodluck!

**Comment by icatat** [comment]
@raisedadead I tried to run some commands on mongodb locally, and I actually noticed that the username is stored in the original format. Am I looking in the right place?
![image](https://user-images.githubusercontent.com/16485007/53593322-66dd6880-3b66-11e9-8905-3c016cbb77a5.png)

**Comment by RandellDawson** [comment]
@icatat It is stored that way in the db, so that it displays as the user originally entered it.

**Comment by Bouncey** [comment]
@icatat That is more an implementation of the `Development User`. this record should insert the user with the correct casing of the username also.

**Comment by raisedadead** [comment]
@icatat @addv12345 I have created a fresh request for the requirement, since it differs from the original issue.

**Comment by icatat** [comment]
@raisedadead  Thank you very much! We will look into the new issue then!
