### ISSUE TITLE
[Bug] Basic Data Structures: Check if an Object has a Property

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#19382]
**Describe your problem and how to reproduce it:**
Found from this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/19367
The tests are only checking if all the properties exists and another check is done after deleting all the properties so code like:
```js
function isEveryoneHere(obj) {
  return users.hasOwnProperty('Alan', 'Jeff', 'Sarah', 'Ryan'); //shouldnt pass since .hasOwnProperty() doesnt take more than 1 parameter but would only check the first one.
}
```
and 
```js
function isEveryoneHere(obj) {
  return obj.hasOwnProperty("Alan");
}
```
Passes the challenge whereas they shouldn't.

This can be resolved by adding checks after deleting each property or randomly deleting one and then checking.
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property/

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 69
* Operating System: 10

**Comment by ezioda004** [comment]
Hey @QuincyLarson @raisedadead, is it fine to accept PR to update the tests to fix this bug?

**Comment by anarkafkas** [comment]
This issue still persists. hasOwnProperty method doesn't accept multiple parameters, contrary to what has been shown in the lesson. The [solution](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property/) also seems to be incorrect.

**Comment by lms15** [comment]
Hello, thanks for your help 
Mamie

**Comment by razzlestorm** [comment]
Just confirming that this issue is still persisting. `if (users.hasOwnProperty('Alan')){
  return true;
} else {
  return false;
  }`

will pass the tests.

**Comment by RandellDawson** [comment]
@razzlestorm It has been fix but not deployed to production.

**Comment by wudifeixue** [comment]
The guide on this question is also very misleading, basically giving the wrong answer, and since the test is not strict enough people can pass with the wrong answer. [Wrong Guide Link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property/index.md)
This is probably due to the fact that you could do this with `Object.hasOwnProperty`
![image](https://user-images.githubusercontent.com/7316929/58364684-437c3e00-7e75-11e9-8b3d-42dc7db8c696.png)

And still have true returned. 

Students on the forum has got the answer for this question and the proper way of solving the problem [here](https://www.freecodecamp.org/forum/t/check-if-an-object-has-a-property/196213).

**Comment by RandellDawson** [comment]
@wudifeixue I completely agree with you, so I just created PR https://github.com/freeCodeCamp/freeCodeCamp/pull/36125 to added valid solutions to the guide.  Keep in mind, even when the PR is merged, you will not see the Guide updated until the current `master` branch has been deployed to production.

**Comment by wudifeixue** [comment]
@RandellDawson Awesome, thanks for the super fast pull request too!
