### ISSUE TITLE
Typos in tests

### ISSUE THREAD

**Issue by NigelDawson** [FreeCodeCamp/FreeCodeCamp#2082]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The script segments in the tests for this waypoint have typos.  "$(document" is missing the closing ")"

![image](https://cloud.githubusercontent.com/assets/13345461/9333333/ae4d9820-45c9-11e5-8255-43320347b39e.png)

**Comment by bugron** [comment]
@NigelDawson thanks for posting this issue!
@BerkeleyTrue seems this issue is solved in [source code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L19) and can be closed, thanks.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
