### ISSUE TITLE
Waypoint: Use CSS Selectors to Style Elements

### ISSUE THREAD

**Issue by miurajose** [FreeCodeCamp/FreeCodeCamp#2084]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It gives you the green light to go to the next challenge after writing just this:
<style>h2{color: blue</style>

Notice the missing ; and the missing }.

**Comment by sJhonny-e** [comment]
actually, surprisingly, this seems to be valid;
If you create an HTML file like so (notice the missing ; and }):

```<html>
<body>
<style>
  h2 {
    color: blue
  
</style>
<h2 >CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
</body>
</html>
```

and open it in your browser- the CatPhotoApp text does appear in blue, and you don't see any errors in your console...

so, although this isn't best practice by any means- it seems to be valid.
(I'm also not sure how to technically detect this issue, since the browser seems to be ok with it,,,)

**Comment by Croasdell** [comment]
this is what worked for me

<style>
  h2 {
    color: blue;
  }
</style>
<h2 >CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by Mattosky** [comment]
thanks
