### ISSUE TITLE
Camper News doesn't show comments unless authenticated

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#209]

**Comment by jameskopacz** [comment]
While trying to fix this I think I've ran into a bigger problem. Which is how the stories/comments are submitted.

First, the comments aren't showing up because of a js error. A variable named 'user' is being set containing a json string of the req.user object (which is the reason for #213). When a user isn't logged in they have an empty req.user object and that causes the output to create invalid js code. https://github.com/FreeCodeCamp/freecodecamp/blob/master/controllers/story.js#L151

But once the errors are fixed, depending on how you fix it, you can now post comments without being logged in. The comment submission relies on the 'user' variable to get the username, profile picture, and user id of the author which are all submitted when a comment is. None of it is checked server side. You can can submit comments on the live site right now without being logged in.

I haven't tried to fix anything yet since it looks like it might be stories, comments and comment replies that are doing this and with the site being moved to react I don't know if it's worth changing everything when it'll just be changed again soon.

**Comment by terakilobyte** [comment]
It may be easier than all that. Adding something like
`user = req.user || null`, in the controller
and then explicitly checking against a defined user when someone tries to reply.

**Comment by jameskopacz** [comment]
Awesome, looks like that fixes it!
