### ISSUE TITLE
null is not an object (evaluating 'editor.match(/

### ISSUE THREAD

**Issue by RobinsonKameron** [FreeCodeCamp/FreeCodeCamp#2100]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Getting an issue if you only have style="" typed into the editor once you add the style the error disappears.

**Comment by benschenker** [comment]
Hey @RobinsonKameron I was able to replicate but I'm not really sure what we can do about this....

I'll keep this open for now.

**Comment by kishoresmeda** [comment]
When i used style="color : white" (space on either side of colon), i got the editor.match(...) error.
I removed the spaces to look like this style:"color:white" (without spaces) and the error disappeared. Hope this helps.

**Comment by benschenker** [comment]
I believe that the issue is that the space before the colon is making the test fail.

**Comment by bugron** [comment]
@benschenker you are [right](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json#L3343). There are many challenges where camper fails to pass the test because of a space. or a new line character. To avoid issues like this we need to go through all challenges and extend tests so they'll actually allow any whitespaces which is a hard work. This work actually had to be done by the creator of this challenges.

**Comment by TiffanyECook** [comment]
There's a different issue with this waypoint - it's not recognizing the pink-text class within my element. Tried a hard refresh, still nothing. 

![screen shot 2015-09-10 at 3 57 17 pm](https://cloud.githubusercontent.com/assets/13739292/9799397/dd3d8ace-57d4-11e5-9826-be4effc1ee9c.png)

**Comment by benschenker** [comment]
@TiffanyECook this seems to be a separate issue.  Feel free to [open a new issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) about this.
