### ISSUE TITLE
User Answer is wrong but System is Right

### ISSUE THREAD

**Issue by bdwanggang** [FreeCodeCamp/FreeCodeCamp#2292]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

on of the label buttons name is indoor-outdoor,then system analysis syntax is right.However,another name is wrong.

**Comment by bugron** [comment]
Dear camper, your issue is related to these ones:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1390
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1307
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1017

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
