### ISSUE TITLE
Bonfire: Mutations - incorrect solution passed tests

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#2305]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations

I haven't actually managed to write a correct solution yet, but my last attempt passed even though I know it doesn't work. My solution:

    function mutation(arr) {
  
    var match = true;
    var string = arr[0].toLowerCase();
    var toCheck = arr[1].toLowerCase();
  
    for(i=0; i<toCheck.length; i++) {
        var matched = string.indexOf(toCheck[i]);
        if (matched == -1) {
          match = false;
        } else {
          match = true;
        }
    }
    arr = match;
    return(arr);
   }

A test that could be added that will cause this to fail:

    expect(mutation(['floor', 'xfor'])).to.be.false;

**Comment by fnky** [comment]
The above code would also do the same in any case where the first character is anything else:

```js
['Ammy', 'Xmmy'] // true
['octodad', 'i am oct.odad'] // true
['catopus', 'catopus···']
```

The reason is in your condition you check for each letter, wether there's a match. However, you don't `return` out of the loop, and it will keep setting the `match` to `true` and `false` until the last character. Then it will return the last set value of `match`.

This wouldn't be that easy to circumvent.

**Comment by erratadei** [comment]
I submitted a Pull request to see if they accept it, I got impacient because I had reported the same issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1754

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
