### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by marcoshuet** [FreeCodeCamp/FreeCodeCamp#2337]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Your left-well element should have a red background." is not completed until you make it with #target1 as well.

**Comment by denmch** [comment]
I don't believe this is a bug, but rather that the instructions could be clarified. The example code is a bit misleading, because it shows `.parent()` applied directly to the left well, which is probably confusing a lot of campers.

The goal here, however, is to use `.parent()` to change the style of the left well, and to do that you need to apply `.parent()` to one the left well's children. This is clear from the following part of the instructions:

> Give the parent of the #target1 element background-color of red.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1934
@denmch exactly! I think instructions need to be clarified maybe in this way.
Here's an example of how you would use the ```parent()``` function **to set the ```#left-well```  element's parent element background color** ```$("#left-well").parent().css("background-color", "blue")```.
