### ISSUE TITLE
Incorrect description in Waypoint: Sift through Text with Regular Expressions

### ISSUE THREAD

**Issue by rufanov** [FreeCodeCamp/FreeCodeCamp#2345]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. 

We have this regular expression:

    /the+/gi;

And that's how it's explained:

> Let's break this down a bit:
>
>`the` is the pattern we want to match.
>`+` means we want to find one or more occurrences of this pattern.

But it's incorrect. `+` in this expression is really says that we want to match one or more `e` after `th`. 

Also, i think there is mistype in this challenge title - there should be `Shift` word instead of `Sift`.

**Comment by rsprice** [comment]
@rufanov I think "Sift" is fine. Google tells us that the verb "Sift" means "examine (something) thoroughly so as to isolate that which is most important or useful.". At any rate, I submitted a PR to fix the regex, so hopefully that will get fixed.

Cheers!

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2331
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2184
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2163
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
