### ISSUE TITLE
looks for wrong regular expression in solution

### ISSUE THREAD

**Issue by ibiwan** [FreeCodeCamp/FreeCodeCamp#2357]
Challenge http://freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the re to find "and" should be /and/gi -- the exercise is only marked complete if the re /and+/gi is used, which matches "and", "andd", "anddd", "andddd", etc... which I do not believe to be the intent

**Comment by rsprice** [comment]
@ibiwan I submitted a pull request for this earlier. Hopefully my fix works and the changes will get merged soon!

Cheers! :beers:

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2345
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2331
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2184
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2163
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
