### ISSUE TITLE
Major of specs needs to be rewritten

### ISSUE THREAD

**Issue by fnky** [FreeCodeCamp/FreeCodeCamp#2358]
I, as well as many others, have noticed a substantial amount of specs (*tests*) that are misleading and/or confusing.

The reason why I made this huge issue thread, is because this is a large amount of work, and specs needs to be written after certain rules, that are easy to follow and understand for any level of skill.

This is more of a discussion towards a solution to re-write current specs, and write future specs to cut down on issues, which aren't bugs but simply bad understading of a specific task, specified by a description and/or spec.

Currently some of the dilemmas with the current specs are:

#### The major of specs are misleading and lack of detail
Specs that does not give enough information makes a waypoint difficult to solve—not even based on experience, but overall solution.

> Add two `div` elements inside your `div class="well">` element both with the class `col-xs-6`.

Taken from the [Create Bootstrap Wells](http://freecodecamp.com/challenges/waypoint-create-bootstrap-wells) waypoint.

The spec contradicts with it's description.

> Bootstrap has a class called `well`  that can create a visual sense of depth for your columns. Nest one `div` element with the class `well`  within each of your `col-xs-6` `div` elements.

#### Some specs promotes bad practice, by bad implementation

This is already described in issue #2306 and should be entirely rethought. Testing syntax rather than behavior leads to unpredictable results (as show in the issue). This also promotes bad practices as not allowing code to be DRY, forcing the user to write a code a specific, predefined way.

This discussion is another one entirely, which should not be taken up in this dicussion, as it is a fundamental change to specs that does this, which needs to test for unpredictable results based on given assignment of the waypoint.

### Specs are written in wrong formats

An example is the [http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop](Manipulate Arrays With pop) waypoint.

```js
assert((function(d) {
  if (d[0] == 'John' && d[1] == 23 && d[2] == undefined) {
    return(true);
  } else {
    return(false);
  }
})(myArray), 'myArray should only have the first two values left(["John", 23])');
```

> myArray should only have the first two values left(["John", 23])

The variable name `myArray` could be changed and is not even tested, so it should not be part of the assert message. Consider

> Should only contain the first two values.

The waypoint could also be cleaned up and remove the enclosed function and the comments that should be in the description and specs:

```js
var myArray = ["John", 23, ["cat", 2]];
var removed = myArray;

test(myArray, removed)
```

It's less cumbersome for beginners, and a lot cleaner by keeping the rules in specs and how-tos in description.

Also the specs could leverage the use of testing frameworks such as [Jasmine](http://jasmine.github.io/), or simply [tape](https://github.com/substack/tape). This would allow specs to be written as

```js
// tape
t.plan(2)
t.same(myArray, ["John", 23], 'Should only contain the first two values')
t.same(removed, ["cat", 2], 'Should contain the removed array')

// jasmine
it('should only contain the first two values', function () {
  expect(myArray).toEqual(["John", 23])
})

it('should only contain the removed array', function () {
  expect(removed).toEqual(["cat", 2])
})
```

---

> This is incomplete, and will change over time as issues are being opened.

**Comment by benschenker** [comment]
I totally agree with this.  I think going with a jasmine style approach could also resolve the point I brought up in [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2158#issuecomment-133280490).  It is just kind of a pain to fix any tests right now.   I'd love to help move over to jasmine or something more sane.

Any input @benmcmahon100  or @BerkeleyTrue?

**Comment by benmcmahon100** [comment]
Well there are two problems with this. Firstly I don't think it's going to happen that we leave chai js unless there is a significant benefit to moving. The second issue is that what's being proposed is that some take the time to go through each challenge to change each layout individually. This in itself provides to issues. First, if we asked a camper to do this then the meaning and purpose of a lot of challenges will be lost or chamged. The obvious solution to this is for me to do all of them which would mean no new content. As for the challenges being syntax specific and not dry this is 100% intentional. People have to repeat things to remember them and the challenges are done in such a way to teach one reliable method of doing things. Interpertation means that you could finish them in any way at which point they are no longer lessons but smaller easier bonfires.

**Comment by fnky** [comment]
The problem with the syntax specific, as described above is not only that people have to repeat things, but also introduces problems with waypoints not being successful, even though there's no problem with the output.

Specs should only assert on output, not check how you wrote the code syntaxically—which linters do—to get the output.

**Comment by benmcmahon100** [comment]
Which is correct when coding but we are trying to teach syntax stuff and what methods do. Not how to solve problems. The bonfires are for problem solving and as such have no syntax requirements

**Comment by BerkeleyTrue** [comment]
> The spec contradicts with it's description.

You are giving an example of an incorrect description that should be fixed by a PR. This isn't an indication of bad curriculum, just an indication of a small team that overlooked a mistake. If you would like to form a PR for those when you see them that would be awesome!

> The variable name myArray could be changed and is not even tested, so it should not be part of the assert message

It is tested. That specific challenge asks the user to mutate that var. If they change the name of the var then they have miss understood the purpose of the challenge.

> test(myArray, removed)

This provides no useful information to the user and could be removed without noticeable difference. The reason we have the whole test in the editor is so the user can see how we go about testing the challenge. More information is better then none or obscured information.

> Also the specs could leverage the use of testing frameworks such as Jasmine, or simply tape.

There is no difference between jasmine in chai in the examples given. The syntax @fnky points out `it('does something', fn)` is used when using the test harness, which we do not use in testing challenges. assert by itself is more then sufficient. There is no real value in adding tape, although I do want to move to it in the future and we will be using it in the testing curriculum.

```
t.same(myArray, ["John", 23], 'Should only contain the first two values') = assert.equal(myArray, ["John", 23], 'Should only contain the first two values')
```


At the moment we are only using chai to pull off assert and add `should` to the prototype (which I'm against and will fix). We are currently removing all instances of expect and moving to assert so we get clean test message. 

I think a lot of the issue people are having would be fixed by using CodeMirror and adding in proper line breaks to display the testing suite instead of just inserting them into the DOM as text.

**Comment by fnky** [comment]
The example I gave was just one of many similar issues. There are a lot of challenges that has contradicting descriptions.

Currently there is a growing amount of duplicated issues—as newcomers don't search for similar topics before posting, but that is another matter of its own—and a lot of the issues are because of misleading descriptions for tasks and asserts which does not have sufficient descriptions, or none at all.

The goal of this topic is to make it easier for newcomers to understand the tasks and testing results, and to know when a failed test is a their fault or a bug/problem in the task itself.

**Comment by BerkeleyTrue** [comment]
> There are a lot of challenges that has contradicting descriptions.

And we are working on fixing them, but we do require a lot of help with these. So it would be awesome if we could get campers to point out each mistake individually, in its own issue, so they can be improved/fixed/removed by other campers in PR's.

Is that what you are pointing out in this issue, that a lot of challenges need to be improved?

**Comment by benschenker** [comment]
@fnky, I and others have also been going through and deduping/labelling the whole backlog of issues so that it is clearer going forward.  It is much easier to find that your issue has been reported when there are only 50 outstanding issues than when there are 500.

**Comment by QuincyLarson** [comment]
@fnky Thanks for the issue. I agree with Ben and Berkeley that each flawed test should have its own issue. These are meant to be as specific and granular as possible.
