### ISSUE TITLE
missing ')'

### ISSUE THREAD

**Issue by LuckyOreo** [FreeCodeCamp/FreeCodeCamp#2394]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the last check step is missing ')' after document

Close your $(document.ready(function() { function with });.)

Also, when the third check step is completed, the ')' disappears after document

**Comment by benschenker** [comment]
Hey thanks for pointing this out!

Confirmed! Actually tests 3 and 4 both do that.  This is definitely a typo

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2229
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2081
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1953
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
