### ISSUE TITLE
Again also completed early

### ISSUE THREAD

**Issue by Eiseldora** [FreeCodeCamp/FreeCodeCamp#2399]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

While I was tying in the comment before I typed in text it told me that the challenge was completed and advanced me to the next challenge.

I"m not sure what is causing this.

Code I wrote:
```html
<!---

--->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
![comment to clarify code](https://cloud.githubusercontent.com/assets/8946787/9403037/124f580c-4798-11e5-9e6c-6b50a0f70b04.png)

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2398
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2393

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by eabedrapo** [comment]
Hi @bugron, I don't think this issue is related to the issues you mention above. They talk about other waypoints so in those cases the tests pass by other reasons.

The problem with this waypoint (http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code) is that once typing `<!--` we automatically get inserted a closing comment tag at the end of the code (`-->`) so the third requirement (be sure to close your comment with) is wrongly fulfilled.

Why?
1. Because students won't have the opportunity to actually close the opened comment by themselves, so the test in this case doesn't proof that students are learning to close them.
2. Also because the tag is in the wrong place (we don't want to comment our HTML out but just leave a comment at the top of it).
3. By accomplishing the requirement with the closing comment tag in the wrong place might lead students to confusion as the goal of the exercise is just leave the comment "You shouldn't need to modify code below this line" at line 1.

So in my opinion a fix for this issue would be:
1. Prevent the closing comment tag automatically inserted once the opening comment tag is typed.
2. The third test should only pass if the comment is closed at the end of line 1.

I hope it helps to clarify the problem and make things better :wink:

Regards!

**Comment by benschenker** [comment]
This is an interesting point @Eiseldora and @eabedrapo.  Lets leave this open to see if anyone whose been working on the curriculum wants to chime in.

**Comment by AEA2002** [comment]
@eabedrapo Thanks for your comment:

> I don't think this issue is related to the issues you mention above. They talk about other waypoints so in those cases the tests pass by other reasons.

There are many issues posted where waypoints and other challenges are completed before the correct code is entered that are considered "related to other issues," but the issues are not resolved. Maybe I should post this as an issue?

an issue I posted (see above) 
>Incorrect code marked correct #2548

**Comment by BerkeleyTrue** [comment]
closing as stale
