### ISSUE TITLE
Confused about why code did what it did

### ISSUE THREAD

**Issue by MyganAshton** [FreeCodeCamp/FreeCodeCamp#2404]
function reverseString(str) {
   var strArray = str.split('').reverse().join('');
   return strArray;
}

reverseString('hello');
____________________________________________________________________________

function reverseString(str) {
   var strArray = str.split('');
   strArray.reverse();
   strArray.join('');
   return strArray;
}

reverseString('hello');

_____________________________________________________________________
Can anyone tell me why the top block of code produces a string while the second block of code produces an array? I passed the challenge, but I just want to understand WHY there was such a drastic difference.

**Comment by KleoPetroff** [comment]
Not sure if this is the right place to ask this question, but nevertheless:

In the first example you are using a pattern called method chaining .In other words, you are calling multiple methods on a single object. The methods will be called from left to right. So first, the `split()` method will create an array with elements , the characters of the string. After that, `reverse()` will reverse the position of the elements and finally the `join()` method will join all elements of the array in a string. That string will stored in the variable `strArray`.

But why the second example is not working? Let's investigate - you are assigning the array of characters of `str` to the `strArray` variable and reversing the array after that. Nothing fancy so far. But when you try to join the elements of the array nothing happens. That is because JavaScript calls the `join()` method, joining the elements of the array in a string and after that discards the change. That's why you are not seeing the string when you return the `strArray` variable. Storing the result of calling `join()` method in a variables, or just returning it will work. 

In your example:
```
function reverseString(str) {
    var strArray = str.split(''); // Assigning the value of str.split('') to strArray
    strArray.reverse(); // Calling reverse method reversing the array
    strArray.join(''); // Calling the join method and discarding the change after execution
    return strArray // strArray will return the reversed array
}
```

Proper way

```
function reverseString(str) {
    var strArray = str.split(''); // assigning the value of str.split('') to strArray
    strArray.reverse(); // calling reverse method reversing the array
    return strArray.join(''); // calling the join() method on the strArray variable and returning the result. It will actually return a string.
}
```

Another proper way:

```
function reverseString(str) {
    var strArray = str.split(''); // assigning the value of str.split('') to strArray
    strArray.reverse(); // calling reverse method reversing the array
    var result = strArray.join(''); // calling the join method and assigning the value to the variable
     return result; // returning result variable. It will return a string
}
```

You can use [FreeCodeCamp's Help Room](https://gitter.im/FreeCodeCamp/Help?source=orgpage) so ask questions about Waypoints and other related technical questions.

**Comment by BerkeleyTrue** [comment]
Hello @MyganAshton ,

In the future please use the chat to ask questions. Issue tracker is to track bugs with code/curriculum.

Happy Coding!

**Comment by MyganAshton** [comment]
I apologize, but I had issues posting to chat earlier. I'm sorry if my post caused any confusion or delays in your regular activity and will be more mindful of my posts in the future. Thank you for your patience! And thanks to KleoPetroff for providing an answer to my question.

**Comment by BerkeleyTrue** [comment]
@MyganAshton No worries. Happy Coding!
