### ISSUE TITLE
Your left-well element should have a red background.

### ISSUE THREAD

**Issue by kairatomurbek2** [FreeCodeCamp/FreeCodeCamp#2407]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
I don't know what the exact problem is but https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2403 + https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2354.
Please, first use GitHub filters.

**Comment by benschenker** [comment]
Thanks for posting this issue!

If you are having trouble completing the challenge, feel free to ask in the gitter chat room and someone should be able to help there.

If you are encountering something that you think is a bug, please post a screenshot here with some description so that we can attempt to replicate the issue.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
