### ISSUE TITLE
Reverse a String (function)

### ISSUE THREAD

**Issue by ChristianBrouns** [FreeCodeCamp/FreeCodeCamp#2422]
Challenge http://www.freecodecamp.com/challenges/bonfire-reverse-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/13905119/9410893/29777466-4823-11e5-8048-4338ad484426.png)

As soon as I type function in the body of the script the page freezes. I can no longer type anywhere else, not even on a different webpage.

**Comment by benschenker** [comment]
Confirmed that browser freezes when you type function at the end of this challenge.

You may need to clear your browser cache in order to be able to complete this challenge.

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2272
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2264
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1960

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
