### ISSUE TITLE
Error: array.reduce(...) is not a function

### ISSUE THREAD

**Issue by zloy531** [FreeCodeCamp/FreeCodeCamp#2427]
Challenge http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce has an issue.

Error: array.reduce(...) is not a function

My code: 
```
var array = [4,5,6,7,8];
var singleVal = 0;
// Only change code below this line.

singleVal = array.reduce(function(prev, cur) {
  return prev + cur;
})

// Only change code above this line.
(function() {return(singleVal);})();

```

**Comment by saadanerdetbare** [comment]
You are missing a semicolon after the the reduce function. Changing the code to this: 
```
var array = [4,5,6,7,8];
var singleVal = 0;
// Only change code below this line.

singleVal = array.reduce(function(prev, cur) {
  return prev + cur;
});

// Only change code above this line.
(function() {return(singleVal);})();
```
Makes it run

**Comment by BerkeleyTrue** [comment]
Please see:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!

**Comment by zloy531** [comment]
But I still think what this is a bug.
Semicolons isn't necessary in EcmaScript. Result should not depend on semicolons.
Or, at least, error must be more verbose.

**Comment by BerkeleyTrue** [comment]
As best practice, we teach to include semi colons.

* While not necessary to include, semicolons are added at runtime by compilers as a fix. Meaning that compilers are fixing your code.
* Because we are reading in your code and `eval` it, the tester will actually freeze up because newlines are lost.
* Because whitespace is meaningless in javascript, semicolons are explicit notices to other coders that you are intentionally ending a line of code. It is always better to be explicit than Implicit. This also remove ambiguities that result in errors, especially with new coders.


Happy Coding!
<br>
<br>
<br>
<br>
<br>
<br>

#semicolonsEverywhere

**Comment by benschenker** [comment]
@BerkeleyTrue, Agreed about the semicolons but is it possible to have a better error displayed?  Right now it just says `YYY is not a function` and that isn't really helpful in this situation.

**Comment by thdoan** [comment]
Explanation why you're getting this error: https://stackoverflow.com/a/42036382/452587
