### ISSUE TITLE
Waypoint Bug

### ISSUE THREAD

**Issue by alinalper** [FreeCodeCamp/FreeCodeCamp#2462]
Challenge http://freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes has an issue. It seems like a bug. Thanks.

<img width="421" alt="screen shot 2015-08-22 at 01 41 11" src="https://cloud.githubusercontent.com/assets/5332145/9420506/fb07939e-486e-11e5-8c5f-20906d1bdad9.png">

**Comment by benschenker** [comment]
Thanks for posting!

Can you post the code that you've got on that page?  Take a look at [Code Formatting](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting).

What you posted a screenshot of is the sidebar that shows the specific tests that are run against your code.  If you see an X then the test is failing and you need to fix your code.

Lastly, take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug) to see the best way to resolve a problem with the site.

**Comment by alinalper** [comment]
Hi. 

Code is working well. I did waypoint. But I want to show "null is not an object" area. Actually it must be say "do something". Not "null is not an object" I think. 

Thanks.

<img width="1280" alt="screen shot 2015-08-22 at 01 38 24" src="https://cloud.githubusercontent.com/assets/5332145/9423004/49bb8452-48b8-11e5-9f8a-0662638623ff.png">

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2341
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2314
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2182
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
