### ISSUE TITLE
RE: Waypoint: Learn how Script Tags and Document Ready Work

### ISSUE THREAD

**Issue by spramp** [FreeCodeCamp/FreeCodeCamp#2463]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue.

The way the last two directions are written is *very* confusing:

**Add $(document.ready(function() { to the beginning of your script element.)**

**Close your $(document.ready(function() { function with });.)**

It took me awhile (maybe I was just being slow today) to realize that you don't need to repeat the script element: **$(document.ready(function() { }**

**Comment by BerkeleyTrue** [comment]
This has been fixed but it may be cached in your browser. Try opening up the same tab in incognito mode  or in different browser and let me know if you are still seeing the incorrect version.

**Comment by benschenker** [comment]
I think he is referring to the wording of the test cases, not the missing parenthesis

**Comment by spramp** [comment]
Yes, sorry.  The wording is what caused confusion. The last two directions taken together make it sound like you need to write the script element twice.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2428
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2425
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2394
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2229
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2081
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1953
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
