### ISSUE TITLE
The APIs and Microservices Certification is now missing from curriculum and translations

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#24632]
The APIs and Microservices Certification is now missing from curriculum and translations:

![freecodecamp_curriculum_challenges_english_at_master_ _freecodecamp_freecodecamp](https://user-images.githubusercontent.com/985197/47259846-bb186380-d475-11e8-9fc1-7a6a6cbf74d9.png)

We need to add this certification and its translations back in.

**Comment by Fordco** [comment]
Should this issue be closed since a solution was merged?

**Comment by QuincyLarson** [comment]
@beaucarnes Were you able to run this certification through the translator? 

If you haven't, of course, be very careful as it can get expensive quickly if you make a mistake.

Once these are translated, could you open a new PR adding these translations to the repo?

**Comment by beaucarnes** [comment]
This has not been done yet. I will start working on it.

**Comment by RandellDawson** [comment]
@beaucarnes Please make a separate PR for each set of language translations, so they are not all tied together.  That way, the translators can focus on their own specific language PR and not hold up the others.

**Comment by moT01** [comment]
Do we want someone who can speak these languages to review these or is it safe to merge them? I took a quick look and they seem fine to me.

**Comment by moT01** [comment]
Do we want someone who can speak these languages to review them? Or is it safe for me to merge them? I glanced at them and they look good to me.

**Comment by RandellDawson** [comment]
@moT01 I believe we can go ahead an merge these translations now as long as there are no other earlier PRs for them (which there should not be).  

FYI - I was given permission by Quincy to merge any non-English curriculum PRs as long as after reviewing, I did not see anything in appropriate (spam, referral links, etc.) after running the translations through Google translate.  For these this is a non-issue, because they have only been run through Google translate.
