### ISSUE TITLE
Discrepancy between instructions and checklist on 1st jQuery waypoint

### ISSUE THREAD

**Issue by evasyl1** [FreeCodeCamp/FreeCodeCamp#2475]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions say $(document).ready... and the checklist says $(document.ready....
$(document).ready.... seems to be the one that lets me move forward. :-)
![image](https://cloud.githubusercontent.com/assets/13828160/9422587/3ed9ea92-484f-11e5-8cc0-d097d92075fb.png)
![image](https://cloud.githubusercontent.com/assets/13828160/9422593/7acc4a7c-484f-11e5-8ace-7f7120ac3970.png)

**Comment by issyl0** [comment]
Hi there! This appears to have already been fixed. :-) Maybe try again now and see if you can get through?

**Comment by BerkeleyTrue** [comment]
@evasyl1 

Try opening this page in incognito mode or a separate browser. Let me know if that makes a difference.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2463
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2428
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2425
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2394
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2229
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2081
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1953
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by evasyl1** [comment]
Looks great. Thanks.
