### ISSUE TITLE
build a simon Zipline displays Tic Tac Toe zipline video

### ISSUE THREAD

**Issue by jschnei** [FreeCodeCamp/FreeCodeCamp#2476]
Challenge http://freecodecamp.com/challenges/zipline-build-a-simon-game has an issue. 

The video displayed is for the Tic Tac Toe zipline.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2063
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1906
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1864

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
