### ISSUE TITLE
Wrong class to change in #Waypoint: Target a Specific Child of an Element Using jQuery

### ISSUE THREAD

**Issue by adrienZ** [FreeCodeCamp/FreeCodeCamp#2492]
The instructions ask us to change the second child of div with class="well", but the exercise is validate when you change div class="target" element.

**Comment by jbmartinez** [comment]
This test is right. The children of the `well`s have the `target` class and you can target them with `.target:nth-child()` because, again, they're the children. You can also use `.well :nth-child()`, notice the space in this case.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2429
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2187
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2068
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2005

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
