### ISSUE TITLE
Basic Java Script: Manipulate Arrays With pop()

### ISSUE THREAD

**Issue by nabikiram123** [FreeCodeCamp/FreeCodeCamp#2500]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The last element required by the challenge is not the correct one when the pop is applied

**Comment by BerkeleyTrue** [comment]
This challenge is working. Can you describe the steps to reproduce the issue?

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2406
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2132
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1911

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
