### ISSUE TITLE
Challenge text changes 

### ISSUE THREAD

**Issue by daksh844** [FreeCodeCamp/FreeCodeCamp#2512]
Hi All,

The text of the challenge changes from "Give your h1 element the inline style of color: white." to this text "Cannot read property 'length' of null" as soon as I write in-line "style" tag in the h1 tag. Is this normal to appear as all the tags are checked dynamically - but would be great to confirm.

Cheers,
Deepanshu

Challenge http://freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @daksh844 thanks for posting this issue!

Take a look at (Our Bug Posting Guidelines)[https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug] and run through the steps there.  

I can't help you much without seeing a screenshot, but my guess is you are trying to add a `<style>` tag inside of the `<h1>` instead of adding the style as an attribute like:
`<h1 style="color: green"></h1>`

**Comment by daksh844** [comment]
Hi @benschenker here is the screenshot below:
![image](https://cloud.githubusercontent.com/assets/8793646/9427590/73381cdc-49a3-11e5-8dc5-88ba4ccc13dc.png)

As soon as I write the style tag inside h1 the challenge question on the LHR changes the text from "Give your h1 element the inline style of color: white." to this text "Cannot read property 'length' of null".
Let me know if you require any further inputs from my end.

**Comment by dokkillo** [comment]
This waypoint have an assert that looks you have 1 style,

assert(editor.match(/<h1.*style/gi) && editor.match(/<h1.*style.*color:/gi).length > 0

When you only writes style and not writes the rest, the assert crashes, because it try to do a length from a null variable.
But really, in this waypoint you need the H1 in white, you have it in orange and 2 errors, Its secondary that for a short time, it says another error message but if you finish the sentence, the errors will fix without problems

Regards

**Comment by daksh844** [comment]
ok thanks for the clarification. appreciate it
