### ISSUE TITLE
Is this a typo? Waypoint: Disable an Element Using jQuery

### ISSUE THREAD

**Issue by Cadence22** [FreeCodeCamp/FreeCodeCamp#2543]
It says "Here's how you would disable all buttons: $('#button').prop('disabled', true);"
but shouldn't it say 

$("#button").prop("disabled", true);

![screen shot 2015-08-22 at 8 44 04 pm](https://cloud.githubusercontent.com/assets/13908810/9426534/12aa61ca-490f-11e5-8750-0be07e1e5d75.png)

**Comment by benschenker** [comment]
Hey thanks for submitting this! Someone else posted this issue too: See #2014 for more info, it seems like this will be fixed with Pull Request #2018

This issue can be closed as a duplicate, but take a look at our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for future reference.
