### ISSUE TITLE
Stock Price Checker REST Best Practice and Unclear Instructions

### ISSUE THREAD

**Issue by johnkmzhou** [freeCodeCamp/freeCodeCamp#25863]
For the [Information Security and Quality Assurance - Stock Price Checker](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/stock-price-checker/) project, sending back the like in a GET is a bad practice. GET should be idempotent. It would probably be a better idea to do it in a PATCH.

Also if you actually restrict your content security policies to only allow the loading of scripts and css from your server, then jQuery won’t work because the script comes from the domain jquery.com.

**Comment by Lewis65** [comment]
You're right about jQuery, since the CDNs are often faster than hosting locally. But, if required for hypothetical security reasons, hosting a minified copy locally would not be awful.

As for REST best practices, again you're probably right. It could be nice to have a writeup on these concepts available on the FCC Medium page so that it can be linked from the project. I don't think it is unlikely that someone doing the project would make the GET idempotent if they design/test their project thoughtfully, but it would be useful to explicitly and purposefully encourage this.

**Comment by numoonchld** [comment]
Since unclear instructions is included in the title, I'd like to add that the user-story 

> 5. If I pass along 2 stocks, the return object will be an array with both stock's info but instead of likes, it will display rel_likes(the difference betwwen the likes) on both.

listed [here](https://giant-chronometer.glitch.me/) is unclear on what the actual behaviour should be.

It'll take some amount of guesswork by the camper to finish the project.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
