### ISSUE TITLE
assert shown in challenge

### ISSUE THREAD

**Issue by KuchiVanDerK** [FreeCodeCamp/FreeCodeCamp#2599]
Challenge http://freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. 

The asserts propably shouldn't be shown.
It's the same for the other Basic JavaScript Waypoint's.

Chrome: Version 44.0.2403.157 
Windows 8.1

![ccbug](https://cloud.githubusercontent.com/assets/3470426/9429757/6adafd3c-49dc-11e5-81fd-9ac766e8473d.png)

**Comment by benschenker** [comment]
Hey @KuchiVanDerK thanks for posting an issue!

That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.

This can be closed as a duplicate.  Take a look at the [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some tips to get your questions answered more quickly.

**Comment by bugron** [comment]
@KuchiVanDerK  thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2462
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2376
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2373
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2341
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2314
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2182
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by AdventureBear** [comment]
Plus, writing code against tests is a good project development practice as far as I am aware. Write out tests as program expectations and when the all pass your app works!
