### ISSUE TITLE
Left and Center columns scroll together on waypoints

### ISSUE THREAD

**Issue by Kaereste** [FreeCodeCamp/FreeCodeCamp#2625]
http://puu.sh/jMRT1/3dfb64f10b.png
Final instruction not visible on screen. Any changes to code cause page to jump to top.
If this is intentional, then it is a massive failure of forethought and design. I'm not sure how I'm to work in the center column when the instructions are not visible.

**Comment by benmcmahon100** [comment]
This is the original way that the editor worked I personally added the the separate scrolling feature after several people complained about the same issue you were having. This was subsequently back-tracked after several users complained after the update that they hated the single element jumping to the top and wanted it changed back. I'm afraid that the jump is caused by a technological limitation eager than something that we can directly influence. I have and ode that ms achieve the best of both worlds but I'm sure that there will he a contingent of people who will be unhappy with the change. That said if more people like yourself come back and say that they preferred the separate scrolling element solution then I will implement my idea at that point. For the time being you may find it helpful to zoom out slightly from the page which will allow more to fit in the screen at the cost of font size.

**Comment by Kaereste** [comment]
Zooming out isn't really an option. I already have it the smallest that I can comfortably see it. I guess I'll just go back to using codecademy. Thanks.

**Comment by BerkeleyTrue** [comment]
fixed.

Happy Coding!
