### ISSUE TITLE
Incorrect submission graded as correct

### ISSUE THREAD

**Issue by oharrison** [FreeCodeCamp/FreeCodeCamp#2652]
Challenge http://freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![untitled](https://cloud.githubusercontent.com/assets/10459779/9458425/144700d4-4abc-11e5-9da1-df445ba5c7ad.png)

**Comment by bugron** [comment]
@oharrison thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2300
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2210
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2115
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2075

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
