### ISSUE TITLE
Not sure if this is right.

### ISSUE THREAD

**Issue by Nomey-LNSP** [FreeCodeCamp/FreeCodeCamp#2656]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

It seems that you need a space after .well to make the proper :nth-child() work. It shouldn't require that space considering .well:nth-child() works as is per your example. 

https://drive.google.com/file/d/0ByhvcOYrgFMGY21heUFkNC1qLTA/view?usp=drivesdk

**Comment by a1rr0wh3ad** [comment]
Hello. If you use $(".target:nth-child(2)").addClass("animated bounce"), then there shouldn't be a space because we are selecting elements with class target and is 2nd child.

If you use $(".well :nth-child(2)").addClass("animated bounce"), you need the space because we are then selecting elements that are descendants of elements with class well, and is 2nd child.

Given that this is one of the most asked questions in the FreeCodeCamp chat at Gitter, maybe this does need some clarification in the text.
