### ISSUE TITLE
Constant MIME Errors for Chrome and Firefox. Unable to even see the site. Multiple users report

### ISSUE THREAD

**Issue by kerukelw** [FreeCodeCamp/FreeCodeCamp#2660]
![imag333333e 1](https://cloud.githubusercontent.com/assets/13267311/9461707/f7684db0-4b42-11e5-9923-b507a9b455e6.png)

Firefox and Chrome is not allowing me to view freecodecamp till to a mime header problem. 

Some of my friends from Singapore are unable to see the website on various browsers. IE is fine, but mozilla firefox and chrome cant seem to work.

**Comment by kerukelw** [comment]
Just in, Opera is not working.

**Comment by benmcmahon100** [comment]
@BerkeleyTrue This Is weird isn't it?

**Comment by benmcmahon100** [comment]
Update: Site works with a proxy forwarding everything on. Why? Who knows

**Comment by BerkeleyTrue** [comment]
Someone in Singapore with some know how is going to have to help with this.

1. Who is sending `mime type error` page? Since it works through a proxy it is obviously not a browser issue but some middleman is smudging things.
2. Is there a way to find what the MIME type header looks like when requesting directly.
3. Is there some kind of firewall in between that is causing this. He have had issue's with headers being to long before when it comes to some firewalls. Not much we can do in this situation. Though, I have yet to see it complain about the MIME header, it is usually the CSP headers that are blocked.

**Comment by abhisekp** [comment]
I'm getting this while using a Singapore proxy to access http://www.freecodecamp.com/

# 502 Bad Gateway

The server returned an invalid or incomplete response.

**Comment by awesomeaniruddh** [comment]
Reporting in from Singapore: I'm not having issues with accessing FCC. I have a few friends who use FCC too, and they are not having any errors either (AFAIK).

Weird.

**Comment by BerkeleyTrue** [comment]
I'm closing this as it seems like this is actually a firewall issue (which we have an issue open for somewhere).

**Comment by kerukelw** [comment]
Dear people, 
I know this issue closed one month ago, but i found out a potential issue which may help in the future.

I noticed that I am not having problems when I am not prompted to log in to a network ON A BROWSER. after connecting (for example, the Hilton hotel, you need to log in with your room ID and your hotel number in the browser itself, among other things).

My local network does the same thing since I am working in a shared space, which would explain why me and my peers are getting these messages. Hope it helps.
