### ISSUE TITLE
Waypoint: Make Images Mobile Responsive

### ISSUE THREAD

**Issue by sir-castiq** [FreeCodeCamp/FreeCodeCamp#2661]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Below is the code for 2 images as requested. 2 of 3 tests pass. The last one says the image URL should be "http://bit.ly/fcc-running-cats" as is shown below. The image loads correctly but the test does not pass.
img class="thick-green-border img-responsive" src="http://bit.ly/fcc-relaxing-cat"
img class="thick-green-border img-responsive" src="http://bit.ly/fcc-running-cats"

--angle tags removed to prevent image loading

**Comment by Shufeng01** [comment]
Have you tried to reset the test to and paste it again? it worked on mine.

**Comment by benschenker** [comment]
Thanks @sir-castiq!

Check out the [Code Formatting Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting) for how to display your code and not have it render the html.

I think your issue is that your first img tag isn't inside the `<a>` from the previous challenge:
```
  <a href="#"><img class="smaller-image thick-green-border" src="http://bit.ly/fcc-relaxing-cat"></a>
  <img class="thick-green-border img-responsive" src="http://bit.ly/fcc-running-cats">
```
works fine for me.

I'm going to close this but reopen it if you are still having issues.

**Comment by yaseenagag** [comment]
<img class="thick-green-border img-responsive" src="https://bit.ly/fcc-running-cats">

Your forgot to add the S to your http it should be https

**Comment by yaseenagag** [comment]
<img class="thick-green-border img-responsive" src="http://bit.ly/fcc-running-cats">

You need to add an s to your http (https:)
