### ISSUE TITLE
Some unnecessary code revealed.

### ISSUE THREAD

**Issue by Roylyan-Nikita** [FreeCodeCamp/FreeCodeCamp#2676]
Challenge at http://freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. If be more accurate all Basic JS exercises have that issue. 
-----------------------------------------------
Just watch screenshot: http://i.imgur.com/IZVEsPL.jpg;
Browser: FF42

**Comment by bugron** [comment]
@Roylyan-Nikita thanks for posting this issue!
See merged pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2633 and also check [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code) - the last paragraph of the challenge description clarifies this.
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2599
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2462
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2376
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2373
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2341
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2314
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2182
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
