### ISSUE TITLE
learnyounode resources to learn nodejs and mongodb are not good enough

### ISSUE THREAD

**Issue by mfaizanchaki** [FreeCodeCamp/FreeCodeCamp#2730]
Although learnyounode has been recommended by nodejs.org for tutorials on how to learn node js, but it has seriously failed in making students understand node js or mongodb.

The thing is, in some challenges there, the preceding challenge's instructions or tutorial is contained in later challenges which makes it difficult for students to keep up with the tutorial and also to complete the challenges.

I would suggest using native tutorials for node js as well, as freecodecamp has done with the rest of the Front-End part of the program.

**Comment by awesomeaniruddh** [comment]
You are very correct here: learnyounode is certainly very lackluster.

To get you started with the basejumps, follow some of the tutorials on this link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Basejump-Resources

It's a page on the FCC Wiki that is regularly updated by some of us campers who are doing the basejumps. We ran into roadblock like you too, and SaintPeter created the page so that we can compile all the resources.

Hope that is helpful.
