### ISSUE TITLE
A problem in jQuery course

### ISSUE THREAD

**Issue by mohessaid** [FreeCodeCamp/FreeCodeCamp#2733]
The jQuery course has a problem in printing all the parts of the pages. And in Firefox an infinite loop keep executing and showing the notification box of challenge complition.

**Comment by bugron** [comment]
@mohessaid thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2731
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2729

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
