### ISSUE TITLE
Waypoint: Remove an Element Using jQuery missing specific assignment instructions

### ISSUE THREAD

**Issue by metakata** [FreeCodeCamp/FreeCodeCamp#2758]
Challenge http://freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This challenge is missing the specific target instructions of what to remove.  I only found out what was meant to be removed after clicking the "Run Code" button and the detailed lesson check list came up.

Otherwise all is great.  Thanks for setting this up!!

**Comment by metakata** [comment]
{Fixed] I have found where these instructions are in the code and it has been fixed in the current "staging" branch.   When the live version is updated, the new line "Remove element <code>target4</code> from the page by using the <code>.remove()</code> function." will be present in the instructions.  

/seed/challenges/jquery.json

Unfortunately, I do not know how to "close" this issue.

**Comment by metakata** [comment]
I should be clear, it was fixed before I looked at the code, but it isn't incorporated to the live version yet.

**Comment by bugron** [comment]
@paulopadopalos thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2781

Also this issue was resolved with merged pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2734.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
