### ISSUE TITLE
The CodeSchool AngularJS is really inadequate for Basejumps.

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#2762]
The CodeSchool course is _okay_ to start, but it does not go into fundamental concepts of AngularJS including _$scope_, creating services and factories and _routing_.

It's also a very difficult course to follow along with on your own. They frequently add and modify code that is not shown in the video.

Routing and $scope are pretty essential in how the Basejumps are set up, but they are not taught anywhere in the curriculum at the moment.

I know @QuincyLarson doesn't want to use Codecademy any more, but their course is much better than the CodeSchool course for learning Angular.

**Comment by jbmartinez** [comment]
I followed Codecademy to complement CodeSchool and I think both courses are good, but the Codecademy course was easy to follow for me because I completed the CodeSchool one first.

On the other hand and slightly off topic, I've followed several courses and tutorials about AngularJS and found that all of them lack lots of information. Things like factory, service, provider, $on, $link, $digest, $apply and many others are almost a mystery to me. I read that Angular 2 simplifies those things a lot, though

**Comment by 1hella** [comment]
I think a lot of those things are a little more advanced than what we might need for Basejumps. I'm not sure because I don't know what a lot of them are haha.

I just think that if we have to choose between either the CodeSchool or Codecademy course, the Codecademy course teaches more what we need for Basejumps using the angular-fullstack generator and _maybe_ clementine.js. Not knowing what $scope and routing do are pretty huge knowledge gaps.

**Comment by jbmartinez** [comment]
Agree, routes and $scope are fundamental concepts

**Comment by anjanjanj** [comment]
I found the official tutorial was quite useful for the basics of routing and $scope: https://docs.angularjs.org/tutorial

**Comment by benschenker** [comment]
Agreed.  The CodeSchool lesson is a great intro but is not substantial enough on its own.

**Comment by ltegman** [comment]
I think part of the problem is that angular is such a huge framework that there are sometimes multiple ways to do the same thing and it's hard for a course to cover all of them in a clear and concise way. I've actually seen many people argue that the `Controller as` syntax used in the CodeSchool lessons is the better practice vs using `$scope`. ([Digging into Angular's 'Controller as' syntax](http://toddmotto.com/digging-into-angulars-controller-as-syntax/)) However, there are lots of applications built using `$scope`, so it is definitely something people need to learn at some point.

**Comment by awesomeaniruddh** [comment]
This is a very good alternative that helped me a ton when I was starting out: https://thinkster.io/a-better-way-to-learn-angularjs

**Comment by matty22** [comment]
Can this issue be closed since the move to React is just a few weeks away?

**Comment by ltegman** [comment]
@matty22 Good call. This isn't even on the curriculum right now XD
