### ISSUE TITLE
[feature request]: Timeline for revision

### ISSUE THREAD

**Issue by StubRavi** [freeCodeCamp/freeCodeCamp#27722]
It will be good if there is a separate timeline for revising curriculum. For example, If someone has finished the "css challenges" 4 months ago and now want to revise it again; the system should keep track that he/she has finished these challenges again on this date. Because, during the revision, it is not recorded by streak.

![timeline](https://user-images.githubusercontent.com/34769076/47412934-98928d00-d78a-11e8-858a-3349249b5fa6.JPG)

**Comment by RaspberryLime** [comment]
How would you envisage it to be recorded? Just a simple entry in the list (so duplicate entries for the same item), or to have a completed date column and a revised date column?

**Comment by StubRavi** [comment]
I can't say about the old curriculum, but it will be good having a second column for recently completed.

**Comment by RaspberryLime** [comment]
@ezioda004 there were multiple columns in the previous curriculum. Google has examples -- it actually had three columns, one for date completed, one for the most recent modified date, and then a link to the saved solution. As the solution is no longer saved maybe this is why the modified date was dropped?

But I think that it should be tracked and counted in the streak if someone redoes a challenge. Maybe someone starts the course and then comes back to it again after many months and redoes everything as a refresher. They shouldn't lose their streak because they do that.

**Comment by moT01** [comment]
So all a user would have to do to keep their streak alive is go do the easiest challenge over again every day. I'm not sure I like that.

**Comment by raisedadead** [comment]
The current timeline shows the latest completion data. Going to close this, as for this being an easy way to keep the streak live is fine I guess. GitHub streak is also hackable, you can commit in the past.

Its really upto you to maintain the academic honesty.

**Comment by raisedadead** [comment]
<details>
<summary>Details</summary>



</details>
