### ISSUE TITLE
Waypoint: Iterate over Arrays with map - "array.map(...) is not a function"

### ISSUE THREAD

**Issue by joshcronkhite** [FreeCodeCamp/FreeCodeCamp#2778]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map has an issue. Reporting "array.map(...) is not a function". Code in the console at the time is as follows:

//Use map to add three to each value in the array
<code>var array = [1,2,3,4,5];</code>
// Only change code below this line.
<code>array = array.map(function(val){
  return val + 3;
})</code>

// Only change code above this line.
<code>(function() {return(array);})();</code>

The following example shows this code working on an alternative environment (logging values):
http://repl.it/BEC4

**Comment by MayankJ30** [comment]
I have been able to replicate this issue on my machine too.

**Comment by benmcmahon100** [comment]
So the issue here is that the map needs a semi colon at the end! Weird right? No idea why it gets so upset about the semi-colon in this instance but that is the cause of the problem. Sorry about the confusion this has caused and I'm not sure this can be fixed really as the editor is reporting an inaccurate response. My guess is that it's because the editor is in "Use Strict" mode but for some reason it gives the wrong error.

**Comment by joshcronkhite** [comment]
Indeed, although I'll happily accept the explanation. Thanks for the feedback! I'll be mindful of this in future exercises if trouble arises again.

**Comment by benmcmahon100** [comment]
I'm going to see if I can either fix this error reporting or else have at least a notice for the issue

**Comment by BerkeleyTrue** [comment]
We require the semi-colon because of the use of eval to actually test your code. Closing as stale. If anyone finds a work around please chime in.


Happy Coding!
