### ISSUE TITLE
Multi-line valid comment rejected as possibly correct answer

### ISSUE THREAD

**Issue by junhaoyap** [FreeCodeCamp/FreeCodeCamp#2787]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

<img width="609" alt="screen shot 2015-08-27 at 12 12 12 pm" src="https://cloud.githubusercontent.com/assets/6291947/9530476/ee363482-4cb4-11e5-983c-e9b6559cebdc.png">
<img width="574" alt="screen shot 2015-08-27 at 12 12 24 pm" src="https://cloud.githubusercontent.com/assets/6291947/9530477/ee483e66-4cb4-11e5-89d6-3f2a97b0ede9.png">

The multiline comment does have 5 or more characters but is rejected by the Regex assertion.

**Comment by bugron** [comment]
@junhaoyap thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999

Also there is PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2185 which fixes this issue.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by junhaoyap** [comment]
Apologies, let me close this issue.
