### ISSUE TITLE
JS challenge compilator error

### ISSUE THREAD

**Issue by xam4lor** [freeCodeCamp/freeCodeCamp#28087]
**Description of the problem:**
I wanted to solve the "JavaScript Algorithms and Data Structures Projects: Caesars Cipher" problem and I wrote the code localy before copying it on the submit area. The code worked perfectlly on my browser but it broke with an error "assignment to undeclared variable index" which seems to be recurrent on the web interface.
I have the following code:
```javascript
let SHIFT_NB = 13;
let letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];

function rot13(str) {
  (str = str.toString().toUpperCase().split('')).forEach((el, i, arr) => {
    let com = letters.indexOf(el);
    com != -1 ? arr[i] = letters[index = com + SHIFT_NB > letters.length - 1 ? com + SHIFT_NB - letters.length : com + SHIFT_NB] : null;
  });

  return str.toString().split(",,").join(" ").split(",").join("");
}

// Change the inputs below to test
rot13("LBH QVQ VG!");
```

**Link to the page:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher/

**Browser and operating system:**
* Browser Name: Firefox Developer Edition
* Browser Version: 64.0b3 (64 bits)
* Operating System: Windows (64 bits)

**Screenshot:**
![image](https://user-images.githubusercontent.com/9009614/47450261-12476c80-d7c5-11e8-866a-3762807574d2.png)

**Comment by xam4lor** [comment]
If found the error, the web compiler doesn't like my `letters[**index =** com + SHIFT_NB...` but my browser does..... Weird!

**Comment by RandellDawson** [comment]
Not sure if you tried bringing this issue up in the forum first, but in the future, try there to see if anyone can provide you guidance when you believe your code is "correct" but the tests will not pass.

The reason you code does not pass is because of the linter which FCC uses for the curriculum.  It runs code int Strict mode, so all variables must be declared first before using.  That is why you get **index is not defined** error.

I am closing this, because you can resolve this by first declaring your variable **index** (which is a best practice anyway).  If you still want to reopen this as an issue, then reply back.

Thank you.
