### ISSUE TITLE
JavaScript Section errors

### ISSUE THREAD

**Issue by shaikhatik0786** [FreeCodeCamp/FreeCodeCamp#2818]
I just completed jQuery, and started Javascript, but the challenges section is all messed up
I tried in all browsers, and all latest updated. Chrome, Mozilla, Microsoft Edge.

I even tried on both my desktop PC as well as laptop, same issue
![screenshot_4](https://cloud.githubusercontent.com/assets/4403762/9554808/3e6c2146-4de6-11e5-9936-17a63a048718.png)

**Comment by bugron** [comment]
@shaikhatik0786 thanks for posting this issue!
Note that your issue is a duplicate and already solved.
See merged pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2633 and also check [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code) - the last paragraph of the challenge description clarifies this.
Screenshot below is a part of **yours**.
![](http://i.imgur.com/rabZB2b.png)

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by shaikhatik0786** [comment]
@bugron Aah!, I see, I thought it was unusual to have the bug only in this section. Now I understand the point. 
Thanks for the help mate.
