### ISSUE TITLE
Each Camper News comment load triggers its own server call

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#284]

**Comment by jameskopacz** [comment]
Looking at the way comments are stored. I'm not seeing a way to find what story deeply nested comments are attached to.
```
Main Story
- First level comment
-- Second level comment
--- Third Level comment
```
First level comments are the ones people use to directly comment on the story. When saved it's easy to notify the Main Story poster since it referencing the Main Story.

Second level would be replies to the above comments. They're easy to notify because the ```associatedPost``` of the above comments are set to the Main Story id. So you can check if the comment being posted is to a Main Story by checking the object and if it isn't then you can use ```associatedPost``` to get information about the Main Story.

The problem starts with Third level comments. Their ```associatedPost``` references the Second level comment id. A Fourth level comment ```associatedPost``` references the Third level comment id and so and and so on.

How do you get what Main Story Third+ level comments are attached to without recursive database calls?

I hope I'm wrong  and am overlooking something. But if what I'm seeing is correct, we could probably just add a field to the comment model that holds the Main Stories id. I just don't wanna go messing around with things unless it really needs it and it has an OK from others.

**Comment by QuincyLarson** [comment]
I figured out a way to persist the original article and its author in the comments. I now have emails working on our Nonprofit-show branch (which will soon be merged into UX-improvements, which will then be merged into master). But you're right - we shouldn't hit the server for every comment. 

@terakilobyte should we refactor this to grab all of these comments in one call? I think they could add up quickly on a popular Camper News thread.

**Comment by QuincyLarson** [comment]
I discussed this with @terakilobyte. he didn't seem to think this was a big deal. We'll monitor New Relic and if we see these story show views causing spikes, we'll go in and refactor it. Thanks for pointing this out, @jameskopacz!
