### ISSUE TITLE
Neglects programming principle of D.R.Y. and forces repetition of code. 

### ISSUE THREAD

**Issue by jhaeger** [FreeCodeCamp/FreeCodeCamp#2855]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This isn't so much of a bug, as a problem with the curriculum itself. 

My code

  var ranNumb = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotOne = ranNumb;
    slotTwo = ranNumb;
    slotThree = ranNumb;

Which results in the correct result, but it will not pass. Why? Because I tried to minimize repetition by using another variable.

**Comment by suhussai** [comment]
The way you have it, the same random number generated in the beginning will be stored in all three variables, slotOne, slotTwo and slotThree. From the description of the waypoint, I think what they want is three different random numbers in each variable, which means you would need to generate the random number three times.

**Comment by benmcmahon100** [comment]
Hey @jhaeger what @suhussai is 100% correct! Otherwise you'd have a slot machine that always won! and that wouldn't be right, the house always win after all ;) I think i see what you're try to get at though. You could, if you were ever making a slot machine make the random number generation into a function and set each number to be that same function which would yield a random result for each one. Unfortunately, due to limitations in how the testing works you'll have to just use the given method fo each variable or else the tests wont pass

**Comment by jhaeger** [comment]
Yes, thanks for pointing that out. It is obvious, but I missed it. (blame it on lack of sleep)

**Comment by benmcmahon100** [comment]
Ha Ha no worries! Happy Coding!

**Comment by BerkeleyTrue** [comment]
@jhaeger The principal of Premature Optimization is more important then DRY. DRY will sometimes hold back a developer because they spend too much time trying to program perfectly, which is a waste of time/money. There are also places where DRY does not apply. For instance, when building a testing suite repetition is unavoidable and you will end up introducing a lot of unnecessary complexity.

Its always more important to get it working first, refactor after.


Happy Coding!

**Comment by jhaeger** [comment]
@BerkeleyTrue Thank you for the good advice. I know I've got a lot to learn. CodeCademy and the free stuff on CodeSchool can only take one so far. 

In my day job, I'm a web designer/developer, but it's pretty light on scripting or OOP. Thanks again.

**Comment by BerkeleyTrue** [comment]
No worries, code happy!

**Comment by APrioriRainbows** [comment]
I'm wondering why this can't be written as a function? If writing it as a function works, and upholds the principle of D.R.Y, then that would be the better choice. 
Here is the code that I tried to run below
------------
     function numGenerator(){
       return Math.floor(Math.random() * (3 - 1 + 1)) + 1;
     };
     
    slotOne = numGenerator();
    slotTwo = numGenerator();
    slotThree = numGenerator();
------------
I get why jhaeger's code would not work, but I think writing it as a function would.
