### ISSUE TITLE
Challenge waypoint-manipulate-arrays-with-unshift has an issue

### ISSUE THREAD

**Issue by aryasaatvik** [FreeCodeCamp/FreeCodeCamp#2916]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. unshift(['Paul']) does not solve the challenge and returns a cryptic message instead 

```
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
// ourArray now equals [["happy", "joy"], "J", ["cat"]]

var myArray = ["John", 23, ["dog", 3]];
myArray.unshift(["Paul"]);

// Add "Paul" to the start of myArray
// Only change code below this line.


// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(y, z){return 'myArray = ' + JSON.stringify(y);})(myArray);
```

![screenshot from 2015-08-31 09 22 51](https://cloud.githubusercontent.com/assets/5666379/9575778/d57c42c8-4fc1-11e5-95ac-d28564185795.png)

**Comment by awesomeaniruddh** [comment]
```
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
// ourArray now equals [["happy", "joy"], "J", ["cat"]]

var myArray = ["John", 23, ["dog", 3]];
myArray.shift();

// Add "Paul" to the start of myArray
// Only change code below this line.
myArray.unshift("Paul");

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(y, z){return 'myArray = ' + JSON.stringify(y);})(myArray);
```

That works. The reason is pretty self-explanatory, however, if you do not understand, then hit me up on the FCC GItter chat: @awesomeaniruddh.

Also, when code does not work, please go to the Help channel on the FCC gitter (Link: https://gitter.im/FreeCodeCamp/Help). More often than not, someone will point out the mistake in the code and explain why your solution does not work, and point you towards the correct solution.

Also, the 'cryptic error' is the test that FCC uses to validate your solution: it may seem cryptic at first, but if you look at it more closely, then I'm sure you will be able to make sense of it. It's not formatted properly on the website, so you might find it easier to copy the code to a text editor that supports syntax highlighting (or even ask someone on the FCC gitter to break it down for you). The test will often help you understand the demands of the challenge when the description of the challenge is not clear.

**Comment by nazmulhooque** [comment]
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();

// Only change code below this line.
myArray.unshift(["Paul",35]);
