### ISSUE TITLE
Return Largest Numbers in Arrays ??? 

### ISSUE THREAD

**Issue by zngit** [FreeCodeCamp/FreeCodeCamp#2924]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/13928066/9582477/c2e8ff98-502f-11e5-9ef3-aa6d883a5bc9.png)

my solution is working on nodepad++ and other browser but not working on freecodecamp

function largestOfFour(arr) {
  // You can do this!
  
  var newArr = [];
  var k = 0;
  
  		for (i=0;i<arr.length;i++)
		{
			for (h=0;h<arr[i].length;h++) 
			{
				if(k<arr[i][h])
				{
					k=arr[i][h];
					newArr[i] = k;
				}
				
			}
	
		}		
	  
  return newArr;
  
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

**Comment by bugron** [comment]
@zngit thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2890
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

There are a few PRs (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879, https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2887) which are waiting for approvement. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
