### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by 0-cool** [FreeCodeCamp/FreeCodeCamp#2931]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. 

When you start exercising the compiler tells you "cannot read property 'eql' of undefined", the problem is that I have never stated that property and more change that I made in the editor, compile always says the same.

**Comment by bugron** [comment]
@0-cool thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2890
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

There are a few PRs (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879, https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2887) which are waiting for approvement. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
