### ISSUE TITLE
Search option not working.

### ISSUE THREAD

**Issue by SKSSKS** [freeCodeCamp/freeCodeCamp#29311]
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a Github issue.

Search bar is not working properly. Search option working first time, on search the page will redirected to another page and after that search on that page search option does not work.

1. Go to 'Homepage'
2. Click on 'Curriculum'
3. Search  'hello'
4. It will redirected to 'new page'
5. Again search hello
6. hit enter

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser chrome
 - Version 
![screenshot from 2018-10-26 12-06-08](https://user-images.githubusercontent.com/11253853/47549389-83983400-d919-11e8-9450-cf5001bd9090.png)
![screenshot from 2018-10-26 12-06-25](https://user-images.githubusercontent.com/11253853/47549417-97dc3100-d919-11e8-8ae0-e6835044c23d.png)

70.0.3538.67 (Official Build) (64-bit)

**Comment by rishikesh1410** [comment]
@SKSSKS I also noticed it . Can I work on this ?

**Comment by skyemorgan0907** [comment]
yesSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Rishikesh Sahu <notifications@github.com> Date: 2/2/19  3:11 PM  (GMT-06:00) To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [freeCodeCamp/freeCodeCamp] Search option not working. (#29311) @SKSSKS I also noticed it . Can I work on this ?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rishikesh1410 in #29311: @SKSSKS I also noticed it . Can I work on this ?"}],"action":{"name":"View Issue","url":"https://github.com/freeCodeCamp/freeCodeCamp/issues/29311#issuecomment-459999323"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/freeCodeCamp/freeCodeCamp/issues/29311#issuecomment-459999323",
"url": "https://github.com/freeCodeCamp/freeCodeCamp/issues/29311#issuecomment-459999323",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RandellDawson** [comment]
@Bouncey I can confirm this is still an issue.  Should this be reported over at https://github.com/freeCodeCamp/search-assets/issues ?

**Comment by ojeytonwilliams** [comment]
I'd quite like to take a look at this, but I've fallen at the first hurdle!  Where is the source for the search.freecodecamp.org page?  It doesn't appear to be in https://github.com/freeCodeCamp/search-assets.

**Comment by coder077** [comment]
I can take a look at this.
