### ISSUE TITLE
Bonfire: Convert HTML Entities : doesn't convert apostrophe

### ISSUE THREAD

**Issue by anknits** [FreeCodeCamp/FreeCodeCamp#2950]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Here is what my code looks like:
```
function convert(str) {
  // &colon;&rpar;
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g,'&apos');
}

convert('Dolce & Gabbana');
```
However, it doesn't pass the test "Shindler's List". Why?

**Comment by awesomeaniruddh** [comment]
The challenge itself doesn't have an issue. Please go the FreeCodeCamp Gitter help channel (https://gitter.im/FreeCodeCamp/Help) for help with the bonfire.

**Comment by catapixel** [comment]
@anknits To answer your immediate question, your apostrophe would not be replaced in the example code you've provided because the html entity ends in a semi-colon but your replace function for the apostrophe is missing this in the substitution.

Regarding the rest of your code, it is difficult to read the code you have pasted in because I believe the html entities you've typed in your replace functions have already been swapped out.

I, like @awesomeaniruddh do not believe there is an issue with this challenge.

**Comment by anknits** [comment]
Well that explains the error. Thank you so much Jason.

Regards,
Ankur

**Comment by bugron** [comment]
@anknits if your problem is solved feel free to close the issue, thanks.
