### ISSUE TITLE
Broken link for guide on challenge: iterate through object using for in.

### ISSUE THREAD

**Issue by Hassanraja447** [freeCodeCamp/freeCodeCamp#29554]
**Describe your problem and how to reproduce it:**
I found a broken link and can anyone tell me how can I fix it?

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
Chrome, Window 10
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by jeremynofs** [comment]
In https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/_meta/basic-data-structures/meta.json there is a leading space for the title.

Basically, in challenge https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement/ under get a hint it leads to

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement/

instead of

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/

**Comment by imambungo** [comment]
how about changing [the directory](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement) name?

from this:
-iterate-through-the-keys-of-an-object-with-a-for...in-statement
to this:
-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Comment by twins16** [comment]
same her broken link !!

**Comment by luane91** [comment]
Any update on this issue? I am still finding broken links in the same challenge > 'get a hint' button

**Comment by QuincyLarson** [comment]
It looks like the hint article is located at https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/

I think the hint button automatically changes any non-alphanumeric character into a `-` so the guide article file name should instead use `---` instead of `...`

And yes, as @jeremynofs pointed out, there is a leading space in the challenge name. We aren't quite ready to deploy the new Master branch, so we should just change the `...` into `---` at this point, then address the trailing space later - otherwise the guide and the curriculum will be out-of-sync.

Any takers?

**Comment by moT01** [comment]
I have created an issue to consolidate all of the broken "get a hint" links https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/learn)
