### ISSUE TITLE
"Check for Palindromes" bug

### ISSUE THREAD

**Issue by gorlovn** [FreeCodeCamp/FreeCodeCamp#2956]
Use the following code:

```
function palindrome(str) {
  // Good luck!
  var str_lc = str.replace(/ /g,'').toLowerCase();
  var str_r = str_lc.split('').reverse().join('');
  if (str_r == str_lc)
    return true;
  else
    return false;
}

palindrome("eye");
```

Get error:

```
assert.deepEqual(palindrome("A man, a plan, a canal. Panama"), true);
expected false to deeply equal true
```
![bonfire check for palindromes free code camp - mozilla firefox_019](https://cloud.githubusercontent.com/assets/4133988/9602826/367247e0-50c5-11e5-87e2-54ed722bb4b0.png)

**Comment by Mansuro** [comment]
Punctuation should be ignored

**Comment by catapixel** [comment]
@Mansuro is correct. @gorlovn your regex needs to replace all non-word characters before you check to see if the remaining letters form a palindrome. Your current regex only looks for and replaces spaces. As a help, in regex any white space character can be represented by \s. It helps make your regex a little more readable as well. Hope that helps to clear things up. All of the other tests are passing with your current code because they don't have punctuation or other non-word characters.

**Comment by iheartkode** [comment]
@gorlovn Once you see the above messages can you close this issue? For future reference you can check the https://gitter.im/FreeCodeCamp/freecodecamp help chat :)

**Comment by gorlovn** [comment]
Thank you very much for all your comments.
