### ISSUE TITLE
Javascript Section of Free Code Camp

### ISSUE THREAD

**Issue by mikevarela** [FreeCodeCamp/FreeCodeCamp#2960]
I had prevoiusly written Quincy about some small things I've found in the course, things that aren't as simple or directly addressed and have confused me a little.

These things relate to:

1) code that runs functions below my code. This is often distracting to the eye and causes the window to be clogged up and messy.

2) the hint code below on left if not very readable and often just gives you the answer.

3) in the array section, you mention putting arrays in arrays, but you do this with only one example, and it looks like this var myArray = [["something"]]. While this is correct, it doesn't really highlight the idea that you can have multiple items in an array ALONG WITH another array. I would have preferred var myArray = [7, "hi", ["something", 6]];

4) in the length tutorials, it's not really clear if I need to augment the text that is already there, or write my own. and you assign variables to variables, but that has never really been discussed, so it's confusing to see.

5) in the codcademy tuts, they were great about showing you an idea, how it worked, then making you write it and often, you wrote the same code often, meaning there was a tactile learning part as well.

6) You sort of breeze over objects and relate them to arrays. I'm thinking later they're be more instruction on that, but objects aren't really arrays, sure in javascript they behave like so because almost eveything is an object, but this doesn't setup someone for a deeper discussion on objects and properties/methods

7) in the math section, it might be better for use to write out the expression and not just change a number. it's too passive. also, maybe have another section of order of operations and using multiple operators in a single problem?

I write this not to say that I'm not grateful, not that I'm not learning. But the codcademy course waht very well thought out, specifically with an eye to a slow and gentle walk through of the basics which led to a greater understanding . They also made you write a lot of code, hence building that muscle/brain memory. This course, at least thus far, has felt like a short quick introduction that is more interested in getting a few concepts across than actually taking the time necessary to fully explain why and how.

In any case, keep up the work. I see it improving all the time and again, say a huge thanks for putting it all together.

**Comment by benschenker** [comment]
Hey @mikevarela thanks for posting this!

I believe 1 has been fixed.

**Comment by benmcmahon100** [comment]
Hey @mikevarela sorry about the delayed response but we have worked on a lot of these issues since then.

1 -> Most of theses functions have been tidied up or removed. There may be some more room for improvement but we now have people working through these challenges so hopefully this will be fully addressed soon. This also applies to point three to some degree but this hasn't been the focus at the moment. I can see if we can make this a slightly higher priority.

2 -> We have redone the layout of the left hand side bar a few times now that should improve readability.

5 -> We should have @Srinarth working on this soon! He wants to work on lessons that introduce a topic and work towards it in a similar way to the bonfires but in a more guided way.

6 -> I think @brianamarie has covered some of these topics in her hikes. If they aren't though the other aforementioned stuff should partially address confusions and lacking explination

**Comment by QuincyLarson** [comment]
@mikevarela We just pushed a major overhaul of our JavaScript curriculum, an effort lead by @SaintPeter. When you have time, please work through it again and let us know which of these issues persist. Thanks for your time and feedback! http://www.freecodecamp.com/map#basic-javascript
