### ISSUE TITLE
Code passes without the "()" part of "function()".

### ISSUE THREAD

**Issue by Risle** [FreeCodeCamp/FreeCodeCamp#2962]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

My code was incorrect and returned a "null" but it still passed. The challenge was to return a random number between 1 - 10.  Here is the code:

Correct answer:
"return Math.floor(Math.random() * 10);"    //(random number generated)

My input:
"return Math.floor(Math.random * 10);"    //"null"

![codecampchallenge](https://cloud.githubusercontent.com/assets/10679949/9610815/b1a96306-5090-11e5-9d02-6b76214b63a2.png)

**Comment by bugron** [comment]
@Risle thanks for posting this issue!
There is a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2892 which is waiting for approvement and will fix this issue because i've added a new test which is checking if you are generating your random number using this code: `Math.floor(Math.random() * 10);`, so if you omit parentheses that test will fail. If my answer satisfies you, feel free to close the issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
