### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays 

### ISSUE THREAD

**Issue by billcw** [FreeCodeCamp/FreeCodeCamp#2965]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think my code works, but it looks like the array in the right column, that is used for the answer is different from the array that is used in the largestOfFour call.

![capture](https://cloud.githubusercontent.com/assets/13501980/9614172/1401f8ce-50be-11e5-9339-fc26ed9e6605.JPG)

**Comment by catapixel** [comment]
@billcw there is problem with your current code. your 'largest' variable is not being reset to zero each time you move to the next array so your results are not coming back correctly. You can see this in the second test failure which shows your code returning ```[27,27,39,1001]``` when it should be returning ```[27,5,39,1001]```.

In other words after your code processes the first array the largest variable is equal to 27. When it moves on to process the second array the largest variable is still set to 27 because it has not been reset and, since 27 is larger than any values in the second array, that is the value that gets, pushed....

Hope that helps you understand why you're failing at this point. Almost there. Good luck!

**Comment by billcw** [comment]
@catapixel Thank you very much Jason.  I should have looked into it deeper before submitting an issue.  I assumed that since it returned correct results for what was called from my code, it was right.

Per your advice, I reset largest to 0 outside of the outer FOR loop, and it passed.

Thank you very much!

**Comment by billcw** [comment]
@catapixel  Thank you very much Jason!  I should have looked deeper, or asked for help before submitting and issue. 

Per your suggestion, I reset 'largest' to 0, outside of the outer FOR loop.

Thank you very much for your help!
