### ISSUE TITLE
Waypoint: Give your JavaScript Slot Machine some stylish images showing error 

### ISSUE THREAD

**Issue by vishdha** [FreeCodeCamp/FreeCodeCamp#2989]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/6947417/9625629/26636b6c-5175-11e5-904a-a911df536b0a.png)

**Comment by bugron** [comment]
@vishdha thanks for posting this issue!
I've just passed that test with the code provided in description. [Proof](http://prntscr.com/8bsd70). Tried in FF 38 and Chrome 43.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by catapixel** [comment]
@vishdha The code you've screenshot is not passing because it doesn't match the code provided. You have accidentally introduced an illegal space between the double quote and the single quote after the the src declaration begins...
```$($('.slot')[0]).html('<img src = " '``` should be
```$($('.slot')[0]).html('<img src = "'```
If you make the correction and eliminate the extra space you will pass the inital test.
