### ISSUE TITLE
Test Case fails for Correct Answer

### ISSUE THREAD

**Issue by Thiruppathi** [FreeCodeCamp/FreeCodeCamp#3003]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

#Bonfire: Return Largest Number Of Arrays
```
function largestOfFour(arr) {
  // You can do this!
  var subArrCollection = arr.map(function(subArr){
    return Math.max.apply(null, subArr);
  });
  var result = Math.max.apply(null, subArrCollection);
  return result;
}
largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```
I'm able to get the largest number. But Why this is failing in the test cases? 

Here is the JSBin
http://jsbin.com/gezupo/edit?html,js,console,output

**Comment by infoalisaa** [comment]
I am actually just having the same problem myself with this Bonfire!
Here is my code:

function largestOfFour(arr) {
  arrResult = [];
  var biggest = 0;
  for(var i = 0;i<arr.length;i++){
      for(var j = 0; j<arr[i].length;j++){
       if(arr[i][j]>biggest){
            biggest = arr[i][j];
          }
       else{
             biggest = biggest;
             } 
       }
          arrResult.push(biggest);
}
  return arrResult;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);


I think the problem may be with the second test:

assert.deepEqual( largestOfFour( [[13, 27, 18, 26], [4, 5, 1, 3],     [32, 35, 37, 39], [1000, 1001, 857, 1]]), [27,5,39,1001], 'arrays should match.');
arrays should match.: expected [ 27, 27, 39, 1001 ] to deeply equal [ 27, 5, 39, 1001 ]

It might be trying to match the final array on [27, 27, 39, 1001] instead of [5, 27, 39, 1001].
Hope this gets fixed soon!

**Comment by infoalisaa** [comment]
Actually, now that I see your code, Thiruppathi, you do not need to return the largest number.
The directions are that you need to return the largest number in each subarray and then have the program return it as an array.
I still think there is an issue with this problem because my answer, which I am pretty sure is correct, does not match what the Bonfire tests for.

**Comment by dmytroyarmak** [comment]
@Thiruppathi, @infoalisaa is right, accoring to the task you should return array of 4 largest numbers (one per each subarray).

So your code can be changed to:
```
function largestOfFour(arr) {
  return arr.map(function(subArr){
    return Math.max.apply(null, subArr);
  });
}
```

@infoalisaa You should reset `biggest` to `Number.NEGATIVE_INFINITY` (for current test cases `0` is ok too) on each iteration of outer scope.
The problem that you have is `biggest` having value `27` (max value of first arrray) when you are starting to compute max for second array.

**Comment by Thiruppathi** [comment]
@infoalisaa Thanks for pointing out.. I misunderstood the requirement... 
@dmytroyarmak   Thanks for your input...
