### ISSUE TITLE
Is this ok? 

### ISSUE THREAD

**Issue by MiodragP** [FreeCodeCamp/FreeCodeCamp#3051]
Challenge http://freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
<i class="fa fa-thumbs-up"><button class="btn btn-block btn-primary">Like</i></button>

i think that </i> have to be at the end of line code... is that correct?

**Comment by ahstro** [comment]
Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by abhisekp** [comment]
@MiodragP please close this issue and read guidlines before posting as @ahstro says.

@ahstro as a collaborator you could close this issue as it's irrelevant.

**Comment by bugron** [comment]
@MiodragP thanks for posting this issue!
Is that a stereotype that the "Like" button has to be in the bottom of your page? Anyway I'm closing this issue because it isn't actually an issue. Please, discuss such question in our official [Gitter chat room](https://gitter.im/FreeCodeCamp/FreeCodeCamp). Thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
