### ISSUE TITLE
The file of the img seems to be wrong.

### ISSUE THREAD

**Issue by DitriAhmetaj** [FreeCodeCamp/FreeCodeCamp#3073]
Challenge http://freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the source of the img is : https://bit.ly/fcc-relaxing-cat. seems wrong since it doesn't end with a .jpg or .jpeg or any sort of image format...

How to pass the exercise ?

**Comment by quatridunull** [comment]
The link given is still a valid image. If you click through to the link, it sends you to https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg (notice the .jpg) which is the image that you are actually embedding. bit.ly is a link shortener, and fcc used it so you don't have to type in that whole long URL when you're doing the exercises.

**Comment by bugron** [comment]
Closing this issue as @quatridunull fully answered to @DitriAhmetaj's question.

**Comment by Afrodisiac** [comment]
Although this issue is closed, I'd like to add some insight for anyone else having trouble with this challenge: Be careful when you're selecting the link text to copy and paste into your code! If you copied `http://bit.ly/ffc-relaxing-cat.` into your `img` tag, the `.` at the end will **break** the link, thus resulting in a broken image. Simply removing the `.` will fix the link and show you that *puuurty* kitten. :smile_cat:

**Comment by JonthueM** [comment]
My image is broken without the .

**Comment by pjmay** [comment]
@Afrodisiac Actually test passes even with the extra `.` I think it's still a bug cause test only verify if src attribute **contains** https://bit.ly/fcc-relaxing-cat not if it's **equal**
