### ISSUE TITLE
heroku cloud 9 terminal command is incorrect, I think.

### ISSUE THREAD

**Issue by venturads** [FreeCodeCamp/FreeCodeCamp#3080]
Challenge http://freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

~/workspace/dist && heroku config:set NODE_ENV=production && heroku addons:create mongolab

is should be:

~/workspace/dist && heroku config:set NODE_ENV=production && heroku addons:add mongolab

not "create" should be "add"

**Comment by jonslucas** [comment]
No, create is deprecated.
Check: https://devcenter.heroku.com/articles/managing-add-ons
specifically this line:
"Previously to add an add-on you could use the command addons:add. That is now deprecated in favor of the create command."

**Comment by venturads** [comment]
Then why do i an error? Add worked create said not a valid heroku command

-------- Original Message --------
Subject: Re: [FreeCodeCamp] heroku cloud 9 terminal command is incorrect, I think. (#3080)

**Comment by jonslucas** [comment]
@venturads What is the error that you are getting?

**Comment by venturads** [comment]
In c9 it says that create is not a valid heroku command and when I do heroku help addons its doesn't list create only add

-------- Original Message --------
Subject: Re: [FreeCodeCamp] heroku cloud 9 terminal command is incorrect, I think. (#3080)

**Comment by jonslucas** [comment]
@venturads  The problem here is that the heroku package is more than likely out of date.  If you run: `heroku version`  you'll more than likely see 3.31.x.  When you run `heroku help addons` do you see this line:
`WARNING: Toolbelt v3.41.5 update available.`?
If you do, run this line in the console:
`wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh`
which will update the toolbelt to the latest version.  You'll then see the changes to the `heroku help addons` command.

I find out of date versions to be the common issue with cloud9.  For instance, node.js is version 0.10.x not 0.12.x which is the current stable release.  The default npm is similarly out of date, for what it's worth.

**Comment by venturads** [comment]
is there any list of latest version and how to update them?Thank you,Albert Ventura909-810-3512  


-------- Original Message --------
Subject: Re: [FreeCodeCamp] heroku cloud 9 terminal command is
incorrect, I think. (#3080)

**Comment by venturads** [comment]
Thanks that worked, i updated my toolbelt.  When I push new commits to heroku: $ grunt --force && grunt buildcontrol:herokubut i get another error: "  GET /api/thingsMongoDB connection error: MongoError: connect ECONNREFUSED"


-------- Original Message --------
Subject: Re: [FreeCodeCamp] heroku cloud 9 terminal command is
incorrect, I think. (#3080)

**Comment by jonslucas** [comment]
@venturads That error is part of the default tests built into the default api endpoints.  If you were to be running your server at the time that those tests were run, you probably wouldn't see that error.  If you want to explore testing more you can look at the *.spec.js files.  Glad things otherwise got worked out for you!  You might find better help regarding other errors you might encounter in the chat.  Feel free to reach out to me there too.

**Comment by abhisekp** [comment]
@venturads Please close this issue if it's resolved. Please don't keep a hanging issue.
