### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MrAndrewPeterson** [FreeCodeCamp/FreeCodeCamp#3081]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I believe I have this correct.  Am I doing something incorrect in this code?

$("#left-well").parent().css("background-color", "red");

Your left-well element should have a red background.
There is a Large red X next to this section.

![image](https://cloud.githubusercontent.com/assets/10198376/9698477/c5171bb6-536c-11e5-9572-92943270e31b.png)

**Comment by bugron** [comment]
@MrAndrewPeterson thanks for posting this issue!
You can't pass the test because you are using **an example** from the description of the challenge and **not** the correct code. [See here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2980) for more information. Also there is a merged PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3050 which clarifies this situation. But in fact this type of issues are opened because campers don't actually read instructions entirely or they are not attentive.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
