### ISSUE TITLE
Question: How do I locate the pages (other than seeds) that have issues in fcc staging?

### ISSUE THREAD

**Issue by AEA2002** [FreeCodeCamp/FreeCodeCamp#3100]
I can locate the challenge pages in staging, but I don't know where to find any other pages that have issues, when I look for them to attempt to resolve the issues.

Thanks

**Comment by QuincyLarson** [comment]
Which files are you talking about specifically? View files? 

If you can find a unique string on a page, you can do a codebase-wide search and usually find that page. That's the only shortcut I know of to finding individual view files.

**Comment by AEA2002** [comment]
Thanks for the response. I'm embarrassed to write I don't remember what the page was.
I had looked at an issue, but couldn't find the page when I went to staging. 

Okay, if I close this for now and reopen if I have this issue again?

**Comment by bugron** [comment]
@AEA2002 yes, you can close this issue for now. Feel free to reopen if you still experience problems, thanks.

**Comment by ahstro** [comment]
@AEA2002 A minor protip that has saved me god knows how much time is `grep -R "search string"`. If you're on a Unix (a.k.a. not Windows) machine, this command will most likely be available in your terminal, and it searches through all files in your current directory and all subdirectories for the provided string. You might need to learn how to exclude certain folders though, since `node_modules` can contain a bunch of hits.

**Comment by AEA2002** [comment]
Thanks all.
@ashstro Thanks for the info. Unfortunately, I'm riding with windows, but there must be some equivalent to that search feature, right???? I'll guess I'll search for that search feature for windows
