### ISSUE TITLE
Target the parent of an element using jQuery - red background

### ISSUE THREAD

**Issue by dev-diva** [FreeCodeCamp/FreeCodeCamp#3107]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I've read the multiple issues classified as bugs where the child (#target1) wasn't identified in the code but the parent (#left-well) was.  I believe I have the correct code and the background of the well is appearing red but "Your left-well element should have a red background" is not checked as correct.  If I change the child to "#target3" my answer is accepted.  

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
  });

**Comment by natac13** [comment]
I can clear this up with the the PR I submit for some test changes in that file for single and double quotes as well I see there is a typo on that same challenge

**Comment by bugron** [comment]
@dev-diva actually your issue is **11th** duplicate issue. See this comment for [more info](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2337#issuecomment-133099660). I'll leave it open because @natac13's PR will automatically close it.

**Comment by bugron** [comment]
@natac13 I've just verified that your fix is working. Thank you for contributing!
P.S. A little advice from @benmcmahon100. For example, `$(" #button ")` will not pass your test because you force campers to use `$("#button")`. You can consider using whitespaces by adding `\\s*?` in your code for example:
`editor.match(/\\$\\s*?\\(\\s*?\\'\\s*?button\\s*?\\'/g)`. Of course this will make your RegExp more complex but users won't be confused.
