### ISSUE TITLE
couldn't save current progress !!

### ISSUE THREAD

**Issue by msaoudallah** [FreeCodeCamp/FreeCodeCamp#3136]
hello there , i'm new to FCC and i noticed that  the site don't auto-save my progress and i can't do that myself. that happens with me in wayPoints ! 
i do read another issue about the same problem but i can't see there is a solution yet 

-windows 8 
- chrome browser

**Comment by awesomeaniruddh** [comment]
This is not an issue with your computer or browser, but with the FCC back-end. The FCC team is working on it, and as you said, there indeed is another issue, opened by @QuincyLarson: #3116 

Since the issue has already been reported, please close this one. If you wish to voice your concerns regarding the issue, you can do so by commenting in the other issue :)

Thanks.

**Comment by msaoudallah** [comment]
@awesomeaniruddh  thanks , i will close it  :)
