### ISSUE TITLE
Broken Test - doesn't recognise removed backslashes

### ISSUE THREAD

**Issue by Kimothey** [freeCodeCamp/freeCodeCamp#31675]
**Describe your problem and how to reproduce it:**
For the Basic JavaScript: Quoting Strings with Single Quotes test, the test does not recognise removed backslashes.

See the attached image where the task has been completed and note the removed backslashes in the test area, and the message in the lower right for lack of completion.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/quoting-strings-with-single-quotes

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 70.0.3538.77
* Operating System: Microsoft Windows 10 Pro
![backslashes not recognised as removed](https://user-images.githubusercontent.com/44027463/47643551-b03f8c00-db63-11e8-9a4d-babca2884b3a.PNG)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Nirajn2311** [comment]
@Kimothey you are missing a `/` in the closing tag of `a` tag.
> The backslash \ should not be be confused with the forward slash /. They do not do the same thing.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding
