### ISSUE TITLE
Responsive Web design Project

### ISSUE THREAD

**Issue by Minahil-ayaz786** [freeCodeCamp/freeCodeCamp#31698]
how to do this challenge??
Responsive Web Design Projects
Introduction to the Responsive Web Design Projects
 a Tribute Page
 a Survey Form
 a Product Landing Page
 a Technical Documentation Page
 a Personal Portfolio Webpage

**Comment by vanditbhatt** [comment]
You can use codepen.io or jsfiddle. Just follow the instructions given in  project guidelines paste the link that points to your pen in the solution field.

**Comment by Nirajn2311** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding
