### ISSUE TITLE
Waypoint: Manipulate Arrays With pop: Typo

### ISSUE THREAD

**Issue by zahedshareef** [FreeCodeCamp/FreeCodeCamp#3190]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is a typo in this waypoint:

`'myArray should only have the first two values left(["cat"], 2)');`

Here `myArray` needs to be replaced with `removed`

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @zahedshareef , but this is not a typo :)

There are two tests to determine whether the first two elements were removed using `pop()`: the first that `myArray` contains only the first two values, and the second that `removed` contains the last two values.

If you were to manually modify `myArray` and remove the two values, the first test will accept it, but the second test will not.

Since this resolves your issue, I am closing it. Feel free to reopen if you feel that your issue was not resolved :)

**Comment by kkennethlee** [comment]
![image](https://cloud.githubusercontent.com/assets/15114745/10495132/1e8a01ce-726f-11e5-87f1-863bde767141.png)

I think its a typo in a sense that it should be: removed should only contain ["cat", 2] 

and not  ["cat"], 2

For what should be so simple, this confused the heck out of me.

**Comment by awesomeaniruddh** [comment]
Oh, I seemed to have missed that. Opening a PR.
