### ISSUE TITLE
'Run Test' Button not responsive

### ISSUE THREAD

**Issue by AbuNadhrah** [FreeCodeCamp/FreeCodeCamp#3196]
Challenge http://www.freecodecamp.com/challenges/bonfire-factorialize-a-number has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I enter the following code, I do not get a response:

function factorialize(num) { 
  for (i=1; i=num; i++) {
    num = num * i
  }
  return num;
}
factorialize(10);

However, If I introduce a bug in my code, say by altering the syntax, it responds with the accurate error. For example, using 'nu' instead of 'num' on the 3rd line of code will result in the error "can't find variable: nu" in the console.

**Comment by bugron** [comment]
@AbuNadhrah thanks for posting this issue!
Actually your code is incorrect. I mean this part:
```javascript
for (i=1; i=num; i++) {
num = num * i
}
```
This is an infinite loop because there is no any condition which will stop this loop. You can find more info about this bonfire in our [Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki). Please, discuss issues like this in our [Gitter char room](https://gitter.im/FreeCodeCamp/Help) first, thanks.
Closing this issue.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
