### ISSUE TITLE
The last example is not a palindrome.

### ISSUE THREAD

**Issue by vkarla** [FreeCodeCamp/FreeCodeCamp#3226]
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.1, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

https://drive.google.com/file/d/0B3wxZOoKId9pb3NsalFtZ2NCdUU/view?usp=sharing this is a screenshot. You can se that I tried with the last palindrome. And too, I tried to replace "-" with "_", but it doesn't help. I think it is not a palindrome, so please check it. Every other examples work good. Thenk you. :)

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @vkarla, but it *is* a palindrome!

You have to remove *all* punctuation. Without any punctuation, the string is just `0000`, which as it turns out, *is* a palindrome :)

I am closing this issue, but you can always visit the [help chat](https://gitter.im/FreeCodeCamp/Help) over at Gitter, there are plenty of helpful people hanging out there who can help you out with your code :)

**Comment by sigshane** [comment]
That is a cheesy test string. Why on Earth would anyone enter that combination of characters, expecting the program to strip out 75% of them? Anyone employing common sense would look at that as some sort of emoticon, and reverse what they SEE, not what the program perceives as whitespace and trash characters.
Silly trap is all that last one was.

**Comment by jbmartinez** [comment]
This challenge should be reworded to clarify it, in my opinion. Currently it says " ignoring punctuation, case, and spacing".

I'm not a native English speaker, but according to [wikipedia](https://en.wikipedia.org/wiki/Punctuation_of_English), the underscore is not a punctuation mark. Even regexes consider the underscore as a word character. Dashes are punctuation marks, but can be considered by many campers as a word character because words can be hyphenated. 

Could you consider to reopen this issue?

**Comment by mathewleland** [comment]
Yeah, defining underscores as punctuation is very questionable.  Using a standard regular expression flag like \W even lets underscores go.

For anyone who is having trouble defining a regular expression to eliminate all punctuation, 
var punc = /\W|_/gi;
should work

**Comment by gitasong** [comment]
I'm with @sigshane and @jbmartinez on this one. Why are all those extra characters used in the final challenge if they're merely supposed to be deleted? That's just a bait-and-switch. A better challenge would be to write code that correctly perceives the string to be a palindrome—or not.

**Comment by SaintPeter** [comment]
@gitasong The last challenge is specifically put there to determine if you are just using `/\W/` as a regular expression.  If so, it will fail because `\W` = `[^a-zA-Z0-9_]`.  It's basically a way to force users to understand what they're using to clean the string.  Maybe there is another way we could do this, but the funny pattern is very effective at getting people to fix their solutions.

**Comment by gitasong** [comment]
Ah; gotcha, @SaintPeter . Perhaps something to that effect could be mentioned in the instructions, or some other pattern used for which the instructions don't appear to defeat the purpose of its existence?

**Comment by SaintPeter** [comment]
@gitasong We could be more explicit . . . but part of solving these problems is discovering the contours of the problem as you go.  

The discovery of idiosyncrasies in a function or feature are part and parcel of being a programmer.  We seek not only to teach the direct skills associated with the language, but the secondary skills of searching for additional information. 

I do agree that we could present that aspect better.  We have plans for a "Welcome to Bonfires" waypoint that will get some of this across.
