### ISSUE TITLE
Waypoint: Make Object Properties Private

### ISSUE THREAD

**Issue by brinquedo** [FreeCodeCamp/FreeCodeCamp#3233]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-object-properties-private has an issue. 

I simply typed `this` before `getSpeed` and this is what I get:

![captura de tela de 2015-09-10 21 37 12](https://cloud.githubusercontent.com/assets/12961941/9804461/266544d8-5804-11e5-981a-137b868838a1.png)

Probably because I'm dark.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @brinquedo. It is preferred that from next time on you attempt to resolve issues with your code in the Gitter help chat first (link: https://gitter.im/FreeCodeCamp/Help). There are lots of helpful folks hanging out there who will help you :)

Now to your issue:
You have to replace remove the `this` keyword from the line `this.speed = 100;`

Since I believe that this resolves your issue, I'm closing it. Feel free to reopen if you feel that your issue wasn't resolved. Please go to the help chat over at Github in the future to attempt to resolve such issues first.

Thanks for cooperating :)

**Comment by Jinnd319** [comment]
OPEN THIS BACK UP!!!
WTF WOULD YOU INCLUDE EXAMPLE CODE IF YOU CAN'T TEST IT!?!?!

This is what happens when you try to test the getSpeed method.

![bug](https://cloud.githubusercontent.com/assets/19861230/22906928/6c11e150-f20c-11e6-9b8b-147f077bac41.PNG)

Someone needs to fix this.
