### ISSUE TITLE
Bug keeping me from passing all tests - Bonfire: DNA Pairing

### ISSUE THREAD

**Issue by Gmrpr7** [FreeCodeCamp/FreeCodeCamp#3274]
Challenge http://www.freecodecamp.com/challenges/bonfire-dna-pairing has an issue. User Agent is: <code>Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

I seem to have found a solution to this challenge, but I can only pass a test if the test arguments are inserted into the function call at the bottom of my code. I tried placing two more function calls to see if this workaround would work to make all three tests pass, but it didn't. It should be clear that something is wrong from looking at the pictures I've included.
![screenshot from 2015-09-12 13 16 54](https://cloud.githubusercontent.com/assets/7867826/9833610/a84d2b34-5951-11e5-90b3-c349ea2aae0b.png)
![screenshot from 2015-09-12 13 17 08](https://cloud.githubusercontent.com/assets/7867826/9833612/ad3b15d4-5951-11e5-8ec9-29b61d345f30.png)
![screenshot from 2015-09-12 13 17 45](https://cloud.githubusercontent.com/assets/7867826/9833613/b017c482-5951-11e5-8633-0b40d23821e9.png)

**Comment by catapixel** [comment]
@Gmrpr7 I can help.

First, your `var i=0;` statement needs to be moved inside of your for loop.  A proper for loop looks like this using your variables:
```
for (var i = 0; i < str.length; i++) {
  [loop code goes here....]
}
```
Check out the examples in the documentation for more examples (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for).

Second, "yes" you need to move your `var result = [];` inside of your function. You can place it right below where you assign `str` and above your for loop. The reason why is because right now you are declaring `result` as a global array and so, when each test runs, it is not getting reset. By moving it inside of your function it will get reset each time the function is called which is what you want.

Right now, when the first function call runs `result` gets the appropriate values pushed to it. Then the second function call/test runs and `result` gets ADDITIONAL results pushed to it. Then the third test and so on. You want `result` to start fresh for each function call which again is why you need to place it inside of your function. This is best way to make sure it gets reset each time.

**Comment by Gmrpr7** [comment]
Thank you. I knew I did something wrong. I'm surprised most challenges didn't seem to have a problem with that. I think I read a book that said declaring a variable in a for loop was less efficient than declaring it outside the loop because it has to declare it for each iteration. Either way, I did a lot of things wrong lol.
