### ISSUE TITLE
Missing "http:"

### ISSUE THREAD

**Issue by csnord** [FreeCodeCamp/FreeCodeCamp#3285]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.3, Win64

Kind of a bug. In the notes it mentions to access bootstrap to use the link element

`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">`

It's missing "http:" in the href, so...

`<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>`

**Comment by Kocisov** [comment]
Not big deal. You don't need to specify protocol

**Comment by ahstro** [comment]
@csnord Thank you for reporting :)
Leaving out the protocol makes the browses try to fetch the document using the same protocol that you're currently using, i.e., if you're browsing freeCodeCamp over http, Bootstrap will get fetched over http as well. Whether this is good or if https might be preferred when possible is up to you to decide.
I'll close this since it's not harming the usability of FCC in any way, but feel free to create a pull request if you feel that this is something that should change.
