### ISSUE TITLE
A longer explanation of functions such as `map()` and `reduce()` is necessary

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#3290]
Challenge http://freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

A longer explanation of reduce is necessary, as well as the clear instruction on what to do.
The code is just given to you and you have to assume to copy and paste. Not very in depth lesson.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue, @tesla809.

I agree a 100%. `reduce` is one of the hardest JS functions (that I've come across) to get in your head, and it doesn't make sense for a long time. An in-depth tutorial is certainly needed, and we're working on that.

Thanks for bringing this to light!

**Comment by josevill** [comment]
I did use map() and filter() in the latter steps of the basic bonfires, but this is a must.
Nothing you can't learn from reading, but i think if we're going to have something recommended to use in the bonfires, we should at least know how the function works and what usages they have.

**Comment by paul-howard** [comment]
+1.

I'm already familiar with map/reduce, so the lack of explanation as to what they do, how they work, and why they're interesting didn't faze me much (though I could certainly see how it would throw those with less experience) but the lack of clear instruction on exactly what what is expected to complete the waypoint is what brought me here.

Without getting into the what/how/why issue, modifying the instruction to something like this would make the expectation much clearer to me:

> `reduce()` can be useful for condensing an array of numbers into one value. For instance, we can get the product of all values in an array of integers like so:
> ```var singleVal = array.reduce(function(previousVal, currentVal) {
>      return previousVal * currentVal;
> });```
> **Use `reduce` to store the sum of the values in `array` into `singleVal`.

P.S. In the current instructions, "array or numbers" should be "array **of** numbers".

**Comment by pedromaltez** [comment]
The current exercise for `waypoint-condense-arrays-with-reduce` isn't clear on the fact that your reduction has to be an addition. If you do anything else it won't work, but that's not clear. I wanted to multiply instead of copying the example directly but it wouldn't work.

**Comment by richyvk** [comment]
+1 much more help needed here. It's not even clear what you have to do to pass the waypoint.

**Comment by bschaden** [comment]
Also agree, Very vague, not enough for someone learning this for the first time.

**Comment by BerkeleyTrue** [comment]
Lots of discussion in this thread. Anyone up for putting together a PR?

**Comment by awesomeaniruddh** [comment]
Like I've mentioned before, the current layout of the website is not very
suitable for longer descriptions because of the small width of the panel
with the instructions.

Alternate solutions to this include adding a button to the panel that
expands it to cover the full screen or adding articles to the wiki. I'm
guessing the first solution will be desirable.

I can write a longer explanation for map() and reduce(), but I don't have
enough knowledge of the FCC codebase to actually add the expanding panel.

**Comment by BerkeleyTrue** [comment]
Why not instead add links to MDN? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

**Comment by Zhaggy** [comment]
+1 Absolutely agree. Copy/paste examples are really unhelpful. Even if you don't add much of an explanation, just having the requirement to pass the waypoint be something other than the example code in the description would make a huge difference.

**Comment by ltegman** [comment]
I have already addressed some of the concerns from this thread (lack of clearly communicated instructions for example) in my recent PR #3766, but I'm going to work on addressing more of these concerns (like adding MDN links and seeing if I can come up with clearer explanations of the concepts) in the coming days. If that PR hasn't been accepted by then I'll just add new commits onto it, otherwise I'll open a new PR for it.

**Comment by tesla809** [comment]
Thanks man !

**Comment by benmcmahon100** [comment]
Closed in #3766
