### ISSUE TITLE
Issue: Saved code no longer matches updated problems

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3293]
There are regular updates to various waypoints and Bonfires.  As campers progress, their code is saved.  If a camper is in the middle of a waypoint or bonfire when a change occurs, they will have a saved local copy of the "old way" that it was.

I propose that each waypoint and bonfire get an internal version number.  When code is saved locally it is stores the version number.  If the current version number and the stored code's version number don't match, the user should be prompted to find out if they want to reset their code.   It must be optional, because we don't want to blow away their nearly functional code.

It could also be helpful to note the version of the problem that a user has in their bonfire solutions.

**Comment by BerkeleyTrue** [comment]
This would involve a lot of work for what seems like a minor issue. Often challenges change because of typos or addition of edges cases that are not correctly covered.

**Comment by QuincyLarson** [comment]
@SaintPeter I've also encountered this issue, but I agree with @BerkeleyTrue. In most cases, improvements to Bonfires shouldn't affect working solutions. In some extreme cases, the test cases themselves will change, or one recently added test will fail because the camper's original solution wasn't sufficiently robust.

But it would be a lot of work to try to version the challenges and remember to change the version number when we update the challenges. Also note that the code stored in Local Storage is meant to be perishable. We are writing their actual solutions to our database, and will soon display them on the profile pages again.
