### ISSUE TITLE
Improvement on US phone numbers bonfire

### ISSUE THREAD

**Issue by florianpnn** [FreeCodeCamp/FreeCodeCamp#3358]
Challenge [Bonfire: Validate US Telephone Numbers](http://www.freecodecamp.com/challenges/bonfire-validate-us-telephone-numbers) needs an improvement.

I'm struggling because I don't know why "6505552368" isn't a US phone numbers, maybe adding a link to explain how US phone numbers are build can be a good decision for non US resident.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue, @florianpnn!

That *is* a valid US phone number. But look at the test case more closely:
```js
assert.deepEqual(telephoneCheck("(6505552368)"), false);
```

The number is wrapped inside brackets, which is *not* a valid form of writing phone numbers. It would have been valid if only the first three digits were wrapped in brackets, but in this case, the entire number is wrapped in brackets.

I am closing the issue because I believe that resolves your issue. Feel free to reopen if you feel it didn't (or need further clarification) :)

**Comment by plasticmacaroni** [comment]
I had a lot of trouble with this bonfire as well, because of `(6505552368)`. After reading this, it was apparent it should fail because it doesn't match one of the criteria, but it wasn't apparent to me or my program at the time :)
