### ISSUE TITLE
Allowed to Proceed with Incomplete Declaration

### ISSUE THREAD

**Issue by KillerDesigner** [FreeCodeCamp/FreeCodeCamp#3364]
Challenge [Waypoint: Use RGB to Color Elements White](http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-white) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: rgb(255, 255, 255)
  }
</style>

```

If we are teaching Best Coding Practices, campers should NOT be able to proceed without adding a semicolon at the end of the declaration, should they? I accidentally omitted it, but was allowed to proceed.

**Comment by bugron** [comment]
@KillerDesigner thanks for posting this issue!
Actually, in this case semicolon is not required because `background-color` is the last property in `body` so there is no need to terminate it. But it is a good practice to place semicolons after each property-key declaration. Answering to your question I think we should not impose campers to use optional things like this but one more time, of course, it is a good practice.
Closing this issue, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
