### ISSUE TITLE
Gives the correct result, but doesn't give a checkmark

### ISSUE THREAD

**Issue by Deeevo** [FreeCodeCamp/FreeCodeCamp#3366]
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:40.0) Gecko/20100101 Firefox/40.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function titleCase(str) {
  str = str.toLowerCase().replace(/((?=\b)([a-z])(?=[a-z]|'))|(\b[a]?)/g, function(firstLetter){
  return firstLetter.toUpperCase();
  });
  return str;
}

titleCase("I'm a little tea pot");
```

This code returns what the challenge asks for, yet it doesn't give a green checkmark for it.

**Comment by bugron** [comment]
@Deeevo thanks for pointing this out! I've submitted a PR.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by eldios** [comment]
+1 :)

**Comment by Deeevo** [comment]
This issue hasn't been resolved yet. I'm getting the same result and it's still not passing...

**Comment by awesomeaniruddh** [comment]
Deploying the staging code to production happens once every week or so.

**Comment by jero930** [comment]
Hi,

I have the same issue. 
Here is my code

text="";
function titleCase(str) {
  array = str.split(" ");
  for(i=0; i<array.length; i++){
    text += array[i].charAt(0).toUpperCase() 
           + array[i].substr(1,array[i].length-1).toLowerCase() 
           + " ";
   }
  return text.trim();
}

titleCase("sHoRt AnD sToUt");

**Comment by ltegman** [comment]
@jero930 Your code is failing the tests because you're using a global variable `text` in your function. It looks like it works because the first time you run the function it works as expected, but any time after that the function won't work as expected because the `text` variable is not empty. You should be initializing your variables in the function itself with a `var` keyword in front of it to avoid this problem.

Thanks and happy coding!

**Comment by carleyf1010** [comment]
I still can't sign in, when it seems me my passwords it's sent by a outlook account without the link active and I can't cut it, idk I'm tired of getting nowhere with this


Sent by Outlook for Android



From: Logan Tegman

Sent: Tuesday, October 27, 8:32 PM

Subject: Re: [FreeCodeCamp] Gives the correct result, but doesn't give a checkmark (#3366)

To: FreeCodeCamp/FreeCodeCamp



@jero930 Your code is failing the tests because you're using a global variable text in your function. It looks like it works because the first time you run the function it works as expected, but any time after that the function won't work as expected because the text variable is not empty. You should be initializing your variables in the function itself with a var keyword in front of it to avoid this problem.


Thanks and happy coding!

**Comment by jero930** [comment]
Hi Logan,

Thanks for the help!

Best,
Jerome

**Comment by ElD0C** [comment]
Well, I have a similar problem too.

My code:
```
function titleCase(str)
{
  str = str.toLowerCase().replace(/\b\S/g, function (m) {return m.toUpperCase();});
  str = str.replace(/'\S/g, function (n) {return n.toLowerCase();});
  return str;
}

titleCase("I'm a little tea pot");
```
I get the correct string, but I don't get the green checkmark. :(

**Comment by ltegman** [comment]
Looks like the PR that fixed this issue has been overwritten. I'm making a new PR for this now.
