### ISSUE TITLE
Issue with "Bonfire: Pairwise". Test wrong?

### ISSUE THREAD

**Issue by soulchainer** [FreeCodeCamp/FreeCodeCamp#3375]
I was going to do this bonfire, and, after a time thinking about how to do it, I noticed this test:

```js
expect(pairwise([0, 0, 0, 0, 1, 1], 1)).to.equal(10);
expected 1 to equal 10
```

That's arr[0] + arr[4] = 0+4 = 4
And arr[1] + arr[5] = 1 + 5 = 6
6 + 4 = 10

These are [0,1] pairs, **repeated**.

Well, the explanation of this bonfire says this:

> Bla bla bla
**If multiple sums are possible, return the smallest sum**. Once an element has been used, it cannot be reused to pair with another.

So, if you get the same pair, **Only use the smallest sum of indexes**, right?
This test breaks this condition. With this, I don't know if even I can trust in the exercise description. I don't know if the exercise is wrong, if the description is misleading or if only the test is wrong, but something seems to be wrong.

**Comment by natac13** [comment]
I believe I see what you are saying... where the first and 4th test are expecting the sum of all the indices that can be paired to add to the 2 param.  But if the description say to only return the smallest sum then test one `expect(pairwise([1, 4, 2, 3, 0, 5], 7)).to.equal(11)` should equal 4 (from the 4 and 3 being added) and the 4th test (the one you mentioned) should be 4?

**Comment by soulchainer** [comment]
No, @natac13 , because there arent repeated pairs. I mean. In the test I said, they get the pairs:
`[0, 1]` and `[0, 1]`. It's the same sum. So, you are supposed to only keep the smallest one sum of indexes for that specific combination of numbers that sums 1.
In case of test first, it's OK, because you have:
`[4, 3], [2, 5]` that have indexes `1 + 2 + 3 + 5` that equals to 11. That's fine. The case I mentioned, I believed not.

**Comment by natac13** [comment]
Fair enough I am just going of the if there are multiple sums then return the smallest sum... so because there are two different sum that equal 7 for the first test I though it should only return the sum of `[4, 3]` being index `1 + 3` to equal 4... I apologize for misunderstanding your inquire

**Comment by richchurcher** [comment]
@soulchainer I've often thought this exercise and its description caused more confusion than it was worth.

I believe the test is ok, though. It only says once an *element* has been used it can't be re-used... it doesn't say, once an *integer* has been used. It also asks for the sum of *all* indices that can be paired. The test provides multiple elements with the same value for the purpose of checking if the provided solution can detect the lowest possible combination. Possible answers include:

```js
[0, 0, 0, 0, 1, 1]
Indices: 0 + 4, 1 + 5 = 10
Indices: 1 + 4, 2 + 5 = 12
Indices: 2 + 4, 3 + 5 = 14
```

So the test is required to ensure that the solution has correctly picked the lowest sum.

**Comment by soulchainer** [comment]
Oh. I see. That makes sense, @richchurcher :).
Thanks. Description limits itself to the most simple cases and there you have no confusion, till you see the test cases.

**Comment by ltegman** [comment]
Closing this issue as resolved. Feel free to follow up if you still have concerns with this bonfire.

Thanks and happy coding!

**Comment by YannHulot** [comment]
Hi , I am sorry to reopen this issue but I am currently trying to find the solution of this bonfire and I am really confused. I am a bit relieved that I don't seem to be the only one but even after reading the previous messages, I still can't wrap my head around this problem. 

Why does test 1 return 11 ? 

```
Return the sum of all indices of elements of 'arr' that can be paired with one other element to form a sum that equals the value in the second argument 'arg'. If multiple sums are possible(Which sum are you talking about?), return the smallest sum. Once an element has been used, it cannot be reused to pair with another.

``` 
In the explanation above you are talking about sums but which one are you talking about? The sums of the indices of the elements or sums of the the elements of the array, both? I don't want to be nitpicking but, FreeCodeCamp is an international community and many campers picked up English as a second language. I have been living in an english speaking country for at least 4 years now and I have been told repeatedly that my english skills are quite good but even I got confused by this exercise.  If I got confused , then it is a bad sign because that means that all those people with lower English skills will struggle even more. 

Take the first example: 
( [ 1, 4, 2, 3, 0, 5], 7 )

In this case arr[1] + arr[3] = 7     sumIndices1 = 4
         and   arr[2] + arr[5] = 7      sumIndices2 = 7

If I follow the instructions correctly,  the test should return the smallest sum of indices from a pair. In this case it should be 4. Why does the solution ask us to add sumIndices1 and sumIndices2 . Nowhere in the description is it written that in case of multiple pairs  of elements , we should return the total sum of all the indices. 

I believe you should provide more examples and/or explain in better way how you are supposed to find the expected results. 

Thank You.

**Comment by diogogomeswww** [comment]
I don't understand.
The problem clearly says `If multiple pairs are possible that have the same numeric elements but different indexes, return the smallest sum of indexes.`

So for test case: 
`[0, 0, 0, 0, 1, 1]
Indexes: [0,4], [1,5]
Values: [0,1],[0,1]`

The indexes 1+5 should be not included, hence the answer should be 0+4 = 4, right?
