### ISSUE TITLE
Curriculum progress opening page

### ISSUE THREAD

**Issue by DoviMaj** [freeCodeCamp/freeCodeCamp#34236]
the curriculum page always opens the basic html section of the curriculum. shouldn't it open my recent track or at least the section im in?

Also would like to request a feature for the curriculum page: that be added a progress bar regarding the full curriculum as well as the current track in progress. and better navigation

**Comment by DoviMaj** [comment]
no one thinks this is important?

**Comment by coder077** [comment]
@raisedadead is it something that we should be concerned? If yes then I can take a look at it!

**Comment by hughforsyth** [comment]
@coder077 I would add that in 2015 when I last used FreeCodeCamp it did work how @DoviMaj is requesting, i.e., when you went to the curriculum page (or "Map" as it was then) it would expand the tree at the first incomplete lesson, so this is something that has broken/changed in the last few years.

I personally would like to see it working how it did in 2015 as I'm currently re-doing the certification based on the new curriculum and it was easier when FCC prompted you with what lesson you should do next, rather than showing you lessons you have already completed. I'm not suggesting it's worth investing 100s of man hours but it's probably worth a quick look as I suspect this is a simple bug rather than by design. It does remember where you are in the tree if you never refresh the page so perhaps there is a some sort of variable storing your place that is supposed to persist in a cookie or something.

**Comment by xolowapx** [comment]
@raisedadead Has anyone fixed it yet?

**Comment by raisedadead** [comment]
Nope this is available for and open for implementation, if you are interested.

**Comment by ojeytonwilliams** [comment]
I made some progress in https://github.com/freeCodeCamp/freeCodeCamp/pull/35421, but it's been a while since I looked at it.  I'll take another look and see if that PR is any use.

**Comment by brianRey2017** [comment]
I would like to help if you need it @ojeytonwilliams @raisedadead

**Comment by ojeytonwilliams** [comment]
Hey @brianRey2017, thanks for the offer!  I think the PR is basically okay, but there's one change I'm looking to make (handling the completion of an entire section of the curriculum).  I'll have a go at that this week and let you know if I run into difficulties.

**Comment by brianRey2017** [comment]
Ok. I'll be waiting here :smile:
