### ISSUE TITLE
Handle scrollTo event more gracefully for the guide navigation

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34285]
I was wondering if this could even be done or not, but can the whole system or the guide at least be ported over to make a react app. Right now it's really annoying having the page reload for everytime we click a link and then having to scroll back to that point in the menu to get to another place. It would surely take time and a lot of effort, but can this be done, if so, I think it should be done

**Comment by Bouncey** [comment]
@thecodingaviator The guide has always been made with react. It was built with `gatsby v0.*`. What the issue your seeing is a `scrollTo` event firing when the navigation is clicked.

It has been so long since I have worked on that set of components, I couldn't even guess where to look. It might be something we have implemented, or it could be coming from `gatsby-link`(which is now deprecated in favour of `import { Link } from 'gatsby'`)

**Comment by thecodingaviator** [comment]
I see. So what can we do about it right now, or should we leave this for the mean time till we can finish the Hacktoberfest PRs?

**Comment by thecodingaviator** [comment]
@Bouncey Then how can/should we proceed with this?

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, thanks for looking into this. Since it could be Gatsby Link that could be causing the issues, [these files](https://github.com/freeCodeCamp/freeCodeCamp/search?q=gatsby-link&unscoped_q=gatsby-link) and the docs [here](https://www.gatsbyjs.org/docs/gatsby-link/) might be good places to start.

**Comment by StephenHogsten** [comment]
@thecodingaviator I can look into fixing this if you're not planning on working on it

**Comment by QuincyLarson** [comment]
This is still a problem, and I believe fixing it would dramatically improve the usability of the guide. 

Here's a gif demoing the issue:

![2019-01-17 13 08 43](https://user-images.githubusercontent.com/985197/51297006-89ee0600-1a59-11e9-9e53-f676585d6b92.gif)

@StephenHogsten are you still interested in fixing this?

**Comment by StephenHogsten** [comment]
@QuincyLarson yes, I'll take a look
