### ISSUE TITLE
Tests for various challenges are too strict about whitespace around function arguments

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#34344]
## The problem
In the "[React and Redux: Moving Forward From Here](https://learn.freecodecamp.org/front-end-libraries/react-and-redux/moving-forward-from-here)" challenge, I tried the following code:
```js
console.log( 'Now I know React and Redux!' );
```

However, this code did not pass the tests. But if I simply remove the spaces, it passes:
```js
console.log('Now I know React and Redux!');
```

I think the tests for this challenge need to be less strict on spacing. Perhaps a partial minifier could be run on the code to remove excess whitespace within lines before making the test comparison?

**This same kind of issue also affects the following challenges:**
- ["Data Visualization with D3: Add Axes to a Visualization"](https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/add-axes-to-a-visualization): spaces are not allowed around `call` method.
```js
svg
      .append( 'g' )
      .attr(
        'transform',
        `translate(${padding}, 0)`
      )
      .call( yAxis );
```
- ["JSON APIs and Ajax: Get JSON with the JavaScript XMLHttpRequest Method"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method): spaces not allowed around `JSON.parse` arguments.
```js
const apiRequest = new XMLHttpRequest();
  apiRequest.open( 'GET', '/json/cats.json', true );
  apiRequest.send();
  apiRequest.onload = function() {
    const json = JSON.parse( apiRequest.responseText );
    document.getElementsByClassName( 'message' )[0].innerHTML = JSON.stringify( json );
  };
```

## Browser and OS info
* Browser Name: Firefox Developer Edition
* Browser Version: 66.0b5
* Operating System: Antergos Linux

**Comment by wmollenkopf** [comment]
I hope it was okay, but I went ahead and created a RegExp instead of a pure string compare for the assertion.

**Comment by nikrb** [comment]
@RandellDawson 
discuss: handling whitespace (and possibly capitalisation). Looking for comments from all mods.

It seems unreasonable to fail a challenge because of whitespace and free text capitalisation. The challenge addressed by this pr is to enter `console.log('Now I know React and Redux!');`. Should the user have extra spaces in function arguments, text or mis-capitalise text, the challenge should still pass. 

suggestions so far include:
create helper functions in the application layer to remove whitespace, remove whitespace and lowercase.
create new vars alongside `code` like, `codeNoSpaces`, `codeNoSpacesLowered`

This seems more manageable/readable than removing whitespace in the `testString`'s themselves and circumvents regular expressions sprinkled with copious `\s*`'s.

I have looked into this and can create a pr to show the general idea if required.

**Comment by RandellDawson** [comment]
@nikrb I think if we are going to use regular expressions to test a challenge in this way, then as far as the code goes, I think removing the whitespace in all parts of the testString are fine.   I think the exception to that would be if we are looking for a specific string to be rendered (per instructions) within the users code.  For example, if we were expecting a user to specifically display a specify string to the console like `Hello World", then we should not strip the space between `Hello` and `World`, because that was the intent of the instructions.  I also think it promotes a better attention to details, which is extremely important when you are first learning a language.  I believe our goal is to make our instructions clear and concise and design tests which best validate the user has followed the instructions.

This is why I think the second suggestion of using something like codeNoSpacesLowered would be a mistake.  JavaScript is a case-sensitive language, so we want users to make sure they are writing `forEach` instead of `FOREACH` or `foreach` or anything else if we are expecting the user to implement a `forEach` in their code.

The main issue brought up by the OP is strictly focues on whitespace in code function calls like allowing the following:
```
console.log( "Hello World" );
```
I have no issues with allowing the above to work as it is valid JavaScript.  In many challenges, we could definitely use If you can design a globally available function like stripWhiteSpace when a challenge does not expect spacing in the console display or within an element displayed in the client.  If you can create such a global function, I believe that would be useful as long as we are careful on which challenge we use it for.

**Comment by nikrb** [comment]
@RandellDawson yes I have to agree ... got carried away trying to trim down the `testString`'s. I'll have a think about a global stripWhiteSpace function.
