### ISSUE TITLE
Challenge (Hazards of Imperative Code) passes after running tests without any changes made to the code

### ISSUE THREAD

**Issue by nemanjajeremic** [freeCodeCamp/freeCodeCamp#34394]
**Describe your problem and how to reproduce it:**
After "Run the tests" is clicked, challenge is marked as completed and you can proceed to the next challenge. This happens even without making changes to the original code, meaning it happens with incorrect output.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/understand-the-hazards-of-using-imperative-code/

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 63.0.3
* Operating System:  Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by drecali** [comment]
The problem is with the tests. There are effectively no actual tests being run on the code. Here is what I found in the challenge [code:](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/understand-the-hazards-of-using-imperative-code.english.md)

## Tests
<section id='tests'>

```yml
tests:
  - text: Move ahead to understand the error.
    testString: '' # assert(true, 'Move ahead to understand the error.');

```
</section>

The page linked above has a commit that is titled [test(curriculum): test suites must fail on the initial contents](https://github.com/freeCodeCamp/freeCodeCamp/commit/0aa6881508e6c53c1e8a7d74f9bba5d3dd58e8f1). However, the test passes regardless of the code in the editor. I think a proper test needs to be written, so the correct output is needed to pass the challenge. Alternatively, if the challenge intentionally doesn't need to be solved, I think the explanation should be a bit clearer. The difference between the expected output and the seed code's actual output is easily missed. It would be helpful to refer to the actual difference between the outputs so students can think about the potential cause.

By the way, @nemanjajeremic has an outstanding PR https://github.com/freeCodeCamp/freeCodeCamp/pull/34364 It's well explained an easy to follow, with helpful examples and alternative solution. Thanks for taking the time to do it!

**Comment by ojeytonwilliams** [comment]
@drecali It is a bit of an anomaly to have a challenge that always passes!  I'll add a PR that encourages campers to find a way to fix `newTab()`.
