### ISSUE TITLE
Silent failure on forgetting that strings in JS are immutable

### ISSUE THREAD

**Issue by matkoniecz** [freeCodeCamp/freeCodeCamp#34435]
**Describe the bug**

JS interpreter crashes on attempting to modify string. It would be more helpful to show error message in the console.

**To Reproduce**
1. Go to for example https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/reverse-a-string
2. In code area replace code with
```
let test = "ABFC";
console.log("before");
test[0]="A";
console.log("after");
```

**Expected behavior**

I would expect something like "attempted to modify immutable string object" in the output of console, rather than a silent failure

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Lubuntu 16.04
 - Browser Firefox 63.0.3 (64-bit)

**Additional context**

**Comment by ezioda004** [comment]
Hi @matkoniecz,

Thank you for opening this issue. The ECMAScript specification doesnt throw error if you try to mutate primitive values, therefore none of the browsers (implementer of the the spec) throws an error if you try to mutate the String or any other primitive type.

If you try the following code in the browser:
```
let test = "ABFC";
test[0] = "E";
```
You'll see that the last assignment returns "E", giving the impression that string has been mutated whereas in reality it hasnt been mutated.

We're simply sticking to the language spec, which IMO is completely fine, because if we didnt campers will get confused with different behavior.

Hope this resolves your issue. Closing this.
Feel free to reopen if you think this issue hasnt been resolved.

Happy coding.

**Comment by matkoniecz** [comment]
> Feel free to reopen

Note that on GitHub people are unable to reopen issues closed by maintainers :)

> The ECMAScript specification doesnt throw error

Is it explicitly requiring a silent failure?

I still think that it would be better to give error message noting that this type of error would cause program to silently crash, but I understand why it was fine this way.

**Comment by matkoniecz** [comment]
Maybe the proper solution would be to add strict mode to the initial code?

It is a good practise, especially for people learning as it seems to give much better error reporting without loss of any reasonable functionality.

**Comment by ezioda004** [comment]
@matkoniecz I suppose its possible to add `use strict` to the challenges, we do have strict mode in some challenges. Maybe others can chime on this.

Reopening the issue.

**Comment by matkoniecz** [comment]
If no-one protests I will start making PRs adding strict mode.

**Comment by ezioda004** [comment]
I'd suggest not doing that until a proper discussion happens. This probably was suggested before too and if they didnt add that, then there might a reason.

Lets wait for the core members.

cc @Bouncey @raisedadead

**Comment by Bouncey** [comment]
Sorry, I though I had replied already.

`'use strict` is not required to throw an error here. We run all the code through `babel` and `babel` does this for us. The results of which can be seen in the `output` window under the editor

![image](https://user-images.githubusercontent.com/18572518/49227501-23495600-f3e1-11e8-8b4f-528cb3e2b37c.png)


If we need to make this clearer some how, I would gladly listen to suggestions.

**Comment by Bouncey** [comment]
Using that code in my browser console 

FireFox:
```js
"use strict";
let test = "ABFC";
console.log("before");
test[0]="A";
console.log("after");
// TypeError: 0 is read-only[Learn More]
```

Chrome:
```js
"use strict";
let test = "ABFC";
console.log("before");
test[0]="A";
console.log("after");

// before
// Uncaught TypeError: Cannot assign to read only property '0' of string 'ABFC' at <anonymous>:4:8
```

The `TypeErrors` are what you are seeing in the output panel below the editor. All we do is copy the error message and display it in the output window. 

Is there anywhere else we can display this or increase the visibility in some way that makes sense from a UI/UX standpoint?

> And adding `"use strict";` is not changing anything from what I see in my testing

This is because it is already there, in the background, as we run all code through `babel` in the browser to enable the use of the latest language features.

**Comment by matkoniecz** [comment]
> The TypeErrors are what you are seeing in the output panel below the editor.

Only on clicking "Run the tests" button, rerunning code after edit is not displaying them.

> Is there anywhere else we can display this or increase the visibility in some way that makes sense from a UI/UX standpoint?

Show this type of error also after user edited text in code text area.

**Comment by moT01** [comment]
Looks like some recent modifications to the console output now display an error in these cases...
<img width="522" alt="Screen Shot 2019-12-16 at 10 56 32 AM" src="https://user-images.githubusercontent.com/20648924/70926443-bfe19480-1ff2-11ea-8dd6-5ef9d4a3d880.png">

So it's probably safe to close this.
