### ISSUE TITLE
Create a guide of the freeCodeCamp codebase?

### ISSUE THREAD

**Issue by lmilliken** [freeCodeCamp/freeCodeCamp#34438]
As someone who is looking to start contributing to to freeCodeCamp, I'm really curious about how this is all deployed.   Looking through the folders, I can kind of see how they map to particular sections of the fcc website but feel like I'm still missing the larger picture.

It would be great if someone produced an article or video on how exactly this is all boostrapped (is this the right word?).  I would envision something like a "tour" of each of the main folders and how they are deployed; for example: what exactly happens when someone goes to guide.freecodecamp.org (how does the app know which page/language to display?)

Let me know if there already resources for this.

**Comment by matkoniecz** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md#help-us-fix-bugs-in-freecodecamporgs-learning-platform has some basic info.

**Comment by thecodingaviator** [comment]
@lmilliken I would say that you take up this topic in the Gitter Contributor's chat room

**Comment by Bouncey** [comment]
@lmilliken this is something that has been on the roadmap for a while. A large contributing factor to it not happening yet is the fact that this codebase has changed completely, twice, in the past 12 months. 

Once we have things settled down considerably, we can revisit this.

**Comment by raisedadead** [comment]
> ...codebase has changed completely, twice...

I count more than that.

**Comment by moT01** [comment]
How about adding a readme to each folder? Or at least the main ones

**Comment by thecodingaviator** [comment]
@freeCodeCamp/moderators since we moved out the guide, our repo has been very simple IMHO. Do we still need this?

**Comment by moT01** [comment]
I'm still in favor of adding a readme to some/many of the folders - I think that could be beneficial. The repo is easier to deal with, but still has a lot of folders that people don't know the purpose of (myself included).

**Comment by ahmadabdolsaheb** [comment]
It seems that there are some confusion regarding some of our main subdirectories and what they do and adding  readme files could be beneficial.

Would you like to lead the effort? @moT01

**Comment by raisedadead** [comment]
The markdown linting rules should be enforced only on the `/curriculum` directory. 

Coming to the documentation. I think the nicer approach is to keep things in the `/docs` vs the main directories. This is because its ever changing. Also IMHO, it will not be possible to maintain every detail.

IMHO, what we really need instead of the docs is to simplify the code structure. The client for instance can be organised way better than it is.

A lot of the implementation cruft can be refactored and go away.

Code IMHO, should self explain it self. Micro functions with dedicated responsibilities. Well named components (long names are fine, `logo` vs `freeCodeCampNavLogo`, etc), and finally implementing DRY as much as we can.

**Comment by ojeytonwilliams** [comment]
I've looked into this a bit more and I think we can ditch the `h1` requirement for anything that's displayed on Github, because the readme is already beneath an `h2`.  `h2` or `h3` should be fine for the top-level headings in those files. 

I'll get on with a PR to change that, so you should be able to create what you want.

@raisedadead they are restricted to `/curriculum` when you run `npm run lint`, but not when you commit.  Husky checks everything.  Arguably it *shouldn't*, but that's how I set it up.

**Comment by raisedadead** [comment]
> Husky checks everything. Arguably it shouldn't, but that's how I set it up.

Oh. Thanks for clarifying, we should then remove that requirement (or modify it to be only for curriculum)

**Comment by moT01** [comment]
I agree that code should explain itself when possible, but it's tough sometimes - and it simply doesn't always happen.

If it's not clear - I was thinking to put a readme in each folder with a small overview of what's in the folder. 

And you're thinking a single readme overview in the docs folder instead @raisedadead?

I think either way works; I think my way might be a little more functional in that you would be able to see what's in the folder when you click on it so it's right there in front of you. But I suppose then there isn't one place to get a good overview of the repo.

**Comment by ojeytonwilliams** [comment]
> Oh. Thanks for clarifying, we should then remove that requirement (or modify it to be only for curriculum)

I think it could make sense to lint both the curriculum and the other markdown, but with different rules (since the curriculum md is a bit odd).  For now, I'll just restrict it to the curriculum to lower the amount of pain it's causing.
