### ISSUE TITLE
Merge Set Challenges

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#34492]
Currently, we have 3 challenges for creating Set Class and its methods:
1. [Create a Set Class](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-set-class/)
2. [Remove a Set Class](https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-from-a-set)
3. [Size of the Set](https://learn.freecodecamp.org/coding-interview-prep/data-structures/size-of-the-set/)

The last 2 challenges have only couple of lines of challenge text/instructions and don't feel like "challenges".

I propose we merge the last 2 challenge with the Create a Set Class challenge. 
This will be following the structure of other Data Structure challenges we already have.

**Comment by raisedadead** [comment]
Yes, that is ideal. We want to err on the side of keeping challenges to be about 2 minutes, but we do not want too much redundancy that gets annoying.

**Comment by abhishekakade** [comment]
Can I work on this issue?

**Comment by raisedadead** [comment]
@abhishekakade All yours. Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

**Comment by JoelLau** [comment]
if it isn't done, yet, I would like to help with this!

also, @raisedadead, the link you posted seems to be broken

**Comment by abhishekakade** [comment]
Sorry, I was unable to complete this due to some unforeseen circumstances. I can get it done by this weekend if that's fine.

**Comment by ezioda004** [comment]
@abhishekakade No worries, try to do it by the weekend else @JoelLau can work on this.

@JoelLau Heres the link to [Contributing guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).

**Comment by JoelLau** [comment]
@abhishekakade no worries dude, was just looking for something to contribute to, it's all yours

**Comment by scissorsneedfoodtoo** [comment]
@ezioda004, I'm actually thinking that it would be better to keep these as separate challenges. It's true that there's some similarity in the descriptions of each problem, but the approach for each is quite different. I worry that if we combine them that completing the challenges would take much more than two minutes. That being said, I could see changing the descriptions or adding additional tests so that they feel more substantial.

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo I understand your concern. We have challenges such as [this](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-queue-class) one in which we are asking camper to create 5 different methods (with different approaches). This one after merging will have the camper create only 3 methods (similar to the linked challenge). 

>if we combine them that completing the challenges would take much more than two minutes. 

That's true. However, all the coding interview prep challenges will take anyone more than 2 mins and a decent amount of time. IMO, its a good thing. The coding interview questions are usually about solving questions efficiently rather that solving them fast.
So far each challenge in this section deals with isolated concepts. Only Set challenges have been stretched out to 6 challenges, which stands out to be odd.

**Comment by scissorsneedfoodtoo** [comment]
@ezioda004, I'm very sorry, I didn't look at the section these challenges are in! You're right, for these challenges in the coding interview section it is strange that they're split up like this. My mistake--for some reason I thought they were in the earlier JavaScript Algorithms and Data Structures section.

In that case, the way that you're proposing we merge them makes sense. So it would be create, remove, and size first in one challenge, then union, intersection, difference, and subset in a second challenge? That sounds like a good way to split them up rather than having one massive challenge where the user has to write seven different methods.

When the groups of challenges are combined this way, what are you thinking for the seed file? Right now it makes sense that each seed file builds off the other so the last challenge has a bunch of code already in it. When we make these changes, are you thinking that it would be better to start off with a relatively empty seed like the one in [Create a Set Class](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-set-class/)?

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo 
>So it would be create, remove, and size first in one challenge, then union, intersection, difference, and subset in a second challenge? 

Yes, exactly.
>When the groups of challenges are combined this way, what are you thinking for the seed file?

Yeah, we can go with the empty file as in the challenge you linked. Then in the next one (union, intersection, diff) we could build the seed for `add`, `remove` etc methods.

**Comment by scissorsneedfoodtoo** [comment]
@ezioda004, that sounds great! Looking forward to reviewing it later.

**Comment by abhishekakade** [comment]
I'm really sorry for the delay.
