### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.map()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3450]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by natac13** [comment]
I would like to tackle this today.

**Comment by BerkeleyTrue** [comment]
@natac13 Thanks!

**Comment by natac13** [comment]
I came up with a question... for the examples I write should they continue to be in ES5 syntax or would it be advisable to use ES6?

**Comment by BerkeleyTrue** [comment]
Either both or only ES5.

**Comment by natac13** [comment]
no problem! Almost complete.

**Comment by natac13** [comment]
@BerkeleyTrue So bad luck for myself or poor searching... this wiki seems to be complete already [Here}(https://github.com/freecodecamp/freecodecamp/wiki/js-array-prototype-map). Should I submit what I have written since I just finished so the community can see both...?

**Comment by natac13** [comment]
# Array.prototype.map()

### Overview
`.map()` will call a function for every element in the array and uses the returned value from that function to build a **new** array. The word new is important since `.map()` will not mutate(change/modify) the original array. 

Another way to think of `.map()` is a `for` loop which builds a new array based of the length of the original array.

```js
var ogArray = [1, 2, 3, 4],
    newArray = [];

function addTwo(num) {
    if(typeof num === 'number') {
        return num + 2;
    }
}
/*** Below is what is equivalent to .map() ***/
for(var i = 0, len = ogArray.length; i < len; i++) {
    var val = addTwo(ogArray[i]);
    newArray.push(val);
}

/*** .map() version of above code ***/
var reallyNewArray = ogArray.map(addTwo);

/*** Sanity check ***/
console.log('original array: ' + ogArray);
console.log('new array from for loop: ' + newArray);
console.log('really new array from map function: ' + reallyNewArray);
```

If you run the above code you will see that the `for` loop and `.map()` will create new arrays by using the `addTwo()` function. If you wish to see this happen step by step check this [visualizer](http://www.pythontutor.com/javascript.html#mode=edit) out.

### Parameters `.map(callback[, thisArg])`

#### Callback 

The function which will be called for each element in the array. This function takes 3 arguments, *current value*, *index*, *array*. This function's declaration does not need to include the `index` and `array` parameters; will get explained more by reading through the examples.

**Current value** - is the current element of the array that `.map()` is iterating(looping) over.

**index** - the index number of the current element of the array.

**array** - the array `.map()` was called upon.

#### thisArg

Optional argument. If passed in will act as the *this* value of the callback function; if nothing is passed then `undefined` is used

```js
var objectForThisValue = {
    a: 2
}

var arr = [1, 2, 3, 4];
function addTwo(currentValue, index, array) {
    return this.a + currentValue;
}
/*** map over array passing in a value for this ***/
var newArray = arr.map(addTwo, objectForThisValue);
```

### More Examples
Through out these examples you will see that the callback function passed to `.map()` can have all 3 parameters or the first 2 `currentValue` and `index` or really only the first one `currentValue` if that is all you need for your functionality.

##### Changing vowels to uppercase!
```js
var vowels = ['a', 'e', 'i', 'o', 'u'];
var normalString = 'Hello Free Code Campers!';

var arrayifedString = normalString.split('');

var uppercasedArray = arrayifedString.map(function(char) {
        // check if the character is in the vowels array
        if(~vowels.indexOf(char)) {
            return char.toUpperCase()
        } 
        return char.toLowerCase();
    });
// change the new array back to a string
var modedString = uppercasedArray.join('');
console.log(modedString);
```

##### Working with objects in an array
```js
var people = [
{
    name: "Sean Campbell",
    username: "natac13",
    github: "http://github.com/natac13",
    twitter: "http://twitter.com/natac1311"
},
{
    name: "Berkeley Martinez",
    username: "BerkeleyTrue",
    github: "http://github.com/BerkeleyTrue",
    twitter: "http://twitter.com/BerkeleyTrue"
},
{
    name: "Quincy Larson",
    username: "QuincyLarson",
    github: "http://github.com/QuincyLarson",
    twitter: "http://twitter.com/FreeCodeCamp"
}
];

var modedPeople = people.map(function(person) {
        // return new object
        return {
            firstName: person.name.split(' ')[0],
            lastName: person.name.split(' ')[1],
            githubURL: person.github
        }
    });
console.log(modedPeople);
```

##### BlankOut every other word of a sentence
```js
var sentence = 'I do hope you find this guide helpful! It you have anything to add feel free to make this Wiki better!';

var censored = sentence.split(' ').map(function(word, index) {
    if(index % 2 === 0) {
        return '****'
    }
    return word;
    }).join(' '); // turn array back to string
console.log(censored);
```

### Notes:
Although `.map()` does not mutate the array, the callback function can. However any element pushed to the original array will not be included in the `.map()` iteration(loop). However if an element gets changed before `.map()` iterates over it then the updated value is used. Deleted element will not be passed to the callback if deleted prior to becoming the current value. 
If you wish to see more on it can be found at the end of the description section of the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

#### Contributors
If you found this helpful please paste the following in gitter chat.
```
thanks @natac13
```
Add your username if you helped with this wiki!

**Comment by bugron** [comment]
Closing this issue. See https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/js-Array-prototype-map.
