### ISSUE TITLE
JS: Comparison with Equality operator / test case not returning false in console

### ISSUE THREAD

**Issue by jeremyfiel** [freeCodeCamp/freeCodeCamp#34507]
**Describe your problem and how to reproduce it:**

console output should return "Not Equal" but return value is not displayed during test case.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 70.0.3538.110
* Operating System: win 7 64 ent

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/32110157/49334760-59d2cc80-f5ab-11e8-836d-f645ba4d09ce.png)

![image](https://user-images.githubusercontent.com/32110157/49334745-3740b380-f5ab-11e8-9b40-21942de5982d.png)

**Comment by thecodingaviator** [comment]
The tests don't need to show in console.log , they are on our internal side, you may close this PR if you've been answered

**Comment by Nirajn2311** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding

**Comment by anup-thunder** [comment]
its not working now
