### ISSUE TITLE
Information Security and Quality Assurance Projects - Metric-Imperial Converter : example app not functioning

### ISSUE THREAD

**Issue by C-Hg** [freeCodeCamp/freeCodeCamp#34504]
**Describe your problem and how to reproduce it:**
The example app (hard-twilight) is not working properly, neither with Firefox nor with Chrome. Instead I get an explorer with the public source files.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter
Direct link to the app: 
https://hard-twilight.glitch.me/

**Tell us about your browser and operating system:**
* Browser Name: Firefox and Brave
* Browser Version: latest
* Operating System: Ubuntu 18.04
![challenge](https://user-images.githubusercontent.com/30982918/49329742-216bc800-f584-11e8-9e43-b72cabbf8496.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by doubleUTF** [comment]
I submitted a PR last October [#23953](https://github.com/freeCodeCamp/freeCodeCamp/pull/23953) which basically replaces the broken URL with a working one implemented by myself. FCC refused to merge it since its not under their direct control and they haven't offered any suggestions on how to properly address this. If submitting another URL is off the table, then contributors would need access to the original project to do anything about it. @RandellDawson please let us know how we can fix this broken link that's been going on for over 6 months!

**Comment by N0bl3** [comment]
It looks like this section of the FCC curriculum is abandoned... I write this just to put this post into light once again.

**Comment by doubleUTF** [comment]
@N0bl3 I tried everything I could to get this project up and running, but they didn't give a damn about my contributions and inquiries. Why bother?

**Comment by RandellDawson** [comment]
@N0bl3 Your PR has been merged, but until master is deployed to production, we are just waiting like you.  As soon as it is deployed, hundreds of fixes that many of us have merged will fix many bugs currently in production.  I understand it is frustrating, but there are some other pressing issues which the core team is working.  Once those are resolved, they will work to fix some final issues which are keeping us from deploying master to production.

https://www.freecodecamp.org/forum/t/quick-update-on-beta-master-deployment/272119

**Comment by RandellDawson** [comment]
> I tried everything I could to get this project up and running

@doubleUTF Are you having trouble setting up FCC locally?  If so, the best place to ask your question(s) would be the in the [Contributors Gitter channel](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by doubleUTF** [comment]
@RandellDawson No, read my comment on Mar 6 please.

**Comment by RandellDawson** [comment]
@doubleUTF Got it.  @raisedadead How can incorporate the code from the  glitch project referenced in PR #23953 to one that FCC controls?

**Comment by cmccormack** [comment]
@RandellDawson I think a single repo for all the Glitch projects is a great idea.  I just performed a test in Glitch and you can specify a directory within a repo to import using the syntax `username/repository:path`.

**Comment by RandellDawson** [comment]
@cmccormack OK, then I will first start mapping out which Glitch projects are actually in the camperbot account and which ones are missing.  I will create a separate issue where we can track what needs to be done.

**Comment by raisedadead** [comment]
Sure, thanks a lot for figuring out the workflow. If needed I can give you: @RandellDawson and @cmccormack access to our Glitch account for taking this up amongst yourselves? Let me know here and we can discuss further over a call early next week.

**Comment by KaustubhD** [comment]
In the meantime, is there a link to a backup of that project ?

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo can you update this Glitch project when you get a chance.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I can't update the broken Glitch project because it's not one of ours, but I'd be happy to help with the transfer over to the camperbot account.

@RandellDawson, here's a list of projects in the camperbot Glitch account:

- shard-weed (API Header Parser boilerplate)
- fern-freeze (Backend Challenges boilerplate - package.json)
- prairie-waterfall (Exercise Tracker REST API)
- actually-bison (Back-end Infosec & Helmet.js boilerplate)
- trite-organ (Back-end Mongo & Mongoose boilerplate)
- purple-paladin (API file metadata solution)
- season-puffin (Manage Node.js projects and npm packages using package.json)
- roasted-season (API file metadata boilerplate)
- sincere-cone (Back-end QA mocha-chai boilerplate)
- nonstop-pond (Exercise Tracker solution)
- thread-paper (API URL shortener solution)
- fcc-weather-api-1-1
- wind-bow (FCC Twitch API pass-through)
- curse-arrow (FCC Timestamp API solution)
- dandelion-roar (API Header Parser solution)
- storm-leopard (Backend npm - package.json boilerplate)
- wild-song (Full-stack Pinterest clone solution)
- chrome-delivery (Trade books with other users)
- flicker-hill (ClementineJS boilerplate)
- evening-bane (API Image search solution)
- grove-voice (A P2P Video Chat based on WebRTC)
- shimmer-ripper (FCC Timestamp API Boilerplate)
- pastoral-caution (API URL Shortener boilerplate)
- fertile-pixie (Back-end Basic Express boilerplate)
- shell-swallow (Full-stack Book Club solution)
- glen-neck (Full-stack Stocks solution)
- cream-ape (Full-stack Nightlife solution)
- ballistic-swallow (Full-stack Voting solution)

And here are the ones I'm unsure about:
- rail-lettuce
- gentle-trowel
- sweet-hook
- zest-blizzard

**Comment by doubleUTF** [comment]
@scissorsneedfoodtoo No Github repo , but Glitch exposes a link to clone: [https://api.glitch.com/git/languid-pen](https://api.glitch.com/git/languid-pen). You can run command 'git clone https://api.glitch.com/git/languid-pen' to pull it into local repo.

**Comment by scissorsneedfoodtoo** [comment]
@doubleUTF, awesome, thank you! Since it's a solution I just mirrored your project to the camperbot Glitch account for now. Here's the new link: https://incongruous-beard.glitch.me/

Would you be able to update the link in #23953 to the URL above? Or please feel free to open up a fresh PR with the new link.

**Comment by doubleUTF** [comment]
@scissorsneedfoodtoo Updated New Glitch URL in #23953.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for pointing that out! Yes, it would be good to correct that. I'll update the project in the fCC account now.

**Comment by doubleUTF** [comment]
@scissorsneedfoodtoo Great, thanks for helping resolve this longstanding issue!

**Comment by scissorsneedfoodtoo** [comment]
@doubleUTF not at all, thank you for all of your help with this. Sorry it took us some time to get to it -- we're still recovering from Hacktober fest last year! 

And I didn't do much, I just happened to have the login info to help in this case. There would still be thousands of PRs if not for @RandellDawson, @cmccormack, and others, so they deserve the thanks more than anyone.

**Comment by doubleUTF** [comment]
@RandellDawson @cmccormack Thanks for your assistance, let me know if anything else is required.
