### ISSUE TITLE
Issues with the hint of basic algorithm scripting (Truncate  a String).

### ISSUE THREAD

**Issue by sammychinedu2ky** [freeCodeCamp/freeCodeCamp#34708]
In the hint of this javascript challenge, the hints give the solution of replacing the last three strings of a truncated string with "..." instead of adding "..." to the truncated string.

**Comment by MGenteluci** [comment]
@sammychinedu2ky Are you going to submit a PR for this issue?

**Comment by sammychinedu2ky** [comment]
Please where can I submit it?

**Comment by MGenteluci** [comment]
In pull requests, just create one referencing this issue and the owners of the repo are going to review it.

**Comment by thecodingaviator** [comment]
@sammychinedu2ky Please tell on which link is the problem?

**Comment by sammychinedu2ky** [comment]
@thecodingaviator It's here https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string
But Please I would like to learn how to do it

**Comment by sammychinedu2ky** [comment]
Thanks man... I didn't see how to change the hint.. I'm only the challenge

**Comment by BrandonWingerAir** [comment]
It's still currently incorrect as the solution doesn't work and uses another requirement. This is the correct code if anyone needs it or knows where I could submit it. 

if (str.length > num) {
    return str.slice(0, num) + '...';
} else {
    return str;
}

**Comment by RandellDawson** [comment]
I am closing this issue, because PR #34228 has fixed the issue on the `master` branch and we are just waiting on the changes to be moved to production. You can view the [current file here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/index.md).  

If you do not believe the current `master` version of the file mentioned fixes this issue, please respond back with more information.

Thank you.
