### ISSUE TITLE
[Suggestion] Add a percentage so we could be aware of progress

### ISSUE THREAD

**Issue by glennvill** [freeCodeCamp/freeCodeCamp#34707]
Add percentage somewhere in the page so we could be aware if we're near the completion of the topic/certification

**Comment by DoviMaj** [comment]
Yes, yes, yes

**Comment by mawalicoder** [comment]
Maybe somewhere as mentioned in the image!!!!
![55d1b1c3f5fa5aea3c043dc0a0d0725861c5aee8](https://user-images.githubusercontent.com/26973191/53045249-20777200-34b3-11e9-85f4-70ea4490f9ce.png)

**Comment by DoviMaj** [comment]
That's a good idea!

**Comment by ahmadabdolsaheb** [comment]
it would be challenging to assign a percentage since some topics specially the projects take much longer than others. I believe the screenshot is from the production website, since we currently have a way to show progress in the  master branch.

<img width="729" alt="screen shot 2019-02-19 at 11 48 48 pm" src="https://user-images.githubusercontent.com/4591597/53046447-1b112c00-34a1-11e9-8b02-950331cce378.png">

**Comment by mawalicoder** [comment]
Close it then!!!!

**Comment by moT01** [comment]
The image above is going to be added to production - I think this satisfies your concern of not knowing how much progress you made and have left @glennvill. Thanks for the suggestion! Adding a percent as well will just add clutter and possible confusion.
