### ISSUE TITLE
Restrict Possible Username: wrong solution

### ISSUE THREAD

**Issue by ugitch** [freeCodeCamp/freeCodeCamp#34760]
**Describe your problem and how to reproduce it:**
Solution to this challenge doesn't take into account that:
- Three-or-more-character usernames with a single alphabet letter character at the beginning are obviously the solution as well.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Ubuntu Mate 16.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ugitch** [comment]
I suggest this solution:
`/^[a-z]{2,}\d*$|(?=\w{3,})^[a-z]{1,}\d+$/i`

Obviously, my solution uses positive lookahead (studied few challenges forward in the curriculum).

**Comment by icatat** [comment]
@ugitch  If my understanding is correct, from this description: "1) The only numbers in the username have to be at the end. There can be zero or more of them at the end." it sounds like you cannot mix letters and digits together. So if you have 3 or more letters, but only 1 at the beginning, that means that the rest have to be mixed with other numbers, and this is the reason is not covered in the solution.
The fact that your solution passes, could be an issue in the test cases maybe. What do you think?
I am willing to fix this once we can decide whether the description & solutions are wrong, or the test cases.

**Comment by ugitch** [comment]
@icatat I mistakenly wrote letter instead of character in _three-or-more-character_. I corrected it. You can check my solution in a website like regexr with the examples of usernames. Thanks for showing interest!

**Comment by moT01** [comment]
This challenge was recently updated. The solution added to the challenge file...
```
let username = "JackOfAllTrades";
const userCheck = /^[a-z]([0-9]{2,}|[a-z]+\d*)$/i;
let result = userCheck.test(username);
```
This can be put in the guide.
