### ISSUE TITLE
Search box in Learn's navbar is offset on retina displays

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#34887]
**Describe the bug**

On retina displays, this is what Learn's search navbar looks like on retina displays (2012 and beyond Macbooks):

<img width="1064" alt="welcome_to_learn_freecodecamp_" src="https://user-images.githubusercontent.com/985197/51297128-0e408900-1a5a-11e9-9bdc-74a10a606c3a.png">

Note that the Guide's navbar looks fine on Retina displays:

<img width="1222" alt="freecodecamp_guide" src="https://user-images.githubusercontent.com/985197/51297166-2e704800-1a5a-11e9-92ed-40730ae5e0ca.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Yes - the navbar still looks slightly offset on my retina display when running locally:

<img width="1187" alt="welcome_to_learn_freecodecamp_" src="https://user-images.githubusercontent.com/985197/51844209-a63e4c80-234f-11e9-9676-6461dfa8db21.png">

The search field is way too wide, too, though that probably deserves a separate issue 😉

**Comment by ahmadabdolsaheb** [comment]
Hi @scissorsneedfoodtoo, Thanks for working on this. Please let me know when you have the PR ready so we could review and merge it ASAP.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, sorry for the delay with this! Been flying a bit blind since I don't have a Retina screen device of my own. Ended up using some kiosk MacBooks and playing with the CSS in the browser. Could only test with Safari, but I suspect that this is caused by the search bar having an undefined height.

I'm just about to submit a PR, so could you and @ahmadabdolsaheb check it out when you can?
