### ISSUE TITLE
Iterate with JavaScript Do…While Loops

### ISSUE THREAD

**Issue by geekysmurf123** [freeCodeCamp/freeCodeCamp#35110]
**Describe your problem and how to reproduce it:**
The description of the problem and the solution that passes are not the same.  The code that passes this section would give you the wrong answer to the instructions.  write the proper code for the instructions and it will not pass.  try it.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

**Tell us about your browser and operating system:**
* Browser Name: CHROME
* Browser Version: Version 71.0.3578.98
* Operating System: OSX

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Can you be more specific?  For example, what code passes the challenge which you think goes against the instructions?

**Comment by Fordco** [comment]
I just came up with this solution based on the instructions and passed the test cases. 

![image](https://user-images.githubusercontent.com/21327614/52512282-0fd11d00-2bd2-11e9-829f-5fdf7bc76e47.png)

After thinking about it more I can see how the instructions might be misleading. The following code pushes the number 10 to myArray, and i will be equal to 11 when the code finishes running, but the array equals [5, 6, 7, 8, 9, 10]. It might be less confusing if the instructions said 
"Change the ```while``` loop in the code to a ```do...while``` loop so that the loop will push _only_ the number 10 to ```myArray```, and `i` will be equal to `11` when your code finishes running.
![image](https://user-images.githubusercontent.com/21327614/52512380-81a96680-2bd2-11e9-86a3-076c82613c73.png)

**Comment by geekysmurf123** [comment]
the first pic is the way i tried it first and it wouldn't pass.  i got it
to pass changing the while:

} while (i < 5);

that should not have passed.

i also had a few connection issues with that one.  like i clicked on run
test and the page would lockup.
i would close my browser, reopen it, go to your page, click on curriculum,
and it gave me a 404 error message
a few times.

Have a great day!

Jeremiah Kalb

**Comment by RandellDawson** [comment]
@geekysmurf123 The code `while (i < 5)` should definitely pass the tests, because you just need the loop to iterate one time.  So, the while loop condition should evaluate to `false` in the first iteration (which it does with that code).

@Fordco If you start with the original seeded code, `i` is `10` and not `5`, so it is not going to add other numbers anyway.  That being said, the wording change you suggest might not be a bad idea.  Would you be interested in creating a PR for this change you suggest?

**Comment by Fordco** [comment]
@RandellDawson I would love to do that.

**Comment by RandellDawson** [comment]
@Fordco How's your PR coming along?

**Comment by Fordco** [comment]
@RandellDawson  I'm pretty sure I finished with it. Is there anything else I need to do with it? The correct PR is #35214

**Comment by Craigmindset** [comment]
this how i got mine to pass

// Setup
const myArray = [];
let i = 10;

// Only change code below this line
do {
myArray.push(i);
i++;
} while (1 < 0);
