### ISSUE TITLE
Freezes Chrome...

### ISSUE THREAD

**Issue by MindfulBell** [FreeCodeCamp/FreeCodeCamp#3524]
Challenge [Bonfire: Sum All Odd Fibonacci Numbers](http://freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers#) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have to submit this in IE because my chrome page keeps crashing and I am not clicking on "RUN" or anything. Whenever I load this challenge, it just freezes Chrome. Here is what I have entered from Chrome (I don't see an infinite loop, but even if there was one, I am not running it...)

```
var fibArray = [];
for (I=0; I<num; I++) {
fibArray.push(I + (I-1))
}
return  fibArray;
}
```

**Comment by bugron** [comment]
Hello @MindfulBell. Actually your code is incorrect because your `num` variable is not defined. Also you don't check if your current Fibonacci number is odd. And one more thing, you return an array of Fibonacci numbers but need to return the sum of that numbers.
Closing this issue. Please, post this in our [Gitter chat room](https://gitter.im/FreeCodeCamp/Help), thanks.

**Comment by MindfulBell** [comment]
I don't have it front of me (on phone) but I thought num was passed through
the function...

That wasn't my submission for the code that was just an example of it not
working. I know I returned an array and didn't check for oddness.

Thanks

**Comment by MindfulBell** [comment]
I'll put all the code in next time. I am sure I made a simple mistake

**Comment by SanjeetSk** [comment]
I am also getting same issue. Yes my code is incorrect but that should not freeze entire window. I am not able to change my code now.
