### ISSUE TITLE
several html guide pages have nothing in them

### ISSUE THREAD

**Issue by TheFinalDawn** [freeCodeCamp/freeCodeCamp#35328]
**Describe your problem and how to reproduce it:**
Half of the guide doesn't exist.
Open it.
**Add a Link to the page with the problem:**
**[This whole section.](https://guide.freecodecamp.org/certifications/responsive-web-design/applied-visual-design/)**
https://guide.freecodecamp.org/certifications/data-visualization
etc. etc. Basically 50% of the guide doesn't exist.

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 72.0.3626.109
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![dear-god-why](https://user-images.githubusercontent.com/45810243/53176159-58111780-35a2-11e9-9307-5e26c2545729.PNG)
(Almost) everything pops up like that.

**Comment by RandellDawson** [comment]
I am closing this issue, because this is known already and is part of the whole open source strategy here at Free Code Camp.  If you would like to add new content, you can visit the [master branch on GitHub](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications/data-visualization) for this particular section and add content to any article you feel would benefit the article.

To get started, visit the [How to work on Guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md) documentation.  If you need help, visit us in the [Contributors Room](https://gitter.im/FreeCodeCamp/Contributors) on Giiter.

**Comment by raisedadead** [comment]
Have you read through the links in there?
