### ISSUE TITLE
Variable names improvement. ES6 Higher order arrow functions

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/freeCodeCamp#35337]
In [the guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/index.md) for the [ES6: Write higher order functions ](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/) we used the same `const` name (`squaredIntegers`) in two different scopes (inside and outside the function), they work well but might be confusing for some users. 
I first thought it was because we didn't realized it when creating the code solutions but there is a 
 ` return squaredIntegers;` statement below the  ` // change code above this line` so it kind of forces one to use it.
Should we change the guides and the ` // change code above this line` placement or leave it as is?

**Comment by Manish-Giri** [comment]
I don't think it is confusing as such, especially because two earlier ES6 lessons ([Compare Scopes of the var and let Keywords](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords/) and [Explore Differences Between the var and let Keywords](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords/)) do mention the changes introduced with block scoping using `let`. This challenge (Higher Order Arrow Functitons) is a good example for campers to see how block scoping works correctly, in a different exercise.

That said, it is also true that the two earlier lessons didn't explcitiy mention `const` with regards to block scoping, and the next challenge on [Explore Differences Between the var and let Keywords](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword/) just explains the constant/immutable nature of `const` variables. Maybe a note could be added here mentioning the block-scoping feature of `const`, like so -

> `let` is not the only new way to declare variables. In ES6, you can also declare variables using the `const` keyword.

> `const` has all the awesome features that `let` has, like block-scoping - 
       `// an example to show block scope here`

>  The added bonus of using `const` is that variables declared using `const` are read-only. They are a constant value, which means that once a variable is assigned with `const`, it cannot be reassigned.

Just my 2 cents. I'll let others chime in.
