### ISSUE TITLE
Looking for reviewers for C/C++ implementations of selection-sort algorithm

### ISSUE THREAD

**Issue by cmccormack** [freeCodeCamp/freeCodeCamp#35391]
Looking for anyone proficient with C/C++ to review the imperative and declarative implementations of the `selection-sort` algorithm in [`/guide/english/algorithms/sorting-algorithms/selection-sort/index.md`](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/algorithms/sorting-algorithms/selection-sort/index.md).

Ideally, any person reading the guide should be able to copy this code into a file or site like repl.it and be able to compile and run the code as-is - perhaps adding a `main` function and a test array would help make this work and help users understand better.

@RandellDawson @Manish-Giri please add any additional comments/concerns you would like addressed as well.

**Comment by Manish-Giri** [comment]
I already have a repl.it link that I made to test the recursive selection sort implementation snippet added in that file by a PR. This link has the working code with a test array and output logs. 

I'll make a PR with the code I have. Since the iterative implementation just provides the body of the `for` loop, I think I can create a function for the iterative version, and make my "main" call this too, thereby demonstrating both approaches.
