### ISSUE TITLE
Falsy Bouncer not passing

### ISSUE THREAD

**Issue by HanniAbu** [FreeCodeCamp/FreeCodeCamp#3540]
Challenge Bonfire: [Falsy Bouncer](http://freecodecamp.com/challenges/bonfire-falsy-bouncer) has an issue.

My code:
```
function bouncer(arr) {
  var arr1 = [];
  for (i = 0; i < arr.length; i++) {
    if (arr[i] !== false && arr[i] !== "" && arr[i] !== 0 && arr[i] !== null && arr[i] !== undefined && arr[i] !== NaN) {
      arr1 = arr1.concat(arr[i]);
    }
  }
  return arr1;
}

bouncer([false, null, 0], "");

// should return []
```
My code doesn't pass, but I've tested with Chrome dev tools and it checks out.

**Comment by abdulhannanali** [comment]
The last test case is returning [NaN] instead of [] for you and that's because when you check for NaN funny thing is NaN !== NaN will be true because NaN === NaN is false . Check for yourself in Console.
So for check if the element is NaN use a built in JavaScript function called isNaN() instead of the above mentioned comparison...

**Comment by abdulhannanali** [comment]
Also, You don't have to make explicit comparisons such as arr[i] !== false (instead use !arr[i]). Also 0 == false is true so you don't want to make an explicit comparison here too so is true for "" (empty string). The only extra comparison you want to make is for NaN.. Also, consider using Array.filter...

**Comment by HanniAbu** [comment]
Thank you for that clarification
