### ISSUE TITLE
Update video for challenge: introduction to html5 elements

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#35437]
I think the video for this challenge should be updated.
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/introduction-to-html5-elements/

It does not show the proper nesting of both the p elements inside the main element. It also has one error as one of the p elements are not closed properly.
https://scrimba.com/c/c4Ep9Am

**Comment by RandellDawson** [comment]
@beaucarnes Any comments?

**Comment by barrykeegan** [comment]
Agreed with lasjorg,

In this exercise a new paragraph should be added below the first, with a main tag then added to wrap around both paragraphs.

In the video, the main tag is added around the newly added second paragraph only, plus the newly added paragraph has an opening p tag at the end instead of a closing p tag.

For contrast, the very next video has the main and paragraph tags the way they should be. Discovered this error when my daughter ran into difficulty with this exercise, and when she watched the video became even more confused.

**Comment by RandellDawson** [comment]
@beaucarnes Any thoughts?

**Comment by beaucarnes** [comment]
I will redo that video.
