### ISSUE TITLE
We should remove remove repl.it, codepen.io, and other external online code testers from the Guide's certifications folder

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35479]
This was discussed recently in the Gitter chat, but I could not find an issue created for it.  

I did a search in the `guide/english/certifications` folder and found 79 files which have links to replt and 7 files which have links to codepen.io.  I did a search for jsfiddle.net, but did not find any files.

Since people can delete the sessions and pens anytime, the links can break easily.  Also, as mentioned by @Bouncey, there really is no need to have these kind of links in the guide (which can become outdated if the challenge changes), because the user can just copy the solution from the Guide article and paste it directly in the challenge editor to see that it works.

@Bouncey Would you like me to create a PR to remove all of these links and their associated text?   Since they all have the same pattern, they are easy to find and delete with a simple regular expression in my code editor.

An example of one such a link is:
```
![:rocket:](https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:") <a href='https://codepen.io/dylantyates/pen/wxwxRd' target='_blank' rel='nofollow'>Run Code</a>
```

**Note:** Actually, we may consider expanding this to all Guide articles, because the same issue arises when a repl.it session or pen is removed by the user.

**Comment by Nitin96Bisht** [comment]
@RandellDawson You are right, we should remove all external links since It may lead to 404 error in the future for many reasons. However, there might be a situation where one would like to take the reference just for understanding the concept. If we remove all references then It may be difficult for one to understand the concept clearly. Possibilities are:

- We can provide a shared link which does not require any codepen or repl account, it will not lead to 404 error.

- We can strict for one to copy and paste solution directly. (i.e. No Ctrl+C and Ctrl+V).

Kindly let me know your views on it. Otherwise I can start from one of the language guide to remove all external links and their associated text.

**Comment by RandellDawson** [comment]
@Nitin96Bisht I was not proposing to remove all external links, but instead remove links to the code testing sites such as repl.it and codepen.io.  I personally do not think we should make it any easier for someone to copy and paste a solution.  The solution will be there and if they want type it out or copy/paste, that will be up to the user.

I am not understanding what you mean by the following:
> We can provide a shared link which does not require any codepen or repl account, it will not lead to 404 error.

**Comment by Nitin96Bisht** [comment]
@RandellDawson I meant to say that We can provide shared link of codepen.io or repl.it that are not associated with any account. However I think you are right, Yes we should remove all codepen.io or repl.it links .

Anyways Let me know, I can start working on one of the language guide to remove all such links and their associated text.

**Comment by Manish-Giri** [comment]
@Nitin96Bisht I believe Randell already has a regex (for certification guides) in place, that he can customize to target these links in all guide articles.

**Comment by RandellDawson** [comment]
@Nitin96Bisht Like @Manish-Giri mentioned, I have a way of targeting and replacing these already.  I created the issue to get feedback.  I want to wait until a core-team member gives the official OK on this issue, before moving forward.   The core team members are very busy right now, so it may be a few days before we get a response.  I will take care of creating the PR if that is OK with you.

**Comment by Nitin96Bisht** [comment]
@RandellDawson It is fine. 👍

**Comment by AdrianSkar** [comment]
Hi all! Newb's 2 cents if it may help. 
I come from this [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/28510) because I included a link without knowing it was going to stop being allowed. Maybe we should remove references to it on the [style guide for creating and editing guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#images). 
On the other hand, as I'm currently learning using this guides too, I often see myself using repl.it, codepen or local editors and you're right in that we can copy and paste the solutions but that makes it a bit harder for one to play with code (specially those of us who are not used to it) and I wonder if we could implement a similar playground/console we find on the exercises but on the guide pages so it gets easier. 
Or even just something like the examples you find on [stackoverflow](https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable-in-jav) where you display and run them only if you want to.

**Comment by RandellDawson** [comment]
@AdrianSkar Based on the new direction as it pertains to the curriculum in general, I doubt your idea of a console playground will be made.  It is an interesting idea, but since the current editor already is designed and a simple copy/paste accomplishes the same thing, it would be a whole lot of extra work to build out such a feature with very little gain.

**Comment by RandellDawson** [comment]
@Bouncey , @raisedadead I have created a branch in my fork which I believe removes all repl.it and codepen.io links from curriculum-related Guide articles.  Just awaiting confirmation this is still OK, before creating the PR related to these changes

**Comment by RandellDawson** [comment]
@raisedadead I have not created the PR, but have made the changes on a branch.  Just need to know if I should go ahead and make the official PR to remove these from the Guide's certifications folder.  We could also do something similar for all Guide articles to prevent linking to code which no longer exists.

**Comment by raisedadead** [comment]
Yes, please go ahead with the PR. Thanks for your work on this.

**Comment by thecodingaviator** [comment]
All PRs pertaining to this issue have been merged we now need to decide whether to discuss removal of all such links on this issue or another one. My opinion is that we should remove all `repl.it`,`codepen.io`, etc. links from the guide

**Comment by RandellDawson** [comment]
@thecodingaviator Can you create a new issue and reference this one for your idea and close this issue?

Thanks.
