### ISSUE TITLE
Remove instructions from glitch/github boilerplates?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35541]
On a number of the backend style sections - the instructions are written on the challenges themselves, and in the glitch/github boilerplate. As modifications get made to the descriptions in the challenges, they slowly diverge from the instructions in the boilerplate. I propose removing the instructions from the boilerplate so the only place instructions exist are on the website. And what should remain in the boilerplate is simply the title to the challenge, similar to [this boilerplate](https://github.com/freeCodeCamp/boilerplate-express/blob/gomix/myApp.js) - and maybe a note about doing the challenges in order when that's needed + maybe a little introduction or something. This really isn't a big deal right now - I think the instructions are similar enough that a camper will figure it out, but it would simplify things a little bit.

**Comment by ojeytonwilliams** [comment]
I just encountered this when looking into #37770.  Any further thoughts on this @moT01?  I found myself having to look up the tests in the source while trying to pass the tests for https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.  This was because I was working from the boilerplate, not the example project.

**Comment by moT01** [comment]
Not really, I made my suggestion - I thought that it would be better to have the instructions on the website - because without them, the pages would be empty.

**Comment by moT01** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/35541
