### ISSUE TITLE
Can't View Certificates even though I accepted Academic Privacy Policy

### ISSUE THREAD

**Issue by devparth** [freeCodeCamp/freeCodeCamp#35559]
**Describe your problem and how to reproduce it:**
I am trying to claim my certificate, but the certificate is not showing instead the one message shows like
"parthchaudhary has not yet agreed to our Academic Honesty Pledge."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/parthchaudhary

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 72.0.3626.121 (Official Build) (64-bit)
* Operating System: Windows 10 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/48122273/54106978-dcb2c100-43fd-11e9-9cb7-b35662754bb2.png)
![FCC-issue](https://user-images.githubusercontent.com/48122273/54107031-01a73400-43fe-11e9-809b-3b774f9446f7.png)

**Comment by ahmadabdolsaheb** [comment]
@devparth Thank you for reporting this issue. While we are working resolve the issue, you can view your certificate by signing out and visiting your portfolio's link or visiting the following link.
https://www.freecodecamp.org/certification/parthchaudhary/responsive-web-design

**Comment by MahmoudAFawzy** [comment]
@ahmadabdolsaheb I have the same issue what should I do?

**Comment by raisedadead** [comment]
@devparth @MahmoudAFawzy please drop me an email: <code>mrugesh  at  freecodecamp  dot  org</code> from your registered email id with the username

**Comment by nikrb** [comment]
unable to reproduce, linux/chromium

**Comment by ahmadabdolsaheb** [comment]
@devparth, this is caused by having duplicate accounts and we are working to merge your accounts ASAP. In the meantime, to help us resolve this issue completely I was wondering if you could knidly tell us the actions you took that you suspect resulted in having duplicate accounts. Your input is very valuable as it allows us to reproduce this issue, fix it, and prevent other campers from facing the same problem.

**Comment by devparth** [comment]
Hi,
Yes I am also confused about it, but maybe I forgot my password or
something, so i try to login but maybe when i created the account i used my
GIT to login and when this problem happen, so i singed out and try to login
again but i forgot to use my GIT account and instead of GIT account i
selected the "CONTINUE WITH GOOGLE" and when i logged in everything was
reset.

**Comment by ahmadabdolsaheb** [comment]
Thank you @devparth.

**Comment by MahmoudAFawzy** [comment]
I used my github mail in both of my accounts so they got connected some how but I tried deleting one of my accounts and everything went perfect and I got my certificate

**Comment by irasanchez** [comment]
I am also having this issue.

**Comment by irasanchez** [comment]
> https://www.freecodecamp.org/certification/{username}/responsive-web-design
Side note: this solution did not work for me.

**Comment by jimmychu0807** [comment]
@ahmadabdolsaheb Hi, I have the same issue as well. 

My freeCodeCamp user handle is: `@jimmychu0807` , or the link here: https://www.freecodecamp.org/jimmychu0807

I think the possible reason of duplicate account is because I use gmail feature of `username+suffix@gmail.com` to register. Let me know if this is the case, or any further info you need to debug this issue.

Thanks!

**Comment by raisedadead** [comment]
Please drop us an email: <code>support@freecodecamp.org</code> from your registered email id with the username. This is most likely due to duplicate accounts.
