### ISSUE TITLE
Add "Compare Bonfire Solutions" Button to Profile Page

### ISSUE THREAD

**Issue by ChillTrain** [FreeCodeCamp/freecodecamp#356]
Discussed this with @terakilobyte.  The feature would works as so:

- "Compare Bonfire Solutions" button would be added to the profile page
- What a user clicks that button, a modal comes up with a list of bonfire names that the user viewing the profile and that user whose profile is being displayed have both solved (this prevents cheating)
- When the user clicks on a bonfire name, the prettified solution written by the user in the profile is displayed

I'll be submitting a PR eventually...

**Comment by QuincyLarson** [comment]
If people want to cheat, they'll figure out a way to cheat. There's no reason to obscure people's solutions. This would remove the benefit to prospective employers and other non-campers of being able to see a camper's code.

**Comment by ChillTrain** [comment]
If that's the case, is there still value in the "Compare Bonfire solutions" button at all or should we just prettify the Bonfire answers as they are currently displayed on the profile page?

**Comment by terakilobyte** [comment]
I believe there is still value in having a compare bonfire solutions
button.  We save **every** bonfire solution a  user makes. Rather than
clutter up the profile with repeat solves, having a button that brings up a
modal with the names of challenges, then clicking on a challenge name will
show a list of solutions would create a better flow.

**Comment by terakilobyte** [comment]
@chilltrain How is the progress coming on this?

**Comment by ChillTrain** [comment]
@terakilobyte Having some trouble figuring out a way to display all the solutions for one Bonfire together...

**Comment by terakilobyte** [comment]
Ok, let me know if you want some help.

**Comment by phoenixstormcrow** [comment]
After going through the Dev Tools waypoint, I was able to come up with a fix for issue #332 that requires minimal change to the css. Since that issue is closed, I'm not sure what the etiquette is to fix that issue. My fix does not address the broader changes discussed above, but would not conflict with them, being only the addition of a single css rule.

**Comment by ChillTrain** [comment]
I'm going to let someone else have a shot at this.  Sorry to disappoint.

**Comment by BerkeleyTrue** [comment]
closing as stale. Reopen if you feel like taking this on again.
