### ISSUE TITLE
[rocks] inadequate test for declare javascript variables challenge

### ISSUE THREAD

**Issue by nikrb** [freeCodeCamp/freeCodeCamp#35617]
**Describe your problem and how to reproduce it:**
The challenge requires declaration of a variable. There is a comment `Declare myName below this line` but the var can be declared anywhere

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-javascript-variables

**Tell us about your browser and operating system:**
* Browser Name: chromium
* Browser Version: 68.0.3440.106
* Operating System: Ubuntu 16.04.5 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Since the intent of this challenge is to get the user to declare a variable named `myName` and since it really does not matter where (in the global scope) a variable is declared with `var`, I don't see any problem with the current tests or that anything really needs to be changed.  If anything needs to be changed, I would say remove the comment.

**Comment by nikrb** [comment]
yep remove the comment was my thought aswell,
