### ISSUE TITLE
Challenge is mixing protocols in a possibly confusing way

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#35642]
Challenge: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements/

This challenge is mixing the http and https protocols in a possibly confusing way.

All the example links shown in the challenge text is using https, but the challenge test requires the use of http. The challenge text should show the same protocol as the test. The challenge test can also just allow for both protocols, or it should at least test for the same protocol as shown in the challenge text.

**Comment by ArielLeslie** [comment]
The example `href` is a different reference than the one required by the challenge. It's a different protocol, domain, and top-level name. Looking at the actual required string from the instructions, as opposed to the example, is something that campers have to do frequently.

**Comment by lasjorg** [comment]
@ArielLeslie You're not wrong of course.

However, I have seen people make this mistake enough times to believe the protocol is causing issues. I think it's a subtle thing that happens quite subconsciously from looking at the challenge links. The domain and top-level name are different enough that people do not seem to mistake them the same way.

In any case, I don't really see the harm in making the test accept both protocols.

**Comment by RandellDawson** [comment]
@lasjorg I am leaning towards not watering down the possible solutions here.  At some point the campers have to learn how to follow instructions.  Attention to the details is important in software development.  Changing the tests to allow more flexibility for valid syntax is one thing, but changing the tests to account for people not following the instructions is a whole different matter.

**Comment by ArielLeslie** [comment]
About as often as people fail this test because they use the wrong `href`, I see people fail tests because they return "Go home!" instead of "Go Home!" in the golf code exercise or set a color to "grey" instead of "gray" or have spaces at the beginning or end of a string. I'd argue that it's important to learn to look for these errors early, because typos will haunt them throughout their lives as programmers.

**Comment by lasjorg** [comment]
I do agree that paying attention to details is an important skill to learn early on. I just can't help but think that the difference in the protocol here is unintentional. It just feels like an oversight. Anyway, it's not that important I was just thinking it would spare us a few forum posts if we made all the links use the same protocol.

@ArielLeslie Learning to follow requirements is vital but when making a challenge we need to account for hard requirements and soft requirements.

Using a different spelling for the color gray in CSS is a soft requirement. In all likelihood, this requirement is simply the person writing the test not accounting for all valid syntax. This should not become a hard requirement by accident. In my opinion, it should not fail the test.

All challenges are on a case by case, but there are plenty of challenges which can fail for what I would consider the wrong reason. The problem is the assertion message can be confusing and often do not guide the user to the correct solution as well as they should.

**Comment by moT01** [comment]
I can see both arguments here. But the instructions do explicitly say to use the `http` version so there shouldn't be much confusion. I went through maybe two dozen posts on the forum and found one where the `s` was the deciding factor for finishing the challenge. There were others that used the `s`, but had much bigger problems than that.

Since two people are leaning towards leaving it as is. I am going to agree with them. Thanks for opening the issue but the consensus is that this really isn't a problem. It's good to struggle a little. Feel free to reopen it and continue making your case if you want.

For further emphasis, when I actually go to https://freecatphotoapp.com, it doesn't load from security risk issues.
