### ISSUE TITLE
For the Bonfire exercises, there should be a display for the location of where a bug occurs

### ISSUE THREAD

**Issue by mels065** [FreeCodeCamp/FreeCodeCamp#3566]
It would make debugging code so much easier. Sometimes, I might accidentally leave a symbol in my code that will cause an error to occur, but I have no idea where the bug is originating.

Having the Bonfire show you where an error occurred would help a lot.

**Comment by SaintPeter** [comment]
It is not technically possible to programmatically determine where a bug is occurring.  The best we can do is to tell you if your syntax is wrong or if your code doesn't pass the tests.  In that regards, we ARE sort of telling you where the bug is.

You can try using tools like http://repl.it - it has a built in "linter" which will check your syntax for you.  It will highlight lines which are syntactically incorrect.

Note that a program that could tell you where your bug was would effectively be an AI.  I've love that, but it's one of those 50+ year out things.

You should close this bug as being impossible with current technology.
