### ISSUE TITLE
Reducing duplicate forum posts

### ISSUE THREAD

**Issue by kirubiel** [freeCodeCamp/freeCodeCamp#35708]
When users click the "Ask for Help" button on any challenge, it should take them to a related questions page first so that they can scroll through questions asked before them. After that they can decide whether to ask a question or not. I think it would reduce the number of similar posts on the forum instead of expecting them to "Read-Search-Ask" which most new campers don't do.

**Comment by raisedadead** [comment]
Do you mean something along the lines of a URL like this:

[`https://www.freecodecamp.org/forum/search?q=Say%20Hello%20to%20HTML%20Elements`](https://www.freecodecamp.org/forum/search?q=Say%20Hello%20to%20HTML%20Elements)

If yes, this would be a button in itself?

**Comment by kirubiel** [comment]
Yes something like that with a couple of differences.

1. There is would be no search bar since the only thing they want to see is the topics related to the challenge they're on.
2. It wouldn't be an exhaustive search result. Either paginated or a limited number of topics related to this.
3. No it would not be a button by itself. It would be the next thing that the camper would see after clicking the "Ask for Help" button.
4. They will have the option of posting a new topic via a button in the page if they find that it didn't help them find a solution.

**Comment by raisedadead** [comment]
What you are saying may not be trivial to implement. This is because the topics are all on the forum which is a discourse instance, the code for which really do not control. We have very limited control over the customization of the UI.

We can point to a URL from a button, and what shows up there is really for discourse to take care of.

I think we should discuss the approach with the forum mods on the forum itself. I am going to close this issue here for now until we have a more concrete path ahead.

We can always comeback and reopen this.
