### ISSUE TITLE
Move font-awesome challenges to Font Awesome 5.x.x

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35714]
The challenges:

* [Add Font Awesome Icons to our Buttons](https://www.freecodecamp.rocks/learn/front-end-libraries/bootstrap/add-font-awesome-icons-to-our-buttons) , and,
* [Add Font Awesome Icons to all of our Buttons](https://www.freecodecamp.rocks/learn/front-end-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons)

Still teach Font Awesome v4.5.0. Although there's nothing wrong with teaching the older version, I personally feel that since it is just 2 challenges, we should update them to the latest version

**Comment by Nirajn2311** [comment]
@thecodingaviator These challenges are in the Bootstrap curriculum(even that is the old version). I had opened an issue before #34815 to update the Bootstrap curriculum and had also started updating it but due to exams I could only update one challenge. If you want you can take up and continue from there or we can pair up and do it.

**Comment by wang1998tina** [comment]
@Nirajn2311 I'd love to help out on this issue if you're busy!

**Comment by thecodingaviator** [comment]
@Nirajn2311 I'm pretty busy myself right now with other parts, so please go ahead and take it up. If you and @wang1998tina want to pair up, that's fine too :)

**Comment by wang1998tina** [comment]
Cool - I'll get started on the first challenge! @Nirajn2311 let me know if you'd like to pair up :)

**Comment by Nirajn2311** [comment]
@wang1998tina I'll be out of town till 20th April so won't be able to do anything until then. Keep us posted on the progress.
