### ISSUE TITLE
Logo positioning incorrect on the Search pages

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35716]
On the [search](https://search.freecodecamp.org/?) page and all query variations of it, the fCC logo is improperly aligned like this:

![image](https://user-images.githubusercontent.com/34807532/55274185-96b19480-52fb-11e9-8c02-a5079abcc9a9.png)

**Comment by Suyash2810** [comment]
The div tag with class as "nav-logo" has not been given the alignment. 

![align](https://user-images.githubusercontent.com/42000949/55292955-45de9080-540e-11e9-9e28-41c96695211f.png)

**Comment by scissorsneedfoodtoo** [comment]
Seems like it's [this](https://github.com/freeCodeCamp/search-assets/blob/f66d54dc75204cb8f0021f6734c92323adee2578/www/src/layouts/index.css#L231) line in the search-assets repo that's pushing up the nav-logo.

@Bouncey started the process of porting over the search bar and its assets in https://github.com/freeCodeCamp/freeCodeCamp/pull/35540 and https://github.com/freeCodeCamp/freeCodeCamp/pull/35458, so the styling can be fixed once those are merged into the main repo.

**Comment by QuincyLarson** [comment]
As always, thanks for reporting this, @thecodingaviator. We don't need this search page any more, so I'm closing this.

**Comment by raisedadead** [comment]
Hi @QuincyLarson we would still be using this search page (the index will be different). This is the react version of the page. The one that you have in mind (the new one on news) is going away.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I believe this was solved by an earlier PR. This is how it looks running fCC locally:

![image](https://user-images.githubusercontent.com/2051070/62099217-4dcd1500-b2c8-11e9-8b30-4c161cc8806b.png)

**Comment by raisedadead** [comment]
Great, thanks for confirming.

**Comment by victoriahchang** [comment]
@raisedadead If this search page is being used, this issue still persists.

The bug is due to the previously mentioned line in `layout.css` for `margin-bottom`: https://github.com/freeCodeCamp/freeCodeCamp/blob/af1071c5185d15b178b31dbec6f9b219d7bf6c85/client/src/components/layouts/layout.css#L212

In console, `margin-bottom: -6px` vertically aligns the logo but using negative pixels isn't a clean solution. Perhaps we could add a specific class to target the logo style?

<img width="1200" alt="Screen Shot 2019-07-31 at 3 35 14 PM" src="https://user-images.githubusercontent.com/16747397/62260245-ffde0d00-b3ac-11e9-899c-db528fb3b5c5.png">

**Comment by scissorsneedfoodtoo** [comment]
Hi @victoriahchang thanks for reporting this. Yes, this is still a problem on the live site as shown by your screenshot. However, this should be fixed when running fCC locally, and won't be a problem once master is pushed to production. Could you try running fCC locally and see if this is still an issue on your machine?
