### ISSUE TITLE
Add Images to Your Website | Passes with a missing quotation

### ISSUE THREAD

**Issue by Dave-Melia** [freeCodeCamp/freeCodeCamp#35768]
**Describe your problem and how to reproduce it:**
A missing quotation mark within img src allows the challenge to pass, even though it's incorrect and the image doesn't display.

For example:
`<img src="https://bit.ly/fcc-relaxing-cat alt="Author standing on a beach with two thumbs up.">`

notice I've not got a quotation mark after the cat image and before the alt text.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-images-to-your-website

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.86
* Operating System: MacOS Mojave 10.14.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
Confirmed that this is still an issue on beta.
The img src is valid without any quotes
Also, the alt attribute doesn't need to include any text.
These all pass...
`<img src=https://bit.ly/fcc-relaxing-cat alt="">`
`<img src=https://bit.ly/fcc-relaxing-cat alt=">"`
`<img src===https://bit.ly/fcc-relaxing-cat alt=">"`


[This is the file where this needs to be fixed](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.english.md)

**Comment by RandellDawson** [comment]
> The img src is valid without any quotes

This is technically not a problem.  Attribute values do not have to have quotes around them.  It is advisable, because if there are any spaces in them, this can cause unexpected results.

I created a PR which still allows the `src` to not have quotes, but we may decide we want to not allow `src` without quotes, just to make it more consistent with the test I created for the `alt` attribute.  The tests do not handle all edge cases, but they handle the OP's and the 2nd and 3rd of @moT01's above.
