### ISSUE TITLE
Create a media query challenge may fail

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#35785]
Challenge: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/

I have seen issues with this challenge on the forum a number of times.

The [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md) is using the computed properties but because you can set a minimum font size in the browser this may not work. In Chrome, you can use `chrome://settings/fonts` and set the minimum font size to be greater than 10px. If you then run the test it will fail.

Changing the test to use a regex instead might be better.

I'm not sure if this proposed change will fix all problem cases but it will at least take care of any minimum font size set in the browser. It should likely also fix any browser compatibility issues. I say that because this is one of the challenges where switching browsers often seem to help people pass the test.

**Comment by aditijoshi14** [comment]
@lasjorg Can I look at this issue?

**Comment by aditijoshi14** [comment]
@RandellDawson @lasjorg 

I also want to point out that the following code passes even if it's incorrect because the way we test right now. 

<img width="642" alt="Screen Shot 2019-04-08 at 2 22 18 PM" src="https://user-images.githubusercontent.com/23132028/55748070-b9cef900-5a0b-11e9-86d6-9dd68320b729.png">

**Comment by aditijoshi14** [comment]
@RandellDawson @lasjorg

I also want to point out that the following code passes even if it's incorrect because the way we test right now.

<img width="565" alt="Screen Shot 2019-04-08 at 2 36 36 PM" src="https://user-images.githubusercontent.com/23132028/55748181-f995e080-5a0b-11e9-84e5-572ece867904.png">

**Comment by RandellDawson** [comment]
I think one possible solution (avoid regex) is just have the original style section as:
```
<style>
  p {
    font-size: 30px;
  }
  
  /* Add media query below */
  
</style>
```
and then have the camper change the font-size to 20px or 25px with the media query.  The main reason people change this setting to something greater than 10px, is because the resolution on many screens is higher than it used to be, so 10px seems "small".

**Comment by RandellDawson** [comment]
@aditijoshi14 That is true.  This will involve changing the tests.

**Comment by aditijoshi14** [comment]
@RandellDawson That makes sense.  Chaing the size will surely fix the original issue.  Also, yes we do have to change the test for fixing the issue I pointed out above. Can I work fixing both of these issues? Also, do you want me to make a different new issue for the problem I pointed out or is it okay to have PR under this issue?

**Comment by RandellDawson** [comment]
Actually, the more I think about this, we can not just look at the computed value regardless of the font-size we are looking for, because we don't have a way of mocking the user's screen height.  We really need something like puppeteer to simulate the screen height at below and above 800px to validate the correct size is used.  

I guess we are stuck with using regex for both tests.  I suggest we also add a new test which validates the normal font-size for p elements is 20px, so the user does not change the seed code.  Then, I suggest we rearrange the tests, so the current second test becomes the first.  There is no need to modify the test below because we just want to make sure they are using a media query of any kind and this test does validate that.  The second test (currently the first test) is where we will need to make sure the media query is used and that the font-size will be 10px when the height is less than or equal to 800px.

This means the new second test's regex will be very similar to the first test's regex, but it will validate the ```
 p {
  font-size: 10px;
}
```
exists inside the media query definition.  

@aditijoshi14 Go ahead and take a shot at the tests using what I have described above.  Also, go ahead and remove the assert message arguments from the `testString`s, as they are no longer needed.

**Comment by aditijoshi14** [comment]
@RandellDawson Thank you so much for providing me detail information on things that I should get started with. 

It is good that we no longer need message argument from the testString as it was just repetitive. 

I will get started with this.

**Comment by aditijoshi14** [comment]
@RandellDawson 
Here is the order of the test:
1. Checking media query is declared right or not (currently the second test)
2. Checking font-size is set to 10px or not for screen size lower than 800px using media queries. (using regex). 
3. Checking the normal font-size for p elements is 20px. 

For number 3, I can only think of a regex solution. Because if we keep the following test, it might not always pass as it depends on the browser's screen size. 
```$('p').css('font-size') == '20px' ```
Should I just proceed with regex for the 3rd test as well?

**Comment by RandellDawson** [comment]
To check number 3 above, you should strip out any media query (regex with a replace) and then validate that you find:
```
  p {
    font-size: 20px;
  }
```

**Comment by aditijoshi14** [comment]
That sounds like a valid test. I will work on it and push a PR.
