### ISSUE TITLE
console.log spelled incorrectly

### ISSUE THREAD

**Issue by darrinlallen** [freeCodeCamp/freeCodeCamp#35853]
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/

console.log spelled wrong at bottom of link above

Reassign properties using deconstruction.
var basicOjb = {x: 40};
//To reassign 'get the value of the x property of basicObj and place its value into bigX' in ES6:
const { x: bigX } = basicOjb;
consle.log(bigX) // ans = 40

**Comment by RandellDawson** [comment]
This has already been fixed on the `master` branch, but has yet to be deployed to production.  You can view the page on our [beta site](https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/) which is a recent live version of the `master` branch.

I am closing due to this just waiting to be pushed to production.

Thank you for reporting.
