### ISSUE TITLE
Possible glitch in Bonfire: Confirm the Ending Challenge

### ISSUE THREAD

**Issue by Joqr** [FreeCodeCamp/FreeCodeCamp#3587]
Challenge [Bonfire: Confirm the Ending](http://freecodecamp.com/challenges/bonfire-confirm-the-ending) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function end(str, target) {
  
  var myArray = str.split("");
  var whichWord = myArray.pop(-1);
  var whichLetter = whichWord.substr(-1);
  
  if (whichWord === target || whichLetter === target) {
    return true;
  } else {
    return false;
  }
};

end("Bastian", "n", "");

```

My code seems to work flawlessly except for the "name" test, but the "name" test is exactly the same as the "specification" test so I see no reason why it will not accept my code. I believe there may be a bug within this challenge. 

If I'm missing something, please let me know. I have searched the forums and online and couldn't find any information on my exact issue, so I posted this as a new bug.

Here are the tests and whether or not my code passed them:

assert(end("Bastian", "n") === true, '"Bastian", "n" should return true.'); (PASSED)

assert(end("Connor", "n") === false, '"Connor", "n" should return false.'); (PASSED)

assert(end("Walking on water and developing software from a specification are easy if both are frozen.", "specification") === false, '"Walking on water and developing software from a specification are easy if both are frozen.", "specification") should return false.'); (PASSED)

assert(end("He has to give me a new name", "name") === true, '"He has to give me a new name", "name" should return true.');"He has to give me a new name", "name" should return true. (FAILED)

assert(end("If you want to save our world, you must hurry. We dont know how much longer we can withstand the nothing", "mountain") === false, '"If you want to save our world, you must hurry. We dont know how much longer we can withstand the nothing", "mountain" should return false.'); (PASSED)

**Comment by ltegman** [comment]
This is not an issue with the tests. In your solution `myArray` is an array of every individual character of the input, so when you pop off the end `whichWord` is only the last letter, meaning your code will always return `false` when the string being looked for is more than 1 character.

I can see where you're going though -- you meant to be splitting `myArray` at every space. Take note that while this solution would pass all the tests it wouldn't quite be correct for some other input. For example, that approach would return false for `end("He has to give me a new name", "me")` since `me` would not match `name` or `e`, but it should return true. A test case should probably be added to account for this.

**Comment by ahstro** [comment]
@ltegman is right, this is unfortunately an error with your code, not the bonfire. I've created a pull request with the test case suggested above to prevent an incorrect solution.
Good luck :)

**Comment by Joqr** [comment]
I altered my code and passed the challenge. I believe the issue here is the language used to describe the challenge, as well as the recommended method to solve it. 

I submitted two commits to improve this challenge here: #3674 & #3676.
