### ISSUE TITLE
Cookie problems?

### ISSUE THREAD

**Issue by mitziw** [FreeCodeCamp/FreeCodeCamp#3590]
I use a mac at home and win7 at work, my work sometimes stays with my mac and the is not current when i open the bonfires from work. Bonfire http://www.freecodecamp.com/challenges/bonfire-search-and-replace does not reflect my work I did over the weekend.

**Comment by ltegman** [comment]
Cookies are specific to a local machine, so this is expected. FCC will only store your unfinished challenge work on the machine you do the work on. However, once you pass a challenge you will see that answer in your profile on any computer.

While it would be nice for unfinished work to be saved to the FCC servers to continue on any computer that also introduces some potential problems. For example -- if you code an infinite loop that breaks the page but you're code is stored on local storage you can fix that just by clearing your local storage, but if this were in a DB on the FCC end there would need to be a mechanism to clear the DB entry in order to remove that broken code.

**Comment by BerkeleyTrue** [comment]
@ltegman Is correct. We store challenges in localStorage not on our servers until you complete the challenge. Unfortunately this will not change anytime soon as this would be a huge drain on our resource.

On the bright side, share-able challenges will be released soon. This will make your URL's unique and reflect the current state of you challenge. In order to accomplish what you are after you would only need to send yourself your current URL. Clicking on that link would load you challenge on any browser. Look for this in the next couple of days.

Happy Coding!

**Comment by mitziw** [comment]
oK. I finished the work today and it's not pulling the completed code from the db as you've stated is the expected behavior http://www.freecodecamp.com/challenges/bonfire-missing-letters. stop spitting on my cupcake and telling me it's frosting.Berkely

**Comment by ltegman** [comment]
It should pull it from the db and put it on your profile page http://www.freecodecamp.com/mitziw . It won't use that to populate the challenge page.
