### ISSUE TITLE
[rocks/beta] many "news" images don't show up

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35932]
**Looking forward for reporting a security issue:**
Go to the news page on beta and many of the images don't show up.

**Screenshots**
Firefox: doesn't display any images
<img width="1265" alt="Screen Shot 2019-04-29 at 8 50 36 AM" src="https://user-images.githubusercontent.com/20648924/56902170-4c891380-6a5f-11e9-879b-d8674aabec8d.png">

Chrome: only displays profile thumbnails
<img width="1005" alt="Screen Shot 2019-04-29 at 9 17 44 AM" src="https://user-images.githubusercontent.com/20648924/56902332-ae497d80-6a5f-11e9-87f2-146a98f747c4.png">

**Desktop (please complete the following information):**
 - OS: high sierra 10.13.6
 - firefox 66.0.1
 - chrome  74.0.3729.108

**Additional context**
Tested on chrome and firefox

**Comment by ahmadabdolsaheb** [comment]
Thanks for reporting this issue. rocks/news is sharing some infrastructure with .org/news therefore the image paths are relative to the .org instance. this should not be an issue once the .rocks/news runs on its own stack which is in the works and supposed to happen pretty soon. that's why I will close this for now, but feel free to reopen it if the issue persists in a couple of weeks.
