### ISSUE TITLE
Sign-Up does not work

### ISSUE THREAD

**Issue by keschte** [freeCodeCamp/freeCodeCamp#35944]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Join functionality broken due to missing jQuery dependency.
See attached screenshot.

![image](https://user-images.githubusercontent.com/878256/57008208-c8fe2c80-6bee-11e9-94df-0ef8e0f5c0fe.png)

**To Reproduce**
1. Go to 'Start coding, it's free'
2. Click on 'any of the buttons'
3. Does not work.

**Expected behavior**
Take to oauth partner to sign in and get a token.

**Screenshots**
-
**Desktop (please complete the following information):**
 - Windows
 - Chrome, Internet Explorer, Edge

**Comment by keschte** [comment]
![NJpRa4OT5y](https://user-images.githubusercontent.com/878256/57008260-27c3a600-6bef-11e9-870b-c0408b81e5e0.gif)

**Comment by raisedadead** [comment]
The root cause is that something on your network is blocking the jQuery library being served off of jsdeliver. Ideally you would want to allow (with help of your network admin / ISP) this on your network.

We do plan to move away from jQuery soon. But its going to be a while before we do that.

I can't suggest any plausible alternatives other than trying a different network, if you can or even a VPN if you can.

Thanks for your report.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead I attempted to reproduce, I got a 500 after clicking on the start coding now button
![image](https://user-images.githubusercontent.com/4591597/57059095-522f6500-6cbc-11e9-9e1d-6b34f864e2a5.png)

**Comment by raisedadead** [comment]
@ahmadabdolsaheb This is flagged for production. What you are seeing is for an unrelated issue documented in #34872
