### ISSUE TITLE
[challenge] bad tests: Regular Expressions: Specify Only the Lower Number of Matches 

### ISSUE THREAD

**Issue by nikrb** [freeCodeCamp/freeCodeCamp#35988]
[challenge](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/regular-expressions/specify-only-the-lower-number-of-matches) has insufficient tests.
Challenge instructions:

> Change the regex haRegex to match the word "Hazzah" only when it has four or more letter z's.

`/z{4}/` is enough to pass, whereas I _think_ it should be more like `/Haz{3,}ah/`

Found this while testing #35747 locally, tested on .rocks with same results.

**Tell us about your browser and operating system:**
* Browser Name: Chromium
* Browser Version: Version 72.0.3626.121 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
* Operating System: crouton running on chromebook - Ubuntu 16.04.6 LTS

**Comment by moT01** [comment]
Yea, that's a problem - I can take a look at this.

**Comment by RandellDawson** [comment]
@nikrb Don't you mean it should be `/Haz{4,}ah/` ?

**Comment by RandellDawson** [comment]
@moT01 I have reviewed this PR and the original issue and honestly, I do not see anything wrong with the challenge as it currently is on master.  I think the original issue and this PR should be closed as unnecessary.
```js
let haRegex = /Haz{4}ah/; // Change this line
```
If a camper uses the above  regular expression it will correctly pass the first 4 tests (as it should) because:
* The first test checks for the curly brackets which it has
* The second test makes sure that "Hazzah" does not match which it would not
* The third test makes sure that "Hazzzah" does not match which it would not
* The fourth test makes sure that "Hazzzzah" does match which is should

and the remaining tests should fail (as they do) because the regex does not have the extra `,` after the `4` which it needs to full the the challenge instructions:
> Change the regex `haRegex` to match the word `"Hazzah"` only when it has four or more letter `z`'s.

Just like other challenges, we have various tests which can pass and fail depending on what the user writes as a solution.  As long as we have written all the tests needed to make sure the challenge requirements are met, then the tests are solid.  Regarding an individual test, we only care that the solution passes when it should and fails when it should. 

If I am missing something simple here, please help me to understand.  I think I need to to see an example of a solution which does not fulfill the requirements of the challenge yet passes ALL (not just a few) of the existing tests.

Thanks.

**Comment by moT01** [comment]
I think you are missing something.

- The exact instructions are: `Change the regex haRegex to match the word "Hazzah" only when it has four or more letter z's.`
- That means it should match the full word: `Hazzzzah` - all 8 characters
- As it says in the issue here - "`/z{4}/` is enough to pass"
- But that regex won't match all 8 characters of `Hazzzzah` - it will only match the `zzzz` - and yet it passes the tests.

**Comment by RandellDawson** [comment]
Sorry for my lightbulb not being on before.  I get it now.

**Comment by moT01** [comment]
That will happen - things get a little fuzzy after a whole day of screen time
