### ISSUE TITLE
should search bring up results instead of suggested terms?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35985]
When searching on the search page (https://search.freecodecamp.org/?q=html) - it brings up results - lessons, guides, youtube stuff

<img width="1053" alt="Screen Shot 2019-05-07 at 9 39 48 AM" src="https://user-images.githubusercontent.com/20648924/57308676-6902fc80-70ac-11e9-8a3a-d74c823c3a40.png">

But when searching from anywhere else on the website it brings up suggested search terms...

<img width="1036" alt="Screen Shot 2019-05-07 at 9 40 02 AM" src="https://user-images.githubusercontent.com/20648924/57308739-7fa95380-70ac-11e9-9029-ca28914d3dad.png">

I'm wondering if we can or should bring up the same results you would get on the search page when using the search anywhere else.

**Comment by Hardik500** [comment]
Hi @moT01 
I think it would be best that the search result from search page (https://search.freecodecamp.org/?q=html) should be used to display queries or any page.
Since when user searches anywhere first he is redirected to the search page with the same query and then is redirected to the the article or docs. 
It would save up a lot of time if one could search up the same results from anywhere.

**Comment by RandellDawson** [comment]
@moT01 I think we can close this now, as it has been decided by the core team that the search feature will only be searching the news articles.

**Comment by moT01** [comment]
Sounds good - the issue might still exist, I'm not sure how it will display things when it's running. But for now, yes, we can close this and test it when it's up and running.

**Comment by RandellDawson** [comment]
There were a ton of PRs related to the search functionality which were merged in the last two weeks.  Once freecodecamp.rocks is up and running again, we can validate everything is as it should be.
