### ISSUE TITLE
tutorial pages are also marked as stubs

### ISSUE THREAD

**Issue by PragatiVerma18** [freeCodeCamp/freeCodeCamp#36090]
the tutorial pages are marked as stubs, since, they are not usual guide articles, they shouldn't be treated as stubs and if possible they can only be considered as the sidebar heading that leads into the dropdown rather than acting as a link that opens a page.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/css/tutorials/

![issue](https://user-images.githubusercontent.com/42115530/58002004-b9da1280-7afa-11e9-827b-c62ef5c8c9e0.JPG)

**Comment by RandellDawson** [comment]
@PragatiVerma18 Instead of creating a new issue for each section you find stubs in, I think it is best to change your original issue title to some less specific regarding stubs in the Guide.  There are going to be stubs scattered through all the Guide sections.  Plus update your other issue.  I am closing this one now.

Thank you.
