### ISSUE TITLE
CSS cascade and inheritance not introduced

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36109]
While looking into #36108 I realised that inheritance and the cascade are not defined in the curriculum.  Some of the concepts are introduced at various points, but they aren't formally defined or really tied together.   

Should we add some challenges to cover these concepts and, if yes, where?

**Comment by RandellDawson** [comment]
I think the only way to properly do it is to introduce the basic ideas of both at the very beginning of the Introduction to Basic CSS and then rewrite (and possibly reorder) some of those challenges so that it is clear how each relates to the concepts.  Some of the existing challenges gloss over `specificity` which is directly related to the cascade concept.   This could end up being a major undertaking to pull this off in the current curriculum.  It might be best to introduce all of these concepts in a project of the new curriculum.  I don't see any project in that repo which would cover these concepts.

**Comment by ojeytonwilliams** [comment]
That might be the best idea.  One problem is Basic CSS is all very practical and fairly light on technical details, so a raft of definitions wouldn't really fit stylistically.

**Comment by RandellDawson** [comment]
As we tell others on the forum, FCC is not meant to be comprehensive.  We teach just enough so users can get things going, but they will still be required to learn much more and asking many more questions outside of FCC to be well rounded.

**Comment by ojeytonwilliams** [comment]
On reflection, since the curriculum is going to be reworked anyway, a big change to the existing curriculum seems premature.  Closing this on that basis.
