### ISSUE TITLE
Basic JavaScript: Iterate with JavaScript Do...While Loops missing hint pagge

### ISSUE THREAD

**Issue by darrinlallen** [freeCodeCamp/freeCodeCamp#36107]
the hint page is missing here
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

**Comment by RandellDawson** [comment]
@darrinlallen Thank you for reporting this issue, but it has been fixed on our `master` branch.  The reason you do not see it fixed is because the `master` branch has not been deployed since October 2108 after a major repo restructuring.  When it is deployed, the issue will no longer be present in production.
