### ISSUE TITLE
Two challenges about Objects missing content

### ISSUE THREAD

**Issue by twhite96** [freeCodeCamp/freeCodeCamp#36105]
**Describe your problem and how to reproduce it:**
Iterate with `for in` and Generate Array with `Object.keys()` lessons not maintaining state; generating `404` on my profile. See https://github.com/freeCodeCamp/freeCodeCamp/issues/36096#issue-446200317

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object.keys

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 74.0.3729.157 (64-bit)
* Operating System: macOS 10.14.5

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![](https://cl.ly/1c037b5bc40e/Screen%252520Recording%2525202019-05-21%252520at%25252008.56%252520PM.gif)

**Comment by sergeyradov** [comment]
@twhite96 Could you please advise what browse did you us to open these resources? 
I have tried to get access to these pages and found them working, but with a difference in the URI.

Here is the working one which I could open from Chrome
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys/

and I can see `-keys/` instead of `.keys`

Same for the second resource 
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement/

The difference is seen is `...` instead of `---`

**Comment by sergeyradov** [comment]
Updated browser to 74.0.3729.169 (Official Build) (64-bit) and results hasn't changed.

**Comment by RandellDawson** [comment]
@sergeyradov Thank you for reporting this issue, but it has been fixed on our `master` branch.  The reason you do not see it fixed is because the `master` branch has not been deployed since October 2108 after a major repo restructuring.  When it is deployed, the issue will no longer be present in production.

**Comment by sergeyradov** [comment]
@RandellDawson actually it works fine in Production 
https://learn.freecodecamp.org/
thank you for update.
