### ISSUE TITLE
Fix code fencing in guide

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#36102]
We have several guide files in all the translated languages where the code fencing ``` is messed up or/and is not associated with a code language. One example can be seen in the PR linked below:
https://github.com/freeCodeCamp/freeCodeCamp/pull/36098

**Comment by RandellDawson** [comment]
@thecodingaviator I think it has something to do with the way the translations were created.
https://github.com/freeCodeCamp/guide/edit/master/src/pages/css/properties/background-position-property/index.md

@raisedadead It appears the first time we see the above and any other Arabic translations is in [this commit](https://github.com/freeCodeCamp/freeCodeCamp/commit/da0df12ab7b3bae46c2a376da246a6c499afd88b#diff-3c649215c74ed9f9bc8a132a4604b42a).  Do you know what type of logic was used to create the translations.  I could not find any of the Guide articles translated in the archived Guide repo, so it appears the translations were created during the creation of the mono repo?

I am not sure of any easy fix for this, because we lost the original language post-fix as well as the triple backticks.  Also, since there are actual times when single backticks were used for inline code, we would not just want to replace all single backticks with triple backticks.

The only thing I can think of doing which is not full proof because coded sections might have changed, but I could pull down the latest version of the Guide and then write a script which would check each Arabic Guide article in the freeCodeCamp repo for anything surrounded by single backticks and see if a match of the inner portion is found in the corresponding Guide repo file which was in English (located in `src/pages/`).  If it is, then grab the code post-fix and replace the mono repo version with triple backticks plus the language post-fix. 

Another option is just to look in the corresponding current English version of the freeCodeCamp repo and do the same thing, but my thinking was the English version could have changed significantly enough that many code sections may have been removed or modified.  I figure the translated Guide articles code sections were not changed as much, because the focus was on converting the actual text.

Let me know what you think and I will proceed with my idea.

**Comment by RandellDawson** [comment]
@raisedadead @thecodingaviator It turns out it was a bit more complicated than I first thought.  An example of a mult-line code segment in the archived Guide repo looked like the following:
````
**Example:**

```css
body {
    background-color: crimson;
}

div {
    background-color: #ffffff;
}

.myClass {
    background-color: rgba(0, 0, 0, 0.5);
}
```

#### Property Values:
````
However, when it was translated, it ended up looking like the following:
````
**مثال:**

 `body { 
    background-color: crimson; 
 } 
 
 div { 
    background-color: #ffffff; 
 } 
 
 .myClass { 
    background-color: rgba(0, 0, 0, 0.5); 
 } 
` 

#### قيم الملكية:
````

It might be difficult to tell by just looking at these two code sections, but instead of triple backticks, there are only single backticks surrounding the code section.  Also, there is an extra space character at the end of each line. Lastly (which took me a while to figure out), there is an extra space character on any line which does **not** already start with a space. 
  
Anyway, after many hours, I was still able write a script which accomplishes the main goal stated in the original issue posted by @thecodingaviator .  The script replaced `3432` multi-line code sections in `1163` articles.

Based on the sheer number of files affected and there are still 62 open Arabic guide-related PRs which have yet to be reviewed/merged, I think I should wait to implement a series of PRs (with max of 200-300 files) on each until we have we get all of them reviewed/merged.

An alternative to using the script I have created above for all the files, would be to get a list of all of the Arabic Guide files which have a last modified date greater than the date/time the mono repo was created (when the translations were actually added).  Then, correct whatever script was originally used to make these translations for all the files currently in the English Guide but exclude any on the list created in the step before.  This way, we won't redo the Arabic translation with Google translate for any file which has already had corrections to the translations since the original translations were created.  Then, I can use the same script against just the files on the list which could result in a much smaller PR to review in general.

**Comment by thecodingaviator** [comment]
The latter sounds like a better solution. If we implement changing just the files that haven't been changed, merging is easy

**Comment by RandellDawson** [comment]
To perform the latter we will need to fix the script which wrongly converted the code sections the first time around for the files which have never been changed since the mass translation.  I have no idea where that script is.

**Comment by thecodingaviator** [comment]
I think if you follow the trail back to the guide repo, you'll find the person who made the change, then they can probably give you the script

**Comment by RandellDawson** [comment]
The change was performed between the two repos.  When the mono repo was created, the translations appeared in a PR created by @raisedadead.  I assume he has the script somewhere.

**Comment by raisedadead** [comment]
Hi @beaucarnes can you guide here, since you were the original author of the scripts?

**Comment by RandellDawson** [comment]
@moT01, @Manish-Giri, @ojeytonwilliams, @thecodingaviator - I have created 15 PRs to deal with this issue.  Keep in mind if the original English Guide repo article did not have a language post-fix, there will not be one in the converted version in these.  There are several of these, but instead of trying to fix them on these PRs, I would prefer once these are all merged, that we tackle them on a separate set of PRs, because the other languages (including English) will also be missing the language and I can take care of them (all languages) in a single PR later.

@raisedadead There are 67 Arabic Guide related open PRs currently.   Should we go ahead and merge these 15 PRs out of order and deal with any merge conflicts which may occur during the review of those PRs or do you want me to go through each of the 67 PRs and fix and code sections in the hopes of averting any merge conflicts?

**Comment by raisedadead** [comment]
Lets do this:

> [...] go ahead and merge these 15 PRs out of order and deal with any merge conflicts which may occur during the review of those PRs [...]

**Comment by beaucarnes** [comment]
Whoops. This looks like it was my fault since I created the translation script. The script is here: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/tools/translation

Let me know what help you need.

**Comment by RandellDawson** [comment]
@thecodingaviator I think it is fine to close this issue now as 99% of the Arabic guide code sections were fixed in the above PRs which were merged before the guide was removed from the repo.
