### ISSUE TITLE
abrupt switch to Queues and DS in JavaScript Course

### ISSUE THREAD

**Issue by PragatiVerma18** [freeCodeCamp/freeCodeCamp#36135]
The JavaScript Course which is dealing with the basics of functions suddenly has a problem with Queues.

![guide](https://user-images.githubusercontent.com/42115530/58386295-17022680-801b-11e9-923b-825314e6ab17.JPG)

Then, the display code is too complex for the beginners, this lesson/challenge must be shifted somewhere below on the curriculum list. Here, is a screenshot of the challenge:

![guide1](https://user-images.githubusercontent.com/42115530/58386304-503a9680-801b-11e9-9002-146e67d0ae78.JPG)

**Comment by Manish-Giri** [comment]
> Then, the display code is too complex for the beginners,

Can you specify which part of the code you were referring to?

IMO, the Stand In Line challenge is introduced ***after*** several challenges on functions, arrays, array manipulations, returning values from functions, etc have been already presented. So, by this point, the challenge tasks - adding an item to the end of an array, and returning and removing the first array element should be pretty straightforward, even for beginners.

If you were referring to the terminology about the Queue at the beginning of the challenge being distracting/confusing for beginners, we could do something about that, since a knowledge of Queues is really not necessary for this challenge. Maybe it could be moved to the *end* of the challenge description, as a side note, mentioning this is how Queues work.

**Comment by PragatiVerma18** [comment]
I was referring to the following code :

![issue1](https://user-images.githubusercontent.com/42115530/58751720-ec531a80-84bf-11e9-8e3c-0dcb8f86bd36.JPG)

This challenge can be introduced in the Basic Data Structures part wherein the arrays are further expanded. This is just a kind suggestion as this seems a bit abrupt to start dealing with queues without even having the proper knowledge of arrays beforehand.

Please mention the appropriate file name so that I can make a PR and change the sequence appropriately. Hope you get my point. Thanks!!!

**Comment by RandellDawson** [comment]
>This is just a kind suggestion as this seems a bit abrupt to start dealing with queues without even having the proper knowledge of arrays beforehand.

@PragatiVerma18 I am not sure what you are talking about.  There are 9 challenges before this one on various aspects of arrays.  Everything the camper needs to understand has already been presented.
