### ISSUE TITLE
Not supporting Microsoft Edge with local docker

### ISSUE THREAD

**Issue by 0071241** [freeCodeCamp/freeCodeCamp#36157]
Hello, I have noticed that there is not full support for MS Edge when using a local fCC running on docker. Here is a link to a problem I was having, which was not being able to sign in using Edge. [Link](https://github.com/freeCodeCamp/freeCodeCamp/issues/36139) 
Hopefully, someone can help me out with this or fix this issue, and thank you in advance.

**Comment by raisedadead** [comment]
Edge has been a bit difficult for some of our platform code. 

You have not specified the OS, but I think it's not limited to any. In any case I think this will improve one Edge goes full chromium soon. They went ahead with that on macOS for instance: https://twitter.com/raisedadead/status/1130569340779032577

I think once we have a GA, we could revisit this hopefully because the underlying APIs will become common.
