### ISSUE TITLE
[Discussion] Should JavaScript section be restructured?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36226]
The JavaScript section has always felt out of order to me. Currently it looks like this...

```
Basic JavaScript
ES6
Regular Expressions
Debugging
Basic Data Structures
Basic Algorithm Scripting
Object Oriented Programming
Functional Programming
Intermediate Algorithm Scripting
```

Why are regex and debugging third and fourth?
I understand why ES6 is second - we want to get users right into the newest stuff... but it still feels a little out of order. And the way some of the ES6 lessons are written is more complex than they need to be, making it feel even more out of order. 

It just doesn't feel like it follows a natural progression. Certainly `Basic Data Structures` and `Functional Programming` have to be more important than regex and debugging.

I don't know what the solution is but I thought I would open an issue up for discussion. Perhaps something like this would be better...

```
Basic JavaScript
Basic Data Structures
Functional Programming
ES6
Debugging
Basic Algorithm Scripting
Object Oriented Programming
Regular Expressions
Intermediate Algorithm Scripting
```

If we decide to rearrange things - we would definitely want to take a closer look at the challenges to make sure things aren't introduced after they need to be used.

**Comment by ojeytonwilliams** [comment]
I think it would be better to put ES6 after all the basic concepts.

Right now it seems a bit back to front, since [destructuring assignment](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/) is introduced before [dot notation](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-dot-notation-to-access-the-properties-of-an-object/).

So, maybe something like:

```
Basic JavaScript
Basic Data Structures
Functional Programming
Object Oriented Programming
ES6
Debugging
Basic Algorithm Scripting
Regular Expressions
Intermediate Algorithm Scripting
```

Also, it could be better to swap 'Basic Algorithm Scripting' and 'Debugging'.  The scripting challenges are a little different from the rest (they are more problem solving focused), so provide a break from the other, more conceptual challenges.

**Comment by RandellDawson** [comment]
There will still need to be some challenges shifted around or presented differently if you put Functional Programming before Object Oriented Programming.  The `this` key word is introduced in the Object Oriented Programming section and then in the Functional Programming section, there are the following challenges presented which require the knowledge of `this`:

[Implement map on a Prototype](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype)

[Implement the filter Method on a Prototype](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype/)

**Comment by QuincyLarson** [comment]
@moT01 Thanks for your feedback. Since we are going to replace the existing JavaScript curriculum with the updated project-orient curriculum - basically, a series of practice projects: https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546

So there is no need for us to go back through and make significant changes to the existing curriculum.

In case you're curious, this is coming along quite well. You can see the progress here: https://github.com/orgs/freeCodeCamp/projects/10

**Comment by birdysexy** [comment]
Well am learning
