### ISSUE TITLE
RegExp Restrict Possible Usernames challenge need stricker test

### ISSUE THREAD

**Issue by minggas** [freeCodeCamp/freeCodeCamp#36317]
**Describe your problem and how to reproduce it:**
There's no test for the first check:
`1) The only numbers in the username have to be at the end. There can be zero or more of them at the end.`

That way the RegEx `/[a-z]{2,}/i` pass in all tests when it shouldn't, because this regex match any username who has at least two letters.
 
**Add a Link to the page with the problem:**
[Restrict Possible Usernames](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 75.0.3770.90 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
Thanks for reporting this @minggas - this is fixed in beta. However the beta site is down right now so the only way verify that it's fixed is to run the site locally - which I have done.

<img width="1359" alt="Screen Shot 2019-06-21 at 11 08 28 AM" src="https://user-images.githubusercontent.com/20648924/59936144-ebedd580-9414-11e9-8548-8a029b92ba31.png">

**Comment by ahmadabdolsaheb** [comment]
I can confirm that this issue is non-existent on the current master. 
It will be updated as soon as the new version is live.
