### ISSUE TITLE
ES6: Write Concise Object Literal Declarations Using Simple Fields

### ISSUE THREAD

**Issue by Pen-pusher** [freeCodeCamp/freeCodeCamp#36325]
const createPerson = (name, age, gender) => {
  "use strict";
  // change code below this line
 1+3
  // change code above this line
};
console.log(createPerson("Zodiac Hasbro", 56, "male")); // returns a proper object

and this code works perfectly on the exercise.even its not the right solution

**Comment by lasjorg** [comment]
There was a PR for this which fixes that specific issue (not in production yet). However I do believe the test is still broken, you can pass the test using an empty object.

This passes the (new from PR) test:

```
const createPerson = (name, age, gender) => {
  "use strict";
  return {
  }
};
```

I would also like to change the name of the challenge and use properties instead of fields.
