### ISSUE TITLE
An Export Fallback with export default in ES6

### ISSUE THREAD

**Issue by Cunning0fDesires** [freeCodeCamp/freeCodeCamp#36347]
**Describe your problem and how to reproduce it:**

Hi, since my last report was closed for no reason and didn't even read properly, I have to report it once again.

My initial solution was the following:

export default function subtract(x,y) {
return x - y;
}

It didn't work

But then I wrote the SAME code in ONE line, and it worked:

export default function subtract(x,y) {return x - y;}

Hence, my code is correct. And https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Using_the_default_export MDN agrees with me. JavaScript doesn't discriminate against spaces or arbitrary line formatting between valid expressions. So, the issue is that it won't parse the function correctly on multiple lines

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-an-export-fallback-with-export-default

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 75.0.3770.100
* Operating System: Windows 10
![photo_2019-06-29_15-11-38](https://user-images.githubusercontent.com/51486985/60384039-ed0cab80-9a81-11e9-9a0d-ef44a0e26cb1.jpg) 
![photo_2019-06-29_15-12-33](https://user-images.githubusercontent.com/51486985/60384045-f269f600-9a81-11e9-9523-8151bb5dc623.jpg)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@Cunning0fDesires I see what you mean now.  After looking at older issues which have been closed, this was already reported in the past and was fixed on our master branch.  The master branch fix has not been deployed to production, so it is not yet working correctly.

I am closing this issue, because the fix has already been made and is just waiting on a deployment.  You can see below where I have tested the challenge using code written on multiple lines and passes the test.

Thank you.

![image](https://user-images.githubusercontent.com/5313213/60384723-3afbc200-9a36-11e9-8d0b-f079c49921b1.png)

**Comment by RandellDawson** [comment]
Also please not.  If you ever have more information to add to an issue which has been closed, you can simply reply back to the same issue (which is preferred) instead of creating a new one.

Thank you.

**Comment by Cunning0fDesires** [comment]
Alright, thanks
