### ISSUE TITLE
Why use mlab in "Implement the Serialization of a Passport User"?

### ISSUE THREAD

**Issue by kiwisquash** [freeCodeCamp/freeCodeCamp#36343]
**Describe your problem and how to reproduce it:**
Currently, the challenge named in the title says we can set up a free database on mLab. 

That seems a bit odd, considering that the previous coding challenges had us create [Mongo Atlas accounts](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose).

Note that I am not advocating one service over the other. I just think it's strange and confusing to switch services mid-curriculum without any explanation.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/implement-the-serialization-of-a-passport-user

**Comment by jonathan-grah** [comment]
@raisedadead, Is there an advantage to choosing to adopt one over the other across all mentions or does it really matter?

**Comment by raisedadead** [comment]
All these will have to be updated in the next release of curriculum. In general, you can use any platform of your choice.

**Comment by jonathan-grah** [comment]
I'm going to close this due to the above reasons @kiwisquash. It doesn't really matter if we encourage different services at different points, it's not a rule; just a suggestion.

We will be changing this soon with our refactored curriculum, you can learn more about that here:
https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546
