### ISSUE TITLE
Start a Working Express Server Challenge - Suggestion to make less confusing

### ISSUE THREAD

**Issue by mtpiercey** [freeCodeCamp/freeCodeCamp#36376]
So, I was doing the "Start a Working Express Server" challenge as part of the "Basic Node and Express" block in the "APIs and Microservices Certification", and I struggled with the instructions for a bit. There is a line in the instructions that says:

```
Use the app.get() method to serve the string Hello Express, to GET requests matching the / root path.
```

Now, I know what that's supposed to mean (now), but I was confused about it for a while since I didn't notice the space between ```/``` and ```root```; I thought the path was supposed to be ```/root```, and so I was thus confused.

IMO, I think something like: 
```
Use the app.get() method to serve the string "Hello Express" to GET requests matching / - the root path.
```

but that's just an idea.

----------
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/start-a-working-express-server

* Browser Name: Google Chrome
* Browser Version: Chrome 75
* Operating System: macOS

**Comment by jonathan-grah** [comment]
Hi @mtpiercey, we are currently refactoring the curriculum (you can find out more about that here: https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) - basically to a more project-based approach to learning.

We are [quite far on in this process](https://github.com/orgs/freeCodeCamp/projects/10) so we would prefer contributors would spend time on that rather than update soon-to-be legacy content.

Thanks 😃

**Comment by mtpiercey** [comment]
Awesome!
