### ISSUE TITLE
Get JSON with the JavaScript XMLHttpRequest Method - Test seems arbitrary

### ISSUE THREAD

**Issue by mtpiercey** [freeCodeCamp/freeCodeCamp#36378]
For the "Get JSON with the JavaScript XMLHttpRequest Method" challenge, I noticed that the checkbox ```Your code should have an onload event handler set to a function.``` didn't light up when I tried to use an (apparently valid and working) ES6 arrow function:

```javascript
request.onload = () => {
  newJson = JSON.parse(request.responseText)
  document.getElementsByClassName('message')[0].innerHTML = JSON.stringify(newJson)
}
```
^ Unless I'm missing something, this should work (and it seemed to - when I clicked the button in the challenge the paragraph's text updated as it was supposed to update), but it didn't pass the function checkbox's text because it wasn't:

```javascript
request.onload = function() {
  newJson = JSON.parse(request.responseText)
  document.getElementsByClassName('message')[0].innerHTML = JSON.stringify(newJson)
}
```
^ This *did* pass all the tests.
----------
https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method

* Browser Name: Google Chrome
* Browser Version: Chrome 75
* Operating System: macOS Sierra

**Comment by RandellDawson** [comment]
@mtpiercey This issue was fixed a while back on the master branch but we are waiting for the master branch to be deployed to production (so you can see it).  In the mean time, I used your code in the latest version of master (I have setup the repo locally) and you can see it passes the tests.

In the future, you should search through the closed issues to see if someone has already reported the issue and to see if a pull request has already been merged.

I am closing this since it has actually been fixed.

**Comment by mtpiercey** [comment]
Okay. Yeah, I figured someone would've already caught this. Next time if I run into something like this I'll take a look at the other issues/commits (and I may clone the repo locally to test it as well).

Thanks!
