### ISSUE TITLE
Dealing with legacy lifecycle methods

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36381]
As mentioned in https://github.com/freeCodeCamp/freeCodeCamp/pull/35894 and https://github.com/freeCodeCamp/freeCodeCamp/pull/35895#issuecomment-508145165 there are still challenges that use legacy React lifecycle methods.

Let's discuss what we should do with those challenges.

Personally, I think [the challenge](https://learn.freecodecamp.org/front-end-libraries/react/manage-updates-with-lifecycle-methods/) that uses them should simply be removed.  Quoting the [React blog](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html):
> some of our legacy component lifecycles tend to encourage unsafe coding practices

So, not something we need to teach.

The other [challenge](https://learn.freecodecamp.org/front-end-libraries/react/optimize-re-renders-with-shouldcomponentupdate/) has `componentWillReceiveProps`, but it is not integral to the challenge.  If the method is removed, I think that challenge will be fine.

**Comment by thecodingaviator** [comment]
My opinion is that we should remove the corresponding challenges from the curriculum

**Comment by jonathan-grah** [comment]
Hi @ojeytonwilliams, we are currently refactoring the curriculum (you can find out more about that here: https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) - basically to a more project-based approach to learning.

We are [quite far on in this process](https://github.com/orgs/freeCodeCamp/projects/10) so we would prefer contributors would spend time on that rather than update soon-to-be legacy content.

Thanks 😃

**Comment by RandellDawson** [comment]
@jonathan-grah @ojeytonwilliams, @thecodingaviator and I have been working quite extensively only fixing the existing curriculum.  It will still be quite a while before the new curriculum replaces this one, so even though we probably won't be creating much new content, I see no harm in making the existing content better.  This is a discussion thread.  If we all agree to close it, then that is fine, otherwise let's keep it open.

**Comment by jonathan-grah** [comment]
@RandellDawson, it would be very easy if we do as @thecodingaviator says and delete said challenges. If someone wants to spend time on this, no problem 👍

**Comment by ojeytonwilliams** [comment]
@jonathan-grah As I understand it, there's no point making significant changes since those changes will only be temporary.  However, these changes would be pretty trivial.

@thecodingaviator isn't it worth keeping "Optimize Re-Renders with shouldComponentUpdate"? The fix is pretty simple.  We delete 

```js
componentWillReceiveProps(nextProps) {
  console.log('Receiving new props...');
}
```
from the seed and solution and change "the other lifecycle hooks are triggered" to "the lifecycle hooks are triggered".  I'd be happy to create the PR for this.

**Comment by thecodingaviator** [comment]
@ojeytonwilliams I'm onboard with that, I think you should go ahead and make the PR
