### ISSUE TITLE
Certificate doesn't scale to page

### ISSUE THREAD

**Issue by hansinla** [FreeCodeCamp/FreeCodeCamp#3639]
<img width="1680" alt="screen shot 2015-10-07 at 10 01 39" src="https://cloud.githubusercontent.com/assets/373708/10344840/7411deae-6cda-11e5-97c5-1962da86347b.png">
When opening the Front End Developer Certificate, the image is blown up and doesn't scale to the size of the browser window.

**Comment by BerkeleyTrue** [comment]
This is purposeful. Certs are not responsive.

Happy Coding!

**Comment by hansinla** [comment]
It's that's by design: It looks horrible.

**Comment by BerkeleyTrue** [comment]
cc @QuincyLarson

**Comment by QuincyLarson** [comment]
Hi @hansinla, to give you a more detailed explanation why these aren't responsive, we are using absolute positioning to dynamically add certain text to the certificate. I don't believe it's possible for us to do this and also make the image responsive (though if you can think of a way, we welcome a pull request).

You can zoom out your browser a bit and send employers a screenshot of the certificate.

We dynamically generate these so that they can be verified (with a unique URL) and thus make impossible to difficult to forge these certificates without access to our production database.
