### ISSUE TITLE
Add guide stub articles for newly created lessons

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36399]
Many new lessons have been created recently - they should probably have an associated guide article for each of them - even if it's only a stub. Also, some lessons have been renamed - so maybe rename those associated articles, as well.

Here's a few recent PR's that added new lessons...
~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36201~~
~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36144~~
~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36200~~

Here's some open PR's that add new lessons and could probably have the guide articles added on those PR's...
~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36045~~ 
https://github.com/freeCodeCamp/freeCodeCamp/pull/35770
~~https://github.com/freeCodeCamp/freeCodeCamp/pull/35968~~

EDIT: looks like articles were added for all those that were merged

Feel free to add to this list if you know of others.

**Comment by jonathan-grah** [comment]
Hi @moT01, we are currently refactoring the curriculum (you can find out more about that here: https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) - basically to a more project-based approach to learning.

We are [quite far on in this process](https://github.com/orgs/freeCodeCamp/projects/10) so we would prefer contributors would spend time on that rather than update soon-to-be legacy content.

Thanks 😃

**Comment by RandellDawson** [comment]
This is still a valid issue.  Before closing issues in the future, make sure there is a consensus to do so.

**Comment by jonathan-grah** [comment]
@RandellDawson, sorry. As far as I was aware after talking to Quincy, it was best for us to clean up any issues around improving the current curriculum, due to the nearing release of version 7.0.

**Comment by RandellDawson** [comment]
It is not that close to be releases.  The deployment of the current master branch is very close to being deployed to production though.

**Comment by jonathan-grah** [comment]
Okay @RandellDawson.
I just think it's better if we try and focus community contributions towards the new project-based challenges, instead of driving attention away towards minor improvements - it will slow us down otherwise.

This is fine, I completely understand, I was definitely too quick to close this. However, I don't think we should be adding any additional challenges etc. from this point on.

**Comment by RandellDawson** [comment]
The existing curriculum which was launched in June 2018 had many bugs which many contributors have fixed since October, so we are very eager to have the current master deployed to production as fixed (many of which are major) were needed.  Any contributions here are appreciated whether existing current bugs are fixed or if it is work on the new curriculum.  If you are on the forum at all, you quickly find out where the improvements in the existing curriculum are needed.

**Comment by jonathan-grah** [comment]
@RandellDawson I was talking about preferring contributions to new curriculum over adding new challenges to the current one. Bugs are a different ball game.

**Comment by RandellDawson** [comment]
@jonathan-grah Got it.  There are only a few outstanding PRs with new challenges still open that we are actively trying to get merged.  Once those are in (many are quite old), then I agree we probably should only add new challenges to the current curriculum if it is really warranted or just refer users to the curriculum expansion.  Alot of the newer challenges that have been created for the existing curriculum could be modified and ported over to the new curriculum, so it is not wasted effort.  Plus, I do not see the new curriculum being launched until 2020 based on what I have seen and considering how long it has taken just to get the current mono repo in shape to be deployed to production.  The material we have in the current repo will still be valid for quite a bit longer.

**Comment by jonathan-grah** [comment]
@RandellDawson Great! Thanks for the clarification and sorry for the confusion

**Comment by RandellDawson** [comment]
@moT01 Can this be closed or are we still waiting for something?

**Comment by moT01** [comment]
There's one PR still there which adds four new challenges. If it gets merged - we maybe want to create guides for them. I was thinking we should have an issue here or something somewhere to keep track of challenges that get added or modified so we can update the guide.

**Comment by RandellDawson** [comment]
> Probably best to create a new issue specifically for that.

@moT01 I think that would be a good idea.  Those 4 challenges should be the last ones added to the current curriculum if I am not mistaken.

We should probably adjust the challenge documentation to reflect that a PR for a challenge can not be merged without the corresponding hints/solutions topic on the forum is updated with any relevant changes.

**Comment by moT01** [comment]
I have [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/36703) which changes one of the challenges and there's a few sitting in the chat room as well. I can create a new issue for tracking the PR's.
