### ISSUE TITLE
Broken Test For "Basic Node and Express - Use the .env File"

### ISSUE THREAD

**Issue by Deadmano** [freeCodeCamp/freeCodeCamp#36445]
The test fails with the following bit of code:

```
const jsonMessage = 'Hello json';
const jsonObject = {"message": jsonMessage};

function jsonHandler(req, res) {
  if (process.env.MESSAGE_STYLE === 'uppercase') {
    jsonObject.message = jsonMessage.toUpperCase();
  }
  return res.json(jsonObject)
}

app.get('/json', jsonHandler);
```

But if you add the return statement inside of the if statement, then the challenge passes... I've double-checked the value I am expecting to return, and it is indeed the expected `message: "HELLO JSON"`.

**Comment by ojeytonwilliams** [comment]
Hey @Deadmano.

This one took me while to puzzle out.  Your code works perfectly, but only the first time it's executed! To be precise, if you submit a project with this code to freeCodeCamp, it will work the first time you run the tests and fail the second time.

This happens because `jsonObject` is global and so when `process.env.MESSAGE_STYLE === 'uppercase'` the message property becomes `HELLO JSON`.  Next time `jsonHandler` is called, if `MESSAGE_STYLE` is undefined, it will return the modified `jsonObject`.

To fix this, just pull the variable declarations inside the function.

Also, please ask on the forums if you have a problem with a specific challenge.  If no-one can help you out there, then definitely file an issue.

I'm closing this, since there does not appear to be a bug.
