### ISSUE TITLE
Challenge "Search and Replace"- Changes to Instructions and Tests

### ISSUE THREAD

**Issue by Jryke** [freeCodeCamp/freeCodeCamp#36520]
Challenge **Search and Replace**

I recently submitted a PR to update the solution to this challenge which brought up a lot of questions in the thread about how this challenge should be set up.  The challenge is based on finding a word `before` in the sentence `str` and replacing it with word `after`.  The real challenge here is not just using the `.replace()` method, but also to match the upper/lower case of the first letter of each argument (word) before performing the `.replace()`.  The objective (and difficulty) of the challenge change depending on the test cases that are used.  Once it is decided what test cases are used, the description of the challenge needs to be made a little bit clearer (or the challenge can be deduced by looking at the tests and the return that is required).  Below are the current tests followed by some of the topics we discussed:

existing tests: 
`myReplace("Let us go to the store", "store", "mall")` should return "Let us go to the mall".
`myReplace("He is Sleeping on the couch", "Sleeping", "sitting")` should return "He is Sitting on the couch".
`myReplace("This has a spellngi error", "spellngi", "spelling")` should return "This has a spelling error".
`myReplace("His name is Tom", "Tom", "john")` should return "His name is John".
`myReplace("Let us get back to more Coding", "Coding", "algorithms")` should return "Let us get back to more Algorithms".

- There is no test case for `before` starting with a lower case letter and `after` starting with an upper case letter.  The tests include the opposite (`before` starting with an upper case letter and `after` starting with a lower case letter).  To make this challenge more complete, I believe that it should be tested both ways.
examples of proposed tests based on existing tests: 
`myReplace("He is sleeping on the couch", "sleeping", "Sitting")`
`myReplace("Let us get back to more coding", "coding", "Algorithms")`

- There could also be test cases that `str` and `before` start with different  upper/lower case (requiring the solution to be a little bit more difficult)?  The tests all have the same upper/lower case for the first letter of the `str` argument as well as the `before` argument.  
examples of proposed tests based on existing tests:
`myReplace("His name is Tom", "tom", "John")`
`myReplace("Let us go to the store", "Store", "mall")`
`myReplace("He is sleeping on the couch", "Sleeping", "Sitting")`

- What should be the standard for the correct upper/lower case of the first letter?  Should the solution match the case of the word in original sentence (`str`), or should it match the case of the word in the `before` argument?  

**Link to the challenge page:**
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/search-and-replace](url)

**Comment by owen-duncan-snobel** [comment]
# Search And Replace Updated Tests:

I went through and created updated tests for the Search And Replace problem. I provided one solution as an example of a way to solve it. I'll address your points below as listed.

- There is no test case for before starting with a lower case letter and after starting with an upper case letter. The tests include the opposite (before starting with an upper case letter and after starting with a lower case letter). To make this challenge more complete, I believe that it should be tested both ways. 

- There could also be test cases that str and before start with different upper/lower case (requiring the solution to be a little bit more difficult)? The tests all have the same upper/lower case for the first letter of the str argument as well as the before argument.
examples of proposed tests based on existing tests:

Tests have been completed, for all the distinct ways it could can be done. There is 8 tests. 

 **4 Cases return uppercase values**

`myReplace("His name is Tom", "Tom", "John")               Should return 'His name is John'`
`myReplace("Let us go to the Store", "Store", "mall")      Should return 'Let us go to the Mall'`
`myReplace("He is Sleeping on the couch", "sleeping", "Sitting")    Should return 'He is Sleeping on the couch'`
`myReplace("Let us get back to more Coding", "coding", "algorithms")  Should return 'Let us get back to more Coding'`

**4 Cases return lowercase values**

`myReplace("His name is tom", "tom", "john")   Should return 'His name is john'`
`myReplace("Let us go to the store", "store", "Mall")    Should return 'Let us go to the mall'`
`myReplace("He is Sleeping on the couch", "Sleeping", "sitting")  Should return 'He is sleeping on the couch'`
`myReplace("Let us get back to more coding", "Coding", "Algorithms")  Should return 'Let us get back to more coding'`

- What should be the standard for the correct upper/lower case of the first letter? Should the solution match the case of the word in original sentence (str), or should it match the case of the word in the before argument?

From what I saw on the original problem the algorithm wants to keep the case of the word being replaced from the string. So it shouldn't match the begin word but matches what is in the original string. 

Here is a solution so that you can look and see if it is within the scope of what is required up until that point to implement the algorithm. [https://gist.github.com/owen-duncan-snobel/2a8212ae08ef7a010bde56b1e5a4b1ce](url)

And here is my attempt at making the problem more clear: 

## Search And Replace
Perform a search and replace on the sentence using the arguments provided and return the new sentence. 

1. First argument is the sentence to perform the search and replace on.

1. Second argument is the word that you will be replacing (before).

1. Third argument is what you will be replacing the second argument with (after).

ex. myReplace("Let us go to the store", "store", "mall") should return "Let us go to the mall".

**Note:**
Preserve the case of the first character in the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"
ex. myReplace("I love to look at the Book", "Book", "dog") should return "I love to look at the Dog".

or  For example if you mean to replace the word "Book" from the original string with the word "dog" from the after string,  but the before string is "book" it should still be replaced as "Dog"
ex. myReplace("I love to look at the Book", "book", "dog") should return "I love to look at the Dog".

*It is to say that case of the before and after are not important unless the before matches the case of that of the word that is in the original string. 

-Owen

**Comment by sauravbhagat026** [comment]
![Screenshot from 2019-07-24 22-55-02](https://user-images.githubusercontent.com/53368998/62313138-a01b5b00-b4ad-11e9-93d7-47b1894e2a7e.png)

**Comment by PartyLich** [comment]
This thread was evidently created to continue the discussion, but there doesn't appear to be any discussion here. 

Is it ongoing elsewhere? 
The merged PR #36366 discussion mentioned a move to project based curriculum. WRT that, is this issue still relevant?

I'm just trying to gain clarity on whether or not there's something I could feasibly contribute to here.

**Comment by ShaunSHamilton** [comment]
From what I can tell, this has since been resolved.
- New tests have been added
- There are cases for `before` being uppercase when `after` is lowercase, and vice-a-versa

As such, I am going to go ahead and close this.

_I cannot find which PR did this, as the blame is lost beyond a point_
