### ISSUE TITLE
Typo on Specify Upper and Lower Number of Matches page

### ISSUE THREAD

**Issue by Jay-snow** [freeCodeCamp/freeCodeCamp#36521]
**Describe your problem and how to reproduce it:**
The word spoiler is misspelled on the guide page linked below. I could not find on github how to fix/pull this page to fix the typo, but I'd be happy to if someone pointed me in the right direction.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/regular-expressions/specify-upper-and-lower-number-of-matches/

![image](https://user-images.githubusercontent.com/25333854/61974685-2408ab00-afb5-11e9-8c1c-aaed248b394f.png)

**Comment by RandellDawson** [comment]
This is a non-issue as the current version on the master branch no longer looks like this (see below).  We will be porting these articles to the forum soon, so you will see the changes there in the near future.  I am closing this, because we are just waiting for the guide to be ported.

![image](https://user-images.githubusercontent.com/5313213/61975223-67efb600-af9d-11e9-80eb-eb66ee99a6cb.png)
