### ISSUE TITLE
[localhost] Can't read buttons on dev 404 page + nightmode

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36652]
with an instance running locally
go to any user profile url (localhost:8000/anyuser)
it will bring up this page...

![Screen Shot 2019-08-20 at 4 12 47 PM](https://user-images.githubusercontent.com/20648924/63384907-7abf9580-c365-11e9-9f73-905f508c9386.png)

can't read the buttons/search

**Comment by raisedadead** [comment]
This is a low priority issue to resolve development experience

**Comment by lizzardarcher** [comment]
Hello, I want to help you with this problem

**Comment by ahmadabdolsaheb** [comment]
thank you @lizzardarcher. please go ahead with proposing a solution or submitting pull request.

**Comment by chezzwizz** [comment]
Since the production site seems to issue an error page that resembles the attached image:

![issue_36652_0](https://user-images.githubusercontent.com/1437965/64054089-553b4480-cb3a-11e9-924f-6351f4321044.png)

this issue may be related to a local setup issue. Check to make sure that your server and client are accessing the proper libraries and extensions. If you are able to do a thorough audit of your setup and files and still find that you are having the issue, try posting some information about what type of server you are using and perhaps some information from your logs that might relate to missing files. Also, be sure that your client side (browser) is loading the provided scripts correctly. Look for errors in the console related to missing or bad libraries.

**Comment by raisedadead** [comment]
Hi @chezzwizz check this: https://www.gatsbyjs.org/docs/add-404-page/

**Comment by raisedadead** [comment]
Gatsby has a middleware that renders a "pre" 404 page. We need to handle the default styles on this middleware page.

**Comment by sfialok98** [comment]
I don't understand the issue completely..
The submit button seems to work fine.
Can someone explain the issue.. And is this the expected page ? 

![fcc](https://user-images.githubusercontent.com/21196697/64195928-52c14d80-cea0-11e9-8908-b1998cd6c439.png)

**Comment by ahmadabdolsaheb** [comment]
@sfialok98, please visit http://localhost:8000/1243er4 locally to view the 404 page.

**Comment by RisingGeek** [comment]
Can I work on this issue?

**Comment by ahmadabdolsaheb** [comment]
Defiantly, @RisingGeek. Please go ahead with describing the solution you have in mind or submitting a pull request.

**Comment by lirikf** [comment]
Hi all,   

#gatsby-focus-wrapper .ais-InstantSearch__root .default-layout button,
#gatsby-focus-wrapper .ais-InstantSearch__root .default-layout input
  {
  color:var(--blue-dark);
  }

Including these lines in client/static/css/bootstrap.min.css seems to fix the problem. However, I'm not entirely certain it doesn't produce side-effects.

**Comment by sangeet** [comment]
Hi @lirikf :

That will affect every button and input under every other page as `#gatsby-focus-wrapper .ais-InstantSearch__root .default-layout` seems to be shared by every other page. I am not sure if it is a good idea to change all buttons and inputs under all pages. 

The source for this page is at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js and I can't seem to find any classes or IDs attached to these elements.

So, with no ID's or classes attached to that component , I am unsure if a clean way to do something like that is possible. Maybe someone who understands this better can comment further on this.

Is changing button color globally under dark mode a viable solution for this?

**Comment by sangeet** [comment]
The following changes in global.css fixes this bug and brings the styling more along the lines of the rest of the website. Since, the colors are based on variables which change based on light/dark theme, this shouldn't break anything on the website (AFAIK, every other button, etc are using the .btn class)

```
button, input[type="submit"] {
  background-color: var(--quaternary-background);
  color: var(--secondary-color);
}

input[type="text"]{
  background-color: var(--quaternary-background);
  color: var(--primary-color);
  border-color: var(--quaternary-color);
}

input[type="text"]::placeholder {
  color: var(--primary-color);
}
```

Is this an acceptable fix?

**Comment by chezzwizz** [comment]
> Gatsby has a middleware that renders a "pre" 404 page. We need to handle the default styles on this middleware page.

If it uses the themes API, then I would imagine there might be some good information at [https://www.gatsbyjs.org/docs/theme-api/]()

There are several mentions of the `gatsby-config.js` file with some path and color references. Perhaps there might be some settings in this file or another file in the components of the theme directory that the 404 page rendering uses.

**Comment by Dnguye92** [comment]
Do you have to ask for permission to work on these issues or can we just submit a PR

**Comment by ahmadabdolsaheb** [comment]
@Dnguye92, you are welcome to work on this issue and submit a pr.
Also, feel free to discuss your solution before submitting your pr.

**Comment by 5hel2l2y** [comment]
how do you activate the nightmode?
