### ISSUE TITLE
[.dev] Make all the section progresses align to the right

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36664]
I personally think that it would be easy on the eye if the progresses are all aligned to the right, since with the current design, I have to scan through each line to fine where the progress is.

<img width="527" alt="Screen Shot 2019-08-22 at 12 37 52 PM" src="https://user-images.githubusercontent.com/25715018/63488783-681a9d00-c4da-11e9-93de-ebace46f9412.png">

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen that is a good idea.
please go ahead if you are interested in implementing this modification

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb Thanks! I'll give this a stab.

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen, apologies. I think I misunderstood your point.

the reason they were brought to the left is that it would be obvious which progress belongs to which block. Since we are minimizing the UI and we do not alternate background color for each row, it would save eye ball travel by having them in the same side. 

I will close this issue for now. however, if you think my response is not satisfactory or another person is experiencing the same issue, feel free to reopen it.

Thank you.
