### ISSUE TITLE
[.dev] Some challenge titles on the map wrap to a new line unexpectedly

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36676]
**Describe the bug**
Some challenge titles on the map wrap to a new line while the parent width is big enough for them to display on a single line.

<img width="818" alt="Screen Shot 2019-08-23 at 8 42 26 PM" src="https://user-images.githubusercontent.com/25715018/63597971-d0f03b00-c5e8-11e9-805e-1e6fb128c8fe.png">

I think it's due to the `max-width: 28rem` rule applied to the `li` tags.

**Comment by xyozio** [comment]
The reason for this is because the `li` element has a `map-challenge-title` class which has `max-width: 28rem;`

![Screenshot from 2019-08-24 09-36-26](https://user-images.githubusercontent.com/53935166/63633550-e0a46980-c652-11e9-9d5d-740e726e1a21.png)

**Comment by xyozio** [comment]
@huyenltnguyen I think that `max-width: 28rem` can be removed. I don't see any reason to keep it.

**Comment by huyenltnguyen** [comment]
@xyozio Yeah we can remove the rule as long as we make sure that the removal doesn't affect anything else.

Feel free to make a PR for this 😄

**Comment by ojeytonwilliams** [comment]
I think it might be nice if the effective left and right margins of the titles were the same.  Currently, because they're (roughly) `<ul><li><ul><li>Title</ul></li></ul></li>` what happens is the left margin is larger, because each `ul` has its elements indented slightly by `padding-inline-start`.

Try `max-width: calc(100% - 80px);` and see what you think.  Obviously it's a bit of a compromise (a few more titles will wrap), but I think that'll look better.
