### ISSUE TITLE
Two articles on same topic in freeCodeCamp/guide/english/sql

### ISSUE THREAD

**Issue by shreyas1599** [freeCodeCamp/freeCodeCamp#36698]
There are two articles which talk about the SQL ```UPDATE``` statement. 
Here are the links to the two articles:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-update-query/index.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-update-statement/index.md

These are redundant. Can I merge these two articles into a single one and create a PR?

**Comment by raisedadead** [comment]
Hi, thanks for the report. The guide is moving away from this repo. We have a few outstanding pull-requests that we need to close and then we would completely remove the guide in favor of an equivalent on the forum.

You should probably wait until then, since the guide on this repo in its current state is not live anywhere, and we would not want to you work on it without reason.

Thanks a lot for your interest in contributing. May I recommend you to take a look at some of the help wanted issues, if those may interest you?

**Comment by shreyas1599** [comment]
@raisedadead It'd be helpful if this is updated in the readme of contributing so that others would not do the same.

**Comment by raisedadead** [comment]
> @raisedadead It'd be helpful if this is updated in the readme of contributing so that others would not do the same.

That's fine. In a couple days, we are removing the guide completely.
