### ISSUE TITLE
Splash effect with theme

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36732]
I have been seeing an annoying splash effect when the default mode (currently night) does not match the user setting mode (most users have set this to light (as part of sign up defaults))

This is going to be the same if we defaulted to light theme and user had night theme.

**Comment by ojeytonwilliams** [comment]
Just a quick explanation: Gatsby builds a static (html) site and then 'hydrates' it with JavaScript.  The problem here is that the static site doesn't know what the user's settings are and one of them is dark/light mode.  What's happening on .dev is the default theme appears initially and then is almost immediately replaced.  If the user's settings aren't the default, they see a flash of the other colour.

I think any solution is going to have to either hide the site for a moment (spinner or whatever) before the hydration happens or use css to smooth the transition.

**Comment by thecodingaviator** [comment]
This is a workaround and something that'll need to be done later but what if we write a line of JS separately in the head of each page. This would fix it for now, but as I said, it's a workaround, not a fix

**Comment by ojeytonwilliams** [comment]
@raisedadead wouldn't the cookies still need js to work? If the problem is hydration, then I don't think cookies will fix it - it would still need hiding. The loader discussed in #36757 will address this, I guess, though I'm not 100% on how that's going to work.

Presumably it would go something like:

Loader (render spinner only) -> cookie parsed (render full site) -> server response (change accordingly)

Finally, as mentioned in #36734 there's already a partial solution using local storage. That should be taken out if we're using cookies.

**Comment by moT01** [comment]
As a side thought - night mode(or whatever is default) isn't available for people without a username or not logged in. Perhaps it could or should be taken out of the db completely and stored in browser storage with a toggle switch in the nav or something.

**Comment by thecodingaviator** [comment]
@raisedadead I thought a bout was hat I  wrote but it won’t wo work sonthats that


About what’s @moT01 said, I second that, I’ve been doing the same for my portfolio website too.

**Comment by raisedadead** [comment]
We are removing the support for storing theme on the user object and instead moving to store theme per device, like most sites Youtube, Twitter etc. 

This would mean some users using multiple devices are affected. But I find that to be a much less of a pain than having to manage the quirks of hydration and all other nuances.

Thanks everyone for your involvement in these issues. Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/36819
