### ISSUE TITLE
Idea: In beta, forward arrow on top of challenge page should only be available if next challenge has already been completed.

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#36731]
In the new beta, I believe that the forward arrow on top of a challenge page should only be available if next challenge has already been completed. This will make it more difficult for users to get the answer to a challenge without thinking about it first.

The next challenge often contains the answer to the previous challenge. This will be _especially_ true once we make live the updated curriculum projects before overhauling the platform. Currently I'm working on making one of the new curriculum projects work with the current platform and every challenge contains the answer to the previous challenge.

Any other thoughts on this idea?

**Comment by raisedadead** [comment]
I think this is a nice idea, the navigation arrows are a feature that we added recently, and have not been released. I am quite inclined to not make it seemingly intuitive.

That said, IMHO, we base our certification on the Academic Honesty Policy. So, if people game the system, we believe that it is a loss in learning on their part. 

I let others chime in though.

**Comment by RandellDawson** [comment]
In the current curriculum, I think only a few sections actually have this kind of progression.  Some of the HTML sections and the Bootstrap and jQuery sections.  Almost all of the JavaScript challenges do not need such a feature and in fact would not allow a user to easily move around to a challenge they would like to learn more about.

I kind of agree with @raisedadead here in that since only the projects and not the challenges are required, we should not force the user to stay on a challenge with the back and forward arrows.  In the new curriculum it makes a lot more sense though.

**Comment by maxiqboy** [comment]
Just some of HTML sections have an answer for the previous , so no need to force the user like that.
If some one wanna cheat, they have many ways to cheat, and it's bad for them.

**Comment by moT01** [comment]
I may be a little biased, but I would prefer it always stay displayed - it makes navigating around a lot easier. Like mentioned, it won't be much of an issue with the current curriculum - it might actually be helpful... there are some areas where the lessons area little out of order and it might be nice to jump ahead to find something out. It makes more sense with the projects - but I think I would still prefer it stay displayed.

**Comment by raisedadead** [comment]
I am closing this, with the common thought being this would not help much. Please feel free to contribute to discussion and re-open if necessary.
