### ISSUE TITLE
Night Life Coordination Example App broken

### ISSUE THREAD

**Issue by conradkay** [freeCodeCamp/freeCodeCamp#36743]
**Describe your problem and how to reproduce it:**
The recipe box demo website does not work because it is using a deprecated yelp api.
**Add a Link to the page with the problem:**
http://whatsgoinontonight.herokuapp.com/
(view network log when searching)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: N/A, server side issue
* Operating System: Ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2019-09-01 18-59-31](https://user-images.githubusercontent.com/24818636/64083255-adb14400-ccea-11e9-95ce-498f9404cee8.png)

**Comment by moT01** [comment]
I think you are looking at the [nightlife coordination app project](https://learn.freecodecamp.org/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app) - and not the recipe box.

**Comment by scissorsneedfoodtoo** [comment]
Just to clarify, the recipe box demo is here: https://codepen.io/freeCodeCamp/full/dNVazZ/

However, it's true that the nightlife coordination project is currently broken due to the Yelp v2 API being discontinued in favor of [Yelp Fusion](https://www.yelp.com/developers/documentation/v3). Is this another project we should get working before the release of Next, @QuincyLarson?

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Yes - we should find a nightlife coordination project built by someone that uses Yelp Fusion and link to that instead. Could you look around and see if you can find such a project? If not, we may need to retrofit the existing code to use Yelp Fusion.

**Comment by raisedadead** [comment]
Bump.
