### ISSUE TITLE
Typo in Challenge - Basic Data Structures: Use an Array to Store a Collection of Data

### ISSUE THREAD

**Issue by clarkngo** [freeCodeCamp/freeCodeCamp#36797]
**Describe your problem and how to reproduce it:**
In the screenshot provided, the property `d` has a property value that is enclosed with `”` instead of `"`.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/use-an-array-to-store-a-collection-of-data/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 77.0.3865.75
* Operating System: MacOS Mojave 10.14.2

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/30854108/64926597-44cecf00-d7b4-11e9-9ab7-fe44e90b3ed7.png)

**Comment by RandellDawson** [comment]
@clarkngo Thanks for reporting, but this bug was fixed in a pull request.  You can [view the current version of the file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/use-an-array-to-store-a-collection-of-data.english.md) to see it has been corrected on the master branch.  Once the master branch is deployed to production, it will show correctly.  I am closing due to just waiting on master to ship to production.

**Comment by clarkngo** [comment]
I have checked the master branch and saw it was correct. However, I didn't know about the shipping stage. Hence, the issue. Apologies for creating an extra same issue. Thank you @RandellDawson.
