### ISSUE TITLE
Instead of Arrow navigation buttons we should use hotkeys

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36795]
At some point we added arrows to be able to quickly navigate through the challenges. While this makes it easier for superusers to step through the challenges, they're not ideal from a pedagogical perspective.

The presence of these arrows will encourage people to just start skipping around the moment they get stuck instead of just being patient and trying to solve the challenge. And once a learner has skipped a challenge, they are less likely to come back and complete it. It's like skipping ahead and reading the last page of a novel - it diminishes your willingness to flip back to the beginning and read the rest of it.

This features is still useful, though. We should trigger this functionality with a hotkey. We should put most of our superuser-type features as hotkeys so they don't complicate the UI or confuse the initial learning experience.

<img width="745" alt="Learn_Basic_HTML_and_HTML5__Uncomment_HTML___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/64925970-92036e80-d7bd-11e9-9d1b-124a1849daad.png">

**Comment by RandellDawson** [comment]
@QuincyLarson PR #https://github.com/freeCodeCamp/freeCodeCamp/pull/35485 added these and closed issue #17509.  I think these arrows are a great feature which allow users to easy go back and forth to other lessons they have already completed also.  This is very useful for users completing the challenges which build upon each other.  A user may get stuck, but remember that a couple lessons back they successfully completed a lesson which could help them solve the current one.  Instead of having to click back on the Learn button and fumble through trying to find the lesson, they can simply back up until they find the lesson and read the challenge and then forward through till they get back to the current lesson.   Users have always been able to skip around.  They just leave the lesson and start a different lesson using the map.

If you still want to remove them, you can, but I wanted to put out my two cents of why I think they are very useful.

**Comment by QuincyLarson** [comment]
Hi @RandellDawson. Thanks for your feedback. I regret that I didn't see that discussion thread earlier or I would have said something sooner.

This arrow feature addresses a symptom of the navigation problem, but not the underlying problem.

That underlying problem is that our challenge navigation is too cumbersome. We should instead work on simplifying that navigation.

Clicking back and forth through a series of dozens of challenges is not a good way to find something. In practice it will just spur people to click through challenges when one of the challenges stumps them, then shrug and leave freeCodeCamp instead of working through the challenges.

We are getting ready to de-index all of Learn from Google. So we won't have to worry about people arriving on random challenges in the middle of the curriculum.

So here's what I propose we do:
1. remove the "Introduction to [topic]" pages from the map (We added these for now-obsolete SEO purposes)
2. make it so we can link to specific sections of the map like this https://learn.freecodecamp.org/#basic-html-and-html5
3. Make the "Basic HTML and HTML5" part of the title  - whatever part comes before the : - into a hyperlink to that specific section of the map
4. Remove the arrow navigation items

**Comment by raisedadead** [comment]
Since this was introduced on master, we will have to address this before shipping out. Any takers?

**Comment by vkWeb** [comment]
@QuincyLarson We have thousands of challenges in our curriculum. Suppose if the user is in 300th challenge and wants to go back to 200th challenge, the hotkeys or the arrow keys are not at all useful in cases like these. We can implement hotkeys for superusers but it's not solving the underlying navigation problem. 

Actually, we should not look at it as a problem because there's no better approach to solve the navigation problem than the current one - going to map and finding the challenge. We can explore possibilities like putting a search box for challenges in the map. But still, the search box won't be that effective. So the current method of navigating challenges looks best to me. 

Since we are landing hotkeys on #36808 for super users, I would recommend highlighting the current challenge. After the user has revised the previous challenges it would make it easy for him to stop on his current challenge. We can do something like this:

![Screenshot (8)](https://user-images.githubusercontent.com/26724128/65284047-22430a00-db56-11e9-9e9e-243fc4347977.png)
