### ISSUE TITLE
Can I translate freeCodeCamp's curriculum?

### ISSUE THREAD

**Issue by aenkirch** [freeCodeCamp/freeCodeCamp#36877]
I began today to translate FCC curriculum (HTML basics) to french, anyone can help of course :)

**Comment by raisedadead** [comment]
Hi @aenkirch thanks a lot for your interest in translating freeCodeCamp to french. 

Unfortunately while we do intend to make freeCodeCamp in more languages, right now we do not have a ETA on that. 

We will begin by making freeCodeCamp available in **Chinese** first to understand the caveats and the streamline the development and the deployment workflow and pipelines.

The next languages to follow would be Arabic, Portuguese, Russian and Spanish in no particular order.

Again we do not have any ETA on any of these. So we would not want your efforts go into something that is not on the roadmap for quite a while.

I am going to keep this issue open for myself, and add more guidelines to clarify this better.

Thanks once again!

**Comment by aenkirch** [comment]
@raisedadead Thanks for all the infos you gave me, that‘s helpful.
However, what you are telling me is that I cannot offer my help to translate FCC curriculum in French only because there‘s no planned date of releasing ?

**Comment by raisedadead** [comment]
You can translate regardless. And we welcome your contributions (we will merge the pull-requests). 

That said, we would probably release the languages listed in my comment above sometime next year. French as of now is not planned at all. So it will be delayed even further.

This is not because we are biased towards any languages, its the limited resources we have to provision instances. I am quite confident as people donate to us more, and we optimise our server costs, we would be able to support more and more languages.

We are extremely grateful for your efforts though :)

**Comment by Arnau-Ninerola** [comment]
@raisedadead So, even if it will take some time to see this efforts because as you said first you'll release these languages. Is it okay if I go ahead and translate it to another language that is not on the list? I know it will be long until implemented, but I am just excited for when that time comes and wish to be the first who does some translation in that language :)

**Comment by raisedadead** [comment]
> Is it okay if I go ahead and translate it to another language that is not on the list?

I would not recommend that, we are not accepting languages not on the list as I mentioned in my previous comment. Thanks for your interest though.

**Comment by Arnau-Ninerola** [comment]
@raisedadead But you said the opposite. That even though it is far from the future, you will merge the PRs.

> You can translate regardless. And we welcome your contributions (we will merge the pull-requests).

**Comment by raisedadead** [comment]
- We are accepting pull-requests in **Chinese**, which we are planning to release next.

- We may accept pull-requests in (high quality translations)

  > The next languages to follow would be **Arabic, Portuguese, Russian and Spanish** in no particular order.

  We do not have any ETA on these releases.

- All other world languages, we will not accept pull-requests for now.

**Comment by Arnau-Ninerola** [comment]
Thanks for clearing it.
