### ISSUE TITLE
[step challenges] Skip button

### ISSUE THREAD

**Issue by sanspace** [FreeCodeCamp/FreeCodeCamp#3690]
In the Waypoints, there's only Go to next step option. There's no previous step to go back if I wanted to.

Browser's back button takes me to the start not the previous page.

Also, a skip button would be great. I had to click 'open link in new tab' every time to go to next step. What if I already had a github account. What if I already finished the chapter and I'm revisiting.

Back / Previous and Skip buttons would be of great help and make a better UX.

**Comment by abhisekp** [comment]
Certainly, that's a missing feature. I hope it will be added soon.
cc: @QuincyLarson

**Comment by QuincyLarson** [comment]
@sanspace Thanks for this suggestion. We are already working on a back button, and a skip button is a good idea.

**Comment by QuincyLarson** [comment]
Back button is complete and functional! We just need a skip button now. Is anyone interested in helping with this?

**Comment by SaintPeter** [comment]
![Sample Image](https://camo.githubusercontent.com/76a1e5d951d8ecf47ee7958fd89988e464618a94/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f416c773370416b6c737852436c3445595966356371764a5a2d55677547524d54673634422f696d6167652e706e67)

**Comment by gasperno** [comment]
I would like to work on this Skip Step button. Can I take this?

**Comment by bugron** [comment]
@gasperno of course.

**Comment by gasperno** [comment]
I would like some suggestions regarding my idea behind Skip Button.
Instead of having an additional button, I would like to enable 'Go to next step' in two cases.
+ If the user profile is linked to Github __or__
+ If the user has already completed the challenge. 

1) Is it the goal of forcing the user to 'open the new tab' is to link their Github profiles?
2) If a user is not linked to github and he/she completed the challenge, should such users be forced to open new tab or not?

**Comment by ltegman** [comment]
@gasperno There's a couple step challenges that force you to open a link and not all of them are for Github, so that would not be a valid reason to let users skip. However, I really like the idea of not having a separate button, but just not disabling the button if they've already completed the challenge.

**Comment by gasperno** [comment]
I noticed that there are the following types of links. 
+ github links (login, profile picture, star fcc repo)
+ gitter link(login, download app, fcc/help)
+ freecodecamp/wiki
+ linkedin
+ commit to non-profit

@ltegman I think it is safe to force all users(logged via github or not) to click 'Open link in new tab' unless they completed the challenge. Even if they are logged in with github, 'Open in new tab' encourages them to set their profile picture,  go to fcc github repository. As you mentioned, all other non github links are definitely important to visit. 
Besides, I think another button is not required as there would be 'Go to next step' button which is always disabled and Skip Step button which is always enabled-- allowing user to do the same function that Go to next step is preventing the user to do.
