### ISSUE TITLE
Custom author field for Ghost

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36920]
We need a custom field on Ghost's author profiles so we can add authors' freeCodeCamp forum usernames.

**Comment by ahmadabdolsaheb** [comment]
We might need to verify the inserted forum usernames to make sure they belong to the author before using them to create topics.

**Comment by ahmadabdolsaheb** [comment]
Ghost won’t have custom fields on users any time soon since It’s a major change with lots of performance implications and very little demand (at the moment).

Ghost team also suggested the followings:

Since discourse has its own concept of [custom fields](https://meta.discourse.org/t/adding-and-editing-user-custom-fields/26498), that would be the logical place to create a link.
alternatively we could create a microservice which talks to both APIs and creates a mapping between them.

**Comment by moT01** [comment]
@ahmadabdolsaheb - I'm not too familiar with the details of ghost, but it sounds like this isn't viable. Close?

**Comment by raisedadead** [comment]
Ghost is pretty opinionated about anything that does not align with their roadmap. I do not see us maintaining a fork of Ghost (because of limited resources).

Closing.
