### ISSUE TITLE
[.dev] Change verbiage on a users own private profile page?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36928]
<img width="616" alt="Screen Shot 2019-10-01 at 3 26 24 PM" src="https://user-images.githubusercontent.com/20648924/65998362-c2efce80-e460-11e9-88a1-205e420c1b3a.png">

This is a picture of my own private profile locally, seems like it should say something like "You have not made your profile public" instead of "mot01 has not made their profile public"

And as I'm typing this, I'm wondering if a profile should render completely if it's theirs, even if it's not public - there's no way for a user to see what their profile would look like if they don't have it public.

**Comment by ojeytonwilliams** [comment]
> seems like it should say something like "You have not made your profile public" 

That does look better.  The next sentence should be something like "You need to change your privacy settings in order for other people to view your profile".

> I'm wondering if a profile should render completely if it's theirs, even if it's not public - there's no way for a user to see what their profile would look like if they don't have it public.

So, they should be able to preview their public profile, basically?

Sounds good.  If going that route, it would be good to emphasise (even more than currently) that their preview is not public.  It wouldn't be good if people went to their preview, saw that it looked right and didn't notice that they were the only people that could see it.

**Comment by raisedadead** [comment]
> "You need to change your privacy settings in order for other people to view your profile".

Yes to this, please open a PR. It seems to have been an oversight.

> So, they should be able to preview their public profile, basically?

I think it's fair to leave the warning on their own pages while showing this page in that case, which means we may need to update the copy for them.

**Comment by moT01** [comment]
> I think it's fair to leave the warning on their own pages while showing this page in that case, which means we may need to update the copy for them.

Can you clarify what you want here @raisedadead? I'm not sure I understand - do we want to keep the page how it is, and just change the two sentences? Or do we want to display their private profile for them?

**Comment by raisedadead** [comment]
Yes. Sorry about being vague last time.

I thought about this a little more and I think we should show the users their own profile only when they are signed in.

Here is what we should achieve at the end of the day:

1. User profiles which are public are visible by default.

2. The settings button is only available if the user is on their own profile page.

3. Users who **are not signed in** and are visiting profiles which are **not public** and are **not their own** are shown the current notice and warnings:

   ![image](https://user-images.githubusercontent.com/1884376/66111341-471f8e80-e5e6-11e9-83df-6a97bc3f9a12.png)

   Note, the settings button is not shown (because user is not signed in).


4. Users who **are signed in**  and are visiting profiles which are **not public**  and are **their own** are shown the same notice as the above screenshot in point 3 with the verbiage stating "You" and the settings button available.

**Comment by ojeytonwilliams** [comment]
> The rest of the their profile is visible as a preview.

So, there'd be a button on their private profile labelled 'Preview profile' and a label 'preview how your profile would look *if* you made it public'.

Clicking that would take them to, say, `/<username>/preview` which shows the preview (and a notice saying that it's currently private).

Something like that?

**Comment by raisedadead** [comment]
> So, there'd be a button on their private profile labelled 'Preview profile' and a label 'preview how your profile would look _if_ you made it public'.
> 
> Clicking that would take them to, say, `/<username>/preview` which shows the preview (and a notice saying that it's currently private).
> 
> Something like that?

Nope it their profiles can be rendered just below the notice like so:

![image](https://user-images.githubusercontent.com/1884376/66114785-2dce1080-e5ed-11e9-8f95-4c4a6cb3665d.png)


Here is the copy:

You have not made your profile public.

You need to change your privacy setting in order for your profile to be seen by others. This is a preview of how your profile will look when made public.
