### ISSUE TITLE
Waypoint Generate random whole numbers

### ISSUE THREAD

**Issue by europaradise** [FreeCodeCamp/FreeCodeCamp#3698]

**Comment by europaradise** [comment]
Waypoint: Generate Random Whole Numbers within a Range
var min = 0;
var max = 9;
function myFunction() {
return Math.random();
  Math.floor(Math.random() * (max - min + 1)) + min
   
}

I need to generate an integer not a decimal.

**Comment by bugron** [comment]
@europaradise thanks for posting this issue!
Actually you're `return`ing `Math.random();` and not the correct value so you're getting decimals instead of whole numbers.
Closing this issue. Feel free to reopen if you still experience problems.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
