### ISSUE TITLE
Quantify donations on user profile

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37023]
- [ ] A "Donations from [username] have helped pay for N hours of freeCodeCamp server time" element on camper portfolios. Reddit uses this to help put the dollar value of donations in more tangible terms.

**Comment by ahmadabdolsaheb** [comment]
Should this be similar to the copy that we have in the donation page, since donating to help people learn is more relatable than paying for servers?

"Donation from [username have helped  provided 250 hours of learning to people around the world each month" 

Additionally, the number of learning hours change based on the number of people using our platforms. What is a good way to reduce every dollar donated to maintain /learn, /news, and /forum into learning hours?

We could keep that number in .env, update it every quarter, and multiply it with the amount donated. 

We could use the same multiplier for donate page message to keep it up to date.

**Comment by raisedadead** [comment]
I think we should have a call with Quincy, about this. Do you mind checking in with him and blocking some time. I am available at both your convenience.

**Comment by ahmadabdolsaheb** [comment]
I asked him about this during another call. 


We could go with with the hours hours of learning and the multiplier that is based on hours of usage which translates roughly  about 50hr for 1 usd based on his last calculation.

let me know if you still would like to arrange an additional meeting.

**Comment by raisedadead** [comment]
> let me know if you still would like to arrange an additional meeting.

If you have a clear path forward, go ahead with the pull-request when you are ready and we can take it from there.
