### ISSUE TITLE
404 error on get hint of code challenge

### ISSUE THREAD

**Issue by dougfabris** [freeCodeCamp/freeCodeCamp#37055]
**Describe your problem and how to reproduce it:**
I realized an error when get a hint on code challenge: "Iterate Through the Keys of an Object with a for...in Statement" in Basic Data Structures of Javascript Algorithms And Data Structures Certification.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 76.0.3809.132
* Operating System: Mac OSX High Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura de Tela 2019-10-06 às 13 13 38](https://user-images.githubusercontent.com/27704687/66272133-2badc100-e83c-11e9-8378-746229ae3a43.png)

**Comment by raisedadead** [comment]
Thanks for the report. 

This should be fixed in the next release of the platform in the upcoming weeks.

For now the guide is available at:

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement

Please reachout to [community forum](https://www.freecodecamp.org/forum) for further help.
