### ISSUE TITLE
Create/Update Completion modals to show a sense of achievement

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37143]
We would like to update the completion modals to show a sense of achievement at key places, like completing a whole section or claiming a certification.

These can then have a one liners (copies of which will be shared later), that say something on lines of:

> Congrats on completing the {achievement name}. And [...] 

These places could be a good place to politely remind users that we are donor supported and they can choose to donate by visiting the donate page. 

We will not show the card form etc. on the modal. We would simply have a CTA for the donate page.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb you can start by adding some placeholder text strings configured in a json object, that can be randomized on the modals. We can get @QuincyLarson to share a comprehensive lists of quotes and other motivational CTA.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, should this be a separate modal or embedded in the completion modal?
Also, are you thinking of a message similar to the upcoming news paragraph and cta, or a list of quotes?

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb With our new curriculum, we won't even show modals when people complete a single test - instead it will just advance them to the subsequent test. We will only show a congratulatory modal when they finish the entire project.

So I think a single type of modal will suffice.

I am going to close this because instead of working on these modals, we can instead use that time to work on the updated design for the new curriculum.
