### ISSUE TITLE
[Beta] Clicking on freeCodeCamp logo on sign in page directs to oauth's homepage

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#37225]
**Looking forward for reporting a security issue:**
Clicking on freeCodeCamp logo on sign in page directs to oauth's homepage.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/signin
2. Click on freeCodeCamp logo

**Expected behavior**
It should direct me back to freeCodeCamp.org.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 Bit Pro
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by lrm25** [comment]
Reproduced.  I'll take this one.

**Comment by lrm25** [comment]
After briefly going through the code, it looks like this page isn't actually in this code.  It looks like an external redirect (AUTH0_DOMAIN) specified in the .env file before deployment, and that the page itself is actually run by auth0.  Therefore, I can't actually fix this issue in this repository.  Is that correct?

**Comment by vkWeb** [comment]
@lrm25 Visit [this link](https://github.com/freeCodeCamp/auth0-templates/blob/8165027db58e4c69557d4c82edd76dd303f244be/pages/login.html#L387-L390) to see the code which needs to be changed, but I am not sure if we should hard code freeCodeCamp.org into the `href` because in production we have a 302 redirect for taking us from https://auth.freecodecamp.org/ to https://freeCodeCamp.org when nav logo is clicked.

@raisedadead Should we do it or we'll have a redirect?

**Comment by lrm25** [comment]
@vkWeb OK, it's in a different subproject.
The problem is that the freeCodeCamp logo link is '/', or the current page minus the queries.  In the case of the dev site, that's freecodecamp-dev.auth0.com.  Unfortunately, without the /login query, there's no data at that subdomain, and auth0's behavior in the case of a non-existent subdomain is to redirect the user back to auth0.com.  If you goof around and type in something like fdkjljfajdfadjfa.auth0.com, you'll see the same behavior.

Would a possible solution be to just get freecodecamp-dev.auth0.com to redirect back to the /login query?  That way, a fix to this issue wouldn't possibly affect the main freecodecamp.com site or the developer install.

**Comment by raisedadead** [comment]
Can't reproduce.
