### ISSUE TITLE
None of the JQuery lessons work

### ISSUE THREAD

**Issue by ArtGuru123** [FreeCodeCamp/FreeCodeCamp#3723]
this seems to be a common problem. none of the jquery lessons work and the directions disappear. How do you fix this?

**Comment by RobRoseKnows** [comment]
Can you please provide screenshots or any errors you may be getting?

**Comment by willmash** [comment]
Same problem here

**Comment by BerkeleyTrue** [comment]
We only officially support the Chrome browser as MS browsers to not have the features we require to run challenges.

@ArtGuru123 which browser are you using?

**Comment by willmash** [comment]
Well that is poor. Would have thought you would support all browsers

**Comment by BerkeleyTrue** [comment]
@willmash You've mentioned Java twice now. We do not use Java at all.

**Comment by willmash** [comment]
@BerkeleyTrue so what if you don't use Java???
Problem remains your code does not run in most browsers. Imho, this is very poor from a site teaching how to write internet based code.
Maybe you should add "Only works in Chrome" or "You must install another browser" to various pages on the site...force everyone else to conform.

**Comment by matty22** [comment]
@willmash You are confusing Java and JavaScript. These are two different programming languages that are not related in any way. NO web browser will run Java. ALL web browsers will run JavaScript. 

Each web browser runs JavaScript differently, so making a web app this complicated run perfectly in each one is an exercise in keeping 40 plates spinning without dropping any. Fixes to get the site working in one browser can break it in others.

For anything development related, you ought not be using IE (because it is not standards-compliant) or Edge (because it's brand new and so has lots of growing up to do) anyhow. Chrome and Firefox offer the best developer/console tools for people working in the web development space. Best to move to one of them now as you will need their superior tools as you get deeper and deeper into development.

**Comment by willmash** [comment]
@matty22 I am fully aware of the differences between java and javascript. I am also aware that Java can run in a browser, albeit with a plugin.

Still, using JavaScript that is not compatible with all (or even just the popular) browser is not a good idea.

So back to the original question "this seems to be a common problem. none of the jquery lessons work and the directions disappear"
If it is such a common problem, why not state that FreeCodeCamp only supports 1 browser...or make it cross-browser compatible. Sure there are differences, but ALL browsers should be able to run the scrips without too much modification.

**Comment by BerkeleyTrue** [comment]
> or make it cross-browser compatible. 

@willmash We are an open source project. If you would like to help us tackle IE that would be awesome.

My comment earlier was in response to why you where mentioning Java.
> Looks like the problem is MS Edge browser. It doesn't apparently do Java

I don't see how ^ is related to this issue, hence why I stated that we don't depend on or require our campers to depend on Java.

**Comment by willmash** [comment]
@BerkeleyTrue Forget me even mentioning Java, I had no idea what was used in creating this site. However, Edge and IE still do not work with this site....and that IS relevant.

Suggesting to customers to change their browser is more likely going to lose the customer. Also some people may not be able to install other browsers.

As for the open source project, you now are aware of an area that could, or even should, be improved.

**Comment by BerkeleyTrue** [comment]
@willmash Thanks for the suggestion. We are aware of the issues but we do not have the resources to support every browser.

**Comment by jbmartinez** [comment]
All the challenges run smoothly on Firefox, which is a standard compliant browser.

**Comment by ArtGuru123** [comment]
Ive been using google or yahoo since ive been using my moms computer. But now that i can use my laptop again the Opera browser works ^-^
