### ISSUE TITLE
Setting input boxes use old colours

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37309]
**Describe the bug**
Some of the input boxes (Email Settings and Your Internet Presence at least) get the old green border when valid inputs are entered.

**To Reproduce**
1. Go to `/settings`
2. Scroll down to 'Your Internet Presence'
3. Enter `https://twitter.com` below 'Twitter'
4. Click on something else to remove focus
5. See the green border.

**Expected behavior**
The border should fit with the current colour scheme.

**Screenshots**
![SettingsInput](https://user-images.githubusercontent.com/15801806/66842077-f8b9aa80-ef6a-11e9-9a16-f1f74f2d8c0b.png)

**Comment by alexyiangou** [comment]
Hey there! I could handle this! :slightly_smiling_face:

**Comment by ojeytonwilliams** [comment]
Thanks @alexyiangou!  Feel free to submit a PR when you're ready.

**Comment by rickysyamsi** [comment]
Hi @ojeytonwilliams.

I had tested this on all input boxes in setting page. Affected input are only in Email Settings and Internet Presence like you described.

The green border is caused by Bootstrap default class `.has-success .form-control`. I also had overridden color changes caused by another Bootstrap default classes which is `.has-error .form-control` and `.has-warning .form-control`.

The focus state was actually also affected but it is harder to see because the border became dark green (which is quite hard to distinguish with dark gray in general). I had fixed that too.

I had tested my fix both on day and night mode. In night mode, border color on normal and focus state is hard to see but it should be correct with `var(--quaternary-background)` and `var (--tertiary-color)`.

I am also sure that accessibility is not negatively affected even though there are no longer border color changes, because the input label is still able to change color correctly based on previous validation result classes `(.has-error, .has-warning, and .has-success)`

**Comment by ojeytonwilliams** [comment]
@rickysyamsi I tried out your PR and it looks great!  Before we go ahead with that I would like your thoughts on a couple of things.  

Firstly, are you getting the appropriate error and warning classes applied?  Testing locally I don't seem to be.  

Secondly, what do you think about inverting the input boxes in night mode?  i.e. dark background + light text to fit in with the rest of the aesthetic.

**Comment by rickysyamsi** [comment]
Thanks for testing it @ojeytonwilliams :)

I realized about those two points you mentioned when I was working with this issue, I intended to create several new issues about it and another accessibility issue.

Yes the client validation for email settings and internet presence is all over the place and need some improvements. Border color for focus state on input boxes with night mode is also hard to see. Inverting some colors looks like a good idea.

Now that this issue is already closed, let's move the discussion to new issues. I will mention you when it have been created.
