### ISSUE TITLE
Basic JavaScript: Replace Loops using Recursion

### ISSUE THREAD

**Issue by gareth-d85** [freeCodeCamp/freeCodeCamp#37408]
**Describe your problem and how to reproduce it:**
I can't get the challenge to pass even when I use the solution from the get a hint page.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion

**Tell us about your browser and operating system:**
* Browser Name: firefox
* Browser Version: 69.0.3 (64-bit)
* Operating System: linux mint 19

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/20612560/67157097-1eee9a00-f31f-11e9-83a8-178393e88534.png)

**Comment by rickysyamsi** [comment]
I can reproduce this with same Firefox version. On latest Chrome, it is working well.

**Comment by gareth-d85** [comment]
ok, so I can get it to work in chrome. but still not in firefox for me.

**Comment by moT01** [comment]
Seems like a bug with firefox - I get this this error...
<img width="357" alt="Screen Shot 2019-10-20 at 9 13 36 AM" src="https://user-images.githubusercontent.com/20648924/67160924-362b8880-f31b-11e9-9cc2-ac117d34da26.png">
`s` should be a valid flag. 

So that's why the solution passed our tests, but is failing in firefox. This will be a problem anywhere else we used the `s` flag. Fortunately, it's not something that is used in many other places, if any.

**Comment by Manish-Giri** [comment]
Open bug report on Bugzilla about the `s` flag - https://bugzilla.mozilla.org/show_bug.cgi?id=1361856

Doesn't look like it will be implemented anytime soon.
