### ISSUE TITLE
All challenge progress lost

### ISSUE THREAD

**Issue by mkamri** [freeCodeCamp/freeCodeCamp#37456]
When I logged in this morning, all progress on all challenges has been lost. With a quick google search it said to sign out to begin to fix the problem, but I cannot find a sign out button anywhere. I can't even find account settings.

1. Click 'Sign in and get started (it's free)
2. All progress has been lost.

No link to account, sign out, anything:
<img width="600" alt="freecodecamp" src="https://user-images.githubusercontent.com/55006708/67253741-52166200-f4b4-11e9-9cd8-e063155aa677.png">

**Comment by CodeFay** [comment]
Hi Mkamri, please try these steps:

1. Click Portfolio in top Right.
2. Click "Update my Settings" 
3. The second button on the top should be "Sign me out of freecodecamp" 

Or you can try clicking the link that the button in step 3 links to: https://www.freecodecamp.org/signout

**Comment by vkWeb** [comment]
@ahmadabdolsaheb This issue is interesting. Actually, this hints that something isn't right with the UX we are trying to deliver with settings nav. If @mkamri can't find settings page then there must be many who might struggle a bit as well. I'm not saying they won't find the settings page. They'll eventually click on portfolio and find the settings page but it'll be "by chance". We need to keep things obvious.

Settings is under portfolio which isn't that intuitive. Let's put "update my settings" on welcome or somewhere near the eyes of the user (it should be accessible from nav like legacy prod.)? 

Since we have shipped the beta so now we have ample of time to think of a fulll-proof solution to this. 
cc @ojeytonwilliams.

**Comment by ahmadabdolsaheb** [comment]
@vkWeb, you are correct. 
the top navigation will be shared across all of our apps, so we need to make the nav items universal and not app specific. we are working on ways to modify the in app contextual navigation to make the UX more intuitive.

**Comment by raisedadead** [comment]
> I logged in this morning, all progress on all challenges has been lost.

We can assure you none of your progress is lost, chances are you got into a different user (probably new) user account than you intended to. User accounts are tied to an email, that is received by us from either Facebook, Google, GitHub or the Email that you enter on the sign in page.

If this email is changed on the social provider you will end up in a different account. 

I recommend you try another email that could be on the original user account. If you are still stuck, send me an email `mrugesh@freecodecamp.org` and I will take a look.

Thanks.

>  Actually, this hints that something isn't right with the UX we are trying to deliver with settings nav.

We are probably not going to add the settings on the top nav. This is the direction we are headed and we are opinionated about it.

The platform is to be considered a set of three applications (more coming soon) and only application will be on the nav.

The portfolio and the settings (or a direct link to signout) will be made available on the learn application soon.

**Comment by mkamri** [comment]
Thank you all for your replies. I was able to use the "Update My Settings" button to sign out, then I signed in using the email that used to be connected to my github. Thanks!
