### ISSUE TITLE
Completion date for bonfires doesn't match local time

### ISSUE THREAD

**Issue by pahlsson** [FreeCodeCamp/FreeCodeCamp#3750]
Noticed last night that the completion dates displayed on the profile page didn't match my actual local date, but rather showed the previous one. The streak calendar got it right (but the Current Streak count is one day less than it should be). I'm in UTC+1 if that makes a difference.

Image shows a few just completed bonfires, as well as the then current date/time.

![unmatch](https://cloud.githubusercontent.com/assets/10562666/10507014/ba4791f4-731d-11e5-8105-29ee1fd2eb25.png)

**Comment by terakilobyte** [comment]
This issue is tied to #2290 . I'm going to close this issue to focus the conversation there.

Currently all timestamps are stored on the server, and the streak is calculated there. The server is located in EST. So, based on time offsets it's possible to miss a day.

For example, if you live in PST:
I complete a challenge on Wednesday at 8 PM, which equates to Wednesday at 11PM EST
I complete a challenge on Thursday at 9:01 PM, which equates to Friday at 12:01 AM EST
This results in a Thursday being technically missed.
