### ISSUE TITLE
Bonfire: Diff Two Arrays - Last Test is Broken

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3758]
@BerkeleyTrue Made commit b4417a4f4d566a62e7d301559f58861d0be9e66d which changes the last test in Diff Two Arrays.

The instructions say:
Compare two arrays and return a new array with any items not found in both of the original arrays.

It doesn't say anything about duplicates.  My working assumption (and the least effort solution) is that duplicates should be retained.  This is how the test was originally written when @abhisekp submitted it.

The Test:
`diff([1, 2, 3, 3], [1]), [2, 3, 3]`
should return `[2, 3, 3]`

Here is my code:
```js
function diff(arr1, arr2) {
  var output = [];
  
  // Check arr2 for arr1's contents
  for(i=0;i<arr1.length;i++) {
    if(arr2.indexOf(arr1[i]) === -1) {
      output.push(arr1[i]); // Not found, throw it in the output
    }
  }
  
  // Check arr1 for arr2's contents
  for(i=0;i<arr2.length;i++) {
    if(arr1.indexOf(arr2[i]) === -1) {
      output.push(arr2[i]); // Not found, throw it in the output
    }
  }
  
  return output;
}

diff([1, 2, 3, 3], [1]);
```

**Comment by BerkeleyTrue** [comment]
Outputting an item twice means your diffing algorithm is defective.

> return a new array with any items not found in both of the original arrays

Notice it states nothing about the index of the item in its array.

If 3 is not in both arrays add 3 two the new array. Since three is already in the array it does not need to be re-added.

in other words since 3 === 3 they are the same item not separate items. This would be a different case if the two items in question where '3' === 3 as these are different items.

Here is a pretty standard but admittedly inefficient solution:

```js
function diff(a1, a2) {
 var a = {}, diff = [];
  for(var i = 0; i < a1.length; i++) {
    a[a1[ i ]] = a1[ i ];
  }
  
  for(var j=0; j < a2.length; j++) {
    if(a[a2[ j ]]) {
      delete a[a2[ j ]];
    } else {
      a[a2[ j ]] = a2[ j ];
    }
  }
  
  return Object.keys(a).map(function(prop) {
    return a[ prop ];
  });
}
```

> This is wrong and breaks everyone's solutions.

We shouldn't be afraid of changing tests because it will break old solutions. The process of adding tests to old challenges is to increase the quality of future solutions. I also didn't make this change lightly.


Lets open it up for discussion.

**Comment by SaintPeter** [comment]
Technically, 3 and 3 are separate items in the array.  There is no discussion of value.

If I'm larry and this is my brother darryl and other brother darryl, the list of people in the room might be:
`[ 'larry', 'darryl', 'darryl', 'bob' ]`
If the brothers leave and bob's wife comes in:
`[ 'mary', 'bob' ]`

Then the diff of the room before and after is:
`[ 'larry', 'darryl', 'darryl', 'mary' ]`
not
`[ 'larry', 'darryl', 'mary' ]`

This is actually very similar to the discussion about "No Repeats Please".  In that case we have argued that, despite the "normal" rules of permutation , where we're talking about "aab" we say that the "a"s are different.  If you're going to argue otherwise for this, then FCC's bonfires are not internally consistent.

I can certainly see an argument for both algorithms, but I would say that with this new test case in place you're asking for the "Unique Differences" between the two, not just the "Difference".  In terms of teaching, I think it is more useful pedagogically for the students to need to realize that you have to compare A vs B and B vs A, rather than doing a concat and removing repeated elements.

**Comment by ArielLeslie** [comment]
Throwing in an opinion from the peanut gallery:  As @SaintPeter points out, I feel like the logic should be consistent with "No Repeats Please" and that duplicates should either be "unique items" or not.  I think either logic is valid, but in either case the instructions should address the issue.

**Comment by BerkeleyTrue** [comment]
This is a faulty example. While we know the word `darryl` represents two different people, in javascript these are identical symbols.

Now if we had two people objects with the name `darryl` then your example would be valid, but then we would be identifying them by some different metric instead of identifying them by value.

Now lets take your example and say instead that someone was recording these values in a ledger and they mistakenly record the same name twice.

`[ 'darryl', 'larry', 'darryl', 'bob' ]`
and then.
`[ 'mary', 'bob' ]`

Sometime in the future someone wants to get the diff of both and is not aware that these names represent people. Now in this case your answer of `[ 'larry', 'darryl', 'darryl', 'mary' ]` would be wrong as it would be obvious that 'darryl' is equal to 'darryl'. Since the only value we have to go against is the name value then we must assume that they are the same item.

**Comment by ArielLeslie** [comment]
That's perfectly valid, but shouldn't the same logic be applied to "No Repeats Please"?  Unless we want to add a lesson "by value" vs. "by reference" and there are exercises to illustrate the difference, changing the expectations seems counterproductive.

**Comment by BerkeleyTrue** [comment]
What does this bonfire have to do with the other.

**Comment by SaintPeter** [comment]
In "No Repeats Please" we treat items with the same "value" (ie: 'a') as being separate for the purposes of generating permutations.

**Comment by dting** [comment]
It's not mentioned that the solution should be a set diff. I feel like the instructions should at least mention it. As stated the criteria for inclusion should just be that the element is not in the other array. It doesn't imply that the result array should be a set of the elements.

**Comment by BerkeleyTrue** [comment]
For the purpose of this discussion lets stick to this challenge. It seems awkward that we need to consider all challenges when solving one problem.

> It's not mentioned that the solution should be a set diff. 

I'm ok with adding a mention that a diff algorithm shouldn't have repeats.

> Unless we want to add a lesson "by value" vs. "by reference"

With strings and numbers there is no reference. None of the tests have anything other than items that would be evaluated by reference.

> criteria for inclusion should just be that the element is not in the other array.

The instructions state

> not found in both of the original arrays.

This is import and differentiates this problem from using something like Lodash which difference method removes those from one to the other.

**Comment by dting** [comment]
> The instructions state

>> not found in both of the original arrays.

I don't believe this implies uniqueness in the returned array. The element is implicitly in one of the arrays already otherwise you wouldn't be checking for that element in the other array. 

Also, the suggested links don't really imply using delete or objects to store values. I guess an answer like this might be conceivable: 

    function diff(arr1, arr2) {
      return [].concat(arr1.filter(function(v) {
        return arr2.indexOf(v) === -1;
      }), arr2.filter(function(v) {
        return arr1.indexOf(v) === -1;
      })).filter(function(v,i,a) {
        return a.indexOf(v) === i;
      });
    }

In any case, it seems like the inputs shouldn't contain duplicates like it was before the change, or maybe adding something like, "Remove duplicates from the result array before returning."

**Comment by dting** [comment]
This also makes the problem very similar to the [symmetric difference](http://freecodecamp.com/challenges/bonfire-symmetric-difference) challenge.

**Comment by abhisekp** [comment]
@BerkeleyTrue When you run `git diff`, does it discard duplicates?
A diff algo shouldn't be used as a filter to get unique values. That's another algo.

**Just a suggestion:-**
It's not a good idea to make a direct fast forward merge commits about test cases. It's better to open a PR for discussion about the change. 
The CONTRIBUTING page mentions about how to contribute (or the workflow!) but the owners themselves don't follow it. :worried:

**Comment by BerkeleyTrue** [comment]
> The element is implicitly in one of the arrays already otherwise you wouldn't be checking for that element in the other array

So you suggest we return it twice? Or ignore the duplicates altogether for the duration of the function? That seems like a faulty algorithm design.

If your lead asked you to design a diff function that let me know which items where not found in both arrays and gave you some data to test with. If you saw this: 
```js
var foo = {};
diff([foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo],[3]);
```
is it okay to return to your lead with a function that returns essentially a combination of both? Isn't that a lot of useless information if I just wanted to know that foo and 3 are not in both arrays? Imagine if the typical data for this function would number in the thousands. I would see an array of thousands of duplicates. 

> Also, the suggested links don't really imply using delete or objects to hash the values.

This is just one solution not necessarily the only solution.

> adding something like, "Remove duplicates from the result array before returning."

Agreed.

> This also makes the problem very similar to the symmetric difference

`Symmetric difference` is quite different. It requires someone to find the differences over n individual arrays. It also has some unintuitive rules like if the item is in an odd number of arrays it is included in the result.

> When you run git diff, does it discard duplicates?

This is the same as using `_.difference`. You are comparing one from the other. This challenge clearly states `compare two arrays` not `compare the first array to the second`.

> Just a suggestion:-
It's not a good idea to make a direct fast forward merge commits about test cases. 

Thanks for the suggestion @abhisekp but when it comes time to push to production and a bug is found sometimes you need to make a fix right then and there. I merged your PR. When reviewing the commits before a push to production I notices the error in the last test case that wasn't covered by the solution you provided. My understanding of the diff challenge is it did not involve duplicates. I discussed it quickly with Quincy and he agreed. A fix was committed. 

> It's better to open a PR for discussion about the change. 

A discussion is what we are having now, @abhisekp.

**Comment by dting** [comment]
If we are asking for the symmetric different of two arrays we should just ask for that to clear up any ambiguity.

**Comment by SaintPeter** [comment]
var foo = {};
    diff([foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo,foo],[3]);

> is it okay to return to your lead with a function that returns essentially a combination of both?

Sure, if that's what the problem/function description is calling for.  I'm not sure that this is a directly comparable example, though, because `foo` really is identical to `foo`, where multiple `3`s, or other strings could be thought of as independent.  You could just as easily say:

     diff([ 1,1,1,1,1,1,1,1,1,2,2,2,2,2,2 ], [3,3,3,3,3,3,3,4,4,4,4,4,4]);

Yes, the diff is just a combination of the two, but that's what diff *means* in this case.

Honestly, I can think of a couple of uses cases for either type of difference function.  I have personally written a diff function that preserves "duplicates" for doing product BOM comparisons.  I used it at my job.

The way I see it there are 3 possible options:
1) Remove the last test case entirely and leave the problem more open to either type of solution. This allows you to do the "two loops" or "two filters" solution or a "three filters" solution or some combination thereof.   Considering that it is the second Bonfire in the Intermediate Bonfires, I think a bit of leeway might be appropriate.

2) Leave the new test as is.  Add some descriptive text as @dting has suggested to make it clear what is required.  I'm not sure that the current position of the challenge as #2 in intermediate 

3) Revert the test to match the original submission by @abhisekp.  Possibly add verbiage to indicate that duplicate elements should be preserved (sort of like 'Sorted Union').  

Of the three, I prefer 1.  I think it fits better with the curriculum and is easier to "teach" to.

**Comment by BerkeleyTrue** [comment]
> Of the three, I prefer 1. I think it fits better with the curriculum and is easier to "teach" to.

Agreed.

**Comment by abhisekp** [comment]
Any instructional changes that simplifies the wording should close #3529

**Comment by edper** [comment]
Is this resolved already. Is it reverting back now to its original test sets which means sans the last controversial test item? Because I just tested it and the controversial last items is still in it.

Additionally, regarding arrays remember that is not just values but also positions/index. So, to treat values as purely symbols in array without regard for its positions/index is to ignore the very nature of arrays.

Secondly, the goal is to get the difference between two sets of arrays which is very clear in the instruction. So, to include that there should be no duplicates with the resulting array (which is NOT explicitly mentioned) is not a good pedagogical strategy because you are trying to let students do two things at once and an IMO an unnecessary permutations of the main goal.
