### ISSUE TITLE
Use getters and setters to Control Access to an Object unclear instructions

### ISSUE THREAD

**Issue by MDutro** [freeCodeCamp/freeCodeCamp#37612]
First I want to thank everyone who works on freeCodeCamp. I have learned a lot from it so far. 

That said, some of the instructions for some of the exercises are quite poor and in desperate need of improvement. A perfect example of this issue is the ES6 exercise "Use getters and setters to Control Access to an Object."

This exercise tells the new user that "Getter functions are meant to simply return (get) the value of an object's private variable to the user without the user directly accessing the private variable." 

However, the solution to this exercise requires that the user create a getter that alters the private variable in the constructor. This may be a perfectly valid use of a getter in JavaScript but it feels very misleading when the user has just been told that a getter is for the purpose of retrieving a variable that is meant to be private (I assume so that the variable is not accidentally altered, hoisted, etc.). If there are, indeed, other valid uses of a getter the exercise should address them or at least provide a link to some external documentation (or something) that explains this.

The solution I am referencing is found here: https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-use-getters-and-setters-to-control-access-to-an-object/301220

The instructions to the user say that he/she should create a class, a getter, and a setter to convert Fahrenheit to Celsius. The instructions do not tell the user that there should be a way to convert from Celsius to Fahrenheit, despite the fact that the solution requires exactly that.

There are clues, but to call them such would be generous at best and I did not recognize them as such until I already knew the solution. For instance, the instructions give the formula for conversion of Celsius to Fahrenheit, albeit with no clear directive attached. Also, there is the "Note" section where the following text appears:

"When you implement this, you would be tracking the temperature inside the class in one scale - either Fahrenheit or Celsius.

This is the power of getter or setter - you are creating an API for another user, who would get the correct result, no matter which one you track."

This note is difficult to parse, grammatically awkward, and terribly unclear. What's all this about "tracking" things, for instance? If this is supposed to inform the user that the class should be able to convert temperatures both ways, it should be entirely rewritten.

I consider myself pretty good at reading! I am a college educated, native English speaker. I hold a law degree - I know how to speak, read, and write the English language. If I find exercises like this confusing and misleading I can only imagine that others, especially non-native speakers, must also be baffled by instructions like these.

Thank you again for your hard work and the valuable service that freeCodeCamp provides. I hope this issue will be taken in the constructive way in which it is intended.

**Comment by RandellDawson** [comment]
> Getter functions are meant to simply return (get) the value of an object's private variable to the user without the user directly accessing the private variable.

@MDutro Thank you for creating this issue.  What do you think about the following change?
> Getter functions are meant to access the value of an object's private variable without the user directly accessing the private variable.  This value can be returned with or without performing any additional modifications to it.

We are open to making the challenge description, examples and instructions clearer to help users like yourself be able to complete the challenges with less confusion.  Feel free to make any other suggestions or reword my suggestion.

**Comment by ojeytonwilliams** [comment]
@MDutro I agree that this challenge is in need of some work.  For one thing, it has a jokey tone that does not really fit with the rest of the site.

While I like @RandellDawson's suggestion, I'd be in favour of a complete rewrite of the description to convey that

1. Getters can provide encapsulation and make function calls look like property lookups
2. Setters can make complicated assignments look like setting properties

The instructions more or less get you to do that, but instead of the property being `temperature` I think it would be clearer if it was `celsius`, so that the user sees that they construct using Farenheit, but then getting and setting is done in Celsius.  The way it is expressed right now it feels like there are three things: Celsius, Farenheit and temperature.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I am not sure about renaming the getter/setter property to `celsius`.   What would the constructor look like?

**Comment by ojeytonwilliams** [comment]
Actually, now that I look at this, I realise just how loose these tests are.  The first solution above works and the completely different solution in the hints works too:
```js
class Thermostat {
  constructor(fahrenheit) {
    this.fahrenheit = fahrenheit;
  }
  
  get temperature() {
    return (5 / 9) * (this.fahrenheit - 32);
  }
  
  set temperature(celsius) {
    this.fahrenheit = (celsius * 9.0) / 5 + 32;
  }
}
```
If we want to teach the fact that get/set can do more than just access/update other parameters, we probably should only solutions like the one in the hints.  Maybe.  What do you reckon?

**Comment by Pallof** [comment]
Is this issue still available?

**Comment by ojeytonwilliams** [comment]
@Pallof it is, PRs are welcome.

**Comment by beasleyDOTcom** [comment]
Hello everyone, 
To get straight to the point, I would like to propose adding the need to name the getter and setter "temperature" to the instructions. 

I think struggle, and digging on your own is an important part of learning. However, I spent 5 days this past week working on this lesson. I did as much as I could to research and learn the concepts needed to pass but still couldn't get it. I kept going back and forth trying again and again, but after a week I gave up and then looked at the answer to try and figure out why the answer I believed should work didn't work. Alas, the only thing I got wrong was that I didn't name my getter and setter "temperature". In hindsight I can see that I could have deduced the necessity by looking at the way it was it was used (thermos.temperature), but that was too much too fast for me.

I guess all I can say is that I've been studying pretty hard and I didn't make the mental leap required to connect those dots. 

Thank you everyone for all that you do. Free code camp has been a huge part of my survival during quarantine. 
Cheers,
 - Beasley

**Comment by bhagerty** [comment]
I also found this question very confusing, but I'm not sure that [the PR from @Pallof](https://github.com/freeCodeCamp/freeCodeCamp/pull/38703) is the best solution (if that PR is even still alive). I would propose a different solution. I think that the issue is more one of substance than one of wording. 

Here's why the problem, as written, is confusing:

- The constructor takes a Farhenheit value.
- The getter should return a Celsius value.
- The setter takes a Celsius value. *It is confusing for the constructor and the setter to take different values.* In what real-world situation would a constructor and a setter take values from different scales (without also allowing you to specify a scale)?

Currently there are two ways to solve the discrepancy between the constructor and setter and pass the tests:

- First, the constructor can convert the input from Fahrenheit to Celsius and store it as Celsius. The getter will always return Celsius, either because at the constructor stage Fahrenheit was converted to Celsius, or because at the setter stage, the input value was Celsius. This was my naive solution.
- Second, the constructor can do no conversion and can store the input as Fahrenheit. The setter, however, can assume that it is getting Celsius input and convert it to Fahrenheit. Since the value will now be stored as Fahrenheit by both the constructor and setter, the getter can convert the value to Celsius in every case. This is the solution in the [official hint](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-use-getters-and-setters-to-control-access-to-an-object/301220).

As I see it, the key point of the exercise is to teach how logic can be embedded inside a class, either in a constructor or in a getter or setter. The complexity arising from the discrepancy between the scale of the input for the constructor and the setter just gets in the way. 

So I would rewrite this substantively so that the constructor and the setter *both* take a Fahrenheit value, and the getter returns a Celsius value. There would still be two possible solutions (do conversion from F to C in the constructor and setter, or do it only in the getter). This would require changing much more than the instructions, including the link to the hint, which would no longer be accurate after these proposed changes. I'm not sure I'm capable of making *all* the required changes, but I would be happy to try if it makes sense. I don't want to step on the existing PR, though

**Comment by Omicron666** [comment]
yes this is currently terrible OOP example
imho, just get rid of conversion and formulas in get/set/constructor
and store/manipulate only with Farhenheit values by default (or Celsius, either way)
rename Class to FarhenheitTemperature
+ eventually add a new method getAsCelsiusValue()

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.

**Comment by ravitejaniddana** [comment]
well explanation my guys
