### ISSUE TITLE
Should the first challenge only focus on teaching the learn UI?

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37702]
Should the first challenge only focus on familiarizing the users with passing tests and the learn UI and we start with tags from the second challenge?

**Comment by ojeytonwilliams** [comment]
It's difficult to be sure what people in general want, but I generally want to get going as soon as possible. I prefer features to be introduced gradually or be left for me  to explore rather than have to complete a tutorial before starting.

I have no idea if I'm typical, though.

**Comment by moT01** [comment]
I'm not sure what to think here. At first, I thought it would be better to have this suggestion as more of an introduction page, where there's just maybe a picture with some text to explain things. Then I thought that maybe a challenge would be better, since it's hands on and users would actually be running the tests and interacting with the interface.

Do we know if people are struggling with this at all? I can't really find much of anything on the forum except a bunch of people who are using IE or Safari and can't pass. And others with bad code. So if they can all figure out the interface, I don't think this is really a problem. But I also am not against adding something like this.

**Comment by ahmadabdolsaheb** [comment]
good points, @QuincyLarson I looked around and it seems like getting the users to learn as soon as possible would increase engagement in the on boarding process.

I will close this issue for now. thanks everyone for your feedback.
