### ISSUE TITLE
Bug in CSS Grid: Use grid-column to Control Spacing

### ISSUE THREAD

**Issue by sascharissling** [freeCodeCamp/freeCodeCamp#37720]
**Describe your problem and how to reproduce it:**
Correct solution lets you not pass test. 
The `grid-column: 2 / 4;` is called in the next challenge and even being refered to as well.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-grid/use-grid-column-to-control-spacing

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version:  78.0.3904.97 (Official Build) (64-bit)
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot 2019-11-08 at 22 58 59](https://user-images.githubusercontent.com/53901545/68513512-7d9e9800-027b-11ea-97a8-f4ea8631af27.png)

**Comment by RandellDawson** [comment]
Do you see any errors in the browser console?

**Comment by ojeytonwilliams** [comment]
This is potentially a rounding error.  @sascharissling could you open the dev console and tell us the width of the iframe with id `fcc-main-frame`?  I tried a bunch of widths and they all passed, but to know we've squashed the bug we need to know how to reproduce it.

**Comment by RandellDawson** [comment]
@sascharissling Also, while in the console, click on the Inspect icon () and click the element with the 5 and then enter each of the following into the browser console (pressing Enter after each line) and post a screenshot of the console results.

```
$('.item2').width() * 2 + 10;
```
```
$('.item5').width();
```

**Comment by sascharissling** [comment]
@ojeytonwilliams size of the element you asked is 466.031 x 474.984

**Comment by sascharissling** [comment]
Also here is a screenshot of everything. @ojeytonwilliams & @RandellDawson 

![Screenshot 2019-11-08 at 23 32 57](https://user-images.githubusercontent.com/53901545/68515098-1f27e880-0280-11ea-9fa2-91e4387d8f25.png)

**Comment by RandellDawson** [comment]
@sascharissling Thank you for the quick reply.  @ojeytonwilliams The current test only allows a difference of `0.01`.  His difference of `0.016` is out of the bounds we allow for passing the test.  How big of a tolerance should we allow?

**Comment by sascharissling** [comment]
you're welcome. i added a screenshot for the `fcc-main-frame`size. 

thank you for being on it :-)

**Comment by RandellDawson** [comment]
@sascharissling Can you test the following two statements in the console?

```
$(".item2")[0].getBoundingClientRect().width * 2 + 10
```
```
$(".item5")[0].getBoundingClientRect().width
```

**Comment by sascharissling** [comment]
![Screenshot 2019-11-09 at 00 13 30](https://user-images.githubusercontent.com/53901545/68516927-cce9c600-0285-11ea-9e59-437382cee1cb.png)

**Comment by RandellDawson** [comment]
Make sure you have first clicked on the preview pane using the Inspector tool.

**Comment by sascharissling** [comment]
![Screenshot 2019-11-09 at 09 05 44](https://user-images.githubusercontent.com/53901545/68525257-21199800-02d0-11ea-83ad-e62bc971661b.png)

**Comment by ojeytonwilliams** [comment]
@sascharissling thanks for taking the time to work through this. Those screenshots are a massive help.
@RandellDawson how about jumping up to 1? That should still avoid false positives since the wrong answers are out by a lot more than that.

**Comment by RandellDawson** [comment]
@lasjorg What are your thoughts on how to validate the two are equal (or close enough) without using a larger tolerance of `1`?

**Comment by lasjorg** [comment]
Hmm, another zoom bug in Chrome. Fails at zoom level 33% and 67% for me. At this point I'm wondering what the underlying problem is.

The current test isn't really testing for the right thing. Using the incorrect values of `grid-column: 1 / 3;` and `grid-column: 1 / span 2;` passes the test as well.


Are we explicitly asking for the use of `2 / 4` here? Or should the use of `span` be allowed? If not, we can just grab the string value from the `gridColumn` property.


```
window.getComputedStyle(document.querySelector('.item5')).gridColumn
// "2 / 4"
```

**Comment by RandellDawson** [comment]
@lasjorg Good catch!  As long as it produces the same effect as `2 / 4` we should not really care.  The original test only allow `2 / 4`, but [this issue](https://github.com/freeCodeCamp/freeCodeCamp/pull/35786) was created when the user thought that `grid-column: 2 / -1` should be accepted also.

It was my PR that created the current test which as you have found allows an incorrect visual effect.  I am open for anything that allows us to test that the final visual effect (below) is achieved.

![image](https://user-images.githubusercontent.com/5313213/68531702-004e4400-02ca-11ea-8496-68254152b633.png)

**Comment by sascharissling** [comment]
Just wanted to say thanks for working hard on the issue. As well this is highly interesting to follow, as i just entered one of the first webdev bootcamps here in germany. This is way too advanced for me and we just started with JS this week but i think I'm learning something from your problemsolving 👍 . 

have a nice weekend  and thanks.

**Comment by lasjorg** [comment]
@RandellDawson There is quite a few combinations that can produce that result. Here are at least some I can come up with.

```
grid-column: 2 / 4;
grid-column: 2 / span 2;
grid-column: 2 / -1;
grid-column: span 2 / -1;
grid-column: -1 / 2;
```

We can check the elements position, but looking at coordinates somehow feels brittle (might not be). Also, is there a reason for not just rounding the width?

I tested this and it gives me the correct results at all zoom levels in Chrome. We shouldn't really need the diff but I just left it in anyway.

```
<script>
const hasCorrectSpacing = () => {
  const contTwoPlusThreePlusGapWidth = Math.round($('.item2').width() * 2 + 10);
  const item5Width = Math.round($('.item5').width());
  const diff = Math.abs(contTwoPlusThreePlusGapWidth - item5Width);
  const positionTop = Math.round($('.item5').position().top) === 111;
  /* To avoid rounding errors the largest allowed diff is set at 0.01px */
  return diff <= 0.01 && positionTop;
};
</script>
```

I would like to point out that this challenge is now also becoming inconsistent compared to the [row version challenge](https://www.freecodecamp.org/learn/responsive-web-design/css-grid/use-grid-row-to-control-spacing) where we only allow for `2 / 4`. That challenge can also be solved using other values that its current test does not allow for (e.g. `grid-row: 2 / -1;`).

**Comment by ojeytonwilliams** [comment]
@lasjorg I'm a bit wary of rounding like that.  Consider the case where `.item2` has width 0.25.  `contTwoPlusThreePlusGapWidth = Math.round(0.25 * 2 + 10) = 11` and `item5Width = Math.round(10.5) = 11`.  That's how it should work, right?  

What if, due to browser weirdness, `.item2` actually ends up as 0.249, but `.item5` remains at 10.5?  Well, now `contTwoPlusThreePlusGapWidth = Math.round(0.249 * 2 + 10) = 10` and `diff` is 1.  

I think the safer approach is just to make `diff` bigger.

**Comment by ojeytonwilliams** [comment]
And, yes, once we're happy about how to solve this, we should port the solution over to the row version.

**Comment by ojeytonwilliams** [comment]
@sascharissling this is almost entirely a discussion about maths and precisely what we want to be testing.  Don't worry about the coding side of things if there's something you want to say about this issue.

**Comment by lasjorg** [comment]
@ojeytonwilliams Maybe your right. I just feel like for that to happen there would need to be a bug in the browser's grid implementation and how it calculates the `1fr`. Otherwise, how would one of the values stay the same?

If we need to account for weirdness from browsers, devices and settings then I don't really see how we can make this test dynamic based on anything the browser has to calculate first before reporting back to us. We would need to limit the scope of the challenge to the grid-column settings we can think of and just do a hard-coded check. Either using the string reported from the `gridColumn` property or using a regex.

**Comment by ojeytonwilliams** [comment]
@lasjorg we already know from things like

![Screenshot 2019-11-09 at 09 05 44](https://user-images.githubusercontent.com/53901545/68525257-21199800-02d0-11ea-83ad-e62bc971661b.png) 
that what browsers report isn't to the greatest precision.  It doesn't mean it's displaying incorrectly (after all it can only be displayed an integer number of pixels wide).

Anyway, I could be wrong, but I think it's okay to assume that browsers won't be out by an entire pixel.  If I am, you can quote me on this next time this issue is raised!

**Comment by ojeytonwilliams** [comment]
It's a good point about 'devices', too. Definitely something we'd want to check on phones and so on.

**Comment by moT01** [comment]
> window.getComputedStyle(document.querySelector('.item5')).gridColumn
// "2 / 4"

I would go for something like that from @lasjorg's comment. 
Here's what I came up with...

```js
testString: const gridStart = getComputedStyle($('.item5')[0]).gridColumnStart;
const gridEnd = getComputedStyle($('.item5')[0]).gridColumnEnd;
const result = gridStart.toString() + gridEnd.toString();
assert(result === "24" || result === "2-1" || result === "2span 2" || 
result === "2span2" || result === "span 2-1" || result === "-12");
```

**Comment by ojeytonwilliams** [comment]
To my mind the main thing is that we always accept `2 / 4`  and always reject everything that doesn't achieve the same effect.  It doesn't matter as much if we reject correct, but weird, answers, since they're probably going to be generated by people that already know how to do it the obvious way.

With that in mind, I like @moT01's implementation of @lasjorg's idea the most and think we should go with that.

It is missing, `span 24`, though. Can anyone think of any more `result`s to check for?

**Comment by lasjorg** [comment]
Here are two more:

```
grid-column: span 2 / auto;
grid-column: auto / span 2;
```


I think checking the strings is likely the safest way to test as well, even if we do miss some weird combo. It's pretty crazy just how many ways there are of achieving the same layout.

Here are the ones we have so far:

```
grid-column: 2 / 4;
grid-column: 2 / span 2;
grid-column: 2 / -1;

grid-column: span 2 / 4;
grid-column: span 2 / -1;
grid-column: span 2 / auto;

grid-column: auto / span 2;

grid-column: -1 / 2;
```

**Comment by ojeytonwilliams** [comment]
> It's pretty crazy just how many ways there are of achieving the same layout.

@lasjorg it is that!  

@RandellDawson if you're happy with this approach, I think we're ready for a PR.

**Comment by RandellDawson** [comment]
@ojeytonwilliams It is not elegant, but it seems like the only way to proceed at this point.  Who wants to create the PR?
