### ISSUE TITLE
Donate Page PayPal Integration

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37783]
- [ ] PayPal integration for subscription and onetime donations.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb I believe you can move over the buttons from the other pages like discussed.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, since a new year has already started. should we redirect year-end-gift to donate.
they are very similar at this point.

**Comment by raisedadead** [comment]
That would be Quincy's call. I will defer to your judgement.

**Comment by ahmadabdolsaheb** [comment]
It seems like we could display the Paypal button regardless of authentication?

**Comment by raisedadead** [comment]
I would like to track the donations, and be able to use it to display motivational and thanks messages on user profile like we plan to.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, instead of having a full server integration where each payment goes through our server to PayPal, we could use [PayPal smart buttons](https://developer.paypal.com/docs/subscriptions/integrate/#4-create-a-subscriptionl) that are paypal's preferred payment method for handling subscriptions.  

 The button would handle the payment and we could update our api accrodingly using a onApproave function that is called once the payment goes through. 

Let me know what you think.

note: [Related npm smart button module with subscriptions example](https://www.npmjs.com/package/react-paypal-button-v2#subscription-example-usage)

**Comment by raisedadead** [comment]
Unless PayPal has a webhook that can deliver a payload to our API, I will not trust any client side code to rely on the logic.

Client side logic is easily spoofed and beats the purpose of the server side validations.
