### ISSUE TITLE
Superblock intros are missing

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37850]
The markdown files for superblocks exist: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/learn/apis-and-microservices/index.md, but don't currently appear in the curriculum map.  Also, the user does not get sent to them when they complete the previous superblock.  Pages are being created for them, but (to my knowledge) nothing links to them:

https://www.freecodecamp.dev/learn/apis-and-microservices/

They probably should either be easier to access or removed entirely.

**Comment by IMHOJEONG** [comment]
How about this way?

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/2fe5b0aa-cca9-480a-b698-60d9625b2f23)

**Comment by RandellDawson** [comment]
Issue https://github.com/freeCodeCamp/freeCodeCamp/issues/37144 already was discussing removing the intros.

**Comment by ojeytonwilliams** [comment]
@IMHOJEONG yep, if we do want to reinstate them, that looks reasonable.  However, I suspect, based on the issue that Randell linked, we're probably going to remove them/merge them into existing challenges.

**Comment by moT01** [comment]
Here's a list of the superblock pages...

https://www.freecodecamp.dev/learn/responsive-web-design/ - stub
https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/ - pretty plain
https://www.freecodecamp.dev/learn/front-end-libraries/ - stub
https://www.freecodecamp.dev/learn/data-visualization/ - stub 
https://www.freecodecamp.dev/learn/apis-and-microservices/ - this one seems well done
https://www.freecodecamp.dev/learn/information-security-and-quality-assurance/ - stub
https://www.freecodecamp.dev/learn/coding-interview-prep - strangely takes you to like an index page with folders of the block sections - weird - looks like it's because it's the only folder without an index.md file.

Seems like these are mostly garbage and can probably be deleted. And find a way to stop gatsby from creating pages for them. Since if the index.md file doesn't exist, you get what the last link there shows.

**Comment by ojeytonwilliams** [comment]
> https://www.freecodecamp.dev/learn/coding-interview-prep - strangely takes you to like an index page with folders of the block sections - weird - looks like it's because it's the only folder without an index.md file.

seems to be problem with `zeit/serve`.  @raisedadead I fixed this locally by removing `"renderSingle": true` from `serve.json`.  I don't know of any cases where we have a single (non-html) asset in a directory that we want to serve, so it should be safe to remove this.

**Comment by raisedadead** [comment]
> so it should be safe to remove this.

OK - Thanks for confirming. I will update the config.

**Comment by raisedadead** [comment]
We should remove the intros, as discussed previously. This would involve some changes to the challenge parser and the gatsby config and pages generation logic etc.

**Comment by ahmadabdolsaheb** [comment]
We might not need to remove the intros after all #38820
