### ISSUE TITLE
GIF in How to Setup fCC locally needs to be updated

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#37907]
The GIF [over here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#how-to-sign-in-when-working-locally) depicts fCC in its old design. Even though I don't think there's anything wrong with it, I guess it should be updated to align with how fCC looks now

![image](https://user-images.githubusercontent.com/34807532/70627002-6e7c8280-1c4b-11ea-87d6-a7a176fe1d95.png)

**Comment by ruchika90** [comment]
Hi, I'll work on this

**Comment by RandellDawson** [comment]
@ruchika90 Just submit a PR when you are ready.

**Comment by ruchika90** [comment]
@RandellDawson When I click the "sign-in" button on the homepage, I see this screen - 

![Screenshot_2019-12-24 Learn freeCodeCamp org](https://user-images.githubusercontent.com/29990697/71431820-b3200900-26a2-11ea-8cc2-2b52a1069920.png)

Is this the expected behavior? Should I be creating a GIF of this?

**Comment by RandellDawson** [comment]
Yes, this is expected behavior.
