### ISSUE TITLE
Demo calculator can't subtract negative numbers

### ISSUE THREAD

**Issue by johntyree** [freeCodeCamp/freeCodeCamp#37942]
**Describe your problem and how to reproduce it:**

The example implementation provided for https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator can't subtract negative numbers, e.g. `10` `-` `-9` should yield `19`, but instead the UI prevents you from typing the second `-`.

**Add a Link to the page with the problem:**

https://codepen.io/freeCodeCamp/full/wgGVVX

**Comment by RandellDawson** [comment]
@johntyree It is not supposed to.  User Story no. 13 is clear about that.  Even Google Calculator will not let you do that.

**Comment by johntyree** [comment]
User Story no. 13 says explicitly "excluding the negative (-) sign", otherwise you couldn't do _anything_ with a negative number as the second operand. `10 - -9` is perfect valid math and also matches User Story 13. They even give `5 * - 5 = -25` as an example.

Also, https://www.google.com/search?q=12+-+-8.

**Comment by RandellDawson** [comment]
>User Story no. 13 says explicitly "excluding the negative (-) sign"

That is so you can make calculations such as `5 * -5 = -25`.  

> 10 - -9 is perfectly valid arithmetic. 

I agree.  It is just not a requirement that the calculator be able to make this calculation. `10 - -9` is the same as `10 + 9`, so that calculation is totally possible.

Also, the Google Calculator example uses parentheses and this calculator project does not require them.

**Comment by johntyree** [comment]
>>User Story no. 13 says explicitly "excluding the negative (-) sign"

>That is so you can make calculations such as 5 * -5 = -25.

Yes, and how does that differ from `5 - -5 = 10` really? It's just a different operator. Everything else about it is the same.

I'm a bit flabbergasted that you think that the intent of User Story 13 is specifically to permit multiplication, division and addition of negative numbers but not subtraction. It says nothing about subtraction being a special case, only that "-" can mean negation. Having a "workaround" is not the point. By that logic we could ban division as well, since you can always multiply by an equivalent fractional value.

More importantly, it's not particularly hard to make a calculator that does arithmetic correctly and this is a learning project intended to teach people about meeting requirements. If we're going to present a demo calculator that _doesn't_ meet the requirements as written, then we might as well not have any and just say, "Make a calculator that behaves like this one." That isn't a bad idea and is also a good skill to build, but since someone bothered to write requirements for this it is clearly not the intent of this project.

If I bought a calculator that couldn't subtract a negative number, I'd return it to the store, wouldn't you?

Google _shows_ parentheses so that people who don't understand order of operations don't get confused. It _always_ [shows all implicit parentheses](https://www.google.com/search?q=12+-+-8+*+3). It doesn't require entering them at all. I obviously didn't enter any.

**Comment by moT01** [comment]
Googles calculator will not let you input a `--`, you can only do a calculation like that by using parenthesis or typing it in to the search bar. So the example does behave the same as that.

I do think there's a slight bug here, although I don't think it's that much of a problem. The tests don't check for the `--` input, so a campers project can account for that or not and will pass either way as long as it can handle `*-`.

Any ideas on a solution @johntyree? Do you want to go fix the project? If you did, we could probably get that changed.

Or perhaps we could change the instructions to something like: "If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the minus (`-`) operator). For example, if `5 + * 7 =` is entered, the result should be 35 (i.e. 5 * 7); if `5 * - 5 =` is entered, the result should be -25 (i.e. 5 x (-5)). If `5 - - 5 =` is entered, your calculator can interpret that as `5 - 5` or `5 - (-5)`" - which is a bit of a mouthful.

**Comment by johntyree** [comment]
Unbelievably, you're right! The google calculator has a ridiculous UX bug that eats the second negative sign. Especially since they allow typing it into the search bar. It's even worse because it works for every other operator and doesn't warn you at all that pressing e.g. "8 - - 2" will silently turn into "8 - 2" and give you the wrong answer. I've filed bug with them as well. 

But ok, so Google made a UX snafu. It happens. We don't have to copy it.

> The tests don't check for the -- input, so a campers project can account for that or not and will pass either way as long as it can handle *-.

This means our tests aren't that great, not that the bug isn't important.

> Any ideas on a solution @johntyree?

Since I'm the one making a stink about this, I will try to find some downtime over the holidays to fix it or recruit a camper to work on it :).

> "If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the minus (-) operator).

This seems worse to me. It would be doubling down on the idea that surprising UX is OK as long someone made it weird on purpose. Strictly in a development sense, that's fine, but if we're trying to help folks become valuable engineers that make good products, then I think training them to say "Well it's broken but I guess that's what the requirements say so whatever" is not great.

**Comment by RandellDawson** [comment]
There are some other things worth considering before spending time "fixing" this "bug".  The other repo which actually has the tests would have to be modified in such a way that older projects would still pass the tests in case the older projects did not allow two `-` operators.  Older projects can not break just because we add new conditions to the user stories.

**Comment by moT01** [comment]
Do the tests need to be modified? Or would it be fine to just change the example project? I don't think new conditions need to be added to the user stories - the instructions say what should happen, the example just doesn't behave like it suggests. I would be fine leaving all the tests and user stories.

> Older projects can not break just because we add new conditions to the user stories.

The test suite didn't exist back when I did all these projects, so none of my old projects pass the tests. I don't think we need to worry too much about projects already submitted not passing anymore. People are unlikely to go back and test their old projects again, and I would be willing to sacrifice that for a better experience going forward.

> if we're trying to help folks become valuable engineers that make good products, then I think training them to say "Well it's broken but I guess that's what the requirements say so whatever" is not great.

The requirements don't say to make a broken product, it just so happens that the example project doesn't quite work right. Which I really don't think is a big deal, but if someone wants to fix it, I wouldn't object.

**Comment by RandellDawson** [comment]
>  I don't think we need to worry too much about projects already submitted not passing anymore. 

@QuincyLarson Based on my conversation with you, I was under the impression that you expect any projects created when the original tests were implemented should not fail the tests now as to not make the user's project look as if it has issues if shown to the public in a portfolio of some sort.

**Comment by johntyree** [comment]
@RandellDawson I think the question is, "is the calculator defined by the user stories or the tests?"

Personally, I don't see the point of the user stories if we're going to say that implementations that don't follow them still "pass." I actually discovered this problem while evaluating a camper's project and trying out each of the user stories in turn, so I don't think leaving it as-is is risk free for people's portfolio's either.

> . I would be fine leaving all the tests and user stories.

I agree. I think the least painful thing to do is to fix the demo project. Having less-than-perfect test coverage is an unfortunate reality. Maybe we could reiterate to campers that the tests aren't exhaustive?

**Comment by RandellDawson** [comment]
>Maybe we could reiterate to campers that the tests aren't exhaustive?

That is a given on all the projects.

**Comment by johntyree** [comment]
Of course. It's the reality of basically all software. But if campers are thinking that their projects are complete as soon as all tests pass, then it would be good to point out that this is not really how things work.

**Comment by moT01** [comment]
> Maybe we could reiterate to campers that the tests aren't exhaustive?

I don't think that needs to be pointed out - it may lead to people intentionally doing less simply because they know they don't have to. The user stories tell people how it should behave, and they should strive for that. If they get lucky and maybe pass one test here or there when their project doesn't behave perfect, I think that's acceptable. We can't write a test for every possible input and scenario.

**Comment by johntyree** [comment]
> I don't think that needs to be pointed out - it may lead to people intentionally doing less simply because they know they don't have to.

I'm not sure I follow. The goal would be to suggest the opposite of this. You should pass all tests, but passing all tests does not mean you are done.

> We can't write a test for every possible input and scenario.

Right. You know that and I know that, but does someone who is new to software engineering know that? I feel like in most educational settings, passing the test means you are done. My understanding was that people are mostly coming to FCC to break into software engineering, rather than experienced folks coming to learn a new technology or two.

At any rate, this is kind of independent from the discussion about fixing the calculator demo itself.

**Comment by jondparadise** [comment]
Thanks for sharing here ojeytonwilliams. I look forward to an update. Particularly in regards to the "5 * - - 5 =". Should that be interpreted as "5 * 5 ="? Or does only the last minus sign count as a negative flag, in which case the actual result should be "5 - (-5)=". Since I would imagine that everyone expects "5 * + 5" to be interpreted as "5 + 5". This whole user story is wonky. Why not just make a requirement for a 'negative flag'. I have done so in my CodePen repo: https://codepen.io/jon-paradise/pen/NWPwbpW
I feel strongly that I should be able to submit that CodePen as an accepted answer to the Certification Challenge.

**Comment by ojeytonwilliams** [comment]
It's reasonably clear that the camper is supposed to satisfy the user stories *and* the tests - the second paragraph is this:

> Fulfill the below user stories and get all of the tests to pass.

I don't think there's a need to spell out the that the tests aren't perfect.  If we want to reiterate anything, it's that they need to satisfy the user stories.

@jondparadise it's tricky.  My opinion is that the user stories should not be changed, since they define what the user should be doing.  People have been making good faith attempts to produce projects that fulfil the stories and so we should not make them 'wrong' retroactively.  However, if a test rejects code that satisfies the stories, then that test should be changed.

**Comment by johntyree** [comment]
For what it's worth, neither the Google calculator nor the little four-function calculator I have in a desk drawer at home have a dedicated `+/-` flag to toggle negativity of the current number. They both overload the `-` button, which is essentially where all the confusion about this project is coming from.

As far as teaching exercises go, I'm in favor of _not_ adding a dedicated `+/-` toggle button, since there are both real-world examples without it and it simplifies the input handling so much that the project becomes a little boring. Also, it would be a pretty drastic change and probably require forking the project to avoid breaking existing solutions.

I feel like the user stories are actually pretty clear. `-` can mean minus or negative and your calculator should do math correctly. That means negative numbers are first-class citizens. Right now, the only thing that is missing is negative subtraction.

**Comment by moT01** [comment]
Thanks for reporting, but I am closing this as stale. If someone wants to try fixing this up, feel free.

**Comment by johntyree** [comment]
Is it stale because the bug is no longer present or because no one has fixed it in the span of a few months?

**Comment by moT01** [comment]
It's stale because there hasn't been any activity on the issue in 9 months. The issue is likely still present.

**Comment by moT01** [comment]
Want to review this @johntyree https://codepen.io/moT01/pen/GRZBLMr?editors=0010 ?

**Comment by johntyree** [comment]
Looks good to me. Thanks for fixing it! :)

**Comment by nhcarrigan** [comment]
@moT01 I took a peek at the CodePen and it looks good to me as well 🙂

**Comment by Sky020** [comment]
@moT01 The CodePen you linked resolves this issue, and passes all tests 👍

**Comment by scissorsneedfoodtoo** [comment]
@johntyree, thanks for opening up this issue and kicking off this discussion. Like some others have suggested, I'm also in favor of leaving the user stories and tests the way they currently are. 

But I don't see a problem with updating the project. If anything, subtracting negative numbers can be seen as a hidden feature. If campers discover it and want to implement it themselves, then they can definitely do that without it being a strict requirement.

@moT01, checked out your CodePen and everything LGTM. :+1: :+1:

**Comment by johntyree** [comment]
Sounds good to me. As I mentioned before, the user stories as written already cover this as far as I'm concerned.

**Comment by brimarq** [comment]
While trying to learn TypeScript, I decided to convert [my old calculator project](https://codepen.io/brimarq/full/ejXgNG) for some fun/practice. Imagine my surprise when it no longer passes all of the tests anymore, as they have been changed since I coded the project. 

So... that sucks. 

I guess I'll be removing the test suite from that pen, as it's certainly no longer a "selling point", if it ever was at all. As far as I'm concerned, my calculator isn't broken - the tests are. My project works just fine and has a "+/-" button to solve the negative numbers issue similar to [this example](https://codepen.io/no_stack_dub_sack/full/jrxpKP/) (which, coincidentally, would fail the current test). I can't be held responsible for moving goal posts after I'm done.

**Comment by moT01** [comment]
Sorry to hear that @brimarq - A number of my projects don't pass the tests anymore either. I think I made some of them before the tests existed. I think the "selling point" would be if it's a good product - not if the tests pass. Certainly doesn't hurt if they do though. If you earned the certificate using that project, it will not be affected.

I don't think this particular issue is what broke the tests for your project - I believe we ended up just updating the example project from this issue, not any tests. If I had to guess, I think they've probably not been passing for a while. The last changes to [the tests in that file](https://github.com/freeCodeCamp/testable-projects-fcc/commits/5f75b129fda5b5d125251e1a3fc2cec2ab788857/src/project-tests/calculator-tests.js) were back in 2019. I will try and take a closer look at your project and the tests to see if there's a bug with the tests.

**Comment by brimarq** [comment]
Well, @moT01, I finished the project [back in 2018](https://www.freecodecamp.org/certification/brimarq/front-end-libraries) (holy crap, has it really been that long?!?), and I'm sure the tests must have changed since then. I wouldn't have submitted my project (or, any of them, for that matter) unless it passed ALL of the tests at the time. I even remember having to write some extra, arguably unnecessary code on a couple of projects just to cover some buggy test cases for that very reason. I would have considered it to be 'cheating' otherwise. Maybe that's why it kinda gets under-my-skin that it fails now after having been so careful to make it pass. Know what I mean?

All things considered, it's really not *that* big of a deal. I wouldn't have even noticed had I not dug it up again for some TypeScript practice. Actually, I'm a little horrified at some of the code I wrote back then. LOL  I hadn't even considered that the tests would fail in the future. I'm almost afraid to check my other projects - I guess I should remove the test suite from those, too, just-in-case.

**Comment by moT01** [comment]
I know exactly what you mean. Went through all of that myself. 

If you're looking for some more typescript practice, we are in the process of migrating our codebase to use it 😄 Here's [the issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/42256) - I would be willing to help you out if you have any questions.

**Comment by johntyree** [comment]
You're not responsible for moving goal posts because no one asks you to maintain your old work, but I don't think freecodecamp is responsible for maintaining backwards compatibility forever when bugs are discovered either.

At any rate, this is a great illustration of why continuous testing is basically essential if you need things to keep working continuously.
