### ISSUE TITLE
Parsing of translated challenges

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37955]
Following on from the discussion in https://github.com/freeCodeCamp/freeCodeCamp/pull/37911 and conversations with @RandellDawson, I'm just writing it up for visibility.

Randell's idea is to simplify the process of keeping multiple translations in sync by modifying how challenges are parsed.  Instead of each language being independent, we could use the English markdown file as a template and add translated text from the other language's file.  That way the code (tests, seed and solutions) could be held in the English version and made available to all the other languages.

This would be achieved by modifying the `challenge-md-parser` for non-English languages.  It would first parse the English version, creating a challenge object, and then parse the other language and replace the challenge objects `description`, `instructions` (and the test `text` strings) with translated versions.

**Comment by thecodingaviator** [comment]
That said, we'd have a lot of merge conflicts. We'll have to wait 21 days to close each PR if they get a merge conflict and that'll take up a lot of time IMHO

**Comment by ZhichengChen** [comment]
So, we should only translate the localeTitle, description, instructions and testString, right? @RandellDawson @ojeytonwilliams

**Comment by RandellDawson** [comment]
Not testString.  You should translate text of each test.

**Comment by ZhichengChen** [comment]
@RandellDawson Oh, yes, it's text need to be translated, and one more thing, if we don't translate the challenge seed, it may hard for the user to understand the challenge, because the description is base on the challenge seed. So, if it is possible to translate the challenge seed and make sure do not break the testString. thanks.

**Comment by RandellDawson** [comment]
@ZhichengChen No seed code should be translated, because we want to use the same seed code across all languages.  This would allow the non-English languages to have the following structure:
````
---
id: Unique identifier (alphanumerical, MongoDB_id)
title: Challenge Title
challengeType: 0
videoUrl: 'url of video explanation'
localeTitle: translated title goes here
---

## Description
<section id='description'>
A Description of the challenge and what is required to pass
</section>

## Instructions
<section id='instructions'>
Instructions about what exactly needs to be done.
</section>

## Tests
<section id='tests'>

``` yml
tests:
  - text: test 1 text goes here
  - text: test 2 text goes here
```

</section>
````
The one thing we will need to do is to come up with a standard comment translation lookup table (hopefully small), so that any comments in the the challenge seed code would be translated at render.  For example, you might see the following in several places in the challenge see code.
```
//Only change code below this line


//Only change code above this line
```
The parser would need to be able replace any comments based on a lookup table.  My suggestion is that we move to a common format syntax using `/*   */` and are always on a separate line. It would be an object that looks something like the following:
```
var commentTranslation = {
  '/* Only change code below this line */' : {
    arabic: '/* translation goes here */',
    chinese: '/* translation goes here */',
    .
    .
    .
  },
  '/* Only change code above this line */' : {
    arabic: '/* translation goes here */',
    chinese: '/* translation goes here */',
    .
    .
    .
  }
}
```
Actually, if we parse the comment out and trim any white space,  then the property names would not even have the `/*` or `*/` in them.

@ojeytonwilliams Could we use the linter to check that any comments in the seed code must use the `/* */` syntax I mention above?  Also, the tests would need to be written so if any comment found in the seed code which does have a corresponding translation, would fail with applicable message.

**Comment by ZhichengChen** [comment]
@RandellDawson Thank you, I got it.

**Comment by RandellDawson** [comment]
To validate the tests pass for all challenges, make sure to assign `chinese` to the `TEST_CHALLENGES_FOR_LANGUAGES` variable in the `.env` file before running `npm run test`.

Only challenges with solutions will even attempt to test.  

Once we your recent batch of PRs merged, I will run a script to check for any missing `text/testString` pairs.  There were a lot of changes in the English versions back in October and even in the last month, so some challenges may be missing some tests and some challenges may have some tests that no longer apply and some challenges tests may have changed.  I will create an issue which details all the differences or each challenge and then you or someone else can create PRs to bring the Chinese curriculum up to date with the English version.  

I will also run another script that will replace all the solutions in the Chinese challenge files with the latest version in the English files, so that we can truly validate the Chinese tests are not broken (by someone accidentally modifying something by mistake).

In the mean time, we will continue to figure out how to have the non-English versions use the English  seed code, solution(s), and textStrings, so that we can eventually get rid of all of the extra content in the challenge files.

**Comment by ZhichengChen** [comment]
@RandellDawson Thank you. I have pushed a new commit in #37911 , could you please help me to review the structure of the markdown file? all the translate have been reviewed.

**Comment by RandellDawson** [comment]
@ZhichengChen Until we have a working solution as described above in this issue, you can not remove the challenge seed code, solution(s), Before/After test sections, or the `testStrings`.  This issue is to discuss how we will go about implementing a solution so you do not have to add these sections.

**Comment by ZhichengChen** [comment]
@RandellDawson OK, I will revert the commit.
