### ISSUE TITLE
Toxicity when contributing to FreeCodeCamp

### ISSUE THREAD

**Issue by SimonSiefke** [freeCodeCamp/freeCodeCamp#38014]
I want to support the FreeCodeCamp by submitting Issues and Pull Requests but I don't feel comfortable doing so anymore. 
When I asked for a source for something which seemed to me like wrong information, the pull request was promptly closed without any further discussion.
When gave my opinion on an issue I was told that I should take it away from any discussion. It's fine if there is a disagreement and someone says that they disagree, but it's not fine to tell someone "Go Away. You're not welcome here. Your comment is irrelevant" - which is what the whole thread in #37988 feels like to me.
I don't think it should be this way. 

Kind Regards
Simon Siefke

cc @QuincyLarson

**Comment by moT01** [comment]
Sorry you feel that way @SimonSiefke, your contributions are certainly welcome. Seems like your PR was closed because it wasn't the approach we were looking for. The issue looks like it's still open for discussion and something can still potentially be done with it.

> it's not fine to tell someone "Go Away. You're not welcome here. Your comment is irrelevant" - which is what the whole thread in #37988 feels like to me.

What you feel and what was actually said are two different things. I see some disagreements, but not anyone telling you any of those things - it seems mostly polite to me, but not very productive and got off topic.

I do know that issues aren't for sharing your frustrations with other contributors, so it should not have been opened. Thanks.

**Comment by raisedadead** [comment]
Hi @SimonSiefke thanks once again for your feedback. 

I am a staff member here at freeCodeCamp.org,  I look after the technology stack and I am also responsible for all the Open Source projects by the org on GitHub. I am at the liberty of speaking on the behalf of my team, and I believe all the moderators active on freeCodeCamp.org

Our community is built on the foundation of friendly, welcoming and open values. [Our code of conduct](https://www.freecodecamp.org/news/code-of-conduct/) (hardly takes 2 mins to read) reflects and enforces that. Our 3K+ contributors especially a majority of them being first timers to open source know that. 

I am sorry if you feel otherwise. However, we want to make it absolutely clear that we are not sorry for any of the actions on the pull request or the issue thread.

We remain objective while making a decision. And as staff or mods we do not things lightly.

As community leaders we have been well seasoned in agreeing to disagree, and especially when we disagree on something. 

As per our discretion the PR was welcome but rushed, we would not have merged it as is without additional discussion on the issue thread.

The issue threads are not a place to debate. It's a place to propose constructive solutions. As per our discretion we found it to be going off topic, and we decided to request for additional comments and interest from the community.

We found, even after that you proceeded to comment that we found again at our best judgement to be off topic. 

We find this issue thread to be off topic as well and a waste of everyone's time than helping provide the community the resources it needs.

You are welcome to write to us at these emails: `dev@freecodecamp.org`, `team@freecodecamp.org` and `quincy@freecodecamp.org`
