### ISSUE TITLE
[guide] images are not loading 

### ISSUE THREAD

**Issue by ichbinkiana** [freeCodeCamp/freeCodeCamp#38067]
Hello,
I wanted to tell you that images that are in the SQL tutor on your website are not loading for me. I’ve tried to open it with different browsers and devices but none of them solve the problem. ( I used firefox and chrome - both the latest version - on Ubuntu 19.10 and iPad OS ).

![Screenshot from 2020-01-14 19-24-11](https://user-images.githubusercontent.com/24723210/72359416-7d9b9800-3703-11ea-9396-96ca0727cbca.png)

**Comment by ojeytonwilliams** [comment]
Hi, @ichbinkiana, thanks for the report.  Could you link to the page that's not working?

**Comment by ichbinkiana** [comment]
there is not just one page. 
Here are the ones I've found : 
https://guide.freecodecamp.org/sql/sql-alter-table-statement
https://guide.freecodecamp.org/sql/sql-and-operator/
https://guide.freecodecamp.org/sql/sql-avg-function/
https://guide.freecodecamp.org/sql/sql-between-operator/
https://guide.freecodecamp.org/sql/sql-count-function/
https://guide.freecodecamp.org/sql/sql-create-index-statement/
https://guide.freecodecamp.org/sql/sql-create-table/
https://guide.freecodecamp.org/sql/sql-create-view-statement/
https://guide.freecodecamp.org/sql/sql-date-functions/
https://guide.freecodecamp.org/sql/sql-drop-view-statement/
https://guide.freecodecamp.org/sql/sql-syntax/

**Comment by RandellDawson** [comment]
@raisedadead I assume we are not going to fix these as the guide is no longer supported?

**Comment by raisedadead** [comment]
I will defer to Quincy on this, he was working on something a few weeks ago to move the articles on forum and news, I think before we could add 301s. If anything the outdated guide articles are probably contributing to the bounce rate.

/cc @QuincyLarson

**Comment by QuincyLarson** [comment]
@ichbinkiana Thanks for spotting this and alerting us to this. 

We have indeed copied articles over to /news and I've fixed the images there. We are planning to deprecate the Guide completely in the coming months and 301-redirect the guide articles to their /news equivalents. This will provide better usability, accessibility, and faster page loads (since we'll be able to have AMP versions).

In my humble opinion, it's not worth going back to fix the broken images on these guide articles since we may only be a month or so away from full redirecting the guide.
