### ISSUE TITLE
How to run project locally

### ISSUE THREAD

**Issue by AshNaz87** [freeCodeCamp/freeCodeCamp#38084]
Apologies if this has been answered already...

Is there any documentation which outlines how to run the repo locally? If not, it would be super useful.

Thanks!

**Comment by AshNaz87** [comment]
Apologies if this has been answered already...

Is there any documentation which outlines how to run the repo locally? If not, it would be super useful.

Thanks!

**Comment by AshNaz87** [comment]
Actually found the instructions in `docs > how-to-setup-freecodecamp-locally.md`

Perhaps there could be a section in the README?

**Comment by ahmadabdolsaheb** [comment]
Yes, those are the instructions.

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md

Please try to follow the instructions step by step and let us know if you have problems with running the repo locally here: https://gitter.im/FreeCodeCamp/Contributors

I will close this issue for now, please feel free to reopen if you think this issue was closed by mistake.

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb No worries

I'll create a PR for the README

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb Submitted a PR for this and other small tweaks in documentation
Think it's issue #38086
