### ISSUE TITLE
Tests for project completion not working

### ISSUE THREAD

**Issue by dotEsuS** [freeCodeCamp/freeCodeCamp#38118]
**Describe your problem and how to reproduce it:**
It is currently possible to pass all tests with any random link. It doesn't even have to be a glitch link.
Try facebook.com or github.com and all tests will pass.
I've only tested this with the apis and microservices projects.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79.0.3945.130 (Official Build) (64-bit)
* Operating System: Ubuntu 19.10

**Comment by raisedadead** [comment]
This is known and expected behaviour. The submitted links are public and available on the user profile when certifications are issued and made public.

Anyone sharing their certs with others with such links will get flagged by community and this is covered under the honor based academic honesty policy.

Thanks a lot for your report.
