### ISSUE TITLE
Show Local Communities to Users

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp/freeCodeCamp#38115]
## Is your feature request related to a problem?
As a **Local Community organizer** (work in [ChengDu, China](https://fcc-cd.tk/) for 3 years), I found that many **Online Users** don’t know there is a **FCC local community** in their city, let alone contact us.

## Describe the solution you'd like
We may show a list of **nearby FCC communities** to online users based on their **IP addresses** (request permission to locate in Web browser without Private information saved).

A **Community Registry** sub-system is needed for this feature.

## Additional context
https://devdocs.io/dom/geolocation_api

**Comment by too** [comment]
how about a small backend for it? or is there one already?

**Comment by ahmadabdolsaheb** [comment]
That was the original plan, then we updated our community directories to implement that. 
It turned out a large number of our facebook communities were not updated and most of the activity were in community management  websites such as meetup.

When meetup introduced fees,  we started an open source community management tool called chapter. https://github.com/freeCodeCamp/chapter

I would think if there is going to be a geo community finder, it would be implemented through chapter.
