### ISSUE TITLE
Add 2019 to top contributors profiles

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38138]
my profile has this on it...
<img width="588" alt="Screen Shot 2020-01-30 at 12 33 04 PM" src="https://user-images.githubusercontent.com/20648924/73479056-d3f01400-435c-11ea-9d77-e13c2774236d.png">

2019 should be added to it and to the other top contributors profiles. Not sure if that is manually added to the database or what.

**Comment by raisedadead** [comment]
Hi @QuincyLarson do we have all the usernames for the Top Contributors for 2019.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for your patience. Yes - here is my best guess at the /learn accounts for each of the 2019 top contributors' accounts. Note that not all of these will work and some may still be set to private: https://gist.github.com/QuincyLarson/e2a6e957cf9c7412ff9ea0956ff9ba3d

**Comment by raisedadead** [comment]
Thanks for the list, I will add the years to these profiles. 

Once I am done, I will let you know, so that you can post this on the forum. Anyone we missed should then be able to reach out to us and I can do the update on their profile.

**Comment by raisedadead** [comment]
![image](https://user-images.githubusercontent.com/1884376/76142413-79508300-6093-11ea-97af-42409124457c.png)


### 🎉 Congratulations and Thanks 🎉

**Comment by RandellDawson** [comment]
@QuincyLarson @raisedadead It might be nice to add a hover-over and/or link over the `Top Contributor` verbiage that links to a page explaining what it means to be awarded this honor. 

I say this because right below this designation, the heat map shows.  My current heat map looks below, because I have finished most of the challenges and do not complete very many (if any) each day.  Some might think the Top Contributor and the heat map are related.

**Comment by raisedadead** [comment]
Sure, please create and tag a help wanted issue.

**Comment by moT01** [comment]
Looks good @raisedadead - what do you think about putting the years in an "array" ...
<img width="416" alt="Screen Shot 2020-03-07 at 11 24 06 AM" src="https://user-images.githubusercontent.com/20648924/76147872-552a7d00-6066-11ea-9130-c14ccb070443.png">
