### ISSUE TITLE
Error on running npm run develop

### ISSUE THREAD

**Issue by rishipurwar1** [freeCodeCamp/freeCodeCamp#38141]
I tried to clone the freecodecamp repository. I followed all the instructions given in the readme. But when I ran the npm run develop it gives me error look like this(Error: Cannot find module 'freeCodeCamp\client\node_modules\@webassemblyjs\wast-parser\lib\index.js'. Please verify that the package.json has a valid "main" entry.
After this error, I installed two npm packages @freecodecamp/challenge-md-parser and @webassemblyjs/wast-parser 
But, this error is still showing.
I cloned this project locally.
So, please help me with this issue.
Thank You

**Comment by ojeytonwilliams** [comment]
Hi @rishipurwar1, I recommend running through the [troubleshooting tips](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#troubleshooting), if you have not already.  If `npm run clean` does not work, use `npm ci` then try the commands again.

 However, I'm closing this because Github issues are for tracking problems with the site.  Please ask on the forums (where more people will see your question) if you're still having trouble and, if people there determine that there is a broader problem, don't hesitate to re-open this.

**Comment by rishipurwar1** [comment]
Ok! Thanks

**Comment by ojeytonwilliams** [comment]
No problem.  Good luck!
