### ISSUE TITLE
Broken Images In The Algorithm Guides Section - Images Coming From The FCC Forum?

### ISSUE THREAD

**Issue by benjaminthedev** [freeCodeCamp/freeCodeCamp#38189]
Hi folks, 

It seems that there are broken images in the Basic Algorithms Scripting guides section.

For example, if you go to [Boo Hoo Algorithm](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/boo-who) 

You will see broken images.

Another example is the speech balloon:

![Screenshot 2020-02-10 at 07 40 34](https://user-images.githubusercontent.com/14097672/74129922-b16dbe80-4bd8-11ea-90b9-feec9a679205.png)

It looks like the images are coming from the forum and could be an SSL issue as I tried to open and image in a new link and this is what I got:

![Screenshot 2020-02-10 at 07 42 22](https://user-images.githubusercontent.com/14097672/74130013-eaa62e80-4bd8-11ea-88dd-336977cf435f.png)

Hope it can get fixed soon.

Cheers!

**Comment by raisedadead** [comment]
@QuincyLarson now that we are in the process of deprecating the guide, can we have a standard message that we can use to point users about this and close issues like this?

**Comment by QuincyLarson** [comment]
@benjaminthedev Thanks for reporting this. 

@raisedadead Yes - how about the following for a standard response:

Thanks for reporting this.

We are in the process of improving all the guide articles and migrating them over to /news. (The Guide codebase and its many contributions will remain on GitHub.)

So rather than spending time to fix this specific issue, we will stay focused on finishing this big migration as fast as possible.
