### ISSUE TITLE
Status bar kudos

### ISSUE THREAD

**Issue by Jelliebeans** [freeCodeCamp/freeCodeCamp#38237]
**Is your feature request related to a problem? Please describe.**
This is just a humble suggestion. When we finish challenges, the status bar pops up and there is a new kudos above it. Kudos are fine and encourage learning, but I've noticed these are different from standard kudos and may incorporate pop culture. I actually wouldn't mind it but a couple of the the ones given have been distracting and/or questionable. It could be my lack of knowledge in the context of the lines, but I actually looked one up out of curiosity and it made me feel a bit uncomfortable. 

**Describe the solution you'd like**
It would be nice if we had the option to turn the kudos, or even the status bar on/off just so we didn't have to see it after each challenge if we so choose. 

**Describe alternatives you've considered**
There really isn't an alternative aside from another site, but I happen to really enjoy this one!!

**Additional context**

![image](https://user-images.githubusercontent.com/61239479/74844271-d4902080-52f2-11ea-82c3-634597a81853.png)

**Comment by ojeytonwilliams** [comment]
Hi @Jelliebeans! Thanks for bringing this to our attention. There's been a bit of discussion about the quotes recently: #38200, but that's more an attempt to clean them up, rather than disable them entirely.

Adding an option to disable them is certainly possible, but I think @QuincyLarson will need to decide what the best course of action is.
