### ISSUE TITLE
Broken link from the forum

### ISSUE THREAD

**Issue by BoyeongYoon** [freeCodeCamp/freeCodeCamp#38338]
## **Describe your problem and how to reproduce it:**
There is a broken link to the MDN docs.
- [Current link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)
- [Might be a correct link](https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)

## **Add a Link to the page with the problem:**
[freeCodeCamp Challenge Guide: Implement map on a Prototype](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-implement-map-on-a-prototype/301230)

## **Tell us about your browser and operating system:**
* Browser Name: google Chrome
* Browser Version: 
* Operating System: MacOS

## **If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-03-07 at 4 08 44 PM](https://user-images.githubusercontent.com/30683150/76152523-80c15d80-608e-11ea-8ccf-c65924d66b73.png)

**Comment by RandellDawson** [comment]
@BoyeongYoon I have fixed this issue.  In the future, please create a forum topic under the Contributors category for anything to do with forum topics related to curriculum hints/solutions.  The forum content is separate from the freeCodeCamp repo, so it is best to alert mods under that category instead of creating a GitHub issue. 

Thank you for letting us know about this problem.  I am closing this issue, since it is now resolved.

**Comment by BoyeongYoon** [comment]
> @BoyeongYoon I have fixed this issue. In the future, please create a forum topic under the Contributors category for anything to do with forum topics related to curriculum hints/solutions. The forum content is separate from the freeCodeCamp repo, so it is best to alert mods under that category instead of creating a GitHub issue.
> 
> Thank you for letting us know about this problem. I am closing this issue, since it is now resolved.

I will create a forum topic in the future for this kind of issue. Thank you.
