### ISSUE TITLE
Could you update the Chinese Publication?

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#38490]
![image](https://user-images.githubusercontent.com/19358186/78240599-d106d080-7511-11ea-90b7-d92846f81991.png)

![image](https://user-images.githubusercontent.com/19358186/78240640-dc59fc00-7511-11ea-83d9-499e829528d6.png)

Could you delete these buttons above and below an article since it's not easy for most readers to share on Twitter/Facebook? And we don't use comment now.

Sharing through email is optional, but I think it's better to add it later when we add other buttons - share through WeChat, Weibo, and QQ.

Do we need to direct readers to /learn (maybe when the Chinese version is live) or /forum? @QuincyLarson 

Thanks!

**Comment by raisedadead** [comment]
The Chinese news theme is not at parity with the english version. 

This is likely because we chose to use branches for having different versions (we had to owing to forking the parent theme). 

We have gathered cruft again, Ghost has an inbuilt way of i18n that we should use.

We can sure quickly patch this, but I am not in favor of "report - fix - move ahead approach" which is a constant theme.

**Comment by ahmadabdolsaheb** [comment]
You are absolutely right, @raisedadead.  Since going headless seems further down the road, I will look into i18n and releases for the current theme.
