### ISSUE TITLE
Comment in html tag prevents validation

### ISSUE THREAD

**Issue by wirthual** [freeCodeCamp/freeCodeCamp#38559]
Basic HTML and HTML5: Declare the Doctype of an HTML Document

I added:
```
<!DOCTYPE html>
<html>
  <!-- Your HTML code goes here -->
  <h1>Test</h1>
</html>
```
 
But when I want to validate it tells me:
 // running tests
The html tags should wrap around one h1 element.
// tests completed

I think the comment should be ignored, it works if I delete the comment.

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/declare-the-doctype-of-an-html-document

* Browser Name:  Firefox
* Browser Version:  75
* Operating System: Ubuntu
![image](https://user-images.githubusercontent.com/2640499/79518780-c7e42c00-8006-11ea-8d45-06ea7ac7cb66.png)

**Comment by Sky020** [comment]
Hello, wirthual.

Please note: This kind of question regarding the freeCodeCamp curriculum is better suit for the [forum](https://www.freecodecamp.org/forum). Specifically, you could have posted this on the _contributors_ sub-forum.

This is because, as it stands, the issue is not with the testing suite, but your code; the instructions do not say to add any comments, and the seed code does not include any comments.

So, as you have pointed out, if you follow the instructions by:
>Add a DOCTYPE tag for HTML5 to the top of the blank HTML document in the code editor. Under it, add opening and closing html tags, which wrap around an h1 element.

Then, you will pass the tests.

**Comment by raisedadead** [comment]
Thanks for helping with the triage @Sky020
