### ISSUE TITLE
Applied Accessibility "Add an Accessible Date Picker" | Challenge issue 

### ISSUE THREAD

**Issue by ramengyoza** [freeCodeCamp/freeCodeCamp#38570]
Issue:
I'm currently going through the "Responsive Web Design Certification" and came across what I think may be something incorrect (however I'm still learning so I may think it is wrong where it is actually correct).

In Step 12 of the Applied Accessibility "Add an Accessible Date Picker", the example (along with previous examples) require that the "for", "id" and "name" attributes to all be the same.
However, in this exercise, the "name" attribute is different to the "for" and "id" attributes. Please see below image highlighting this.

Link:
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/add-an-accessible-date-picker

Browser and Operating System:
* Browser Name: Google Chrome
* Browser Version: Version 80.0.3987.163 (Official Build) (64-bit)
* Operating System: Windows 10 Pro (Version 1903)

Screenshot:
![DatePicker_NameIncorrect](https://user-images.githubusercontent.com/63893978/79628387-dd329500-8183-11ea-80a8-9e901afcf9ba.PNG)

**Comment by Sky020** [comment]
Hello there.

I cannot see anything incorrect with the content of the lessons. In the above example, if there is only **1** `input` element, then it is perfectly normal to have the `id`, and `name` be the same. It is just an example. There is no requirement for them to be the same, and the lessons do not convey a requirement.

In general, you cannot have the `id` and `name` attributes be equal, because the `name` attribute groups inputs, and the `id` must be unique for the whole page. A `label`'s `for` should equal the `id` of the intended `input`, as this is what links them for indexing.

I would recommend, for future posts, you use the [Contributors sub-forum](https://www.freecodecamp.org/forum/c/contributors) to bring up questions like this. It is a useful place to discuss changes/improvements to the curriculum.

It is good to ensure the curriculum content is consistent.

**Comment by moT01** [comment]
Thank you for reporting this issue.

I don't see a problem here either, I think @Sky020 gave a good explanation, so I am going to close it.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding.
