### ISSUE TITLE
Integrate start-server-and-test for Cypress

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38679]
We want to integrate [`start-server-and-test`](https://github.com/bahmutov/start-server-and-test) for our Cypress setup.

The utility allows us to [wait on multiple servers](https://github.com/bahmutov/start-server-and-test#starting-two-servers)  as well.

Ideally we would want to keep all the config as npm-scripts in the package.json itself.

**Comment by git-singh** [comment]
I can help with this.

**Comment by git-singh** [comment]
@raisedadead Can I help with this ?

**Comment by peterimoh** [comment]
Please guys. Can anyone help me with running freecodecamp offline on my
computer. I have a hard time accessing the internet where i am

**Comment by ojeytonwilliams** [comment]
@git-singh please do, anything with the help wanted tag is open for contributions.

@peterimoh unfortunately that is not yet possible, but you can find the discussion here: #35755.  If you have any thoughts about how that might be done, please drop them in that issue.  Otherwise the forum is probably a better place to discuss this.

**Comment by gikf** [comment]
Hey @raisedadead,

this seems to be done in #39036, or is there anything else that's still required?

**Comment by raisedadead** [comment]
Nope. Closing.
