### ISSUE TITLE
MongoDB and Mongoose - Challenge nº 9 (findByIdAndUpdate) - works without updating the model.

### ISSUE THREAD

**Issue by LeoDalcegio** [freeCodeCamp/freeCodeCamp#38677]
This is the challenge: https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/perform-new-updates-on-a-document-using-model.findoneandupdate.

The challenge is to update a "Person" model using "findByIdAndUpdate", but I notice that both of the following codes work:

```
var findAndUpdate = function(personName, done) {
  var ageToSet = 20;
  
  var person = Person.findOne({name: personName}, (err, data) => {
    if (err) return console.log(err);
    
    data.age = ageToSet;
    
    Person.findByIdAndUpdate(data._id, data, { new: true }) // THIS LINE
    
    done(null, data);
  })
};


var findAndUpdate = function(personName, done) {
  var ageToSet = 20;
  
  var person = Person.findOne({name: personName}, (err, data) => {
    if (err) return console.log(err);
    
    data.age = ageToSet;
    
    // WIHTOUT FINDBYIDANDUPDATE
    
    done(null, data);
  })
};

```

**Comment by moT01** [comment]
Thanks for pointing this out @LeoDalcegio. To me, this seems quite minimal and probably not worth the effort it would take to fix it. It says to use `findOneAndUpdate` so users should try to use that. If they can achieve the correct result in another way in this case, I don't really have a problem with it.

The challenge also mentions to find the person by name and not id. Your examples use Id. It's not perfect, but like I said, I don't think it's worth the effort in this case. Most users are going to use `findOneAndUpdate` because it says to right there.

But, if someone wants to dive in and try to fix it - I wouldn't object.

**Comment by LeoDalcegio** [comment]
Yeah you are right, it is just a small thing that I notice, but it is not something that would stop people from learning.


-------- Mensagem original --------
De : Tom <notifications@github.com>
Data: 30/04/2020 12:32 (GMT-03:00)
Para: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Leonardo Luís Dalcegio <leoodalcegio@hotmail.com>, Mention <mention@noreply.github.com>
Assunto: Re: [freeCodeCamp/freeCodeCamp] MongoDB and Mongoose - Challenge nº 9 (findByIdAndUpdate) - works without updating the model. (#38677)


Thanks for pointing this out @LeoDalcegio<https://github.com/LeoDalcegio>. To me, this seems quite minimal and probably not worth the effort it would take to fix it. It says to use findOneAndUpdate so users should try to use that. If they can achieve the correct result in another way in this case, I don't really have a problem with it.

The challenge also mentions to find the person by name and not id. Your examples use Id. It's not perfect, but like I said, I don't think it's worth the effort in this case. Most users are going to use findOneAndUpdate because it says to right there.

But, if someone wants to dive in and try to fix it - I wouldn't object.
