### ISSUE TITLE
Regular expression lesson's order

### ISSUE THREAD

**Issue by arthurvmdantas** [freeCodeCamp/freeCodeCamp#38682]
Hello,

In the Regular Expressions section, maybe the "Check For Mixed Grouping of Characters" lesson ought to come before "Restrict Possible Usernames"?

I needed grouping to solve the proposed exercise of "Restrict Possible Usernames".  So, I kind of needed to use something that was explained only later.

Best,

**Comment by thecodingaviator** [comment]
cc: @raisedadead

**Comment by raisedadead** [comment]
Tom is correct, we are not reordering challenges at the minute. 

We understand and acknowledge the annoyance, however we are motivated to push the project based challenges which would help in understanding the concepts better because the progress on the project would be incremental in nature.

**Comment by blentz100** [comment]
It took me a few days to solve this challenge. I ended up learning alot in the process - I might have learned more because of the ordering issue. If it can't be reordered - perhaps consider adding a disclaimer within the challenge. Something to the effect of: "some campers have found this challenge to be extra difficult, consider skipping it, doing all the others challenges and then doing this one last." Either way, thanks to the maintainers for this awesome resource!

**Comment by ShaunSHamilton** [comment]
@blentz100 Thank you, for commenting. This has come up before: https://forum.freecodecamp.org/t/restrict-possible-usernames-solution-requires-knowledge-not-introduced/395660/7

The challenge is very much completable solely with knowledge from previous lessons. Whilst the challenge can be considered _more difficult_ than any previous challenge, many Campers have been able to complete it, and, where they struggle, we recommend the _READ-SEARCH-ASK_ methodology.

I welcome you to ask any more questions on the [forum](https://forum.freecodecamp.org/) 🙂
