### ISSUE TITLE
Solution not being validated (APIs and Microservices Certification)

### ISSUE THREAD

**Issue by tiagofsanchez** [freeCodeCamp/freeCodeCamp#38733]
**Describe your problem and how to reproduce it:**
On the Managing Packages with Npm (APIs and Microservices Certification) after submitting the first challenge with the URL from gitHub, codePen of codeSandbox, I am not able to pass the test.

**Add a Link to the page with the problem:**
Links to my repo - https://github.com/tiagofsanchez/freecodecamp-apis-microservices
Why is that not working passing? 

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/11288873/81037250-97403580-8ed4-11ea-85e8-fa3e9573423a.png)

**Comment by ojeytonwilliams** [comment]
These challenges expect to receive a full app, rather than the source code.  If you submit the 'live app' of your Glitch project it should work.

The [forum](https://www.freecodecamp.org/forum/) is a better place to ask questions like this, though.  If the community concludes there's a bug, they will always suggest you create an issue here.

**Comment by tiagofsanchez** [comment]
thank you @ojeytonwilliams.

**Comment by ojeytonwilliams** [comment]
No problem, good luck with the challenges.
