### ISSUE TITLE
PayPal called during development

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38734]
**Describe the bug**
The PayPal sdk gets called by the local site, even when there are no keys specified in .env

**To Reproduce**
1. Go to any page with a donation component
2. Open the console
3. See a 400 error

**Expected behavior**
If the keys are missing, PayPal should not be contacted.

**Screenshots**
![image](https://user-images.githubusercontent.com/15801806/81048398-8edc0080-8ebc-11ea-8c11-2fd5c88a986d.png)

**Comment by UgRoss** [comment]
Hello guys!
Does this happen on `/donate` page or somewhere else too?

I noticed that this page fails to load also because of the missing Stripe API key for me.
If the goal is just to make page load without Stripe/Paypal keys and skip PayPal calls I'd like to help with that.

Also, I noticed it has a typo `clinetId` -> `clientId`. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Donation/PaypalButton.js#L82

**Comment by ahmadabdolsaheb** [comment]
@UgRoss, it should happen if you hard refresh on donation page. (and on donation modal)
That script loads the button.
 A solution would be to check for paypalClientId in the render of PaypalButton component and return PayPalButtonScriptLoader only if paypalClientId is truthy.

**Comment by UgRoss** [comment]
PR is ready. Could you please take a look?

Also about the Stripe issue. I'm not sure if it's expected or not but if I don't configure the key for stripe, the `/donate` page isn't loading for me at all.
<img width="1054" alt="CleanShot 2020-05-11 at 02 59 29@2x" src="https://user-images.githubusercontent.com/5703885/81513776-9162ae00-9333-11ea-8c5c-3eb7cf5c1cc0.png">

**Comment by raisedadead** [comment]
Yikes, that seems like it needs a fix as well. Thanks for catching that.
