### ISSUE TITLE
HTML entities Bonfire

### ISSUE THREAD

**Issue by AromaR** [FreeCodeCamp/FreeCodeCamp#3875]
Challenge [Bonfire: Inventory Update](http://www.freecodecamp.com/challenges/bonfire-convert-html-entities) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/8674981/10709521/657b1b94-7a4f-11e5-9de9-fc3f6982b412.png)
![image](https://cloud.githubusercontent.com/assets/8674981/10709524/8fa5f16e-7a4f-11e5-8f04-f6fe3c0fe7eb.png)
I cannot reset my code, which I think is the reason for the hanging up of the browser whenever I come to this bonfire. I've completed others comfortably. 
Please reset the code if there is a backend mechanism to do it.

**Comment by bugron** [comment]
@AromaR thanks for posting this issue!
I think this is happening because of your `while` loop, review it. The code is stored in your browsers localStorage so only you can reset it. Try [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage) and [How to clear specific values from your browser's local storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser%27s-local-storage).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by AromaR** [comment]
Thank you, it worked

**Comment by bugron** [comment]
Glad to help. Closing this issue as resolved. Feel free to reopen if you still experience problems, thanks.
