### ISSUE TITLE
Extra example needed in Project Euler: Problem 18: Maximum path sum I

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#38773]
**Describe your problem and how to reproduce it:**
The current example makes it look like you need to choose the greater of the two adjacent elements of the next row

![image](https://user-images.githubusercontent.com/34807532/81469043-7a6f6f00-9200-11ea-97be-e6918423d845.png)

However, that is not the case. What we need to do is choose the path which will lead to the greatest sum. [Refer to this](https://www.hackerrank.com/contests/projecteuler/challenges/euler018/forum)

A simple fix is to add a new example

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-18-maximum-path-sum-i

**Comment by rajatagg21** [comment]
Hey ,I want to work on this

**Comment by ojeytonwilliams** [comment]
I think the example is deliberately chosen as one that can be solved via a greedy algorithm (pick the biggest adjacent number each time).  It means that the user has to fully understand the instructions in order to complete the challenge (rather than being told by the example).

If someone has missed the fact that it has to be globally maximised they will create something that works for the example and then have to figure out why it does not pass the tests.  I think that's a useful part of the challenge and it would be a shame to remove it.

Also, we have the forums to help people out and the community is great at guiding people to solutions without just straight up telling them the answers.  Users should never feel completely stuck.

**Comment by rajatagg21** [comment]
I agree but then why this issue is open yet?

**Comment by thecodingaviator** [comment]
Hi @rajatagg21 , the issue was still open because it was a discussion still
in progress. I'll close the issue now :)
