### ISSUE TITLE
Tests need to be rewritten/randomized in Project Euler: Problem 69: Totient maximum

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#38809]
**Describe your problem and how to reproduce it:**
I can just pass the challenge by typing 
```js
function totientMaximum() {
  // Good luck!
  return 510510;
}
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-69-totient-maximum

**Comment by Sky020** [comment]
I agree with this issue, but am wondering if we should open a todo list for the Euler Project challenges instead?

**Comment by Ieahleen** [comment]
Maybe considering this are in the Interview Prep and not in the curriculum we can just chuck it at people wanting to practice and do not go crazy in all this "if I write the expected output it passes", because I think this is pretty common in the Euler or even Rosetta challenges

**Comment by moT01** [comment]
I pointed this out before, but this is something that is difficult to test for and I'm not sure it's worth trying to stop. People in the interview prep section are there for a reason. If you try to regex a stop to `return 510510`, or maybe just check for `510510`, people can still use `return 510511-1` or something like that. It's just too easy to get around I think.

What about a check against the length of their code? You really can't pass any of these without a decent size chunk of code. What about making sure that it's >100 characters or something?

What about isolating the `return ...` part of the code, and checking that the `...` is not a number or an equation or something?

**Comment by Sky020** [comment]
@moT01 You are right; I just wanted to get a _quick-fix_ out there.

>What about a check against the length of their code? You really can't pass any of these without a decent size chunk of code. What about making sure that it's >100 characters or something?

The issue with this is, unless the test text does not give away the fact that it is looking at code size, because I could add any amount of garbage code to the end of my script. However, this in combination with another test might be beneficial.

>What about isolating the return ... part of the code, and checking that the ... is not a number or an equation or something?

This probably will not work: 1) Many of my return statements are equations of some-kind; 2) Passing the variable that is the solution is just as easy.

Perhaps you are right -  we should just leave them as is, and let the satisfaction of legitimately passing be the tests.

**Comment by moT01** [comment]
I don't really like this, but what about removing the number from the tests?
Instead of `should return 510510`, it says `should return the correct number`. I don't like it because I use that number to try and figure out how write an algorithm sometimes. It doesn't really stop the direct return of a result, but users wouldn't know what the number is supposed to be anyway.

**Comment by thecodingaviator** [comment]
You know, I've been thinking, and now I don't think we need to touch any problem (in this section) to check if the user is really completing it.

Since this section is not backed by an fCC Certificate anyway, if the users just use workarounds, they're cheating themselves.

Thoughts @QuincyLarson ?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @thecodingaviator. This is definitely something we want to improve over time. 

I do agree that anyone who cheats is just cheating themselves, and a lot of the solutions are freely available online. Still, we want to avoid letting people return a single number and passing a challenge if possible.

One thing we've done is adapt the functions to take arguments, adjust the description, and add more tests. This one would be pretty easy to adapt because there's a table with the answers in the description.

We could change the last sentence of the description to "Find the value of n ≤ `limit` for which n/φ(n) is a maximum." Then we could add or adjust the tests so we're checking for `totientMaximum(10)` and `totientMaximum(1000000)`, which should return 6 and 510510, respectively.

**Comment by Sky020** [comment]
@scissorsneedfoodtoo , Yes, that sounds like a good plan.

In terms of the solution, are we wanting a solution that is as concise/performative as possible so campers can see how to improve? Or, are we wanting a solution that is simple, so campers can refer to workflow, if/when they get stuck?

**Comment by scissorsneedfoodtoo** [comment]
@Sky020, awesome, thank you for all of your help with this.

We have a good mix of those two types of solutions spread across the coding interview prep section. Any solution is perfectly fine as long as it can pass all the test cases before the timeout. We'll add them to the Guide posts on the forum as we go and readjust as necessary if other solutions are submitted to the challenges here or on the Guide posts themselves.

**Comment by thecodingaviator** [comment]
> Thanks for reporting this @thecodingaviator. This is definitely something we want to improve over time.
> 
> I do agree that anyone who cheats is just cheating themselves, and a lot of the solutions are freely available online. Still, we want to avoid letting people return a single number and passing a challenge if possible.
> 
> One thing we've done is adapt the functions to take arguments, adjust the description, and add more tests. This one would be pretty easy to adapt because there's a table with the answers in the description.
> 
> We could change the last sentence of the description to "Find the value of n ≤ `limit` for which n/φ(n) is a maximum." Then we could add or adjust the tests so we're checking for `totientMaximum(10)` and `totientMaximum(1000000)`, which should return 6 and 510510, respectively.
> 
> Also we could add a solution like
> 
> ```js
> function totientMaximum(limit) {
>   let result = 1;
>   const primes = [];
>   let i = 0;
> 
>   const isPrime = num => {
>     for (let i = 2; i <= Math.sqrt(num); i++) {
>       if (num % i === 0) return false;
>     }
>     return num !== 0 && num !== 1;
>   }
>   
>   for (let i = 2; i < 200; i++) {
>     if (isPrime(i)) primes.push(i);
>   }
> 
>   while(result * primes[i] < limit) {
>     result *= primes[i];
>     i++;
>   }
>   
>   return result;
> }
> ```
> 
> But that's almost directly from [this blog](https://www.mathblog.dk/project-euler-69-find-the-value-of-n-%E2%89%A4-1000000-for-which-n%CF%86n-is-a-maximum/), so if there's a more concise original solution, we should go with that.
> 
> What do you think @thecodingaviator and @Sky020?

Sounds awesome!

**Comment by moT01** [comment]
I think we are safe to close this in favor of the issue linked above. Thanks for all the input on this everyone. If anyone thinks I am wrong in closing this, feel free to leave a comment and we can reopen it. Thanks and happy coding 🎉
