### ISSUE TITLE
Keyboard Shortcut to go back and forth between reading area and editor. 

### ISSUE THREAD

**Issue by sweatwork** [freeCodeCamp/freeCodeCamp#38842]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to reach my mouse to go back and forth between reading area and editor, just because I'm using a small screen, I can't read the whole thing and need to scroll down and then go back to editor using mouse. This causes frustration which often prevents me from coding, for long hours.

**Describe the solution you'd like**
A keyboard shortcut to go back and forth would definitely help. 

**Describe alternatives you've considered**
I have tried to scale down my browser window, but it creates readability issues, which not only makes it hard to read but it's difficult for the eyes too.  

**Screenshot**
![2020-05-19](https://user-images.githubusercontent.com/22967284/82250653-7a424280-9969-11ea-80db-2105f1701a4d.png)

**Comment by ojeytonwilliams** [comment]
Hi, that's possible, though we haven't documented it yet, sorry!  The plan has been to make all this clear via a legend, but that PR, https://github.com/freeCodeCamp/freeCodeCamp/pull/38203, is still in the works.  A package I needed has been updated today, so that should be doable now.

Anyway, as it stands, you can use `Esc` to leave the editor and `e` to go back to it.  That's going to change (because `Esc` has multiple other uses), but when it does the new hotkey will appear in the legend.

I'll leave this open for now, since it highlights the issue, but that PR will close it.

**Comment by sweatwork** [comment]
I tried using `Esc` and `e`, it somehow does the job but not complete. Anyway, I hope it gets added soon and goodluck for the work.

**Comment by ojeytonwilliams** [comment]
Thanks! 

What goes wrong with `Esc` and `e`? It might be something we can fix.

**Comment by sweatwork** [comment]
No, the `e` works. It does take you to the editor, only if you are in reading pane. However, the `Esc` just takes you out from there to nowhere. If it could take you back to reading pane or maybe a combination of it, that would be great.

**Comment by raisedadead** [comment]
something like `r` if its not used? In escape mode obviously.

**Comment by sweatwork** [comment]
Nope, didn't help.

**Comment by raisedadead** [comment]
> Nope, didn't help.

Oh - I meant we would need to add this as a shortcut combination. It does not exist yet. 😅

**Comment by sweatwork** [comment]
> Oh - I meant we would need to add this as a shortcut combination. It does not exist yet. 😅
My bad, I misunderstood. Anyway, that'd be convenient.
