### ISSUE TITLE
Unable to find out error

### ISSUE THREAD

**Issue by Emmanuelsam124** [freeCodeCamp/freeCodeCamp#38867]
I was doing one of the exercises in freecodecamp.org and the exercise asked that I make the height and width of an image 100 pixels each. I did it correctly but the test result keeps telling me to make the width 100 pixels and the height 100pixels. Below is my code. I am thinking the issue is from the freecodecamp website... Not sure
`<style>
  img{
    width:100px;
    height:100px;
  }
  </style>

<img src="https://s3.amazonaws.com/freecodecamp/FCCStickers-CamperBot200x200.jpg" alt="freeCodeCamp sticker that says 'Because CamperBot Cares'">
`

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum). Remember, you can use the _Ask for Help_ button on the lesson page to automatically create a post in the forum.

Common issues people face with the _Responsive Web Design_ content is due to their browsers. If you have any browser extensions with access to freeCodeCamp, disable them. They can influence the tests. If your browser is set to a zoom level other than 100%, this can also affect some tests. Also, the latest stable release of Chrome is the recommended browser to work through the curriculum.

I am closing this issue. If you have any more questions related to this, it would be easier to help if you use the _Ask for Help_ button on the lesson.

Thank you.

**Comment by Emmanuelsam124** [comment]
Thank you. I resolved the issue already. I used another computer for it and
it worked.
