### ISSUE TITLE
Can't proceed to next step in challenge.

### ISSUE THREAD

**Issue by 3adel** [FreeCodeCamp/FreeCodeCamp#3887]
1. When I tap on Run tests, nothing happens for this particular step. 

Challenge [Waypoint: Create a Bootstrap Headline](http://freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline#?solution=%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playgournd%3C%2Fh3%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h3 class="text-primary text-center">jQuery Playgournd</h3>


```

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @3adel.

I think you were expecting some sort of prompt when you clicked the button? If you did, then the reason was that the last test failed. If you scroll down in the left panel, you will see the tests that are run on your code to validate it. The last of these failed, because of which the modal didn't appear.

**Comment by 3adel** [comment]
sorry I should've scrolled and see the error. Stupid me :S.
