### ISSUE TITLE
Advanced Node.js and Express has a lot of broken tests

### ISSUE THREAD

**Issue by magnus195** [freeCodeCamp/freeCodeCamp#38882]
**Describe your problem and how to reproduce it:**
I'm having a ton if issues with advanced Node.js. A lot of things seem to be broken.
My first major issue was where I had to create a middleware. It would not accept anything unless I added "Home page" to my template. This is an easy fix though, but very hard to understand in the middle of doing coding challenges.
My currrent issue is here:
[https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users)
No matter what I put, I get errors of different kinds, even when using the solution provided with [Github](https://gist.github.com/JosephLivengood/6c47bee7df34df9f11820803608071ed).

**Add a Link to the page with the problem:**
[https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: Latest :|
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![bilde](https://user-images.githubusercontent.com/22998711/82741808-45adfc80-9d56-11ea-8b05-1a0307036483.png)

**Comment by ericblancas23** [comment]
are you still having this current problem?, also just to be sure do you mind pasting your middleware function here?

**Comment by magnus195** [comment]
As said in above post, the bug affects the solution too. Nothing seems to pass those two points. And some issues are mentioned in issue #38837 

My middleware is here:
```
function ensureAuthenticated(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  }
  res.redirect('/');
};
```

**Comment by krisb1220** [comment]
> As said in above post, the bug affects the solution too. Nothing seems to pass those two points. And some issues are mentioned in issue #38837
> 
> My middleware is here:
> 
> ```
> function ensureAuthenticated(req, res, next) {
>   if (req.isAuthenticated()) {
>     return next();
>   }
>   res.redirect('/');
> };
> ```

@magnus195 Did you get through the challenges? I just finished them, so I'm able to answer any questions you may have. BTW, I had the same issue with registration. The issue was resolved when I cleared the FCC test user from my database. Apparently the test doesn't check if the user already exists. 

Feel free to mention me or pop into the Gitter chatrooms, if you need any help :) Or, if you want, feel free to email me via krisb1220@gmail.com :)

**Comment by magnus195** [comment]
Is anything being done to this?

**Comment by Radoogle** [comment]
Wow, I didn't expect this, not now when I'm so close to finish.
I totally agree with @magnus195 that there are a lot of broken test!!!!
So @krisb1220 if you can please help me!!!

Here is my issue:
I started the chapter "Advanced Node and Express" on the 9th of June (I believe the date is important also, because I see a lot of things have changed since 2 moths ago and probably since 17 days also since Magnus posted his issues).
I passed the first lesson ("Set up a Template Engine"), then the second ("Use a Template Engine's Powers")  and when I got to the third ("Set up Passport") all hell broke loose! So I did a very simple task but got all the test failed, starting with passport and express-session should be dependencies. How hard can it be? Especially when glitch is installing them for you. But anyhow I checked with other solutions (even the one that is specified in the lesson) and did also copy/paste and nothing helped. 

package.json file contains this:

{
  "//1": "describes your app and its dependencies",
  "//2": "https://docs.npmjs.com/files/package.json",
  "//3": "updating this file will download and update your packages",
  "name": "fcc-advanced-node-and-express",
  "author": "http://github.com/JosephLivengood",
  "version": "0.0.1",
  "description": "What am I about?",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.16.1",
    "cors": "^2.8.1",
    "pug": "^3.0.0",
    "express-session": "^1.17.1",
    "passport": "^0.4.1"
  },
  "engines": {
    "node": "^12.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://glitch.com/#!/project/welcome-project"
  },
  "keywords": [
    "node",
    "glitch",
    "express",
    "pug",
    "passport",
    "socketio"
  ],
  "license": "MIT"
}

server.js file  contains this:

'use strict';
const express     = require('express');
const bodyParser  = require('body-parser');
const fccTesting  = require('./freeCodeCamp/fcctesting.js');
const session     = require('express-session');
const passport    = require('passport');
const app = express();
fccTesting(app); //For FCC testing purposes
app.use('/public', express.static(process.cwd() + '/public'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.set('view engine', 'pug');
app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: true,
}));
app.use(passport.initialize());
app.use(passport.session());
app.route('/')
  .get((req, res) => {
    res.render(process.cwd() + '/views/pug/index', {title: 'Hello', message: 'Please login'});
  });
app.listen(process.env.PORT || 3000, () => {
  console.log("Listening on port " + process.env.PORT);
});

.env file contains:

SESSION_SECRET=8


and here is the printscreen with test failed
![test failed](https://user-images.githubusercontent.com/52208792/84138534-14704480-aa57-11ea-8a62-afd5d2576285.jpg)

and again without doing anything, just hit the button ("I've completed this challenge") and some test pass now.
![test failed 2](https://user-images.githubusercontent.com/52208792/84138640-41bcf280-aa57-11ea-9d7b-c8ce6a9d4b60.jpg)

again without doing anything, just hit the button ("I've completed this challenge") with different result in the test passed/failed
![test failed 3](https://user-images.githubusercontent.com/52208792/84138950-c3148500-aa57-11ea-80b0-318ef4a02177.jpg)


I even went back to the first lesson and restarted the project from zero in glitch and now I can't pass lesson 1!! And get random number of test to pass/fail every time I hit the button ("I've completed this challenge").
if it helps, the glitch pages are here:
project page: https://glitch.com/~lace-spiny-musician
live app: https://lace-spiny-musician.glitch.me
code: https://glitch.com/edit/#!/lace-spiny-musician

Now I'm stuck and don't know what to do!

**Comment by Radoogle** [comment]
LOLOLOLOLOL
five minutes later, I closed the freecodecamp tab, then reopened and tried again the magic button ("I've completed this challenge") and I think from the 3rd try I got lucky! and DESTROYED THE CHALLENGE! This is the very appropriate message that came with all the tests passed!
So now I move on, but keep in mind: if it doesn't work from the first try, keep trying till it does! And bother to change anything, just hit the button! :)))))

**Comment by magnus195** [comment]
That is now how it should be though. The part about express and passport can actually be very easy but when FCC has those broken tests, we risk learning the wrong thing and losing motivation to finish the courses. How can we know that the tests doesn't give false positives when it gives so many false negatives?

**Comment by ojeytonwilliams** [comment]
@magnus195 Yeah, these challenges are something I'd like to improve.  You can see https://github.com/freeCodeCamp/boilerplate-advancednode/pull/6 for discussion of some of the issues surrounding this.  One is that Chrome silently discards headers during AJAX calls, so you can't tell if a login worked or not.

Help is very much wanted, but I think it might come down to either 

- warning that Chrome does not work
- an rewrite that avoids the entire login + redirect flow

**Comment by Radoogle** [comment]
I ran out of luck!
For the next lesson "Advanced Node and Express - Serialization of a User Object" I believe I did right, but can;t get the tests to pass.
Pretty often (no change just submit) I get 2 out of 4:
![test 1,3](https://user-images.githubusercontent.com/52208792/84156867-b2bdd380-aa72-11ea-98bd-948de8788a79.jpg)

then the other 2:
![Tests 2, 4](https://user-images.githubusercontent.com/52208792/84156891-ba7d7800-aa72-11ea-9e8c-3b0b6625b155.jpg)

Once I got 3 out of 4 wow:
![Test 1, 2, 3](https://user-images.githubusercontent.com/52208792/84156925-c6693a00-aa72-11ea-8271-96f055f5bf07.jpg)

But just can't get 4/4...

**Comment by magnus195** [comment]
Serialization and deseralization are pretty easy in passport.js but the tests didn't work as they should for me. What I recommend is watching YouTube tutorials or reading documentation. Then do the projects

**Comment by krisb1220** [comment]
@Radoogle Can you post the link to your code?

**Comment by krisb1220** [comment]
@Radoogle I got it actually. Just realized that you posted the link in your pics. I'm gonna check it out rn :)

**Comment by krisb1220** [comment]
@Radoogle The problem is that the MongoDB client isn't correctly set up in the examples they give. MongoDB changed the way to connect to the DB after this was released. You can find the right way to connect in my post #38837 .. - in addition, they don't really go over the different syntax. For this project I used Mongoose instead. I just checked with your code and it let me login using the below connection method. All challenges still pass if you use Mongoose. However, if you still want to use MongoDB use the connection method in #38837. 

So, change your connection to this:

```javascript
mongoose.connect(process.env.DATABASE,{useNewUrlParser:true, useUnifiedTopology:true}, (err, db) 
```

from this: 
```javascript
mongo.connect(process.env.DATABASE, (err, db)
```


**BTW**: If you get a "URI should be of type String" error, wrap your URI in quotes when you store it in your .env file.  

So instead of
```
DATABASE=mongodb+srv://<user>:<password>@anae-main-fi7v8.mongodb.net/test?retryWrites=true&w=majority
```

Do this: 
```
DATABASE="mongodb+srv://<user>:<password>@anae-main-fi7v8.mongodb.net/test?retryWrites=true&w=majority"
```

**Comment by magnus195** [comment]
I have no experience with contributing to these kinds of projects but are someone fixing the curriculum/tests?

**Comment by Radoogle** [comment]
@krisb1220 thank you!
I managed to pass that challenge, now I'm at #8 "Create new middleware". We'll see how it goes.
So the previous challenges I passed knowing that I did it right and just hit the submit button a bunch of times till I got lucky.
Among the changes I did was the one you mention: "URI should be of type String"
I kept the db connection with mongo, but changed the connection driver in the db settings.

**Comment by Sky020** [comment]
> I have no experience with contributing to these kinds of projects but are someone fixing the curriculum/tests?

@magnus195 , I have been working my way through the lessons and boilerplate, and will hopefully have some fixes soon. It is just taking me a lot of time. I am also discussing removing Glitch as the recommended platform to host the challenges/projects.
