### ISSUE TITLE
Add a button to skip to the important part of python videos

### ISSUE THREAD

**Issue by magnus195** [freeCodeCamp/freeCodeCamp#38958]
**Is your feature request related to a problem? Please describe.**
I have tried the python lessons. I must say, it is really good for beginners, but kinda annoying for those who know about the insides of a computer's hardware and software. The videos are very long, and I feel like if the older curriculums are 300 hours, python will be 900 hours per category.

**Describe the solution you'd like**
I would like a button that skips to the part of the video that is purely related to code.

**Describe alternatives you've considered**
I've seen other websites do it, but I have no idea how. Probably some JS.
[Here's some iframe docs I think](https://developers.google.com/youtube/iframe_api_reference)

**Comment by raisedadead** [comment]
This could be a source of skip-submit-next type behaviour and counter productive?

The video challenges are optional and are not required for you to complete the certification itself.

You could focus on checking out parts that you would want to learn about, even more so the questions on the challenges are already shown to the user. Meaning there is no reason to watch the same if you are absolutely confident about a answer.

Finally, the video player also lets you watch videos at higher playback like you would on YouTube.

**Comment by magnus195** [comment]
I think adding such a button would be the opposite of skip-submit-next. Right now I read the questions and try to find something on google to help me understand. The videos are good, but they just might be a bit too in-depth for many people.
I'd vote for an _optional_ "skip to coding" button for those who have a bit of experience and just wants to learn coding.

**Comment by raisedadead** [comment]
> Right now I read the questions and try to find something on google to help me understand.

**Understood. Its fine and should be OK.** 

Wanting to skip means, a user is only interested in blowing past the challenges as a milestone and nothing more. 

Learning is discovering things by any means available to you. Watching videos or doing a manual search on Google, StackOverflow is normal. It means you are putting an efforts (and doing the hard work) to find a solution. That is all that the certification aims to teach. Not just the technology, but the ability to plough thru using all tools at your disposal. This is also one of the traits that the user would likely need in a job too :)

Considering the scenario (as a user, you):

- answer the MCQ (multiple choice questions) to get familiar with the topic.
- want to do that quickly (...indicating you are in rush? If yes, why?)
- do not need to answer all the MCQs, if you are familiar with the topic (...it's not mandatory, it's only a refresher)

So, we really need to understand is the requested feature going to encourage useful behaviour like learning something which they can apply in the real world?

Also,

**We have a linear curriculum. This is intentional.**

The idea and goal - has always been NOT to be a one solution fits everyone. We intentionally split things into required and optional. At the same time we do not make it very explicit. This makes it so that beginners go thru the whole thing as they probably should? 

This also make it so that anyone with some experience understands that somethings are trivial and they can skip to the projects which count for the certification.

There are some changes planned to make it a little more clear though.

**Comment by ahmadabdolsaheb** [comment]
After considering this feature, we have decided not move forward with it in the time being. Thank you @magnus195 for the feature request. Please let us know if you come across other functionalities that could further enhance our users' learning experience.
