### ISSUE TITLE
Adding and modifying profile picture

### ISSUE THREAD

**Issue by Advitya-sharma** [freeCodeCamp/freeCodeCamp#38983]
my FCC account is signed in with github,today I changed profile picture on github but the changes didn't reflected on FCC forum account,then I tried uploading manually but the image is cropped automatically and I can't modify if the crop was wrong .

syncing profile picture with github and giving option to user so that he/she is able to crop image that is uploaded

**Comment by raisedadead** [comment]
This is by design, we do not store any information that is not required by us. That includes the data from GitHub or other social providers.

For changing your image all you need is to give us a URL to the image. Like so:

![image](https://user-images.githubusercontent.com/1884376/83409243-ad88d500-a431-11ea-9a4d-aa8bc1370157.png)
