### ISSUE TITLE
page not responding

### ISSUE THREAD

**Issue by Advitya-sharma** [freeCodeCamp/freeCodeCamp#39025]
In certain challenges when I entered incorrect code the page stopped working, then the browser and at last the whole PC .

I faced problem in vivaldi and then in chrome but some times it only happens in vivaldi .

to reproduce the problem 

- go to the link on google chrome 
https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-component-with-composition
- copy this code  
```
const ChildComponent = () => {
  return (
    <div>
      <p>I am the child</p>
    </div>
  );
};

class ParentComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1>I am the parent</h1>
        { /* change code below this line */ }
<ParentComponent>
<ChildComponent/>
</ParentComponent>

        { /* change code above this line */ }
      </div>
    );
  }
};
```
- see results 

its happening in some other challenges also but can't mention them all here

* Browser Name: vivaldi , google chrome
* Browser Version: latest
* Operating System:  windows 10

**Comment by Sky020** [comment]
Hello there,

Whilst I can understand the confusion, this is not what the challenge asks for:
```
<ParentComponent>
  <ChildComponent/>
</ParentComponent>
```
The reason your browser is freezing is because you are calling `<ParentComponent>` within itself. This causes a recursive call to the component that never ends. We have discussed implementing fail-safes for this kind of behaviour (#36118) , but the fact remains, you are not supposed to ever (in the curriculum) call a component within itself.

I am closing this issue, as it is already mentioned above. Thank you.
