### ISSUE TITLE
Super minor issue: unclear wording in coding challenge

### ISSUE THREAD

**Issue by AlvaroLuken** [freeCodeCamp/freeCodeCamp#39058]
**Describe your problem and how to reproduce it:**
I just went through this coding problem in the Javascript Regex part of the certificate; it's super minor and should be just a small text fix: in the instructions it says 'Apply the regex myRegex on the string myString using the .test() method.' which implies to do write the code as the example states:
let testStr = "freeCodeCamp";
let testRegex = /Code/;
testRegex.test(testStr);
// Returns true
BUT the answer requires you to initialize a variable result and equal it to myRegex.test(myStr)

I know this is like SUPER minor, but it had me stumped for quite a while when the fix was that I plainly just had to declare a variable and equal it... maybe in the instructions it can say (updating the original instructions) something like: 'Apply the regex myRegex on the string myString using the .test() method ** and assign it to a new variable result.'

Am I crazy for thinking this? I know this would have definitely avoided me going into the Get a Hint section!

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1266" alt="Screen Shot 2020-06-11 at 8 34 59 PM" src="https://user-images.githubusercontent.com/25407127/84462178-2ef71900-ac23-11ea-93bf-f97ba6fb18e8.png">

**Comment by Ieahleen** [comment]
there is also written in the starting code
> `let result = myRegex; // Change this line`

how would you word it? the variable is already there, you just need to fix the right part of the assignment
saying "new variable" may mean that one has to write a new variable name

**Comment by AlvaroLuken** [comment]
Ah hey, you are 100% right - I don't know how I missed this! Thank you, it is perfectly fine as is.

**Comment by broadsword-MO** [comment]
Since I blew some time on this as well following the **same path** as the OP, and since this is the very first lesson on Regex, and since the test parameters at the bottom of the page *should* return `true` **without** the `result` variable being used (as a `console.log()` will verify)...

If I could suggest... This situation would be much clarified with a very small addition to the instructions.

The original instructions: "Apply the regex myRegex on the string myString using the .test() method."

Simply add: "and assign its value to the `result` variable." or something similar.

Thank you to the fCC staff for your consideration and all the work done on these courses!
