### ISSUE TITLE
AMP support for YouTube is not working/implemented?

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39075]
AMP support for YouTube is not working/implemented in Ghost. Needs investigation.

Context as reported by @AbbeyRenn:

https://twitter.com/carlfwalsh/status/1272198642313515009

**Comment by raisedadead** [comment]
Yep, it seems like its a special tag: https://amp.dev/documentation/components/amp-youtube/

**Comment by simarpreetsingh-019** [comment]
Maybe I could help in this and do my first good issue. Where to see the code and can you provide youtube video links?

**Comment by ahmadabdolsaheb** [comment]
Thanks @simarpreetsingh-019,
There is our theme repo. https://github.com/freeCodeCamp/news-theme

I highly recommend starting from here 
https://ghost.org/docs/api/v3/handlebars-themes/google-amp/

and checking out the ghost forum for a solution.
https://forum.ghost.org/

**Comment by simarpreetsingh-019** [comment]
@ahmadabdolsaheb  thanks for this. Could you also attach links of video that should be added to that page?

**Comment by ahmadabdolsaheb** [comment]
it could be any video. the idea is to have a template that inserts amp-youtube for imbedded youtube videos when viewed on amp.

**Comment by simarpreetsingh-019** [comment]
ohh , i didn't know much about working on for templates, as i have just started with AMP, but, will try my best to do something

**Comment by simarpreetsingh-019** [comment]
Pull request have been made , with some suggestions. Please review .

**Comment by scissorsneedfoodtoo** [comment]
Thanks for this contribution @simarpreetsingh-019.

This is working locally for be, though I had to update Ghost and restart to get the AMP version of the YouTube embed to render.

While digging more into this, it seems like the `amp-youtube` script controlled by Ghost in more recent versions: https://github.com/TryGhost/Ghost/pull/11058/files

Not sure if it's best to add it in the theme here, or to either add those lines to our Ghost install or wait until we update to a more recent version.

Since we're still running an older version of Ghost, we'll need to update `/current/core/frontend/apps/amp/lib/helpers/amp_content.js` directly. It seems like we just need to add to the `'amp-youtube'` to the `allowedAMPTags` here: https://github.com/TryGhost/Ghost/blob/23bf432514c67ac7714cb51846f4ffc8353afd41/core/frontend/apps/amp/lib/helpers/amp_content.js#L25

Then update `allowedAMPAttributes` with `'amp-youtube': ['src', 'width', 'height', 'layout', 'frameborder', 'autoplay', 'loop', 'data-videoid', 'data-live-channelid']` like on this line: https://github.com/TryGhost/Ghost/blob/23bf432514c67ac7714cb51846f4ffc8353afd41/core/frontend/apps/amp/lib/helpers/amp_content.js#L114

**Comment by simarpreetsingh-019** [comment]
@scissorsneedfoodtoo That's great news that it worked, and thanks for referring to `allowedAMPAttributes` with `amp-youtube`. I was suggesting about that. Well if it's already implemented, I had to see other things for any other suggestion in which I could also help to contribute.
Just one doubt, will this contribution be added to repo? or I would have to wait for some more time with another issue to be merged as my first contribution to any org?

**Comment by scissorsneedfoodtoo** [comment]
@simarpreetsingh-019, thanks for your patience.

I don't think everything mentioned in my last post is implemented in our production Ghost instance, though I haven't been able to check on it directly.

Either way, someone on the team will need to implement the fix, either by updating our Ghost instance or adding those values to the `/current/core/frontend/apps/amp/lib/helpers/amp_content.js` file. Once we do that, I don't think we'll need to update the handlebars template, though we'll need to do more testing.

That said, there's still a lot of issues we need help with over on /news or here in the main repo. Feel free to look for other issues and submit PRs!

**Comment by scissorsneedfoodtoo** [comment]
This appears to be resolved with our current version of Ghost.

Here's the AMP page for the article mentioned in the tweet above: https://www-freecodecamp-org.cdn.ampproject.org/v/s/www.freecodecamp.org/news/learn-javascript-by-making-digital-tabletop-games-and-web-apps/amp/?amp_js_v=a3

The videos all appear and are all converted to `amp-youtube` elements.

Note: The broken video is a video playlist, and works fine in the [non-AMP version](https://www.freecodecamp.org/news/learn-javascript-by-making-digital-tabletop-games-and-web-apps/) of the article.
