### ISSUE TITLE
Jquery challenges broken

### ISSUE THREAD

**Issue by DivyanshTiwari0** [freeCodeCamp/freeCodeCamp#39100]
One time challenges pass, other time they fail. Fully random. I know a similiar issue was reported but it was fixed and closed on June 15 while I experienced it yesterday.

**Comment by ojeytonwilliams** [comment]
Hi @DivyanshTiwari0, thanks for the report.  

This should be fixed on the staging site, https://www.freecodecamp.dev/learn/, but we don't immediately push everything to production.  This lets us test new changes (like that fix) to make sure they don't break something unexpected.  Since the fix is on the way, I'm closing this issue.

If you experience the same problem on the staging site, please re-open this and I will look into it.
