### ISSUE TITLE
Challenge Bonfire: Where art thou -- An array wasn't returned

### ISSUE THREAD

**Issue by razouckt** [FreeCodeCamp/FreeCodeCamp#3912]
Challenge [Bonfire: Where art thou](http://freecodecamp.com/challenges/bonfire-where-art-thou#?solution=function%20where%20(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20collection.slice(0)%3B%0A%20%20Object.keys(source).forEach(function%20(k)%20%7B%0A%20%20%20%20arr.forEach(function%20(e%2C%20i)%20%7B%0A%20%20%20%20%20%20if%20(!e.hasOwnProperty(k)%20%7C%7C%20source%5Bk%5D%20!%3D%3D%20e%5Bk%5D)%20%7B%0A%20%20%20%20%20%20%20%20arr.splice(i%2C%201)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0A%20return%20arr%3B%20%0A%7D%0A%0Awhere(%5B%7B%20first%3A%20%22Romeo%22%2C%20last%3A%20%22Montague%22%20%7D%2C%20%7B%20first%3A%20%22Mercutio%22%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20%22Tybalt%22%2C%20last%3A%20%22Capulet%22%20%7D%5D%2C%20%7B%20last%3A%20%22Capulet%22%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where (collection, source) {
  var arr = collection.slice(0);
  Object.keys(source).forEach(function (k) {
    arr.forEach(function (e, i) {
      if (!e.hasOwnProperty(k) || source[k] !== e[k]) {
        arr.splice(i, 1);
      }
    });
  });
 return arr; 
}

where([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });

```

![captura de tela de 2015-10-26 14 23 06](https://cloud.githubusercontent.com/assets/14312156/10735040/3a939542-7bed-11e5-930a-6f289c458e98.png)

My code is the epitome of hard work and my love for people, yet when I tried to submit it, the page said it hasn't returned an array containing objects. How can it be when I try to be such a nice person and a good developer.

I love you, guys.

**Comment by ltegman** [comment]
The wording of this test is rather unclear and we have a fix pending deployment to the production website that will clarify what the test is asking for. What it should say (and will soon) is `where([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" })` should return `[{ first: "Tybalt", last: "Capulet" }]`. It looks like your code returns `[{ first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }]`, so it is an array of objects, just not the correct array of objects.

Closing this issue since a fix for this test is already in the staging branch, but feel free to reply if you need further clarification.

Thanks for your infectious enthusiasm and happy coding!

**Comment by razouckt** [comment]
Well, I guess I'll have to redo this exercise.
Thank you for all your work, guys. Thank you, man.
