### ISSUE TITLE
[Python] Syntax highlighting for single backticks (code tags)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39128]
I noticed some of the challenges, like [this one](https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-course/reading-data-introduction) still has some goofy looking highlighting...

<img width="390" alt="Screen Shot 2020-06-24 at 6 48 22 PM" src="https://user-images.githubusercontent.com/20648924/85638558-cf016900-b64b-11ea-8ee6-7b60ca245af8.png">

We need to change the background of these code tags to white, or maybe a lighter gray? Could just leave it I guess - it's not too bad.

**Comment by moT01** [comment]
I believe code blocks with triple backticks get a white background if they're in the answer area. [code file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/conditional-execution.english.md) : [challege page](https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/conditional-execution)

When in the question, it looks like there's some inconsistencies that are probably fine. The picture above has two [codeblock sections](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-introduction.english.md), one background is the same as the page background, and the other gets that tan.

**Comment by ojeytonwilliams** [comment]
Good point.  Why don't we make all the backgrounds (inline, multiline, answer and question) white in day mode and dark blue in night mode?  It improves the contrast and consistency.

**Comment by moT01** [comment]
I tried to differentiate the questions from the answers by making the answers have a white background. So if we don't change that, then codeblocks(inline or multiline) wont have any background in the answers, or they will match anyway. And they will have the background in the questions. I don't think it looks too bad the way it is, but it does seem a little scattered. Hmm.

**Comment by ojeytonwilliams** [comment]
If we force them to be white everywhere they'll, effectively, have a background in the questions, because the page as a whole is grey.  It looks quite good, I think:

![image](https://user-images.githubusercontent.com/15801806/85735689-2a8c2f00-b6fe-11ea-866d-ac3c037ed5d4.png)

**Comment by moT01** [comment]
Yea, I like that I think.

**Comment by ahmadabdolsaheb** [comment]
So we had a similar situation where we wanted distinguish between the codes and their backgrounds so we went with quaternary background to make styling simple and make sure they stood up from their background.

![image](https://user-images.githubusercontent.com/4591597/85846844-20763900-b7af-11ea-9c43-0c2b4e0bf98b.png)

Styling the code elements similar to regular text will make them less differentiable  when they are used together in the radio buttons. 

We also need to consider having pre and code blocks inside radio buttons if that is ever the case, and if we need to have a hover/select styling.

Additionally, since we have recently introduced the radio button components we need to find a better way to make it consistent with the rest of the UI elements' hierarchy.

Following our current conventions> we would go one contrast level down when an element overlaps another element or we want to differentiate it from another element. that being said, following that convention here would lead to the following layout. 

Here is what our current UI would look like based on our current design style guide:

![image](https://user-images.githubusercontent.com/4591597/85846379-64b50980-b7ae-11ea-85f2-75ba547a8542.png)

Here is what happens if we style codeblocks and pre one contrast level highter.
![image](https://user-images.githubusercontent.com/4591597/85846443-81e9d800-b7ae-11ea-8987-18f6134e243f.png)

Here is what happens when we remove the borders (things start to blend it):
![image](https://user-images.githubusercontent.com/4591597/85846547-aa71d200-b7ae-11ea-9ca7-59ec91eef37b.png)

I am not in love with any of them, so feedback is appreciated.

**Comment by ojeytonwilliams** [comment]
I see what you mean about making it clear that the inline text is special.  However, we're (probably) going to run into contrast issues if we stick with the convention of pale background, darker box and even darker text.  If, instead, we go with a slightly darker background to contrast with the white box then it should be obvious that the box is special and we maximise the contrast with the text.

Like this:

![image](https://user-images.githubusercontent.com/15801806/85859217-26731680-b7bd-11ea-923a-9674aceea50e.png)

and this, with some (possibly too subtle) borders

![image](https://user-images.githubusercontent.com/15801806/85859495-92557f00-b7bd-11ea-95f4-aae05af2d364.png)

**Comment by moT01** [comment]
I think I like Ahmad's second example the best if it weren't for the green and blue text. Even on a white background, that green text is pretty tough. Maybe we should consider looking into changing that highlighting?

**Comment by ahmadabdolsaheb** [comment]
All of our color/background combinations are within best practices so backgrounds should be alright as long we make them consistent across learn; 

If we decide to go with white we need to lower the saturation on some of the  highlights.

I believe the current prism highlights are optimal for a slightly off white background. 

Here is optimal steps to take in my opinion:

-  Decide on the on the optimal /learn foreground background colors. (consider night/light mode and our theme switching mechanism)
- Decide on global code/code block background color.
- Adjust syntax highlighting for monaco and code blocks accordingly so they are similar #37166

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
