### ISSUE TITLE
Enabling A/B testing 

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39125]
It would be helpful to have different versions of the site live so we could make more data-driven decisions regarding the changes that we introduce to the the client.

**Comment by erictleung** [comment]
A/B testing could be useful but it might be good to specify a few things if this were to be implemented.

- What sort of elements would we change? (See below)
- Whose responsibility is it to view the analytics and coordinate changes on which experiment to use?

Users will most likely be on content related pages like the curriculum and the news routes. My assumption is that users would stay on the site longer if the content is good, rather than some visual of the site, but I could be wrong.

[This blog post](https://ikbendirk.nl/posts/how-to-ab-test-your-react-and-gatsby-components) appears to be helpful in actual implementation of this using https://www.npmjs.com/package/@marvelapp/react-ab-test.

Good news is that it appears that `@marvelapp/react-ab-test` is maintained as of last December, which is good because it is a fork of what appears to be an unmaintained [`react-ab-test`](https://github.com/pushtell/react-ab-test) from 2017.

It appears that this is all that might be needed to implement an experiment.

```
<Experiment name="My Example">
    <Variant name="A">
        <div>Version A</div>
    </Variant>
    <Variant name="B">
        <div>Version B</div>
    </Variant>
</Experiment>
```

**Comment by ahmadabdolsaheb** [comment]
We are mainly interested in improving time on site, sign-ups, donations, etc.

That would require split testing the followings:
- challenge UI, map UI, ... 
- donation modal UI, interval, and copy, ...
- landing page, sign up button placement, ...

I will take on the testing for the time being.
