### ISSUE TITLE
Bonfire: Exact Change crashing from the start

### ISSUE THREAD

**Issue by kkennethlee** [FreeCodeCamp/FreeCodeCamp#3919]
I tried executing a code but after that, it seems to freeze. Refreshing and Ctrl Shift J to delete local resources don't work either. 

What else can I do?

Thank you.

**Comment by AkhterAli** [comment]
Have you attempted a different browser than the one you're currently using?  Could you also be more accurate where the freeze is happening?

**Comment by kkennethlee** [comment]
Not yet.
Freezing is happening as I open the webpage, making it impossible to edit my code. 
--
Sent from myMail app for Android
Monday, 26 October 2015, 01:19PM -07:00 from Akhter Ali <notifications@github.com>:

**Comment by kkennethlee** [comment]
I was able to reset the page by going incognito mode in Chrome browser.  Thank you. 
--
Sent from myMail app for Android
Monday, 26 October 2015, 01:19PM -07:00 from Akhter Ali <notifications@github.com>:

**Comment by AkhterAli** [comment]
Try a different browser.
Try with developers tools on to see where the freeze "may" be happening.
Check your system specs to see if cpu/memory utilization spikes.

**Comment by ltegman** [comment]
Closing this since it looks like @AkhterAli was able to help you solve your problem. If you run into further problems with code causing lockups this guide should help [How to clear specific values from your browser's local storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage).

Feel free to reply if you need further assistance with this issue.

Thanks and happy coding!
