### ISSUE TITLE
10-21 : Test should pass

### ISSUE THREAD

**Issue by MartinDelille** [FreeCodeCamp/FreeCodeCamp#3923]
In the [Bonfire Argument optional](http://freecodecamp.com/challenges/bonfire-arguments-optional), I wrote the following code that return *null* according to the black box output (see picture) but the corresponding unit test fails:

    function add(a, b) {
      if(a % 1 == 0) {
        if(b == null) {
          var f = function(c) {
            if (Array.isArray(c))
              return null;
            else
              return a + c;
          }
          return f;
        }
        else if(typeof b == "string")
          return null;
        else
          return a + b;
      }
    }

    add(2)([3]);

<img width="802" alt="capture d ecran 2015-10-27 00 15 45" src="https://cloud.githubusercontent.com/assets/879889/10745234/26b55558-7c40-11e5-80cb-718e2bd05005.png">

I managed to fix the code like that but I'm not sure why the previous code doesn't work:

    function add(a, b) {
      if(a % 1 == 0) {
        if(b == null) {
          var f = function(c) {
            if (!Array.isArray(c))
              return a + c;
          }
          return f;
        }
        else if(!(typeof b == "string"))
          return a + b;
      }
    }

    add(2)([3]);

**Comment by ltegman** [comment]
This is because in javascript `null` and `undefined` are not the same value. The reason your corrected version works is because all javascript functions return something and if nothing is specified by the function's code that return value is `undefined`. So by leaving out the areas of your original solution where you would `return null;` the function is instead returning `undefined`. It's the same as if you'd left your code like it was originally but instead of specifying a value of null you simply `return;`.

Closing this issue but feel free to reply if you need any further clarification.

Thanks and happy coding!

**Comment by MartinDelille** [comment]
Thanks @ltegman that is perfectly clear!
