### ISSUE TITLE
Tests passes even without any CSS

### ISSUE THREAD

**Issue by vikramvi** [freeCodeCamp/freeCodeCamp#39257]
Please refer to https://forum.freecodecamp.org/t/tests-passes-even-without-any-css/409817

Tell us what’s happening:

This exercise asks to create Survey form.
As per survey form; I’ve entered all the necessary HTML elements
After running the code in codepen all the tests are passed
Expected Result:

As user has not used any CSS, test must fail
As user is learning both HTML and CSS; user stories should include CSS as well
Your code so far

Your browser information:

User Agent is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36.

Challenge: Build a Survey Form

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-survey-form

**Comment by Sky020** [comment]
Hello there,

I will leave this issue open for others to comment, but here is how I see it:

Firstly, the projects are there for users to practice _some_ of the topics taught in previous lessons. With emphasis on some, as (and this is seen in all of the projects continuing forward) the general idea is for the projects to become increasingly _difficult_, and, perhaps, expect more tools/techniques to be used. For example, the Frontend Libraries projects can all be completed without using _React_ or _Redux_, yet they are a large portion of the lessons. However, they are encouraged to be used to complete the projects, as are campers encouraged to use _"unnecessary"_ principles (CSS, design, or otherwise) to give their projects their unique _spin_.

Then, there is the fact that adding more user stories/tests to these projects, automatically causes thousands of previously submitted projects to fail the test cases. So, we would need to introduce a different kind of testing where the test-suite knows when to test a project that has been submitted prior a certain date.

Also, with the development of the new _project-based_ version of the curriculum, this kind of change will be made in any case.

Others are welcome to triage, and disagree. However, I assume a change like this will not be implemented.

**Comment by RandellDawson** [comment]
> Then, there is the fact that adding more user stories/tests to these projects, automatically causes thousands of previously submitted projects to fail the test cases. So, we would need to introduce a different kind of testing where the test-suite knows when to test a project that has been submitted prior a certain date.

Technically, this could be handled with versioning the actual test CDN.  When changes are introduced to the test scripts that would cause previously submitted projects to potentially fail any of the tests, then a new version is corrected an advertised to be used from a certain date on.  Then, when someone submits the project, we dynamically insert the latest CDN into the code to validate it works.  Then, we would record which CDN was used for each project successfully passed.  This would allow us to go back to spot check any user's project with the correct CDN that would have been used at the time it was originally submitted (or resubmitted for that matter).

**Comment by lasjorg** [comment]
I don't think CSS is very relevant to this challenge project.

The main point is to use the form elements and attributes that are needed when creating an HTML form. And as said, to revisit some form related concepts previously taught in the curriculum.

**Comment by vikramvi** [comment]
> I don't think CSS is very relevant to this challenge project.

Then how can new engineer is able to practice CSS learnt in the curriculum ? 

I personally finding it hard to do exercise projects as CSS is not made mandatory

**Comment by Sky020** [comment]
@vikramvi , CSS is _mandatory_ in every other project. So, you will practice it then.

**Comment by vikramvi** [comment]
> @vikramvi , CSS is _mandatory_ in every other project. So, you will practice it then.

All the 5 projects passes without any CSS, which other project did you mean ?

**Comment by RandellDawson** [comment]
> > @vikramvi , CSS is _mandatory_ in every other project. So, you will practice it then.
> 
> All the 5 projects passes without any CSS, which other project did you mean ?

@vikramvi That is not true.  The Tribute project requires you to use CSS to pass two tests.  The Product Landing Page project requires you to use CSS to pass three tests.  The Technical Documentation Page project requires you to use CSS to pass two tests.  Finally, the Personal Portfolio project requires you to use CSS to pass 3 tests.

The only project that does not use tests for CSS is the Survey Form project.

**Comment by vikramvi** [comment]
> > All the 5 projects passes without any CSS, which other project did you mean ?
> 
> @vikramvi That is not true. The Tribute project requires you to use CSS to pass two tests. The Product Landing Page project requires you to use CSS to pass three tests. The Technical Documentation Page project requires you to use CSS to pass two tests. Finally, the Personal Portfolio project requires you to use CSS to pass 3 tests.
> 
> The only project that does not tests for using CSS is the Survey Form project.

Thanks for pointing out but that is bare minimal CSS. 
IMHO after doing this course amount of HTML learnt is 10X compared to CSS which is 0.5X. We're team of 6 folks learning together and got similar feedback from others as well.

My sincere request was to add more complex CSS so that new learners of this technology gets loads of benefits while doing projects

**Comment by RandellDawson** [comment]
> My sincere request was to add more complex CSS so that new learners of this technology gets loads of benefits while doing projects

@vikramvi Just to be clear, you are requesting more complex CSS requirements be added to the certification projects or to the curriculum challenges?

Adding more CSS requirements to the projects would start to restrict users' individual design expression and cause users' projects to start to all look the same.  As far as the CSS curriculum is concerned, we strive to cover most of basics of CSS and some intermediate CSS topics and leave it to the students do further research on more advanced CSS topics.  The FCC curriculum challenges are meant to get you started in each topic (HTML, CSS, JavaScript, etc...).  We have many articles on our [news](http://freecodecamp.org/news) where more advanced CSS topics can be found.  Also, students can always inquire about more advanced CSS topics on [our forum](https://forum.freecodecamp.org).

**Comment by vikramvi** [comment]
> > My sincere request was to add more complex CSS so that new learners of this technology gets loads of benefits while doing projects
> 
> @vikramvi Just to be clear, you are requesting more complex CSS requirements be added to the certification projects or to the curriculum challenges?

curriculum challenges I meant; the current challenges doesn't really teach which, how, when, what of CSS ( CSS property ) to be used.

I agree that CSS is more like adding extra spices to the dish; but atleast teach new students what are basic CSS to be used through project.

ATM after struggling with CSS like hell; I'm looking at sample projects; re-doing it myself and trying to understand which, how, when, what of CSS ( CSS property )

This is not only from me but 5 other students who are learning along with me

**Comment by nhcarrigan** [comment]
I am in agreement with Randell, here, that adding additional CSS requirements would restrict the individuality and personalisation of a user's project.

**Comment by RandellDawson** [comment]
@nhcarrigan Recently, we had some discussions where we might start adding more slight restrictions to validate users know how to implement certain CSS syntax.  The goal will be to try to allow a variety of options that must be included to still allow creativity.  We will have some more discussions about this in the near future.

**Comment by moT01** [comment]
I think we could add more CSS requirements without restricting design freedom. Maybe some tests like:
"You should use flexbox at least once".
"You should use at least 3 different colors."
"You should use at least 2 different fonts."

Those seem testable.

Versioning the test-suite sounds like a solid idea - I think we would only need to update the forkable codepen projects to use the new version, and update the url on each project page. Dynamically inserting the test-suite code sounds possible, but it may complicate things a little? Users could just create their projects with the latest version - and if they want to use a newer released version, they can just update it.

I wouldn't object if someone wanted to try and expand the CSS requirements. If we were to try and add more tests, would we have to start versioning the test suite? I think that we probably would since we don't want to break all the older projects - I don't see another way that makes sense.

Since these projects won't be going anywhere with the project based curriculum, it might be worth trying to keep improving them.

**Comment by RandellDawson** [comment]
> I wouldn't object if someone wanted to try and expand the CSS requirements. If we were to try and add more tests, would we have to start versioning the test suite? I think that we probably would since we don't want to break all the older projects - I don't see another way that makes sense.

Yes, we will need to start versioning the test suite.  I think we will want to track of what version the user used at the time of project submission, so if we audited a project for "academic honesty", then the project should still pass all the tests of the test suite used on submission.

**Comment by nhcarrigan** [comment]
`https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`

Our CDN URL is already structured to allow versioning, so if we publish changes to a new version and host that URL, we wouldn't be breaking any existing tests.

**Comment by RandellDawson** [comment]
@nhcarrigan True.  We will just need to figure out a way to hopefully update the references to the latest CDN across the `/learn` pages without having to manually do it everything a new CDN is changed.

**Comment by nhcarrigan** [comment]
Actually, we could add a test to the projects - `fetch` the camper's input URL, and search the HTML for the CDN import.

This could even be implemented now, and would allow us to verify that the test suite is at least included with the project.

**Comment by moT01** [comment]
I'm still not convinced we would need to keep track of the version used at the time of submission. Just let users use what version they want. It's potentially not fair if one person can get a cert by passing projects using one version, and another person was forced to use a more difficult version to get a cert. I think that's where my vote would currently go - although, I can be swayed. Plus, it would add another thing to store in the DB for every project submitted.

**Comment by nhcarrigan** [comment]
To clarify, I'm not suggesting tracking any additional information in the database.

Just a test on the project page that reads the HTML and looks for the presence of the test suite - and that test would be updated as we update the CDN version so that *new projects* would be expected to use the latest version.

**Comment by moT01** [comment]
okay, so we would test the version on the fly then. I gotcha. What if I submit my project with v1, then v2 gets released and I want to update my project or change URL's - maybe glitch doesn't work with my project anymore or something - so I want to resubmit the project. Like I mentioned, I think trying to force a version complicates things - but sure, I guess I'm fine with it.

**Comment by nhcarrigan** [comment]
That wouldn't be any different than how we handle the other projects.

For example, we've updated tests on the Sudoku Solver. If I migrated my project from Glitch to Repl.it, I would fail on re-submission because the tests have changed since the time I built the project.

**Comment by moT01** [comment]
Fine - maybe I'm making a fuss over nothing then 😄

**Comment by RandellDawson** [comment]
Just as long as we don't allow users to submit projects with an older version of the CDN, then I would be happy.  The CDNs will change for mainly three reasons:

- Bug fixes with existing tests
- Additional tests to validate something that was in a user story
- Additional tests due to changing/adding/deleting user stories

We are planning on changing a few of the Front End Library projects to force the user to use React and/or Redux, so obviously we would not want to allow an older CDN that does not care if any library is used.  That would not be fair to others using the most current CDN to obtain the certification.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
