### ISSUE TITLE
Edit: Help improve or add subtitles

### ISSUE THREAD

**Issue by donchanee** [freeCodeCamp/freeCodeCamp#39306]
**Describe your problem and how to reproduce it:**
Data Analysis with Python Course

I went into the help to improve or add subtitles in the video on the Python course, but I couldn't fix it.

![image](https://user-images.githubusercontent.com/42461455/88353980-73391580-cd9a-11ea-94c5-4a6081d5476a.png)

Please open the permission to modify it.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
Hi @donchanee 

Unfortunately, YouTube has disabled/removed the ability to add publicly contributed closed captions (subtitles) for a while now. We would love to support this and are brainstorming on other ways.

I am going to have to close this due to the limitation. We will make an announcement if we figure out something.
