### ISSUE TITLE
where() should return an array of objects doesn't pass. Not even when faked.

### ISSUE THREAD

**Issue by Sepix** [FreeCodeCamp/FreeCodeCamp#3932]
Challenge [Bonfire: Where art thou](http://www.freecodecamp.com/challenges/bonfire-where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20%2F%2F%20Faking%20the%20first%20where()%20because%20it%20seems%20buggy%20but%20it%20still%20doesn't%20work%0A%20%20%0A%20%20if(source%20%3D%3D%20null%20%7C%7C%20collection%20%3D%3D%20null)%20%7B%0A%20%20%20%20return%20%5B%7B%7D%5D%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20The%20actual%20stuff%3B%0A%20%20%0A%20%20var%20objects%20%3D%20Object.keys(source)%3B%0A%20%20%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20var%20counter%20%3D%200%3B%0A%20%20%20%20for(var%20j%20%3D%200%3B%20j%20%3C%20objects.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if(collection%5Bi%5D.hasOwnProperty(objects%5Bj%5D))%20%7B%0A%20%20%20%20%20%20%20%20counter%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(counter%20%3D%3D%20objects.length)%20%7B%0A%20%20%20%20%20%20%20%20arr.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0Awhere(%5B%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%20%7D)) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {
  var arr = [];
  
  // Faking the first where() because it seems buggy but it still doesn't work
  
  if(source == null || collection == null) {
    return [{}];
  }
  
  // The actual stuff;
  
  var objects = Object.keys(source);
  
  for(var i = 0; i < collection.length; i++) {
    var counter = 0;
    for(var j = 0; j < objects.length; j++) {
      if(collection[i].hasOwnProperty(objects[j])) {
        counter++;
      }
      if(counter == objects.length) {
        arr.push(collection[i]);
      }  
    }
  }
  
  return arr;
}

where([{ "a": 1 }, { "a": 1 }, { "a": 1, "b": 2 }], { "a": 1 })
```
<img width="295" alt="screen shot 2015-10-27 at 5 05 44 am" src="https://cloud.githubusercontent.com/assets/6631103/10757468/7bbfe4fa-7c68-11e5-967b-772a2b04df4e.png">

**Comment by DustInCompetent** [comment]
+1

**Comment by carleyf1010** [comment]
I have no clue, can't learn either so idk sorry, I wanna know but my
husband has a great friend out there fucking up my game

**Comment by ltegman** [comment]
The wording of this test is unclear and we have a fix pending deployment to the production website that will clarify what the test is asking for. What it should say (and will soon) is `where([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" })` should return `[{ first: "Tybalt", last: "Capulet" }]`.

@Sepix it looks like your code is returning `[{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }]` and @DustInCompetent yours is returning `[{ first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }]`

Closing this issue since a fix for this test is already in the staging branch, but feel free to reply if you need further clarification.
