### ISSUE TITLE
Rewording of JS: Comparisons with the Logical Or Operator

### ISSUE THREAD

**Issue by jimtryon** [freeCodeCamp/freeCodeCamp#39345]
**Describe your problem and how to reproduce it:**
In the mentioned challenge, it's not clear that the user has to check for invalid values instead of valid values. I wrote my solution as `if (val >= 10 || val <= 20) ` with the intent being that the code would check for 10 and 20, inclusive and after awhile, I could not get it to work so I asked for help in the Discord and found out that in order to pass the tests, we have to check for invalid values. It would help if the text was explicit to indicate this but I was able to pass and move on to the next challenge.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator
**Tell us about your browser and operating system:**
* Browser Name: Google Chrome 
* Browser Version: 84.0.4147.105
* Operating System: MacOS Catalina 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="605" alt="Screen Shot 2020-07-31 at 12 48 30 AM" src="https://user-images.githubusercontent.com/8931936/89012782-98141800-d2c7-11ea-8e16-cf521b5648f5.png">

**Comment by Sky020** [comment]
Hello there,

I do not understand the confusion with the instructions. What would you propose as a change to the wording?

**Comment by RandellDawson** [comment]
> we have to check for invalid values.

Invalid values?  

```js
if (val >= 10 || val <= 20) 
```
Based on the existing instructions, you know if `val` is not between 10 and 20 (inclusive), you must return `Outside`.  This means if `val` is less than 10 OR `val` is greater than 20, you must return `Outside`. 

Your code would return `Outside` for the value 15.  Why?  Because the `val >= 10` is evaluated first and evaluates to `true`.  As learned in the exercise, when an `||` (OR) operator is used, if either the left or right condition evaluates to `true`, then the entire statement evaluates to `true`.

The instructions are very clear on this matter.  It seems more a matter of not understanding how the `||` operator works instead of the instructions being incorrect.

I am going to close this for now.  If you have a suggestion regarding how to word the challenge differently, please feel free to request it be reopened.

Thank you.
