### ISSUE TITLE
pathMigration and LOCALE

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39343]
if `LOCALE` is not set in production, `pathMigration.json` does not get filled properly - it defaults to a single empty json object. In this case the server does not behave correctly, though it does boot without issues.

We need to do two things

- [ ] generate `pathMigration.json` correctly, regardless of the `LOCALE` value.
- [ ] fail fast if it is missing/empty.

We can default to `english` to make sure that *something* is generated, but unless the file is the same in all locales, this might cause worse problems.

Ideally the failing fast should be during CI.  If we can make Cypress close enough to the production environment, that would be ideal.  If not, we should cancel the boot with a message explaining the problem.

**Comment by raisedadead** [comment]
Since https://github.com/freeCodeCamp/freeCodeCamp/pull/39447, this file is unused. Most branches (by extention forks, and PR) which have not been rebased will see this getting created.

We could add this to `.gitignore` but that would be treating the symptoms. I would rather wait until the branches/forks heal themselves.
