### ISSUE TITLE
"Go to Current Challenge" throwing 404 on click

### ISSUE THREAD

**Issue by thediveshsoni** [freeCodeCamp/freeCodeCamp#39369]
**Describe your problem and how to reproduce it:**
The 'Go To Current Challenge' button for logged in users is opening up a 404 page. https://www.freecodecamp.org/challenges/current-challenge

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn

**Recommended fix, suggestions (how would you update it?):**
Update the href attribute of 'Go to current challenge' link to point to appropriate page

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/33605250/89287608-efbcd580-d671-11ea-9668-ef8b8824cb16.png)

**Comment by Sky020** [comment]
Hello there,

Could you please elaborate exactly the steps that lead to you encountering this error?

The _Go to Current Challenge_ button works as expected for me. However, if I click on the link you provided, then I am given the 404 page, due to the fact that I am redirected from here, instead of my profile. So, to clarify, you should not be using the link as a bookmark, as it will only work from a logged-in profile.

**Comment by moT01** [comment]
Any idea what your current challenge is @thediveshsoni? I'm thinking there's a misalignment in the page name and the one that is being linked. I've seen it before - usually a special character that didn't get translated correctly when creating the slugs or something.

**Comment by raisedadead** [comment]
Hi @thediveshsoni can you add more information to this thread when you get a chance?
