### ISSUE TITLE
[BUG] - FCC Glitch projects unavailable

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39392]
**Describe your problem and how to reproduce it:**

The API provided for the Stock Price Checker project is currently unavailable. According to glitch, it appears to have reached its maximum hours for the month. It may be beneficial to find an alternate hosting platform. This issue was brought to my attention by a user attempting to complete this project.

**Add a Link to the page with the problem:**
 
[Glitch Project](https://repeated-alpaca.glitch.me/)
[freeCodeCamp project page](https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker)
[Forum post](https://forum.freecodecamp.org/t/stock-price-checker-api-isnt-running/414620)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 84.0.4147.105
* Operating System: Windows 10 version 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/63889819/89816646-c7165f00-dafb-11ea-88e5-08ebc456c92e.png)

## Edit

It appears this issue is impacting most of freeCodeCamp's projects hosted on Glitch. I'm seeing a lot of posts on the forums about example projects being down.

### APIs and Microservices
[Timestamp Microservice Project](https://curse-arrow.glitch.me/)
[Request Header Parser Microservice Project](https://dandelion-roar.glitch.me/)
[URL Shortener Microservice Project](https://thread-paper.glitch.me/)
[Exercise Tracker Project](https://nonstop-pond.glitch.me/)
[File Metadata Microservice Project](https://purple-paladin.glitch.me/)

### Quality Assurance
[Metric-Imperial Converter Project](https://incongruous-beard.glitch.me/)
[Personal Library Project](https://fuzzy-mink.glitch.me/)
[Sudoku Solver Project](https://bottlenose-eucalyptus.glitch.me/)
[American-British Translator Project](https://youthful-grave-scabiosa.glitch.me/)
*the [Issue Tracker](https://protective-garage.glitch.me/) loads for me*

### Information Security
[Stock Price Checker Project](https://sphenoid-crater.glitch.me/)
[Anonymous Message Board Project](https://spiky-well-vein.glitch.me/)

### Take Home Projects
[P2P Video Chat Application](https://grove-voice.glitch.me/)
[Book Trading Club](https://chrome-delivery.glitch.me/)
[Pinterest Clone](https://wild-song.glitch.me/)

**Comment by nhcarrigan** [comment]
@Sky020 - I've consolidated a list of the projects that are down, to hopefully prevent the need to create additional issues. 🙂

**Comment by Sky020** [comment]
@nhcarrigan , That is excellent! It is nice to have it all here. I will go ahead an close the related issues, then.

_Weird about the Issue Tracker (I assumed all of the projects were under Joseph Livengood's account)_

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for reporting this @nhcarrigan. Sorry I'm just seeing this now.

Seems like this is due to a paid plan that Glitch recently introduced. Now there are just [1,000 project hours](https://support.glitch.com/t/glitch-1000-hours/29723) per month for registered users.

I went ahead and upgraded our account and "boosted" some of our most popular applications ([Timestamp Microservice Project](https://curse-arrow.glitch.me/), [Exercise Tracker Project](https://nonstop-pond.glitch.me/), [URL Shortener Microservice Project](https://thread-paper.glitch.me/), [Sudoku Solver Project](https://bottlenose-eucalyptus.glitch.me/), and [Metric-Imperial Converter Project](https://incongruous-beard.glitch.me/). Those should be up now.

Unfortunately the rest are still down because we've already hit the 1,000 monthly limit. I've emailed Glitch support about raising the limit or resetting it for this month. They're usually good at getting back within 24 hours or so.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Will this issue get closed out once you create your other PR for the remaining Glitch projects in the Take Home Projects section?
