### ISSUE TITLE
Unclear instructions on an FCC CSS Grid challenge

### ISSUE THREAD

**Issue by AnonymousRepositoryStuff** [freeCodeCamp/freeCodeCamp#39433]
* On the CSS Grid challenge "CSS Grid: Use grid-area Without Creating an Areas Template" I think the wording is a little unclear

- Go to https://www.freecodecamp.org/learn/responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template
- Notice the wording on the test reading "item5 class should have a grid-area property such that it is between the third and fourth horizontal lines and between the first and fourth vertical lines."

I think this reads that the area should be a decimal point between 3 and 4 horizontally, and a decimal point between 1 and 4 vertically i.e. beginning horizontally at something greater than three, and beginning vertically at something greater than one.

Leading to incorrect CSS something like:

`grid-area: 3.5/1.5/4/4;`

I'm happy to close this if I am the only person to think this, but I think the below wording is nicer:

**Original:**
"item5 class should have a grid-area property such that it is between the third and fourth horizontal lines and between the first and fourth vertical lines."
**Improved:**
"item5 class should have a grid-area property that begins on the third horizontal line, ending on the fourth horizontal line and begins on the first vertical line, ending on the fourth vertical line."

Leading to something like the below, which would better guide the user to pass the test:

`grid-area: 3/1/4/4;`

This isn't a browser specific problem, I just think it would be a nice quality of life improvement.
![image](https://user-images.githubusercontent.com/25173414/90677381-3bb47080-e255-11ea-97d3-2e14d865cb84.png)

**Comment by nibble0101** [comment]
> "item5 class should have a grid-area property that begins on the third horizontal line, ending on the fourth horizontal line and begins on the first vertical line, ending on the fourth vertical line."

 Aren't you implying that the area starts on the line? The way i have understood grid lines is that they are "width-less"  boundaries of the areas within which the grid items lie.  The numbers 1, 2, 3, ... are just labels for the vertical and horizontal lines splitting your grid container into grid areas. And you can give them any name you want instead of using numbers. From your interpretation it seems you are implying the lines have width hence taking up space and there are sub-grid lines within adjacent vertical lines or adjacent horizontal lines which is not the case. The numbers are just labels for the vertical and horizontal lines enclosing the grid tracks nothing more. 

Perhaps look at

**Comment by AnonymousRepositoryStuff** [comment]
> Aren't you implying that the area starts on the line?

I don't think it reads that way personally. Do you?


I understand your point but I disagree.
I still think my proposed description is an improvement for the item listed above, as I think it is using the same terms the underlying CSS is using. 
`grid-area: 3/1/4/4;` is essentially shorthand for: `grid-area: <name> | <row-start> / <column-start> / <row-end> / <column-end>;`
I think it makes more semantic sense to use the terms "begins" and "ending" in the description of what the user needs to do, to better mirror the CSS.
I got the above snippet from reading https://css-tricks.com/snippets/css/complete-guide-grid/#prop-grid-area

**Comment by nibble0101** [comment]
> I think it makes more semantic sense to use the terms "begins" and "ending" in the description of what the user needs to do, to better mirror the CSS.

If this is the reason for your suggestion, i have no objection. 
Actually my response above is mostly to your explanation of why the change is necessary not the actual change itself, i should have made that clear from the onset:

> I think this reads that the area should be a decimal point between 3 and 4 horizontally, and a decimal point between 1 and 4 vertically i.e. beginning horizontally at something greater than three, and beginning vertically at something greater than one. Leading to incorrect CSS something like: grid-area: 3.5/1.5/4/4;

Essentially what i am saying is that interpreting the instruction that way would mean  the lines take some sort of "width" and/or "height" therefore  the area must exclude that width/height which isn't the case. If your intention is to make the instruction align with the doc. it is okay because even the mighty [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area) is using the same.

**Comment by AnonymousRepositoryStuff** [comment]
Okay, you have been a very helpful sounding board @nibble0101 - thank you for bouncing your ideas/ why it's necessary.

If I make a pull request and go with what I discussed above:
"item5 class should have a grid-area property that begins on the third horizontal line, ending on the fourth horizontal line and begins on the first vertical line, ending on the fourth vertical line."

Does FCC have a process to translate it into the other supported languages? My Arabic leaves a lot to be desired.
Or should I perhaps only change the English?

**Comment by RandellDawson** [comment]
> Or should I perhaps only change the English?

Just change the English version for now.

**Comment by AnonymousRepositoryStuff** [comment]
Thank you for the assistance @RandellDawson
