### ISSUE TITLE
Feature to Refactor SolutionForm

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39520]
Currently, the method `SolutionForm` and `FormFields` uses to parse and display the various fields is convoluted, and prevents customisability.

The main feature is to refactor the code methods for parsing the `placeholders` and `options` objects.

The minor feature is to change `Github Link` -> `GitHub Link` (capital `H`)
![image](https://user-images.githubusercontent.com/51722130/92244473-e0bc8380-eeba-11ea-935b-ce2c734fa9f3.png)

**Comment by RandellDawson** [comment]
It turns out this is a bigger issue than originally expected. With the way the current `FormField` component is designed, the label text and the `name` attribute for the field make use of the field name passed to `fields` prop .  Whoever originally wrote the code was always counting on the Lodash `startCase` method to ignore non-letters characters like `+`.   Unfortunately, the method removes such characters from its return value.  Also, another side-effect of the `startCase` method, is that it modifies the intended project titles to something else. 
For example, the `Visualize Data with a Heat Map` project title gets displayed as `Visualize Data With A Heat Map`, because all first letters of each word are capitalized.
