### ISSUE TITLE
[BUG] - Edge Case Handling on "Define the Head and Body of an HTML Document"

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39531]
**Describe your problem and how to reproduce it:**

In relation to the changes from #39112...

A few things that the tests seem to miss:
1. The tests do not validate that the `head` elements are separate from the `body` elements. The following code passes:
```
<html>
  <body>
  <head>
    <title>The best page ever</title>
  </head>
  <h1>The best page ever</h1>
  <p>...</p>
</body>
</html>
```
2. The reverse is also true:
```
<html>
  <head>
    <title>The best page ever</title>
  <body>
  <h1>The best page ever</h1>
  <p>...</p>
</body>
</head>
</html>
```
3. Adding the required elements at the bottom of the code will pass:
```
<html>
  <title>The best page ever</title>

  <h1>The best page ever</h1>
  <p>...</p>
<head><title></title></head>
<body><h1><p></p></h1></body>
</html>
```
**Add a Link to the page with the problem:**

[Basic HTML and HTML5: Define the Head and Body of an HTML Document](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 85.0.4183.83 
* Operating System: Windows 10 v 1909

**The changes from the PR do not appear to be live yet - these tests were done on a local instance**

**Comment by ruhci28** [comment]
Hii @nhcarrigan I want to work on this issue

**Comment by moT01** [comment]
I believe there is [something in the works to change how the code is rendered in the preview](https://github.com/freeCodeCamp/freeCodeCamp/issues/39101#issuecomment-676477771) so that we could use jQuery on these tests, which would make life a lot easier. It may be worth waiting for that, instead of trying to redo the regex. But, if you want to give a try @ruhci28, go for it. 😄

**Comment by RecodeExistence** [comment]
Could anyone please advise how the error handling works in this case for FCC?  
I have a solution that is working, but want to be sure I'm passing errors correctly.

**Comment by IamSurrett** [comment]
Hey @ruhci28, do you need help working on this issue? I'm willing to help you with it or take it over if you aren't interested in working on it anymore

**Comment by ojeytonwilliams** [comment]
> Could anyone please advise how the error handling works in this case for FCC?
> I have a solution that is working, but want to be sure I'm passing errors correctly.

It's a little complicated, but, basically, errors thrown during a test's evaluation should just be reported as that test failing.

For example, try

```js
function functionWithArgs(param1, param2) {
  console.log(param1 + param2)
  if(param1 == 7) throw Error('Will fail')
}

functionWithArgs(1,2)
```

in https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments 

In this case, the third test fails, because it passes in 7.

**Comment by RecodeExistence** [comment]
Oh no, the code makes perfect sense.  
It was the throw Error bit exactly I was looking for, the method to pass my error string into in order to return to the user that the program was wrong :)  

I'll try to edit my code to include that.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
