### ISSUE TITLE
How to sign up and sign in on local dev server?

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39586]
I was planning on writing some Cypress tests that'll check common user workflows such as creating a new account and signing in with it as suggested in #38611.

Looks like clicking the CTA button on the landing page automatically logs you in with the test/development account. But there's no documentation on how to create new accounts locally and sign in with them. If there's a way please let me know.

**Comment by Sky020** [comment]
Adding this as a reminder (probably for me): Once an answer is given for creating new accounts locally, relay information to [question on forum](https://forum.freecodecamp.org/t/offline-freecodecamp/421004).

**Comment by ojeytonwilliams** [comment]
At the moment everything goes through auth0 unless `LOCAL_MOCK_AUTH === 'true'`, so we don't currently support local account creation.   The dev user is created via `seedAuthUser.js` in which a user object is directly inserted into the DB.

This could be the approach for testing purposes, but I don't think that is of much use.

As far as testing auth0 goes, I'm not sure how we'd go about that - my guess is that we can't realistically mock it, but I don't know.  This is more in @raisedadead's sphere of expertise, though.

**Comment by ahmadabdolsaheb** [comment]
Here is an article I came across that might be helpful for cypress + auth0 integration:
https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/

**Comment by raisedadead** [comment]
We should be able to mock authenticated routes with the local user, seeded in the DB. 

It would not cover Auth0 integration, but it should still cover sessions and any route that needs auth (using the `mock` strategy seen here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/passport-providers.js#L13).

Instead of the development build, you would build for production with `LOCAL_MOCK_AUTH=true`. Then on you can serve the application normally and run Cypress tests with it. 

Clicking Sign-in will appear to take you to `/learn`, but it would still create an actual access-token and set the session cookies, etc.

It's like skipping over Auth0, but that is OK.

It simply means we are able to test everything but the Auth0 hosted page itself. The hosted Auth0 page is not a part of the core platform.

> Here is an article I came across that might be helpful for cypress + auth0 integration:

Good article but needs you to set up Auth0 keys on the CI, which is fine for us - not for the contributors. They would have to get the keys themselves. Not ideal.

**Comment by Sembauke** [comment]
Hey @Twaha-Rahman,

I will be closing this one as a stale issue.

If you still want to work on this feel free to reopen.
