### ISSUE TITLE
A shortcut for doing everything

### ISSUE THREAD

**Issue by GuruTheCoderYoutube** [freeCodeCamp/freeCodeCamp#39635]
Just need  shortcuts to run the tests, download and for everything for productivity

**Comment by Twaha-Rahman** [comment]
I believe there's key bindings for those. @ojeytonwilliams why aren't they documented?

**Comment by Guru-coderZ** [comment]
We hve to see, ya From: Twaha RahmanSent: 21 September 2020 09:28To: freeCodeCamp/freeCodeCampCc: Guru-coderZ; AuthorSubject: Re: [freeCodeCamp/freeCodeCamp] A shortcut for doing everything (#39635) I believe there's key bindings for those. @ojeytonwilliams why aren't they documented?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ojeytonwilliams** [comment]
> I believe there's key bindings for those. @ojeytonwilliams why aren't they documented?

I was working on them here: https://github.com/freeCodeCamp/freeCodeCamp/pull/38203, but I never seem to find the time.  I'll try to get that done before too long.

**Comment by reutKeyshawn** [comment]
Is the issue still relevant?

**Comment by Twaha-Rahman** [comment]
> Is the issue still relevant?

I believe so. (I could be wrong though)

**Comment by GuruTheCoderYoutube** [comment]
>  Is the issue still relevant?


It is feature request I suppose.
I am a beginner, what do I know.

**Comment by ojeytonwilliams** [comment]
@Twaha-Rahman is right, it's still relevant.  However, it's just not the highest priority, so I keep putting it off.  If anyone is interested in finishing it, they're more than welcome to add commits to the open PR.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
