### ISSUE TITLE
Give challenge authors better control test messages

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39658]
**Is your feature request related to a problem? Please describe.**
Challenge tests only report success or failure, with no specific information about why a test failed.  If a test is moderately complicated (i.e. has multiple assertions) and can fail at several points, a user may have difficulty understanding what they did wrong.

**Describe the solution you'd like**
Allow a test writer more control over what a test reports.  For example, if they use an assertion like

```js
assert(expression, "Customised message")
```

Then, if that fails, "Customised message" should appear in the fcc console.  However, if they write.

```js
assert(expression)
```

The default message should appear.  Possibly we can achieve this when we handle `AssertionError`s, but I haven't confirmed this.

**Describe alternatives you've considered**
Encourage contributors to write smaller tests.  Generally this is a good idea, but it's not always practical.  Particularly not for backend tests which can often naturally have a few steps.

**Additional context**

Follows up a  conversation with @SaintPeter in [discord](https://discord.com/channels/692816967895220344/715074489422970962/758360132802707457)

**Comment by SaintPeter** [comment]
For the projects, there are many steps that require an initial setup in order to get a known id.  For example, with the exercise tracker, you have to create a user every time so you can get an id to add an exercise to it.  For the Personal Library, you need to create a book (or books) before you can add comments.  In order for the tests to be atomic, this needs to happen for each test.

In general, we need to be able to give good feedback about what specifically is failing.

I don't have an issue with breaking the tests out into more/smaller steps, but there is some irreducible complexity.

With regards to the message - The `AssertionError` has a `.message` value which is either the default message ("x should be y") or the custom message.  The key would be capturing that it was an `AssertionError` as opposed to an `XHRError` (or whatever those are).

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
