### ISSUE TITLE
Problem with "Build a Technical Documentation Page" (a Responsive Web Design Project)

### ISSUE THREAD

**Issue by JoeCodesStuff** [freeCodeCamp/freeCodeCamp#39672]
#### Issue Description
When trying to fulfill **[User Story No. 14: On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page)**, the check for passing the test **fails** if the **#navbar** element is 50% of the width of the page. This caused much head-scratching on my part, as I tried to fulfill the user story, since I interpreted the phrase "on the left side of the screen" as "filling the left side of the screen" and so I did just that, specifically to fulfill the user story -- but it's not allowed.

#### Easy Fix
- Change the test to accept width values of **<= 50%** (less than **or equal to**) instead of ~~< 50%~~ (less than but **not** equal to).
- Alternately, change the verbiage of the User Story text to indicate that **#navbar** must be LESS than half the page's width.

**Comment by Harshal0902** [comment]
Can I work on this Issue?

**Comment by Sky020** [comment]
This seems like a reasonable change. The relevant code is here:
https://github.com/freeCodeCamp/testable-projects-fcc/blob/95a87141946174f5c77e14799478686b6c0348d8/src/project-tests/technical-docs-tests.js#L329

As it stands, I would not change the wording. There is nothing in it which seems to suggest the width **must** be that of the left-half.

So, for now, a change to allow the width of the `#navbar` to be `50%` will do.

For anyone who finds this later, and thinks their code should pass because the `width` is set to `50%`, remember, `padding` or a `border` could push the value above `50%`.

**Comment by Sky020** [comment]
@Harshal0902 , You are welcome to work on any open issue with a _help wanted_ label. If you have not already done so, please read the [Contributors Docs](https://contribute.freecodecamp.org/#/)

**Comment by JoeCodesStuff** [comment]
Thanks, all! I'd have done it myself, but I was just trying to blaze through and complete everything as quickly as possible.

**Comment by KatFrog** [comment]
Please assign this to me.  I'll fix it this week.

**Comment by RandellDawson** [comment]
@KatFrog If you want to create a PR to fix the issue, definitely read the [Contributors Docs](https://contribute.freecodecamp.org/#/index) as referenced by @Sky020.  We will merge the first PR that addresses the issue.
