### ISSUE TITLE
Inconsistent dasherization

### ISSUE THREAD

**Issue by ltongues** [FreeCodeCamp/freecodecamp#397]
First: the zipline title `Zipline: Stylize Stories on Camper News` dasherizes as `zipline:-stylize-stories-on-camper-news`. Note the dash after colon. However the story on camper news `AppMachine: Make an app within hours. - AppMachine` dasherizes as `appmachine-make-an-app-within-hours--appmachine`. No dash after colon and a confusing double-dash at the end, which brings us to...

Second: one of the requirements of the zipline is to make a link to the story discussion page. In the json that `http://www.freecodecamp.com/stories/hotStories` returns there is a property `storyLink` and for the AppMachine story the value is `appmachine make an app within hours appmachine`.  If I were to turn all spaces into dashes I would get `appmachine-make-an-app-within-hours-appmachine`, which is incorrect (remember the double-dash?).

I think the only way to link back to the page from json is to dasherize the `headline`, which is more difficult to do and probably not intended (otherwise, why include `storyLink`?)

What do you think the proper dasherization algorithm is? Maybe we should just delete all punctuation, trim the string and replace all whitespace with single dashes?

**Comment by ltongues** [comment]
Ok, check this out:
headline: `The full-stack employee — Medium`
storyLink: `the fullstack employee medium`
actual link: `http://www.freecodecamp.com/stories/the-fullstack-employee--medium`

I think it's clear that there's no way to infer the right link from the storyLink property. Am I missing something obvious?

**Comment by QuincyLarson** [comment]
Hey @terakilobyte - I agree, this is important. I think we should remove all non-alphanumeric values and then turn the spaces to dashes. I think we should apply this across: 
- Bonfires
- Challenges
- Stories
- Fieldguides
I think you've already written code that does this - we just need to apply it everywhere. Maybe it could be a shared function in resources.js? This is a priority, because Google is re-indexing our site and we don't want it indexing a bunch of things that will soon become dead links. Let me know if I can help.
