### ISSUE TITLE
Update the Chinese language landing page to look similar to the English version

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39804]
- [ ] We need to: update the Chinese landing page to look like the English-language landing page and use the same assets and everything.
- [ ] Because it would not have a learn page yet, we would need links to the Chinese language forum

**Comment by raisedadead** [comment]
For now this file needs updating: https://github.com/freeCodeCamp/error-pages/blob/master/landing/cn/index.html, which will eventually be replaced by the core learn lading page later.

**Comment by QuincyLarson** [comment]
@raisedadead I just talked with @miyaliu666  about this, and she is going to oversee the translation of the landing page as well as some of the key documents (code of conduct). For now we can use the use the same layout and copy and everything, and just link to the forum instead of linking to /learn. Then once we launch Chinese /learn we can update those links.

**Comment by UsmanAhmadSaeed** [comment]
@raisedadead I'd like to take this up. Can I? And do I need to know Chinese?

**Comment by Ieahleen** [comment]
@UsmanAhmadSaeed instead, why don't you look at the issues labeled with [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted)?

**Comment by UsmanAhmadSaeed** [comment]
@Ieahleen I appreciate that. Except that, I've got busy and will remain so until the foreseeable future, so might not be able to contribute to any issues at all. I'd, however, try to contribute whenever I can.
Thanks and Best wishes!

**Comment by raisedadead** [comment]
Will not need this anymore.
