### ISSUE TITLE
JSRemoveComments Causing Test to Fail

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39925]
Lesson: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-higher-order-functions-map-filter-or-reduce-to-solve-a-complex-problem

This code fails one particular test:
```
const squareList = (arr) => {
// Only change code below this line
return arr
  .filter(num => num > 0 && Number.isInteger(num))
  .map(num => Math.pow(num, 2));
// Only change code above this line
};

const squaredIntegers = squareList([-3, 4.8, 5, 3, -3.2]);
console.log(squaredIntegers);
```
Whereas, if the spaces to the left of `.map` or `.filter` are removed, the code passes.

Helper Function: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/utils/curriculum-helpers.js

MD File: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-higher-order-functions-map-filter-or-reduce-to-solve-a-complex-problem.md

@RandellDawson  pinging

**Comment by ojeytonwilliams** [comment]
Good catch.  The issue here is that the test requires the `.` to be on the same line as the function and the helper produces 

```js
const squareList = arr => {
  return arr.
  filter(num => num > 0 && Number.isInteger(num)).
  map(num => Math.pow(num, 2));
};
```

The helper should not do this, but, depending on how Babel handles whitespace, it might be unavoidable.  If that's the case, we'd need to audit challenges using `removeJSComments` and either `removeWhiteSpace` first or adjust the regex.

Also, this seems like a good example where additional solutions would help catch broken tests.

**Comment by Sky020** [comment]
Would it be beneficial to remove whitespace as well as JScomments within the same function (always)?

Is there any reason we would ever want just the whitespace removed?

**Comment by nhcarrigan** [comment]
The only time I could think it would be an issue is for the few challenges where we are specifically looking at the user's comments - but I'm not sure that we remove whitespace there. If we don't, then I see no reason we can't do both of these at once.

**Comment by RandellDawson** [comment]
I spoke with @ojeytonwilliams a few months back about automatically removing all the comments (JS, HTML, CSS, JSX) from all challenges except where specified with a special frontmatter key for a particular challenge.

We should not be removing whitespace from all challenges though.  Those should be on a case-by-case basis.  The white space issue will soon not be a big deal when we use a CSS parser to capture CSS property/value pairs instead of using regex.

**Comment by Sky020** [comment]
Let me be more specific: All I am suggesting is adding:
```javascript
// A shorter name please!
const removeJSCommentsAndWhiteSpace = codeStr => {
  // Note: removes trailing new lines and tailing spaces at end of lines
  const options = {
    comments: false,
    retainLines: true,
    compact: false,
    concise: false,
    minified: false
  };
  try {
    const ast = parse(codeStr);
    // To be honest, I am not sure whether `ast` also requires this or not \_.._/
    const { code } = generate(ast, options, codeStr.replace(/\s/g, ''));
    return code;
  } catch (err) {
    return codeStr;
  }
};
```

**Comment by RandellDawson** [comment]
I am not sure what that would do.

[See here](https://babeljs.io/docs/en/babel-generator) for `@babel/generator` options.

I honestly do not see a need to combine the two functions, but that is just me.

**Comment by Sky020** [comment]
> I honestly do not see a need to combine the two functions, but that is just me.

I thought the reason is to resolve this issue - `removeJSComments` by itself causes unwanted formatting.

But I have just thought of why removing whitespace is not the best solution, because JS keywords rely on whitespace for delimanation. Probably works for most tests, but can cause other issues down the line.

**Comment by ShaunSHamilton** [comment]
I am going to close this, for now.

Reason: The specific challenge mentioned does not experience this, anymore, and is/was _AFAIK_ the only one experiencing any issue with `removeJSComments`. So, unless this pops up again in _new_ challenges, nothing will need to be done here.
