### ISSUE TITLE
React: Add Inline Styles in React

### ISSUE THREAD

**Issue by rahul1990gupta** [freeCodeCamp/freeCodeCamp#39969]
**Describe your problem and how to reproduce it:**
Correct answer doesn't get evaluated to true.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/add-inline-styles-in-react

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/8749679/95844299-62c78400-0d66-11eb-82f4-2728d9ccbca4.png)

**Comment by Sky020** [comment]
Hello there,

You have not done what the lesson has asked. Whilst your code does cause the styling of the element to be what is expected, the lesson is about `inline-styles`, your code is not using _inline-styles_ to style the element, and so should not pass the challenge.

As such, I am closing this issue. In general, if you have further questions, I recommend you make use of the [forum](https://forum.freecodecamp.org)

I hope this clarifies.

**Comment by lasjorg** [comment]
Forum thread: https://forum.freecodecamp.org/t/add-inline-styles-in-react-bug-if-styles-variable-not-declared-outside-of-component/463592

I'm reopening this because I don't really understand the reason given for closing the issue. 

More importantly, I think we can make it more clear where the object is supposed to be located. That or make the tests accept a class field as well (seems unnecessary to allow both though).


```
// Change code above this line
const styles = {

}
// Change code above this line
class Colorful extends React.Component {
  render() {
    // Change code below this line
    return (
      <div style={{color: "yellow", fontSize: 24}}>Style Me!</div>
    );
    // Change code above this line
  }
};
```

**Comment by kevinsmithidt** [comment]
I think that the failing example does use inline styles (at least as I understand it), it just does it in a way that doesn't use the typical pattern (but I have declared and modified inline styles dynamically in the component before). But then we're assuming that the learner is already familiar with the pattern we are trying to teach.

Perhaps we could add to the instructions:

> Declare your `styles` object as a global variable at the top of the file.

I was thinking about an example, but it might be too similar to the answer. I think the above addition would make it clear with minimal disruption.

**Comment by lasjorg** [comment]
I think updating the seed code with the example I posted would be fine. But @kevinsmithidt suggestion might work as well. I'm fine with either really.

I was thinking that it seems like a good first-time PR but because issues are not visibly bumped up (can you bump issues?), I'm guessing this issue might be buried too far down. I can label it and see what happens, otherwise, we might just have to do it ourselves.

**Comment by Mallikarjunople** [comment]
Hello, I would like to work on this issue.  Can it be assigned to me?

**Comment by ShaunSHamilton** [comment]
Hello @Mallikarjunople 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
