### ISSUE TITLE
Forum and News links are missing from navigation

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#40033]
Users are not able to find any way to navigate to /news or /forum from freecodecamp.org

![screenshot](https://user-images.githubusercontent.com/6234475/96460662-ac89f180-11e0-11eb-8297-130cfd37fe02.png)

**Comment by Sky020** [comment]
For reference, here is the related issue linking to the PR which removed the links: https://github.com/freeCodeCamp/freeCodeCamp/issues/38808

**Comment by nhcarrigan** [comment]
The search bar does crawl the `/news` platform, so there is *some* connection there. But I would be in favour of restoring the two links, myself.

**Comment by ahmadabdolsaheb** [comment]
Thanks @ArielLeslie for bringing this to our attention. The navigation was simplified by design to allow some room for the  night/light switch and coderadio play button that are on the road map.

If there is a related forum topic to this issue, I would appreciate it if you could share the link as well.

@QuincyLarson, any preference on how we should proceed?

**Comment by nhcarrigan** [comment]
A couple of topics where it was mentioned:
https://forum.freecodecamp.org/t/button-of-the-forum/425558/3
https://forum.freecodecamp.org/t/why-the-forum-option-was-removed-from-the-main-site/425124

**Comment by raisedadead** [comment]
And reddit: https://www.reddit.com/r/FreeCodeCamp/comments/jdhwq1/is_the_freecodecamp_forum_shutting_down_soon

**Comment by raisedadead** [comment]
My personal opinion and 2 cents:

When I use YouTube (or Twitter), I find myself clicking through the nav to view a trending page or a subscriptions page. I find that intuitive and muscle memory. I do this daily, multiple times a day.

I do flip the dark-mode toggle on most sites, but that probably happens once in a blue moon, let alone daily or multiple times a day.

Good UX is a pretty straight concept: "Make it like you would use it" - more often than not you do not need second guessing.

**Comment by QuincyLarson** [comment]
@ArielLeslie We are planning on adding a few other options to the /learn navigation bar, such as the ability to switch from light to dark mode with a single click, and to start/stop Code Radio.

We have links to the forum in the footer and in the challenges themselves (the "ask for help" button).

Since about 90% of traffic to the forum comes from Google search (and about 99% of traffic to /news comes from Google search), I don't think removing the /forum and /news will make much difference in terms of usage.

I did see the Reddit thread asking whether the forum was deprecated, and commented there (I saw your comments as well). I suspect this is just some one-time confusion since we changed the navbar.

**Comment by nhcarrigan** [comment]
Heya Quincy~! 

I'm not seeing a link to the forum in the footer.

It sounds like the link isn't the primary traffic driver, but I fielded quite a few questions on our discord as well regarding the loss of the link - so there is definitely some use-cases there. I'd fully support keeping the link in the footer though, if I could find it. 😅

**Comment by jeremylt** [comment]
My concern with this is twofold.

1) Sure, plenty of users access the forum and news via Google, but where do they learn about the forum and news? Since the forum is the recommended way to receive help, shouldn't we advertise it internally and make it obvious to new users that the forum is our recommended educational support community? 

2) This makes freeCodeCamp feel more more like fragmented pieces that don't have much to do with each other. Already I don't know a lot about the news and YouTube efforts because they are somewhat isolated from the learning support communities on the forum and Discord. I have to find and click through a lot of links to find them o, I have to Google, if I have a reminder that they exist. 

I am not aware of a single place where I can see all of the cool stuff that freeCodeCamp does. The more a user has to do to get to the separate pieces of freeCodeCamp, the more they are separate, isolated pieces, in my opinion.

**Comment by ArielLeslie** [comment]
I actively looked for links to the forum and news in the footer and elsewhere and couldn't find any indication that the forum even existed except via "Ask for Help".

I understand that the nav links may not have provided much value in traffic generation, but I'm wondering if this was a deliberate choice in terms of goals for the freeCodeCamp community/experience.

I've always considered freeCodeCamp to be a community that is centered around the curriculum with additional resources that extend beyond the lessons (forum, YouTube, News, chat). Maybe I'm just stuck in the past, but it feels deeply weird to me that going to freeCodeCamp.org doesn't directly reference any of these other resources. It seems though that long term vision is a more silo-ed approach rather than an ecosystem. That makes sense if the future of the forum (and news, etc) is more along the lines of "A better alternative to StackOverflow, brought to you by the creators of freeCodeCamp".

I'm not inviting myself to the conversation about the long term vision for freeCodeCamp, I just wanted to reassure myself that this is a conscious decoupling of /news /forum and /learn, because it took me by surprise.

**Comment by raisedadead** [comment]
Some updates about this: https://forum.freecodecamp.org/t/proposed-improvements-to-the-freecodecamp-forum-localization-approach/426565

We will be adding back the nav items. Thanks for your feedback everyone.
