### ISSUE TITLE
Tests may assume a particular implementation, unit tests include functional tests

### ISSUE THREAD

**Issue by OsakaStarbux** [freeCodeCamp/freeCodeCamp#40043]
Hi, I have some questions about the Sudoku Solver QA project tests.
Firstly, these two unit tests:

- Valid complete puzzles pass
- Invalid complete puzzles fail

Why do we need to test complete puzzles? The user stories can be fulfilled without this. After completing a working project I would have to write more code just to pass these tests.

Then this one:

- Parses a valid puzzle string into an object

It seems to assume the implementation. The project can be completed without this transformation.

This test is in with the unit tests:

- Puzzles that are not 81 numbers/periods long show the message "Error: Expected puzzle to be 81 characters long." in the `div` with the id "error-msg"

This seems more like a functional test. Rather than test a function imported from the code it reaches into the DOM to check what's in a div.

**Comment by nhcarrigan** [comment]
Heya @OsakaStarbux,

My apologies for the delay in responding to this. We currently have a work-in-progress that will refactor this project a bit. 

> Valid complete puzzles pass
Invalid complete puzzles fail

These tests still remain, primarily to verify the error handling of the code - even if I provide a complete puzzle string, I should still receive feedback on whether the string is a valid puzzle or not. 

> Parses a valid puzzle string into an object

This test has been abstracted away. Implementation does need to be somewhat standardised, however, to allow for effective testing through the `/learn` page. 

> Puzzles that are not 81 numbers/periods long show the message "Error: Expected puzzle to be 81 characters long." in the div with the id "error-msg"

This test has been moved to the functional tests and modified slightly - to focus on the back-end implementation rather than the front-end result. 

[This is the relevant pull request](https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver/pull/8), if you'd like to view the proposed changes.

**Comment by moT01** [comment]
I think we are safe to close this with the rework of this project live. If someone feels there is still an issue surrounding any of this, feel free to leave a comment and it can be reopened. Thanks and happy coding 🎉

**Comment by ashwinkadel** [comment]
is I am In for this course?
