### ISSUE TITLE
Rosetta Code: Knight's tour tests likely don't output correct values

### ISSUE THREAD

**Issue by ylevental** [freeCodeCamp/freeCodeCamp#40055]
**Describe your problem and how to reproduce it:**
In my opinion, I would recommend for this problem that only one path for an 8x8 chessboard is found.  See the official challenge: https://rosettacode.org/wiki/Knight's_tour

**The known issue though** is that one line of code says `knightTour(6, 6) should return 35`.  However, a 6x6 chessboard contains a closed tour, so the answer should be 36.  Here is one example: https://www.markkeen.com/knight/images/Untitled7.gif

Because of the symmetric nature of a chessboard, this number wouldn't make sense anyway, as it claims that only one square can't be a starting point.  It could also be that the other results are not correct.

**Add a Link to the page with the problem:**
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-knights-tour/302297 and
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/knights-tour

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux

**Comment by Branamad** [comment]
I took a look into this and you're right. This paper, http://www.math.cmu.edu/~nkomarov/21-110/knighttour.pdf, does the proof for the following theorem: 
An m X n chessboard with m < n has a knight's tour unless one or more
of these three conditions holds:
(a) m and n are both odd;
(b) m = 1, 2, or 4; or
(c) m = 3 and n = 4, 6, or 8.

A 6x6 board does not fall under one of those conditions and so would have a closed tour which would mean all 36 squares have a tour. The linked gif already shows an example of this. Similarly for the last test, an 8x6 board should return 48 while the current solution returns 47. I tried a few things to see if it was just a math error but it turns out that the Warndorff's rule, which is the basis for this solution, is only a heuristic and not guaranteed to return the full solution. The solution could be upgraded to follow the algorithm proposed in this paper,
[SGKnightsTourPaper.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/5669710/SGKnightsTourPaper.pdf),
which adds sets of tie breaking moves based on board position or implementing a backtracking aspect to the solution. 

I'll try my hand at implementing the paper's solution but I wonder if that would make the challenge solution overly complicated. If the goal of the challenge is just to use Warndorff's rule with the knight's tour then I like your suggestion ylevental of just finding one solution for a board. That seems more in line with the 2 minute guideline. It seems like there are some decisions to be made here, I'm curious what others opinions are.

**Comment by gikf** [comment]
That 35 clearly shows something is not right. Here are results that I got from own solution:
`knightTour(6, 6)` -> `36`
`knightTour(5, 6)` -> `28`
`knightTour(4, 6)` -> `12`
`knightTour(7, 3)` -> `10`
`knightTour(8, 6)` -> `48`

It's a bit rough on the edges, but can be looked at [Knight's tour](https://gist.github.com/gikf/ee5742fc41f9404e19b6f303d48400db). Personally I find more interesting finding the number of starting positions from which visiting every square is possible, rather than finding just a single path doing that. Some consideration might also give more complicated testing if path is indeed correct, compared to trivial checking two numbers.

**Comment by gikf** [comment]
Some more regarding the issue.

[Sample soution](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/knights-tour.md#--solutions--) giving incorrect answers is based on the C version from the original [Rosetta Code site](http://rosettacode.org/wiki/Knight's_tour#C). That version however, as it is in the original challenge, is looking just for one path. If it doesn't find path in single path for specific starting position it just moves to the next starting position. This gives some room for incorrect results when used to find number of starting positions, from which complete path is possible.

Here's repl.it of the C version, just with added options to choose board size and starting position from the console https://repl.it/@sanityto/knightstour#main.c. The troublesome starting position for `6 x 6` board for that solution is `2`, `2`. As it can be seen in the visualization the path is searched just once for starting position. Without any tries to wander off and try the alternative paths, when finding one is not successful.
Here's visualization tool showing that path from this starting position is obviously possible: http://paulo-jorente.de/webgames/repos/knightsTour/


Most of the examples of the results that I've encountered are showing the total number of paths for given board, I've found also such that are presented on a board, with allows to verify which position allows to get full path - [5 x 5](https://oeis.org/A165134), [3 × m](http://www.tri.org.au/3x.html), [4 × m](http://www.tri.org.au/4x.html), [5 × m](http://www.tri.org.au/5x.html).

One of these links shows that solution in my previous post also had error! The correct answer for `knightTour(5,  6)` is `30`. Which means that in those two missing cases, possible path wasn't achievable by using only the *best* moves with the least number of next moves.

Trying all other possible moves, after these best moves, very quickly made everything slow to a stop, I had more luck with getting the best next moves twice. That is - after finding moves with the least possible next moves, from the rest of the moves are again searched moves with the least next moves. Thankfully execution time with this change is still within the execution time limit of the tests. This version can be looked at and run at: https://repl.it/@sanityto/knights-tour-js#index.js
