### ISSUE TITLE
docs: RTL is broken and does not reset when switching back

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40062]
Also, if you traverse from a _right-to-left_ language (Arabic, Chinese), then go to English, the text remains _right-to-left:
![image](https://user-images.githubusercontent.com/51722130/96883995-ed039c80-1478-11eb-9dec-51bc486b391a.png)

_Originally posted by @Sky020 in https://github.com/freeCodeCamp/freeCodeCamp/issues/39785#issuecomment-714522654_

**Comment by dipayanDebTheCoder** [comment]
Are translations available ?. Because If I go to the page click on translation and select a language , then the language remains as english , just the LTR or RTL thing changes. 
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/72683956/97952697-57df9c80-1dc4-11eb-8736-fdd5079cc177.PNG">

**Comment by Sky020** [comment]
> Are translations available ?

@dipayanDebTheCoder Not for many of the languages yet. They still need to be translated by contributors.
