### ISSUE TITLE
Logo link is inconsistent

### ISSUE THREAD

**Issue by robole** [freeCodeCamp/freeCodeCamp#40074]
**Describe your problem and how to reproduce it:**
1. Go to https://www.freecodecamp.org/
2. Run a search. Type "Java" into the search field in the menu bar and hit enter.
3. On the search result page, click on the website logo. I would expect to brought back to `https://www.freecodecamp.org/`, but instead it brings me to `https://www.freecodecamp.org/news`.

**Recommended fix, suggestions (how would you update it?):**
The industry norm is to have the logo link to the homepage everywhere on the website. I would update the news pages to reflect this.

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to report this. For as long as I can remember, this has always been the behaviour of the page. I do not expect this to change.

However, there might be discussion about adding `/learn` to the `/news` navbar. I will leave this up for clarification and discussion.

**Comment by robole** [comment]
Hi,

It is your call, but it is not intuitive the way is. I would suggest you change it regardless of how long it has been in it's current state.

**Comment by ahmadabdolsaheb** [comment]
I see the pain point. So currently we have three platforms. /learn, /news, /learn, and clicking logo which each of these platforms would take the users to the "home" of that platform.

By inserting 'java' and hitting enter, you are redirected to the news search page. Therefore, clicking on the nav would results in a redirection to that platform's home page( /news).

@ojeytonwilliams, any thoughts of how avoid the confusion?

**Comment by ojeytonwilliams** [comment]
I'm not sure, but if the logo indicated which platform you were on that might help.  Something as simple as saying "freeCodeCamp curriculum/news/forum" as appropriate, maybe?

**Comment by raisedadead** [comment]
Hi @robole thanks for your recommendation. This is a deliberate navigation choice and may change in future, for now we are keeping it as is.

**Comment by QuincyLarson** [comment]
I have been thinking a lot about this, and I think I have now come to agree with @robole. For the forum, I think it's OK for the freeCodeCamp to lead to forum.freecodecamp.org since that's a different subdomain (and we have the "Visit the curriculum" link on the left hand side of the navigation.)

But /news is on the same www.freecodecamp.org subdomain, and in many cases people clicking that logo would probably be wondering "what is freeCodeCamp"? (about 80% of traffic to /news comes from Google). So I do think it would be OK to redirect these people to / instead of /news.

**Comment by raisedadead** [comment]
See related discussion here instead of this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/41373, I am moving your comment there instead for better visibility.
