### ISSUE TITLE
Incorrect result processing Euler-81

### ISSUE THREAD

**Issue by VadimEv** [freeCodeCamp/freeCodeCamp#40164]
During Euler 81st challange I found that exactly the needed result in testMatrix is checked as wrong:
![Euler-81-error](https://user-images.githubusercontent.com/10043733/97969270-de01e000-1dd0-11eb-8031-bf0c06571b77.png)
reference code for challane is here: https://github.com/VadimEv/ProjectEuler100/blob/master/Euler-81.js
In console I added explicit output to highlight the value given in test run.

**Comment by Sky020** [comment]
Thank you, for taking the time to report this.

The issue is the final line of the code: `pathSumTwoWays(testMatrix)` because your code alters the array (matrix).
1) This means `testMatrix` is changed, before the tests run
2) This is bad-practice, and suggest you change your code to copy the `arr`, and not change the argument passed in.

Moving forward with this, we have two options:
1) Leave the challenge as is, because bad-practice is bad-practice. This reminds campers of that.
2) Have the tests not rely on the visible `testMatrix` variable. This seems to both increase and decrease confusion for some campers.

@RandellDawson Thoughts?

**Comment by VadimEv** [comment]
Can confirm, made a deep copy with help of JSON.parse and JSON.stringify
IMHO it is worth mentioning in relevant challanges difference between shallow and deep copy in case of nested arrays/object with reference to existing [FCC article ](https://www.freecodecamp.org/news/how-to-clone-an-array-in-javascript-1d3183468f6a/)

**Comment by Sembauke** [comment]
Hey @VadimEv,
As Shaun stated:
> This is bad-practice, and suggest you change your code to copy the arr, and not change the argument passed in.

>Have the tests not rely on the visible testMatrix variable. This seems to both increase and decrease confusion for some campers.

and this seems also to be a stale issue.

I will close this issue for this reason.
