### ISSUE TITLE
forum's curriculum nav item should link to relevant language of the curriculum 

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#40372]
If user clicks on the curriculum nav button while visitting the a subform with a non-english language, the user should be redirected to the respective language of the curriculum.

![image](https://user-images.githubusercontent.com/4591597/101236860-7d263a00-36e5-11eb-95dc-75945ef53ff8.png)

**Comment by ahmadabdolsaheb** [comment]
We could detect the url and see if the user is visiting in one of the language subforms for which we have a translated curriculum.

Should that nav item also display the relevant translation of  'curriculum' in that case?

Note: The url does not specify the subform when a certain topic is visited. So preferably the discourse api should be used to detect subforms.

**Comment by Eddiebee** [comment]
The curriculum nav item should display with the translation already used in
subform.

**Comment by ojeytonwilliams** [comment]
If we can use the api, we definitely should. Otherwise we're committing to painful migrations.  And yes, if we can get the subforum from the api, translating 'curriculum' makes sense.

**Comment by RandellDawson** [comment]
@ahmadabdolsaheb @ojeytonwilliams Is this still an issue?

**Comment by ojeytonwilliams** [comment]
@RandellDawson it hasn't been addressed yet - both the Chinese and Spanish forums link back to freecodecamp.org/learn

**Comment by moT01** [comment]
The Chinese forum is linking to the Chinese learn. The rest of the forum languages are sub-categories of the English forum - not sure if we can do anything about that or if it can be any better than it is at the moment. Close this?

**Comment by erikasby** [comment]
Hi, was trying to help with this issue, but looks like I'm unable to help with https://forum.freecodecamp.org/ directly, because I don't have access to it's source.

@ahmaxed already mentioned that it should be done the same way how it works in the https://freecodecamp.org/ already -> when user chooses Espanol language for example, then redirect link to forum has `/c/expanol` in it.

I searched around how to do that on the Discourse platform and I think this [discussion](https://meta.discourse.org/t/can-i-change-the-url-of-the-main-logo/186127) has the solution. I guess there could be some .json file or whatever in the Discourse platform which has available languages of freeCodeCamp website and when user clicks on the subforum and it's name corresponds to the list, then the _href_ of "Visit the Curriculum" can be changed accordingly.

If there is a way for me to test this please let me know I would be glad to help with this issue.

**Comment by ahmaxed** [comment]
@erikasby, Thanks for looking into the issue. Feel free to use https://github.com/freeCodeCamp/forum-theme in a local instance of discourse.  That should give a similar discourse environment to work with. Once you have a working solution submit a pr and we can take it from there.
