### ISSUE TITLE
[BUG] Able to pass challenge "Basic JavaScript: Initializing Variables with the Assignment Operator" with incorrect answers

### ISSUE THREAD

**Issue by ErinVillasenor** [freeCodeCamp/freeCodeCamp#40406]
**Describe your problem and how to reproduce it:**
The challenge asks the user to initialize the value a to 9. However, it seems like any value that starts with 9 will pass the test e.g. 90, 99, 9000, 9999999999.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/initializing-variables-with-the-assignment-operator

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 83.0 (64-bit)
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![bug3](https://user-images.githubusercontent.com/38110750/101560238-a9f18000-3977-11eb-9201-ae44127a7adf.PNG)
![bug2](https://user-images.githubusercontent.com/38110750/101560242-ac53da00-3977-11eb-9877-c546f9e55f80.PNG)
![bug1](https://user-images.githubusercontent.com/38110750/101560246-ad850700-3977-11eb-9e12-bf65cb4e198b.PNG)

**Comment by nhcarrigan** [comment]
Hello~!

Thank you for bringing this to our attention! I did a little digging, and it appears to be due to the regex used to parse the code.

We could either modify the regex to use anchor characters to validate 9 and not 90, or I believe we can assert the value of `a` directly in the test. (Tried this approach locally and it did work).
