### ISSUE TITLE
e2e tests for translated versions of /learn

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40466]
Since we will be building independent versions of the client for the different languages, the current Cypress testing approach won't cover problems specific to non-English clients.

I propose we extend coverage by setting up a parallel test run for one of the new languages (probably Chinese, simply due to it's level of completion, but it doesn't really matter).  We should also add tests covering the 'Go to my current challenge' button, since that will use the English slugs and we want to be sure that we miss any bugs that only appear in the translated site.

**Comment by moT01** [comment]
Many of the tests will be broken since we often use english text to get an element or test an elements text. We should be probably start switching to custom attributes for targeting things. And we won't be able to have tests that check if certain text is on a page or in an element. Unless we want to duplicate our cypress tests for another language, but that doesn't seem like a good approach. Hmm, we could possibly use the json files I made for the client stuff. A test might look something like this:

```
const translations = require(`CLIENT_LOCALE/translations.json`);

it('should contain the text', `translations.key`);
```

That seems doable.

**Comment by ojeytonwilliams** [comment]
I quite like the idea of having a couple of tests to confirm that the translations is being applied, too.  So a hard coded check that the title is "Aprenda a codificar gratis - cursos de codificación para personas ocupadas" conditional on `CLIENT_LOCALE`.  We wouldn't want many like that, though.

> We should be probably start switching to custom attributes for targeting things.

Agreed.  It didn't seem that useful before, but definitely makes sense now.

**Comment by moT01** [comment]
Closing cause we don't have the power.
