### ISSUE TITLE
Update on Helmet X powered By

### ISSUE THREAD

**Issue by santimirandarp** [freeCodeCamp/freeCodeCamp#40476]
**Describe your problem and how to reproduce it:**
In the [first Helmet challenge](
https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet-hidepoweredby) it is said that to hide the X-powered-By set by default in some servers, can help to avoid attacks. I'm not saying this isn't true, but this is an extract from Helmet:

> Removing the header offers very limited security benefits (see this discussion) and is mostly removed to save bandwidth.

They have an interesting side note for express:

> If you're using Express, this middleware will work, but you should use `app.disable("x-powered-by")` instead.

[Source](https://www.npmjs.com/package/helmet)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. I am not sure I understand what you are saying needs to happen/ be changed?

The current `server.js` boilerplate file has what you mentioned: https://github.com/freeCodeCamp/boilerplate-infosec/blob/gomix/server.js#L16

The idea behind the lesson is not _how to use Helmetjs for Express apps_, but _what security measures exist_, and _what do they do._

**Comment by santimirandarp** [comment]
You're welcome. I'd just include or link to helmet npm at least. Because it's not really useful for security, as far as I can see.

I've read the boilerplate, it was great to see that :+1:

**Comment by ShaunSHamilton** [comment]
Ok, after doing more searching into this, I agree there are two things we might benefit from doing:
1) With the version we have set to be installed and used, `hidePoweredBy` can take arguements, but version `4` cannot. So, I would suggest a camper **not** use an option. I.e. remove `app.use(helmet.hidePoweredBy({ setTo: 'PHP 4.2.0' }))`
2) Add some information along the lines of:
> helmet.hidePoweredBy removes the X-Powered-By header, which is set by default in some frameworks (like Express). Removing the header offers very limited security benefits and is mostly removed to save bandwidth.

**Comment by santimirandarp** [comment]
Yes, that'd be great, I was puzzled by the option too, cause they don't include it in the home page at least.

**Comment by moT01** [comment]
I dunno, I really don't see much of a problem here. The challenge says that "Hackers can exploit known vulnerabilities in Express/Node if they see that your site is powered by Express." So it doesn't really claim that it adds security, more that it throws people off. Certainly, a determined person could figure out what is powering the app, this just makes it a little harder. Since the version of helmet we are using allows for the option to set the header, I don't mind leaving that in - I suppose removing would probably be better at this point - although, only slightly. It's certainly nice to update lessons when a package changes, but it's also difficult to keep things up to date.

> If you're using Express, this middleware will work, but you should use app.disable("x-powered-by") instead.
The `app.use(helmet.hidePoweredBy())` method works with helmet v3 and v4 so I'm not sure why it's suggested to use that.

One thing that does bother me here is that the boilerplate has the `app.disable('x-powered-by');` that @ShaunSHamilton pointed out. So if you want to actually see the header, you can't without removing that line no matter what method or options you use.

My vote goes to just removing that line from the boilerplate. I actually don't mind making adjustments to this, but I don't think it's particularly necessary or that the current lesson is inaccurate. Part of my suggestion has to do with the translation effort taking place with the curriculum. When a lesson changes, we will need to start updating it in across all languages. So a minor fix like this becomes a significant effort. All that being said - if the consensus is to make some changes, I won't fight it. If we do end up changing it, I would say to switch to the `app.disable("x-powered-by")` method.

Side note: the `helmet.noCache()` method that's used a few lessons after this was removed in helmet v4.

**Comment by santimirandarp** [comment]
> One thing that does bother me here is that the boilerplate has the app.disable('x-powered-by'); that @ShaunSHamilton pointed out. So if you want to actually see the header, you can't without removing that line no matter what method or options you use.

That's not true just initiate the app, you'll see the header. My point is: you don't want people to learn a useless setting. Idk, seems to me the whole section is rather weak.
