### ISSUE TITLE
Remove solutions from forum hint articles?

### ISSUE THREAD

**Issue by qaz6209031** [freeCodeCamp/freeCodeCamp#40472]
#### Edited by @moT01:
I hope you don't mind @qaz6209031, but I am changing this issue to discuss the removal of the solutions in the hints. I fixed the original issue described below, see the conversation for the new direction of the issue.

**Describe your problem and how to reproduce it:**

There are several bugs in  [freeCodeCamp Challenge Guide: Timestamp Microservice](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-timestamp-microservice/301508) Solutions section
All these bugs can be reproduced by submiting the timestamp project with the solution in the hint

This first bug is a typo
```javascript
 if (dateObject.toString() === "Invalid Date") {
    res.json({ error: "Invaid Date" });
 }
```
`res.json({ error: "Invaid Date" })` should change to `res.json({ error: "Invalid Date" })`

The second bug is
```javascript
if (/\d{5,}/.test(dateString)) {
    dateInt = parseInt(dateString);
    //Date regards numbers as unix timestamps, strings are processed differently
    res.json({ unix: dateString, utc: new Date(dateInt).toUTCString() });
}
```
The `res.json({ unix: dateString, utc: new Date(dateInt).toUTCString() });
  }` should change to `res.json({ unix: dateInt, utc: new Date(dateInt).toUTCString() });
  }` since  unix field is expecting a number not a string

The third bug is a runtime error 
 **Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client**,
I think the original solution is calling `res.json()` twice if we do a get request on projecturl/api/timestamp/1451001600000
So the simplest way to fix this in my opinion is just add a else condition like the following

```javascript
if (/\d{5,}/.test(dateString)) {
    dateInt = parseInt(dateString);
    //Date regards numbers as unix timestamps, strings are processed differently
    res.json({ unix: dateInt, utc: new Date(dateInt).toUTCString() });
} else {
    let dateObject = new Date(dateString);

    if (dateObject.toString() === "Invalid Date") {
      res.json({ error: "Invalid Date" });
    } else {
      res.json({ unix: dateObject.valueOf(), utc: dateObject.toUTCString() });
    }
}
```

**Add a Link to the page with the problem:**
[freeCodeCamp Challenge Guide: Timestamp Microservice](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-timestamp-microservice/301508)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. In general, for the guide posts, we recommend you open a topic on the contributors sub-forum on the [forum](https://forum.freecodecamp.org).

@moT01 @RandellDawson Are we planning on removing the guide posts/solutions for the projects?

**Comment by RandellDawson** [comment]
There has been only limited discussion about it.  I personally think the solutions for the projects should all be removed from the Guide, so the users do their own work and less tempted to see the solution.  It would create more interaction on the forum, which is fine, because that would mean more learning opportunities.

**Comment by nhcarrigan** [comment]
>  I personally think the solutions for the projects should all be removed from the Guide, so the users do their own work and are less tempted to try and reverse-engineer a working solution.

I'm of the same opinion here.

**Comment by ieahleen** [comment]
should the guide posts be deleted (removing "Get a hint" button from projects), or still there but with a message to ask for help?

**Comment by ShaunSHamilton** [comment]
@ieahleen  I would say we should leave the Guide posts and the button, but remove the solutions - in case, in the future, we want to include any sort of hint in the Guide posts.

**Comment by nhcarrigan** [comment]
I'd propose replacing the text in the guide posts with something like "Hints/Solutions are not provided for certification projects as these are intended to be a test of your learning and understanding."

**Comment by qaz6209031** [comment]
> Hello there,
> 
> Thank you, for taking the time to open this. In general, for the guide posts, we recommend you open a topic on the contributors sub-forum on the [forum](https://forum.freecodecamp.org).
> 
> @moT01 @RandellDawson Are we planning on removing the guide posts/solutions for the projects?

Thanks for letting me know

**Comment by ieahleen** [comment]
> "Hints/Solutions are not provided for certification projects as these are intended to be a test of your learning and understanding."

if we have agreement from higher ups, I volunteer in making these changes to the guide

**Comment by RandellDawson** [comment]
We will try to get some feedback from the team by next week.

**Comment by moT01** [comment]
I adjusted the guide article for the time being to fix the original issue and have changed the issue to reflect the discussion. 

This particular article is a solution for one of the certification projects. I am definitely in favor of removing solutions for all of the certification projects. I actually prefer keeping solutions for the regular challenges. I use them often to quickly test challenges, so I'm a little biased. But, I don't think it's a problem to keep those.

**Comment by nhcarrigan** [comment]
> I actually prefer keeping solutions for the regular challenges. 

I'm 100% on board with this (I test against them sometimes too).

**Comment by ieahleen** [comment]
I don't think it was ever discussed removing solutions from regular challenges, it's just the guide page for the projects that some of us were wondering about.

**Comment by ieahleen** [comment]
@freeCodeCamp/moderators 

the discussion here has stopped

The issue is about the guide topics for the curriculum projects
for the JavaScript and Python projects that involve algorithms
 - (only JavaScript) do we keep current solutions?
 - do we accept new contributions from users?
 One pro in keeping solutions is to have a place from where to check if the solution is copied and pasted
 
 for all of them
 - do we accept contributions for the Hints section?
 - do we keep the pages that already have contributions?
 - will they keep existing when the new curriculum will start being rolled out in future?
 
 the threads in question are
 - Tribute Page (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-tribute-page/301147
 - Survey Form (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-survey-form/301145
 - Product Landing Page (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-product-landing-page/301144
 - Technical Documentation Page (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-technical-documentation-page/301146
 - Portfolio (emtpy, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-personal-portfolio-webpage/301143

 - Palindrome Checker (explanation, hints, solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-palindrome-checker/16004
 - Roman Numeral Converter (explanation, hints, solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-roman-numeral-converter/16044
 - Caesar Cipher (hints and solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-caesars-cipher/16003
 - Telephone Number Validator (hints and solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-telephone-number-validator/16090
 - Cash Register (explanation, hints, solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-cash-register/16012
 
- Random Quote Machine (problem explanation) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-random-quote-machine/301374
- Markdown Previewer (empty, asks for contributions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-markdown-previewer/301372
- Drum Machine (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-drum-machine/301370
- JavaScript Calculator (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-javascript-calculator/301371
- 25 + 5 Clock (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-build-a-pomodoro-clock/301373

 - Bar chart (project explanation) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-visualize-data-with-a-bar-chart/301464
 - Scatterplot Graph (project explanation) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-visualize-data-with-a-scatterplot-graph/301467
 - Heat Map (emtpy, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-visualize-data-with-a-heat-map/301466
 - Choropleth Map (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-visualize-data-with-a-choropleth-map/301465
 - Treemap Diagram (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-visualize-data-with-a-treemap-diagram/301468

- Timestamp Microservice (explanation, hints, solutions) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-timestamp-microservice/301508
- Request Header Parser Microservice (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-request-header-parser-microservice/301507
- URL shortener microservice (explanation and hints) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-url-shortener-microservice/301509
- Exercise Tracker (invite to contribute, hint) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-exercise-tracker/301505
- FIle Metadata Microservice (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-file-metadata-microservice/301506

- Metric Imperial Converter (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-metric-imperial-converter/301570
- Issue Tracker (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-issue-tracker/301569
- Personal Library (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-personal-library/301571
- Sudoku Solver (this one is not a single topic, the Get a Hing bring to the search) https://forum.freecodecamp.org/search?q=Sudoku%20Solver%20in%3Atitle%20order%3Aviews
- Americam British Translator (Get a Hint is a search link) https://forum.freecodecamp.org/search?q=American%20British%20Translator%20in%3Atitle%20order%3Aviews

- Arithmetic Formatter (forum search) https://forum.freecodecamp.org/search?q=Arithmetic%20Formatter%20in%3Atitle%20order%3Aviews
- Time Calculator (forum search) https://forum.freecodecamp.org/search?q=Time%20Calculator%20in%3Atitle%20order%3Aviews
- Budget App (forum search) https://forum.freecodecamp.org/search?q=Budget%20App%20in%3Atitle%20order%3Aviews
- Polygon Area Calculator (forum search) https://forum.freecodecamp.org/search?q=Polygon%20Area%20Calculator%20in%3Atitle%20order%3Aviews
- Probability Calculator (forum search) https://forum.freecodecamp.org/search?q=Probability%20Calculator%20in%3Atitle%20order%3Aviews

- Mean-Variance-Standard Deviation Calculator (forum search) https://forum.freecodecamp.org/search?q=Mean-Variance-Standard%20Deviation%20Calculator%20in%3Atitle%20order%3Aviews
- Demographic Data Analyzer (forum search) https://forum.freecodecamp.org/search?q=Demographic%20Data%20Analyzer%20in%3Atitle%20order%3Aviews
- Medical Data Visualizer (forum search) https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer
- Page View Time Series Visualizer (forum search) https://forum.freecodecamp.org/search?q=Page%20View%20Time%20Series%20Visualizer%20in%3Atitle%20order%3Aviews
- Sea Level Predictor (forum search) https://forum.freecodecamp.org/search?q=Sea%20Level%20Predictor%20in%3Atitle%20order%3Aviews

- Stock Price Checker (empty, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-stock-price-checker/301572
- Anonymous Message Board (emtpy, invites to contribute) https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-anonymous-message-board/301568
- Port Scanner (forum search) https://forum.freecodecamp.org/search?q=Port%20Scanner%20in%3Atitle%20order%3Aviews
- SHA-1 Password Cracker (forum search) https://forum.freecodecamp.org/search?q=SHA-1%20Password%20Cracker%20in%3Atitle%20order%3Aviews
- Secure Real Time Multiplayer Game (forum search) https://forum.freecodecamp.org/search?q=Secure%20Real%20Time%20Multiplayer%20Game%20in%3Atitle%20order%3Aviews

- Rock Paper Scissors (forum search) https://forum.freecodecamp.org/search?q=Rock%20Paper%20Scissors%20in%3Atitle%20order%3Aviews
- Cat and Dog Image Classifier (forum search) https://forum.freecodecamp.org/search?q=Cat%20and%20Dog%20Image%20Classifier%20in%3Atitle%20order%3Aviews
- Book Recommendation Engine using KNN (forum search) https://forum.freecodecamp.org/search?q=Book%20Recommendation%20Engine%20using%20KNN%20in%3Atitle%20order%3Aviews
- Linear Regression Health Costs Calculator (forum search) https://forum.freecodecamp.org/search?q=Linear%20Regression%20Health%20Costs%20Calculator%20in%3Atitle%20order%3Aviews
- Neural Network SMS Text Classifier (forum search) https://forum.freecodecamp.org/search?q=Neural%20Network%20SMS%20Text%20Classifier%20in%3Atitle%20order%3Aviews

- Show the Local Weather (empty invites to contribute) https://forum.freecodecamp.org/t/302368
- Build a Wikipedia Viewer (empty invites to contribute) https://forum.freecodecamp.org/t/302360
- Use the Twitch JSON API (problem explanation) https://forum.freecodecamp.org/t/19541
- Build an Image Search Abstraction Layer (empty invites to contribute) https://forum.freecodecamp.org/t/302361
- Build a Tic Tac Toe Game (empty, invites to contribute) https://forum.freecodecamp.org/t/302358
- Build a Simon Game (empty, invites to contribute) https://forum.freecodecamp.org/t/302357
- Build a freeCodeCamp Forum Homepage (empty, invites to contribute) https://forum.freecodecamp.org/t/302349
- Build a Recipe Box (empty, invites to contribute) https://forum.freecodecamp.org/t/302354
- Build the Game of Life (empty, invites to contribute) https://forum.freecodecamp.org/t/302362
- Build a Roguelike Dungeon Crawler Game (empty, invites to contribute) https://forum.freecodecamp.org/t/302355
- P2P Video Chat Application (empty, invites to contribute) https://forum.freecodecamp.org/t/302366
- Show National Contiguity with a Force Directed Graph (empty, invites to contribute) https://forum.freecodecamp.org/t/302367
- Map Data Across the Globe (empty, invites to contribute) https://forum.freecodecamp.org/t/302365
- Manage a Book Trading Club (empty, invites to contribute) https://forum.freecodecamp.org/t/302364
- Build a Pinterest Clone (empty, invites to contribute) https://forum.freecodecamp.org/t/302352
- Build a Nightlife Coordination App (empty, invites to contribute) https://forum.freecodecamp.org/t/302351
- Chart the Stock Market (empty, invites to contribute) https://forum.freecodecamp.org/t/302363
- Build a Voting App (empty, invites to contribute) https://forum.freecodecamp.org/t/302359
- Build a Pong Game (empty, invites to contribute) https://forum.freecodecamp.org/t/302353
- Build a Light-Bright App (empty, invites to contribute) https://forum.freecodecamp.org/t/302350

### Conclusions
We have a lot of "Get a hint" buttons that go to a stub, those could be made to go to a search on the forum, like the Python projects, if we don't want to write explanation+hints there

Guide articles that contains solutions are the JavaScript projects ones, some have several solutions - should we keep accepting user contributions? Should we check if explanations are up to date and all links are still working?
There is also the TimeStamp project that has a solution, only one outside of the JavaScript cert. Keep it? Discard it?

And then, just a few, have a an explanation with hints, sometimes brief, sometimes going pretty deep. Check if they are up to date? replace with search? Check if all links go to the right place?

**Comment by ShaunSHamilton** [comment]
@ieahleen That is excellent booking. I have edited it slightly, so we can keep track.

---

My suggestion is still to keep the button, and remove the project solutions (and the calls to submit solutions). I like Nicholas' suggestion: https://github.com/freeCodeCamp/freeCodeCamp/issues/40472#issuecomment-747667812

**Comment by ieahleen** [comment]
So replace all the stubs with the "No hints for projects" message? What about those that have forum searches from the hint button? and those that have Hints?

**Comment by ShaunSHamilton** [comment]
>So replace all the stubs with the "No hints for projects" message?

Yes, but Nicholas' wording so there is not ambiguity about whether we accept solution contributions or not.

> What about those that have forum searches from the hint button? and those that have Hints?

Replace all with the "_No hints_..." message.

**Comment by ieahleen** [comment]
for the few projects that have explanations or hints? keep, remove? I would be to make everything the same

**Comment by ShaunSHamilton** [comment]
Everything, for the projects, should be the same - no hints, and no explanations. Just a stub with the phrase:
> Hints/Solutions are not provided for certification projects as these are intended to be a test of your learning and understanding.

If we so happen to add hints/clarification for whatever reason, then so be it. However, this should be one of the last resorts for the projects.

**Comment by ieahleen** [comment]
so for this, mods only can edit the guide articles, so that's on us

I don't know what's the process to have camperbot create new topics, but once that's done we can open changing the links iin the challenges files for contributors

**Comment by raisedadead** [comment]
@RandellDawson do we use some of the scripts you had created in the past to automate this?

**Comment by ieahleen** [comment]
I've edited all existing guide articles, now only the forum search ones need new guide articles

**Comment by raisedadead** [comment]
@ieahleen you are a rockstar! 🎉

**Comment by ieahleen** [comment]
@raisedadead for the missing ones, should I create the topics then someone can move them to camperbot, or there is a way to do that automatically?

**Comment by raisedadead** [comment]
I have bumped your privileges on the forum, you should be able to create the posts and transfer them to camperbot.

**Comment by ieahleen** [comment]
Left to do, change the Get a Hint link for the 20 projects still unchecked in https://github.com/freeCodeCamp/freeCodeCamp/issues/40472#issuecomment-820537307, any volunteer for this?
these are the topic links to use 
Quality Assurance
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-sudoku-solver/462357
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-american-british-translator/462358

Scientific Computing with Python
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-arithmetic-formatter/462359
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-time-calculator/462360
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-budget-app/462361
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-polygon-area-calculator/462363
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-probability-calculator/462364

Data Analysis
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-mean-variance-standard-deviation-calculator/462366
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-demographic-data-analyzer/462367
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-medical-data-visualizer/462368
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-page-view-time-series-visualizer/462369
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-sea-level-predictor/462370

Information Security
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-port-scanner/462372
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-sha-1-password-cracker/462374
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-secure-real-time-multiplayer-game/462375

Machine Learning
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-rock-paper-scissors/462376
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-cat-and-dog-image-classifier/462377
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-book-recommendation-engine-using-knn/462378
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-linear-regression-health-costs-calculator/462379
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-neural-network-sms-text-classifier/462380

**Comment by moT01** [comment]
Nice job @ieahleen 🎉 

So the task for that would be to take the number at the end of each of those URL's and put it in the front matter of each english challenge file as the `forumTopicId` - similar to what's at the top of [this one](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/main/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/issue-tracker.md). Seems like a good first timer issue?

**Comment by vipranarayan14** [comment]
This is my first time here. I completed the "JavaScript Algorithms and Data Structures" Certification a few days ago. I learnt a lot. I thank you all very for creating and maintaining this wonderful platform. 

This issue seems to be a simple one. I would like to help you with it.

**Comment by ieahleen** [comment]
@vipranarayan14 we don't assign issues, the first comprehensive PR is evaluated, you are welcome to open yours. If you haven't done so yet I suggest you read our contributing docs at contribute.freecodecamp.org

**Comment by vipranarayan14** [comment]
Thank you, @ieahleen. I was actually waiting for someone to assign me the issue. Now I understand. I will go through the contributing docs and also submit the PR.

**Comment by vipranarayan14** [comment]
I have [submitted a PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42339) with the required changes.
