### ISSUE TITLE
Typo error Basic JavaScript: Do while loops

### ISSUE THREAD

**Issue by frankiefab100** [freeCodeCamp/freeCodeCamp#40493]
**Basic JavaScript: Iterate with JavaScript Do...While Loops**
The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first do one `pass` ...

I think it should be `part`

**Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

**Recommended fix, suggestions:**
The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first do one part ...

**Comment by RandellDawson** [comment]
The word "part` does not really fit here.  "pass" is definitely a better choice than "part".  A "part" of something is a "piece" of something, which does not mean the same thing as "pass".  The word "iteration" might be possible, but "pass" still fits the sentence better.  We could change the word "do" to "make" which could help though (as below).
> The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first make one pass...

Another word could be to use "execute" with "iteration":
>The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first execute one iteration...

Let's get some more feedback, before making a final decsion.

**Comment by jdwilkin4** [comment]
I guess another way to write it could be like this

Do while loops run the statement at least once before checking the condition.  

Similar phrasing to the mdn definition 
The do...while statement creates a loop that executes a specified statement until the test condition evaluates to false. The condition is evaluated after executing the statement, resulting in the specified statement executing at least once.

I think this works too though
The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first make one pass...

**Comment by NirajNair** [comment]
It can be also rephrased as 

> The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will always execute the code inside the do block once before checking the condition stated inside while.

**Comment by ShaunSHamilton** [comment]
I am going to agree with @RandellDawson  on this, and say I do not see a better change.

_"[P]ass"_ is the correct word, in this context. Also, the current verbiage is excellent for describing the main subject of the lesson:
> It is called a `do...while` loop because it will first `do` one pass of the code inside the loop no matter what,

I would not change `do` to _'make'_, because it it not called a `make...while` loop.

**Comment by frankiefab100** [comment]
@RandellDawson i agree with your last suggestion.

```
The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first execute one iteration
```

**Comment by nhcarrigan** [comment]
I'm also in agreement that we don't need a change here.

> The next type of loop you will learn is called a do...while loop. It is called a do...while loop because it will first execute one iteration...

This *might* be a more clear verbiage, but then we lose the explicit breakdown of the `do` and `while` keywords, which I argue is important to leave in the challenge text.

**Comment by RandellDawson** [comment]
I am thinking we should just close this issue as not needed at this time.  I just have not seen many forum topics where this has been brought up in the past.

**Comment by nhcarrigan** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue has been triaged and we have determined that there is no need for a fix at this time. As such, we are going to close this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding
