### ISSUE TITLE
[BUG] - Heroku hosted projects are down

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40521]
The following Heroku hosted projects are down:

- [Chart the Stock Market](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/chart-the-stock-market)
- [Image Search Abstraction Layer](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-an-image-search-abstraction-layer)
- [Voting App](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-voting-app)

It looks like there was a plan to migrate/rebuild these on the `.rocks` domain. These projects are also still hosted on Heroku but are currently up:
- [Nightlife Coordination App](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app)

**Comment by RandellDawson** [comment]
@nhcarrigan When I visited all of the above apps (including the Nightlife Coordination App), they are all down.

These were all created by volunteers about 4-5 years ago before I was involved with FCC.  I believe the Nightlife Coordination App, Chart the Stock Market app, and the Voting App were created by the same person (@arthow4n) .

See below for what I believe are the repos for the ones listed above.

- https://github.com/arthow4n/fcc-nightlife
- https://github.com/arthow4n/fcc-voting
- https://github.com/arthow4n/fcc-stockstream

**Comment by nhcarrigan** [comment]
The NightLife app is working on my end, but I mistakenly linked to the Image Search app here. Updated the link for that one.

**Comment by moT01** [comment]
I adjusted my old projects and added them to the demo-projects repo.

**Comment by nhcarrigan** [comment]
Awesome - thanks!

That seems to leave only the nightlife coordination app as the only one that is "not ours".

Do we have those deployed yet? If so, I can update the links on the challenge pages.

**Comment by arthow4n** [comment]
Hey folks 👋 Nothing special but I just want to say thank you for rolling my sites away. Glad that they helped some folks in the past although I still don't know why they got picked as demo, but those 5 years old sites of mine were just too unmaintained for 2021 😅... The sites were down because Heroku discontinued their free MongoDB add-on which was used by the apps and I haven't got the time for fixing them. Heroku's free PostgreSQL is still a good alternative though.

Keep up the great work, and thanks for FreeCodeCamp helped me starting my coding career!
