### ISSUE TITLE
Challenge "Basic JS: Record Collection" Bug

### ISSUE THREAD

**Issue by AdonisProgramming** [freeCodeCamp/freeCodeCamp#40532]
Hi,

In reference to the challenge here: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

I worked through the challenge and have a working solution but the JSON object is not updated fully and as a result, will not pass the tests needed.

Specifically all tests pass beside the test as follows: 
"After updateRecords(collection, 5439, "tracks", "Take a Chance on Me"), tracks should have Take a Chance on Me as the last element."

Running my code locally via CLI results in the JSON object being updated correctly, this is backed up by the CLI log of the returned object.

When printing the object in the freecodecamp console it shows that object not being updated even though it is the same code.

Code and Images below:

```
function updateRecords(object, id, prop, value) {

if(prop !== "tracks" && value.length !== 0){
  console.log("in first if");
  object[id][prop] = value;
  }

else if(prop === "tracks" && !object[id].hasOwnProperty("tracks")){
  console.log("in 2nd if");
  object[id][prop] = [];
  object[id][prop] = value;
  }

else if(prop == "tracks" && value.length != 0){
  console.log("in 3rd if");
  object[id][prop].push(value);

  }

else if(value.length == 0){
  console.log("in last if");
  delete object[id][prop];
  }

  console.log(object);
  return object;

}
```

![1](https://user-images.githubusercontent.com/31748850/103113926-01e7e200-461a-11eb-9cb5-996be62068dd.PNG)

![2](https://user-images.githubusercontent.com/31748850/103113932-057b6900-461a-11eb-9172-42940c4af6b3.PNG)

**Comment by nhcarrigan** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
