### ISSUE TITLE
Your form element should have the background-color of green

### ISSUE THREAD

**Issue by saatishq** [FreeCodeCamp/FreeCodeCamp#4055]
Hi! please check the snapshot. I have followed the instructions correct, but it still shows the error: "Your form element should have the background-color of green".
![codecamp_44](https://cloud.githubusercontent.com/assets/15331098/10863078/e95fc9ea-7fd2-11e5-94e7-f10913564d5e.JPG)

**Comment by awesomeaniruddh** [comment]
@saatishq Can you please post the link to the waypoint in question?

**Comment by saatishq** [comment]
@awesomeaniruddh http://freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element

**Comment by ltegman** [comment]
@saatishq The link you posted passes all the tests. Based on your screenshot though it looks like you had originally copied and pasted the css declaration from the sidebar description, because the whitespace size is slightly different. The sidebar example code contains thin-space characters which are not valid CSS whitespace. Try typing your CSS declaration from scratch and see if that helps.

Closing as not an issue with the tests but please feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by saatishq** [comment]
@ltegman  thanks! i just reset the codes and typed back.. it worked :)

**Comment by Pretenderr** [comment]
I think need disable "copy past" from example in this case. Or do code in sample more friendly for copy\past.

**Comment by JanPoonthong** [comment]
u using dark reader? or any chrome extensions for dark mode?
