### ISSUE TITLE
List of lectures

### ISSUE THREAD

**Issue by Vince-vegas** [freeCodeCamp/freeCodeCamp#40590]
There is a bug in freecodecamp coding.

e.g

when I pass the coding algorithms why it didn't get checked or save to the database record when I click the **left arrow button chrome browser**

I am grateful for the freecodecamp team
but I would suggest the feature, when a developer pass the coding challenges the data should be send into the database even though the developer might not go to the next coding exercise.

even if the developer click the **chrome left arrow** the data is saved or it should be **checked** on the list.

Thanks freecodecamp.

**Comment by ojeytonwilliams** [comment]
Hi @Vince-vegas, thanks for bringing up this issue.  

We deliberately keep a separation between running the tests and submission.  This gives the user control over their own progress - they get to decide when they're done with a challenge.  Also, we keep this pattern for the projects where a user is likely to submit and test their projects multiple times before finally submitting the finished project.

Finally, code is stored when you run the tests.  If, as you described, you navigate back, you can still return to the challenge later and complete it.

So, thank you for the feedback, but this behaviour is intentional.
