### ISSUE TITLE
 Configure Helmet Using the ‘parent’ helmet() Middleware - Information Security with Helmet JS

### ISSUE THREAD

**Issue by ofk8vb** [freeCodeCamp/freeCodeCamp#40613]
**Describe your problem and how to reproduce it:**
Hello,

 In the challenge description, it says `app.use(helmet()) will automatically include all the middleware introduced above, except noCache(), and contentSecurityPolicy(), but these can be enabled if necessary. `

As of latest version of helmet, contentSecurityPolicy middleware is automatically enabled when top level helmet function is used.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/configure-helmet-using-the-parent-helmet-middleware

**Recommended fix, suggestions (how would you update it?):**
 Description should be: 'app.use(helmet()) will automatically include all the middleware introduced above, except noCache() but this also can be enabled if necessary. '

then we should change the example configuration appropriately.

source:
https://www.npmjs.com/package/helmet

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

It is important to remember, these lessons do not use the latest version of Helmet.js.

Ideally, this whole section would be updated to use the latest version. However, it has not been a priority, since:
A) The new version of the curriculum has been receiving more attention for development
B) The content within the _Information Security with Helmet.js_ section is still useful, and relatively accurate _for the version used_.

_Majority_ of the intended learning outcomes for this section are not specific to Helmet.js, but general web security.

---

So, some options moving forward:
1) Re-work all of the lessons and boilerplate to use the latest version of Helmet.js
2) (_Not Recommended_) Add notes throughout the lesson content explaining these changelog-related updates

**Comment by moT01** [comment]
I think the consensus was to stick with the current version of helmet. I also do not recommend adding a note for each problem that comes up. I think we are fine leaving this as-is and closing the issue. What do you think @ShaunSHamilton?

Side note: the first lesson explicitly says to install v3.21.3. So users should know that they are not using the latest version.

**Comment by ShaunSHamilton** [comment]
@moT01 Ja, if no one has any strong determination to re-work these lessons, then I think there is no issue. We are specifically setting the version. So, any change outwith that version is an added bonus Campers can find in personal R&D.

It is understandable that some might `app.use(helmet())` in a new project, and expect no `contentSecurityPolicy` (and get it). But this is far into the curriculum, and IMO any Camper here should have the know-how to do the specific doc-diving.
