### ISSUE TITLE
Certification coursework description error (Data Analysis with Python)

### ISSUE THREAD

**Issue by gianplod** [freeCodeCamp/freeCodeCamp#40634]
**Describe your problem and how to reproduce it:**
I recently completed the Data Analysis with Python projects and claimed the certification. I noticed that the coursework described in the certificate (400 hs) doesn't match the official one (300 hs), as it appears in the curriculum.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/certification/gianplod/data-analysis-with-python-v7

**Recommended fix, suggestions (how would you update it?):**
Change the coursework to 300 hs.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nhcarrigan** [comment]
Hey there,

Thank you for bringing this to our attention. This appears to be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/39284, so we are going to close this issue as a duplicate. 

If you feel this issue is not related, please provide any additionally relevant information and request that we reopen the issue. 🙂

**Comment by gianplod** [comment]
I did some searching to find any similar issue, but it seems it wasn't good enough. Thank you!
