### ISSUE TITLE
cleaning up

### ISSUE THREAD

**Issue by DvalCaruso** [freeCodeCamp/freeCodeCamp#40640]
,

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
