### ISSUE TITLE
[Frontend Libraries ├ Redux ├  5.Dispatch an Action] Alternative Answer is not accepted 

### ISSUE THREAD

**Issue by abdallahakrab** [freeCodeCamp/freeCodeCamp#40677]
### Description:

The test won't pass if the user passed the action object:
![image](https://user-images.githubusercontent.com/37980706/104291569-5ae1c200-54c4-11eb-87fd-771ee2140d6c.png)

 instead of using the action generator function which returns exactly the same object.
![image](https://user-images.githubusercontent.com/37980706/104291639-71881900-54c4-11eb-856a-dd2ed8880a7b.png)

I am not sure if this is intentional.

### Link 
https://www.freecodecamp.org/learn/front-end-libraries/redux/dispatch-an-action-event

### Browser & OS Info:

* Browser Name: Google Chrome
* Browser Version:  Version 87.0.4280.141 (Official Build) (64-bit)
* Operating System: Windows 10 

![image](https://user-images.githubusercontent.com/37980706/104283634-7c897c00-54b9-11eb-9741-74c9dbe497fc.png)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.
> I am not sure if this is intentional.

This was intentional, and code like this should not pass
```js
store.dispatch({type: 'LOGIN'});
```
This is because it does not follow the instructions of:
> Dispatch the `LOGIN` action to the Redux store by calling the `dispatch` method, and pass in the action created by `loginAction()`.

Whilst the text of the failing test could be clearer, it should fail.

At the end of the day:
```javascript
loginAction() === {type: 'LOGIN'} // Evaluates to false
```

As such, I am going to close this issue. I recommend, if you want to continue any discussion like this, potentially opening a topic on the [forum](https://forum.freecodecamp.org/) will be the best way

Happy coding
