### ISSUE TITLE
FindanIssue.com broken site provided in freecodecamp article 

### ISSUE THREAD

**Issue by muskansawa** [freeCodeCamp/freeCodeCamp#40690]
**Describe your problem and how to reproduce it:**
this is a site made by a developer of freeCodeCamp to help beginners in finding issues where they can contribute in open source.
seems like this website is not working

I am am using windows OS , and google chrome as my browser. 

**Add a Link to the page with the problem:**
in this page-->
https://www.freecodecamp.org/news/use-this-site-to-contribute-to-open-source-ec9b2751cb2/
this is a broken site -->
https://findanissue.com/

**Recommended fix, suggestions (how would you update it?):**

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/44108897/104436594-ceaec800-55b3-11eb-9394-78c613de0050.png)

![image](https://user-images.githubusercontent.com/44108897/104436239-5fd16f00-55b3-11eb-83c4-0b0ec914f0aa.png)

**Comment by raisedadead** [comment]
Hey @scissorsneedfoodtoo, can you take a look and update the article.

**Comment by scissorsneedfoodtoo** [comment]
Hi @muskansawa, thanks for catching this.

Turns out that the site now lives at https://findanissue.org/. I went in and updated the links and text throughout the article.

Please let us know if you notice anything else.

**Comment by ieahleen** [comment]
@scissorsneedfoodtoo it still doesn't seem to be working, it shows only six months old issues, mostly closed

**Comment by muskansawa** [comment]
still the same issue , its not fixed .
 @scissorsneedfoodtoo

**Comment by scissorsneedfoodtoo** [comment]
Hi @ieahleen, thanks for pointing that out. Yes, I took a look at the project's GitHub repo and it doesn't seem like it's been updated since September last year. Not sure if the author/maintainer plans on updating it on a daily basis like it used to be, but at least the site is up for historical reasons.

If you know of a site with similar functionality, please let me know and I can go in and edit those parts of the article.
