### ISSUE TITLE
Enable Ghost's Posts Scheduling

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40718]
TBD: Add details

**Comment by ahmadabdolsaheb** [comment]
@scissorsneedfoodtoo, I am curious to hear your findings about this.

**Comment by scissorsneedfoodtoo** [comment]
Hey @ahmadabdolsaheb, sorry for the delay.

As far as I can tell this is a simple permissions issue. Not sure exactly when they cropped up, but I got this error while trying to schedule one of Abbey's posts:

![ghost-scheduled-post-error](https://user-images.githubusercontent.com/2051070/105686374-8049e380-5f3a-11eb-809c-14023aee6e4c.png)

When I took a look, it seems like the directory and folder permissions for the English News VM are slightly different than the ones on Chinese News. For example some are `drwxr-xr-x` instead of `drwxrwxr-x`.

The Ghost docs have a section about this: https://ghost.org/docs/ghost-cli/#permissions

We're just waiting for a good time to hop on a call and try out the fix suggested in the docs.

**Comment by ahmadabdolsaheb** [comment]
If it is an issue with how ghost is handling internal keys, it might worth raising the issue with ghost as well.

**Comment by scissorsneedfoodtoo** [comment]
Late update -- I wrote on the Ghost forums about our issue here: https://forum.ghost.org/t/scheduled-post-permission-error/19957

**Comment by ieahleen** [comment]
Ghost never answered, if it’s still an issue would it be worth it to reach again to them?

**Comment by raisedadead** [comment]
I might be wrong, but Ghost's team is rightfully opinionated about support on their forum. More often than not, their team does get a lot of backlash for something which is open-source. 

We should probably get in touch with them again, but I think the best path forward is to develop our own tooling. I will take this up myself once I get more time post the 11ty work.

**Comment by raisedadead** [comment]
We have moved over to JAMStack, so this workflow will not be of significance any longer. Going to have to close this for now as a wont-fix.
