### ISSUE TITLE
Change the array used in test or add another case

### ISSUE THREAD

**Issue by chaitanyasjoshi** [freeCodeCamp/freeCodeCamp#40724]
**Describe your problem and how to reproduce it:**
Below mentioned challenge can be passed using simple .sort() function instead of using .sort((a,b) => a-b)

**Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array

**Possible solutions**
1. Change the existing array from [5, 6, 3, 2, 9] to something like [1, 30, 4, 21, 100000]
2. Add another test case with array [1, 30, 4, 21, 100000]

So that the challenge cannot be passed without using .sort((a,b) => a-b) function

**Comment by HristijanGjorgjioski** [comment]
https://user-images.githubusercontent.com/76740146/104847614-6f1d2900-58e1-11eb-8bbc-a82da8ddaa34.jpg
[return-a-sorted-array-without-changing-the-original-array.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/5826328/return-a-sorted-array-without-changing-the-original-array.txt)
Here is my simple solution to this problem. I just use ES6 syntax using spread. **return [...arr].sort();** and that is it!

**Comment by ieahleen** [comment]
I think this is a change that may be necessary, there often cases where users are stumped in following lessons because they use `sort` without an argument and can't understand why the numbers are not ordered from lowest to highest

but I will wait for others to comment

**Comment by jb-larriviere** [comment]
The risks of using `sort` without a callback function are pretty well covered in the previous challenge : 
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method)

I think changing the test case could be a good way to help campers remember this.
And/or adding some sort of warning in the challenge description : "**Caution** : remember that in order to work as expected, `sort` should be used with a callback function"

**Comment by Ismailtlem** [comment]
In order to ensure that the callback function is provided, a test case with the array [140000, 104, 99] can also be added
