### ISSUE TITLE
Concept mentionned when its not been covered in previous challenges

### ISSUE THREAD

**Issue by jb-larriviere** [freeCodeCamp/freeCodeCamp#40738]
**Describe your problem and how to reproduce it:**
Hi everyone,
In the challenge linked below, it is mentionned : 

> So far, you've seen how to use `if/else`, `&&,` `null` and the ternary operator (`condition ? expressionIfTrue : expressionIfFalse`) to make conditional decisions about what to render and when.

I have seen challenges about if/else, && and the ternary operator but not about null.

After looking for some documentation, it appears that it is still a valid method for hiding a component.

**Potential solutions :**

- I think a challenge could be added to introduce this concept.
- An other option would be to modify the [if/else challenge](https://www.freecodecamp.org/learn/front-end-libraries/react/render-with-an-if-else-condition) to cover this concept.
- Finally, a last option would be to delete the mention of this concept in the challenge linked below.

Any opinions ?

**Add a Link to the page with the problem:**
[React: Render Conditionally from Props](https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this issue.

Just to mention:
- No more challenges are being added to this version of the curriculum
- `null` is mentioned (albeit not quite the same way) here: https://www.freecodecamp.org/learn/front-end-libraries/react/write-a-react-component-from-scratch

**Comment by jb-larriviere** [comment]
Thanks for your answer, I agree that `null` is mentionned but it doesn't explain how it can be used for conditionnal rendering.

I was thinking of adding something like this

> **Note** : remember that a React component's render method can return `null`. That can be used to hide a component.

to the [if/else challenge](https://www.freecodecamp.org/learn/front-end-libraries/react/render-with-an-if-else-condition) but I'm afraid it could be confusing, as you're supposed to hide the `h1` in this challenge, and `null` can't be used here.

If that's not an option, I'm happy with closing this issue. At worse it pushes campers to look for documentation, and the answer about how `null` can help with conditional rendering is easily found here : [https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering](https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering)

Any thoughts ?

**Comment by ShaunSHamilton** [comment]
> Any thoughts ?

I think something could be done about what you mentioned. My thoughts are:
- Nothing should be added to: [Render Conditionally from Props](https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props), because it is already quite a _wall-of-text_
- There are very few instructions within [Use && For a More Concise Conditional](https://www.freecodecamp.org/learn/front-end-libraries/react/use--for-a-more-concise-conditional). So, I can see a note being useful in there.

Options:
- Add a note, similar to what you mentioned, to the `&&` challenge.
- Rewrite the `&&` challenge to involve more than 1 component, and make use of `null`

---

I will leave this for others to weigh in, as I could go either way.

**Comment by moT01** [comment]
I do think something could be changed here since it says something like: `you've seen how to use null to make conditional decisions about what to render and when.` - which is false, as far as I can tell. 

I feel like a note about it would belong on the [ternary lesson](https://www.freecodecamp.org/learn/front-end-libraries/react/use-a-ternary-expression-for-conditional-rendering), since that's where I feel like I've seen it used the most. e.g. `return test ? <component> : null`

We could maybe add a second example with a small sentence about how you can use null.

What about just removing the `null` reference from the challenge? - it's an easy fix - I think I vote for this. It really doesn't seem to make sense in the sentence either, `null` isn't a conditional decision so much as a conditional result, no? Maybe I'm playing semantic games there - but yea, I vote to just remove it.

**Comment by ShaunSHamilton** [comment]
@moT01 Good point; `null` is not even needed in this challenge.

@jb-larriviere Do you still agree going with your third potential solution, and remove mention of `null`? If so, we could open this up to first-timers.

**Comment by jb-larriviere** [comment]
@moT01 good point

@ShaunSHamilton that's fine by me !

**Comment by ShaunSHamilton** [comment]
Excellent.

Then, I am opening this up to _first-timers_. What needs to be done is as mentioned in the OP:
> Finally, a last option would be to delete the mention of this concept in the challenge linked below.

That is, the description of the challenge should not mention Campers as having learnt about `null`.


---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
