### ISSUE TITLE
Rapid settings changes causes some issues

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40764]
Go to your settings and try to rapidly change settings - they get stuck...

![Jan-23-2021 16-15-01](https://user-images.githubusercontent.com/20648924/105615430-2d372b80-5d96-11eb-8a2f-4c6362720eec.gif)

I was able to sort of reproduce this on production, but it wasn't nearly as severe or as easy. I got a button or two to get stuck after a few tries. 

On staging happens every time if you try.

**Comment by Durbatuluk1701** [comment]
Just wanted to leave my notes here, I have been able to reproduce this on Production and Dev, but unable to on GitPod.

**Comment by ojeytonwilliams** [comment]
Thanks @Durbatuluk1701, it's interesting that GitPod doesn't show this, since I could see it locally and those should be similar environments.

It looks like there are a couple of problems here.  First being that we send all the flags back to the server, which means that later requests could overwrite earlier ones.  Secondly there's obviously an issue with the front end, which should not get stuck with both public and private highlighted.  It *could* be one issue, but I suspect not.

**Comment by raisedadead** [comment]
We need a little bit of debouncing here (not on the UI) with the requests getting sent to mitigate the rapid clicking issue.

**Comment by Sembauke** [comment]
I am not able to reproduce this bug locally or on GittPod.

**Comment by ojeytonwilliams** [comment]
Thanks for investigating, @Sembauke.  At it's heart it's a timing issue, so, depending on the speed of your connection and the speed of clicks, you may or may not see it.

Here's what happens when I try it on https://www.freecodecamp.dev/settings (the final step is a reload to show that the last button click overrode all the others)

![ClickClick](https://user-images.githubusercontent.com/15801806/107791830-aa7e0c80-6d54-11eb-9eff-530f38ecd529.gif)

**Comment by nhcarrigan** [comment]
Just throwing ideas out there, but I wonder if we could disable all of those setting buttons in the click handler, then enable them after the API response comes back 200.

**Comment by RandellDawson** [comment]
@Sembauke To simulate the slow connection, you can got to the Network tab under Chrome Developer Tools and select Slow 3G and easily recreate the issue described above.

**Comment by raisedadead** [comment]
We do not need to do anything with the UI. We just need to debounce the call. Here is a an article that might help understand the concept: https://www.freecodecamp.org/news/debounce-and-throttle-in-react-with-hooks

**Comment by ojeytonwilliams** [comment]
I'm not 100% convinced debouncing `toggleFlag` alone solves this. IYou'd end up with only the last click registering (i.e. more or less what you see in my gif).  We'd need to debounce multiple toggles of the same `flag` to avoid this.

I think we should also send single updates.  Rather than updating the entire profile when one button is clicked, we should only update that flag.  Combine that with debouncing each flag and you can rapidly change all your settings, but won't end up spamming the api by repeatedly toggling back and forth.

**Comment by Sembauke** [comment]
> I think we should also send single updates. Rather than updating the entire profile when one button is clicked, we should only update that flag.

Shouldn't the API endpoint be updated to receive single values? To my understanding, it's only possible to send the entire object right now otherwise nothing is received back or the values are not updated.

**Comment by ojeytonwilliams** [comment]
Yes, that's correct, both client and server would need updating.

**Comment by Sembauke** [comment]
> Yes, that's correct, both client and server would need updating.

Is this something that needs to be updated internally?

**Comment by ojeytonwilliams** [comment]
Do you mean by staff members? Nope, PRs are very welcome.

**Comment by raisedadead** [comment]
IMHO, I still think adding more endpoints to get around these non-burning issues are a band-aid and over engineered approach. 

The issue at hand is the:

1. Client state of the user object
2. Client UI (a representation of the said state)
3. User object on the DB (via API)

are not in sync. 

And let's see, we have asynchronous calls (ajax) to the API and we have a state-management library in the client. We want to update the db - a "remote" state of the user (via the API) to match it up with the one in the client. 

Sure, we could add more endpoints, but is it the best approach? Do we need the specificity and the literal sync?

To me personally, alongside features like syncing up progress when you connect to internet (already available) this is going in the reverse direction. 

This is not innovation, and adding more logic in solving a non-burning issue seems like adding more cruft long term.

Not against the idea, but not too excited about this.

In any case if implemented, we would want this to be rolled out like so (for my sanity for the ops):

1. PR no.1 adds the endpoints to the API - rolled out on day 1
2. PR no.2 adds the changes to the client - rolled out on day 2
3. PR no.3 removed the old endpoints (mostly to reduce clutter) after PR 1 and 2 have been rolled out. 

The above will ensure a sane non-blocking rollout.

**Comment by ojeytonwilliams** [comment]
Is it fair to say that we want to replace Redux with something easier to understand and maintain?  Apollo, maybe?

I've not played with it much, but the basic idea (let it worry about state management, so you don't have to) seems reasonable. 

Regarding this particular issue, it just depends how soon we're going to get around to overhauling state management.  If it's soon, we should just block this and focus on the overhaul.  I'm not sure when we will, though.

**Comment by Sembauke** [comment]
IMO, I have been looking and trying to find a solution for this problem for about 3 hours now. I came up with a solution that sends single flags.

only to see an updated flag return to its original state when another flag was changed. (Might be caused by me)

Then I went into looking at how the API was called by `sumbitProfileUI` it was very hard to understand.  I agree that some things should be made easier.

**Comment by raisedadead** [comment]
We can take simple smaller steps. [React 17 upgrade is around the corner](https://github.com/freeCodeCamp/freeCodeCamp/pull/41890) and we may want to go the hooks route while at it. If we do https://swr.vercel.app is a natural fit with the existing API

**Comment by Sembauke** [comment]
to get back to the issue,

It seems that what we want to do here is changing the user's settings data without sending the entire object.

Would a PATCH method resolve this? 

@raisedadead

**Comment by raisedadead** [comment]
We would want the API and client to be slightly agnostic of each other, and hence think in those terms.
