### ISSUE TITLE
Search bar disappears from the nav

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40808]
On freecodecamp.org/news, the search bar for searching articles disappears at a smaller width. How can people search?

![Jan-27-2021 09-18-30](https://user-images.githubusercontent.com/20648924/106012259-daed5780-6080-11eb-9d02-10c1b1cddf1f.gif)

There's [some nav updates for the main website in the works here.](https://github.com/freeCodeCamp/freeCodeCamp/pull/40709) - maybe for a reference or something.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb can you confirm the behaviour.

**Comment by ahmadabdolsaheb** [comment]
Yes, that is correct as we removed the menu button in favor of a single donate button. 

I agree that we should reincorporate the menu and and have cookie based donation prompts in addition to/ instead of the  he current donation nav button.

@QuincyLarson how would you like us to proceed?

**Comment by PeterF521** [comment]
So I agree with that, because if we stop to think a bit, Donate button doesn't appear on Homepage so, why It appears on news page?
In my opinion, We have two options:
- We add Donate button to Homepage;
- Or We remove it from News page

**Comment by ahmadabdolsaheb** [comment]
Related: #41035

The news nav as simple as possible to direct the users to the learn platform through the banner.

Adding more items to the mobile nav would require adding a collapsable menu item, and since we are leaning towards exposing the donate button on all screen sizes, there would not be enough space on the nav menu for two nav items and a full logo.

I will be closing this issue for now; however, we will be looking into ways where we could offer search and additional navigation options for news mobile users in the future. 

Please re-open this issue if it has been closed by mistake.
