### ISSUE TITLE
Make autoscroll opt-in

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40825]
We should make the auto-scroll to current challenge on the cert pages as an opt-in (via user settings). This should be off by default.

At the moment for a new user it can be overwhelming and annoying when they are browsing around and trying to read through the intro for the certs. 

Once they have some familiarity, they should be able to discover the setting and toggle it one should they want to. We have reduced the clutter by splitting up the map as is, so the scroll is kind of a distraction.

Thoughts?

**Comment by moT01** [comment]
> At the moment for a new user it can be overwhelming and annoying when they are browsing around and trying to read through the intro for the certs.

One thing to note about the current implementation, is that it only scrolls when a user is logged in - so they should be a little familiar with things - although, probably not a lot of it - I do see how it could be frustrating.

My suggestion was to only auto scroll under two conditions: when a user clicks one of the blocks from the breadcrumb links - or when a user goes to a superBlock that includes their current challenge. This would make it fairly infrequent.

I'm honestly not a fan of creating a setting just for this.

Alternatives:
We could just scrap the auto scroll altogether.
We could only auto scroll when a block from the breadcrumb is clicked.
We could do a "jump" instead of an auto scroll.

**Comment by raisedadead** [comment]
> We could only auto scroll when a block from the breadcrumb is clicked.

I think that would be a pretty neat balance.

**Comment by ojeytonwilliams** [comment]
> We could only auto scroll when a block from the breadcrumb is clicked.
We could do a "jump" instead of an auto scroll.

I think we should do both.  The scrolling just doesn't *feel* great to me.

One thing we definitely want to remove is the scrolling when you navigate forward and back on the browser, that's really confusing.

**Comment by ahmadabdolsaheb** [comment]
I think the only use of auto scroll would be when we need to navigate the user to a certain part of a page, but we would also want the user to see that there are other content in the page.

Autoscroll might work well with breadcrumbs, but we should otherwise jump when linking to ids.

**Comment by moT01** [comment]
To be clear, we want to auto-scroll to a block when someone clicks a block from the breadcrumb
And, we want to "jump" to the block of a users current challenge if they go to a superBlock page that includes their current challenge.

So would we still want a setting to enable/disable this? I am still voting no on that, doesn't seem worth it for just those two instances - but I won't fight a consensus.

**Comment by raisedadead** [comment]
> So would we still want a setting to enable/disable this?

Here are the user stories that I can think of:

1. In between page navigations DO NOT scroll ever. (back & forward buttons)
2. Use scroll if the link clicked was a "block link", but take them to the block instead. 
3. Use jump to top of the page if it was a "super-block" link - this lets users glance the intro.

None of the above require a dedicated setting.
