### ISSUE TITLE
Navbar UI improvements

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40821]
This is an issue to discuss general improvements to the navigation.

- The logo and the search bar are is being set absolutely in certain scenarios ( width ). We should use flexbox to make the code more maintainable.

- To save real-estate in small screens the menu item could be simplified to a burger menu in small screens
- To improve visual consistency the sign up button could have a similar padding to the menu button when the view allows, and all items could be aligned from the left equally including the search bar ( in mobile )
- The language nav item shares the same background with the search bar which is an active element. We could avoid that by having a different background for the isDonating message, have a disabled background and font for the 'sign in to change theme' and visually nesting the languages by add extra padding
- Although each functions differently, they look the same. We could add checkbox/ toggle for the theme switch, radio button for language selection, double arrow (similar to landing page certificate buttons) for in app links, and new tab icon for items that opens another platform in a new tab.
- items such as sign out and settings could be added for ease of use.
- Items could be grouped based on their functionality by having them above one another and isolating them with a  border 

Here is a quick wireframe to start the discussion (updated):
Descriptions left to right: signed in, signed out, signed in donating.
![image](https://user-images.githubusercontent.com/4591597/106186692-aaf3a080-61b5-11eb-8803-e8b41bd4eadd.png)

**Comment by moT01** [comment]
Overall, I like it @ahmadabdolsaheb 🎉

Are we sure we want to add the Settings and Sign out buttons? I'm in favor of it, but I don't think they were included in the original discussion. The news link is missing from the image - just an FYI - I know it's just a wire frame.

One issue I see - the language links currently open in new tabs I believe, the radio buttons don't really imply that. Visually, I think they look great - We could perhaps try to get those to open in the same tab (which, I think I would prefer) - then I would be on board with the radio buttons. Otherwise, maybe they could use something like the forum and radio buttons - maybe with a checkmark next to the current lang? - Really though, they aren't too bad even if the links open in a new tab.

> The language nav item shares the same background with the search bar which is an active element

I do like the different background for non-clickable items. Perhaps we could just make it more subtle. It probably wouldn't be too bad though if they had the same background as the rest of the buttons, but just didn't have the hover effect.

**Comment by ahmadabdolsaheb** [comment]
Yes, I missed the news link :)

I added settings and sign out as suggestions. they have not been confirmed.

Is opening a new tab with a new language by design? I am not sure how having both tabs open would be beneficial. It would make more sense to redirect. 

We could style the donation message similar to success flash messages( green on green ), the "sign in to change theme" as inactive ( quat color on quat background), and leave the "languages" item as is without a hover effect.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb I love the subtle horizontal breaks in the navigation, and the "opens in new tab" symbol. I think this looks solid. If changing the language results in opening new tab, we should probably visually indicate that somehow. How hard would it be for us to just change the language without opening a new tab? I'm not saying we should do this for our first release, but I'm curious if there's a quick hack for this.

Am I correct that the empty box in the navbar will be where the authenticated user's profile image will be?

I agree that – given enough space, the sign in button should also be in the nav bar to the far right. I do think we want to use the golden CTA color for this to catch peoples' eyes.

I agree that in extreme cases, we could show the hamburger icon instead of the "Menu" button. But spelling things out is always preferable.

Finally, the words "Menu" and "Sign in" do not seem to be vertically centered in the images above.

**Comment by nhcarrigan** [comment]
> How hard would it be for us to just change the language without opening a new tab?

This could be accomplished with `sameTab={true}` I believe.

> I agree that – given enough space, the sign in button should also be in the nav bar to the far right. I do think we want to use the golden CTA color for this to catch peoples' eyes.

This is the current functionality - though in https://github.com/freeCodeCamp/freeCodeCamp/issues/40820 we were discussing the viability of moving/hiding the button on small screens. In our current draft, we modified the `profile` link in the dropdown to become a `sign in` link during unauthenticated sessions, which allows us the option to hide the `Sign In` button at screen widths of less than 365px (slightly larger than the breakpoint for the responsiveness issues in the aforementioned issue).

**Comment by raisedadead** [comment]
Closing as shipped please open fresh issues as needed.
