### ISSUE TITLE
Rework coding interview prep challenges

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40896]
Many of the coding interview prep challenges, specifically the rosetta code and project euler challenges I believe, ask for a specific amount to be returned. e.g. "Your function should return 12345". We should rework all of them so the function takes an argument and returns something based on the argument. More [description here](https://github.com/freeCodeCamp/freeCodeCamp/issues/38809#issuecomment-637460224), and there's a PR linked in that issue with an example of a challenge that was adjusted.

If anyone adjusts one of these challenges, just reference this issue. If a large amount of challenges get reworked, we can make a list of the ones remaining at some point. I would keep PR's to a single challenge at a time.

This can be a discussion for now to make sure we can go ahead and start accepting PR's.

**Comment by nhcarrigan** [comment]
So I don't disagree that these would benefit from more clarity - however:

Doing so would deviate from the original challenges - is that something we're okay with? What's the ultimate intent behind incorporating these in freeCodeCamp's curriculum?

**Comment by moT01** [comment]
The clarity of these challenges isn't what this issue is for. To try and be more clear, this would take the existing challenges and slightly restructure them so that they can't be passed by just returning a number. So that's the intent, to make it so you can't pass them with code like:
```
function() {
  return 12345;
}
```

So instead of having (hypothetical) instructions like "return the 10th number in the sequence" - they might say "return the 
nth number in the sequence". And `n` would be passed to the function. Then, we could write tests like:
```
function(5) should return 123
function(10) should return 12345
```
instead of
```
Your function should return 12345
```
I'm not sure if deviating from the original rosetta or euler challenges is going to be a problem. I suppose that's something to discuss. I don't mind it, and I think this may have already been done to some of them.

**Comment by ojeytonwilliams** [comment]
Sounds like a good plan.  If we do change to instructions like "return the nth number in the sequence", I think it would help to add "where n is <= `<the original number>`'  Reason being, it would be frustrating to run into timeouts and fail when your algorithm is correct, if not quite fast enough.

**Comment by moT01** [comment]
I don't mind adding something like that to the instructions. Although, it kind of seems like that might be more on us to just not write tests that exceed the number. Either way works.

**Comment by moT01** [comment]
Thanks for working on these @gikf & @Ne0nWinds. I had a thought as I was reviewing one of these - perhaps we should include one test on each challenge with a random input so users can't see all the values that are being tested. The text might be `function(n) should return the correct value` and the test would check a value different from the other tests. This would be to help deter the problem described here.

**Comment by gikf** [comment]
I don't really know. As much as that would make a bit harder for somebody wanting just use results to fool tests, it won't stop from reading challenge code. Looking at the other side there's also possibility of somebody sincere being affected by it, if for some reason *hidden* test would hit some edge case. With solution that's matching *visible* tests that might be rare, but still possible.

**Comment by Ne0nWinds** [comment]
@moT01 I was actually thinking the same thing! I can add it to my PR when I get a chance

**Comment by Ne0nWinds** [comment]
@moT01 To add on to what @gikf said, for problem 461, I had a solution that was correct for low numbers, but got less accurate with high numbers. This would've been really confusing if the hidden test case was a higher number than the visible ones. I do like this idea, though. I think it would be better if one or two test cases were slightly randomized (but still visible). I'm not sure how we'd actually implement that

**Comment by moT01** [comment]
Thanks for the input. I feel like we should come to a consensus on it so we can be consistent moving forward. I could go either way. The safe play is probably to just not include a test like this, but I do like the idea - so I'm torn.

As for actually randomizing the test - we could randomize the test, but the text can only be static. So there would be the same concern there.

**Comment by nhcarrigan** [comment]
I'm personally not a fan of "hiding" the test input/output, and here's why:

- First, it makes debugging more streamlined if a camper can see the input and expected result, vs having to jump through hoops to figure that out
- Second, it makes things smoother to catch if we have a bug in our test case - "Your test expects the value of 25, but really it should be 26".
- Third, it keeps in line with our general practise of transparency to include the input/output in the test text.

I do understand there is a concern that I, as a camper, could write a bunch of "if parameter is X, return Y" to pass the tests, but then I'm really only hurting myself, right?

**Comment by moT01** [comment]
Alright, I think that settles it. Let's avoid those tests for now then @Ne0nWinds & @gikf.

**Comment by moT01** [comment]
There's been some discussion about how to display mathematical equations on a few of the open PR's. I think we should come to a consensus on that, as well. I looked around and most challenges don't use inline code around math - a few do. I think moving forward we should use mathJax around all math equations and variables etc - and reserve the backticks for computer code. It looks like there's [some options we can use](http://docs.mathjax.org/en/latest/web/typeset.html#conversion-options) to make mathJax display a little differently if we want to at some point. What do you all think?

**Comment by gikf** [comment]
Keeping math to MathJax and code to backticks sounds sensible, What about a case with lone number, as a part of sequence, which refers to both code and math?

**Comment by nhcarrigan** [comment]
@moT01 do you know of any files that currently use the MathJax?

**Comment by moT01** [comment]
I found a few - 81 ([code](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-81-path-sum-two-ways.md) - [demo](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-81-path-sum-two-ways)), 82 and 83 are similar. There are also some that have a comment, `<!-- TODO Use MathJax -->`. 

more: [368](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-368-a-kempner-like-series), [377](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-377-sum-of-digits-experience-13), [431](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-431-square-space-silo), [450](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-450-hypocycloid-and-lattice-points), [463](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-463-a-weird-recurrence-relation), [471](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-471-triangle-inscribed-in-ellipse), [473](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-473-phigital-number-base)


You can right click the math and pull up some options.

Some others use inline html like 6 ([code](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/29e91dc3a314d68583b2cf782c635127ea41ca8c/curriculum/challenges/chinese/10-coding-interview-prep/project-euler/problem-6-sum-square-difference.md) - [demo](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-6-sum-square-difference))

**Comment by nhcarrigan** [comment]
So the downside with MathJax (vs code blocks) is that it doesn't register in Crowdin with anything we could use to hide the strings or detect translations.

@RandellDawson was poking at it, and it looks like sometimes we wrap the math in `<big>` tags which we *could* use, but that's not a consistent standard we follow.

**Comment by moT01** [comment]
And the upside is that it looks right.

Do you think people will try and translate them if they aren't hidden? I see some numbers in the [Chinese file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/01-responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template.md)s that just stayed as 1, 2, 3, ...

**Comment by nhcarrigan** [comment]
I do think it's a possibility - we could rely on proofreaders to catch it, but it's nice to have extra validation in place.

**Comment by RandellDawson** [comment]
> Do you think people will try and translate them if they aren't hidden? I see some numbers in the [Chinese file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/01-responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template.md)s that just stayed as 1, 2, 3, ...

We have already seen some translations of `code` tag content where they did not make a different translation, but they spelled the name of the function with a different case.

**Comment by Ne0nWinds** [comment]
I do like the idea `math to MathJax and code to backticks` as a general rule of thumb, but I have a few thoughts:
1. The math symbols in mathjax and the ones in backticks are completely different, so try to stay consistent with whatever you introduced the symbol as (Look at the phi symbol in the equations vs the one in `gcd`)
![image](https://user-images.githubusercontent.com/36315399/110077281-b4cf6d00-7d3a-11eb-9005-03954423451c.png)
2. I think backticks are better for simple math equations (add/sub/mul/div), because these things can be directly translated to code
3. A few things may just have to be decided on a case by case basis depending on what's more readable / makes sense.

**Comment by RandellDawson** [comment]
For localization, we need a way to validate these equations don't get change or at least if they do, a QA message prompts the translator and proofreader when reviewed.  One easy way to do that currently, is to nest all of the matJax stuff in `big` elements.  It is best if they are in there own separate paragraph.  This creates a special `big` context we can use to make them untranslatable.

**Comment by gikf** [comment]
Below 100 of Project Euler there's few challenges left that may not be as feasible or straightforward to change. Does anybody have any ideas for these challenges?
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-33-digit-cancelling-fractions - Checking numbers with 1 digits in numerator and denominator wouldn't make sense. 3 digits would make challenge harder than original one.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-34-digit-factorials - Only two numbers are fulfilling requirement.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-44-pentagon-numbers - Challenge ask for minimized value of `D`, but that's actually already the first such value.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-45-triangular-pentagonal-and-hexagonal - This one is already requiring argument and there isn't much room for adding more tests, except of example and answer there's just one other case (number `1`) which could be added.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-46-goldbachs-other-conjecture - Challenge already asks for smallest number matching requirements.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-49-prime-permutations - As challenge description explains there's no such sequences from `1`, `2` or `3` digit primes, and both sequences with `4` digit primes are used in example and answer.
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-60-prime-pair-sets
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-68-magic-5-gon-ring
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-90-cube-digit-pairs
- https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-93-arithmetic-expressions

Those above 100, I'd start with some basic cleanup, rather than full reworking. One reason is they are in worse state - i.e. function named in pattern `eulerXXX`, missing images in description, or some other mangling in description. Another reason is the difficulty significantly rising at that point, which makes full rework that much harder.
As the cleanup shouldn't be as demanding, I'd go with more challenges in single PR, rather than one challenge one PR, as it is for full rework. What do you think?

**Comment by moT01** [comment]
> Those above 100, I'd start with some basic cleanup, rather than full reworking.

I would be fine with that @gikf 👍 There's 380 challenges higher than 100, I would try to limit PR's to maybe 25 or so - maybe 50 if they are looking easy to review. Make sure that we are keeping them as closely aligned as we can with what the original Euler challenge is asking for.

I'm not sure exactly what to do with the #'s <100 in question. I don't think there's a blanket solution - they will probably need to be handled case-by-case. Maybe we come back to them later.

**Comment by gikf** [comment]
There are also places with listed all answers, without the need to look for them one-by-one.

**Comment by moT01** [comment]
Update on this: Many of those PR's that made changes to Euler just made an improvement to them that partially helps with the issue here, but doesn't make the full adjustment. So the list that hasn't been changed is still quite large.

**Comment by Florenciasicre** [comment]
@moT01  @gikf  can you review my PR for problem 125?
