### ISSUE TITLE
i18n: Handling Missing Files

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40907]
@RandellDawson and I pulled down #40906 to test the build. Adding `espanol` to the allowed curriculum languages allowed the `ensure-env` run to pass, as expected. We added `responsive-web-design` to the `is-audited.js`, and ran `clean-and-develop`.

The GraphQL query errors out, presumably because the `espanol` folder is missing challenges, presumably. 

![image](https://user-images.githubusercontent.com/63889819/106833974-63ec2c00-6649-11eb-8dff-e07425bd2c86.png)

The build fails, and the development instance will not load.

While the intention is to have a 100% completion of a superblock prior to enabling it in `is-audited.js`, this will potentially become a significant issue going forward as we add/remove challenge files. There are definite concerns here, especially looking forward to the V7 curriculum, where modifications to the flow will break or block deployments.

 @ojeytonwilliams - is it possible I missed a configuration during the testing? I noted the comment in the `is-audited.js` file that explicitly states the superblock should be 100% complete, so a build error is what I was expecting, but is this the ideal approach?
 
 @raisedadead - I'm not sure of the specifics of the deployment pipelines. Would a merge to `production-current` trigger a build on all i18n sites simultaneously? Or are we able to push each one independently?

**Comment by raisedadead** [comment]
> I'm not sure of the specifics of the deployment pipelines. Would a merge to `production-current` trigger a build on all i18n sites simultaneously? Or are we able to push each one independently?

Yes - you are correct, at the minute we deploy on a commit basis regardless of what files a commit touched. That is the underlying assumption is because a commit is a snapshot of the repo at some instance of time, it's wise to build and deploy the sources across API, and clients matching the commit.

Its costly, but is sane from an operator's perspective.

So, to work around the problem where may not have sources ready as in the case of Espanol, we are "falling back" to building sources in English. To make this a bit flexible we are doing this on a per-cert basis.

The assumption again is that we would not adding a cert to the list of ready to build unless is ready to be pulled from Crowdin.

And - you are right this will make it difficult going forward where we are doing this microscopically at a challenge level, and at such point in time we would be expanding this array to be microscopic as well.

Here is an off the top of my head approach when we do get there:

- At the moment we are building certs by saying any cert in the array of `is-audited` should be built for a language that we chose in the pipelines. This is obviously falling back nicely to English for a cert that is not ready.
- In future we expand the same logic to get if a cert & an array of challenges in the cert is ready for build as well. The list of challenges necessarily may not be hard coded. When we add and remove challenges, we should be able to programmatically add/remove from this list.
- Finally, we expand our validation logic to look at not only the audited cert list, but also the audited challenge list.

This sounds ugly on the paper but is a cost of maintaining i18n in a same way. We always will have the catching up to do where the languages lag behind the primary dev on new challenges. But above all it's just an engineering challenge IMHO, so doable.

**Comment by ojeytonwilliams** [comment]
> a significant issue going forward as we add/remove challenge files. There are definite concerns here, especially looking forward to the V7 curriculum, where modifications to the flow will break or block deployments.

Right, but the build is failing here because that PR only includes a subset of one cert for Spanish.  To build, at the moment, we need to have all the Spanish challenges, translated or otherwise.  The above error is happening because Gatsby builds its schema from the objects we pass it (which means it needs at least one of each type of challenge).  

We do need to decide what to put in the translated clients when we add or remove a challenge. Regardless, it's important that some stage of the build fails if there isn't a 1-to-1 map between English and each other language. That way we can avoid deploying a client in a broken state.

Just to complicate things slightly, I envisage phasing out `is-audited` in the future, rather than expanding it.  It's useful at the moment, so that we (as devs) can make 100% sure we're releasing entire certs.

Longer term, when we have everything translated, we can rely on Crowdin to provide eventual consistency.  If we can tolerate a few challenges having a few machine translated strings, I think it would be fine to just use whatever comes back from Crowdin.  As long as we push upcoming changes to Crowdin enough in advance, it should be fine.

**Comment by RandellDawson** [comment]
I am going to add a complication here.  I have found a flaw with the current Crowdin workflow.  Currently, there are 3 steps:

1. Upload all applicable English challenge file
2. Delete any files off Crowdin that are no longer present on `main` branch
3. Hide/Unhide strings based on our specified criteria

The problem is, if we delete a file off Crowdin, when we do the next Download from Crowdin, the non-English challenge files that were removed in Step 2 above are not affected (deleted).  Why?  Because Crowdin's action only adds/replaces files.  It does "know" that we want delete a file.

One solution to this problem is we will need to have an additional step between the existing Step 2 and Step 3 of the upload workflow that creates a commit/PR to delete the corresponding non-English files identified in Step 2 from the repo.

**Comment by ojeytonwilliams** [comment]
I'm in the process of writing a test to check that all the English files have corresponding translated files, so we'll at least know if something went wrong before we try and deploy.

**Comment by raisedadead** [comment]
I think we are all on the same page. Either way we all want that any files (I repeat files) added or removed to English curriculum should be added/removed simultaneously from all non-English curriculum.

So, essentially, we have two cases, files added and files deleted.

At the minute we are using this is-audited array for our sanity, but once we hit 100% on our current pre 2020 certs we should phase that out.

So, circling back to the two use cases:

1. Files deleted could be removed with a commit to the codebase removing them all across.
2. Files added should be using some form of fallback, even if it means literally copy pasting the English version over (won't be a terrible idea honestly).

What do you all think?

**Comment by ojeytonwilliams** [comment]
Yep, that's exactly how I think it should go.

We don't duplicate the `meta.json` yet, but your mention of 'files' makes me wonder if we should.  However the only translatable bit is `"name": "Advanced Node and Express"` so maybe it should be handled differently, idk.

**Comment by RandellDawson** [comment]
> Files deleted could be removed with a commit to the codebase removing them all across (and Crowdin of course).

Currently we only remove files from Crowdin via the action that runs before the strings our hidden/unhidden on Crowdin as part of the upload workflow.  Currently, we are only running the upload workflow sporadically but plan to eventually run this on some kind of schedule (daily).  Are you suggesting that we would somehow run the delete action (to remove files on Crowdin) as part of a new workflow that "listens" for commits that delete non-English files?  That is doable.

**Comment by raisedadead** [comment]
> Are you suggesting that we would somehow run the delete action (to remove files on Crowdin) as part of a new workflow that "listens" for commits that delete non-English files? That is doable.

Does not need to be fancy, a sane manual `workflow_run`, that purges it all across. Chould be scoped to be executed by observers in the curriculum team.

**Comment by ojeytonwilliams** [comment]
Randy raised a concern - can we construct a Crowdin workflow that defaults to untranslated if a file isn't, say, 100% proofread? At the moment we only know how to get the accepted files.

If we can't, then we need to change how we build the curriculum, so that it can work with a partial download like in https://github.com/freeCodeCamp/freeCodeCamp/pull/40906

**Comment by nhcarrigan** [comment]
Randy's the expert on these workflows, but I believe:
```yml
skip_untranslated_files: true
```
This line could be switched to false to trigger the download of untranslated files as English.

<hr>

My overall concern, unrelated to this workflow, is that when V7 rolls out we'll likely be making a lot of tweaks. If we add an English file, am I correct in understanding that same file must be present in the i18n languages to avoid a build error?

**Comment by raisedadead** [comment]
Here is the full list of options that you can take a look at: https://github.com/crowdin/github-action/blob/master/action.yml

The action is an extension of their CLI. Its best we reached out to Crowdin directly with these queries.

> If we add an English file, am I correct in understanding that same file must be present in the i18n languages to avoid a build error?

Yes. And hence we would want to create the same file across all languages (even if it's in English, at first until we can get a copy from Crowdin).

**Comment by RandellDawson** [comment]
On the test repo, I need to test out what happens if we use:
```
export_only_approved: true
skip_untranslated_strings: true
```
that hopefully It will download all files and if a string has not been approved, it will download the English for that string.

While it seems possible to do this, I do not recommend it, because then you would have some of the files being a mix of English and non-English sections.  That would be frustrating for users.

**Comment by raisedadead** [comment]
> That would be frustrating for users.

I agree with that sentiment. We would much rather have the whole block or super-block not pulled down and fallback to English.

**Comment by nhcarrigan** [comment]
Would it be better, then, to start off with *all* of the English files copied in to the Espanol folder? Then we'd be replacing them with translations as they were 100% completed.

**Comment by raisedadead** [comment]
Yes - that is the idea. 

But while that "makes our lives easy" immediately we do need to test our workflows, and tests, and pipelines and the general strategy with the first few weeks. Gain the experience and understanding and then phase out the auditing once the process is mature.

**Comment by nhcarrigan** [comment]
@RandellDawson we should test what happens if we pass `skip_untranslated_files: false` and leave the others true - I am hoping that would result in a 100% approved file being downloaded, and a partially translated file being skipped. Then, that partially translated file is considered "untranslated" and the English source is provided instead.

@raisedadead I will go ahead and PR to copy the `english` directory to `espanol`, then. That way we are able to build the `espanol` locally (I'll rebase the PR) and confirm everything renders in the translations as expected.

**Comment by RandellDawson** [comment]
@nhcarrigan I will test both your suggestion and mine to see the differences.

**Comment by ojeytonwilliams** [comment]
> Would it be better, then, to start off with all of the English files copied in to the Espanol folder

Yes and no.  If we can get *all* the files from Crowdin, defaulting to translated when we want to, that's fine.  However, if we can't then we'll need to re-work how we build the translated curricula.

So, in a slight rush I asked Nick to wait.  However if we just want to test things out, it's fine to copy the English over to the Spanish for now.

How we handle things depends on precisely what we'll be getting back from Crowdin, but for testing it's fine.

**Comment by nhcarrigan** [comment]
Catching up on the conversation in chat...

I pulled down the `i18n-sync-learn` branch, changed the `is-audited` and `allLangs` values to allow the espanol curriculum, and ran a development build. It looks like we've configured Crowdin correctly to send down source files for incomplete translations - I had no build errors this time and was able to explore the curriculum.

I think this is safe to close now. 🙂
