### ISSUE TITLE
Certificate translation

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41000]
Currently we have a single url that a user can visit to prove that they have earned a certificate. 

```
https://www.freecodecamp.org/certification/<username>/<certificate-name>`
```

With the ongoing i18n effort, we want to let users see their certifications in their own languages. However, we need to decide where all these translations of the certs are going to live. Do we

- want to maintain one per language? e.g. `https://chinese.freecodecamp.org/certification/<username>/<certificate-name>`,  `https://www.freecodecamp.org/espanol/certification/<username>/<certificate-name>` and so on.
- give people a button to on the cert to change rendering?
- control it with a query param?

Some initial discussion here: https://github.com/freeCodeCamp/freeCodeCamp/pull/40938

**Comment by raisedadead** [comment]
How about this:

Say, we have a dedicated service that is rendering (server-side) the certs at:

```
https://certs.freecodecamp.org/<username>/<certificate-name>
```

This way we can address some of the pain points and issues we have had over the years:

1. Server-side rendering enhances the authenticity.
2. It's a unique non-changing URL. 
3. We render the cert in English at all times. 
4. Users are able to add a query param to get a version that the like.

   ```
   https://certs.freecodecamp.org/<username>/<certificate-name>?language=<lang>
   ```

This does mean we need to map our current links, but that is not half as bad because we can throw it at the dedicated service to manage all the different types of URLs we are introducing right now.

**Comment by moT01** [comment]
Solved 👍
