### ISSUE TITLE
A bug while signing in and  then signing out

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41060]
When we sign in successfully a URL is generated if we copy that URL and then logout 
and then we just directly paste the URL we are heading to the page which says that we have been signed up successfully
![Screenshot (141)](https://user-images.githubusercontent.com/71023799/107694308-38b2ae00-6cd5-11eb-99e8-118cd8924f83.png)

**Comment by raisedadead** [comment]
Not sure what URL you are talking about, please report issues filling the detailed template that you are presented with when opening an issue.

**Comment by RandellDawson** [comment]
@raisedadead The user means if you sign in successfully you get the message "Success! You have signed in to your account. Happy Coding!" at the top of the page.  The url is `https://www.freecodecamp.org/learn/?messages=success%5B0%5D%3Dflash.signin-success`.  

If you signout and paste the above url back in (not sure why someone would do this), you are still logged out, but the message  "Success! You have signed in to your account. Happy Coding!" appears at the top again. It is because we are showing the message based on the querystring instead of the actual status of being logged in?

**Comment by raisedadead** [comment]
Thanks for clarifying. 

The query param should ideally be stripped off once the message is displayed to avoid this confusion. Nonetheless I do not see why a user would actually copy paste the URL.

In any case the behavior is by design to render the message on the client.

Going to close.

@Aanandgupta let us know if you have further queries.

**Comment by Aanandgupta** [comment]
Thank you 
Totally agreed almost nobody would be doing so but still 
"The query param should ideally be stripped off once the message is displayed to avoid this confusion. "
this is what I was also thinking would be better 
@raisedadead 
@RandellDawson
