### ISSUE TITLE
Background Gif not displayed for mobile devices

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41063]
![Screenshot (143)](https://user-images.githubusercontent.com/71023799/107697019-ae6c4900-6cd8-11eb-8a7b-147bb585bf02.png)
In the radio page https://coderadio.freecodecamp.org/
The Background gif is not displayed for mobile devices we could have scaled that gif for mobile devices but don't know for what reason its been hidden

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. There is actually a separate repo for the Code Radio: https://github.com/freeCodeCamp/coderadio-client

Also, this was a specific design choice, in order to reduce the data consumption on mobile devices.

As this is not an issue, I am closing this 😃

**Comment by Aanandgupta** [comment]
> Hello there,
> 
> Thank you, for taking the time to open this. There is actually a separate repo for the Code Radio: https://github.com/freeCodeCamp/coderadio-client
> 
> Also, this was a specific design choice, to reduce the data consumption on mobile devices.
> 
> As this is not an issue, I am closing this 😃

I taught that was done mistakenly so raised the issue thinking it would be helpful.
Thank You for clarifying
