### ISSUE TITLE
feat(coderadio): Add Additional visualizers

### ISSUE THREAD

**Issue by AskMP** [freeCodeCamp/freeCodeCamp#41078]
This one is a little more long term however I would like to open up the option that I originally had where people could submit their own visualizer code and it could be added. We could have them credited and available by a dropdown list.

**Comment by ahmadabdolsaheb** [comment]
I am not sure how much interest there would be in creating visualizer, but in order to achieve that we should:
- have e2e tests in place to make sure added visualizers are not altering the app's main functionality(play, pause, change streams, change volr)
- have performance tests in place to make sure new visualizers don't exceed a certain limit. 
- have the current visualizer and its css in one component to serve as an example.
- have the visualizer dropdown functionality in place to switch between visualizers.
 
Any other aspects we need to consider?

**Comment by ahmadabdolsaheb** [comment]
Having additional visualizers is a great idea; however I will close this feature request for now due to lack of interest.

We could revisit this feature once there is sufficient demand for it.
