### ISSUE TITLE
Successive bonfires don't get marked as completed if I skip previous ones.

### ISSUE THREAD

**Issue by prashanthcr** [FreeCodeCamp/freecodecamp#411]
![screen shot 2015-05-02 at 11 31 48 pm](https://cloud.githubusercontent.com/assets/7514066/7441641/86696366-f123-11e4-9d74-47dbe8a52ce4.png)

I skipped 16 but completed 17, 18, 19 and 20, but only 17 gets marked. I've skipped ahead couple of times before, today is the first day I've had this issue.

**Comment by terakilobyte** [comment]
I was unable to reproduce this behavior. Please include additional steps to repeat. https://www.dropbox.com/s/i4rbejxza1vczw2/Screenshot%202015-05-07%2007.48.59.png

**Comment by prashanthcr** [comment]
It's a difficult-to-reproduce bug I guess. It worked for me early on, then the bug occurred and for now at least it's working as expected.

**Comment by alnero** [comment]
As soon as you finish a challenge you click "I've completed this challenge (ctrl + enter)", but on your roadmap of all challenges it is not marked up as completed, only when you click "On to my next challenge (ctrl + enter)" in the pop up it will be marked. It's OK if you follow them in order, but a bit confused when you do them randomly.

**Comment by terakilobyte** [comment]
This is the default functionality. We will consider modifying it in the
future.

**Comment by terakilobyte** [comment]
Ah I think I see. You are "completing" the challenge but instead of clicking the button to take you to your next challenge you are manually clicking around?

**Comment by alnero** [comment]
Yeap, exactly. I close the pop up and move around.

**Comment by terakilobyte** [comment]
Ok, yep. This is actually the way it's coded currently. The challenge really isn't complete until you select the transition option to your next challenge. We did this to discourage just such behavior, but we'll have a conversation about marking actual completion.

The largest problems I see immediately. One, if someone wants to complete a bonfire, then isn't happy with the code and changes it and runs it again, then forgets they left a console.log statement so they remove it, then decides that their instance of the Cowboy object should be called Doc Holiday instead of Bat Masterson, etc...

Now each one of those is a completion event when they most certainly only wanted one. Additionally, since we encourage pair programming and pop have a field to grant completion to a pair in the completion modal as well, we'd then have to separate the partner completion into its own controller action. 

Lastly, this would start breaking with the consistent style we use in zipline and basejump completions as there you *must* provide additional data aside from attesting you have, in fact, completed the challenge.
