### ISSUE TITLE
Bonfire:  "Return Largest Numbers in Arrays"; Should be able to accept different orders of the correct answer. 

### ISSUE THREAD

**Issue by nikhilnd** [FreeCodeCamp/FreeCodeCamp#4110]
I have done the Bonfire: Return Largest Numbers in Arrays and I have the correct answer except it won't accept it because it is not in the wanted order. 

My code: 
```
function largestOfFour(arr) {

  var largest = null;
  var largestArr = [];

  for(var i = 0; i < arr.length; i++) {
    // console.log(arr[i]); - used for testing
    for(var x  = 0; x < arr[i].length; x++) {
      if(largest === null || arr[i][x] > largest) {
        largest = arr[i][x];
      }
      // console.log(arr[i][x]); - used for testing 
    }
    largestArr.push(largest);
  }

  return largestArr;

}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

Returns: 
```
[5, 27, 39, 1001]
```

Won't accept this and instead wants it in a different order. Wanted result:
```
[27,5,39,1001]
```

Please fix this or tell me what I'm doing wrong.

**Comment by akashsondhi** [comment]
Hi,

I've viewed your code. There is no issue with the code. Rather, the function that you've created is acting funny.

The reason is that the variable "largest" is assigned initially to null and in each iteration it is saving largest from the last array.

To overcome the solution, simply set largest to null in first for loop.

I've tried it and it works. :)

**Comment by nikhilnd** [comment]
Ok just tried it and it works. Thanks Akash :)

**Comment by bugron** [comment]
@nikhilnd then I'll close this issue. Feel free to reopen if you still experience problems, thanks.
