### ISSUE TITLE
Applied Visual Design, Challenge 16 broken (Set the font-size for Paragraph Text)

### ISSUE THREAD

**Issue by jasper-schnabel** [freeCodeCamp/freeCodeCamp#41116]
The solution is not accepted and therefore the challenge cannot be solved.

![issue](https://user-images.githubusercontent.com/67754783/107886331-6aa75880-6eff-11eb-9c60-d9acf54690b2.png)

[Link](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/set-the-font-size-of-paragraph-text)

* Browser Name: Firefox
* Browser Version: 85.0.2
* Operating System: Archlinux

**Comment by ShaunSHamilton** [comment]
Hello there,

The challenge, and code passes for me. I have tested this in both Firefox, and Chrome. So, I assume the issue is potentially with something like a browser extension affecting the tests on the page. In this case, I suggest you disable browser extensions with access to `freecodecamp.org`.

In general, I recommend you open a topic on the [forum](https://forum.freecodecamp.org/), and only once it is determined to be a bug there, open an issue on this repo. You can use the `Get Help > Ask for Help` button to create an auto-populated post with your current code.

Hope this helps
