### ISSUE TITLE
Wrong color on Basic CSS course

### ISSUE THREAD

**Issue by 2ndemosthenes** [freeCodeCamp/freeCodeCamp#41128]
**Describe your problem and how to reproduce it:**
In the basic CSS course, the test shows an error about the color being wrong even though in the preview everything is right.

I have tried it on multiple browsers but the problem persists.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-a-css-class-to-style-an-element

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/style-multiple-elements-with-a-css-class

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 85.0
* Operating System: Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot](https://user-images.githubusercontent.com/46780868/107946385-36d33e00-6fa6-11eb-984d-e443b4265882.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for  taking the time to open this. In general, I recommend opening a topic on the [forum](https://forum.freecodecamp.org/), in order to debug.

In your current screenshot, I can see you have a dark extension enabled. This is directly changing the CSS of the page which will affect the tets. Please disable all browser extensions with access to `freecodecamp.org`.

Once you do that, try submit the lesson again, and close this issue, if it is resolved.

**Comment by 2ndemosthenes** [comment]
Thank you very much!
I tried the forum but I couldn't find the answer there.
I disabled the extension and it works fine now.
