### ISSUE TITLE
Oppo CPH2139

### ISSUE THREAD

**Issue by Hery127** [freeCodeCamp/freeCodeCamp#41145]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ColorOS 7.2]
 - Browser: [e.g. chrome, safari]
 - Version: [10]

**Smartphone (please complete the following information):**
 - Device: [ColorOS 7.2]
 - OS: [ColorOS 7.2]
 - Browser: [e.g. stock browser, safari]
 - Version: [10]

**Additional context**

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
