### ISSUE TITLE
Hint system for challenge description box

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4119]
A challenge description should have a button you can click that will reveal - and then cycle through - a series of hints leading on up to a solution.

Edited by @bugron.
This would be similar functionally to the hint command used in our chat rooms:

![](https://www.evernote.com/l/AlwOnsotU1xEk6irl8q9zwv9tltaa0PXEz0B/image.png)

Except that it would be a button clicked within Free Code Camp.

![](https://www.evernote.com/l/AlwnZv2UWQBNAJeEfsIleJOCGJUXzM9nMSkB/image.png)

Each time you click the hint button, it would pop up the subsequent hint in a modal, until the last time, which would actually show the solution.

We will add an array attribute to each challenge object called "hints" with text to cycle through.

**Comment by KelCard** [comment]
There are some downfalls to this. 

1. It makes it very easy to just go to the hints instead of forcing the camper to Read-Search-Ask. I am learning a lot by taking my search to different places.
2. The hints can be found in chat which leads to the wiki. I'm just getting started in chat, but that's because I needed help on Bonfires and the help button led to chat.

Just some of my thoughts.

**Comment by JesseJTF** [comment]
These "downfalls" are already present though. if I wanted an answer to a bonfire, i can either A. R/S/A, B. just google the answer, or C. go to the chat and copy and paste the answer.  You can never force someone do something. most of the answers can be found with a quick search on google.

work smart not hard

**Comment by KelCard** [comment]
It gets the camper out of the coding interface. That's the point of R/S/A in the first place.

**Comment by AkiraLaine** [comment]
@KelCard I see what you mean but I think that having a button on the page is better (especially if FCC is slowly becoming a single page application).
