### ISSUE TITLE
react-i18next old method warning

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41211]
When developing the client, this warning appears:

```console
react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.
```

Seeing as this has been recently adopted, I would not expect to see warnings about old methods.

**Comment by bobbysingh2005** [comment]
i got same error

**Comment by paulyoyo** [comment]
I have the same

**Comment by RaulitoEC** [comment]
I'm not associated with this project, but I stumbled upon this post while trying to fix this problem for myself. I was able to get rid of this warning by adding { useSuspense : true } to the react object in the i18n configuration. Here is the link to the docs for more info, I hope it helps. https://react.i18next.com/latest/i18next-instance

**Comment by BertCatsburg** [comment]
I am using i18next together with nextjs. Since nextjs is SSR, useSuspence is not possible yet. So, with some effort I found the setting to switch off useSuspence, and now I get the message that I can better use useSuspence. :-)

Can that check be modified so that it does not message when in SSR mode?

**Comment by raisedadead** [comment]
Here are the docs for react i18next: https://react.i18next.com, if you need help please consider seeking assistance on their community channels.

Thanks.
