### ISSUE TITLE
JavaScript QA projects print "undefined" when FCC test is run

### ISSUE THREAD

**Issue by studio1202** [freeCodeCamp/freeCodeCamp#41238]
The [JavaScript QA projects ](https://www.freecodecamp.org/learn/quality-assurance/#quality-assurance-projects) print "undefined" to the console when FCC fetches the results of local tests from routes defined in file [fcctesting.js](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/routes/fcctesting.js)

There is no practical consequence, but it would be more appropriate to either not print anything, or to print what is happening. I created a [sample patch](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/compare/gomix...studio1202:gomix-bugfix) to address the first solution.

(The patch also addresses other small issues for which I will open other bug reports.)

**Comment by gikf** [comment]
Please correct me if I'm wrong, but this also seems to be code no longer used and could be removed. Because how `error` in `fcctesting.js` is supposed to change? Only place explicitly using `error` variable is [server.js#L49 ](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/server.js#L49), but it's defined first in it own scope,

**Comment by ShaunSHamilton** [comment]
@gikf  `error` is defined in the global scope, and `app.get` takes a callback which will be run in a new thread, once that is invoked.

It is supposed to be set here: https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/server.js#L50

I suspect the `let` is messing things up, because it is not in other projects: Example 
- https://github.com/freeCodeCamp/boilerplate-mochachai/blob/main/server.js#L92

**Comment by gikf** [comment]
That makes more sense, thanks. It *should* be available globally to work. Declaring `error` again in `server.js` is one thing, another is exporting `error` only inside of the function from the `fcctesting.js`. That will need more changes than what's in the sample patch from @studio1202.

**Comment by ShaunSHamilton** [comment]
Once the above are merged, this should be closed.
