### ISSUE TITLE
Anonymous Message Board,    This Test Passes without actually passing it.   Passes even with #NODE_ENV=test.

### ISSUE THREAD

**Issue by saugatdhimal** [freeCodeCamp/freeCodeCamp#41321]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. However, this is expected behaviour: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md

The tests have not all be written, yet. And are awaiting contribution to write them. I will point you to this thread, where this is discussed:
https://forum.freecodecamp.org/t/anonymous-message-board-test-errors-and-unclear-directions-on-proper-response-object/448737/6
