### ISSUE TITLE
Anonymous Message Board Project Tests

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41323]
Currently, the [AMB Project](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md) has no tests for most of the user-stories.

Discussion can be had within this issue about adding/changing/removing current user-stories. A PR does not need to cover every user-story, but try not to open a PR, if one is already aimed at resolving a specific user-story.

This issue is open for contributions aimed at adding to the user-stories outlined:

- [x] Only allow your site to be loaded in an iFrame on your own pages.
- [x] Do not allow DNS prefetching.
- [x] Only allow your site to send the referrer for your own pages.
- [x] You can send a POST request to /api/threads/{board} with form data including text and delete_password. The saved database record will have at least the fields _id, text, created_on(date & time), bumped_on(date & time, starts same as created_on), reported (boolean), delete_password, & replies (array). [resolved in #41848]
- [ ] You can send a POST request to /api/replies/{board} with form data including text, delete_password, & thread_id. This will update the bumped_on date to the comment's date. In the thread's replies array, an object will be saved with at least the properties _id, text, created_on, delete_password, & reported.
- [ ] You can send a GET request to /api/threads/{board}. Returned will be an array of the most recent 10 bumped threads on the board with only the most recent 3 replies for each. The reported and delete_password fields will not be sent to the client.
- [ ] You can send a GET request to /api/replies/{board}?thread_id={thread_id}. Returned will be the entire thread with all its replies, also excluding the same fields from the client as the previous test.
- [ ] You can send a DELETE request to /api/threads/{board} and pass along the thread_id & delete_password to delete the thread. Returned will be the string incorrect password or success.
- [ ] You can send a DELETE request to /api/replies/{board} and pass along the thread_id, reply_id, & delete_password. Returned will be the string incorrect password or success. On success, the text of the reply_id will be changed to [deleted].
- [ ] You can send a PUT request to /api/threads/{board} and pass along the thread_id. Returned will be the string success. The reported value of the thread_id will be changed to true.
- [ ] You can send a PUT request to /api/replies/{board} and pass along the thread_id & reply_id. Returned will be the string success. The reported value of the reply_id will be changed to true.
- [ ] All 10 functional tests are complete and passing.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sembauke** [comment]
How would I get started writing test for this project?

**Comment by ShaunSHamilton** [comment]
@Sembauke , If you have not already, best to read the contributors docs linked above. in terms of writing the tests:
- Have a look at the tests written for other backend projects
- Run fCC locally, and play around with the tests
- Play around with your solution to the project

At the end of the day, some tests may need to be removed/changed, as we have tried to keep a near parity between the unit/functional tests and the user stories.

**Comment by Sembauke** [comment]
Thank you.. but where would I find the current test for the backend project. Can't find them anywhere,

**Comment by ShaunSHamilton** [comment]
@Sembauke The tests are stored in the `--hints--` section of the Markdown (`.md`) files. The `.md` file for this project is linked in the original post.

**Comment by jonathankerr** [comment]
Hey @ShaunSHamilton i've been working on some of the tests for this and i was wondering if i could get some clarification on the 6th test: 

 "You can send a GET request to /api/threads/{board}. Returned will be an array of the most recent 10 bumped threads on the board with only the most recent 3 replies for each. The reported and delete_password fields will not be sent to the client."

When you mention the fields `delete_password` and `reported` will not be sent to the client does that mean they shouldn't be returned when `/api/threads/{board}` is requested? Because currently the example site https://anonymous-message-board.freecodecamp.rocks/ returns both of these fields on that request. Thanks 👍

**Comment by jonathankerr** [comment]
Hey I've been working on more of the tests for this and noticed that the example project we give: 
https://anonymous-message-board.freecodecamp.rocks/ would actually fail the two GET request tests. Currently sending a GET request to `/api/threads/{board}` and `/api/replies/{board}?thread_id={thread_id}` results in both the `reported` and `delete_password` fields being shown which goes against the requirements for passing the tests.

I'm not sure if this was intentional to help with debugging when creating the project but if not i can open an issue.

**Comment by ShaunSHamilton** [comment]
@jonathankerr You are quite right. I am only just noticing this now. As this is the Information and Security section, it would make sense to not send through the sensitive information. As such, I suggest we change this user story's test:
> You can send a `POST` request to `/api/threads/{board}` with form data including text and delete_password. The saved database record will have at least the fields _id, text, created_on(date & time), bumped_on(date & time, starts same as created_on), reported (boolean), delete_password, & replies (array).

To not look for the `reported` nor `delete_password` fields. At least, until we decide on a better method to test these kinds of things.

**Comment by jonathankerr** [comment]
Hey @ShaunSHamilton thanks for getting back to me and sorting that out. I'll have the remaining tests for this project sorted shortly.

**Comment by HOuadhour** [comment]
Hello @ShaunSHamilton

I've tried to create the 5th test for this project.
But I've got a (Test timed out)

I don't know because if it is because of the implementation of my code.
Or also The post request doesn't return a JSON it will do a redirect, and that redirect will do another get request.

I think this is a problem in general.

Here is my code.

I did a GET request at the beginning to get a thread_id, so I can send it alongside the POST request

```js
async (getUserInput) => {
  const url = getUserInput('url');
  const body = await fetch(url + '/api/threads/fcc_test');
  const thread = await body.json();

  const date = new Date();
  const text = `fcc_test_reply_${date}`;
  const delete_password = 'delete_me';
  const thread_id = thread[0]._id;
  const replyCount = thread[0].replycount;

  const data = { text, delete_password, thread_id };
  const res = await fetch(url + '/api/replies/fcc_test', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data)
  });
  if (res.ok) {
    const checkData = await fetch(`${url}/api/replies/fcc_test?thread_id=${thread_id}`);
    const parsed = await checkData.json();
    try {
      assert.equal(parsed.replycount, replyCount + 1);
      assert.equal(parsed.replies[0].text, text);
      assert.equal(parsed._id, thread_id);
      assert.equal(parsed.bumped_on, parsed.replies[0].created_on);
    } catch (err) {
      throw new Error(err.responseText || err.message);
    }
  } else {
    throw new Error(`${res.status} ${res.statusText}`);
  }
};
```
