### ISSUE TITLE
Low priority: ignore comments when checking the code in the challenges

### ISSUE THREAD

**Issue by gmfuster** [freeCodeCamp/freeCodeCamp#41448]
This is low priority and I'm not sure if it has been brought up, sorry if I'm doing this wrong.  On one of the challenges I had commented out the splice call but I still got an error that I should not use it.  I assume when the checks are being performed they are not skipping commented out lines.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/remove-elements-from-an-array-using-slice-instead-of-splice

**Tell us about your browser and operating system:**
* Browser Name: Edge
* Browser Version: Version 89.0.774.45
* Operating System: Windows

**Comment by RandellDawson** [comment]
@gmfuster You are correct that we do not by default ignore comments in the code when performing most checks like the one you had trouble with on the challenge.  We do have a helper function that we can use to sanitize the code for a specific test, which is what is needed for this particular challenge.  I am going to compile a list of all the challenges that should be using this helper function and explain how to use it.  I will post the list and instructions of how to fix the challenges later today.

Thank you for reporting this issue.  We have been handling these on a one-off basis, but a full list of such challenges would help us fix them all in one sweep.

**Comment by RandellDawson** [comment]
The following list contains only the `testStrings` contained in 86 challenges that would to be changed for the JavaScript Algorithms and Data Structures certification.  There are probably some I missed and there would be many more if we were to do the same for the other certifications. 

@ojeytonwilliams We discussed a while back (like 5 months ago) the idea of applying the various comment remover helper functions across all challenges, except where we add a front matter key/value of something like `removeComments: true`.  This way all the editor code would be stripped of comments before any tests are ran and we would not have to add all of these helper functions. There are only a few challenges were we want to not remove the comments, such as the challenges where we ask the user to add code comments.  

Until I went through the exercise of finding all of these, I had forgotten how many there actually were.  Based on these findings, I think we should implement what we discussed before instead of having someone go through and add all these comment remover helper functions in the code base.

  <details>
<summary>See testStrings needing the removeJSComments helper function</summary>
- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/confirm-the-ending.md

```js
assert(!/\.endsWith\(.*?\)\s*?;?/.test(code) && !/\['endsWith'\]/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/repeat-a-string-repeat-a-string.md

```js
assert(!/\.repeat/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice.md
```js
assert(mixedNumbers.toString().match(/\.push/));
```

```js
assert(!/shift|unshift/.test(code));
```

```js
assert(!/\[\d\]\s*=/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/adding-a-default-option-in-switch-statements.md
```js
assert(!/else/g.test(code) || !/if/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords.md

```js
(getUserInput) => assert(!getUserInput('index').match(/var/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword.md
```js
(getUserInput) => assert(!getUserInput('index').match(/var/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords.md
```js
(getUserInput) => assert(!getUserInput('index').match(/var/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.md
```js
(getUserInput) => assert(!getUserInput('index').match(/function/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements.md

```js
(getUserInput) => assert(!getUserInput('index').match(/slice/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/write-arrow-functions-with-parameters.md
```js
(getUserInput) => assert(!getUserInput('index').match(/function/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/add-elements-to-the-end-of-an-array-using-concat-instead-of-push.md
```js
assert(code.match(/\.concat/g));
```

```js
assert(!code.match(/\.?[\s\S]*?push/g));
```

-  curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/combine-an-array-into-a-string-using-the-join-method.md
```js
assert(code.match(/\.join/g));
```

```js
assert(!code.match(/\.?[\s\S]*?replace/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype.md
```js
assert(!code.match(/\.?[\s\S]*?map/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype.md
```js
assert(!code.match(/\.?[\s\S]*?filter/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/remove-elements-from-an-array-using-slice-instead-of-splice.md
```js
assert(code.match(/\.slice/g));
```

```js
assert(!code.match(/\.?[\s\S]*?splice/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.md
```js
assert(code.match(/\.filter/g));
```

```js
assert(!code.match(/for\s*?\([\s\S]*?\)/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/introducing-else-statements.md

```js
assert(code.match(/if/g).length === 1);
```

```js
assert(/else/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/replacing-if-else-chains-with-switch.md
```js
assert(!/else/g.test(code));
```

```js
assert(!/if/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/returning-boolean-values-from-functions.md

```js
assert(!/if|else/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups.md

```js
assert(
  !/case|switch|if/g.test(code.replace(/([/]{2}.*)|([/][*][^/*]*[*][/])/g, ''))
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs.md
```js
assert(!code.match(/\.?[\s\S]*?replace/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.md

```js
assert(!code.match(/\.\s*flat\s*\(/) && !code.match(/\.\s*flatMap\s*\(/));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for...in-statement.md

```js
assert(
  code.match(
    /for\s*\(\s*(var|let|const)\s+[a-zA-Z_$]\w*\s+in\s+[a-zA-Z_$]\w*\s*\)/
  )
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-with-javascript.md
```js
assert(code.match(/Math.random/g).length >= 1);
```

```js
assert(
  code.match(/\s*?Math.random\s*?\(\s*?\)\s*?\*\s*?10[\D]\s*?/g) ||
    code.match(/\s*?10\s*?\*\s*?Math.random\s*?\(\s*?\)\s*?/g)
);
```

```js
assert(code.match(/Math.floor/g).length >= 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range.md

```js
assert(
  (function () {
    if (
      code.match(/myMax/g).length > 1 &&
      code.match(/myMin/g).length > 2 &&
      code.match(/Math.floor/g) &&
      code.match(/Math.random/g)
    ) {
      return true;
    } else {
      return false;
    }
  })()
);
```

```js
assert(code.match(/Math.random/g).length >= 1);
```

```js
assert(
  code.match(/\s*?Math.random\s*?\(\s*?\)\s*?\*\s*?10[\D]\s*?/g) ||
    code.match(/\s*?10\s*?\*\s*?Math.random\s*?\(\s*?\)\s*?/g)
);
```

```js
assert(code.match(/Math.floor/g).length >= 1);
```




- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop.md

```js
assert(code.match(/(var|let|const)\s*?total\s*=\s*0.*?;?/));
```

```js
assert(/for\s*\(/g.test(code) && /myArr\s*\[/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/manipulate-arrays-with-pop.md

```js
assert(/removedFromMyArray\s*=\s*myArray\s*.\s*pop\s*(\s*)/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/multiply-two-decimals-with-javascript.md

```js
assert(/\*/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/multiply-two-numbers-with-javascript.md

```js
assert(/\*/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/practice-comparing-different-values.md
```js
assert(code.match(/===/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/add-two-numbers-with-javascript.md

```js
assert(/\+/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator.md

```js
assert(code.match(/==/g) && !code.match(/===/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-greater-than-operator.md
```js
assert(code.match(/val\s*>\s*('|")*\d+('|")*/g).length > 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-greater-than-or-equal-to-operator.md

```js
assert(code.match(/val\s*>=\s*('|")*\d+('|")*/g).length > 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-inequality-operator.md
```js
assert(code.match(/(?!!==)!=/));
```


- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-less-than-operator.md
```js
assert(code.match(/val\s*<\s*('|")*\d+('|")*/g).length > 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-less-than-or-equal-to-operator.md
```js
assert(code.match(/val\s*<=\s*('|")*\d+('|")*/g).length > 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-strict-equality-operator.md
```js
assert(code.match(/(val\s*===\s*\d+)|(\d+\s*===\s*val)/g).length > 0);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-strict-inequality-operator.md
```js
assert(code.match(/(val\s*!==\s*\d+)|(\d+\s*!==\s*val)/g).length > 0);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-and-operator.md
```js
assert(code.match(/&&/g).length === 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator.md
```js
assert(code.match(/\|\|/g).length === 1);
```

```js
assert(code.match(/if/g).length === 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-addition.md
```js
assert(code.match(/\+=/g).length === 3);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-division.md
```js
assert(code.match(/\/=/g).length === 3);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-multiplication.md
```js
assert(code.match(/\*=/g).length === 3);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-subtraction.md
```js
assert(code.match(/-=/g).length === 3);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator.md
```js
assert(code.match(/(["']).*\1\s*\+\s*(["']).*\2/g));
```

```js
assert(/var\s+myStr/.test(code));
```

```js
assert(/myStr\s*=/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-the-plus-equals-operator.md
```js
assert(code.match(/myStr\s*\+=\s*(["']).*\1/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/constructing-strings-with-variables.md
```js
assert(code.match(/["']\s*\+\s*myName\s*\+\s*["']/g).length > 0);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/decrement-a-number-with-javascript.md
```js
assert(/[-]{2}\s*myVar|myVar\s*[-]{2}/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript.md
```js
assert(/4\.40*\s*\/\s*2\.*0*/.test(code));
```

```js
assert(code.match(/quotient/g).length === 1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/divide-one-number-by-another-with-javascript.md
```js
assert(/\d+\s*\/\s*\d+/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings.md
```js
assert(code.match(/\\"/g).length === 4 && code.match(/[^\\]"/g).length === 2);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript.md
```js
assert(/\s+?remainder\s*?=\s*?.*%.*;?/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.md


```js
assert(/[+]{2}\s*myVar|myVar\s*[+]{2}/.test(code));
```

```js
assert(/var myVar = 87;/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string.md
```js
assert(code.match(/\.length/g).length > 0);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-multiple-conditional-ternary-operators.md
```js
assert(/.+?\s*?\?\s*?.+?\s*?:\s*?.+?\s*?\?\s*?.+?\s*?:\s*?.+?/gi.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator.md
```js
assert(/.+?\s*?\?\s*?.+?\s*?:\s*?.+?/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-the-parseint-function-with-a-radix.md
```js
assert(/parseInt/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-use-of-assignment-operator-instead-of-equality-operator.md
```js
assert(code.match(/x\s*?===?\s*?y/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/use-the-javascript-console-to-check-the-value-of-a-variable.md
```js
assert(code.match(/console\.log\(a\)/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/use-typeof-to-check-the-type-of-a-variable.md
```js
assert(code.match(/console\.log\(typeof[\( ].*\)?\)/g).length == 2);
```

```js
assert(code.match(/typeof[\( ]seven\)?/g));
```

```js
assert(code.match(/typeof[\( ]three\)?/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/create-an-export-fallback-with-export-default.md
```js
assert(
  code.match(
    /export\s+default\s+function(\s+subtract\s*|\s*)\(\s*x,\s*y\s*\)\s*{/g
  )
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays.md
```js
assert(/\[\s*(\w)\s*,\s*(\w)\s*\]\s*=\s*\[\s*\2\s*,\s*\1\s*\]/g.test(code));
```


- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.md
```js
assert(
  !code.match(/lowToday = LOCAL_FORECAST\.today\.low/g) &&
    !code.match(/highToday = LOCAL_FORECAST\.today.high/g)
);
```

```js
assert(
  code.match(
    /(var|const|let)\s*{\s*today\s*:\s*{\s*(low\s*:\s*lowToday[^}]*|[^,]*,\s*low\s*:\s*lowToday\s*)}\s*}\s*=\s*LOCAL_FORECAST(;|\s+|\/\/)/g
  )
);
```

```js
assert(
  code.match(
    /(var|const|let)\s*{\s*today\s*:\s*{\s*(high\s*:\s*highToday[^}]*|[^,]*,\s*high\s*:\s*highToday\s*)}\s*}\s*=\s*LOCAL_FORECAST(;|\s+|\/\/)/g
  )
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects.md
```js
assert(
  !code.match(/highToday = HIGH_TEMPERATURES\.today/g) &&
    !code.match(/highTomorrow = HIGH_TEMPERATURES\.tomorrow/g)
);
```

```js
assert(
  code.match(
    /(var|const|let)\s*{\s*(today\s*:\s*highToday[^}]*|[^,]*,\s*today\s*:\s*highToday\s*)}\s*=\s*HIGH_TEMPERATURES(;|\s+|\/\/)/g
  )
);
```

```js
assert(
  code.match(
    /(var|const|let)\s*{\s*(tomorrow\s*:\s*highTomorrow[^}]*|[^,]*,\s*tomorrow\s*:\s*highTomorrow\s*)}\s*=\s*HIGH_TEMPERATURES(;|\s+|\/\/)/g
  )
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-extract-values-from-objects.md
```js
assert(
  !__helpers
    .removeJSComments(code)
    .match(/today\s*=\s*HIGH_TEMPERATURES\.(today|tomorrow)/g)
);
```

```js
assert(
  __helpers
    .removeJSComments(code)
    .match(
      /(var|let|const)\s*{\s*(today[^}]*|[^,]*,\s*today)\s*}\s*=\s*HIGH_TEMPERATURES(;|\s+|\/\/)/g
    )
);
```

```js
assert(
  __helpers
    .removeJSComments(code)
    .match(
      /(var|let|const)\s*{\s*(tomorrow[^}]*|[^,]*,\s*tomorrow)\s*}\s*=\s*HIGH_TEMPERATURES(;|\s+|\/\/)/g
    )
);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/combine-two-arrays-using-the-concat-method.md
```js
assert(code.match(/\.concat/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array.md
```js
assert(nonMutatingSort.toString().match(/\.sort/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/return-part-of-an-array-using-the-slice-method.md
```js
assert(code.match(/\.slice/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.md
```js
assert(code.match(/\.sort/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/split-a-string-into-an-array-using-the-split-method.md
```js
assert(code.match(/\.split/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-every-method-to-check-that-every-element-in-an-array-meets-a-criteria.md
```js
assert(code.match(/\.every/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md
```js
assert(code.match(/\.map/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data.md
```js
assert(code.match(/\.reduce/g));
```

```js
assert(!code.match(/for\s*?\([\s\S]*?\)/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-some-method-to-check-that-any-elements-in-an-array-meet-a-criteria.md
```js
assert(code.match(/\.some/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/make-code-more-reusable-with-the-this-keyword.md
```js
assert(code.match(/this\.numLegs/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-constructor-property.md
```js
assert(/\.constructor/.test(code) && !/instanceof/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/use-a-constructor-to-create-objects.md
```js
assert(code.match(/new/g));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/use-dot-notation-to-access-the-properties-of-an-object.md
```js
assert(/console.log\(.*dog\.name.*\)/g.test(code));
```

```js
assert(/console.log\(.*dog\.numLegs.*\)/g.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/check-for-mixed-grouping-of-characters.md
```js
assert(code.match(/myRegex.test\(\s*myString\s*\)/));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/extract-matches.md
```js
assert(code.match(/\.match\(.*\)/));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method.md
```js
assert(code.match(/myRegex.test\(\s*myString\s*\)/));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/check-for-the-presence-of-an-element-with-indexof.md
```js
assert.notStrictEqual(quickCheck.toString().search(/\.indexOf\(/), -1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/copy-array-items-using-slice.md
```js
assert(/\.slice\(/.test(code));
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-all-an-arrays-items-using-for-loops.md
```js
assert.notStrictEqual(filteredArray.toString().search(/for/), -1);
```

- curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/remove-items-from-an-array-with-pop-and-shift.md
```js
assert.notStrictEqual(popShift.toString().search(/\.pop\(/), -1);
```

```js
assert.notStrictEqual(popShift.toString().search(/\.shift\(/), -1);
```
</details>

**Comment by gmfuster** [comment]
@RandellDawson Thank you!

**Comment by rohitbhat1603** [comment]
This is low priority and I'm not sure if it has been brought up, sorry if I'm doing this wrong. On one of the challenges I had commented out the splice call but I still got an error that I should not use it. I assume when the checks are being performed they are not skipping commented out lines.

**Comment by ShaunSHamilton** [comment]
@rohitbhat1603 We do have specific functions to deal with these cases. So, could you open a new issue (unless it is the same challenge as mentioned in this), and be sure to include as much detail as possible. Thanks.

**Comment by ojeytonwilliams** [comment]
@RandellDawson sure, we could definitely default to removing comments.  I feel like this could be an interesting 'help wanted' issue, too, since there's no time pressure.
