### ISSUE TITLE
Video missing for Replace Loops using Recursion Challenge

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41489]
**Describe your problem and how to reproduce it:**
A user on the forum pointed out that this challenge did not have a video with it. 
The article that is there is titled How Recursion Works — Explained with Flowcharts and a Video.
There is also this sentence in the article You can also watch this 5-minute video I made about recursion.
But I could not find a video in the article. 

I think it would be helpful to link the video with the challenge since recursion is a tricky topic. 
Thanks! 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1144" alt="Screen Shot 2021-03-14 at 3 44 58 AM" src="https://user-images.githubusercontent.com/67210629/111065564-b524e200-8477-11eb-963c-460930f91320.png">

**Comment by NA-E** [comment]
Can someone point me towards the repository for the news platform?

**Comment by ieahleen** [comment]
@NA-E thank you for your desire to help, but the articles are on a private database, only the editorial team can deal with it

Please take a look at issues with the label "help wanted"

**Comment by scissorsneedfoodtoo** [comment]
Thanks for opening an issue for this @jdwilkin4. I just went into the article and added that video in. It must have gotten lost in the move off of Medium.

Now when someone clicks the "Watch a Video" button for that challenge, the article should include the video. But I had to do a hard refresh of the challenge page for the video to load properly, otherwise it showed the cached version of the News article without the video.

Will close this issue for now. Please just let me know if there are any other issues with this challenge or the "How Recursion Works — Explained with Flowcharts and a Video" article.
