### ISSUE TITLE
Hard to read the instructions for "Golf Code" in the JavaScript course.

### ISSUE THREAD

**Issue by y-arjun-y** [freeCodeCamp/freeCodeCamp#41530]
**Describe your problem and how to reproduce it:**
Commas are missing in the paragraph, making it hard to read and understand the meaning behind the problem.

It should be something like this:
"In the game of golf, each hole has a par, meaning, the average number of strokes a golfer is expected to make in order to sink the ball in the hole to complete the play. Depending on how far above or below par your strokes are, there is a different nickname."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/golf-code

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 89.0.4389.90
* Operating System: macOS Big Sur Version 11.2.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="712" alt="Screen Shot 2021-03-19 at 10 20 21 AM" src="https://user-images.githubusercontent.com/58625220/111739592-ba7d9480-889c-11eb-8508-eb2b3911ddb5.png">

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Along improving that part of text, it also should be considered, per #40749, if external link to Wikipedia page about golf is necessary for completing challenge. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/golf-code.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by csparklz** [comment]
**I could be completely wrong... this is literally the first thing I have ever worked through... but I went through this problem with the posted video... and it had me write it out like this but it won't post for credit** 

const names = ["Hole-in-one!", "Eagle", "Birdie", "Par", "Bogey", "Double Bogey", "Go Home!"];

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1) {
	  return names[0];
  } else if (strokes <= par - 2) {
	  return names[1];
  } else if (strokes == par - 1) {
	  return names[2];
  } else if (strokes == par) {
	  return names[3];
  } else if (strokes == par + 1) {
	  return names[4];
  } else if (strokes == par + 2) {
	  return names[5];
  } else if (strokes >= par + 3) {
	  return names[6];

  // Only change code above this line
}

console.log(golfScore(5, 4));

**when you go to submit, it does not work for credit and you get an error message.... it you go to the posted answers, this is what works...** 

const names = ["Hole-in-one!", "Eagle", "Birdie", "Par", "Bogey", "Double Bogey", "Go Home!"];

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1) {
    return names[0];
  } else if (strokes <= par - 2) {
    return names[1];
  } else if (strokes === par - 1) {
    return names[2];
  } else if (strokes === par) {
    return names[3];
  } else if (strokes === par + 1) {
    return names[4];
  } else if (strokes === par + 2) {
    return names[5];
  } else {
    return names[6];
  }
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
