### ISSUE TITLE
Video Challenge Console Errors

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41550]
Errors in the browser console, when viewing/loading a video challenge:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://www.freecodecamp.org').
```
```
GET https://www.youtube.com/imgbin/www-hitchhiker.webp 404
GET https://www.youtube.com/img/meh7.png 404
```

Example page: https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/introduction-to-data-analysis

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested Chromium based browsers
 - Version: Latest

Appears on `.org` and `.dev`

**Comment by Sembauke** [comment]
To my understanding, this issue starts when the `iframe` has not completed loading when sending a `postMessage`

**Comment by Sembauke** [comment]
So this is called cross-origin sharing and it is a warning in case a website does not permit you to display their content on a different website. Fortunately, Youtube does allow you to use their videos. The content should work just work.

I think the issue doesn't need to be solved because it's just a safety warning. There may be an option to disable the warning.

**Comment by Sembauke** [comment]
If anyone experiences any issues with videos loading I am happy to reopen this issue.

**Comment by chris123123123123123** [comment]
I am having issues loading the videos on the python course and I think it's due to this error given that it's the only one that shows up in the console

![image](https://user-images.githubusercontent.com/102695617/160918387-170d2992-9ac7-4e97-a83b-d4027992df76.png)

I am using the latest version of chrome beta on windows 10.
