### ISSUE TITLE
understanding initialized variables has wrong criteria

### ISSUE THREAD

**Issue by austinthetaco** [freeCodeCamp/freeCodeCamp#41613]
**Describe your problem and how to reproduce it:**
The solution icons below say a value of `15` for letter `b` but only passes with a value of 10. it also expects `5` for `a` but says it wants `6`. etc.
**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/7856196/112709626-58162c80-8e78-11eb-89b0-5a014f3e2d31.png)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
