### ISSUE TITLE
Compiler does not change ".then" method color

### ISSUE THREAD

**Issue by acoder123** [freeCodeCamp/freeCodeCamp#41636]
**Describe your problem and how to reproduce it:**
If you create a promise and use the method ".then" it does not highlight blue like most methods. This is a small issue however it makes it seem like your code is bugged. This can waste a lot of time for new users who do not like to test their code unless it looks correct.

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 89.0.4389.90 (Official Build) (64-bit)
* Operating System:  Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/74914589/112748616-835a6200-8fc5-11eb-9a55-1a32fd8e22eb.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. This is not an issue, whatsoever. Different themes highlight syntax in different ways, and it is impossible to match what a Camper might have locally, because there are dozens of themes.

My local setup looks completely different to the freeCodeCamp editor.
![image](https://user-images.githubusercontent.com/51722130/112749333-9e26d980-8fb9-11eb-8165-aabec6053a4c.png)

I cannot see this as being an issue for new users, and, if it is, then they are encouraged to READ-SEARCH-ASK - somewhere along that list, they would learn syntax highlighters highlight in different ways.

I have left this as a _feature request_ up for discussion, but I cannot see anything being done about it. It is also important to remember: the freeCodeCamp editor is specifically made to be as _bare-bones_ as possible, in order to reduce potential confusion/overwhelm.

**Comment by raisedadead** [comment]
I agree with @ShaunSHamilton here. We have picked an out of the box syntax highlighter and it is what it is for the moment. If there is a genuine need that the syntax highlighting needs updating say for a11y reasons we can discuss further.

Thanks for taking the time to reach out and report your feedback to us.

**Comment by acoder123** [comment]
Ok sure, thank you for your attentiveness.
