### ISSUE TITLE
Did we drop support for Safari?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41724]
Looking at PR [41501](https://github.com/freeCodeCamp/freeCodeCamp/pull/41501), it seems so.

Just as a heads-up we are starting to see forum threads now from Safari users and that specific [challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/change-a-variable-for-a-specific-area). 

Examples:

https://forum.freecodecamp.org/t/issue-with-detection-for-penguin-belly/453902

https://forum.freecodecamp.org/t/i-cant-pass-the-test-for-some-reason-even-though-it-seems-to-me-i-havent-done-any-mistakes/453964

https://forum.freecodecamp.org/t/penguin-belly-challenge-cant-be-passed/453941

**Comment by Sembauke** [comment]
This might have been me:
https://github.com/freeCodeCamp/freeCodeCamp/commit/87c9c799c6f7a9743a74c602694a2d6dcbfb9a20

Added a regex lookbehind that is not supported by Safari
https://caniuse.com/?search=lookbehind

**Comment by ojeytonwilliams** [comment]
Not deliberately, no.  Part of the problem is that we test the challenges using `js-dom`, not a browser.  I'd like to switch to using headless browsers, but, even then, Puppeteer doesn't currently support Safari: https://github.com/puppeteer/puppeteer/issues/5984.

So, every time fix regex issues, chances are someone (me, in this case) will forget about Safari.

One possible solution that we've discussed a few times is to use a css parser, rather than relying on regexes.  It'll be a bit of work to port the challenges, but hopefully it would prevent these kinds of issues.

**Comment by Sembauke** [comment]
@ojeytonwilliams  I have another solution that is supported by Safari should we revert the commit and change it?

**Comment by ojeytonwilliams** [comment]
@Sembauke yes please.  We won't be switching to a css parser immediately, so a PR to fix this would be great.

**Comment by Sembauke** [comment]
> Not deliberately, no. Part of the problem is that we test the challenges using `js-dom`, not a browser. I'd like to switch to using headless browsers, but, even then, Puppeteer doesn't currently support Safari: [puppeteer/puppeteer#5984](https://github.com/puppeteer/puppeteer/issues/5984).
> 
> So, every time fix regex issues, chances are someone (me, in this case) will forget about Safari.
> 
> One possible solution that we've discussed a few times is to use a css parser, rather than relying on regexes. It'll be a bit of work to port the challenges, but hopefully it would prevent these kinds of issues.

I might have found what you are looking for using a CSS-parser instead of RegEx.
https://www.npmjs.com/package/cssparser
