### ISSUE TITLE
Typo/Bug in For Loop iteration example of Basic Javascript lesson

### ISSUE THREAD

**Issue by RaviOnline** [freeCodeCamp/freeCodeCamp#41741]
**Describe your problem and how to reproduce it:**
When iterating any array normally (from the first to the last element), the loop counter equals the length of the array minus one during its last iteration. The lesson docs incorrectly say
> In this case the last iteration is `i === 4` i.e. when `i` becomes equal to `arr.length` and outputs 6 to the console.

**Add a Link to the page with the problem:**
[Iterate Through an Array with a For Loop](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop) lesson

**Recommended fix, suggestions (how would you update it?):**
The lesson docs should say
> In this case the last iteration is `i === 4` i.e. when `i` becomes equal to `arr.length - 1` and outputs 6 to the console.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot_2021-04-04 freeCodeCamp org](https://user-images.githubusercontent.com/1184040/113501331-d55d3380-9541-11eb-8784-d8058ad45473.png)

**Comment by raunak6662** [comment]
@RaviOnline , I am interested to work on this issue.

**Comment by Nirajn2311** [comment]
Yes, you are correct Ravi. Could you add the "first timers" label also.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by PeroHub** [comment]
I will Really love to work on this!!

**Comment by ieahleen** [comment]
@PeroHub thank you! this issue has already a linked PR. If you have not done so yet check the contributing guidelines at contribute.freecodecamp.org, and look at other issues tagged with "first timers only" or "help wanted" and note that issues generally are not assigned, but the first comprehensive PR is reviewed

**Comment by PeroHub** [comment]
Thank you @ieahleen for the prompt feedback.
I will definitely look out for other "first timers only" issues to fix

**Comment by jeremylt** [comment]
Deleting github issue or pr content is really disruptive
