### ISSUE TITLE
let instead of var

### ISSUE THREAD

**Issue by ShalokShalom** [freeCodeCamp/freeCodeCamp#41771]
**Is your feature request related to a problem? Please describe.**

In all due respect, why do you think its a great idea to use var in the year 2021?

**Describe the solution you'd like**

Let and const

**Comment by ShaunSHamilton** [comment]
Hello there,

Would you mind expanding on what you are referring to?

If you are referring to the various sections of the curriculum in which `var` is used, then it is simple - many codebases still use/have `var` declarations. Therefore, teach a Camper that this is/was a method of variable declaration; it is taught, because it exists, and is used.

If that is not what you are referring to, then a link to a specific resource might be helpful.

Thank you

**Comment by jdwilkin4** [comment]
Hi @ShalokShalom ! 

`let` and `const` are introduced in the curriculum starting with the [ES6 section](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#es6)

It sounds like you are referring to the first JavaScript section that uses `var`. 
But the course does use `let` and `const` throughout the course. 
Hope that helps!

**Comment by ShalokShalom** [comment]
And what keeps var at that first section?

**Comment by ShaunSHamilton** [comment]
> And what keeps var at that first section?

Probably the fact that that section was developed before `let` and `const` were made into the standard. But, also, because `var` is still in the standard.

Imagine being a new programmer to everything. You have solely been taught `let` and `const`. Then, you come across `var`. I would think I was looking at a different language, because it is so fundamental to languages.

It is also important to keep in mind that, whilst `let` and `const` have their advantages, there are many instances where current environments **cannot** interpret them, and `var` **must** be used. For example, in order to develop an application supporting the >99%, a transpiler (e.g. Babel) must be used to take all your _new_ code (`let` and `const`), and transpile it to just `var`.

All I am trying to get at is: `var` is incredibly relevant to JavaScript, and will be for a long time to come, AFAICS.

**Comment by raisedadead** [comment]
Closing this non-issue. Thanks for your feedback @ShalokShalom and your clarifications @jdwilkin4 and @ShaunSHamilton

**Comment by ShalokShalom** [comment]
Writing var and using them are two different things. 
Teaching them, especially as the first thing you do, is imho irresponsible. 

"Then, you come across var." 
He goes to a co-worker, who hopefully explains him, that this is legacy code, that is gonna get replace asap.

**Comment by miku86** [comment]
I totally understand both sides.

As an educator, I use `var`: because a lot of legacy code is built with `var`.

In my workshops, when I used `const`/`let`, people always came up with questions like "I had a look at some code since our last session, what does that `var` mean, we never talked about that!?". Then I had to "overload" their brains with `var`, `const`, `let` and their differences. This mostly led to overcomplicating stuff. I don't think that these implementation details matter that much, because I think it's more about the concept, so I think the term `var` is more intuitive to connect to "a variable value`.

**Comment by ShalokShalom** [comment]
I think you can benefit a lot, by telling them that this is legacy code, that var is buggy and a mistake, and a more experienced developer will fix this immediately.

This helps to avoid cluttering the minds of young programmers with stuff, they have not produced and since freecode is one of the largest Github repos and largest coding tutorial provider, **and since there is no warning** that var is obsolete and buggy, while being one of the first examples on the page, is freecode acting here as an accelerator of buggy code and tons of new developers repeat mistakes, that we **know for decades** are unsuitable, if you want to write stable and secure code.

That this is even a discussion, is ridiculous.
