### ISSUE TITLE
Lesson: Write Reusable JavaScript with Functions // Typo either in lesson or evaluation function

### ISSUE THREAD

**Issue by shmooth** [freeCodeCamp/freeCodeCamp#41791]
**Describe your problem and how to reproduce it:**
The lesson (on the left) says the string to be printed should be `"Hi World"` (_with_ the quotes), but the evaluation function/answer will flag this as wrong/incorrect.

Previous lessons seem to be clear/consistent about what the expected answer should be -- i.e. if quotes are to be included in an expected answer, they are highlighted with grey background in the lesson instructions (on the left).

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/write-reusable-javascript-with-functions

**Expected behavior**
The test/evaluation should pass as correct when you enter an answer such as the following (_with_ quotes):

> function reusableFunction(){
  console.log('"Hi World"');
}
reusableFunction();

**Tell us about your browser and operating system:**
**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser: Chrome
 - Version: Chrome 89 on Chrome OS 13729

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/1012311/114267570-46bd3c00-99b1-11eb-8a94-c4bea09d8729.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. This is one of those things we have been trying to figure out the best way to communicate intent across multiple languages. The idea is the quotes indicate what should be returned is a string, because, often, if the instruction reads:
> ... which prints `Hi World` to the dev...

Campers will write:
```
console.log(Hi World);
```

In general, save for one lesson, we do not ask Campers to print quotes, but I can see the confusion. My personal preference is to include the quotations in a code tag, if the code is a string, but much of the recent overhaul has done the opposite. I have put this up for discussion, until we come to a conclusion.

So, I suppose, for more consistency, we should write:
> Create a function called `reusableFunction` which prints the string `Hi World` to the dev console.

**Comment by JoshuaPelealu** [comment]
Would putting the quotation marks outside of the code tag work? Something like this
> Create a function called `reusableFunction` which prints the string "`Hi World`" to the dev console.

Or might this just make it a lot more confusing?

**Comment by ShaunSHamilton** [comment]
> Would putting the quotation marks outside of the code tag work?

This was one option, but I think this was an issue because different languages treat quotation marks in different ways. Nothing within a code block (backticks) gets translated. So, that kept it reasonably simple.

I loosely followed the translation effort. So, I am going to shut up now, and defer to others.

**Comment by Sembauke** [comment]
>  Create a function called `reusableFunction` which prints the string "`Hi World`" to the dev console.


I think this would be the best solution,  without the quotation marks. The sentence indicates that it should be a string so Campers will automatically write `console.log("Hi World")` instead of `console.log(Hi World)`.

**Comment by ieahleen** [comment]
I would not bet on the "automatically", but if it's just removing the quotes let's open it to first timers

**Comment by andypants888** [comment]
Hello! This is my first time commenting on github like this. I would like to work on this issue. I am researching how to get started, but I was hoping to "reserve" the problem? Please let me know if there is something I am missing.

**Comment by ShaunSHamilton** [comment]
@andypants888 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
