### ISSUE TITLE
Extremely Slow

### ISSUE THREAD

**Issue by IntegraterGithub** [freeCodeCamp/freeCodeCamp#41808]
I have been coding alot on fcc lately but the connection is appalling after a few weeks. Here is what I have tried:
<ul>
<li>Clearing cache </li>
<li>Restarting computer </li>
<li>Asking arond</li>
<li>Closing all of my tabs</li>
<li> Making sure google chrome is only open</li>
<li>Checking with other people that it works for them and it does perfectly </li>

</ul>

**Comment by Sembauke** [comment]
Hey @IntegraterGithub,

Are you referring to the freecodecamp.org website or are you talking about the repository?

**Comment by raisedadead** [comment]
Hello @IntegraterGithub thanks for reaching out to us. 

Sorry about the inconvenience you have been facing. We haven't received any recent reports about a similar issue from others. And like you said it has been working for others you know.

It's very much possible it could be down to the network / ISP etc. you are on. I think it's best you reach out to us on `support at freecodecamp dot org` email with additional details of your machine, location, ISP details, etc.

Because the above is sensitive personally identifying information, please do not share them here and instead use the email address above. We will have someone on the staff help you sort this.

Thanks.
