### ISSUE TITLE
Bonfire: Steamroller - correct return values not passing tests

### ISSUE THREAD

**Issue by alan1001110** [FreeCodeCamp/FreeCodeCamp#4187]
**Return values that should pass tests showi as failing, despite the correct return value shown in the output box.  Interestingly, when I wrapped the initial function call in a console.log(), all tests passed, but the output box showed undefined.**

User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.

*My code, including the console.log() that made everything pass:*
```javascript
var flatArr = [];

function steamroller(arr) {
  for (var i in arr) {
    if (Array.isArray(arr[i])) {
      steamroller(arr[i]);
    } else {
      flatArr.push(arr[i]);    
    }
  }
  
  return flatArr;
}

console.log(steamroller([1, [], [3, [[4]]]]));

```

**Comment by ltegman** [comment]
This is because you are declaring`flatArr` globally rather than inside the `steamroller` function scope. This means that after the first time you run `steamroller` you're not starting with an empty `flatArr` array when the function runs and will return an incorrect result. It looks like you're doing this so all the recursive calls to `steamroller` can share the variable, but as you can see using global variables to solve this problem can get you into a lot of trouble. Here's one way to avoid this issue.

```javascript
function steamroller(arr, flatArr) {
  if (!flatArr)
    flatArr = [];
  for (var i in arr) {
    if (Array.isArray(arr[i])) {
      steamroller(arr[i], flatArr);
    } else {
      flatArr.push(arr[i]);    
    }
  }

  return flatArr;
}
```

Closing as not an issue with the tests.

Thanks and happy coding!

**Comment by alan1001110** [comment]
Thanks for the explanation; I was only thinking about how to solve it once, but I did intend to rewrite it after some sleep without using a global.  

What I don't understand is why all the tests passed when I wrapped the function call in console.log(). It doesn't seem like they should.

**Comment by alan1001110** [comment]
Or just delete the function call.

**Comment by alan1001110** [comment]
Not sure how the tests are done, but...

If the tests essentially put all my code in a wrapper, then call that wrapper for each test, my code will pass every time (as long as I don't call the function in my code), because the local declaration would block any global declaration with the same name.  

But if that's the case, why would it work if I wrap my function call in console log(), since that seems like it would have same scope?

Ah well...
