### ISSUE TITLE
Stale Video - Nest Anchor Element

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#41911]
**Affected page**

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Your code**
Typical user code:

```
<h2>CatPhotoApp</h2>
<main>
<p> View more
<a href="https://www.freecatphotoapp.com" target="_blank">cat photos</a>
</p>
<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">

<p>Kitty ipsum dolor sit amet, shed everywhere shed <a href="https://www.freecodecamp.org">everywhere</a> stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
```

**Expected behavior**

We've had an uptick of people blindly copying the help video from this challenge without reading the instructions:
This leads to campers failing the requirement
> You should only have one `a` element.

(This is generally a problem with the help videos, unfortunately - copying with zero understanding.)

Does this video link need to be updated or removed?

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ieahleen** [comment]
let's remove it, it's already that direction with other videos, once there is a discrepancy, the challenge win and the video is removed

**Comment by lasjorg** [comment]
Seeing as this is an easy fix (I assume we just remove the URL) I will open this up to first-timers. If anyone disagrees feel free to remove the label.

**Comment by raisedadead** [comment]
Thanks for making this a first timers only. The only additional step I would be recommending is using [this template](https://contribute.freecodecamp.org/#/moderator-handbook?id=first-timer-only-issues) as an example to add clear instructions for first timers.

I am going to go ahead and take care of that here.

--

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/99cecfb5818e03c4b6876d6ecfd23da4291daebb/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md#L5

Edit this file and remove the line containing `videoUrl`.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by lasjorg** [comment]
@raisedadead Thanks for the help. I have added the template to a saved reply. Hopefully, I will remember to use it.

Also, I have a stupid question. How do you best "quote" the code and line numbers of a .md file? Do you just use the blame view or look at a commit/PR? I don't understand the commit link you have in your quote. It looks to be for something else?

**Comment by raisedadead** [comment]
Oh - I just use the code view for a markdown file and then grab the permalink. 

<details>
<summary>Details</summary>

Open file in code-view: It's the icon on the left at the top right of the file. Looks like this:

![image](https://user-images.githubusercontent.com/1884376/115919160-15a33800-a496-11eb-9e78-ac8ea2cf2cd5.png)

Getting the permalink by selecting the line (host shift for more lines):

![image](https://user-images.githubusercontent.com/1884376/115919449-76327500-a496-11eb-9a51-0d7c464a7ca9.png)

</details>

**Comment by lasjorg** [comment]
@raisedadead Right, but you can only get to the code view from inside a commit, right? I mean I do not see the source view for .md files when just looking at the file.

Anyway, I will figure it out sorry to bother you with this I know you are a busy man.

**Comment by raisedadead** [comment]
> I mean I do not see the source view for .md files when just looking at the file.

Yes, that is correct. I browse the repo with top commit at the time of making a comment. 

But again, you do not have to spell out every little detail for the first-timers, it's just a "the more the better" type thing.
