### ISSUE TITLE
Confusing Function Argument - Check Obj for Prop

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#41940]
**Affected page**
Add a link to the coding challenge with the problem.
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
let users = {
  Alan: {
    age: 27,
    online: true
  },
  Jeff: {
    age: 32,
    online: true
  },
  Sarah: {
    age: 48,
    online: true
  },
  Ryan: {
    age: 19,
    online: true
  }
};

function isEveryoneHere(obj) {
  // Only change code below this line

  // Only change code above this line
}

console.log(isEveryoneHere(users));
```

**Expected behavior**
The seed code and description for this challenge is confusing. 

> We've created an object, users, with some users in it and a function isEveryoneHere, which we pass the users object to as an argument. Finish writing this function so that it returns true only if the users object contains all four names, Alan, Jeff, Sarah, and Ryan, as keys, and false otherwise.

The challenge can be interpreted as asking the user to reference the global variable `users` inside of their function. The challenge can pass with code referencing the global object `users` or referencing the function argument `obj`. Which is the intended solution? Personally, I think the code should only function correctly when referencing the function argument to encourage best practices.

**System (please complete the following information):**
All

**Comment by jeremylt** [comment]
I'm also not exactly in love with the variable name `obj`, since we're looking at this.

**Comment by moT01** [comment]
I assume it was intended that users should use the object passed to the function. The test text isn't exactly helping: `The function isEveryoneHere should return true if Alan, Jeff, Sarah, and Ryan are properties on the users object`

We could change them all to `the object passed to it` - e.g...

Instructions:
`Finish writing the function so that it returns true if the object passed to it contains all four names, Alan, Jeff, Sarah, and Ryan, as keys, and false otherwise.`

Test:
`The function isEveryoneHere should return true if Alan, Jeff, Sarah, and Ryan are properties in the object passed to it`

The tests would need to be adjusted as well.

`obj` isn't a great name, but I don't think it's that much of an issue either. Could maybe go with `userObject`. I think a bigger problem is that users can use the global object.

**Comment by Ismailtlem** [comment]
I agree with what was being said : 

- From a naming perspective, the name ``` obj ``` is not a great choice. It doesn't have any meaning and can only lead to confusions. Something like ``` userObject ``` as pointed by @moT01 is more appropriate
- I also agree on the fact that the instruction is unclear.
