### ISSUE TITLE
Error with multiple choice question in Python for Everybody

### ISSUE THREAD

**Issue by Jardimjose** [freeCodeCamp/freeCodeCamp#41996]
The given regex syntax does not capture any of the results in the given answers which creates confusion when answer thing questions.

**Affected page**
Add a link to the coding challenge with the problem.
the problem was found here
https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/regular-expressions-matching-and-extracting-data

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
import re
s = 'A message from csev@umich.edu to cwen@iupui.edu about meeting @2PM'
lst = re.findall('\\S+@\\S+', s)
print(lst)
# not the same as the code below, gives different outputs 
import re
s = 'A message from csev@umich.edu to cwen@iupui.edu about meeting @2PM'
lst = re.findall('\S+@\S+', s)
print(lst)
```

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.
[SS of first Regex](https://cdn.discordapp.com/attachments/838318470348406835/839415207469514752/unknown.png)
[SS of second Regex](https://cdn.discordapp.com/attachments/838318470348406835/839415283110248458/unknown.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10,
 - Browser: chrome
 - Version: latest

**Additional context**

**Comment by gikf** [comment]
Thank you for reporting this issue.

Backslash is escaped in string here and it's not considered as literally two backslashes, for that it would be needed to be defined as `r'\\S+@\\S+'` or `'\\\S+@\\\S+'`. On the screen it can be actually seen, that regex there is using the so-called raw strings (the `r` prefix). Here are some examples with the match results: https://replit.com/@sanityto/HandyTinyCarrier#main.py.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
