### ISSUE TITLE
Bug: uBlock Origin breaks certain javascript challenges

### ISSUE THREAD

**Issue by psyfry** [freeCodeCamp/freeCodeCamp#41995]
**Affected page**
Various challenges in "Basic javascript" lessons.
First fully-broken lesson I encountered: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions
Previous lessons gave same error, but were passable without disabling uBlock.
**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:
Have uBlock Origin addon active and try correct solution for https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions
Interestingly, I tried replicating the issue by re-enabling uBlock and trying the code again, and it passed subsequent times with uBlock enabled. 
```
// Setup
function abTest(a, b) {
  // Only change code below this line

if (a < 0 || b < 0) {
  return undefined;
}

  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

abTest(2,2);
```

**Expected behavior**
Add a clear and concise description of what you expected to happen.
Correct solution passes test.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.
Top banner error message that said something along the lines of " Something went wrong, a report has been filed for this issue"

**System (please complete the following information):**
 - Device: [desktop]
 - OS: [e.g. Windows 10]
 - Browser: [Firefox, uBlock Origin addon]
 - Version: [e.g. 22]

**Additional context**
Yeah, it appears uBlock is breaking something with javascript. My understanding is uBlock utilizes different injection methods to heuristically sanitize ad scripts. 
However, re-enabling uBlock and running the test again with the same correct code passes the test.   
Solution that has worked for me so far is just add freecodecamp.org to the allowlist.

**Comment by raisedadead** [comment]
Hi there,

Thanks for reporting this. 

Yes - We use some non-traditional ways to evaluate user code (text from the editor) within the browser's context with a `eval` and DOM snapshots.

This is typically the behavior that trips most extensions including like ad-blockers like uBlock Origin. Theres just not too much we can do about these factors that we do not control, unfortunately.

Glad to know that adding freecodecamp.org to the `allowlist` resolved the issue you are facing. But I would like to clarify and give a fair warning that we do use Google Analytics for our metrics.

**Comment by psyfry** [comment]
Thanks for the heads up about the google analytics. I can see how some people may take offense and it's not a cut-and-dry "disable adblocker" notification solution.
I personally don't care about google analytics for quality open resources like freecodecamp and plan on finishing the rest of the Javascript course material, so which would be most-helpful feedback data?
1. Keep strict ublock and report hard-breaks.
2. Just enable google analytics
3. doesn't really matter either way.

**Comment by raisedadead** [comment]
Hmm, I would say for now it really does not matter. Our implementation is limited in certain ways. 

We put up a warning on some challenges (in the CSS section) I believe asking users to disable the extensions. We do not do a good job of explaining "why" because it's too complicated to explain how it works in a succinct way.

We have been exploring some ways to mitigate this:

1. One way would be bundle and deliver the code execution logic separate from the website bundles. That way using ad-blockers would probably not trip the crucial code. However, it's somewhat of a maybe and not too different than what we do right now already. 
2. The other way would be to rewrite all of the current logic with something that is more secure, that does not have an overlap with the regular JS code like GA, etc.

That said we do not have an ETA on both approaches, because the time and efforts into those somewhat out-weigh asking users with a "Hey! Could you try disabling the extensions?" - not the most virtuous way but helps reduce their frustration.

As for your question: I think you should still leave feedback here if you so please. I am going to add this to the roadmap for doing some hard-thinking.

**Comment by lasjorg** [comment]
@raisedadead I believe the warnings are still missing now after the (not so) recent changes to the layout.

https://github.com/freeCodeCamp/freeCodeCamp/issues/41417

It may have caused a slight increase in forum posts again, but it isn't as bad as I used to be (I think).

**Comment by lasjorg** [comment]
Sure. But I'm just not sure what the consensus was.

**Comment by raisedadead** [comment]
It wasn't getting conclusive so [I said](https://github.com/freeCodeCamp/freeCodeCamp/issues/41417#issuecomment-795844937) we should implement [Nick's suggestion](https://github.com/freeCodeCamp/freeCodeCamp/issues/41417#issuecomment-794892623).

**Comment by lasjorg** [comment]
So two PRs. One for the block note and one for the individual challenge.

**Comment by raisedadead** [comment]
Yup, sounds like a plan and we can close that other thread in favor of this.

**Comment by lasjorg** [comment]
We are basically reintroducing https://github.com/freeCodeCamp/freeCodeCamp/pull/38806 which as an aside originally also tried to deal with ad/script blockers.

Might it not be better to add the warning to the top of the RWD [start page](https://www.freecodecamp.org/learn/responsive-web-design) instead of the section blocks?

1. It's not just the Basic CSS section that has color challenges.

2. I get that the camper is automatically taken from the last HTML challenge to the first CSS challenge (which uses colors). So having a warning on this challenge might be necessary. But again this might be avoided simpely by having a warning at the begining of the RWD section.

Here it is with a bootstrap alert. But it can also just be a simple paragraph (note in bold, or all of it in bold).

![RWD-start-section-bootstrap-alert](https://user-images.githubusercontent.com/28780271/117549409-8e7bc580-b03a-11eb-9451-8a213f7cfbb5.png)

**Comment by lasjorg** [comment]
Also quick question.

I'm totally out of the loop on the i18n stuff. How does the text in intro.json get translated to the other languages? When adding content to the files in `client\i18n\locales` do we need to do anything special?

**Comment by ahmadabdolsaheb** [comment]
So with #42091 merged, do we still need to keep this issue open?

**Comment by raisedadead** [comment]
Yes - see https://github.com/freeCodeCamp/freeCodeCamp/issues/41995#issuecomment-832707706

**Comment by nhcarrigan** [comment]
Going to close this as stale - something we can ideally fix with Oliver's mega-rewrite of our client/curriculum logic.
