### ISSUE TITLE
Typo in 'certification-card' translations

### ISSUE THREAD

**Issue by jonathankerr** [freeCodeCamp/freeCodeCamp#42098]
Pointed out by igorgetmeabrain on the forum we have a small typo in the claim your certifiation card.

![typo](https://user-images.githubusercontent.com/80848313/117825844-8f456f00-b267-11eb-9146-640449e4c513.png)

**Affected page**
Line 564
https://github.com/freeCodeCamp/freeCodeCamp/blob/519c70f819720a0287d0c8b1f553498974867978/client/i18n/locales/english/translations.json

**Additional context**
Potential to make this first timers only?

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Only file linked above needs to be changed, other language files, if needed, will be updated using the translation workflow.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by bodasheera** [comment]
I have fixed the issue. This is my first time contributing in open source. Please check it @gikf https://github.com/freeCodeCamp/freeCodeCamp/pull/42100
