### ISSUE TITLE
The strip-comments library may have broken Safari support

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#42101]
I think we (well I) broke Safari support with this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/41960.

In my defense, I can't test code on Safari and didn't even think about the use of unsupported regex in the library as it has so many weekly downloads on npmjs that I just assumed good browser support.

Here is an issue on the libs Github that seems to confirm it.
https://github.com/jonschlinkert/strip-comments/issues/64

Forum posts:

https://forum.freecodecamp.org/t/invalid-regular-expression-error/459841

https://forum.freecodecamp.org/t/cant-run-test-on-freecodecamp/459842

https://forum.freecodecamp.org/t/syntax-erro-invalid-regular-expression/459834

**Comment by Dorfieeee** [comment]
It appears so.. I was just about to open an issue

**Comment by lasjorg** [comment]
God, Safari really is the new IE. They have had so long to implement this and still haven't. So annoying.

**Comment by lasjorg** [comment]
Who on the fCC team can and does test PRs using Safari? I would really hope we have some way of catching these bugs.

**Comment by Dorfieeee** [comment]
Is rollback possible?

**Comment by lasjorg** [comment]
It is. The problem is, it was fixing another bug https://github.com/freeCodeCamp/freeCodeCamp/issues/41951 with how we were removing comments. So we really need a new solution that works.

**Comment by ShaunSHamilton** [comment]
> Who on the fCC team can and does test PRs using Safari?

In the past, we have needed to rely on @moT01 or @ahmadabdolsaheb .

**Comment by lasjorg** [comment]
@Dorfieeee Thanks for the source dive. It's as suspected. We have been bitten by this before in our own regex tests.

**Comment by ojeytonwilliams** [comment]
At this point I'm wondering if we should just try to create a "good enough" regex ourselves.  Make sure it doesn't use any syntax that Safari can't handle and that it passes the tests (we should add a few more) and just use that.

**Comment by lasjorg** [comment]
@ojeytonwilliams Probably. I just wonder how long it will take for some other update to some lib to break. Safari really needs to implement this feature ASAP.

---

I know this is off-topic but is using `require` based on options considered bad practice?

In the strip-comment lib, the languages all have their own export, and only JS is used by default. So instead of just pulling in all the languages it does the import/require of the language based on the options. I mean it can only work with one language at a time, right? You use it once per language. It's not like you need all the languages required in before the option has been set.

`const lang = require('./languages')[name];`

https://github.com/jonschlinkert/strip-comments/blob/master/lib/parse.js#L20

**Comment by ojeytonwilliams** [comment]
> Probably. I just wonder how long it will take for some other update to some lib to break. Safari really needs to implement this feature ASAP.

Agreed, but at least we'd reduce the number of places where we can run into this.

> I know this is off-topic but is using require based on options considered bad practice?

Generally you don't want to require an entire package if you only want a bit of it.  So, if you're `require`ing rather than importing, you're already getting the whole thing and bundlers like Webpack can't help you.  This [post](https://insights.untapt.com/webpack-import-require-and-you-3fd7f5ea93c0) goes into it quite nicely.

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams I just mean for the library's own code. So it just requires the language object based on the option instead.

Right, but it should have the same consequences either way - namely excessive bundling.  Not that this library is particularly big, so it's not a huge deal.

I'm really curious to see what happens on your fork, because I'd have guessed that deferring the `require` to inside `parse` would still result in the lookbehind's being evaluated (when `parse` gets called) and Safari falling over.

**Comment by lasjorg** [comment]
@ojeytonwilliams Right it doesn't work. I kind of spaced out about webpack as part of our build process, I just tested it with the libs own tests and normal node usage.

I guess you have to remove the HTML object from languages.js as the [other fork](https://www.npmjs.com/package/@tone-row/strip-comments) does. I did test that (using lambdatest) and it worked on macOS Mojave with Safari 12. I also did a diff just to check and it looked fine.

https://replit.com/@lasjorg/strip-comments-tone-row

**Comment by ojeytonwilliams** [comment]
Nice, it looks like that fork works, then. 

It seems that the original repo is fairly lightly maintained these days ([minimal commits since 2019 ](https://github.com/jonschlinkert/strip-comments/commits/master)), so we'd either want to fork that or homebrew a solution.

Either way seems fine to me, but forking seems like the most straightforward approach to me.  We can then polish it as much or as little as we like and we're starting from a pretty reliable base.  What do you reckon?

**Comment by lasjorg** [comment]
I like the idea of going with a fork. As you said, we can tweak it as needed.

**Comment by ojeytonwilliams** [comment]
Hey @lasjorg we now have a fork: https://github.com/freeCodeCamp/strip-comments/  Since you're most familiar with all the issues surrounding this, would you be interested in leading the development? If you have any questions, you can drop them here or reach to me in [chat](https://chat.freecodecamp.org/) (I'm 'oliver' over there)

**Comment by lasjorg** [comment]
@ojeytonwilliams Sure, I can give it a go. I should warn you though. I'm not very proficient with regex, so I'm unlikely to make any improvements to the core parts of this lib.

I will create a PR removing the HTML regex needed for Safari compatibility.

**Comment by ojeytonwilliams** [comment]
Awesome, glad to hear it.  You should have an invite to it now.

There's not a lot needing doing in terms of modifying the core functionality.  Off the top of my head we could start supporting ESM, maybe using https://github.com/getify/moduloze, but that's about it.  

Also, thanks for creating that PR so quickly. I'll take a proper look tomorrow.

**Comment by lasjorg** [comment]
> You should have an invite to it now.

Where would this be? I don't see it anywhere.

**Comment by ojeytonwilliams** [comment]
Usually you get an email. It looks like you've already got maintainer access, though. You should be able to push directly, change settings and so on.

**Comment by Sembauke** [comment]
fixed in  #42254
