### ISSUE TITLE
Josephus Problem - Off By One

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#42141]
**Affected page**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/josephus-problem

**Your code**
```javascript
function josephus(init, kill) {
  // Setup
  let currPrisoner = 0;
  const prisoners = Array(init).fill(true);
  // Execute prisoners
  console.log("Kill Sequence:");
  for (let numAlive = init; numAlive > 1; numAlive--) {
    // Find next prisoner
    for (let numSkip = kill; numSkip > 0; numSkip--) {
      do {
        currPrisoner = (currPrisoner + 1) % init;
      } while (!prisoners[currPrisoner]);
    }
    // Execute prisoner
    console.log(currPrisoner);
    prisoners[currPrisoner] = false;
  }
  // Return last man standing
  console.log("Last Man Standing:");
  console.log(prisoners.indexOf(true));
  return prisoners.indexOf(true);
}

josephus(5, 2);
```

**Expected behavior**
The code that passes the test suite (given above) provides different output than the traditional description of the problem. I think the test suite has an 'off by one' error in initializing the starting position.

Current output with solution that passes test suite:
```
Kill Sequence:
2
4
1
0
Last Man Standing:
3
```
Expected output per problem description:
```
Kill Sequence:
1
3
0
4
Last Man Standing:
2
```
Relevant portion of problem description:
> For example, if there are n=5 prisoners and k=2, the order the prisoners are killed in (let's call it the "killing sequence") will be 1, 3, 0, and 4, and the survivor will be 2.

See also discussion here:
https://forum.freecodecamp.org/t/solution-to-rosetta-code-challenge-josephus-problem/460203

**Proposed Fix**
Change test suite to
> `josephus(30,3)` should return `28`

> `josephus(30,5)` should return `2`

> `josephus(20,2)` should return `8`

> `josephus(17,6)` should return `1`

> `josephus(29,4)` should return `1`

Bug reported by jsdisco on the forum.

**Comment by gikf** [comment]
The issue seems to originate from the original challenge at the Rosetta Code, there's optional allowance for numbering prisoners from `1` in solution, and that's what's happening in the used solution - https://rosettacode.org/wiki/Josephus_problem#JavaScript.

Solution for the challenge also needs small change to use `i` for initial label, instead of `i + 1`.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/josephus-problem.md#--solutions--

**Comment by Nirajn2311** [comment]
I'm confused in the example given in the description, if the executioner starts at 0 and kills every 2nd prisoner then shouldn't the first prisoner that is killed be prisoner 2 and hence the killing order becomes 2,4,1,0. I think the challenge description is the one that has to be changed here. Also if numbering started from `1` then the above killing order is just incremented by 1 which still won't be the solution given as example.

**Comment by gikf** [comment]
This is how I'm seeing it.
```
Starting from 0 ->
01234
 ^
0x234
   ^
0x2x4
^
xx2x4
    ^
```

**Comment by jeremylt** [comment]
Killing every other would be 'safe', 'kill', 'safe' , 'kill', 'safe',.... But the current solution is 'safe', 'safe', 'kill', 'safe', 'kill', 'safe',...
The solution/tests definitely have an off by one

**Comment by Nirajn2311** [comment]
I understood it wrongly @gikf . Also yea its the tests which are off by one. Looks like a good first issue.

**Comment by alirezaghey** [comment]
Hi,
I have a working solution for this, although not the most efficient one. It's relatively concise but using `splice` the time complexity is quadratic. Can I make a PR?

**Comment by Sembauke** [comment]
@alirezaghey, You can always open a PR. After that, we can give feedback and suggest changes if needed.

**Comment by jeremylt** [comment]
I'm not sure why you need to make a brand new solution. You just need to modify one of the existing solutions to reduce the starting value. In my solution, for example, you just set `let currPrisoner = -1`

**Comment by alirezaghey** [comment]
Hi @jeremylt,
AFAIK, there is no compelling reason to completely change the original solution.
The original solution has a better time complexity.
The only benefit to my approach is that the code is less error prone, since we are not implementing a fundamental data structure from scratch, and the basic steps of the algorithm that solve the problem are easier to read, since they are not mixed with the implementation details of the underlying data structure.

I have already made a PR, but can fall back to the original solution, if you see necessary.

**Comment by jeremylt** [comment]
A agree that the original solution is pretty convoluted.
