### ISSUE TITLE
Log [ ] instead of giving error

### ISSUE THREAD

**Issue by jaestaar** [FreeCodeCamp/FreeCodeCamp#4216]
Challenge [Waypoint: Iterate Odd Numbers With a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-odd-numbers-with-a-for-loop#?solution=var%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor(var%20i%20%3D%200%3B%20i%20%3C%2010%3B%20i%20%2B%3D%202)%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afor%20(var%20i%20%3D%201%3B%20i%20%3C%2010%3B%20i%20%2B2)%20%7B%0A%20%20myArray.push(i)%3B%0A%20%20%0A%7D%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof(myArray)%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myArray%3B%7D)()%3B%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [];

for(var i = 0; i < 10; i += 2){
  ourArray.push(i);
}

var myArray = [];

// Only change code below this line.
for (var i = 1; i < 10; i +2) {
  myArray.push(i);
  
}


// Only change code above this line.

if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}


```

**Comment by SaintPeter** [comment]
The issue here is a syntax error on this line:
`for (var i = 1; i < 10; i +2) {`
Should be `i += 2`, not `i +2`.

The code doesn't run because it can't be parsed properly due to a syntax error.  It's not possible to capture syntax errors except possible via the linter.  

@BerkeleyTrue should the linter catch this?

**Comment by BerkeleyTrue** [comment]
That isn't technically a syntax error. It's a logic error for sure.

The for loop syntax only dictates there be valid expressions in it's definitions. i + 2 is a valid expression.

The first part is initialization before running any loop (must be a valid expression).

The second part is a conditional check for each loop (this is the only one that effects the running of the loop) and also must be a valid expression. If that expression returns false, the loop breaks otherwise it continues to loop.

The third part is an eval of an expression after each loop.

**Comment by SaintPeter** [comment]
I'm closing this as "Not detectable by machines".

@jaestaar, thanks for reporting this, don't forget to check by the /Help channels for confirmation if you have trouble.
