### ISSUE TITLE
Small typo in the React for Beginners FCC article

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#42240]
**Describe your problem and how to reproduce it:**
In this article, there is a code snippet in the Embedding JavaScript in JSX section that uses class instead of className.
```
<img src={logo} class="App-logo" alt="logo" />
```
The issue was brought up in this FCC forum discussion.
https://forum.freecodecamp.org/t/mistake-in-the-first-page/461687/5

I think it should be changed to className since the previous section of the article talked about not using class. 
Thanks! 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/react-beginner-handbook/

**Recommended fix, suggestions (how would you update it?):**
```
<img src={logo} className="App-logo" alt="logo" />
```

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2021-05-24 at 10 11 03 PM](https://user-images.githubusercontent.com/67210629/119442557-f0942600-bcdc-11eb-950b-c29012b9d718.png)

**Comment by raisedadead** [comment]
We just streamlined the process a bit, and the fastest way to resolve typo and content errors are to send issues like these to the `editorial<at>freecodecamp.org`

You are still welcome to report issues on this tracker; we will forward the same to the email I mentioned earlier.

/cc @freeCodeCamp/moderators

**Comment by lasjorg** [comment]
> You are still welcome to report issues on this tracker; we will forward the same to the email I mentioned earlier.

@raisedadead So we don't have to do anything in/to the old issues?

How are the issues forwarded if I may ask, is it done manually or what?

**Comment by raisedadead** [comment]
When you see any **content issue** with `/news` reported to you over any of the channels like the chat, forum, discord etc., you should send an email to `editorial<at>freecodecamp.org` with details like a link to the conversation, post etc. instead of reporting it here on GitHub.

Alternatively, as per your convenience & comfort, you can freely report here on GitHub, and one of us mods can send the email to the editorial team. This will mean some extra efforts, but the end goal is to email the editorial team at the end of the day.

All old **content issues** should be audited and closed. If they have not been fixed, you can email links to those to the email.

Again, to clarify, all of this applies to content only and not bugs in the news application.

**Comment by lasjorg** [comment]
@raisedadead Thanks for the clarification.

How do we know when an article has been fixed, do we get an email reply back?

Personally, I think it just feels more organized using issues to track the reports.

- Can avoid people sending duplicate reports.
- A more centralized location for the report that allows others to verify or add to the report.
- Disputes or clarifications would be easier to manage in an issue.

I'm just thinking out loud here.

---

Just as an aside. Should the email be added to the news article page so readers can report corrections? For example down by the author info and tweet button? Or is that just asking for trouble.

**Comment by raisedadead** [comment]
Hi @lasjorg 

Respectfully, I think you are overthinking this. We don't mean to change the process. My recommendation is we trust mods enough to email the editors directly. We all are part of the same team :)

The editorial team uses email to work through every article submission (new & edits) from the authors as a part of their workflow. They process all the emails that they get, and even in 2021, it works remarkably well. We are simply adding to that queue.

Creating GitHub issues while more "organised" and elegant involves more people in the loop only to reach the same email-based workflow. That is, for instance, a mod sees something on the forum, reports here. Staff sees the issue, tags someone else (mostly Kris) to look into it. 

Yes - it's formal, but it's unnecessary overhead.

Email is faster. 

The editors will get the changes done. 

Like any email to support, you will get an acknowledgement from someone on the team when they have looked and have worked on the request. You can always follow up.

Finally, as I said earlier, it's totally OK to report on GitHub as an alternate.

And about listing, not listing the email on all articles is intentional. It's similar to why we want everyone to first reach out to the forum before reporting things on GitHub or the Staff. We can cut many regular queries and keep everyone's focus on the tasks that need attention.

Let me know if this makes sense? Cheers.
