### ISSUE TITLE
Exercise Tracker App: 7th test shows 'timed out' for data sorting(date field) error

### ISSUE THREAD

**Issue by zkindest** [freeCodeCamp/freeCodeCamp#42257]
**Affected page**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker

**My code**
```
app.get('/api/users/:_id/logs',async(req,res)=> {
  const {_id:id} = req.params;
  if (!id) {
    res.status(500).send("Please Provide user id")
    return;
  }
  else {
    try {
      const user= await User.findById(id,{__v:0});
      const {from,to,limit} = req.query;
      await user.populate({
        path: 'log',
        select: {
          __v: 0,
          _id: 0
        },
        match: {
          $and : [{date: { $gte: from || new Date(1970)}},{date: { $lte: to ||new Date() }}]
        },
        // options: {
        //   sort: {
        //     date: -1
        //   }
        // },
        perDocumentLimit: limit && +limit
        
      }).execPopulate();
      let log = user.log.map(({date,description,duration})=> {
        return {'date': new Date(date).toDateString(),description,duration}
      })
      let data = {
        _id: user._id,
        username: user.username,
        count: log.length,
        log
      }
      res.json(data)
    }
    catch(err){
      res.status(500).send(err.message)
    }
  }
})
```

**Expected behavior**
1. it should not say test timed out if sort options(see above) are not provided.

**Need Help (Optional)**
Please let me know if there's any better way to format date with mongoose.Thanks in Advance!!

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
