### ISSUE TITLE
Typo in medical data visualizer AssertionError message

### ISSUE THREAD

**Issue by kkralik** [freeCodeCamp/freeCodeCamp#42267]
**Affected page**
https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/blob/master/test_module.py

Typo on line 47: word 'different' is missing the second 'e'

**System (please complete the following information):**
 - Device hp pc
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 75.0.3969.267

**Additional details**
Typo on line 47: word 'different' is missing the second 'e'

**Comment by ShaunSHamilton** [comment]
Closed by https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/12

**Comment by n4i9kita** [comment]
Hi there, can I do it?

**Comment by ShaunSHamilton** [comment]
@n4i9kita

Thank you, for your interest in contributing. This issue is already closed.

However, you are welcome to find an issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
