### ISSUE TITLE
Missing period at the end of the second sentence.

### ISSUE THREAD

**Issue by stephanduesterhoeft** [freeCodeCamp/freeCodeCamp#42331]
**Affected page**
curriculum/challenges/english/01-responsive-web-design/basic-css/specify-how-fonts-should-degrade.md

**Expected behavior**
At the end of the second sentence "These generic font families include monospace, serif and sans-serif" the period is missing.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/57948566/120474441-84828380-c3a8-11eb-8eab-cd39f4a0686d.JPG)

**Comment by SethFalco** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/specify-how-fonts-should-degrade.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
