### ISSUE TITLE
Project Description/submission pages do not load on Safari

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#42431]
**Affected page**
All Project description pages except those in the JavaScript Algorithms and Data Structures Certification.

**Expected behavior**
The page should render, but it is stuck in the loading screen.

**System (please complete the following information):**
 - Device: iPhone 11 (also reported on iPads)
 - OS: iOS
 - Browser: Safari and Firefox
 - Version: latest

**Comment by ShaunSHamilton** [comment]
Could reproduce on: Mozilla/5.0 (iPad; CPU OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/85.0.4164.0 Mobile/15E148 Safari/604.1

404 from CloudFlare:
```
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=NATj2TAtTi0w0Q3QSDMU9xxi3d1Q3vZ4HnncwEAoUE9CviR6eKb1X8kdV4vBp7oq0tWIytsxX4AZVUFbpLNgPfwE8AwqT%2FWhoaGfzI9gP8eI0b%2FU5pt3ESWejf%2FoyGqIuw%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
status: 404
```
However, I was also unable to access any page without seeing the loading screen.

Could not reproduce on 13-inch Mac (does not tell me version on Lambda Test 🤷‍♂️ )

**Comment by raisedadead** [comment]
Quick follow-up question: 

Assuming from Ariel's report the earliest this was seen was at least two hours ago (2:20 pm - UTC). I just pushed out a fresh batch of the platform updates minutes ago (4:26 pm - UTC). Can you confirm after waiting for a few more minutes the issue is still current?

**Comment by ArielLeslie** [comment]
The earliest report I have of the issue is from yesterday via this reddit post: https://www.reddit.com/r/FreeCodeCamp/comments/nvu4by/problem_while_opening_the_projects_in_ipad/

It doesn't seem to be working yet on, but I'll give it time to take effect and try again.

**Comment by ShaunSHamilton** [comment]
I can access from `.dev`, now.

**Comment by ArielLeslie** [comment]
I'm still not able to on Firefox or Safari.

**Comment by raisedadead** [comment]
Thanks, @ArielLeslie & @ShaunSHamilton. It seems that the OP on Reddit have mentioned it's a recent iOS update thrown into the mix. 

We will need to keep investigating.

**Comment by Neeti797** [comment]
Hi I am the OP in reddit  and yes i still cant access it .tried on safari and chrome. something with the new iOS update

**Comment by lasjorg** [comment]
It's odd how this also seems to be affecting clicking the links. If you look at the [video posted](https://forum.freecodecamp.org/t/safari-curriculum-pages-stuck-loading/464358/9) on the forum they also can't left-click the link and has to use right-click open in new tab. I would expect that to be a totally different issue from the loading one.

If this happens on different browsers, it must be some update to some core OS feature (you would think anyway). Surely we can't be the only ones affected by this?

Here is a link to the security updates:
https://support.apple.com/en-us/HT212528

**Comment by ArielLeslie** [comment]
It appears to also be a problem on Safari for MacOS.  It is also affecting the Settings page.

https://www.reddit.com/r/FreeCodeCamp/comments/nxlejk/projects_and_settings_wont_load/
https://forum.freecodecamp.org/t/cannot-make-my-profile-public/464295

**Comment by ojeytonwilliams** [comment]
The fix is live in production now, thanks to @moT01.

**Comment by moT01** [comment]
Hey @Neeti797, is it working for you now?

**Comment by Neeti797** [comment]
Yes .thank you

**Comment by lasjorg** [comment]
I don't understand how that Safari regex bug is able to affect other browsers? I thought we had reports of this breaking on Chrome and Firefox on iOS?

**Comment by raisedadead** [comment]
Actually, the facts, the cause and signals that we got during this are a bit confusing and rightly so. I will shed some light. 

- The issue is some browsers do not support some features - Safari infamously doesn't support lookbehind regex. 
- We happened to upgrade a dependency (see linked PR) right around when a new version of iOS was also released. This dependency internally used lookbehind in its code.

  While the new iOS update may not have contributed to the confusion, it was coincidental enough to confuse us and everyone else, sending yours truly, in particular, on a goose chase.

- And on top of this, our limited ability to have good QA coverage (actual human validation for releases) of all sorts of browser combinations allowed this significant bug to pass thru.

We have clarified additional sources of information on the bug and the need to downgrade a package in the linked PR, which you are welcome to check and diagnose even further should you be interested.

That said, we are looking into integrating tools like BrowserStack & Percy to improve our coverage on multiple devices - browser combinations, and reduce human bias while we QA and release updates.

We would welcome some help with the above integration if that interests anyone.

**Comment by Nirajn2311** [comment]
I have used Browserstack for cross testing and it hasn't disappointed me at all. Mostly I've used it for mobile testing because Devtools has its own restrictions. I haven't tried Percy though.

**Comment by raisedadead** [comment]
Sure we can discuss this in more detail. Would you be interested in leading the effort? If yes, go ahead and create a thread?

**Comment by Nirajn2311** [comment]
Sure, is it fine I paraphrase your comment?

**Comment by raisedadead** [comment]
By all means. I would keep it about BrowserStack (cross-testing) specifically though. We may have other umbrella issues discussing testing and libraries in general which I will look up and share later.
