### ISSUE TITLE
Background color of Learn UI - Challenge Instructions

### ISSUE THREAD

**Issue by dottorgross** [freeCodeCamp/freeCodeCamp#42557]
Can I suggest to render the Instructions of each challenge with a background color to diversificate it from the explanations (description)?

**Comment by raisedadead** [comment]
Thanks for reporting this to us. Could you possibly elaborate a bit on the motivation behind doing so?

**Comment by dottorgross** [comment]
Certainly. As a curriculum user:
-  I read the explanations
- I read the instructions
- I try to do what is required but...
- ...if I have some problem and I think I have understanded the explanations, I visually search the instructions to re-read them

I think I would be more comfortable visually if the instructions were marked with a slightly different background, or with an icon...

**Comment by ojeytonwilliams** [comment]
There is a horizontal line separating the two: 
![image](https://user-images.githubusercontent.com/15801806/122583008-151fbb80-d059-11eb-93eb-80aa1c90ede9.png)

It's quite subtle, though, so I can see why it might not be a strong enough of an indicator.

**Comment by dottorgross** [comment]
Exactly... mine is just a suggestion, nothing essential

**Comment by raisedadead** [comment]
@dottorgross 

Thanks for sharing your feedback, we appreciate it.

To share some context, the subtle horizontal line is intentional. We would want the users to slow down, read and understand the challenge. Often times we see users doing a speedrun thru challenges just to solve each one quickly.

I feel having a clear distinction would only encourage that behaviour more. But we are open to ideas.

Thanks again.

**Comment by dottorgross** [comment]
Thank you! I hadn't thought about "speedruns". In this case it is good that the instructions merge with the explanations.
