### ISSUE TITLE
Portfolio Description Breaks Words on Wrap

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42676]
**Affected page**
Any profile with a portfolio item: https://www.freecodecamp.org/sky020

**To Reproduce**
1) Go to above portfolio link
2) Scroll to first and only portfolio item
3) Be shocked and horrified at word-wrapping

**Expected behaviour**
There should be no word wrapping breaking the word. I suggest something be added to the CSS like:
```css
.media-body > p {
  word-wrap: normal;
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/51722130/123931796-c3483100-d988-11eb-81ae-1d06ff978004.png)

Reported on forum: https://forum.freecodecamp.org/t/profile-on-freecodecamp-org/467140

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by alirezaghey** [comment]
Hi @ShaunSHamilton 
I had a look at this. It appears that this line is creating the mess.
https://github.com/freeCodeCamp/freeCodeCamp/blob/9ad2882009ed0bfae1ca240c3cc34ad88b29c11f/client/src/components/profile/components/portfolio.css#L10-L12
Wouldn't it be better to just remove that rule? I've tested it through dev tools and it works. Also checked the source  and it appears that `portfolio.css` is only referenced in `Portfolio.tsx`, so there are probably no unwanted side effects.
Unfortunately, I can't access the profile page on my local setup to test.
On a sidenote, how could I setup my local instance so that I can access the profile page?

Anyway, what do you think?

**Comment by ShaunSHamilton** [comment]
@alirezaghey 
> Wouldn't it be better to just remove that rule?

Potentially. But, as you say, only if there are no side-effects.

> how could I setup my local instance so that I can access the profile page?

It is in this section of the [Contributors Docs](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=sign-in-with-a-local-user).

---

> Anyway, what do you think?

If you want to make the change, and open a PR, I think that makes sense. We will QA it, and, if anyone notices the change breaking something else, then we can work from there. Thanks, for digging deeper into this.

**Comment by alirezaghey** [comment]
Thanks!
Will send a PR, tomorrow!
