### ISSUE TITLE
Solution to wrong challenges getting accepted

### ISSUE THREAD

**Issue by Sukriti-sood** [freeCodeCamp/freeCodeCamp#42694]
**Affected page**
Projects accepting the solution link of of challenge (repl) are accepting the solution of another challenge they are not checking the challenge solution with challenge statement and this thing is easing the process of claiming certification , one can easily paste the link of different challenge and will complete all projrcts and will claim cerification.

**Expected behavior**
Challenges (Projects) should accept the solution link of correct challenge ,

**Comment by ShaunSHamilton** [comment]
Hello there. Thank you, for taking the time to open this.

This is expected behaviour. Some projects do not have all of their tests written (https://github.com/freeCodeCamp/freeCodeCamp/issues/41323), and others do not have any tests. Anyone completing the curriculum is expected to abide by the _Academic Honesty Policy_ , and, if any Camper is found to be in violation of the policy, their certificate(s) will be revoked.

All projects are provided with a method for Campers to test their own work - either through the test-suite, or included assertion scripts.

As such, I am going to close this issue. Happy coding 🙂
