### ISSUE TITLE
[BUG] Throws error when using `background-image` instead of `background` (Learn Applied Visual Design - Add Background Image)

### ISSUE THREAD

**Issue by billimarie** [freeCodeCamp/freeCodeCamp#42738]
**Affected page**
[Learn Applied Visual Design: Create Texture by Adding a Subtle Pattern as a Background Image](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image)

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
<style>
  body {
    background-image: url('https://cdn-media-1.freecodecamp.org/imgr/MJAkxbh.png');
  }
</style>
```

**Expected behavior**
Both `background` and `background-image` should be accepted as correct answers.

**System (please complete the following information):**
 - Device: Laptop / Tablet
 - OS: Both iOS and Windows 10
 - Browser: Firefox

**Additional context**
Reporting this as the ability to accept multiple right answers was apparent with the `margin` and `padding` lessons (example: accepted both clockwise notation and -top, -right, -bottom, -left declarations). The same should be done with a `background` vs `background-image` issue.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here is the file that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image.md

The fix would be to add an optional `-image` part in the regex patter, like this
```js
assert(
  code.match(
    /background(-image)?:\s*?url\(\s*("|'|)https:\/\/cdn-media-1\.freecodecamp\.org\/imgr\/MJAkxbh\.png\1\s*\)/gi
  )
);
```

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ajl223** [comment]
Created a pull request for this @ #42738, hopefully I am doing this right.

**Comment by billimarie** [comment]
@ajl223 Works like a charm.
