### ISSUE TITLE
fcc_demographic_data _analyzer error

### ISSUE THREAD

**Issue by lavish2801** [freeCodeCamp/freeCodeCamp#42904]
Hello Everyone,
Trying to learn from free code camp data analyst course.
There is an error in my code for #Demographic_data_analyzer .. it will be a pleasure if someone can resolve this issue. try to run .. link is below 
https://replit.com/@LavishSinghal/boilerplate-demographic-data-analyzer-1#demographic_data_analyzer.py 
Thank You

_Originally posted by @lavish2801 in https://github.com/freeCodeCamp/CurriculumExpansion/issues/237#issuecomment-881583297_

**Comment by gikf** [comment]
Thank you for opening this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
