### ISSUE TITLE
https://www.freecodecamp.org/learn/information-security/

### ISSUE THREAD

**Issue by Hamzaobi** [freeCodeCamp/freeCodeCamp#42933]
**Affected page**
Add a link to the coding challenge with the problem.

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```




```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
