### ISSUE TITLE
Unclear requirement on microservices/apis timestamp project

### ISSUE THREAD

**Issue by DanCouper** [freeCodeCamp/freeCodeCamp#43049]
## Affected page

Challenge on learn:

https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

Challenge .md:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.md

## Your code

n/a

## Expected behavior

n/a

## Screenshots

<img width="776" alt="Screenshot 2021-07-28 at 14 42 05" src="https://user-images.githubusercontent.com/573694/127333102-b741c8ec-b3c8-4a2a-a8d7-706bca5c5554.png">

## System

n/a

## Additional context

Minor, but this doesn't really imply that the thing the test is looking for is an ability for the API to parse the literal string `"05 October 2011"`. If a camper goes to look for what a valid date string is, they are not going to find that without some digging because all documentation quite clearly states that that input is non-standard (given standard input would be the compact version of an ISO-compliant date, like `"2011-10-05"`, and even that is likely to cause inconsistent behaviour due to no timezone). I've just been trying to help someone on the forum who was having an issue with this, and I just assumed that the ISO string was what was expected, and it isn't. Plus, just to add to the confusion, the tested string is one of the multiple possible non-standard date formats (could be `"05 Oct 2011"`, `"Oct 5 2011"`, `"05 October 2011"`, `"OCT, 5, 2011"` and so on).

afaics a few options, I would have made a PR but not sure what's the best:

- wording of the test was to be amended to just say
  > A request to `/api/05 October 2011` should return `{ unix: 1319500800000, utc: "Tue, 25 Oct 2011 00:00:00 GMT" }`
- test changed to test against the standard compact ISO format
    ```
    (getUserInput) =>
        $.get(getUserInput('url') + '/api/2011-10-05').then(
    ```
- one or more additional tests added to cover a few more valid date strings.

**Comment by ShaunSHamilton** [comment]
Hey Dan,

I feel like I am missing some of the context for what the issue is. Would you mind sharing the forum thread link?

I would propose: The intent behind the test is:
- Not provide the actual used date (input), to prevent a Camper from feeling the need to hard-code
- As stated, not test every acceptable case, but expect the Camper to use the built in Date object API, and accept a common date format.

All of the "non-standard" date formats you gave as an example conform to the [spec](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.parse). So, whilst not ideal, JavaScript can handle them - that is, the only _standard_ date format is that returned by `Date.parse`.

**Comment by connersmartin** [comment]
I think the problem might be that the test is specifically looking for `00:00:00 GMT`  where `toUTCString()` uses the user time zone. So in PST I was getting:
` 05 October 2011
{"unix":1317798000000,"utc":"Wed, 05 Oct 2011 07:00:00 GMT"}`
so it didn't pass until I added `dateVar.setUTCHours(0)`
and got
`05 October 2011
{"unix":1317772800000,"utc":"Wed, 05 Oct 2011 00:00:00 GMT"}`

**Comment by nhcarrigan** [comment]
I feel like the purpose of this test is really to suggest to the camper that using `new Date(req.params.date)` is the ideal approach?
