### ISSUE TITLE
given wrong value to "n" js aAlgorithms

### ISSUE THREAD

**Issue by recarcoder** [freeCodeCamp/freeCodeCamp#43266]
<b>please change the value of "n" so the algorithm works</b>
<img src="https://raw.githubusercontent.com/recarcoder/imgweb/main/report.jpeg">
<h2>link to that page:https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/drop-it </h2>

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
