### ISSUE TITLE
Eu

### ISSUE THREAD

**Issue by Wol7** [freeCodeCamp/freeCodeCamp#43273]
## Your code

```




```

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you are looking for help with a challenge, please open a topic on the [forum](https://forum.freecodecamp.org/).

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
