### ISSUE TITLE
can't get the right time by new Date().toString() or new Date().tolocaleString()

### ISSUE THREAD

**Issue by necessityOVO** [freeCodeCamp/freeCodeCamp#43295]
## Affected page

the challenge says using `new Date().toString()` to get current time.

![image](https://user-images.githubusercontent.com/60960561/130748405-7d2c980b-911b-4122-808b-00731e5e362c.png)
[challenge link](https://chinese.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/chain-middleware-to-create-a-time-server)

but the time late for 8 hours;

![image](https://user-images.githubusercontent.com/60960561/130748256-ac4d11cf-623d-42f0-99cb-306a8c9d4161.png)

[app link](https://replit.com/@necessityOVO/boilerplate-express#myApp.js)
## Your code

```
var express = require('express');
var app = express();
const bodyParser = require("body-parser");

app.use(express.static(__dirname + "/"))
app.use(bodyParser.urlencoded({ extended: false }))


// app.get("/json", (req, res) => {
//   // console.log(process.env)
//   res.json({ "message": process.env.MESSAGE_STYLE == "uppercase" ? "Hello json".toUpperCase() : "Hello json" })
// })

app.get('/now', function (req, res, next) {
  // req.time = new Date('2021-08-25T14:44:00');
  // req.time = new Date().toString();
  req.time = new Date().toLocaleString();
  console.log(req.time);
  next();
}, function (req, res) {
  res.json({ "time": req.time });
})

console.log(new Date().toLocaleString())
console.log(new Date().toString())

module.exports = app;
```

## System

- Device: MacBook Pro
- OS:  macOS Big Sur 11.5
- Browser: chrome
- Version: 92.0.4515.159

**Comment by ieahleen** [comment]
IThank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
