### ISSUE TITLE
Unnecessary pair of comments causing confusion on solving a challenge

### ISSUE THREAD

**Issue by DanielRosa74** [freeCodeCamp/freeCodeCamp#43331]
On the Front-end > React > Create a Controlled Input challenge, lines 7 and 9, there is a pair of "// Change code below/above this line" comments. They are, however, unnecessary to solve the challenge, produce an error if we try to insert anything within and lead the user to think they need to insert code there.

https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-input

## Expected behavior

 In order to pass the test, the user has to insert the handleChange function within the second pair of comment lines and the input tag with the bind within the third pair

## Screenshots
Initial code with comment lines to remove highlighted
![image](https://user-images.githubusercontent.com/58576743/131205860-2b1e033e-db8c-4ab0-8cd8-afc432f3b3ce.png)

Challenge solved without the need of inserting anything within the first comment line pair
![image](https://user-images.githubusercontent.com/58576743/131205966-4b6e31de-dd2d-41fe-b428-33dc00629189.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 92

**Comment by ieahleen** [comment]
the first pair of comments is to bind `handleChange` to `this`, they are not unnecessary

**Comment by anshul2807** [comment]
> the first pair of comments is to bind `handleChange` to `this`, they are not unnecessary

But what is the need to have a handleChange function...We can do without that...
![Screenshot (52)](https://user-images.githubusercontent.com/56274258/131208441-1bd44536-3127-4f4d-876c-00e4913597b2.png)

**Comment by DanielRosa74** [comment]
@ieahleen , if you take a look at the second screenshot, by adding handleChange after the closing of the constructor (thus, within the second comment pair) and the input within the third pair, the challenge is solved. What is missing on the first comment? If there is anything missing, then we'd better check the Get a Hint part, as it does not mention anything related to what to insert there (between lines 7 and 9). The user can do the binding in the input.

**Comment by ieahleen** [comment]
you should write
`this.handleChange = this.handleChange.bind(this)` in the first set of comments
the definition of handle change in the second set of comments
and `onChange={this.handleChange}` in the element

**Comment by ieahleen** [comment]
> But what is the need to have a `handleChange` function...We can do without that...

it's more readable, and abstraction of components is the point of React

---

Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
