### ISSUE TITLE
Prevent Object Mutation with Object.freeze: Conflicting info

### ISSUE THREAD

**Issue by amberream** [freeCodeCamp/freeCodeCamp#43330]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/prevent-object-mutation

## Expected behavior

At the top, the challenge says, " Any attempt at changing the object will be rejected without an error."  A few lines later it says, "The obj.review and obj.newProp assignments will result in errors".

This seems to be conflicting information - will there be an error or not?  Maybe the 2nd part should say "The obj.review and obj.newProp assignments will be rejected".

## Screenshots

![image](https://user-images.githubusercontent.com/1459928/131202368-b509f7f1-e27a-4f31-83be-690f612eec57.png)

**Comment by amberream** [comment]
Oddly, when I run the tests I can see an error in the log:
[TypeError: Cannot assign to read only property 'PI' of object '#<Object>']

But when I run the same code in jsFiddle there is no error in the console.

**Comment by nhcarrigan** [comment]
I do agree that some clarification here would be beneficial.

Possibly changing that first line to `Any attempt at changing the object will be rejected, with an error thrown if the script is running in strict mode.

And the second line being `The obj.review and obj.newProp assignments will result in errors, because our editor runs in strict mode by default, and the console will...`

Thoughts?

**Comment by Sembauke** [comment]
That seems like a good solution Nich, I'll put a help wanted label on it!
