### ISSUE TITLE
Incorrect test goal - "Only use jQuery to add these classes to the element."

### ISSUE THREAD

**Issue by andideve** [freeCodeCamp/freeCodeCamp#43381]
Challenge Waypoint: [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.org/learn/front-end-development-libraries/jquery/target-a-specific-child-of-an-element-using-jquery)

The waypoint works correctly, however one of the test goals is You should only use jQuery to add these classes to the element.

```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $(".well .target:nth-child(2)")
      .addClass("animated bounce");
  });
</script>

<!-- Only change code above this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by ieahleen** [comment]
Can you add more details on what the issue is here?

**Comment by andideve** [comment]
There my code is working correctly, i am using jquery to add the classes into the element, but after testing it's wrong

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
