### ISSUE TITLE
Sort an array alphabetically using the sort Method - need to specify the array should be returned from the function

### ISSUE THREAD

**Issue by amberream** [freeCodeCamp/freeCodeCamp#43417]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method

## Your code

```
function alphabeticalOrder(arr) {
  // Only change code below this line
  arr.sort((a,b) => a === b ? 0 : a < b ? -1 : 1);

  // Only change code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);
```

## Expected behavior

The instructions on this page say, "Use the sort method in the alphabeticalOrder function to sort the elements of arr in alphabetical order."  Since sort happens in place, I didn't realize I need to return the value to pass the challenge, I kept thinking there was something wrong with my code.  Maybe just adding a line "return arr;" in the template code would make this more clear, or updating the instructions to specify the array needs to be returned.  Would be good to mention that sorting happens in place too, I only knew because I happened to look at the Mozilla documentation.

**Comment by ieahleen** [comment]
the tests say "should return", I'm not sure how much this would need to be changed, but yes, it would be more user friendly to make it more clear that the function should return the expected result

I don't know what would be the best way tho

**Comment by gikf** [comment]
>The function should return the sorted array.

Maybe something like this, added to the instructions?

**Comment by ieahleen** [comment]
That would work, let's go with it!

---

Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. ...
2. ...
3. ...

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by abhinav-raman** [comment]
Is this issue fixed? I am a first-timer and interested in contributing to this issue.

**Comment by ieahleen** [comment]
@abhinav-raman there is already an open PR targeting this issue
