### ISSUE TITLE
Legacy Full Stack Certification "Issued" Date is incorrect

### ISSUE THREAD

**Issue by brimarq** [freeCodeCamp/freeCodeCamp#43439]
**Describe the bug**
Yesterday, after completing my [Scientific Computing with Python certification](https://www.freecodecamp.org/certification/brimarq/scientific-computing-with-python-v7), I decided to revisit the links for my previously completed certs to verify that they were all still accessible. All seem to be there and in order except for my
[[Legacy] Full Stack Certification](https://www.freecodecamp.org/certification/brimarq/full-stack), which now shares the same "Issued" date as the python cert I just completed instead of the originally issued date of March 3, 2020.

**To Reproduce**
Compare date on my live Legacy Full Stack Certification with the screenshot below. 

**Expected behavior**
Certificate should keep the actual completion date. 

**Screenshots**
Here's a screenshot of my original [Legacy] Full Stack certification, taken on the actual date of completion:           
![fcc_full_stack_cert](https://user-images.githubusercontent.com/11450156/132810669-d733866f-cc0f-4e1d-b8bd-9da503a08c8c.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser: Firefox v91.0.2, Chrome v93.0.4577.63, Safari v14.1.2

**Additional context**
Related issue?? : #18128

**Comment by jahantaila** [comment]
I have the same problem, i'm using widows 10

**Comment by moT01** [comment]
So, I think the issue here is that the full stack cert was claimed previously, then the python was released, you two then finished the python certs which was the last cert - and the full stack data was updated in the database. The api should check if the full stack cert has been previously claimed before updating that date.

**Comment by 7harshit20** [comment]
I would love to solve this as my first open-source contribution. I explored the certificate.js file, but I got confused in the below given part of code: 

// if fullcert is not found, return the latest completedDate
        if (certType === 'isFullStackCert' && !certChallenge) {
          completedDate = getFallbackFrontEndDate(
            completedChallenges,
            completedDate
          );
        }
 export function getFallbackFrontEndDate(completedChallenges, completedDate) {
  var chalIds = [...Object.values(certTypeIdMap), oldDataVizId];

  const latestCertDate = completedChallenges
    .filter(chal => chalIds.includes(chal.id))
    .sort((a, b) => b.completedDate - a.completedDate)[0].completedDate;
     return latestCertDate ? latestCertDate : completedDate;
}


Is it the part that needs to be modified?

**Comment by moT01** [comment]
Thanks for your interest @7harshit20 - I'm not positive that what I described is the problem. It's what I think is happening, and it might be quite difficult to reproduce. That does look like the area of the code where that check would need to happen. If you want to see if you can fix it, go for it 👍 I'm not sure how difficult it will be to fix it - or if the problem is even in the codebase. There's a chance it's something completely different, like something with their accounts or something. I might recommend seeing if you can reproduce the issue locally.

If you have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

**Comment by AdamHumble** [comment]
Hello, may I please work on this issue?

**Comment by ieahleen** [comment]
@jahantaila you can open a PR to fix this, if you think you know how

**Comment by AndreiD049** [comment]
Is there a way to test certificate claiming faster on dev environment?

**Comment by ShaunSHamilton** [comment]
@AndreiD049 You can change the `is...Cert` fields of the fully certified user to `false`, then seed the fully certified user:
```bash
npm run seed:certified-user
```

The fully certified user data is in: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/scripts/seed/certifiedUserData.js
