### ISSUE TITLE
Lost all the progress

### ISSUE THREAD

**Issue by vytautasjar** [freeCodeCamp/freeCodeCamp#43485]
## Affected page

https://www.freecodecamp.org/learn

Hi, I've completed "Basic HTML and HTML5" and "Basic CSS" while signed in with my GitHub account, but when I open the curriculum page all the progress seems to be gone.

**Comment by ieahleen** [comment]
thank you for your report, we are trying to find the issue, and we are collecting all the reports together in this forum post so that maybe we can find the common factor: https://forum.freecodecamp.org/t/collation-completed-and-submitted-challenges-not-recorded/474250

**Comment by Sembauke** [comment]
Thank you for reporting, you can receive further support on the forum as linked above.

I wish you a wonderful day!

**Comment by moT01** [comment]
I feel like it might not be a bad idea to have an issue here to track this. I didn't know this was happening. Do we have any idea what the problem is?

**Comment by ShaunSHamilton** [comment]
@moT01 So far, nothing has stood out in the thread of what could be a commonality.

My bestest guess would be some sort of discontinuity between the Camper and the `update-challenge-complete` logic. Potentially caused by internet disconnects, or when we deploy new builds - but I have no basis for this.

I have been completely unable to reproduce any of these kinds of issues both with my production account, and locally.

**Comment by scissorsneedfoodtoo** [comment]
If the reports are anything like the emails we receive in the support inbox, a lot of the time the issue has something to do with Safari and/or an extension, usually an ad blocker.

There have also been a few cases where a VPN with a built-in ad blocker is the culprit. In cases where an ad blocker is involved, once the freecodecamp.org domain is allowed, the issue is usually resolved.

Also, some people were able to resolve the issue by disabling Safari's content blocking setting for freecodecamp.org by following these steps: https://www.macworld.com/article/3535209/how-to-disable-content-blockers-on-a-per-site-basis-in-macos-safari.html

**Comment by ieahleen** [comment]
I will add Help Wanted to this issu, to help investigate the issue

**Comment by Sembauke** [comment]
So I suggest we close this issue as there is no response from the original poster and no new campers have seemed to have the same issue.

**Comment by ieahleen** [comment]
@Sembauke on the forum there have been various people with the issue still

**Comment by moT01** [comment]
We could try and find someone who can reproduce this consistently. Maybe see if they're willing to pair up and we can try to find where the info is getting lost or not saved. Check the network requests - see if they going through as expected.

I thought it might have to do with user accounts - maybe they signed up with one method, and then used another and we have a duplicate email in the database or something. We could look closer at an account or two in the database and see if something looks off. We may need to ask and get permission from the user for that - not sure.

Glancing through the forum post, Big Sur and other Apple products show up a lot  - but not exclusively. Makes it hard to believe that it's the OS or Browser alone - but I can't be certain. Maybe it's a small group of OS's or some combination of OS and browser.
