### ISSUE TITLE
Need to remove videos from HTML challenges using old image src url

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#43624]
For the HTML and CSS challenges, the src url for the image tag was recently changed. 

This is the old url
`src="https://bit.ly/fcc-relaxing-cat."`

This is the new one
`https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg`

We have campers using the old URL because they watched the video in the Get Help section.
For example,
[Forum post of user copying incorrect code from video](https://forum.freecodecamp.org/t/everything-is-correct-i-literally-copied-and-pasted-the-completed-code-from-the-how-to-video-and-it-still-wont-accept-it/479728)

The videos should be removed from these challenges:
[Add Images to Your Website](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website)
[Size Your Images](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images)

Thanks!

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by deepto98** [comment]
Hi, I'd like to work on this issue, can you please assign this to me?

**Comment by jdwilkin4** [comment]
Hi @deepto98 ! 

This issue has been marked with the first timer contributor label. 

First timers only label are open for anyone doing contributions for first time to freeCodeCamp. You do not need permission to work on these.
Make sure to read the material that @gikf posted on how to contribute.

**Comment by deepto98** [comment]
@jdwilkin4 Sure, thank you. I'll go through this.
