### ISSUE TITLE
Chunky Monkey won't run test

### ISSUE THREAD

**Issue by jacob4** [FreeCodeCamp/FreeCodeCamp#4391]
Hi, I'm getting an error when I try to run my code. It won't even output anything...looks like it's crashing or something. See attached.
![capture](https://cloud.githubusercontent.com/assets/10079209/11130663/74e492b0-8943-11e5-9568-72e1a4b459b1.JPG)

**Comment by ltegman** [comment]
You have an infinite loop in your code because `i + size` doesn't actually increment the value of `i`. You'd need to change that to `i += size` for it to actually modify the value of `i`.

In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) to ask for help before filing a bug.

Thanks and happy coding!
