### ISSUE TITLE
Tribute page: Difference between project’s stated requirements in own page and in widget on codepen

### ISSUE THREAD

**Issue by kalimann** [freeCodeCamp/freeCodeCamp#44068]
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

## Expected behavior

On the tribute page project’s page, it states:
>User Story `#3`: I should see a div element with a corresponding id="`img-div`"

while in the tests widget on the codepen of the tribute page, it states: 

>I should see either a `<figure>` or `<div>` element with corresponding id=“`img-div`”.

So a figure element is accepted through the widget, but not officially on the project page. Surely this must be a mistake.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

Here is more context: https://github.com/freeCodeCamp/testable-projects-fcc/pull/781

@lasjorg This is a stretch, but do you remember why the `/learn` user-stories remained the same?

**Comment by lasjorg** [comment]
@ShaunSHamilton I don't remember, but I don't think there was a reason for it. It's likely just an oversight.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the file that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by AishTron7** [comment]
Hi @ieahleen  Thanks for the clear instructions. I'm a first time contributor and I've submitted a pull request #44076 Please let me know if there's anything else that I need to do in order to solve this issue. :)
