### ISSUE TITLE
Profile Settings issue on iPads

### ISSUE THREAD

**Issue by MR-Kurl** [freeCodeCamp/freeCodeCamp#44126]
Using FCC with students who only have school district iPads, ios 14.6. I want them to make their Name and Points public, but any attempt to go to settings and change them from Private fails on both Safari and Chrome on the tablets, the private button sticks on, and both buttons stay highlighted and stay selected, and it won’t save any settings changes and leaves their profiles private. Any suggestions. Thanks - Aaron
## Affected page

https://www.freecodecamp.org/settings

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by cbenjamin2009** [comment]
I just tested this by browsing to freecodecamp.org/settings on my iPad air 2 running iOS 14.8 and was able to toggle between Private and Public without issue. This sounds like a possible Network related issue that School District IT department may be able to check firewall rules and settings?  It does appear that both buttons are pressed and highlighted for a moment and then the page updates with a green banner at the top saying my settings were updated successfully.

**Comment by Sembauke** [comment]
Yes this may occur due to a slow network connection. 

There should not be anything with your Ipads this issue has been known for a long time:
https://github.com/freeCodeCamp/freeCodeCamp/issues/40764

Does this seem like familiar behavior?

If it is, try changing the settings slowly until the "settings changes successfully" message pops up.

If it is not, please provide some video or picture to us.

**Comment by MR-Kurl** [comment]
Thanks. I will ask my IT department about possible firewall rules and settings.
