### ISSUE TITLE
Waypoint: Trigger Click Events with jQuery

### ISSUE THREAD

**Issue by guylemon** [FreeCodeCamp/FreeCodeCamp#4418]
Top code example does not pass the waypoint, but performs the same function as the long form method (bottom).
```javascript
$('#getMessage').click(function(){
  alert('foo');
});
```
vs

```javascript
$('#getMessage').on('click', function(){
   alert('foo');
});
```

**Comment by SaintPeter** [comment]
The `.on('click',` call is the recommended method, since it is [more efficient](http://stackoverflow.com/a/11878976) when applied to multiple elements.  We specifically call it out in the description, too, so there is no question as to what should be used.

We consider `on..click` to be a "best practice" for jQuery.

Thank you and happy coding!
