### ISSUE TITLE
Add instructions to real time multiplayer game

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#44192]
Edit from @moT01: See [comment below](https://github.com/freeCodeCamp/freeCodeCamp/issues/44192#issuecomment-1190403770) for the new focus of this issue.

Related to #39721

The Secure Real Time Multiplayer game is missing user stories
reported here: https://forum.freecodecamp.org/t/where-are-the-user-stories/485714

**Comment by ShaunSHamilton** [comment]
I might be missing something, but that is like most of the other backend projects in that the user stories are in the test text:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/51722130/142200264-2b6e1fc4-c274-492d-bea7-ed32bd459837.png">


That is, it looks like nothing is missing?

**Comment by raisedadead** [comment]
The user stories are made available on the challenge page, instead of the readme. That readme in the screenshot in the forum itself is misleading. It should be more verbose about where to find the instructions from. 

Does anyone want to propose a template and take up updating the boilerplates on GitHub eventually?

**Comment by ieahleen** [comment]
I checked other backend projects, there is at least a brief description explaining what the project is about instead of just giving the link to the boilerplate

**Comment by raisedadead** [comment]
I understand. We need to simply standardize this README in that case.

**Comment by raisedadead** [comment]
> Are we intending to clarify that the instructions are found at that link?

Yes. And standardize all the boilerplate readme files at the same time. BTW, we should create a GitHub template repo for this.

**Comment by nhcarrigan** [comment]
Awesome, thanks for clarifying. This issue has been sitting here for a bit, so I'll take care of it today.

**Comment by nhcarrigan** [comment]
Okay with that above PR merged, I've used the same format to apply to the rest of the boilerplate projects. PRs are open and ready.

**Comment by moT01** [comment]
This issue is changed to focus on adding instructions. The [multiplayer game](https://www.freecodecamp.org/learn/information-security/information-security-projects/secure-real-time-multiplayer-game) doesn't really have any instructions so users don't know what to do. The other JS projects in this area do - see the [stock price checker](https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker) and the [anonymous message board.](https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board)
