### ISSUE TITLE
Mistake in the description of Problem 29: Distinct powers

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44242]
## Affected page

Coding Interview Prep > Project Euler > Problem 29: Distinct powers
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-29-distinct-powers

## Expected behavior

The description says `ab` but I think it should be `a^b`

## Screenshots

![project_euler_29_issue](https://user-images.githubusercontent.com/25644062/142906868-fca9194e-fe77-4895-b198-4900f4e3cf61.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.45

## Additional context

Originally reported in a comment on Crowdin duing translation.
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/21122/en-ja/132?filter=basic&value=3#q=623850

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-29-distinct-powers.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by MxDui** [comment]
Hi , I would like to work in this issue.

**Comment by gikf** [comment]
Hey @MxDui 

Issues are typically not assigned to specific person, other than long-time contributors. You can read more about this at https://contribute.freecodecamp.org/#/FAQ?id=how-can-i-get-an-issue-assigned-to-me. 

Issues labelled with `help wanted` or `first timers only` are open for contributions for all.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by pariksh1th** [comment]
I did my first [ contrubution](https://github.com/freeCodeCamp/freeCodeCamp/pull/44248) 😆

**Comment by Pavithradevadiga** [comment]
Is this issue closed or can I still make my contribution.I am a first timer
