### ISSUE TITLE
Broken link on Scientific Computing with Python project pages

### ISSUE THREAD

**Issue by joanmdavis** [freeCodeCamp/freeCodeCamp#44293]
## Affected pages
The link to the Learn Python Video Course is broken on these  pages:

* [Arithmetic Formatter](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter)
* [Time Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/time-calculator)
* [Budget App](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/budget-app)
* [Polygon Area Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/polygon-area-calculator)
* [Probability Calculator](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/probability-calculator)

## Your code

```




```

## Expected behavior

When a user clicks on the link "Learn Python Video Course", the home page for the course should be displayed. 

## Screenshots

<img width="675" alt="Screen Shot 2021-11-26 at 8 30 44 AM" src="https://user-images.githubusercontent.com/54745929/143588516-8802808a-775d-4847-8f62-ffc017e357a8.png">

## System
- Device: laptop
- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Version: 96.0.4664.55

**Comment by gourcool** [comment]
It is working fine you can check now

**Comment by joanmdavis** [comment]
I checked again and still get a 404 error for the Learn Python Video Course link on all the project pages.

**Comment by shenlong3010** [comment]
None of them are broken anymore

**Comment by joanmdavis** [comment]
I tried the links again and still got 404.  I might not have been clear in my initial issue report. These are the steps I take to reproduce the error:

1. Go to the [Arithmetic Formatter project](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter) page.
2. Click the link [Learn Python Video Course ](https://www.freecodecamp.org/news/learn-python-video-course/) (10 hours).
A 404 page is displayed.

I've cleared my cache and tried different browsers, but I get the same result. If the Learn Python Video Course vi no longer exists, consider removing the link from the project pages.

**Comment by nickmccullum** [comment]
I am getting this problem too.

**Comment by ShaunSHamilton** [comment]
@beaucarnes I am not actually sure which resource this is/was supposed to link to. Do you have any idea what happened here?

**Comment by beaucarnes** [comment]
The missing link is for an article. I think this is the new link for the article: https://freecodecamp.org/news/learn-python-basics-in-depth-video-course/

Someone must have changed the link URL to get better SEO but didn't realize it was in the curriculum.

My suggestions is that we remove that link completely. I think we should remove the following text from all of the challenges linked above:
`We are still developing the interactive instructional part of the Python curriculum. For now, here are some videos on the freeCodeCamp.org YouTube channel that will teach you everything you need to know to complete this project:

Python for Everybody Video Course (14 hours)

Learn Python Video Course (10 hours)`

I think we included that text BEFORE we actually added those very video courses into the curriculum. There is no reason to have that text now since students following the curriculum will already have seen those courses as part of the curriculum. 

Do others agree with this?

**Comment by ShaunSHamilton** [comment]
> Do others agree with this?

Yes, I am happy to have that text removed. I cannot imagine it is used/needed much by Campers who have reached the projects page.

**Comment by joanmdavis** [comment]
@raquelocasio The [Curriculum File Structure](https://contribute.freecodecamp.org/#/curriculum-file-structure) page should help.
