### ISSUE TITLE
Missing whitespace after a MathJax tag in "Problem 331: Cross flips"

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44303]
I think we are missing a whitespace after the MathJax tag `$N × N$` in the following sentence.
```
Let $C_N$ be the following configuration of a board with $N × N$disks: A disk at ($x$, $y$) satisfying $N - 1 \le \sqrt{x^2 + y^2} \lt N$, shows its black side; otherwise, it shows its white side.
```
Although it is rendered properly on the curriculum site, it is causing unnecessary QA warning on Crowdin translation platform. (See the screenshot below)

## Affected page
Coding Interview Prep > Project Euler > Problem 331: Cross flips
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-331-cross-flips

## Expected behavior
Add a space between `$N × N$` and `disks`
```
Let $C_N$ be the following configuration of a board with $N × N$ disks: A disk at ($x$, $y$) satisfying $N - 1 \le \sqrt{x^2 + y^2} \lt N$, shows its black side; otherwise, it shows its white side.
```

## Screenshots
![problem331](https://user-images.githubusercontent.com/25644062/143719333-96caf89c-e08d-452c-8784-ffc0b5bef5f6.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.45

## Additional context

Originally reported in a comment on Crowdin
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/23456/en-ja/132?filter=basic&value=17#q=760983

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-331-cross-flips.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by sstonaker** [comment]
I have submitted a pull request in an attempt to address this issue.
