### ISSUE TITLE
Toggling night mode through the hamburger menu is silent 

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#44330]
## Affected page

All pages.

## To reproduce

1. Go to /settings
2. Toggle campfire mode on
3. Toggle night mode via the button (not the menu)
4. Hear pleasing guitar sounds
5. Toggle night mode via the hamburger menu
6. Hear the silence of the void

## Expected behavior

I expected to hear pleasing guitar sounds in both cases.

**Comment by nhcarrigan** [comment]
So in the prototype I had to rip this feature out, presumably because of that whole saga mess as well (it was causing issues where sound stopped playing if the camper clicked that toggle).

Wouldn't be too difficult to add back in. I propose we block this until #44320 is landed, and then open it up for `help wanted`.

**Comment by ShaunSHamilton** [comment]
Provided the current bug in #44320 is resolvable, it should close this.
