### ISSUE TITLE
Cant use String as a constructor. & My Challenges are all reset automatically. 

### ISSUE THREAD

**Issue by Roy1990** [FreeCodeCamp/FreeCodeCamp#4446]
Challenge [Bonfire: Repeat a string repeat a string](http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function repeat(str, num) {
  // repeat after me
  return str;
}

repeat("abc", 3);


.  

```
![empty-paramiters-copy-copy](https://cloud.githubusercontent.com/assets/15723369/11167502/ef961496-8b89-11e5-8042-fe0e368ac332.png)

I done know where is the code that I have written, I usually log on to freeCodeCamp  from my office or use my PC at home, but now when i open all the challenges I find its reset. Any how i had a screenShot of this issue which i have attached.

The problem which I face is when I use the Global String object i.e. var str1=new String();
for this particular challenge It does not select the output as correct even though I get the expected output i.e, "".

**Comment by SaintPeter** [comment]
You are correct, you can't use `new String` to declare a blank string, because the string constructor doesn't generate an empty string, it generates a String object.
![image](https://cloud.githubusercontent.com/assets/553494/11168007/31709034-8b31-11e5-9c53-9bba5bf8c4b9.png)
[More Information Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Distinction_between_string_primitives_and_String_objects)

Additionally, if you pay attention to the little warning symbol next to the code in the code editor, it tells you not to use String as a constructor:
![image](https://cloud.githubusercontent.com/assets/553494/11168021/fa4b0110-8b31-11e5-9aec-27ef3c2dfa44.png)

Closing as this is not an issue with the site.

Happy Coding!
