### ISSUE TITLE
Exercise Tracker - Issue with one test case due to timezones

### ISSUE THREAD

**Issue by chapuawe2** [freeCodeCamp/freeCodeCamp#44475]
## Affected page

[Exercise Tracker Project](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker)

## Your code && Screenshots

You can check it deeply in the forum post: [Forum Post](https://forum.freecodecamp.org/t/exercise-tracker-datestring-format/488362)

## Expected behavior

To pass all test cases

## System

- Device: Laptop
- OS: Windows 10
- Browser: Edge
- Version: 96

## Additional context

One of the test case says that when the date field is empty it should take the actual date, so while the replit server is in one country and I'm in another when in my country might be Friday at night in the replit server will be Saturday at morning. And that's a problem because the test case error only shows that the format is no the right format and doesn't gives you any hint, this was possibly only with me being in front of the computer trying to realize why it doesn't work

**Comment by chapuawe2** [comment]
I suggest to check in the client side with .toUTCString() and to modify the content of the requirements to encourage the user to implement .toUTCString() at the output of the server.

**Comment by nhcarrigan** [comment]
This has been a recurring issue for a while now, and something should probably be done with it. That being said, I'm not sure *what*.

We could just modify the test to be more forgiving, but IMHO we'd be missing out an a great opportunity to encourage campers to explore the Date API and understand things like timezones and UTC offsets.

**Comment by PaulPresident** [comment]
I made a post on the FCC forum about a similar issue and was directed to this ticket. I am honestly not very experienced with creating tests in Javascript, but I had a thought (again not sure how this would be implemented). Perhaps there is a way to test if `new Date.now()` has been called when a date is not provided in the exercise form.
Alternatively (I think this is what @nhcarrigan was getting when they mentioned making the tests more forgiving) the test could be written in such a way that if date is not provided then current date will be checked for with tolerance of 26 hours to encompass the furthest timezones on earth
In my opinion, having this tolerance is better than not checking for it at all which, having just completed this project, I was very confused why 6 of the tests were not passing. Turns out it was because I missed that part that said: "if date is not supplied then current date should be used".

**Comment by Nirajn2311** [comment]
Make the tests more forgiving by asking the user to send the timezone along with the date and fallback to the current test if not present.

**Comment by naomi-lgbt** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/63889819/182631191-06b583cf-dc5d-4ef9-9479-b94332c31b73.png">

We could potentially change the `datestring` instruction to `UTCstring`

**Comment by Hermione2408** [comment]
Can you tell what needs to be done and assign it to me?

**Comment by nayabatir1** [comment]
> <img alt="image" width="326" src="https://user-images.githubusercontent.com/63889819/182631191-06b583cf-dc5d-4ef9-9479-b94332c31b73.png">
> 
> We could potentially change the `datestring` instruction to `UTCstring`

Is this the proposed solution for this issue ?

**Comment by AdventureBear** [comment]
I agree this was a really frustrating experience for me, having to dig into forum posts to find the suggested fix.    The easiest correct would be to address the timezone offset in the instructions with the correct method, and ensure the test is also using the correct method.
