### ISSUE TITLE
Advanced Node and Express: Set up a Template Engine

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#44494]
It would be nice if the example code given in [the Gist](https://gist.github.com/camperbot/3515cd676ea4dfceab4e322f59a37791) followed the [express docs](http://expressjs.com/en/guide/using-template-engines.html) on how to set up the template engine.

I also think the challenge is pretty vague about how to do it. Shouldn't it be teaching how to do it using `app.set` for the views path like the docs shows it?

```
app.set('view engine', 'pug');
app.set('views', './views/pug');

app.route('/').get((req, res) => {
  res.render('index');
});
```

I can't remember when or if I ever did this section of the curriculum so I don't know if using that approach will work all the way through and I'll be honest I didn't check. I'm also not at all a user of template engines so there is that as well.

@ShaunSHamilton I think you are the one I should be pinging about this so 🔔

---
Edit: forum post that made me make this issue
https://forum.freecodecamp.org/t/how-to-set-up-a-template-engine/488662

**Comment by ShaunSHamilton** [comment]
Hey Lasse,

> I also think the challenge is pretty vague about how to do it.

I am obviously biased, but I think the description is quite explicit.

> Shouldn't it be teaching how to do it using app.set for the views path like the docs shows it?

🤷‍♂️ It _can_, but, ultimately, I see nothing incorrect about the way the lesson shows it.

---

To clarify what you think would help?:

- Change lesson to teach what `app.set('views')` does from an Express point of _view_ 😉 
- Change Gist (answer) to use `app.set('views')`, because it is mentioned in Express docs

**Comment by lasjorg** [comment]
> To clarify what you think would help?:

Both, I think it would be helpful if we followed the [express docs](https://expressjs.com/en/guide/using-template-engines.html) so that if people look up how to set the view path in the docs it matches. So teach `app.set` for setting the path and make the example reflect it has well.

I realize there are multiple ways of doing it but using `app.set` seems the most straightforward and as said would be in line with the docs.

**Comment by ShaunSHamilton** [comment]
This issue is open for contribution. The only thing that should be changed is this file:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/set-up-a-template-engine.md

**Desired Change**

1) Lesson content to teach:
a) More information about `app.set('views')` from an Express point of view
b) The expected code is `app.set('views', './views/pug')` - as required

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by naomi-lgbt** [comment]
Reviewed this in our issue triage meeting - this hasn't received any contributor interest, and apparently we've got a gist for each step in this section and most (if not all) would need updating with the changes.

Happy to reopen and re-evaluate if someone has more perspective on this. 💜
