### ISSUE TITLE
`basic-node-and-express/use-the--env-file` - unable to proceed as test case failing

### ISSUE THREAD

**Issue by iRachana06** [freeCodeCamp/freeCodeCamp#44555]
Even after completing test case , getting error message - The response of the endpoint /json should change according to the environment variable MESSAGE_STYLE

## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

## Your code

```js
var express = require('express');
var app = express();

const mySecret = process.env['MESSAGE_STYLE']
response= {"message": "Hello json"}
app.get("/json", function(req, res){
  if (mySecret === "uppercase"){
     res.json({message: "Hello json".toUpperCase()});
  }
  else
    res.json({message: "Hello json"} );
});

```

Env Variable is also set:
![image](https://user-images.githubusercontent.com/68515362/147121333-9439ea63-5489-4d8a-a3bd-159a8eed12bc.png)

## Expected behavior
Test case should pass

## Screenshots

This is the output created: 
![image](https://user-images.githubusercontent.com/68515362/147120553-1e9eaa60-156f-41bc-a5cd-155765dfecc1.png)

This is what I get after submitting task
![image](https://user-images.githubusercontent.com/68515362/147120760-2aac4bda-a047-4fd7-ac3c-2c1273bb3347.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

**Comment by gikf** [comment]
This passed for me, after moving `const mySecret = process.env['MESSAGE_STYLE']` into the callback function.

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by abuhafs1433** [comment]
process.env.MESSAGE_STYLE='uppercase';

app.get('/json', function(req, res){

if(process.env.MESSAGE_STYLE==='uppercase'){
  res.json({
  "message": "HELLO JSON"
})
} else {
    res.json({
  "message": "Hello json"
})
  };
});

**Comment by devbenja** [comment]
The order of imports influences this problem, you must first import the dotenv config:

require('dotenv').config()
let express = require('express');
let app = express();

app.get('/json', (req, res) => {

  let response = "Hello json";

  if (process.env.MESSAGE_STYLE === "uppercase") {
    response = response.toUpperCase();
  }

  res.json({ "message": response});

});
