### ISSUE TITLE
Page keeps freezing up on me

### ISSUE THREAD

**Issue by CaffeineQueen** [FreeCodeCamp/FreeCodeCamp#4456]
Challenge [Bonfire: Slasher Flick](http://www.freecodecamp.com/challenges/bonfire-slasher-flick) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function slasher(arr, howMany) {

  var final = [ ];
  
  for (var i = 0; i < arr.length; i += howMany)
    final.splice(i);
  
  var final2 = final.join();
  
  
  
  
  return [final2];
}

slasher([1, 2, 3], 2);

```

**Comment by SaintPeter** [comment]
You are creating an infinite loop, because `howMany` can be 0.

The second test case is:
`slasher([1, 2, 3], 0)`
Which means `howMany` is 0, which means your loop will never complete, since you've written `i += howMany`.

In the future, when you have a code problem, I encourage you to use our [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to ask for assistance.  There are many skilled and enthusiastic helpers who can easily identify problems such as these.
