### ISSUE TITLE
javascript lesson 102:

### ISSUE THREAD

**Issue by Alexanderdev478** [freeCodeCamp/freeCodeCamp#44622]
please there is an issue with that lesson,  i can't continue to the next challenge .. It seems there's a problem with it..

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
