### ISSUE TITLE
Suggestion: Update "How to set up FreeCodeCamp Locally" with instructions to see RWD beta

### ISSUE THREAD

**Issue by xoxoKaralee** [freeCodeCamp/freeCodeCamp#44642]
## Affected page
Currently, the instructions for setting up FreeCodeCamp locally has us copy `sample.env` to `.env` and suggesting not to change any keys. `sample.env` has `SHOW_NEW_CURRICULUM` defaulting to `false`. The `sample.env` and `.env` when using Gitpod also defaulted to `false`. From discussion in the Forums and the Contributor chat, I learned that in order to see the Responsive Web Design beta section, this value needs to be changed to `true` (once changed to true, I was able to see the section). I assume that this will be a problem for both GitPod and locally. 

Also- Since `.env` is included in `.gitignore`, this change will need to be done each time GitPod loads. 

[How to set up FreeCodeCamp Locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally)

## To reproduce

When you open a change in Gitpod, the `.env` file has  `SHOW_NEW_CURRICULUM` set to false. This makes it so that you cant see the RWD Beta while testing in the host unless you change the value to true. 

## Recommended fix, suggestions

I would like to propose that we add a tip or section that lets people know they will need to manually change `SHOW_NEW_CURRICULUM` value to `true` in order to see the Beta section. There is already a tip blurb [here](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=configuring-dependencies) that we could expand or add another under it. 
If it's decided that it's more important than a tip and should be it's own thing, I think Step 1 of Configuring Dependencies would be a good place to expand upon this. 
I'd also like to suggest Including more information on the nuances of using GitPod while working on things for FreeCodeCamp. GitPod is an option presented, but I personally couldnt find much about how to make use of it. This would be a great place to put information about needing to do fix this each time GitPod loads. 

Another option could be to change the `sample.env` and `.env` file to have the value default to `true`, but I dont know enough about what else that would effect. I thought it would be worth bringing up as an idea, just in case. 

## Screenshots

Left is with `.env` file that has the default value of `false`, and the missing RWD beta. right is the freecodecamp website where RWD beta should be. 
<img width="1512" alt="Screen Shot 2022-01-01 at 9 08 29 AM" src="https://user-images.githubusercontent.com/49349280/147859574-3f69ba83-26ab-4765-affa-4301f0ed4a65.png">

Changing `.env` file to `true` 
<img width="1120" alt="Screen Shot 2022-01-01 at 3 27 02 PM" src="https://user-images.githubusercontent.com/49349280/147860522-bee12964-e77c-4ed4-9d57-da66bddda3d9.png">

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

As mentioned in the [forum thread](https://forum.freecodecamp.org/t/using-gitpod-to-preview-changes-not-seeing-rwd-beta/490724/6), the main reasons to not include a note about this is:
a) This section is under development, and, as such, subject to rapid change - the guidelines could easily become outdated
b) Most of this development was being done internally by the curriculum team

>  ...Including more information on the nuances of using GitPod while working on things for FreeCodeCamp.

Sometimes we include nuanced information (see [WSL](https://contribute.freecodecamp.org/#/how-to-setup-wsl)). However, as freeCodeCamp does not maintain Gitpod, it would be an extra pain to keep updated, and prevent further confusion rather than the current recommended practice of _if you are using some other tool, we recommend reading their docs_

> Another option could be to change the sample.env and .env file to have the value default to true, but I dont know enough about what else that would effect. I thought it would be worth bringing up as an idea, just in case.

Thank you, for bringing it up. However, as you correctly surmised, the `sample.env` file is not supposed to be changed to suit a specific feature for testing. This could cause us to accidentally bring features under development into production - potentially breaking it.


Once this is out of Beta, working on the new curriculum will become a lot clearer.

I will leave this open for others to weigh in on, but hope this helps somewhat.

**Comment by xoxoKaralee** [comment]
I understand and appreciate you taking the time to discuss! It's my understanding that each curriculum will be going under revision and I assume, each have it's own beta period (where people will be able to raise issues and help make changes). 

I guess I'm not understanding how the beta shows up on the website, shows up here on github, but wont show up when running the test environment (as the screenshots in the forum thread showed) without changing that variable, unless this is a GitPod specific issue.

**Comment by moT01** [comment]
Looks like the [default for this variable](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/sample.env#L60) is now `true`, so the beta should be getting shown when running locally or on gitpod. I think that the problem in this issue won't arise anymore. I do think there's a potential need to describe more about the variables in the .env somewhere - what about adding comments in the sample.env...

```
# show/hide alpha curriculum (curriculum not on production anywhere)
SHOW_UPCOMING_CHANGES=false

# show/hide beta curriculum (curriculum on certain production builds)
SHOW_NEW_CURRICULUM=true
```

**Comment by moT01** [comment]
Closing, the default in the sample.env is now to show the new curriculum
