### ISSUE TITLE
RWD Beta: Nutrition label code typo

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44649]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-61

## Your code

```
<p>Vitamin D 2mcg <span class="right">10%</span></p>
```

## Expected behavior

The behavior is fine, it's a typo in the code you are supposed to use. The paragraph text of `mcg` I assume should be `mg`, an abbreviation for milligram. Since you are expected to enter the text given as part of the lesson, I can't fix that typo. If I do that the answer would always be wrong. That change has to also be done first in whatever code checks for a correct answer. Then I or someone else can fix the typo in the lesson text.

## Screenshots

![milligram](https://user-images.githubusercontent.com/66497948/147884431-87a35f49-aa5e-4b0a-b598-c629ba7078f4.PNG)

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

**Comment by gikf** [comment]
Thank you for reporting this issue.

As far as I'm aware that's microgram, for which mcg is one of the used abbreviation. Because of that I'm going to close this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by Kernix13** [comment]
Oh, I did not know that was an accepted abbreviation - yes, go ahead and close this.
