### ISSUE TITLE
Is code comment removal broken?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#44705]
Forum thread: https://forum.freecodecamp.org/t/anonymous-functions-right-solutions-doesnt-pass-the-test/491397

---

Another example, I would expect this code to pass if the comment was removed.

```
const FCC = "freeCodeCamp"; // Change this line
let fact = "is cool!"; // Change this line
fact = "is awesome!";
console.log(FCC, fact); // Change this line
// var test = 'test';
```

challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword

**Comment by ShaunSHamilton** [comment]
@lasjorg This appears to be an issue with the use of `getUserInput`:

https://github.com/freeCodeCamp/freeCodeCamp/blob/c242c6495dc5ad3dc5b64fe4a57df6700abee26c/client/src/client/frame-runner.ts#L122-L124

I will look into this now to confirm.

**Comment by ShaunSHamilton** [comment]
So, as I thought, the comments are not removed, if the test is of type `function`.

So, I am opening this as `help wanted`, because I have not investigated this enough to solve it myself.

**What needs fixing**

- We automatically remove comments for most challenges code, but this is not happening if the test is of the form `(getUserInput) => ...`

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Jagrutiti** [comment]
@ShaunSHamilton is this issue open to work?

**Comment by ShaunSHamilton** [comment]
@Jagrutiti Heya 👋 

Yes, any issue with the `help wanted` label is open for contribution.

**Comment by ojeytonwilliams** [comment]
Hi there @raditotev I don't think we want to strip js comments from challenges that use the DOM. Mostly because it increases the possibility of error (strip-comments assumes that it's being called on code in a single language).  Also because there aren't any comments inside script tags in html challenges (to my knowledge).

I think @nhcarrigan's approach is best - namely to refactor any tests that use `getUserInput` form just to use `code`. Once that's done we can stop catering for `getUserInput` entirely.

**Comment by ShaunSHamilton** [comment]
@raditotev Thank you, for taking the time to look into this.

> The example given in the https://github.com/freeCodeCamp/freeCodeCamp/issues/44705#issue-1095805739 by @lasjorg doesn't fail anymore - with or without commented code.

That is because we temporarily fixed it here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/45133

> namely to refactor any tests that use getUserInput form just to use code. Once that's done we can stop catering for getUserInput entirely.

I would argue against this. For the most part, I recommend not writing any more challenges/tests using that format, but we should not just keep editing these old challenges in major refactors.

---

**Comment by nhcarrigan** [comment]
> we should not just keep editing these old challenges in major refactors

Why, though? If we're preserving the challenges on the map, IMHO we should be maintaining them (at least at the level of bug fixes like this).

**Comment by ojeytonwilliams** [comment]
I'm not keen on maintaining a second way of getting the user code.  We need a way to get the user's url for backend submissions, but we don't need two ways of getting their source, imo.

**Comment by Nirajn2311** [comment]
Fixed
