### ISSUE TITLE
Bonfire:Steamroller, output shown is correct but solution is not being accepted.

### ISSUE THREAD

**Issue by rehul29** [FreeCodeCamp/FreeCodeCamp#4472]
Challenge [Bonfire: Steamroller](http://www.freecodecamp.com/challenges/bonfire-steamroller?solution=var%20final%20%3D%5B%5D%3B%0Afunction%20steamroller(arr)%20%7B%0A%20%20%2F%2F%20I%27m%20a%20steamroller%2C%20baby%0A%20%0A%20%20for(var%20i%20in%20arr)%7B%0A%20%20%20%20if(Array.isArray(arr%5Bi%5D))%7B%0A%20%20%20%20%20%20steamroller(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20final.push(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20final%3B%0A%7D%0Asteamroller(%5B%5B%5B%22a%22%5D%5D%2C%20%5B%5B%22b%22%5D%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var final =[];
function steamroller(arr) {
  // I'm a steamroller, baby
 
  for(var i in arr){
    if(Array.isArray(arr[i])){
      steamroller(arr[i]);
    }
    else{
      final.push(arr[i]);
    }
  }
  return final;
}
steamroller([[["a"]], [["b"]]]);
```

**Comment by ltegman** [comment]
You are declaring `final` as a global variable, so any run after the first one will give a wrong answer because it's not starting with an empty array.

In the future please take code questions to the [Help Chat](https://gitter.im/FreeCodeCamp/Help) and [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) before filing a bug.

Thanks and happy coding!
