### ISSUE TITLE
Minor UI issue in homepage, while toggling night mode.

### ISSUE THREAD

**Issue by Palakash27** [freeCodeCamp/freeCodeCamp#44835]
**Affected Page**
https://www.freecodecamp.org/learn and all the pages in which we are flashing `We have updated your preferences` this message on changing of `Night Mode`

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/learn' and sign in/ sign up
2. Click on 'Menu' button on navigation bar and select night mode `ON/OFF`
3. After selecting the night mode, you will see a message flashes with text `We have updated your preferences`

**Expected behavior**
The text in the message and button should be in the center. But it is not centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/29005595/150133193-578ec7b2-f60f-48e9-b1ea-42c27ff382a3.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 97.0.4692.71 (Official Build) (arm64)

**Comment by Palakash27** [comment]
I am capable of fixing this issue. Please let me know if I can. Thanks.

**Comment by GoonerBrian** [comment]
I'm a first time contributor and am also going to look into this.

**Comment by moT01** [comment]
I'm not sure if this is something we want. You can feel free to look into it, but I can't promise we would accept the changes. Here's one of the longer messages:
![Screenshot from 2022-01-25 19-16-23](https://user-images.githubusercontent.com/20648924/151086834-039259c2-6c4d-45f1-a2e8-fd84fcc76989.png)
Perhaps there's a reason the text is how it is. The text may not be centered, but the content as a whole is. The text is on the left and close button is on the right, with same margin on the outside of each. I don't think this is a problem that needs fixing. If you want to play with it and make a suggestion of something you like better, go for it. I would share an image if you do.

**Comment by GoonerBrian** [comment]
Thanks,  will do. It's also this way with the flash-message that popups when a user signs in for the first time. I'll play around with it. It's okay if you decide to kept it as-is. If you could, please keep this open until next Monday!

**Comment by GoonerBrian** [comment]
Here is a picture of the updated UI that I created a pull request for. This also works for other occurrences where a flash-message alert pops up. Thanks for keeping this open for me.
<img width="1238" alt="Updated Preferences" src="https://user-images.githubusercontent.com/42704371/151735001-3b92737d-14a8-4f7d-818a-da37426748f5.png">

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen since you are working on the alert component. The proposed change above look good; however, it would make tapping it a bit challenging for mobile devices since it become close to two other active components;

We need to be discussing the following points for next iterations of our notification.

**Comment by ahmadabdolsaheb** [comment]
Although we need to keep the close button in the same spot for consistency, I could see how this would be confusing for larger screens. We could create a visual guide by reducing the width of the notification component to a container with a max-width and have it cover the default layout. 

Since we are in the process of creating a component library and the alert component is already in, I would prefer making iterations on the alert component once the UI library is in use. 

Thank you for creating this issue. I am closing this issue for now as we will be addressing it among others in the upcoming iterations of the [UI component library](https://github.com/freeCodeCamp/freeCodeCamp/issues/44668).

**Comment by Wildchild11** [comment]
> 

How to fix
