### ISSUE TITLE
Last test on js calculator should give a different result 

### ISSUE THREAD

**Issue by PabloPenia** [freeCodeCamp/freeCodeCamp#44857]
## Affected page

[JS Calculator](https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-javascript-calculator)
## Expected behavior

5 * - + 5 = 25

## Additional context

_User Story #13: If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign). For example, if 5 + * 7 = is entered, the result should be 35 (i.e. 5 * 7); if 5 * - 5 = is entered, the result should be -25 (i.e. 5 * (-5))._

Last test calculates **5 * - + 5 = 10.** In the demo calculator when you hit + it removes * and - . I was testing several calculators, all works different but results are always 25 or -25:

Galculator: 5 x - + 5 = 5 x + 5 = 25
google: 5 x - + 5 = 5 x - (+ 5) = -25

I think this should be changed or place a user story which explains this point on why should give 10 and not 25 0r -25

**Comment by jeremylt** [comment]
I think this test is fine.

> If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign)

If you remove all but the last operator, you get `5 + 5 = 10`.

We don't want to send users down the route of the complex parsing that Google is attempting to do.

**Comment by PabloPenia** [comment]
I think the gnome calculator is more accurate, when you hit more than 2 operators the last one is changed. But in the demo 2 operators change, the last "+" removes "-" and "*". 
Anyway what happens after you submit the challenges on FCC? I can edit my code just to pass the tests and then edit it again?

**Comment by jeremylt** [comment]
> But in the demo 2 operators change, the last "+" removes "-" and "*".

I wouldn't describe it that way. In the demo when multiple operations are pressed, only the last one is used.

I could be wrong, but as I understand the intent, are three cases:

1) One operation is used => call that operation

2) Two operations are used AND the last one is - => call the first operation, using the - as a negative sign

3) More than two operations are used OR two operations are used and the last one is not a - => use the last one

This is far simpler than the 'proper' logic, but intentionally so.

---

If you submit a project you are asserting that it passes all tests. If you want to make an extended version of the project with different behavior, personally I'd keep that separate from the certification version.

**Comment by c-ehrlich** [comment]
To me the real problem is that when adhering to the minimum specs of the project, the `-` button is pulling double duty as a regular `-` arithmetic button and a `+/-` button. 

This creates some weird cases.
`5 * - 5` is evaluated as 5*(-5).
`5 * - + 5` is evaluated as 5+5.
`5 * / - 5` is evaluated as 5/(-5).

Requiring students to make separate `-` and `+/-` buttons is probably not a good idea as they would then need to implement their own math because it introduces cases that `eval()` doesn't know how to deal with, such as `eval(1--1)`.

In the end I agree with @jeremylt that `5 * - + 5 = 10` is correct behaviour given the current constraints and any changes to the challenge would only make it more confusing.

**Comment by jeremylt** [comment]
> `5 * / - 5` is evaluated as `5/(-5)`.

I don't know if this is accurate or not. It's not a tested condition to have both a extraneous operator and a negative sign, so I don't know if that is a case user calculators are supposed to handle in specific way. 

I think 'easy to use eval' probably shouldn't be an argument in any direction since use of eval is discouraged.

**Comment by c-ehrlich** [comment]
> User Story #13: If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign). For example, if 5 + * 7 = is entered, the result should be 35 (i.e. 5 * 7); if 5 * - 5 = is entered, the result should be -25 (i.e. 5 * (-5)).

I believe this user story fully describes the intended behaviour for multiple arithmetic operators. Maybe it's worth to clarify by adding an example that has 3 operators with the last one being '-'?

**Comment by naomi-lgbt** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue has been discussed and we have concluded no fix is necessary at this time.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
