### ISSUE TITLE
Typo on step 43 of the Beta  Learn the CSS Box Model by Building a Rothko Painting

### ISSUE THREAD

**Issue by katkelsch1** [freeCodeCamp/freeCodeCamp#44871]
## Screenshots

![typo on step 43 Rothko painting CSS Box Model](https://user-images.githubusercontent.com/98189777/150601805-bc767957-c944-4cb5-a010-a95bde06a4fd.png)

**Comment by jdwilkin4** [comment]
Hi @katkelsch1 ! 

Thank you for finding this typo.
I have added the first timers only label since this is an easy fix.

For those interested in fixing this issue, here is the file you need to change.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-the-css-box-model-by-building-a-rothko-painting/step-043.md

Proposed fix:
The border-radius property accepts up to four values to round the top-left, top-right, bottom-right, and bottom-left corners.

Please also read through our [Contributing docs](https://contribute.freecodecamp.org/#/index).

Happy contributing!

**Comment by GoonerBrian** [comment]
I'm going to start looking into this.

**Comment by katkelsch1** [comment]
Thank you for fixing the issue. It was the first time for me on Github. I'm
a total newbie in the webdev coding bootcamp.😀
