### ISSUE TITLE
Adding an alt attribute to steps 2-4 of the CSS Box Model project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#44923]
This might be a small issue, but I think for consistency sake we should always require users to add an alt attribute for their image tags.
In steps [2](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-2), [3](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-3), and [4](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-4) the challenge has the users working with an image tag but they are not required to add an alt attribute.
I understand that we remove that image tag in step 5, but I think for best practices we should always require users to add the alt attribute. 

Thoughts?

**Comment by sstonaker** [comment]
Since the attribute is introduced early in the HTML section [Step 9](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-9) I think it would be beneficial to be consistent and use best practices for the remaining exercises.

It may be distracting for the box model since it is an illustration that is removed, however there are other courses such as Photo Gallery [Step 6](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-6) where "be sure to include an appropriate alt attribute for each img tag" with an associated test would fit well.

**Comment by bbsmooth** [comment]
@jdwilkin4 love your attention to accessibility :+1: 

In these three instances I think it might be OK to just have a note saying that normally you always want to have an `alt` attribute describing the image but for brevity we are leaving them out since the images are temporary.

I think the real accessibility issue here is that these three images are being used to explain a concept. Thus, the text content must be a sufficient alternative to the images. So I think we need to make sure that these steps explain the concepts being conveyed in the images without needing the images.

**Comment by ShaunSHamilton** [comment]
@bbsmooth Which are you more advocating for:

a) Making the editor description more explicit such that the images are _redundant_?
b) Give the images detailed alts and captions such that screen readerers can get the same information as a person trying to learn from the image?

**Comment by bbsmooth** [comment]
@ShaunSHamilton I think I would advocate for making the description for each step more detailed so that the images aren't even needed. I'm not saying we have to get rid of them, just that they are not essential for explaining the concept.

Personally, I feel like the images should be in the description themselves. If we did this then perhaps we could rely on the alt text to help explain the concept. But having the user add the image seems awkward if we want to rely on the image in any way. We would have to give the user not only the URL but the alt text as well. But if we are going to do that, then why not just include the alt text in the description in the first place? Also, a screen reader user isn't going to know why they are adding these images unless we tell them, so we have to add even more to the description to explain that these images are not essential and everything you need to know is in the description text.

If we added the images to the descriptions then we could use alt text effectively and the images would make sense to everyone. But then we lose the interactive task of adding/changing the image for each step. My proposal would be to use the `div.frame` element from the project to demonstrate the box model. It has the `width`, `padding`, `border`, and `margin` properties set on it so it covers all four aspects of the box model presented in the images. Each step could add one of these properties to `div.frame` with an explanation of how it relates to the box model.

**Comment by ShaunSHamilton** [comment]
Thank you, for that @bbsmooth .

I would have to do some usability testing with the images in the description - just because we tried to create these practice projects with as little stuffs as possible (_even then, we can improve a lot_). That being said, it does sounds like the approach that makes the most sense.

---

@nhcarrigan What are your thoughts on this?

**Comment by nhcarrigan** [comment]
I have many thoughts on this. Primarily in agreement that what we currently have isn't ideal.

I think, of all the options we've discussed, the proposal to construct the `div.frame` as a way to teach the box model is the most logical.

**Comment by ieahleen** [comment]
> My proposal would be to use the `div.frame` element from the project to demonstrate the box model. It has the `width`, `padding`, `border`, and `margin` properties set on it so it covers all four aspects of the box model presented in the images. Each step could add one of these properties to `div.frame` with an explanation of how it relates to the box model.

We would want to remove the images alltogether, or add them to challenge description?

**Comment by Mfonn** [comment]
Hi, can I please be assigned this issue @naomi-lgbt @ieahleen

**Comment by bbsmooth** [comment]
Did we come to a consensus that using `div.frame` to explain the box model is the way to go here?

> We would want to remove the images altogether, or add them to challenge description?

I personally don't think we need the images if we use `div.frame`. What we might need to do is add a background color to it so that the user can see the space that it takes up and can see the changes as we have them add width, padding, margin and border. 

I do wonder if this issue is ready to be implemented yet though? This change is going to involve a lot of rewriting of the steps and possibly adding additional steps. Seems like we should map it out a little better as to exactly how we want this done.

**Comment by naomi-lgbt** [comment]
Going to remove https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted from this issue as we seem to still be discussing the implementation.

**Comment by moT01** [comment]
Closing this as stale. If anyone thinks we still need adjustments here, feel free to leave a comment and we can reopen.
