### ISSUE TITLE
Drum Machine project's 6th test fails and throws an error

### ISSUE THREAD

**Issue by elidrissidev** [freeCodeCamp/freeCodeCamp#44938]
The 6th test of this project is failing every time and throws the error `Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().` in the browser console, after some research I've found this [thread on the forum](https://forum.freecodecamp.org/t/drum-machine-not-passing-last-test/239158), it seems that other people have faced it too.

## Affected page

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-drum-machine

## Your code

Here is the link to the pen that reproduces this issue: https://codepen.io/elidrissidev/pen/bGYbmgy

## Expected behavior

The test should pass as the functionality is working when interacting with the app manually.

## System

- Device: MacBook
- OS: macOS Catalina
- Browser: Google Chrome
- Version: 97.0.4692.99

## Additional context

The issue seems to arise because the calls to `play()` and `pause()` are async and return a promise, but in the test they're not handled properly.

**Comment by elidrissidev** [comment]
Tried on my desktop and now the tests pass, but the error is still thrown in console.

**Comment by nhcarrigan** [comment]
Thanks for reporting this.

The linked forum topic includes a great explanation of where the bug is likely to be occurring. A PR to solve this can be made on the [testable project repo](https://github.com/freeCodeCamp/testable-projects-fcc). I'll go ahead and open this issue up for contribution.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by PavanS04** [comment]
@nhcarrigan I am a first time contributor. Is the issue still there? If yes, then I could work on it .

**Comment by elidrissidev** [comment]
@PavanS04 Yes it's still there. Go to the linked pen and run the tests to reproduce the error.

**Comment by PavanS04** [comment]
@elidrissidev I am not getting any error while running it on code pen (not even in console). Can I share the screenshot here?

**Comment by TaraBryn** [comment]
Wouldn't this require an update to [bundle.js](https://raw.githubusercontent.com/freeCodeCamp/cdn/main/build/testable-projects-fcc/v1/bundle.js)? Do we have a tool to do that?

**Comment by elidrissidev** [comment]
@TaraBryn there is another [repo](https://github.com/freeCodeCamp/testable-projects-fcc) for it

**Comment by TaraBryn** [comment]
@elidrissidev  thank you! I spent an entire day looking in the freeCodeCamp repository for where to adjust this

**Comment by TaraBryn** [comment]
I see three potential solutions here:

1. embedding a timeout in a promise and putting the call to `paus()` in the `.then()` function (I tested this, setting the timeout to 2000 ms, and it didn't work)
2. removing the `pause()`s altogether, which I also tested, and this one did of course work, with the side effect that the user can hear the sounds during the tests
3. Have the user create a global variable and assign it to the promise returned by the `play()` function and then check if the global variable is undefined (which has the side effect of requiring another User Story to make sure that the variable is created a given a specific name). I feel as though this alternative adds unnecessary complexity to the parameters of the project.

**Comment by elidrissidev** [comment]
@TaraBryn if the only side-effect of solution 2 is user will hear the audio, how about setting the volume to 0?

**Comment by TaraBryn** [comment]
@elidrissidev thank you, I will try that

**Comment by TaraBryn** [comment]
@elidrissidev SoI tried both setting the volume to zero and muting the audio elements and both ran into the same issue. Because the `play()` is asynchronous and we have no way of accessing the `play`'s promise, when you go to unmute it or return the volume back to what it was, the audio still plays after the tests are complete.

Honestly, I think hearing the tests playing is something we might be able to live with here, if preventing the error message is important enough (which it might be because it can cause confusion, esp to people new to coding)

**Comment by elidrissidev** [comment]
@TaraBryn how about muting them before the test suite is started, and unmuting them afterwards, is this the same thing you tried?

https://github.com/freeCodeCamp/testable-projects-fcc/blob/62f1d8bca3ad2d05497ff423bffdbc67f08f367c/src/project-tests/drum-machine-tests.js#L49-L53

**Comment by TaraBryn** [comment]
@elidrissidev this is what I tried:

https://github.com/TaraBryn/testable-projects-fcc/blob/fix/update-drum-machine-test/src/project-tests/drum-machine-tests.js

(lines 7-12 and 205-206)

**Comment by Nirajn2311** [comment]
Device specific issue
