### ISSUE TITLE
Typo in Responsive Web Design (Beta)

### ISSUE THREAD

**Issue by Dainelli** [freeCodeCamp/freeCodeCamp#44968]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-28

## Your code

```

Give each fieldset an adaquate name attribute.

```

## Expected behavior

Should be **adequate** 

## System

- Device: [Laptop]
- OS: [openSUSE Tumbleweed]
- Browser: [Vivaldi]
- Version: 5.0]

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in staging (PR #44906). This means that the next time we push our staging branch to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by ieahleen** [comment]
Wait, sorry, there are more adequates to fix
