### ISSUE TITLE
Make sure finished projects render on certs / timeline?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44979]
Nice to have:

- [ ] A user can open previews in full-screen in a new tab.

**Comment by ShaunSHamilton** [comment]
For this, did we decide on:
- When the preview is open, the code is visible?
- The preview lives in a unique URL to be linked to directly?

**Comment by ojeytonwilliams** [comment]
We've not got that far on the ui design, but options are:

- separate buttons to show preview and source
- separate tabs for preview and source

I'm leaning towards separate buttons, as I think that'll be less cluttered.

As for the Nice To Have, there would need to be a URL that fetches the preview. It could just be handled via query params, rather than unique paths, though.

**Comment by moT01** [comment]
I think I would go with two buttons, one for the code and another for the preview. Both open a modal on the page, and they would probably need to work anywhere else we show solutions - the cert itself, the timeline, and the settings page.

I guess if you can make a URL that opens the preview in a new tab, that would be preferable. I assume that would be more difficult, but I'm not sure.

**Comment by ShaunSHamilton** [comment]
I would prefer:
- A Camper can link to a unique URL (url with query params. e.g. `freecodecamp.org/certification/sky020/responsive-web-design?view=full`)
- The _full_ view opens in a new tab (always?)
- The _editor_ view opens in the current editor? Or, a completely new view showing uneditable code and preview?

**Comment by ojeytonwilliams** [comment]
Since this just intended to showcase work, I think there should just be a code view, not an editor view.  Prism highlighted text should do the job.

Putting in a real editor, even a read-only one, seems like overkill.
