### ISSUE TITLE
Allow async testing in challenges

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#4506]
@SaintPeter We need some ideas on how to specify async testing in challenge JSON files.

**Comment by SaintPeter** [comment]
Some ideas:
1) Allow a callback function which sets an assertion to be true/pass.
Some sort of "Text X has passed" sort of thing.  I don't know if that means we have to have some sort of timer built into the tests, where there is a period, per-challenge definable, during which we wait for the callback to fire.  If it never fires, we fail the test.  Need a visual indicator that we're waiting . . . like the test symbol is a (:question:) or a spinny, for the timeout.

`assertWithin(10, test1 === true, 'Your callback function never fired')`

The code to do the callback might have to run in the `tail`?

This gets sticky on flaky internet connections.

2) Callback Injection
Somehow inject our callback into their functions?  How do we specify location to inject?  "Before the last `}`", "After the second `{`" or  "Before the last `return` statement"?  Needs to fail safely if we can't find the place to inject it at run time.

3) Allow us to write code which runs between tests
Imagine that you want to test a "click" function.  We can write code to artificially "click" the button for us, to force the function to fire.  This could possibly be combined with a callback?  We check the HTML before the change, fire the click off, then wait for an event of some sort to check the HTML again?

`assert(some HTML Check here)`
`$('.someButton').click()`
`assert(Check for changed HTML)`

4) Spies are helpful here
Since we can bypass the issue entirely by checking to see if the proper parameters have been passed to an async function.  You don't need to check if the `.getJSON` completed successfully if you know the proper params were passed.  Also, if we can capture the success function, we can run it "manually" with faux input.

**Comment by bugron** [comment]
Is there are progress on this?

**Comment by BerkeleyTrue** [comment]
For testing we'll be implementing `before`, `after`, `beforeEach`, `afterEach` in the challengeSpec. 

The hard part will be how to get the framework to recognize when a test is async.

**Comment by BerkeleyTrue** [comment]
We now have async testing using either callbacks, observables, or promises!
