### ISSUE TITLE
Waypoint: Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by jaimehn** [FreeCodeCamp/FreeCodeCamp#4509]
<img width="498" alt="2" src="https://cloud.githubusercontent.com/assets/15893785/11231835/efa82f48-8d71-11e5-82b9-4bfa61a727c6.PNG">

The only task I haven't completed is the "Your p element should have the text "View more " (with a space after it)." However, when I add a space after my code (line 34) it still doesn't accept my code.

**Comment by bugron** [comment]
@jaimehn thanks for posting this issue!
Please, post the link to the challenge.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ltegman** [comment]
The challenge in question is [this one](http://www.freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph). However, I am unable to repro this even with code that looks to be just like what you have in your screenshot. Please copy and paste all the code from your editor so that we can attempt to reproduce this.

**Comment by ltegman** [comment]
Closing this as no repro.
