### ISSUE TITLE
Correct answer is not verifying / showing its wrong

### ISSUE THREAD

**Issue by midhxn** [freeCodeCamp/freeCodeCamp#45119]
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images

## Screenshots

![freecodecamp](https://user-images.githubusercontent.com/69138490/154046714-95189ffa-e076-44d3-9e13-d33d77a55329.JPG)

## System

- OS:  Windows 10
- Browser: firefox

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
