### ISSUE TITLE
Challenge (Timestamp Microservice) unix value must be of type number

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45280]
The test requires that the `unix` value is of type Number. But you have to look at the example response given and realize it is a number and not a string.

> A request to `/api/1451001600000` should return `{ unix: 1451001600000, utc: "Fri, 25 Dec 2015 00:00:00 GMT" }`

We do pretty often get forum posts about this so maybe this needs to be made more clear?

Challenge: https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice

**Comment by c-ehrlich** [comment]
I feel like observing the behaviour of the demo API and figuring out how your own API differs from the spec is an important part of the project, where giving too much information up-front might not be desirable because then people can complete it on autopilot instead of having learning experiences.

There is something to be said more generally though about the current difficulty in debugging _why_ your code fails one of the project requirements, as unlike the Frontend Libraries Cert you can't see the actual output of any failed tests.

**Comment by lasjorg** [comment]
I completely agree but it would be nice if the test blocks were formatted a bit better. Like the response on its own line using a fenced code block with some highlighting. I know it would make it take up more space but I think that would be worth it.


Just as an example:

![formatting](https://user-images.githubusercontent.com/28780271/155981284-5ee0e9e2-516e-4e90-af3b-42acfa7580eb.png)

**Comment by lasjorg** [comment]
BTW, the type is provided for the other response:

> A request to `/api/:date?` with a valid date should return a JSON object with a `utc` key that is a string of the input date in the format: `Thu, 01 Jan 1970 00:00:00 GMT`

I'm not suggesting we spoon-feed the students, just that we give them clear instructions.

**Comment by nhcarrigan** [comment]
> A request to /api/:date? with a valid date should return a JSON object with a unix key that is a Unix timestamp of the input date in milliseconds

Personally, "in milliseconds" suggests it should be a number to me. But that could be more due to my experience than anything else.

I don't see a reason why this shouldn't be clarified, so I'm on board. Maybe just adding a note will work?

> A request to /api/:date? with a valid date should return a JSON object with a unix key that is a Unix timestamp of the input date in milliseconds (as a number)

**Comment by lasjorg** [comment]
I would be fine with just a mention of the type in the message.

**Comment by nhcarrigan** [comment]
Works for me! Will go ahead and open up for first timers.

---

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by abhijain2003** [comment]
I created a full-stack JavaScript app that is functionally similar to this: https://timestamp-microservice.freecodecamp.rocks/.
you can check it https://github.com/abhijain2003/boilerplate-project-timestamp/tree/date at github repo I also requested a pull.
and how it works I uploaded a video , please accept my pull request and merge it



https://user-images.githubusercontent.com/91718608/156928288-7266301a-1fed-4bd6-8ab0-a7adc596078f.mp4

**Comment by lasjorg** [comment]
@abhijain2003 This is an issue about adding type information to one of the test output blocks.

We do not merge people's projects. You submit the project on the challenge page and it gets tested.

**Comment by abhijain2003** [comment]
ok but there's a problem that every time after refresh it changes its localhost port because of this it's hard to deploy it

**Comment by lasjorg** [comment]
@abhijain2003 Please use the [fCC forum](https://forum.freecodecamp.org/) if you need help with the curriculum.
