### ISSUE TITLE
Comma missing in Exercise Tracker "exercise" object

### ISSUE THREAD

**Issue by y-arjun-y** [freeCodeCamp/freeCodeCamp#45308]
## Affected page
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

## Expected behavior
There should be a comma for  "username: "fcc_test", otherwise the JavaScript Object syntax is wrong.

## Screenshots
<img width="775" alt="image" src="https://user-images.githubusercontent.com/58625220/156348265-6d8e462f-9140-4f5f-a06c-cb38e50f4bff.png">

## System
- Device: MacBook Air M1
- OS: macOS Monterey 12.0.1
- Browser: Chrome
- Version: 98.0.4758.109

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. (https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
