### ISSUE TITLE
extra word

### ISSUE THREAD

**Issue by yuanhepeng** [freeCodeCamp/freeCodeCamp#45449]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-41
## To reproduce

extra word -> "time" word continuous appeared twice 
## Recommended fix, suggestions once 
"time" should just only appeared once in the first sentence

Now it's time to add other details to the markers
## Screenshots

![image](https://user-images.githubusercontent.com/39111057/158770642-b299d8b5-5441-4c38-b1eb-0e6e42433ca6.png)

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here is the file that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/618a16d21bd3dad1bb3aa8ef.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
