### ISSUE TITLE
Creating Custom FormControl Component

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#45459]
### Props:
   - onChange: func
   - value?: string
   - componentClass?: string
   - placeholder?: string
   - name?: string
   - required?: string
   - rows?: 4
   - type?: 'text' | 'email | 'url'

### Variations:
- FormControl
- FormControl.static
- FormControl.Feedback

**Comment by Sboonny** [comment]
Form control for chapter: 

Need to alter the props to account for chapter need here is the link of the chakira component

https://github.com/chakra-ui/chakra-ui/tree/main/packages/form-control

**Comment by ahmadabdolsaheb** [comment]
Which prop is being used in the chapter that we are not passing in the component library?
Since chapter views are limited, it might be easier to create the components with learn specifications and use those props to control the component. does that make senes?

**Comment by Sboonny** [comment]
Instead of checking the chaikra library and comparing it with the current component, I am better off checking chapter itself for prop it's using.

for example, in this file https://github.com/freeCodeCamp/chapter/blob/main/client/src/components/Form/Fields.tsx
we are using `key` and `isRequired`, so I note these down and check if these 2 props are different from the props we are using.

depend on how different they are, I may do from the follow:

* Add new value to existing prop.
* Add new prop to the component.

**Comment by ahmadabdolsaheb** [comment]
Here is what I propose we do. We could continue building the components with the learn spec and ship them. For the second sprint, we collect the Chapter requirements and update the components accordingly.
