### ISSUE TITLE
Addding a margin to the header

### ISSUE THREAD

**Issue by wongruiyang** [freeCodeCamp/freeCodeCamp#45510]
## Is your feature request related to a problem? Please describe.
On mobile devices, there is a navigation bar where you can switch back and forth the pages right below the header. It can be quite frustrating to tap on the logo accidentally when you tap on the 'Info' or 'Code' in the navigation bar.
![Screenshot_20220323-152933_Chrome](https://user-images.githubusercontent.com/97069075/159647660-1195d596-0439-4226-9d6a-33d29d84d9a0.jpg)

## Describe the solution you'd like

I am proposing to add a padding to the header component, which can help to prevent accidental taps on the logo when using the navigation bar right below the header on mobile devices.

**Comment by moT01** [comment]
I can see how that might be frustrating. Mobile devices are quite limited on space - a little more padding would be better than a button you can't press. Here's another idea... what if we made the hit box for the button bigger, but visually it looks the same. Apple does something like this with their mobile keyboards. Perhaps a combination of more padding and an bigger hit box or something.

Curious, are you using the mobile app or just running your mobile browser @wongruiyang?

**Comment by wongruiyang** [comment]
I use both the mobile app and the browser. The screenshot was taken running on the browser. I am not sure whether making the hitbox will work because tapping on the logo will redirect you to the home page.

**Comment by c-ehrlich** [comment]
I don't think making the header bigger is the right solution here, because it should probably be consistent throughout the site, and I'm not sure it's a problem on other parts of the site.

That being said I tried it out on my phone, and it is indeed not easy to hit those buttons. They have the header above them and the curriculum breadcrumbs below them, both touch targets that move you to a different page.

Another option would be to increase the size of the buttons. Here I've doubled the padding (which makes the buttons about 33% taller in total), simulated on a larger screen phone (iPhone 13) and a smaller screen phone (iPhone 5 / SE 2016).

Thoughts about this or a similar solution?

<img src="https://user-images.githubusercontent.com/8353666/160995907-a775f39e-9467-4c66-8804-1d6c902ff738.png" alt="Increased button padding (iPhone 13)" width="390" />

<img src="https://user-images.githubusercontent.com/8353666/160995966-d9f7ed7d-0d3a-4a5e-bc81-d67881454503.png" alt="Increased button padding (iPhone 5/SE)" width="320" />

**Comment by wongruiyang** [comment]
Works as well! Just giving a suggestion

**Comment by ahmadabdolsaheb** [comment]
ideally two active elements should not be placed next to one another on mobile interfaces, but in this case making the tabs larger should do the trick.

**Comment by moT01** [comment]
I believe we need to add some padding to those buttons at the top and stop the bottom buttons from going off the screen.

**Comment by riddhitech** [comment]
Can you please assign me this issue,I want to contribute.

**Comment by ahmadabdolsaheb** [comment]
@riddhitech , please go ahead 👍. No assignment is necessary as described in our [contribution guidelines](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by riddhitech** [comment]
Sir, where is the code , I am a begineer , finding difficulty to find.

**Comment by ragnarok-02** [comment]
I am a beginner. I would like to contribute to this issue. Can you please help me find the code and related details, and assign this to me?

**Comment by kclalit64** [comment]
Is this issue still supposed to be open? On my smartphone, I'm currently looking at a different header (which I suppose, solves the mentioned issue)
![WhatsApp Image 2022-10-20 at 8 41 18 PM](https://user-images.githubusercontent.com/91486778/196988270-28c43984-8c2e-4d29-87e5-1b19b9629045.jpeg)
