### ISSUE TITLE
add isStepBased to meta files

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#45522]
This will benefit the mobile client immensely as it will give us the opportunity to differentiate step-based blocks and normal blocks.

it should be fine to only add the key in actual step-based files.

**Comment by moT01** [comment]
There isn’t anything explicitly denoting a step based challenge or block - they do have some things you could maybe use…
- The filenames for step challenges are all mongo id’s, e.g. `613e2546d0594208229ada50`. Probably don’t want to rely on that though
- There’s a few properties in the step based files - `title: Step #` and `dashedName: step-#` are in the front matter. These might be usable to determine if it's a step.

If we decide to add the `isStepBased` property, I would lean towards putting it in the block meta if we can. That would mean all the lessons in the block are step based. It probably makes more sense to put it on the challenge, since it's more related - but then we need to add it to all the steps, instead of one block. Probably similar to the `usesMultifileEditor: true` and `hasEditableBoundaries: true`that we added to the block meta, even though those seem more related to a challenge and not the whole block. We just don't really mix and match challenge types within a block.

**Comment by moT01** [comment]
I'm fine with adding it

**Comment by ojeytonwilliams** [comment]
Can't we just use a combination of the editable region and `usesMultifileEditor`? That's how the client determines if it's step vs. a multifile project vs. something else entirely.

**Comment by Sembauke** [comment]
It might be less work, but it would not be good for semantics.  

What if we decide to use the multi file editor everywhere?

**Comment by moT01** [comment]
I think I agree with @Sembauke here - using that combination seems like added complexity that could be unreliable. I don't personally like using that type of logic in the client either.

Another option could be to add another challenge type. The step challenges are type 0, which is the same as all the alpha RWD challenges, even though they are quite different. Seems like we should maybe do that anyway.

**Comment by ojeytonwilliams** [comment]
I'm fine with using a new challenge type, since that reduces overall complexity.

**Comment by Sembauke** [comment]
The only thing is, that adding a new challenge type may resolve the current complexity problem for checking which challenge is step based.

But the main reason why I am requesting this feature is that I somehow need to know which block is and is not a step-based block. (For the mobile app of course.)

My question therefore is: Is it still reasonable to add a new challenge type if it has nothing to do with the actual challenge? Does it not make sense to add it as a block type/meta attribute?

**Comment by ojeytonwilliams** [comment]
Thing is, blocks don't use the multifile editor, challenges do. So, if a block is a practice project or not depends on the challenges in it.

If we use @moT01's approach of differentiating challenges by their type (which is better than my method), then we can determine if a given block is "step based" if all it's challenges are of the step type. To be honest, it wouldn't hurt to have tests for that since we're unlikely to want a mixture in a single block.

That way the mobile app gets what it needs and we keep the separation of concerns (challenges still 'own' all challenge properties).

**Comment by Sembauke** [comment]
What I am trying to get at the API needs to know if a block is step based without knowing anything about the challenges. 

The logic you are suggesting I am fine with.

**Comment by ojeytonwilliams** [comment]
Yep, I think we're on the same page here. When we generate the mobile data for a block, we can check its challenges and use their challengeTypes.

**Comment by Sembauke** [comment]
> Yep, I think we're on the same page here. When we generate the mobile data for a block, we can check its challenges and use their challengeTypes.

if every challenge type is the same in one block, sure that will do.

**Comment by moT01** [comment]
Closing as stale.
