### ISSUE TITLE
Conflict with Ctrl + Enter keyboard shortcut in monaco editor

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#45571]
## Affected page

Any page with the monaco editor embedded.

## Discussion

Currently FCC uses the Ctrl + Enter keyboard shortcut to trigger the testing functionality on the user's code. Unfortunately, the monaco editor also uses this keyboard combination to insert a line. Since testing code is something that is done often I think it is essential to keep a keyboard shortcut for this functionality. Is it a possibility to switch to a different keyboard combination? I don't think Alt + Enter is being used by monaco. Otherwise, if this change would be too severe then perhaps we should remove this option from the monaco F1 menu.

**Comment by nhcarrigan** [comment]
`Ctrl + Enter` inserts a new line - is this a necessary shortcut to retain?

**Comment by ojeytonwilliams** [comment]
I didn't even know that was a shortcut, so I'm fine with removing it.  I'd be very reluctant to remove `Ctrl + Enter` as run the tests, because that's quite often a shortcut to 'execute stuff', so I think it's quite natural.

**Comment by nhcarrigan** [comment]
So the issue here is that the shortcut is listed in the `F1` palette but doesn't actually work (because we hijacked it).

I think I asked this on another issue too, but can we just... remove the `F1` palette?

**Comment by bbsmooth** [comment]
@nhcarrigan, yes, that is the issue. I think the Ctrl + Enter shortcut is used by a lot of text editing applications to add a new line when the Enter key itself doesn't add a new line. For example, in google spreadsheets, hitting Enter in a cell takes you to a new cell, so if you want to start a new line in a cell then you use Ctrl + Enter.

The reason I brought this issue up is because I was using the keyboard only to test the new beta RWD and I wanted an easy way to add a new line below the current focus in the editor. Some of the steps ask you to add an element below an existing element but the focus is on the current element. At first I tried to find a shortcut that would move the cursor to the end of the line so I could just hit Enter to start a new line but I couldn't find a shortcut for that :-( But searching through the F1 menu I did find a shortcut that allows you to insert a new line below the current line, but of course that was Ctrl + Enter :-) 

I think these keyboard shortcuts are important to know, especially for people who only use a keyboard (or voice control). So I would be hesitant to remove the F1 menu unless we provided alternative documentation for the keyboard shortcuts.

**Comment by nhcarrigan** [comment]
Thanks for the valuable input! I'm definitely a `Home`/`End` key user, which is why the keyboard shortcuts seem less necessary to me.

You are correct that `F1` isn't really documented anywhere - neither is the `n` and `p` shortcuts for switching challenges. A contributor has started work on a keyboard shortcut modal: https://github.com/freeCodeCamp/freeCodeCamp/pull/45530 We could potentially include the `F1` command palette shortcut there.

**Comment by ojeytonwilliams** [comment]
One thing we've been doing is avoiding advertising the hotkeys because we don't want to encourage users to skip between challenges.  I'm beginning to think we should change this approach.

Instead, how about we either

* drop the `n` and `p` shortcuts
or
* don't put them on the hotkey modal.

Either approach frees us up to advertise the modal and point people towards the `F1` command palette.

Also, if we want a shortcut for inserting lines below the cursor, how about `Alt + Enter` for that? It's better than not having it at all and means we don't have to confuse existing users by changing what runs the tests. Also we keep consistency with Jupyter notebooks, so that users that go through the Math/Data Science curricula keep using the same shortcut.

**Comment by ShaunSHamilton** [comment]
Just to mention, for the other tool I have been working on, I have specifically looked for another shortcut key for running the tests, because I use `Ctrl + Enter` all the time in VSCode - I also consider it bad form to overwrite a default.


For the most part, I have settled on `Ctrl + K`. So, perhaps we could move to using that.

**Comment by ojeytonwilliams** [comment]
Almost everything we come up with will be used for something. `Ctrl + k` for instance, takes you to the default search bar in Firefox. Also, it starts 31 chords in VSCode (so is a pretty disruptive choice).

**Comment by raisedadead** [comment]
Most users on freeCodeCamp are used to the shortcut & it would be a bad idea to change the shortcut.

> I have specifically looked for another shortcut key for running the tests, because I use ...

If there is an overlap with another tool, application, etc. it's unfortunate but doesn't necessarily call for an obligation to change it — unless we are breaking a11y (we are not in the <kbd>Ctrl</kbd>+<kbd>Enter</kbd> case).

So, I understand in a use case like yours it's just a matter of convenience (due to muscle memory). In that case, the "feature request" would be to allow users to remap keys. 

We can't get into that either.

**Comment by bbsmooth** [comment]
The consensus I'm getting from this discussion is that we are keeping `Ctrl + Enter` for triggering the tests and we should remap the monaco shortcut that currently uses `Ctrl + Enter` (Insert Line Below) if monaco allows this or remove this option from the F1 menu if it does not.

**Comment by raisedadead** [comment]
To the best of my knowledge, Monaco does allow custom keyboard events.
