### ISSUE TITLE
Basic Javascrip - Access Array Data with Indexes Example is confusing.

### ISSUE THREAD

**Issue by kadivadavidak** [freeCodeCamp/freeCodeCamp#45572]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/access-array-data-with-indexes

## Your code

The example, and example explanation are confusing here. Right now, array[0] is initialized to 50, and the second line is doing nothing, and the explanation says "array[0] is now 50, and data has the value 60.", where array[0] has always been 50. I think this is confusing, and maybe the second line in the example should change the value of array[0], and the explanation should say "array[0] is now [new value], and data has the value 60.". 

## Expected behavior

Example is not confusing.

## Screenshots
![image](https://user-images.githubusercontent.com/3832586/160747767-7c443d96-e99e-4a21-83c6-45ce2fd4b535.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 98.0.2

**Comment by amancodify** [comment]
Hi @kadivadavidak, I'll be happy to take up this issue.

**Comment by ojeytonwilliams** [comment]
Hi @kadivadavidak, thanks for pointing this out.

The next challenge shows users how to set array elements, so there's no need to introduce that concept here. Instead, we can modify the text slightly

> `array[0]` is 50

so that it's not implying at `array[0]` has changed.

**Comment by jeremylt** [comment]
That line doesn't do anything, so it always felt a bit strange to me. What about using a console log so it actually does something if the user tries to run the example? `console.log(array[0])`?

**Comment by nhcarrigan** [comment]
I'd be in favour of combining Oliver's and Jeremy's solutions:

- Update the line in the code to be `console.log(array[0]);`
- Update the text below the code to say "The `console.log(array[0])` prints `50`, and `data` has the value `60`.

**Comment by ojeytonwilliams** [comment]
@jeremylt, I agree about that line - it's just weird to have it there doing nothing.

@nhcarrigan, I like that approach.

**Comment by nhcarrigan** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/access-array-data-with-indexes.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by NnajiChimuanya** [comment]
That line doesn't do anything, 
It's just there to show you how to access an item in an array: that is there shouldn't be a space between the array name and the brackets containing the index...

**Comment by nhcarrigan** [comment]
Hey there,

You are correct that the second line does not do anything, which is why we are updating it to be a `console.log` call. 🙂

**Comment by sprajams** [comment]
Hi all,

First timer here and I made sure to read the guidelines.

Just created a pull request to attempt to fix this issue. Please let me know if I did this correctly or if you have any pointers/advice for a beginner to open source.
Thank you so much!

**Comment by nhcarrigan** [comment]
Hey there @sprajams!

Thanks for your interest in contributing - I'll take a look at your pull request shortly. A quick note that in the pull request body there's a line `Closes #XXXXX` - if you replace the XXXXX with this issue number (`Closes #45572`), GitHub will link the pull request to the issue and close the issue automatically if the PR is merged. 😁

**Comment by sprajams** [comment]
Gotcha! Thank you so much @nhcarrigan for your feedback and review 😃
