### ISSUE TITLE
Show completed code in completed steps (courses - learn platform)

### ISSUE THREAD

**Issue by lem0n4id** [freeCodeCamp/freeCodeCamp#45617]
## Is your feature request related to a problem? Please describe.

I am learning from the RWD course, and I wanted to revise what I had done previously. 

I went to previous steps, but I found that the steps are **shown incomplete** when I open them. It tells you to do the step again.

This doesn't make sense because you have a `Restart Step` button at the top if you do want to do the step again.

## Describe the solution you'd like

Completed code should be shown in completed challenge's code editor along with an indicator like  `✅ Step completed.` 

### What it currently looks like when you visit a previously completed step
![image](https://user-images.githubusercontent.com/61219881/161431677-d63a4a71-6704-49b4-b5c0-e5853e6f5655.png)

### What it should look like when you visit a previously completed step
![image](https://user-images.githubusercontent.com/61219881/161431717-4f824e56-eefb-47e1-baa4-15553f75ec54.png)

**Comment by ojeytonwilliams** [comment]
It would be relatively easy to show the solution to a step, and the "Step completed" text, (rather than storing the user's code) if a user has already submitted that step.

If other maintainers are in favour of this change, I'd be happy to open this up for PRs.

**Comment by nhcarrigan** [comment]
My concern with that approach would be it completely destroys the UX if someone wants to go through a practise project again.

**Comment by lem0n4id** [comment]
> My concern with that approach would be it completely destroys the UX if someone wants to go through a practise project again.

I propose to add a button `Restart Project` under the summary of each project for this issue.

**Comment by ojeytonwilliams** [comment]
I'm not keen on adding a button to do that, given the potential for frustration if someone triggers that accidentally.

**Comment by nhcarrigan** [comment]
I think I'd be in favour of the existing flow, presonally.

**Comment by moT01** [comment]
At a minimum, we could probably add the checkmark next to "Step 22" like we do for all the other challenges after it has been completed. That seems to be missing here.
![Screen Shot 2022-04-26 at 5 27 49 PM](https://user-images.githubusercontent.com/20648924/165403097-236f10d2-0214-412f-8a21-8df2847823e7.png)

**Comment by nhcarrigan** [comment]
That's a good idea, IMO.

**Comment by moT01** [comment]
I think just adding that check mark is probably the way to go then. It keeps it consistent with everything else. I'm going to open it up for contributions. If anyone still has reservations, be sure to bring them up.

**Comment by raditotev** [comment]
May I suggest in addition to indicating completed challenges in the challenge itself, to do that in the list of steps. Here is a crude representation of what I have in mind:
<p align="center">
  <img src="https://user-images.githubusercontent.com/5617443/168877692-edee2a78-b12f-4620-82c3-7242c6bd0e72.png" width=500 align="centre"/>
</p>

**Comment by benjaminJohnson2204** [comment]
@raditotev I believe it already does that. Here's a screenshot of what the challenge looks like for me, after I've completed it (the steps are highlighted in blue instead of white).
![completed HTML course](https://user-images.githubusercontent.com/68413232/168954823-fc322946-69b4-4e63-88a8-96a69f0cf80b.PNG)

**Comment by benjaminJohnson2204** [comment]
Also, I would like to work on this issue, and I agree that adding a checkmark next to the step would be a good fix, but I noticed that the RWD courses don't have a step number or title at the top like the other courses do. For other courses, the checkmark for completion is displayed next to the name of the challenge, like you can see in the first screenshot (of the JS Algorithms & Data Structures courses). However, for the RWD course, there is nothing in this location, as you can see in the second screenshot.
![Golf Code Title](https://user-images.githubusercontent.com/68413232/168955437-6c1ece70-3e06-4d53-bb59-55256260d284.PNG)
![HTML course title](https://user-images.githubusercontent.com/68413232/168955446-700cab4f-dea1-4d21-b9b3-bca485223949.PNG)

How should we go about adding a checkmark to the RWD course? Should we just put it next to where it says `Step 1` on the screenshot (inside the instructions block)? Or should we move the step number to the same place as where the challenge names are for the other courses and put the checkmark there, in order to be consistent with the other courses?

**Comment by raditotev** [comment]
> @raditotev I believe it already does that. Here's a screenshot of what the challenge looks like for me, after I've completed it (the steps are highlighted in blue instead of white). ![completed HTML course](https://user-images.githubusercontent.com/68413232/168954823-fc322946-69b4-4e63-88a8-96a69f0cf80b.PNG)

Thanks @benjaminJohnson2204. I could not log in since yesterday and this is probably the reason I don't see indication for completed challenges in the list of steps.
