### ISSUE TITLE
Put the `projectName` in the CodePen templates by default for testing

### ISSUE THREAD

**Issue by Yash-Singh1** [freeCodeCamp/freeCodeCamp#45738]
## Is your feature request related to a problem? Please describe.

Whenever a [CodePen template](https://codepen.io/pen?template=MJjpwO) is given, it doesn't set the `projectName` global variable as done in the examples. This makes the user have to select the project type in the dropdown menu every time they start a new project.

## Describe the solution you'd like

Make each of the templates unique with the `projectName` set for their corresponding project.

## Describe alternatives you've considered

Either set the `projectName` yourself or just select the localized project name from the dropdown menu (it is stored in the `localStorage`).

## Additional context

Curriculum project tests repo: https://github.com/freeCodeCamp/testable-projects-fcc

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time top open this.

There is only one given template. As such, it cannot set the project name (because it is used by multiple projects). This is done for simplicity. Otherwise, it would not be a template, but a boilerplate which, in this case, would be unnecessary.

---

I am going to close this issue, because, with the upcoming release of the new curricula, these templates will be sunset (archived) anyway.
