### ISSUE TITLE
[i18n] Handling English Fallback of Audited Superblocks

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#45736]
Oliver added a fantastic improvement to our curriculum build flow which allows i18n builds to fall back to the English files if a translated challenge file is not present. At my suggestion, we added a step that would fail the build if an audited superblock was falling back to the English files, as audited superblocks should be 100% translated.

However, there were some pitfalls I failed to consider. My biggest concern is what should be the flow if we add a new challenge to an audited superblock? Or if we add a whole new block? These would both cause the builds to fail.

A couple of potential solutions:
- We could mark the superblock as unaudited until translation is complete. The downside here would be that the superblock changes location in the map depending on whether it's audited or not.
- We could add the English files to the i18n directories. This defeats the purpose of the fallback and I would not recommend this approach, but it's listed here for discussion.
- We could remove the validation I had proposed. This might be the best approach, though that validation was definitely nice to have.

Thoughts?

**Comment by ojeytonwilliams** [comment]
> I believe the badges are determined at the superblock level with the isAudited flag.

That's right, they all check `isAuditedCert`

> By removing the validation do we still have the ability to add a "translate this" badge to the particular new challenge or new block?

We could add them at the block/challenge level if we see that we needed to fallback to the English.

That way 'isAudited' really means 'was audited at one point', but chances are *most* of the pages will still be translated.

**Comment by moT01** [comment]
> We could mark the superblock as unaudited until translation is complete.

An additional downside is that the whole superblock reverts to English, correct? Actually, I'm not sure if that's the case now - but if it is and I'm going through the Spanish curriculum, and we set `isAudited` to false, I'm now going through it in English - even though it's mostly translated. I'm fine with waiting until the cert is 100% translated before we deploy it, but I don't like reverting to unaudited/English after it's been released. We could potentially add some badges at the block or maybe just the challenge level, like mentioned, for when something new is added after a cert has been audited. Then we could check something like `if falling back to english && !challengeNeedsAuditing -> fail build` - or something like that maybe.

I dunno, we should probably do something with that validation for now. Some of these other solutions might take a little time to implement. I might just turn it into a warning log or something instead of a failed build until we come up with something better.

**Comment by naomi-lgbt** [comment]
Believe we can close this due to the CI added in #47116
