### ISSUE TITLE
Step 42 on the basic html course has a spelling error 

### ISSUE THREAD

**Issue by Shonki56** [freeCodeCamp/freeCodeCamp#45825]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-42

## Your code

```




```

## Expected behavior
Supposed to say though instead of through 

## System

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: Not sure

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed on `main` branch in #45789. This means that once the change goes through the deployment workflow, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
