### ISSUE TITLE
Improve definition for "Decimal" in Waypoint: Use Hex Code for Specific Colors

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4589]
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors) has an issue.

The definition for "Decimal" is . . . pretty bad.  The actual term should probably be "Base 10 Numbers".  Either way, the definition is clunky and needs a tune-up.

Current text:
>Decimal means the numbers zero through nine - the numbers that people use in everyday life. Hexadecimal includes these 10 numbers, plus the letters A, B, C, D, E and F. This means that Hexidecimal has a total of 16 possible values, instead of the 10 possible values that our normal base-10 number system gives us.

Maybe some improved verbiage and a "more info" link to discuss Base-16 numbering systems?

**Comment by rahulshinde235** [comment]
Float/Decimal is a term is used in various programming languages to define a variable with a fractional value. Numbers created using a float variable declaration will have digits on both sides of a decimal point. This is in contrast to the integer data type, which houses an integer or whole number.

**Comment by Darksmurf** [comment]
I think that we should include both definitions because the current one could be used to help get a user's head wrapped around the concept of Base-10 and Base-16 numbers. I think that it is important the a user understands the concept of base numbering systems, so we might also include base 2(binary) and the concept of counting with these new bases
