### ISSUE TITLE
Typo in legacy Build a Personal Portfolio Webpage, test 2 and 5

### ISSUE THREAD

**Issue by Shaylin-8bit** [freeCodeCamp/freeCodeCamp#45983]
### Describe the Issue

I'm not certain that legacy courses are still being up kept, but the 2nd and 5th tests have typos in their text. 

Second test:
> Your #welcom-section element should contain an h1 element.

"welcom-section" should be "welcome-section"

Fifth test:
> Your portfolio should contain at least one elment with a class of project-tile.

"one elment" should be "one element"

### Affected Page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

### Steps to Reproduce

Go to link, and scroll down to the tests.

### Recommended fix or suggestions

Just correcting the test text.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
