### ISSUE TITLE
Typo on Step 27 in Cafe Menu

### ISSUE THREAD

**Issue by DemonSlayer112** [freeCodeCamp/freeCodeCamp#46004]
### Describe the Issue

![image](https://user-images.githubusercontent.com/70122500/168688808-7f543700-9009-4890-9b47-3b9b9263ffb4.png)
I added "of"
It is missing orginally.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-27

### Your code

```

```
there is no code, just lesson typo

### Expected behavior

for the text to read "front _of_ it"

### System

- Device: Omen Desktop
- OS: Windows 10
- Browser: Chrome
- Version: version of?

### Additional context

Sry if the System section isnt very clear, its just a typo so i assume it doesnt matter all to much.

**Comment by Sboonny** [comment]
thanks for time, for typo errors feel free to open pull request directly with typo in the title. if you have questions about contributions or how to make pr feel free to check [contribution guideline](https://contribute.freecodecamp.org/#/). if you are stuck, or something is unclear, feel free to ask for help in [freecodecamp chat](https://chat.freecodecamp.org/channel/contributors)

**Comment by raisedadead** [comment]
Thanks for opening this issue.

It looks like this issue is something that "first-time" code contributors to this repository can fix. Here are the files that you should be looking at to work on:

List of files:

1. [`curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f356ed6199b0cdef1d2be8f.md`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f356ed6199b0cdef1d2be8f.md?plain=1#L10)


Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We prioritize accepting the most quality contribution, followed by the earliest request.

Happy contributing.

**Comment by hvinnieg** [comment]
i added it to my pull request

**Comment by DemonSlayer112** [comment]
No clue what to do to help with files or fixing stuff tbh, I'm still pretty new to all this GitHub stuff. Someone might be much better for this than I. But hopefully ill have the experience in the future to help with things like this, big or small.

**Comment by UCYLMZ** [comment]
I see that it's a perfect start for beginners like me, however using repo or GitHub is not easy that much :D. For this issue, finding correct challenge on my local files and fixing it is an achievement for me. I am excited for more. :)

**Comment by raisedadead** [comment]
@DemonSlayer112 @UCYLMZ 

Contributing to open-source is a rewarding experience. You get to learn so much, things like coding practices, collaboration skills, and most critically, working with folks you have never met (or most likely never will) in person.

We encourage you to participate, not just in this community but in many different open-source projects out there.

You got this!

If you need help, we are here to help you help us. All you need to do is get started. As I mentioned earlier, if you are interested, head over to the contributing docs and jump right in.

Cheers & happy coding.
