### ISSUE TITLE
Responsive Web Design exercise, Portfolio #navbar 

### ISSUE THREAD

**Issue by Itanglish1** [freeCodeCamp/freeCodeCamp#46041]
### Describe the Issue

The Test is not passing my code for the top fixed #navbar. Link to the files are here: Itanglish1/personal-portfolio-exercise.git .

It is working, but I might have something not working with the rest of the code.

Exercise is at the time of writing, not finished and missing queries.

Thanks

### Affected Page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

### Your code

```
#navbar {
    background-color: rgb(179, 58, 58);
    height: 7rem;
    text-align: right;
    padding-top: 2rem;
    position: fixed;
    width: 100%;
}
```

### Expected behavior

I expected the test to accept the outcome for the exercise, the part about the fix #navbar at the top of the page 

### System

- Device: Laptop Lenovo ThikPad
- OS: Ubuntu (latest at the time of writing)
- Browser: Chrome and Brave
- Version:

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
