### ISSUE TITLE
Code incorrect on step 28 new responsive web design

### ISSUE THREAD

**Issue by hvinnieg** [freeCodeCamp/freeCodeCamp#46088]
The closing > for the img element is missing

**Comment by ieahleen** [comment]
please expand, the various fields on the module to submit a bug should all be filled

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
