### ISSUE TITLE
manipulating complex objects file has too many `<dfn>`

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46142]
### Describe the Issue

here is [the file raw](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects.md) notice there are a lot of definition elements `<dfn>`, but there is lack of definition. 

Edit: the below paragraph is wrong check bbsmooth comment below.

I think this harming accessibility, because in [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn) it says that "indicate the term being defined within the context of a definition phrase or sentence", but we aren't defining them.

- [ ] [manipulating complex objects](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects.md)
- [ ] [create decimal numbers](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript.md)
- [ ] [caesars-chiper](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher.md)
### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects

### Your code

```md
Sometimes you may want to store data in a flexible <dfn>Data Structure</dfn>. A JavaScript object is one way to handle flexible data. They allow for arbitrary combinations of <dfn>strings</dfn>, <dfn>numbers</dfn>, <dfn>booleans</dfn>, <dfn>arrays</dfn>, <dfn>functions</dfn>, and <dfn>objects</dfn>.
```

### Expected behavior

Definition following the elements

### Additional context

I maybe overthinking like how I usually does, but I do think it's best to remove these elements.

**Comment by bbsmooth** [comment]
Technically, I think you are correct, these terms are not being defined and so they should probably not be marked up with the `<dfn>` element. As for accessibility, I doubt this has any affect on it. The Windows screen readers all ignore this tag and I'm pretty sure the Apple screen readers do to. This happens with a lot of elements. Screen readers also ignore `<em>`, `<strong>`, `<del>`, '<ins>', '<code>', ... I could go on. This doesn't mean you shouldn't use those elements, just that they won't have any affect on accessibility, and if it is important that a screen reader user knows why you used one of these elements then you have to tell them in some other way. But I don't think that is the case here. I don't think we need to do anything special with these terms. We could just leave them as plain text, or perhaps wrap them in `<em>` if we want them to stand out visually. And we could leave them as `<dfn>` and it won't affect accessibility at all.

**Comment by bbsmooth** [comment]
> The use of`<dfn>` is required in order to meet level AAA

SC 3.1.3 does not really say this. It says that a "mechanism" should be available for identifying specific definitions of words or phrases used in an unusual or restricted way. This mechanism can be a variety of things and does not require a specific HTML element. If we really wanted to meet SC 3.1.3 then we would have to either define each of these terms in the instructions or provide a link to their definitions. But I'm not sure that they would even fall under SC 3.1.3 in the first place because it applies to words or phrases "[used in an unusual or restricted way](https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/meaning-idioms.html#unusual-restricteddef) and these are all terms commonly used in web development. I'm not saying we shouldn't perhaps define some of these, just that SC 3.1.3 does not technically apply here.

Regardless, the `<dfn>` element is intended to be used when the definition is actually being given on the page, which we are not doing here, so technically it is probably not the best element to use. But as far as accessibility is concerned, it is not an issue (as I explained above).

**Comment by Sboonny** [comment]
> Certain disabilities make it difficult to understand nonliteral word usage and specialized words or usage. Certain disabilities make it difficult to understand figurative language or specialized usage

I think it's hinting about dyslexia and ADHD 🤔, true it being visually different helped.

My issue with `<dfn>` was that it may have harmed accessibility and I expected definition to follow it.

Luckily, I am wrong about accessibility, but there aren't need to use it with `em` existing, after all we aren't providing definition different from the docs' ones.

> but there aren't need to use it with `em` existing

Of course, there is no need to change it either, it isn't harming anyone, and my original intention is already fulfilled. I am okay with both changing them or keeping them👍

**Comment by Sboonny** [comment]
It has been 11 days, before the last activity. So, before I close this. 

We should decide either to change `<dfn>` or keep it.

If you wanna change, simply emote on this. If you are against it, simply ignore this, I will close it in 4 days.👍
