### ISSUE TITLE
"Ask for Help" button duplicates the code in forum post

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#46153]
### Describe the Issue

The "Ask for Help" button duplicates the HTML and CSS code when ported over to the forum.
This issue happens with steps/projects with multiple files. (e.g. index.html and styles.css)

### Affected Page

Any steps/projects with multiple files.

### Steps to Reproduce

1. Go to any step/project with an editor with mutiple files. [For example this one](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-2) 
2. Try submitting incorrect code until Ask for Help button appears
3. Click Ask for Help and create a post on the forum
4. See the code in the draft post

### Expected behavior

The code should not be duplicated in the forum post

### Screenshots

![image](https://user-images.githubusercontent.com/25644062/170331381-d10b68ae-495a-4529-800d-348613deb2d4.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 101.0.4951.67

### Additional context

I noticed it seeing the forum posts below and I could reproduce the issue myself.
https://forum.freecodecamp.org/t/step-49-cant-figure-this-one-out-its-so-simple-though/511630
https://forum.freecodecamp.org/t/why-the-image-is-not-seting-on-html-page/511638

**Comment by sidemt** [comment]
I initially thought it's happening with only HTML, but noticed that happens with both HTML and CSS. Edited the title and desc accordingly.

**Comment by bellhuffstutler** [comment]
So I can't dupilicate it if it only has the index.html file (i.e. on CatPhotoApp Step 1), it actually just posts everything normally. 

I have a hunch it has something to do with this: 
```
function filesToMarkdown(challengeFiles = {}) {
  const moreThanOneFile = challengeFiles?.length > 1;
  return challengeFiles.reduce((fileString, challengeFile) => {
    if (!challengeFile) {
      return fileString;
    }
    const fileName = moreThanOneFile
      ? `\\ file: ${challengeFile.contents}`
      : '';
    const fileType = challengeFile.ext;
    return `${fileString}\`\`\`${fileType}\n${fileName}\n${challengeFile.contents}\n\`\`\`\n\n`;
  }, '\n');
}
```

and i *think* it might be because it's calling ${fileString} and ${challengeFile.contents}, because if I'm reading the code correctly, it calls ${fileString} only on ones where there's just the one file, and it pastes correctly fine when there's just the one file. 

I would test, but I have literally no idea how to get the forum functionality running locally which puts me at kind of an impasse here

**Comment by bellhuffstutler** [comment]
It's just working now?? 

like it's not giving me the issue on any of the pages I am confusion
