### ISSUE TITLE
Colored markers step 60 fails on safari

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46233]
### Describe the Issue

[Step 60 of the colored markers project](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-60) fails in Safari. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-60

### Expected behavior

It not to fail.

### Additional context

https://forum.freecodecamp.org/t/css-color-marker-step-60/513020/3

**Comment by ShaunSHamilton** [comment]
@moT01 Which version are you using. I was unable to reproduce with: `5.0 (Macintosh; Intel Mac OS X 10.16) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.0 Safari/605.1.15`

**Comment by Nirajn2311** [comment]
I was able to reproduce this issue in Safari v15.5. I think this version breaks it and not v14.

**Comment by ShaunSHamilton** [comment]
Can either of you reproduce this for `49`, `60`, and `66`? They all use similar tests.

**Comment by moT01** [comment]
I'd rather not share my version... 13.1.2

**Comment by Nirajn2311** [comment]
> Can either of you reproduce this for 49, 60, and 66?

Yup, the tests don't pass for any of these challenges

**Comment by lasjorg** [comment]
I wonder if the support for the new color spaces (lab/lch/hwb) has anything to do with it? Did anyone check what value the helper is returning on that version of Safari?

https://developer.apple.com/documentation/safari-release-notes/safari-15-release-notes
https://bugs.webkit.org/show_bug.cgi?id=205675
https://caniuse.com/?search=lab()

**Comment by Nirajn2311** [comment]
The value returned by the helper is `background-color: rgb(0, 127, 0);`

**Comment by lasjorg** [comment]
So the value is correct just not the property.

```js
assert.include(new __helpers.CSSHelp(document).getStyle('.green').cssText, 'background: rgb(0, 127, 0)');
```

Is there a reason why we are checking `background` and not `background-color`?

**Comment by moT01** [comment]
The instructions for all three of those steps have you change the property from `background-color` to `background`.

**Comment by tugkankibar** [comment]
This issue is reproducible on any step that checks for `background-color` to `background`. It only seems to happen on Safari; as Google Chrome works normal.

Furthermore; it seems to be some magic regarding `background` property being transformed. In the following screenshots, you can see it happening;

<img width="1570" alt="Screenshot 2022-06-10 at 12 43 46" src="https://user-images.githubusercontent.com/5172699/173048998-1af47826-ee07-4524-a983-c3876b8af0a7.png">
<img width="802" alt="Screenshot 2022-06-10 at 12 44 47" src="https://user-images.githubusercontent.com/5172699/173049037-a80af160-8661-47a7-84bb-c88d86d50e83.png">

Even though we supply `background` as opposed to `background-color` on code; we end up with `background-color` on `.green`. Furthermore; for `background` property of `.red`; we suddenly have `background-image` as a replacement.

Finally; I've given a check into "a good old fashioned HTML file" to see if this is an issue with this project or Safari in general. What I could unearth was that; even when we give `background` property in this fashion; and we can see in dev tools as `background: red;` - the result in CSS side is `background-color: red;`!

**HTML used**
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        h1 {
            background: red;
        }
    </style>
</head>
<body>
    <h1 id="test">Test</h1>
</body>
</html>
```

**Result in Safari**
<img width="315" alt="Screenshot 2022-06-10 at 12 54 50" src="https://user-images.githubusercontent.com/5172699/173050487-f9e5cba3-e8f6-4acb-b7b2-697d96c020b6.png">
<img width="1018" alt="Screenshot 2022-06-10 at 12 55 31" src="https://user-images.githubusercontent.com/5172699/173050598-762d6e85-47fc-4cb1-8a6b-b98c07f00cca.png">

**Comment by lasjorg** [comment]
This has to be a bug. As far as I can tell, it is taking the shorthand property and expanding it into the longhand form(s) as if it was a computed property.


style
```
.green {
  background: border-box red;
  font: 1.2em "Fira Sans", sans-serif;
}
```

Safari:
```
.green { background-origin: border-box; background-clip: border-box; background-color: red; font-style: normal; font-variant-caps: normal; font-weight: normal; font-stretch: normal; font-size: 1.2em; line-height: normal; font-family: \"Fira Sans\", sans-serif; }
```
Chrome:
```
.green { background: border-box border-box red; font: 1.2em "Fira Sans", sans-serif; }
```

Pretty sure that isn't how the `sheet` property is supposed to work.

---

BTW, I just figured out you can test Safari (well WebKit) on Linux using the GNOME Web/Epiphany browser.

**Comment by bbsmooth** [comment]
Is it time to add a disclaimer to the steps with this Safari issue? We get a lot of people posting in the forum about this.

**Comment by moT01** [comment]
> Is it time to add a disclaimer...

I think I would use that as a last resort. There's a number of other issues like this, where a browser will have a different computed value than is expected. We adjusted our tests in those cases to allow the values from either browser. I think those ones were a little easier, but I would vote to do the same here. I doubt anyone will like this, but I think we may need to just regex this one - since we are asking to change `background-color` to `background`, but it's still computed as `background-color`.

**Comment by lasjorg** [comment]
@moT01 A bit unrelated, but how difficult would it be to switch (or just add) Playwright for the CI browser tests? It has support for Webkit.

**Comment by moT01** [comment]
I really don't know @lasjorg - I've heard ideas like that floated around before, but don't think there's ever been much of a real discussion around it. I don't know a whole lot about it, or what would be involved in switching to or adding it. There's probably some other staff who could elaborate more on it. Maybe @ojeytonwilliams or @naomi-lgbt. Feel free to open an issue if you want a more dedicated place for a discussion.

**Comment by naomi-lgbt** [comment]
I poked around with Playwright a bit, but nothing too in-depth. The testing API seems similar enough to Cypress that things should migrate well, but different enough that we'd be doing a lot of rewriting.

The Cypress team have finally started implementing Safari support (hooking in to Playwright's webkit driver, ironically enough) - so hopefully we can use that.

**Comment by naomi-lgbt** [comment]
Believe this was intended to close in https://github.com/freeCodeCamp/freeCodeCamp/pull/47262
