### ISSUE TITLE
Missing test in step 117 of city skyline project

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#46385]
### Describe the Issue

missing test in step 117 of city skyline project
the code in the file is like this
```
> # --hints--
> 
> You should add a `:root` selector to the media query.
> 
> ```js
> ```
```

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e993d.md

### Your code

```

```

### Expected behavior

The missing test should be added to the file

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
The test on [step 118](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e993e.md) would probably be similar to what we want. Maybe something like this: `assert.equal(new __helpers.CSSHelp(document).getRuleListsWithinMedia("(max-width: 1000px)")?.find(x=>x.selectorText === ":root");`

**Comment by JordanMooree** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

### Suggested change:
Add in the following test to [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e993d.md#--hints--) as found in Tom's [comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/46385#issuecomment-1149905948):

```
assert.equal(new __helpers.CSSHelp(document).getRuleListsWithinMedia("(max-width: 1000px)")?.find(x=>x.selectorText === ":root");
```
in-between `line 16` and `line 17` of that file I mentioned above.

---
Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
