### ISSUE TITLE
[Suggestion] Make the first zip line project less daunting

### ISSUE THREAD

**Issue by hughforsyth** [FreeCodeCamp/FreeCodeCamp#4650]
Summary: Add some more supporting notes/information to zip line 1, and/or introduce a "zipline 0" that is much simpler/more guided first.

Detail:
This might just be me but I found zip line 1 daunting, demoralising, probably a bit soon (or too late [1]), and a bit ambiguos too [2]. 
http://www.freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage

I seriously considered abandoning FCC at this point and doing something else. Not because it was hard, more that it felt wrong or out of place and that reflects on the entire curriculum/FCC. It was kind of jarring and I wondered if I'd clicked a wrong link or something. It suddenly made FCC feel incomplete or ill thought out I suppose. Up to that point I'd been really impressed with how thorough everything felt.

I'll get over it (and maybe that's the point) but I worry that you might be losing people at this stage who could go on and complete with a little more info/support. 

I understand that one of the main lessons of FCC is how to use google and chat to find answers (and have asked some things) but I think the very 1st zip line should have little or nothing that was not included in the coursework. It feels a little more like a test of google skills rather than solidifying the course content at the moment.

I also get that unclear user requirements/ambiguous briefs are quite common in the real world (and I might just be overthinking/misinterpreting the instructions) but it's perhaps too soon for that lesson too.

I also know some of this is just the shock of a blank canvas, but again, I think you should ease people in on the very first project, as it feels too soon in the process for that lesson too.

Possible ways to address this are:

1. Do nothing. Most people are fine and it's just me. People are obviously getting through this so it may only affecting a few people.

2. Add an optional "zip line 0" that is much more tutorial like. This could be unmarked/not assessed but great for people not confident/experienced enough to dive straight into zip line 1. Or perhaps it could just be part 1 of zip line 1, e.g., how to build the sample Codepen that you provide for cloning, or the top 2 sections of the page. You can then build on that in zip line 1.

3. Or maybe add more info for the existing zip line 1. Perhaps a Wiki page/video that provides hints or a more detailed explanation of what is required, e.g., "getting started with zip line 1",  use these fonts, use these images, this is how to do a nav bar, this is how to get images for buttons if they don't exist in glyphicons, how to do full sized image backgrounds, "use whatever fonts you want/you must use at least one google font", "you must use at least 1 full sized image background", etc.. 

The video's great and tells me I don't have to use his images but perhaps extend it by a couple of minutes or add a part 2 to expand a bit more on the requirements, or a link to a "hints" or "more info" wiki page for those who are stuck or unclear.

Notes:

[1]: I wonder if it might have been less daunting if it had appeared straight after the bootcamp modules rather than about 60 hours later. In zip line 1 there isn't really any need to use jQuery, Javascript, basic algorithms or object oriented functional programming so theoretically it could be moved forward to straight after the bootcamp module.

If it did stay where it is now, the end of the bootstrap modules could be a good point to introduce a new "zip line 0" too, e.g., a simple CodePen to build part 1 of the portfolio project. 

[2]: Some of the ambiguity may be overthinking on my part or "a little knowledge is a dangerous thing", i.e., I'm worrying about things that others might not. In no particular order:

a) Will this be marked/assessed and if so when? I assume it will at some point as zip lines are mandatory for certification and you ask for the Codepen URL. I assume later as there's an option for immediate feedback (and it would make sense to only assess people when they've completed everything). "Verified Front End Development Certificate" suggests that somebody will verify this at some point, on the other hand "sign our Academic Honesty Pledge" suggests it might be done on trust. This is not about cheating BTW, it about whether it's worth leaving this for now and coming back to it later.

b) What constitutes a pass? I suppose this is the definition of "personalization" and "reverse engineer". Or how lose if the brief? I've done things in the past where you'd be marked down for having a few pixels out of place, others that were more loose. Is default bootstrap formatting okay? Do fonts have to match? Do buttons have to have images? Does styling have to match? Do you have to have full sized background images? Do the portfolio items have to have overlaid text and a hover effect? Parallax yes/no? Is "view source" classed as cheating (vs looking at the Codepen source that is forbidden)? Is the idea to learn by looking at his source? 

I could go on but I think it would be helpful, especially for beginners, of this was a bit simpler.

Thanks

**Comment by hughforsyth** [comment]
Update after doing Zipline 2 which is much clearer. 

In the Zipline 2 video (Random Quote Generator) it mentions the assessment/feedback process, i.e. at 1:18 its says, 

> "So when you are finished just click this button and it will go ahead and tweet this out and let us know we need to review it, otherwise we'll just take a look at it before you move on to your non-profit projects".

It would be helpful to include that info somewhere in the wiki/FCC site and more importantly on Zip line 1 too. Perhaps linked from.  
> "If you'd like immediate feedback on your project from fellow campers, click this button and paste in a link to your CodePen project."

Or it could be included as text elsewhere on the page, e.g., there's space under the video and "help"/"bug" buttons that could be used for notes without wrecking the page layout.

On a related point I'd say those two statements are implying slightly different outcomes.

The text on the page suggests that "fellow campers" will take a look which I'd guess meant other FCC students giving unofficial advice rather than FCC staff. 

The text in the video says "we'll take a look" suggesting FCC staffers rather than other students (if there is a difference in this context).

**Comment by SaintPeter** [comment]
Thank you for your detailed feedback.  There is a lot here, so let me touch on some points:

1. We are definitely aware of the rather sharp ramp up in difficulty.  This is a non-trivial problem to solve, because at SOME point there will need to be a "blank page" challenge.  We do plan to have more, smaller "blank page" type problems earlier in the curriculum, interspersed with the actual content.  
See also this interesting article about [Why Learning to Code is So Damn Hard](http://www.vikingcodeschool.com/posts/why-learning-to-code-is-so-damn-hard) - I believe the "Cliff of Confusion" accurately describes the start of the Bonfire and/or Zipline challenges for many.

2. With regards to feedback - we also have a [CodeReview Chat Room](https://gitter.im/FreeCodeCamp/CodeReview?utm_source=share-link&utm_medium=link&utm_campaign=share-link) and a [HelpZiplines Chat Room](https://gitter.im/FreeCodeCamp/HelpZiplines?utm_source=share-link&utm_medium=link&utm_campaign=share-link).  It's fairly common to see users post their projects in one of those and get detailed feedback from one or more campers.  Response can be varied, so posting at a different time may be good.  I've opened an issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4699 to note that we need to explicitly call these places out as a resource.

3. What is good enough and when are you done?  I think this is and should probably remain a nearly purely subjective judgement.  The only hard and fast requirement is that you fulfill all of the non-bonus User Stories.  You can be as creative or derivative as *you* want to be.  There will be no judgement except as to if you have fulfilled the user stories and did your own work.
Ultimately, it will be YOUR resume that has these on it (or not).  If you're comfortable letting perspective employers look at your work and you believe that it is the best work you can do with your level of knowledge, then perfect.  
Personally, Ziplines have been my favorite part of the curriculum, since I figured that I'd get out what I put in, so I chose some personal goals to stretch myself a bit.  You can see [my profile here](http://www.freecodecamp.com/saintpeter).  
Takeaway from this discussion, though is that we need to communicate this better to our campers.

I've pointed this feedback out to @QuincyLarson.

I'm going to close this as an issue, since we are aware of these topics, but I'm happy to continue this conversation here if you have additional points you'd like to cover.

**Comment by hughforsyth** [comment]
Thanks. 

Being partway through zip line 5 an important takeaway is that the very first zip line needs to be the clearest defined in terms of requirements and understanding the FCC. I've had no issues with 2-5 as it's been clear what is required. I just didn't get that from zip line 1.

Referencing Quincy's article, I'd also argue that for zip line 1 "The cliff of confusion" and "desert of despair" should solely be inspired by the "coding is hard", "blank pages are hard" type concepts that Quincy describes in his article. Not so much "I don't know what you are asking me to do, what happens next, I don't know if you are going to mark this or when, I don't know how close to the example it has to be, I'm not even sure what a zip line is?, etc.". There's enough to worry about with the "blank page shock" without adding "how FCC works" confusion.

I guess my point is that if page 1 of http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines was a slightly edited version of your comments here, and perhaps some copy/paste from Quincy's Quora answers, it would be a much clearer process, e.g., "The only hard and fast requirement is that you fulfill all of the non-bonus User Stories. You can be as creative or derivative as you want to be." is great and could be added to the zip line page.

Re the difficulty, I'd still argue Zip line 1 might be better situated in the "Hand holding honeymoon" phase" or you are going to get more people than necessary splatting at the bottom of the cliff. I guess that will be addressed by smaller blank page problems you referenced in your answer. Zip lines 2-5 are blank page enough and induce enough fear (although I enjoyed them).

Thanks again.

**Comment by keponk** [comment]
read through this whole conversation. I fully empathize with @hughforsyth comments on how I felt after reading. I went Ctrl+Ener expecting the real explanation to come up after that. Since the next thing was the phrase gen and it sounds more feasible I assume the previous page was just an example of what will the last excercise look like. It still felt wrong so I googled my concen and reached this page.

Thanks @hughforsyth for making me feel less dumb. I think many others will feel like me as well.

**Comment by willnwhite** [comment]
Yeah, at least you don't have to do the challenges in order.

**Comment by Sydney-Cook** [comment]
I'm waiting to make my portfolio page until the end of the ziplines. I want to make the zipline pieces functional that require JavaScript, then I plan to go back and make everything including my portfolio page be as uniform as possible such as using the same font, colors, styles, etc... The design part is much easier for me then some of the mind numbing code. I'm really a noob at JavaScript, so for me it's harder. I do think the portfolio page should be re-created a different way or there should be an option to follow along at some point if somebody wanted to. I think Free Code Camp is by far one of the best online tools to learn web technology by far.

**Comment by olddognewtrix123** [comment]
I have indeed experienced this sense that each new challenge is exponentially more difficult than what came before while working through the FCC challenges. But this has always proved to be a short-lived feeling.   Sure, you are in a "valley of darkness" for a little while if you are new to coding and starting out on one of these projects. And it takes an hour or a day or even sometimes a week to pass through on each project. But it always comes to an end and the solution always reveals itself to the seeker. 

(I am at the tail end of the data viz projects so far, btw)
