### ISSUE TITLE
New RWD : Media Queries aren’t explained

### ISSUE THREAD

**Issue by Bharath314** [freeCodeCamp/freeCodeCamp#46579]
### Describe the Issue

In [step 20](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-20) of Learn CSS Flexbox by Building a Photo Gallery, we are asked to create a media query. However, media queries are explained neither in this challenge nor the ones prior to it. A brief explanation would be less blunt.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-20

### Expected behavior

A brief explanation on what media queries are and how to use them would be a good idea, even if they explained in later sections.

### Screenshots

![image](https://user-images.githubusercontent.com/69413757/174579003-8d1ff53b-5535-4892-821e-e67a55a724d6.png)

**Comment by Sboonny** [comment]
I remember a forum post, in which someone used `@media` as a value, I do vote for changing the description. 

Here is an example

> when your screen is smaller or larger than your media query break point `width` of `800px`, you can change the style of your property `#gallery-img`, to fit the new screen.

**Comment by Bharath314** [comment]
We also have to include a description on what media queries are and their syntax. They aren't explained in previous challenges.

**Comment by lasjorg** [comment]
@ShaunSHamilton I don't see why we even need media queries for this. Part of what makes flexbox awesome is that we often do not even need media queries. Willy-nilly throwing in media queries without any explanation of how they work and just a syntax example seems a bit odd to me.

I should have a PR for this that just uses the flex-wrap for the responsiveness. But in my infinite wisdom, I started changing things I shouldn't have which made it more work than it needed to be.

**Comment by lasjorg** [comment]
@ShaunSHamilton Why are we using the images we are? They would appear to be promotional images for a website that doesn't seem to exist anymore. I think we should replace them with some freeCodeCamp images.

https://mobile.twitter.com/devalertme

@bbsmooth The images are very random and non-specific most are commercial in nature. I might wait and hear what people have to say about replacing them. Then give the images a descriptive `alt` text.

**Comment by nhcarrigan** [comment]
These images were used in the demo on the curriculum expansion repo.

I'm more than happy to replace them.

**Comment by lasjorg** [comment]
Half of them are promoting what I would view as a third-party product. I can't see that being intentional.

I know there are some images from freeCodeCamp meetups, maybe that would be something we can use for this?

**Comment by nhcarrigan** [comment]
@ShaunSHamilton has a decent approach in some of the tests where the test expects a value, the hint text suggests a value, and then the seed code uses that value.

**Comment by lasjorg** [comment]
@nhcarrigan But we have no expected or suggested values if the user can set whatever they want as the value, right?

It seems the easier option is to just remind the user that the images should have an `alt` text and leave it at that. But if anybody has a good idea for this I'm all ears.

**Comment by nhcarrigan** [comment]
We could assert specific values after we land on some new images.

**Comment by ShaunSHamilton** [comment]
For other practice projects, we assert things like:

> Your `title` should contain some text.

> Your `title` should contain at least 10 characters.

----

So, I imagine we could just:

````markdown
You should give all the `img` elements `alt` text describing the image. _Hint: You could use `lasse in the park`._

```js
assert.notEmpty(img.alt);
```

You should give all the `img` elements `alt` text of at least `5` characters.

```js
...
```
````

**Comment by lasjorg** [comment]
@ShaunSHamilton Sounds like a plan 👍

> ```gfm
> _Hint: You could use `lasse in the park`._
> ```

I think you have me confused with someone who leaves his apartment :rofl:

**Comment by lasjorg** [comment]
@ShaunSHamilton Wait but what about the seed code? What should I put in the seed code for the following steps?

**Comment by ShaunSHamilton** [comment]
> What should I put in the seed code for the following steps?

`alt="lasse in the park"`

Here are some ~~examples~~ example: 
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6133acc353338c0bba9cb553.md
-

**Comment by lasjorg** [comment]
@ShaunSHamilton I don't get it. I know we can test for the attribute and also test the string length (not that I see a length test as very useful). But if we didn't specify the content by letting the user create their own `alt` text how can we add that to the seed code in the following steps? We can't just use the same string for all of them, that would make the `alt` text incorrect.

I think the best we can do is use an empty string, or specify the `alt` text for them. But I worry that requiring specific `alt` text for all the images will break the flow of the challenge and be a bit boring.

---

I'm honestly thinking of just adding the `alt` attribute as the requirement but not the text and just adding an empty alt text for the following steps seed code.

**Comment by ShaunSHamilton** [comment]
@lasjorg Well, we can just make it the final step.

The reason we have some tests checking for length is to try force Campers to think about the values they are using

**Comment by bbsmooth** [comment]
OK, don't know why this didn't come to me earlier? I don't think it is a good idea to ask campers to create their own alt text for these images because that assumes that they can see the images in the first place. I think we either need to give them the alt text to enter or just don't do alt text for these in the first place and add a note explaining that this is intentional and that you would normally have alt text for the images.

**Comment by lasjorg** [comment]
> Well, we can just make it the final step.

That is probably the best option. We don't have any seed code to worry about and it won't break the flow of the challenge.

@bbsmooth How does a visually impaired developer add `alt` text? Is this not as good a time as any to test that part of their workflow?

**Comment by bbsmooth** [comment]
@lasjorg They would use the `alt` attribute just like anyone else would. My point was that we can't just ask them to add alt text for an image without them knowing what the image is in the first place. Unless we are going to explain what each image is then it isn't really reasonable to expect someone who can't see the image to add appropriate alt text. Or are we expecting them to find someone who can see the images and explain it to them?

**Comment by nhcarrigan** [comment]
I remember reading that `alt` attributes could be omitted for images that were purely decorative and did not convey any relevant information. Is that an approach we could take here?

**Comment by bbsmooth** [comment]
@nhcarrigan Yes, purely decorative images should have empty alt text, but seeing as this is a photo gallery app and it exists purely for the purpose of showing photos I'm not sure these photos are decorative :-)

**Comment by Sboonny** [comment]
What about converting them to SVG? Image gallery is good place to take about different graphic format.

**Comment by bbsmooth** [comment]
I guess it depends on what you consider the purpose of this course and this particular step to be. To me, the purpose of this course is learning flexbox, not creating a photo gallery, so I don't see the images themselves as an integral part of this course and thus I don't think a camper should need to get assistance from someone else in order to create appropriate alt text. Also, I think people who can't see  images already know that they will need help creating acceptable alt text and we probably don't need to teach them that or help them figure out how to do that.

I'm working under the assumption that these courses are intended to be able to be completed by someone on their own. Yes, they can ask for help in the forums if they need it, but that isn't a requirement. Asking people to write acceptable alt text on images they can't see violates this principle. And the forums are not an acceptable alternative because then it basically forces someone to disclose they have a disability, which is something you don't want to do. So I think we either need to give all of the information needed to complete the step (i.e. give them the specific alt text to enter) or just don't include the `alt` attribute with a disclaimer as to why.

**Comment by lasjorg** [comment]
I feel like we are getting into some chicken and egg territory. We want developers to use alt text for accessibility. We need to teach them this. If we don't teach them this because the developer might be visually impaired then who are we really hurting here? It strikes me as a bit ironic to skip this requirement because the user might be visually impaired.

Maybe we can add a note?

> Note: If you are visually impaired you may add any text you'd like for the alt text if getting help with this isn't an option.
> 

I mean it's not like we are checking the text anyway, we can't unless we use a specified alt text.

@bbsmooth I understand the point you are making and I agree this isn't the main focus of the challenge. I also fully understand that creating the alt text would be much more difficult if you are not able to see the images. But it seems to me to be something we have to consider how to best deal with and just skipping the requirement doesn’t really solve it, it just pushes  it aside.

**Comment by bbsmooth** [comment]
Yes, anytime you require images to complete a course you are going to have this dilemma. 

If we are concerned with being 100% accessible here (not just in the HTML itself but also usability) then I think the correct way to do this is to give the user the alt text to enter for each image. Otherwise, we are going to have to make some decisions. The other options I've seen suggested so far are:

1. Don't add the `alt` attribute at all with a note explaining why
2. Let the user add whatever they want for the alt text and then either a) replace what they entered with our own alt text OR b) use empty alt text for all subsequent steps.

I think 1 is acceptable because the note will explain that alt text for these images is required but is being left out intentionally, but I can understand that some would rather have the `alt` text in there. If 1 is not acceptable then I think 2a is the best solution since it will be actual accessible HTML with proper descriptive alt text. The issue with 2b is that empty alt text should only be used for decorative images (which these are not) and thus you are going to have to explain why the alt text the user entered suddenly disappeared and why empty alt text isn't acceptable in this situation and why we are using it here. So we are back to adding a disclaimer similar to option 1.

If we do go 2a, then I do like your suggestion of including a note letting people know that the alt text can actually be anything. But I would change a few things. I wouldn't target it just to visually impaired people since there is a possibility that someone may not be loading images intentionally in their browser. Also, I would definitely drop "if getting help with this isn't an option." I'm not saying this was your intent, but I can definitely see someone taking that as slightly condescending. Maybe something more like:

"Note: If you are unable to view the images you may use any alt text you like."

Here's an idea. We will need to add a new step to the course for adding the alt text since you can't add the alt text until you can see the images. Perhaps we can add it as the new last step? Then we just need to test that they actually added some text for the `alt` attribute but we don't need to concern ourselves with what they added and we wouldn't need to worry about what to do with the `alt` text on subsequent steps. Kind of solves all of these problems at once.

**Comment by Sboonny** [comment]
I will be honest, I don't think someone who want to contribute will read 30 comments, so I am adding one more. So are we 
going to change this to `flex-grow`, `flex-shrink`, and `flex-base` test using lasjorg example

> ShaunSHamilton I don't see why we even need media queries for this. Part of what makes flexbox awesome is that we often do not even need media queries. Willy-nilly throwing in media queries without any explanation of how they work and just a syntax example seems a bit odd to me.
> 
> I should have a PR for this that just uses the flex-wrap for the responsiveness. But in my infinite wisdom, I started changing things I shouldn't have which made it more work than it needed to be.

Or we stay with `media`.

> Thank you for taking the time to open this. Here is the recommended change:
> 
> In `step-020` for `learn-css-flexbox-by-building-a-photo-gallery`, add the following:
> 
> ```gfm
> A media query can be used to change styles based on certain conditions, and they look like this:
> 
> ```css
> @media (condition) {
> 
> }  
> ```
> ```
> 
> **ALSO**, in `step-114` of `learn-css-variables-by-building-a-city-skyline`, remove the same.
> 
> An issue with the _help wanted_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.
> 
> If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/
> 
> If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by lasjorg** [comment]
1. I will defer the `alt` text decision to whatever consensus we can come to. I have already added it as the last step (we had two leftover steps that used to be for the media queries which I have used for this and one other thing so the step count remains the same). I also added the note suggested by @bbsmooth, thank you for that. As it is the last step I can easily remove it if need be.
2. We need new images. I know Quincy has helped us before so maybe we should ping and hear if we have any freeCodeCamp images that are available for public usage. Otherwise, we can just pick some public domain images. I would have preferred to test the code with the new images just to be sure but I guess it isn't strictly necessary.

The PR is pretty much done. I think the challenge as it stands is more a dip your toes than a flexbox deep dive anyway. I did sort of want to expand it a bit more but I haven’t figured out how to do it with so few elements on the page and I don’t really want to start changing everything again.

**Comment by bbsmooth** [comment]
@lasjorg Dealing with the `alt` attribute on the last step seems like a winner to me! Also, just because we are on this topic, check out the `alt` text on this gallery: https://leedswf.co.uk/gallery/. No need to look at more than one image, they are all exactly the same.

**Comment by ieahleen** [comment]
That seems a really useful alt text... ok, so this seems to be going in the direction of fixinf half of #46538

If you need my opinion I vote for descriptive alt text, even if we have to give the user the text to use.

**Comment by Bharath314** [comment]
I vote in favor of having alt text too. It's better to build good habits earlier on in budding developers. What's the consensus on the media query? Will it be dropped then.
