### ISSUE TITLE
Confirmation modal on signing out

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#46623]
### Is your feature request related to a problem? Please describe.

In the menu on `/learn`, I keep clicking "Sign out" accidentally instead of "Change Language" while I'm working on translation. I wish there was a confirmation modal to prevent that.

I don't know how many users change the language setting frequently, but I would often switch between 2 languages when I read a translated website as a user.

### Describe the solution you'd like

A confirmation modal before signing out would be useful.

### Describe alternatives you've considered

Moving the sign out button to somewhere else?

### Additional context

The current menu dropdown is like this:
![Clipboard - June 21, 2022 10_29 PM](https://user-images.githubusercontent.com/25644062/175064119-605d506e-fcfa-496e-b06c-ec6918e32117.png)

**Comment by ShaunSHamilton** [comment]
If we do anything, I prefer the suggestion to move the "Sign out" further from "Change Language".

That is to say, I am very much against adding a modal to confirm you want to sign out.

**Comment by ahmadabdolsaheb** [comment]
@ShaunSHamilton the modal seems like a convention. Is there a reason why you don't prefer it?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Personally, I dislike.

My bank does this thing where, after clicking "logout", it takes you to a new page (you are still signed in) so they can show you an advert. I then need to click a very small "Continue to logout" button in order to actually log out. This infuriates me, and the modal is its next equivalent.

I am not sure how much of a convention it is? I do not expect it, and could miss the need to confirm - on a public PC, in a rush to leave, click logout, but am not logged out.

---

If we decide to have the modal, can we make the logout automatic after `x seconds`?

**Comment by ahmadabdolsaheb** [comment]
Thanks for the feedback Shaun. A small inconvenience is intentional just to make sure users are doing what they think they are doing. I think we can initially adopt the modal convention and add the seconds as a follow up feature if needed.

**Comment by bbsmooth** [comment]
I like both the suggestion to put more space between the Sign out button and Change Language and adding a confirmation modal. If I had to choose one I would start with extra spacing. 

Another option would be to have a Sign out button in the upper right and remove the sign out option from the menu, just like we do with the Sign it button, but I understand that we also have the avatar icon link in the upper right as well so there might not be enough room for that.

A different highlight color for Sign out is fine too, but my guess is that this isn't necessarily a problem with people not realizing that they are clicking Sign out instead of Change Language but rather that they just accidentally have the mouse cursor over Sign out when they click the mouse (perhaps because they are moving the mouse so quickly that they accidentally overshoot the Change Language option). Putting more space between the two would help with this, which is why it is my first choice.

**Comment by ahmadabdolsaheb** [comment]
Spacing seems to be an issue across our layout specially in the main navigation and the dropdown menu.
Introducing spacing in a dropdown does not seem to be a common practice; however, we could increase the height of each item to make the clickable area larger so the items are not mixed up.

**Comment by Sboonny** [comment]
raisedadead, mentioned good points about automating the signing out, function and I can't find the original text about automating it, so I think this is pure misunderstanding on my part and I could have closed this issue while back, sorry about that

https://github.com/freeCodeCamp/freeCodeCamp/pull/48385#issuecomment-1303087398
