### ISSUE TITLE
Brownie Points - Give points for time-on-site, Rescale points

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4676]
### Points for Time on Site
We want to encourage users to Always Be Coding, so we should give points for time spent active on the site working problems.  One brownie would be added for every given time period (15 minutes?) that the user spends actively working on a waypoint/challenge.  

However, if we're going to be granting points for time on site, we need to scale the points of other activities to give them the appropriate weight.  

Note:  we should do some due diligence to ensure that actual "activity" is occurring, we shouldn't stress too much over it.  Brownie Points are a simple incentive and, ultimately, not "worth" anything.

### Proposed values

Activity | Points
------------ | -------------
Active Time on Site (Per Unit) | 1
Waypoint | 1
Camper News Upvote | 1
Thanks on Chatroom | 5
Bonfire | 15
Zipline | 50
Basejump | 150

These are very rough values and open to debate.

### Transition
Users will keep all points they have already received.  We will re-reward all points at the new level on top of existing points.  This will reward people for the activities they have already completed, while setting the overall scale properly for points generally.

**Comment by alan1001110** [comment]
@SaintPeter  Did this spring from a discussion elsewhere? 

One could take various approaches for how to give points. Personally, think there is value in trying to match the reward with the perceived effort/pride/value of the activity.   Here's how I would value my own perceived effort/pride for the items I've done:

Waypoint: 1
Receive Camper News Upvote: 1
Receive thanks on Chatroom: 5
Bonfire: 15
Zipline	: 150
Basejump: Haven't done any.

A couple other thoughts:

Giving points for time could have unintended consequences.  One issue is that someone who is slow to complete challenges would get more points per challenge than someone who is more efficient.  Also, some people prefer to work through challenges outside of the FCC editor, and then paste in their code.  On the flip side, with an introduction of points for time, people who are particularly motivated by points could also start doing strange things like working on scripts for their own side projects inside of the FCC editor etc.   Lastly, I think I would find being rewarded for the time spent working on a challenge a bit of a  disincentive.

Also, I doubt it's worth choosing points differently for each challenge, but external tutorial waypoints can be much more involved than the FCC content waypoints since they often lump multiple lessons into one waypoint. They are almost the only thing that don't fit nicely into point categories.  I suppose external tutorials could have their own category, and be called something else.  "Hikes" or "outings" or something similar could  be an appropriate name.

**Comment by alan1001110** [comment]
Maybe more like 10 for bonfires, 100 for ziplines.

**Comment by SaintPeter** [comment]
Yeah, this sprung from a discussion I had with @QuincyLarson and @BerkeleyTrue about points and rewards.

I am not solid on the point values, especially for the later values.  I could easily see Ziplines as 100 or 150.  We'd just have to scale the Basejumps separately.

I agree that it does have a paradoxical effect of giving fewer points to someone who is "less efficient", but I would argue that those are exactly the people who need more motivation to keep going.  Efficiency is it's own reward :wink:.

I'm not sure that we're going to care too much about people who game the system.  The points are, at some level, meaningless.  They only have value if you value them.  I can get a saved game editor to alter the score in a game I play, or an invulnerability hack to kill the top boss with with a pencil and a piece of string . . . but I'm not bragging to my friends about my amazing feats.  

For example, I think that people who help out in the /Help channels earn the respect of others not by the amount of points they've gotten, but by the people they've helped in doing so.

**Comment by alan1001110** [comment]
To me, it doesn't make sense to give out points for being slow.

**Comment by Narshe1412** [comment]
Rather than activity in the site, should be chat activity. Even talking about the weather contributes toward relationship building and rapport. Spending 10 hours in the same exercise does not and could encourage the wrong behavior.

**Comment by matty22** [comment]
@Narshe1412 Couldn't the flip be said of rewarding spending time in the chat rooms? The chats are great and I often hang out in there to help others and get help for myself, but rewarding brownie points for overall chat activity encourages people to hang out in chat which is of ancillary importance to being in a challenge and coding.

Rewarding brownie points for time on site actively coding gets more and more hairy the further along in FCC you get. People working on the first set of Ziplines are probably spending the majority of their time in CodePen or a local text editor. Those even further along are probably working entirely in their own local development environment and logging into FCC just for submitting code.

Though, it's probably true that people who have made it that far, aren't the ones who brownie points are targeted at, there is some amount of weight carried by your brownie point total. If someone in chat provides feedback on a Zipline project and their brownie point total is 1500, it's likely that his/her opinions and critiques will carry more weight than someone who has 200 brownie points.

Personally, I can see it both ways. Keeping brownie points the way they are today, you can look at someone's total and have a pretty good idea of where they are in the program and/or how helpful they have been in chat. 

With the proposed change to reward brownie points based on time on site, you'll still be able to look and have a general idea of where someone is in the program and/or how helpful they have been in chat, the window might just be a little wider and fuzzier around the edges. And, you get the added benefit of encouraging those campers who might be struggling with the beginning Waypoints and (especially) Bonfires. Even if they aren't completing challenges, they are making progress by learning through their struggles and are being rewarded for that.

**Comment by Narshe1412** [comment]
You are right. Unfortunately I haven't reached Ziplines yet to see how time consuming are. I do however consider that engaging with the community should be rewarding, somehow. It's very nice for when you need to have a break and just have some chit chat :)

**Comment by QuincyLarson** [comment]
I'm late to this discussion, but I think this is an important issue and eager to chime in.

Here's why I think it's important that we give points for time on site:
1. If you're working hard, you shouldn't lose your streak just because you couldn't complete a Bonfire in time. In practice, most campers are quite busy and have less than an hour a day they can dedicate toward working on Free Code Camp.
2. We want to encourage people to grapple with the coding challenges. By giving them points, we're tacitly telling campers it's OK to stick with it, and their efforts will be rewarded regardless of how long they choose to take.

I agree with @SaintPeter that we don't need to reward campers for going faster. These campers will ultimately get more points anyway, as they'll be able to get significantly more brownie points by helping people.

### Proposed values

Activity | Points
------------ | -------------
Active Time on Site (Per 15 minutes) | 1
Non-project challenge | 1
Project challenge | 50
Camper News Upvote | 1
Thanks on Chatroom | 10

This weighting assumes that all projects take about the same amount of time, which isn't actually true, but I think it's easier to remember. It's more important for this system to be as simple as possible.

We want Thanks on Chatroom to be by far the most time-efficient way to earn points.

Also, regarding some of the insights that @alan1001110 brought up, yes - these projects are done on external sites (for now). Since they have larger point values associated with completing them, you could say that the "time spent" is baked into those extra points.

**Comment by SaintPeter** [comment]
We definitely have more projects now than we did when we first had this conversation.  I still think the original Basejumps are "worth" a lot more than 50 points, but it's probably not worth the trouble to come up with the code to handle the special cases.

Looking at the code, all of the front end projects have a challenge type of 3 ("Zipline") and the back end projects are type 4 ("Basejump").  Should be easy enough to add some code to detect the submit and give appropriate points.

**Comment by SaintPeter** [comment]
Are we sure we don't want "Algorithm Challenges" to have an additional value?  I know that these are still a significant time investment for many campers.  While they are likely to get more points from "time on site", I think they ought to be worth more.  They're also distinguished by a challenge type of 5, making them easy to add points for.

**Comment by pradeepce** [comment]
Here are two methods I think would probably work:

**1.** Since Ziplines and Basejumps take a bunch of time, is it possible to give them more points like discussed (say, 50 or 100) but _distribute_ the points over a period of time (4 or 5 days, say)? That way, if I'd been working on a Zipline for a couple of days, I can still keep my streak.

**2.** Keep the current points setup as such, and add a note advising users to continue working on their waypoints while hacking on their Ziplines in parallel. This ought to help them improve their projects as they learn more, and teach them about working on different things simultaneously.

-

IMHO, awarding points for time spent on the site attracts unethical behavior, and as @alan1001110 mentioned, has unintended consequences. 

Can you please consider having a combo-reward / bonus-points kind of system instead? For example, if a user progresses through 10 or 20 waypoints in under an hour, give them 5 points as a bonus. For every day a user maintains his streak, give them a point. For every 10-day streak, give them a 10-point bonus.... and so on.

I think this will encourage campers to show up to code daily, and work consistently.

**Comment by qmikew1** [comment]
What about optional points?

Some of the earlier comments have good points regarding 
folks gaming the system (which in the scheme of the universe for
points that don't have *value, isn't the biggest deal) with challenge/session
time. 

Not so much for the easy challenges, but for the more complicated stuff (i.e., 
Bonfires, Ziplines, Basejumps) maybe including an optional survey (with point incentive -only
available when challenge is completed) might work vs. session activity. 

Why?

Because even if users put 'blah, blah' to questions like:
1. What did you learn?
2. What was the greatest challenge?
3. What could be improved?

You'd have (or eventually would have) a sample for analysis (and maybe get insight apart from the 
original intent).

*Points. - Just wanted to comment that sometimes this (generally concepts in competitive psychology) can be a disincentive (but, yes there are clearly advantages) to learning. As a camper, I like the "go at your own pace" vibe within the curriculum - (as mentioned in other comments people have different amount of time to devote) - I think it's a plus.

**Comment by BerkeleyTrue** [comment]
We've abandoned this idea.

Happy Coding
