### ISSUE TITLE
Dead Code in Example

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46813]
### Describe the Issue

We have code that does nothing in this example.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups

### Your code

```javascript
const alpha = {
  1:"Z",
  2:"Y",
  3:"X",
  4:"W",
  ...
  24:"C",
  25:"B",
  26:"A"
};

alpha[2]; // This does nothing
alpha[24]; // This does nothing

const value = 2;
alpha[value]; // This does nothing
```

### Expected behavior

We should update the example to include meaningful example code.

Perhaps:
```javascript
const alpha = {
  1:"Z",
  2:"Y",
  3:"X",
  4:"W",
  ...
  24:"C",
  25:"B",
  26:"A"
};

const thirdLetter = alpha[2];
const lastLetter = alpha[25];

const value = 2;
const valueLookup = alpha[value];
```

### System

All

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Dhruv-Gajjar** [comment]
I would like to work on this issue.

**Comment by ieahleen** [comment]
Welcome @Dhruv-Gajjar, as described in the documentation, issues are up for grubs, they are not assigned, so feel free to work on it.
