### ISSUE TITLE
There is no Ryan

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46815]
### Describe the Issue

The challenge text mentions Ryan but there is no Ryan.

> Sometimes you may need to iterate through all the keys within an object. This requires a specific syntax in JavaScript called a for...in statement. For our users object, this could look like:
```javascript
for (let user in users) {
  console.log(user);
}
```
> This would log Alan, Jeff, Sarah, and Ryan - each value on its own line.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for---in-statement

### Your code

```
const users = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(usersObj) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(users));
```

### Expected behavior

We should only mention parts of the example that exist, ideally.

> This would log Alan, Jeff, and Sarah - each value on its own line.

### System

All

**Comment by texas2010** [comment]
wow. Ryan was exist?  that is interesting.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for...in-statement.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
