### ISSUE TITLE
Colored Markers project step 12: inaccuracy in description

### ISSUE THREAD

**Issue by CarstenNeubert** [freeCodeCamp/freeCodeCamp#46846]
### Describe the Issue

In the "Learn CSS Colors by Building a Set of Colored Markers" project, the step 12 description reads:

>Notice that your marker doesn't seem to have any color. The background color was actually applied, but since the marker div element is empty, it doesn't have any width or height by default.

The div doesn't have any height by default, but as it's a block-level element it spans the entire width of the containing element (body).

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-12

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by Sboonny** [comment]
@CarstenNeubert  As not a native english speaker, I am confused. Can you provide more details, and an alternative you think will fit the current step?

**Comment by lasjorg** [comment]
I agree, it should only be height, not width. As you pointed out the element does have a width.

**Comment by lasjorg** [comment]
Suggested change, remove the "width or" from the sentence.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/616d50b93ba424d6282c99cf.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by jasoncarr95** [comment]
This is my first "real" contribution to open source (let alone to FCC), so although it is a pretty insignificant one, please feel free to provide me with any feedback and/or constructive criticism please!
