### ISSUE TITLE
Cafe Menu Step 18: Test fails if meta tags are not separated by newline

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46856]
### Describe the Issue

If the user adds the new `meta` tag on the same line as the first `meta` tag then the test will fail. The hint will tell the user that they should have two `meta` tags, which they do. As soon as the new `meta` tag is moved to a new line then the test will pass.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-18

### Your code

```
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta charset="utf-8" />
  <title>Cafe Menu</title>
  <link href="styles.css" rel="stylesheet"/>
</head>
```

### Expected behavior

If we want to require that new `meta` tag be on a separate line then we should mention this in the instructions or give a hint that tells the user it must be on its own line. Otherwise we should update the test to stop checking for this.

### System

Confirmed in both Firefox and Chrome.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3477cbcb6ba47918c1da92.md

Changes to make:

You will need to change this test:
https://github.com/freeCodeCamp/freeCodeCamp/blob/9adf9fa9f2d33a873957ac544e4eb97665cf4b34/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3477cbcb6ba47918c1da92.md?plain=1#L20-L24

The regex needs to become `<meta.*?\/?>/g`. Explanation: the `.` matches everything but line breaks, so it matches all the line up to the `>`, in case of two meta tags on the same line, it matches both of them. Adding the `?` in front of `*` makes it a lazy matching, meaning it will match as little as possible while satisfying the pattern.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
