### ISSUE TITLE
Bad Grammer

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46854]
### Describe the Issue

In this challenge the instructions say:

> Go ahead, and give each submittable element a unique name attribute of your choosing. Except for the two radio inputs.

The phrase 'Except for the two radio inputs' is not a complete sentence. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-36

### Expected behavior

We should use complete sentences.

### System

All

**Comment by nhcarrigan** [comment]
> Give each submittable element a unique name attribute of your choosing, except for the two radio inputs.

How's that?

**Comment by jeremylt** [comment]
I like it!

**Comment by nhcarrigan** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fad1cafcde010995e15306.md

Change to make:

1. Update the sentence `Go ahead, and give each submittable element a unique name attribute of your choosing. Except for the two radio inputs.` to `Give each submittable element a unique name attribute of your choosing, except for the two radio inputs.`

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by utsav0** [comment]
Hey, new here. 
Can I work on this?

**Comment by jeremylt** [comment]
Its open to anyone - go ahead

**Comment by bbsmooth** [comment]
My mother the English teacher would be proud.
