### ISSUE TITLE
Waypoint: Use the Bootstrap Grid to Put Elements Side By Side - HTML Course - Bootstrap Grid not showing up.

### ISSUE THREAD

**Issue by TheLegNBass** [FreeCodeCamp/FreeCodeCamp#4693]
In the Waypoint on using the BootStrap Grid, there's a section that reads:

"Here's a diagram of how Bootstrap's 12-column grid layout works:"

In Google Chrome (version 46.0.2490.86), the grid does not show up.  I've tried to pull it up in IE as well and it doesn't appear to be showing up there either.  

I'll try to test this from a different computer on a different network and update, but at this point it doesn't seem to show up.

**Comment by ltegman** [comment]
This image shows up just fine for me. It is hosted on imgur. Perhaps you are behind a firewall or using a browser extension that might block content from that website? I'd check your console and if there are no errors there try disabling browser extensions.

Closing this since is appears to be a problem with your individual setup.

Thanks and happy coding!
