### ISSUE TITLE
Slight change in word for 2nd test of Chain Middleware to Create a Time Server challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#46941]
### Describe the Issue

I never paid much attention to it before, but after someone tried to add a `setTimeout` of 20 seconds to the [Chain Middleware to Create a Time Server](https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/chain-middleware-to-create-a-time-server) challenge to pass test 2 (shown below), I think we should modify the wording to make it clear, the user should not purposely make a delay in the call.

> The /now endpoint should return a time that is +/- 20 secs from now

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/chain-middleware-to-create-a-time-server

### Your code

```
n/a
```

### Expected behavior

I was thinking something like the following for a replacement:
> The /now endpoint should return the current time.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/basic-node-and-express/chain-middleware-to-create-a-time-server.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ShaunSHamilton** [comment]
> The /now endpoint should return a time that is +/- 20 secs from now

I am not sure this wording is much better?

Do we really need to mention the approximation used in the test? That is, can we make it:

> The `/now` endpoint should return the current time.

**Comment by RandellDawson** [comment]
@ShaunSHamilton It may not be much better.

As far as the approximation being used in the text, it has been that way since the curriculum was ported over from the [old curriculum repo](https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/05-apis-and-microservices/basic-node-and-express.json).  I assume it was added to account for some users with slow connections or maybe if someone ran the tests closed to midnight?

The first commit this test appeared in was [this one](https://github.com/freeCodeCamp/curriculum/commit/6f9fab3043077af0c17a76e56ac2a59620af3e38) created by Quincy over 5 years ago.

**Comment by RandellDawson** [comment]
I am with you now.

Whoever takes this issue on, please change the text to reflect @ShaunSHamilton's suggestion shown below:
> The /now endpoint should return the current time.
