### ISSUE TITLE
"Where do I belong" bonfire redirects to 404 error

### ISSUE THREAD

**Issue by mkrumhansl** [FreeCodeCamp/FreeCodeCamp#4695]
I am working on my "Where do I belong" bonfire. Current code looks like this:
```
function where(arr, num) {
  // Find my place in this sorted array.
  
  arr = arr.sort();
  var i = 0;
  location = -1;
  while (location === -1 && i<arr.length){
    if (arr[i]>num){
      location = i;
    }
    i++;
  }
  return location;
}


where([40, 60], 50);
```

However, when I try to submit to run tests, I get redirected to the "Map" page and at the top is the error:

```404: We couldn't find a challenge with the name `hike-computer-basics-13-software` Please double check the name.
404: We couldn't find path /challenges```

EDIT: using Chrome, tried in a new incognito window with same result. Tried different code (using a for loop instead of a while loop) and still reproduces.

**Comment by ltegman** [comment]
This is due to the fact that because you left off `var` from your declaration of the `location` variable it is trying to reference the `window.location` variable, which controls browser navigation and history and makes your browser go haywire when you modify it incorrectly.

@BerkeleyTrue Is there something we can do to prevent this being possible to accidentally do, and do we want to spend the time on it? Or is this just the risk users run when writing their own code?

**Comment by BerkeleyTrue** [comment]
@ltegman When we introduce eslint, we can programmatically prevent code from eval if it is overwriting globals.

**Comment by BerkeleyTrue** [comment]
Not sure how `Hikes` should up. Strange

**Comment by ltegman** [comment]
I believe this issue will be closed by PR #4696 when it is accepted.

**Comment by BerkeleyTrue** [comment]
PR merged.

**Comment by ltegman** [comment]
I think the code executing in strict mode like it does now (and therefore catching most accidental uses of global variables) is probably the best we can do. Closing this.

Thanks and happy coding!
