### ISSUE TITLE
Certification printing / saving as PDF not formatted correctly

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#46965]
**Describe the bug**
Certifications are not correctly formatting when downloading / printing.

**To Reproduce**
View a certification. For example: https://www.freecodecamp.org/certification/mainlycoding/javascript-algorithms-and-data-structures

Then right click save as PDF or print. You will see the formatting jumbled, despite efforts to manually resize. The signature, for example, is way too big.

**Screenshots**
Here's the twitter thread with some screenshots: https://twitter.com/Lebron29ayy/status/1549522926751318017/photo/1

**Desktop (please complete the following information):**
 - Browser: latest Chrome and Firefox tested – it doesn't work in either

**Comment by ShaunSHamilton** [comment]
Sounds like the fix for this might require some research into [`<link media="print" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link). _That is just my initial suggestion_

---

An issue with the _help wanted_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ChiragSharma0208** [comment]
Can you assign this to me so that I can look into it?
