### ISSUE TITLE
 Problem step 6 new responsive web design? CAMPER CAFE

### ISSUE THREAD

**Issue by lawfets** [freeCodeCamp/freeCodeCamp#46978]
### Describe the Issue

when putting the opening en closing tag p on differnt lines from Est. 2020. I get a failure response although this seems to be acceptable in html.

Only when I put both p tags on the same line as Est. 2020, I get the answer right.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-6

### Your code
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Cafe Menu</title>
  </head>
  <body>
<h1>CAMPER CAFE</h1>
    **<p>
      Est. 2020
    </p>**
 </body>
</html>
```

### Expected behavior

This should pass as a correct answer as this is acceptable in html.

### Screenshots

![step6](https://user-images.githubusercontent.com/23460345/180278068-d3b9792e-1dbf-4ff5-ae98-6d3cf6fd8f7c.jpg)

### System

- Device: [ Laptop]
- OS: [ Windows 10]
- Browser: [Vivaldi]
- Version: [5.3.2679.68]

**Comment by Sboonny** [comment]
This error happens because regex is expecting the value to be in that form, as shown in the code below.

https://github.com/freeCodeCamp/freeCodeCamp/blob/f0e4131f9dac8ec449cec6289e6227382739d8d7/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f332a88dc25a0fd25c7687a.md#L38-L42

We can change regex, but I prefer using DOM instead because it will align with acceptable HTML all the time, I hope.

We can change the test to look like the code below.

> Your `p` element should have the text `Est. 2020`.
>
> ```js
> const paragraph = document.querySelector("p").innerText
> assert(paragraph === "Est. 2020");
> ```

This will make the test pass.

![cafe menu step 6 passed](https://user-images.githubusercontent.com/88248797/180286563-7425bbe6-c941-492f-b70b-9ded1fe2b716.png)

here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/f0e4131f9dac8ec449cec6289e6227382739d8d7/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f332a88dc25a0fd25c7687a.md
