### ISSUE TITLE
Confusion cased by the description on step 11 of color marker

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47102]
### Describe the Issue

While try to help camper in the forum https://forum.freecodecamp.org/t/preview-does-not-work-on-the-responsive-web-design-course/536554/4

He mentioned not being able to see the changes, after looking into it, I can see why this happened.

I think we should warn learners about this, like we do in skyline project, to reduce the coming confusion.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-11

**Comment by DylanDevelops** [comment]
What should the warning say exactly? I'm a little confused about why it doesn't show.

**Comment by Sboonny** [comment]
> What should the warning say exactly?

I am leaving this part for people who smarter than me, and because I am worried that people will open a pull request without other people skimming in and voicing their opinion.

But to answer the question, we can alter the first paragraph and the last, and reword it, so people won't expect a color to be changed.

> It's time to add some color to the page. Remember that one way to add

to something like

> It's time to set color to the background. Remember that one way 
> ...
> and set its `background-color` property to `red`. this won't change the page

**Comment by DylanDevelops** [comment]
I can add this change if you would like. But if there is anything else other than rewording what it says, I might not be the best person for it.

**Comment by Sboonny** [comment]
I would wait for other people to voice their opinion

**Comment by DylanDevelops** [comment]
Yeah, that works for me. I'm excited to see what they do so I can learn from it lol.

**Comment by bbsmooth** [comment]
Agreed @Sboonny, seems a little weird to mention at the beginning that they are going to add color but then they can't see any color added after they add the CSS. Personally, I might swap step 11 and 12 so that the div has width/height when they add the background color to it. But I can see how they built this up because step 12 explains why they didn't see any color immediately after completing step 11. 

I might start the first sentence as:

"It's time to give the marker some color." or "It's time to add some color to the marker."

Just to make it clear that the background color they are adding is for the marker and not the "page".

And then ya, just add a little warning after the last sentence.

"Please note, the color will not appear yet after you add the CSS."

**Comment by moT01** [comment]
I do think that swapping step 11 and 12 might be better, but you could run into the same problem there. You would be adding a width and height, but nothing would show up on the page still. I would just change the descriptions cause it's easier.

Step 11:
Change the first sentence to "It's time to add some color to the marker."
And add "You will not see any changes after you add the CSS" after the last sentence.

Step 12:
Change the description to:
"The background color was applied, but since the marker div element is empty, it doesn't have any height by default.
"In your .marker CSS rule, set the height property to 25px and the width property to 200px.

^ Maybe overboard, but I swapped it so they add the height first since it's mentioned as the problem. Also, I remove the first sentence since we are mentioning it at the end of the previous step.

What do you all think?

**Comment by ojeytonwilliams** [comment]
Sounds good, Tom.  Does anyone want to take this up?

**Comment by DylanDevelops** [comment]
I'll work on these changes!

**Comment by DylanDevelops** [comment]
So I'm trying to find the file but everything is all different. How do I find this?
