### ISSUE TITLE
CatPhotoApp Step 68: Issues with `meta` element

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47118]
### Describe the Issue

I believe this is the first step to introduce the `meta` element. Two issues with this step:
- [ ] The description does not explain that it is a self-closing tag
- [ ] The tests accept a closing tag

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-68

### Your code

You can pass this step with the following:

```
<meta charset="UTF-8"></meta>
```

### Expected behavior

Since this is the first time the `meta` element is used we should explain in the description that it is a self-closing tag. I'm assuming that we are not expecting the user to look up this information themselves.

Also, we should fix the test so that it does not accept a closing `</meta>` tag.

### System

N/A

**Comment by Sboonny** [comment]
Meta and link closing tag is accepted almost everywhere, I made sure it's the similar test to make it easier to change them to self-closing if issue rise from that. But changing them will make it harder unnecessary in my opinion, because browsers take care self-closing tags.

About the description, we should include it, that was mistake from my part.

**Comment by lasjorg** [comment]
According to the specs, the end tag is not allowed.

https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element

It will fail validation with `Error: Stray end tag meta`

**Comment by Sboonny** [comment]
@lasjorg same is applied to link element, iam convinced.

We should change link element tests as well

**Comment by lasjorg** [comment]
Yes, the tag omission rules are the same for the `link` element.

I'm not suggesting we absolutely have to test for it everywhere, I'm just saying it is in fact invalid syntax to have the end tag. Not sure how many tests would need to be implemented for this to be consistent across all challenges, or if it's worth it or not.

**Comment by Sembauke** [comment]
Let's keep it simple:

Since this is the first time the meta element is used we should explain in the description that it is a self-closing tag. I'm assuming that we are not expecting the user to look up this information themselves.

Also, we should fix the test so that it does not accept a closing `</meta>` tag.

We can always add more tests to other steps.

**Comment by bbsmooth** [comment]
I'm going to make another suggestion. Perhaps we should just get rid of this step completely? According to MDN, the only valid value for `charset` is `UTF-8`. The W3C validator will throw an error if you use any other value. And even more, it won't complain if you don't include a `charset` at all. It appears all browsers will just automatically default to `UTF-8`, so you don't need a `charset` definition in the first place.

**Comment by lasjorg** [comment]
I would imagine it is still considered a best practice to include it. I'm not so sure relying on browsers to do the work is a good starting point to take when teaching, even if all modern browsers do the right thing.

I'd also suggest that when teaching taking the pedantic approach is often the better choice.

**Comment by bbsmooth** [comment]
Ya, you're right, we should teach it because it seems to be the accepted best practice.

**Comment by Sboonny** [comment]
Because this is the last step in a project, and people can't see the right way to type it, I can see why we should make it strict.

But again, is it worth it? We aren't asking people to type `</meta>` tag and in follow-up projects they can see the right way.

We can add the regex back, and make it more strict. if you guys think it's worth it

**Comment by adhiramaa** [comment]
<!DOCTYPE html> 
I do this at the starting the code and the executed

**Comment by adhiramaa** [comment]
//<!DOCTYPE html>

**Comment by adhiramaa** [comment]
!DOCTYPE html
