### ISSUE TITLE
Inserted wrong command and I was able to pass the minichallenge

### ISSUE THREAD

**Issue by JustLolo** [freeCodeCamp/freeCodeCamp#47148]
### Describe the Issue

Inserted wrong command and I was able to pass the minichallenge.
I can't remember but it was one or two minichallenges after this one.
I had to reset the whole thing bc the next minichallenge made no sense based on the error I had.

### Affected Page

database course

### Your code

```
ALTER TABLE characters ADD PRIMARY KEY(more_info_id);
```

### Expected behavior

won't be able to pass the minichallenge bc of the error I got on the postgresql console

### Screenshots

![image](https://user-images.githubusercontent.com/103621114/182706940-1a7e9179-425d-4bab-af4a-c03ce86c5f6c.png)

it's one or tow minichallenges before this picture, I can't remember

### System

windows 10, latest chrome version, 

### Additional context
this is the code I should have inserted

ALTER TABLE more_info ADD PRIMARY KEY(more_info_id);

_No response_

**Comment by moT01** [comment]
I don't think this is a bug @JustLolo.

If you have an issue like this, follow [these steps](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#issues-within-a-course-9) to restart the challenge to what it is supposed to be at the start of the challenge you are on. If you run into other problems, there's quite a few other troubleshooting steps in that post. I would take a look at those to see if anything will help you solve the issue. If nothing there helps, you should create a forum post with the issue you are having and I, or someone else, can help you there. If it's determined to be a bug, we can then create an issue here. Unless you are really convinced that it is in fact a bug, I would go to the forum first.

I'm going to close this because I don't think this is a bug. If anyone thinks I'm wrong, feel free to leave a comment with some more information and we can revisit. Thanks and happy coding 🎉

**Comment by JustLolo** [comment]
My explanation wasn't the best bc I had no information about the step I made wrong bc I restart the challenge before doing this post, I created I can't remember if was a key or a table in the wrong way and I was able to pass the minichallenge, bc of this I thought I was ok, but, after one/two or three I have to do an step that depended on the challenge I did wrong, that's why I inserted the corresponded postgresql command, I was able to pass, but I got an error in the console, bc this didn't make sense to me I proceeded to reset the whole thing, and everything took sense after that.

So, what I am trying to say is that the potential error/bug is one, two or three steps back, bc I was able to pass inserting the wrong command, the command was related to the declaration or creation of a key.
