### ISSUE TITLE
new RWD step-based blocks have incorrect padding

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#47158]
### Describe the Issue

There is no padding on completed challenges on the left, only on the right. I would rather see them in squares instead of rectangles also. 

![image](https://user-images.githubusercontent.com/46919888/182878459-c41ff6fe-ddd8-4a85-8b1b-64143f543030.png)

### Affected Page

https://freecodecamp.org/learn/2022/responsive-web-design/

### Steps to Reproduce

-

### Expected behavior

There should also be padding on the left.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ahmadabdolsaheb** [comment]
Thanks for your patience with that. The reason that they are connected horizontally is that it gives it a sense of direction instead of having the eye wonder around. <img width="302" alt="Screen Shot 2022-08-08 at 5 31 54 PM" src="https://user-images.githubusercontent.com/4591597/183442599-8976f414-f49e-47d6-bc85-8c96849b8e86.png">

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb have you considered highlighting the ends?  Something subtler than a giant blob, of course.

**Comment by ahmadabdolsaheb** [comment]
Sure, I think that makes sense. We could experiment with flipping the colors.
