### ISSUE TITLE
"start at the beginning" link navigates to the legacy RWD

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#47206]
### Describe the Issue

When a new camper signs in and visits the top page of `/learn` , a message "If you are new to coding, we recommend you start at the beginning." is displayed.

But when they click the link, it will take them to the legacy RWD. I think we should switch it to the new RWD.

### Affected Page

https://www.freecodecamp.org/learn/

### Steps to Reproduce

1. Sign in with a new user (with less than 15 challenges completed, as far as I understand the code. I checked this behavior by creating a new GitPod workspace)
2. Go to /learn
3. Click the link "start at the beginning"
4. It will navigate to the first lesson of the **legacy** RWD

### Expected behavior

The link should take the camper to:
- The new RWD curriculum if the new RWD is translated for the current language
- The legacy RWD curriculum if the translation is not ready

### Screenshots

![start-at-the-beginning](https://user-images.githubusercontent.com/25644062/183304517-7551d46e-4cc1-4b90-af33-18e35b56628d.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 104.0.5112.81

**Comment by jdwilkin4** [comment]
Good catch. 

That should definitely be pointing to the new curriculum.

**Comment by mmatsumoto1026** [comment]
Hello,

The link is set by slug (line 63, @client/src/components/Intro/index.tsx) and the one seems to be set by the data get from a graphql query (line 101 - 111, @client/src/pages/learn.tsx).

But in the challengeNode of data, id "learn-html-by-building-a-cat-photo-app/step-1" is not contained and we can not set the link to new RWD so how about that adding the id for new RWD's step-1 and reading the id by the correct graphql query. 

![graphql_ide](https://user-images.githubusercontent.com/44451585/183354172-67308d9c-2161-469a-b24f-3c58628be734.png)

I'm now searching the file which contains or generate the allChallengeNode data or the endpoint which send back the one(because now I think the one is in fcc codebase).

Thanks.

**Comment by moT01** [comment]
Use the superblock. Filter for the first challenge in the new RWD superblock.

**Comment by mmatsumoto1026** [comment]
@moT01  The query like this？

```graphql
query FirstChallenge {  
  challengeNode(
    challenge: {superBlock: {eq: "2022/responsive-web-design"}, challengeOrder: {eq: 0}, order: {eq: 0}}
  ) {
    challenge {
      fields {
        slug
      }
    }
  }
}
```
