### ISSUE TITLE
Example Snippet Formatting

### ISSUE THREAD

**Issue by hanswang123456** [freeCodeCamp/freeCodeCamp#47220]
### Describe the Issue

The current example snippet for `JavaScript Algorithms and Data Structures` -> `Basic JavaScript` -> `Access Multi-Dimensional Arrays With Indexes` has the expected output underneath the sample code. It would be clearer for campers if the expected output is moved into the example snippet.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/access-multi-dimensional-arrays-with-indexes

### Your code

Current Sample Snippet
```javascript
const arr = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [[10, 11, 12], 13, 14]
];

arr[3];
arr[3][0];
arr[3][0][1];
```
`arr[3]` is `[[10, 11, 12], 13, 14]`, `arr[3][0]` is `[10, 11, 12]`, and `arr[3][0][1]` is `11`.

### Expected behavior

It would be more concise to give the output in the Snippet. 

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: []

**Comment by gikf** [comment]
I'd rather change it similarly to #46813. Keep the explanation below the code, and either remove `arr[3](...)` from it, or add concrete variables to refer to them in explanation.

**Comment by hanswang123456** [comment]
@gikf that seems like a good explanation. Another way could be wrapping the array access in a console.log and comment the output beside it.

**Comment by moT01** [comment]
I think I agree @hanswang123456 - however, it looks like it used to be like that and [they were remove here](https://github.com/freeCodeCamp/freeCodeCamp/commit/7117919d36d3565e1da7f701dd959b6605ae7b50#diff-e1cda84da65ba1f15cb0ba73938003283c5e0610675b1d53934bb84ca0f22fd7R23), on [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/41092), to streamline the translation process. It is more difficult to translate comments in code than plain text in the instructions and descriptions, so I presume that's why they were removed.

That alone might be enough reason to leave them how they are - but additionally, we want to focus our efforts on the new project based curriculum and not continue to make fixes to the soon to be legacy curriculum.

Again, I think I would prefer they be like this suggestion, but I think I would vote to leave them how they are for these reasons. I will leave this open for discussion.
