### ISSUE TITLE
Responsive Web Design - Learn CSS Flexbox - Step 5

### ISSUE THREAD

**Issue by shiv19** [freeCodeCamp/freeCodeCamp#47223]
### Describe the Issue

The instructions ask you to create a div with the id of "gallery", but it expects you to create a div with a class of "gallery".

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-5

### Your code

```html
<!-- The instructions prompt you to create -->
<div id="gallery">
</div>

<!-- The exercise expects you to create -->
<div class="gallery">
</div>
```

### Expected behavior

The current instruction reads

```
Below your .header element, create a new div element with the id of "gallery". 
```

I suggest we change it to

```
Below your .header element, create a new div element and assign it a class of "gallery". 
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/61537c9eecea6a335db6da79.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by itsnoa04** [comment]
Hey is this issue taken, Im trying to get into OSS this seems like a solid start. Can I work on this?

**Comment by shiv19** [comment]
Hey @itsnoa04, A PR has already been created for this issue. It is pending review.

**Comment by itsnoa04** [comment]
It that case I'll just review the PR
