### ISSUE TITLE
Step 5 of the Learn CSS Flexbox course says create an id but the solution is a class

### ISSUE THREAD

**Issue by skrewde** [freeCodeCamp/freeCodeCamp#47252]
### Describe the Issue

Step 5 of the [Learn CSS Flexbox by Building a Photo Gallery](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-css-flexbox-by-building-a-photo-gallery)
 course says create a div element with an id (gallery) but the Hint requests a class instead.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-5

### Steps to Reproduce

1. Copy-pasting the link in address bar,
2. Solving the step as described,
3. Clicking "Check Your Code" button/Pressing the Ctrl+Enter shortcut,
4. Regard Hint.

### Recommended fix or suggestions

Having been blocked by this typo, I am running on the assumption that the solution will be consistent across the course. I recommend switching the 'id' text to 'class.'

### Screenshots

![image](https://user-images.githubusercontent.com/94148640/183959545-36f07f9c-0e3e-47b8-83c1-cc13aa7549ea.png)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed (#47223) in staging. This means that the next time we push our staging branch to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
