### ISSUE TITLE
Add empty line below input field in Responsive Web Design curriculum

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#47324]
I just observed someone not understanding that they could press enter within their answer box to create a new line, then add their new element there. See screenshot below:

<img width="1124" alt="Cursor_and_mom_mp4_-_Google_Drive" src="https://user-images.githubusercontent.com/985197/185535009-e793693b-6a2e-44c8-b7d1-bdf1249c9d7f.png">

I propose we add an empty line below the seed code, so that learners better understand where they should type their solution.

**Comment by ShaunSHamilton** [comment]
Before we go and make this change, do we want to discuss additional changes we would like to make to the editor/seed as a whole? _Just so we are not immediately overwriting other changes_

Specifically, I am thinking about the possibility to completely overhaul this project so that the page starts with a blank slate (no distracting elements in the editor).

**Comment by ahmadabdolsaheb** [comment]
Here are my thoughts from chat for reference:
1) When asked to input text on the next line, we should either have an empty line or tell users early on to hit enter.
2) The editable region is not distinguishable enough, we would need to either add more contrast and/or tell the user were to edit the code.
3) We probably need to explain the html tags early on so users don't wonder about pre existing tags on the page.

**Comment by moT01** [comment]
I'm not against an update to the project so that we have them create the html element and stuff - although, I've always felt that part of this projects goal is to get people who have never written code before, excited about it. So I think having them add fun things like cat images as soon as possible, helps with that.

I would suggest that for now, we just go through the first 20 steps? whole project? of the cat photo app, and make sure there's an empty line in the seed code where needed.

**Comment by ahmadabdolsaheb** [comment]
At some point the users need to learn about creating a new line, or they will face an issue down the line.

**Comment by ojeytonwilliams** [comment]
> When asked to input text on the next line, we should either have an empty line or tell users early on to hit enter.

I'm strongly in favour of the former, but what we should do is make sure that a user has to enter in two lines of code fairly early on.  That way they'll see that the region expands as they use it and we won't need to tell them.

> The editable region is not distinguishable enough, we would need to either add more contrast and/or tell the user were to edit the code.

Or... what Shaun said.  If they have blank slate for step 1, everything is editable.  That way nobody should fall at the first hurdle. More visual distinctiveness couldn't hurt, though!

> So I think having them add fun things like cat images as soon as possible, helps with that.

Agreed.  If we're overhauling, how about this: start with fun stuff and only add in the invisible bits once the user's already managed to make something happen on the page?  If step 4, say, was "The page is taking shape. Now is a good time to do things properly..."

**Comment by ojeytonwilliams** [comment]
Since we're discussing issues with the early challenges: I got a bit more parental feedback, just on step 1.

It wasn't obvious to my dad where to start. He read the instructions carefully, correctly understood he needed to modify the h1 element, but didn't realise we meant the _second_ h1 element.  The fact that there's what looks like an h1 element in the instructions threw him off.

Aside from Ahmad's proposed changes, something as simple as going from

> Find the h1 element and change its text to: `CatPhotoApp`

to
> Find the h1 element below and change its text from `Hello World` to `CatPhotoApp`

could help draw the attention to the editable region.

If we're not going for a blank slate, something like that would help.

**Comment by bbsmooth** [comment]
> The editable region is not distinguishable enough, we would need to either add more contrast and/or tell the user were to edit the code.

Agree 100%. Should probably do both. Make it stand out more on the page and explain in step 1 how it works. And then in step 2 we could explain how to create a new line.

I also think it is potentially confusing that you can edit code outside of the intended editable region. I know this is probably not a popular opinion, and I am prepared to take the criticism :smile: but I really do think we should only allow edits to be made in the intended editable region. This would solve a lot of "accidentally changed HTML they weren't supposed to change" issues in the forum. And it does seem a little weird to me that we have an intended editable region that is styled to look like it is in an editor and then everything else is styled in a different color that sort of looks like it is disabled, but yet you can move the cursor in there and make changes. 

Perhaps we need to make it very clear early on that they do not need to/should not change any code outside of the intended editable region to pass the steps.

**Comment by ojeytonwilliams** [comment]
It's tempting to put in a lesson about the editor, and we have considered this, but I think that is something we should do as a last resort. We still have room to improve the UI to make it clearer and the lessons to guide the user. If all our attempts fail, we can try a "lesson 0" which just teaches about the editor.

It does risk putting people off, as all tutorials do. They're very frustrating when all you want to do is start learning to code.

Restrictions on where you can edit are also (in principle) possible, but they'd be incredibly irritating in practice. Being only able to edit in a tiny little box stops people from experimenting and breaking things. Both of which are important parts of learning.

What we can definitely do is warn people that they're off the beaten path and likely to encounter weirdness. That should help with the "accidentally changed HTML they weren't supposed to change" issues.

**Comment by PiyushBhangale** [comment]
j
