### ISSUE TITLE
Bonfire: [Factorialize a Number] not accepting correct answer

### ISSUE THREAD

**Issue by dawnguard** [FreeCodeCamp/FreeCodeCamp#4733]
Challenge [Bonfire: Factorialize a Number](http://www.freecodecamp.com/challenges/bonfire-factorialize-a-number?solution=var%20factorial%20%3D%20%5B%5D%3B%0Afunction%20factorialize(num)%20%0A%7B%0A%20%20if(num%3D%3D%3D0)%0A%20%20%7B%0A%20%20%20%20%20%20return%201%3B%0A%20%20%7D%0A%20%20%0A%20%20for(i%3D1%3Bi%3C%3Dnum%3Bi%2B%2B)%0A%20%20%7B%0A%20%20%20%20%20%20factorial.push(i)%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20result%20%3D%20factorial.reduce(function(a%2C%20b)%7B%0A%20%20%20%20return%20a*b%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20result%3B%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var factorial = [];
function factorialize(num) 
{
  if(num===0)
  {
      return 1;
  }
  
  for(i=1;i<=num;i++)
  {
      factorial.push(i);
  }
  
  var result = factorial.reduce(function(a, b){
    return a*b;
  });
  
  return result;
}

factorialize(5);
factorialize(10);
factorialize(20);
factorialize(0);

```

It is returning the right result in every case, yet the crosses don't turn into ticks

**Comment by dawnguard** [comment]
Is ``if(num===0)`` not allowed?

**Comment by ltegman** [comment]
You are declaring the factorial variable globally, which means that the second time you call factorialize you are not starting with a blank array and will get the wrong output (unless the input was 0, since that doesn't rely on the factorial variable). For this reason and many others global variables are very dangerous and you should always make sure you're scoping variables to the function that needs them.

In the future please ask for coding help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) before filing a bug.

Thanks and happy coding!
