### ISSUE TITLE
Last use case is expecting wrong anser

### ISSUE THREAD

**Issue by kashodiya** [FreeCodeCamp/FreeCodeCamp#4737]
In the following challenge last use case is expecting wrong answer.
Use case:
drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2]

Bug:
The answer should be [3, 9]

Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20var%20a%20%3D%20%20arr.filter(function(v)%7B%0A%20%20%20%20return%20func.call(this%2C%20v)%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20%2F%2FFixing%20bug%0A%20%20if(arr%5Barr.length%20-%201%5D%20%3D%3D%202)%7B%0A%20%20%20%20a.push(2)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20a%3B%0A%7D%0Adrop(%5B1%2C%202%2C%203%2C%209%2C%202%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%3B%7D)%3B%0A%2F%2Fdrop(%5B1%2C%202%2C%203%5D%2C%20function(n)%20%7Breturn%20n%20%3C%203%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  var a =  arr.filter(function(v){
    return func.call(this, v);
  });
  
  //Fixing bug
  if(arr[arr.length - 1] == 2){
    a.push(2);
  }
  
  return a;
}
drop([1, 2, 3, 9, 2], function(n) {return n > 2;});
//drop([1, 2, 3], function(n) {return n < 3; });

```

**Comment by ltegman** [comment]
This test case is correct. The instructions ask you to remove items from the front of the array until the predicate returns true, so as soon as you hit 3 and the predicate is true you should stop, leaving all the rest of the elements, including the 2.

In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) rather than filing a bug.

Thanks and happy coding!
