### ISSUE TITLE
Provide optimal/best learning outcomes for ziplines

### ISSUE THREAD

**Issue by dshgna** [FreeCodeCamp/FreeCodeCamp#4742]
While Free Code Camp provides a lot of flexibility in ziplines, some hints on the 'optimal or best learning outcome' would encourage campers to improve on the solutions they have already built.

For example, in the 'Random Quotes Machine', the normal way would be to get a random quote from an array of quotes. A better solution may be to use an API and learn about REST services in the process.

**Comment by SaintPeter** [comment]
We have deliberately not suggested that there is any sort of "optimal" solution to any of our Bonfires, Ziplines, or Basejumps.  We do not want to encourage campers to go back and rehash the work that they have already done.  That sort of naval gazing is not conducive to moving forward with their learning.

We deliberately removed the API version of the Quote Machine because we had not established a foundation for the knowledge needed to complete it.  The API related Ziplines now occur after our section on APIs and JSON data.  I can tell you from hours in the /Help rooms, many campers were completely lost with how to use an API.

That said, we definitely encourage users to stretch themselves on the Ziplines and Basejumps.  That's why we have the Bonus User Stories.  If you want to go above and beyond what is specified, you're absolutely welcome to.  Some campers have done some amazing things.  If you want to do an API based quote machine, more power to you.  It's your portfolio to own.

We plan to update the "Get Set for Ziplines" waypoint soon with more emphasis on going "above and beyond" and not limiting yourself to the example project.

Thank you and Happy Coding!
