### ISSUE TITLE
Learn CSS Grid by Building a Magazine - Step 64

### ISSUE THREAD

**Issue by alfonsusac** [freeCodeCamp/freeCodeCamp#47466]
### Describe the Issue

The instruction can confuse people who are used to use `"` as the enclosing character for strings.

Id suggest giving a tip (?) that you can also use `'` to enclose strings.

Which brings me to this bug (see Your code section) which is accepted when I was first confused. Then I went to the next step to see what they meant by the question haha.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-64

### Your code

```css
.quote::before{
  content: " ";
}
.quote::after{
  content: " ";
}
```

### Expected behavior

This should be rejected / failed.

### Screenshots

![image](https://user-images.githubusercontent.com/20208219/189089040-c52c62a4-b585-4041-a87b-617f4e613951.png)

### System

- Device: PC
- OS: Windows 10
- Browser: Brave
- Version: Latest

**Comment by bbsmooth** [comment]
The following also mistakenly pass:

```
.quote::before{
  content: ' "';
}
```

Notice that the space is before the double quote instead of after it.

```
.quote::after{
  content: '" ';
}
```

Notice that the space is after the double quote instead of before it.

**Comment by Sboonny** [comment]
I have tested `\\?((?<=\'))\\?\"\s(?=\')` for :before selector, and `\\?((?<=\'))\s\\?\"(?=\')` for the `after` selector test and got no luck making the seed code pass. 

The only option I see is to select the style element like this `document.querySelector("style")` and search for `.quote::before { content: '" '}` in it, which I hate the idea of.

Maybe I am overthinking it, and there is a simple regex for this, but I can't think about one, that account for previous values without selecting these values in this selector `assert(new __helpers.CSSHelp(document).getStyle('.quote::before')?.content?.match(/\\?\"\s/));`.

Here is the file for anyone want to mess with it

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-grid-by-building-a-magazine/6148d3fff5186b57123d97e2.md

Because I can't solve it, I am opening this for contribution.

**Comment by moT01** [comment]
The content selector is including the quotes and comes back as something like `" "`. If that's the case, I think something like this would work: `^' "'$`

**Comment by Sboonny** [comment]
Here is the test, I have tried. I think this issue is the selector selects the content inside the quotes, to give context if I add `content: 'hello'`, it will select `hello` without quotes.

```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::before')?.content?.match(/^'" '$/));
```

```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::after')?.content?.match(/^' "'$/));
```

**Comment by Sboonny** [comment]
It actually didn't work
```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::befoe')?.content?.match(/^" $/));
```

But this somehow worked

```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::befoe')?.content?.match(`" `));
```

But both of these didn't work

```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::after')?.content?.match(/^ "$/));
```

```js
assert(new __helpers.CSSHelp(document).getStyle('.quote::after')?.content?.match(` "`));
```
