### ISSUE TITLE
Wrong answer to the question

### ISSUE THREAD

**Issue by tahiraslammm** [freeCodeCamp/freeCodeCamp#47475]
### Describe the Issue

Given question is,  What is the value of a after you run the following code?
a = np.arange(5)
a + 20

and the correct answer is [20, 21, 22, 24, 24] but it's marked as wrong answer 

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations

### Your code

a = np.arange(5)
a + 20

Result: 
array([20, 21, 22, 23, 24])

### Expected behavior

Should mark [20, 21, 22, 24, 24] as correct answer

### Screenshots

![image](https://user-images.githubusercontent.com/40141282/189286640-319143e7-1c40-4e48-83a5-0a31ab629814.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by gepetobio** [comment]
Yep, I came here to open the exact same issue... tks @ghost for doing that. @ieahleen I may be wrong but I think this ticket shouldn't have been closed. Here's the screenshot of the code ran on my Jupyter Notebook:

![MyOwnStudies_ipynb_—_FreeCodeCamp-Pandas-Real-Life-Example](https://user-images.githubusercontent.com/1509314/197565035-6607db67-77e1-47a3-9465-1ec0913940c4.jpg)

**Comment by ieahleen** [comment]
The value of `a` has not changed, so the answer is correct
