### ISSUE TITLE
Waypoint: Change Text Inside an Element Using jQuery

### ISSUE THREAD

**Issue by ghoal** [FreeCodeCamp/FreeCodeCamp#4748]
I believe my code is correct but the instruction 'to leave text otherwise unchanged is' is marked red X. 
[file.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/46219/file.txt)

**Comment by SaintPeter** [comment]
If you use the "bug" button on the waypoint and choose the option to create a bug it will automatically include your code as well as a link to the waypoint in question.

However, I encourage you to seek assistance on the [Help Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) rather than posting an issue.

Closing as this the waypoint is functioning as designed.
