### ISSUE TITLE
Registration Form Step 29 Displays Text Input Instead of Checkbox

### ISSUE THREAD

**Issue by rutterjt** [freeCodeCamp/freeCodeCamp#47480]
### Describe the Issue

In step 29 of the Learn HTML Forms by Building a Registration Form challenge, there seems to be incorrect seed code. The checkbox for accepting terms and conditions is missing a `type="checkbox"`, so when the step first opens it displays a plain text input instead of a checkbox.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-29

### Your code

N/A

### Expected behavior

A checkbox should be rendered instead of a text input.

### Screenshots

![Screenshot 2022-09-09 at 14-50-07 freeCodeCamp org](https://user-images.githubusercontent.com/69657008/189423201-d95575c7-1dcc-4cca-bce8-de3baec66e8b.png)

### System

- Device: Laptop
- OS: Ubuntu 20.04
- Browser: Firefox (104), Chrome (105)

**Comment by naomi-lgbt** [comment]
Whoops! Yeah, that should be fixed.

Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fabf0dd4959805dbae09e6.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by rutterjt** [comment]
Sounds good! I'll submit a PR to fix it!
