### ISSUE TITLE
Account Settings Keyboard Shortcuts

### ISSUE THREAD

**Issue by Smeagol2069** [freeCodeCamp/freeCodeCamp#47517]
### Is your feature request related to a problem? Please describe.

I feel like the settings page does not make it clear what the keyboard shortcuts are.

### Describe the solution you'd like

I think that the setting for keyboard shortcuts should hyperlink to the [guide detailing the keyboard shortcuts](https://forum.freecodecamp.org/t/free-code-camp-hotkeys/59467). 

### Describe alternatives you've considered

Another option would be a page within the primary website about the keyboard shortcuts, but I feel like that would be redundant.

**Comment by bbsmooth** [comment]
I've been thinking we need something like this for a while now, but not just for the hot keys, but for any additional information that is not easily evident from the UI. I've got few accessibility issues in mind that affect JAWS users. It would be great to have a place to list these issues so that JAWS users could check there first.

**Comment by naomi-lgbt** [comment]
I believe that post needs some updates, but yes, linking to it would be beneficial IMHO.

**Comment by moT01** [comment]
The [PR that added the toggle for the shortcut keys](https://github.com/freeCodeCamp/freeCodeCamp/pull/45530) added a modal that shows the details of the shortcuts. You can access it by going to a challenge, pressing escape, then `shift + ?`. This is feels very hidden, which isn't terrible - I think we maybe just need a way to let users know that exists and how to see it.

**Comment by bbsmooth** [comment]
@ojeytonwilliams Yes, we did discuss this elsewhere. The solution we came up with was to allow people to disable all single character shortcuts in the settings. There is now an "Enable Keyboard Shortcuts" setting that allows people to toggle these off/on. As long as the "?" shortcut honors that then we are technically OK with regards to [WCAG](https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html).

Personally, I don't like the idea of hiding these shortcuts from any users. Their existence should be made known to everyone because you never know who might benefit from them. So bullet point one above would be a no for me. And as mentioned above, not allowing people to turn off the `?` shortcut would be a WCAG failure, so bullet point two is out. Bullet point three is on the right track. I've always thought that we need a way for everyone to be able to discover all of the keyboard shortcuts available.

Another thing to keep in mind is that most single key shortcuts are not going to work with screen reader users because their screen reader will already be hijacking them for their own purposes. Granted, screen reader users have other ways to navigate around a page so perhaps they don't need to rely on them as much. But take for instance the `n` and `p` shortcuts we offer. Both JAWS and NVDA use those keys for navigation and thus the FCC shortcuts aren't going to work for those users. So it might be a good idea to offer two versions of a shortcut (at least for shortcuts we think are essential for everyone): a single key version (that can be turned off) and a version that uses some combination of control keys plus a character key so screen reader users can take advantage of them.

**Comment by wulph111** [comment]
> The [PR that added the toggle for the shortcut keys](https://github.com/freeCodeCamp/freeCodeCamp/pull/45530) added a modal that shows the details of the shortcuts. You can access it by going to a challenge, pressing escape, then `shift + ?`. This is feels very hidden, which isn't terrible - I think we maybe just need a way to let users know that exists and how to see it.

I just found the "enable keyboard shortcuts" setting and had to come here to find out how to use them. Some explanatory text ("press ESC ? to show shortcuts" for example) directly below the Settings toggle would be very helpful.

**Comment by ShaunSHamilton** [comment]
@wulph111 The only issue with adding that text in the settings page is that it does not work in the settings page. Although, I cannot think of a nice place to add it in the editor. So, what about underneath the toggle in the settings page:

> Within a challenge, press `ESC` followed by `SHIFT + ?` to show a list of available shortcuts

**Comment by wulph111** [comment]
> So, what about underneath the toggle in the settings page:
> 
> > Within a challenge, press `ESC` followed by `SHIFT + ?` to show a list of available shortcuts

This sounds like a good plan. Cheers!

**Comment by ShaunSHamilton** [comment]
@moT01 Are you happy with the above suggestion to close this issue?

**Comment by moT01** [comment]
Sounds good to me 👍 The text style can match the rest of the messages on the settings page like that.
