### ISSUE TITLE
Skip to content Button for accessibility

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47523]
### Is your feature request related to a problem? Please describe.

I was trying to implement freeCodeCamp `Skip to content` button to Chapter, but there is none in freeCodeCamp. The button is used in websites like YouTube, this button will provide quality of life to people who access the site daily and give them chance to skip some annoys

### Describe the solution you'd like

Creating a skip to content button component, that skips the navigation bar

### Describe alternatives you've considered

Toggle the nav bar component, that hides the navigation. Although not standard, it's used in sites like CodePen

**Comment by ppeters0502** [comment]
I'd love to work on this issue if it's accepted as a feature request! So a button with a tabindex of 0 above that's hidden unless the user hits tab and then it would display above the navbar? Or would we want it to display within the navbar, like to the left of the search box?

**Comment by Sboonny** [comment]
@ppeters0502 good questions 👍, but I will defer to @ahmadabdolsaheb about how it will look, how should it be positioned, and if it's needed?

**Comment by bbsmooth** [comment]
Having a skip to main content link at the very top of the page is a good idea. I was actually working on this a while ago but got distracted and forgot about it :facepalm: 

This should be marked up as a link (`anchor` element) and should be the very first element on the page. I would place it as the first element in the `header`, before the `nav`. It can definitely be hidden by default and then only displayed when it has keyboard focus. Where/how you display it at the top of page is more an issue of aesthetics, just as long as it meets color requirements.

The other part of this is where the skip link targets. Based on the HTML structure used in FCC, I would recommend the skip link target the first heading in the `main` element. A quick look through the various types of pages in FCC learning curriculum confirms that this will be the `h1`, except for the Profile and Donate pages which are starting with `h2` instead of `h1` (this should probably be changed). This of course means that these headings will need to be given an `id` so that the skip to link can target them.

Speaking of the target heading, it should NOT be given a `tabindex` of `0`. We do not want to create another tab stop here, and it is not necessary. All browsers will automatically shift the focus to the target when you click on an internal link without needing an explicit `tabindex` set on the target.

An additional feature that is sometimes used with skip links (but not required) is to provide a temporary focus indicator on the target when the skip link is activated. This is often implemented as a focus ring or background color on the target that fades out over a period of a few seconds. This is a nice visual indicator that the skip link actually worked and shows the user that the focus is now on the heading (remember, skip links are primarily for sighted users). For example, if I am on a Step in a RWD course and I activate the skip link, chances are nothing visually is going to indicate that the skip link worked. Placing a temporary focus indicator on the `h1` heading will help confirm that the skip link worked and show me exactly where the focus is placed. Some examples of this in action:

[WebAIM: Skip Navigation Links](https://webaim.org/techniques/skipnav/)
[Adrian Roselli](https://adrianroselli.com/2022/09/accessibility-at-the-edge-w3c-cg-is-an-overlay-smoke-screen.html)

Note: In order to add a focus effect on the target heading we would need to add `tabindex=-1` to the heading, which is fine since it doesn't add the heading to the default tab order.

**Comment by ahmadabdolsaheb** [comment]
I agree with all the above :). For the styles, we could have an absolutely positioned div (outside view) and with an anchor element inside. When the anchor element is on focus, we could bring the div into view and placed it under the navigation to the left side of the screen.

**Comment by Sboonny** [comment]
With @ahmadabdolsaheb and @bbsmooth comments, I feel comfortable opening this for contribution.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by diivi** [comment]
Please assign this issue to me

**Comment by naomi-lgbt** [comment]
Heya @diivi,

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by JaySable82** [comment]
Heyy @naomi-lgbt where would i get the good first issue as beginner!!!

**Comment by YuriDevAT** [comment]
Hi. I am an Accessibility Developer. If this issue is still open, I would like to work on this.

**Comment by bbsmooth** [comment]
There is already a PR open for this (see above) and it is just about to be merged.

**Comment by Sboonny** [comment]
Do I open new issue for [donate](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/pages/donate.tsx) and [profile](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/profile/profile.tsx) missing `h1`?
