### ISSUE TITLE
feedback on Learn Css Variables By Building A City Skyline

### ISSUE THREAD

**Issue by lucyferu** [freeCodeCamp/freeCodeCamp#47555]
### Describe the Issue

this project assumes you haven't worked with Flexbox yet hence it just givesyou the code without it being a real challenge/test.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline

### Your code

```
none
```

### Expected behavior

just to be given directions about what to do (as per usual) without giving you all the lines of code.

### Screenshots

![Screenshot at 2022-09-18 15-46-28](https://user-images.githubusercontent.com/79750206/190913067-c57e6207-7e1f-4c00-ad7d-56af341d5582.png)

### System

- Device: Zenbook
- OS: Linux Mint 20.3
- Browser: Brave
- Version: v1.43.93

**Comment by moT01** [comment]
I'm guessing that these instructions were written at a time when the flexbox project came after this skyline project. Since campers should have already gone through that flexbox project, I think we can change this. We could just make the instructions for this step a little less explicit. Here's one example:

"Center the parts of your building by turning the `.bb1` element into a flexbox parent. Use the `flex-direction` and `align-items` properties to center the children.

Or we could possibly split it up into three steps:
1. "Turn your `.bb1` element into a flexbox parent so you can center the parts of the building."
-hint: You should give `.bb1` a `display` of `flex`
2. Set the `flex-direction` so the building items are in a column layout.
-hint: Your `.bb1` should have a `flex-direction` property
-hint: You should give `.bb1` a `flex-direction` of `column`
3. Center the items horizontally using a flex property
-hint: Your `.bb1` should have an `align-items` property
-hint: You should give `.bb1` an `align-items` property of `center`

**Comment by lucyferu** [comment]
yeah, i think the three steps are cool.
they also sound less explicit than the first one you wrote which i think it's more effective.
i prefer when given directions without the actual code i need to use so i can try and fail and try again until i guess. 😸

**Comment by ieahleen** [comment]
@lucyferu that would be awesome if you can!

**Comment by Avijit-1352** [comment]
can i work on this

**Comment by ShaunSHamilton** [comment]
@Avijit-1352 
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ieahleen** [comment]
I would suggest to 

> Center the parts of your building by turning the `.bb1` element into a flexbox parent. Use the `flex-direction` and `align-items` properties to center the children.

I like this, it feels much less handholding, considering flexbox was alredy introduced earlier.

**Comment by lucyferu** [comment]
> @lucyferu that would be awesome if you can!

there are the steps in which flexbox is mentioned (and assumed not to been known) :

[13](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-13); [20](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-20); [32](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-32); [66](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-66); [71](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-71); [102](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-102).

**Comment by ieahleen** [comment]
Step 13 has already a PR dedicated

The others also will need to be changed to not spoon feed flexbox. The hints can probably stay the same, the instructions will need to be less "use thie exact property with this exact value" and more "use flexbox for this purpose" 

I wonder if we can expand the scope of this issue or open a new one...

Thank you @lucyferu for the report on the steps that have this issue

**Comment by ieahleen** [comment]
reopening for the other steps

**Comment by getcoder-top** [comment]
hiii, ieahleen can you please explain the issue,

**Comment by getcoder-top** [comment]
> reopening for the other steps

hiii,
can you please explain the issue to me

**Comment by ieahleen** [comment]
The steps [20](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-20); [32](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-32); [66](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-66); [71](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-71); [102](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-102) speak of flexbox as if the learner has never learned it before, the steps need to be changed so that instead of giving exactly what to write in the css, the step description should instruct to use flexbox for the goal of the step, describing the goal, not the property/value pair to use.

**Comment by ieahleen** [comment]
@denquinlan We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @lucyferu, and thank you again for your help everyone.

I took a closer look at the history for the steps mentioned here (13, 20, 32, 66, 71, and 102), and it seems like we can close this.

Steps 13, 20, 71, and 102 all had descriptions with the issue originally mentioned in the OP, and have all been fixed. Now they all assume that the learner has some knowledge of Flexbox from the previous Photo Gallery project.

Steps 32 and 66 don't need to be fixed. Those steps mention Flexbox or a Flexbox related property, but don't have the same issue where Flexbox is treated as a new concept.
