### ISSUE TITLE
Learn accessibility by building a quiz - step 37

### ISSUE THREAD

**Issue by WitchDevelops** [freeCodeCamp/freeCodeCamp#47574]
### Describe the Issue

The instructions say to give a **name** attribute to the  **select** element.

> Step 37
> Link the first **label** element to the **select** element, and give the **select** element a **name** attribute.

When I do it, code doesn't pass the tests, and the hint says:
> Hint
> You should give the **select** element an **id** attribute.

For a novice, it is confusing. Are they the same? Probably not. Instructions are not clear here.
![Accessibility quiz step 37](https://user-images.githubusercontent.com/112077394/191334077-39e9ea77-9ad4-4ced-b009-7240869c079d.png)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-37

### Your code

```
            <div class="question-block">
              <label for="dropdown-menu">Are you a frontend developer?</label>
            </div>
            <div class="answer">
              <select name="dropdown-menu" required>
                <option value="">Select an option</option>
                <option value="yes">Yes</option>
                <option value="no">No</option>
              </select>
            </div>
```

### Expected behavior

I expected the tests to pass, as my code seems correct and follows the instructions.
The instructions should get changed from "give the **select** element a **name** attribute." to "give the **select** element a **name** and an **id** attributes."

### Screenshots

![Accessibility quiz step 37](https://user-images.githubusercontent.com/112077394/191334417-d8065f44-e0e0-4f68-8105-1e433dc0a2a5.png)

### System

- Device:  Laptop
- OS: Windows 10
- Browser: Chrome, Safari
- Version: 105.0.5195.127

**Comment by ShaunSHamilton** [comment]
Hello there,

This is intentional.

In order to link a `label` element to a form element (e.g. `select`), the `label` element needs a `for` attribute with a value matching the form element's `id` attribute.

So, you are instructed to give the `select` element an `id` attribute:
> Link the first `label` element to the `select` element

So, in the same way you are not explicitly told to give the `label` element a `for` attribute, you are not explicitly told to give the `select` element an `id` attribute. It is not possible to link the existing `label` element to the `select` element without giving the `select` element an `id` attribute.

Hope this clarifies

**Comment by WitchDevelops** [comment]
Hello,

thank you for the clarification. I thought it was a mistake in
the instructions, but I was wrong. Now I understand :)

all the best,
Domi
