### ISSUE TITLE
Cat Photo App - Step 56 Common Error

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47601]
### Describe the Issue

This is a common error on this Step - we should modify the hint to point out the capitalization 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-56

### Your code

```html
<input id="loving" type="checkbox"> <label for="Loving">Loving</label>
```

### Expected behavior

User should receive hint that helps them see the capitalization error

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
The current hint is:

"The new `label` element should have a `for` attribute with the value `loving`. You have either omitted the value or have a typo. Remember that attribute values should be surrounded with quotation marks."

Technically, the attribute value doesn't need to be wrapped in quotes since there are no spaces in the value. Also, it will pass if you don't use quotes for the value, so this part of the hint seems unneeded and should probably be removed.

@jeremylt Are you thinking that we should have a separate test just to check whether the `for` value has been capitalized? Or do you think we just add a warning to the current hint reminding them that capitalization (or lack thereof) matters?

**Comment by jeremylt** [comment]
I'm not quite sure what the best way forward would be. I just know what most questions for this step on the forum are related to Loving vs loving.

**Comment by ShaunSHamilton** [comment]
We do have dynamic hints we can use: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/61a8fe15a6a31306e60d1e89.md
