### ISSUE TITLE
preview in new window disappears if resize the parent window

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47608]
### Describe the Issue

The preview-in-new-window is a really nice feature.
But if I want to have the editor parent page and the popped out window on the same screen I need to resize the parent window, and below a certain size, the preview window disappears.

### Affected Page

All with the preview window

### Your code

N/A

### Expected behavior

I would expect to not have the preview window disappear. I have often the dev-tools open in a specific way and those disappear too.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ojeytonwilliams** [comment]
cc: @moT01 

@ieahleen do you know what width triggers the disappearance?  My guess is that it's going from desktop display to mobile.

**Comment by moT01** [comment]
I noticed this @ieahleen - and yes, that is the problem @ojeytonwilliams. The mobile layout just doesn't include that option at the moment. I wanted to get this feature live, it was a little trickier to add there - I didn't actually try, so it may not be that tricky. I suppose the minimum thing we could do is basically duplicate what we did in the desktop layout - you would probably have to click the button to reopen the preview window after it disappears if we do this.

One thing I played around with a little when working on that PR was moving all the layout settings to redux. e.g. the pane sizes, the preview state, etc. That way we should be able to keep the layout between steps instead of it resetting on each step. We could potentially move just the preview state to redux for this issue, then we should be able to keep the window open when you resize down to the mobile size.

Probably a separate issue, but one thing I noticed when looking at this just now is that the lower jaw resets when you resize the window down to mobile, as well - e.g. the hints disappear.

**Comment by CallmeHongmaybe** [comment]
I see this issue's been going on for a little over a month now, can I still make a PR from this ?

**Comment by moT01** [comment]
The PR linked above will solve the problem of the preview not staying open when moving between challenges, but I don't believe it will solve this problem of the preview disappearing when resizing the window to the mobile layout. I am going to add a help wanted label - if anyone wants to try and tackle this problem, feel free to give it a try.

**Comment by BalanaguYashwanth** [comment]
hey @moT01 ,

The problem is pop-out preview window is disappearing, when resizing to mobile window ?

**Comment by moT01** [comment]
Correct, the pop-out preview (portal) would need to be added to the mobile layout I believe.

**Comment by CallmeHongmaybe** [comment]
I don't think it's enough after testing it myself. Any input would be helpful.
