### ISSUE TITLE
Add tests for navigating language menu with keyboard

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47649]
### Is your feature request related to a problem? Please describe.

> Thanks a ton for fixing those lint errors - it's looking way better.
> 
> A couple of things went a bit wrong, though.
> 
> The keyboard navigation is broken - probably because of the changes to `doKeyPress`, since case matters when it comes to `event.key`.
> 
> This also didn't trip up any tests and I feel like it should have. Doesn't need to be much, but checking that the language selector opens with enter and can be navigated by the arrow keys would be good.

See [comment 1](https://github.com/freeCodeCamp/freeCodeCamp/pull/46644#pullrequestreview-1067444828)

> I was going to try and add some tests to this PR - I found that [cypress doesn't support pressing the tab key](https://docs.cypress.io/api/commands/type#Tabbing). There's a helper plug-in we can use, but I didn't want to expand this PR that much right now. I say we go with this as it is and I can make a separate PR with some tests.

and [comment 2](https://github.com/freeCodeCamp/freeCodeCamp/pull/46644#issuecomment-1251502538)

**Comment by Aman123lug** [comment]
@moT01  assign me i can work

**Comment by moT01** [comment]
We don't typically assign issues @Aman123lug - the first PR that fixes the issue will be accepted. Feel free to work on it and create a PR 👍

**Comment by Aman123lug** [comment]
@moT01  okay thanks

**Comment by yashdev9274** [comment]
> We don't typically assign issues @Aman123lug - the first PR that fixes the issue will be accepted. Feel free to work on it and create a PR 👍

Fine, then I'll work on it too.

**Comment by himanu** [comment]
Hi @moT01, could you please explain the feature which needs to be implemented or the final goal of this issue?


On official website, I have tried navigating the language menu using the keyboard, it was working fine.
By pressing the enter, the language selector can be opened and can be navigated by pressing key-up and key-down.

**What I understand** is this issue is only about adding navigation-related tests to `header.test.tsx` file. No need to change the code inside components folder.
Am I right in my understanding?

**Comment by bbsmooth** [comment]
> this issue is only about adding navigation-related tests

This is correct. The keyboard functionality for the menu and language submenu is fine now, nothing needs to be fixed there. The first part of this issue was explaining that at one time the keyboard functionality was accidentally broken and that we would have some tests in place to test for that so that we don't accidentally break it again and not notice. It also suggests the bare minimum we would need to test.

**Comment by saw-jan** [comment]
@moT01 and others, I have proposed PR #47791 for this issue. Please, have a look if that is acceptable or not.

**Comment by Prince-Mendiratta** [comment]
Hi @Sboonny, is this issue available again for contributions? I'd like to work on this.

**Comment by Sboonny** [comment]
@Prince-Mendiratta, you have to communicate with @saw-jan, so both of don't get in each other ways while improving the test.

But the issue won't be closed after their PR, there are still tests need to implemented based on this comment

https://github.com/freeCodeCamp/freeCodeCamp/pull/46644#issuecomment-1210022946

**Comment by Prince-Mendiratta** [comment]
I could create a branch based off @saw-jan 's PR and send a new PR with all the new tests so we could have all the tests added in one PR and the majority of relevant discussion being there if @saw-jan is alright with this?

**Comment by nayabatir1** [comment]
Hey I have written tests as pr [#46644 comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/46644#issuecomment-1210022946)

- [x] When the main navigation menu is expanded and keyboard focus is on an item in main menu, the Esc key should close the menu and put keyboard focus on the Menu button.

- [x] When focus is on the Change Language item in the main menu, the up arrow should open the lang menu and place focus on the last item in the lang menu.

- [x] When focus is on the Change Language item in the main menu, the down arrow should open the lang menu and place focus on the first item in the lang menu.

- [x] When lang menu is opened and keyboard focus is automatically moved into lang menu, the up and down arrow keys should move the keyboard focus up/down one menu item.

- [x] In the lang menu, when focus is on the last item, arrow down should move focus to first item. Similarly, when focus is on the first item, arrow up should move focus to last item.

- [ ] When focus is on an item in the language menu, Shift + Tab should close the lang menu and put focus on the item immediately above the Change Language item.

- [ ] When focus is on an item in the language menu, Tab should close the lang menu and put focus on item immediately after the Change Language item, or if no such item exists then put focus on the next element that can receive focus on the page (which is the Sign In button at this time).

- [x] When focus is on any item in lang menu, the Esc key should close the lang menu and put focus back on the Change Language menu item.

I was unable to write 2 tests as cypress don't support tab key yet. [need tab support](https://github.com/cypress-io/cypress/issues/299). This issue is still open.
I also tried to [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) it didn't workout.

Do let me know how shall I proceed ahead.

**Comment by saw-jan** [comment]
> I could create a branch based off @saw-jan 's PR and send a new PR with all the new tests so we could have all the tests added in one PR and the majority of relevant discussion being there if @saw-jan is alright with this?

I have added the additional tests in PR https://github.com/freeCodeCamp/freeCodeCamp/pull/47791#issuecomment-1274069643
