### ISSUE TITLE
Missing button text in Bootstrap Add Elements within Your Bootstrap Wells

### ISSUE THREAD

**Issue by munyanezaarmel** [freeCodeCamp/freeCodeCamp#47728]
### Describe the Issue

in the instructions, they forgot to specify the button text and tests are passing without button text I think this is a good practice a button should always have a text and tests can not run without it for good practice

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/bootstrap/add-elements-within-your-bootstrap-wells

### Your code

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
<button class="btn"></button>
<button class="btn"></button>
<button class="btn"></button>


      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">

<button class="btn"></button>
<button class="btn"></button>
<button class="btn"></button>

      </div>
    </div>
  </div>
</div>
```

### Expected behavior

the button element should have a button text  I think for good practice button should always have a button text in the instructions they forgot to include button text and tests are passing without it I think this should be solved 

### Screenshots

![image](https://user-images.githubusercontent.com/73389979/193400182-ff91621c-d3d2-46cb-a82b-84a620e3f47b.png)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: 22

**Comment by SiddheshKukade** [comment]
I would like  to work on this issue please assign me

**Comment by ieahleen** [comment]
The text of the buttons is added in a following step, this one
https://www.freecodecamp.org/learn/front-end-development-libraries/bootstrap/label-bootstrap-buttons

This may require more work than just adding the text on the reported step

**Comment by Samaresh-Das** [comment]
I would like to contribute to this issue. May I get assigned please?

**Comment by ieahleen** [comment]
@Samaresh-Das thank you for your interested in contributing, please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted

**Comment by munyanezaarmel** [comment]
thanks, @ieahleen I was wrong

**Comment by JUSTICEESSIELP** [comment]
[ieahleen](https://github.com/ieahleen) please assign this project to me and label it hacktoberfest

**Comment by ieahleen** [comment]
@JUSTICEESSIELP thank you for your interested in contributing, but this issue is not open for contributions, please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted

**Comment by bbsmooth** [comment]
We do this incremental building of an element(s) in a lot of places. So even though something doesn't start out as accessible, it does become accessible at some point. I'm guessing in this case we only add the button and not the text in this step in order to keep it short and simple. And as @ieahleen pointed out, the text is added in a later step. If we don't want to make a change to this step then I would recommend we add a little blurb about the necessity of having text on buttons in the step that adds the text. Right now it reads:

> Just like we labeled our wells, we want to label our buttons.

In order to highlight the importance of a button's text for accessibility, perhaps change it to something like:

> A button should have text associated with it in order to make it accessible to all users.

Technically, this text does not need to be visible (for example, you could use a well-known icon instead of visible text) but then underneath you would use `aria-label` or `aria-labelledby` to give it an accessible name. But I think this much detail might be too much for this particular step. So using "text associated with it" is ambiguous enough to cover either method.

**Comment by moT01** [comment]
I don't think we need to change anything here. We do this throughout the curriculum, specifically the new curriculum, where we add empty elements and fill them in later. I would vote to leave these as they are. I know the new front end curriculum probably won't be ready for a while, but these challenges will become legacy and not maintained at some point. We have discussed that want to minimize (or eliminate) the work we put into these challenges so we can focus on the new curriculum.

**Comment by ieahleen** [comment]
Considering the discussion, I am closing this issue. You can request to have it reopened if you think it's needed.
