### ISSUE TITLE
freeCodeCamp profile is missing indications of fields

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47847]
![image](https://user-images.githubusercontent.com/26656284/194050783-42296fd9-f3d2-4f63-9582-d88ef5986288.png)

When you read a profile it's not clear that those are Name, Location, About

![image](https://user-images.githubusercontent.com/26656284/194050839-7ed5864f-073c-4247-8c5b-c7724d24246a.png)

Maybe @bbsmooth can give some accessibility indications?

**Comment by bbsmooth** [comment]
Hey @ieahleen How do I get to that profile you displayed in your first pic?

**Comment by ieahleen** [comment]
Thank you @bbsmooth , it's at freecodecamp.org/ieahleen

**Comment by bbsmooth** [comment]
There are quite a few accessibility issues with this profile page, but I'll stick to the topic at hand. For the personal information displayed in your first pic above, there is no requirement that you need to label what each of these are. Yes, it is not clear what some of these are, but it is not clear for everyone, regardless of how you are accessing the page, so there is no accessibility issue here since everyone experiences this ambiguity. The decision as to whether you want to label these to make it clearer is a usability issue. If we want to make sure that everyone understands what these are then we should label them. If we are fine with the ambiguity then we can leave them as is.

**Comment by ppeters0502** [comment]
I tested out adding translatable labels next to the Name, Location, and Bio to make it a little clearer. If this looks ok, and there aren't any accessability issues, I can submit a PR with these changes.
![image](https://user-images.githubusercontent.com/6621379/194146362-22449247-be9e-4570-b156-e239fa0dc208.png)

**Comment by moT01** [comment]
I think I would prefer to leave this how it is - but I'm not against adding some labels either. That looks pretty decent. I wonder if it would look better with the colons all lined up - e.g. the colon (`:`) on each line would be horizontally centered. Hmm, I think that `about` section allows quite a lot of characters so that may not work well.

**Comment by ojeytonwilliams** [comment]
> I think I would prefer to leave this how it is 

It's not terrible as is, but I think there's room for improvement.

However, I'm not sure we need labels for all of them, since Name should be self-explanatory and About probably is, too. That said, Location being the only one with a text label looks a little strange.  We could try using a icon (with aria-label) for Location and see how that looks.

@ahmadabdolsaheb what do you reckon?

**Comment by ppeters0502** [comment]
I know we're still kind of on the fence about whether labels are needed or not. I tweaked my original changes I screenshotted earlier to line the labels up and put the responses in a <Col> so that they don't bleed past what would look normal. I think this looks better, but I totally understand if we go towards not having labels:
![image](https://user-images.githubusercontent.com/6621379/194386701-0c6814bf-053b-4c79-937a-4875345491eb.png)

**Comment by nayabatir1** [comment]
> Here's one more screenshot with a longer About section so you can see how it would look if someone wrote a novel for their bio :) ![image](https://user-images.githubusercontent.com/6621379/194388442-a9a92f94-de49-4cdc-a6f1-0abf9cf5da74.png)

This is neat 🔥

**Comment by ppeters0502** [comment]
I went ahead and submitted a PR with these changes, if everyone else thinks we shouldn't need the labels, I can close the PR. If everyone approves of the changes, if I could get a hacktoberfest label applied, that would be great!

**Comment by ahmadabdolsaheb** [comment]
The redesign of the Profile is way overdue. How about organizing the user information section in the following way. It should make things more obvious.


<img width="483" alt="Screen Shot 2022-10-11 at 4 22 36 PM" src="https://user-images.githubusercontent.com/4591597/195102593-b94ecde6-f867-4a00-b568-5a9cb25da87e.png">

**Comment by moT01** [comment]
I like Ahmad's design here - but it also doesn't include any labels. So I think we are probably leaning towards not adding labels. I looked a few profiles quick - twitter, github, our forum - they don't really include labels either. But they do seem to universally use some icons to indicate things where applicable...

Twitter:
![Screen Shot 2022-10-20 at 11 44 33 AM](https://user-images.githubusercontent.com/20648924/197009357-ca68591e-6bf8-4ba0-a5ca-fd171bfe585b.png)

GitHub:
![Screen Shot 2022-10-20 at 11 45 10 AM](https://user-images.githubusercontent.com/20648924/197009343-5d52a914-a0d9-48b4-a164-a25cebcddb7d.png)

Forum:
![Screen Shot 2022-10-20 at 11 44 48 AM](https://user-images.githubusercontent.com/20648924/197009315-99453426-4949-4b83-8675-7881dee1190e.png)

Our current profile pages have some icons already, so I would vote to stick with those. We could find an icon for each of the areas - or maybe just the location can have one of those drop pins or something. Wondering if we should have this issue focus on adding some icons and make another for the redesign, or just do the redesign here.

**Comment by moT01** [comment]
For this specific issue, I think we should either add another icon for the location, or just leave it all as is and close this - and create a separate issue for the redesign.

**Comment by ahmadabdolsaheb** [comment]
That is a good idea. As Ilenia mentioned, the Profile info is not presented well. It would be better if we focus our attention to a redesign. 

I am closing this issue in favor of #48234
Please let me know if this has been closed by mistake.
