### ISSUE TITLE
Step 12 Minor Tweek

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47854]
### Describe the Issue

The changes to Step 12 on Cat Photo App seem to be paying off. 

One last common issue seems to be the period inside of the anchor text. Should we add a dynamic hint? 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

```html
<html>
  <body>
    <h1>CatPhotoApp</h1>
    <main>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos --> 
      <p>Click here to view more <a href="https://freecatphotoapp.com"> cat photos.</a></p> 
      <a href="https://freecatphotoapp.com">link to cat pictures</a>
      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
    </main>
  </body>
</html>
```

### Expected behavior

Clear hint indicating to remove the period.

### System

All

**Comment by nayabatir1** [comment]
Why do we need to add extra information, as per instruction `cat photos` is without period(.).

**Comment by KravMaguy** [comment]
which option do you want? 
1. clear hint to remove the period
2. accept a link text with a period at the end

Ive done #2

**Comment by jeremylt** [comment]
We haven't decided yet

**Comment by moT01** [comment]
Change the test so it so it doesn't matter where the period is.

**Comment by KravMaguy** [comment]
Sure no problem, is this open to working on it or not? I've been told the
issue is not open to accepting pull requests

**Comment by jeremylt** [comment]
There is a label when its ready for contribution. 

I don't think we care about the period, so I'm fine making the test more flexible and letting the period be optionally included.

**Comment by jeremylt** [comment]
I closed the PR because having this discussion in a PR tends to pull the contents of the changes back and forth as the discussions work towards consensus. 

WWe have three consistent votes for the second, to accept the period inside or outside of the anchor, but in a consistent location. Placing the period in a location that turns the words into gibberish should not be allowed.

I generally like restructuring the sentence to avoid this issue, but I don't see a clean way to do that here.

**Comment by ShaunSHamilton** [comment]
I am all for keeping programming what it is - absurdly specific. So, I like the suggestion to make the hint dynamic/specific.

Either, have a test specifically looking for a `.` within the textContent. Or, use a dynamic hint to say "expected X, but found Y".

**Comment by KravMaguy** [comment]
> I am all for keeping programming what it is - absurdly specific. So, I like the suggestion to make the hint dynamic/specific.
> 
> Either, have a test specifically looking for a `.` within the textContent. Or, use a dynamic hint to say "expected X, but found Y".

The user can either have a period at the end of the link or not. and display a dynamic hint otherwise. Is the work I did good? 

problem is equal only take two parameters I cant do equal(userInput, "cat photos"||"cat photos")
should we change modify this:

https://github.com/freeCodeCamp/freeCodeCamp/pull/44279/files/8a535e7489b96754df62a7e3e8879ec1689c3c62

**Comment by ShaunSHamilton** [comment]
> The user can either have a period at the end of the link or not. and display a dynamic hint otherwise.

No. We specifically want to make sure Campers do **not** include a period in the link.

**Comment by moT01** [comment]
My suggestion to...

> Change the test so it so it doesn't matter where the period is.

comes because I recall a very similar conversation on another issue. My original position in that conversation was similar to yours @ShaunSHamilton - programming doesn't allow typos, so why would we? But I was overruled because we don't want people to get stuck in spots like this. They completed the main learning task of adding the anchor element, but just misplaced a period - so we decided to be more flexible in spots like this. I really don't care in this instance, it's pretty minor - but that was the result of that discussion and my reasoning for the suggestion.

**Comment by KravMaguy** [comment]
> > The user can either have a period at the end of the link or not. and display a dynamic hint otherwise.
> 
> No. We specifically want to make sure Campers do **not** include a period in the link.

ok ive fixed it.

https://github.com/freeCodeCamp/freeCodeCamp/commit/25078213a76767e789a2c6a7f1592e90f16840ed

**Comment by ShaunSHamilton** [comment]
@moT01 I suppose that is a fair point. My reason for sticking with requiring specificity is we have the ability to say: "We expected `some text`, but you put `some text.`".

We could even go as far as pointing out the diff.

**Comment by nayabatir1** [comment]
If instruction provided says `some text`, I don't think we should allow `some text.`

**Comment by bbsmooth** [comment]
Just throwing out another option that I alluded to above. Reword the sentence to something like:

"View more cat photos from our collection."

And have the link text be "more cat photos". This gets rid of the awkward "Click here" at the beginning of the sentence, which if you think about it, the "Click here" should be the link. But really, "Click here" is so mid-90s early internet. We shouldn't be encouraging it.

**Comment by KravMaguy** [comment]
> We could even go as far as pointing out the diff.

Very cool, i'd like to do it, does this feature currently exist somewhere in fcc? if not, it would be a seperate feature request and have its own issue yes?

> If instruction provided says some text, I don't think we should allow some text.

Agreed, I think it is enough for most users who have made it this far to figure out what needs to be done in order to pass the challenge:

![image](https://user-images.githubusercontent.com/37171082/194624198-d841c2a8-aa57-4273-8bca-81cfe8de7e49.png)

**Comment by RandellDawson** [comment]
> Agreed, I think it is enough for most users who have made it this far to figure out what needs to be done in order to pass the challenge:

Not sure what you mean by "made it this far".  The test is in a particular order so that the correct hint is given.  I would just stick with creating the hint, so that it says  "We expected some text, but you put some text." as @ShaunSHamilton suggested.  Creating a diff seems unnecessary because you can just tell the user what they have and what is expected without creating a diff.

**Comment by KravMaguy** [comment]
Ok, I had referenced this. I hope it solves it.

https://github.com/freeCodeCamp/freeCodeCamp/commit/25078213a76767e789a2c6a7f1592e90f16840ed

then it was suggested "We could even go as far as pointing out the diff." that is why I thought that what I had done was perhaps not enough.

**Comment by nayabatir1** [comment]
@KravMaguy It is advisable to create PR for issue with label `help wanted`. 
Read contribution guideline for more info.

**Comment by jeremylt** [comment]
> Just throwing out another option that I alluded to above. Reword the sentence to something like:

> "View more cat photos from our collection."

I think this is a bit more work but ultimately a better fix.

**Comment by Sembauke** [comment]
Let's change it to: `See more cat photos in our gallery.` please follow Jeremys comment above.
