### ISSUE TITLE
"Exercise Tracker" typo in `substring` method

### ISSUE THREAD

**Issue by sonnguyen112** [freeCodeCamp/freeCodeCamp#47887]
### Describe the Issue

I have pass all test case of "Exercise Tracker" challenge except the 7th test case("you can POST to /api/users/:_id/exercises with ..."), I tried many way but still can't pass this test case. When i open the console of Chorm, i found the bug "Date.now(...).subtingr is not a function" when i click on the button "I've completed this challenge" to submit the `project```

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### Steps to Reproduce

1. Open the console of brower
2. Fill the link into Solution Link
3. Click on "I've completed this challenge"

### Expected behavior

This error should be disappear

### Screenshots

![bug_FCC](https://user-images.githubusercontent.com/80495667/194501968-4e84ddf7-0e20-4d64-9fe2-3b2ecf5bfa38.png)

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [106.0.5249.103]

**Comment by ieahleen** [comment]
Please provide the link to the project that you submitted

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md

Line https://github.com/freeCodeCamp/freeCodeCamp/blob/93347ea2856ce267e016b6690cef2ca64afaf293/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md?plain=1#L167
contains the typo, `substingr` should be `substring`.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by surajrane42** [comment]
Hello, I am interested in working on it

**Comment by ieahleen** [comment]
@surajrane42 hey there, I suggest reading our contributing guidelines! as it says, all issues with https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only and https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted labels are up for grabs

**Comment by surajrane42** [comment]
@ieahleen I have fixed this issue and raised a PR. 
https://github.com/freeCodeCamp/freeCodeCamp/pull/47892
