### ISSUE TITLE
"Exercise Tracker" typo in substring method 

### ISSUE THREAD

**Issue by sonnguyen112** [freeCodeCamp/freeCodeCamp#47934]
### Describe the Issue

When i click the "I've completed this challenge" button in "Exercise Tracker" challenge, the "Date.now(...).substingr is not a function" still appear, i think in source code still have some typo bugs, so i use grep to find "substingr" and i found 4 bug

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### Steps to Reproduce

1. Fill the link into Solution Link
2. Open the console in brower
3. Click on the "I've completed this challenge" button

### Expected behavior

This error is not appear

### Screenshots

![bug_FCC](https://user-images.githubusercontent.com/80495667/194716618-a0dbe29f-6cdb-4b2e-9aea-14729fae85b4.png)
![bug_fcc_2](https://user-images.githubusercontent.com/80495667/194716651-c09f33e0-0d9f-4139-9524-c4caca6d49f1.png)

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [106.0.5249.103]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in code base. This means that the next time we push to production, this problem should be fixed. Because of this, we're closing this issue.

Files in languages other than English will be updated using the translation workflow.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
