### ISSUE TITLE
CatPhotoApp Step 12 (the part "by placing these words inside of opening and closing anchor tags")

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#47983]
### Describe the Issue

I know many people have been working on improving this step. I see currently there is another issue #47854 open (it's about how to deal with `.` ). Hope you don't mind me opening another issue here.

Currently the latter part of the instruction says:
>In the text of your `p` element, turn the words `cat photos` into a link to `https://freecatphotoapp.com` **by placing these words inside of opening and closing anchor (a) tags**.

The starting code look like this:
```html
      <p>Click here to view more cat photos.</p>
      <a href="https://freecatphotoapp.com">link to cat pictures</a>
```

As an ESL leaner, it seems less confusing to me if the instruction said "**by adding opening and closing anchor (a) tags around these words**"

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

At first, I thought I was requested to cut the "cat photos" part out and paste it in between the existing `a` tags below.  Something like this:
```html
      <p>Click here to view more .</p>
      <a href="https://freecatphotoapp.com">cat photos</a>
```

Or like this (this one passes the test, but contradicts with the starting code of the next step):

```html
      <p>Click here to view more <a href="https://freecatphotoapp.com">cat photos</a>.</p>
      link to cat pictures
```

### Expected behavior

It seems less confusing if the instruction said "**by adding opening and closing anchor (a) tags around these words**"

### System

- Device: Laptop
- OS: Windows 10
- Browser:Chrome
- Version: 106.0.5249.103

### Additional context

Context: I'm working on translating the curriculum and noticed this issue.

If there are not many confusion like this on the forum, then it could be just me, so I'm not strongly requesting to change it but just a suggestion.

**Comment by jeremylt** [comment]
Changing 

> by placing these words inside of opening and closing anchor (`a`) tags.

to

> by adding opening and closing anchor (`a`) tags around these words.

makes sense to me

**Comment by nayabatir1** [comment]
It feels like both are same thing, just a way of writing things differently

**Comment by ieahleen** [comment]
Let's see if this change would help...

Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc174fcf86c76b9248c6eb2.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
