### ISSUE TITLE
Reduced unused Javascript

### ISSUE THREAD

**Issue by sonicx180** [freeCodeCamp/freeCodeCamp#48016]
I ran a lighthouse test on free code camp and it said to reduce unused Javascript.

See screen shot here:

![Screenshot 2022-10-12 8 16 05 PM](https://user-images.githubusercontent.com/83236320/195491062-adcb0977-16c4-4f37-9bf2-71cb44b2a0c3.png)

Another screen shot :

![Screenshot 2022-10-12 8 16 47 PM](https://user-images.githubusercontent.com/83236320/195491156-64f8c55d-f5b9-4d50-8523-21bccd3e746a.png)

Thanks for helping!

**Comment by astitva0011** [comment]
assign this to me

**Comment by ieahleen** [comment]
@astitva0011 We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by raisedadead** [comment]
@sonicx180 

Thanks for bringing this up. 

Please look at closed issues #40419 and #37742 for more context on what we have done in the past. You are welcome to research past PRs and the codebase as well.

I am going ahead and closing this because of issues requesting perf improvements usually go stale. We - the maintainers - know perf & benchmark issues exist, and you always have scope to improve.

That is, as a contributor you can create incremental fixes if you so prefer. So if you have any suggestions in mind we would love to see a PR.

Thanks and happy contributing.

cc @freeCodeCamp/dev-team
