### ISSUE TITLE
Is there a plan for adding research  ?

### ISSUE THREAD

**Issue by imvetri** [freeCodeCamp/freeCodeCamp#48141]
Hi,

freecodeCamp' is doing amazing job. I'm amazed by @QuincyLarson and supporting members keeping this going.

Phd / Masters / Bachelors shouldn't restrict an individual from chasing their ideas. Some curious minds believe in themselves and may find it hard to get it in reality.

I'm not asking for one more curriculum like I asked in the past and I'm unable to put it in right words.

To be crisp - **how about Computer Research Topics?**

Don't have to follow how academicians do it, it can be free code camp style. Just a thought.

https://github.com/freeCodeCamp/freeCodeCamp/issues/17486

**Comment by raisedadead** [comment]
Hi @imvetri 

Thanks a lot for this question. Could you re-open this on our forum instead? This open-ended question makes a good fit there instead of the issue tracker.

> ##### freeCodeCamp forum: https://forum.freecodecamp.org

As a staff member, I can say that we are happy to discuss this and think there are some plans. But again, it's best to discuss this on the forum.

**Comment by imvetri** [comment]
@raisedadead I'm not doing it. I'm not comfortable with other interfaces other than github.

**Comment by imvetri** [comment]
@raisedadead  If you were in charge of maintaining these topics, why wouldn't you copy paste my contents over there? leave this opened until someone else notices it rather than closing it.
