### ISSUE TITLE
code returns values greater than 5 but test doesn't pass

### ISSUE THREAD

**Issue by caseyjohnston** [FreeCodeCamp/FreeCodeCamp#4823]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3E%205%3B%0A%20%20%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7B%20return%20newArray%3B%20%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val > 5;
  
});

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by bugron** [comment]
@caseyjohnston thanks for posting this issue!
I thinks you misunderstood how `filter` works. 
>Any array element for which the callback returns true will be kept and elements that return false will be filtered out.

To remove all elements that are greater than 5 you should keep all elements that are less or equal to 5 so your condition is `val <= 5` and not `val > 5`.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by warren2k** [comment]
@bugron I don't think this is correct. Filter does not alter the contents of the original array. How then, can we obtain an array with only elements greater than 5, when our end result in using `val <= 5` gives us two arrays with the following contents:

oldArray: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
newArray: [1, 2, 3, 4, 5]

I don't know if the behavior of filter changed since the definition of this Waypoint, but if you run the code in your developer tools, you'll see that these are the results, and they do not meet the requirements of the test, so I think the test is wrong.

**Comment by warren2k** [comment]
@bugron Never mind. I see that I am misunderstanding the instructions. I didn't understand it as asking us to get only the values less than or equal to 5, which is what happens if you filter out all values greater than 5...duh.
