### ISSUE TITLE
Number Guessing Game Pass Validation

### ISSUE THREAD

**Issue by shanethecrane** [freeCodeCamp/freeCodeCamp#48360]
### Describe the Issue

The tests 1:1 7 through 13 is looking for me to print certain statements, which I am doing, but it does not pass.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/build-a-number-guessing-game-project/build-a-number-guessing-game

### Your code

```

```

### Expected behavior

I would expect the "Enter your username:" test to pass, but it's not even when it's the first line my program prints, reads a username, and queries against my tables with said username

### Screenshots

![Number Guessing Game](https://user-images.githubusercontent.com/22037659/199122638-58cddf39-3372-4800-a0cd-78b892860522.PNG)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by shanethecrane** [comment]
[number_guess.sh.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/9905424/number_guess.sh.txt)
[number_guess.sql.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/9905425/number_guess.sql.txt)
I've attached my .sh and .txt files for this

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Ask for help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
