### ISSUE TITLE
CSS Penguin Step 75: the change is not visible on some browsers

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#48449]
### Describe the Issue

The instruction starts with:
>If you look closely, the heart emoji is slightly different.

I can see the purple heart has become slightly bigger in Firefox. However, I can't see the difference in Chrome or Edge.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-75

### Your code

```
.shirt {
  font: bold 25px Helvetica, sans-serif;
}

.shirt div {
  font-weight: initial;
}
```

### Expected behavior

We can change the first sentence to:
>**In some browsers,** the heart emoji **may look slightly larger**.

(I changed "different" to "larger", so that campers don't have to spend too much time looking for the difference)

And the last sentence to:
>**To make it consistent on different browsers, target** the div with the heart emoji, and **set** its font-weight to its original value.

### Screenshots

https://user-images.githubusercontent.com/25644062/200926484-26f72d6b-ff19-489a-a03c-3881b2cb1788.mp4

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome (ver. 107.0.5304.106), Edge(ver. 107.0.1418.35), Firefox (ver. 106.0.5)

**Comment by ShaunSHamilton** [comment]
> We can change the first sentence to:
> > In some browsers, the heart emoji may look slightly larger.
>
> (I changed "different" to "larger", so that campers don't have to spend too much time looking for the difference)

The difference is not always the size, though. I am unable to reproduce a change in Chrome, but when I was making this, the heart would get a hashed pattern inside. There is a chance Google has changed something.

As such, I suggest we keep the use of _"different"_, and go with:

> In some browsers, the heart emoji may look slightly different.

**Comment by ShaunSHamilton** [comment]
I think that is too much useless information. We specifically removed information here: https://github.com/freeCodeCamp/freeCodeCamp/pull/44214#discussion_r761480322

**Comment by moT01** [comment]
I played with this for a bit and I really don't have a preference here. Most of instructional suggestions sound good to me - removing the step sounds good as well.

**Comment by naomi-lgbt** [comment]
> The difference is not always the size, though. I am unable to reproduce a change in Chrome, but when I was making this, the heart would get a hashed pattern inside. There is a chance Google has changed something.

I believe both the browser and operating system determine how emotes are rendered.

**Comment by nayabatir1** [comment]
Is this up for contribution ?

**Comment by mmatsumoto1026** [comment]
The "a hashed pattern inside" of heart that @ShaunSHamilton mentioned (and I also noticed this a few months ago when translating this step) can be reproduced using the [`Noto Emoji` font family](https://fonts.google.com/noto/specimen/Noto+Emoji?query=noto+emoji), as shown below.

![noto_emoji](https://user-images.githubusercontent.com/44451585/204297919-5da972f1-6f0b-4133-a329-4c317474199c.png)

We can also think that the STEP 75 imparted knowledge to the learner to control emoji colors (albeit in a different way).

Therefore, instead of removing STEP 75, how about adding the following steps:

1. Step to add `@import url('https://fonts.googleapis.com/css2?family=Noto+Emoji&display=swap');` (this may be step 75)
1. Add font-family: 'Noto Emoji' to the `.shirt div` to see the emoji color change (this may be step 76)
1. Delete the lines added in the above two steps, then resume the current step 76 procedure (this may be step 77)

**Comment by naomi-lgbt** [comment]
I don't see the need to add steps that import and remove a font for this.

I'd much rather stick with adding the note "In some browsers, the heart emoji may look slightly different from the previous step." so that we can focus on the concepts this project is actually trying to teach.
