### ISSUE TITLE
CSS Form Project

### ISSUE THREAD

**Issue by SylvesterStrydom145** [freeCodeCamp/freeCodeCamp#48454]
### Describe the Issue

On Step 48, Instructions say that you should change the display type and the margin of the input, textarea and select element. Then when you submit, the test fails because the user didn't change the width of the elements to 100%, but there is no instruction on doing so. 

Just thought that I should report this small bug.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-48

### Your code

```
input, textarea, select {
  display: block;
  margin: 10px 0;
}
```

### Expected behavior

I expected to pass the step because I followed all instructions that was laid out to me.

### Screenshots

![Screenshot 2022-11-10 125329](https://user-images.githubusercontent.com/111201019/201072685-d1495361-13a4-4ba1-8612-20dcb3b3de8d.png)

### System

- Device: [Dell Laptop]
- OS: [Windows 10]
- Browser: [Microsoft Edge]
- Version 107.0.1418.35 (Official build) (64-bit)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
