### ISSUE TITLE
Celestial Bodies Database TUTORIAL.MD instructions are not logically organized

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48452]
### Describe the Issue

When looking at the steps presented to users of the Celestial Bodies Database course in coderoad, I noticed that the list of requirements was not ordered in a way that would be considered logical. A person would need to read the whole list in order to re-organize it by the required chronology.

For eg. The list currently shows the following at the start
```
You should create a database named universe
Be sure to connect to your database with \c universe. Then, you should add tables named galaxy, star, planet, and moon
```
Then some steps later it says
```
Your database should have at least five tables
```
This instruction should be listed immediately after the first two as it informs us of the number of tables required.

Another example around the 10th line of instruction shows these 3 lines:
```
Each "star" should have a foreign key that references one of the rows in galaxy
Each "planet" should have a foreign key that references one of the rows in star
Each "moon" should have a foreign key that references one of the rows in planet
```
Then some number of lines later the following is mentioned:
```
Each primary key column should follow the naming convention table_name_id. For example, the moon table should have a primary key column named moon_id
Each foreign key column should have the same name as the column it is referencing
````
This makes many people get confused as they begin working on the list from top-to-bottom and they wonder why their primary key and foreign key links aren't being accepted (oh it's because you didn't read all the way down the list and set them up with the expected names)

We have had some people hit this issue, enough to make me investigate why. I do believe the reason is that the list has not been organized in a logical way (or that it was not made clear that the entire list should be read and considered before attempting to work on the project)

One more reason to re-order the list is related to how the checks are done. In order for this step for eg to be marked as done
`Each "star" should have a foreign key that references one of the rows in galaxy`, the user must first complete a step listed 3 rows  below this one which says `Each table should have at least three rows`
(people complete the foreign key setup then wonder why there is no checkmark shown next to it, and it turns out its because they haven't added the rows yet - an instruction they didn't quite get to yet)

### Affected Page

https://github.com/freeCodeCamp/learn-celestial-bodies-database/blob/main/TUTORIAL.md

### Your code

```

```

### Expected behavior

I would expect some instruction to warn people that the list is not ordered and must be read in full in order for the steps to be clear. Or I would re-organize the list so it works from top to bottom, and a person can read one requirement at a time without having to be fully aware of the details of the remaining steps.

One possible re-organization could be:

#### SUBTASKS

- You should create a database named `universe`
- Be sure to connect to your database with `\c universe`. Then, you should add tables named `galaxy`, `star`, `planet`, and `moon`
- Your database should have at least five tables
- Each table should have a primary key
- Each primary key should automatically increment
- Each table should have a `name` column
- All columns named `name` should be of type `VARCHAR`
- Each table should have at least three columns
- The `galaxy`, `star`, `planet`, and `moon` tables should each have at least five columns
- At least two columns per table should not accept `NULL` values
- At least one column from each table should be required to be `UNIQUE`
- You should use the `INT` data type for at least two columns that are not a primary or foreign key
- You should use the `NUMERIC` data type at least once
- You should use the `TEXT` data type at least once
- You should use the `BOOLEAN` data type on at least two columns
- Each table should have at least three rows
- Each "star" should have a foreign key that references one of the rows in `galaxy`
- Each "planet" should have a foreign key that references one of the rows in `star`
- Each "moon" should have a foreign key that references one of the rows in `planet`
- Each foreign key column should have the same name as the column it is referencing
- The `galaxy` and `star` tables should each have at least six rows
- The `planet` table should have at least 12 rows
- The `moon` table should have at least 20 rows

### System

N/A

### Additional context

Some forum questions that relate to the confusion caused by the order include:
https://forum.freecodecamp.org/t/celestial-bodies-database-foreign-key/569351
https://forum.freecodecamp.org/t/celestial-bodies-database/559342
https://forum.freecodecamp.org/t/celestial-bodies-database/565496
https://forum.freecodecamp.org/t/tasks-in-celestial-database/568823
https://forum.freecodecamp.org/t/celestial-body-database-cant-make-some-test-pass/557609
and more.

**Comment by raisedadead** [comment]
@moT01 what do you think about the above? I like the proposed changes.

**Comment by moT01** [comment]
Thanks for the detailed issue and for all the help on the forum @hbar1st 🎉 I haven't been on there much lately - I'm glad to see people are getting the help they need 👍

I would prefer to leave the user stories/tests in the order they are in - that order is intentional. The goal with that was to try and make campers use more of the things they learned. e.g. the `Each primary key column should follow the naming convention...` test is near the bottom. If it's at the top, they are more likely to name their keys correctly right away - with it at the bottom, they may have to use some `RENAME` commands. Similar thoughts with the few other tests that are "out of order". I'm quite sure that all of the tests are passable without reading further down. I think the minimal frustration this may cause is worth it to make the project a little more difficult. That frustration is not the... crappy type  - e.g. broken tests or unclear instructions - it's just... campers having to do more work. Once campers get to those tests, they should be able to complete the task and pass it. I only glanced at the forum posts you linked, but I don't think the order is the key thing causing any of their problems - they mostly just aren't completing the task asked. Some of which, may be a little unclear...

Many of the tests on this and the other RDB projects check that at least one row exists. So for the `Each "star" should have a foreign key that references one of the rows in galaxy` (and similar) tests - it checks all the "star" rows have a foreign key referencing a galaxy. But if no rows exists, it fails. This was intentional, as well, since the test was passing if the user didn't have any rows - so if you started the project, didn't do anything but run the tests, those would pass. I think this is a little unclear and could be improved. Maybe ``Each "star" should have a foreign key that references one of the rows in galaxy. You need at least one row in the `star` table to pass this test.``

A few of the other user stories mentioned...
`Each primary key column should follow the naming convention table_name_id. For example, the moon table should have a primary key column named moon_id`
and
`Each foreign key column should have the same name as the column it is referencing`
...seem pretty clear to me. Those campers just weren't doing what was asked. If you have any suggestions for grammer improvements on those, please share. Maybe ``Each foreign key column should have the same name as the column it is referencing. For example, a `moon_id` foreign key should be referencing a column named `moon_id`.``

**Comment by hbar1st** [comment]
hi Tom, thanks for your kind and detailed response as well.

Tbh, I wasn't expecting your answer that you were hoping to make things a little harder via the organization of these steps. I'm not sure how I feel about this because on the one hand, that's cool, but on the other, it makes the tests look disordered and I don't feel that's fair to you/the exercise either. 

One initial thought that comes to mind is that if we want the student to practice things like renaming, why don't we just tell them to do that? I have a tendency to read all instructions when I am unsure of something (eg. cooking recipes) and so if I had done this to this list, I would have immediately noticed the requirements aren't listed in order and evaded any extra work... My point is, I think, that it seems like a not very balanced/even way of treating everyone. Those more inclined to read first will have an easier time? (also I never suggested renaming the columns to anyone on the forum with this issue, so for all we know they were dropping them and re-adding them when they were made aware of the instructions) I think it is good to think about if we want different people to go thru the project in different ways or not. For eg. maybe since it is a project it doesn't matter much how they get it done but if it ever *did matter* then perhaps finding a more consistent method to ensure everyone practices the same skills is needed. (I have no formal experience creating course content so I do not know what the standards are for this type of thing. My prior experience as a sofware dev working for a large corp suggests that consistency is paramount so that's the instinct I'm fighting here)

Moving on though from this, yes I do think if you rewrite the instructions for the foreign keys to mention that they need to add at least one row would be helpful. 

>Each foreign key column should have the same name as the column it is referencing
...seem pretty clear to me. 

Finally, I agree the instruction's wording is clear, but the *order* is the cause of the confusion (if the camper hasn't read far enough down, they end up asking for help and then get told that they missed this requirement - which I feel the need to say is listed later on in the list - and then yes they end up renaming the column) But if that was the intention anyway, I'm not sure what else there is to say about other than the previous thoughts I expressed.

**Comment by hbar1st** [comment]
hi Tom, 
It is true that I can find more examples to show you of people struggling with these specific steps, but I think we have covered already that the order is meant to be the way it is so I will not dredge up more. 
I would be happy to have the additional mention of adding rows to the checks for the foreign keys as that will save me and others on the forum having to state that every time it comes up.
So yes, I will  close this one so that you can open the other PR for that update and that will be perfectly fine with me.
thanks again.
