### ISSUE TITLE
Overly strict comments

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#48527]
### Describe the Issue

The declaration of arr doesn’t need to be guarded by ‘Do Not Change’ comments. There exist many solutions (3 in the guide) that do not need that variable declaration.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/wherefore-art-thou

### Expected behavior

These comments should be removed or at least moved.

### System

All

**Comment by RandellDawson** [comment]
[Thread concerning possible solutions to this issue](https://forum.freecodecamp.org/t/wherefore-art-thou-original-problem-code-changed-so-the-solutions-dont-match/413404/3).

**Comment by jeremylt** [comment]
I was thinking something simplier

```javascript
function whatIsInAName(collection, source) {
  return collection;
}

whatIsInAName([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });
```

We've ditched a lot of these comments in the rest of the intermediate algorithm challenges. Does the comment help us at all here?

**Comment by RandellDawson** [comment]
> Does the comment help us at all here?

Probably not.  I honestly would not even put the `return collection` after the return.  At this point in the curriculum, users should know the function needs to have a `return` statement and they can craft their own.

**Comment by jeremylt** [comment]
Sure, then the fix would be:

```javascript
function whatIsInAName(collection, source) {

}

whatIsInAName([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });
```

This looks like a good first-timer issue.

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/wherefore-art-thou.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
