### ISSUE TITLE
Typo in CSS Learn CSS Transforms by Building a Penguin

### ISSUE THREAD

**Issue by Kirwiisp** [freeCodeCamp/freeCodeCamp#48560]
### Describe the Issue

In :
Step 43
Increase the psuedo-element's transparency by 30%.

psuedo instead of pseudo 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-43

### Steps to Reproduce

just loading the page

### Recommended fix or suggestions

change for : 
Increase the pseudo-element's transparency by 30%.

### Screenshots

![image](https://user-images.githubusercontent.com/59315476/203062798-67ba9e46-bad0-4dad-b333-0acf7ef09314.png)

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/aff567f4bf82a02262176d32374f6d051f3f4a3f/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/619be8ce4ea49008c5bfbc30.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Rohan-07** [comment]
@Kirwiisp can you assign me this issue.

**Comment by gikf** [comment]
Hey @Rohan-07

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by Kirwiisp** [comment]
currently following the guideline to make my PR
