### ISSUE TITLE
In the previous step you turned the words link to cat pictures into a link by placing them between opening and closing anchor (a) tags. You can do the same to words inside of an element, such as a p element.  In the text of your p element, turn the words cat photos into a link to https://freecatphotoapp.com by adding opening and closing anchor (a) tags around these words.

### ISSUE THREAD

**Issue by vivian87251** [freeCodeCamp/freeCodeCamp#48642]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ShaunSHamilton** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
