### ISSUE TITLE
Button that clears search bar inputs

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48662]
### Is your feature request related to a problem? Please describe.

This is a quality of life request. If camper interact with the search bar, fill it with their inputs, then wants to clear their input, they have to select all their text then delete it.

### Describe the solution you'd like

We can add a button in the search bar that clear the search bar for new camper inputs. Here is the functionality that I am talking about.

https://user-images.githubusercontent.com/88248797/205431779-69d670db-f954-4d82-93ee-73e8f3ad7150.mp4

Here is the website, if you want to mess with their search bar https://service-manual.nhs.uk/search

### Describe alternatives you've considered

This is quality of life, it's fine to ignore it if it harms accessibility.

### Additional context

You may have noticed that clicking the icon in the video doesn't close the keyboard, it would be lovely to implement that too, but we have to account for accessibility concerns as mentioned in this comment https://github.com/freeCodeCamp/freeCodeCamp/pull/48586#issuecomment-1335724747

Accessibility comes before implement this.

**Comment by bbsmooth** [comment]
> it's fine to ignore it if it harms accessibility

I don't see why this feature would harm accessibility, that is as long as it is implemented accessibly :slightly_smiling_face: 

I do find it interesting that the site you referenced above only implements this when it detects someone is using a touch interface (at least that's what appears to be  happening for me). I would think that keyboard users might also find this convenient. And possibly even mouse users. My point being that we should implement this feature for everyone instead of trying to impose our own ideas on who we think would benefit from it. 

As far as implementation is concerned, this appears to be just a simple button that when clicked will clear the current typed input in the input field and set the focus back to that input field. The accessible name would be something like "clear search terms". Whether it is placed before or after the actual search button in the DOM can be discussed. If we are going to show the button inside the input box, to the left of the search button then my preference would be that it come before the search button in the DOM so the tabbing order follows the visual order.

**Comment by Sboonny** [comment]
> I don't see why this feature would harm accessibility, that is as long as it is implemented accessibly

Nice.

> why this feature would harm accessibility

I think I was clouded halfway through creating the issue, because I was thinking of Run button 🤔. Well, I hope so at least 🤣  

> I do find it interesting that the site you referenced above only implements this when it detects someone is using a touch interface (at least that's what appears to be happening for me). I would think that keyboard users might also find this convenient. And possibly even mouse users. My point being that we should implement this feature for everyone instead of trying to impose our own ideas on who we think would benefit from it.

I think they are doing it to account for people with Parkinson, as they may have difficulty moving the mouse and stuff a like. I am not sure, tho. Here is an article about Parkinson https://www.nia.nih.gov/health/parkinsons-disease

This doesn't apply to us because the search function won't be close to the clear icon, so it will be friendlier to them. I agree that implementing everywhere is a plus for us.

> Ahh, let me revise that last statement. I was looking at the example and not the actual FCC search bar. The FCC search bar has the search icon on the left side of the input. So if we add the clear button at the end of the input then it will visually be to the right of the search button and thus it should probably be added after the search button in the DOM.

I agree, too, let's add a bigger spacing between the icon and the text in the long search bar inputs, inputs like "How do you create an accessible icon for searchbar component?", to make it easier to not miss-click the icon

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this up @bbsmooth, and for your insight @bbsmooth.

It's been so long now that I don't remember why we decided to hide the clear button, but @ahmadabdolsaheb is correct — `react-instantsearch-dom` includes both a search and clear button.

The search button is still shown, and is the magnifying glass on the left side of the search bar. And the clear button is an "X" on the right side of the search bar, and is hidden by [some CSS here](https://github.com/freeCodeCamp/freeCodeCamp/blob/73e5c4d935578e76c01e0248a7e6d042c99fb52b/client/src/components/search/searchBar/searchbar.css#L13).

This should be pretty easy to fix. We just need to remove that bit of CSS and align the clear button within the search bar.

I believe `react-instantsearch-dom` will take care of the rest. The clear button is hidden by default and appears when someone starts typing. Clicking or tapping on the clear button clears the search bar and closes the dropdown if it's open.

It also has a `title` attribute with `"Clear the search query."` by default. Unfortunately I don't think we're able to change the `title` for the search or clear buttons.
