### ISSUE TITLE
Add jest snapshot following setting button and certification page consistent

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48695]
**Describe the bug**
This PR #48211 makes the button consistent, we can use snapshot to make sure that these section still consistent and make it easier to review future PRs

Here are the docs about snapshot https://jestjs.io/docs/snapshot-testing

Here is an example file from the codebase, that creates a snapshot https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/certification.test.tsx

**Comment by nayabatir1** [comment]
Is there any convention we follow for test cases ?
Like file structure etc.

**Comment by Sboonny** [comment]
I didn't find jest documentation on our contribution section, so I cc @raisedadead for this. they are the oldest here I think, and they could know if we have convention for them or not 👍

**Comment by nayabatir1** [comment]
Can anyone of the reviewer look at my draft PR and let me know if I'm heading in the right direction.

**Comment by nayabatir1** [comment]
PR is up for review.

**Comment by nayabatir1** [comment]
Hey, maintainers.
CI/CD test case for my PR is [failing](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/3895915146/jobs/6651811243#step:6:190) but it's not showing what is the issue.
I ran `lint:prettier` locally but didn't get any issue. Please do let me know how can I fix this issue.

**Comment by raisedadead** [comment]
It tells you the name of the file that is throwing the error. In this case, it is as seen in the output for the CI job.

```
client/src/components/settings/settings-button.test.tsx
```

It is helpful to set up your editor with prettier and eslint to handle the formatting automatically. 


Alternatively, 

You can run `npm run format` before you commit and push changes. We have this script specifically to assist with formating.

**Comment by nayabatir1** [comment]
Hey @raisedadead,
I ran `npm run format` locally. I'm getting this errors, but I haven't touched these files. Also I've prettier and eslint vscode externsion installed.
It also says unable to resolve module, but my branch is updated and all the packages are installed.

<details>
<summary>npm run format</summary>

![image](https://user-images.githubusercontent.com/91016903/212048993-d88b7540-c17e-4ce2-a574-0fb63d0a23d7.png)
</details>


I also tried `npm run format:prettier`, Below are the files that are being modified, but no changes in `settings-button.test.tsx`

<details>
<summary>npm run format:prettier</summary>

![image](https://user-images.githubusercontent.com/91016903/212049547-b206b8f5-21f5-4f72-a36e-8732b1eb98dd.png)
</details>

**Comment by Sboonny** [comment]
Because prettier is using the old format, can you check the local version of both eslint and prettier?

Prettier should be 2.8.2, and eslint 5.47.1.

If they locally aren't the same versions as package.json, `npm ci` should update them in the local environment.

---

I think that that prettier and eslint aren't installed, because I haven't faced issue in gitpod 

![image](https://user-images.githubusercontent.com/88248797/212057973-8778cf89-1afa-4974-993d-e8a4cb68193c.png)

**Comment by nayabatir1** [comment]
I've updated prettier, `npm ci` didn't update any packages, so I've have to manually remove it `npm remove prettier` and install it again `npm i -D prettier`.

Now facing another [issue](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/3904894376/jobs/6671250444#step:6:42). Current jest version is `27.5.1` whereas latest version is `29.3.1`.  As per gatsby documentation mention [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/48751#issuecomment-1374138561). I've to add `ts-jest` in `jest.config.js`. I had to install it via `legacy-peer-deps` as normal installation fails. Which is also failing for CI/CD. 

Is there any way to install legacy dependency in CI/CD?

**Comment by Sboonny** [comment]
Yeab, you can include the version of the package after its name https://docs.npmjs.com/cli/v6/commands/npm-install. Ususally, I add the package name in `package.json` file and run `npm i` or `npm ci`, tho.

Up to you which method you choose, but make sure to not have `^` in the `package.json`.

---

It's weird that `npm ci` didn't work, I would have loved to know what happens if you ran `npm run clean` then `npm ci`. Doesn't matter anymore. You can find some of our npm scripts in the quick references to contribution, there are commands for easier

**Comment by raisedadead** [comment]
Hi, @nayabatir1. 

Thanks for working on this.

You have gone off-track in an attempt to resolve something simple. 

Let's consider what you want to achieve (we call this the scope of the PR) and what you should and should not be doing (out of scope).

1. Your PR aims to add/update some snapshots for the existing Jest-based tests.
2. Additionally, you may write more specs (test cases) because it is related.

To achieve this, you start by updating the existing tests and writing more new ones, as the case may be.

You should be able to limit your changes to the above; anything you are doing beyond that is out of scope. If you encounter issues (such as needing to install dependencies, etc., and need clarification on what it means), head over to the contributors' chat and ask for help.

**Now coming to your particular troubles:**

1. Your PR branch may sometimes go out of sync from the `main` branch. Sometimes just clicking the update branch button will not fix things. You need to do an actual `git rebase` to get the changes "in the correct order" on your PR branch. Your branch has over 33 commits as of this comment. Some of those commits are useless because the changed files are no longer relevant.

   This is the source of your troubles.

2. I recommend you delete your local branch, create a new branch by the same name, and manually apply each change (code change).

3. Then make a commit and push (`git push --force`) to your fork. That step will clean your PR. GitHub will replace the branch in the PR.

4. Once you have a clean PR. Move on to rebasing against the upstream. Follow the contributing guide for the steps. Doing so will bring your local branch to par with the main branch and your final changes. This is very important to be done.

   ```
   git pull --rebase upstream main
   ```

5. Next, could you clean up your local setup? It's messy with all the random dependency installations and troubleshooting you have been doing. We have a nice npm run-script for it `npm run clean`. 

   This will take a while, be patient.

6. Next, move on to setting things up the regular way: `npm ci`, `npm run develop`, or if testing `npm run test`

All of these steps should usually work (If tests fail, that should be expected). Please feel free to comment on your changes temporarily to ensure everything is set up correctly.

**Now a note about prettier (or linting and formatting) in general:**

You DO NOT need to install anything on your local machine. These dependencies that are declared and the configs in place are pre-configured to work on every machine (setup). Unfortunately, if you manually play with the versions, you are not doing it correctly. 

As I explained previously, it is better to "clean up" your setup. That means running the commands shared above and bringing them at par with the `main`. 

That's it.

Your IDE may have different versions than ours, but that does not matter. 

The npm run-scripts `npm run lint` and `npm run format` will ensure the code changes are in order and compliant with the formatting we want. Only try what is necessary, which would be a good use of your time.

**Jest dependency upgrade & Gatsby config instructions**

Major (SemVer) version upgrades come with many breaking changes and are not simple. It would be best if you dropped the idea of doing that because it is out of the scope of your PR.

You should reevaluate the best compromise in code without upgrading (like not using TypeScript) because it can make life easier, and then discuss this with others in that chat or here.

Please don't start upgrading dependencies or changing configs because the manual says so. It would be best if you talked about it first so that you understand the scope.

I hope this helps you to tackle a feature/fix, etc. 
Cheers.

**Comment by nayabatir1** [comment]
hey @raisedadead, I agree with you. It would make my life much easier.
I'll reset my branch with this [commit](https://github.com/freeCodeCamp/freeCodeCamp/pull/48751/commits/053f1daba6eb6a06404a27b449a05a2b6f42037c). In this commit all the test cases are passing with no unnecessary config and no dependencies were upgraded.
After that we can discuss best possible way to move forward.

**Comment by nayabatir1** [comment]
I've reverted my pr to one of the previous commits. All the tests are in js. All the test cases were passed successfully . All recent changes in config were removed. No dependency were upgraded.

I understand that I went down the rabbit hole in order to fix the issues and failing test cases. A lot of pr request were created because the test were successful in my local machine but it were failing CI/CD, I don't know any other way to test the changes other than making a pr and let it run its course.

Issues that I faced, when converting my tests js -> ts
- in order for ts to work properly with gatsby mock some config changes were needed.
- `jest-config.js` has one dependency `ts-jest` which need jest latest version. If we want it to work with current jest version legacy dependency needs to be installed.
- Even though legacy dependency installed on local system, it were failing on CI/CD.

If we are keen on converting tests to ts. Do let me know how to proceed without making any changes in the config or upgrading dependency.

I regret any inconvenience that may have been caused.

**Comment by raisedadead** [comment]
Thanks for the update @nayabatir1 – Yes, we can agree that the codebase is complex, and sometimes it is tricky to get things working. 

We would like to use TypeScript. @ojeytonwilliams, can you help guide us on the nuances that Atir has identified in the pain points above? Thanks.
