### ISSUE TITLE
FreeCodeCamp Debugging Console iPadOS Support

### ISSUE THREAD

**Issue by felkru** [freeCodeCamp/freeCodeCamp#48744]
### Is your feature request related to a problem? Please describe.

Since Covid lots of students have gotten iPads to do their schoolwork. For most of them their iPad is their only device with a large viewport. Their possibility to learn coding is very dependent on browser support. Most of freecodecamp fulfills this requirement, but debugging is quite challenging, because things like console.warn() and the console timer don’t work. This is particularly evident when working on “JavaScript Algorithms and Data Structures” > Debugging.

### Describe the solution you'd like

Allow console to interpret and show:
console.warn(), console.error(), console.time(), console.count(), console.debug(), console.clear() and message grouping.

### Describe alternatives you've considered

Give students on iPad the possibility to use a remote desktop for coding.

### Additional context

You could only show the improved console on iPads to encourage campers on desktop to use the browsers console.

**Comment by ojeytonwilliams** [comment]
Thanks for the suggestion, @felkru. It sounds like a solid feature.

I think it should be fine to show all the logs to all the users - no need to hide it for desktop users.  People are always free to look at the browser console if they wish and I don't think we need to encourage or discourage its use.

I'd like see what other maintainers think about this, but personally I'm in favour.

**Comment by Nirajn2311** [comment]
I'm in favour of showing the console output to the users. I remember keeping the browser console open when I went through the JS cert as sometimes I would log the output while playing around with what I learnt in that lesson.

**Comment by felkru** [comment]
How would we implement it than?

**Comment by felkru** [comment]
I would love to implement it, but I think I might need some help, because I am not familiar with freecodecamp‘s codebase.

**Comment by ojeytonwilliams** [comment]
Hi @felkru, sorry for the delay getting back to you.

What we currently do is wrap the browser's `console.log` function with our code. That allows us to intercept `console.log` calls, send them to the fcc console and still log them to the browser's log as normal.  If you search for `proxyLog` you should find the relevant code. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/b2a5ef72484177c9fa213b57be6beb2184b0f2f7/client/src/templates/Challenges/utils/frame.ts#L192

and 

https://github.com/freeCodeCamp/freeCodeCamp/blob/b2a5ef72484177c9fa213b57be6beb2184b0f2f7/client/src/client/workers/test-evaluator.ts#L48

are good places to start, too.

With that in mind, I think the implementation would need to extend that to wrap all of the functions you mentioned. I'd start small and extend it to `error`, `warn`, `debug` and `info` (since they're basically the same thing).  That alone would be a decent PR.

**Comment by felkru** [comment]
Thanks. Since I‘m not on holidays anymore I currently can‘t work on that. I will try to start implementing as soon as I have some free time.

**Comment by felkru** [comment]
I tried to understand the code and I think I need some further assistance to understand the architecture. Would someone be willing to jump on a zoom call to explain it to me?

**Comment by ojeytonwilliams** [comment]
Someone might, but the maintainers have a lot of demands on their time.  It's worth asking in discord/forums since you will reach more people that way.

> I need some further assistance to understand the architecture

What were you trying to understand?

**Comment by felkru** [comment]
Where proxyLogger is originally called and what framecontext is.
