### ISSUE TITLE
Tag System

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#48800]
Creating a new issue specifically to track discussion for the tag system - spinning off of #48502.

This also follows up on #47478

**Comment by moT01** [comment]
Here's some notes I wrote down from our meeting:

- Make a "tags" dropdown or something expandable in the block descriptions.
- When expanded, it would list all the tags that are used in steps within that block.
- When you click on a tag, it filters the steps in the grid display to only show steps with that tag.

**Comment by laportabellita** [comment]
For this design, the goal was to create tags with topics that will show up under the "Start Project" button. When clicked, they will highlight the blocks of steps that are connected to the tag’s subject.  
While designing, I had the following considerations in mind:

- People with visual impairments should be able to use this feature like everyone else, therefore we shouldn’t rely solely on color or contrast to differentiate the relevant numbers

- One posible option could be to have a small text somewhere explaining what the tags do for those who are not familiar enough with technology and don’t understand that these are links 

- If there could potentially be like 50 tags, we need to come up with a way to make them look easy on the eye so the users will want to interact with them and not be intimidated or confused, otherwise if they look cluttered users will ignore them due to how difficult they are to read. This is why I made the tags a bit bigger, especially because the tag section can be hidden as you'll see in the design

The final draft I made today can be found on the lower right side of the figma file, the frame where the flow starts is called "Second iteration". If you choose this frame you can interact with the prototype, here's a screenshot for reference: 
<img width="1008" alt="Screen Shot 2022-12-19 at 5 00 18 PM" src="https://user-images.githubusercontent.com/82290980/208551025-0d479b6d-6f25-4a6f-b720-ebad503754ee.png">

[Here's the figma file ](https://www.figma.com/file/5CzMtYAXczx4unvriYUtVR/FreeCodeCamp-NavBar-(Copy)?node-id=239%3A953&t=6BabYSgem7caPwLG-1)where you can explore the process, some of my notes and the final design 

And this is a quick video showing you where to find the prototype and the flow itself. 

Bu the way, this is just an initial draft that needs refining once we can discuss it. The design of the "See all steps" button particularly needs more work and I've just put it there as a placeholer

https://user-images.githubusercontent.com/82290980/208550712-1309fbe5-e747-49f1-8272-f95a3ca4b05e.mp4

**Comment by bbsmooth** [comment]
@laportabellita I like what you've done here and you incorporated my first two bullet points above! I just have a few suggestions at this time:
- It would be best if the name for the toggle button that opens/closes the list of tags stays the same for both states. Perhaps just keep it as "Filter steps by topic"? We will use the `aria-expanded` attribute on the button itself to let screen reader users know which state it is in. The issue with changing the name on toggle is that some screen readers might not immediately pick up the change. Also, using the `aria-expanded` attribute is an accessibility best practice and it wouldn't make logical sense to change the name when using that attribute.
- I would vote for "Clear filter" as it would be more consistent with using "filter" on the toggle button. If we change the name on the toggle button to something that doesn't use "filter" then whatever that is, I think the clear button should use that same name for consistency's sake.

**Comment by laportabellita** [comment]
If you guys liked the design I can start converting it to a final draft

**Comment by laportabellita** [comment]
[Here's the updated version ](https://www.figma.com/proto/5CzMtYAXczx4unvriYUtVR/FreeCodeCamp-NavBar-(Copy)?page-id=309%3A228&node-id=309%3A229&viewport=815%2C477%2C0.22&scaling=min-zoom&starting-point-node-id=309%3A229)

**Comment by ojeytonwilliams** [comment]
Thanks for sharing those designs, @laportabellita. The idea is really taking shape and the mockups look great.

The only thing that leapt out to me was that there's quite a bit of empty space in the filtered view. What do you think to collapsing the gaps between the filtered steps?  e.g. rather than having `1 2     5` it would just be `1 2 5`. That way, even for projects with lots of steps, there's no risk that people fail to notice that later steps are unfiltered, even if they would otherwise be off the page.

**Comment by laportabellita** [comment]
I think that's a good idea, here's a quick mockup showing what the design would look like with that modification 

<img width="369" alt="Screen Shot 2023-01-04 at 12 19 55 PM" src="https://user-images.githubusercontent.com/82290980/210632644-ce4e911f-8cca-4b40-a535-3350a356e3d2.png">

**Comment by ojeytonwilliams** [comment]
Thanks @laportabellita, I think that looks great.

**Comment by oriooctopus** [comment]
I'm really happy to see this idea taking shape :)

What are the next steps for this?

**Comment by bbsmooth** [comment]
Just to clarify, are we allowing multiple tag filters at at time, or just one?

**Comment by ojeytonwilliams** [comment]
> Just to clarify, are we allowing multiple tag filters at at time, or just one?

I'd start with one.  If that feels too limiting we can consider allowing more, but I suspect it'll be fine in practice.

**Comment by bbsmooth** [comment]
Assuming we only allow one tag at a time, in the minimal design, is that supposed to function as a traditional `select` element? Or is it similar to the original design in which it acts as a disclosure button?

**Comment by oriooctopus** [comment]
> Or is it similar to the original design in which it acts as a disclosure button?
Could you clarify?

**Comment by SuitlessStan** [comment]
Hello @everyone 
Following up on your discussion, I would like to take this one!

**Comment by moT01** [comment]
I think we decided that we want to use something similar Ahmad's mock to start. The argument for keeping the full grid is that campers can see where they are and also where the challenge is that has that tag. As far as the dropdown, we can start with that but may want to show the tags. We are going to add a help wanted label on this and can fine tune some things on the PR.

Feel free to work on it if you want @SuitlessStan or anyone else 👍

**Comment by bbsmooth** [comment]
If we allow multiple tags at a time, are those going to be OR'd together or AND'd together?

**Comment by ojeytonwilliams** [comment]
I think we'd want OR (i.e. the union). Reason being there should not be many lessons with multiple tags, so AND would typically be empty.

**Comment by bbsmooth** [comment]
> I think we'd want OR

Ya, that was my thought too. @Canopius, here's another update for your PR :slightly_smiling_face:

**Comment by Sebastian0011** [comment]
I would like to work on this issue

**Comment by Sembauke** [comment]
We have decided not to implement this feature.
