### ISSUE TITLE
Grammar in step 48 of new JS course (build an rpg)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48836]
### Describe the Issue

In crowdin, I noticed that step 48 of the new JS course, build an rpg, uses a sentence that may need a grammar correction. Instead of “your button innerText” it should say “your buttons’ innerText”? Full sentence was:

`In your <code>goTown</code> function, update your button <code>innerText</code> properties to be <code>Go to store</code>, <code>Go to cave</code>, and <code>Fight dragon</code>.`

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/25f0fc5d93f10955814376c56c9c1e6813809dcb/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7c071219da921758a35bb.md

### Your code

```

```

### Expected behavior

Grammar correction. 

### System

N/A

**Comment by ShadyResurrected** [comment]
Hello , Can you assign me this?

**Comment by naomi-lgbt** [comment]
Should be changed to:

```md
In your `goTown` function, update your `button` elements' `innerText` properties to be `Go to store`, `Go to cave`, and `Fight dragon`.
```

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
