### ISSUE TITLE
Step 59 new js course (build an rpg) is missing needed backslashes

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48865]
### Describe the Issue

Step 59 asks users to copy code from one place to another. However the hint text below is missing the escape backslashes around the word “Store” which were found in the original code being copied. 

Your `update` function should set `text.innerText` to `You are in the town square. You see a sign that says "Store".`.

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b0b5053f16111b0b6b5f.md

### Your code

```

```

### Expected behavior

The hint should say:
Your `update` function should set `text.innerText` to `You are in the town square. You see a sign that says \"Store\".`.

### System

N/A

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b0b5053f16111b0b6b5f.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by AnshPhirani** [comment]
I'll work on this.

**Comment by MaryannAlonge** [comment]
@AnshPhirani thanks for getting here before me and fixing the issue. I hope it gets merged!
