### ISSUE TITLE
Unlclear instructions 

### ISSUE THREAD

**Issue by Kel-VinTech** [freeCodeCamp/freeCodeCamp#48877]
### Describe the Issue

I have followed the instructions but it still gives error

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-52

### Your code

```

```

### Expected behavior

Gives an error

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Laptop

**Comment by bbsmooth** [comment]
These types of questions are best answered in the [forum](https://forum.freecodecamp.org). Even better, use the Get Help button in the step itself to generate a post on the forum.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
