### ISSUE TITLE
Flash messages are out of view

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#48910]
### Describe the Issue

The flash messages are showing up out of view if you are scrolled down the page a small amount.

### Steps to Reproduce

1. Go to your settings page
2. Scroll down any amount more than about a few hundred pixels
3. Change one of the settings in a way that a flash message should appear. Change the `Night Mode` or `Campfire Mode` setting for instance.
4. You won't see the flash message
5. Scroll back to the top.
6. See the message

### Expected behavior

Messages to show no matter the scroll position.

### Screenshots

![Jan-03-2023 11-04-36](https://user-images.githubusercontent.com/20648924/210405434-fc0617d7-094a-4dcd-8976-3005e73ed938.gif)

**Comment by Sboonny** [comment]
Changing the position property in the selector below should sort it.

```css
.flash-message {
  display: flex;
  justify-content: space-around;
  flex-direction: row-reverse;
  margin-bottom: 0px;
  padding-top: 3px;
  padding-bottom: 3px;
  width: 100%;
  position: relative;
  z-index: 150;
```

**Comment by oriooctopus** [comment]
Ah this is my bad. It's a result of https://github.com/freeCodeCamp/freeCodeCamp/pull/48861 
I didn't realize that we wanted it to persist like that, sorry.

**Comment by Sboonny** [comment]
Not really. 
- I could have made a 2nd quick review instead of assuming that you have reverted the position, and deleted the code.
- I could have been more careful, because my dyslexia, make it easier to misread words, and could have tested it instead.
- I could have read Oliver comment more carefully, instead of assuming.

---

So it was mostly on me as I didn't do my full diligence and could have easily prevented this awkward situation.

**Comment by oriooctopus** [comment]
IMO, bugs are always a result of multiple team members, the existing infrastructure, and existing processes. I never truly think that a bug is any one person's fault.

**Comment by oriooctopus** [comment]
> I do hate the components used for styling like spacer and alike, but I am wondering what specific layout, that you were trying to achieve and the spacer got in your way.

Can you clarify??

**Comment by Sboonny** [comment]
I think I derailed, and maybe bringing a second issue into this, but here I am anyway.

I will use an example, in the landing page "https://www.freecodecamp.org/", there are 4 `div` elements before the first heading, which are used for spacing and styling.

These and `div` elements that are used for styling can be gone for flex or grid layout. I don't know what specific layout to choose because there aren't problems raised about them yet.

So saying my thoughts out load, showing me that I was tunnel visioned and connecting 2nd issue with original one. 🤔

**Comment by oriooctopus** [comment]
I think I see what you're saying. You're suggesting improving the way that things are styled by using flex or grid in order to make the code less verbose?
