### ISSUE TITLE
null issue

### ISSUE THREAD

**Issue by nickolsj** [FreeCodeCamp/FreeCodeCamp#4894]
Challenge [Bonfire: Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer?solution=function%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don%27t%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20var%20newArray%20%3D%20arr.filter(falsyElement)%3B%0A%20%20return%20newArray%3B%0A%7D%0Afunction%20falsyElement(str)%20%7B%0A%20%20switch(str)%20%7B%0A%20%20%20%20case%20false%3A%20return%20false%3B%0A%20%20%20%20case%20null%3A%20return%20false%3B%0A%20%20%20%20case%200%3A%20return%20false%3B%0A%20%20%20%20case%20%22%22%3A%20return%20false%3B%0A%20%20%20%20case%20undefined%3A%20return%20false%3B%0A%20%20%20%20case%20NaN%3A%20return%20false%3B%0A%20%20%20%20default%3A%20return%20true%3B%0A%20%20%7D%0A%7D%0Abouncer(%5Bnull%2C%200%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  var newArray = arr.filter(falsyElement);
  return newArray;
}
function falsyElement(str) {
  switch(str) {
    case false: return false;
    case null: return false;
    case 0: return false;
    case "": return false;
    case undefined: return false;
    case NaN: return false;
    default: return true;
  }
}
bouncer([false, null, 0, NaN, undefined, ""]);

```
The null array element doesn't get filtered out for some reason when with other elements. If I execute my code on just a null array ie. bouncer([null]) it works fine, or even in bouncer([null, 0]).
For some reason when dealing with many elements it isn't removed.

**Comment by ltegman** [comment]
For some reason the console is displaying that `null` is the item left in your array, but the item that's actually left if `NaN`. This is because in javascript `NaN === NaN` will return false. You can use the `isNaN` function to get around this problem. However, the point of this exercise is to show you how with type coercion you don't actually have to be checking for specific "falsy" values because javascript will coerce it to `false` for you. So for example, your filter callback could just be:
```
function falsyElement(element) {
  return element;
}
```
Because `filter` is looking for a boolean it will coerce your value into one -- turning "falsy" values to `false` and "truthy" values to `true`.

Hope that helps and makes sense.

Thanks and happy coding!

**Comment by 13ck015405** [comment]
great!! but how in the world are we supposed to know about type coercion when it wasnt even listed as a hint??

now I'm wondering; "how many times have I missed the point of a challenge?"
