### ISSUE TITLE
Non-English keyboard guidance/warning needed

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48943]
### Describe the Issue

Has anyone thought about adding a new section to the translated version of the curriculum to explain to people how to find characters like backslash and double quotes? Or a reference link? I think we probably should add something to tell people to switch their keyboard language at the start of the curriculum just like we warn them that some browser extensions can cause problems?

### Affected Page

Translated versions of the curriculum (such as Arabic)

### Steps to Reproduce

This issue affects international users whose computers are not normally set to the English language.

### Expected behavior

Just like we warn users that browser extensions can interfere with the behaviour of the learn site, we can warn them that using a non-English US keyboard can interfere with their ability to code. Ideally there should be some guidance given on how to find required keys like backslash (which is missing on the Arabic keyboard for instance), or we should suggest to everyone to switch their language settings.

### System

N/A

**Comment by bbsmooth** [comment]
The forum is a great resource but I'm not sure we should depend on it for known issues like this. I think if we know there is an issue then we should try our best to make people aware of it so they can deal with it themselves. There is no guarantee you will get a correct solution in the forums.

**Comment by hbar1st** [comment]
Because there is no live Arabic version of fcc at the moment, no-one has asked us this question specifically for Arabic on the forum. (other me as I am proofreading the old JS curriculum in Arabic.) However, yes we do see this question (or issues that arise from this) from other learners around the world (so far from latin-language learners maybe because their keyboards work for the most part for coding). And we have to be aware on the forum of these issues constantly (note they are hard to test for in a long piece of code) because some people will (and I really have no clue how that happens), write one double quote correct and another incorrectly. 
Sometimes I just cannot detect this so I usually say - please redo this step with the language setting corrected; and sometimes I am able pinpoint the issue. I've also had at least one case where Ilenia had to help because it was not something I had seen before. And at least one where I sent the person multiple references to try to get them to find the correct backslash (for the backend projects) and things didn't immediately go well.

I hope we can provide some kind of support outside the forum (even in the form of a linked article) that helps people get setup for the learning they will take part in. (Hopefully by the time major new language releases are ready for release)

**Comment by ShaunSHamilton** [comment]
We do have this post: https://forum.freecodecamp.org/t/forum-code-formatting/25574

However, my issues with this are:
1) This is not programming or freeCodeCamp specific
2) This is OS and hardware specific

So, instead of linking to a resource/article/guide detailing in 100 languages X 4 OSes X 10 Keyboard/Region layouts how to find keys, and where to change them, I suggest we make the instruction and hint text more "common error" prone.

That is, have tests in beginning lessons looking out for various types of reasonably confusing quotation mark (U+2018, U+2019, U+201C, U+201D...). Then, explain/expect Campers will need to figure out (the Google) how to have their Mac use an acceptable quotation mark. Same goes for "special" characters.

**Comment by hbar1st** [comment]
hi Shaun, the scenario just leaves out what happens when I can't find the character at all? (if it is not on the keyboard at all?)

**Comment by Sboonny** [comment]
I am in favor of adding the keyboard guidance, in some test we are case-sensitive, which doesn't exist for Arabic language.

Instead of trying to describe and think of a way to add a definition that doesn't exist in the Arabic language, but can be understood by Arabic-speaking campers is close to impossible without adding external link, which is against the rules of freeCodeCamp.

Some guidance which is translatable, for example:

> Press <kbd>Shift</kbd> or <kbd>Cap lock</kbd> to change the case of the English letters to pass the case sensitive test.

Will be extremely appreciated from Arabic localizing side

**Comment by Sembauke** [comment]
This implementation is not specific to the freeCodeCamp codebase and is beyond our scope.
