### ISSUE TITLE
JS course button "Reset All Code" should probably be called "Reset This Lesson" instead

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48986]
### Describe the Issue

In the JS course (such as the Basic Javascript course), the button to "Reset All Code" leads to a dialog titled "Reset This Lesson" which contains a button titled "Reset this lesson". 
I believe that "Reset this lesson" is a clearer and truer description of what clicking on "Reset All Code" is meant to do so I opened this issue to discuss that. I've also heard feedback before on the forum where someone was afraid to press on "Reset All Code" button because they thought it would delete all their progress.
For this reason and for the reason for having a consistent and predictable user-interface, I suggest the button "Reset All Code" be renamed to match the dialog "Reset This Lesson"

### Affected Page

all js course pages

### Steps to Reproduce

click on the button in any of the JS course steps to see the dialog 

### Expected behavior

please see the description of the issue

### Screenshots

![js-reset-button](https://user-images.githubusercontent.com/35541470/211630120-0b7e77d4-7e92-4fbd-8145-3f54f38fccbb.png)

### System

laptop devices and other large screens

**Comment by bbsmooth** [comment]
Agreed. I have heard that feedback as well.

**Comment by moT01** [comment]
Sounds good to me.

That is [located here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/tool-panel.tsx#L104) There's [a few spots in the lower jaw we should probably change](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/lower-jaw.tsx#L193) as well.

We can just change them to use the [existing reset-lesson key](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json#L50)

**Comment by bbsmooth** [comment]
I agree, the current accessible name on the restart icon button in the steps is "Reset All Code", so that needs to change as well. But since we refer to theses lessons as "Steps" then I think it makes more sense to use "Reset this step" instead of "Reset this lesson".

**Comment by moT01** [comment]
hmm, I suppose I agree there - although, the modal still says "lesson" on those steps. Perhaps we should just fix the older challenge types (like in the screen shot) for this issue, and make another one to change the lower jaw button and the reset modal to use "step" for the new style challenges.

**Comment by bbsmooth** [comment]
> although, the modal still says "lesson" on those steps

Good catch, I didn't notice that (that will teach me for not actually clicking the button). Funny how these things are always more involved than they first appear to be.

I have no opinion on whether to split these into two issues. If I were going to fix this I would just do it in one PR. But if you were thinking these would be first timer issues than perhaps it would make more sense to split them.

**Comment by moT01** [comment]
It really doesn't matter. To clarify then, we want to...

1. Change the [older style challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/tool-panel.tsx#L104) to say "Reset this lesson" using the [`reset-lesson` key.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json#L50)

2. Change the newer style challenges to say "Reset this step". We will need to add at least two new keys in the translations, one that says "Reset this step", and one or more for the reset modal that use "step" instead of "lesson". The current modal uses the [keys here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json#L50)

- Then change the button in the lower jaw
- And we will need to conditionally change the reset modal text based on the type of challenge or something and use "step" if it's the newer style

That sound about right @bbsmooth?

**Comment by bbsmooth** [comment]
I think you've covered everything!

**Comment by mashinsp** [comment]
Assign it to me

**Comment by moT01** [comment]
We don't typically assign issues @mashinsp. The first PR to fix the issue will be accepted. Feel free to make a PR that fixes one or both of those things mentioned. Let us know if you need any assistance.
