### ISSUE TITLE
Error on Step 27: Typography project in Responsive Web design

### ISSUE THREAD

**Issue by Hills95** [freeCodeCamp/freeCodeCamp#48991]
### Describe the Issue

I am one of the students undertaking the freecodecamp curriculum. However, I am experiencing an error on step mentioned above. The hint says “You should have a new .lg selector” which according to the code i entered, everything is fine. Here is my code:

.lg {
  height: 10px;
}
.lg, .md {
  background-color: black;
}

Your support is highly appreciated.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-27

### Your code

```
.lg {
  height: 10px;
}
.lg, .md {
  background-color: black;
}
```

### Expected behavior

The code should create an .lg selector with a height property set to 10px and a .lg, .md selector with background-color property of black.

### Screenshots

<img width="479" alt="Screenshot 2023-01-11 103443" src="https://user-images.githubusercontent.com/32170809/211745222-dea25f99-d4cf-4eea-8eb1-0d5b14e2cb49.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
