### ISSUE TITLE
HTML challenges do not warn users or run tests when there are syntax errors

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#49018]
**Describe the bug**
Syntax errors in HTML and multifile challenges stop the tests from running.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Replace code with `<script> ) </script>`
3. Click "Check Your Code..."
4. See nothing

**Expected behavior**

The tests should still run, even with broken syntax. Otherwise challenge creators are overly limited in the kinds of lessons they can write.

This is trickier to do for HTML challenges than pure JS ones, since we first build the frame and then run the test code in it.  When there's a syntax error, that's not possible. Instead we will probably need to create a separate environment for the test to run in.  A JS test runner, perhaps?

@naomi-lgbt is there anything I missed?

**Comment by naomi-lgbt** [comment]
This behaviour is also present in the new JS curriculum we've been working on (which is where it was really an issue).

**Comment by Sembauke** [comment]
Javascript will not run if there are syntax errors in the code. The browser or JavaScript engine will stop executing the script and display an error message indicating where the syntax error occurred.

We are running the tests in the same `eval()` function as the executed code. I do not think we can prevent it with the current test runner.

**Comment by oriooctopus** [comment]
> Instead we will probably need to create a separate environment for the test to run in. A JS test runner, perhaps?
If we have two separate environments can they still reference one another?

> This is trickier to do for HTML challenges than pure JS ones
Yeah, the pure JS ones should just be a matter of running each test individually and wrapping each evaluation in a try/catch block

To me, if there is an HTML error I think it's sufficient enough to just tell the user something roughly like "this test failed because the HTML is invalid". The catch though is how we can distinguish between an HTML error and a JavaScript error. Especially when the JavaScript referenced is not an external script

**Comment by Ifham1111** [comment]
is this still open 
/assign
