### ISSUE TITLE
Normalize the use of dasherized cert titles

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#49049]
The client code uses both the dasherized titles of the certificates and their normal titles for component props. This needs to be normalized so that we use only the dasherized titles in the props of any component.

This is the first of the two changes to be done for de-duplicating the translation keys for certification titles. [Source](https://github.com/freeCodeCamp/freeCodeCamp/pull/48785#issuecomment-1359561934)

**Comment by nyni123** [comment]
Hi @Nirajn2311 

 I noticed your comment about normalizing the use of dasherized certificate titles (#49049) in FreeCodeCamp's client code. 
Before starting to work on this issue, I have a few questions that could help me better understand the problem:

1) Could you please provide more context about the problem? Specifically, what issues have you encountered with the use of both dasherized and normal certificate titles?
2) Do you have any guidelines or conventions in mind for approaching the normalization of certificate titles? If so, please share them so that we can ensure we are following the correct standards.
3) Can you give any specific examples of components or pages that are affected by this issue? This will help me better understand the scope of the problem.
4) Are there any other related issues that we should be aware of before starting to work on this problem?
5) Is there a specific timeline or deadline for resolving this issue that we should be aware of?

Thanks for your help in clarifying these points. Looking forward to your response!

**Comment by ieahleen** [comment]
how's it going with this @Nirajn2311 ?

**Comment by saifdarwish** [comment]
Hey @Nirajn2311,

How ist it goeing? I hope all is well. I've addressed your comment about normalizing dasherized certificate titles in FreeCodeCamp's client code. Before proceeding, I have a few clarifying questions:
Could you provide more context on the issues faced with using both dasherized and normal certificate titles? Understanding the challenges will help in devising an effective solution.
Do you have specific guidelines or conventions in mind for the normalization of certificate titles? Having clear standards will ensure adherence during the implementation.
Could you share specific examples of components or pages affected by this issue? This will assist in grasping the extent of the problem.
Are there any other related issues we should be aware of before delving into this problem?
Is there a specific timeline or deadline for resolving this issue?
Your insights are valuable, and I want to ensure that any contributions align with the project's objectives. Looking forward to your guidance on these points.

Best regards
