### ISSUE TITLE
Learn CSS colors  Step #78

### ISSUE THREAD

**Issue by jparkton** [freeCodeCamp/freeCodeCamp#49061]
### Describe the Issue

Instructions want you to select two classes, but does not pass correct CSS

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-78

### Your code

```
.cap .sleeve{
  display: inline-block;
}
```

### Expected behavior

Should pass and carry on to #79

### Screenshots

![step-78](https://user-images.githubusercontent.com/14003326/213337494-48873a84-6f5f-465d-9db0-0663d7547ff7.png)

### System

- Device: Asus Chromebook
- OS: Chrome OS
- Browser: Chrome
- Version 108.0.5359.172 (Official Build) (64-bit)

**Comment by gikf** [comment]
Thank you for reporting this issue.

There seem to be missing comma between the selectors.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by NewCoomerr** [comment]
.sleeve , .cap{
display: inline-block;
}
