### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/freecodecamp#491]
The challenge is satisfied before finishing the opening anchor tag, let alone adding the closing tag.

This passes, even though it's broken:
`<a href="#"<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>`

**Comment by terakilobyte** [comment]
This is because the browser is too smart and by the time the test runs the browser has sniffed it, and fixed it (by adding the missing symbols). Our tests run on what the browser interprets the html as for the most part.

As has been mentioned on other issues we'll look into hardening these. Keep those bug reports coming.
