### ISSUE TITLE
Potential improvement: On map pages, don't fetch all challenges at once

### ISSUE THREAD

**Issue by oriooctopus** [freeCodeCamp/freeCodeCamp#49112]
### Is your feature request related to a problem? Please describe.

Currently on a course page such as https://www.freecodecamp.org/learn/2022/responsive-web-design, all challenges belonging to all blocks are fetched at once. In the case of "responsive-web-design" this is over 1000 challenges. 

### Describe the solution you'd like

Instead of fetching these all at once, we could potentially benefit from leveraging gatsby's out of the box capabilities for lazy loading with viewport-based prefetching.

We are actually already doing something very similar on the overall map page. On the overall map page the challenge data is prefetched based on what is in the viewport as shown in the video below. In what I'm proposing above, when a user loads a page such as `https://www.freecodecamp.org/learn/2022/responsive-web-design`, instead of loading all 1000+ challenges the only challenges that would be loaded are for the challenges belonging to the blocks in the viewport.

https://user-images.githubusercontent.com/20331238/213938329-985ca08d-15ee-4245-b160-6ba572cc86db.mp4

This would save data in 2 places:

1. The first one was mentioned above. On an individual course page such as https://www.freecodecamp.org/learn/2022/responsive-web-design we will save data because we won't have to load those 20kb all at once. Most of the time we will only load a fraction of that
2. On the overall course map page, gatsby's prefetching means that it prefetches the necessary data for an initial page load for any links on a page that are in the viewport. This is shown in the video above since all the individual course pages load all of the challenges it means that on the overall course map page all of the challenges of all courses can potentially be loaded. Buy only loading the challenges that would belong to the blocks in the initial viewport  we would reduce the data sent in this case significantly as well.

### Describe alternatives you've considered

Not doing it

### Additional context

This proposal is based on the assumption that reducing the data sent over the server/cdn would result in meaningful cost reduction for free code camp. I don't have a ton of experience with estimating server costs so this assumption could definitely be wrong.

The size of the challenge data for the "responsive-web-design" course is about 20 kB. Other courses are smaller but as they get converted to the new course style I expect them to be a similar size. If we are talking about the overall course map page and say there are 10 courses of a size of 20kbs, this could potentially save 100-200kb of data being sent

Regarding the implementation, the devil is definitely in the details and while we might find that this is simple to implement, we might also find that it is very difficult to implement. It may also come with some drawbacks regarding limitations that are not worth it. So this is really just a proposal discussion that I want to begin and see where it goes.

One other thing to mention is that this could potentially complicate the filtering system proposed in https://github.com/freeCodeCamp/freeCodeCamp/issues/48800. Specifically, if we decide to add filtering on a super block level instead of just a block level we will need to have all challenges in a super block be loaded by that point.This may not be an issue because filtering is not open by default and has to be expanded to be used. Once it is expanded we can load all challenges.

**Comment by ShaunSHamilton** [comment]
I would be happy with any improvement here.

The main thing to realise is what you showed in the video **is Gatsby being Gatsby** (default). So, if you do not drag your cursor over the all links, Gatsby will not invoke a fetch for all of the page data.

I am not sure what you are suggesting with "block level" improvements. The data **has** to be there when the superblock loads. That is, we cannot:

1) Load a superblock
2) Click on a block
3) Fetch block links/data

Because React has already created the elements (links).

---

Personally, I am not a fan of any of this behaviour (pre-fetching based on cursor position). So, if a solution is to stop doing this, I could get behind that.

**Comment by oriooctopus** [comment]
> The main thing to realise is what you showed in the video is Gatsby being Gatsby (default). So, if you do not drag your cursor over the all links, Gatsby will not invoke a fetch for all of the page data.

Ah yes you are right, I was mixing up the behavior of Gatsby with a library called [QuickLink](https://web.dev/quicklink/). 

> I am not sure what you are suggesting with "block level" improvements. The data has to be there when the superblock loads. That is, we cannot:
> Load a superblock
> Click on a block
> Fetch block links/data
> Because React has already created the elements (links).

Are you sure? From what I understood this is not the case. It is possible to query for the challenges and filter on the `block` property, the same as is currently done when we filter challenges based on the `superblock` property. Then we would just wait for a block to be in viewport here before actually querying for its challenges . Or we can get even more lazy and only query for them on hover

**Comment by ShaunSHamilton** [comment]
> Are you sure?

No, I am not. However, without what I would assume to need to be a major refactor, all of a superblock's HTML is already loaded - even when it is below the viewport.

What I am getting at is: Once you land on a superblock, the data **has** to be there, otherwise React would crash (JavaScript error). So, currently:

1) `/learn` - hover over RWD
2) Hover causes pre-fetch of RWD allChallengeNode
3) Click on RWD
4) SPA fun - RWD superblock is "loaded", and all blocks are populated (on page)

Maybe I am over thinking the complexity to refactor to get:

2) Hover causes pre-fetch of only "block-level" data (no challenges)
3) Click on RWD - fetch for first block challengeNode, because first block is always expanded
4) On hover over "Expand" buttons, pre-fetch block/challenge data

🤷‍♂️ 

---

I am out of discussion. We can wait for more discussion from others. Or, if you are particularly inclined, a semi-working PR could be interesting.

**Comment by oriooctopus** [comment]
Maybe the next step before investing too much time and discussion is to even find out if the potential speed improvements would be meaningful. On the one hand freeCodeCamp serves like 10 million people a year, on the other hand this is data served through a CDN which I imagine is dirt cheap. Is there anyone on the team who knows about server costs?

**Comment by ojeytonwilliams** [comment]
@raisedadead is the one who would know if there are significant cost reductions on the table. My guess is that cost wise there's not much we can do, but we can almost certainly improve performance.

We did disable core prefetching a few years back https://github.com/freeCodeCamp/freeCodeCamp/pull/35512, but it's possible  we can turn it back on again.
