### ISSUE TITLE
Take campers back to map after finishing a block

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#49170]
Just opening this up for discussion since it came to mind. I was testing a PR and submitted a new RWD project and it took me right to the first step of the next block. I'm wondering if we should take campers back to the map so they can see their checkmark and then they have to click on the next thing to do. It feels like that might be a little better to me.

**Comment by ShaunSHamilton** [comment]
When you say "block", do you mean our blocks? Or, do you mean 2 practice projects + 1 certification project?

**Comment by moT01** [comment]
I mean any individual block, e.g. "Learn HTML by Building a Cat Photo App", "Survey Form", and "Basic JavaScript", etc.

After they submit the last step or the project or whatever else, take them back to the map and scroll to that spot.

**Comment by Sboonny** [comment]
While I was finishing the project 9 months ago, I didn't read any intro info, because of the skip that is happening, which created the habit of ignore the sections' intro completely.

If the intro is important, I am in favor of navigating to the `block#id`, instead of the first step in the next block.

**Comment by CallmeHongmaybe** [comment]
I like this idea too. It's not just limited to RWD I believe. For me it'd be better to include a button that allows campers to go back to map situated under the "Download my solution" button.
