### ISSUE TITLE
A lesson in Coding Interview Questions allows possibly incorrect code to pass

### ISSUE THREAD

**Issue by CallmeHongmaybe** [freeCodeCamp/freeCodeCamp#49260]
### Describe the Issue

When adding a new node ( or element ) to a binary search tree, I was supposed to compare the value supplied `add` method with that of current node. But it seems odd to me that, despite not doing it at all, the testing script somehow ignored it.  

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/add-a-new-element-to-a-binary-search-tree

### Your code

Here's the code I wrote
```
var displayTree = tree => console.log(JSON.stringify(tree, null, 2));
function Node(value) {
  this.value = value;
  this.left = null;
  this.right = null;
}
function BinarySearchTree() {
  this.root = null;
  // Only change code below this line
  this.add = function (value) { 
      let newNode = new Node(value), cr = this.root 

      if (!cr) {
        this.root = newNode;
        return undefined;
      }

      while (cr) { 
        let direction = cr.value > value ? "left" : "right"

        if (cr[direction] === value) return null

        if (!cr[direction]) { 
            cr[direction] = newNode 
            return undefined
        }

        cr = cr[direction] 
      } 
  }
  // Only change code above this line
}

```

### Expected behavior

I expect the unit test case ` Waiting:The add method should add elements according to the binary search tree rules` to fail instead of to succeed.

Also, if I slightly edit this LOC here: 
```
if (cr[direction] === value) return null
```
to  
```
if (cr[direction].value === value) return null
```
Then I expect the said unit test case to pass. 

### System

- Device: Dell Latitude 5580  
- OS: Ubuntu 22.04
- Browser: Brave Browser 
- Version: 1.45.127

**Comment by mtangmt** [comment]
The reason the "The add method should add elements according to the binary search tree rules." test passes is because the test does not test for adding duplicate keys. 
I've added a pr that changes the test so it adds a duplicate key, and the solution in the docs still works.
The code you wrote now fails (correctly).

Your intended fix of changing 
`if (cr[direction] === value) return null`
to
`if (cr[direction].value === value) return null`
does not work, as if cr[direction] is null, you can't get its .value
