### ISSUE TITLE
Build a Magazine Step 27: Is box-sizing needed?

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#49284]
### Describe the Issue

Someone in the forums pointed out that adding the `box-sizing` property just to `html` will not have the intended effect since the property is not inherited. It appears to me that removing this property completely from `html` in the final product does not seem to make any difference to the layout.

- Do we need `box-sizing`?
- If so, if the intent is to apply it to all elements then it should probably be moved to the `*, ::before, ::after` rule set.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-27

### Your code

```
html {
  font-size: 62.5%;
  box-sizing: border-box;
}
```

### Expected behavior

Either remove `box-sizing` completely or move it into the `*, ::before, ::after` ruleset.

### System

N/A

**Comment by lasjorg** [comment]
Pretty sure I saw this in another challenge too and it got fixed.

The CSS used looks like the [inherit version](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) of setting the `box-sizing` but with the actual inheriting missing from the code.

```
*,
::before,
::after {
  padding: 0;
  margin: 0;
  box-sizing: inherit;
}

html {
  font-size: 62.5%;
  box-sizing: border-box;
}
```

It should be fixed, but I would _not_ suggest we remove `box-sizing`, setting that (in my opinion) is pretty much a best pratice.

**Comment by MadasuDeepika** [comment]
Yes, the box-sizing property is needed here. Because by default, the width and height of an element are calculated based on its content but using box-sizing: border-box changes this behaviour so that the padding and border are included in the calculation sometimes.

If the intent is to apply the box-sizing property to all elements on the page, it should be moved to the universal selector (*), which applies it to all elements including pseudo-elements like : :before and : :after rule set. This ensures that all elements on the page have consistent sizing and layout behaviour.

Therefore the solution for the above problem is to move the "box-sizing: border-box" property into the universal selector (*), which applies it to all elements on the page, including pseudo-elements like : :before and : :after. The updated code would be:

`
html {
  font-size: 62.5%;
}

*, *: :before, *: :after {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

`

This ensures that all elements, including the HTML element, inherit the box-sizing property and that the layout behaves consistently across the page.

**Comment by lasjorg** [comment]
I'm guessing it would be easier and take less explaining to update step 26 to add the `box-sizing` on that selector and then remove the mention of it in step 27. Then update all the seed code.

**Comment by Sboonny** [comment]
Just a heads up, if lasjorg PR merged without issue, balance sheet project suffer the same issue, we can open a PR or issue for it, if the PR is merged
