### ISSUE TITLE
"non-virtual DOM elements" undefined phrase used in data visualization certification projects

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49303]
### Describe the Issue

In the 5 certification projects for the Data Visualization certificate, the phrase "(non-virtual) DOM elements" is used without any prior explanation (I checked the Data Visualization curriculum and no such phrase was introduced at any point).
It is not clear therefore to the learner what the requirement "Required (non-virtual) DOM elements are queried on the moment of each test." could actually mean.

Now, maybe it means "actual DOM' vs "virtual DOM" from the React curriculum. But requiring that a priori knowledge to understand a Data Visualization project requirement seems like overkill?

I propose that this requirement in all 5 projects be stated simply as "Required DOM elements..." The chance of someone not understanding that we mean 'actual DOM elements' seems miniscule to me in the context of these challenges, but I'm not a web developer, so if there is a valid reason to use the term 'non-virtual DOM elements', it would be very interesting for me to learn/hear of it.

ps. should this issue be accepted, please also fix the phrasing "on the moment" to be "at the moment" which I believe is what was actually meant.

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart

### Your code

```

```

### Expected behavior

update all 5 certification project statements referring to (non-virtual) DOM elements as per the above discussion.

### System

N/A

**Comment by naomi-lgbt** [comment]
I think this is more of a note for advanced campers, similar to mentioning that the tests might not work with a framework like Vue.

**Comment by hbar1st** [comment]
Yes I think so too, but it is too confusing to someone who is not that advanced. If we didn't say it, what is the chance an advanced camper will run into a problem?

**Comment by naomi-lgbt** [comment]
It likely wouldn't - though I also haven't seen much mention of beginners who *do* have confusion.

**Comment by hbar1st** [comment]
I agree that I haven't seen questions on this either but since the rule-of-thumb is to not include undefined technical terms in the challenges and projects, we should do something about this one. (Either define it or drop it)

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-choropleth-map.md
3. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-heat-map.md
4. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph.md
5. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-treemap-diagram.md

In these files, the text `Required (non-virtual) DOM elements` should be updated to `Required DOM elements`.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by yanrivera19** [comment]
Hello! I would love to contribute and fix this issue. May I proceed to do so?
