### ISSUE TITLE
visualize-data-with-a-bar-chart: "The bar elements'" in user stories 7/8/9, should place `.bar` in backticks

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49309]
### Describe the Issue

Should the word 'bar' in this sentence be in a code block? 
<strong x-id="1">User Story #8:</strong> The bar elements' <code>data-gdp</code> properties should match the order of the provided data.
 The context is this project: 
https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart 

Asking for translation purposes as I'm not familiar with this project.
(same question for all the user-stories with similar phrases 7/8/9)

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart

### Your code

```

```

### Expected behavior

references to elements whose class is bar should use backticks around the name of the class or use the phrase ".bar" in backticks

### System

N/A

**Comment by naomi-lgbt** [comment]
Yeah, we should definitely replace `bar` with `.bar` in those user stories.

**Comment by naomi-lgbt** [comment]
This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart.md


Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Vansh-Baghel** [comment]
Hey, I fixed this issue. Soon going to raise the PR, reading guidelines so that I dont mess up  🫡

**Comment by Vansh-Baghel** [comment]
Hey @naomi-lgbt I changed it even from the non-english language files because it was necessary. Shall I remove it?

**Comment by Vansh-Baghel** [comment]
Apologies for closing 2 PRs before it, I accidently made changes in non-english language. In the new PR, I made changes only in the English Language files
