### ISSUE TITLE
name attr. injected into step 41 of Building a Registration Form

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49301]
### Describe the Issue

Sometime ago, the seed code shown for step 41 of the Building a Registration Form was modified to include the name attributes on several input elements. I believe this was done by mistake (Ref: https://github.com/freeCodeCamp/freeCodeCamp/commit/2e83a3d41dd3e7fbc313dddd7635d25c24eab120#diff-1d97b888ed401f911b92086f080f24fd953294a3902771f73ea3830955c43b17)

Please see the discussion here as well:
https://forum.freecodecamp.org/t/unexpected-injected-attributes-learn-html-forms-by-building-a-registration-form-code-injected-between-step-40-and-step-41/590851

The name attribute should not be in the seed code (excepting the radio buttons) until the learner adds it in step 41.
Please remove the attribute from the required areas. I believe these are: first-name, last-name, email, password, terms-and-conditions and referrer.
(please double check carefully)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-41

### Your code

```

```

### Expected behavior

the seed code should not include name attributes that were not added in a previous step

### System

n/a

### Additional context

I discovered this issue because of the complaint filed in the forum: https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-41/590773

**Comment by naomi-lgbt** [comment]
Yeah, those should be removed (just from that step's seed code).

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fad1cafcde010995e15306.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
