### ISSUE TITLE
Invalid instruction: Step 53 learn typography by building a nutrition label

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49324]
### Describe the Issue

The text below is referring to a span that doesn’t exist:

Finally, nest the Cholesterol and 0mg span elements inside an additional span element for alignment.

There is no 0mg span element in the code at this point.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-53

### Your code

```

```

### Expected behavior

Change the text to:
Finally, nest the Cholesterol span element and 0mg inside an additional span element for alignment.

### System

N/A

**Comment by jeremylt** [comment]
If we apply the same changes from Step 43, the new text would be:

> After your last `.divider`, create a new `p` element with the text `Cholesterol 0mg 0%`. Wrap the text `Cholesterol` in a `span` element, and give that `span` element the `class` of `bold`. Wrap the text `0%` in another `span` element, with the `class` of `bold`. Finally, nest the `Cholesterol` `span` element and the text `0mg` in an additional `span` element for alignment.

**Comment by Nirajn2311** [comment]
@jeremylt You're right, the instruction should be updated to the one in your comment.

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f7de4487b64919bb4aa5e.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
