### ISSUE TITLE
Grammar: Basic JS Step: Assignment with a return value

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49408]
### Describe the Issue

The step contains an incomplete sentence (grammatically speaking) when it says:

will call the sum function, which returns a value of 17 and assigns it to the ourSum variable.

It is not clear who "will call the sum function" without actually looking at the code because the sentence is broken.
(The sentence is untranslatable at the moment.)

Perhaps it should say:
This line of code calls the sum function, which returns ...

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value

### Your code

```

```

### Expected behavior

correct the grammar of the sentence so it is clear who is doing the calling.

### System

N/A

**Comment by atnakayrus** [comment]
I believe the change will not be necessary as the sentence when read together with code is "then: ourSum=sum(5,12); will call the sum function" , which is in correct grammar , also there are not enough elements in this code for there to be any confusion

**Comment by hbar1st** [comment]
As I mentioned, this is not translatable as the code in the middle is not translatable. 
A line of code in the middle of a sentence is also not correct grammar in my estimation.

**Comment by hbar1st** [comment]
> Calling the `sum` function with the arguments of `5` and `12` produces a return value of `17`

This part I understand but the following part "and assigns it" is not true? As calling the function does not also assign. 
The line of code does both sure, but that's why I suggested "This line" or "This statement" or something like that to be the 'actor' here.
"This statement calls the sum function with the arguments..., and assigns it to the ..."

**Comment by jeremylt** [comment]
> Assume we have defined a function `sum` which adds two numbers together.
```javascript
ourSum = sum(5, 12);
```
> Calling the `sum` function with the arguments of `5` and `12` produces a return value of `17`. This return value is assigned to the `ourSum` variable.

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value.md

In this file, the text:

````md
Assume we have pre-defined a function `sum` which adds two numbers together, then:

```js
ourSum = sum(5, 12);
```

will call the `sum` function, which returns a value of `17` and assigns it to the `ourSum` variable.
````

should be replaced with:

````md
Assume we have defined a function `sum` which adds two numbers together.

```javascript
ourSum = sum(5, 12);
```

Calling the `sum` function with the arguments of `5` and `12` produces a return value of `17`. This return value is assigned to the `ourSum` variable.
````

> Calling the `sum` function with the arguments of `5` and `12` produces a return value of `17`. This return value is assigned to the `ourSum` variable.

will call the `sum` function, which returns a value of `17` and assigns it to the `ourSum` variable.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by JoLalo** [comment]
Hi! I'm new to open source programming. Could you guide me?

**Comment by Abibaj** [comment]
> I believe the change will not be necessary as the sentence when read together with code is "then: ourSum=sum(5,12); will call the sum function" , which is in correct grammar , also there are not enough elements in this code for there to be any confusion

I agree with this, it reads with the line of code.

**Comment by hbar1st** [comment]
another step that has the same issue and should get a similar fix:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-and-operator

The sentence:
"will only return Yes if num is greater than 5 and less than 10. The same logic can be written as:"
should be changed to:
"This will only..."
(adding This is enough to fix it as a reference to the previous code block)

And similarly for this step as well:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator

**Comment by jeremylt** [comment]
Probably worth making a new issue since this one already has a PR
