### ISSUE TITLE
Incorrect description of "npm run seed" in quick commands reference

### ISSUE THREAD

**Issue by javrrr** [freeCodeCamp/freeCodeCamp#49414]
### Describe the Issue

In the [quick commands reference](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=quick-commands-reference) section of the setup guide, the command `npm run seed` is incorrectly described as "Parses all the challenge markdown files and inserts them into MongoDB."

This description is incorrect as the [package.json script](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/package.json#L91) is only executing [seedAuthUser.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/scripts/seed/seedAuthUser.js), which only inserts users into the mongodb collection.

### Affected Page

https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally

### Steps to Reproduce

1. Follow setup instructions for [how to setup freecodecamp locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) and setup local machine
2. Navigate to [quick commands reference](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=quick-commands-reference) of the setup guide
3. Execute `npm run seed` and validate contents in mongodb

### Recommended fix or suggestions

Update description to "Creates authorized test users and inserts them into mongodb"

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-setup-freecodecamp-locally.md

In this file, at the very end, is the `Quick Reference` section. The description for the `npm run seed` command needs to be updated from `Parses all the challenge markdown files and inserts them into MongoDB.` to `Creates authorized test users and inserts them into MongoDB.`

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
