### ISSUE TITLE
"user function" was meant to be "user object"? (tests in "Serialization of a User Object")

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#49418]
### Describe the Issue

There are these tests in this lesson:

> You should serialize user function correctly.

> You should deserialize user function correctly.

I guess it was meant to be "user object", not "user function".

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/serialization-of-a-user-object

### Your code

```

```

### Expected behavior

The tests should be:
> You should serialize user object correctly.

> You should deserialize user object correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/25644062/219844822-6c3c0361-70c8-47b0-8486-c6fdf957f3b1.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 110.0.5481.104

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/serialization-of-a-user-object.md

In this file, the text `You should serialize user function correctly` should be updated to `You should serialize the user object correctly`, and the text `You should deserialize user function correctly` should be updated to `You should deserialize the user object correctly`.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by MohitBansal321** [comment]
would you like to assign this issue to me?

**Comment by MohitBansal321** [comment]
@sidemt done
