### ISSUE TITLE
take-home-projects progress bar

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#49449]
### Describe the Issue

Re: #49447 

The progress bar now no longer makes sense.

### Affected Page

https://www.freecodecamp.dev/learn/coding-interview-prep/

### Steps to Reproduce

1. Go to above link
2. Submit a project
3. See modal information

### Expected behavior

We should probably just remove the text. Alternatively, we can change it to be correct (`0 out of 0 completed`)

### Screenshots

<img width="706" alt="image" src="https://user-images.githubusercontent.com/51722130/220190467-28a9b256-9a7e-472c-b203-e17155353433.png">

### System

N/A

**Comment by ojeytonwilliams** [comment]
The underlying issue is that `challengeType` is doing too much, so we end up with bizarre situations like this.

A reasonable use of `challengeType` is to determine what component needs to render a given challenge page. However,
as @gikf pointed out https://github.com/freeCodeCamp/freeCodeCamp/pull/49447#issuecomment-1437431639 we also use `challengeType` to determine if a block is a final project or not. And that leads us here.

I think a relatively simple improvement would be to stop inferring block properties from the `challengeType`. Instead, we can declare them in the meta files and rely on validation to ensure that the challenges in a block are allowed. For example use the same `isFinalProject` logic to ensure that all the challenges in a final project are really challenges, but do this during the build.

cc: @moT01 @naomi-lgbt

**Comment by ShaunSHamilton** [comment]
>  Instead, we can declare them in the meta files and rely on validation to ensure that the challenges in a block are allowed.

Did we not remove a lot of this meta information, not too long ago?

**Comment by ojeytonwilliams** [comment]
I think so, but if so it was because it was not being used.

belated cc: @Sembauke since you've been through the pain of moving blocks around most recently.
