### ISSUE TITLE
Clarify instructions for Cafe Menu Step 87

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#49595]
### Describe the Issue

There may be some possible confusion over what "address" is referring to. It wouldn't hurt to make this a little clearer.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-87

### Your code

N/A

### Expected behavior

Suggested improvement to instructions:

> Now apply the `address` class to the `p` element containing the street address `123 Free Code Camp Drive`.

### System

N/A

**Comment by lasjorg** [comment]
I can't see any downside to making this clarification and it seems like a good first-time issue.

---

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e7a4750dd05b5a673920.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
