### ISSUE TITLE
JavaScript Algorithms and Data Structures - Testing Objects for Properties

### ISSUE THREAD

**Issue by AnthonySummers157** [freeCodeCamp/freeCodeCamp#49689]
### Describe the Issue

Attempting this lesson and I create this:

This is shown in the box below:
// running tests
checkObj({gift: "pony", pet: "kitten", bed: "sleigh"}, "gift") should return the string pony.
checkObj({gift: "pony", pet: "kitten", bed: "sleigh"}, "pet") should return the string kitten.
checkObj({city: "Seattle"}, "city") should return the string Seattle.
// tests completed

And I cannot move on.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties

### Your code

```

```
function checkObj(obj, checkProp) {
  // Only change code below this line
  return "Not Found";
  // Only change code above this line
}

### Expected behavior

The correct answer

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
@AnthonySummers157 This sounds like it should be asked in the [forum](https://forum.freecodecamp.org). Please use the Get Help button in the challenge to Ask for Help, which will create a new post in the forum and automatically include our code.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by AnthonySummers157** [comment]
This is not an ask for help, the answer being provided is not related to the input being asked, it is two different scenarios in one.

**Comment by gikf** [comment]
What do you mean? 

`checkObj` called with `{gift: "pony", pet: "kitten", bed: "sleigh"}, "gift"` is expected to return string `pony`.
At the same time when called with `{gift: "pony", pet: "kitten", bed: "sleigh"}, "pet"` it should return string `kitten`.
