### ISSUE TITLE
Learn Relational Databases by Building a Mario Database

### ISSUE THREAD

**Issue by duartenunes86** [freeCodeCamp/freeCodeCamp#49806]
### Describe the Issue

I put the right code but it doesn't advance for the next exercise

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```

```
INSERT INTO sounds(filename, character_id) VALUES('yay.wav', 3), ('woo-hoo.wav', 3);

### Expected behavior

I put the right code but it doesn't advance for the next exercise

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Browser Chrome in a library

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Ask for Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
