### ISSUE TITLE
Update Redux Challenges in Frontend Library Curriculum to use recommended Redux Toolkit

### ISSUE THREAD

**Issue by JamieVaughn** [freeCodeCamp/freeCodeCamp#49928]
### Is your feature request related to a problem? Please describe.

The frontend libraries development certification challenges that cover `redux` [1] and `react-redux`[2]  use the old deprecated syntax. The recommended way to use redux today is with the package `react-redux` paired with `@reduxjs/toolkit` and it's new exported methods. 

[1] https://www.freecodecamp.org/learn/front-end-development-libraries/#redux
[2] https://www.freecodecamp.org/learn/front-end-development-libraries/#react-and-redux

### Describe the solution you'd like

I'd like to update the challenges in the two redux related curriculum segments above to use Redux Toolkit or `zustand` instead of the old redux syntax.

### Describe alternatives you've considered

Other alternatives:
1) Teach one of the different, simpler React state management libraries, like `zustand`, `valtio` or `jotai`.
2) Remove redux from the curriculum altogether as the recent consensus on it is that it's a more of a niche state management library for highly complex business logic and may not be generally applicable any longer, especially for small to medium apps. 

But I think teaching the old redux syntax (which the redux core team no longer recommends using) is not viable.

### Additional context

I'd be willing to volunteer to submit a PR towards this aim, but would want to know the direction preferred by FCC.org among the alternatives I listed or any others subsequently suggested.

**Comment by ShaunSHamilton** [comment]
@JamieVaughn Thank you for taking the time to open this.

We are no longer doing major updates to the current curricula, because they are being completely overhauled with the new version of the curriculum. So, we are happy to accept bug fixes, but would prefer any major efforts to be focused on the new version.

With cases like this, it is a matter of timeline. A few sections of the curriculum teach _"depracated"_ tooling, but the content is still relevant. We do not want to remove completely valid content.

Example: class-based components are considered "outdated", but there are still hundreds of production apps written with them, so developers will still need the resources to learn them. Same goes for jQuery, the XMLHttpRequest API, and this issue you have opened here.

So, seeing as the lesson content is not broken or incorrect, we will keep it as is. Once the new version is ready, it will be "front-lined" in the UI.

I hope this clarifies

**Comment by JamieVaughn** [comment]
I understand your perfectly rational position, and thanks to you & the FCC community very much for your efforts.

However I would just like to add for sake of context: as a frontend development instructor, I have stopped recommending to my students to complete most of the challenges in the frontend library development curriculum because it ends up confusing them. They get frustrated and discouraged by the disorienting variety and complexity of having to learn not only the modern syntax but also the older syntax. For new students, the topic of web development is already paralyzingly vast, so any opportunity to pare it down for their first exposure is essential to reduce student attrition.

I do still have them complete the frontend development projects. In any case, thank you for all your efforts to the wonderful resource that is freecodecamp.org. I don't intend this negatively at all, just sharing a perspective.
