### ISSUE TITLE
User should be redirected to /learn page if logged in

### ISSUE THREAD

**Issue by NiazMorshed2007** [freeCodeCamp/freeCodeCamp#49946]
### Every time I visit freecodecamp.org it shows the default `home ("/") page` (image shown below). 

![image](https://user-images.githubusercontent.com/77217706/229858158-5be6e59f-b614-43fd-93b6-366a1d5f13e1.png)

Every time I've to click the `'get started'` button to see the courses even when I'm already logged in. But it seems not a good experience to me. I think it will be great experience for learners if it automatically redirects him to the `/learn` page if the user is logged in. I believe it will helpful for learner to stay focused. 

### Describe the solution you'd like

Solution: Redirect user from `"/"` to `"/learn"` only if when the user is logged in.

### Describe alternatives you've considered

N/A

**Comment by umangm17** [comment]
We can used react roting and condinal rendering

**Comment by sambhavgupta0705** [comment]
I would like to work on it.

**Comment by raisedadead** [comment]
Thanks for the recommendation; this behavior is intentional by design :)

Our landing page renders the same (minus the user avatar and some other elements in the nav) for both versions, which is exactly what we expect from the landing page.

This is a simple UX pattern that we follow all across the platform.

You may have noticed clicking the button takes you to the learn page without taking you to the authentication page if you are already logged in. It's instant.

Happy coding!
