### ISSUE TITLE
Bad Grammar Cat Photo App 8

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49964]
### Describe the Issue

The last sentence here is bad grammar. Also. The period after the code block can look awkward on mobile.

> HTML attributes are special words used inside the opening tag of an element to control the element's behavior. The src attribute in an img element specifies the image's URL (where the image is located). An example of an img element using an src attribute: `<img src="https://www.example.com/the-image.jpg">`.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-8

### Your code

N/A

### Expected behavior

Rework sentence for better grammar and formatting.

Possible fix

> HTML attributes are special words used inside the opening tag of an element to control the element's behavior. For example, the src attribute in an img element specifies the image's URL (where the image is located). 

```
<img src="https://www.example.com/the-image.jpg">
```

### System

All

**Comment by naomi-lgbt** [comment]
Perhaps something like:

````md
HTML attributes are special words used inside the opening tag of an element to control the element's behavior. The `src` attribute in an `img` element specifies the image's URL (where the image is located).

Here is an example of an `img` element with a `src` attribute pointing to the freeCodeCamp logo:

```html
<img src="https://cdn.freecodecamp.org/platform/universal/fcc_secondary.svg">
```
````

(unrelated but I strongly dislike the fact that github doesn't wrap codeblocks lol)

**Comment by jeremylt** [comment]
I like that fix better

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. [Cat Photo App - Step 8](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc24073f86c76b9248c6ebb.md)

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by KunalSalunkhe12** [comment]
May I start working on this issue? This will be my first open source contribution, and it seems like I can fix it.

**Comment by naomi-lgbt** [comment]
Heya @KunalSalunkhe12,

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by KunalSalunkhe12** [comment]
@naomi-lgbt  
Thank you for the information. I have made sure to review the guidelines for contributing before submitting my pull request.
