### ISSUE TITLE
Bash scripting courses + challenges

### ISSUE THREAD

**Issue by marktlinn** [freeCodeCamp/freeCodeCamp#49978]
### Is your feature request related to a problem? Please describe.

Looking through the *Learn Bash Scripting by Building Five Programs* and running through the challenges on CodeAlly's IDE causes some issues and bugs for example:
* issues with the keyboard not recognising certain keys on international keyboards, special characters etc.
*  browser specific setup, inability to copy and paste into terminal - meaning the user has to change settings.
*  the terminal crashing, or the code not passing the test until everything is reloaded

Overall I think the experience can be quite buggy and could potentially make some people give up on what is a really good intro to Bash scripting

### Describe the solution you'd like

Currently users can only go through the bash scripting courses such as *Learn Bash Scripting by Building Five Programs* by waiting for the script on each level/challenge to be tested and pass, but sometimes the testing fails for no reason, or simply fails to run (see the issues stated above)

It could be a good idea to give the user the option to follow challenges off-platform in some manner e.g. have the user follow the screen instructions while coding in their own preferred IDE or terminal. This way they would not need to wait or continously reload the browser based terminal and IDE on CodeAlly if there were issues. Rather seeing that their code is working they could continue on with the next challenge.

### Describe alternatives you've considered

Above

**Comment by moT01** [comment]
There's not much we can do about some of these issues.

> issues with the keyboard not recognizing certain keys on international keyboards

We've discussed this before - I think the consensus was that we can't really do anything about it.

> browser specific setup

Again - not a whole lot we can do. If there's a specific browser setting that's consistently causing problems, we could maybe add a note or something about it.

> the terminal crashing, or the code not passing the test until everything is reloaded

I haven't seen many instances of the terminal crashing - maybe I'm just not looking. But yes, the tests can be buggy - more-so because something isn't set up correctly rather than the test itself. Meaning that you need to close and open the terminal for the bashrc to take effect, and any other settings that may have got messed up - which can require resetting or other debugging to make it work again. We would certainly like to continue to improve this wherever we can. 

> It could be a good idea to give the user the option to follow challenges off-platform

The [instructions are available in markdown,](https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs/blob/main/TUTORIAL.md), they aren't formatted all that great or that easy to find - but campers could look at those if they wanted. I'm not sure where we would put just the instructions. Possibly on [these intro pages](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/) - that's for one of the RWD blocks, but we could make the pages for RDB and put them there.

**Comment by marksist300** [comment]
For sure! I think having the instructions available and possibly the expected output (if/when applicable) might be worth while. The Code Ally site doesn't work at all for me anymore regardless of the browser I use or its settings, have tried soft and hard resets to no avail. There must be other people having the same or similar issues, who'd probably benefit from having easy access to the instructions so that they can do the challenges locally.

**Comment by pkdvalis** [comment]
I'm having the same problems with CodeAlly, many others as well:

https://forum.freecodecamp.org/t/stuck-on-starting-virtual-server/667205/

It's too unreliable. I'm going to try completing locally using this guide:
https://www.freecodecamp.org/news/how-to-run-freecodecamps-relational-databases-curriculum-using-docker-vscode-and-coderoad

Is it correct that we can't submit our answers and mark as completed on freeCodeCamp if we do this? There are other lessons where we can put files on a github repo and submit that, but I don't see that option here.

**Comment by moT01** [comment]
We are working on fixing the issue with running the courses @pkdvalis. Thanks for your patience. If you want to save to your fCC account while running the courses locally, there's some [instructions here on how to do that.](https://forum.freecodecamp.org/t/local-database-cert-code-to-fcc/641820/3) They aren't super specific, so you will have to figure some things out.

**Comment by naomi-lgbt** [comment]
Going to close this as we've migrated to GitPod, which should resolve a good number of the pain points.
