### ISSUE TITLE
lower-jaw component can be refactored to separate files

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#50118]
### Describe the Issue

in order to make a code more readable and clear, it can be better - to split code of this [file](https://github.com/shootermv/freeCodeCamp/blob/fix/cypress-flaky-test-multiline/client/src/templates/Challenges/classic/lower-jaw.tsx) to several separate files 

### Affected Page

https://github.com/shootermv/freeCodeCamp/blob/fix/cypress-flaky-test-multiline/client/src/templates/Challenges/classic/lower-jaw.tsx

### Steps to Reproduce

1. Go to 'https://github.com/shootermv/freeCodeCamp/blob/fix/cypress-flaky-test-multiline/client/src/templates/Challenges/classic/lower-jaw.tsx'
2. You can see a lot of code
3. Several components at the same file
4. It can be refactored 

### Expected behavior

code can be shorter and clearer

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Sboonny** [comment]
I am against splitting the files, I don't see the gains and I see a couple of examples, that were extremely difficult to interact with the files
- `nav-link` and its wrong typing, which cased the state to be passed to the `header` as props without the need to pass it. https://github.com/freeCodeCamp/freeCodeCamp/pull/49860
- the wrong typing to `profile` that create the wrong true state for points, here is the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/50106 and there are similar PR to it in the history of the file.

---

in my opinion, the lower-jaw component needs to:
- use `TFunction` instead of the `string` props, to have a better and cleaner code.
-  it has 5 `useStates`, so using `useReducer` instead of them to iron down the edge cases which may bug the states if that even possible.
- Rename multiple variables name and remover the `lowerJaw` from the subComponent variables' name, because the components aren't exported so adding `lowerJaw ` is redundant.
- Remove the `useEffect` that shift the layout, and use grid for that.
