### ISSUE TITLE
Incomplete argument in test

### ISSUE THREAD

**Issue by artoma** [freeCodeCamp/freeCodeCamp#50135]
### Describe the Issue

Please check this commit: https://github.com/freeCodeCamp/freeCodeCamp/commit/b5448c05f252d98f06f17e9ccb3ca316ce24055a

There is a missing }) on line 524!

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### Your code

```
This fragment of the test code is broken!

const expected = {
      username,
      description: 'test',
      duration: 60,
      _id,
      date: new Date().toLocaleDateString("en-US", {
        timeZone: "UTC", weekday: "short", month: "short",
        day: "2-digit", year: "numeric"
    };

Please take a look the link in description!
```

### Expected behavior

Should look like this:

```
const expected = {
      username,
      description: 'test',
      duration: 60,
      _id,
      date: new Date().toLocaleDateString("en-US", {
        timeZone: "UTC", weekday: "short", month: "short",
        day: "2-digit", year: "numeric" })
    };
```

### Screenshots

![image](https://user-images.githubusercontent.com/6938118/233775226-ad194df9-f892-408a-9e88-c23498cf3e11.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md

The intended change appears to be:
```
      date: new Date().toLocaleDateString("en-US", {
        timeZone: "UTC", weekday: "short", month: "short",
        day: "2-digit", year: "numeric"
      }).replaceAll(',', '');
```

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Abi-Liu** [comment]
Hi is anyone working on this issue? If not can I fix it?

**Comment by gurvirbaraich** [comment]
@artoma Thanks for mentioning the issue. Its seems really easy to fix and I see some pull requests are already there. I am also looking for my first contribution but as per the ethics I should not create pull request for this issue.

**Comment by Jayant107** [comment]
Hi, is it still open can i work on it
