### ISSUE TITLE
Won't submit

### ISSUE THREAD

**Issue by mjohnstonee** [FreeCodeCamp/FreeCodeCamp#5027]
Challenge [Waypoint: Override Class Declarations with Inline Styles](http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20%0Aclass%3D%22pink-text%20blue-text%22%0Astyle%3D%22color%3A%20white%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" 
class="pink-text blue-text"
style="color: white">Hello World!</h1>

```

**Comment by gasperno** [comment]
@mjohnstonee 
Thank you for reporting the issue.
Until this PR is fixed, edit your code such that `<h1>` tag is in single line.
> \<h1 id="orange-text" 
> class="pink-text blue-text"
> style="color: white">Hello World!</h1>

Edit the above line as below. Instead of spanning multiple lines, your code will be in single line.
`<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>`

Your code is perfect. This edit will pass the test case. 

Note to other contributors:
 `.*` is used in code base as regex to match any character in multiple cases. It matches any character except new line characters. 
It is legitimate for html code to span multiple lines. So the regex should be changed to `[\s\S]*?`. This regex matches any character including new line character.

I will submit a PR for this issue.

**Comment by gasperno** [comment]
I think this is pretty legitimate. When a tag spans multiple lines, the test case is not passed. 
Would you mind if I fix it?

**Comment by erictleung** [comment]
@ltegman can you close this issue? It appears that PR #5031 fixes this but wasn't closed when the PR was merged.
