### ISSUE TITLE
Certification border is cut off

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#50340]
### Describe the Issue

The certifications have the top border cut off.

### Affected Page

https://www.freecodecamp.org/certification/mot01/responsive-web-design

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/certification/mot01/responsive-web-design
2. Top border is behind address bar

### Expected behavior

Border to be visible

### Screenshots

<img width="931" alt="Screen Shot 2023-05-09 at 12 28 24 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/e28a7b46-64ce-4307-b08f-ad4735d2d05f">

### System

Firefox 111.0.1

**Comment by Sboonny** [comment]
Removing the `calc` in that property will fix this.

https://github.com/freeCodeCamp/freeCodeCamp/blob/5d9dccb37f4e695775a3ee3b22858667941dbd46/client/src/pages/certification.css#LL147C1-L149C1

it doesn't look broken with profile. we can remove it. 🤔

**Comment by Sboonny** [comment]
I am opening this for contribution for first timers, because the solution seems small and it doesn't have a big affect 🤔.

----

To solve this issue, you need to change the value of `margin-top` property, by removing the `calc` function from it.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Sboonny** [comment]
sorry for the delay @krsnamara, you can use the environment of your choice as long as you have tested the changes in the development environment. 👍 

Because the issue is already solved, you can visit https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 and pick one.

**Comment by krsnamara** [comment]
All good, Thank you!
