### ISSUE TITLE
Lesson: "Add Font Awesome Icons to all of our Buttons" in Front End Development Libraries Certification 

### ISSUE THREAD

**Issue by LaurenC2022** [freeCodeCamp/freeCodeCamp#50471]
### Describe the Issue

Course: Front End Development Libraries Certification
Section: Bootstrap
Lesson: Add Font Awesome Icons to all of our Buttons

The wording is as follows: "Note: The span element is an acceptable alternative to the i element for the directions below."

The word "below" is wrong. The instructions are above, not below. Switch word "below" with "above". 

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons

### Your code

```



```
None/ not applicable to issue. 

### Expected behavior

N/A, not applicable to issue 

### Screenshots

Issue is found within the text of the instructions 

### System

N/a, not applicable 

### Additional context

This is only a grammatical error found in the instructions for the challenge.

**Comment by xynoan** [comment]
I think the directions mentioned here is the tests.

**Comment by naomi-lgbt** [comment]
Yes, this is referring to the instructions in the test text, which is where the `i` element is requested.

**Comment by jeremylt** [comment]
Maybe something like this would be clearer

> Note: This challenge requires i elements but you can also use span elements in your own projects.

**Comment by naomi-lgbt** [comment]
The challenge will accept span elements.

**Comment by jeremylt** [comment]
Ahh. So we should probably say something more like

> Note: You can use either i or span elements to complete this challenge.

**Comment by naomi-lgbt** [comment]
That one works for me.

Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/03-front-end-development-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons.md

You should update the instruction text to replace:

```md
**Note:** The `span` element is an acceptable alternative to the `i` element for the directions below.
```

With:

```md
**Note:** You can use either `i` or `span` elements to complete this challenge.
```

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by jeremylt** [comment]
We don't assign issues. We accept the first complete pull request that fully addresses the issue

**Comment by AliMora83** [comment]
Very excited 🥳
