### ISSUE TITLE
Automated preview environments at Pull Request

### ISSUE THREAD

**Issue by dakar91** [freeCodeCamp/freeCodeCamp#50518]
**Context*

Bunnyshell is providing free Kubernetes infrastructure for previews at PRs to open source projects.

Would you be interested in having preview environments on future pull requests?

Our team @bunnyshell and @bunnyshellosi are ready to help implement the initial pipeline to get you started!

Example workflow - https://github.com/aris-bunnyshell/demo-books-php/tree/main/.github/workflows
Example configuration - https://github.com/aris-bunnyshell/demo-books-php/blob/main/.bunnyshell/templates/docker-compose/bunnyshell.yaml

We really think some of the issues and PRs can benefit from preview environments, like the over 100 open issues which are platform or UI related: https://github.com/freeCodeCamp/freeCodeCamp/labels?q=platform+ui

**Comment by dakar91** [comment]
Hey @raisedadead and @ShaunSHamilton maybe you can have a quick look here since you've been working with Gitpod in freeCodeCamp?

**Comment by raisedadead** [comment]
Do you have demos where we can see this in use?

**Comment by dakar91** [comment]
[Here's a quick video](https://www.youtube.com/watch?v=IemyjCHOiX8&list=PLZehJJ9s5mC73noi_Fry0GUBSOCN8ssps&index=8&ab_channel=bunnyshell) showcasing the preview environments, however we're suggesting a different, more configurable approach through the your Github Actions workflows instead of handling the logic through the Bunnyshell backend. 

Example workflow - https://github.com/aris-bunnyshell/demo-books-php/tree/main/.github/workflows - this would post the URL endpoints in the PR together with a link to the app logs.

Hope this brings a bit more clarity. @raisedadead

**Comment by raisedadead** [comment]
Thanks, Grig.

I checked the video, and it surely seems interesting and would be a great tool for our quick reviews. I appreciate you sharing it with us.

Here is my candid feedback:

1. The sample code for the workflows you shared with us is overwhelming. Apologies, but we are limited on time :) – I think simplifying your examples should help you get more open-source projects onboarded on the platform.

2. I also looked at the configuration file you shared. We are not Kubernetes experts, but I like that the config looks like a standard `kubectl` and `kustomize` style syntax. But again, to someone who has yet to learn about K8s, writing these out would be an overwhelming experience.

3. Our application code needs to be structured for OCI-compliant style stacks. We have cross-dependencies that make it very tedious to isolate and build things. So you would end up with containers that are gigabytes in size because of the code.

Other pain points that I can see are:

- Having to maintain code in which we are not experts at. Dockerfiles and configs etc.
- GitHub Actions concurrency limits for public repos. We get 20 for the whole organization, and dozens of repositories and workflows depend on this limit.

Unfortunately, these are challenging & strict criteria that need addressing. At this time we can not proceed with the tool as-is. But given the large volume of PRs and activity this repository sees we would be happy to integrate the tool should the pain points and the feedback be addressed in future versions.

Thanks a lot and wishing you the best for the platform! You are doing an amazing job there.

**Comment by dakar91** [comment]
Hey @raisedadead, thank you for the feedback.

1. Yes, the workflow code is a draft and it surely is a bit more complicated than it needs to be. We intend on the short term to create a custom Action in GHA that can be called in one step and that would make the workflows using it significantly less complex.
2. There would be an effort involved at the beginning, mostly from our team where we have to create the initial environment configuration in Bunnyshell. Then if changes are required you can create an issue and tag our team to have a look. Also, we might choose to ingest a DockerCompose file each time a deployment is made so contributors woulnd't have to bother learning Bunnyshell syntax.
3. I'm not sure here, it's not very common to see multiple GB containers, but we can evaluate how this might work.


Considering the limitation on GHA, maybe the triggering functionality and the build could also happen on the Bunnyshell cluster and just our platform would comment on the PR with the URLs.

Please let us know if these things change the current situation, we're happy to discuss further.

Thank you
