### ISSUE TITLE
No test can be run its only loading

### ISSUE THREAD

**Issue by MajidAhmed** [FreeCodeCamp/FreeCodeCamp#5057]
when i finish a challenge and submit it hitting  (ctrl+enter) 

![freee camp](https://cloud.githubusercontent.com/assets/16161983/11619497/d9d2be70-9cb9-11e5-8852-7b9278a513cb.PNG)

**Comment by SaintPeter** [comment]
Can you please explain what the specific problem is that you're experiencing?  Are you saying that no tests pass and you are presented with the "next" screen?  Or that you can't click the "Submit" button?

**Comment by MajidAhmed** [comment]
When i pass the next challenge isn't showing up, it's only showing loading

**Comment by SaintPeter** [comment]
What browser are you on?  Have you tried any others?  Have you tried clearing your cache, reloading the site, etc?

**Comment by MajidAhmed** [comment]
I was using Firefox and tried it even with chrome, it is working well today
although it's stopping some times

**Comment by AkiraLaine** [comment]
@MajidAhmed Are you using a VPN? If so, that's the reason it doesn't work.

**Comment by KethuSingh** [comment]
Even i faced the same issue multiple times but for different reasons:
1. On the left side of the code editor in FCC, they provide few points which is to be completed both before the (Run tests) button and after that.
2. Install a AdBlock to the browser you are using, because i have seen due to Ads interference it is not moving further.
3.Just Logout and Login and come to same point,Run the code, it will be successfully loaded to other task.

**Comment by ltegman** [comment]
Closing this as a problem with the specific connection or browser.

Thanks for your ideas @MajidAhmed and @AkiraLaine.

Happy coding!
