### ISSUE TITLE
can't develop through gitpod due to pnpm version

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50681]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Gitpod can't be used to develop right now. Or maybe it's possible but someone new wouldn't know what steps they need to take.
Should i add a note in how-to-setup-freecodecamp-locally.md so that new people know? 
https://github.com/freeCodeCamp/freeCodeCamp/pull/50613#issuecomment-1577010365
**To Reproduce**
1. follow instructions in how-to-setup-freecodecamp-locally to develop with gitpod, fails with message ` ERROR  /@adobe/css-tools@4.2.0 is an invalid relative dependency path`

**Comment by ojeytonwilliams** [comment]
Thanks for letting us know @jmetev1.

On the pnpm side this should be resolved by https://github.com/pnpm/pnpm/releases/tag/v8.6.2

@ShaunSHamilton any idea why our .gitpod.Dockerfile isn't already using the latest version of pnpm?

**Comment by ShaunSHamilton** [comment]
> @ShaunSHamilton any idea why our .gitpod.Dockerfile isn't already using the latest version of pnpm?

Because I have forsaken the local config to focus on: https://github.com/freeCodeCamp/gitpod-images/pull/3/files#diff-b093d34eec92adf6e0cc6e445edb7147ea45d25fb0c98f2f84a60f5aae6f34f7

For this repo, I have just been manually running `npm i -g pnpm`. Personally, I do not like everything running from the get-go, but realise many like the one-button setup.

This is so quick to fix, I will just PR it before the long-term fix is ready.
