### ISSUE TITLE
Adding React hooks to the React part of the Front End Development Libraries course

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50690]
### Is your feature request related to a problem? Please describe.

Currently, there's no mention of [React Hooks](https://react.dev/reference/react) in the [React](https://www.freecodecamp.org/learn/front-end-development-libraries/#react) section of the [Front End Development Libraries](https://www.freecodecamp.org/learn/front-end-development-libraries/) course. Considering the fact, that how popular React Hooks are and how widely they are used in the industry, I believe React Hooks should be mentioned or taught to the users in one way or another.

### Describe the solution you'd like

In order to educate users about [React Hooks](https://react.dev/reference/react), some modules ( related to React Hooks ) should be added to the [React](https://www.freecodecamp.org/learn/front-end-development-libraries/#react) section of the [Front End Development Libraries](https://www.freecodecamp.org/learn/front-end-development-libraries/) course.

**Comment by jdwilkin4** [comment]
Hi @AnonSar !

Yes, you are correct that react hooks is the modern and standard way in React applications.
The new frontend libraries course will teach hooks and no longer teach class based components. 

I am going to go ahead and close this issue since this is already in plans for the new curriculum. 👍
