### ISSUE TITLE
Markdown instead of HTML

### ISSUE THREAD

**Issue by CBID2** [freeCodeCamp/freeCodeCamp#50703]
### Describe the Issue

I was reviewing the Technical Documentation project and noticed that the steps only use HTML.  I think it would be more beneficial for the user stories to encourage Markdown instead. As someone who has been doing more docs-based open source contributions, this language is used more to create documentation for software. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-technical-documentation-page-project/build-a-technical-documentation-page

### Your code

N/A

### Expected behavior

N/A 

### Screenshots

![user stories](https://github.com/freeCodeCamp/freeCodeCamp/assets/105683440/18e8918c-4abb-45e2-a328-560b785da5ce)

### System

- Device: Mac
- OS: macOS 
- Browser: Chrome 
- Version: 114

**Comment by gikf** [comment]
What do you mean? That project should be done with markdown, instead of HTML + CSS?

**Comment by jdwilkin4** [comment]
HI @CBID2 ! 

> As someone who has been doing more docs-based open source contributions, this language is used more to create documentation for software.

Yes, while it is true that a lot of open source projects will use markdown for their documentation, in the case of this certification project it wouldn't be the best choice. 

The goal of the certification projects for the Responsive Web Design course is for campers to have the opportunity to practice and build projects based on what they learned in the course. 
Since this course focuses on HTML and CSS, all of the certification projects focus on those two languages. 

Campers will be introduced to markdown later on in the Frontend libraries section with the [Markdown Previewer project](https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-markdown-previewer)

Hope that helps 👍

**Comment by CBID2** [comment]
> HI @CBID2 ! 
> 
> 
> 
> > As someone who has been doing more docs-based open source contributions, this language is used more to create documentation for software.
> 
> 
> 
> Yes, while it is true that a lot of open source projects will use markdown for their documentation, in the case of this certification project it wouldn't be the best choice. 
> 
> 
> 
> The goal of the certification projects for the Responsive Web Design course is for campers to have the opportunity to practice and build projects based on what they learned in the course. 
> 
> Since this course focuses on HTML and CSS, all of the certification projects focus on those two languages. 
> 
> 
> 
> Campers will be introduced to markdown later on in the Frontend libraries section with the [Markdown Previewer project](https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-markdown-previewer)
> 
> 
> 
> Hope that helps 👍 

Thanks @jdwilkin4! Will that one need updates? If so, I'd love to help with that. Lol, I've been wanting to contribute to the curriculum for a while now, but I can't seem to find an issue that I can solve with my skillset. :(

**Comment by CBID2** [comment]
> What do you mean? That project should be done with markdown, instead of HTML + CSS?

Yeah @gikf. I'm pretty much suggesting a change to the lesson
