### ISSUE TITLE
Accessibility mention needing more detail. 

### ISSUE THREAD

**Issue by CBID2** [freeCodeCamp/freeCodeCamp#50749]
### Describe the Issue

Step 18 in the Registration Form Lesson briefly mentions accessibility practices, but merely saying it's accessible isn't enough. I've noticed that accessibility is an "afterthought" in conversations about learning how to code, so briefly explaining the impact of using the `for` attribute and the names provided for the `id` attribute or adding a link to sources like [W3CG](https://www.w3.org/WAI/tutorials/forms/labels/) would help campers gain a better understanding of why they should use this method. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-18

### Your code

N/A

### Expected behavior

N/A 

### System

- Device: Laptop
- OS: mac0s  
- Browser: Chrome 
- Version: 114

**Comment by ShaunSHamilton** [comment]
Hello there,

This is briefly mentioned, because:
1) The _Learn HTML Forms by Building a Registration Form_ focusses on teaching form-related elements
2) Later, there is a [Learn Accessibility by Building a Quiz](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-accessibility-by-building-a-quiz) project
3) These newer-style lessons are designed to be as small as convenient - we intentionally do not continue padding the descriptions out

Hope this clarifies
