### ISSUE TITLE
Can't view profile on FCC - Get 'Oops! Something went wrong. Please try again later'

### ISSUE THREAD

**Issue by codemzy** [FreeCodeCamp/FreeCodeCamp#5077]
Just happened this morning... 

May have been after I did the new Waypoint 'Get set for Bonfires' that has just been added under Basic Algorithm Scripting.

If I click on my profile or points link from the menu I just get 'Oops! Something went wrong. Please try again later' and redirected to /map

I can't get to my profile at all. 

Thanks, codemzy

**Comment by ChaituVR** [comment]
![image](https://cloud.githubusercontent.com/assets/15967809/11656566/160f6fd2-9ddc-11e5-86d2-f4bafa1b5393.png)

same problem with me too... i can't get my profile

**Comment by gasperno** [comment]
I can confirm too. 
I just logged into FCC and on clicking profile or points link in navigation bar, the above message appears.

**Comment by zydecat** [comment]
Same here - I've just finished my first zipline and (I think) since then, I have not been able to access my profile or previous code solutions. I get the same error message as above and redirected to /map. Really annoying because I'd like to review my solutions as a first step, to cobble the code for my next zipline project. I'm having to google solutions now and they are hit and miss...

:-/

**Comment by ltegman** [comment]
Huh. I can't repro this myself, but clearly something is going on here. @BerkeleyTrue could you look into this when you get a chance?

**Comment by codemzy** [comment]
Yeah, it's odd! You can see it as an outsider if you try to view my profile... or any of the others having problems, it doesn't work when not logged in either... e.g. www.freecodecamp.com/codemzy

**Comment by BerkeleyTrue** [comment]
@codemzy Can you try now?

**Comment by codemzy** [comment]
Yes! Working now! Thanks very much! 

p.s. I hope by commenting I don't accidentally re-open this issue :fearful:
