### ISSUE TITLE
 Grammatical error in building a quiz - step 8

### ISSUE THREAD

**Issue by franciscomelov** [freeCodeCamp/freeCodeCamp#50888]
### Describe the Issue

The word "to" is repeated one after the other on the instructions:

Scale the image using its id as a selector, and setting the width **to to** be the maximum of 100px or 18vw.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8

### Your code

```



```

### Expected behavior

it should be: 
Scale the image using its id as a selector, and setting the width to be the maximum of 100px or 18vw.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/17803231/fc1e23dc-54c9-413a-af32-c6efded86eb6)

### System

- Device: [Laptop lenovo]
- OS: [Windows 10]
- Browser: [Chrome]

**Comment by Arsaluddin** [comment]
May I fix this error.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/613e275749ebd008e74bb62e.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by nikhilgarg26** [comment]
Hi, being new to open opensource i would like to resolve this issue.

**Comment by gikf** [comment]
Hey @nikhilgarg26

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Avyukth1C** [comment]
Hi, can I try and close this issue, If the issue still persists.
