### ISSUE TITLE
Cannot link account to Github Account

### ISSUE THREAD

**Issue by luongthomas** [FreeCodeCamp/FreeCodeCamp#5093]
Whenever I click on the Link button to link to my GitHub account, it sends me to a 404 Page saying Page not found.

In my .env file, I've added my Github username as the ID and my password for the GITHUB_SECRET entry in single quote marks.  

Is this a bug or am I missing something?

**Comment by ltegman** [comment]
Have you set your callback for the github application to `http://127.0.0.1:3000/auth/github/callback` and are you accessing the local server with `http://127.0.0.1:3000`?

**Comment by luongthomas** [comment]
I'm accessing the local server

**Comment by luongthomas** [comment]
When I type in `http://127.0.0.1:3000/auth/github/callback ` in the browser it also takes me to the same 404 page

**Comment by SarahtheOutlier** [comment]
Every time I go to log into chat it asks me to link to GitHub and then it kicks me out. I am unable to chat... Sad first day with y'all.

**Comment by ltegman** [comment]
@luongthomas You shouldn't be typing `http://127.0.0.1:3000/auth/github/callback` into the browser, you need to be setting it as your callback URL in the github settings for your application on the github website.

I'm closing this because it is not an issue with Free Code Camp. If you need more assistance getting Free Code Camp running locally please visit the [Help Contributors Chat](https://gitter.im/FreeCodeCamp/HelpContributors).

Thanks and happy coding!

**Comment by valterlima** [comment]
Hello,

I had the same problem. When the github 'Authorization callback URL' is ended with 'auth/github/callback' it doesn't work properly and I get the Mismatch Url error.

I solved it by removing the 'aut/github/callback' on the callback URL.

**Comment by techtolentino** [comment]
@valterlima so are you using `http://127.0.0.1:3000/` in your _authorization callback_?

I'm trying that and I'm still getting a `redirect_uri_mismatch` error.

**Comment by valterlima** [comment]
@techtolentino actually I was using the full URL of my c9 project
