### ISSUE TITLE
No visual feedback when wrong code is submitted.

### ISSUE THREAD

**Issue by tekrondo** [FreeCodeCamp/FreeCodeCamp#5111]
The `Run tests (ctrl + enter)` button in waypoints doesn’t give any visual feedback when the wrong code is submitted. 

It would be nice to have this, especially useful to a novice `Camper`.

**Comment by keponk** [comment]
+1

**Comment by ltegman** [comment]
I don't know what the name would be in web design, but perhaps something like what Android calls a "toast" would be a good option. Something that pops on-screen visibly but unobtrusively when the tests have finished running, but doesn't require user interaction to dismiss, it's just timed to appear for a brief second or two.

**Comment by robertcdawson** [comment]
This definitely presents a problem, especially when error messages fall below the fold. Even when a user can see them, it takes a moment to focus on them given their lower-left position on the page.

However, since the issue isn't that the form lacks visible error handling but, rather, that the errors aren't clearly visible, another solution, which leverages existing error handling, might be to move the error messages below the editor, as shown in the attached screenshot.

![freecodecamp_error_suggestion](https://cloud.githubusercontent.com/assets/1414112/11708707/35a9898c-9ec6-11e5-8d47-2d84098fd86f.png)

**Comment by hellawindy** [comment]
@robertcdawson Good suggestion.

**Comment by hallaathrad** [comment]
@ltegman Some sort of a modal window would do the trick nicely. I'm pretty sure either Bootstrap or jQuery UI may have some gizmo we can use for this

-----
Subscribing :)

**Comment by SaintPeter** [comment]
@hallaathrad I know once we go to React that we will be embracing Toasts (little micro-popups) and they would be ideal for this.

**Comment by terakilobyte** [comment]
There's no reason to wait for React. [Toastr](https://github.com/CodeSeven/toastr) could be used to immediately bring about this effect. Give the demo a shot, they're highly configurable.
