### ISSUE TITLE
CSS child combinator could use better explanation

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51235]
### Describe the Issue

I believe that Accessibility Quiz step 13 is the first time we introduce the CSS child combinator. (I've looked through the finished CSS for all previous courses and have not found it.) The instructions and hint for step 13 merely say to use it but they don't explain what it does or why it is needed. And really, since the only child in the `nav` is the `ul`, and there are no embedded `ul`s in the list items, then it is not obvious why it is needed in the first place. We also require the child combinator in later steps and I am not finding any explanation for it in those steps either.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-13

### Your code

The current instructions for step 13:

> Use the > selector to target the unordered list elements within the nav elements, and use Flexbox to evenly space the children.

The hint if you don't use the child combinator:

> You should use the nav > ul selector.

### Expected behavior

Add additional information to the instructions:

- Give the name of the `>` selector (child combinator)
- Describe what it is used for
- Explain why it is being used in this step

### System

N/A

### Additional context

I don't have any suggested text at the moment, I just wanted to get this issue recorded so I wouldn't forget about it. And to be honest, I'm not sure what the rationale is for requiring the child combinator here. Perhaps we are just using it merely for the sake of introducing a new feature in CSS?

**Comment by lasjorg** [comment]
It would make more sense to introduce the selector in an instance where it is actually needed and with its usage explained.

Having said that I don't mind its use here. It should still be explained, because otherwise, what is really being taught?

The why might be a little harder to explain in this example if it is only done as a coding style choice.

---

Personally, I do think the child combinator is often preferable to the descendant combinator when applicable, especially when using type selectors.

It is more explicit about the location of the targeted element which makes it less side-effect prone (i.e. later targeting elements you didn't mean to as more code is introduced or changed).

It is less work for the matching engine. I believe it was used as a bit of a performance enhancement back in the day, but I doubt it really matters much today in most cases (it might if the DOM tree is big enough).

**Comment by WairimuAbigaelWairimu** [comment]
Alternative explanation for CSS  child combinator step 13:

To select all children elements within the parent elements, we use the `>` selector. In this step, use the `>` selector to target the unordered list elements within the `nav` elements, and use Flexbox to evenly space the children.

**Comment by naomi-lgbt** [comment]
I feel like that's a bit too reductive.

**Comment by bbsmooth** [comment]
I'm happy with Naomi's suggestion. This seems like a good first timer issue if we are done discussing.
