### ISSUE TITLE
fix: move definition of 'color wheel' 

### ISSUE THREAD

**Issue by studiozandra** [freeCodeCamp/freeCodeCamp#51271]
### Describe the Issue

Color wheel concept is introduced in lesson 32, but not defined until lesson 36.
Suggest moving definition of 'color wheel' to where it is first introduced in step 32, remove definition from step 36

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-32

### Your code

```
n/a


```

### Expected behavior

definition of 'color wheel' appearing where it is first introduced in step 32

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/17014512/78947549-6464-4557-af35-38a8dfa7dfd0)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/17014512/85d3e2bc-f080-49cc-b2fe-94e2f144863b)

### System

- Device: [e.g. iPhone 6, Laptop] n/a
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04] n/a
- Browser: [e.g. Chrome, Safari] n/a
- Version: [e.g. 22] 22

### Additional context

advised to open this issue here: [PR 51218](https://github.com/freeCodeCamp/freeCodeCamp/pull/51218#pullrequestreview-1576410981)

**Comment by naomi-lgbt** [comment]
Honestly, I'd argue to remove `, and falls between the two colors on the color wheel` entirely.

**Comment by Programmer-Dost** [comment]
> Honestly, I'd argue to remove `, and falls between the two colors on the color wheel` entirely.

So, should I remove the text mentioned by you?

**Comment by NmN03jain** [comment]
this issue is still open ?

**Comment by Programmer-Dost** [comment]
> this issue is still open ?
> 

Sorry for interruption but I have already created a pull request which is waiting for maintainer's approval.🖐

**Comment by naomi-lgbt** [comment]
This issue is not yet open for contribution.

**Comment by lasjorg** [comment]
I agree, we should just remove the color wheel part.

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. [Step 32](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/617bc3386dc7d07d6469bf20.md)

The text:

> This is because orange is the combination of red and yellow, and falls between the two colors on the color wheel.

Should be changed to:

> This is because orange is the combination of red and yellow.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
