### ISSUE TITLE
fix(e2e-playwright): Add authenticated state checks once Login functionality is setup.

### ISSUE THREAD

**Issue by Ahmadkashif** [freeCodeCamp/freeCodeCamp#51346]
**Describe the bug**
The e2e Playwright integration will need a global job setup to test out web page content for authenticated users. We will need to revisit the spec for learn page, written in Playwright, and test out support for the authenticated user. 

**Expected behavior**
This issue is to track the scenario discussed in PR #51276 . This issue is to be closed once we add login job for playwright, with a very minor refactor in the learn spec file.

**Comment by Ahmadkashif** [comment]
Sure @NextThread.

**Comment by rahulsuresh-git** [comment]
@Ahmadkashif Since this hasn't been picked up yet, I'd like to work on this.
I have a question for you, do you want me to include the test only to check if quotes appear for authenticated users as discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/51276, or should I write all possible tests for the authenticated view?

**Comment by rahulsuresh-git** [comment]
@Ahmadkashif I've added the test for the random quote (authenticated user) here: https://github.com/freeCodeCamp/freeCodeCamp/pull/52449
