### ISSUE TITLE
Misspelling in `cat painting project`

### ISSUE THREAD

**Issue by Andrew-J-Larson** [freeCodeCamp/freeCodeCamp#51438]
### Describe the Issue

Here's the last paragraph in the instructions:

> Instead of static, give you .cat-head a position of relative, and leave both top and left properties as they are.

Notice that where is says "... give you .cat-head..." should actually be "... give your .cat-head ..."

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-10

### Your code

N/A

### Expected behavior

N/A

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/19640692/3e9829ac-0a3c-4669-90a9-8413b0c6f172)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 116.0.5845.111

### Additional context

Didn't see a better way to report a spelling issue directly from the website.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/d4a40c384ce9c29e681baf80c4711cb338c6df7e/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6476f5c17f99146071ee884c.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by jjvemz** [comment]
Can I Contribute on this issue?

**Comment by Drdoofen** [comment]
attempting #51438

**Comment by gikf** [comment]
Hey @jjvemz

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by vishal-phoenix** [comment]
@gikf please check out the update.

**Comment by gikf** [comment]
Hey @vishal-phoenix yout PR is targeting `main` branch of your own fork, not the `freeCodeCamp:main`.

**Comment by vishal-phoenix** [comment]
i think its targeting the right one now.

**Comment by Andrew-J-Larson** [comment]
@vishal-phoenix, of you want to tackle some other grammatical errors I found, I know there is a missing space in a step somewhere, and missing punctuation in another.

I've forgotten where, but I know they both happened prior to this step I reported here, but not before "Learn the CSS Box Model by Building a Rothko Painting". Both were on different steps.
