### ISSUE TITLE
Add validation for progress on C-Sharp Certs

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#51455]
RN,

There is a bit of hoping between the order of things to be done on fCC Learn and MS Learn. Roughly, you need to:

1. Complete a section (block) on MS Learn
   
	<details>
	<summary>Details</summary>

   <img width="794" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/2cf1653e-3907-4afd-950a-c87c83a9a2cb">

	</details>

2. Claim the trophy (last item in each section/block) on fCC Learn
3. Repeat 1-2 for all sections/block.
4. Be eligible for the certification exam.
   
	<details>
	<summary>Details</summary>

   <img width="850" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/51a6c6ef-4f49-4d1b-90cd-637dd23b5146">

	</details>

Solution we need to add more validations in step 4 (and maybe in step 2??):

  - If URL is valid, check user's Microsoft learn account has completed necessary/any modules
  - If not, respond in kind.

_Originally posted by @ShaunSHamilton in https://github.com/freeCodeCamp/freeCodeCamp/issues/51419#issuecomment-1698850070_

**Comment by ShaunSHamilton** [comment]
Are we wanting to do most/all of this client-side?

Is there anything to worry about having the `fetch` requests from the client to MS?

**Comment by raisedadead** [comment]
To the best of my knowledge MS is not doing anything special to ensure requests are made from us specifically, so server-side checks aren't needed?

**Comment by ojeytonwilliams** [comment]
No, but we shouldn't be trusting the client when we don't have to. By verifying on the server we can be sure that the linked user has completed the required MS trophy.

**Comment by raisedadead** [comment]
Last I checked there is literally no way to tell if username `oliver` on fCC is same person on MS. There is NO OAuth based grants involved here. Sure you can move the call to server, but that solves nothing for all practical intents.

**Comment by ojeytonwilliams** [comment]
That's right, but each fcc account can only be associated with a single, valid MS account, which is better than nothing. Not _much_ better, obviously, but better.

**Comment by moT01** [comment]
You need access to the MS account to create the transcript link. We don't know for sure that it's that user, but you would have to intentionally be malicious for it not to be.

> Is there anything to worry about having the fetch requests from the client to MS?

I was getting CORS errors when trying to fetch MS API from our client.

> add more validations in step 4

I'm not sure what else we would add there. We could check their trophies on the server again (call MS API) - but we already did that when they completed those challenges.

I'm also not sure what the focus of this issue is. Let me clarify some of the process a little...

I created `POST /user/ms-username` and `DELETE /user/ms-username` endpoint to link and unlink MS accounts to fCC accounts...

<details><summary>images</summary>

Unlinked account:

![Screen Shot 2023-09-01 at 7 59 18 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/b8de58c1-61d6-4fbe-932c-f1b258e383c8)

Linked account:

![Screen Shot 2023-09-01 at 7 59 43 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/cef87031-ebaf-43cb-901e-51b006f1507d)

</details>

You only need to link your account once. This happens on step 2 - when you want to verify your first trophy on fCC you need to link your account so we can verify it. I think this is the area the original comment is talking about. We want to give better feedback to users about what is going wrong. e.g. maybe "That username is already being used by someone else." or "You have not earned that trophy."

The example in original comment adds server-side validation to the transcript URL. I don't think that's entirely necessary because the call to the MS API will fail if the URL isn't valid. But it doesn't hurt either - I guess we wouldn't have to make the API call if we know the URL isn't the correct format.

So, to clarify my clarification - I think this issue should focus on those error messages. But maybe I'm not understanding what you all had in mind.

**Comment by raisedadead** [comment]
> #### I'm also not sure what the focus of this issue is.

It is precisely what I said in the OP:

> "There is a bit of hoping between the order of things to be done on fCC Learn and MS Learn." 

which IS confusing (corroborated by the issue reports (and me too's), mentions on forum, etc.). To me is a simple UX problem, plain and simple.

Thinking objectively, I believe none of this "needs" any sever side checking at all or why the discussions (and "opinions") need to be about it at all. 

I care about is the end user experience, which IS BAD. I'll defer to you all for a proper fix (unless the UX is acceptable).

**Comment by ojeytonwilliams** [comment]
Okay, so there are two concrete actions:

> If URL is valid, check user's Microsoft learn account has completed necessary/any modules

We do this already.

> If not, respond in kind.

We don't do this adequately. When the user has not completed all the modules we show them a flash message

> We were unable to verify your trophy from Microsoft's learning platform.

Which is true, but doesn't help them out.

A quick fix would be to add a link to https://forum.freecodecamp.org/t/verify-your-trophy-from-microsoft-solution/633660 in the flash message.

**Comment by ShaunSHamilton** [comment]
> A quick fix would be to add a link to https://forum.freecodecamp.org/t/verify-your-trophy-from-microsoft-solution/633660 in the flash message.

I am happy with this solution.

I assume this can only stay whilst the superblock is only offered in English?

**Comment by ojeytonwilliams** [comment]
Yeah, it's just a bandaid, really. If there are no objections, we can go with this and discuss better, more permanent solutions in a separate issue.

**Comment by raisedadead** [comment]
The main task is communicating the user stories for a lesson (as a learning platform). Correct?

If we need support posts and explainers, we have failed at doing the most important thing we are supposed to do. As a user, it would be frustrating for me to jump here and there and figure out problems that are not related to the certification. It's an unnecessary distraction.

Mind that we only see complaints where people are more vocal. Others are just walking away because of the experience and we will never hear about it.

The first task/lesson on certifications should be to acclimatize users on their onboarding needs. This applies to certs we offer on learn natively, the coderoad-based certs., MS learn certs and everything in between.

Anyways,

The action item for this issue should be to let the user know what went wrong with their submission. 

The link is OK - it's a horrible experience though.

**Comment by moT01** [comment]
I do think that the recent changes should help quite a bit with the confusion. We could be more specific in areas - e.g. On the regular challenge pages, instead of "complete all the tasks {MS module}" - maybe...

"Complete the seven {MS module} tasks:

Introduction,
Exercise - Write your first code,
Learn how it works,
Complete the challenge,
Review the solution,
Knowledge check,
Summary"

**Comment by ojeytonwilliams** [comment]
I was thinking about something like that, but had trouble wording it. Maybe something like this:

> Now that you've completed all of the "Write Your First Code Using C#" challenges, you should have earned the trophy for it on the Microsoft Learn platform. If you don't see this trophy when viewing <a href="https://learn.microsoft.com/users/me/achievements#trophies-section" target="_blank" rel="noreferrer">your achievements page</a> you have not completed all the modules in the learning path needed to earn it.
>
> To complete the learning path you must complete the following modules on the Microsoft Learn platform: 
>
> [Write your first C# code](https://learn.microsoft.com/en-gb/training/modules/csharp-write-first/), [Store and retrieve data using literal and variable values in C#](https://learn.microsoft.com/en-gb/training/modules/csharp-literals-variables/), 
[Perform basic string formatting in C#](https://learn.microsoft.com/en-gb/training/modules/csharp-basic-formatting/), [Perform basic operations on numbers in C#](https://learn.microsoft.com/en-gb/training/modules/csharp-basic-operations/), [Guided project - Calculate and print student grades](https://learn.microsoft.com/en-gb/training/modules/guided-project-calculate-print-student-grades/), [Guided project - Calculate final GPA](https://learn.microsoft.com/en-gb/training/modules/guided-project-calculate-final-gpa/)

**Comment by moT01** [comment]
Posting here before I forget - Quincy suggested to "hide things" until a task is complete.

For instance, on one of the regular challenges, we could hide the multiple choice question until campers check a box or click a button that says, "I have completed the tasks on Mircrosoft Learn"

Similarly on the trophy challenges - hide the "Link your Microsoft account" section until they check a box that says "I have earned this trophy on Microsoft Learn"
