### ISSUE TITLE
Issue with Waypoint: Make Unique Objects by Passing Parameters to our Constructor

### ISSUE THREAD

**Issue by SeamlessPi** [FreeCodeCamp/FreeCodeCamp#5145]
I used variables and my code works. But when I use arguments it does not work. What am I doing wrong? Apologies for a question that might not make sense. I am very new to programming and not able to articulate properly. Thanks for your help.
![screen shot 2015-12-11 at 11 24 35 am](https://cloud.githubusercontent.com/assets/15959176/11747625/b2ed01dc-9ffa-11e5-84e8-38cd7b7f9fe9.png)
![screen shot 2015-12-11 at 11 24 46 am](https://cloud.githubusercontent.com/assets/15959176/11747628/b6f750fc-9ffa-11e5-965c-3dddfb5074c3.png)
![screen shot 2015-12-11 at 11 28 47 am](https://cloud.githubusercontent.com/assets/15959176/11747631/be1dae30-9ffa-11e5-8ed2-9a3da9ac1211.png)

**Comment by ltegman** [comment]
This is failing because the object literal at the end of your code is not necessary. The object is only in the sidebar to show you what the object the `Car` constructor makes will look like, but it should not be in your code. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help with challenges rather than filing a bug.

Thanks and happy coding!

**Comment by SeamlessPi** [comment]
Understand regarding chat. Thank-you for prompt response.
