### ISSUE TITLE
Test in Cat Photo Step 12 too restrictive

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#51459]
### Describe the Issue

The test requires an `href` attribute of exactly `https://freecatphotoapp.com`, but the instructions say to use `https://freecatphotoapp.com/`.

Note the trailing slash.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

```
      <p>See more <a href="https://freecatphotoapp.com/">cat photos</a> in our gallery.</p>
      <a href="https://freecatphotoapp.com">link to cat pictures</a>
```

### Expected behavior

The test should not care if the trailing slash is present or not, to be honest. As far as I know, the behaviour for the link would be the same.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

We should change the test to use a regex match on the attribute to make the presence of the trailing slash optional.

Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md

Bonus points to a PR that updates the tests to use specific assert methods, and remove the jQuery.

**Comment by Riya267** [comment]
Hey @naomi-lgbt  FYI I have started working on this

**Comment by lasjorg** [comment]
I would suggest we remove the trailing slash from the example code and instructions as well.

**Comment by Riya267** [comment]
I have removed trailing slash and updating assert methods and and removing the jQuery

**Comment by alikeayush** [comment]
,

**Comment by michaelachrisco** [comment]
Im at a meetup and we just found this issue :) Thanks for addressing it!

**Comment by stokedDev** [comment]
I found out about this problem today while helping someone in the freeCodeCamp forum.
[naomi-lgbt](https://github.com/naomi-lgbt), thank you for opening this issue.
I just tried to use "https://freecatphotoapp.com/" for the anchor element href of the text "cat photos" as instructed by the challenge, and the challenge test error still occurs. 
As of the time I am writing this comment, the url without the forward slash is passing the tests. 
Since it has been more than 3 days and this problem still occurs:
I think the required url in the challenge instructions should be changed to the url without the forward slash. 
I think this fix just requires an html text edit and will make the instructions cooperate with the tests.
If students can just see the url ( in the challenge instructions ) without the forward slash that passes the tests, "https://freecatphotoapp.com", that should be enough.
The url with the ending forward slash is not a clean url anyway.
I mean the url with the forward slash would just take longer to type in the real world, and I doubt it would ever have any advantage ( without additional website navigation text after the forward slash ).
