### ISSUE TITLE
D3 Zipline: Show Relationships with a Force Directed Graph

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5157]
The nature of this D3 Zipline has yet to be determined. Please respond to this issue with ideas.

**Comment by mutantspore** [comment]
Using the Camper news as data for a Force-Directed Graph to show associations between our article posters and the places they post articles from and the interest that that generates within the FCC community.

The Nodes are the authors and the server host names of the articles (actual articles is overkill).
The visualization allows the viewer to see the network of authors and the places they post the articles from. The nodes are sized based on the number of links they have to them. Authors avatar pictures are used as their node. It is also intended that the colour of the server nodes reflect the aggregate of the up-votes for articles on that server. Tooltips reveal the names/servers associated with the nodes.

I have a nearly finished a version on CodePen that I will be trying to finalize in the next day or so.

http://codepen.io/MutantSpore/full/KVdbMO/

for your consideration
Bruce

**Comment by QuincyLarson** [comment]
Hi @mutantspore,

All I have to say is: wow! Awesome idea, and great execution so far. This looks great!

So the user stories would be something like:

1. I can see a Force-directed Graph that shows which campers are posting links on Camper News to which domains
2. I can see each camper's icon on their node
3. I can see the relationship between the campers and the domains they're posting.
4. I can tell approximately many times campers have linked to a specific domain from it's node size.
5. I can tell approximately how many times a specific camper has posted a link from their node's size.

**Comment by mutantspore** [comment]
I was trying to aggregate the up-votes on a server basis and show that as a color scale in the server nodes. What I have done so far with that isn't an aggregate but more of a last one in sort of thing. I want to finish that aspect. You can see a little coloring now though. My array/object manipulation of the news data needs some work for that aspect. I'm just reading a chapter on this type of graph to make sure i'm doing it correctly.  While it has it's issues it should give some idea of how "good" the articles are on a particular server. Of course it could be saying that there are a lot of low grade articles if there are a lot of connections. The connections are the circle size as you've noted.

It has tooltips for the node names also. That could easily display more info but I also feel that there needs to be somethings left for the camper to show off their own skills.

So with a day or so to make sure the color aspect is working and my code is ok (remember I've only had 24 hrs of D3), it should be good to go. There is an official plugin JS file that is in the docs that I was going to use to get a nicely graduated color scale. I haven't found a decent CDN for it, though it is included in the github site of D3. https://github.com/mbostock/d3/wiki/Ordinal-Scales#colorbrewer

Did you try dragging a node about a bit ... looks like it's alive. It actually looks good still and is usable on my iPhone 6+ without any modification. I was surprised.

I'm glad you like it :)

**Comment by QuincyLarson** [comment]
Yes - I think adding the color element to show the volume of upvotes is yet another useful visualization of data. 

I enjoyed dragging the nodes around and re-arranging this. This is definitely going to be a fun Zipline!

D3 is pretty amazing, eh?

Please take your time - I will record the video and add the challenges to the map once we have all 5 D3 challenges and their user stories confirmed, which should probably Dec 28 or so at the latest. 

Keep up the hard work, and if you feel your done, please feel free to dive into creating another visualization.

Best,

Quincy

**Comment by mutantspore** [comment]
:)  I'd be happy to try another.

It's done except for deciding on exactly how to represent the up-votes.

I have implemented it so that we can alter the way it's done by changing one word once we decide.
the up-votes for a server could be the:
`min`
`max`
`mean`
`median`
`sum`
of the up-votes.
After thinking about it and looking at the results of those and what they "tell" me as a user, I have decided to show the up-votes for the `max` up-voted article on a server. The `mean` is a killer as you could have 2 articles, one with 75 and the other with 8.. . or the `sum` is worse as you could have 10 articles with 7 votes . So I went for the votes of the most loved article.

But as I said .. it's 2 secs to change it as I have all the up-votes for a node in a rank array in the node object and D3 lets me do operations on that very easily.

The only other thing is that I've used the D3 `colorbrewer.js` plug-in to get the Orange color scale for the up-votes. 
It's in the github site for D3. 
https://github.com/mbostock/d3/tree/master/lib/colorbrewer
https://github.com/mbostock/d3/blob/master/lib/colorbrewer/colorbrewer.js

I've just pasted it in to my JS in CodePen as I couldn't see a CDN that actually worked (some claim to but...)

Ok the app is at the same place as before. I've had a bit of a fiddle with the aesthetics, colors etc. I've set the "graph" size at 850 x 850 pixels. it fits ok on a HD desktop screen though as I said it works well on my iPhone too. 

Let me know what to do next :) 

thanks again for the opportunity to participate.
Bruce
