### ISSUE TITLE
D3 Zipline: Interactive Scatterplot

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5158]
The nature of this D3 Zipline has yet to be determined. Please respond to this issue with ideas.

**Comment by cdikibo** [comment]
Claiming this data viz zipline.

**Comment by SaintPeter** [comment]
@cdikibo Please describe what you intend to do with it.  We can't just have people calling "dibs" without some sort of description of what they intend to do.

**Comment by cdikibo** [comment]
@SaintPeter Sorry for my "dibs" behavior. 

My original idea has been scrapped after the only way to get my dataset was to use XPath and Selenium AKA things that FCC is not about. My scrapped idea consisted of using chlorpeth map to visualize people killed by police. It was going to have user stories to highlight when searched by different cats eg gender. Plus it was going to have bottom that would pick random dataset, highlight it, give a name to that dataset and a link to an article. 

Since there's already D3 Zipline using a map. I will come back with a new dataset(user stories with codepen link) that I will visualize in a non-map way.

**Comment by QuincyLarson** [comment]
@cdikibo OK - sounds good. Thanks for the further clarification. Please keep us posted on how this is coming along, as January 1 is fast approaching.

**Comment by cdikibo** [comment]
I have decided on an interactive scatterplot for this zipline.   I hope that choice adds to the diversity of the D3 ziplines as a whole.

**Comment by QuincyLarson** [comment]
@cdikibo Great! I agree - this will be a nice addition, since scatterplots are a staple form of data visualization :)

**Comment by AdventureBear** [comment]
I also have a scatterplot I'm working on, I'll post the link here when it's reasonable to review and you guys can see what you think.

**Comment by AdventureBear** [comment]
Here is my mostly finished scatterplot!   If it works for the curriculum great, if not I learned a lot while doing it and am a little better at D3 now than I was before. 
http://codepen.io/AdventureBear/full/jWrbqB/

**Comment by AdventureBear** [comment]
Like I had mentioned in the chat room, I think an idea of showing a camper one to three types of examples for each visualization (scatterplot) in this case could be helpful, but I'm not sure if that fits the current curriculum model. If cdikibo's zipline is used for the curriculum, mine could be used as an example during the instructive portion perhaps, or vice versa.   I didn't want to step on anyones toes, but I had already been working on this one since discovering the existence of the data and brainstorming about D3 projects for FCC.

**Comment by SaintPeter** [comment]
I think it looks fab!  It just needs a legend or something so we can understand what it means to those of us who are not bike racing fans.

**Comment by AdventureBear** [comment]
Thanks, I'll add that tomorrow.  select.append.circle...

**Comment by QuincyLarson** [comment]
Hi @AdventureBear,

Could you add the legend and link me to your dataset? We'll host it.

This looks amazing.

I'd like to start recording videos tomorrow :)

**Comment by AdventureBear** [comment]
Yes I'll do all that, I'm just updating my JSON file so it's more accurate with the variation of the distances normalized.  It changes the order of the finishers a bit.

**Comment by AdventureBear** [comment]
here's a gist of the updated data file 
https://gist.github.com/AdventureBear/b616fd2a5c3e58e19999

**Comment by AdventureBear** [comment]
otherwise it's pretty done, with exception to tinkering with the tooltip, but I think this is "good enough"

**Comment by QuincyLarson** [comment]
@AdventureBear excellent! I'll upload the dataset and update the import path on the official codepen fork of this! Thank you so much for your hard work on this.
