### ISSUE TITLE
React challenges throwing "Potential infinite loop detected" error

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#51656]
### Describe the Issue

I only checked a few but it seems like anything with a state update (inputs, buttons, etc.) throws this. You can pass the challenges with the correct code but any interaction with the page that triggers a state update seems to throw this error.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/write-a-simple-counter  https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-controlled-input  https://www.freecodecamp.org/learn/front-end-development-libraries/react/use-advanced-javascript-in-react-render-method

### Your code

```



```

### Expected behavior

Valid passing code shouldn't crash the challenge page when interacting with the rendered page.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Just saw this as well. Forum: https://forum.freecodecamp.org/t/fcc-solutions-are-crashing-the-render-frame/640546

**Comment by moT01** [comment]
I can confirm this. It seems to have been [introduced on this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/51542) - I revert that and it worked. I added `disableLoopProtectPreview` in the `meta.json` of the react challenges (similar to what's in that PR) and it fixed it - so I think that's what we need to do. We will also want to add that to the `react and redux` meta file since some of those challenges seem to have the same problem. [This one](https://www.freecodecamp.org/learn/front-end-development-libraries/react-and-redux/extract-local-state-into-redux), for instance - probably others.

**Comment by ojeytonwilliams** [comment]
Thanks for the report and discussion, I've created a PR to fix this. I went with making the loop-protection more forgiving, rather than removing it entirely. That way this issue goes away, but recursive renders don't crash the user's browser.
