### ISSUE TITLE
Sharing short URLs for article/news pages

### ISSUE THREAD

**Issue by mibijoy007** [freeCodeCamp/freeCodeCamp#52036]
### Is your feature request related to a problem? Please describe.

Whenever I am reading any article and I want to share that , there is no option.

I had to copy the 'long' url  and the share the url. 

### Describe the solution you'd like

It will be really helpful if the (news) pages has the "share" option like 'youtube' where if we click the "Share" button a '**short**' url pops up. And we can share easily

### Describe alternatives you've considered

Also social options would be nice

### Additional context

My main concern is the very **long** links. This is annoying. 

I love FreeCodeCamp and use it almost everyday.  So a short url would be helpful to share any specific article

Thanks

**Comment by Harshsharmaa28** [comment]
@mibijoy007 i can work on this looks intresting can you assing me

**Comment by Anushri-Rawat** [comment]
I would like to work on this issue,can u assign this to me

**Comment by XD-Admin07** [comment]
it's interesting, I can do it, could you assign me, please?

**Comment by raisedadead** [comment]
Hi @mibijoy007 

Thanks for requesting this, we discussed this and decided against short-links at the time owing to need for maintaining additional resources (domains, servers, maintenance) etc. 

Since we are tiny team with limited resources we can only prioritize features that we think make significant impact to our campers and supporters :)

Hope this is understandable.

Happy coding!
