### ISSUE TITLE
FourOhFour page appears to re-render on click

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52205]
### Describe the Issue

The FourOhFour page displays a random quote every time it mounts/renders:

https://github.com/freeCodeCamp/freeCodeCamp/blob/16e7a04a990a309128f3898f9d06a39d4369451e/client/src/components/FourOhFour/index.tsx#L13-L15

But it's interesting that the component re-renders when the user clicks anywhere on the page, resulting a new quote each time:

https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/f017d667-6df1-4355-803d-c812d1d3e538

We get the same behavior when the user focuses on the search box using keyboard:

https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/06c6213e-1caf-4241-a38f-3373c0eb5e47

---
This behavior was discovered in https://github.com/freeCodeCamp/freeCodeCamp/pull/52054#discussion_r1377046240, and I'm creating this issue to check if this is a bug or a feature 😆 

I think this has something to do with how Gatsby loads the page or passes props to the page (which causes the re-renders), but I'm not experienced with it enough to investigate. 

A "fix" for this is to use `useRef` to save the original quote:

```tsx
const FourOhFour = () => {
  const quoteRef = useRef(randomQuote());

  return (
    <div>
      <p>{quoteRef.current.quote}</p>
      <p>{quoteRef.current.author}</p>
    </div>
  )
}
```

This makes the page less funky (well, only if we consider this a bug) but it isn't a proper fix as the component still re-renders on any user interaction behind the scene.

### Affected Page

https://www.freecodecamp.org/not-found

### Expected Behavior

- The page shouldn't re-render when clicked or when the search box is focused.
- The random quote should remain the same when the page is clicked or when the search box is focused.

**Comment by ojeytonwilliams** [comment]
Thanks for the detailed writeup, @huyenltnguyen. I don't have much to add, but I can confirm that this is not intended behaviour.

As for the fix, I agree that it should not be re-rendering on click, but I think it's also worth making the quote stable between renders.

`useRef` should work, but I think `useEffect` is more idiomatic (since we do actually want to render `quote` and changes to it should trigger renders... even though we have no intention of doing so!).

**Comment by Sboonny** [comment]
Just for context: adding a `path` to the `FourOhFour` component will give gatsby enough context to stop the re-render. https://github.com/freeCodeCamp/freeCodeCamp/blob/16e7a04a990a309128f3898f9d06a39d4369451e/client/src/pages/404.tsx#L18

**Comment by ojeytonwilliams** [comment]
Yeah, that's the source of it. It could be because we're using an old version of redux, but the issue is that any change to the state triggers a re-render. Even if the change is just that a new state object (even one with exactly the same properties and values) is used.

https://github.com/freeCodeCamp/freeCodeCamp/blob/135812162e9938633ec6e3784bf1c5e25335c2c6/client/src/components/search/redux/index.js#L35-L38

is what we have right now and

```ts
    [types.toggleSearchFocused]: (state, { payload }) => {
      const focussed = state.isSearchBarFocused;
      return focussed === payload
        ? state
        : { ...state, isSearchBarFocused: payload };
    },
```

fixes it.
