### ISSUE TITLE
Registration Form Step 12 is not case insensitive

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52375]
### Describe the Issue

The tests will not allow the value "POST" to pass. It will only pass if the value is "post".

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-12

### Your code

This does not pass:

```
<form action='https://register-demo.freecodecamp.org' method="POST">
    </form>
```

### Expected behavior

The `method` attribute and its values are [case insensitive](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method), so the tests should allow any form of capitalization (or lack thereof) to pass. I have tested and they do allow `METHOD` to pass, they just don't allow `POST` to pass.

### System

N/A

**Comment by Asifdecoder** [comment]
It is actually not working the issue highlighted is correct as I have examined here is the screenshot of it.
![Screenshot from 2023-11-17 14-39-14](https://github.com/freeCodeCamp/freeCodeCamp/assets/47385309/7e65e5dc-663a-4500-989b-bd66f0fba7e0)

**Comment by bbsmooth** [comment]
@Asifdecoder Did you not believe me :slightly_smiling_face:

**Comment by Asifdecoder** [comment]
> @Asifdecoder Did you not believe me :slightly_smiling_face: 

I believe you, I was fixing the issue on local machine just was waiting for its availability for the contribution of the issue.

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. [Registration Form - Step 12](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/63541ef4f96cd82e8e6c788a.md)

A PR which resolves this issue should update the assertion statement in the tests to allow for any case variation of `post` to pass. The best approach is probably to use an `assert.match()` and a case-insensitive regular expression.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Aravind1505** [comment]
@naomi-lgbt Hey naomi, I am a first timer, can i contribute to this issue?

**Comment by NalinDalal** [comment]
hi, was looking to start the contribution, if this one I solve it would be my first contribution. Please assign me this one

**Comment by neuronCoder** [comment]
Hi, a first-timer contributor here. I wish to contribute to this issue. I have a question: how do I run this on my local to know whether my fix works or not?

**Comment by neuronCoder** [comment]
Hi @naomi-lgbt @moT01 , 

The approved PR for this issue (https://github.com/freeCodeCamp/freeCodeCamp/pull/52418) raised by @AnmolDh allows for user to successfully enter strings like PoSt or pOst. Do we want to allow users to do this?
