### ISSUE TITLE
Nutrition Label Step 55 unclear instructions

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52376]
### Describe the Issue

The instructions do not state clearly where the new `p` element should be added. I believe they are relying on the fact that the previous two steps added a `p` element to the end of the `.daily-value` div and thus they assume the user will continue this trend in step 55. But I just ran into a forum post that added the `p` element after the `.daily-value` div, so I'm not sure that's a safe assumption.

Step 54 tells the user to add the `p` element "Below your last `p` element" and I think we should do the same thing here.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-55

### Your code

N/A

### Expected behavior

Change the beginning of the instructions to read:

"Below your last `p` element, add another `p` element with the text..."

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Asifdecoder** [comment]
Yes, you're correct. The phrase "so to have it aligned to the left" can be revised to "to have it aligned to the left" for a better concise expression.

**Comment by Asifdecoder** [comment]
When will be waiting for triage label removed

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. [Nutrition Label - Step 55](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f7ecb09de9a938ef94756.md)

A pull request which resolves this issue should:
- [Update the first sentence in the challenge description](https://github.com/freeCodeCamp/freeCodeCamp/issues/52376#issue-1998280628)
- [Fix the typo in the final sentence of the challenge description](https://github.com/freeCodeCamp/freeCodeCamp/issues/52376#issuecomment-1815906523)

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ArvindParekh** [comment]
Hi, do you think the sentence could be made more effective by removing the redundant phrase 'span element' that occurs twice in the same line?

```diff
--- Also add an additional span element to wrap the Total Carbohydrate 37g text in a span element to have it aligned to the left, and 13% to the right.
+++ Also add an additional `span` element around the `Total Carbohydrate 37g` text, to have it aligned to the left, and `13%` to the right.
```

**Comment by ArvindParekh** [comment]
Agreed. Two commas seem to break the sentence unnecessarily.
I already raised a PR (#52420) suggesting the removal of the redundant `"in a span element"` part, which was not merged. Should I push changes in the same PR, or create a new one?
