### ISSUE TITLE
Accessibility Quiz step 46 should accept multiple valid CSS selectors

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#52410]
### Describe the Issue

Multiple CSS selectors are valid for this challenge, but only `li > a` passes the tests.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-46

### Your code

```css
nav > ul > li > a {
  color: #fff;
}
```

### Expected behavior

My code passes the tests.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Edge
- Version: 119

### Additional context

Since the provided answer for the previous challenge is `nav > ul > li`, the logical answer for this challenge should be `nav > ul > li > a`. But it's not accepted.

**Comment by justpingme** [comment]
Hi, Can i start look into this issue?

**Comment by naomi-lgbt** [comment]
The challenge specifically says `Change the font color of all the anchor elements within the list elements`. The selector `li > a` does that. The selector `nav > ul > li > a` **also** does that, but only because the list items are only present in the nav bar.

We also run into the issue of "how do we allow every selector" - in this case, we likely only want to allow the `li > a` selector and the instructions should be updated to specify that.
