### ISSUE TITLE
Role Playing Game: Move initial JS steps to the front

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52667]
### Describe the Issue

Having 16 steps of boilerplate HTML before you even get to any JS seems a bit much.

Why not move steps 2 to 17 to before step 30 when the DOM content is needed?

1 > 17-29 > 2-16 > 29-end

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-1

### Your code

```



```

### Expected behavior

Not spending so much time writing HTML before the initial JS intro. 

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> Having 16 steps of boilerplate HTML before you even get to any JS seems a bit much.

That's fair.

I think the original assumption was that campers would just move through those first 16 steps pretty quickly since it is basically review from the responsive web design curriculum.
But we don't want people to feel like they are never going to get to the javascript portion so a re organization like you suggested makes sense to me.

I will add a discussing label on this to see if any other members of the team want to weigh in

**Comment by naomi-lgbt** [comment]
The intent behind this design was:

- Have campers write the HTML they'll be specifically using, so they can connect the dots later
- Then keep them entirely focused on JavaScript, so they aren't bouncing back and forth between that and HTML during their first experience with the language

**Comment by lasjorg** [comment]
In my opinion, considering this is the first introduction to JS, there are too many steps before they get into the JS.

1. Baseline introduction to JS. Unrelated to anything in the DOM.
2. Add the DOM content needed, possibly even on a per-step basis.
3. Connect the JS to the added DOM content.

As a beginner, by the time you get to step 17, you will not remember what you added in step 5 and will have to refer back to the HTML anyway.
