### ISSUE TITLE
RPG Step 162

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52671]
### Describe the Issue

No need to use `let` here since the array is not re-assigned in later steps.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-162

### Your code

```
let numbers = [];
```

### Expected behavior

We used `const` for other arrays in this project that aren't reassigned.

### System

All

**Comment by adamresemius** [comment]
Hello, I fixed this by doing the following:

1) went to [metadata](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/learn-basic-javascript-by-building-a-role-playing-game/meta.json)

2) found the ID of step-162 (62aa2626c3c10244b94c787b)

3) went to the repositories code and searched for the markdown file through ID.

4) Branched the markdown file 

5) Updated the markdown file to use 'const' instead of 'let' 

![Screenshot 2023-12-21 030007](https://github.com/freeCodeCamp/freeCodeCamp/assets/103894466/b8668b54-d27d-48c3-8f6b-df7132c9607a)

After this commit is approved, this should be able to be closed.

**Comment by jeremylt** [comment]
All of the seed code for subsequent challenges would also be changed. And the test may need to change.

**Comment by adamresemius** [comment]
@jeremylt I am not sure what you mean by this. Is there anything I can do to learn this? 

Are you referring to all references of 'let' initialization to be changed to 'const' in future steps?

**Comment by jeremylt** [comment]
Not quite - the answer to this step becomes part of the starting code for all future steps. If we change the instructions to use `const` here, then then starting code on all future steps needs to be swapped to reflect that.

**Comment by altsun** [comment]
Hi, I raised a PR https://github.com/freeCodeCamp/freeCodeCamp/pull/52857 to fix this
