### ISSUE TITLE
[New JS projects] Interactive elements are having focus outline set to `none`

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52709]
### Describe the Issue

(Hey Bruce, don't look.)

I went and audit the new JS projects after I saw #52701, and found that we have focus outline removed in a couple more places.

- Pokemon Search:
  - Search button in the demo: https://pokemon-search-app.freecodecamp.rocks/
- Roman Numeral Converter:
  - Input and button in the demo: https://roman-numeral-converter.freecodecamp.rocks/
- Number Sorter:
  - Sort button: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-1

### Expected behavior

Remove the `outline: none` rule in the following places:

```[tasklist]
### Pokemon Search
- [x] https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/pokemon-search-app/public/styles.css#L89 - https://github.com/freeCodeCamp/demo-projects/pull/558
- [x] `#search-button` in https://github.com/freeCodeCamp/freeCodeCamp/blob/33933a23693cf3fa41c34d69fa0603c5f714d6a9/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-pokemon-search-app-project/build-a-pokemon-search-app.md#--solutions-- - #52728
```

```[tasklist]
### Roman Numeral Converter
- [x] https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/roman-numeral-converter/public/styles.css#L85-L86 - https://github.com/freeCodeCamp/demo-projects/pull/558
- [x] https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/roman-numeral-converter/public/styles.css#L90 - https://github.com/freeCodeCamp/demo-projects/pull/558
```

```[tasklist]
### Number Sorter
- [ ] `button` in the CSS seed code: https://github.com/freeCodeCamp/freeCodeCamp/tree/33933a23693cf3fa41c34d69fa0603c5f714d6a9/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter. Note that the change needs to be applied to all steps.
```

**Comment by mmatsumoto1026** [comment]
After removing `outline: none;`, especially in Pokemon Search, even though the default outline is displayed when either the input or the button is focused, it may be difficult for people who is visually impaired or have low vision to discern.

After reading "[Success Criterion 2.4.7](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)" and "[Using an author-supplied, visible focus indicator](https://www.w3.org/WAI/WCAG21/Techniques/general/G195)", should we show outline around the input and buttons when it has focus, with css code like below?

```css
input:focus, 
button:focus {
  outline: 3px solid #198eee;
}
```

**Comment by bbsmooth** [comment]
@mmatsumoto1026, you are correct, the default focus outline is often not adequate. Technically, if you rely on the browser default (in other words, you make absolutely no CSS changes to the focus outline) then you are satisfying WCAG. But realistically, it is usually better to customize the focus outline to ensure it is always easily visible with the color scheme being used.

I have no objection to customizing the focus outline, but I would recommend we use `:focus-visible` instead of `:focus`. All browsers today use `:focus-visible` for the default focus outline, so I think we should stick with that as well.

But if the only thing we do is get rid of `outline: none` that's fine. At least I will be able to sleep at night again.
