### ISSUE TITLE
RPG( JS ) Step 41 - Issue with checking 

### ISSUE THREAD

**Issue by slayeh17** [freeCodeCamp/freeCodeCamp#52814]
### Describe the Issue

The regex used for checking this step does not have a check for ```;```.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-41

### Your code

```
function goCave() {
  console.log("Going to cave.")
}
```

### Expected behavior

It should give a hint if the ```;``` is missing, and not accept the answer.

### Screenshots

![Screenshot_20231229_111949](https://github.com/freeCodeCamp/freeCodeCamp/assets/104914725/d7b0ec84-208f-4760-bf04-c21fdc6d5396)

### System

- Device: Laptop
- OS: Fedora 39
- Browser: Firefox
- Version: 

### Additional context

The fix is to change the current regex ```/console.log\(('|")Going to cave\.\1\)/``` to this one ```/console\.log\(('|")Going to cave\.\1\);/```

I also found the same issue on [Step - 42](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-42). There might be more of these issues later in the course, as I have not reached that far into it.

**Comment by gikf** [comment]
Thank you for reporting this issue.

Whether it can be discussed if it's good idea to omit semicolons in JavaScript, it's not required to always add them by hand. What's more JavaScript can add them automatically if needed. Because of that both versions are valid.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
