### ISSUE TITLE
How to Use package.json add instructions for Live App

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#52810]
### Describe the Issue

I kept getting an error "package.json should have a valid “author” key" when linking to my replit as I was used to doing with Python lessons. I found the solution in the forum was to launch the live app and link to that:
https://forum.freecodecamp.org/t/package-json-must-have-a-valid-author-key/470404/4

It seems this has happened a lot "A lot of people new to the backend challenges ran into the same issue when using replit for the first time." https://forum.freecodecamp.org/t/test-failed-package-json-should-have-a-valid-author-key/485606/3?u=pkdvalis

I think it would be great to just add this instruction at the end so it's clear.

`If you are using Replit, click Run to launch the Live App. 

Then, click the "New Tab" button in the Webview window 

Copy and paste the URL of the new tab as the Solution Link`

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package

### Your code

```
{
  "author": "pkdvalis",

```

### Expected behavior

Make it more clear how to submit the answer

### Screenshots

![Screenshot 2023-12-28 151345](https://github.com/freeCodeCamp/freeCodeCamp/assets/79821659/d105c83c-0b12-4d90-a452-be58bf544862)

### System

- Device: Laptop
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
Hey @pkdvalis ! 

I agree that the directions could mention how to submit the live replit link since it does come up a lot on the forum.

> Then, click the "New Tab" button in the Webview window

> Copy and paste the URL of the new tab as the Solution Link

We should avoid updating the directions that include literal matches to the button text because Replit has updated its UI a few times and the "New Tab" button text might not be there if they update again.
As you can see in a screenshot from a forum post from a year ago, the button just showed the new tab icon without the text
https://forum.freecodecamp.org/t/how-to-post-solution-link/526760/3

Maybe the direction could say "Once the application is running, submit this live Replit URL: https://boilerplate-npm.USER-NAME-GOES-HERE.repl.co/ "

I have opened this up for discussion so the other maintainers and mods can add their two cents on updates to wording before we open this up for contribution 👍

**Comment by ShaunSHamilton** [comment]
> Maybe the direction could say "Once the application is running, submit this live Replit URL: https://boilerplate-npm.user-name-goes-here.repl.co/ "

The issue with this, is the replit username is not always the same as the URL. I.e. when users have special characters in their usernames, it changes the URL. _We have had issues with this in the past_

I know _certain accessibility experts amongst us_ dislike this, but we do have the example Replit URL as placeholder text. So, I do not think adding it again to the description adds much.

I think it is best we mention **"preview window URL"** somewhere in the section about Replit.

**Comment by pkdvalis** [comment]
> we do have the example Replit URL as placeholder text. So, I do not think adding it again to the description adds much.

It's the first lesson using the Live Webview, so it's not really clear what that URL is. The Webview Live URL is also not even visible in the page the learner will be working from.

Maybe something like this where we let them know to run and submit the Live Webview URL as the solution link:

>If you are using Replit, click Run to launch the Live App. Open the Webview frame in a new tab and paste that URL as the Solution Link

I would suggest that note be as close as possible to the Solution Link field, since it will be most visible and relevant there. It makes sense to group it with the other Replit notes, I just think people might forget about it when they are ready to submit the solution. There is multiple paragraphs of text after this.

We could omit this sentence: `When you are done, make sure a working demo of your project is hosted somewhere public. Then submit the URL to it in the Solution Link field.` because this seems to be interpreted as just submitting the Replit source code link.

Hopefully this also works for _certain accessibility experts amongst us_ ?

**Comment by jdwilkin4** [comment]
> We could omit this sentence: When you are done, make sure a working demo of your project is hosted somewhere public. Then submit the URL to it in the Solution Link field. because this seems to be interpreted as just submitting the Replit source code link.

I think this note applies to if you weren't using replit for these challenges and submitting the live link. But personally, I think if campers aren't going to use replit, it is just easier to submit the localhost link instead of bothering to host the project somewhere. 

But otherwise, I think the changes you suggested make sense. We should just update this to mention the preview window URL like mentioned earlier

```md
If you are using Replit, click Run to launch the Live App. Open the Webview frame in a new tab and paste that preview window URL as the Solution Link
```

**Comment by naomi-lgbt** [comment]
Opening this up for contribution using Jessica's suggestion above.
