### ISSUE TITLE
Conflicting hint with the instruction

### ISSUE THREAD

**Issue by RockyPukar1** [freeCodeCamp/freeCodeCamp#52863]
### Describe the Issue

The instruction is saying to using variable name as right_array. But the corresponding variable name just before right_array was left_part.

If we use the variable name right_array, it says the variable name should be right_part which is valid hint. But the instruction is wrong.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-5

### Your code

```
right_array = array[middle_point:]
```

### Expected behavior

The instruction should say to make the variable name right_part

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/98908559/37a22bae-9dc9-43ac-926e-3f33aa927da3)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [PopOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This issue is fixed in #52836. This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase. This means that the next time we push to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
