### ISSUE TITLE
RPG step 172: Don't use indexOf to test for true/false

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52898]
### Describe the Issue

I don't think we should be teaching the use of `indexOf` as we are in this step. It is fine if the index is needed but if you only need a true/false I would suggest it should be using `includes` not `indexOf`

---

As an aside, an if statement is not an expression as it is called in this step. I'm pretty sure I have seen this in other steps as well, I will try to look for it so we can correct it.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-172

### Your code

```



```

### Expected behavior

Using `includes` seems like the proper method to use here, not `indexOf`

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
That sounds like a good change to me 

Any thoughts on the updated description before we open it up for contribution?

# --description--

The `.includes()` method determines if an array contains an element and will return either `true` or `false`.


```js
const numbersArray = [1, 2, 3, 4, 5]
const number = 3

if (numbersArray.includes(number)) {
  console.log("The number is in the array.")
}
```

Inside your `if` statement, check if the `guess` is in the `numbers` array using the `.includes()` method.

**Comment by jdwilkin4** [comment]
Also, after some research, it looks like the `indexOf` method doesn't come up again until the music player project.
So we will need to create an issue to properly introduce that 👍

**Comment by lasjorg** [comment]
I like what you have for the description.

---

Step 36 in the music player project looks like a much better time to introduce `indexOf`. Not sure if we need an extra step, some of the text in that step looks a bit superfluous so maybe we can shorten it to make room for `indexOf` to be introduced.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-36

**Comment by jdwilkin4** [comment]
I have created a new issue for introducing the `indexOf` method in step 36 of the music player project. I left my thoughts on how to break it up into two steps

**Comment by jdwilkin4** [comment]
# Note to Contributors 

This issue has been opened up for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

You will need to update step 172 to teach the `includes` method instead.
Please use the description [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/52898#issuecomment-1874829674)
You will also need to update the tests and the seed code for the remaining steps to use the `includes` method instead of the `indexOf`

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Happy coding!
