### ISSUE TITLE
Bugs in Roman Numeral Converter

### ISSUE THREAD

**Issue by wisnuops** [FreeCodeCamp/FreeCodeCamp#5298]
9. Intermediate Algorithm Scripting > 3.Bonfire: Roman Numeral Converter

Looks like it doesn't work with global variable, for example when I define:

    `var roman = [];`

and then have 4 functions processing it (`getThousands(n)`, `getHundreds(n)`, `getTens(n)`, and `getOnes(n)`).

It works on my local computer, but, it doesn't work on FCC.

I deleted the global variable and pass the variable through the functions input (using `getThousands(n, roman)`, `getHundreds(n, roman)`, `getTens(n, roman)`, and `getOnes(n, roman)`) and somehow it works.

**Comment by ltegman** [comment]
This is not a bug with Free Code Camp. Using global variables for function specific storage (and generally) is bad practice because the second time the function runs it is starting with a 'dirty' variables rather than a freshly initialized one. If you call your function twice in a row on your local system you'll find that the value you get returned the first time is not the same as the value you get returned on the second time.

Thanks and happy coding!

**Comment by wisnuops** [comment]
I asked this on the chat (gitter) before and someone there said it is okay to use global variable in Free Code Camp Bonfire.

Thanks a lot for the explanation.

**Comment by SaintPeter** [comment]
Don't know who said that on main chat, but I can tell you that a lot of bugs have been caused by have been caused by having global variables.  The more typical scenario is to forget a `var` and have the variable end up being global accidentially.
