### ISSUE TITLE
ToDo project - remove unnecessary instances of aria-label

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52981]
### Describe the Issue

The task says

> Set the `innerText` of the `addOrUpdateTaskBtn` button to `Update Task` and its `aria-label` to `Update Task` as well.

The step is looking for users to do `addOrUpdateTaskBtn.ariaLabel = "Update Task";`, but the Step says `aria-label`. Do we mention somewhere that you set the `aria-label` of the HTML by changing the `ariaLabel` property of the DOM element?

We do have the error message of

> You should set the `ariaLabel` of the `addOrUpdateTaskBtn` button to `Update Task`

but that's not clear to all users.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-43

### Your code

```
  addOrUpdateTaskBtn.innerText = "Update Task";
  addOrUpdateTaskBtn.ariaLabel = "Update Task";
```

### Expected behavior

Clear instructions

### System

All

**Comment by jdwilkin4** [comment]
> Do we mention somewhere that you set the aria-label of the HTML by changing the ariaLabel property of the DOM element?

The music player project first teaches updating the aria label.

But it couldn't hurt to update the instructions

**Comment by jeremylt** [comment]
Good to know its covered previously. There was some confusion (seen 3 people today) over that who picked something syntactically valid off the internet that wasn't what the tests were expecting.

**Comment by jdwilkin4** [comment]
I am looking at the final [solution](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-84) in the music player more closely and we teach them to use `setAttribute`.

I was under the impression that we taught this syntax. `addOrUpdateTaskBtn.ariaLabel`. I didn't realize we switched it up on them in this project. 

In this case, I vote we update the tests to accept both valid answers but then update the directions to look for ` addOrUpdateTaskBtn.setAttribute("aria-label", "Update Task")` since that is what we taught them to do earlier.

**Comment by jeremylt** [comment]
Ah yeah, that was what I kept seeing, and I was surprised it was so different from the intended solution.

**Comment by jdwilkin4** [comment]
# Note for interested contributors 

An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Change that need to be made
Please make the following changes outlined here
https://github.com/freeCodeCamp/freeCodeCamp/issues/52981#issuecomment-1879271309

Also, this issue requires updating the seed code for steps 44 through the end to use this solution `addOrUpdateTaskBtn.setAttribute("aria-label", "Update Task")` instead of `addOrUpdateTaskBtn.ariaLabel = "Update Task";`

**Comment by bbsmooth** [comment]
Please allow me to throw a wrench in here. This button already has text associated with it, the text "Update Task" between the opening and closing `button` tags. That is all that is needed to give the button an accessible name. Using the `aria-label` attribute here is unnecessary and redundant and is considered an accessibility anti-pattern. And I'm seeing `aria-label` being used unnecessarily on the "Cancel" and "Discard" buttons in the unsaved changes modal, and on the "Add Task" button.

Personally, I'd vote that we remove these unnecessary `aria-label`s completely. Is it the worst thing in the world if we leave them? No. But since it's happening on so many buttons I fear it gives the impression that you always need to use `aria-label` when in fact you should only use it as a last resort. Also, since a few of the buttons aren't using `aria-label` (such as "Add New Task", "Edit", and "Delete") then I think it creates confusion about why some do and some don't, and we don't have a good explanation for that even if we wanted to try and explain it. The only buttons I see that can justify the use of `aria-label` are the "Close" buttons since they are using an icon instead of text.

**Comment by jdwilkin4** [comment]
Thanks for the reply @bbsmooth 

Since this is going to require some more changes I have assigned it to myself and will remove the instances of the aria label in both the html and JS files tomorrow 👍

**Comment by bbsmooth** [comment]
Awesome @jdwilkin4. Honestly, I wasn't expecting anyone to take me up on my suggestion. I do have a tendency to get a little excited about accessibility, so thank you for humoring me.
