### ISSUE TITLE
fix tests for step 96 of platformer game

### ISSUE THREAD

**Issue by RodrigoHLC** [freeCodeCamp/freeCodeCamp#53019]
### Describe the Issue

Previous challenges only worked if the single parameter used for .map() and other types of methods was wrapped in parenthesis. This challene only works if said parameter is NOT wrapped in parenthesis:
```
const checkpoints = checkpointPositions.map(
  (checkpoint) => new CheckPoint(checkpoint.x, checkpoint.y)
);
```
DOESN'T work,

but
```
const checkpoints = checkpointPositions.map(
  checkpoint => new CheckPoint(checkpoint.x, checkpoint.y)
);
```
does work.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-96

### Your code

```
const checkpoints = checkpointPositions.map(
  (checkpoint) => new CheckPoint(checkpoint.x, checkpoint.y)
);
```

### Expected behavior

The parameter used in the .map() function should work both when wrapped and not wrapped in parenthesis.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by RodrigoHLC** [comment]
Similar issue in Step 98 and in a lot of previous steps. Recommend taking a look at all of them (my first report in regards to this issue was in step 72 or 73, but there might have been errors in previous steps which I didn't yet know how to report)

**Comment by jdwilkin4** [comment]
> Similar issue in Step 98 and in a lot of previous steps

In the future, if you seen a list of challenges that have the same issue, you can create one issue and provide a list of links to those challenges and describe the general issue with them. 
Then a maintainer can triage the issue and open it up for contribution

> but there might have been errors in previous steps which I didn't yet know how to report

If you are not sure if something is a bug, you can still report it. 
A maintainer will take a look and there will be discussion that happens on the thread.
Then if it turns out to be a bug, then we will open it up to be fixed.
If it is a larger issue, then that will be handled by a team member.

Hope that helps
