### ISSUE TITLE
Bonfire: Falsy Bouncer - contradictory instructions

### ISSUE THREAD

**Issue by kokushozero** [FreeCodeCamp/FreeCodeCamp#5303]
Challenge [Bonfire: Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%0A%20%20arr%20%3D%20arr.filter(function(val)%7B%0A%20%20%20%20if%20(val%20%3D%3D%3D%20false%20%7C%7C%20val%20%3D%3D%3D%20null%20%7C%7C%20val%20%3D%3D%3D%20undefined%20%7C%7C%20val%20%3D%3D%3D%20%22%22%20%7C%7C%20val%20%3D%3D%3D%200%20%7C%7C%20isNaN(val))%20return%20false%3B%0A%20%20%20%20return%20true%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0Abouncer(%5Bfalse%2C%20null%2C%200%2C%20NaN%2C%20undefined%2C%20%22%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.

The instructions to Falsy Bouncer indicate that a Falsy value is of various types including **NaN**.
The first test requires that the function call **bouncer([7, "ate", "", false, 9])** should return **[7, "ate", 9]**
however note that the string **"ate"** is **NaN** therefor it should not be included in the resulting array.

Therefor it seems that there is no way to pass test 1 and test 3 with the same code block, they are mutually exclusive answers.

My code:
```javascript
function bouncer(arr) {
 
  arr = arr.filter(function(val){
    if (val === false || val === null || val === undefined || val === "" || val === 0 || isNaN(val)) return false;
    return true;
  });
  
  return arr;
}

bouncer([false, null, 0, NaN, undefined, ""]);

```

**Comment by kokushozero** [comment]
Apologies in advance if I have misunderstood something here.

**Comment by ltegman** [comment]
`NaN` is an actual value a variable can have and it is falsey. `"ate"` is not a number and `isNan("ate")` will return true, but the value "ate" is not falsey, only the specific value of `NaN` is falsey. The beauty (and occasional bug source) of falsey values is that you don't need to explicitly look for them like your code does, because whenever a boolean value is needed Javascript will type coerce them to a boolean value of false. What this means is that the code for your filter function can simply be this:
```
arr = arr.filter(function(val){
  return val;
});
```

Thanks and happy coding!

**Comment by SaintPeter** [comment]
And, technically, you can use the `Boolean` function to do that for you, so the problem can be solved:
`return arr.filter(Boolean)`, since Boolean takes truthy/falsy values and returns true or false.
