### ISSUE TITLE
Typo on A2 English for Developers (Beta) - Learn Greetings in your First Day at the Office - Task 160 

### ISSUE THREAD

**Issue by herminiotorres** [freeCodeCamp/freeCodeCamp#53057]
### Describe the Issue

On the current page exist this sentence:

```
Jake tells Sarah he can get in or out after he hears the door click, meaning he can enter or leave the building
```

But when you listen to the audio, it sounds like Jake explained to Sarah, so I think it should be `she` instead of `he` all over the sentence.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-160

### Your code

```
```

### Expected behavior

n/a

### System

n/a

**Comment by jdwilkin4** [comment]
HI @herminiotorres ! 

Thank you for opening up this issue.

I agree that it would make more sense to change the pronouns here since this is talking about what Sarah is going to do. 

## Note to contributors 

This is has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files to work on 

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2b6aaad95013a86cea6c.md

## Changes that need to be implemented

```md
# --description--

`Get in` means to enter a place, while `get out` means to leave a place. For example, in the dialogue, Jake tells Sarah she can `get in or out` after she hears the door click, meaning she can enter or leave the building.
```

**Comment by herminiotorres** [comment]
Thanks for the explanation. I just shared my frustration, but I understand someone taking over and opening the PR, and I'm happy about it since sometimes not all who open issues will work on them or have the knowledge to do so.

Maybe next time 🤞
