### ISSUE TITLE
Definition for symmetric difference should be more precise

### ISSUE THREAD

**Issue by AlexWD** [FreeCodeCamp/FreeCodeCamp#5308]
The mathematical term symmetric difference refers to the elements in two sets that are in either the first or second set, but not in both.

This is two for two sets but it's misleading. For example, it implies that for 3 sets the symmetric difference is the set of elements in any of the 3 but not all 3. This is wrong since the symmetric difference for 3 sets includes the intersection of all 3 sets.

The link to the video is great, but I think the wording on the problem could be improved for clarity.

**Comment by SaintPeter** [comment]
What would you propose as an alternate description?

We do try to give a basic explanation for a given Bonfire, but we don't always spell out everything.  At some point the user has to read the article and/or watch the video to understand it all.

**Comment by AlexWD** [comment]
How about:

    The symmetric difference of two sets is the set of elements which are in either of the sets and not in their intersection.

It's a little nit-picky but that's more clear imo.

**Comment by Demon000** [comment]
The mathematical term symmetric difference refers to the elements that are present in only one of the given sets of elements.

**Comment by SaintPeter** [comment]
I don't think it's "only one", because if you have [5], [5], [5], the difference is actually [5].

@AlexWD I thought your primary concern was how the definition applies to more than 2 arrays?

**Comment by AlexWD** [comment]
It's a wording issue.

    The mathematical term symmetric difference refers to the elements in two sets that are..

That sounds as if symmetric difference is defined as an operation on two sets, but the real definition is more abstract than that.

That's why I suggest this wording:

    The symmetric difference of two sets is the set of elements which are in either of the sets and not in their intersection.

That specifies that the symmetric difference of two sets contains elements that appear in one but not both, but doesn't imply thats the case for more than 2 sets as you can see is the case with [5], [5], [5] that @SaintPeter  mentioned.

**Comment by YannHulot** [comment]
Hi, I would like to interject into this conversation. I am actually working on this bonfire and found the description confusing. Also I did not watch the entire video that you provided. that was my bad.

 What is wrong with the description of the bonfire is that you should warn the campers that this definition:

 ``` The symmetric difference of two sets is the set of elements which are in either of the sets and not in their intersection.``` <strong>is only valid for two sets of numbers.</strong>

 When you include a third set of numbers , the definition of symmetric difference would be something like this: 
``` Lets call the symmetric difference for the 3 sets of numbers  A,B and C: "finalDiff" and the symmetric difference between sets A and B: " firstDiff".  "firstDiff" is the symmetric difference between the sets of numbers A and B whereas "finalDiff" is actually the difference between the set "firstDiff" and the set C. If set A = { 1,2,3,4,5}, set B={3,4,5,6,7} and C ={5,6,7,8,9} then firstDiff = {1,2,6,7} and finalDiff ={5,1,2,8,9}.```

I don't want to be nitpicking but the description of the bonfire made me believe that I had to find the  numbers that were <strong>only</strong> present in one of the sets of numbers . 
Again, I only blame myself because I did not take the time to watch the video but the description of the bonfire made me believe that my understanding of what a symmetric difference was , was in fact correct. 

My last point, will be that campers come from  many backgrounds and speak many languages, many of them speak English as a second language like me. If they don't understand the problem they are not likely to find the solution, so explaining this bonfire in a different way would be really beneficial. 

If you add a second example with this time 3 sets of numbers and leave the video has a backup, then I think everybody will understand what they are supposed to do in this bonfire.

**Comment by SaintPeter** [comment]
Personally, when I did this one, I made the same naive error that almost everyone makes at first and then had to do research on the web to learn more.  I actually filed the PR which added the video as a link, since I found it so helpful.

This is a non-trivial problem to solve and I don't think that's necessarily a bad thing.  Sometimes we need to solve hard problems and sometimes we need to research them.

I remain open to a succinct description that you believe captures the essence of the definition of a Symmetric Difference.

**Comment by YannHulot** [comment]
I will think about it and get back to you asap. Thanks for taking the time to answer me.

**Comment by chuckadams** [comment]
I think the problem should be simplified to eliminate the step of reducing over an arbitrary number of args unless and until some description comes around that neither confuses the reader nor requires a wall of text larger than most other challenges to explain.  Just have the user implement symmetric difference until a better treatment of Array.reduce can be put into another challenge.
