### ISSUE TITLE
Camper News gives "no url supplied" error on successful story submission

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5318]
![](https://www.evernote.com/l/AqQEEW5F8F5Pj5BS2DkOM9wbQTxWMVmB_YUB/image.png)

**Comment by vanirt** [comment]
Hello, How can I assing this issue to myself ?

**Comment by SaintPeter** [comment]
@vanirt Go right ahead.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp

**Comment by Em-Ant** [comment]
I experienced this issue in the past days but it wasn't so bad, because it ended up letting me correctly submit the link I wanted. Today (12-20-15) it seems to be worse. I had big troubles submitting a link, and I ended posting it twice (and I got no brownies at all). I also see a lot of links submitted twice in the news section.

**Comment by raisedadead** [comment]
I can't seem to reproduce it. @Em-Ant : What is the frequency of this issue, in terms of attempts?

**Comment by Em-Ant** [comment]
@raisedadead I experienced the "no url supplied" on every post of mine in the last week (3 or 4 posts in total). Only the last submission ( dec-20 )  required three attempts. I've not posted anything after that.

**Comment by SaintPeter** [comment]
I am getting this issue as well.  Confirmed.

**Comment by mkemo8870** [comment]
I am having this issue. Has anyone resolved it?

**Comment by harishsun** [comment]
I am unable to post link as well :(
