### ISSUE TITLE
Re submitting, bonfire doesn't update portfolio 

### ISSUE THREAD

**Issue by anders462** [FreeCodeCamp/FreeCodeCamp#5326]
When I try to resubmit my already passed bonfires with new code, the portfolio solution is never updated. Further of some reason I have multiple copies of the solution in some cases. 

Anders

**Comment by SaintPeter** [comment]
This is expected behavior.  We collect the time and date of each submission.  We are working on functionality to allow users to delete unwanted solutions, but all passing solutions will be retained for now.  You can scroll down to the bottom of your solutions list to see your newer solutions.

If you don't want to save your solution, don't hit the big green "Submit and go to my next challenge" button.  Just hit the X in the upper right corner and it won't be written to your profile.

**Comment by anders462** [comment]
Hi Rex,

I see  the new one listed further down now, I thought they were listed alphabetically but I realize now that it's chronological.

Look forward to be able to clean up and delete unwanted submission as some test cases have been added so some of my old passed wouldn't today 

Thanks 

Anders
