### ISSUE TITLE
Learn Intermediate OOP by Building a Platformer Game - Step 42 - strict test

### ISSUE THREAD

**Issue by pmpkata** [freeCodeCamp/freeCodeCamp#53287]
### Describe the Issue

these 2 if statements are functionally equivalent and yet one passes and the other does not pass, took me over a half hour, and made me a very sad panda

 if(keys.rightKey.pressed && player.position.x < 400) {

  }
    if (keys.rightKey.pressed === true && player.position.x < 400) {
  
  }

the problem is that later the keys are defined with press as false, which makes you assume you need to check if it is true, though you do not, and that is horribly confusing and stupid.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-42

### Your code

```



```

 if(keys.rightKey.pressed && player.position.x < 400) {

  }
    if (keys.rightKey.pressed === true && player.position.x < 400) {
  
  }

### Expected behavior

I expected to pass and be done with this in 2 minutes or less.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by sahilintech** [comment]
The === operator checks for strict equality, meaning both the value and the type must match. So, keys.rightKey.pressed must be the boolean true, not just any truthy value.

In this case, even if keys.rightKey.pressed is 1, "some string", or {}, the condition will not evaluate as true. It will only be true if keys.rightKey.pressed is exactly true.

So the elegant way of writing if condition is first one only because in tests keys.rightKey.pressed can be equal to anything some timestamp or anything

**Comment by pmpkata** [comment]
so would just using 2 equals signs work then?

**Comment by sahilintech** [comment]
I am just saying that your code is tested in backend and test is written is such a way that it will handle only first if statement otherwise your second if statement is also correct.

**Comment by jdwilkin4** [comment]
> I am just saying that your code is tested in backend and test is written

The tests are in the frontend code and use a regex

```js
assert.match(animate.toString(), /keys\.rightKey\.pressed\s*&&\s*player\.position\.x\s*<\s*400/);
```

Even though `keys.rightKey.pressed && player.position.x < 400` would be more common in JS apps, we should allow `keys.rightKey.pressed === true` because a lot campers will still feel more comfortable writing that and the tests should allow for either answer.

hope that helps 👍

**Comment by pmpkata** [comment]
Thank you, I appreciate it.
