### ISSUE TITLE
Grammatical error in "Challenge Project - Debug a C# Console Application Using Visual Studio Code"

### ISSUE THREAD

**Issue by wblondel** [freeCodeCamp/freeCodeCamp#53299]
### Describe the Issue

Hello,

On the challenge project "Debug a C# Console Application Using Visual Studio Code, the question is:

> Which of the following options can be used set a breakpoint in Visual Studio Code?

The word `to` is missing between `used` and `set`.

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/challenge-project-debug-a-c-sharp-console-application-using-visual-studio-code

### Your code

N/A

### Expected behavior

I believe the question should be:
> Which of the following options can be used to set a breakpoint in Visual Studio Code?

### System

- Device: all
- OS: all
- Browser: all
- Version: all

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/challenge-project-debug-a-c-sharp-console-application-using-visual-studio-code.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
