### ISSUE TITLE
bug in line 3

### ISSUE THREAD

**Issue by akashelhance** [FreeCodeCamp/FreeCodeCamp#5330]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%7Bcolor%3Ablue%3B%7D%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2{color:blue;}
<h2>CatPhotoApp</h2>
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by SaintPeter** [comment]
This is not a bug, this is an error in your code.  You have placed your `h2` element inside your `style` element.

In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) rather than posting an issue.  Issues are for problems with the site, not for asking for help.

**Comment by akashelhance** [comment]
okkk...
