### ISSUE TITLE
Update regex tests for Platformer Game Step 82 to accept multiple valid solutions

### ISSUE THREAD

**Issue by pmpkata** [freeCodeCamp/freeCodeCamp#53301]
### Describe the Issue

in .every the rule section is required to be wrapped in parenthesis even though it doesn't effect the functionality.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-82

### Your code

```
if (collisionDetectionRules.every(rule => rule)) {
    player.velocity.y = 0;
    return; 
  }


```

### Expected behavior

I expected to pass. this is what the checker is actually asking for:
```
if (collisionDetectionRules.every((rule) => rule)) {
    player.velocity.y = 0;
    return; 
  }
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by tsirianni** [comment]
I can help with that. I will fix the regex and open a pull request soon! :)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase. This means that the next time deployment is made, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by pmpkata** [comment]
great thanks guys!
