### ISSUE TITLE
Code passes when outside the body element.

### ISSUE THREAD

**Issue by Stephen-254** [freeCodeCamp/freeCodeCamp#53333]
### Describe the Issue

Despite the code being written outside both the body and html elements, the code passes.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-8

### Your code

```

<html>
  <body>
    <main>
      <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->
      <p>See more cat photos in our gallery.</p>

<!-- User Editable Region -->

      

<!-- User Editable Region -->

    </main>
  </body>
</html>
<img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg">

```

### Expected behavior

The code should not pass, and an error should be thrown to bar the user from moving to the next step.

### Screenshots

![Screenshot 2024-01-23 162239](https://github.com/freeCodeCamp/freeCodeCamp/assets/106899176/88d975ed-bfc7-422d-8baa-9695f4cd81c6)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for taking the time to open this.

This is expected behaviour, and is caused by the browser:
<img width="1280" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/817b9a60-954d-4f15-88d2-741972f759ee">

The HTML parser is very forgiving, and will try to render what it **thinks** you meant. So, it fixes the code for you.

The current tests just check for an `img` element within the `document`, which is fine, because the instructions are:
> Inside the existing `img` element...

So, provided the existing `img` element is used, the instructions are fulfilled.

Sometimes, we purposefully avoid this by writing our tests using the input code and regex. However, this is prone to error, because we essentially start acting as the HTML parser, and it often causes valid code to fail the tests. As such, we opt to test what the browser renders more often than just what the Camper puts in the editor, and I do not think this lesson prompts any changes.

Hope this clarifies

**Comment by Stephen-254** [comment]
Hello Shaun. That was very insightful. Thanks.
