### ISSUE TITLE
Misattributed Quote

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#53376]
### Describe the Issue

    It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.

    — Elinor Smith

This quote is commonly attributed da Vinci but seems to be from Elinor Smith's book. We should confirm and update the attribution.

### Affected Page

https://www.workiversary.com/blog/elinor-smith

### Steps to Reproduce

Check our quotes database 

### Expected behavior

Quotes should be attributed accurately 

### System

All

**Comment by jdwilkin4** [comment]
Through some digging around, I also found the discrepancies surrounding this quote and DaVinci.

Aside from the article you linked, I was able to find one other place where she is attributed to the quote
https://www.brainyquote.com/quotes/elinor_smith_120920

But I couldn't verify that she is the credible source either.

So I vote, for now that we just remove that quote completely until a more credible verification can be made. Then we can just add in back in at that time.

**Comment by jeremylt** [comment]
It's supposed to be from her book, Aviatrix. It shouldn't be too hard to track down a copy of her book.

**Comment by jdwilkin4** [comment]
I still think the simplest answer would be to remove it now from the quotes array.

Then someone gets a copy, verifies it, then we just create a new PR to update it

**Comment by jdwilkin4** [comment]
And if it turns out she didn't say it, then at least the quote is removed from now until we can find the credible source of who actually did say this 👍

**Comment by jeremylt** [comment]
Ha, fair. That quote probably won't come back in that case since so much is going on, but there are lots of other quotes in the database.

**Comment by jdwilkin4** [comment]
# Note to first time contributors 

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/motivation.json

Remove this quote, since we can't verify the original author at this time

```js
   {
      "quote": "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
      "author": "Leonardo da Vinci"
    },
```

Happy contributing

**Comment by rick-joi** [comment]
The quote is definitely from Elinor Smith’s book Aviatrix. A screenshot of the page that includes the quote from the Kindle edition is attached. 

![IMG_6395](https://github.com/freeCodeCamp/freeCodeCamp/assets/133763409/756773cb-7aef-496c-8d33-be082b5d10f1)

**Comment by jeremylt** [comment]
Since we have a proper attribution now, I'm re-opening so we can discuss putting the quote back with the correct original source

**Comment by jeremylt** [comment]
Ah, wasn't clear to me in the discussion here. Should have checked the issue that closed it.
