### ISSUE TITLE
Javascript Learn Function Programming By Building a Spreadsheet Step 14 to sensitive

### ISSUE THREAD

**Issue by SabuWolf96** [freeCodeCamp/freeCodeCamp#53372]
### Describe the Issue

The tests are just to sensitive, (This step is not allone in this)
We are asked to call the forEach Method on the array letters and put in our createLabel Method as callback function

`letters.forEach(letter => createLabel(letter))` Doesn't pass allthough it's syntactly correct (and in my opinion clearer)
While the following:
`letters.forEach(createLabel)` Does pass

Didn't took me to long to revert back to the shorter version, But they both do the same and most of the time an arrow call back function is wanted in the tests, so we are getting conditioned to use the arrow syntax.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-14

### Your code

```
letters.forEach(letter => createLabel(letter))
// vs
letters.forEach(createLabel)
```

### Expected behavior

Well I expected to get a pass with the first version aswell

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: probably the latest

**Comment by Nishant-Nagururu** [comment]
I would like to solve this issue as my first open source contribution. When I look for step 14 of the lesson, I can see the .md file and it has what assertions need to be passed. [Here](https://github.com/freeCodeCamp/freeCodeCamp/blob/987fe44b27f561dda6f3fec4778d7fa70e650a79/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/64347464f78cd9209545f35c.md) is the file I'm talking about. There is a mistake with those assertions that is causing the first option to fail. However, I don't think the actual code is coming from that runs the web page. This is my first time trying to contribute to free code camp but I would love to solve this issue so if someone could point me in the right direction that would be great @jdwilkin4 @SabuWolf96

**Comment by jdwilkin4** [comment]
Hi @Nishant-Nagururu ! 

> However, I don't think the actual code is coming from that runs the web page.

I am not really sure what you mean here. 

But I would suggest adding a console statement to that first test so you can see what the `code` variable is.

```js
console.log(code)
assert.match(code, /letters\.forEach\(/);
```

Then following these steps to see the code variable: 

1. start the local server
2. go to the step
3. write some random code
4. open the console 
5. press the "Check your code" button
6. see the existing seed code along with your answer printed 

<img width="809" alt="Screenshot 2024-01-26 at 12 06 47 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/9e382f88-fa04-4cc1-be51-e8c2bed77e91">


For any other questions about working on this issue, please create a post on either the forum or discord where contributors can assist you there.
It is easier to have discussion threads there instead directly on this issue here.

Hope that helps
