### ISSUE TITLE
My code isn't working

### ISSUE THREAD

**Issue by Edrubo** [freeCodeCamp/freeCodeCamp#53477]
### Describe the Issue

The body of the if statement isn't working. What can be done?

### Affected Page

Learn Basic String and Array Methods by Building a Music Player

### Your code

```
 if (userData?.currentSong?.id === id) {
    userData?.currentSong = null;
    userData?.songCurrentTime = 0;
    pauseSong();
    setPlayerDisplay();
  }


```

### Expected behavior

The body of the if statement is not working and I don't know why.

### Screenshots

![challenge](https://github.com/freeCodeCamp/freeCodeCamp/assets/126637160/d6fca660-a23b-47f1-ae64-39da2639ca4f)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

There's error in instructions, optional chaining shouldn't be used in assigning.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase. This means that the next time we push to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

- - -

Note for future:
Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.
