### ISSUE TITLE
learning local storage by building a todo app

### ISSUE THREAD

**Issue by maverickflow-er** [freeCodeCamp/freeCodeCamp#53492]
### Describe the Issue

I am trying to get past step 30, using an arrow syntax to create an addOrUpdate function, then moving the dataArrIndex variable, taskObj and if statement in the addOrUpdate function. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/#learn-localstorage-by-building-a-todo-app

### Your code

```

const addOrUpdateTask = () => {dataArrIndex, taskObj; if(){}};

```

### Expected behavior

i expect the dataArrIndex, taskObj and the if statement to all be in side the addOrUpdate function

### Screenshots

You can enhance code readability and maintainability by refactoring the submit event listener into two separate functions. The first function can be used to add the input values to taskData, while the second function can be responsible for adding the tasks to the DOM.

Use arrow syntax to create an addOrUpdateTask function. Then move the dataArrIndex variable, the taskObj object, and the if statement into the addOrUpdateTask function.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

here is the error message i keep getting: You should move the dataArrIndex variable into the addOrUpdateTask function.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
