### ISSUE TITLE
[python]: cipher/step-41: clarify 'empty space'

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#53526]
### Describe the Issue

The instructions ask:
```
print the result of comparing char with an empty space (' ').
```
It's common for people to make the error of using an empty string, instead of a space
```
char == ''
char == ' '
```
I think calling it an "empty space" might be a bit unclear (even though it does give the example ' '). I propose changing the wording to "a space character" or just "a space"

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-41

### Your code

NA

### Expected behavior

NA

### Screenshots

NA

### System

- Device: NA

- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase with #53514. This means that the next time we push to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
