### ISSUE TITLE
String quotation rules in Python.

### ISSUE THREAD

**Issue by zairahira** [freeCodeCamp/freeCodeCamp#53542]
### Describe the Issue

It would be a good idea to introduce the concept of the restriction on using the same type of quotation marks inside a string (like `"` inside `" "` or `'` inside `' '`) without escape characters in one of the lessons. The Cipher project would be a good place to add and explain this.

in Python is due to the way Python parses string literals. When Python encounters a quotation mark, it treats it as the start of a string. The next quotation mark of the same type is treated as the end of the string. This is a common convention in many programming languages to clearly define the beginning and end of string literals.

### Affected Page

https://freecodecamp.org/learn/scientific-computing-with-python

## Problematic strings

"This is a "problematic" string"
'It's a problematic string'

## Non-Problematic strings

"This is a \"non-problematic\" string"
'This is a "non-problematic" string'
"""This is a "non-problematic" and multi-line string,
"It's a non-problematic string"

### Expected behavior

Teaching this concept would be useful to the campers.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
cc @Dario-DC

**Comment by ilenia-magoni** [comment]
do we want to add a print with `'decoding text "<something encrypted>"'`?
or something more complicated?

**Comment by Dario-DC** [comment]
[Step 92 ](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-92) introduces escaping but mentioning only the newline character. This might be a good place to add a new step to teach that escaping is necessary to write a string  containing the same kind of quote used to surround the string.

Otherwise we should add another step towards the beginning where strings are introduced.

**Comment by fhsinchy** [comment]
According to the [PEP-8 style guide](https://peps.python.org/pep-0008/#string-quotes), we should avoid escaping quotations. Since single and double quotes are the same, it'd better to teach the learners to pick a style and stick to that. If they have to put quotations inside a string, then they can mix the two types. For example, if they want double quotation to show up within the string then they can use single quotation around the whole string and vise versa.

**Comment by Dario-DC** [comment]
I agree @fhsinchy but it's worth to just mention that escaping is possible.

**Comment by fhsinchy** [comment]
@Dario-DC I agree with that.

**Comment by Niko030303** [comment]
Agree

**Comment by benzoms** [comment]
Hi all, if you all want to open this to contributions with the help wanted tag, I have code ready to go.
You can see above the pull request that incorporates
- the concept of using quotes within strings without escape characters
- an additional criteria to the step which asks the camper to surround text within an fstring with double quotes.

into [Step 92](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-92).

**Comment by ilenia-magoni** [comment]
The discussion has not reached a consensus, if you want to partecipate in the discussion you are welcome, but at this time the issue is not ready for contribution @benzoms

**Comment by Dario-DC** [comment]
This has been partially addressed https://github.com/freeCodeCamp/freeCodeCamp/blob/cbdc470012756b4befe22b18b4620f3ae064393a/curriculum/challenges/english/07-scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/65822bd82d708c4895080c35.md?plain=1#L10-L13
