### ISSUE TITLE
Typo which changes meaning in "localStorage by Building a Todo App" lesson of the new JavaScript course

### ISSUE THREAD

**Issue by bwyoungy** [freeCodeCamp/freeCodeCamp#53613]
### Describe the Issue

In step 30, we refactor the code a bit by splitting up code we already wrote into functions. One of the statements to move is an if statement which checks the result of a findIndex function on an array.  I forgot to mark the if statement in my cut-paste job and got the following note when checking the code:
`You should move the if statement with the condition dataArrIndex === 1 into your addOrUpdateTask function.`
Unfortunately the condition in the note is completely wrong as the condition we want is to check if it's equal to -1 as that is the flag the findIndex function returns if it doesn't find a match. If the return value was 1, that's the id and we'd not want to enter the if statement.
It's only the note which is wrong, and if I enter
`if (dataArrIndex === 1) {
    taskData.unshift(taskObj);
  }`
in the code, then I still have the note when checking the code, and only the actual correct if statement of equalling -1 lets me continue. But I'm sure such a situation could be frustrating for a camper if they write what's in the note and stay stuck

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-30

### Your code

```
const addOrUpdateTask = ()=>{
 const dataArrIndex = taskData.findIndex((item) => item.id === currentTask.id);
  const taskObj = {
    id: `${titleInput.value.toLowerCase().split(" ").join("-")}-${Date.now()}`,
    title: titleInput.value,
    date: dateInput.value,
    description: descriptionInput.value,
  };
if (dataArrIndex === 1) {
    taskData.unshift(taskObj);
  }
};
```

### Expected behavior

To not accept the code and display a note saying the if condition should be `dataArrIndex === -1`

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/150274996/97532be9-417b-401e-8283-eed01ca15291)

### System

- Device: VivioBook ASUS Laptop
- OS: Windows 11 Home
- Browser: Mozilla Firefox

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64fad07f43a101779cb8692a.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by bwyoungy** [comment]
> This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

Thank you. I tried to fix it in the repository. Hope I did it properly :)

**Comment by jdwilkin4** [comment]
>  I tried to fix it in the repository. Hope I did it properly :)

@bwyoungy

I see that you made a commit to your forked copy of the project here
<img width="416" alt="Screenshot 2024-02-08 at 4 10 12 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/888c0253-6fab-4f63-b48c-9e25bef505e6">

But I don't see any new pull requests opened by you.
Please read through the [Contributing Guide](https://contribute.freecodecamp.org/#/) to learn how to make a pull request.
If you need help, then please post on either the forum or discord with your question and people can assist you there 👍
