### ISSUE TITLE
Learn Basic JavaScript by Building a Role Playing Game - Step 86 - function passed twice

### ISSUE THREAD

**Issue by iambherulal** [freeCodeCamp/freeCodeCamp#53624]
### Describe the Issue

In the JavaScript Algorithms and Data Structures (Beta) series/course Step 86 there is a bug in the locations object.

```
  {
    name: "store",
    "button text": ["Buy 10 health (10 gold)", "Buy weapon (30 gold)", "Go to town square"],
    "button functions": [buyWeapon, buyWeapon, goTown],
    text: "You enter the store."
  }
```

in the "button functions" `buyWeapon` is repeated twice the first one should be `buyHealth`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-86

### Steps to Reproduce

1. Go to '...' https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-86
2. Click on '...' Go to store button
3. Scroll down to '...'

### Expected behavior

Clicking on the Go to Store button and Buy Health should update the health value but it's not happening because of the correct function is not in place.

### System

- Browser: [e.g. Chrome, Safari]

**Comment by gikf** [comment]
Nice finding. Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8cbd1e3595431d5a2b3f1.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
