### ISSUE TITLE
JavaScript Algorithms and Data Structures (Beta) - Inconsistent requirements regarding semi-colon at the end of line

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#53694]
**Describe the bug**
Most of the steps neither explicitly require semi-colon at the end of line, nor explicitly not require. Unless regex is too strict, either no semi-colon and semi-colon present is fine.

However there's few steps (about a dozen) that force using, or not using the semi-colon. Often that's only indicated in the hint, what can be particularly annoying for camper.

For example:
- requiring
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3b41c9494f937560640ab.md
- not requiring
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da4b16937be43ba24c63d.md

**Expected behavior**
More consistent approach to semi-colon requirements.

**Comment by jdwilkin4** [comment]
The origianl intent was to get campers used to writing semi colons because a lot of linters and projects will automatically insert semicolons into their JavaScript code.

But since the requirements of semicolons is inconsistent, I vote we only keep the requirement in [step 3](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-3) and all other steps should be optional

**Comment by aaqib605** [comment]
> The original intent was to get campers used to writing semi colons because a lot of linters and projects will automatically insert semicolons into their JavaScript code.
> 
> But since the requirements of semicolons is inconsistent, I vote we only keep the requirement in [step 3](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-3) and all other steps should be optional

@jdwilkin4 I support this, please clarify are you talking about making semicolons optional in just the `role playing game` or throughout the entire `new javascript course.`

**Comment by jdwilkin4** [comment]
@aaqib605 

The semicolons will be optional for the entire course.

**Comment by jdwilkin4** [comment]
A quick update:

There will be a new project added before the RPG project.
That project will probably have just one step to talk about semi colons, otherwise semicolons will be optional.

I am currently working on the update to the RPG to accommodate the new project going before it. So changes will be made to remove mandatory semicolons in that RPG project.

All other projects should have semi colons be optional.

If there are any other projects beside the RPG project that have mandatory semi colons, then it would be best to create a separate issue to report those so it can be fixed.

**Comment by naomi-lgbt** [comment]
I disagree with this approach. I think we *should* require semi-colons, at least in the beginning. Most linters/formatters will insert them, and JavaScript's interpreter itself "inserts" them at run-time.

Here's the thing though. While they may *seem* optional, there are specific edge cases where not having a semi-colon will cause issues with the interpreter. See [some examples here](https://en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion), as well as my personal favourite:

```js
import test from "test"

(async () => await test())()
```

IIFE here will actually be parsed as a call of "test" because there is no semi-colon.

**Comment by naomi-lgbt** [comment]
thin

**Comment by naomi-lgbt** [comment]
Sorry, smacked the tab key on accident.

**Comment by lasjorg** [comment]
If we want to teach beginners about semicolons, we should explain what they are, and why JavaScript can work without them. It doesn't have to be overly technical, just the basic concept.

If we want it to enforce semicolons usage, we should be consistent about it. Not just in a few random steps for no apparent reason. We could simply make semicolons a requirement in the first challenge _after_ we explain them.

> Semicolons `;` are part of the language syntax, you can think of them as punctuation. To make the language more approachable and convenient, JavaScript is able to automatically insert semicolons.
> 
> Throughout this first lesson, you are required to add semicolons, as a best practice. Later in the curriculum, this requirement will go away.

I'm truly not sure what it is we believe we are teaching by randomly having semicolon requirements appear out of nowhere in such an inconsistent and unexplained way?

I know we are all about getting people to code as fast as we can, with as little reading as possible, but sometimes we have to stop and explain things. It is unrealistic to think otherwise.

**Comment by moT01** [comment]
The general philosophy that we've often used is that "valid code should pass". So semi-colons should usually be optional in my opinion. Except for the cases where it's needed, like Naomi mentioned, or if we are trying to teach about them - or maybe some other instances.

The issue I think is that we can't control this. We could go through the entire curriculum and make them all optional or whatever is appropriate, and then someone may add a challenge that requires them where they should be optional, or makes them optional where it should be required. So I don't know how to be consistent with this. I think we just need to fix them on a case-by-case basis when issues or posts come up.

Because of that, unless there's some specific challenges that we want to fix, I would vote to close this.

**Comment by jdwilkin4** [comment]
> If we want to teach beginners about semicolons, we should explain what they are, and why JavaScript can work without them. It doesn't have to be overly technical, just the basic concept.

The new cert has a lecture video talking about this

> If we want it to enforce semicolons usage, we should be consistent about it. Not just in a few random steps for no apparent reason. We could simply make semicolons a requirement in the first challenge after we explain them.

Since we have the lecture video before the first workshop in the new cert, semicolons will not be enforced. 
So far the merged content tests isn't enforcing them. If there is a test that slips through with a required semicolon, then we will create a separate issue for that.
