### ISSUE TITLE
typo - English for developers - 3rd chapter, Task 61 - happen not happens

### ISSUE THREAD

**Issue by pchomik101** [freeCodeCamp/freeCodeCamp#53777]
### Describe the Issue

In task 61, the last word of the first sentence is missing the letter S at the end.
Should read happens, not happen.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-conversation-starters-in-the-break-room/task-61

### Steps to Reproduce

-proceed to 3rd chapter, task 61
-observe the first sentence

### Recommended fix or suggestions

Please change the first sentence to:
There are some words you can use in your sentence to express how often something happens.

### Screenshots

![happens](https://github.com/freeCodeCamp/freeCodeCamp/assets/153861556/3bd87684-43c0-4b8a-990a-774410508ecd)

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657ce0bbf16c312c8dcc8dff.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by helip0269** [comment]
I would like to work on this issue.
