### ISSUE TITLE
gender - English for developers - 3rd chapter, Task 41 - he/she they?

### ISSUE THREAD

**Issue by pchomik101** [freeCodeCamp/freeCodeCamp#53776]
### Describe the Issue

The course currently only supports binary gender, he and she, they is excluded.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-conversation-starters-in-the-break-room/task-41

### Steps to Reproduce

-Advance to 3rd chapter, task 41
-oberserve the text

all platforms, all fw

### Recommended fix or suggestions

Please make this course more inclusive, with something like:

What do/does (he/she/they) look like?

### Screenshots

![task41](https://github.com/freeCodeCamp/freeCodeCamp/assets/153861556/3243b63d-9e76-4ca6-b438-ad828a3c3c34)

**Comment by pchomik101** [comment]
The string "What is (he/she) like?" also appears in Task 42.

**Comment by pchomik101** [comment]
"they" is taught in task 43. 

Even if it is discussed in task43,  it can still be used in respective string from Task 41 onwards.

**Comment by areebqazi** [comment]
I have updated the issue as asked . Please review it .

**Comment by a2937** [comment]
Hi there,

Thanks for creating this pull request.

The linked issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to update this pull request to reflect the issue consensus. Until the issue is open for contribution, we will not be able to review your pull request.

**Comment by a2937** [comment]
Hi there,

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by naomi-lgbt** [comment]
Hmmmmmm,

While I am always advocating for inclusivity, in this case it may not make sense. Specifically because in English, even when using the singular "they", plural verb conjugations are used.

"What does (he/she) look like?" -> "What **do** they look like?"
"What is (he/she) like?" -> "What **are** they like?"

**Comment by areebqazi** [comment]
I have made the changes as @naomi-lgbt said .

**Comment by naomi-lgbt** [comment]
# Open for Contribution

The following tasks need to be updated with these texts.

## Task 41

```md
`To look like` is used to describe someone's or something's appearance, often implying a comparison.

When you're curious about someone's physical characteristics, such as their hair color, height, or overall look, you might use expressions like:

`What does (he/she) look like?` or `What do they look like?

The choice between these depends on the number and gender of the person you're asking about. Use `does` with singular pronouns `(he, she)` when referring to one person and `do` with `they` when referring to someone whose gender might not be known or if referring to people in a non-binary or plural sense.

**Note:** Remember that questions about a person's appearance can be sensitive. Some people may not feel comfortable discussing physical traits, and it's important to respect their feelings. Always use this question politely and in the right context, where it is appropriate to do so.
```

## Task 42

```md
When you want to know about someone's character or personality, you can ask, `What is (he/she) like?` or `What are they like?`.

This question is about the qualities of a person, not about their physical appearance. Example:

Imagine you meet a new student in your programming class and you want to know more about her. You can ask a classmate `What is she like?`.

You are not asking if the new student likes computers or games; you are asking about her personality. Maybe she's friendly, smart, or really good at coding.
```
