### ISSUE TITLE
broken test for step 1 on learn HTML By Building a cat photo app

### ISSUE THREAD

**Issue by zulfiqr** [freeCodeCamp/freeCodeCamp#53830]
### Describe the Issue

code does not pass

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1

### Your code

```

<h1>CatPhotoApp</h1>

```

### Expected behavior

the code should pass tests

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/9796354/1c78ef8d-2510-47ea-a854-272c9177a062)

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Chrome,]
- Version: [121.0.6167.187]

**Comment by Mikey-Esteban** [comment]
Hi @zulfiqr, 

There's a hint in your screen shot saying "You appear to be using a browser extension that is modifying the page. Be sure to turn off all browser extensions." 

Does doing so still cause the code to not pass the test?

**Comment by ilenia-magoni** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
