### ISSUE TITLE
Horizantal scroll not working

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53847]
### Describe the Issue

The code snipper should have horizantal scroll but it does not and half code is cut and not scrollable

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-13

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-13
2. Click on code snipper
3. Scroll left or right
4. it won't scroll

### Expected behavior

The code snippet should scroll horizontol 

### Screenshots

<img width="601" alt="Screenshot 2024-02-24 at 02 42 09" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/8664996/6243299d-d685-4e3a-ab1e-fe47ef1e6fca">

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome
- Version 121.0.6167.184 (Official Build) (arm64)

**Comment by mmatsumoto1026** [comment]
Perhaps this issue is similar to another [one](https://github.com/freeCodeCamp/freeCodeCamp/issues/51750)?

**Comment by bbsmooth** [comment]
@mahassan Can you be very very explicit about what you are doing when trying to scroll the code snippet. We need to know exactly how you are trying to scroll.

And yes, as @mmatsumoto1026 suggested, have a look at that previous issue. You may have to use your mouse on the horizontal scrollbar because of the limitations of the monaco editor.

**Comment by aceppaluni** [comment]
Hi Is this still open?

**Comment by raisedadead** [comment]
Closing as duplicate
