### ISSUE TITLE
Machine Learning with Python Certification Projects not validate Solution Links (not run tests)

### ISSUE THREAD

**Issue by fabianbernhart** [freeCodeCamp/freeCodeCamp#53894]
### Describe the Issue

In the Machine Learning Pythone Course the Submit Link from Certification Projects not run test

https://github.com/freeCodeCamp/freeCodeCamp/assets/135550293/15ff3e9b-a8bb-4332-b819-6812adff1824

### Affected Page

https://www.freecodecamp.org/learn/machine-learning-with-python

### Your code

```
Solution Link: https://google.com
```

### Expected behavior

Tests failed you cant complete this challenge. run test_module.py in your project for details.

### Screenshots

![grafik](https://github.com/freeCodeCamp/freeCodeCamp/assets/135550293/cf08147b-621a-4c8c-b8bf-44d8eece3a66)

### System

- System: Windows 10
- Browser: [Chrome, Firefox]

**Comment by jeremylt** [comment]
I think this is a know issue, but I'm not sure if a path ahead has been decided upon

**Comment by fabianbernhart** [comment]
> I think this is a know issue, but I'm not sure if a path ahead has been decided upon

i cant find a issue with the same "issue"

**Comment by jeremylt** [comment]
I'm not sure if or where the issue is being tracked but I do know it's been discussed

**Comment by fabianbernhart** [comment]
> I'm not sure if or where the issue is being tracked but I do know it's been discussed

ISSUE CLOSED.

**Comment by jeremylt** [comment]
The problem is still present, right? Why close the issue?

**Comment by fabianbernhart** [comment]
ISSUE REPOPEND. 
i thought there was another issue open ups

**Comment by ShaunSHamilton** [comment]
Hello there,

This is expected, because there are no tests to run. The tests exist on the submitted project. As such, you are expected to follow the Academic Honesty Policy when submitting your project, and the project can be reviewed/reported at any time.

**Comment by Angel-Mathew007** [comment]
Hi! I’d like to work on this issue. Please assign it to me if it’s available.

**Comment by majestic-owl448** [comment]
@Angel-Mathew007 the issue is closed, it is not available, also We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
