### ISSUE TITLE
Cafe Menu Step 58 font casing

### ISSUE THREAD

**Issue by Supravisor** [freeCodeCamp/freeCodeCamp#53911]
### Describe the Issue

The instructions ask to learner to use the Impact font.
One learner on the forum posted that the tests fails use of using lower case first letter for the font name.

In the screenshots, one picture is the rendering of the unaltered code, the other using impact (lower case) font name.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-58

### Your code

```
h1, h2 {
  font-family: impact;
}

h1, h2 {
  font-family: Impact;
}

// both are valid syntax
```

### Expected behavior

The tests should pass use of either impact or Impact.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/47c9309e-73e4-40a5-9f22-65e85fd6d927)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/6ec8d99a-92ea-40d9-8002-e3532e1d5c05)

### System

NA

```[tasklist]
### Tasks
```

**Comment by ilenia-magoni** [comment]
The test right now is:
```
const hasFontFamily = new __helpers.CSSHelp(document).getCSSRules().some(x => x.style['font-family'] === 'Impact');
```
which constrict to a specific casing

it could be transformed into
```
const hasFontFamily = new __helpers.CSSHelp(document).getCSSRules().some(x => x.style['font-family'].toLowerCase() === 'impact');
```

---

Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e056bdde6ae6892ba2.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
