### ISSUE TITLE
Clarify Progress Reset Modal

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#53959]
The modal currently lists everything that will be reset in a single block of text:

<img width="681" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/0b5c5111-2649-44c7-a26f-d0415afdd7ba">

We should update this to be a bit more clear. Maybe a list:

<img width="675" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/4f81539e-8ec4-4ba4-85af-705df35f6759">

Verbiage can be discussed here, or iterated over in a PR to close this issue.

**Comment by SaintPeter** [comment]
It might make sense to include this in this proposed change #47464

**Comment by JBhrayn** [comment]
@naomi-lgbt I agree with you. I just have few suggestions, such as keeping the text short and adjusting the alignment of list.
Let me know what you think about this (and if I could make a PR on this too): 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/110586557/63872f11-4771-4431-9615-e73bedf63361)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/110586557/1b35bfe6-1bdb-4c07-953c-5ec60d45cbce)

**Comment by SaintPeter** [comment]
@JBhrayn That looks good.

I wonder if we should also add clarification to the Danger Zone area as well:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/553494/381a0ec4-7f8f-4cde-ac8d-566bfc22a3e7)

I don't like the idea that you have to push a really dangerous looking button to find out what it will do. We don't even say that there will be a confirmation modal. I was didn't even want to click it for testing, since I have a huge amount of stuff on my personal account.

**Comment by Sembauke** [comment]
Lets go with @JBhrayn idea.

**Comment by RavidYael** [comment]
Hey @naomi-lgbt , looking at the discussion about making the progress reset modal clearer, I'm thinking it could be a great 'first timers only' issue. What do you think?
