### ISSUE TITLE
Login/Avatar/Profile Edit Problem

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#54]
I have had issues after filling out my FCC public profile.
Test Settings: Windows 7 Firefox 32 bit
Bug Trigger: Filled out profile fields. Profile fields include Username(path to public profile), Twitter, Github, CoderByte, and LinkedIn.  
Bug Description: 
Avatar picture will not display.
Cannot login.
Cannot login even after resetting password.
Cannot edit Profile after first profile edit.
Bug Reproduction:
Could not reproduce with a secondary test account, bug only found with Nguyench@live.com.

Link with google, attached video of the bug.
https://drive.google.com/file/d/0B-94cRSEUQu_YkdvTTlaWEM4UGs/view?usp=sharing

**Comment by terakilobyte** [comment]
Can you try logging into fcc with your email all lowercased and see if it lets you in? I'm suspecting the capital N may be causing an issue since internally we are converting everything to lowercase.

If this proves to be the login issue I'll address it immediately. Some very strange behavior on the other stuff, I'll have to watch the video a few more times to see if I notice anything.

**Comment by QuincyLarson** [comment]
I talked with @crosscris and we think we've sorted this one out. We think it was a one-off problem due to a weird record from early on. We solved it on his account. No one else has brought this issue to our attention, so I'm closing this.
