### ISSUE TITLE
Run Test Button Broken

### ISSUE THREAD

**Issue by asgh09** [freeCodeCamp/freeCodeCamp#54031]
### Describe the Issue

Working on the Telephone Number Validator project and tried to click the 'Run the Tests' button as usual. Unfortunately, the button stopped running the tests. Went through the necessary steps necessary before reporting the bug and couldn't locate the 'local storage' because I didn't see that option. Refreshed the browser; tried another browser; and restarted my computer and I'm still having the same issue.  Maybe I clicked it too much?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-telephone-number-validator-project/build-a-telephone-number-validator

### Steps to Reproduce

1. Go to 'Build a Telephone Number Validator' project 
2. Scroll down on the column on the left side and Click on 'Run the Tests'
3. Wait for a while and realize that it will never actually run the test. 

### Expected behavior

Expected for the 'Run the Test' button to show a checkmark for all criteria that was met and an 'X' for all criteria that wasn't met. 

### System

Windows NT 10.0 Win64 x64
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0
Safari/537.36

### Additional context

N/A

**Comment by Re1nGer** [comment]
Small context addition: the tests work in incognito mode both on firefox and chrome, but only for unregistered users, once the user signs in , the test seem to run only once

**Comment by ilenia-magoni** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by asgh09** [comment]
Request to be reopened.

**Comment by ilenia-magoni** [comment]
@asgh09 have you opened a topic on the forum with your code first?

**Comment by asgh09** [comment]
It's not a code problem. The 'Run the Tests' button doesn't work. What does my code have to do with the 'Run the Tests' button not working at all?
    On Saturday, March 9, 2024 at 08:12:54 AM EST, Ilenia ***@***.***> wrote:  
 
 


@asgh09 have you opened a topic on the forum with your code first?

**Comment by ilenia-magoni** [comment]
The button will not run the tests if you have a syntax error, so please open a topic on the forum with the code you are trying to run
