### ISSUE TITLE
For HTML Image Waypoints remove self closing tags

### ISSUE THREAD

**Issue by zackforbing** [FreeCodeCamp/FreeCodeCamp#5406]
Challenge [Waypoint: Turn an Image into a Link](http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

the instructional text has a typo in the example image link code that may cause confusion:
```
<a href="#"><img src="http://bit.ly/fcc-running-cats"/></a>
```
should be:
```
<a href="#"><img src="http://bit.ly/fcc-running-cats"></a>
```
My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by raisedadead** [comment]
Hi @zackforbing,

As per you
`<a href="#"><img src="http://bit.ly/fcc-running-cats"` **/** `></a>` Incorrect
`<a href="#"><img src="http://bit.ly/fcc-running-cats"></a>` Correct

Is my understanding correct, about what you are saying?

What I feel is that the example is correct in the instructions, because the `img` tag should be closed as good coding practice.

But looking at the sample code in the editor window:
`<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">`
Its not closed.

Now its okay not to close the tag for `img` in HTML5 : Refer http://stackoverflow.com/a/14860596
in context of void elements in HTML5, Refer [this](http://w3c.github.io/html-reference/syntax.html#void-element) because `<img> NO CONTENT CAN GO HERE </img>`.

So, I am not sure what to do about this. Personally I feel we should **self-close** the `img` tag in the sample code in the editor and leave the example code in instructions as it is.

Lets wait for what others have to say? If opinions are in favor I can do the change, and do a PR.

**Comment by SaintPeter** [comment]
We might want to actually test to see if the "self closing" mark is present.  It may also make sense to explicitly mention it in a prior waypoint.

I propose that we update the tests (and possibly the description) in this waypoint to explictly mention and check for the self closing tag.

We should also update the text and tests of [Add Images to Your Website](http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website).

**Comment by BerkeleyTrue** [comment]
html5 void elements shouldn't have the extra slash. The slash in the img tag should be removed.

**Comment by SaintPeter** [comment]
Description updated.

So it is a "typo" and needs to be removed.

**Comment by AkiraLaine** [comment]
I'm on it :smile:

**Comment by raisedadead** [comment]
Great :+1: seems reasonable.

**Comment by decriminal** [comment]
Thanks
