### ISSUE TITLE
[python] password-generator-step-66 typo

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#54103]
### Describe the Issue

There is an example given in this lesson
```
def add(x, y):
    return x + y

spam(x=1, y=7) # 8
```

It looks like a typo, spam should be "add" to call the function

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-66

### Your code

```

NA

```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: NA
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase. This means that after the next deployment, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
