### ISSUE TITLE
Learn HTML by Building a Cat Photo - Step 56 BUGGED

### ISSUE THREAD

**Issue by HahaPlease** [freeCodeCamp/freeCodeCamp#54127]
### Describe the Issue

On Step 56 - 
The question does not mention anything about adding "name", however this is required for the solution which I only found later on through a forum.

I've replaced <> with ()

The actual answer which it does not accept-
(input id="loving" type="checkbox") (label for="loving")Loving(/label)

The only answer it accepts-
(input id="loving" type="checkbox" name="loving") (label for="loving")Loving(/label)

---------------

When it goes to Step 57 the equation automatically resets to its normal answer-
(input id="loving" type="checkbox") (label for="loving")Loving(/label)

And the solution to Step 57 is as following-
(input id="loving" type="checkbox" name="Personality") (label for="loving")Loving(/label)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-56

### Your code

(input id="loving" type="checkbox") (label for="loving")Loving(/label)

### Expected behavior

I expected it to be Correct but it gets bugged out and says its incorrect. Task 56 is bugged.

### System

Im using Windows 10

**Comment by Supravisor** [comment]
Hi @HahaPlease I just tried step 56 of the Cat Photo App practice project, and it worked fine.

If you want to post code, you can use back ticks.  If you can, try restarting your computer and attempt the step again.  Include screen shots of the error and hint messages.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
