### ISSUE TITLE
Make Tailwind CSS tutorials for practice frontend design 

### ISSUE THREAD

**Issue by nik132-eng** [freeCodeCamp/freeCodeCamp#54148]
### Is your feature request related to a problem? Please describe.

In the latest market, many companies are using tailwind as their main styling stack so as the developer gets he/she had work on it in freecodecamp-like platform it will be very beneficial for himself because the platform can provide more value to them.

### Describe the solution you'd like

we can add a track in the responsive design certification course.

### Describe alternatives you've considered

As a developer, you have to refer to docs of tailwind make projects and make document blogpost.

**Comment by jdwilkin4** [comment]
Hi @nik132-eng ! 

The team is currently working on the updates to the JavaScript certification. But when work begins on the Front End Libraries certification, there will be discussions on what should be included when talking about css libraries and frameworks.
Tailwind CSS will be one of those discusses at that time. 

For now, I am going to close this issue since it will already be discussed in future updates to the curriculum.
