### ISSUE TITLE
MathJax should be rendered on component level instead of on Render with Gatsby

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#54169]
### Describe the Issue

Gatsby in development works a bit differently than it does in production. Gatsby's `onRenderBody` returns a `pathName`, this `pathName` will return `/` on any subpath in development but returns the actual subpath in production. This has something to do with how the rendering and building works to save time in development. 

The function `isMathJaxAllowed` receives a pathname form Gatsby. Which will always be true for development, but not for production.

e.g: `[path_array].includes("/");`

See the following function:

```js
export const isMathJaxAllowed = (pathname: string) =>
  [
    '/learn/javascript-algorithms-and-data-structures-v8',
    '/learn/project-euler/',
    '/learn/rosetta-code',
    '/learn/scientific-computing-with-python'
  ].some(allowedPath => pathname.includes(allowedPath));
```

For example see http://localhost:8000/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-18 and check if MathJax is inject into the head.

I want to confirm this with a couple others before I jump to conclusions. The development environment has been showing a lot of different results.

**Comment by gikf** [comment]
`isMathJaxAllowed` is currently used only with Gatsby's SSR.
https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/gatsby-ssr.js#L34-L41 
https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/utils/tags.tsx#L57-L74
I'm not sure when exactly that's used in production, for development there's config option: https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/gatsby-config.js#L16
Setting it to `true`, will use SSR on every full reload.

Having said that, I wasn't able to confirm that during development `pathname` is always `'/'`. However `'/'` shouldn't matter, check is flipped, so with real values it's for example:
```javascript
'/'.includes('/learn/javascript-algorithms-and-data-structures-v8') //  false
```
- - -

Otherwise MathJax is loaded from `client/src/templates/Challenges/classic/editor.tsx`, if challenge has editable region: https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/src/templates/Challenges/classic/editor.tsx#L400-L406

- - -
Or from `client/src/templates/Challenges/components/side-panel.tsx`, with a bit rough check for block/SuperBlock:
https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/src/templates/Challenges/components/side-panel.tsx#L44-L48

- - -

For the `responsive-web-design/learn-html-by-building-a-cat-photo-app/step-18` it would be loaded because of editor, not the SSR.

**Comment by Sembauke** [comment]
So any conclusions? Is this the desired behavior?
