### ISSUE TITLE
Typo on Step 61 of Sudoku Solver project in Scientific Computing with Python (Beta) cert

### ISSUE THREAD

**Issue by friendlyseal** [freeCodeCamp/freeCodeCamp#54250]
Typo on Step 61 of Sudoku Solver project in Scientific Computing with Python (Beta) cert: "withing" in the hint text when I'm sure you meant "within". 

<img width="595" alt="Screen Shot 2024-03-21 at 1 39 54 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/94906150/b240b221-b493-4b75-9a1d-cd2948ec6d93">

Thanks for all the content!

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/6569e481e67f123ad25c5d20.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
