### ISSUE TITLE
Update step 1 of cafe menu project

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#54338]
### Describe the Issue

It took me an embarrassing amount of time to get this right without googling. We should not require the whole Doctype thing right off the bat imho. 

If we require it, we should have a hint that is more explicit so people don't get stuck here. 

For many people visiting /learn, they may skip straight to this project and we want them to have a smooth entry.
<img width="1081" alt="Cursor_and_Learn_Basic_CSS_by_Building_a_Cafe_Menu__Step_1___freeCodeCamp_org" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/985197/d57c10f0-b8a9-4350-ba68-f1fea27f8d1c">

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-1

### Your code

```



```

### Expected behavior

It shouldn't be so frustrating

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
At a quick glance, it looks like most projects have campers build out the HTML boilplate starting with the doctype each time.

Here are some first steps from other projects

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-1

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-1

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-1

Personally, I vote to provide the HTML boilerplate for each project and have them add in the link for the styles sheet and write the code for the body. 

Because normally, you would never write this on your own. You would just use the keyboard shortcuts in VS code(or whatever editor of choice) to generate that boilerplate for you. Or you would be working on project that has this setup already. So I am not really sure I see the point in having campers write it out each time. But I would love to hear from the rest of the team. 

If we do decide to provide the HTML boilerplates for them, then the new first steps of the project would look like this:

<img width="699" alt="Screenshot 2024-04-09 at 3 41 27 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/9bb4c309-5c85-4bac-9385-040e254c65bb">

Curious to hear thoughts from the rest of the team

**Comment by Supravisor** [comment]
`<DOCTYPE html>` is the foundation of html.
Boilerplate code this early in the certification makes it too easy, and does not instil good coding practice.

I'm for more explicit instructions, or hints.
Boilerplate code after the second or third project is okay.

**Comment by jdwilkin4** [comment]
> Boilerplate code this early in the certification makes it too easy

That might actually be a good thing considering the activity I have seen on the forum around the first project. Campers might need an easier learning curve in the beginning. 

> I'm for more explicit instructions

Step 1 for the cafe menu could be changed to this essentially

````html
As you learned in the last few steps of the Cat Photo App, there is a basic structure needed to start building your web page. Every HTML project should have a `DOCTYPE` declaration and `html` element. The `DOCTYPE` tells the browser which version of HTML the document is in. And the `html` element represents the root element which contains all other elements.

```html
<!DOCTYPE html>
<html lang="en">
<!--all other elements go here-->
</html>
```

Add the `<!DOCTYPE html>` tag, and an `html` element with a `lang` attribute of `en`.
````

> Boilerplate code after the second or third project is okay.

I think one project to learn it (cat photo app) and one project for review(cafe menu) should suffice IMO. Because you would almost never write out a HTML boilerplate on the job. You would either join an existing project or work on a greenfield project  where you are probably using some sort of UI framework that generates the boilerplate for you. 

Normally I am all for repetition for the sake of learning. But here I question how much repetition we need for boilerplate code, that you would never write out yourself anyway.

**Comment by ilenia-magoni** [comment]
The issue I have seen most often for this step on the forum, is people not adding a closing `</htm>` tag. I think we could try to keep this as one step and have hints that are more granular and help guide better toward the complete boilerplate

**Comment by jdwilkin4** [comment]
Let's go with this update to the description and hints

````md
# --description--

In this project, you will learn the basics of CSS(Cascading Style Sheets) by building a cafe menu. CSS is the language used to style an HTML document. It describes how HTML elements should be displayed on the screen.

As you learned in the last few steps of the Cat Photo App, there is a basic structure needed to start building your web page. Every HTML document should have a `DOCTYPE` declaration and `html` element. The `DOCTYPE` tells the browser which version of HTML the document is in. And the `html` element represents the root element which contains all other elements.

```html
<!DOCTYPE html>
<html lang="en">
<!--all other elements go here-->
</html>
```

Add the `<!DOCTYPE html>` tag, and an `html` element with a `lang` attribute of `en`.

# --hints--

You should have the `<!DOCTYPE html>` declaration.

```js
assert(code.match(/<!DOCTYPE html>/i));
```

You should have an opening `<html lang="en">` with the language set to english.

```js
assert(code.match(/<html\s+lang\s*=\s*('|")en\1\s*>/gi));
```

You should have a closing `</html>` tag.

```js
assert(code.match(/<\/html>/i));
```
````

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f33071498eb2472b87ddee4.md

Happy coding
