### ISSUE TITLE
Doing Step 6 of basic Java confused on my mistake here.

### ISSUE THREAD

**Issue by KenyanH12** [freeCodeCamp/freeCodeCamp#54429]
### Describe the Issue

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/166903470/032c3410-4536-477c-ad20-92d5188d20b6)
The test states I need to add a semicolon and define xp, but I've place quotation marks around it and ended it with a semicolon I'm very confused.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-6

### Your code

```
let camperbot = "xp";


```

### Expected behavior

I don't know how to answer this.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by a2937** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
