### ISSUE TITLE
Changes made to challenge files does not show up while running FCC locally

### ISSUE THREAD

**Issue by natac13** [FreeCodeCamp/FreeCodeCamp#5445]
I have started fresh by first deleting my FCC repo. Re-cloned and get the app launching locally.
The challenges display. However when I got to make changes to the .json files and run `node seed` then `gulp` I do not see the changes in the local app. 
Please note I have even tired to change the display function call to the tail property. Again this does not show up in. 
Am I not suppose to run `node seed` after changes any more. I believe I have tired this by just running gulp and making changes to the files while the app in running locally. However still no change.

![fccchallengechange](https://cloud.githubusercontent.com/assets/10660283/12003921/6d166704-ab01-11e5-9efb-707a9de9aab8.png)

![fccnochange](https://cloud.githubusercontent.com/assets/10660283/12003920/6d164800-ab01-11e5-9269-f59614f6d0bb.png)

**Comment by SaintPeter** [comment]
Three things:

1. If you make a change to the title of a waypoint you will need to re-`node seed`, because the Challenge Map is not loaded dynamically and the titles map directly to the loaded challenge.  
All other changes to a bonfire should be available as soon as you refresh the page that it's on.
2. Note that changing the `challengeSeed` does *not* automatically clear your `localStorage` copy of the `challengeSeed` that is displayed on the screen.  The process that keeps you from losing your code on a page refresh causes the original code to display.   
Click the "Reset" button and "Clear Code" to force a re-load of the `challengeSeed`
3. You may just be using this challenge as an example, but note that I have completely revamped almost all of the challenges in `basic-javascript.json` and all PRs against it will be rejected until it goes live in a few days.

**Comment by natac13** [comment]
@SaintPeter You are a Wizard! Thank you so much! The process to contribute is so much easier now!! Getting this back working I now feel I should re write the [contribute wiki](https://github.com/FreeCodeCamp/wiki/blob/master/Contributions-Guide---with-Typo-Demo.md) I wrote to reflect these changes.

**Comment by SaintPeter** [comment]
@natac13 That would be awesome - anything we can do to make this process easier for others is a win!
