### ISSUE TITLE
Javascript Curriculum should alert camper that they're trying to print the page 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#54487]
### Describe the Issue

It's not exactly common, but it's an extremely easy mistake to make. In Python, you would use the `print` function to print things out. However in our JavaScript lessons; it prompts the camper to print out the current page they're in within the curriculum. There should be some kind of universal check tied to this type of challenge that determines if the code in the challenge contains the `print` function instead of `console.log`. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-4

### Your code

```
print("This is a test"); 
```

### Expected behavior

Rather than the print page prompt showing up, the test once evaluated should tell me that I've made a mistake and should be using `console.log`. 

### System

- Device: Desktop 
- OS: Windows 10 
- Browser: Firefox
- Version: 125.0.2 

### Additional context

Appears on this thread.

https://forum.freecodecamp.org/t/stuck-on-step-32-print-i-is-going-to-my-printer/686617

**Comment by naomi-lgbt** [comment]
Interesting. I'm not a fan of overwriting the built-in `print`, personally.

**Comment by Sembauke** [comment]
Hey @a2937,
Thanks for bringing this to our intention. I think this is mostly because the user is new to programming. We should allow them to make mistakes!

We already have an example in the instructions of how to "print" something to console. I do not think we can make it any easier without over-engineering the test evaluator.

Thus I am closing this as not planned. Feel free to reopen if you feel like doing so.
