### ISSUE TITLE
Add hint to remember `this` keyword for step 48 of shopping cart project

### ISSUE THREAD

**Issue by juancaorg** [freeCodeCamp/freeCodeCamp#54602]
### Describe the Issue

When working through the [Shopping Cart Step 48](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-48), mentions the following:

> Declare a variable tax and assign it the value of calling your new .calculateTaxes() method, passing subTotal as the argument.

And when passing the following solution:

```js
calculateTotal() {
  const subTotal = this.items.reduce((total, item) => total + item.price, 0);
  const tax = calculateTaxes(subTotal);
}
```

This hint shows up:

> Assign the value of calling your new .calculateTaxes() method, passing subTotal as the argument, to the tax variable.

This doesn't pass because is expecting the following:

```js
calculateTotal() {
  const subTotal = this.items.reduce((total, item) => total + item.price, 0);
  const tax = this.calculateTaxes(subTotal);
}
```
I think adding the hint "Remember to use the `this` keyword." is a valid hint, just like in [step 49](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-48) when the `this` keyword is not added in the solution.

It may be repetitive, but I think the user should be informed for this possible mistake. It's already in other steps anyway.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-48

### Your code

```js
calculateTotal() {
  const subTotal = this.items.reduce((total, item) => total + item.price, 0);
  const tax = calculateTaxes(subTotal);
}
```

### Expected behavior

When passing the incorrect code from the above, add the "Remember to use the `this` keyword." hint and validation.

### System

- Device: Laptop
- OS: macOS 13.6.6
- Browser: Chrome
- Version: 124

**Comment by jdwilkin4** [comment]
We can open this up to `first timers only` since this is a small change

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-oop-by-building-a-shopping-cart/63f03686c5ea863533ec71f4.md
## changes that need to be made

Change the last hint to be the following

```md
Assign the value of calling your new `.calculateTaxes()` method, passing `subTotal` as the argument, to the `tax` variable. Remember to use the `this` keyword.
```

Happy coding

**Comment by MrGliff** [comment]
I can do it!
