### ISSUE TITLE
rewording suggestion for step 26 learn introductory javascript by building a pyramid generator

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54743]
### Describe the Issue

first discussed on the forum here: https://forum.freecodecamp.org/t/ambiguous-wording-in-learn-introductory-javascript-by-building-a-pyramid-generator-step-26/689842

I had a concern about the starting sentence of step 26 of the js pyramid project here: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-26

It starts out with: "The let keyword allows a variable to be reassigned." which I think can be misinterpreted to mean that we can use the `let` keyword to reassign a variable. I believe a reword to "Declaring a variable with the let keyword allows it to be reassigned." will be not as easy to misinterpret. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-26

### Your code

N/A

### Expected behavior

slight reword to instructions needed as per above

### System

N/A

**Comment by lasjorg** [comment]
Seems like a good change.

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

### File that needs to be changed:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f165270622fd4ec0da3f7.md

### Change needed:

From:

```md
The `let` keyword allows a variable to be reassigned.
```

To:

```md
Declaring a variable with the `let` keyword allows it to be reassigned.
```

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
