### ISSUE TITLE
typo in step 4 of js beta review project for building a gradebook app

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54826]
### Describe the Issue

When invalid code is submitted to step 4 of the gradebook app review project, a message is shown which has a typo. "Your studentMsg function should return a the correct ..."

Please remove the `a`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-js-fundamentals-by-building-a-gradebook-app/step-4

### Your code

just click submit without typing anything to trigger the error message display

### Expected behavior

pls correct the typo

### System

N/A

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/6626b8dcf5057f896f948440.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Sayalikukkar** [comment]
Hi @gikf, I am intrested to work on this, Can I start?

**Comment by thejon07** [comment]
iam interested to working in this issue please assign me

**Comment by gikf** [comment]
Hey @Sayalikukkar, @thejon07

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by Jaiharishan** [comment]
Hi, can I take up this issue? I am new to open source so looking to start with some small contributions.

**Comment by jdwilkin4** [comment]
@Jaiharishan 

We do not assign issues except to long time contributors and members. 

please read through this not here on contributing
https://github.com/freeCodeCamp/freeCodeCamp/issues/54826#issuecomment-2114822238
thanks

**Comment by bhusal-rj** [comment]
@jdwilkin4 
I have created a PR #54846 for the issue.
Waiting for your feedback. Thank you!
