### ISSUE TITLE
SCWP(Beta) - Learn Classes and Objects by Building a Sudoku Solver - Step 73: Accepting wrong solution

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#54886]
### Describe the Issue

The step asks for a **list comprehension**, but the following code is accepted as a solution (with parenthesis): 
`row_str = (str(i) for i in row)`

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/step-73

### Your code

```
def __str__(self):
        board_str = ''
        for row in self.board:
            row_str = (str(i) for i in row)
```

### Expected behavior

I _believe_ the step must only accept the list comprehension with square brackets []:
`row_str = [str(i) for i in row]`

### System

- Device: Laptop
- OS: Windows 11
- Browser: Brave
- Version: 1.64.116

**Comment by Dario-DC** [comment]
Thank you for reporting this issue. I don't think this is a huge problem, since the code works well with a generator expression too. However, since the instructions are asking for a list comprehension, it makes sense to fix the test.

The helpers do not discriminate between the various comprehension types, so I'd import the `ast` module and check if the value of the `row_str` variable is an instance of `ast.ListComp`. This additional check should take place within  [this test](https://github.com/freeCodeCamp/freeCodeCamp/blob/4811993716394a263de6a344abf744ed3cb199ad/curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/660ac35d55a15d81afdedd76.md?plain=1#L20-L24)
