### ISSUE TITLE
Cracking the coding interview section for FreeCodeCamp

### ISSUE THREAD

**Issue by sol-flex** [freeCodeCamp/freeCodeCamp#54881]
### Is your feature request related to a problem? Please describe.

It would be great to create an interview prep section for FreeCodeCamp which mirrors the Cracking the Coding Interview content.

### Describe the solution you'd like

I'd like to see a section that goes through the content of the Cracking the Coding interview book. 

### Describe alternatives you've considered

n/a

**Comment by jdwilkin4** [comment]
In a situation like this, we would probably have to get permission from the author.

The book has been out for a while now, and I haven't seen any other interactive courses based exclusively on her material. 
So that might be a roadblock and it might be possible that we wouldn't be able to do something like this.

**Comment by jdwilkin4** [comment]
But also, a lot of the problems used in the book are pretty similar if not pretty close to what you can find in the existing interview prep section here 

https://www.freecodecamp.org/learn/coding-interview-prep/

**Comment by naomi-lgbt** [comment]
I'm going to go ahead and close this.

[Rosetta Code](https://rosettacode.org/wiki/Rosetta_Code:Copyrights) and [Project Euler](https://projecteuler.net/copyright) are both under permissive licenses. Since Cracking the Coding Interview is not under a similar copyright, we can't really use it in our curricula.
