### ISSUE TITLE
[Building a Cafe Menu] Clarify what `text-align` does in step 11 and 12

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55018]
## Description

In step 11 and 12 of Building a Cafe Menu, we ask the users to use `text-align: center` to:

> Center your `h1` element

or

> Center the `h2` and `p` elements

But what the property does is centering the elements' _content_, rather than the elements themselves.

This is minor, but I think we should update the wording to be clear.

## Affected pages

- https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-11
- https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-12

## Suggested changes

Perhaps changing the instructions to:

```md
Center the content of your `h1` element...
```

And 

```md
Center the content of the `h2` and `p` elements...
```

**Comment by lasjorg** [comment]
Seems like a good change to me.

---

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f344f9c805cd193c33d829c.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3477ae9675db8bb7655b30.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
