### ISSUE TITLE
Long loops with console log output causes "out of memory" crash

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55016]
### Describe the Issue

The context for this issue is this forum thread.

https://forum.freecodecamp.org/t/potential-website-crash-do-to-infinite-loop-on-step-64-and-65-of-the-pyramid-generator/692412

The infinite loop does make the loop protection kick in, but the browser will still crash with an out of memory error.

I suspect it is the console log output because it happens with finite loops as well, just as long as they run for long enough. Also, if I switch to `console.dir` so it only outputs to the browser console, the code runs without crashing.

Reproduction step (⚠️this will crash your browser):

Go to

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-64

Set `count` to `4000`

To verify it is the output, change the bottom `console.log` in the code to `console.dir` and run the same code again.

---

Not sure if the loop protection can be dynamic depending on what code is executed?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8

### Your code

```



```

### Expected behavior

To not exhaust memory before loop protection kicks in.

To not crash from rendering large amounts of text.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ojeytonwilliams** [comment]
> Not sure if the loop protection can be dynamic depending on what code is executed?

Not easily, no, but we could change the timeout on a per-test basis. It would need to be very small, though, since 4000 loops takes about 4 ms on my machine, so we're talking 2 - 3 ms timeouts.

However, given how tiny it is, it's possible (depending on ratio of CPU to memory, number of tabs people have open etc. etc.) that some people's machines will simply crash no matter what value we pick. Hard to say.

This might be something that's better addressed via instructions, rather than loop-protect.

**Comment by lasjorg** [comment]
I guess there are two separate things here.

- The rendering crashing the browser.
  - The browser shouldn't crash from printing to the "console" with finite loops that otherwise wouldn't crash. I mean, if this was just a React app with a 4000 iteration loop rendering a bunch of characters and spaces to the page, it wouldn't crash with "out of memory". Surely there is something going on here that isn't right.

- The loop protection.
  - I don't think the loop protection is the solution here. The fact is, the loop protection can kick in, but the page still crashes. I was just wondering if the "real" problem can't be solved if the loop protection could help guard against the crash.

**Comment by naomi-lgbt** [comment]
Hmm, could we have the loop protection clear the console?

**Comment by lasjorg** [comment]
I haven't tested it, but I suspect by the time the loop protection kicks in it is too late.

This seems like a render bug. I don't see why rendering the console output should cause an out of memory crash.

**Comment by ojeytonwilliams** [comment]
Yeah, that's right, loop protection isn't going to be much help here. It normally kicks in at 100ms, but even if `count = 30000` the computation of `result` takes ~ 15ms. When `count = 4000` it's more like 3ms. And all that's specific to my machine. It might work, but I'm not convinced it's the way to go.

I also agree that there's an issue with the platform, simply because codepen does a lot better. It _does_ use a lot of memory and eventually it tries to produce a string longer than V8 can handle, so the code fail, but it can handle a count of 20,000, while ours can't.

That said, I think the pragmatic fix is to restructure the lessons to avoid laying traps for learners. For example, if we comment out `rows.push(padRow(i + 1, count));` during a prior lesson, then loop protection is enough. They'll get the warning, but the browser should be fine. This allows us to explain about infinite loops and how easy it is to create them while making it unlikely that learners write code that we can't protect them from.

**Comment by lasjorg** [comment]
Would it be possible to truncate the output somehow? I notice in Chrome it limits the log, and it has a show more badge.

![chrome-truncated-log](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/8c2c4939-2472-44bb-a0fd-fbfc6aed8761)

---

Not sure, but the layout might somehow be involved. I messed around with the `react-reflex` props to see if it changed anything and at one point got it to render 10,000 logs, but if I then resize using the splitter it crashes with `RESULT_CODE_HUNG`. If I look at the performance logs, most of the time is spent in Layout, and it warns about "Forced reflow". If you use the splitter after a smaller loop, like 800 it is still pretty laggy, and I can hear my fans spin up.

**Comment by ojeytonwilliams** [comment]
> Would it be possible to truncate the output somehow?

That's a good idea and, yes, that's possible. I think it would be fine to simply truncate it for now, rather than implementing "show more". We can make the cut-off high enough that most people won't be affected.

> Not sure, but the layout might somehow be involved. 

That makes sense. There's really not much going on, React-wise, except that the iframe is embedded in a ReflexElement.

**Comment by ojeytonwilliams** [comment]
Sounds good!  Here's a summary of how I think we should proceed:

* The output needs to be truncated if it exceeds 500,000 characters.
* When truncated it should say "Logs truncated. See browser console for more".
