### ISSUE TITLE
Learn Recursion by Building a Decimal to Binary Converter - Step 1: Wrong element mentioned

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#55020]
### Describe the Issue

- In the last phrase, it is mentioned a `<h2>` element with `id="result"`, but only an `<output>` element has `id="result"`:

> "(...) and the `h2` element with the (...)."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-1

### Your code

.

### Expected behavior

- Rectify to the following:

> "(...) and the **`output`** element with the (...)."

### System

.

**Comment by lasjorg** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

Change `h2` to `output` in the markdown file.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-recursion-by-building-a-decimal-to-binary-converter/63db7f4677d06d7500a13321.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by gikf** [comment]
I think the backticks on the `h2`/`output` can be dropped while changing this. Other elements mentioned in the paragraph are not backticked.

**Comment by lasjorg** [comment]
But the question is, shouldn't they be?

I think they should, to be consistent with the rest of the curriculum. We use backticks with element types.

**Comment by gikf** [comment]
To be honest I'm not sure what's the current convention, when element type (button/input/output) itself is not actually used in code. This might be also the only project explicitly naming them in description, instead of referring to them via id.

**Comment by lasjorg** [comment]
Then I feel like the elements shouldn't be mentioned at all. If we mention the element type, I think the types should have backticks.

But I guess I can see your point, and I'm not sure what the convention is here.
