### ISSUE TITLE
Python Scientific Computing: Budget App Chart Unit Test Issue

### ISSUE THREAD

**Issue by 509dave16** [freeCodeCamp/freeCodeCamp#55025]
## Summary
Either the expected representation is wrong or the wording of the Budget App project is misleading. My assumption was the "o"s represent how much has been spent. So if you spent $200 out of $1000 deposited, you would see a "o" on lines for 20, 10, and 0. But even if it was the opposite as in how much is left in a budget category, that doesn't explain how 30% is spent on food when 900 was deposited and 105.55 was withdrawn. That rounds down from ~12% to 10%.

https://github.com/freeCodeCamp/freeCodeCamp/blob/680b319cea4cf0457640e5cbab31032a8c3bba15/curriculum/challenges/english/07-scientific-computing-with-python/build-a-budget-app-project/budget-app.md?plain=1#L734-L742

## Received(by my code)
![Screenshot 2024-05-29 at 4 48 10 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/2925882/7bc04edd-be93-46da-909a-936455c20d15)

## Expected(according to unit test)
![Screenshot 2024-05-29 at 4 50 30 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/2925882/80cd386c-61b9-4d2b-a1b8-3155088b53fe)

**Comment by gikf** [comment]
Thank you for reporting this issue.

Per the description:
> The chart should show the percentage spent in each category passed in to the function. The percentage spent should be calculated only with withdrawals and not with deposits.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
