### ISSUE TITLE
Learn Recursion by Building a Decimal to Binary Converter - Step 104: Typo

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#55021]
### Describe the Issue

- In the first paragraph, on the 2nd phrase, you can read:

> "(...). Now you can get those **the** paragraph elements (...)."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-104

### Your code

.

### Expected behavior

- Rectify to the following:

> "(...). Now you can get **those paragraph elements** (...)."

### System

.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-recursion-by-building-a-decimal-to-binary-converter/6464ad3c9b2e6cf58224cfa9.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by lasjorg** [comment]
I would suggest we remove "those" and keep "the" so we are not repeating "those".

I would also suggest using "attribute value"

> You used the `inputVal` property as the `id` attribute value for your paragraph elements. Now you can target the paragraph elements with those `id`s.

**Comment by lasjorg** [comment]
The next paragraph reads pretty bad as well. It's just confusing to read. Maybe we can come up with something better.

> You set the `id` attribute value for your paragraph elements to the `inputVal` property.
> 
> Now, use `getElementById` to select the element with that attribute value using the `inputVal` property.

Or something like that?

**Comment by andrebdinis** [comment]
I know the first line already mentioned "paragraph elements", so it is presumed that the second line is referring to that type of element. But as a newbie, when I read "to select the element with that attribute value", it seems any kind of element.

Could we be more specific, and edit to "(...) to select the **paragraph** element (...)"?

> You have set the `id` attribute value for your paragraph elements to the `obj.inputVal` property.
> 
> Now, use `getElementById` to select the paragraph element with that attribute value, again using the `obj.inputVal property`.

**Comment by lasjorg** [comment]
> when I read "to select the element with that attribute value", it seems any kind of element.

It is selecting by `id` so the element type doesn't matter. Saying what the element type is seems redundant to me.

But if you or anyone else feel it would make it more clear, then I wouldn't be opposed to it.

**Comment by andrebdinis** [comment]
Yes, you are right. Mentioning `id` is what matters.
