### ISSUE TITLE
Legacy Python For Everybody - More Conditional Structures

### ISSUE THREAD

**Issue by Stephen-254** [freeCodeCamp/freeCodeCamp#55053]
### Describe the Issue

No correct answer in the code snippet, the exercise provided.

### Affected Page

https://www.freecodecamp.org/learn/python-for-everybody/python-for-everybody/more-conditional-structures

### Your code

```
temp = "5 degrees"
cel = 0
fahr = float(temp)
cel = (fahr - 32.0) * 5.0 / 9.0
print(cel)


```

### Expected behavior

I expect after execution, the code to produce the correct answer.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by arnav177** [comment]
The code attempts to convert a string containing non-numeric characters ("5 degrees") to a float, which raises a ValueError. As a result, the exception is caught, and the error message "Error: Could not convert temp to float" is printed. Since the conversion fails, the variable cel remains at its initial value of 0. The final output of the program is:
Error could not convert temp to float 0

**Comment by gikf** [comment]
Other than changing `cel = 0` to `cel = None`, there isn't much that can be done.

Example is a bit abstract, but to make `cel` at the end the right converted temperature, it would need something like:
```python
temp = "5 degrees"
cel = 0
try:
    fahr = float(temp)
except ValueError:
    fahr = 5.
cel = (fahr - 32.0) * 5.0 / 9.0
print(cel)
```
Which is a bit pointless, since it's clear that attempt to convert `temp` string to `float` will cause exception, in which case `fahr` is basically manually set to the right value.

**Comment by ssparser** [comment]
`temp = "5 degrees"

try:
  value = float(temp.split()[0])
except ValueError:
  print("Invalid temperature format")
  exit()

if temp.endswith("degrees"):
  unit = temp.split()[-1].lower()
  if unit in ("celsius", "c"):
    print(value)
  elif unit in ("fahrenheit", "f"):
    celsius = (value - 32.0) * 5.0 / 9.0
    print(celsius)
  else:
    print("Invalid unit:", unit)
else:
  print(value, "degrees Celsius")`

1. Splits the input string and converts the first part (assumed value) to a number. Checks if it ends with "degrees".
2. Prints the value directly if the unit is Celsius (case-insensitive).
3. Converts Fahrenheit to Celsius (if unit matches) and prints the result. Prints an error message for other units.
4. Assumes Celsius and prints the value with a message if no unit is provided.
5. Handles conversion errors (like "five degrees") using a try-except block (not shown in the 5 lines).

**Comment by ilenia-magoni** [comment]
I am not sure what change is being discussed here, the question asks which lines need to be in a `try` block to avoid an error being thrown, and that is line 3 because of trying to convert a string to float and then also line 4 as it uses the variable created on line 3
```py
temp = "5 degrees"
cel = 0
try:
    fahr = float(temp)
    cel = (fahr - 32.0) * 5.0 / 9.0
print(cel)
```

So the correct answer of 3,4 is present between the options.

**Comment by gikf** [comment]
> I am not sure what change is being discussed here, the question asks which lines need to be in a `try` block to avoid an error being thrown, and that is line 3 because of trying to convert a string to float and then also line 4 as it uses the variable created on line 3

As I understand it, the raised issue brings to attention fact, that once lines `3` and `4` are in the `try/except` block, the printed number - `0` - is _incorrect_, as that's not what `5` Fahrenheit degrees is in Celsius.

**Comment by naomi-lgbt** [comment]
> As I understand it, the raised issue brings to attention fact, that once lines 3 and 4 are in the try/except block, the printed number - 0 - is incorrect, as that's not what 5 Fahrenheit degrees is in Celsius.

That's the expected behaviour, though. When lines three and four are wrapped in a try, line 3 throws an error and line 4 is not executed. So the `cel` value does not get overwritten and is in fact still 0.

I don't see anything that really needs to be changed here. If we insist on it, I could go for what was proposed earlier:

> Other than changing cel = 0 to cel = None

**Comment by VPYen** [comment]
I think I agree here that this is a non-issue. The issue was already raised once before, the question for this problem is not surrounding if the correct output is the conversion to Celsius but which lines should be placed in a try block. Although, to clarify the challenge question, maybe the response in issue #55107 can be used- (ie. change question from `Which line/lines should be surrounded by try block?` to `which lines should be put into the try block to make code execute without exceptions.`). I think changing the question to the latter; however, gives away too much of the answer. Even as it stands the question is not faulty.
