### ISSUE TITLE
Learn Advanced Array Methods By Building A Statistics Calculator - Step 32: Confusing Phrase

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#55137]
### Describe the Issue

Confusing phrase:
- "Inside your `getMode` function, on the empty line above your return call `forEach` on `array`. (...)"

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-32

### Your code

.

### Expected behavior

I believe it is better understood by (1) placing an extra comma (,), and maybe (2) placing backticks (``) on the "return", like the following:
- "Inside your `getMode` function, on the empty line above your `return`, call `forEach` on `array`. (...)"

**NOTE:** The problem was: I was keep reading "above your return call", and then "`forEach` on array", and it wasn't making any sense to me. I had to read multiple times until I get it, to separate "return" from "call `forEach`".

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in codebase - #55106. This means that the next time latest codebase changes will be pushed to production, this problem should be fixed. Because of this, we're closing this issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
