### ISSUE TITLE
Learn Functional Programming by Building a Spreadsheet - Main menu description

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#55138]
### Describe the Issue

- I believe we should improve the final phrase:
"This project will cover concepts like the `map()` method, `find()` method, `parseInt()`, the `includes()` method."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/

### Your code

.

### Expected behavior

- Change it maybe to this:
"This project will cover concepts like the `map()`, `find()`, `parseInt()`, and `includes()` methods."

### System

.

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by MuhammadZariyanAsif123** [comment]
Hi,
Hope you are doing great.
I would like to work on this.

**Comment by ilenia-magoni** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by MuhammadZariyanAsif123** [comment]
The bug has been resolved.

I have created a pull request. 

Please verify.
