### ISSUE TITLE
step 74 of Build a Music Player (JS Beta) has incorrect statement

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55390]
### Describe the Issue

In the instructions for step 74 of the build a music player JS beta project, the statement is made:
" For the value, use a ternary to set song?.title to Play ${song.title} or "Play" if there's no song.title available."

I think this should be changed to:
"For the value, use a ternary to set the aria-label value to `Play ${song.title}` or `"Play"` if there's no `song.title` available."

The reason for the change is that the original sentence seems to suggest that the 'song?.title' is to be changed which is not true.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-74

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by lasjorg** [comment]
This does need to be changed. But we need the optional chaining for `song?.title` in the text.

Another option:

> Using a ternary, set the attribute value to `Play ${song.title}` or `"Play"` if `song?.title` is not available.

**Comment by lasjorg** [comment]
This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

File:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6555de565387a2efe90a6ccc.md

Change this part of the text:

```md
For the value, use a ternary to set `song?.title` to `Play ${song.title}` or `"Play"` if there's no `song.title` available.
````

To:

```md
Using a ternary, set the attribute value to `Play ${song.title}` or `"Play"` if `song?.title` is not available.
````

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Anyona-00** [comment]
Just submitted my first pull request.
