### ISSUE TITLE
Bonfire Exact Change compiler error

### ISSUE THREAD

**Issue by stevaras** [FreeCodeCamp/FreeCodeCamp#5543]
I have the same problem as this person had...! https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1653

My code returns the expected answer but the specific 2 tests fail :(

**Comment by ltegman** [comment]
You need to provide us with the code you think should be passing in order for us to help you. Not a screencap of the editor, but copy of the code in text, formatted with markdown.

**Comment by stevaras** [comment]
it's kinda messy the code but here it is ... 
```javascript
function drawer(price, cash, cid) {
  var change=[];
  var dif = (cash-price).toFixed(2);
  var i;
  var value=[0.01,0.05,0.1,0.25,1,5,10,20,100];
  var arr_test=[];
  var sum;
  var backup = JSON.parse(JSON.stringify(cid));
  var index_minus=[];
  var minus=[];
  var leftover=dif;

  function a(diaf) {
  var test=[];
  for (var i=0;i<value.length;i++){
    if ((diaf/value[i])>=1)
      test.push(parseInt(diaf/value[i]));
   // else
    //  test.push(0);
  }
    return test;
}

var upoloipo=0;
 
for (i=0;i<cid.length;i++){
    upoloipo+=cid[i][1];
}  
  upoloipo=upoloipo.toFixed(2);

 if (upoloipo-dif<0)
    return 'Insufficient Funds';

  
arr_test=a(dif);
var tessss=[];
var testtest;  
  
  for (i=arr_test.length-1;i>-1;i--){
    
    tessss.push(i);
    if (arr_test[i]>=1){
      
      sum=(arr_test[i]*value[i]).toFixed(2);

      if (cid[i][1]-sum>0){
    
        leftover=(leftover - sum).toFixed(2);
        cid[i][1]=(cid[i][1]-sum).toFixed(2);
        index_minus.push(i);
        minus.push(sum);
        testtest=[cid[i][0],sum];
        change.push(testtest);
        //change.push(cid[i][0],sum);
        // Array.prototype.push.apply(change, [cid[i][0],sum]);
        
      }
      else {
        
        leftover=(leftover - cid[i][1]).toFixed(2);
        minus.push(cid[i][1]);
        testtest=[cid[i][0],cid[i][1].toFixed(2)];
        change.push(testtest);
       //change.push(cid[i][0],cid[i][1].toFixed(2));
       //Array.prototype.push.apply(change, [cid[i][0],cid[i][1].toFixed(2)]);
        cid[i][1]=0;
        index_minus.push(i);
       
      }
      if (leftover==0)
        break;
      else{
        arr_test=a(leftover);
       // i=arr_test.length-1;
      }
    }
  }
  
  if (leftover!=0){
    cid=backup;
    return 'Insufficient Funds';
  }

  upoloipo=0;
 for (i=0;i<cid.length;i++){
   upoloipo+=cid[i][1];
  }  

if (upoloipo==0)
  return 'Closed';
  // Here is your change, ma'am.
  return change;
}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

drawer(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);
```

**Comment by raisedadead** [comment]
Okay I tested your code, the logic seems correct since its returning the required output as per the test cases:

`drawer(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]])` should return `[["QUARTER", 0.50]]`

and

`drawer(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]])` should return `[["TWENTY", 60.00], ["TEN", 20.00], ["FIVE", 15], ["ONE", 1], ["QUARTER", 0.50], ["DIME", 0.20], ["PENNY", 0.04]]`

However, digging deeper, and debugging the code, I found that the 2D array that the `function drawer` is returning is:

![1](https://cloud.githubusercontent.com/assets/1884376/12051892/4e207506-af2f-11e5-93ac-1a6c5dcbef5f.PNG)

The point to note is **"0.50"** is a string in your array. While the test case are looking for decimals **0.50**.

Of course the first element, i.e `"QUARTER"` has to be string, but the second element `0.50` has to be number.

Now you are using [Number.prototype.toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed), if you go through the docs it says, that it returns a formatted string.

> Returns
> A **string representation of numObj** that does not use exponential notation and has exactly digits 
> digits after the decimal place.

Well I don't have a solution for you right now, but I hope this analysis helps in someway, either in making your code work, or changing the test case.

BTW, its indeed a complex challenge... LoL took me a while to understand! Nice One! :smile:

**Comment by ltegman** [comment]
@raisedadead is correct. Thanks and happy coding!

**Comment by stevaras** [comment]
@raisedadead thanks a lot for your time ... and for making me see that I should check the console.log !! Thanks a lot for your time :) happy new year :)

**Comment by raisedadead** [comment]
@stevaras Cheers! :smile:  Happy to help! Have a good one! Happy new Year to you too! :smile:
