### ISSUE TITLE
Learn LocalStorage By Building a Todo - Step 6 clarification

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55447]
### Describe the Issue

In step 6 of the Todo app (js beta) the following sentence needs a slight correction:
> Add an event listener to the openTaskFormBtn element and pass in a click event for the first argument and an empty callback function for the second argument.

The part where it says "an empty callback function for the second argument" is the issue. It needs to say "a callback function..." (minus the word empty). This is because the word empty implies this:
`() => {}`
but actually the very next instruction tells us to add some code in the function after-all.

Note that step 7 has a very similar set of instructions but doesn't make the mistake of saying "an empty callback function" in its instructions. (please compare 6 to 7 for this slight difference in the wording)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-6

### Your code

N/A

### Expected behavior

N/A

### Screenshots

N/A

### System

N/A

**Comment by lasjorg** [comment]
Maybe instead:

> Add an event listener to the `openTaskFormBtn` element and pass in a `"click"` event for the first argument and an anonymous callback function for the second argument.
> 
> Inside the callback function, use the `classList.toggle()` method to toggle the `"hidden"` class on the `taskForm` element.

**Comment by lasjorg** [comment]
This looks like something that can be fixed by "first time" code contributors to this repository. Here is the file that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64e4e78a7ea4a168de4e6a38.md

Change:

```md
Add an event listener to the `openTaskFormBtn` element and pass in a `click` event for the first argument and an empty callback function for the second argument.

For the callback function, use the `classList.toggle()` method to toggle the `hidden` class on the `taskForm` element.
```

To:

```md
Add an event listener to the `openTaskFormBtn` element and pass in a `"click"` event for the first argument and an anonymous callback function for the second argument.

Inside the callback function, use the `classList.toggle()` method to toggle the `"hidden"` class on the `taskForm` element.
```
---

**Please make sure** you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by lasjorg** [comment]
It is open to all first timers, you do not need to get permission.

**Comment by zhrfrd** [comment]
Ok, thank for letting me know
