### ISSUE TITLE
ToDo App - Parenthesis added to code without explanation between step 23 and 24

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55455]
### Describe the Issue

After completing step 23, (in the Todo app of the js beta) I noticed a new pair of parenthesis were added on line 48 and 50 of the code which was just created. The paren was added without an explanation (though perhaps one will come later?)

I think if it is not needed for the code we shouldn't have it as extra parens make the code harder to read.
(I've included lines 48-50 of step 24 for ref in the 'Your code' area of the issue)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-24

### Your code

```
      (tasksContainer.innerHTML += `
          
      `)


```

### Expected behavior

expecting the code from step 23 to stay as-is in step 24 unless step 24 mentions something about the change(s)

### System

N/A

**Comment by lasjorg** [comment]
It is probably a prettier formatting leftover from when the callback had an implicit return (i.e. no function body block).

I agree, it should be removed.

**Comment by lasjorg** [comment]
This looks like something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64ec9343769e8f85c1e17e05.md

Change to make:

Find the `--seed-contents--` at the bottom and change:

```js
taskData.forEach(({id, title, date, description}) => {
    (tasksContainer.innerHTML += `
    --fcc-editable-region--
        
    --fcc-editable-region--
    `)
  }
);
```

To:

```js
taskData.forEach(({ id, title, date, description }) => {
  tasksContainer.innerHTML += `
  --fcc-editable-region--
      
  --fcc-editable-region--
  `;
});
```

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by zhrfrd** [comment]
Hello, I'm happy to fix this issue.
