### ISSUE TITLE
Role playing game - Step 124 - tests incorrectly checking for `+ 1` and hint has wrong variable name

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55583]
### Describe the Issue

step 124 of the rpg game allows the code below to be submitted as the correct result even though it is missing the `+ 1` to make the random number start at 1. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-124

### Your code

```
  monsterHealth -= weapons[currentWeaponIndex].power + Math.floor(Math.random() * xp);
```

### Expected behavior

test should look for the generated random number to start at 1

### System

N/A

**Comment by yuik371** [comment]
Change the modified attack function to the following, adding + 1 so that the random number starts at 1:
`function attack() {
  text.innerText = "The " + monsters[fighting].name + " attacks.";
  text.innerText += " You attack it with your " + weapons[currentWeaponIndex].name + ".";
  health -= monsters[fighting].level;
  monsterHealth -= weapons[currentWeaponIndex].power + Math.floor(Math.random() * xp) + 1; // add + 1 so that the random number starts at 1
}
`

`
monsterHealth -= weapons[currentWeaponIndex].power + Math.floor(Math.random() * xp) + 1;
`

**Comment by hbar1st** [comment]
Is it too late to also point out that the hint shown when we type:
```

monsterHealth -= weapons[currentWeaponIndex].power + (Math.floor(Math.random() * xp) + 1);
```
is incorrect because it references the wrong variable currentWeapon instead of currentWeaponIndex?

Hint currently says:

You should add the result of Math.floor(Math.random() * xp) + 1 to the result of weapons[currentWeapon].power.

But should say:

You should add the result of Math.floor(Math.random() * xp) + 1 to the result of weapons[currentWeaponIndex].power.

Also, in case it bears clarification, the hint really should not be shown for the code above as it is functionally correct unlike the code that has a missing +1
