### ISSUE TITLE
On "Waypoint: Add Two Numbers" task "Use the + operator" will always validate

### ISSUE THREAD

**Issue by Demon000** [FreeCodeCamp/FreeCodeCamp#5558]
Link to the page: `http://www.freecodecamp.com/challenges/waypoint-add-two-numbers-with-javascript`.
Problem: The "Use the + operator" task will still validate even without using the `+`, because there's a `+` in `(function(z){return 'sum='+z;})(sum);`.

Possible solution: replace `(function(z){return 'sum='+z;})(sum);` with `(function(z){return z;})(sum);`.

**Comment by Pratik151** [comment]
'sum='+z is like printing a string, '+' here is concatenation operator. So 'sum='+z returns 'sum=20' (if z(sum) is 20)
See the output : sum=20

**Comment by ltegman** [comment]
We recently deployed a bunch of updates to the Basic Javascript waypoints and I think you may still be looking at the old seed code, because the current seed does not include that display function and therefore does not pass any tests that it shouldn't. If you press the reset button you'll see the most recent seed code.

Thanks and happy coding!
