### ISSUE TITLE
Waypoint: Quoting Strings with Single Quotes / only works one direction

### ISSUE THREAD

**Issue by harwluk** [FreeCodeCamp/FreeCodeCamp#5571]
Waypoint begins with quote: "String values in JavaScript may be written with single or double quotes, so long as you start and end with the same type of quote."

However, when testing the output, it fails to recognize and reinforce this convention by only allowing it to work in one fashion:

Works: 
```javascript
    var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
```
Fails:
```javascript
    var myStr = "<a href='http://www.example.com' target='_blank'>Link</a>";
```

Both ways, of course, remove the need for escaping, which seems to be the point of the exercise.

**Comment by SaintPeter** [comment]
I don't know how the instructions could possibly be any clearer:
> Change the provided string from double to single quotes and remove the escaping.

In the prior waypoint you use double quotes.  In THIS waypoint you use single quotes.  While you technically can use single quotes in HTML, it is more common to use double quotes.

I'm closing this as the instructions and tests are internally self consistent.

**Comment by harwluk** [comment]
Chill, man. This wasn't about the instructions not being clear. It's about the fact that you pigeonhole the user into your own stylistic choices without a need, and don't allow a perfectly legitimate answer to pass. 

Also, a simple google search shows that single vs. double quotes is not a settled matter as some people prefer single and some prefer double.

Also, yes, double quotes are used in the previous exercise. They are not used in conjunction with single quotes. 

"String values in JavaScript may be written with single or double quotes, so long as you start and end with the same type of quote."....... except when SaintPeter doesn't like it that way?

**Comment by SaintPeter** [comment]
> String values in JavaScript may be written with single or double quotes, so long as you start and end with the same type of quote.

Except when the instructions explicitly tell you to use one or the other to demonstrate a specific point.  This is not an opportunity to exercise stylistic choice, it's a learning exercise to guide users into understanding a point of JavaScript.

Consider also that I have to write a test for it.  I am currently testing if users did what the instructions told them to do, not some other random thing.  It may *technically* be possible to write a test both ways, but the second way would still be the opposite of what the user is instructed to do.

What do you propose?

**Comment by harwluk** [comment]
@SaintPeter I understand that you're busy and it's not worth your time, so leave it as-is. You've got better things to do.

To be 100% clear, I completely understood the instructions-- it was about the fact that the focus seemed to be misplaced and imposed a stylistic bias for (what I perceived as) no reason.  

What I misunderstood was the purpose of the exercise-- what you're actually trying to teach in this specific lesson. I thought that the point of the exercise was understanding how nested quotes work in order to avoid needing to escape with backlashes. 

With that in mind, I thought it was strange that the information states that single/double quotes are interchangeable... and then they're not. 

Look, it's not a big deal. Honestly, my bug submission was not meant as an attack on your curriculum. I was just trying to help contribute to the community in what I thought was a constructive manner. So far FCC has been pretty instructive and is always boasting about its strong community. I was just a bit surprised at the snide response.

**Comment by SaintPeter** [comment]
I apologize if I came off as snide.  That was not my intent.  It's hard to read tone via text. If I am terse it is because I am reading a lot of issues and writing a lot of fixes on material I just spent 2 months working on.  It's quite challenging.

I don't see it as being a "stylistic" choice and more of a deliberate choice for pedagogical reasons.  I try to teach one and only one thing in each lesson to keep things simple and to build foundational knowledge.  In some case this means deliberately omitting key caveats or alternate possible solutions.  

As an expert it is easy to say "You could do it this way . . . or that way", but a beginner will just be confused by that.  Which one should they use?  They don't know.  If we only show them one way, they can't get THAT wrong and, by the time they realize that there is an alternative they will hopefully have enough experience under their belt to be able to utilize it properly.

This is part of the challenge with writing the curriculum - it needs to be accessible to the true novice and still be useful to more experienced programmers.
