### ISSUE TITLE
Inconsistencies in Task 12 of `Learn Conversation Starters in the Break Room`

### ISSUE THREAD

**Issue by mamaruo** [freeCodeCamp/freeCodeCamp#55755]
### Describe the Issue

The feedback for choice B states, "The first sentence is asking for a favorite thing, not interest in an activity," which negates the option. But what it negated is part of right choice D.

Related file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b23ad0df43588a6eadfa4.md

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-conversation-starters-in-the-break-room/task-12

### Expected behavior

Improve the feedback or choice.

**Comment by Neema-Joju** [comment]
Hi,
I would like to work on this issue

**Comment by Neema-Joju** [comment]
The sentence `What is the team’s favorite?` is actually a way of asking about interests. So, I'll edit Feedback of option B to a more appropriate one.

**Comment by a2937** [comment]
> Hi, I would like to work on this issue

Hi there,

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by naomi-lgbt** [comment]
The hint for option B should be edited to:

> The first sentence is correct. The second sentence is a statement, not a question.
