### ISSUE TITLE
Bug in step 57, learn-accessibility-by-building-a-quiz, HTML and CSS course, browser Edge 127.

### ISSUE THREAD

**Issue by Ma-ryna** [freeCodeCamp/freeCodeCamp#55912]
### Describe the Issue

Can't complete step 57, learn-accessibility-by-building-a-quiz, HTML and CSS course. Throws an error when there is no error.  Browser Microsoft Edge. When switching to Google Chrome, the problem disappeared.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-57

### Your code

```
label {
  text-align: right;
}

.info > label, .info > input {
  display: inline-block;
}


```

### Expected behavior

Pass the check and go to the next step

### Screenshots

![image](https://github.com/user-attachments/assets/7dd486ef-aa72-4aa7-b730-00aa70f80481)

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Edge]
- Version: [127]

**Comment by gikf** [comment]
Thank you for reporting this issue.

Red underlines visible on the screen suggest there might be some issue before the part visible on screen.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by Ma-ryna** [comment]
Thank you! I don't need help. I found a solution myself  - I changed my
browser. But I think it would help for you if I report it.

"Red underlines visible on the screen suggest there might be some issue
before the part visible on screen."
The screenshot contains all the code I am allowed to edit in this step.

**Comment by gikf** [comment]
Other code still can be changed. That's what I think has happened here.

**Comment by Ma-ryna** [comment]
Ok, thank you!
