### ISSUE TITLE
Building a Dice Game - Step 14 - Typo in hint

### ISSUE THREAD

**Issue by dajo09** [freeCodeCamp/freeCodeCamp#55937]
### Describe the Issue

typo error on the console warning:
If a large straight is rolled, your checkForStraights function should enable the fifth radio button, set the value to 40, and update the displayed text to , score = 0.  
i recreated the last step to get to the warnings.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-14

### Your code

```
const checkForStraights = (arr) => {
  let baseNum;
  let increment = 1;
  // arr.sort((a, b) => a - b);
  for (let x = 0; x < arr.length-1; x++){
    baseNum = arr[x];
    // console.log(baseNum, arr[x + 1]);
    if ( baseNum + 1 === arr[x + 1]){
      increment++;
      // console.log('+1', arr[x + 1], increment);
    } 
    // else if (arr[x] !== arr[x + 1]) {
    //   increment = 1;
    // }

  }
  if (increment === 5){
    console.log('large');
    updateRadioOption(4, 40);
    updateRadioOption(3, 30);
  } 
  if (increment >= 4){
    console.log('small');
    updateRadioOption(3, 30);
  } 
 updateRadioOption(5, 0);
}


```

### Expected behavior

it's supposed to say :If a large straight is rolled, your checkForStraights function should enable the fifth radio button, set the value to 40, and update the displayed text to , score = 40.  ---- not 0.

### Screenshots

<img width="442" alt="Screenshot 2024-08-25 at 8 08 39 PM" src="https://github.com/user-attachments/assets/653d95cf-3c7d-436c-9317-a56b317ab02c">

### System

- Device: Mac
- OS: Ventura 13.6.9
- Browser: Brave, Safari
- Version: Brave - [Version 1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (x86_64)](https://brave.com/latest/), Safari - Version 17.6 (18618.3.11.11.7, 18618)

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-algorithmic-thinking-by-building-a-dice-game/657e230500602983e01fff6e.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
