### ISSUE TITLE
Typo in Step 75 Description in JavaScript Algorithms and Data Structures (Beta)

### ISSUE THREAD

**Issue by dyazdani** [freeCodeCamp/freeCodeCamp#55961]
### Describe the Issue

A sentence in the description is missing the word "object". It currently says: 

> A NodeList is an array-like, which means you can iterate through it and it shares some common methods with an array.

It should say:

> A NodeList is an array-like *object*, which means you can iterate through it and it shares some common methods with an array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-75

### Your code

```
---
id: 63c9e3a83bb3e61a80eea564
title: Step 75
challengeType: 0
dashedName: step-75
---

# --description--

You also need to get the value of your `#budget` input. You already queried this at the top of your code, and set it to the `budgetNumberInput` variable. However, you used `getElementById`, which returns an `Element`, not a `NodeList`.

A `NodeList` is an array-like, which means you can iterate through it and it shares some common methods with an array. For your `getCaloriesFromInputs` function, an array will work for the argument just as well as a `NodeList` does.

Declare a `budgetCalories` variable and set it to the result of calling `getCaloriesFromInputs` – pass an array containing your `budgetNumberInput` as the argument.
```

### Expected behavior

The word "object" is missing. The sentence should say, "A NodeList is an array-like object..."

### Screenshots

![Screen Shot 2024-08-30 at 11 07 17](https://github.com/user-attachments/assets/1113b199-9544-4d28-a3a9-1dcfaaaefb44)

### System

- Device: MacBook Air
- OS: MacOS 12
- Browser: Opera
- Version: 112.0.5197.53

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e3a83bb3e61a80eea564.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
