### ISSUE TITLE
Waypoint: Nesting For Loops (variable in example has wrong name)

### ISSUE THREAD

**Issue by AgathaLynn** [FreeCodeCamp/FreeCodeCamp#5604]
Challenge [Waypoint: Nesting For Loops](http://www.freecodecamp.com/challenges/waypoint-nesting-for-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the example on this page, the variable used on the second (inside) for loop is `j`, it is referenced as `k`.  

What the example says:

`for (var j=0; k < arr[i].length; j++) { `

What it should say:

`for (var j=0; j < arr[i].length; j++){`

**Comment by abhisekp** [comment]
this has been rectified

**Comment by SaintPeter** [comment]
@abhisekp Do you have a PR ref for this?

**Comment by abhisekp** [comment]
@SaintPeter it's in the staging. And it was added in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5519/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R4535 
But you did something and the fix was gone poof :dash: 
So it was added again in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5567/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R4060

**Comment by SaintPeter** [comment]
@abhisekp It's all part of my evil plan.

Thanks for the ref!

Closing as fixed.
