### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#563]
No closing `</h2>` element in the More Information section:

Here's how you would set your h2 element's text color to blue: 
`<h2 style="color: blue">CatPhotoApp<h2>`

**Comment by BerkeleyTrue** [comment]
Hello @JesseNoBata Thanks for filling this issue.

For future reference please wrap code in backticks so that github presents it as text instead of trying to render it as html. I have gone ahead and added them for you. When you get a chance take a look at [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

I have verified the issue and will be filling a fix soon. Thanks again!

**Comment by JesseNoBata** [comment]
@BerkeleyTrue Thanks for the heads up, I was wondering how to show code in the issue box!

**Comment by BerkeleyTrue** [comment]
No problem. This issue is fixed now. The code should be up in production later today! Thanks again!
