### ISSUE TITLE
Issues in package.json

### ISSUE THREAD

**Issue by Riya54671** [freeCodeCamp/freeCodeCamp#56526]
1)Unnecessary Dependency in dependencies: dotenv is listed in dependencies, but it's usually a development or local environment dependency, so it should be moved to devDependencies.
2)Inconsistent Naming for npm-run-all2: There seems to be a typo with npm-run-all2. The correct package name is npm-run-all, so npm-run-all2 should be replaced with npm-run-all.
3)Invalid/Unused Fields: "main": "none" doesn't make sense. Typically, you would either leave it out or point it to the entry file of your application (if needed).
4)Redundant Scripts:The predevelop script and the prebuild script are running similar tasks (create:shared). This redundancy could be avoided to streamline the task running process.
5)Overloaded Use of npm-run-all: There is excessive use of npm-run-all for simple parallel and sequential task execution. Since PNPM has native task running capabilities, using pnpm run should suffice in many cases.
6)Unused scripts: Some scripts, such as playwright:install-build-tools, knip:all, etc., may be specific to development and might not need to be included in production-level code. Consider keeping only relevant scripts to avoid confusion.

**Comment by Ranaujjawal** [comment]
I want to contribute to this assign it to me

**Comment by Ranaujjawal** [comment]
I have sent a Pull request after making the changes.

**Comment by naomi-lgbt** [comment]
@Ranaujjawal your PR has been closed because this issue is not triaged and opened for contribution yet.

@Riya54671 this issue appears to be an automated/AI-generated analysis of our package.json file. Just as a few examples:

- `dotenv` is often used in production. 
- `npm-run-all2` is not a typo - that is a legitimate fork of the original `npm-run-all` package.

As such, I'm going to close this issue.
