### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#566]
The insertion of 

link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'

isn't listed at the top of the Coding screen; without it the Lobster font doesn't display correctly.

**Comment by terakilobyte** [comment]
Thanks for the heads up, we're working on it! See issue #516

**Comment by JesseNoBata** [comment]
Cool. Is there a way to search and see if a bug has already been reported? Like tied to a specific challenge?

**Comment by terakilobyte** [comment]
Yep, because the bugs are clearly labeled by their challenge name you can just check the open issues and see if it is listed. If so, provide additional details in the existing thread if it's not covered already.

Appreciate the feedback though! We'd rather people let us know if something isn't up to standard than just ignore it.
