### ISSUE TITLE
football team card project - step 27 missing space between name and (Captain)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#56666]
### Describe the Issue

The code below is being accepted by step 27 of the football team card project (js beta) but in the next step, a space is added to the left of the `${name}` to correctly space the label (Captain) from the player's name.
It would be good if this space was explicitly requested (though I imagine it will cause trouble because more people will forget than add it correctly).
Or it would be good if the solution below was accepted as well as the actual solution as shown in step 28 (that is, if we don't want to bother explicitly asking for a space)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-27

### Your code

```
          <h2>${isCaptain ? '(Captain) ' : ''}${name}</h2>

```

### Expected behavior

the step should either ask for the space it requires or accept solutions that produce the same result

### System

N/A

### Additional context

forum post that led to this issue https://forum.freecodecamp.org/t/learn-modern-javascript-methods-by-building-football-team-cards-step-27/716079

**Comment by ishan657** [comment]
Hlo @hbar1st 
I am going to start my open source contribution journey and I would to kick start with this issue so , kindly assign me this issue ..
Thankyou 😺

**Comment by ilenia-magoni** [comment]
@ishan657 Hi there,

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by naomi-lgbt** [comment]
Given that `<h2>${isCaptain ? "(Captain)" : ""}${name}</h2>` passes (with absolutely no spacing)...

We should update the tests to expect a space between "(Captain)" and "{name}". `setPlayerCards` is a global function, so we should be able to call it in the tests with the necessary array and query the DOM to get the live result, rather than relying on a regular expression to catch all the ways a space could be added.

**Comment by SOHAIB-code-png** [comment]
hey assign me this issue I would love to contribute

**Comment by ilenia-magoni** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by Awais142** [comment]
assign me this issue.

**Comment by ilenia-magoni** [comment]
@Awais142 That's not how it works here. Read the comment before yours.
