### ISSUE TITLE
Punctuation mistake

### ISSUE THREAD

**Issue by khushi144** [freeCodeCamp/freeCodeCamp#56851]
### Describe the Issue

There is a punctuation mistake in line - 

> To fix this, move your script element out of the head element, and place it at the end of your body element (just before the closing </body> tag.)

"." should come after ")"

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-16

### Your code

```



```

### Expected behavior

> To fix this, move your script element out of the head element, and place it at the end of your body element (just before the closing </body> tag).

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [22]

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/c723ab25d15fb5385539462fe5ae5e6782d0b237/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62b46e3a8d4be31be5af793d.md
   https://github.com/freeCodeCamp/freeCodeCamp/blob/c723ab25d15fb5385539462fe5ae5e6782d0b237/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62b46e3a8d4be31be5af793d.md#L10

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by gikf** [comment]
Here's search through repository for similar pattern. Most of them are okay and bulk comes from one practice project, but these also should be checked, if fixing is needed https://github.com/search?q=repo%3AfreeCodeCamp%2FfreeCodeCamp+%2F%5C.%5C%29%24%2F+path%3A%2F%5Ecurriculum%5C%2Fchallenges%5C%2Fenglish%5C%2F%2F&type=code
