### ISSUE TITLE
Two test cases with Eagle as a result

### ISSUE THREAD

**Issue by Phajava** [FreeCodeCamp/FreeCodeCamp#5690]
Challenge [Waypoint: Golf Code](http://www.freecodecamp.com/challenges/waypoint-golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%20%20if(strokes%20%3D%3D%201%20%20)%20%7B%0A%20return%20%22Hole-in-one!%22%3B%0A%7D%20else%20if%20(strokes%20%3D%3D%20par-2)%20%7B%0Areturn%20%22Eagle%22%3B%0A%7D%20else%20if%20(strokes%20%3D%3D%20par-1)%20%7B%0Areturn%20%22Birdie%22%3B%0A%7D%20else%20if%20(strokes%20%3D%3D%20par)%20%7B%0Areturn%20%22Par%22%3B%0A%7D%20else%20if%20(strokes%20%3D%3D%20par%2B1)%20%7B%0Areturn%20%22Bogey%22%3B%0A%7D%20else%20if%20(strokes%20%3D%3D%20par%2B2)%20%7B%0Areturn%20%22Double%20Bogey%22%3B%0A%0A%7D%20else%20%20%7B%0Areturn%20%22Go%20Home%22%3B%0A%7D%0A%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

(4, 2) should return "Eagle"
(5, 2) is an "Albatross"!

<img width="252" alt="golf" src="https://cloud.githubusercontent.com/assets/15259933/12069834/9438e1dc-b050-11e5-93e9-81ce3aea6419.PNG">

**Comment by ltegman** [comment]
The rules state anything `<= -2` should be an eagle. -3 is called different things in different countries and having the exact correct list of golf terms is not important to the lesson being taught. Thanks and happy coding!

**Comment by paul-howard** [comment]
Actually, I agree with Phajava. AFAIK, the "nicknames" of the various golf scores are not mentioned at all in either the [USGA](http://www.usga.org/rules/rules-and-decisions.html#!rule-01) nor the [R&A](http://www.randa.org/RulesEquipment/Rules/Rules-Explorer) versions of The Rules of Golf. And in my 20+ years of playing this game, I've never heard of a 3-under-par score described as an Eagle. In the US, a score of 3-under is a "Double Eagle" (a term that has rightly been criticized as nonsensical) and everywhere else in the world, it's an "Albatross" (due to the reputation of the eponymous creature as a "rare bird.")

The PGA agrees with this assessment [here](http://www.pga.com/golf-instruction/instruction-feature/fundamentals/golf-glossary-and-golf-terms), as does Wikipedia, [here](https://en.wikipedia.org/wiki/Glossary_of_golf), and [here](https://en.wikipedia.org/wiki/Par_(score)#Eagle).

This is confusing to those of us who are familiar with the game, and should be changed.

**Comment by BEBEDYDY** [comment]
function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes === 1){return "Hole-in-one!"}
  else if(strokes <= par - 2){return "Eagle"}
  else if(strokes == par - 1){return "Birdie"}
  else if(strokes === par){return "Par"}
  else if(strokes == par + 1){return "Bogey"}
  else if(strokes == par + 2	){return "Double Bogey"}
  else if(strokes >= par + 3){return "Go Home!"}
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
golfScore(4, 1);
golfScore(5, 2);
golfScore(4, 3);
golfScore(4, 4);
golfScore(1, 1);
golfScore(5, 5);
golfScore(4, 5);
golfScore(4, 7);
golfScore(5, 9);
