### ISSUE TITLE
Waypoint Record Collection update tracks unexpected behavior

### ISSUE THREAD

**Issue by jmsims2** [FreeCodeCamp/FreeCodeCamp#5697]
It appears that the array for record 1245 is not initialized properly, which causes the solution:

    collection[id][prop].push(value);

to not pass the test of:

"After update(1245, "tracks", "Addicted to Love"), tracks should have a length of 1"

When looking in dev tools, it seems like the empty array is not getting initialized.  I noticed in the forums that campers are instead doing:

    collection[id][prop] = [value];

Which passes the test, but will overwrite any data in a non-empty array.

I apologize I don't yet know enough about how the site is setup to submit a PR, but hopefully I learn more and can contribute in the future. :)

**Comment by ltegman** [comment]
You can see the array being initialized in the editor. It's a syntactically correct array initialization. If `collection[id][prop].push(value);` isn't working there's an error somewhere in the logic of your code, because I have a working solution that does not require the workaround you mention. Thanks and happy coding!
