### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by WalterPhillips** [FreeCodeCamp/freecodecamp#570]
I think there is a bug here.
1. Here is my change, but FCC does not pass it:
```
<p>Click here for <a href='#'> <img src='http://bit.ly/fcc-kittens2'> </a>.</p>
```

2. The code below passes FCC, but the html is incorrect
```
<a href='#'> <img src='http://bit.ly/fcc-kittens2'> </a>
<a href='#'>
<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>
```
Notice, that the anchor tag is unclosed, and it still requires the 1st anchor tag there.

I'm using the chrome browser.

**Comment by BerkeleyTrue** [comment]
hello @WalterPhillips Thanks for filling this issue.

The second code passes because we are only testing to see if the first `a` tag at the root contains an href with '#'. It does not check whether the whole challenge is valid html. 

The first line of the second answer is the correct solution.

@terakilobyte Do you think this test should be expanded to check whether the first 'a' with href='#' should contain an 'img' child?

Otherwise the test is valid and we can close this issue.

**Comment by terakilobyte** [comment]
I've increased the specificity of the selectors in a lot of tests. Additionally, we're testing to dom at the moment vs testing editor value. A lot of closing tags are in fact optional, and browsers are good at fixing other errors.

I'm closing this and we'll revisit the closing tags issue when things settle down a bit.
