### ISSUE TITLE
Clarify default HTTP method for fetch in Data Visualization course

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#57099]
### Describe the Issue

In the Data Visualization course, specifically in the section where `fetch` is introduced, the example code provided does not mention that `GET` is the default HTTP method for `fetch`. 

This might lead to confusion for learners, as the test currently expects `fetch('/json/cats.json')` without an explicit `{ method: "GET" }` option.

However, many learners may choose to specify `{ method: "GET" }` explicitly, which the test does **not** currently accept.

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method

### Your code

```js
fetch('/json/cats.json', { method: "GET" })
  .then(response => response.json())
  .then(data => {
    document.getElementById('message').innerHTML = JSON.stringify(data);
  });
```

### Expected behavior

- Accept `{ method: "GET" }` as a valid solution, **OR** Clarify in the course instructions that `GET` is the default HTTP method for `fetch`.

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [130.0.6723.117]

### Additional context

The current course example uses:
```js
fetch('/json/cats.json')
  .then(response => response.json())
  .then(data => {
    document.getElementById('message').innerHTML = JSON.stringify(data);
  });
```
Adding a note in the instructions to clarify the default behavior of `fetch`, or updating the test to allow `{ method: "GET" }` explicitly, would enhance clarity for learners and align with common practices in real-world coding.

**Comment by James-Z-Zhang00** [comment]
Hi I'm working on this

**Comment by James-Z-Zhang00** [comment]
Hi this's my first time to work on solving issues, I added instruction for the learner for the certain step and pushed to my fork on GitHub. Could you help me with the instruction of merging code? And I didn't find where is the code that checks the user input. Feel free to contact me at james.z.zhang00@gmail.com

Thank you!

**Comment by ilenia-magoni** [comment]
Hi there, @James-Z-Zhang00 @darkpsinight 

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by James-Z-Zhang00** [comment]
@ilenia-magoni Hi, 

When I was trying to fix the part for user input validation (so it can accept both with and without the GET method specification), I couldn't find which part of the code is doing that checking. I tried to search for freeCodeCamp documentation but didn't find the answer. Is there an official documentation? Or do you know which part of the code does the validation? Thank you!

**Comment by ilenia-magoni** [comment]
@James-Z-Zhang00 As I said, the issue is not open for contribution. Anywaym the file where the tests are written is the file for the challenge itself https://github.com/freeCodeCamp/freeCodeCamp/blob/8ba08fb5f6f7a0d479983950f504e76d0b5ddcb9/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method.md
