### ISSUE TITLE
This challenge doesn't seem appropriate here?

### ISSUE THREAD

**Issue by abrown820** [FreeCodeCamp/FreeCodeCamp#5714]
I don't understand why Caesar's Cipher is a waypoint dwarfing the difficulty of the waypoints before and after it in the basic Javascript section? Isn't it more appropriate to have this exercise as a Bonfire after exercises that demonstrate, for example, the map method? 

I'm struggling enormously with the exercise, most of the answers I've found from others either involve methods I haven't learnt yet, or mapping the alphabet using a switch or lookup, which can't be the most efficient way to do it.

**Comment by smrajagopal** [comment]
@abrown820 
:+1:
- Even I am not very sure if the placement of this challenge in this place is correct.
- But again this is not actually too complex because you could apply what you learnt from  ['WayPoint: Using Objects for Lookups' ](http://www.freecodecamp.com/challenges/waypoint-using-objects-for-lookups). 
- At my first attempt (about 3.00 a.m in the morning), I didn't apply lookup as well which could make this challenge a very simple one. Didn't think much and I just wrote some crazy complex code to solve this challenge.

**Comment by ShaggyTech** [comment]
I agree this seems a little out of place and it might fit in better as a Bonfire exercise.

**Comment by abrown820** [comment]
@smrajagopal 

Usually I would say there's some merit in learning the inefficient way of doing something and then learning the efficient way to prevent a mix up in the future, but in this case I don't think it takes a genius to realise that mapping 26 letters isn't the desirable solution. I don't think there's any value in this exercise and the application of lookups, if anything it's going to encourage bad habits.

**Comment by noinkling** [comment]
I agree with @abrown820, even newbies might feel like "there must be a better way to do this", so they should at the very least be made aware that there are better ways to solve that particular problem than with an object literal character map (you don't necessarily have to mention what those are, e.g. char codes).

Ideally though, we'd have a more suitable problem for making use of a map.

**Comment by ltegman** [comment]
This has been moved to the bonfire section in PR #5736. Should be deployed to the website before long.
