### ISSUE TITLE
Step 87 of calorie counter too strict

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#57147]
See https://forum.freecodecamp.org/t/learn-form-validation-by-building-a-calorie-counter-step-87/720435/

The test will fail if there are extra spaces at the end of certain lines, this should not cause failing

It would be great if the test could check the effect of calling `calculateCalories`, instead of regex

This is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/4524a11e57c68602fdfa27cc7ff57261e4f69a19/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e8fe3a6f022a05a04675.md

**Comment by leaHaimovich** [comment]
**Functionality-based testing:** 
Instead of checking for exact HTML formatting, test the effect of calling calculateCalories() by inspecting the output.innerHTML content after the function runs. This approach will focus on verifying the expected calorie values are displayed correctly without enforcing specific formatting.

**Comment by ilenia-magoni** [comment]
@leaHaimovich does your comment add something to this issue?

**Comment by ilenia-magoni** [comment]
@a2937 it's HTML, the newlines don't matter too much. But it's good practice to write human readable code
