### ISSUE TITLE
add border color check and MDN border docs link to Waypoint: Add Borders Around Your Element 

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/freecodecamp#572]
Conflicting statements to confuse new beginners. In the Top portion it asks for "10-pixel-wide green border"; but below in your checks it states "Your image should have a border with a width of 10 pixels."; yet your code must have this: 
.thick-green-border {
    border-width: 10px;
    border-color: green;
    border-style: solid;
}

Nothing in there states to make the border solid, the top asks for color while the bottom doesn't not state the color. 
I consider myself pretty well beyond beginners level HTML/CSS although not a master by any means, and this one stumped me for a few minutes where i had to ask for help. 

![border2](https://cloud.githubusercontent.com/assets/10119077/7823980/f629d1c8-03c4-11e5-8e7a-b155353110cc.PNG)

**Comment by BerkeleyTrue** [comment]
Hey @GhostParticle Thanks for bringing this to our attention.

While it is confusing, there a couple of reasons this is so.

* border-width by itself is not valid css, it requires border-style in order to render. Without these it will not render and cannot be tested
* We are only testing for width, so the test message only states width required. 
* If you pull down the more-info button it shows an example of using border and it shows all three attributes required to render a border

The omission of the fact that border-width by itself is required may have been intentional to get campers to get used to looking at the spec for css.

That being said we may need to add a test to verify that the border color is green. 
I would also say that adding a link to MDN or w3c documentation may be prudent!

**Comment by BerkeleyTrue** [comment]
For reference: http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements

**Comment by terakilobyte** [comment]
I've resolved this with commit 94a303b42baaf69eb6a7164b9d3a586c7f3bc30e, thanks!
