### ISSUE TITLE
How to Have a Conversation About Preferences and Motivations - Dialogue 4 - Irrelevant content showed up

### ISSUE THREAD

**Issue by Arasan-Github** [freeCodeCamp/freeCodeCamp#57235]
### Describe the Issue

On the dialogue 4 content in the [A2 English for Developers (Beta)](https://www.freecodecamp.org/learn/a2-english-for-developers)
[Learn How to Have a Conversation About Preferences and Motivations](https://www.freecodecamp.org/learn/a2-english-for-developers/#learn-how-to-have-a-conversation-about-preferences-and-motivations) full-length conversation there's another video("Python for beginners" I guess) merges with the content

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-have-a-conversation-about-preferences-and-motivations/dialogue-4-chatting-about-gadgets

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-have-a-conversation-about-preferences-and-motivations/dialogue-4-chatting-about-gadgets'
2. You can see the video playback

### Expected behavior

The irrelevant content should be removed from this course. The conversation video should be shown correctly.

### Screenshots

![Image](https://github.com/user-attachments/assets/17db04c3-e7f7-47eb-8580-9a0c6fd94db0)

### System

- Device:  Laptop
- OS:  Windows 11
- Browser:  Chrome
- Version: 22

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/21b433a81bf6cfd96d16fd674a696f201bfaae25/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-have-a-conversation-about-preferences-and-motivations/65a3dafe5c945761cef35199.md

`videoId` should be removed from the top of file.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by SunilChackoPS** [comment]
Trying to achieve my first acceptance as an Open Source Contributor. @Arasan-Github  @gikf 

Thank You

**Comment by SunilChackoPS** [comment]
Sure. Thank You for the guidelines.  Will be careful next time.
Good Day.
