### ISSUE TITLE
Support for li elements without closing tags?

### ISSUE THREAD

**Issue by Logabe** [freeCodeCamp/freeCodeCamp#57452]
### Describe the Issue

According to the [W3 Spec](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#optional-tags), A [li](https://www.w3.org/TR/2011/WD-html5-20110525/grouping-content.html#the-li-element) element's end tag may be omitted if the `li` element is immediately followed by another `li` element or if there is no more content in the parent element. But in this affected page at least, closing the tags is required - without being explicitly mentioned in the prompt. I know this is a trifling error, but may be worth taking into consideration as this _is_ valid HTML.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23

### Your code

```
<ul>
  <li>cat nip
  <li>laser pointers
  <li>lasagna
</ul>
```

### Expected behavior

I expected the code to pass the test.

### Screenshots

![Image](https://github.com/user-attachments/assets/eed74531-6961-4372-b01d-629b6a8455af)

### System

- Device: Laptop
- OS: Arch Linux
- Browser: Firefox stable
- Version: 132

**Comment by ilenia-magoni** [comment]
The test explicitly asks also for the closing tag, when there is written like that you should follow the hint

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for taking the time to research this and provide the links.

For the first few projects/lessons, we specifically have more strict tests than 100% necessary to achieve the same outcome as how browsers decide to render the HTML. The reason for this is because we did not want there to be confusion when some structure sometimes works, and did not want to put in all the information necessary to explain why/how this can happen.

As such, because Campers are specifically expected and asked (in the hints) to _fully type_ their HTML, I am going to close this issue.
