### ISSUE TITLE
Glitch JavaScript by building a pyramid generator

### ISSUE THREAD

**Issue by Cathy1000** [freeCodeCamp/freeCodeCamp#57453]
There is a glitch on question 43 the code is correct but will not process this will not allow the introduction to be complete when all other answers are answered correctly an finished.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp and choose option which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
