### ISSUE TITLE
Feature/Show progress bar on each waypoint similar to shown at map

### ISSUE THREAD

**Issue by wakqasahmed** [FreeCodeCamp/FreeCodeCamp#5759]
When a camper is on a waypoint of any block (e.g. HTML and CSS) he needs to know how far he is from completing that block. Checkout the proposal given below (Not a good UX though but clears the point):

<img width="1280" alt="screen shot 2016-01-02 at 6 27 45 pm" src="https://cloud.githubusercontent.com/assets/4486133/12074752/263706f8-b17e-11e5-9b7c-47b123dcdad9.png">

**Comment by ltegman** [comment]
I personally am all for further gamification, but someone will need to come up with a less obtrusive UI for it than that.

**Comment by SaintPeter** [comment]
I agree with this sentiment but, as @ltegman says, it needs to be much less obtrusive.  We have been talking about moving away from the modals, even, for the end of challenge notification.

**Comment by elvirafortune** [comment]
What about showing percentage number in the right bottom corner instead of using status bar on the top?

**Comment by flipsyde606** [comment]
@SaintPeter @ltegman  The modal approach can prove to be useful if we are moving towards gamification. At the end of the challenge we can display stats and progression.

**Comment by atjonathan** [comment]
@hallaathrad, what do you think of this?

**Comment by hallaathrad** [comment]
The gamification idea has been of great appeal to a lot of people (including myself) but I'm not sure I've ever heard @quincylarson speak for or against it.
That said, we could consider better options than the modal window (specially considering it's going away soonish, if I've understood correctly).

A progress bar would be shown for the challenges position in the block of content (e.g. HTML and CSS... Or JavaScript). And then at the end of each of these blocks an additional progress indicator for it's part of the stack/certification.

However, as an argument against progress bars, and similar progress indicators: people should not be misled into thinking this is a race or competition they could speed through. Coding is more like learning to paint than building a lego toy. Constance ans repetition rather than a linear process until some imaginary "completion".
