### ISSUE TITLE
Building Checkout Page instruction requirement 10 tab-index

### ISSUE THREAD

**Issue by JakobMitterauer** [freeCodeCamp/freeCodeCamp#57809]
### Describe the Issue

Hi dear contributors :)
in new Beta curriculum for html accessibilty in Lab Build a Checkout Page tabindex attribute is mentioned as "tab-index" which was confusing for me and led to the tests failing checking the tests it is meant to be "tabindex".
Iam not sure if it is intended to be a learning that it is tabindex and not tab-index i just wanted to let you know :)

BR,
Jakob

### Affected Page

https://www.freecodecamp.org/learn/full-stack-developer/lab-checkout-page/build-a-checkout-page

### Your code

```
![Image](https://github.com/user-attachments/assets/07a76de3-fc0b-471b-aa4d-71aa01b63159)




```

### Expected behavior

Requirement 10 should be tabindex?

### Screenshots

![Image](https://github.com/user-attachments/assets/05bb6752-bed4-4a46-8235-7e8f12f96f35)

### System

Windows 10

**Comment by gikf** [comment]
Thanks for opening this issue.

`tab-index` should be replaced with `tabindex`.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/418ce6e3dc931b5f68533b044438ab82130cfe8e/curriculum/challenges/english/25-front-end-development/lab-checkout-page/66da326c02141df538f29ba5.md?plain=1#L24

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
