### ISSUE TITLE
Design a Greeting Card Step 8

### ISSUE THREAD

**Issue by webro1989** [freeCodeCamp/freeCodeCamp#57825]
### Describe the Issue

Hi!

The instructions for the challenge step is:

The first one should have a text of Send Card, a class of send-link and an href of #send.

The first one should have a text of Share on Social Media, a class of share-link and an href of #share.

For the second anchor element instructions, the instructions using the words `first one`. It should be `second one`.

### Affected Page

https://www.freecodecamp.org/learn/full-stack-developer/workshop-greeting-card/step-8

### Your code

```
      <div class="card-links"></div>

```

### Expected behavior

Instructions For the second anchor element within the challenge step should have the words `second one`, instead of `first one`.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/779bb5a574058472ac75139ee1693dbca86be613/curriculum/challenges/english/25-front-end-development/workshop-greeting-card/672b4434dd6d6a1edc405419.md#L14-L15

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
