### ISSUE TITLE
Streak seems broken (screenshot)

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5799]
![](https://www.evernote.com/l/AqQfsoH-3NpLabxkPG3YCVNHNOswzBgFUpgB/image.png)

**Comment by LenaBarinova** [comment]
As I understand this problem happens because ```cal-heatmap``` displays data in user's browser timezone. Streaks and completed challenge list dates are shown in server's time zone. Thus the difference.
To solve it I suggest showing all three components using client's timezone. I can see to ways doing this:

1. Store user's timezone in a ```cookie``` from client side and on the server side get cookie and calculate Streaks and show completed list in a timezone from cookie.
2. Store user's timezone in a user profile (persist to Mongodb) and on the server side use timezone from profile. 

I would prefer second option. Maybe in the future there will change user settings functionality on FreeCodeCamp and user will be able to change timezone to one of her choice. 
What do you think, guys? I could implement needed changes.

**Comment by BerkeleyTrue** [comment]
The problem with 1 is now everyone will see different results when viewing the same profile.

**Comment by BerkeleyTrue** [comment]
2 sounds viable

**Comment by LenaBarinova** [comment]
Well, @BerkeleyTrue, with option 2 everyone will see diff results as well, since there is no way to control timezone on ```cal-heatmap``` (as far as I know). 
I think the main issue - inconsistency among several components on one page. Seeing someones profile in your timezone doesn't look that bad to me.

**Comment by LenaBarinova** [comment]
On the other hand, we could prep data before passing it to ```cal-heatmap``` using user's timezone.

@BerkeleyTrue, @QuincyLarson I need a second opinion, if I'm looking into another user's profile, should I see data represented in his timezone (so it would be the same for same user everywhere) or should it be in my timezone? I'm wondering how Github is doing it..

**Comment by SaintPeter** [comment]
I guess I would be less worried about what other people saw that what I saw.  We get lots of complaints that user's don't see their streak, or it appears to be broken.  I can't imagine that we get many that complaints about viewing OTHER people's profiles.

Still, it would be nice to fix it "once and for all" ... even if it means "Xtream timezone maths!"

**Comment by jwithington** [comment]
Can confirm this is still happening [on my profile](http://www.freecodecamp.com/jwithington), though I'll assume that's because the fix hasn't been merged yet. :smile:

**Comment by QuincyLarson** [comment]
The streak is also showing zero days for camper @thebgar who completed a challenge today:
![](https://www.evernote.com/l/AqTxC4j0fbZHt6pUKto5siCSwbxBwv8qE4AB/image.png)
