### ISSUE TITLE
expand tests in waypoint-create-a-set-of-radio-buttons

### ISSUE THREAD

**Issue by ryebr3ad** [FreeCodeCamp/freecodecamp#581]
I only had one name typed into the radio button field before it accepted that I had both names entered.  Only make it so both fields need to have a shared name before triggering the "accepted" state.

**Comment by BerkeleyTrue** [comment]
@ryebr3ad Thanks for filling this issue!

The test for this challenge need to be expanded for sure.

**Comment by QuincyLarson** [comment]
I just spent about 40 minutes on stream trying to get this to work for both fields with this attribute. I recommend we just let this be for now since it's not that huge of an issue imho. I did make some minor improvements to the test, though. Thank you for bringing this to our attention. If we have some testing breakthrough that can be applied to this problem down the road, I'll revisit this.
