### ISSUE TITLE
Sass Waypoints

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5844]
For this issue, we need to:
1. create rough list (using checkboxes) of which concepts we want to teach, in what order
2. start building the challenges
3. QA the challenges and refine their copy

**Comment by AkiraLaine** [comment]
@QuincyLarson I'm currently learning SASS and want to help with the Waypoints. Here is how we could lay it out.

- [ ] Sass - CSS with Superpowers! (Intro to pre-processors)
- [ ] Variables 
- [ ] Nesting
- [ ] Partials
- [ ] Imports
- [ ] Mixins
- [ ] Extend/Inheritance

**Comment by QuincyLarson** [comment]
Hi @AkiraLaine,
Yes, we would teach the SCSS syntax since that's way more popular. If we have time, we can explain vanilla Sass syntax, but that's less of a priority. 
I've asked @storbeck to come by and share his thoughts on this as well.
I'm thrilled that you're up for the challenge of creating these Waypoints. I think in total we'll probably want to have 30 - 40 challenges.

**Comment by AkiraLaine** [comment]
Ok, cool. I'll wait for @storbeck to give his ideas :smile:

**Comment by jbmartinez** [comment]
I agree with the list proposed by @AkiraLaine.

There are only 3 differences between SCSS and Sass, as far as I know: curly braces, semicolons and indentation. We can explain those differences in a couple of waypoints after explaining SCSS.

**Comment by QuincyLarson** [comment]
@jbmartinez I almost feel like that would be a better Hike as opposed to trying to teach them that in a waypoint, because it might introduce confusion.

**Comment by HoBi** [comment]
@QuincyLarson I work with Sass on real projects and I also wrote some tutorials about Sass (in Czech). I can do some of waypoints and/or prepare a curriculum, if I may.

*But I would probably need some help with English correction.*

**Comment by jbmartinez** [comment]
@QuincyLarson makes sense, it's better for a Hike

**Comment by storbeck** [comment]
The layout from @AkiraLaine is good, it's ripped directly from the [sass official guide](http://sass-lang.com/guide) which is worth working off of. In addition to those I would also include [control directives](http://www.sitepoint.com/sass-basics-control-directives-expressions/), they give a really good reason to use a preprocessor.

A short intro as to why we use preprocessors, what they give us, and why it's worth the extra strep in the build process.

Variables will be the easiest to explain and people will immediately see the benefit of this if you are using variables for themes ($backgroundColor, $textColor, $fontFamily, etc).

Nesting is the next logical step for me, as it introduces an easier way to organize your code into components.

Mixins should be introduced as custom mixins - not using any mixin library. Maybe an example for a cross-compability mixin like example 4 or 5 on [these examples](http://zerosixthree.se/8-sass-mixins-you-must-have-in-your-toolbox/)

Controls are often forgotten but are very useful, you can easily build your own grid layout just using 1 for loop to set sizes. This is a bigger step in showing off the power of scss and how larger frameworks (like bootstrap or skeleton) can be easily removed if you just learn to use the preprocessors.

Partials don't need much explanation. Maybe an example of building out a _colors.scss page of color variables then including it so web themes can be easily replaced in just one definition file instead of going through 20 css files.

Extend/inheritance should be easy to explain, and they're used a decent amount, but I don't think they're overly important and it would be a nice breather to wind down the series.

Imports are hugely important (compass/bourbon) but I think just a simple explanation of how to import and then go to the sites documentation. Both bourbon and compass have great documentation of their own.

I'd probably go with this from important/most-used to not as important
- [ ]  Sass - CSS with Superpowers! (Intro to pre-processors)
- [ ]  Variables
- [ ]  Nesting
- [ ]  Mixins
- [ ]  Control (if/for/while/each)
- [ ]  Partials
- [ ]  Extend/Inheritance
- [ ]  Imports

**Comment by AkiraLaine** [comment]
@QuincyLarson I really want to get started on these ASAP. @storbeck Maybe we can work on these together?

**Comment by denmch** [comment]
Seems like people have this well covered, but I'd like to add a small note in favor of including the parent selector (`&`), if only for the clean way it allows you to include pseudo-selectors without writing a separate rule.

**Comment by storbeck** [comment]
@AkiraLaine I won't have time to contribute to making the waypoints, was just giving my thoughts on it. Have at it

**Comment by luishendrix92** [comment]
I think clarifying that there are two syntaxes (pythonesque syntax –or old syntax– and scss with curly braces) is a good way to start, decide between one or the other or let them decide for themselves.

Mixins with parameters (acting like functions) would be great. Also, with all this, it won't hurt to teach about some software (paid or free such as prepros, crunch or koala) that tackles the compilation of SASS or the command line --watch --compile and how to install it via the Ruby Gems installer (or codepen.io, using it directly).

**Comment by AkiraLaine** [comment]
@luishendrix92 I think I will mention ```.sass``` (if that's what you're talking about) briefly as it might become a Hike. I've done the basics for Mixins, but everything will need to be polished. I could definitely talk about compilers - but I'm not sure where.

Here is my fork if you want to check out what I've done or want to help: https://github.com/AkiraLaine/FreeCodeCamp

**Comment by SaintPeter** [comment]
Reviewing: 
https://github.com/AkiraLaine/FreeCodeCamp/tree/new/sass-waypoints
@AkiraLaine 

General Notes:
Spacing - You can just use regular spaces inside `<blockquote>` elements.  They use the `<pre>` tag formatting, so spaces are preserved.

### 1) SASS with Superpowers
This is essentially a "no content" challenge, an introduction to SASS.  This should be a "Step Challenge" (Challenge Type 7), which has images and text below them.
The tone may be a bit too conversational here - maybe ok for a step challenge, but I think the focus should be on what SASS can do for you - how it can save time and/or keystrokes.

### 2) Storing Data with Sass Variables
Should probably focus on how create SASS variables is different from creating Javascript Variables.
> In Javascript, to declare a variable you use the `var` keyword.  In Sass, all variable names start with a `$` and they are declared by simply assigning a value to them:
`$color = red`

I presume that the stuff in `<style>` is really going to be in the Sass editor tab? 
As an illustration of this concept, I think there should be multiple class definition and pre-defined HTML which all use a common color, maybe defined by a hex code.  Show that you can replace the hex code with a variable and that later you can change your mind.  The variable should be semantically named, like `$primary-text` or something.  You can see examples of how this is used in the bootstrap .less files.

### 3) Nesting your CSS
I'm not sure I get this waypoint.  I think if you want it to be clearer you need to have the first code block be identical in function to the second code block.
```css
nav {
  background-color: red;
}
nav ul {
  list-style: none;
}
nav li {
  display: inline-block;
}
```
It's not entirely obvious to me why this is better.  It does allow you to change the top level class or element without having to find all references to it.  Maybe that's the example to use?

Your instructions need to be significantly more explicit.  They need to say exactly what styling is being applied to what element.  Using actual class names (especially semantic ones) might be a better choice than HTML elements.  Or maybe a semantic name for the top level div and use the html elements for the sub-pieces (which is pretty common).

### 4) Mixing the Cake
I would make the analogy that `mixins` are basically like functions for CSS.  

Your instructions need to be much more descriptive.  You need to give a specific value to set it to.  Rather than `$val`, I'd call it `$radius`.
>**Instructions**
>Write your own mixin called `br` to give an element all four corners a `border-radius` of `$radius`.
>Then use border-radius to give `#awesome` a radius of `5px`.

Or something like that.   Needs work.

### 5) Using if and else
The first example should be in `blockquotes`.  The explanation needs to be a bit clearer about what the use case is.  The example seems good, but the text doesn't support it.  The idea, as I understand it, is to set attributes based on an input, so you can define multiple classes with a single mix-in.
I'm thinking that we may want to keep drawing the analogy back to JavaScript, since that's what we're using as our basis of comparison.

(To be continued . . .)

**Comment by SaintPeter** [comment]
### 6) Continuing with for
Text is a bit jumpy, need to be smoothed out.  This is the first big departure from JS syntax, so some clear examples would be good.  Just the single for line.  It might even be worth writing two separate waypoints, one for `start to end` and `start through end`
Use a `blockquote` for the first example here. 
Instructions -
> This should create 5 classes called .text-"number here" that makes the font-size: 10 * the number.

Maybe

> This should create 5 classes called `.text-1` through `.text-5` that makes the font-size: 10 * the number.

### 7) Expanding with each
These are basically arrays (I think they call them lists)?  I think it would be worthwhile to approach this as "This is a sass feature like a JS array".  Pull some info from here: http://hugogiraudel.com/2013/07/15/understanding-sass-lists/

This specific waypoint is probably too complex, since it introduces too many new concepts.  Break it in two, maybe 3.  This makes a fine introduction to `@each`.

I like the examples and instructions.

### 8) Wrapping up with while
Woah, woah WOAH!  Wait, you can do math on variables?  That part needs to be WAY earlier, after you introduce variables.  I'd have two prior waypoints:
* Doing Math in SASS
* Updating/editing variables
Or maybe have those after we introduce mixins?  Anyway, I don't think we can just throw it in in the middle of while loops.
I'd like to see an example/instructions that were different from the for loop example.  No idea what that would look like, but this is almost identical.

Aaaaand . . that's all she wrote.

**Comment by SaintPeter** [comment]
Thinking about testing these.
What I was thinking we might need would be an "Xpath for CSS".  What I found was:
* https://github.com/aramk/CSSJSON - Converts CSS to JSON
* http://jsonselect.org/#overview - Does "CSS" style selectors against JSON

I think if we run our output against both scripts that we can easily write simple "CSS Like" selectors that the match counts should be non-zero.  We can run these against the Sass output.  We may need to couple these with some simple regex searches on the pre-compiled code, but this feels workable to me.

**Comment by HoBi** [comment]
@AkiraLaine good work, but:

I have a bad feeling about using Sass into `<style>` element... And it's not clarified at all! - that you have to compile it using Ruby or LibSass (much much faster) version of compiler. Would be awesome if you have two separated contents for code - one for Sass and one for HTML.

The example in **Mixing the Cake** is really out of reality, because in real life you use tools like Autoprefixer. I recommend you to think some better example. :-)

Also no space between selector and bracket is so ugly. Can you just put one space there? :-) It's look much nicer. E.g. `#awesome{` -> `#awesome {`. I have some real experience that it's also esier to learn with.

In **Continuing with @for** where you mention difference between `to` vs `through` woul be nice if you also use comparison with `<` and `<=` operators, which may help to non-native speakers.

**Extend your CSS styles** (or some related checkpoint) should also contain information about [placeholder selectors](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholder_selectors_).

Don't remember to mention `//` **comments** and **data types**. :smirk_cat:

**Comment by SaintPeter** [comment]
With regards to the `<style>` element, I expect to see some sort of "Mutli-file editor".  At the very least there will be a single "SASS" input file and maybe some HTML it's run against.  I'd worry more about content then the specific form.

**Comment by Sainkglory** [comment]
hi...

**Comment by jacobbogers** [comment]
HI, A was notified of the existence of this thread , the FCC project https://www.freecodecamp.com/challenges/build-a-markdown-previewer  
Specify to use SaSS, but can someone from FCC explicity state that ScSS use will not be rejected in the solution.?  
Maybe you have auto parsing tools to check projects that only understand SaSS for now, or maybe for you SaSS and ScSS are interchangible when talking about them

But I would like to get an explicit "ok" to use "ScSS" for the 2nd certificate.
Thanks very much

**Comment by abhisekp** [comment]
@jacobbogers you are free to use whichever technology gets the work done. There is no restrictions of use of technology. :smiley: 
In fact, it's really appreciated to use Sass (SASS/SCSS syntax) preprocessor for developing your front-end projects.

You may use whichever platform you like for developing and publishing online. (It should be viewable publicly, ofcourse). 
Try [Plunker](http://plnkr.co), [Code Pen](http://codepen.io), [JSBin](http://jsbin.com) or [JS Fiddle](http://jsfiddle.net). :white_check_mark: All are :ok: 

btw, this thread is about curriculum development of Sass challenges to teach Sass preprocessor in the curriculum. :wink:

**Comment by BerkeleyTrue** [comment]
This work has moved to https://github.com/FreeCodeCamp/CurriculumExpansion
