### ISSUE TITLE
React Waypoints

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5846]
We need to:
1. create rough list (using checkboxes) of which concepts we want to teach, in what order
2. start building the challenges
3. QA the challenges and refine their copy

**Comment by benmcmahon100** [comment]
Working on getting Redux to work in Codepen

ES6?
if yes then we should do some ES6 waypoints of this style

Vanilla react challenges will be easy enough to make

**Comment by TheTommyTwitch** [comment]
Well I figure we should get started brainstorming a list of challenges, so I will propose something!

* Basic React component
* Intro to JSX
* How to use props
* Setting states
* Using AJAX in components
* Events

This is just a start. I would love to hear some more feedback from the community.

**Comment by QuincyLarson** [comment]
@benmcmahon100 Yes - we should definitely do ES6 react imho. May take a little extra time to teach, but that seems to be how everyone's doing it now.

**Comment by ltegman** [comment]
@benmcmahon100 You probably already got it going, but if not my [React Roguelike](http://codepen.io/ltegman/pen/obLXKQ) uses Redux in codepen.

**Comment by yhagio** [comment]
What about testing for React components like using built-in TestUtils? Will it be included?

**Comment by TheTommyTwitch** [comment]
@QuincyLarson maybe we should have a small section dedicated to ES6?

**Comment by DDaems** [comment]
@TheTommyTwitch :+1: 
I think ES6 could be a seperated section too, the specification is huge.

I am currently trying to learn React for completing the challenges.. Which turned out to be allot harder than i though it would be. Especially the lack of expierence and knowledge about using `this`, binding, tracking `state'. Is the part where i struggle the hardest. i think FCC could certainly use a bit more challenges that explain `this` and binding indepth.

**Comment by QuincyLarson** [comment]
@DDaems yes - I agree. We plan to have way more Waypoints focused on `this` and binding.

@TheTommyTwitch we should indeed have an ES6 section. We still have some technological hurdles regarding getting ES6 to work in the browser.

@ltegman could you walk us through how you went about getting Redux to work on Codepen?

**Comment by ltegman** [comment]
@QuincyLarson Sure. Redux works perfectly it's just the react-redux bit that connects them that I couldn't get working. This is how I got around it (based roughly on a codepen I saw using redux, don't remember which anymore).

**All Steps are done in the container component**
1. Pass the `getState` function from my redux store as a prop.
2. (Optional) Make a `_select` method that maps redux state to component state. All future steps can be done without this wrapper if you don't need to transform the redux state in any way.
3. Return `this._select(this.props.getState())` from `getInitialState`.
4. Make a `_storeDataChanged` method that calls `this.setState(this._select(newState))`.
5. In `componentDidMount`: `this.unsubscribe = store.subscribe(this._storeDataChanged)`.
6. In `componentWillUnmount`: `this.unsubscribe()`.

**Comment by noinkling** [comment]
For what it's worth: as someone who has been familiar with React for a while but only recently picked up ES6, :-1: on introducing ES6 at the same time as React, I think it would complicate things too much and that they should be separate topics. I'd be completely lost if I was learning *both* React and idiomatic ES6 at the same time, but because I knew ES5-style React first I can compare it with ES6-style and quickly see how things line up between them. This allows me to easily separate mental concerns regarding structure/syntax/API, so I'm not getting confused between "what is React" and "what is ES6" in my (and other people's) code. Other reasons:

* The React docs still use ES5.
* ES6 style requires some knowledge of `this` and `bind`/arrow functions; with `createClass` it's mostly taken care of for you. Agree that this is an important topic that needs to be covered though; the Udacity course that used to be part of the curriculum covered this in a pretty easy-to-understand manner I thought, maybe you can take some cues from that?

My opinion is that separate ES6 waypoints should be introduced first, then the React waypoints can cover both styles (hopefully in an intuitive structure). Or else ES6 can be given a brief mention at the end of the React waypoints, maybe some links are provided, but it isn't covered in any more depth than that - until after ES6 is introduced as a separate topic on its own.

ES6 stuff aside, I know you guys want to rely on external resources as little as possible, but the [Thinking in React](http://facebook.github.io/react/docs/thinking-in-react.html) article is required reading as far as I'm concerned, and possibly the [tutorial](http://facebook.github.io/react/docs/tutorial.html) as well (depending on the quality of the waypoints).

Also I just wanna link to Pete Hunt's recent repo here with his advice, it might be useful: https://github.com/petehunt/react-howto

**Comment by krisgesling** [comment]
I did the first two challenges just based off the official tutorial and documentation but have been searching for more intermediate things. I've been looking through some of the resources at https://www.codementor.io/learn-reactjs
I haven't done any kind of exhaustive review but so far I think buildwithreact.com has had the simplest explanations and examples to get started. They only have a handful of tutorials and articles but they are done quite well. 

I also think that along with `this` it would be good to cover `.bind` as I didn't understand it until I started to understand `this`. I don't think I fully understand either yet but then my chances of 'fully understanding' any javascript component is probably pretty low

**Comment by bgvianyc** [comment]
Here is a simple codepen counter example demonstrating Redux. http://codepen.io/anon/pen/LNYBKP

It does not use React in this simple example, but I think it's more demonstrative of the pattern without React.

**Comment by TheGalacticNinja** [comment]
ES6 should be its own topic and have its own trail. Teaching the ES5 way react can be a good start but a large portion of the community is moving towards ES6. Also using the features from ES6 is a ton of fun. I think ES6 definitely should be its own track. 

Maybe have react after that and go into the different implementations. Once react is taught move into items like Redux, Flux, and possibly immutable. 

Tasks For React
- [ ] Simple React Component
- [ ] Structure
- [ ] Events
- [ ] Props and State
- [ ] Changing States
- [ ] Using Ajax (possibly fetch) with components

Once these things are done go into how to create data flow structures

**Comment by yhagio** [comment]
This program is great for starting React.js, it is also free.
http://courses.reactjsprogram.com/courses/reactjsfundamentals

**Comment by BerkeleyTrue** [comment]
This work has moved to https://github.com/FreeCodeCamp/CurriculumExpansion
