### ISSUE TITLE
Testing Waypoints

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5847]
We need to expand our current testing waypoints. Currently there are only two. Ideally, we want to cover a testing framework like Jasmine. We need to:
1. create rough list (using checkboxes) of which concepts we want to teach, in what order
2. start building the challenges
3. QA the challenges and refine their copy

**Comment by yhagio** [comment]
Hello, I'm new to testing and also new to FreeCodeCamp. Is this testing module for Front-End/React (i.e. Jasmine) or Back-End (i.e. Mocha/Chai) ? Hopefully for all Front-End/React & Back-End. 

I personally thought that it makes more sense to include testing lesson in each Front/React/Back Waypoint module than making an independent testing module since how to test Front-End, React Component, and Node/Express API are a little different. Also, TDD is important for creating projects, so it is great to be included in each project module (Ziplines & Basejump).

**Comment by Dadsaster** [comment]
My preference would be for a TDD style tutorial broken up into stages.  Ideally first stage is having tests written and then have the camper make the tests pass.  Second stage would be to have user write tests first, then write code to make them pass, then have them refactor.

**Comment by BerkeleyTrue** [comment]
> Ideally first stage is having tests written and then have the camper make the tests pass.

This is how every challenge on Free Code Camp currently works.

**Comment by BerkeleyTrue** [comment]
This work has moved to https://github.com/FreeCodeCamp/CurriculumExpansion
