### ISSUE TITLE
I am have a Little of trouble

### ISSUE THREAD

**Issue by Redkobra1979** [FreeCodeCamp/FreeCodeCamp#5870]
Challenge [Checkpoint: Word Blanks](http://www.freecodecamp.com/challenges/checkpoint-word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
    var result = "";
    // Your code below this line
    

    // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by ltegman** [comment]
Does not describe a problem. Please check out the [gitter chat](https://gitter.im/FreeCodeCamp/Help) if you need help and file a bug that [follows this guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) if they confirm your issue is a site bug.

Thanks and happy coding!
