### ISSUE TITLE
Deleted account code is still available

### ISSUE THREAD

**Issue by douglas-b-clark** [FreeCodeCamp/FreeCodeCamp#5910]
I created my first FreeCodeCamp account in the summer of 2015.  I decided to start over so I could blog through the whole process.  I went through the process of clicking on my profile picture, scrolling to the bottom of the screen and clicking on the pinkish "Delete my Free Code Camp account".

I then created a (supposedly) new FreeCodeCamp account with the same GitHub account, and started going through the HTML and CSS Waypoints, and noticed that all of the code changes had already been made.  I am assuming this is simply the old code I modified with my deleted account surfacing in my current account.

Do I need to create another GitHub account in order truly start over?

**Comment by ltegman** [comment]
I'm assuming you don't see any completed challenges in your profile that you wouldn't expect? If not then this is expected behavior because FCC saves your solution code in localStorage. You can clear this by [following this article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage)

**Comment by douglas-b-clark** [comment]
Hey Logan, clearing my localStorage did, in fact, resolve the issue.

Thank you for this!

Doug
