### ISSUE TITLE
Suggestion to improve waypoint instruction clarity

### ISSUE THREAD

**Issue by AdamLombard** [FreeCodeCamp/FreeCodeCamp#5921]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements) has an issue:

<i>My first GitHub issue! Sorry if this isn't the place/way to suggest this...<i>

The current instructions for this waypoint have the first three paragraphs in this order:
"(1)With CSS, there are hundreds of CSS properties that you can use to change the way an element looks on your page.

(2)When you entered `<h2 style="color: red">CatPhotoApp</h2>`, you were giving that individual h2 element an inline style.

(3)That's one way to add style to an element, but a better way is by using CSS, which stands for Cascading Style Sheets."

<br>
Re-arranging them would improve clarity of the instructions, especially for someone who has never encountered CSS. Like so:

"(2)When you entered `<h2 style="color: red">CatPhotoApp</h2>`, you were giving that individual h2 element an inline style.

(3)That's one way to add style to an element, but a better way is by using CSS, which stands for Cascading Style Sheets.

(1)With CSS, there are hundreds of CSS properties that you can use to change the way an element looks on your page."

**Comment by denmch** [comment]
One point to clarify here is the apparent distinction made between inline styles and external style sheets. While CSS stands for Cascading Style Sheets, it's also the name of the language and not specific to style sheets per se.

I wonder if there would be any objection to me writing a couple of Waypoints to (1) clarify the distinction between style sheets, the style element, and inline style attributes, and (2) introduce specificity and the cascade.

I actually have a Medium post in the works on this topic.

**Comment by GravityTitan** [comment]
As someone who is quite new to all of this, I those Waypoints sound like they'd be very helpful.
I'll also watch for your Medium post!

**Comment by ltegman** [comment]
@denmch I think those would be great additions to the curriculum which we would welcome. External style sheets may be a more practical lesson to implement once we have separate editors for HTML/CSS/Javascript, which is on the roadmap.

@GravityTitan I actually think that structure is a less natural way of arranging the sentences. @FreeCodeCamp/issue-moderators what do you all think?

**Comment by hallaathrad** [comment]
Personally, I have to agree with the way @GravityTitan orders those phrases. +1 if we're voting.

**Comment by GravityTitan** [comment]
@ltegman Point taken about the "naturalness" of the arrangement. My order doesn't _sound_ particularly smooth...

I was really trying to suggest a better order for the presentation of the _concepts_, rather than suggesting a natural order for those specific phrases. 

If someone has literally never heard of CSS before, it's jarring to start your very first CSS lesson with the phrase "With CSS, there are hundreds of CSS properties....". If I'm new to all this, I already have no clue what we're talking about. I actually thought I'd skipped a lesson, the first time I got to this waypoint!

So, ignoring phrasing, to my mind this sequence presents the concepts in a less confusing way:
1. In the last lesson, you did a thing to your code. 
2. We call that thing an 'inline style'.
3. That's one way to style stuff, but there's this better way called CSS. 
4. CSS stands for Cascading Style Sheets, and this is how it all works...

I think that progression would feel comfortable to someone with zero prior knowledge.

Maybe I'm wrong, but...

@hallaathrad +1 for agreeing with me. :)

**Comment by AdamLombard** [comment]
Issue seems to have died out. Closing.
