### ISSUE TITLE
Passthrough Endpoint for Weather API challenge

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5965]
Currently, campers have to find their own weather APIs and leave their API keys in their solutions. 

We need to create an endpoint where campers can pass params and we'll go fetch the data for them using our unexposed API key, then return that data to them.

This will also make the challenge much easier, as they can focus on working with the data and presenting it, rather than having to figure out the API themselves.

Challenge [Zipline: Show the Local Weather](http://www.freecodecamp.com/challenges/zipline-show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by denmch** [comment]
The OpenWeather API isn't difficult to obtain. I'm not sure if you cover how to set environment variables in Heroku, but it seems like a good topic as people advance in building apps (if there were any chance of moving the hosting from Codepen to Heroku). I haven't looked at the actual limits, but I'd worry about maxing out calls to a shared API as more and more campers complete the challenge.

**Comment by kprenesti** [comment]
Is there any way to move from Codepen to just using Github project pages?

**Comment by d3ddd** [comment]
Open Weather App say that they will remove API limits for open source projects, in case that's useful / new information for you guys.

I've provided a screenshot of exactly what they say, and a link to where I found the information.

![image](https://cloud.githubusercontent.com/assets/9157052/13623281/4c5f1a22-e55a-11e5-988d-e32147f6986e.png)

http://openweathermap.org/faq#error401

**Comment by kprenesti** [comment]
That's great, but that doesn't negate the fact that there information is 
just downright erroneous.  :(

**Comment by d3ddd** [comment]
Yeah that's absolutely true. I was just hoping that knowing that a special non-restricted API key is possible to acquire might make a system where campers would go through a FCC server to get open weather map data more doable.

**Comment by kprenesti** [comment]
I used Weather Underground, and I'd recommend it to anyone.  :)

**Comment by d3ddd** [comment]
Does Weather Underground require an API key to use?

**Comment by kprenesti** [comment]
It does, but so does almost every other API. That said it's free for upto 500 calls per day, which for the most part is fine. It's unlikely an FCC project would need more than that.


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by d3ddd** [comment]
That's very true, but having a publicly posted API key (in codepen) means that people could potentially find that API key and use it for their own purposes and max out that 500 calls per day or get the API key banned because it's abused. As a result, FCC is trying to find a way to allow campers to not have to expose an API key.

**Comment by kprenesti** [comment]
Easy.  Use github to host the projects instead of codepen. Code should 
be pushed to github sooner rather than later.  I had learned github 
myself before coming to FCC, but I don't understand why they wait so 
long to teach it.  With any github repo (for a static site), you need 
only create a branch called gh-pages and push the code. That way you can 
show off your site and the api key is not as easily seen.  Besides,  
Codepen is a nightmare to work with anyway.

**Comment by d3ddd** [comment]
Still a public API key, even if it's slightly harder to find.

**Comment by calicode** [comment]
Is this still needed or was it handled elsewhere?
I've done a few basic node/express backend projects and think that I could handle this. 

I think I understand the requirements. 

Campers should be able to make a get request including latitude/longitude in the request url , and get back a response containing the daily forecast in json.

Is OpenWeather API data that bad? It seemed to provide the basic info I needed. 

If a request/day limited API provides much better data then OpenWeather I could setup a  check on the server. I would log out # of requests in a 24 hour period. If it turns out we are going over the limit for Weather Underground I could create additional api keys that are cycled through once we start getting request failures. 

 Any ideas on dealing with the geolocation issue in the same app? Chrome recently (~6 weeks maybe) removed support for HTML5 Geolocation on non secure origins, i.e free codepen. Some people are using API's for handling that also.

**Comment by calicode** [comment]
I am working on this.

**Comment by BerkeleyTrue** [comment]
Sorry we no longer need this.

Happy Coding

**Comment by lyricism** [comment]
Hey this is Megan. Im going to lose my phone plan tomorrow. Do u know any
wi fi passcodes or any way i can access internet on LG phone?
