### ISSUE TITLE
A new testcase recommended for Checkpoint: Record Collection

### ISSUE THREAD

**Issue by LujunWeng** [FreeCodeCamp/FreeCodeCamp#5993]
[link to checkpoint](http://www.freecodecamp.com/challenges/checkpoint-record-collection)
If people do not check `collection.hasOwnProperty("tracks")` and push the `value` directly, they still can pass the checkpoint. Therefore, I suggest that another test case should be added to fail this situation, like this one:
```
update(5439, "tracks", "ABBA");
```

**Comment by SaintPeter** [comment]
I deliberately omitted this type of test case - not requiring them to create a new array prior to pushing - because it adds complexity to a "simple" Checkpoint.  If this were a Bonfire, I would do that in a heartbeat, but it's not intended to be that difficult.

Folks already have enough trouble as it is, so we won't be changing this one.

Thanks and Happy Coding!

**Comment by cybot1711** [comment]
I am having trouble with this one. I cannot seem to use the push method to push value to end of array. It does not seem to work.

**Comment by SaintPeter** [comment]
@cybot1711 Please try the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
