### ISSUE TITLE
Unable to recognise a link in second paragraph

### ISSUE THREAD

**Issue by bozdar** [FreeCodeCamp/FreeCodeCamp#6018]
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors) has an issue.
Hi,

There is a link in the end of second paragraph of above exercise. The link is in green colour which is difficult to recognise. At first, I thought the link didn't load, so I tried to reload the page; later I found the last word ***here*** is link itself.

I request either change its colour or make it bolder so it can be recognised easily. It's hard to get such links while a user is fully concentrated on a project.

Thanks.

**PS: You can assign this issue to me, and I'll edit it myself.**

**Comment by edwardp11** [comment]
Could you provide a copy of the code

**Comment by raisedadead** [comment]
:+1: 

As a matter of fact I think this should be done for almost most of the links, in other challenges too.
for example, the Read-Search-Ask links in the bonfires, and so on.

![link](https://cloud.githubusercontent.com/assets/1884376/12222125/fd07f038-b7d8-11e5-9189-27f9fadd6fc4.PNG)

Because, for some differently abled, distinguishing between colors is sometimes really challenging, for example yours truly always misses the diff between a black line and a dark green line which are almost similar, for example in the text screenshot above.

I am not sure about the color scheme for FCC, but I do feel the links could be made more prominent.

**Comment by SaintPeter** [comment]
We can make a challenge specific change to the CSS for links to give them whatever color we like, or add a text decoration (underline) to them.  I'm open to suggestions on colors.  I absolutely agree that they're hard to see.

**Comment by raisedadead** [comment]
How about this blue color (Hex code : #31708f), with an underline.
I saw it used here: 

![i](https://cloud.githubusercontent.com/assets/1884376/12229958/7def832a-b872-11e5-8d93-47eaba2adc78.PNG)

It has a good contrast, of course we needn't have to do it bold or italic, just the color and maybe an underline. What do you say?

**Comment by edwardp11** [comment]
I think that will stand out well. I do think an underline would be good, but not sure how it would present with the bold/italic

**Comment by SaintPeter** [comment]
It doesn't have to be bold or italic, just blue, maybe.  Or with an underline.

Here it is with both the bold and blue:
![image](https://cloud.githubusercontent.com/assets/553494/12243782/372baef4-b855-11e5-9204-7d5a175a9278.png)

Rolling over it gives an underline.

**Comment by SaintPeter** [comment]
Bold and green does not look as good:
![image](https://cloud.githubusercontent.com/assets/553494/12243822/5f1a3ca0-b855-11e5-866d-786c0b1616a7.png)

**Comment by raisedadead** [comment]
Yes @SaintPeter , bold and italic are not good.

I like this one as you mentioned:
![](https://cloud.githubusercontent.com/assets/553494/12243782/372baef4-b855-11e5-9204-7d5a175a9278.png)
:+1: from my side!

**Comment by bozdar** [comment]
I am cllosing this issue. Many thanks @SaintPeter
