### ISSUE TITLE
Timestamp Microservice wording

### ISSUE THREAD

**Issue by chrisdziewa** [FreeCodeCamp/FreeCodeCamp#6063]
On this page, http://www.freecodecamp.com/challenges/basejump-timestamp-microservice, it is listed that the user needs to "Build a full stack JavaScript app" when in reality it is just a small API with a landing page. I suggest that this should be changed to something like "Build a small API application" or something similar, as it is misleading.

**Comment by SaintPeter** [comment]
I was unable to find a solid definition of what a "Full stack Javascript App" is online.  To my way of thinking, anything that is using JS on the server is a de-facto "full stack" app, because it's not like you're going to script on the client side WITHOUT Javascript.

Tell me this:
What would you do differently if the description was changed?  In what way would it change your behavior or alter your learning experience?

**Comment by chrisdziewa** [comment]
Well I think that the term Full-Stack can be intimidating for newer coders.
I think if you said something like a "Backend API project" it might take
out some of that initial fear. It was just something I noticed and just
figured I would bring it up as food for thought since I did the project
yesterday.
Le 11 janv. 2016 3:38 PM, "Rex Schrader" <notifications@github.com> a
écrit :

**Comment by SaintPeter** [comment]
Well, you could look at it the other way:  Once they discover how easy the Basejumps are, it might be empowering.  :smile: 

I'm not seeing a need for a change here.  Thanks and Happy Coding!

**Comment by chrisdziewa** [comment]
I suppose that could be true too. No problem, same to you.
