### ISSUE TITLE
Waypoint: Checkpoint: Stand in Line (Disappearing Helpful Links)

### ISSUE THREAD

**Issue by qmikew1** [FreeCodeCamp/FreeCodeCamp#6094]
A camper (in main chat) described an issue with an element disappearing (i.e., seeing momentarily on load and then 'element vanishing'). Was able to reproduce on chromium, firefox, midori (linux x64). There is a line 'helpful links:' (just above the run button) that shows momentarily and then disappears (can be reproduced by refreshing page after load as well). 
![thisone2](https://cloud.githubusercontent.com/assets/13352783/12278216/d987a772-b94d-11e5-85f2-04b3b3687b1f.gif)

**Comment by MyNameIsURL** [comment]
I was able to recreate the bug.  I know what is wrong.  This is the first time I have contributed to this project so it will just take me a second to text it and fix it.

**Comment by MyNameIsURL** [comment]
Follow Up: So this is not really a bug.  The way the code is written is that if there are no links...then it collapses to hide the text.  If there is at least 1 link...then it does not collapse down.  Although I would probably prefer that it not quickly flash, I don't think it is a big enough deal since it is technically working properly.  Thanks.

**Comment by SaintPeter** [comment]
I'm wondering why we can't tell at page render time if there are no MDN links in the Jade.  I think the hiding is a legacy from when there was a "Show More" button.  Seems like this should be rearchitected.  I'm going to leave it open in case some industrious soul wants to yank out the JS and fix the Jade.

**Comment by agazone2015** [comment]
Hi guys, dose anyone can give a tip to beginner as to how solve this challenge?

**Comment by bugron** [comment]
@qmikew1 thanks for posting this issue!
Nice catch, happens for all Bonfires, JS challenges and Checkpoints that don't have those links. I'm looking into this.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by MyNameIsURL** [comment]
@SaintPeter I think the Html is loading first and then the Javascript snippet (which is at the bottom of the page) is loading second.  If the Javascript which is adding the class collapse was actually a part of the Jade template, then it would show properly on load. But since it is jade with an embedded script tag, the Javascript takes a split second to load after the rest of the Html is loaded.

**Comment by evaldasou** [comment]
My code works only with Microsoft Edge (same code does not work with Google chrome):
  
  arr.push(item);
  var removed = arr.shift();
  return removed;

**Comment by SaintPeter** [comment]
@evaldasou -
Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by mfollowill** [comment]
Mine worked like this:

function queue(arr, item) {
  // Your code here
  arr.push(item);

return arr.shift(item);
  
    // Change this line
}
