### ISSUE TITLE
returning element that was removed from []

### ISSUE THREAD

**Issue by computerjohney** [FreeCodeCamp/FreeCodeCamp#6103]
test includes returning element that was removed from [] (which is undefined)
then magically get 1 to pass...
so you have to do something like 
var toReturn = arr.shift() || 1;
???

**Comment by TravisHi** [comment]
Waypoint #?

**Comment by sludge256** [comment]
I believe he is talking about [Checkpoint: Stand in Line](http://www.freecodecamp.com/challenges/checkpoint-stand-in-line)

In regards to this test:
>queue([], 1) should return 1

1 is passed into the array. Then, since it is the first (and only) element in the array, it should be removed and returned as output 
This is expected behavior.

Feel free to comment again if I am misunderstanding the intention of your post.
[Help Chat](https://gitter.im/FreeCodeCamp/Help) is also a good resource for these types of questions.

**Comment by computerjohney** [comment]
Thanks - you're right - didn't read properly! Help chat next time
