### ISSUE TITLE
repeat a string repeat a string

### ISSUE THREAD

**Issue by leprekon91** [FreeCodeCamp/FreeCodeCamp#6123]
is this some bug or am i doing  something wrong?
![image](https://cloud.githubusercontent.com/assets/16616480/12295555/7248242a-ba0a-11e5-93ac-bfb484d1287d.png)

**Comment by bugron** [comment]
@leprekon91 thanks for posting this issue!
Your variable `n` in the loop `for` is not defined. I think it should be `num`.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by hallaathrad** [comment]
Hello @leprekon91, 

Though @bugron 's response is correct, and your `n`should be `num`, (and I would personally also suggest to add the `{ }` to that for, as a good practice), this and any similar questions can and should be asked in our new #helpjavascript channel. 

We're trying to keep github posts only for verified bugs, in order to make it easier for those mythical FCC back-end gods to deal with those hordes of code insects.

Alternatively, please feel free to approach me directly on Gitter. My username is, as you can see, @hallaathrad. Happy coding!

**Comment by leprekon91** [comment]
thank you guys!(cant believe i missed it.)  i will post further questions in the gitter
