### ISSUE TITLE
Overview of progress and links to different sections in the map view

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#6191]
I like the new look and layout of the site, but think this is a missing feature.

I would like to see the same kind of **simple overview of my progress** (using progress bars) and also **quick links** to different sections of the curriculum at the top like I could before.

**Comment by sguermond** [comment]
I agree, the progress bars were my most-used feature on the map.

**Comment by Frithan** [comment]
a quick way to navigate the list would be good, it is way too long to scroll through, especially with the site forgetting what challenge i am on as it is at the moment

**Comment by codemzy** [comment]
I agree, the map progress that used to display at the top of the map page with each section and how far you were through was really handy because you could quickly see which sections you still needed to do and how far through the challenges you were on each section and overall.

In the new map layout you have to expand each section and scroll through to see which checkpoints are not ticked off, which is more time consuming and it is easy to miss the odd one.

With the new layout it makes it harder to know how far you have progressed.

**Comment by AkiraLaine** [comment]
I believe it was temporarily disabled as they are moving FCC to React.

**Comment by rviktor87** [comment]
I agree

**Comment by SaintPeter** [comment]
This is definitely on the Road map.  They were removed temporarily as we're making larger changes to the site.

**Comment by Greenheart** [comment]
@SaintPeter Ah, good! :smile:

**Comment by adamemnonS** [comment]
Great! I'm already missing them!
