### ISSUE TITLE
Bonfire not listed in profile but is marked completed in map

### ISSUE THREAD

**Issue by dcnr** [FreeCodeCamp/FreeCodeCamp#6196]
Hi it's not quite the same as #6193 so I opened a new issue instead.

My Validate US Telephone Number is missing when viewed from my profile, but it's marked as completed in my map. Yesterday before the layout change I was refactoring it and left it unsolved, maybe that's why there's no viewable working solution for it?

**Comment by trueskawka** [comment]
Same here - completed four items today, wanted to share my solutions, no can do.

**Comment by ingochris** [comment]
+1 Issue experienced here on my end as well for all newly passed challenges since the layout revamp. New passes do seem to appear on Profile's Calendar, though.

**Comment by thadseaver** [comment]
Same here. Since the new layout change, completed challenges (Bonfire, in my case) don't show up in the code portfolio, although they do show up in the calendar and they are checked off as complete in the Map. This seems to make it impossible to view my solution.

In the attached image, you can see in the calendar that a challenge was completed on Jan 16, but the list below it shows that the last completed challenge was on Jan 7.

![missing completed challenges](https://cloud.githubusercontent.com/assets/8334645/12390927/22a27eec-bdb2-11e5-9012-64d54525413b.png)

**Comment by dcnr** [comment]
My profile's updated now, with the "Last Updated" field set and too. My Bonfires had also been renamed to Algorithms now, and Waypoints to Challenges.

I've looked at @ingochris and @thadseaver 's profiles and it seems that they've updated too! :smile: 

I'm closing the issue, thank you all!

**Comment by BerkeleyTrue** [comment]
Happy Coding!

**Comment by thadseaver** [comment]
Thanks Code Camp Team. Good job! :+1:

**Comment by ingochris** [comment]
Thanks, @BerkeleyTrue!
