### ISSUE TITLE
Completed challenges marked as completed, but not really.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#6209]
On my Map every challenge I did is marked as complete. But if I go to one that's completed, like one of the Waypoints, it's marked as incomplete as shown below:
![image](https://cloud.githubusercontent.com/assets/11958359/12371015/d6c0ae9c-bc79-11e5-8516-6e483ae753ab.png)

Note: This also allows user to get another brownie points upon completing the challenge again.

**Comment by alistermada** [comment]
Can confirm. I just got 1 brownie point from redoing the "Hello World" Waypoint. 

However, it's marked as complete now. It seems this only affects challenges that are completed before the update, which is pretty much all the challenges for most folks.

**Comment by alistermada** [comment]
@AkiraLaine I think this issue has already been resolved. Can you confirm?

**Comment by cannelflow** [comment]
yes it like that for me also if you try to access it through http://www.freecodecamp.com/map but you can find your solution if you navigate from http://www.freecodecamp.com/username and i agree with alistermada that it is only for challenge completed before UI change.

**Comment by alistermada** [comment]
@SaintPeter Can you check this out to confirm this? This seems to be related to #5957 which was closed because the problem wasn't able to be reproduced.

Here's how to reproduce it:
**1.** Find a challenge (either HTML & CSS or Algorithm) that you completed a while back and have not updated since. For this example I'll use [Inform with the Paragraph Element](http://www.freecodecamp.com/challenges/inform-with-the-paragraph-element) which I completed on June 20, 2015.

**2.** You should see that the challenge doesn't have a green checkmark on the challenge view...
![image](https://cloud.githubusercontent.com/assets/12993334/12870502/8868d3ac-cd7a-11e5-88b5-a5bd8d6b6e52.png)
... despite being marked as complete on the map.
![image](https://cloud.githubusercontent.com/assets/12993334/12870512/058b128c-cd7b-11e5-91a8-fed26dd484cd.png)
If there's a green checkmark on the challenge view, go back to step 1 as this bug won't affect that challenge.

**3.** Complete the challenge. You should notice your brownie points go up by 1.

**4.** Check out your code portfolio. You'll now have a copy of that challenge completed today.
![image](https://cloud.githubusercontent.com/assets/12993334/12870526/ba425b36-cd7b-11e5-8b0f-a267caec9075.png)

**Note:**
* If you go back to that same challenge, you should notice that it's now marked as complete in the challenge view. Redoing it again won't give any brownie points.
![image](https://cloud.githubusercontent.com/assets/12993334/12870533/14a51816-cd7c-11e5-8646-f25dab29567c.png)

* Other challenges besides HTML & CSS and Algorithms don't seem to be affected by this bug.

* If you can't reproduce this, check out my [code portfolio](http://www.freecodecamp.com/alistermada). You'll see that I have 3 items done today (Feb 7, 2016 on my timezone). Those are 1 algorithm and 2 HTML & CSS challenges I've just redone and received brownie points for.

**Comment by SaintPeter** [comment]
Confirmed with a challenge I had completed back in July.

This is interesting, because the code looks like it checks by challenge ID:  https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/challenge.js#L56

What is doubly interesting is that it does show complete on the map.

Before October it did much the same:
https://github.com/FreeCodeCamp/FreeCodeCamp/commit/6c305dbc6763b4bda0c164e6fd2a5516ce08c366#diff-8a44057642cd527c3f82ba5df883ccebL42

Previously the logic was backwards, though:
https://github.com/FreeCodeCamp/FreeCodeCamp/commit/03ea412b4a0837122fefb3e87ebecb0814ae1081#diff-8a44057642cd527c3f82ba5df883ccebR65

It would check to see if the challenge was "uncompleted".  But as near as I can tell, that change predated my completing the challenge.  I can't imagine how it would affect this.

I can only presume that the way these were stored was maybe funky?  It may be hard to debug without seeing my user object.

@BerkeleyTrue Can you take a look at my user object to see if the challenge completion info is stored differently and/or if the updated logic is somehow missing that?

**Comment by bugron** [comment]
I am not able to reproduce. @SaintPeter @AkiraLaine @alistermada @cannelflow is this still an issue for you?

**Comment by AkiraLaine** [comment]
@bugron Hey! No, I don't have this problem anymore. I'll go ahead and close this as no one else reported anything in a while

**Comment by bugron** [comment]
@AkiraLaine awesome, thanks.
