### ISSUE TITLE
Latest solutions not saved

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#6228]
I'm having this issue since a month. My latest new solutions (which i had completed previously) are not saved again. It seems like I'm not improving. :pensive: 

For instance, I had completed **Find the Longest Word in a String** on *Aug 02, 2015* in 3 different ways and they're saved. But today, I tried to submit another new way to solve it, and although marked completed, submitted and moved to another challenge, it didn't save my new solution.

http://www.freecodecamp.com/abhisekp

**Comment by jbmartinez** [comment]
Same problem here, I updated a bonfire and my profile doesn't show the changes

**Comment by hallaathrad** [comment]
Are we talking about saving the multiple solutions separately in the portfolio/profile? Or them being updated the latest one both in the profile and the storage of the challenge itself?

**Comment by abhisekp** [comment]
@hallaathrad the issue is about multiple solution are not stored separately in fact subsequent solutions to already completed challenges are not saved anymore.

**Comment by hallaathrad** [comment]
Yes, that multiple solution part seems to have stopped a while ago. Have you or anyone sort of figured out yet since when did it precisely stop working that way?

And while well aware this is beyond the scope of the issue , I'd like to point out this also entails those multiple solutions being shown somehow in a clearer manner... repeating the solution with a date does not really do the different solutions justice. 
Perhaps the function was removed not exactly by mistake but to avoid this? I'm guessing then the latest solution would've been the only one saved these days, which I thought was the case.

**Comment by abhisekp** [comment]
It would be nice to only save unique solutions by removing all the white spaces from the code and multiple solutions should be encouraged.

**Comment by hallaathrad** [comment]
Perhaps, rather than saving the actual code to be opened in the challenge page, each version of the function should just be appended to a same markdown article. Similar to how the solutions are shown in the wiki? 
solution 1
solution 2
solution 3

This in order to allow comparison as the student evolves?

**Comment by abhisekp** [comment]
@hallaathrad I think it would be nice if solutions appear like this
> [![](http://i.imgur.com/tD7NEZu.png)](http://i.imgur.com/tD7NEZu.png)

> NOTE: this is a preview of my solutions to a challenge in hackerrank.com

**Comment by hallaathrad** [comment]
That would be lovely, if the list was not miles long already. There's got to be a better solution than racking up multiple lines for the same challenge, as all it would take would be for you to change the white space in the code to make a new solution.

**Comment by jbmartinez** [comment]
I know that there are no multiple solutions and I think it's better that way, but I was able to *update* my solutions. My updates are not saved anymore

**Comment by abhisekp** [comment]
My solution which I did just 2 days back now show in the profile. But another new solution of a previously solved challenge that I did today, isn't showing in my profile.

**Comment by BerkeleyTrue** [comment]
A couple of months now, we changed from saving every solution to only saving one solution. There where several reasons, the main one is completedChallenges for some users were getting way out of hand and DB storage space and DB throughput are our main expenses. Another is we wanted to discourage this very behavior described in this issue.

I see that @abhisekp you have not completed any projects. These are the bread and butter of development. We see this all the time, campers focus on getting algo's perfect or finding as many solutions as possible. This isn't an accurate representation of what being a developer is about. 

Projects are the real world in dev. Getting to the nonprofit projects is the end goal with Free Code Camp. 

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/challenge.js#L77 Here is were we overwrite existing challenges with new solution.

If solutions are not being overwritten, then that is a bug.
