### ISSUE TITLE
A few challenges accept answers that should not be valid

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#6244]
Challenge [Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20total%20%3D%201%20%2B%2019%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line
var total = 1 + 19;


```

The code above actually passes when it shouldn't. The instructions are: 

>Declare and initialize a variable total to 0. Use a for loop to add the value of each element of the myArr array to total.

**Comment by alistermada** [comment]
Don't know if I should open a separate issue, but there's a related problem in another challenge: 
[Use Bracket Notation to Find the Nth Character in a String](http://www.freecodecamp.com/challenges/use-bracket-notation-to-find-the-nth-character-in-a-string).

Instruction:
> Let's try to set thirdLetterOfLastName to equal the third letter of the lastName variable.

This passes but shouldn't:
`var thirdLetterOfLastName = 'v';`

Also, the instruction needs to be rewritten to explicitly state that the answer needs to use bracket notation.

**Comment by jamesbvsh** [comment]
How would you write a test for that?

**Comment by SaintPeter** [comment]
Well, a couple of things we could do:
1. Check for `for`, since there should be two for loops (The example and the real one)
2. Check for `total = \d+` as a negative - you should not be assigning an digit to total.

At some point we have to sort of give up, though.  There are always going to be limits to what we can test for.  A determined attacked will always win over fixed tests.  See Also:  Godel's Incompleteness Theorem.  

The main thing we try to do with our tests is make sure that users don't *accidentally* come up with a wrong solution.  Arguably, this falls into that category already.

**Comment by gordonms1** [comment]
In your for statement i should be less than or equal to the array. i <= arr.length

If not, the for statement will look for a number less than 20.
