### ISSUE TITLE
Interesting in eventually forking this project for a C/C++ analog

### ISSUE THREAD

**Issue by emkk** [FreeCodeCamp/FreeCodeCamp#6278]
Is there anything I should know? Has this been done already?

Mostly any information around getting it up and running would be very helpful.

**Comment by SaintPeter** [comment]
This guide: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md describes how to get a local copy up and running.

I am not aware of any such fork, but it seems to me you'll have a tough row to hoe, since you'd need a web-based c-compiler or a way to compile test your code on the server backend.  This site looks interesting: http://ideone.com/ 

Testing will similarly be . . . interesting.

Best of luck!
