### ISSUE TITLE
Highlighting leads to options in code editor. Would Shift + highlight be better

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#6290]
Hey guys,

I just noticed a new feature in the code editor today. Its great to have for copying and pasting code to ask questions, but it can get in the way if I am just doing regular copy and pasting.

Would a better solution to this be to hold down shift + highlight the section as a way to access the menu?

What do you guys think?

**Comment by tesla809** [comment]
Thinking about it, one can just proceed with just ctrl + c and go on with task. Not a huge issue, but it will be interesting to see if anyone thinks the same.

**Comment by SaintPeter** [comment]
We have some tension here between discovery and usability.  It goes away readily enough and I don't think once you have your code already selected that you need to see under it.

The value of having it always pop up is that there is no question on how to do it.

**Comment by ltegman** [comment]
I'd usually be the first person to get frustrated but a popup like this, but I don't find it bothersome. Highlighting something and then needing to carefully read the whole thing AFTER I've finished highlighting isn't something I find happens in my personal workflow and it's easy enough to click somewhere else and remove the highlight if you want it to go away quickly.

**Comment by alistermada** [comment]
One problem I notice is that if you replace whatever you're highlighting, the popup doesn't go away even if nothing is highlighted anymore. Since nothing is highlighted, the links in the popup don't do anything. This could also present another problem if it's blocking whatever you're trying to type.

It seems to only go away with a mouse click, but should be removed with keyboard strokes as well for the sake of convenience.

**Comment by OriBon** [comment]
This feels like something that is going to become very distracting as we continue to see it more often.
The popup does not move if you highlight something in order to type over it. Say for example I typed in the wrong argument in my comparison function, I want to go up to highlight it and replace with whatever my correct text is, but that popup box is covering everything. I can't see what I am typing.  Example shown in the provided picture.
![screenshot from 2016-01-19 05 37 08](https://cloud.githubusercontent.com/assets/10662057/12416457/96daa204-be6f-11e5-9d89-387eaf79e1ec.png)

**Comment by p1xtcode** [comment]
The popup is "in the way" - every single time I highlight some text - whether I'm highlighting it in order to copy it, paste over it, or just because I felt like highlighting a couple lines so they'll stand out while I think about them.

It obscures what I'm working on. It covers not only what I'm trying to highlight, but also lines below and above it.

Adding a "feature" that tosses up a constant hurdle, obscuring the editor, making it more difficult to see the code, is a wretched UX decision.

If people don't know how to do a simple thing like cut and paste some text on a web page, a far more helpful and non-intrusive solution would be a waypoint that explains ctrl-c and ctrl-v.

**Comment by matty22** [comment]
Agree with @p1xtcode. At least half of the time, I am highlighting not to copy/paste, but to replace text or just so I can keep my place while I think about stuff. This pop-up obscures my code and makes those two actions harder to do.

I have noticed that if you highlight and then move your cursor very quickly away from your highlight area, that the pop-up will appear wherever your cursor is after that short delay. So it's a constant race against time every time I highlight some code to get my cursor as far away from that area of the editor so that the pop-up appears elsewhere. Like this:

![2016-01-19_0732](https://cloud.githubusercontent.com/assets/7202935/12423115/c44b4374-be7e-11e5-9756-8925bb4be1d0.png)

**Comment by clarebhamilton** [comment]
I completely agree with matty22 and p1xtcode. This is extremely annoying, especially as it obscures your code.

**Comment by bugron** [comment]
Thanks everyone for this discussion. I'll make the selection with `CTRL+highlight` and will create a PR soon.

**Comment by p1xtcode** [comment]
Anyone wanting to stop discussing and just take the matter of personally removing the annoyance in your own browser --- the following Tampermonkey script will disable it:

```
// ==UserScript==
// @name         FCC remove copy popup
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       P1xtCode
// @match        http://www.freecodecamp.com/challenges/*
// ==/UserScript==
/* jshint -W097 */
'use strict';

$('#copy-btn-parent').remove();
```

Presumably if you're using Firefox instead of Chrome, the script should (theoretically, I didn't test it) work in Greasemonkey as well.
