### ISSUE TITLE
Proposition: Normalize user.progressPoints to user.brownies

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#6305]
**In the beginning there were timestamps**, initially just dumped straight timestamps in the array of what used to be called progress points when a camper completed a challenge.

**Let there be thanks!**, so then we started to give points to those who where thanked in the our chatrooms. This is when progress points were now officially called Brownie Points (BP). These need to store information in order to prevent someone from giving another camper infinite brownie points, so we stored these points as objects with `giver`, `receiver` in addition to timestamp.

**Thou shalt Open Data**, so we started to track challenge completed information in anticipation of releasing information to the public.

**Though shalt Normalize**. Now that we see some stability in how brownie points look, there is chatter about making BP's for algorithms, formally bonfires, and projects, formally ziplines/basejumps, count for more BP's than normal challenges, formally waypoints.

Since there is a need for uniformity, It might be a good idea to start a migration.

**Comment by ltegman** [comment]
Did someone say bronie?
![tumblr_m3rum3a8hy1qd3nj5](https://cloud.githubusercontent.com/assets/1381313/12422750/4a5e1466-be7d-11e5-935a-39a950feb048.jpg)

**Comment by raisedadead** [comment]
Nice catch @ltegman :laughing:
However I really like this idea of having the uniformity @BerkeleyTrue :+1:

**Comment by OriBon** [comment]
Will these increased points for completing algorithms be retroactive to all the people who have already completed a number of algorithms?
Say I already completed 5 algorithms. Is my brownie score suddenly going to increase by an additional 5 points to account for the new brownie value of algorithms?

**Comment by BerkeleyTrue** [comment]
@OriBon yes, this is a migration that will cover all users.

**Comment by hallaathrad** [comment]
So, if I understand correctly, we're renaming "brownie points" to "waypoints"?
Also, we should consider explaining the current score system in the interim as mentioned in #12460.
It'll ease the transition if people understand before hand that little number they've been seeing forevermore, and we'd just update the info to add the new scoring afterwards.

yes, no, maybe? 😃

**Comment by raisedadead** [comment]
> So, if I understand correctly, we're renaming "brownie points" to "waypoints"?

No, I think you got Berkeley's comments on the opening post wrong. In his wizard-ish talk, he meant normal challenges were called waypoints (back then). We had a theme and fancy wording for challenges then namely bonfires, ziplines, basejumps, waypoints. We moved on because we have now users who may not understand such terms (so a simpler standard naming was followed).

Here's what we plan to do (I think):

- The `user.progressPoints` will be renamed to `user.browniePoints` in the code, to bring in uniformity.
- They will updated as such in the DB.
- Finally, we may update points by not a value of 1, but a multiple of 5 or 10 to make it clear that these are scores, so, challenges may have increments of say 5 points, thanks in chat rooms may have 5 points and similar. 
- If the last point is taken up, we will also migrate (normalize) all current users to such points (adding points to bring them at par, of such a system).

**Comment by Bouncey** [comment]
Is there a preference as to how many points are awarded for the different types of challenges? 

At the minute I'm giving step and video challenges 2 points, projects 10 and everything else 5.

**Comment by hallaathrad** [comment]
We've been discussing this recently on https://github.com/freeCodeCamp/freeCodeCamp/issues/12460, and just so we can keep things sane, let's focus this issue on @Bouncey's question (how many points per accomplishment/event), and what that would look like in model and logic.
Thus, that other issue will be able to focus exclusively on UX and UI (such as where and how we're telling people they've received 10 points).

That said, Quincy's and I have agreed on awarding at minimum 10 point increments. Thus, regular challenges should give you 10 rather than 1. (i.e. add a 0). This would be the first step.

Then, if we were to implement higher increments, I propose 20 per thank you, 50 per algorithms and non-basic challenges, and 100 per project. 
Any opposed? @freeCodeCamp/moderators

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38769)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNy-0005ia-C8
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:34 -0400
Received: from out-12.smtp.github.com ([192.30.254.195])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUNY-0006Gc-V2
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:09 -0400
Date: Sun, 03 Jun 2018 07:53:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037587;
	bh=R1pQZawM2L7AaQGsTm1Qj/Dz3s8a9J14FU+D/YV6gXU=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iYD9lHSvXfcIhrkkRngRiQKuopsKopvVzuln/NiOSTpuMze6+TCR7g3eqoITd6Nlj
	 mX5KT+D0PL2QkUynajUBrZSYuTowiGI0GEHHyDhGKkqOnq0N9l7gGQTAzVA4wTfajC
	 /1UYeSFsai5Vzjz8ZuiR9pPgaMedBcQojjvCMicc=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38781)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNz-0005jh-Be
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:35 -0400
Received: from out-5.smtp.github.com ([192.30.252.196])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUNZ-0006Ge-Ta
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:10 -0400
Date: Sun, 03 Jun 2018 07:53:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037588;
	bh=rjvWQ8ELIVMpm5oBLiCZeXv3D2LFXXw7d8k8xyYLndA=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=EYngvUJryuJC5lsnjW3Szjy7skjNICFnH4yKSSP7b/41W579hENsiTHDSabLUDZDx
	 eeFLSi3Q/RCuTA4EmJtSnaQO+8qRe1WrKO5JCbMp1E+LHzwDiZ7a6sn/WxV+hQqruU
	 8Izamfv+bOcAxJgziy43tyKZDM/PHPIVjmQRA+tI=
