### ISSUE TITLE
re: Use Conditional Logic with If Statements example

### ISSUE THREAD

**Issue by TerraDrive** [FreeCodeCamp/FreeCodeCamp#6309]
Hello!

This is the example FreeCodeCamp uses in it's description:

function test (myCondition) {
  if (myCondition) {
     return "It was true";
  }
  return "It was false";
}
test(true);  // returns "It was true"
test(false); // returns "It was false"

However it seems like it should be written like this with a { before 'return "It was false"':

function test (myCondition) {
  if (myCondition) {
     return "It was true";
  }
{
  return "It was false";
}
test(true);  // returns "It was true"
test(false); // returns "It was false"

I base this on the fact that I passed the challenge only after putting in a { in my false statement code.  
  if (wasThatTrue) { 
    return "That was true";
  }
  {
    return "That was false";
}  
  

Thank you!

**Comment by codeurge** [comment]
It's a bit harder to tell without proper indentation here, but this example doesn't appear to be using this line `return "It was false;"` as an else statement, which is why you're implying it needs an extra `{` before that line.

Instead, this function will fire the first return if the conditional is met, otherwise the function will end at the second return, `return "It was false";` and the line `}` after it is not ending the conditional, but the function.

And verified with the following solution:
```
function myFunction(wasThatTrue) {

  // Only change code below this line.
  if(wasThatTrue) {
    return "That was true";
  }
  return "That was false";
  
  // Only change code above this line.

}
```

**Comment by SaintPeter** [comment]
@codeurge is correct.

```js
if (wasThatTrue) { 
  return "That was true";
}
{
  return "That was false";
}
```
is not proper code because there is nothing to join the two sets of curly braces.

Think of it this way:
If the condition is true, the statement inside the curly braces executes.  That will do a return "That was true", which immediately exits the function.  If that statement does not execute, the very next statement returns "That was false".

If statements are a "Do a thing or don't", not "do a thing or do another thing".

I encourage to to ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help) - there are many dedicated helpers who may be able to explain this sort of thing for you.  Issues are really not for code questions.

Thanks and Happy Coding!

**Comment by TerraDrive** [comment]
Thanks for your reply. 

Please excuse me for not knowing the indentation. 

I honestly thought this was an issue because the example didn't seem to match the solution I used, and the test passed for me. From what you're saying, what I used wasn't the answer the exercise wanted. Your logic looks correct, and codeurges example passed too and looked to of been the correct answer. 

It maybe worth checking how this exercise operates because I passed it without the intended solution in mind.

Thank you very much for your replies and I've learned a lot more! Really enjoying free code camp =)

**Comment by SaintPeter** [comment]
It's possible that you had some accidentally syntactically valid code.  It would be helpful if you could post exactly what wrong code you had that passed - the entire thing.  Use ``` on lines before and after your code to format it properly.

**Comment by A010** [comment]
For me the only way to pass the test is to write the "extra" ''' }''' to make it 
```
  if (wasThatTrue) {  
  return "That was true";
}
{
  return "That was false";
}
``` 
I think it's probably a bug. What do you thing campers?

**Comment by gsharloks** [comment]
Block-level scope does not exist，so you could not use “return” in the “{ }”



发自网易邮箱大师


On 2016-12-24 22:29 , A010<mailto:notifications@github.com> Wrote:


For me the only way to pass the test is to write the "extra" ''' }''' to make it

  if (wasThatTrue) {
  return "That was true";
}
{
  return "That was false";
}


I think it's probably a bug. What do you thing campers?

**Comment by gitakpaudyal** [comment]
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case  1:
       answer = "alpha";
          break;

    case 2:
       answer = "beta";
          break;

    case 3: 
       answer = "gamma";
          break;

    case  4:
       answer = "delta";
      
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);
