### ISSUE TITLE
Onboarding forces opening half a dozen windows.

### ISSUE THREAD

**Issue by p1xtcode** [FreeCodeCamp/FreeCodeCamp#6314]
The onboarding process forces opening GitHub, Chat, Facebook, etc, etc, etc.

The user is blocked from progressing unless they click to open the external window (even if they already have signed up for, for instance, GitHub).

Poor UX

**Comment by SaintPeter** [comment]
This is required because we really, actually want you to do these things.  This is by design.  If it were optional we'd just give a link.  There is a good chance that a significant number of people would never do these things.  Right now we have a very good click through rate on these links.

In Part:
1. GitHub is required because we use it as our primary authentication method.  Later steps will absolutely require that you have a GitHub account.  GitHub is also required for Gitter.
2. Gitter (Chat Rooms) are our primary community and support focal site.  For immediate feedback and assistance, you will HAVE to use Gitter.
3. Facebook is our primary location for physical meetups.  This is not required, but looking at the list is.

I don't see us changing this anytime soon.

Can you suggest an alternative to forcing users to click links to do required activities on other sites?

**Comment by QuincyLarson** [comment]
I agree with @SaintPeter - this is by design. If we put a "skip" button on there, 90% of people would just keep clicking it. It's human nature. We have to force them to actually open the tabs.
Of course, this is frustrating for a small percentage of campers, but I don't see how we can avoid it.
