### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#636]
Small grammar issue/s:

_"Also create a "urgently-red" class that give an element the font-color of red, but use "_

Should probably read something like:

_"Also create a**n** "urgently-red" class that give**s** an element the font-color of red, but use"_

Also from a learning standpoint, the **!important** syntax, is the challenge to implement it via an inline `<style>` or in the class=" ... " section part of the tag itself. 

Based on the challenge it seems to be that the goal is to implement the feature via css declaration rather than implementation via class. But there is not clear guidance on how to implement `!important` within the `<h>` tag itself. I.e. should the student enter something similar to the following (which seems to be the way the challenge would have you solve itself, but doesn't work):

`<h2 class=' blue-text !important red-text'>CatPhotoApp</h2>`

**Comment by QuincyLarson** [comment]
@jessenobata thank you for this excellent feedback. I fixed the typos and added some minor verbiage change to reinforce that this change should be made on the class, and not as a style. I think we only use style attribute in one challenge, because it practice, you should almost never use it. (in fact, we could consider eliminating it from our curriculum all together since it's technically an anti-pattern).
