### ISSUE TITLE
Code window on windows phone 8.1 clears newly typed code on enter key

### ISSUE THREAD

**Issue by pksjw** [FreeCodeCamp/FreeCodeCamp#6413]
In the code window I can type in code, but when I hit enter the code disappears. It's a drag because I'd like to use the down time to move forward. It is not always practical to bring my notebook. I'd use my Kindle but my granddaughter has monopolized it to watch Big Hero 6. 😊

**Comment by pksjw** [comment]
Freudian slip on 'keg', should read 'key'

**Comment by SaintPeter** [comment]
We use the CodeMirror package for online code editing and we are entirely dependent on that codebase for support.

According to [this issue on the CodeMirror Repo](https://github.com/codemirror/CodeMirror/issues/3182), this is a known issue and the developer says that he can't/won't fix it.

You're welcome to chime in over there, but considering that windows phone represents only about 2% of the mobile market and only the tiniest sliver of a fraction of that would be trying to code on their phones, it is unlikely to be fixed.  You may have to see if you can get Netflix on your phone for your Granddaughter. :wink: 

I am going to close this issue since it is not a problem with the FCC codebase.

Thanks and Happy Coding!

**Comment by pksjw** [comment]
Thanks for explaining the issue. I happen to like the WP interface better than other phones/tablets out there. That said, I understand the issue is not under FCC control. It does work a little bit better on the Kindle. I was able to use it when she went to play on the playground with other kids there at McDonalds :)

Thx again!
