### ISSUE TITLE
OpenWeatherAPI is incorrect

### ISSUE THREAD

**Issue by Fogthecatman** [FreeCodeCamp/FreeCodeCamp#6424]
Challenge [Show the Local Weather](http://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I would have liked to use OpenWeaterAPI to complete this challenge however the service isn't up to date and isn't working. When I make the api calls I am receiving data that is incorrect and out of range of anything I should be receiving. Is there another service that someone can recommend? I will continue my search for an alternative.

**Comment by YannHulot** [comment]
I have completed that project and I never got the forecast for my district , It was always the data for another city. The point is that the data is not what's important in the challenge but rather if you know how to call the API and how to interpret said data. Don't let the inaccuracy of the service stop you from completing this project.

**Comment by SaintPeter** [comment]
You may be getting results in Kelvin, which is the default for that API unless you explicitly specify Fahrenheit or Celsius.  

This API works "well enough" and is free, so that is what we recommend.  You can search google for other APIs, since there is no requirement that you use this specific one.

I encourage you to ask for help in [HelpFrontEnd](https://gitter.im/FreeCodeCamp/HelpFrontEnd) for more details.

Thanks and Happy Coding!
