### ISSUE TITLE
Feature: Thank URLs on wiki articles

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6448]
We want to encourage campers to create wiki articles, and to expand and improve them.

We also want it to be as easy as possible for campers to thank other campers after they read a helpful wiki article.

![](https://www.evernote.com/l/AqQ5ZkjTTtpMSafmGgszLCY_TNL6uSYZyaAB/image.png)

To this end, I propose that we create a username/thank path, or a /thank/username&username&username path. This way we could put URLs to directly thank campers. The thankor would be the currently authenticated user.

An alternative - if we wanted this to be more visible - would be to create a chatroom called gitter.im/thanks, enable camperbot there, and create URLs to Gitter that pre-populate the message "thank @Rafase282 and @abhisekp".

Now let's talk about abuse. Such a system could be easily abused by a simple chron job. So we would need to place strict limits on how frequently one camper could thank another, or even a global max number of times one camper could thank another (though a crafty abuser could just create brand new accounts every time). One approach might be to make it so, after 5 thanks, only 25% of that user's total thanks could be directed at any given one user - otherwise they wouldn't be persisted.

There may be other avenues for abuse that we need to head off. But I am for making thanking people for their contributions to the wiki as frictionless as possible.

**Comment by SaintPeter** [comment]
I agree this is ripe for abuse.  We currently have a timeout of 1 thanks per 60 minutes per giver/reciever pair on the Camperbot.  I'm thinking this should have a much longer half-life.  Maybe 24 hours?

My secondary concern is:  How does someone know they've been thanked?  With Camperbot it's really obvious and public, but with this you could be thanked 10 times a day and never know it.  Which is actually kind of a problem on the news as well - you can get upvotes galore but you don't really SEE that.

Maybe a pop-up or a toast when you visit the site:  "You have received XX points from your news article YY since your last visit" or "Camper @BlahBlah thanked you for 'message here'".

Actually, along these lines, it might make sense to have a "Brownie Point History" page linked off the profile page.  Something that displayed a pie-chart of how your got your brownie points as well as a reverse chronological list of recently received points.

Thinking more about this:
This could be an automatically generated link from the new Wiki.  There could be a meta-data section of the file which has "contributors" which the site could parse to generate the link.  Then it could append a `&for=Wiki Page Blah Blah` to the URL?

**Comment by atjonathan** [comment]
Closing as we have moved to the forum and have removed the credits.
