### ISSUE TITLE
Show User's Map on User's Portfolio Page

### ISSUE THREAD

**Issue by sealocal** [FreeCodeCamp/FreeCodeCamp#6452]
The new design progress is awesome!  I really like that (my) Map is easily accessible on the right-hand side of the screen.  I think the Map could be utilized in another helpful way.

If I want to show someone my progress, I send them my user portfolio page:  http://www.freecodecamp.com/sealocal.

They can see everything I've solved, but it's overwhelming and doesn't give a high-level overview.  So, I'm suggesting that when someone views my portfolio page and then clicks Map on the nav, they should see *my* map, not their *own* map.  Then, any camper can get a quick idea of where their fellow campers are on in progress, perhaps encouraging collaboration or healthy competition.  Perhaps there's a better way, but I think the progress report on the portfolio page is not very useful as-is.

 Thoughts?

**Comment by santakmishra** [comment]
I agree with @sealocal . Just listing out all the challenges completed in a long table is kinda inefficient. I have a different solution though. I was thinking of displaying the major section titles in a table and then linking to the list of completed challenges within that section.

**Example**
The main table on the profile page could look something like this:-

Section | Date of Completion | Last Updated | Status
----------- | -------------------------- | ------------------ | ---------
[Getting Started](http://link-to-list-of-challenges) | Dec 23, 2016 | Jan 26, 2016 | Completed
[HTML & CSS](http://link-to-list-of-challenges) | Jan 3, 2016 | Jan 12, 2016 | Ongoing
[Bootstrap](http://link-to-list-of-challenges) | Jan 10, 2016 | Jan 16, 2016 | Not Started
[jQuery](http://link-to-list-of-challenges) | Jan 23, 2016 | Jan 26, 2016 | Not Started

And then upon clicking the links of each section, the list of challenges within that course would be displayed. Hope I was able to make it clear.

**Comment by rawreef** [comment]
I agree with @sealocal too that the portfolio page is overwhelming now. I am applying for jobs and want my FCC portfolio page to be a useful page for potential employers to look at. It actually used to be better because the old Bonfires (difficult algorithm challenges) used to be listed before the old Waypoints (easier challenges). Now these two have been mingled together as algorithms.

What's worse is that the algorithms list now begins with the relatively simple old Waypoints, which aren't really algorithms at all but something closer to copying and pasting (useful while learning of course, but not a great showcase of one's skills). So a potential employer might see the "Algorithms" title, click on an old Waypoint, and then think "Wow! This Free Code Camp is a bit simple and lightweight!"

So how about re-dividing the old Waypoints and Bonfires into "basic algorithms" and "complex algorithms", or something like that? And then listing the harder stuff first on the portfolio page.

**Comment by MajideB** [comment]
7372
