### ISSUE TITLE
No Repeats Please - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by michaelkro** [FreeCodeCamp/FreeCodeCamp#6470]
Challenge [No repeats please](http://www.freecodecamp.com/challenges/no-repeats-please#?solution=function%20permAlone(str)%20%7B%0A%20%20%0A%20%20var%20permutations%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20function%20doPerm(str%2C%20arr)%20%7B%0A%0A%20%20%20%20if%20(typeof%20(str)%20%3D%3D%3D%20'string')%20str%20%3D%20str.split('')%3B%0A%20%20%20%20if%20(str.length%20%3D%3D%3D%200%20%26%26%20arr.join(%22%22).search(%2F(.)%5C1%2F)%20%3D%3D%3D%20-1)%20permutations.push(arr.join(''))%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20var%20x%20%3D%20str.splice(i%2C%201)%3B%0A%20%20%20%20%20%20%20%20arr.push(x)%3B%0A%20%20%20%20%20%20%20%20doPerm(str%2C%20arr)%3B%0A%20%20%20%20%20%20%20%20arr.pop()%3B%0A%20%20%20%20%20%20%20%20str.splice(i%2C%200%2C%20x)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20doPerm(str%2C%20%5B%5D)%3B%0A%20%20%0A%20%20return%20permutations.length%3B%0A%7D%0A%0ApermAlone('abcdefa')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello, the following code works for the shorter strings and passes the tests (aab, aabb, etc) but it hangs up on the seven character strings.

My code:
```javascript
function permAlone(str) {
  
  var permutations = [];
  
  function doPerm(str, arr) {

    if (typeof (str) === 'string') str = str.split('');
    if (str.length === 0 && arr.join("").search(/(.)\1/) === -1) permutations.push(arr.join(''));
    for (var i = 0; i < str.length; i++) {
        var x = str.splice(i, 1);
        arr.push(x);
        doPerm(str, arr);
        arr.pop();
        str.splice(i, 0, x);
    }
  }
  doPerm(str, []);
  
  return permutations.length;
}

permAlone('abcdefa');

```

**Comment by ltegman** [comment]
This isn't a surprise. For a string of `abcdefa`your code ends up with a 2520 function deep recursive call-stack. This isn't a limitation of Free Code Camp but rather the JavaScript VM. If your code is running into this problem you need to change your approach to the problem.

As a general note, high volume recursive algorithms in JavaScript should be an option of last resort because JavaScript function calls are very expensive and much slower than doing the same work via purely a for-loop (if a for-loop can do what you want, which it can in this case).

Thanks and happy coding!
