### ISSUE TITLE
Waypoint: Comparisons with the Logical And Operator

### ISSUE THREAD

**Issue by Guilder1333** [FreeCodeCamp/FreeCodeCamp#6569]
`function myTest(val) {`
`  // Only change code below this line`

`  if ((val % 5) === 0) {`
`    return "Yes";`
 ` }`

`  // Only change code above this line`
`  return "No";`
`}`

`// Change this value to test`
`myTest(10);`
Fails test:

> myTest(30) should return "Yes"

**Comment by AkiraLaine** [comment]
Hey @Guilder1333, if you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only :smile:

**Comment by Guilder1333** [comment]
Actually it is an issue. Code is valid for val = 30, and should return "Yes".

**Comment by AkiraLaine** [comment]
You're code is completely wrong. Here is the instructions:
> Combine the two if statements into one statement which will return "Yes" if val is less than or equal to 50 and greater than or equal to 25. Otherwise, will return "No".

You're code just checks whether ```val % 5``` is equal to 0.

**Comment by Guilder1333** [comment]
I know that I didn't follow instructions. Anyway, it passes tests for 25, 50, 51 and 24, and fails for 30. And it is a bug anyway.

**Comment by bugron** [comment]
@Guilder1333 thanks for posting. Actually the test checks the value 49 instead of 30 that is why you get false, see [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a006e487388bbbb6a0d91f6ad2c7b068060a12c3/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2523). So the test message doesn't suite to the test itself. Needs to be fixed.
