### ISSUE TITLE
Not able to clear this challenge

### ISSUE THREAD

**Issue by anohedr** [FreeCodeCamp/FreeCodeCamp#6618]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

tried almost all browsers - chrome, IE and mozilla

**Comment by sludge256** [comment]
There 's no need to add a class to your second p element.

In the past, people would bypass the intention of the lesson by adding the font size rule into the red-text class then apply the class to both p elements. However, the purpose was to have the font size apply to **all** p elements without having to apply the red-text class to all of them. That way you are directly modifying the font size of p elements instead of doing it indirectly by applying the class to each individual p element.

It looks like the test was updated to disallow adding the class red-text to the second p element. This new test may or may not be too strict but disallowing it also prevents the user from making a mistake in the next lesson. For now, just remove the red-text class from the second p element.

**Comment by anohedr** [comment]
thanks it worked!

**Comment by gjergjipro** [comment]
had the same issue thank you
