### ISSUE TITLE
nothing appear in the iphone on right 

### ISSUE THREAD

**Issue by blackwaterx** [FreeCodeCamp/FreeCodeCamp#6722]
Ok when i start the exsercise it suppose to have something in the iphone on right but nothing appear. i wondering if someone could help me to know if that could be my computer or some setting  on the site.
thanks

**Comment by SaintPeter** [comment]
If you click the "Bug" button from the challenge in question it will copy your current code as well as append useful information about your current browser.  I'm going to close this issue since it doesn't actually give us any information at all about the problem.

Please use the Bug button to open a new issue and give details such as your OS, Browser, and if you have any errors in your browser dev console.

**Comment by blackwaterx** [comment]
thank you very much i ll try that

**Comment by VibhorThakral** [comment]
I had the same problem you had at first, I later found out that the problem was due to my ISP provider, using proxy has helped me so I guess you can try that.
