### ISSUE TITLE
Test state does not change after JavaScript error

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [FreeCodeCamp/FreeCodeCamp#6780]
Had a typo in my code and most of the test past when none of them should have. See result = loolup[val]; this was returning undefined but the first 8 test passed.

Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20lookup%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%20%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%20%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20result%20%3D%20lookup%5Bval%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result;

  // Only change code below this line
  lookup = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie": "Chicago",
    "delta": "Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };
  result = loolup[val];
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by cannelflow** [comment]
checked on chrome windows 10 it checked every condition as passed tough giving error ReferenceError: loolup is not defined .however if you do like result = lookup[vall]; then also it is marking every condition as passed giving error ReferenceError: vall is not defined.

**Comment by alistermada** [comment]
Refreshing the browser seems to fix this problem.

**Comment by SaintPeter** [comment]
``` 
lookup = {  // <------ defined as lookup
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie": "Chicago",
    "delta": "Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };
  result = loolup[val];  // <-----  loolup, not lookup
```

Your code is wrong.  You are not referencing the variable you defined.

In the future, please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by MichaelLeeHobbs** [comment]
SaintPeter, you should go back and thoroughly read the initial issue submission. I pointed out that I had a typo yet test were passing that should not have been. It is painfully clear that you did not read it or the following post where others verified the issue. This only servers to make the last two lines of your post very condescending and greatly reduces the odds that I will take the time in the future to type up bug reports.

Regards

**Comment by hallaathrad** [comment]
@MichaelLeeHobbs I gave it a try and cannot seem to be able to replicate your issue from scratch. As @alistermada explains, this seems to be caused somehow after you have initially passed the tests and then change the variable. It's been brought to the core team's attention, but I don't honestly know whether it'll be fixed soon as it is not system breaking. i.e. it does rely on having passed first.

<img width="751" alt="screen shot 2016-02-07 at 11 28 01" src="https://cloud.githubusercontent.com/assets/2107110/12873548/f722bcbe-cd8d-11e5-9ece-fd3dcc97229f.png">

**Comment by SaintPeter** [comment]
@MichaelLeeHobbs You're right, I did not read the issue submission carefully.  Please accept my apologies.  We get a deluge of "my code is broken" errors and I tend to dispose of them quickly.  As for my last two lines, those are boilerplate and I will never apologize for being polite. :wink: 

I was able to replicate the issue:
1. Run partial code which replicates the 6 red/2 green errors (just running without `result` set.
2. Finish the code, but with a typo (or any JS breaking error) and run it.

![image](https://cloud.githubusercontent.com/assets/553494/12873639/c3902b90-cd77-11e5-98a8-488c2fb32782.png)

Our tests run in your browser and any JS error will interrupt code execution, so the code which updates the test status is never run.

I'm not sure that this is a "breaking" bug, though, since you cannot submit code without a successful run.  Our tests, in totality, represent the test for each challenge.  It's definitely possible to "snipe" individual tests into giving incorrect answers, but harder to get all of them to complete with incorrect code.

It may be possible to flag tests as "incomplete" or "indeterminate" when a code error occurs, but I'm not sure if it's worth it.

Reopening for discussion.

**Comment by hallaathrad** [comment]
Hm considering some of us do go back to improve previous code as our skills get better, it is worth improving (I'd use that worth rather than fixing, as it is not broken... it'd rather be a required enhancement). However, it being non-critical, I honestly do not know whether it would be easy enough to add to justify the brain cycles to do so.

**Comment by rahulkr271** [comment]
why can't we use      result =lookup.val;         in place of          result =lookup[val];

**Comment by hallaathrad** [comment]
@rahulkr271 That's because val is a string (which includes the double quotes, as it is required with the square bracket notation... if you did `.val` it would be `lookup."charlie"`which is invalid code)... however, this is actually a question better asked at the [help channels](https://gitter.im/FreeCodeCamp/FreeCodeCamp), my friend. :wink:

**Comment by raisedadead** [comment]
Can't reproduce any longer, and also not relevant in the new infrastructure.
