### ISSUE TITLE
Arrow functions throw warning but work correctly in code editor

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [FreeCodeCamp/FreeCodeCamp#6782]
When using arrow functions in the code editor you revive a warning: 

'arrow functions syntax (=>)' is only available in ES6 ('use esversion: 6').

However they work correctly with no issues.

**Comment by Greenheart** [comment]
FCC recommends campers to use ES5-syntax until the browser support for ES6 is better (which it most likely will be later this year). [ES6 Implementation status](https://kangax.github.io/compat-table/es6/)

This is to minimize confusion for new developers and let them focus on the core concepts instead of cutting-edge syntax and features. 

Happy coding!

**Comment by sludge256** [comment]
If your browser does support ES6 you can add this to the top of your code to disable the warnings.
`//jshint esversion: 6 `

**Comment by dbess1** [comment]
@sludge256 Thanks!
