### ISSUE TITLE
Issue with the const variable declaration

### ISSUE THREAD

**Issue by PeterChauYEG** [FreeCodeCamp/FreeCodeCamp#6786]
Challenge [Reverse a String](http://www.freecodecamp.com/challenges/reverse-a-string#?solution=function%20reverseString(str)%20%7B%0A%20%20var%20strArray%20%3D%20str.split('')%3B%0A%20%20var%20reverse%20%3D%20strArray.reverse()%3B%0A%20%20%0A%20%20return%20reverse.join('').toString()%3B%0A%7D%0A%0AreverseString(%22hello%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This puzzle doesn't pass if I use `const` for variable declaration.

My code:
```javascript
function reverseString(str) {
  const strArray = str.split('');
  const reverse = strArray.reverse();
  
  return reverse.join('');
}

reverseString("hello");

```

**Comment by Greenheart** [comment]
@PeterChauYEG I get this to work on Chrome/48.0.2564.**103** (64 bit) on Ubuntu.

However, FCC recommends campers to use ES5 until the browser support for ES6 is better (which it most likely will be later this year). This is to minimize confusion for new developers and let them focus on the core concepts instead of cutting-edge syntax and features.

**Comment by ltegman** [comment]
This is not a problem with FCC and is dependent on browser support. Thanks and happy coding!
