### ISSUE TITLE
Russian Translation of React Projects

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#6808]
- [x] Build a Markdown Previewer
- [x] Build a Camper Leaderboard
- [x] Build a Recipe Box
- [x] Build the Game of Life
- [x] Build a Roguelike Dungeon Crawler Game

**Comment by rfprod** [comment]
@bugron I just found a couple of typos in the file I committed yesterday. What's the best way to make corrections. And should the issue be closed by someone else after checking an confirming my commit or should I do it myself?

**Comment by bugron** [comment]
@rfprod the best way is making changes and amending the commit (IMHO). Or you can just add another commit (as you did, this is nice option because I can see what have you changed) and when I or someone else verifies that translation is good amend them and get ready to be merged. PR shouldn't be closed in that case. This issue will be closed when your PR is merged.

**Comment by rfprod** [comment]
@bugron got it.
