### ISSUE TITLE
"Iterate Through An Array With For Loop" not accepting valid assignment

### ISSUE THREAD

**Issue by dvaun** [FreeCodeCamp/FreeCodeCamp#6855]
Hi FCC Team,

This is a minor issue, but was brought up by a redditor[ asking for help with his code.](https://www.reddit.com/r/FreeCodeCamp/comments/44yr21/iterate_through_an_array_with_a_for_loop/)

This is what's not accepted:
`for (i = 0; i < myArr.length; i++)`
`{`
`    total = total + myArr[i];`
`}`

I double-checked the instructions, and didn't see it specifying that it be written as `total += myArr[i]`
Hope this relieves some frustration! :)

**Comment by SaintPeter** [comment]
Yeah, the tests look for `+=` explicitly.  We should allow that or `total = total +`.

**Comment by alistermada** [comment]
My mistake. Should've thought of that. I'll fix this one.

**Comment by deesto** [comment]
This is already "fixed", but I've found just now that the test for declaring 'total' outside of the 'for' loop will still always fail unless an assignment to total (via the '+=' operator or just '=') is used within the 'for' loop. No problem if the user understands that an assignment should be done instead of, say, a function, but otherwise puts them on a wild goose chase for why 'total' isn't declared when it is. Strangely, once the operator has been used, the check seems to remain valid even if the operator is removed for testing, until the code is reset.
![fcc-for-loop](https://cloud.githubusercontent.com/assets/91079/15805206/daf59500-2af0-11e6-8740-e5da5bca719b.png)

**Comment by munteanu1107** [comment]
![image](https://cloud.githubusercontent.com/assets/17503186/23824170/50f19924-067a-11e7-8272-263c12fdce4d.png)

**Comment by rapric2115** [comment]
try this 
var total = 0;  // here you declare the variable to 0, them the for loop.

for (var x = 0; x.myArr.lenght; x++){
    total += myArr.push(x);
};

**Comment by Onwa2014** [comment]
Hello forks, after struggling for few minutes,  I have manage to come up with a solution.

// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup

// Only change code below this line
var myArr = [ 4, 6, 10];
var  total = 0;
for (var  i = 0; i < myArr.length; i++) {
  total += myArr[i];  
}
