### ISSUE TITLE
Error on solution to challenge 

### ISSUE THREAD

**Issue by tasha-a-coder** [FreeCodeCamp/FreeCodeCamp#6878]
**[Adding a default option in Switch statements](http://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements)**
Error: 'Unreachable' break after 'return'. 
on each line of the solution's code that is
`break;`

**Comment by alistermada** [comment]
Please show us your code.

**Comment by W12S12E12** [comment]
the best of http://www.codeproject.com/Tips/801032/Csharp-How-To-Read-xlsx-Excel-File-With-Lines-of

**Comment by hey-its-iota** [comment]
All that means is that you called a `break;` after something that would prevent the `break;` from executing, like a `return` statement.  Example:

```
function sillyFunc(x){
    while(x){
        return x;
        break;
    }
}
```
Because the `break;` happens directly after `return x;`, `break;` can never be called because the function ends when it returns, and so `break;` is unreachable.  Examine your code for a situation that would make it impossible for `break;` to be called.

**Comment by hgonzales76** [comment]
Stop

**Comment by W12S12E12** [comment]
test in here http://www.codeproject.com/Tips/801032/Csharp-How-To-Read-xlsx-Excel-File-With-Lines-of

**Comment by ltegman** [comment]
This is not a problem with the site. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need further clarification in this. Thanks and happy coding!
