### ISSUE TITLE
Test should allow for both double and single quotes

### ISSUE THREAD

**Issue by jamigibbs** [FreeCodeCamp/FreeCodeCamp#6919]
Challenge [Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%20%3D%20'I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22'%3B%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = 'I am a \"double quoted\" string inside \"double quotes\"';

```

The above doesn't pass although it does assign the correct string to the variable. As it is now, the challenge will only accept double quotes to pass:

```javascript
var myStr = "I am a \"double quoted\" string inside \"double quotes\"";
```

**Comment by erictleung** [comment]
I think the point of the challenge is that you use double quotes throughout the entire string. But in order to do that, you need to escape the inner quotes. Otherwise, if you use single quotes on the outside, you wouldn't need to escape the inner quotes.

Maybe the instructions could be more explicit and say to use double quotes around the entire string.

**Comment by jamigibbs** [comment]
I guess I was thinking that the inner quotes were required either way but I stand corrected. Thanks @erictleung!
