### ISSUE TITLE
download progress (and solutions) for backup

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#6932]

**Comment by willnwhite** [comment]
Progress: what if FreeCodeCamp [lost my progress](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2062)? I'd have a backup of my own.

**Comment by Greenheart** [comment]
It's your data so theoretically this could be possible. In addition, there would probably only be a small group of users that keep own backups and therefore the downloads of big json-responses wouldn't be too much of a load for FCC's servers.

But the question is what FCC would do **when users wanted to upload their own json-data to "restore" their progress**. Because I see a possibility for users to **exploit this functionality to add progress without achieving it**. 

At the same time, this backup of the progress would most likely only cover the basic concepts users work with for their own learning and **not the projects or non-profit work** which is what's required for the certifications. Therefore cheating would only hurt the users themselves and because of this situation, this would definitely be possible to implement.

**Comment by willnwhite** [comment]
We could start with downloads only. At least then if FCC lost data, users could "prove" their progress, and FCC would be in control of restoring progress, as opposed to letting users upload their own progress. I would encourage all users to download their progress.

**Comment by bugron** [comment]
@willnwhite let's assume we've implemented this. What if FCC "loses" your data and you still haven't downloaded it? Do you know when such a thing will happen? No, of course. And even if you regularly download your data lots of other campers won't do that. I'm not sure if we'll implemented this but I want @BerkeleyTrue to decide what to do with this issue.

**Comment by willnwhite** [comment]
A "back up your progress" download link in the "success" dialog box would help minimize the number of campers who hadn't backed up.

**Comment by ltegman** [comment]
@willnwhite That's impractical. It's unnecessary UI clutter and we don't want someone downloading their entire user object from the db every time they finish a challenge.

**Comment by SaintPeter** [comment]
We do plan on, eventually, providing a facility to export your challenges to GitHub.  This will not be coming soon, but it will be coming.

**Comment by willnwhite** [comment]
@ltegman Or progress could just be downloaded in the background after each challenge, without UI clutter. An array of integers of completed challenges would be small compared to a page load.

**Comment by willnwhite** [comment]
Especially if ranges were represented: [1, ..., 49, 51]

**Comment by ltegman** [comment]
Closing this as we have GitHub export planned and challenges shouldn't be done for the sake of doing them, but for the sake of learning. If something catastrophic were to happen to the DB people should just pick up wherever their learning is without worrying too much about completing everything, since projects are what really matter (and those are stored outside the DB). Thanks and happy coding!

**Comment by karinakozarova** [comment]
Is there a chance for just exporting them to GitHub?
