### ISSUE TITLE
Move Campsites off of Facebook

### ISSUE THREAD

**Issue by martgnz** [FreeCodeCamp/FreeCodeCamp#6942]
Just a suggestion. I would like to meet fellow FreeCodeCamp students on my area but I don't have Facebook nor I plan to use it.

I know the community is huge and it's be difficult to move on, nonetheless it would be great to have a public place to know when is the local community meeting. If not, it feels like a black box.

For example, a lot of people use meetup.com for these kind of groups. Maybe there's an open source alternative, I'm not sure.

I wasn't able to find any issue regarding this, that's why I opened this one. I don't know if this was already discussed. It's true that Facebook is easier for the average person (everyone has one) and that's probably the reason it was decided this way. But I'm probably not alone, having issues with this choice.

Thanks

**Comment by QuincyLarson** [comment]
Hi @martgnz,
We definitely considered a lot of options before going with Facebook. Facebook has very sophisticated groups functionality. Also, 99% of people do have a Facebook account, even if it's with a fake persona that they just use to get access to Facebook's features without giving them all their data.

The main problem with Meetup is they charge $15 per group per month, which would - with our current number of Campsites, cost $15,000 per month to maintain. 

There are other sites that are free, sure, but it would be yet another tool we'd have to create.

I recommend you create a "burner" Facebook account without any personal details if you have privacy concerns, so that you can still make use of our Campsites. We are unlikely to switch away from Facebook any time soon.
