### ISSUE TITLE
falsy-bouncer: -0 is missing as falsy value

### ISSUE THREAD

**Issue by alawatthe** [FreeCodeCamp/FreeCodeCamp#6994]
Challenge [Falsy Bouncer](http://www.freecodecamp.com/challenges/falsy-bouncer) has an issue.

The description says, that the falsy values are ```false```, ```null```, ```0```, ```""```, ```undefined```, and ```NaN```. However ```-0``` is also a falsy value (and not the same as +0). So this should be added to the list as well. 

You also might what to add a link to https://developer.mozilla.org/de/docs/Glossary/Falsy in the helpful links section which explains the weird case of ```document.all```.

**Comment by ltegman** [comment]
-0 and +0 are the same thing, as evidenced by the fact that `-0 === +0` returns `true`. The `document.all` case is a legacy thing not used in much modern code, so it's not worth mentioning as it can only introduce confusion. Thanks and happy coding!

**Comment by alawatthe** [comment]
I agree with the ```document.all``` case.

However, I do not agree, that ```-0``` and ```+0``` are the same thing. This can be seen by this:

```javascript
1/+0 === +Infinity
1/-0 === -Infinity
```
Or by this
```javascript
Math.atan2(-0,-0) === -3.141592653589793
Math.atan2(-0,+0) === -0
```
The explanation, why ```+0 === -0``` returns ```true``` is due to the fact, that ```===``` uses the [SameValueZero](https://tc39.github.io/ecma262/#sec-samevaluezero) comparison and not the [SameValue](https://tc39.github.io/ecma262/#sec-samevalue) algorithm. 
JavaScript uses the [IEEE 754-2008](https://tc39.github.io/ecma262/#sec-terms-and-definitions-number-value) numbers, which have the concept of a [signed zero](https://en.wikipedia.org/wiki/Signed_zero)

I am therefore voting to reopen the issue.

**Comment by alawatthe** [comment]
@ltegman friendly ping :-)

**Comment by ltegman** [comment]
@alawatthe The concept of signed zero only exists for the purposes of floating point math, to account for the fact zero may actually represent a really small number close to zero. For the purposes of finding falsy values there is no difference and convention is to simply refer to unsigned zero, rather than negative and positive. Introducing the concept of signed zero and all it's implications in a challenge that in no way benefits from that knowledge simply serves to distract from the point.

**Comment by alawatthe** [comment]
@ltegman I disagree, but hey, it's your repo so I'll shut up. :-)
