### ISSUE TITLE
Bug with this page

### ISSUE THREAD

**Issue by fmr38** [FreeCodeCamp/FreeCodeCamp#7046]
Challenge [Constructing Strings with Variables](http://www.freecodecamp.com/challenges/constructing-strings-with-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName = "Ryan";
var myStr = "My name is ";
myStr = myStr + myName + " and I am swell!";
```

**Comment by JoshFisk** [comment]
The instructions are:
1. Set myName to a string equal to your name
2. Build myStr with myName between the strings "My name is " and " and I am swell!"

The code you have provided is not following the second instruction, because the myName variable is not between the two strings. Rather it is between a variable, and a string.

A person solving this challenge is meant to read this line:
var ourStr = "Hello, our name is " + ourName + ", how are you?";
And determine that they should make a new line like this:
var myStr = "My name is " + myName + " and I am swell!";

**Comment by fmr38** [comment]
I figured it out after I submitted that. Sorry and thank you for the
response.

​-Ryan​


*​*
*​*On Mon, Feb 15, 2016 at 3:17 PM, Joshua Fisk <notifications@github.com>
wrote:

**Comment by gofighting123** [comment]
my response is 
``
var myName = "GoFight";
var myStr = "My name is " + myName + " and I am well";
``
then Run Tests, and it passed !! @@

Although I got passed it, i think it might be a little typing wrong problem,
bcz the word **well** and **swell** it's so close.

**Comment by vivekmsundaram** [comment]
> "My name is " + myName + " and I am swell!";
Thanks
