### ISSUE TITLE
Need not show Github configuration steps when signed in via Github

### ISSUE THREAD

**Issue by avinoth** [FreeCodeCamp/FreeCodeCamp#7068]
In the second challenge, steps to create & configure Github account is included. This could be skipped automatically for an user who already signed in via Gtihub.

**Comment by QuincyLarson** [comment]
@avinoth Doing this would require significant infrastructural changes (we'd have to completely refactor how we do the step-style challenges). I'm happy to look at PRs for this if you can think of a way to make this work.
The only downside to the current configuration is the minority of people who already have GitHub accounts need to click a button and close a tab in order to advance.
