### ISSUE TITLE
Change the font Size - Lesson has a bug

### ISSUE THREAD

**Issue by Shivamnema05** [FreeCodeCamp/FreeCodeCamp#7069]
In the mean while when I was working with this problem, it occurs that the second p tag ( which do not containing any class attribute) shows an error of having a class attribute. please fix this issue.
![freecodecampbug](https://cloud.githubusercontent.com/assets/11815650/13085940/c32ae9ce-d506-11e5-98e6-7b3c0c12fe6b.PNG)

**Comment by hallaathrad** [comment]
That's because your CSS code is applying those styles to every `<p>`element. You're not applying any class to the first of them. This is CSS actual behaviour and is not a bug.

Please, make sure to confirm with other users on the [help channels](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) read the [bug reporting guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) before opening any new issues.

**Comment by ReshmaPadmanabhan** [comment]
it occurs that the second p tag ( which do not containing any class attribute) shows an error of having a class attribute. please fix this issue.

**Comment by hallaathrad** [comment]
@ReshmaPadmanabhan I stand corrected. Forgive me, @Shivamnema05, there is indeed a problem with this exercise but it's rather in the way the error message is phrased.

The error is coming up because you've removed the class from the first paragraph, even though it says you shouldn't add a class to the second (i.e. new) one.

@FreeCodeCamp/issue-moderators any way we can change this into two separate tests?

**Comment by techtolentino** [comment]
What are the steps taken to reproduce this error/bug?

I've tried this out multiple times and cannot reproduce this.

**Comment by Mattypay** [comment]
@Shivamnema05 to pass this test just edit in <p class="red-text"> to the first p but not the second one that you created in this step.

@techtolentino the objective of "do not add the class attribute to your new p element." Is giving a false error. The new p element does not have a class attribute; however, the scan reads an error because the original p element has also had the class attribute removed. Simply adding the class attribute to the first p element will have a scan success.

**Comment by escapethebadjob** [comment]
Can anyone help me from here?  I wanted to name the second <p> as <p2> (silly I know); but it did work so far up to where I'm at. I must admit though Mattypay I have not tried your process as yet.
![image](https://cloud.githubusercontent.com/assets/15043311/13404985/6b16c6b6-deea-11e5-85a2-9cf04f01c97e.png)

**Comment by escapethebadjob** [comment]
Okay, I see how it works now.  Placing the { font-size: 16px;} back up within the CSS open and closed <style></style> code after the color text closure} worked well!  
![image](https://cloud.githubusercontent.com/assets/15043311/13405766/0eb3fcfa-deee-11e5-8ac9-59bec44da461.png)

**Comment by Shivamnema05** [comment]
Thank you all for working on this bug. I appreciate that all of you worked hard to solve this one problem.

**Comment by hallaathrad** [comment]
Thank you for helping us notice it :) @Shivamnema05
