### ISSUE TITLE
Fix HowToNPM

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7080]
We need to audit HowToNPM and figure out whether outstanding pull requests exist that can fix our current issues with it. 

I had previously recommended campers stop going after they finished challenge 11 (#3685) but it looks like challenge 10 might be broken now, too: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7073

Here's the largely inactive repo: https://github.com/npm/how-to-npm

Here's what I propose we do:
1. Try to run through HowToNPM and see how far we can get
2. Look at the outstanding pull requests and see whether there might be any that would fix that, and test those locally.
3. Reach out to the person who's maintaining it (currently seems to be @ashleygwilliams) and see if we can convince her to accept those PRs that would fix the functionality, and introduce PRs of our own if necessary.

If that doesn't work, we may need to maintain a fork ourselves, which would be undesirable but not out of the question.

**Comment by Greenheart** [comment]
Everything up to and with challenge 10 worked for me

**Comment by ashleygwilliams** [comment]
hi! i'm ashley. i'd love to help. i don't have bandwidth to test all the PRs but if ya'll would like to help with that i can definitely manage merging and new releases and such. just let me know :)

there are several specific bugs re path names on Windows that i'm aware of and could help point ya'll at .

**Comment by BerkeleyTrue** [comment]
@ashleygwilliams Thanks! I think we can find a couple of people to test out PR's.

**Comment by haasDev** [comment]
@ashleygwilliams looking to contribute to oss for the first time.  Wondering where you are with this and if there is anything I can do to help

**Comment by ashleygwilliams** [comment]
hey @haasdev, this workshopper was not originally my project, i inherited it and have not really done much but try to maintain it. i'm p much open to onboarding new contributors since my day to day doesn't allow me to really maintain it the way it needs.

**Comment by haasDev** [comment]
ok do you just want me to get started by following the path quincy suggested?

Tyler Haas
Web Developer
haasdevelopment@gmail.com
(208) 406 - 3322

**Comment by ashleygwilliams** [comment]
sure- the key is going to be whether you are on windows or not. there is a significant Windows path issue. 

some degrees of complication that you may or may not have considered also:
- permissions and how the user chose to fix them
- did they install node using nvm, or another package manager, or the installer
- are they using this workshopper behind a proxy

^^ those are the primarily degrees of complexity we are dealing with

**Comment by haasDev** [comment]
I am using OS X.  will I not be able to replicate the issue?

Tyler Haas
Web Developer
haasdevelopment@gmail.com
(208) 406 - 3322

**Comment by ashleygwilliams** [comment]
no, you cannot replicate the Windows path issue on OSX. I have a Windows dualboot I use, but as I said, I can't make this a priority rn. You might consider dual booting as well?

**Comment by haasDev** [comment]
How can I do that?

Tyler Haas
Web Developer
haasdevelopment@gmail.com
(208) 406 - 3322

**Comment by ashleygwilliams** [comment]
Please google.

**Comment by M1kep** [comment]
I don't think the issues FCC is facing pertain to: 

> permissions and how the user chose to fix them (or not fix them and is using sudo)
did they install node using nvm, or another package manager, or the installer
are they using this workshopper behind a proxy
do they have admin on their machine

Or windows.

Because the lesson specifically tells you how to run the challenge under a [Cloud9](c9.io) instance, which runs its on linux of some sort, and you have access to sudo, and are told how to install it(NPM) i believe and the proxy thing would be a consistent yes or no when it comes to this use case. But I think they should have an easier time solving the issues since you arent non-existed @ashleygwilliams and @BerkeleyTrue says he can find some people to test them!

**Comment by ashleygwilliams** [comment]
it turns out that your fixes *will* need to not break other people's experience which won't be on Cloud9, as evidenced by https://github.com/npm/how-to-npm/issues.

 i won't merge them unless i know that they won't do that. so while your experience might be easier to fix because it is heavily sandboxed, you **will need to consider** other environments while writing patches.

**Comment by theoneinskane** [comment]
@ashleygwilliams not sure if this helps with this issue but I just got to this challenge and I had some serious issues with it. When it came to publish step 08. It told me that I was not authorised and needed to create a new user ```npm adduser``` but I had already created a user (which it turns out is not a fake one!) I could still pass verify but haven't published anything. I now cannot get past the second publish step and get a lot of errors

**Comment by ashleygwilliams** [comment]
i do not have bandwidth to maintain that project right now (as previously stated), i am happy to receive PRs. this issue is *not* a place to files bugs on the workshop.

**Comment by theoneinskane** [comment]
@ashleygwilliams sorry I should have read the thread better. I'm still a bit new to this.

**Comment by jnmorse** [comment]
I just ran how-to-npm recently just to refresh my memory on some points, mostly the version command, and I was able to complete everything, both locally on my Ubuntu installation, and since it worked there I tried it again on cloud 9 and was able to do it there as well.  Since I remembered having seen this issue here I thought I'd mention it.

![how-to-npm](https://cloud.githubusercontent.com/assets/1467889/14229180/9c030a9e-f8fa-11e5-93cc-bc06e99870fb.png)

some of the issues seem to stem from missing the .npmrc file.  If you look at the screenshot on #7515 you don't see the file listed.

Something I might have done differently on cloud9, I deleted all the files and directories cloud9 added aside from the .c9 directory before installing how-to-npm and running it the first time.

**Comment by hutstep** [comment]
There's definitely an issue with the Dist Tag challenge if you do it on Cloud9. It took me 2-3 hours to realize that. I tried all the solutions I could find on Gitgub and Stackoverflow.
`npm dist-tag add @hutstep/npmtest@1.0.2 testit`
and
`npm dist-tag add npmtest@1.0.2 testit`
I started all over again with HowToNPM a few times. I created new workspaces on C9. I deleted everything in the workspace folder before installing HowToNPN. Nothing worked.
Always this error:
`404 missing : -/package/npmtest/dist-tags`
I then installed HowToNPN on my local Linux box, and everything worked the first time I tried!

Something else I noticed. When you call `npm ls`
On C9 it shows only `npmtest@1.0.2` at the top, but on my local machine it shows `@hutstep/npmtest@1.0.2`

**Comment by hutstep** [comment]
Okay, I tried it again on Cloud9. But this time with a blank project, **NOT** Node.js, like @jnmorse mentioned it here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8680#issuecomment-221555728
It worked the first time, no issues. npm and node are already installed.

![c9htn](https://cloud.githubusercontent.com/assets/18348355/15717007/49a5692c-2825-11e6-9e02-2ea777a83466.png)
