### ISSUE TITLE
Smallest Common Multiple: my solution is correct, but your site says it's wrong

### ISSUE THREAD

**Issue by rdquintas** [FreeCodeCamp/FreeCodeCamp#7098]
Hi

I guess this issue is similar to this other one
[#6869](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6869)

I have tested my solution on my local machine (I always try to solve them offline first), and even though I pass all the tests on my local machine, when I paste my code into your website, it fails this test **smallestCommons([1, 13]) should return 360360**

I have no idea why.
:cry: 
```
    function smallestCommons(arr) {
        arr.sort();
        var count = 1;
        
        var keepGoing = true;

        while (keepGoing) {
            count += 1;
            var calcArr = [];

            for (var i = 1; i <= arr[1]; i++) {
                calcArr.push(count % i);
            }

            if (checkArray(calcArr)) {
            	keepGoing = false;
                // break;
            }
        }

        console.log("count: " + count);
        return count;
    }

    function checkArray(arr2) {
        for (var i = 1; i < arr2.length; i++) {
            if (arr2[i - 1] !== arr2[i]) {
                return false;
            }
        }
        return true;
    }

    smallestCommons([1, 13]);
```

**Comment by Greenheart** [comment]
Your solution is correct, but there is an issue with the *code-linter (checking for syntax errors)* since it finds an `potential infinite loop`.

**To fix: ** add `//noprotect` to the top of the solution in the FCC-editor.

If you have problems like these in the future, consider using the [help-chat rooms](https://gitter.im/freecodecamp/Help) and get someone that help you verify that this is an actual problem before reporting an issue.

Happy coding! :)

**Comment by ltegman** [comment]
@Greenheart is correct. Depending on the speed of the setup you're running FCC on solutions to smallest common multiple can end up taking long enough to trigger loopProtect. `//noprotect` will solve this. Thanks and happy coding!

**Comment by brianzelip** [comment]
Wow @rdquintas - that's a very elegant solution. I'm not yet sure how it works, but I look forward to figuring it out.

**Comment by brianzelip** [comment]
Ahh I get it now -- instead of ["brute forcing"](#6869) all multiples up to a certain point, your approach considers remainders (`%`). Nice.

While reading your code I recognized an easy performance boost edit to make -- change `count` and `i` from 1 to the minimum value in the passed array, like so:

```js
function smallestCommons(arr) {
  arr.sort();
  var count = arr[0];

  var keepGoing = true;

  while (keepGoing) {
      count += 1;
      var calcArr = [];

      for (var i = arr[0]; i <= arr[1]; i++) {
          calcArr.push(count % i);
      }

      if (checkArray(calcArr)) {
          keepGoing = false;
          // break;
      }
  }

  console.log("count: " + count);
  return count;
}

function checkArray(arr2) {
  for (var i = 1; i < arr2.length; i++) {
      if (arr2[i - 1] !== arr2[i]) {
          return false;
      }
  }
  return true;
}

smallestCommons([1, 13]);
```

Cheers!

**Comment by brianzelip** [comment]
Another fyi regarding your posted solution here -- the simple `arr.sort();` will provide bad answers for passed arrays such as `[10,2]` and `[13,7]` (see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description) for the reason why this is true).

So you'd need to add a compare function like:

```js
function compareNumbers(a, b) {
  return a - b;
}

arr = arr.sort(compareNumbers);
```
