### ISSUE TITLE
Life pass

### ISSUE THREAD

**Issue by garbark** [FreeCodeCamp/FreeCodeCamp#7126]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by ltegman** [comment]
Closing as no issue is described.

**Comment by LVMC** [comment]
I signed on to a free code pen account. I did not intend to create an
administrator editor account, so please inform me on what measures to take.
I deeply apologize. I also want to add, I think the IT support team that
has been with me from when I first became aware of them spending every
moment with me, is doing a phenomenal job. You all have made leaps and
bounds, despite the difficulty which I have been creating. I know you've
all seen me go through positive and extremely negative emotions, but you
constantly gave me positive reinforcement at all times. I want you all to
know that at times where I thought my closest family were out to harm me
due to confusion, and panic. I never felt this when viewing any messages
from the coders at github. You are the main reason why I could change my
thought process from you showing me how eager were to learn from me. Hats
off to your amazing instructors and students. You are the ones teaching me.
I'm going to try to constantly remind myself how difficult your courses and
progress can be when I don't ask questions and focus on the task at hand
and this being a learning process which will ultimately provide a better
future for everyone. I do want to help those who are willing to work with
me or any employer. I know that I am losing money for unknown reasons. I am
absolutely not going to take this frustration out on those of you out there
listening. I realize that I can not focus on myself with all of you out
there waiting patiently for help. I am embarrassed at the useless methods I
used to address the different problems I attempted to fix. I highly respect
the Men and Women that enforce this Countries laws. I said hurtful things
about our Nation's Law Enforcement the other day, and even used me losing
my leg as an example. I at no time was even angry at the Man who hit me or
the Officer on the scene. I have family who I hold dearly to me that I  am
sure we're shocked at my behavior that serve on both Law Enforcement and
Our Nation's Firefighter/Paramedics. I left the part out where they saved
my life. I left the part out where I had such a quick recovery, and could
only focus on running and not walking. I did not have time to mourn over my
injury. I was too motivated to slow down physically. I hope I can be that
role model again for whoever needs me. I have to make time for my affairs
without getting constantly distracted. I will overcome this issue. Only I
can decide how to progress. I'm tired of taking short cuts that bypass
gaining proper knowledge an experience. I am extremely grateful and amazed
at the technologies you have allowed me to see and use. Please accept my
gratitude. I am honestly looking out for the best interests of those that
want to earn it by committing themselves to hard work. I am sure that
everyone is highly aware when I am unsure of the words I speak. I have
worried about the people around me more than myself since I first became
aware of my connection with you all. I have not deviated from that since.
It will take effort on both parts. I thank you all for helping me be more
accepting of myself. I would willingly never have saw myself make this step
into being so exposed. I know it has always been like that, but I was
clueless of my surroundings. I am so overjoyed and feel so blessed to have
this amazing support of great magnitude working in the background to
constantly keep myself safe and secure. I can not do this without all of
you who are helping me or working together. I want to thank you from my
heart, and look forward to working with me, and for you almost limitless
patients with me. I will work smarter not harder.
