### ISSUE TITLE
No semicolon needed to pass - jQuery

### ISSUE THREAD

**Issue by TJ0** [FreeCodeCamp/FreeCodeCamp#7137]
Waypoints: 
- Target HTML Elements with Selectors Using jQuery
- Target Elements by Class Using jQuery
- Target Elements by ID Using jQuery
- Target the same element with multiple jQuery Selectors
- Remove Classes from an element with jQuery

Windows 7
Firefox 44

I can pass these Waypoints without semicolon in the end of each line of code inside <_document ready function_>.
After I pass first Waypoint, semicolons appeard, but I can delete them and still run tests.

See screenshot

![semicolon](https://cloud.githubusercontent.com/assets/16755816/13178338/9d6d70a2-d71e-11e5-862e-9542b26011bb.jpg)

**Comment by Greenheart** [comment]
@TJ0 JavaScript (and libraries like jQuery) can run without semicolons thanks to a language feature called **Automatic Semicolon Insertion**. However I think FCC have chosen to teach all campers to use a consistent code-style. The reason is probably to simplify the learning and let new developers focus on the fundamentals, not details like if they should use semicolons or not.

If you want more information, there's some great videos on YouTube if you search for "semicolons JavaScript". I personally don't use semicolons in my own projects since the last month, but I'm contexts like FCC I try to follow their style guides.

Hope this helped! :)

**Comment by Greenheart** [comment]
Excellent description of the issue btw! Just think how nice the world would be if this was the standard level of issues... ;)

**Comment by hallaathrad** [comment]
Agreed. This submission level should be a standard, not an exception. :+1: @TJ0!
This "issue" I believe by common agreement rather a "feature", granted @Greenheart's explanation on FCC's recommended learning style.

**Comment by TJ0** [comment]
Thank you @hallaathrad @Greenheart

About submission level - maybe it's because I'am ISTQB Certified Tester :sunglasses:  

I hope that next submission will be about issue, not "issue" :smile:

**Comment by hallaathrad** [comment]
Well, that makes sense ;) Thanks and please do help us catch any system bugs you get!

**Comment by theframeON** [comment]
The same with **Remove an Element Using jQuery** challenge. No need to use semicolon to pass it...
