### ISSUE TITLE
Ability to collapse incomplete challenges in Map across browser sessions

### ISSUE THREAD

**Issue by dshgna** [FreeCodeCamp/FreeCodeCamp#7139]
Currently, all the main sections on the map are collapsible. However, only the completed sections remain collapsed across browser refreshing.

It would be nice if the user was able to collapse incomplete non-certificate challenges across sessions- 
especially in the early parts of the course where users with some knowledge would want to  skip the basic challenges and concentrate solely on the algorithmic scripting and projects.

**Comment by Greenheart** [comment]
Great idea! :) 

Someone please add labels **feature request & help wanted**

**Comment by Soulzityr** [comment]
I'm sorry, I know this is incredibly off-topic but I cannot find the
setting to turn off these emails. I'm getting flooded.

Jason Shih
(954) 303-6292
jason.shih.619@gmail.com

**Comment by bugron** [comment]
@Soulzityr https://help.github.com/articles/unwatching-repositories/, search.

**Comment by Soulzityr** [comment]
Ah there is no way to keep Watch but not get emails? Alright thanks!

Jason Shih
(954) 303-6292
jason.shih.619@gmail.com

**Comment by pradeepce** [comment]
+1

**Comment by hallaathrad** [comment]
This has been a previously discussed feature, but  since it didn't have a general consensus in the core team, was deemed to be implemented pending on future user request.
Perhaps what @dshgna sugests would imply some sort of "hide this section permanently" or "disable this" sort of idea? @SaintPeter, @FreeCodeCamp/issue-moderators what do you think?
