### ISSUE TITLE
Map Is Not Well Designed

### ISSUE THREAD

**Issue by TylerL-uxai** [FreeCodeCamp/FreeCodeCamp#7149]
As a designer, I can say your 'Map' side bar is poorly made.

Put simply, your user doesn't need to see both the project he's working on as well as a list of the other projects. There's really no need to have the side bar function...

I'm not trying to sound arrogant but this should be apparent to anyone with a semblance of artistic skill. It's bothering me that I can't just go to the map without having to first open a side bar that's ugly and poorly built.

Could you perhaps use the link that was in place before adding the side bar feature? It would greatly improve your people's enjoyment. Pleasure to be of service!

**Comment by OriBon** [comment]
It can very easily be argued that while many users are working on various challenges, they like to refer to previous challenges to see how they completed that one and how such an approach might work on their current challenge. I do this very frequently. The simplicity of the popout map feature lets them quickly scroll through and open previous challenges.
On the other hand, using the actual map page, as opposed to the popout map, is still preferred by many people who spend time in Gitter helping others with their work. So I see how only being directed to the popout can be annoying.

If you wish to view the full-page map, you can still go to http://www.freecodecamp.com/map. I have this favorited on my bookmarks bar for fast access.

**Comment by ltegman** [comment]
@TylerL-uxai When you contribute to open source you'll get farther and be a bigger help by not approaching things as if your opinion is the truth. Open source is about working with others and having constructive conversations, rather than being insulting and demanding. What doesn't work for you will work great for others.

You can still access a map page via the url @OriBon pointed out, so if you prefer that you're welcome to keep doing that. We've decided as an organization that having a popout map is the better user experience for a greater number of people. I'm sorry if you disagree.

Thanks and happy coding!

**Comment by jgoatcher81** [comment]
I think the popout map is very handy for the reason OriBon gave, not sure what the problem is? Just don't click it!
