### ISSUE TITLE
infinite loop JS runs on page load.

### ISSUE THREAD

**Issue by CraigBanach** [FreeCodeCamp/FreeCodeCamp#7164]
Issue Description
Issue occurs when you load a challenge with an infinite loop.

When loading the challenge page, the page will lock-up as soon as the challenge runs the tests. This is done on page load and so the code cannot be reset via the button before the infinite loop locks-up the page.

To reproduce -
 Create JS code in a challenge that carries out an infinite loop.

Browser Information
Google Chrome, 47.0.2526.106
Windows 10

Consider not running the JS on a challenge until the "run tests" button is pressed in order to give the user a chance to reset code.

**Comment by AkiraLaine** [comment]
Could you do this: http://freecodecamp.github.io/wiki/en/Clear-Your-Browser's-Local-Storage/ and report back?

**Comment by sludge256** [comment]
I think this issue is trying to address whether it's necessary to auto-run the code on page load, at least for the JS sections.

**Comment by AkiraLaine** [comment]
Oh. Well he still does have an infinite loop.

Cc. @QuincyLarson @BerkeleyTrue

**Comment by cragsify** [comment]
Managed to fix infinite loop by copying the end part of another challenges URL.

so:

freecodecamp.com/challenge/infiniteLoopChallenge#?solution=previousChallenge'sSolutionIsWrittenHere

By doing this, it loaded up the bugged challenge with the previous challenge's code and therefore did not run the infinite loop.

However, the underlying issue is not fixed, this is merely a workaround.

**Comment by ltegman** [comment]
This [Disable Code Auto-Run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) feature is meant for exactly this situation. Thanks and happy coding!
