### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-search-and-replace has an issue 

### ISSUE THREAD

**Issue by timkellogg** [FreeCodeCamp/freecodecamp#720]
Not sure why this isn't passing.  It passes on my computer using node to output and the docs have replace being by default case sensitive. 

function replace(str, before, after) {
	return str.replace(before, after);
}

Is there something I'm missing?

**Comment by QuincyLarson** [comment]
You're missing something. This Bonfire works fine. Keep at it :)

**Comment by juanpastas** [comment]
The logic in that function is odd. Why would I want to `expect(replace("He is Sleeping on the couch", "Sleeping", "sitting")).to.equal("He is Sitting on the couch");`.

Instead of `expect(replace("He is Sleeping on the couch", "Sleeping", "sitting")).to.equal("He is sitting on the couch");`

To  learn? But is a weird method.

**Comment by royshouvik** [comment]
Hi @juanpastas On the instructions it is mentioned
> NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word 'Book' with the word 'dog', it should be replaced as 'Dog'

And yes you are right, its meant to challenge you. Thanks!
