### ISSUE TITLE
Feature Request: un-complete a challenge

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#7213]
#### Issue Description
As a user I cannot unmark a challenge as complete.  This becomes problematic when a user might have accidentally marked something as complete or scope could have changed on an update.

**Comment by ltegman** [comment]
This is not a direction Free Code Camp wants to go. Regardless of how the problem and tests may have changed we don't want to be encouraging students to "undo" progress. We want a student to use challenges purely as a way to prepare for the later project based learning rather than staying on the challenges and this mechanic would be at-odds with that goal. If a student genuinely needs to revisit a problem in order to better understand it or refresh knowledge I'd encourage them to do that, but they don't need to mark it incomplete in order to do it. Thanks and happy coding!

**Comment by benschac** [comment]
I think you might have misinterpreted my request.  Here's a great example.  I accidentally clicked the complete button on the tic-tac-toe project.  How can I got back and uncheck because I clearly have no supporting work.

**Comment by ltegman** [comment]
It's not really a problem to have unfinished work submitted for projects because no one looks at them until you apply for the non-profit projects. If it really makes you uncomfortable you could always just make a placeholder codepen that just says "This isn't actually completed yet" or something, but I don't think you need to do that. I've submitted projects only to realize I missed a story or have a bug and I just go back and fix it, no big deal. This is definitely not a common enough use-case for us to make a whole feature around.

**Comment by DevGrrrl** [comment]
Jumping in because I accidentally marked a challenge as complete this morning when i haven't even started it. I accidentally linked a my wiki viewer to the random quote challenge and so it thinks I've completed it. I wish I could unmark the challenge because I think it looks dishonest. As a quick fix I'm going to create an empty pen with a message on it and link that to the challenge, but it's not ideal.

**Comment by texas2010** [comment]
@DevGrrrl you could reapply link in that challenge again.  try that.
