### ISSUE TITLE
Mutations - right solution doesn't pass the test

### ISSUE THREAD

**Issue by mikulchik** [FreeCodeCamp/FreeCodeCamp#7222]
Challenge [Mutations](http://www.freecodecamp.com/challenges/mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20return%20(arr%5B1%5D.split('').map(function(item)%7Breturn%20(arr%5B0%5D.indexOf(item)%3C0)%3F1%3A0%3B%7D).reverse()%5B0%5D%3E0)%3Ffalse%3Atrue%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A) has an issue.
User Agent is: <code>Chrome/48.0.2564.116</code>.

The mutation(["hello", "neo"]) should return false. As you can see on the Developer Tools panel on the screenshot, the solution works correctly and returns false too. But the solution doesn't pass the test.

![screenshot_7](https://cloud.githubusercontent.com/assets/6012122/13294442/a1f825e2-db2c-11e5-8b5f-c15d8384d38f.png)

My code:
```javascript
function mutation(arr) {
  return (arr[1].split('').map(function(item){return (arr[0].indexOf(item)<0)?1:0;}).reverse()[0]>0)?false:true;
}
```

**Comment by mikulchik** [comment]
As you can see, all the tests with Capital letters have been passed succesfully by the solution without using toLowerCase(). It seems like an issue too.

**Comment by sludge256** [comment]
From what I see, your code (without the ternary) is correct only for the last test. By adding `?false:true`, as you have done, it's "forcing" your code to be "correct" for everything else, but then the last test is no longer passed.

https://repl.it/BptC/0

![image](https://cloud.githubusercontent.com/assets/10524623/13295953/17566de6-dae0-11e5-9ece-6ae1ef8a3198.png)

![image](https://cloud.githubusercontent.com/assets/10524623/13295903/db72c39c-dadf-11e5-9d10-f433f927e2e3.png)

I suggest asking in the [help chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to resolve these issues.
The tests for this challenge merely check to see if your function returns the right boolean values. So, as far as I can tell, the issue is due to your code. I'll leave this issue open for now in case I've missed something though.
```js
"tests": [
        "assert(mutation([\"hello\", \"hey\"]) === false, 'message: <code>mutation([\"hello\", \"hey\"])</code> should return false.');",
        "assert(mutation([\"hello\", \"Hello\"]) === true, 'message: <code>mutation([\"hello\", \"Hello\"])</code> should return true.');",
        "assert(mutation([\"zyxwvutsrqponmlkjihgfedcba\", \"qrstu\"]) === true, 'message: <code>mutation([\"zyxwvutsrqponmlkjihgfedcba\", \"qrstu\"])</code> should return true.');",
        "assert(mutation([\"Mary\", \"Army\"]) === true, 'message: <code>mutation([\"Mary\", \"Army\"])</code> should return true.');",
        "assert(mutation([\"Mary\", \"Aarmy\"]) === true, 'message: <code>mutation([\"Mary\", \"Aarmy\"])</code> should return true.');",
        "assert(mutation([\"Alien\", \"line\"]) === true, 'message: <code>mutation([\"Alien\", \"line\"])</code> should return true.');",
        "assert(mutation([\"floor\", \"for\"]) === true, 'message: <code>mutation([\"floor\", \"for\"])</code> should return true.');",
        "assert(mutation([\"hello\", \"neo\"]) === false, 'message: <code>mutation([\"hello\", \"neo\"])</code> should return false.');"
      ]
```

**Comment by mikulchik** [comment]
It is really was my mistake, because of using reverse() without sort().
For the future I will use the help chat. Thank you, @sludge256.
