### ISSUE TITLE
Flagging challenges in our map

### ISSUE THREAD

**Issue by PhotoGeek1** [FreeCodeCamp/FreeCodeCamp#7233]
Is there a way to flag wayfinders in our map so that we can quickly find the ones we want to review a few more times?

**Comment by BerkeleyTrue** [comment]
wayfinders?

**Comment by PhotoGeek1** [comment]
Yeah, that. I was thinking about a map while I was typing that.

**Comment by bitgrower** [comment]
I am in favor of this as well -- at one point in a gitter room I had suggested making it possible for people to tag the challenges with topics so they could return to review examples on a particular topic ... :)

**Comment by PhotoGeek1** [comment]
YES Please!!

**Comment by khaduch** [comment]
I'd chime in on perhaps adding a way to easily go back and review topics / lessons like a "previous" and "next" button to just take you sequentially back and forth through recent lessons.  Another thought might be to provide helpful links to the lessons that are most immediately applicable to the lesson at hand.  But I think that the "previous" and "next" would go a long way to helping navigate the lessons because they are usually in a good sequence, and just looking at the most recent ones might help to jog a person's memory or give a good hint about what they should do.
