### ISSUE TITLE
Unify theme throughout challenges

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#7247]
Our Basic JavaScript curriculum is in need of a solidified theme, or narrative, to thread the challenges together - similar to what Cat Photo App has done for the HTML/CSS/Bootstrap challenges. The bones of the curriculum are there, so this is just a matter of modifying function names and content into something more cohesive.

**Comment by raisedadead** [comment]
@SaintPeter requesting your views on this. Thanks. 
Just to be clear about the function names, we have something in motion with #7085?

**Comment by thadseaver** [comment]
I'm not convinced that this needs to happen. It seems that it would put an unnecessary limit on learning. Instead of using real world scenarios, forcing a potentially corny theme on a challenge, just for the sake of keeping things _cohesive_, seems to take away from the learning instead of adding to it.

A real world challenge of calculating sports statistics for a team website followed by a challenge on iterating over patient's medical records sounds more valuable to me than calculating how many logs we'll need to bring for a weekend of camp fires followed by how many square feet of tent we'll need for 6 campers.

A section of coding challenges (Responsive Design with Bootstrap *inside* the HTML/CSS section),  certainly lends itself well to the _whole project_ scenario, but to have to put all Basic Javascript challenges under a certain umbrella doesn't make sense to me.

**Comment by techtolentino** [comment]
It'd be nice to have more feedback from the FCC users. User-driven design is highly effective for things like this.

What does the FCC team think about conducting a small survey to pull in real user feedback?

**Comment by SaintPeter** [comment]
I don't disagree that this would be nice to do, but it's also pretty challenging to do.  I found it non-trivial to just create the new content . . . making everything flow together seems like another level of difficulty.

In general I think I would rate the importance of this as being secondary to adding new content/expanding existing content.

**Comment by theflametrooper** [comment]
@SaintPeter Update on this? Can this issue be closed?
