### ISSUE TITLE
non-HTML code on output

### ISSUE THREAD

**Issue by Astamathtos** [FreeCodeCamp/FreeCodeCamp#7267]
Challenge [Create a Bootstrap Headline](http://www.freecodecamp.com/challenges/create-a-bootstrap-headline#?solution=%3Ch3%20class%3D%22text-primary%20%3EjQuery%20Playground%3C%2Fh3%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

On output section, appears some code that isn't HTML.
[screenshot](http://i.imgur.com/Scf7Wqs.jpg)

My code:
```html
<h3 class="text-primary >jQuery Playground</h3>



```

**Comment by AdityaSinghChauhan** [comment]
Dear Sir,
Please add a " at the end f the class name. This might help. 
<h3 class="text-primary"> jQuery Playground</h3>

**Comment by raisedadead** [comment]
Hi @Astamathtos @AdityaSinghChauhan is correct.

Its happening because a missing end `"` in the class `"text-primary`. 
The output window parses the code LIVE as you type, and because of this the error is thrown. as soon as you enter the ending double quote the error should not appear.

We are looking at this issue, however for now I am afraid this is a limitation, until we have a workaround. Please continue with the correct code, and ignore the error.

Thanks for noticing this. Happy coding!

**Comment by Astamathtos** [comment]
Thanks for the reply; I submitted this as a "bug".
I'm on my next challenges!
