### ISSUE TITLE
2. , 3. exercise, maybe even more.

### ISSUE THREAD

**Issue by Dayfiri** [FreeCodeCamp/FreeCodeCamp#7342]
While working on this course I wasted already over 2 hours and I am on 3. exercise at this moment, 3. !!! If I don't do the steps the same way they are written or I do even typo mistake that I need to come back and write same code again in terminal, guess what ? I can't pass the exercise. So every time if there is no perfect copy paste into my terminal the `git-it verify` won't work on c9. And I need to restart everything and start from 0 because no other way will let me pass and I am not crazy to repeat all exercises 20 times just so I can make 1 work that it is in line to be done. GUI (windows, mac) work great as I heard but for linux and terminal not much as I can say. And the worst part is that this all is "intro" into git and I loose over 2 hours for it. Yes, it is very very very very very annoying and time consuming. Please lay eyes on it and check why is it like this ( someone that uses linux I hope ). 
Thank you for your time.

**Comment by M1kep** [comment]
I'm pretty sure that not to much can be done without some more specifics, I personally don't quite understand what the issue is.

**Comment by ltegman** [comment]
`git-it` is definitely a little bit rough around the edges, but we don't have any alternatives at this time and the curriculum is not maintained by us, so there's not much that can be done on our end. Sorry about that. If you find it frustrating and not helpful you're welcome to move on and learn git elsewhere since it is not a required lesson. Thanks and happy coding!
