### ISSUE TITLE
Demo Site does not work

### ISSUE THREAD

**Issue by mqasim13** [FreeCodeCamp/FreeCodeCamp#7351]
Challenge [Show the Local Weather](http://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by sludge256** [comment]
It's functioning for me. What errors are you getting? The weather app gets geolocation information from your browser so if you have that blocked it may not worked. The location can be somewhat inaccurate also.

**Comment by JoshFisk** [comment]
@sludge256 Does the demo have a fall back if it can't get the information? For situations like you describe, maybe it could show some sort of message, instead of the weather.

**Comment by raisedadead** [comment]
Closing as stale. Please re-open if necessary.

**Comment by jackuhlantern** [comment]
I've also encountered an issue with the demo not working. I don't want to look at the code before doing the challenge, though, so I'm not sure what's wrong. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/18414227/20653163/059f5756-b54c-11e6-8573-f9e46a4ffd14.png)
Every time I've tried to open the page that's what it looks like. I know it's not my browser settings since I'm able to access my location and APIs (see below)
![image](https://cloud.githubusercontent.com/assets/18414227/20653182/7f9764e0-b54c-11e6-967b-9f486a03fa07.png)

and using http instead of https results in a 404

**Comment by raisedadead** [comment]
Can anyone confirm, it seems to work for me? /cc @FreeCodeCamp/moderators

**Comment by Manish-Giri** [comment]
It seems to be working for me - 

![screenshot 2016-11-28 02 02 18](https://cloud.githubusercontent.com/assets/11348778/20659015/e30fff34-b50e-11e6-8953-74d79512953f.png)

**Comment by abhisekp** [comment]
It works for me too. It shows my location along with the temperature.

@jackuhlantern Please check your dev console to see for any errors
<kbd>CTRL + SHIFT + J</kbd>

**Comment by Em-Ant** [comment]
If you use https to access codepen your browser is blocking the call to the weather api (which is on http) because of the "mixed active content" policy.

**Comment by jackuhlantern** [comment]
From dev console:
![image](https://cloud.githubusercontent.com/assets/18414227/20691701/fdd5cfd0-b615-11e6-8b62-75bb5ccce059.png)

It does seem to be an issue with https, but I can't load it with http in full view for some reason (404 error). Oddly enough, the app works just fine with http in "Editor View", but 404's in Details or Full view.

**Comment by abhisekp** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
