### ISSUE TITLE
Not able to complete "Nest an Anchor Element within a Paragraph"

### ISSUE THREAD

**Issue by rocnick6** [FreeCodeCamp/FreeCodeCamp#7355]
<h2 class="red-text">CatPhotoApp</h2>
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a> </p>
<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by rocnick6** [comment]
<p>View more <a href="http://www.freecatphotoapp.com"> cat photos</a> </p>

**Comment by rocnick6** [comment]
<p>View more <a href="http://www.freecatphotoapp.com"> cat photos</a> </p>

**Comment by rocnick6** [comment]
<p>View more <a href=http://www.freecatphoto.com> cat photos</a> </p>

**Comment by rocnick6** [comment]
`<p>View more <a href="http://www.freecatphotoapp.com"> cat photos</a> </p>`

**Comment by ltegman** [comment]
Instead of wrapping the existing anchor tag you made a new one, so our test finds the old (still unwrapped) anchor and thinks you didn't complete the challenge. Please only have one copy of the link that is wrapped. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is a site bug and not a bug with your code before filing an issue. Thanks and happy coding!
