### ISSUE TITLE
Fix sequence of test output

### ISSUE THREAD

**Issue by jmorelandsbiz** [FreeCodeCamp/freecodecamp#738]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Normally you would make the ul before making the li's

**Comment by QuincyLarson** [comment]
@terakilobyte Ideally these tests should be in the intended order. For example, for the challenge in question, the "create a UL element" and "Create 3 li elements" have gotten swapped.

**Comment by terakilobyte** [comment]
Yes we can easily change it so they are output in the order of the tests in the json file rather than separate them into failing/passing

**Comment by QuincyLarson** [comment]
Awesome. I think this is a priority, as many campers seem to read our (newly human-readable) failing test messages and solve the challenges that way rather than reading our text (myself included!) So presenting these in proper order will prevent error messages from floating to the top that pertaining to, say, an HTML element the camper has yet to create.

**Comment by terakilobyte** [comment]
Fixed on most recent push.
