### ISSUE TITLE
Scrollbar Overlapping

### ISSUE THREAD

**Issue by demipixel** [FreeCodeCamp/FreeCodeCamp#7385]
Probably related to #7382 

What I'm seeing: http://i.imgur.com/QW3sxGC.png

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

(i.e. Chrome & Mac)

**Comment by alistermada** [comment]
The PR you referenced has already been merged to master but I'm still getting this bug. 

It seems to happen when I try to use the challenge filter on the sidecar and then delete what I typed after I get filtered results. I'm on Chrome.

**Comment by hallaathrad** [comment]
not likely to be related to that PR as it didn't change (AFAIK) anything that could be creating this issue. please explain how to reproduce it? I think I have a possible fix (which solves a glitch I hadn't seen before). Anyone who can reproduce it reliable, let's meet on Gitter and get it fixed asap?

**Comment by Gisonrg** [comment]
Hmmm I got a similar issue as this just now. Not sure if the issue was fixed or not.

Reproduced on Chrome 49, Safari 9.03, Firefox 40. I am using OS X 10.11.

Steps to reproduce:
1. Open Map (I tried it in home page, but seems any page with Map will do)
2. Make sure the top "collapse all" button displays "Collapse all challenges"
3. Collapse one of the section in the map (for example, I collapsed "Join the Free Code Camp Community")
4. Now press the top "collapse all" button, it should display "Expand all challenges" now and all sections are collapsed.
5. Now press the top button again, it should display "Collapse all challenges" again.
6. And then the section we collapsed in step 3 overlaps with others.
![screen shot 2016-03-16 at 04 12 49](https://cloud.githubusercontent.com/assets/4332224/13792563/63bad07a-eb2d-11e5-9197-cbb96cbbf062.png)

**Comment by hallaathrad** [comment]
@Gisonrg have you tried refreshing the site? Please try that so we can make sure the CSS from the latest fix has been applied. if after trying to refresh a couple of times you still get the same issue, please text me directly on gitter so we can figure out how to get it fixed for you ;)
