### ISSUE TITLE
Steamroller won't accept code even if it returns the correct answer on the test cases

### ISSUE THREAD

**Issue by DMBarnett** [FreeCodeCamp/FreeCodeCamp#7442]
So I can't understand why the challenge won't accept a correct answer when I've run several test cases that all returned a statement that appears to be correct.  Below is my code.

```
var foo = [];
function steamroller(arr) {
  for(var i =0; i< arr.length; i++){
    if(Array.isArray(arr[i])){
      var working = arr[i];
      steamroller(working);
    }else{
      foo.push(arr[i]);
    }
  }
  return foo;
}
```

I'm using chrome, and tried it on firefox, and neither accept said solution.  Does FCC have an issue with recursion?

**Comment by ltegman** [comment]
Using global variables is bad. Think about what that function does if you run it more than once. Thanks and happy coding!

**Comment by DMBarnett** [comment]
Well yes, it has a global variable in a testing environment, but it's not responding in any way even though the output box is showing a correct answer to various inputs.  Is there a way y'all can add a popup or message of some kind that throws an error when you've got a global variable so that the user can understand why their answer is being rejected?

**Comment by ltegman** [comment]
The output box shows the correct answer if you only call the function once in the editor. It won't if you call it more than once. That's not something we could do because there are plenty of very simple introductory exercises where global variables are not a problem and we don't want to throw an error, it's only when you're doing variable initialization outside the functions using them that it becomes a problem. Part of programming (particularly in JavaScript) is figuring out what the problem is even when it isn't explicitly pointed out.

**Comment by DMBarnett** [comment]
I understand, however the output box will return an answer that matches the expected output, the 'should return' answer, using this code [as seen here.](http://imgur.com/FbXAehw)

**Comment by ltegman** [comment]
That's because when the function first runs (which is the run at the bottom of your code) it returns the correct answer. There's not really much we can do about that. The code does work correctly once.

**Comment by DMBarnett** [comment]
Ah so the code is copied and tested elsewhere, understood.
