### ISSUE TITLE
Misleading information in Global vs Local Scope exercise

### ISSUE THREAD

**Issue by luke-m** [FreeCodeCamp/FreeCodeCamp#7448]
#### Issue Description
* This is not a code problem, but I wasn't sure where else to bring this up.
* In the exercise description it says "Add a local variable to `myFunction` to override the value of `outerWear` with `"sweater"`." . However, no value gets overridden in this exercise. Local `outerWear` is just an entirely different variable than global `outerWear` and when you call `myFunction`, nothing gets overriden, the value of the other `outerWear` is simply put out. Global `outerWear` would still hold the value of "T-Shirt"

**Comment by ltegman** [comment]
@luke-m Override is an accurate description of what is happening. Override means to extend or overlap, which the local variable does to the global variable. The local name overlaps with the global one, so it overrides it. If we had used the word overwrite that would be incorrect, since it would imply the outer value is getting changed. Thanks and happy coding!
