### ISSUE TITLE
"Seek and Destroy":Test cases remain in Red even though the output looks correct for each test case

### ISSUE THREAD

**Issue by alessandrasp** [FreeCodeCamp/FreeCodeCamp#7457]
Challenge [Seek and Destroy](http://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20var%20myArr%3B%0A%20%20myArr%20%3D%20arr.filter(checkValue%2Carguments%5B1%5D)%3B%0A%20%20myArr%20%3D%20myArr.filter(checkValue%2Carguments%5B2%5D)%3B%0A%20%20return%20myArr%3B%0A%7D%0Afunction%20checkValue(value)%7B%0A%20%20return%20value%20!%3D%3D%20this%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%205%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  var myArr;
  myArr = arr.filter(checkValue,arguments[1]);
  myArr = myArr.filter(checkValue,arguments[2]);
  return myArr;
}
function checkValue(value){
  return value !== this;
}

destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3);

```

**Comment by ltegman** [comment]
Basically you're doing something in your code that shouldn't work but some execution contexts will let you get away with (in this case the editor is letting you get away with it but the test runner isn't). You're passing a primitive value (`arguments[1]`, which is `2`) as the `this` context for the `checkValue` callback. The issue is that the `this` context should always be a context object, not a primitive. In the test framework it turns that primitive into and object with a form like `Number {[[PrimitiveValue]]: 2}` which causes the test to fail. You'll have to find a different way to pass that value in that doesn't involved pushing a primitive value as the `this` context. Good luck and happy coding!
