### ISSUE TITLE
Code is not being restored

### ISSUE THREAD

**Issue by preetamkajalrout** [FreeCodeCamp/FreeCodeCamp#7463]
Currently, All the code I have written till date are missing and I can't see it in editor.

**Comment by ltegman** [comment]
Do you mean your completed challenges are missing from your profile or just you solution is missing when you visit the challenge from the map?

**Comment by raisedadead** [comment]
@preetamkajalrout do you have any updates on this? 

Closing. Feel free to comment to re-open.

**Comment by preetamkajalrout** [comment]
Apologies for late reply.
The issue still persists. The solutions are missing even though the challenges are marked completed(green tick + greyed out).

**Comment by raisedadead** [comment]
@preetamkajalrout Re-opening as per request.

Can you please provide details? When I visit your profile at https://www.freecodecamp.com/preetamkajalrout and check the listed challenges, and click on the View solution, I do the solution in there.

Is it that you cleared your browser cache? If so then the solutions are safe on your profile page.
When you re-visit the page, these would re-appear on the editor.

Can you explain a bit more to remove the ambiguity?

Thanks.

**Comment by preetamkajalrout** [comment]
I did clear my browser cache. However, After that I can see my challenges are marked completed. However, solutions are not there in the editor. Please find the attached screenshot for reference
![image](https://cloud.githubusercontent.com/assets/3712035/14740713/b11ffcd4-08ae-11e6-8f06-e23e78c7a61e.png)

**Comment by raisedadead** [comment]
@preetamkajalrout : Thanks for the screenshot.

Yes this is normal behaviour, and is expected, We store the solutions in the browser's cache as well on the your profile in the database.

Since you have deleted the cache, you can get back the solutions that you submitted only by visiting them on your profile page. We never delete the solution, but just update them should you make any changes and re-submit. All this is reflected on your profile page.

Your completion status and streak is not affected in any way if you re-submit.

I am afraid that's the only approach.

Closing once again with this clarification.

Happy Coding!

**Comment by preetamkajalrout** [comment]
Thanks for the clarification! :8ball:
