### ISSUE TITLE
npm install fails when installing the app

### ISSUE THREAD

**Issue by paolopiccinini** [FreeCodeCamp/FreeCodeCamp#7496]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

#### Issue Description
* When i try to give the command npm install

#### Browser Information
* Windows 7

#### Info
* Node version 4.4.0
* npm version 2.14.20

[node-debug.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/168825/node-debug.txt)

**Comment by raisedadead** [comment]
By the initial looks of it it seems a network error on your machine, broke the installation. 
Please retry.

Also I recommend you update `npm` to `3^` since you are on windows while its alright on your current version, but I have seen `npm 3` to work best. 

To update you can do : `npm install -g npm`

If you are stuck please get in touch with us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors)

**Comment by raisedadead** [comment]
While retrying the `npm install` on the repo's dependencies do this to remove cached modules:
`npm install cache clear`
`rm -rf node_modules`

Followed by
`npm install` as usual

**Comment by paolopiccinini** [comment]
thank you guys. Now i'm able to install the app.
