### ISSUE TITLE
Problem is written poorly and is easily misleading, methinks.

### ISSUE THREAD

**Issue by dunethomas** [FreeCodeCamp/FreeCodeCamp#7514]
The bug isn't in the code, it's in the writing. The challenge states: "If the num is less than or equal to 3, then the length of the three dots is not added to the string length." Adding to the length of the string sounds like adding characters onto the length of a string. For greater clarity, might I suggest: "If the num is less than or equal to 3, then the additional length of the three dots is not added to the total length tested to determine the truncation point." Or something like that. Anyway, it seemed rather unclear exactly what this challenge was asking for. 

Challenge [Truncate a string](http://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20if%20(str.length%20%3C%3D%20num)%20return%20str%3B%0A%20%20if%20(num%20%3E%203)%20%7B%20%0A%20%20%20%20str%20%3D%20str.substr(0%2Cnum-3)%20%2B%20%22...%22%3B%0A%20%20%7D%0A%20%20console.log(str)%3B%0A%20%20return%20str%3B%0A%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  // Clear out that junk in your trunk
  if (str.length <= num) return str;
  if (num > 3) { 
    str = str.substr(0,num-3) + "...";
  }
  console.log(str);
  return str;
}

truncate("A-tisket a-tasket A green and yellow basket", 11);

```

**Comment by sultanshaik** [comment]
Also, the instructions mention that the three dots not be added if num is less than three.
But here is the expected output that ### **_contradicts the instruction_**:
truncate("A-", 1) should return "A...".
truncate("Absolutely Longer", 2) should return "Ab...".

**Comment by Spartano** [comment]
the problem lies in what the code completion ask you to do. they just have to remove the "..." from the last 2 statements and add them to the previous 2, so that you can complete the chalenge.

**Comment by markymarc009** [comment]
I agree with dunethomas

I believe the answer to the challenge is actually the opposite of what is required for it to be cleared. 

**Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a ... ending.** 
The above makes it seem like you are required to add three dots to the length that you have, but the then the expected output shows that you wanted the three dots to take the place (totally replace) the last three characters of your sliced string.


 **Note

 that inserting the three dots to the end will add to the string length.**

 then you see this^^^^

**`However, if the given maximum string length num is less than or equal to 3, then the addition of the three dots does not add to the string length in determining the truncated string.`**

And this kind of confirms what the initial part of the question is asking for. The above is pretty much saying " if the length of num is greater than three, then you are going to add on to the length of the string with dots, but in this case since there num is 3 or less then the addition of the three dots does not add to the string length, but instead replaces the last few characters (whether 3 or less) with dots. 

Its like the two parts of the question should be changed since your answers call for the opposite of the instructions.
