### ISSUE TITLE
"Where do I belong" fails the final test even though my result is correct with the for-in loop

### ISSUE THREAD

**Issue by Scoodood** [FreeCodeCamp/FreeCodeCamp#7535]
#### Issue Description
* When Issue Happens: Every time I run my code with the for-in loop
* Steps To Reproduce: See my code here at [Where do I belong](http://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20temp%20%3D%20arr.sort(function(a%2Cb)%20%7B%20%0A%20%20%20%20return%20a-b%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20%2F%2F%20it%20will%20fail%20the%20test%20if%20I%20replace%20the%20for-loop%20with%0A%20%20%2F%2F%20the%20for-in%20loop%20even%20though%20the%20result%20is%20correct%0A%20%20%2F%2F%0A%20%20%2F%2F%20for%20(var%20i%20in%20temp)%20%7B%0A%20%20for%20(var%20i%3D0%3B%20i%3Ctemp.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(temp%5Bi%5D%20%3E%3D%20num)%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%7D%0A%20%20return%20arr.length%3B%0A%7D%0A%0Awhere(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2035)%3B%0A%0A). Comment out the regular for-loop and uncomment the for-in loop, then run the test.

#### Browser Information
* Browser Name, Version: Google Chrome Version 48.0.2564.116 (64-bit)
* Operating System: OSX 10.10.5 (Yosemite)

**Comment by raisedadead** [comment]
@Scoodood Usually we do not provide code help in Github issues.
But since this can be considered a bug, by others.

I would like to add some thought for anyone looking into this.
> The for-in statement by itself is not a "bad practice", however it can be mis-used, for example, to iterate over arrays or array-like objects.

> The purpose of the for-in statement is to enumerate over object properties. This statement will go up in the prototype chain, also enumerating over inherited properties, a thing that sometimes is not desired.

refering a [stackoverflow discussion](http://stackoverflow.com/a/500531) and a [following answer](http://stackoverflow.com/a/4261096)

You would want to look at the [MDN Documenation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) as well which confirms this notion.

IMHO I do not mean to say that you couldn't use `for...in` but its kind of a practice that you shouldn't, in context of arrays.


Keeping this open for opinion from others.

**Comment by abhisekp** [comment]
@raisedadead I do agree that `for..in` is not the correct way to iterate an array since the browser implementations of `for..in` loop do not guarantee the order of traversal but i do not think it's just a browser issue.

Consider the following cases
- **Using `for..in` loop**: https://repl.it/Bvmm (_works!_) but _doesn't work in **FCC**_
- **Using `for` loop**: https://repl.it/Bvmo (_works!_)
- **console.log enabled in L14**: https://repl.it/Bvml (_doesn't work anywhere & check the output!_) :warning: *weird!*

> *NOTE that the challenges are run and checked in client's browser*

**Comment by ltegman** [comment]
`for ... in` is returning a string and not a number. This is not a site problem. Thanks and happy coding!
