### ISSUE TITLE
Computer Basics text overflows on mobile

### ISSUE THREAD

**Issue by RayBB** [FreeCodeCamp/FreeCodeCamp#7565]
#### Issue Description
When I go to the website the text is over the edge and I can't zoom out to view it.

#### Browser Information
* Google Chrome 49
* Android M (Nexus 5x)

Note: The issue also happens if you view the mobile view on chrome for windows.

#### Screenshot
![screenshot_20160315-135413](https://cloud.githubusercontent.com/assets/921217/13790006/cf8263fc-eabc-11e5-9722-14bf5211ead3.png)

**Comment by drk7891** [comment]
Confirmed on iPhone 6 Chrome and Safari

**Comment by bteng22** [comment]
I could take a stab at this as my first contribution if nobody minds :smiley:

**Comment by bteng22** [comment]
Is there anywhere I could get more context into the app/routes/Hikes/components files? Are these primarily for the Video Challenges while the jade templates are for the coding challenges? It's my first day looking into the code so any context would be greatly appreciated. Thanks!

**Comment by alistermada** [comment]
@bteng22 Yea, the views for the video challenges are generated with React in `common/app/routes/Hikes`. FCC didn't use React when it started out, which is why only the recently-added video challenges use it while the coding challenges use Jade templates.

The margins for the `row` class are declared in `public/css/main.css` starting on line 1402. Note that this class is used across the site, not just on the React-generated views.

**Comment by bteng22** [comment]
@alistermada Ahh sweet thanks for the clarification! I definitely noticed the row class being used in multiple places so I'll be sure to take a careful approach when fixing this. Thanks again man—I'll hopefully have a potential fix in by tomorrow.

**Comment by 3316** [comment]
I do not own an iphone6.....
