### ISSUE TITLE
Falsy Bouncer Bug

### ISSUE THREAD

**Issue by Kennard123661** [FreeCodeCamp/FreeCodeCamp#7587]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
null appears to not be removed from the array when .filter() method is applied.

#### Browser Information
* Google Chrome, Version 49.0.2623.87 m
* Windows 10 64 bit

#### Your Code
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  var arrayNew = [];
  arrayNew = arr.filter(function(val) {
    switch(val) {
      case null:
      case false:
      case 0:
      case "":
      case undefined:
      case NaN:
        return false;
      default:
        return true;
    }
  });
  return arrayNew;
}

bouncer([7, "ate", "", false, 9]);
bouncer([false, null, 0, NaN, undefined, ""]);

```js
If relevant, paste all of your challenge code in here
```

#### Screenshot

**Comment by AkiraLaine** [comment]
Hey @Kennard123661, if you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavascript) room. GitHub is for issues only :smile:

**Comment by Kennard123661** [comment]
Hi Akira!

The issue is that my switch code should remove the null for the array and make an empty array. However, it removes everything but the null. I've tried it with my other if codes but it still didn't work, much to my dismay.

With Regards,
Kennard Ng

On 17 Mar 2016, at 6:31 PM, Akira Laine <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7587<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7587>.

-

**Comment by alistermada** [comment]
@Kennard123661  Actually, the return value for `bouncer([false, null, 0, NaN, undefined, ""])` using your code would be `[NaN]`. You can confirm this by adding `console.log(arrayNew)` just before it is returned and checking your browser's console.

Your `switch` statement doesn't catch `NaN` because `NaN` compares unequal to all values including itself. [More info about `NaN`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/NaN).

I'm not sure why it outputs `[null]` in the challenge console on the left.

**Comment by kreddibletrout** [comment]
You sent this to the wrong member. I'm still learning what 'img' means. 
(We'll talk in a few years when my training wheels are off)

-KT

kreddibletrout.com
'... cos everyone should have a nice piece of Trout to nail to the wall!'
