### ISSUE TITLE
Check for returned user object in unsubscribe logic

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#7686]
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/randomAPIs.js#L295 and https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/randomAPIs.js#L309 does not verify whether the query actually returns a user instance, causing the server to crash hard and reboot.

Anyone up to adding a check for the user object on these?

**Comment by BKinahan** [comment]
I'd like to attempt a fix but I'm having trouble replicating the crash locally using the subscribe/unsubscribe buttons. Are there any additional steps or conditions required?

**Comment by BerkeleyTrue** [comment]
@BKinahan You'd need to navigate directly to the associated URLs using an email that does not exist in the database

**Comment by BKinahan** [comment]
@BerkeleyTrue Have been able to replicate this via the two lines mentioned in the initial issue writeup, and also with https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/randomAPIs.js#L319

I have a working solution that redirects to the /map page and issues the following flash info text:

> Email address not found. Please update your Email preferences from your profile.

I believe this would be the expected behavior and follows the style of the other text alerts, but would would be open to suggestions for the wording and/or functionality.

**Comment by SaintPeter** [comment]
Verbiage looks fine to me.

Should we/can we include a URL that links directly to the `settings` page?

**Comment by BerkeleyTrue** [comment]
LGTM

**Comment by BKinahan** [comment]
@SaintPeter I did think of that first, but if the issue is arising from a user visiting the /unsubscribe/[not-found-emailadress] URL, they may not be signed in, in which case they are redirected to /map anyway and there is an additional text popup about needing to sign in to access /settings.
