### ISSUE TITLE
Error on 'Increment a Number on JavaScript'

### ISSUE THREAD

**Issue by Bandito11** [FreeCodeCamp/FreeCodeCamp#7705]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%20%2B%201%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++ + 1;


```
======================================
Hi;
As you can see writing 'myVar++ + 1' AND 'myVar++' gives the same result. Just tried it.
Regards;

**Comment by zklinger2000** [comment]
The bug here is not really a bug with myVar++, but how the test is written.
This post explains the issue:
[What is the difference between prefix and postfix operators?](http://stackoverflow.com/a/34273764/4294517)

When you type ```myVar = myVar++```, 87 is the proper number being returned, that number is then 'postfixed' and incremented by 1.
The problem is, when you prefix the variable,  ++myVar, 88 is returned, which is proper, but the test won't accept it because the '++' is not _after_ myVar.

The solution to the problem is to not use ```myVar = myVar++```  You're supposed to use simply ```myVar++;``` without any assignment operator.

**Comment by raisedadead** [comment]
#### Note to potential contributors:

Add additional test to check:
> The solution to the problem is to not use myVar = myVar++ You're supposed to use simply myVar++; without any assignment operator.

**Comment by mh-azizian** [comment]
You must rewrite code:
`var result = ++myVar ;`
