### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-basic-computer-science link

### ISSUE THREAD

**Issue by atabas** [FreeCodeCamp/freecodecamp#771]
Coursework from this link (https://class.stanford.edu/courses/Engineering/CS101/Summer2014/courseware/z54/z1/ ) cannot be viewed because it requires login

**Comment by LumenTeun** [comment]
@atabas A lot of the courseware available through FCC is not created by FCC, so some of it will require you to create an account on some separate page. As far as I know, you do not need to complete the waypoints to be able to eventually help non-profits, so if you do not want to create accounts everywhere, you can try to keep going and find information in other places.

**Comment by QuincyLarson** [comment]
@atabas yes - you will need to create an account with Stanford in order to work through this Waypoint. As @LumenTeun said, our Waypoints are optional, but you probably won't be able to complete our Bonfires, Ziplines and Basejumps without having a decent understanding of computer science, which this course will give you.
