### ISSUE TITLE
Function name in code is different than function name in tests

### ISSUE THREAD

**Issue by vxdiazdel** [FreeCodeCamp/FreeCodeCamp#7735]
For this challenge, I had to change the name of the function from truncate() to truncateString() in order to get this to work. I spent several hours looking for help on this issue, only to realize the test was not even registering the default function that was created. Please update the sample code to the correct function name so it is consistent with the actually test.

Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncateString(str%2C%20num)%20%7B%0A%20%20var%20result%20%3D%20''%3B%0A%20%20if%20(str.length%20%3E%20num)%20%7B%0A%20%20%20%20if%20(num%20%3E%203)%20%7B%0A%20%20%20%20%20%20result%20%3D%20str.slice(0%2C%20num%20-%203)%20%2B%20'...'%3B%0A%20%20%20%20%20%20console.log('Result%3A'%2C%20result)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%20%0A%20%20%20%20%20%20result%20%3D%20str.slice(0%2C%20num)%20%2B%20'...'%3B%0A%20%20%20%20%20%20console.log('Result%3A'%2C%20result)%3B%20%20%20%20%0A%20%20%20%20%7D%20%20%20%20%20%20%20%20%0A%20%20%20%20return%20result%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20console.log('String%3A'%2C%20str)%3B%0A%20%20%20%20return%20str%3B%0A%20%20%7D%0A%7D%0A%0AtruncateString(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncateString(str, num) {
  var result = '';
  if (str.length > num) {
    if (num > 3) {
      result = str.slice(0, num - 3) + '...';
      console.log('Result:', result);
    }
    else { 
      result = str.slice(0, num) + '...';
      console.log('Result:', result);    
    }        
    return result;
  }
  else {
    console.log('String:', str);
    return str;
  }
}

truncateString("A-tisket a-tasket A green and yellow basket", 11);
```

**Comment by raisedadead** [comment]
@vxdiazdel This is probably a know side effect of the recent migrations that we are having with #7085 
But I could not seem to reproduce the issue that you state.

Your code passes for me (maybe because you have fixed it to work)

Can you please confirm which is true in your case:
1.  You visited the challenge for the first time, the code editor had some code already in place with `truncate` and not `truncateString`

2. You have visited this page from either yours or someone else solved challenge page in which case it has the code with `truncate` and not `truncateString`

If its case 1 then we might have a bug here, if its case 2 then, as I said that this is known side effect, and you just need to resubmit the solution, by re-naming the functions.

Having said that you original solution is still safe and counted in your progress (if you were logged in), but unfortunately will not pass the tests because of the renaming.

Please let us know.
Thanks!
