### ISSUE TITLE
Challenges with broken links

### ISSUE THREAD

**Issue by filipemeneses** [FreeCodeCamp/FreeCodeCamp#7743]
#### Issue Description
These challenges are with a broken link, they all send to the same [link](https://www.freecodecamp.com/challenges/compound-assignment-with-)

- [Compound Assignment With +=](https://www.freecodecamp.com/challenges/compound-assignment-with-)
- [Compound Assignment With -=](https://www.freecodecamp.com/challenges/compound-assignment-with-)
- [Compound Assignment With *=](https://www.freecodecamp.com/challenges/compound-assignment-with-)

I'm unable to complete any of them because I don't have access to it.
* Steps To Reproduce
Well, just access `Basic Javascript` in the `Map` and find those challenges. Ex.: enter `Compound Assignment With += ` and you'll see `Compound Assignment With /= `

#### Browser Information
* Chrome 49.0.2623.87 m
* Windows 10

**Comment by raisedadead** [comment]
@filipemeneses Thanks for reporting this.

This is a regression with #7667. 
Due to an oversight that symbols in the title are messing with the fetch logic for the map.

Referring back to https://en.wikipedia.org/wiki/Augmented_assignment for this, I think updating the challenge names to

![image](https://cloud.githubusercontent.com/assets/1884376/14064483/66b0da92-f422-11e5-9c08-c478bce6496f.png)

Solves the issue.

**Comment by Rich-Hopkins** [comment]
I see that this issue is closed, but I still cannot get to these three challenges.

**Comment by raisedadead** [comment]
Hi @Rich-Hopkins the fix is on its way, it usually takes a couple of days to release to the main website, we request you to bear with us meanwhile!

**Comment by Rich-Hopkins** [comment]
Oh, ok. Thanks!

**Comment by extwiii** [comment]
I have same problem too
