### ISSUE TITLE
JSON Record Collection exercise, I seem to have the right results, but it's still marking incorrect

### ISSUE THREAD

**Issue by W8sconsin** [FreeCodeCamp/FreeCodeCamp#7759]
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  collection[id][prop] = value;
  if (value === "") {
    delete collection[id][prop];
  }
  return collection;

-----

<img width="946" alt="screen shot 2016-03-27 at 8 13 32 pm" src="https://cloud.githubusercontent.com/assets/9143995/14068992/6d763c10-f458-11e5-9c64-f374dd68feee.png">

**Comment by BKinahan** [comment]
Your code appears to return the correct result for the third test because it sets the value of the `"tracks"` property of the Robert Palmer album to `"Addicted to Love"`, but what it should actually do is set the value of the last element of the *array* that is the value of that property equal to that string, and do this by pushing the string to the array as mentioned in the instructions (using `collection[id][prop].push(value);`)

There is an issue here, though, that the test may be ambiguous. It should either specify "After `update(1245, "tracks", "Addicted to Love")`, `tracks` should have `"Addicted to Love"` as the last element of the array.`, or the original array for that entry should contain another track string so that it is clearer that the code should add a string to the array rather than replacing what is already there.

I'd be happy to make the change after some additional input about which seems better.

**Comment by W8sconsin** [comment]
Thanks for getting back to me.  I was able to work through it eventually.  It's okay as is.

**Comment by pesokot** [comment]
It seems that I have a bug with parsing second and third tests. After testing in IDE, track so not added, but system still throughs error
![image](https://cloud.githubusercontent.com/assets/8618068/14250877/aa09f1d4-fa80-11e5-9f56-3f66ff355181.png)

**Comment by GitH7** [comment]
i think i'm having same problem,

**Comment by ashishhbwsl** [comment]
![screenshot from 2016-06-07 16 49 41](https://cloud.githubusercontent.com/assets/19770447/15855902/df962198-2ccf-11e6-9942-484860327af1.png)

Im also stuck on this question .. hi

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
