### ISSUE TITLE
update new

### ISSUE THREAD

**Issue by zeuosageenti** [FreeCodeCamp/FreeCodeCamp#7781]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3E%D8%B3%D9%84%D8%A7%D9%85%3C%2Fh1%3E%0A%3Ch1%3E%D8%AE%D9%88%D8%A8%DB%8C%3C%2Fh1%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>سلام</h1>
<h1>خوبی</h1>



```

**Comment by erictleung** [comment]
@zeuosageenti Please provide more information about your issue, if there is one.

**Comment by raisedadead** [comment]
@zeuosageenti @erictleung 

This wont pass of course because the tests are against "Hello World" 
> "سلام (Hello)" and "خوبی (Good)" (as per google translate).

@zeuosageenti  
If you are meaning to suggest that we add translations for these challenges?
Then please visit the [Translators Chat](https://gitter.im/FreeCodeCamp/Translators) room and connect with others to know about the status of the translations for the language of your interest.
