### ISSUE TITLE
Correct code generates an error without a blank line following it.

### ISSUE THREAD

**Issue by imnlfn** [FreeCodeCamp/FreeCodeCamp#7799]
Challenge [Accessing Nested Arrays in JSON](https://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json#?solution=%2F%2F%20Setup%0Avar%20myPlants%20%3D%20%5B%0A%20%20%7B%20%0A%20%20%20%20type%3A%20%22flowers%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22rose%22%2C%0A%20%20%20%20%20%20%22tulip%22%2C%0A%20%20%20%20%20%20%22dandelion%22%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20type%3A%20%22trees%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22fir%22%2C%0A%20%20%20%20%20%20%22pine%22%2C%0A%20%20%20%20%20%20%22birch%22%0A%20%20%20%20%5D%0A%20%20%7D%20%20%0A%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20secondTree%20%3D%20myPlants%5B1%5D.list%5B1%5D%3B%20%2F%2F%20Change%20this%20line) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I noticed in a couple cases working on the JSON examples that if there's not a blank line after my code, I get "SyntaxError: Illegal return statement".

After I add the carriage return after the last line, it submits fine.

My code:
```javascript
// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants[1].list[1]; // Change this line
```

**Comment by bteng22** [comment]
As you mentioned, also seeing this in [Accessing Nested Objects in JSON](https://www.freecodecamp.com/challenges/accessing-nested-objects-in-json). Seems like the common.executeChallenge$ method isn't agreeing with format without the newline. I'll keep digging and you let you know what I find. Good catch @imnlfn :+1:

**Comment by bteng22** [comment]
So it looks like the tail functions from the basic-javascript.json from these nested JSON problems are being appended to the code in the editor, but the actual function definition is being cut off due to the comment on the last line, "// Change this line". 

`var secondTree = myPlants[1].list[2]; // Change this line(function(x) {`

`if(typeof x != 'undefined') { 
    return "secondTree = " + x;
  }
  return "secondTree is undefined";
})(secondTree);`

This code is being evaluated in the iFrameScripts.js in common.getJsOutput where eval(code) is catching the illegal return statement error. At the top of my head, the simplest solution would be to add a newline after the comment in question, but any other suggestions are welcomed. I'll try to put in a PR for this asap! Thanks

Screenshots attached below for clarity !
<img width="1440" alt="fcc bug" src="https://cloud.githubusercontent.com/assets/6289711/14128588/041a3bb0-f5d7-11e5-88dc-c6cf99c5bfac.png">

------------------------------------------------

<img width="773" alt="fcc bug-2" src="https://cloud.githubusercontent.com/assets/6289711/14128593/0cfc64f6-f5d7-11e5-8fd7-c52bf8ea074b.png">

**Comment by raisedadead** [comment]
@bteng22 Thanks a lot for analyzing this in depth. :+1:

**Comment by bteng22** [comment]
@raisedadead no problem! it was my pleasure :smile:

**Comment by benmcmahon100** [comment]
I can sort this out!

**Comment by raisedadead** [comment]
@benmcmahon100 We have a PR Open, waiting on @bteng22 to update this!

**Comment by bteng22** [comment]
@raisedadead sorry about that was out of town. updating this as we speak! should be ready for a final check soon !
