### ISSUE TITLE
Challenge 223

### ISSUE THREAD

**Issue by tarnaykin** [FreeCodeCamp/FreeCodeCamp#7816]
My program seems to work as intended, but I'm unable to pass the challenge. I can't see where there can be a problem with my code
http://pastebin.com/2FQbcBZJ

**Comment by BKinahan** [comment]
Your code does not pass the third test:
After `update(1245, "tracks", "Addicted to Love")`, `tracks` should have `"Addicted to Love"` as the last element.
, because the value of `tracks` should remain an array rather than be assigned a string value.

This is not an issue with the challenge; please ask for a review of your code in the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat room when you have questions about your code rather than filing an issue.

Happy coding!
