### ISSUE TITLE
Test isn't accepting multiline comment syntax

### ISSUE THREAD

**Issue by dmitrij-schmidt** [FreeCodeCamp/FreeCodeCamp#7845]
**Challenge:**
https://www.freecodecamp.com/challenges/use-comments-to-clarify-code

**Issue Description:**
Issue happens while trying to pass the test with multiline comment syntax. It's allowing only one-line comments.
It suppose might not be an issue at all, but there's no clear statement about syntax. In this case it would be nice to explain difference between one-line and multiline comments.

**Browser Information:**
*** `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36`

**My Code:** 
(both starting from line 1 as suggested in other posts):

Valid - passed the test
```
<!-- Only change code above this line -->
```

Theoretically valid - doesn't pass the test
```
<!-- 
Only change code above this line 
-->
```

**Comment by BKinahan** [comment]
The `Only change code above[or below] this line` message appears in later challenges, including JavaScript challenges, as far as I'm aware always as a single-line comment. In this way there is no ambiguity about to which line "this line" refers, and this challenge has the added benefit of explaining that these lines are comments only and don't affect the execution of code.

It seems to me that this should be maintained here, and only a single-line comment should be accepted as a valid answer. Maybe the end of the instructions would be better phrased as "Add a comment line at the top of your HTML that says `Only change code above this line.`"

**Comment by enuddy** [comment]
When I used
``

The only requirement not checked off is my comment does not match the specified phrasing of Only change code above this line. Makes me think a quick fix would be to check the content of the comment, removing any new lines and such, then pass along that text for validation.

I disagree with the idea only a single-line comment should be accepted due to people's coding style / preferences. You may enjoy using those new lines for readability, or what ever other reason. Unless the season specifies for a single line comment  vs multiline, the type of comment should not matter.

**Comment by erictleung** [comment]
@FreeCodeCamp/issue-moderators was this test intended for single-line comment? If so, should we make it more explicit that we want the single-line comment specifically?

**Comment by SaintPeter** [comment]
It seems like we could loosen up the regex to allow linefeeds for a multi-line comment.
