### ISSUE TITLE
Last one is not a palindrome, should return false

### ISSUE THREAD

**Issue by pawelpodsiadly** [FreeCodeCamp/FreeCodeCamp#7861]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20isPalindrome%3B%0A%20%20str%20%3D%20str.replace(%2F%5Cs%2B%2Fg%2C%20'')%0A%20%20%20%20%20%20%20%20%20%20%20.replace(%2F%5C.%2Fg%2C%20%22%22)%0A%20%20%20%20%20%20%20%20%20%20%20.replace(%2F%5C%2C%2Fg%2C%20%22%22)%0A%20%20%20%20%20%20%20%20%20%20%20.toLowerCase()%3B%0A%20%20var%20reversed%20%3D%20str.split('').reverse().join('')%3B%0A%20%20if(str%20%3D%3D%3D%20reversed)%7B%0A%20%20%20%20isPalindrome%20%3D%20true%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20isPalindrome%20%3D%20false%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20isPalindrome%3B%0A%20%20%0A%7D%0A%0A%0A%0Apalindrome('0_0%20(%3A%20%2F-%5C%20%3A)%200-0')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var isPalindrome;
  str = str.replace(/\s+/g, '')
           .replace(/\./g, "")
           .replace(/\,/g, "")
           .toLowerCase();
  var reversed = str.split('').reverse().join('');
  if(str === reversed){
    isPalindrome = true;
  }
  else{
    isPalindrome = false;
  }
  
  return isPalindrome;
  
}



palindrome('0_0 (: /-\ :) 0-0');

```

**Comment by BKinahan** [comment]
From the instructions:
> **Note**
You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

Without punctuation, spaces, and symbols, `'0_0 (: /-\ :) 0-0'` is `'0000'`, which is a palindrome. The tests are working as intended.

**Comment by brianzelip** [comment]
I just came across this same issue. I appreciated the final test in question here in this issue because it made me work a little harder to figure out a solution.

I used a different regex approach than @pawelpodsiadly. I chose to go with the `\W` character class that matches any character that is not an alphanumeric character. I'm not sure why but the underscore is included in the definition of an alphanumeric character [in the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes).

If the intention of the challenge was to define an alphanumeric character as per the definition in the docs linked above, then the final test is actually not a palindrome because underscores are considered alphanumeric. If this is the case then the underscore in the final test should be replaced with a hyphen or the final hyphen should be replaced with an underscore.

But if the intention was to define alphanumeric only as letters and numbers, then the final test is indeed a palindrome.

I kind of thought of the final test as an easter egg of sorts, for those who read the docs to find out that the underscore is considered alphanumeric, and so the solution requires figuring out how to remove underscores too (`[\W_]`).

**Comment by rnicks** [comment]
Just had this problem myself. It looks like just a typo. The last one, as written, is "palindrome("0_0 (: /-\ :) 0-0") should return true" which is incorrect (I assume it's supposed to be "0_0 (: /-\ :) 0_0" (which is a palindrome) but there's a hyphen in there by mistake.

I also used the \w character, which I think is the intention of the test.
