### ISSUE TITLE
Inclrease CloudFlare captcha verification timeout

### ISSUE THREAD

**Issue by kehugter** [FreeCodeCamp/FreeCodeCamp#7919]
#### Issue Description
* Browsing freecodecamp behind an IP blacklisted by CloudFlare triggers the captcha challenge too often (~ every 30 minutes in my experience).

I've been experiencing it since last week. I left some time pass to be sure that it wasn't a measure against an attack. Could you consider increasing the revalidation time to 1 day, or at least some hours? It's very frustrating to be interrupted by captchas (often 3+ in a row) while working on the exercises.

**Comment by BerkeleyTrue** [comment]
I'll look into it

**Comment by BerkeleyTrue** [comment]
Can you give me some information? Location? Are you using a VPN? If so, which?

**Comment by kehugter** [comment]
Yes, VPN. Most major commercial VPNs are affected by CF captchas on all locations (see reports at reddit for instance), it won't help to whitelist IP ranges for a particular one.

**Comment by raisedadead** [comment]
@BerkeleyTrue if you remember I was am also affected by this. :wink: 

Location : Pune, INDIA
VPN : None
ISP : Doesnt stay fixed, it keeps changing between networks, because my vendor randomly assigns each subscriber to a different ISP Network, depending upon load, time, etc.
IP : Willing to provide over chat.

Fix:
I have a tested fix for this, I checked on my own domains for that and seemingly it works. Can discuss more on it.

**Comment by BerkeleyTrue** [comment]
@kehugter I've increased the timeout to an hour. 

@raisedadead Do you mind send me a PM on that fix?
