### ISSUE TITLE
Convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by caseydev** [FreeCodeCamp/FreeCodeCamp#7924]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=function%20convert(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0Aconvert(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line
  
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convert(30);

```

**Comment by AkiraLaine** [comment]
Hey! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only. Happy Coding :smile:

**Comment by SamanthaMartinez** [comment]
going to main room or help room wont help with anything, I've tried the help you can find is incorrect most of the time, and everyone is usually to busy talking about their own stuff. 

This code will get you past the convert to Fahrenheit code:

//the problem was it originaly sayd function convert(celcius) needs to say convertToF.

function convertToF(celsius) {
  // Only change code below this line
//here it only has var fahrenheit you need to add celsius *9/5 + 32
 
 var fahrenheit = celsius * 9/5 + 32;

  // Only change code above this line
//above it tells you to only change the code above but if you do not add this below statement the code will not work.
 
 if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
//here you can leave it (30) i changed mine to (0) it will work either way
convertToF(0);

**Comment by dwd2010** [comment]
@SamanthaMartinez,  on any issue for not get a help. if anyone need a help. use chat room. not at issue.  
on issue for report a bug.
