### ISSUE TITLE
Bonfire Pig Latin: Does not inform user that function name has been changed - fails when correct.

### ISSUE THREAD

**Issue by DanJFletcher** [FreeCodeCamp/FreeCodeCamp#7938]
#### Issue Description
* When Issue Happens

The user has loaded the challenge before the function name has been changed from `translate` to `translatePigLatin`. Because of this, the user still has the function name `translate` and so all assertion tests fail even if the output is correct.
* Steps To Reproduce

Change the `translatePigLatin` function name to anything.

#### Code
```js
function translate(str) {  
  if (isVowel(str.charAt(0))) {
    return str + "way";
  }  
  var front = [];   
  str = str.split('');  
  while (str.length && !isVowel(str[0])) {    
    front.push(str.shift());  
  }  
  return [].concat(str, front).join('') + 'ay';
}

function isVowel(c) {
  return ['a', 'e', 'i', 'o', 'u'].indexOf(c.toLowerCase()) !== -1;
}

translate('consonent');
```
#### Possible Solutions
Maybe an assertion test can be added to check the name of the function. We could even add an `update` message in the bonfire instructions for some temporary amount of time. The message could look something like:

[update] The original code in this challenge has been changed. Make sure that your functions names match this name exactly: `translatePigLatin` for the tests to work.

Or we could do a combination of those solutions.

Does anyone think this is something worth addressing? If so, do you have another solutions to propose, or do these solutions make sense?

**Comment by khaduch** [comment]
I was coming here to open an issue on this very topic, having just run into this yesterday while trying to help someone.  It received some discussion on the contributors forum and seems to have some merit.

I think that this would be valuable because of the name changes that have taken place, and also because there are times when wayward editing by a camper changes the name, and then it throws them into a gray zone where they don't know why it is working.  In the first instance, once you are aware of the name changes, all you have to do is remember to check that by looking at and comparing to the test results.  But for the less experienced who might have innocently made a change thinking that they were doing the right thing to complete the challenge, or someone who is unaware of the name changes, it would be a potentially valuable help. (Although I feel that some people don't focus on the test descriptions as useful sources of information.)

**Comment by sludge256** [comment]
Closing in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7944 since it addresses the wider issue. Thanks for posting! Feel free to continue the discussion there.

**Comment by DanJFletcher** [comment]
Ok sounds good!
