### ISSUE TITLE
Function name changes due to the recent test updates, or inadvertent function name edits by students result in test failures

### ISSUE THREAD

**Issue by khaduch** [FreeCodeCamp/FreeCodeCamp#7944]
#### Function name changes due to the recent updates, or inadvertent function name edits by students result in test failures
- When Issue Happens

This is related to issue #7938, but is a more general-purpose request.  As with issue #7938, there were other challenges and tests that had changes to the function names, and even though the code was functionally correct, the fact that the prior solution that was being used still had the old names resulted in test failures.  Discussion in the contributors forum made it seem that there was merit to adding an additional check for the existence of the proper function name prior to running the test. Or perhaps has a first-level test before running the functional tests. This would cover the case where a student went back to a prior challenge to update the solution, without realizing that there was a change to required function names, and would also give a helping hand to someone who did not understand the challenge's instructions and edited the function name, resulting in similar failures.
- Steps To Reproduce

For the case where a prior solution was revisited and the function names changed, all that you have to do is revisit your solution and try to run it.

**Comment by QuincyLarson** [comment]
@khaduch @SaintPeter @erictleung @sludge256 do any of you have any ideas how we might be able to redesign challenges to where changing function names don't break old solutions? 

One idea I have is that we could redesign the challenge framework to check whether there's only one function in the code, go ahead and run it, assuming that there's a typo in the function name, or that the function name was inadvertently changed since the code last ran.

**Comment by erictleung** [comment]
@QuincyLarson I like the idea. We can try executing the function name we expect, and if it doesn't find anything, we can search for a function definition and execute it instead. This is probably best from a user experience perspective. On the other hand, it could be confusing that the typo function would work, because it isn't the function name we see in the challenge tests (if shown). So this could raise questions as well.

Another, but not really scalable, way to work on this issue is to encode the correct function name in each function-required challenge and check for the correct function name and let the user know their function is incorrectly typed. I don't imagine this solution scaling very well, but it is very clear to the user why their code failed. 

If we could somehow let the user know which function was being used if we just use whatever function was in the editor, that might be a viable option.

**Comment by QuincyLarson** [comment]
@erictleung I think both of those solutions are potentially viable, but I agree that it would be better to not have to have to add the function name as a field on every single challenge. I am going to close this issue for now and if you think of a graceful way to let the user know that they've somehow mistyped the function name (or in most cases, deleted boilerplate), we can reopen this and you can make a PR against it.
