### ISSUE TITLE
SSL error - what's causing this?

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7955]
An email from a camper reads:

I am in a program that requires training on freecodecamp but I cannot access your website for some reason.

My computer is very old but I also don't have the funds to buy a new computer.  Is there any way I can tweak something on my computer in order to access your website?

This is the error I get whenever I try to access your website.
This site can’t provide a secure connection

www.freecodecamp.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Hide details
The client and server don't support a common SSL protocol version or cipher suite. This is likely to be caused when the server needs RC4, which is no longer considered secure.

---
Any idea what could be going on here? Is this an old browser or is there something wrong with FCC?

**Comment by jackytck** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=www.freecodecamp.com, SSL should be setup correctly. Perhaps he may try using a more up to date browser.

**Comment by akkatracker** [comment]
Do we know what browser the camper is using? That may help us diagnose the issue.

**Comment by stevenhs8821** [comment]
I am having the same problem.  Also on Win XP.  Have you made any progress solving this issue?

**Comment by stevenhs8821** [comment]
I solved this problem by installing and using the FireFox browser.

**Comment by raisedadead** [comment]
@stevenhs8821 we never had the chance to know the OS and Browser of the original reporter.
Nevertheless, we couldn't possibly support very old OS and systems.
Part of this is because it involves replicating the issue on a environment as on the reported system.
Then much difficult is to find work around for the environment.

But, glad to know that you found a workaround. 

But personally, I do recommend you to upgrade to a newer OS, Windows XP is officially not supported by Microsoft any more and that exposes your PC to security threats.

**Comment by raisedadead** [comment]
Closing for now as stale. Please comment to re-open.

**Comment by jmkazone** [comment]
Hi - I am having the same issue logging onto comcast email through google chrome with OS Windows 7.  I tried IE and had same issue and really prefer google chrome.  Any suggestions??

**Comment by raisedadead** [comment]
We are sorry, This thread is not for 'comcast email.'
