### ISSUE TITLE
Video Challenges and Jobs Board show 0 brownie points

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#7977]
If I go to any Video Challenge, I see the following:
![image](https://cloud.githubusercontent.com/assets/11958359/14374163/2d069c66-fd9e-11e5-84a7-a61923b74855.png)

**Comment by awesomeaniruddh** [comment]
The jobs board also has the same bug.
![screen shot 2016-04-09 at 7 05 24 pm](https://cloud.githubusercontent.com/assets/5279150/14403368/57ac43ba-fe86-11e5-85ef-ab8d578a220f.png)

**Comment by robeerob** [comment]
I am only adding this, as it might be of help to whomever can fix this, but here is the two different <li></li> tags and their content from a regular challenge and a video challenge:

`<li class="brownie-points-nav"><a href="/robeerob">[&thinsp;307&thinsp;]</a>`

`<li role="presentation" data-reactid=".11po48uf400.0.0.2.0.$5/=11"><a href="/robeerob" class="brownie-points-nav" data-reactid=".11po48uf400.0.0.2.0.$5/=11.0"><span data-reactid=".11po48uf400.0.0.2.0.$5/=11.0.0">[ </span><span data-reactid=".11po48uf400.0.0.2.0.$5/=11.0.1">0</span><span data-reactid=".11po48uf400.0.0.2.0.$5/=11.0.2"> ]</span></a></li>`

My best guess is that that spedicific <li> element in the nav should be stripped down and be given the "brownie-points-nav" class, so that some .js file can work it's js or jquery magic on it.
