### ISSUE TITLE
Bonfire Pair Input - Enter Button Does Not Submit

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#80]
This is a minor UX gripe, please consider when there is more time. After putting in the username of the pair partner into the pair field, one must click on the button to proceed rather than the enter key submitting the pair partner username and going to the next challenge.

Attached is a video of the UX shortcoming. I used a test account for the video.

https://drive.google.com/file/d/0B-94cRSEUQu_RnFHTWhnSnhFODQ/view?usp=sharing

**Comment by terakilobyte** [comment]
We've added this functionality into the courseware branch with one small caveat. We've chosen ctrl-enter as the keyboard shortcut to submit the form as it mirrors the keyboard shortcut to execute code evaluation. I'll close this issue when courseware is the new norm.

**Comment by terakilobyte** [comment]
Closing this enhancement request. ctrl-enter will now cause submission of the modal in both coursewares and bonfires. This shortcut was chosen since it is also the same shortcut to execute bonfire tests. Closing the modal by any means will result in focus being returned to the editor area where the user left off.
