### ISSUE TITLE
Indonesian Translation of Getting Started

### ISSUE THREAD

**Issue by baguzzzaji** [FreeCodeCamp/FreeCodeCamp#8025]
Because there's  no Indonesian translation existed, so I want to start one.

**Comment by zainalmustofa** [comment]
Awesome let's start for bahasa :D

**Comment by dikiaap** [comment]
Ok, I want to help.

**Comment by JeansBolong** [comment]
Sound great, i can help 😄

**Comment by alistermada** [comment]
Be sure to join the [Bahasa Indonesia Translation](https://gitter.im/FreeCodeCamp/TranslationBahasaIndonesia) chat room in Gitter. We can discuss translation over there.
 
Check out the [Translations Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Translations-Guide) as well for more technical info.
.

**Comment by christoga** [comment]
Sound's great, maybe I can help

**Comment by iqbaladan** [comment]
awesome, hope can contribute to it.

**Comment by tamami** [comment]
Berhubung udah lama banget.. saya coba lanjut aja ya.. :)

**Comment by christoga** [comment]
Saya juga bingung, ini sudah selesai atau tiba-tiba break?

**Comment by raisedadead** [comment]
Hey all, any updates on this? 

We have moved our translation collaboration to the https://github.com/FreeCodeCamp/TranslationExpansion repo. This issue can continue here, owing to the discussion length it has, but please log any new issues on the above repo.

Thanks, and Happy Translating!

**Comment by alistermada** [comment]
@raisedadead The translation for Getting Started is complete, but it was made by several translators and has some inconsistencies.

Haven't heard much from the original translators. I'm hesitant to fix it up myself since I'm not a native Indonesian speaker. There are campers in my area who are interested in cleaning up the translation and making the PR themselves. Can't make any guarantees, though.

**Comment by raisedadead** [comment]
Moved to https://github.com/FreeCodeCamp/TranslationExpansion/issues/87
