### ISSUE TITLE
Does not work in firefox. But why? 

### ISSUE THREAD

**Issue by kvamsdal** [FreeCodeCamp/FreeCodeCamp#8054]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20a%20%3D%207%3B%0Avar%20b%20%3D%20a%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a;
var b = 2;

// Only change code below this line
var a = 7;
var b = a;
```

**Comment by lastsumerian** [comment]
Shoebox lastsumerian@icloud.com 123Sex free or ND140688VP one from this password if not just need to restore password

**Comment by erictleung** [comment]
@kvamsdal thanks for the issue but I couldn't reproduce this but the `var` statements you've inserted aren't necessary because the variables `a` and `b` are already created. Maybe that'll help. If you get stuck with a challenge in the future, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
