### ISSUE TITLE
Change font size test could be more clear

### ISSUE THREAD

**Issue by insrt** [FreeCodeCamp/FreeCodeCamp#8099]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%20p%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
   p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by cannelflow** [comment]
Your First p Should Contain class="red-text"  You Can Always Use Fcc Chat Room https://gitter.im/FreeCodeCamp/Help Before Coming Here

**Comment by erictleung** [comment]
@insrt thanks for the issue. It does seem contradictory and unclear. The test could be more clear. Only the first `<p>` element needs the `font-size` class. The wording could be changed to:

> Give the first `p` tag element a font-size of `16px`. Browser and Text zoom should be at 100%.

**Comment by Stephaceae** [comment]
Ok, just got stuck on this challenge.  The wording IS clearer now - it was clear that I was supposed to assign both p elements with 16px font INSIDE the style tag.  HOWEVER we are NOT told how to ' create an entry for p elements.'  

With some frustrated googling I found that I could use 'p' to assign attributes to p elements in CSS1 (I guessed that and tried it, but tried putting the period in front of the 'p.'  My entry looked like insert's but with .p {font-size: 16px;} instead of p {font-size: 16px;}... the only way I saw how to do it was finding this thread.  Please add the relevant instructions to this challenge.
