### ISSUE TITLE
personality

### ISSUE THREAD

**Issue by desult** [FreeCodeCamp/freecodecamp#812]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Give your radio buttons the name attribute of "personality".

Cannot satisfy this request. This waypoint is on checkboxes and it is asking for me to edit the radio button. I've changed the checkboxes and the radio buttons to have name="personality" nothing works.

**Comment by desult** [comment]
http://postimg.org/image/4x61duuz9/

**Comment by treece** [comment]
I was just about to report this because someone was having this issue in slacks help channel :) The problem seems to be in the test: `"assert($('input[type=\"checkbox\"]:nth-child(1)').attr('name') === 'trait', 'Give your radio buttons the <code>name</code> attribute of \"personality\".')"`

If you add trait to a checkbox then the challenge will pass.

I think I might start contributing to fix these as they come up :-)

**Comment by desult** [comment]
Thanks

**Comment by BerkeleyTrue** [comment]
@desult Does @treece comment fix your issue?

**Comment by desult** [comment]
@BerkeleyTrue The issue still exists. I've at least been able to get past that waypoint and move on.

The waypoint should be asking for name="trait" for the checkbox. not name="personality" for radio button.

**Comment by treece** [comment]
@desult Yea, my commit hasn't been merged yet :-) but what I think @BerkeleyTrue is asking is if my comment and not commit allows the challenge to pass for you. The comment about adding the name trait to a checkbox passes the challenge for you? By your comment, it seems like that's a yes? correct?
 >If you add the name trait to a checkbox then the challenge will pass.

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.

**Comment by desult** [comment]
@treece Yes, I was able to pass the challenge by adding "trait" to name.
