### ISSUE TITLE
Dealing with Floating-Point Arithmetic in Exact Change

### ISSUE THREAD

**Issue by cmac4603** [FreeCodeCamp/FreeCodeCamp#8162]
Challenge [Exact Change](https://www.freecodecamp.com/challenges/exact-change#?solution=function%20checkCashRegister(price%2C%20cash%2C%20cid)%20%7B%0A%20%20var%20cf%20%3D%201000%3B%0A%20%20var%20changeDue%20%3D%20cash%20-%20price%3B%0A%20%20var%20dues%20%3D%20(cash%20-%20price)*cf%3B%0A%20%20var%20register%20%3D%20cid.reduce(function(acc%2C%20curr)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20acc.total%20%2B%3D%20curr%5B1%5D*cf%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20acc%5Bcurr%5B0%5D%5D%20%3D%20curr%5B1%5D*cf%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20acc%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%20%7Btotal%3A%200%7D)%3B%0A%20%20console.log(register.total)%3B%0A%20%20var%20monies%20%3D%20%5B%5B%27ONE%20HUNDRED%27%2C%20100*cf%5D%2C%0A%20%20%20%20%5B%27TWENTY%27%2C%2020*cf%5D%2C%0A%20%20%20%20%5B%27TEN%27%2C%2010*cf%5D%2C%0A%20%20%20%20%5B%27FIVE%27%2C%205*cf%5D%2C%0A%20%20%20%20%5B%27ONE%27%2C%201*cf%5D%2C%0A%20%20%20%20%5B%27QUARTER%27%2C%200.25*cf%5D%2C%0A%20%20%20%20%5B%27DIME%27%2C%200.1*cf%5D%2C%0A%20%20%20%20%5B%27NICKEL%27%2C%200.05*cf%5D%2C%0A%20%20%20%20%5B%27PENNY%27%2C%200.01*cf%5D%0A%20%20%5D%3B%0A%20%20var%20change%20%3D%20%5B%5D%3B%0A%20%20if%20(register.total%20%3C%20dues)%20%7B%0A%20%20%20%20return%20%22Insufficient%20Funds%22%3B%0A%20%20%7D%0A%20%20else%20if%20(register.total%20%3D%3D%20dues)%20%7B%0A%20%20%20%20return%20%22Closed%22%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20for%20(var%20i%20%3D%200%20%3B%20i%20%3C%209%20%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20var%20cashMoney%20%3D%200.00%3B%0A%20%20%20%20%20%20if%20(dues%20%3E%3D%20monies%5Bi%5D%5B1%5D%20%26%26%20monies%5Bi%5D%5B1%5D%20%3C%3D%20register%5Bmonies%5Bi%5D%5B0%5D%5D)%20%7B%0A%20%20%20%20%20%20%20%20while%20(dues%20%3E%3D%20monies%5Bi%5D%5B1%5D%20%26%26%20monies%5Bi%5D%5B1%5D%20%3C%3D%20register%5Bmonies%5Bi%5D%5B0%5D%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20dues%20-%3D%20monies%5Bi%5D%5B1%5D%3B%0A%20%20%20%20%20%20%20%20%20%20register%5Bmonies%5Bi%5D%5B0%5D%5D%20-%3D%20monies%5Bi%5D%5B1%5D%3B%0A%20%20%20%20%20%20%20%20%20%20register.total%20-%3D%20monies%5Bi%5D%5B1%5D%3B%0A%20%20%20%20%20%20%20%20%20%20cashMoney%20%2B%3D%20monies%5Bi%5D%5B1%5D%2Fcf%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(monies%5Bi%5D%5B1%5D%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20change.push(%5Bmonies%5Bi%5D%5B0%5D%2C%20cashMoney.toFixed(2)%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20var%20left%20%3D%200%3B%0A%20%20for%20(var%20j%20%3D%200%20%3B%20j%20%3C%20change.length%20%3B%20j%2B%2B)%20%7B%0A%20%20%20%20left%20%2B%3D%20change%5Bj%5D%5B1%5D%3B%0A%20%20%7D%0A%20%20if%20(left%20%3C%20changeDue)%20%7B%0A%20%20%20%20return%20%22Insufficient%20Funds%22%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20return%20change%3B%0A%20%20%7D%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function checkCashRegister(price, cash, cid) {
  var cf = 1000;
  var changeDue = cash - price;
  var dues = (cash - price)*cf;
  var register = cid.reduce(function(acc, curr) {
                          acc.total += curr[1]*cf;
                          acc[curr[0]] = curr[1]*cf;
                          return acc;
                        }, {total: 0});
  console.log(register.total);
  var monies = [['ONE HUNDRED', 100*cf],
    ['TWENTY', 20*cf],
    ['TEN', 10*cf],
    ['FIVE', 5*cf],
    ['ONE', 1*cf],
    ['QUARTER', 0.25*cf],
    ['DIME', 0.1*cf],
    ['NICKEL', 0.05*cf],
    ['PENNY', 0.01*cf]
  ];
  var change = [];
  if (register.total < dues) {
    return "Insufficient Funds";
  }
  else if (register.total == dues) {
    return "Closed";
  }
  else {
    for (var i = 0 ; i < 9 ; i++) {
      var cashMoney = 0.00;
      if (dues >= monies[i][1] && monies[i][1] <= register[monies[i][0]]) {
        while (dues >= monies[i][1] && monies[i][1] <= register[monies[i][0]]) {
          dues -= monies[i][1];
          register[monies[i][0]] -= monies[i][1];
          register.total -= monies[i][1];
          cashMoney += monies[i][1]/cf;
        }
        if (monies[i][1] !== 0) {
          change.push([monies[i][0], cashMoney.toFixed(2)]);
        }
      }
    }
  }
  var left = 0;
  for (var j = 0 ; j < change.length ; j++) {
    left += change[j][1];
  }
  if (left < changeDue) {
    return "Insufficient Funds";
  }
  else {
    return change;
  }
}
```
Hello all,

So I have an issue that I can't seem to find already reported, and it is the fact that I think the whole number/floating point arithmetic problem here is handled incorrectly. The test cases, for example, return the number "15" for fives in one, and the number "55.00" in another. I have gone about using a correcting factor, and then use toFixed() to return a string with the number to 2 decimal places.

I believe this is the "correct way" to handle fixed decimal places in JS, after doing a fair bit of research. Is there any way to get an answer like mine, accepted? I'm just not convinced this is the most accurate way with floating points taken into consideration as it currently stands.

Please also note, my method maintains all tracking of monies coming and going as whole numbers, and only returns a string as the answer.

**Comment by BKinahan** [comment]
First, as a minor point, your correcting factor `cf` would probably make more symbolic sense as `100` rather than `1000` because the numbers you're working with would then represent the amount of pennies equivalent to the currency denominations and amounts. Mathematically it makes no difference at the precision used in the challenge, and 1000 seems slightly arbitrary. Could be 3000 or 200 or...

Secondly, as you mentioned, the `toFixed()` method returns a string, which, while useful for representing currencies as we humans are used to seeing them, would make handling further (hypothetical) calculations with the amounts of change given more complex. (For example, summing the total number or value of pennies given as change throughout a business day, etc.) I think expecting these amounts to be represented as numbers in the returned arrays is preferable.

On that note (no money pun intended), I agree that there should be consistency in the number representation in the expected outputs of the test cases. However to be clear, that only refers to the text displayed with each test condition below the "Run Tests" button. That is to say, the number `15` is equivalent (strictly equal) to `15.00` or `15.0000` so it's not necessary to return any further precision than `15` for that number, and the same goes for `1.5` and `1.50` for a dollar and fifty cents. The tests themselves make no distinction, and submitting code that doesn't account for floating point arithmetic problems (like `1.500000001`) will still not pass the tests.

I'll write a quick PR that makes the number format more consistent in the test texts, with two decimal places for positive values and retaining values of `0` as they are. Bike shedding, yay!
