### ISSUE TITLE
Record collection > feels like steep learning curve

### ISSUE THREAD

**Issue by allenhsieh** [FreeCodeCamp/FreeCodeCamp#8207]
Hi All,

Not sure if this is the right place to put this, or even how to put this properly: I have been making my way through FreeCodeCamp and all the exercises up until Record Collection have been built with a steady progression of knowledge and have been very do-able, with all needed knowledge presented in previous exercises.

My issue is that to complete this exercise, double brackets need to be used, for instance

```
 collection[id][prop] = value;
```

I went back and checked various exercises (the 20 before this, and doing a search for "brackets" for all exercises) and I didn't see a mention of double brackets, so I didn't know double brackets were possible and none of the previous exercises seemed to lead me to that train of thought. The only way I was able to complete this exercise was jumping onto gitter and having someone tell me explicitly to use collection[id][prop]. I was able to write all the other parts of the code and work through the logic mostly by myself except for the double brackets part.

I guess i'm just suggesting a note, hint, or exercise on double brackets somewhere before this exercise might be useful as there was no other way for me to know double brackets were possible without the help of others in gitter.

Thank you very much for your time and sincere apologies if this isn't the proper place for this message,
Allen

Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
   if ((value !== "") && (prop !== "tracks")){
     collection[id][prop] = value;
    } else if ((prop == "tracks") && (value !== "")){
      collection[id].tracks.push(value);
    } else if (value === ""){
      delete collection[id][prop];
    }
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by raisedadead** [comment]
@allenhsieh Thanks for reporting this. 
You can also discuss this more in the [Curriculum Development Chat room](https://gitter.im/FreeCodeCamp/CurriculumDevelopment).

@SaintPeter this one needs your expertise I believe.

/cc @FreeCodeCamp/issue-moderators

**Comment by erictleung** [comment]
I agree that it is explicitly mentioned that double brackets are "legal." There is one lesson that does use this double bracket notation, but it is with [multi-dimensional arrays](https://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes). 

I guess it is implied in this lesson that with the first bracket, you get the array. Then with another set of brackets, you're able to access the next level. This confusion might stem from this is on an array nested within a JavaScript object, rather than an array within another array.

For this lesson, I guess it wouldn't hurt to mention that you can access elements within arrays nested within JavaScript objects with double brackets.

**Comment by SaintPeter** [comment]
It might make sense to have another challenge called "Nested Objects" that explicitly shows the double bracket notation.

**Comment by raisedadead** [comment]
So we add a challenge and a hint in this challenge to refer that? That should solve the confusion.

**Comment by khaduch** [comment]
I just noticed this issue - it's a great point.  This particular challenge does seem to throw many people for a loop.  Good to know that it is getting some attention.  I was also trying to develop a better explanation or description of the problem, thinking that some people just didn't grasp the concept of a "record collection" or "album collection" and what they were supposed to be trying to achieve with the code?

It definitely feels that there has to be another stepping stone before this. If it help at least half of the people who get stuck with this, it will be worthwhile!

**Comment by CalcCalcCalc** [comment]
I personally felt like this was the first real stump in the curriculum.
The fact is, this exercise mentions dot notations only, and says absolutely nothing about double bracket notation. 
In the context of JSON objects, double bracket notation is not mentioned prior to this exercise. 
I suggest adding a small exercise showing how to use double bracket notation, and link to that one instead of the one it currently links to.

**Comment by seemaullal** [comment]
I am happy to work on this and add a exercise on multidimensional arrays and objects if people think this needs to be changed. What do you think @FreeCodeCamp/issue-moderators

**Comment by beardedtim** [comment]
Just my two cents from helping people in Gitter with this problem:

It seems that students are not understanding that `obj[key]` is being resolved/boiled down into an actual value and instead is just some sort of magic. If instead of just showing them `obj[key][otherKey]`, I think it would be more effective if we showed them that to our computer `obj[key]` is a value, just like `obj` is. 

I am not sure if equality is taught before `obj[key]` is but perhaps showing that the nested object is equal (literally equal, not equivalent) to `obj[key]` will help drive the point home that we are grabbing a value and then grabbing a value from that value.

**Comment by afable** [comment]
I found the `Record Collection` challenge more difficult because a few challenges before it, the `Accessing Nested Objects` challenge would not accept the following code:

[Accessing Nested Objects challenge gives multiple warnings that both ['car'] and ['inside'] is better written using dot notation](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20myStorage%5B%22car%22%5D%5B%22inside%22%5D%5B%22glove%20box%22%5D%3B%20%2F%2F%20Change%20this%20line%0A%0A)

Which fails a test case with...

`Use dot and bracket notation to access myStorage`

I had to open the Chrome console just to make sure that multiple bracket notation was still valid Javascript. But this mindset led me to start the `Record Collection` challenge with a bunch of `collection.id.prop` instead of `collection[id][prop]` thinking the latter was bad coding form. Unfortunately, the only error I got from the FCC console was:

`TypeError: Cannot set property 'prop' of undefined`

which led me to playing around in the Chrome console again accessing objects via different dot/bracket notations.

**Comment by QuincyLarson** [comment]
Thanks for your feedback, everyone. We've moved Record Collection to the advanced algorithms section.
