### ISSUE TITLE
Bug in Steamroller challenge

### ISSUE THREAD

**Issue by sdg123** [FreeCodeCamp/FreeCodeCamp#8259]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller#?solution=var%20new_arr%3D%5B%5D%3B%0Afunction%20steamrollArray(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20if(Array.isArray(arr%5Bi%5D))%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20steamrollArray(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20else%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20new_arr.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20return%20new_arr%3B%0A%7D%0A%0AsteamrollArray(%5B1%2C%20%7B%7D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
All the test cases produce a valid output but the challenge does not get completed.
My code:
```javascript
var new_arr=[];
function steamrollArray(arr) {
  // I'm a steamroller, baby
  for(var i=0;i<arr.length;i++)
    {
    if(Array.isArray(arr[i]))
      {
        steamrollArray(arr[i]);
      }
     else
      {
        new_arr.push(arr[i]);
      }
    }
      
  return new_arr;
}

steamrollArray([1, {}, [3, [[4]]]]);

```

**Comment by theflametrooper** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by redcinelli** [comment]
Hi peeps. Same issue. My output is right but it seems I can't validate the challenge. None of the test pass, even though the output print it right ? any clue ?

**Comment by deyvidyury** [comment]
I've noticed that in the answers provided with the test cases there are one space between the coma and the number. I think this shouldn't be a cause for not accepting the results. I'm facing this now, trying to produce a output exactly as the outputs on the test cases.

**Comment by GaryLeutheuser** [comment]
While this is closed, I thought I would share my findings for those that may end up here: It seems the reason this doesn't pass the test cases, but still prints the right result, is because it is actually returning more than once for each call.

It seems like Free Code Camp only checks the first value returned, (which is naturally incomplete and wrong), causing you to fail without knowing why. To see this, add a `console.log(new_arr);` right before `return new_arr` - you will see many returns for each call (and the first return for each call will not be correct).

**Comment by msabitabrata** [comment]
This error is happening as you are using global variable to store the data. So, every time this code runs all the array values are pushed to the global variable and that's why you are facing this issue. I resolved it by removing the global variable and pushing the array elements into a local variable.

**Comment by Ynull** [comment]
I think @msabitabrata is right, I was stuck here for a long time, maybe it needs more hints about the restrictions of the problem. Here is my solution:
```
function steamrollArray(arr) {
  // I'm a steamroller, baby
  var ar = [];
  while(Array.isArray(arr)&&arr.length>0){
    var elem = arr.shift();
    if(Array.isArray(elem)){
      arr = elem.concat(arr);
		}else{
			ar.push(elem);
		}
  }
	return ar;
}
```

**Comment by texas2010** [comment]
@Ynull 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
