### ISSUE TITLE
Create challenges on libraries that are used in the background (Animate.css)

### ISSUE THREAD

**Issue by theframeON** [FreeCodeCamp/FreeCodeCamp#8337]
#### Issue Description

I have a question - why this freecodecamp don't teach everything i need to know to code? For example now i started learning jQuery and once again FCC did a background code that i should have learned."Note that we've already included both the jQuery library and the Animate.css library in the background" .If im learning coding, i need to know that things.But FCC don't teach 'em so that's a big minus for FCC...

Without knowing what that background libraries are, and how they work, im not able to fully learn coding. And this is not first time when FCC did a background code.

**Comment by erictleung** [comment]
@theframeON thanks for the feedback. When I was going through that part, I was more focused on actually using jQuery but I can understand how hiding this background code can be frustrating. My guess on why they did wrote it this way was to make it easier to get practice with **using** jQuery instead of just getting bogged down with setting up.

cc/ @FreeCodeCamp/issue-moderators thoughts?

**Comment by theframeON** [comment]
@erictleung Problem is that i'm new to coding. And i don't know anything about what are jQuery libraries and many more things are. 
I can understand that setting everything up can be pain in ass, and it's better to just start using jQuery.
But why not just add at last 5min challenge which will explain everything newbie must know about setting all up and libraries?  
Not setting myself, but understanding what it is and why i need to know it would be nice.

And it's not only about libraries, but about everything they do in background that can be very helpful to know.

I'm not asking to change anything, i'm asking to add more helpful info for newbies.

**Comment by theflametrooper** [comment]
@erictleung Possibly, if we create a challenge just explaining how animate.css works and some links to learning it. I don't think it's really worth creating a whole set of challenges on them.

**Comment by theframeON** [comment]
@theflametrooper Yep. That's what i'm talking about.

**Comment by ltegman** [comment]
Teaching every library isn't practical. Just because Free Code Camp uses something in their code base doesn't mean it's something that is common or useful enough to be worth learning. We also use RxJS but we're not going to make lessons on FRP. We teach core skills that will help you start making full-stack apps, but there's plenty of other tools and libraries you will teach yourself on your coding journey. Animate.css is not valuable enough to be worth teaching, we simply use it because animations make it easy to see what you're doing with jQuery. I hope that makes sense. Thanks and happy coding!
