### ISSUE TITLE
FalsyBouncer - to Easy??

### ISSUE THREAD

**Issue by Balvamar** [FreeCodeCamp/FreeCodeCamp#8381]
#### Challenge Name

[FalsyBouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0Avar%20result%20%3D%20%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D.filter(bouncer)%3B%0A%0Aconsole.log(bouncer(result))%3B)

#### Issue Description

I have used Code Pen to write my code before placing it in the challenge and checking it. 
For this challenge, I started to write the code, and found that the included code passes for each of the four tests provided, however does not pass in the challenge test.

#### Browser Information

Chrome: Version 49.0.2623.112 m
Windows 7 Enterprise
Desktop

#### Your Code

```js
function bouncer(arr) {
  return arr;
}
var result = [1, null, NaN, 2, undefined].filter(bouncer);
console.log(bouncer(result));
/*
bouncer([7, "ate", "", false, 9]) should return [7, "ate", 9]. - correct
bouncer(["a", "b", "c"]) should return ["a", "b", "c"]. - correct
bouncer([false, null, 0, NaN, undefined, ""]) should return []. - correct
bouncer([1, null, NaN, 2, undefined]) should return [1, 2]. - correct
*/

```

**Comment by erictleung** [comment]
@Balvamar thanks for the issue. The tests on FCC will run tests on your function `bouncer`.  For your code so far, it will just return the array it is given, which will not give you the correct answer. So you'll need to modify your code so that passing the function `bouncer` an array will filter out the correct elements. Closing as not an issue with the site. Happy coding!
