### ISSUE TITLE
Issue with add image lecture

### ISSUE THREAD

**Issue by FreedomOpenProjects** [FreeCodeCamp/FreeCodeCamp#8387]
When I was in adding a photo lecture, If i write myself <img scr="url"> then it didnot allow,
but if I copied this code <img src="https://www.your-image-source.com/your-image.jpg"> then modified url to https://bit.ly/fcc-relaxing-cat then booom it's ok

#### Challenge Name

https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fwww.your-image-source.com%2Fyour-image.jpg%22%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A
#### Browser Information

* Browser Name, Version: Chrome latest
* Operating System: window 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<img scr="https://bit.ly/fcc-relaxing-cat">
<img src="https://bit.ly/fcc-relaxing-cat">

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by raisedadead** [comment]
Hi @FreedomOpenProjects 

Thanks for reporting this. But your code is not correct.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding. If its confirmed there that what you are facing is indeed an issue, we may re-open this.

Happy Coding!

**Comment by shriya1240** [comment]
cant go to next challenge. i have completed this one

**Comment by raisedadead** [comment]
@shriya1240 request you to reach out to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to coding, if you feel there is a bug, you can report a new issue.

Thanks.

**Comment by shriya1240** [comment]
Dear Sir ,

after running the code it is showing that i have completed it but i cant go
next.


On Mon, Jun 27, 2016 at 5:51 PM, Mrugesh Mohapatra <notifications@github.com

**Comment by raisedadead** [comment]
@shriya1240,

Okay in that case please visit [this link](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/new) and open the challenge in a new tab, take a screenshot and upload it (drag drop).

We will try to figure out.
Thanks.

**Comment by glennaxworthy** [comment]
This is wonderful. I'm trying to follow the steps but this step is a bug. Hasn't been fixed. Can't progress. My HTML is good. I wrote this stuff for years but wanted a refresher

**Comment by glennaxworthy** [comment]
@raisedadead "Your code is not correct". "If its confirmed there that what you are facing is indeed an issue, we may re-open this".

But you just said it isn't an issue and closed it? Then it's not an issue according to you!

**Comment by raisedadead** [comment]
@glennaxworthy Thanks for reporting, and apologies if this created any confusion.

The Opening Poster has since updated the initial post with below:
> When I was in adding a photo lecture, If i write myself <img scr="url"> then it didnot allow,
but if I copied this code `<img src="https://www.your-image-source.com/your-image.jpg">` then modified url to `https://bit.ly/fcc-relaxing-cat then booom` it's ok

That's what I was referring to initially for the code being incorrect, we usually do not provide coding related assistance on GitHub, and this should be taken up in the chat rooms.

Let us know if this clears the confusion.

**Comment by raisedadead** [comment]
@FreedomOpenProjects @shriya1240 @glennaxworthy we are still open to re-open this in case you guys feel the instructions can be more clear?

**Comment by glennaxworthy** [comment]
Thanks for following up. But I do feel that typing the code in by hand rather than by cut and pasting it reinforces the lesson more. It makes the exercises feel superior to just reading a book at the expense of introducing typos which occur in the real world as we know. I've been writing software for 30 years and taught un-related subjects for two years but HTML is new to me. Again, my problems were:
1. An incorrectly formed url shouldn't have worked in your simulation. If it's not correct it should not work. Why would anyone examine the url for problems if no problem is indicated. Teaching coding by cut and paste so as to avoid typos seems wrong and it won't take you far in the real world.
2. The reportage of the error indicated that I had not supplied a src attribute while I had indeed done so, albeit with an incorrect url. This error message made no sense and wouldn't lead my to re-examine the url either. A message indicating a bad url would have solved the problem in an instant.
I'm not going to push for a fix because I'm long past the issue but I do think a fix for at least one of those issues would save time and frustration for people who would rather type in their code. I like the nature of your website and my daughter is making much of it. You can close the issue if you wish.
Thanks
