### ISSUE TITLE
Forever Testing Challenge...

### ISSUE THREAD

**Issue by Kyotain** [FreeCodeCamp/FreeCodeCamp#8397]
Challenge [Spinal Tap Case](https://www.freecodecamp.com/challenges/spinal-tap-case) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  
  var regex = /\s+|_+/g;
  str = str.replace(/([a-z])([A-Z])/g, '$1 $2');
  return str.replace(regex, '-').toLowerCase;
}

spinalCase('This Is Spinal Tap');

```

When I try to run the test, it says // testing challenge... and never changed. I received notifications when the code was wrong previously, and after I turned toward the internet for help, I no longer get a response from FreeCodeCamp after I ctrl+enter or press the test button. I've tried deleting my cookies and local files, but I still just see // testing challenge... and nothing more. How can I progress?

**Comment by raisedadead** [comment]
Thanks for reporting this. 

Your code is returning a `function` instead of a `string`, this is messing up internally with other intermediate JavaScript, and the execution gets blocked after an exception is thrown.

If you test your code modified to check :
```js
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins

  var regex = /\s+|_+/g;
  str = str.replace(/([a-z])([A-Z])/g, '$1 $2');
  return str.replace(regex, '-').toLowerCase;
}

var x = spinalCase('This Is Spinal Tap');
console.log(typeof x);
```

The output of that log statement in browser console is `function` instead of a `string`

Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!
