### ISSUE TITLE
Check for Palindromes Rule Issue

### ISSUE THREAD

**Issue by HalfEvil3** [FreeCodeCamp/FreeCodeCamp#8442]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20oldstr%20%3D%20str%3B%0A%20%20var%20seminewstr%20%3D%20str%3B%0A%20%20var%20teststr%20%3D%20(%2F%5CW%2Fgi).test(oldstr)%3B%0A%20%20var%20Underscoretest%20%3D%20(%2F%5Cx5f%2Fgi).test(oldstr)%3B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20var%20newstr%20%3D%20%22%22%3B%0A%20%20%0A%20%20if%20(teststr%20%3D%3D%3D%20true)%7B%0A%20%20%20%20oldstr%20%3D%20str.replace(%2F%5CW%2Fgi%2C%22%22)%3B%0A%20%20%20%20seminewstr%20%3D%20oldstr.toLowerCase()%3B%0A%20%20%7D%0A%20%20%20%20arr%20%3D%20seminewstr.split(%22%22)%3B%0A%20%20%20%20arr.reverse()%3B%0A%20%20%20%20newstr%20%3D%20arr.join(%22%22)%3B%0A%20%20if%20(newstr%20%3D%3D%20seminewstr)%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20else%20return%20Underscoretest%3B%0A%7D%0A%0Apalindrome(%22five_four%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  var oldstr = str;
  var seminewstr = str;
  var teststr = (/\W/gi).test(oldstr);
  var Underscoretest = (/\x5f/gi).test(oldstr);
  var arr = [];
  var newstr = "";
  
  if (teststr === true){
    oldstr = str.replace(/\W/gi,"");
    seminewstr = oldstr.toLowerCase();
  }
    arr = seminewstr.split("");
    arr.reverse();
    newstr = arr.join("");
  if (newstr == seminewstr){
      return true;
    
  }
  else return Underscoretest;
}

palindrome("five_four");

```
The above code successfully complies with all the rules given. However, the input may not be a palindrome. As the above example shows, the input "five_four", which is not a palindrome, returns "true". The input successfully complies with all rules given for the lesson.

**Comment by bcherny** [comment]
You're code doesn't look totally right to me.

When you're not sure what your program is doing, it's helpful to use a debugger, or strategically put `console.log`s around your code to see what's actually happening.

I put 2 `log`s in your code:

```js
function palindrome(str) {
  // Good luck!
  var oldstr = str;
  var seminewstr = str;
  var teststr = (/\W/gi).test(oldstr);
  var Underscoretest = (/\x5f/gi).test(oldstr);
  var arr = [];
  var newstr = "";

  if (teststr === true){
    oldstr = str.replace(/\W/gi,"");
    seminewstr = oldstr.toLowerCase();
  }
    arr = seminewstr.split("");
    arr.reverse();
    newstr = arr.join("");
  if (newstr == seminewstr){
      console.log('1')
      return true;

  }
  else {
    console.log('2')
    return Underscoretest;
  }
}
```

Note that when I call your `palindrome()` function with `"five_four"`, the second (`2`) `console.log` is called! So your code says that the given string is a palindrome because `(/\x5f/gi).test("five_four")` evaluates to `true`.

Is that the logic you want? Why are you testing for an underscore in the first place?

**Comment by khaduch** [comment]
I think that the problem is that you can write code that will pass all of the tests that are run, but it will also pass for other cases - any string that has an underscore will return `true` in this case.  It looks like another test needs to be implemented to have a string with an underscore that is **not** a palindrome, so that some code that allows underscore to be the determining factor for some cases will fail.

At least, I think that's the point...

**Comment by bcherny** [comment]
Ah, I see what you're saying. Makes sense!

**Comment by raisedadead** [comment]
Thanks @bcherny and @khaduch 
Yup this could use some updates to the tests.
For example:
> `palindrome("five|\_/|four")` should return false.

**Comment by HalfEvil3** [comment]
You are correct khaduch, the above code can be run and pass all the test for the lesson. Their is nothing wrong with the code itself, but using the logic of the tests for the lesson it will still complete it.

**Comment by HalfEvil3** [comment]
Oh I test for an underscore because a word character(\w) includes the underscore character. Here is a link to w3schools about it: http://www.w3schools.com/jsref/jsref_regexp_wordchar_non.asp

I was trying to remove the underscore before testing it as a palindrome.

**Comment by zaclem01** [comment]
@raisedadead Trying out my git chops. I can add a test for underscores. It just goes in the test key of the JSON for the challenge correct?

**Comment by raisedadead** [comment]
@zaclem01:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L155

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
