### ISSUE TITLE
Add Placeholder Text to a Text Field challenge syntax error

### ISSUE THREAD

**Issue by yungkurt** [FreeCodeCamp/FreeCodeCamp#8443]
![screenshot 4](https://cloud.githubusercontent.com/assets/18606501/15005005/a064e6b6-118c-11e6-914c-02a1f0d02401.png)
![placeholder challenge](https://cloud.githubusercontent.com/assets/18606501/15005054/32c0af18-118d-11e6-8f57-1e01f70731ef.jpg)

Challenge [Add Placeholder Text to a Text Field](https://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cinput%20type%3D%22text%22%0Aplaceholder%3D%22cat%20photo%20URL%22%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text"
placeholder="cat photo URL">
```

**Comment by bcherny** [comment]
This seems like a legitimate bug - spacing shouldn't matter when parsing HTML. If someone can point me to the source code for this challenge (or if there's a more general HTML parser somewhere in the codebase) I can take a shot at fixing this.

**Comment by raisedadead** [comment]
@bcherny Awesome!

Check this for the code :
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L2099

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by bcherny** [comment]
@raisedadead Looks like there's 3 tests - the first 2 can only pass if the `<input>` is valid, making the 3rd test a bit redundant. How do you feel about just removing the 3rd test?

As a side note, inlining JS and regexes into JSON like this seems pretty hacky. Have you guys considered integrating real HTML/JS/CSS parsers?

**Comment by raisedadead** [comment]
@bcherny 
Not sure about removing the third test considering it says
> The finished input element should have valid syntax.

We could just modify the regex to be accepting white space.

Secondly about the JSON : 
The JSON is actually "seeded" into a database (currently mongodb), and pulled out whenever a challenge is requested. This may seem weird a bit, but is actually the architecture at FCC (which I admit is a bit complex)

For instance at the time of this comment 410 challenges are there in the DB.
Its not like that we have 410 actual pages (views) in the code base, but the page is generated on the fly when client requests for it.

There are a few more technicalities, but that needn't be discussed on this thread.

And yeah sadly we do not have very robust code interpreters because we are limited by the browsers engines to evaluate the code. Trust me the community has checked through various possible solutions, and what we have now as the infra is the best fit.

We are open to integrate any proven solutions though, but I am afraid that's not happening any time soon.

**Comment by bcherny** [comment]
> We could just modify the regex to be accepting white space

@raisedadead - we could definitely modify the regex, but what I'm trying to say is that after looking over your tests, I noticed that the 3rd test is redundant. If the input element isn't valid, the first 2 tests wouldn't pass anyway. So the 3rd test is just throwing false negatives, and isn't really testing anything.

> The JSON is actually "seeded" into a database (currently mongodb), and pulled out whenever a challenge is requested. This may seem weird a bit, but is actually the architecture at FCC (which I admit is a bit complex)

That's fine, what I'm suggesting is we find a better way of validating test cases. Currently, you are using regexes (instead of a parser) embedded in JavaScript which you then stringify and store in a mongo document. You then fetch it and eval it when you need to validate something. That's not a great design for a bunch of reasons, and seems pretty hacky to me. I'll think about it and see if I can propose a concrete alternative in a separate issue.

> And yeah sadly we do not have very robust code interpreters because we are limited by the browsers engines to evaluate the code.

You don't need a custom interpreter (though you should consider using one for security), just a parser. There's no reason either one couldn't run in the browser.

**Comment by raisedadead** [comment]
@bcherny Thanks. 

Yes the third is redundant, but does removing it address the issue that's in discussion on this thread?
i.e
> This seems like a legitimate bug - spacing shouldn't matter when parsing HTML.

So my suggestion to anyone looking to fix this :
* _Update the third test case to allow for the white space in the HTML while maintaining validation of the tags like completions, etc._

Yup It would be awesome if you open a separate issue for the architecture related stuff (although we would madly fall in love with you if you submit a PR :wink: ).

**Comment by bcherny** [comment]
> Yes the third is redundant, but does removing it address the issue that's in discussion on this thread?

If we remove the 3rd test case, the issue will be fixed, no?

**Comment by raisedadead** [comment]
> If we remove the 3rd test case, the issue will be fixed, no?

No it wont.

Refer :
![image](https://cloud.githubusercontent.com/assets/1884376/15019379/78bc3e2a-123b-11e6-984f-745034499c97.png)

That's why I mentioned 
> _Update the third test case to allow for the white space in the HTML while maintaining **validation of the tags like completions**, etc._

**Comment by raisedadead** [comment]
While you might argue that browsers auto complete tags, that's not a practice we would be willing to teach the campers. Hence tag completions need to be checked, at the minimum.

**Comment by bcherny** [comment]
@raisedadead Ah, now I see what you mean! The 3rd test is supposed to test that the `<input>` uses valid markup, but just the fact that it renders and `$('input').length > 0` is true doesn't mean that it has valid markup, since the browser has some intelligence around fixing invalid code.

> While you might argue that browsers auto complete tags

This is what was tripping me up. I think the word you're looking for is "close", not "complete". "Autocomplete" usually refers to code completion in your editor (or in devtools). "Closing a tag" refers to the `/ >` or `>` at the end of an HTML tag.

I'll put up a PR tonight!

**Comment by raisedadead** [comment]
Yup, I stand corrected on that. :sweat_smile: 
Thanks a lot for contributing, looking forward to the PR!

Happy fixing!

**Comment by UsamaHameed** [comment]
Hi there! I ran into the same bug. My screen size in 1080p. When I re-sized the browser, the area became clickable. I think there is some issue with the <html> tag height that was set while coding this challenge.

**Comment by esaky** [comment]
Hi guys,
The error came for me too. I just tried and changed the cat url ".jpg"
Now the "The finished input element should have valid syntax." is good.

but the second one "add cat url" is showing error !
![freecodecamp](https://cloud.githubusercontent.com/assets/10112128/21584015/948ca6bc-d0bd-11e6-8810-45af3e523094.PNG)

if we added the default code: "<input type="text" placeholder="https://bit.ly/fcc-relaxing-cat">"

it shows the same error you guys mentioned !

**Comment by esaky** [comment]
The code is working now.
![freecodecamp1](https://cloud.githubusercontent.com/assets/10112128/21584059/41f53462-d0bf-11e6-87de-f6425ec2d3cb.PNG)

We thought to add the cat url in that placeholder, but then i added the text"cat photo url". and it shows good in all three.

am i right - or still it's a buggy.

Advise me !

**Comment by dflostrife** [comment]
Hello I'm having an issue with this too  
![placeholder](https://cloud.githubusercontent.com/assets/27922377/25318182/fecdcb26-284e-11e7-87f3-a5afccc8fd0a.jpg)
