### ISSUE TITLE
No boarder radius, but still able to move on. 

### ISSUE THREAD

**Issue by wdquirk** [FreeCodeCamp/freecodecamp#848]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

My code seems to be correct and I am able to move on in the challenge even through the image is not rendering with a border radius.

![image](https://cloud.githubusercontent.com/assets/10089027/8017014/bf086586-0ba0-11e5-897a-2bfe9e1dca6c.png)

**Comment by treece** [comment]
Hey @wdquirk, I see why the border-radius isn't rendering for you :P You have a `:` colon at the end of your border-radius line and it should be a `;` semicolon. If you fix that then the border radius should render correctly. The reason why it still passed is because FCC has a loose matching system which is how it's intended to work. Thanks!

**Comment by wdquirk** [comment]
Looks like a n00b mistake to me! Thanks for the reply.

WQ

**Comment by QuincyLarson** [comment]
@treece thanks for catching the typo and @wdquirk thanks for submitting the issue anyway. Please always err on the side of submitting an issue. I'm happy to address false positives all day if it means I also fix some true positives.
