### ISSUE TITLE
The term 'encode' is obtuse -- Escape Sequences in Strings

### ISSUE THREAD

**Issue by hyperfilament** [FreeCodeCamp/FreeCodeCamp#8554]
The exercise Escape Sequences in Strings has the following instructions:

_'Encode the following sequence, separated by spaces:
backslash tab tab carriage-return new-line and assign it to myStr'_

The first time I read this I had zero idea what was being asked of me. Why would you ever use the word encode here unless you were purposefully trying to confuse? At this point in the course your user is someone who has yet to build a working function from scratch. Something like this is more readable and clear:

_'Assign the following sequence of escapes to myStr with separating white-space but no commas:
backslash, tab, tab, carriage-return, new-line'_

But even then having two tabs back to back is weird and looks like a typo. This whole challenge might make more sense as a two or three sentence paragraph the student has to assign to myStr using the various escapes they've just been introduced to.

**Comment by raisedadead** [comment]
Refer [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8555#issuecomment-218276739).

Please provide issue details.

**Comment by sludge256** [comment]
I think modifying the challenge to have a more "real world" problem would be a good idea. It's currently pretty abstract since the escape sequences are not used in combination with any text. The output box also only shows the text that the camper types in and doesn't show any of the formatting that the escape sequences would create. Campers might not internalize what they've learned as a result of this.

I am not sure where I stand on "encode" vs "assign" though. I don't think that "encode" is obscure/obtuse enough to cause issues.
The problem I see with using "assign" is that campers will potentially assume that the text proceeding the semicolon are the escape sequences themselves. This is a fairly common help issue with this challenge whereas, I don't think I've fielded any questions as to what "encode" means.

**Comment by erictleung** [comment]
I'm for a more "real world" problem for this challenge. Here's a draft string and instructions:

>  **Instructions**
>  
> Assign the following two lines of text into the single variable `myStr` using escape characters:
> 
> ```
> Here is a backslash: \.
>         Here is a new line with two tabs.
> ```
> 
> The string you need to encode is the following:
> 
> Here is a backslash: `backslash``backslash`.`newline``tab``tab`Here is a new line with two tabs.

Too hard? Too confusing?

**Comment by raisedadead** [comment]
Agreed.

**Comment by dabulo90** [comment]
you guys Im stuck at this challenge I just dont get what Im supposed to be doing  is it 
var myStr=" \\ \t \t \r \n" or  can you please help @raisedadead

**Comment by raisedadead** [comment]
Hi @dabulo90 , I am afraid you would have to consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

**Comment by dabulo90** [comment]
owk mate


On Fri, Jun 17, 2016 at 4:53 PM, Mrugesh Mohapatra <notifications@github.com
