### ISSUE TITLE
Typo in Accessing Objects Properties with Variables

### ISSUE THREAD

**Issue by elazzabi** [FreeCodeCamp/FreeCodeCamp#8626]
#### Accessing Objects Properties with Variables
https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description
There is a typo in the challenge Accessing Objects Properties with Variables.
```
var myDog = "Hunter";
var dogs = {
  Fido: "Mutt",
  Hunter: "Doberman",
  Snoopie: "Beagle"
}
var breed = dogs[myDog]; // "Hunter"
console.log(breed)// "Doberman"
```
In the line
```
var breed = dogs[myDog]; // "Hunter"
```
breed's value is "Doberman" and not "Hunter"

I can make a PR to correct this. Waiting green light...

**Comment by raisedadead** [comment]
```
var breed = dogs[myDog]; // "Hunter"
```
> breed's value is "Doberman" and not "Hunter"

I am afraid its actually correct correct, not sure if this is confusing though.
the comment `// "Hunter"` is meant to say that `myDog is equal "Hunter"`

Yeah, bit confusing.

/cc @erictleung what do you feel?

**Comment by elazzabi** [comment]
In the same page there is:

var someProp = "propName";
var myObj = {
  propName: "Some Value"
}
myObj[someProp]; // "Some Value"

We need a unification in this case

**Comment by raisedadead** [comment]
Yeah @elazzabi I agree, that's the confusion. :sweat_smile: 
I am in for of removing the comment `// "Hunter"`

But lets wait for @erictleung to confirm.

**Comment by erictleung** [comment]
Yeah, it is a bit confusing the more I looked at it. I feel that @raisedadead's suggestion (removing the comment `// "Hunter"`) is good and fairly clear on what it is saying. So go ahead @elazzabi if you want to make a PR for this 👍 

The `var breed = dogs[myDog];` I feel was added (despite being inconsistent) because of what the instructions ask for. Ah and with a quite GitHub search, I found the discussion on where this was added, in case you want to accommodate for other students' struggles #6112.
