### ISSUE TITLE
Exact change - insufficient funds?

### ISSUE THREAD

**Issue by chrysemis** [FreeCodeCamp/FreeCodeCamp#8657]
I'm not sure how to describe this but I wonder if there is an issue with the exact change advanced algorithm? In one of the examples, it should return "insufficient funds" when there is enough change in drawer. 
Here is the example: 
checkCashRegister(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return "Insufficient Funds".

However, it seems that we need change 0.50, and there is 1.00 in ONES and 0.01 in PENNYs...sure that should be enough?

**Comment by nishant-tomer** [comment]
@chrysemis  Yes. Funds are sufficient but you still cant give the change back as you only have a full Dollar and single Cent. How are you going to give 50 cents or 2 quarters or 5 dimes or 10 nickels?

Also yes ,Instructions could have been clearer and anybody could think its a bug but this is not a proper bug and shouldn't have been reported here. 
All coding related help can be found at FreeCodeCamp Help rooms [here](https://www.freecodecamp.com/wiki/en/official-free-code-camp-chat-rooms/)

Keep it up, Happy coding.

**Comment by marisamartinez** [comment]
Stop

@!LATINY!@

**Comment by chrysemis** [comment]
Thanks, I indeed thought it might have been a bug.

**Comment by AdventureBear** [comment]
I'm glad this was reported as a bug because I also was stuck on the same issue. Sometimes when we are thinking within a set of parameters or solving a problem, we fail to see other aspects of the solution.  I probably would have figured this out as I solved the other test case where I had to change my answer to give 6 twenties instead of 8 twenties...but I'm glad that this issue was reported so it can be searched.  Help rooms do not allow for searching of issues this way.  @chrysemis  thank you for reporting it.  Good use of the bug feature in this case.
