### ISSUE TITLE
addTogether - error

### ISSUE THREAD

**Issue by Mason-Rojik** [FreeCodeCamp/FreeCodeCamp#8664]
When I run Test, an error is generated, "TypeError; addTogether(...) is not a funciton"
Challenge [Arguments Optional](https://www.freecodecamp.com/challenges/arguments-optional#?solution=%0Afunction%20addTogether()%20%7B%0A%20return%20false%3B%0A%7D%0A%0AaddTogether(2)(3)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function addTogether() {
 return false;
}

addTogether(2)(3);

```

**Comment by erictleung** [comment]
@Mason-Rojik the error message is telling you what is wrong (albeit a little nuanced). It is saying that `addTogether(...)` is not a function. This is because you called `addTogether(2)(3)`, where the JavaScript interpreter is assuming that `addTogether(2)` is your function being called on 3 (i.e. `addTogether(...)(3)`), which doesn't exist.

If you get stuck with a challenge or have initial questions, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) first. Happy coding!

**Comment by Mason-Rojik** [comment]
Could you expand? You explanation is not making sense to me. And yes, I have been to gitter, it’s a real hit and miss if someone answers a question, so then I have to submit a bug because I just don’t know if it is or not.

 

Thanks again.

**Comment by erictleung** [comment]
@Mason-Rojik this [link](http://www.drdobbs.com/open-source/currying-and-partial-functions-in-javasc/231001821?pgno=2) may help. What you have tried to do is called currying.

Yeah, Gitter can be overcrowded sometimes. You just have to be persistent. Tag me in Gitter if you still don't understand currying and we can discuss there if you need more explanation. Good luck!
