### ISSUE TITLE
The later challenges in learnyounode (challenge 10 onwards) do not work on C9 due to port restrictions. 

### ISSUE THREAD

**Issue by lcarbonaro** [FreeCodeCamp/FreeCodeCamp#8680]
Challenge [Finish working with Nodejs Servers](https://www.freecodecamp.com/challenges/finish-working-with-nodejs-servers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by raisedadead** [comment]
Thanks for reporting @lcarbonaro.

/cc @alayek and we were discussing a couple of days ago about [workshopper](https://github.com/workshopper/workshopper)s like these, tend to have their challenges (breaking frequently) especially on cloud IDEs, due to obvious restrictions.

This is in addition to already somewhat broken how-to-npm workshopper.
Refer #7080

@FreeCodeCamp/issue-moderators thoughts?

**Comment by lcarbonaro** [comment]
At the very least there should be a note against those particular
challenges to alert people that this won't work on C9, and not because
something is wrong in their code necessarily.

**Comment by alayek** [comment]
Thanks for notifying me @raisedadead. @koustuvsinha you might be interested.

One solution could be that we fork those repos and update these features so that they work on c9. Or, we make sure they at least work on our vagrants, without altering the node modules.

Sure, this is like biting off more than one can chew. But I cannot come up with anything better right now :santa:

**Comment by theoneinskane** [comment]
@alayek  and @raisedadead, @jnmorse suggested a bit of a work around that might help when setting up in c9. I am going to test it in the next couple of days and see if it works for me! Will let you know the results and then maybe for now we could update the challenge instructions on FCC to include these preparation steps if they work?

**Comment by jnmorse** [comment]
@theoneinskane I think that using the blank workspace will also work, I didn't know if that would allow you to use node and npm at first, but seems it will.

I just tried and completed the challenges referenced in "[Finish working with Nodejs Servers](https://www.freecodecamp.com/challenges/finish-working-with-nodejs-servers)" at least in this manner.

![learnyounode](https://cloud.githubusercontent.com/assets/1467889/15539454/9bd6bffa-2250-11e6-9166-9d613fcb5835.png)

**Comment by hutstep** [comment]
I just finished learnyounode. No issues at all. Like @jnmorse suggested, and like I wrote here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7080#issuecomment-223046160 for the how-to-npm challenge, it works if you create your C9 workspace with a blank template and **not** a Node.js template.

![learnyounode](https://cloud.githubusercontent.com/assets/18348355/15794721/5fb45a60-29ed-11e6-86fb-2d75d993bc2f.png)

**Comment by raisedadead** [comment]
@lcarbonaro @jnmorse thanks a lot. Looks like we can update the instructions to reflect the same.

**Comment by raisedadead** [comment]
@hutstep thanks a lot for the workaround, would you be interested in making a PR for both the challenges and update the instructions?

**Comment by hutstep** [comment]
@raisedadead ok, will do it for both challanges.
