### ISSUE TITLE
Comment your JavaScript Code fails with Unsafe error when we have function word in comment.

### ISSUE THREAD

**Issue by jkannan** [FreeCodeCamp/FreeCodeCamp#8774]
Challenge [Comment your JavaScript Code](https://www.freecodecamp.com/challenges/comment-your-javascript-code#?solution=%20%2F%2FThis%20line%20will%20be%20ignored%20function%20by%20Java%20Script%0A%0A%2F*%20This%20is%20a%20multi-line%20comment%20in%20%20%0A%20%20%20%20for%20documenting%20the%20functio%20behaviour.%0A*%2F%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
 //This line will be ignored function by Java Script

/* This is a multi-line comment in  
    for documenting the functio behaviour.
*/

```

The test is throwing the following error.When we have a comment with the word function in it.
e.g
//This line will be ignored _function_ by Java Script.

Error: SyntaxError: Unsafe or unfinished function declaration

**Comment by DealPete** [comment]
In "client/commonFramework/detect-unsafe-code-stream.js" we have
if (
   code.match(/function/g) &&
   !code.match(detectFunctionCall)
) {
   return Observable.throw(
      new Error('SyntaxError: Unsafe or unfinished function declaration')
   );
}

where detectFunctionCall = /function\s*?\(|function\s+\w+\s*?\(/gi;

So anytime the word "function" appears in your code without an open parenthesis after it, you'll get the above error.
I don't see how this makes your code any safer, since if you really had an exploit that used the naked word "function", you could easily get around this check by putting the string "function(" in a comment above it.

**Comment by BerkeleyTrue** [comment]
This challenge does not require writing the word `function` into a comment. Seeing how this is an old challenge and this is the first time someone opened an issue for this, does this require a fix?

**Comment by DealPete** [comment]
It's certainly a low priority, but it's a strange behavior of the code runner that could confuse someone.

**Comment by jkannan** [comment]
Agree it is a low priority. But it certainly is an issue. Specially for a beginner taking this course he/she has no way of identifying the cause of the issue.  Even though the challenge does not require writing the word function. It is natural to describe the behaviour using the word function. If not a code fix I think we should have a note saying do not use the word function in comment. Thanks.

**Comment by BerkeleyTrue** [comment]
Someone will need to come up with some regex magic ✨  to get this fixed.
