### ISSUE TITLE
Caesars Cipher's check is not complete

### ISSUE THREAD

**Issue by Pagise** [FreeCodeCamp/FreeCodeCamp#8797]
The challenge ONLY checks for uppercase letters, while the cipher should check for uppercase AND lowercase letters. This caused me to finish the challenge without actually having a solution that would work for lowercase as well... Since the uppercase letters come with numbers that are lower than the lowercase numbers, my first solution would be sufficient, but it wouldn't work for the lowercase numbers. The lowercase numbers would substract 26 and then end up as an uppercase number, while the ROT13 doesn't work that way..... So please fix the challenge, so that it also checks for lowercase characters... Thank you.

**Comment by erictleung** [comment]
@Pagise thanks for the feedback. The challenge specifically asks for uppercase letters so there is no inconsistencies with the tests. 

> All letters will be uppercase. Do not transform any non-alphabetic character (i.e. spaces, punctuation), but do pass them on.

However, even though I think it would be great to ask to make a function to take both uppercase AND lowercase letters, I believe constraining the challenge to just uppercase letters provides a good basic algorithm scripting challenge. So I think the challenge can stay as is.

cc/ @FreeCodeCamp/issue-moderators second opinions?

**Comment by SaintPeter** [comment]
When I wrote the challenge I made a specific decision to keep it all uppercase because I believe it made the problem easier to solve.  At the time it was not an Algorithm challenge, but a "Checkpoint" - it was actually part of the basic JS curriculum.

While I could see making the challenge more difficult and forcing both upper and lowercase . . . but I don't see too much point in that.  Once you've solved it for one case, it's practically cute-and-paste to solve it for the other case.

As @erictleung pointed out, it explicitly says "All letters will be uppercase".  Reading the instructions is an important programming skill as well.

**Comment by hallaathrad** [comment]
Whereas the challenge could indeed include lowercase, I do agree on that the point is not to add complexity but to show capabilities of the tools being taught. 'Aye' to not fixing what isn't broken.

**Comment by erictleung** [comment]
@Pagise thanks again for the feedback but it appears we have agreed that this challenge is fitting enough for where it is in the curriculum. 

But by no means should you feel limited to just Free Code Camp's curriculum requirements. Feel free to implement the cipher that accepts upper and lowercase text as an extra challenge 😃  Happy coding!

**Comment by Pagise** [comment]
Thank you all for the feedback. As SaintPeter said: "As @erictleung pointed out, it explicitly says 'All letters will be uppercase'. Reading the instructions is an important programming skill as well."
I apologize for not reading the instructions as intended...

Yes, the challenge is good enough as it is for the basic algorithm scripting challenge..
Again, thank you all for the feedback!
