### ISSUE TITLE
Understand String Immutability: The objectives are not displayed

### ISSUE THREAD

**Issue by aifrak** [FreeCodeCamp/FreeCodeCamp#8835]
Understand String Immutability

https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%5B0%5D%20%3D%20%22Hello%20World%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A

The objectives are not displayed after the page is loaded. I tried to clear the browser cache but it has no effect (see picture). But if the challenge is completed, then the objectives are displayed correctly.

* Chrome, Version 50.0.2661.102 m (64-bit)
* Windows 7 64 bits
* Desktop

![bug](https://cloud.githubusercontent.com/assets/16720672/15626527/ebb6fb66-24c6-11e6-9977-ab88eeecfebc.jpg)

**Comment by atjonathan** [comment]
Source: https://www.freecodecamp.com/challenges/understand-string-immutability
> For example, the following code:
```js
var myStr = "Bob";
myStr[0] = "J";
```
cannot change the value of `myStr` to "Job", because the contents of `myStr` cannot be altered. Note that this does not mean that `myStr` cannot be changed, just that the individual characters of a `string literal` cannot be changed. The only way to change `myStr` would be to assign it with a new string, like this:
```js
var myStr = "Bob";
myStr = "Job";
```

Please read the challenge description before submitting an issue.
Use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by bugron** [comment]
@aifrak in this case that's because your code crashes our test suite because `myStr[0] = "Hello World"` generates a `TypeError`.

**Comment by aifrak** [comment]
I could solve this challenge but what I wanted to mean is that the red crosses are not displayed at the bottom when the page is loading. Normally red crosses and green symboles are 
displayed at the bottom of each challenge.

OK (example of another challenge): 
![ok](https://cloud.githubusercontent.com/assets/16720672/15626675/41f90470-24cb-11e6-95f0-0e198bb9befb.JPG)

Failed and completed objectives missing:
![bug](https://cloud.githubusercontent.com/assets/16720672/15626677/51a7f1b0-24cb-11e6-890d-8b31e30d5d40.jpg)

**Comment by HNhung05** [comment]
You fix your code to :  // Setup
var myStr = "Jello World";

// Only change code below this line
myStr= "Hello World"; // Fix Me

**Comment by texas2010** [comment]
@HNhung05 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
