### ISSUE TITLE
Bonfire TitleCase

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/freecodecamp#886]
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. 

The instructions are not clear as to what your asking for when running code. I wrote my code to what the initial instructions asked for. However, when running my code i find that what i wrote is not what you were wanting. [See Screenshots]  If you wanted to test each character, those strings should have been added into your bonfire start code, so that we know exactly what your looking for in the code. After spending time working on my code and getting it to work for what was initially asked for, i find its not even correct to what is being requested. Please, if you are looking to check more strings to see if the code works, either be more clear of instructions or provide them within the starter code so we can see what is being looked at. 
![bonfire](https://cloud.githubusercontent.com/assets/10119077/8081650/355cbb8a-0f3c-11e5-93ef-6af8b7e8bce7.PNG)
![bonfire2](https://cloud.githubusercontent.com/assets/10119077/8081655/38811a18-0f3c-11e5-95d1-1560c162b77f.PNG)
![bonfire3](https://cloud.githubusercontent.com/assets/10119077/8081658/3aee66fc-0f3c-11e5-8da0-ddd8db15ac62.PNG)

**Comment by terakilobyte** [comment]
Many of the bonfires include test cases that provide the data in different ways to make the programmer think about various things they may not have initially considered in their haste to smash the problem. It's simply impractical for us to include all of those in the initial instructions since space is limited, but very easy for the user to run the code on an empty bonfire to see all the test cases. This is desired so people become very familiar with test syntax.

**Comment by terakilobyte** [comment]
I've given this some more thought while at work today. @GhostParticle I think it's kind of infeasible to include all test cases in the description, but would a link to our definition of what title casing is help address the issue? http://www.grammar-monster.com/lessons/capital_letters_title_case.htm

**Comment by LumenTeun** [comment]
@terakilobyte You're not looking for that sort of Title Case though, you still want in-between words like 'and' to be capitalized. If you add the link as a clear definition, the test cases need to be changed.

**Comment by brandenbyers** [comment]
@GhostParticle what if we switched out "a" for "the" in the first sentence so that it reads as, "Return a provided string with the first letter of each word capitalized."? The entire point of this challenge (and most of the others) is to write a function that will provide expected results no matter what the given input is.

For example, if I only needed to make this function work for the string in the initial code block, then I could just as easily write a pointless function that only does one thing:

```
function titleCase(str) {
  return "I'm A Little Tea Pot";
}

titleCase("I'm a little tea pot");
```

As @terakilobyte says, part of the learning comes from running the tests and seeing what fails. You don't need to write any code before you can run the tests. The failing tests will elaborate on what is required. But my recommendation is to not only write to pass the tests. While you're at it, try to cheat the tests. See if you can write a function that allows something to slip by and pass that the tests didn't catch (and then submit a PR so these tests can better for the next person). Ideally, we should be able to throw any possible string at your function and it will successfully title case the input.

As is, these tests are pretty basic. They aren't requiring that you cover all edge cases. But that doesn't mean you can't do so yourself. Ask yourself what would happen in your function if the string input were any of the following:

```
""
"i"
".this .is .a .sentence .with .incorrect .punctuation"
"A A A"
"1ove"
```

Also, @terakilobyte like @lumenTeun pointed out, I don't think that specific link will work since we need a title case that capitalizes all letters including "a" and "the." As far as I know, it is not technically a grammar style (at least not AP or Chicago). Here is a simple link for those styles though: http://titlecapitalization.com/

**Comment by dfm212** [comment]
You need to set <-- Just! --> the first letter "toUpperCase" and rest of the letters "toLowerCase". your code is doing right the first part but you are missing the rest.

![untitled-1](https://cloud.githubusercontent.com/assets/12265982/8635137/e130bdce-27df-11e5-8a1c-ad504b0aa7d8.png)
