### ISSUE TITLE
Error in starting local instance of FCC

### ISSUE THREAD

**Issue by dakshshah96** [FreeCodeCamp/FreeCodeCamp#8875]
#### Issue Description

I've been trying to [run a local instance of FreeCodeCamp as described here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started). However, I get an error when I write `gulp` i.e., the last step. Screenshot for the same has been attached below.

IMO, this is a bug with the way I've named one of the folders where the FreeCodeCamp repository is stored. See the line `/Users/dakshshah/Documents/Work/Git: No such file or directory`. The error is encountered exactly where there is a space in the folder name.

Is anyone else able to reproduce the same error?

#### Screenshot

<img width="682" alt="screenshot 2016-05-31 21 28 10" src="https://cloud.githubusercontent.com/assets/7896438/15686089/617dfaae-2777-11e6-8be0-5ca9b316fd3f.png">

**Comment by erictleung** [comment]
@dakshshah96 it looks like it is trying to access `/Users/dakshshah/Documents/Work/Git Works/FreeCodeCamp/...` but that `.../Git Works/...` part is probably throwing it off because it things you listed two directories. It should be `.../Work/Git\ Works/FreeCodeCamp/...`. To fix it, you can try renaming your directory as `Git-Works` or `Git_Works` so it can read the complete path of your directory.

**Comment by dakshshah96** [comment]
Thanks @erictleung!

Just curious though, folder names with spaces not working, is that a problem with FreeCodeCamp or some other module?

**Comment by raisedadead** [comment]
@dakshshah96 almost all of the code for FCC depends upon some or the other node module, it could be any dependency that may or may not be supporting spaces in the path, nevertheless this sure looks like the `nodemon` is  not working somehow with spaces.

You can isolate the trouble by directly running `node server\debug-entry.js`. If it still throws errors then we may have something to be concerned about. Else its just specific to your environment.
Warning : The above is not a workaround and just a debugging step, because ultimately you would need `gulp` to build everything.

We haven't seen any reports of any breaks in recent past on build environments.

P.S : If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
