### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by esiewwfashion** [FreeCodeCamp/FreeCodeCamp#8887]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by esiewwfashion** [comment]
Get help starter

**Comment by erictleung** [comment]
@esiewwfashion thanks for the issue but if you get stuck with a challenge or need help, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). If you are still having issues, please fill out the issue form with as much detail about your problem so that we can help. Happy coding!
