### ISSUE TITLE
Audit MDN links for correctness

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8888]
#### Challenge Name

Select challenges (e.g. https://www.freecodecamp.com/challenges/confirm-the-ending)

#### Issue Description

In a previous issue #6913, we came to the conclusion that we should change `String.charCodeAt()` to `String.prototype.charCodeAt()`.

> "The MDN links are links to documentation. Obfuscating what documentation is being linked to behind 'friendly' syntax is doing a disservice to students. Part of programming is learning how to search docs. Knowing that the chatCodeAt method is a part of String.prototype is both correct and teaches the student how to search for information when it's not provided to them. Making up proprietary ways of linking to prototype methods is confusing and not helpful in the long run." 
> -- @ltegman 

For consistency, we should look through the other MDN links and change them to their appropriate links.

In the challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending), it suggests to use the `String.substr()` method but it should be suggesting `String.prototype.substr()`.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15700816/396ccba8-278b-11e6-9411-3b1686a14a4f.png)

**Comment by Bouncey** [comment]
I can't recall ever inserting `prototype` into a method unless I was adjusting an Object prototype. Would this `String.prototype.sunstr()` be best practise? 

If so then we should be promoting best practise all round.

**Comment by ltegman** [comment]
@erictleung Woot! As my quoted comment suggested, I'm all for this.

@Bouncey Prototype methods are methods that are inherited by every instance of a String through [prototypal inheritance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain). The reason the MDN docs are structured this way is because something that is a method of the String object (like `String.fromCharCode`) is called on the global String object, where prototype methods like `String.prototype.substr` are called on an instance of a string (how I'm sure you're used to using it).

I don't know how'd we'd do it (maybe the video lessons?) but I think a lesson on how prototypes work would definitely benefit the curriculum since it's so core to building a deep understanding of the JS language.

**Comment by erictleung** [comment]
@ltegman awesome! Just wanted to flag it as discussing temporarily to test the waters on whether this change is okay. I'll flag it as help wanted now.

**Comment by tianz** [comment]
Hi, I would like to help with this one!

**Comment by erictleung** [comment]
@tianz great! You'll need to go through the [`bonfireMDNlinks.js`](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/bonfireMDNlinks.js) file and change the values to match the correct JavaScript method. Usually, they are the titles for their corresponding MDN page, like so:

![image](https://cloud.githubusercontent.com/assets/2754821/15765803/b2a3cf9a-28ed-11e6-95da-f16d91d5476f.png)

Keeping track of the links you've changed, you'll need to search through the [`challenges/`](https://github.com/FreeCodeCamp/FreeCodeCamp/tree/staging/seed/challenges) directory and change the line of code to match your changes (for example, you'll change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L352) because `String.substr()` should be `String.prototype.substr()`)
