### ISSUE TITLE
Completing a waypoint advances to the wrong location on the map

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/freecodecamp#893]
Challenge http://www.freecodecamp.com/challenges/waypoint-understand-pseudoclassical-patterns has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

After completing this waypoint, clicking to advance to the next challenge led me to the wrong location three out of four times.

I first landed on Falsey Bouncer, then tested again and landed on Where Art Thou, and then Seek and Destroy. Finally on test number four, it took me to the right waypoint. The same behavior occurs after completing waypoint 9 under OO Javascript, also covering pseudoclassical subclasses.

**Comment by 1hella** [comment]
I've had this happen a few times as well. After completing a bonfire, it took me to an older bonfire – one that I did earlier in the day and hadn't clicked since. 

For me it happened when I clicked on a specific bonfire from the map, completed, then clicked next. It hasn't happened when I've done a few in a row I don't think.

**Comment by LumenTeun** [comment]
I usually advance using the Map instead of the Next button, but I have had this happen when opening multiple tabs of FCC. I'd assume that a value is replaced in storage upon entering a challenge, and that this is what's used to calculate where to go to when clicking 'Next'.

**Comment by 1hella** [comment]
@LumenTeun You're right.

Steps to reproduce:
1. Open a bonfire.
2. Open a different bonfire or waypoint in another tab.
3. Complete bonfire opened in step 1 and press 'Go my my next challenge'.
4. The challenge after the one opened in step 2 will be opened rather than the challenge after the one just completed.

**Comment by BerkeleyTrue** [comment]
This should be fixed when we switch over to loopback. Will keep you guys posted

**Comment by BerkeleyTrue** [comment]
Woops didn't mean to close

**Comment by BerkeleyTrue** [comment]
Fixed in beta.
