### ISSUE TITLE
Tests appear to be incorrect.

### ISSUE THREAD

**Issue by joesmith100** [FreeCodeCamp/freecodecamp#894]
Challenge http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I believe the tests are incorrect, if working off the number line examples provided in the math is fun link.

[ 1, 5 ] - This would equal 5, not 60.
1 2 3 4 5
            5
[ 5, 1 ] - This would equal 5, not 60. 
1 2 3 4 5
            5
[ 1, 13 ] - This would equal 13, not 360360. 
1 2 3 4 5 6 7 8 9 10 11 12 13
                                          13
Unless I am missing something?

**Comment by LumenTeun** [comment]
Sorry to say it, but you are missing something. The bonfire wants you to find the smallest possible number that can be divided by the numbers between the array members.
[1, 5] would equal to 60 because 60 is the first number, counting from 0 up, that can be divided by 1, 2, 3, 4 and 5.

I too found the description rather vague, and started coding on something completely different before figuring out what they really wanted. Maybe this issue should address that and be renamed appropriately?

**Comment by joesmith100** [comment]
Ohhh, man I feel silly. I read that over and over again trying to figure it out. Thanks for the assist, guess I should have pasted in the chat room but I was so convinced it was wrong, silly me!

**Comment by LumenTeun** [comment]
If you rename the title to something like "SCM bonfire instructions needs to be clearer" then you could probably reopen this issue. Seems like quite a few have problems with this one.

**Comment by Hyllesen** [comment]
I had the same misunderstanding
