### ISSUE TITLE
Record Collection

### ISSUE THREAD

**Issue by Nisarg1792** [FreeCodeCamp/FreeCodeCamp#8941]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function updateRecords(id, prop, value) {
 if (value === ""){
    delete collection[id][prop];
  }
  else if ( value !== "" && prop !== "tracks") {
    collection[id][prop] = value;
  }
  else if (prop === "tracks") {
      collection[id].tracks.push(value);
  }
 
  return collection;
}
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/11726988/15790850/ce01bf54-29a1-11e6-853c-9b5e0c687bbc.png)

**Comment by erictleung** [comment]
@Nisarg1792 thanks for the issue but it is unclear on what your issue is. I'm assuming you are pointing out that your code didn't pass the second test. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: what happens when you push to a non-existent property. If this is not your issue, please comment back. Happy coding!
