### ISSUE TITLE
Pesky but professionalim is key...

### ISSUE THREAD

**Issue by gbsimon87** [FreeCodeCamp/FreeCodeCamp#8946]
Not sure if this is supposed to go here, but if not, we can always close the topic...

Challenge [Iterate with JavaScript For Loops]
(https://www.freecodecamp.com/challenges/iterate-with-javascript-for-loops) has an issue, well, typo.

It's really a pesky little thing, but considering I truly respect FCC, I felt the need to point it out as it is very fixable and helps keep professionalim at its highest level :)

"The condition statement is evaluated at the beginning of every loop iteration and will continue as long as it evalutes to true"

Should be, evaluates.  Small typo, but hey, support is support :)

Keep up the amazing work.

A grateful and satisfied FCC user.

```

**Comment by erictleung** [comment]
@gbsimon87 thanks for the support! We do try to keep things as great as possible. And you are correct, there is a typo.

If you or anyone else wants to take care of this issue, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4586) needs to be changed so that `evalutes` is changed to `evaluates`.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
