### ISSUE TITLE
Challenge [Modify Array Data With Indexes]

### ISSUE THREAD

**Issue by ArnoldLaishram** [FreeCodeCamp/FreeCodeCamp#8960]
(https://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray%5B0%5D%20%20%3D%203%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];
// Only change code below this line.
myArray[0]  = 3;

```
This is the challenge .

1. myArray should now be [3,2,3].
2. You should be using correct index to modify the value in myArray.

The first one is correct but the second one seems to be bug because i have given the correct index to achieve the first one.

**Comment by JacksonKearl** [comment]
The problem here is in the assert:
`assert((function(){if(code.match(/myArray\\[0\\]\\s?=\\s?/g)){return true;}else{return false;}})(), 'message: You should be using correct index to modify the value in [<code>myArray</code>.');`
At [https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1741](url)

The regex: `/myArray\\[0\\]\\s?=\\s?/g` is using `\s?` to allow for whitespace, when it should be using `\s*`. The `?` selects 0 or 1, whereas the * selects 0 or more. In your code, you have 2 spaces before the equals sign, which is breaking the check. Your code is fine, albeit not ideal/"lint free", but because the check wants specifically one space, thats your best bet for passing. I'm not sure if this is something I should submit a pull request for, so idk any other way for you to pass

**Comment by ArnoldLaishram** [comment]
Thanks Jackson. That just did the trick

**Comment by erictleung** [comment]
@ArnoldLaishram what @JacksonKearl says is correct. There is an issue with the test only checking for only one space.

@JacksonKearl I see you have referenced this issue with your changes. You'll need to make a pull request on the main repo. Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by pleabargain** [comment]
still having problems with whitespaces:
**fails**
`myArray [0] = 3;`
**passes**
`myArray[0] = 3;`

MDN has plenty of examples where whitespaces are NOT penalized:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

thank you
