### ISSUE TITLE
just a typo, not a bug

### ISSUE THREAD

**Issue by garcia223** [FreeCodeCamp/FreeCodeCamp#8961]
"Your body element should have an black background." doesn't need to be typed as "an"

Challenge [Use RGB values to Color Elements](https://www.freecodecamp.com/challenges/use-rgb-values-to-color-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: #F00;
  }
</style>

```

**Comment by erictleung** [comment]
@garcia223 thanks for catching this!

For anyone wanting to fix this, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4535) needs to be changed so that `an black background` should be `a black background`.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by manshantsingh** [comment]
Well this would be my first time contributing and I want to try this @erictleung.

**Comment by erictleung** [comment]
@manshantsingh go for it! 👍  Let us know through the chat room if you need any help.
