### ISSUE TITLE
Uncomment HTML Bug

### ISSUE THREAD

**Issue by ZGran** [FreeCodeCamp/FreeCodeCamp#8966]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by tjgerot** [comment]
Your issue is simply a post of the contribution template. To submit an issue, fill out the fields in the issue template to provide some details on the issue you are experiencing. For help on this, please take the time to reference [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). Thank you!

**Comment by erictleung** [comment]
@ZGran please describes your bug in more detail so that we may investigate it.

**Comment by erictleung** [comment]
@ZGran closing as stale. Please describe in more detail if you are still having an issue. Happy coding!
