### ISSUE TITLE
Bug Report: FreeCodeCamp : Build a JavaScript Calculator

### ISSUE THREAD

**Issue by tanyagupta** [FreeCodeCamp/FreeCodeCamp#8981]
#### Challenge Name
https://www.freecodecamp.com/challenges/build-a-javascript-calculator
Code pen link: https://codepen.io/FreeCodeCamp/full/PNKdjo/

#### Issue Description
Test case 5+5=+5 should be 15. Shows 5 instead

#### Browser Information
Chrome Version 51.0.2704.79 (64-bit)
OSX El Capitan
Desktop

#### Your Code
n/a

// If relevant, paste all of your challenge code in here

```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by arun1595** [comment]
@tanyagupta When you enter "=", the result of the previous expression is not persisted. 
When you enter +, it knows nothing of the first operand because it doesn't even exist. After that, when you enter 5, you get 5 because its the same as adding 0 + 5. 

Now, you have identified a bug for which the given pen breaks. Keep this in mind and when you develop your own calculator, make sure that you don't get that issue.
PS: I didn't look at the code. I was just playing with the calculator to find the bug.

**Comment by raisedadead** [comment]
Hi I think that the previous result is fetched by using the 'Ans' button, not sure if this is expected, but if anyone has any better thoughts and a codepen to demonstrate then we could use that as well.

Thanks for reporting.

/cc @FreeCodeCamp/issue-moderators

**Comment by SamAI-Software** [comment]
There are different variations of calculators with different functionality and logic.

> Test case 5+5=+5 should be 15. Shows 5 instead

Google Calculator (browser version) shows `10 + 5`
Windows Standard Calculator shows `5` ([here is a check-list](https://github.com/SamAI-Software/test-ur-calc))
[Latest FCC calculator](https://codepen.io/FreeCodeCamp/full/rLJZrA/) shows `5` (same like Windows' calc)

So it's not a bug, it's just a different logic. For more information you can also read [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6130#issuecomment-236822303).
