### ISSUE TITLE
Finding a Remainder in JavaScript

### ISSUE THREAD

**Issue by Mojibul** [FreeCodeCamp/FreeCodeCamp#9001]
Challenge [Finding a Remainder in JavaScript](https://www.freecodecamp.com/challenges/finding-a-remainder-in-javascript#?solution=%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20remainder%3B%0Aremainder%20%3D%2011%20%25%203%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Only change code below this line

var remainder;
remainder = 11 % 3;


```

**Comment by erictleung** [comment]
@Mojibul this error has been fixed with #8958. It still needs to be pushed to the live site. In the meantime, you can complete the challenge by putting everything onto one line. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by Mikaykay0330** [comment]
How do you do this?

**Comment by xavierlopez317** [comment]
mute

gmail

On Mar 30, 2017 1:45 PM, "Mikaykay0330" <notifications@github.com> wrote:

How do you do this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/9001#issuecomment-290523139>,
or mute the thread

**Comment by texas2010** [comment]
@xavierlopez317 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
