### ISSUE TITLE
Misguiding lesson: Create a Set of Checkboxes

### ISSUE THREAD

**Issue by pribilinskiy** [freeCodeCamp/freeCodeCamp#9015]
Challenge [Create a Set of Checkboxes](https://www.freecodecamp.com/challenges/create-a-set-of-checkboxes) has an issue.

My code:

``` html

  <label><input type="checkbox" name="personality" id="">humorous</label>
  <label><input type="checkbox" name="personality" id="">kind</label>
  <label><input type="checkbox" name="personality" id="">smart</label>

```

It's a nonsense to create input fields of type `checkbox` with same `name` attribute value, e.g. checking all of them would make up a query string in form:

```
?personality=on&personality=on&personality=on
```

It's kinda useless, unless the checkboxes are managed with `javascript` like in [this fiddle](http://jsfiddle.net/62f3X/1/)

I suggest in this lesson to add checkboxes with different `names` and add note that each checkbox should have distinctive `name` unless altered with JS

**Comment by crashuniverse** [comment]
I just completed this exercise and I think what @pribilinskiy says is correct. Usage of nonsense is somehow a very strong word and can be refrained in future. Because duplicate name attribute is not a useful repetition, but it is valid html. 

I propose the following enhancement:
1. The set of checkboxes should go from 3 checkboxes to 2 checkboxes. To condense the learning. It can be 1 too, for sake of correctness above volume.
2. Each of 2 checkboxes should have a unique `name` attribute. We can suggest those names to be loving and funny (funny chosen carefully from [a cat top 20 qualities website](http://www.lovemeow.com/top-15-cat-qualities-1607997052.html))
3. Change instructions:
    - All related checkbox inputs should have a unique name attribute.
    - Add to your form a set of 2 checkboxes. Each checkbox should be nested within its own label element. Both should have a unique name attribute.
4. Modify underlying logic for test 4 to: Give your checkboxes a unique name attribute of loving and {funny}.

**Comment by pribilinskiy** [comment]
@crashuniverse ahh, don't mention it )
I've just started the curriculum and it was a bit odd that multiple checkboxes are taught to be used with same name and decided to make the effort and open an issue and discuss with whoever is interested on this topic.

It turns out that in the examples at the ["famous" w3schools.com](http://www.w3schools.com/tags/att_input_checked.asp) and [webplatform.org](https://docs.webplatform.org/wiki/html/elements/input/type/checkbox) the checkboxes are also have same `name` attributes :grinning:

**Comment by QuincyLarson** [comment]
@crashuniverse @pribilinskiy If you think this is suboptimal or a bad practice, would one of you be interested in updating the challenge?

**Comment by dribeiroferr** [comment]
Hey, 
I already took that lesson and had searched almost everywhere, and I found a solution for this: 

    <label for="loving"><input type="checkbox" id="loving" name="personality">loving
    </label>
        <label for="funny"><input type="checkbox" id="funny" name="personality">funny
    </label>
        <label for="cuddly"><input type="checkbox" id="cuddly" name="personality">Cuddly
    </label>

Hope that could be useful ;)
