### ISSUE TITLE
Bonfire: Convert HTML Entities - No real tests to run?

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/freecodecamp#903]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Please correct me if I'm wrong. But I believe the exercise wants us to take characters like "&" and change them into their HTML entities: "&amp", right?

But the tests that are run make no sense (or at least the first one):
- assert.strictEqual(convert('Dolce & Gabbana'), 'Dolce & Gabbana', 'should escape characters');should escape characters: expected 'Dolce & Gabbana' to equal 'Dolce & Gabbana'
    ^-- aren't both the same?

- assert.strictEqual(convert('abc'), 'abc', 'should handle strings with nothing to escape');

**Comment by arecvlohe** [comment]
This is what I see as well. I am not sure what is being asked of us. I wrote a function that passes one test, but not the other even though I have the appropriate escaped character.

**Comment by kurzninja** [comment]
I was able to pass this test by simply using
```javascript
 str = str.replace(/\&/g, "&amp;");
```

Since the included assertion only tests the & case and the "nothing to escape case", this was way too easy, IMO. It doesn't test for the other cases included in the instructions, such as <, >,", and '. 

I think the problem that AkiraLaine is seeing is that when the assertion tests are rendered to the page, it should say:
```javascript
assert.strictEqual(convert('Dolce & Gabbana'), 'Dolce &amp; Gabbana', 'should escape characters');should escape characters: expected 'Dolce & Gabbana' to equal 'Dolce &amp Gabbana'
```
When the assertion tests are written into the HTML page in the browser, it's converting those escaped characters back into their final values, so the two cases look identical. Does that make sense?

**Comment by AkiraLaine** [comment]
@kurzninja Oh, I understand now!  Thanks a lot for your help. @arecvlohe I hope you understand too.
