### ISSUE TITLE
Privacy error: Your connection is not private. 

### ISSUE THREAD

**Issue by sbaldwin24** [FreeCodeCamp/FreeCodeCamp#9032]
#### Issue Description
- Privacy error: Your connection is not private. 
- The SSL handshake could not be performed.
<img width="769" alt="screen shot 2016-06-08 at 9 13 02 am" src="https://cloud.githubusercontent.com/assets/5033746/15897224/4d502b14-2d59-11e6-8158-c7115a726b9a.png">

#### Browser Information

* Chrome, Version: 51.0.2704.84 (64-bit)
* Chrome Canary, Version: 53.0.2761.2 canary (64-bit): 
* Operating System: OS X El Capitan
* Desktop

**Comment by erictleung** [comment]
@sbaldwin24 I can't reproduce this. I put in `https://freecodecamp.com` and it brings me to `https://www.freecodecamp.com`. Have you always had this happen? Recently? Or on specific devices?

cc/ @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
I can't reproduce this either :disappointed:

**Comment by sbaldwin24** [comment]
@erictleung  @atjonathan Apologies for the late response, it turns out it was a network issue and it has been resolved. Thank you for your prompt response!

**Comment by tonyjoker** [comment]
I have faced this issue many times in the past. And in most cases, it was caused by my computer or the program there.

If you want to know more about this issue, read the article here which I found from Google. It's informative.

[https://usefulpcguide.com/16666/your-connection-is-not-private/](https://usefulpcguide.com/16666/your-connection-is-not-private/)
