### ISSUE TITLE
Factorialize a Number issue

### ISSUE THREAD

**Issue by aakanksha-02** [FreeCodeCamp/FreeCodeCamp#9118]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20fact%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for(var%20i%3D1%3B%20i%3C%3Dnum%3B%20i%2B%2B)%0A%20%20%20%20fact*%3Di%3B%0A%20%20return%20fact%3B%0A%7D%0A%0Afactorialize(20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.0.11172 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var fact = 1;
function factorialize(num) {
  for(var i=1; i<=num; i++)
    fact*=i;
  return fact;
}

```

why is it wrong, even if i get correct answers for all the test cases. :(

**Comment by aakanksha-02** [comment]
![image](https://cloud.githubusercontent.com/assets/19503363/16000520/782422e0-316a-11e6-8961-b1feed5e38a8.png)

**Comment by arun1595** [comment]
The problem is with your declaration of **fact** variable. Since its global, fact gets modified after the first call to factorialize. Try to call factorialize twice and you will know what I am talking about.

![factorial](https://cloud.githubusercontent.com/assets/7039523/16000899/b9d83184-316c-11e6-87ae-6f06df650e3c.png)

Declare the fact variable locally inside the function so that everytime the function is called, the variable starts from 1.
```
function factorialize(num) {
  var fact = 1;
  for(var i=1; i<=num; i++)
    fact*=i;
  return fact;
}
```

**Comment by erictleung** [comment]
@aakanksha-02 what @arun1595 says is correct. More your `var fact = 1;` into your function and you shouldn't have any problems. Happy coding!
