### ISSUE TITLE
Test failure is misleading on CatPhotoApp - Change the Font Size of an Element

### ISSUE THREAD

**Issue by samit4me** [FreeCodeCamp/FreeCodeCamp#9210]
#### Challenge Name
CatPhotoApp - Change the Font Size of an Element

#### Issue Description
The following test fails if you remove the class from the first paragraph. Maybe it is not a bug, but it is somewhat misleading.
- Do not add a class attribute to the second p element.

#### Browser Information
* Chrome, Version: 51
* Operating System: OS X 10.11.5
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot
<img width="825" alt="screen shot 2016-06-18 at 12 24 31 pm" src="https://cloud.githubusercontent.com/assets/3248531/16168585/ca7a916c-354f-11e6-8dc7-f7d9e53b079a.png">

**Comment by arun1595** [comment]
The test checks whether only a single `p` without the class `red-text` exists. If it doesn't, it shows up the error. Since you removed the class from the first `p` element, there are two `p` elements which don't have the class `red-text`, so the test fails. The error message looks misleading. I think we need to make sure that only a single `p.red-text` exists.

@atjonathan Can I take this?

**Comment by samit4me** [comment]
Thank you for looking into this @arun1595. Not sure if it would be allowed, but would :nth-child(2) selector do the trick?

```JavaScript
// this
"assert($(\"p:not([class])\").length === 1, 'message: Do not add a class attribute to the second <code>p</code> element.');",
// becomes
"assert($(\"p:nth-child(2):not([class])\").length === 1, 'message: Do not add a class attribute to the second <code>p</code> element.');",
```
