### ISSUE TITLE
declaration var studlyCapVaR

### ISSUE THREAD

**Issue by ftarlaci** [FreeCodeCamp/FreeCodeCamp#9237]

**Comment by ftarlaci** [comment]
![screen shot 2016-06-19 at 11 02 41 pm](https://cloud.githubusercontent.com/assets/18291571/16183017/17445e60-3672-11e6-9f60-eb7b850c5df1.png)

**Comment by erictleung** [comment]
@ftarlaci can you elaborate on what your issue is? Your code is incorrect so that is why you there is a failing test. Or are you pointing at the list of errors you see in Chrome's devtools?

In response to: 

> The code is written in camelcase but `studlyCapVaR` gives error

the tests ask for a different variable name:

> `studlyCapVar` is defined and has a value of 10

**Comment by ftarlaci** [comment]
@ericleung, thank you for the reply. This is the instruction for the question: 

"Instructions
Fix the variable declarations and assignments so their names use camelCase." 

I am not able to see how the camelCase I used, which is seen on my screenshot is incorrect? I only get the error for studlyCapVar (as also seen in the screenshot) and I am wondering if I am receiving this error due to the errors in the console; thus, due to a bug in the code. If not, I would appreciate if you could tell me what error I am making as you seem to be able to see it. Thank you.

**Comment by erictleung** [comment]
@ftarlaci thanks for the clarification. As I mentioned above, your code is incorrect. I would double check your variable names and make sure they are the same. The challenge mentions that variable names are case sensitive and must be typed out precisely. If that solves your issue, please post an update. Otherwise, please ask coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) and if you are still having issues after getting the correct answer, then also post an update on that. Thanks!

**Comment by erictleung** [comment]
@ftarlaci did my suggestion help? It appears you have removed your issue above. If it has been resolved, please close this issue.
