### ISSUE TITLE
"join our Linkedin alumni network" challenge incorrect

### ISSUE THREAD

**Issue by Takaia** [FreeCodeCamp/FreeCodeCamp#9280]
#### Challenge Name

https://www.freecodecamp.com/challenges/join-our-linkedin-alumni-network
#### Issue Description

The challenge says to add "Full Stack Web Development Certification" for the "Degree" input. Upon going to Linkedin, it was apparent that the "Degree" portion for adding a school is not an input (maybe your example is outdated?) but a drop-down that definitely does _not_ include "Full Stack Web Development Certification".
#### Browser Information

- Browser Name, Version: Google Chrome, latest
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop
#### Screenshot

![degreedropdown](https://cloud.githubusercontent.com/assets/13824398/16242364/51aba296-37af-11e6-8f34-f3d1a7ab4ae7.png)

**Comment by atjonathan** [comment]
@Takaia, On linkedIn I see an input box, not a drop down menu.

![](https://i.gyazo.com/66d894d4461edbf1555a92cbe372011f.png)

**Comment by erictleung** [comment]
@Takaia I also see the same thing as @atjonathan where I see an input box and not a drop down.

**Comment by hollowaytape** [comment]
@Takaia I also see the same as @atjonathan and @erictleung, and I am using the latest Chrome on a Windows 10 desktop as well.

**Comment by Takaia** [comment]
That's so strange? I wonder why mine is different... I suppose you could close the issue since I'm apparently the only one with a dropdown

**Comment by QuincyLarson** [comment]
@Takaia please confirm - this is what you see when you click the button on FCC? LinkedIn does these A/B tests and its possible you got a specific test. Were you still able to add FCC to your LinkedIn account?

**Comment by Takaia** [comment]
I confirm that I see a drop down menu for degree rather than a blank input box.

**Comment by raisedadead** [comment]
Can anyone help us in confirm the cause behind this? Seems @Takaia has been consistently getting the issue.

**Comment by Takaia** [comment]
I checked again just to make sure, and I'm getting the same thing. But I mean, this is really Linkedin's problem, not necessarily yours.

**Comment by seannam** [comment]
@Takaia Have you tried entering Free Code Camp in the _School_ field of the form? That seems to turn the drop down menu into a input box.

**Comment by Takaia** [comment]
@seannam no luck!
![image](https://cloud.githubusercontent.com/assets/13824398/16460881/dfeed86a-3de6-11e6-9376-d39167502225.png)

**Comment by seannam** [comment]
@Takaia 
Really don't know what to say! I hope you get this figured out.
![screenshot 2016-07-12 17 06 35](https://cloud.githubusercontent.com/assets/4271055/16759695/1f726c38-4853-11e6-9840-024d0a42e7fe.png)

**Comment by seannam** [comment]
@Takaia Do you have any other schools/colleges on the education section? I have two on mine as a reference.

**Comment by dhcodes** [comment]
@Takaia is this possibly region-specific? What country are you in?

**Comment by atjonathan** [comment]
Closing as stale.

**Comment by mookabrim** [comment]
( http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcMqE7Mfsi7UspOXD-2BRXuNH4-3D2518_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNCA1-2FcXBu7SGDBW040I53qSPKhX0vme8cQC4Gq2FaDN9MG5GR3K5DGsMIE6kBDWAJ9LpfZ886m9TPGX9LYRdejGx34kNOzEldmAoorlOtbrlr1UXXUTzUqpht7WLN1gLcg-3D-3D )

----------
Personal
Information
Notice
----------

Who We Are
Bright Data Ltd., assists vetted businesses in collecting reliable public web data.

This notice is to inform you of the collection, processing, and sale of certain personal information or personal data about you ( *"Personal Data"* ). Some of the public information collected by us from the internet may occasionally include personal data, even though personal data collection is not our main business or objective. Please see below more information about the Personal Data we collect, how we gather it, and how it is used and shared.

What do you need to know?
*Categories of Personal Information Processed*
We may have any or all of the following categories of personal information about you, past or current collected from public websites:
- Name
- Profile picture
- Company
- Office Address
- Telephone Number
- Email Address
- Job Title
- Job Function and Responsibilities
- Education
- Social Media URL

What do you need to do?
*No action is required on your part.*
If you wish to check which Personal Data we have collected about you from the public web, you can check data collected ( http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcOAlwd1qQRQtBa6Uh5iZha0dXCVhSzmVFUbnmhxkItA8XkVnv4VkUWr1nL7-2BKRpN-2BrMEon8Xe2yF4akz0i0iMXTX-2FPUZMzrryTBKQB9G8pvyVOl3zX7oAlE7qKSghBKPfWjeJW6jb5bM6acviVepd5y1KzmoGNDQ1oF0BqzoQ-2FcPKah9Uhw3TmAtqn1BpnHzVw-3D-3DPFgu_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNBxUEQwgjGBS-2F3HCuavzwyaD2zWyk7-2Fnzz4Yj21PCNCgf93FB8dKBNwYJJcZUj4XtPbAyB6sAlUW7g2u3CWrbt00yTN0cDCtu-2B4QErVi8OIiR10YxABTXk1gAHcKIBfNnw-3D-3D ) , where you will find options to keep or request to delete such Personal Data.

Recipients of the Personal Data
This Personal Data may be shared with Bright Data’s customers, its partners, or the customers of its partners. These recipients are business organizations who are permitted to use the information only for lawful purposes and must meet Bright Data’s service agreements, as published in http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcJrk19i2toRBYl6ObE-2BAl6IIFTzPnkwG36KfwbK7vyrbvzAn_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNNkQ83Y3-2B0O4OzNWodyB2yejYmUKfjxXzrsqGisF4FYn7yqfr1Mbg831bqbfeJ-2BGaCHA3zS0X3GsPpZtW7Ui2rVaOUfTH8U0QcKFYPhUSbJmGH2isMxEJOTxP0CO63YxEw-3D-3D
Some of Bright Data's customers may be located globally, including outside of the European Economic Area. In such cases, Bright Data will employ applicable legal safeguards, aligned with the applicable data protection legislation's requirements.

How long will we keep the Personal Data
We will retain your personal information for as long as necessary to provide our services, and as necessary to comply with our legal obligations, or until you instruct us to refrain from processing it.

Purpose of Processing
Bright Data processes publicly available information for business purposes, and such public information may include Personal Data. The information may be licensed to our customers for their research or other business purposes, or to other organizations who may license it to their customers for the same purposes ("partners").

Lawful Basis
Bright Data’s processing of your personal information is based on the legitimate interest of itself and its customers to engage in business activities.

What are Your Rights
You have the right to request Bright Data to
(1) provide you with access to your personal information,
(2) rectify or correct your personal information,
(3) erase your personal information,
(4) restrict processing of your personal information, including refraining from selling it or otherwise providing it to any third parties.

You also have the right to object to processing or transferring your data, and to lodge a complaint with the appropriate supervisory authority in your country, if any. The foregoing rights may be subject to certain limitations pursuant to applicable law.

For individuals who are located in the European Union (including EEA countries):

Pursuant to Article 27 of the General Data Protection Regulation (GDPR), Bright Data Ltd. has appointed European Data Protection Office (EDPO) as its GDPR Representative in the EU. You can contact EDPO regarding matters pertaining to the GDPR:
- by using EDPO’s online request form: http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcGfE3a47jAEhk0UQP4x2Q8jasjskIzJHZJY7-2BTE9DNr0Ysq4_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNHgpxJcKXzK5R3RZEfUUgx2xVEHZBf7ZaS4CJVwbshJiNMfPIuubN8elapHbS2G9w2HJt160n-2FYS2v2UpwRfUDy1uTgiNkVoDqqPzX6-2BCZs-2FlQ3b-2B5KthmAMb7BX80kWBQ-3D-3D ( http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcGfE3a47jAEhk0UQP4x2Q8jasjskIzJHZJY7-2BTE9DNr0-xA7_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNPHJWFRwjOBw52eGzqW3M5BUf2qTsrgiqYUOPLuBabac3LQWtLXiWHTTd-2F-2FxQJOiBs42xsBBVvuvOeDXajCrR8agBl2ir9fwTiwUhQ9jLi2GULcNLO20yJz1ce-2FuLvJvJg-3D-3D )
- by writing to EDPO at Avenue Huart Hamoir 71, 1030 Brussels, Belgium

For individuals who are located in the United Kingdom:

Pursuant to Article 27 of the UK GDPR, Bright Data Ltd. has appointed EDPO UK Ltd as its UK GDPR representative in the UK. You can contact EDPO UK regarding matters pertaining to the UK GDPR:
- by using EDPO’s online request form: http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcG8i35lJtcZOXnw7zuDF6ynaz5DoQBfw98pJ3oqcbrxFlhlq_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNA6dYGmRA3jqqJGop06zrie2QL4mXApCIVyTDYMQymP35f-2FhCMnpOaYQOBraNa-2F2Mb52-2FpGVbfAUb-2B3HAQ5CFPHHGnXVU907cGcd4FrSoSVsSnIfeXSwPHwSQSMX339XdQ-3D-3D ( http://url289.brightdata.com/ls/click?upn=u001.yznX10lPC5qwS59NtqvzcG8i35lJtcZOXnw7zuDF6ynaz5DoQBfw98pJ3oqcbrxFO2YX_51r8jo3L-2BhAoYVmO4X6H12TN-2FK3JEOQVK5W-2FKNv-2Fds5SZl8xz2-2FlWjCw6ilZ-2BXB3Su8q6mTW4ZwLvQ5t9A1f7qze5TNTHPiCJZkG1sW2-2FPwKouwYxWb-2F4r-2FzGzuv89uTYQ1dYUrpZdkaHJ4mS74HYO8VS58WA-2F3AKhTzsRbxLyI8eLF95iPxpKNQh3njUOlQWbySQvAxPO-2BEJdsGLw7mL9PKmzpaSX7bEQLqcaJrdYDB78OEEgGJ5h0Z6KgbbyTsro3FHc7wEfaN-2B9k84moWKKXuLefpaz4vxX0kjyIWdj5FXPOAqLPIiut2P2T2oDqQl03fK1Nvo-2BBhTZk5-2BsZuNFG6XpAm5qhBTxpR1raP57XZ22JajygrGupJYz2ul6PNTc0ywsDA7z8YO0J6ShuSH5neOZBLzkziR3Q7tcKZjOKczOWsZN-2FJf2cxmUU8x-2FDjD8XXnxmFJGaxmGWy143R4Q-3D-3D )
- by writing to EDPO UK at 8 Northumberland Avenue, London WC2N 5BY, United Kingdom

Bright Data is Bright Data Ltd. 4 Hamahshev St., Netanya 4250714, Israel.
