### ISSUE TITLE
Run Tests not working

### ISSUE THREAD

**Issue by JoaoNeto87** [FreeCodeCamp/FreeCodeCamp#9320]
#### Challenge Name
No repeats please

#### Issue Description
Run tests are always returning failure. For example, the test case "permAlone("aabb") should return 8", my code is indeed returning the number 8 but the test case is returning failure.

#### Browser Information
Google Chrome Version 51.0.2704.103 m (64-bit)
Windows 10 Enterprise (64-bit)
Desktop

#### Your Code

```js
var permArr = [], usedChars = [];

function permAlone(input) {
	var permutations = permute(input);
	return countNonRepeatedConsecutiveLetters(permutations);
}

function permute(input) {
	
	var i, ch, chars = input.split("");

	for (i = 0; i < chars.length; i++) {

		ch = chars.splice(i, 1);

		usedChars.push(ch);

		if (chars.length === 0) permArr[permArr.length] = usedChars.join("");

		permute(chars.join(""));

		chars.splice(i, 0, ch);

		usedChars.pop();

	}

	return permArr;

}

function countNonRepeatedConsecutiveLetters(arr) {
	
	var repeatedConsecutiveLetters = 0;

	main_loop:
	for (var i = 0; i < arr.length; i++) {

		secondary_loop:
		for (var j = 0; j < arr[i].length; j++) {
			if (j === 0) continue;
			if (arr[i][j] == arr[i][j - 1]) {  
				repeatedConsecutiveLetters++;
				break secondary_loop;
			}
		}

	}

	return arr.length - repeatedConsecutiveLetters;

}

permAlone("aabb");
```

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/4921522/16306985/0bc09650-3936-11e6-9ac9-83f8ff6e018a.png)

**Comment by mizujin** [comment]
I think this problem comes from the global variables declared (permArr and usedChars). I succeeded in modifying your code and make it work both in repl.it and chrome devtools, unfortunately it hangs while testing on FCC...

```
function permAlone(input) {
	var permArr = [], usedChars = [];
	
    return (function permute(input){
        var i, ch, chars = input.split("");

    for (i = 0; i < chars.length; i++) {

        ch = chars.splice(i, 1);

        usedChars.push(ch);

        if (chars.length === 0) permArr[permArr.length] = usedChars.join("");

        permute(chars.join(""));

        chars.splice(i, 0, ch);

        usedChars.pop();

    }
	    return countNonRepeatedConsecutiveLetters(permArr);	
    })(input);
}


function countNonRepeatedConsecutiveLetters(arr) {

    var repeatedConsecutiveLetters = 0;

    main_loop:
    for (var i = 0; i < arr.length; i++) {

        secondary_loop:
        for (var j = 0; j < arr[i].length; j++) {
            if (j === 0) continue;
            if (arr[i][j] == arr[i][j - 1]) {  
                repeatedConsecutiveLetters++;
                break secondary_loop;
            }
        }

    }

    return arr.length - repeatedConsecutiveLetters;

}

permAlone("aabb");

```

Nesting the variables in PermAlone and using a IIFE function inside to allow recursivity gave me the same result.

**Comment by raisedadead** [comment]
@mizujin Yes that is correct, we haven't specified it yet but the multiple tests run on the same snippet from the editor, this leaves using global variables causing issues such as these.

So @JoaoNeto87 the error that you see is due to the fact that you have used global vars that get mutated in the previous test cases leaving you with this. 

The editor also hangs because of potential infinite loop caused in the algorithm above, you can disable a built in loop protect mechanism by adding `//noprotect` to the top of the code, as a work around.

This relates to the similar situation in #9199

**Comment by JoaoNeto87** [comment]
@raisedadead @mizujin Thank you, guys. Using Global Variables was really causing problems to my code. I erased then inside my permAlone function and it worked perfectly.
