### ISSUE TITLE
Remove Brownie Points from top navbar

### ISSUE THREAD

**Issue by chuckadams** [FreeCodeCamp/FreeCodeCamp#9432]
Anyone on the gitter channels for any length of time has seen inordinately many people confuse the number in square braces at the top of the page with a challenge number.  I suggest that the brownie point display be removed entirely from the standard page layout, and shown only on the profile page instead.  

Leaving this open for a few days to solicit discusson, after which I'll open a PR to do the deed.

**Comment by atjonathan** [comment]
@chuckadams, I agree with this proposition. Let's see what the other @FreeCodeCamp/issue-moderators think :smiel

**Comment by raisedadead** [comment]
We are losing the brownies! NOOOOOO! Its a crime, I love the brownies, lets add a setting or something to toggle the display of those cute nos.

**Comment by wiseleo** [comment]
Add a cookie icon to reflect that's brownie points. 

It is confusing that I can't refer to a challenge by a numeric ID. Challenges mutate and should have unique IDs that are shorter than "Sift through text with regular expressions". Although, there could be a simple fix for this. Upon clicking "Help" inside the challenge, the chat input box should auto-populate with "Hi, I have a problem with [link to challenge]".

**Comment by BerkeleyTrue** [comment]
I think the better question is why do campers insist on numbering challenges?

While linear, the challenges do change order or new ones are added. Campers should always use the name of the challenge when referring to it, not the sequence it appears in.

I think a better solution is to start campers out with five points instead of one. This will reduce the number of campers who are getting confused.

Removing the number from the NavBar is not a good idea.

I do like the idea of adding a cookie, but the nav bar is not a good place add more as it is already crowded.

**Comment by chuckadams** [comment]
Campers "insist" on it because every visual cue they get tells them that this is the number of the challenge.  Sleight-of-hand is not going to help: campers will believe they started with challenge number 5.  There is no indication that this number means anything other than that every challenge they see has an increasing number associated with it. If you make them increase by 10, they will believe challenge numbers increase by 10.

What exactly would be harmed by removing it?

**Comment by qmikew1** [comment]
I agree. No matter what initial brownie value is added, a lot of campers are going to (and do) associate (incorrectly) the count with 'challenge numbers'. If there was an option to expand the bracket section (with a label) - There would be a clear 'visual training cue' and they would be less likely (imo) to confuse things maybe something like in the gif below would work (only there would a separate li with [+] and a nice css animation (and points would still take them to profile)).
![collapsebrownies](https://cloud.githubusercontent.com/assets/13352783/16456498/061356b6-3de6-11e6-99fd-9b460f7633dd.gif)

**Comment by raisedadead** [comment]
How about something on lines of:

![nav-bar](https://cloud.githubusercontent.com/assets/1884376/16457524/76542eca-3e39-11e6-8d17-da2a3b37ef0a.png)

**Comment by BKinahan** [comment]
I'm also against removing the number from the nav bar, since there's nowhere else it's really shown, but I do think that somehow associating it with the user's avatar in a more obvious way would help to signify it's a property of a user and more than just a current-challenge number.

Since both the brownie count and the adjacent avatar both already link to a user's profile, perhaps we could overlap them to form that association, something like this:

![brownie](https://cloud.githubusercontent.com/assets/15965601/16461483/573083b2-3e1c-11e6-90d5-7f00074b1690.png)

Or a combination of this and a CSS animation as @qmikew1 suggests.

As for the conflation of brownie points and challenge number, this doesn't seem to me a persisting problem for any given camper. It's a misconception cleared up much more easily than explaining gitter's markdown formatting to a new user, for example.

**Comment by SaintPeter** [comment]
What about an animation when a brownie point is added?  A little floaty +1 that fades out, triggered when a challenge is completed.

Or maybe an additional message on the completion popup:
![image](https://cloud.githubusercontent.com/assets/553494/16461848/6b6b1e2a-3de3-11e6-9df7-abfe566e878e.png)

Maybe the "Brownie Points" is a link to a wiki on them?

This could be in combination with an animated +1.

**Comment by QuincyLarson** [comment]
As many have pointed out, we definitely should not remove this number from the navbar. If you look at every major website that uses points, they are prominent in the navbar. 

Here's how Stack Overflow shows them:
![](https://www.evernote.com/l/Ar9-7fim7ftJxY0LkebFSPLW-6xZzi_SC9MB/image.png)

And Khan Academy:
![](https://www.evernote.com/l/Ar9OV70LnxJFz6sXU6gwqWSO_c36x0hzD9gB/image.png)

Codecademy's is a drop down menu (I'm not a fan of complex navigation, as they're an [information architecture failure](https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/)):
![](https://www.evernote.com/l/Ar8CF6vQuZBOVLnOIctTq7IZuoEYNbfs22oB/image.png)

I don't think we should add any new UI elements or graphics. Of the proposals so far, @BKinahan's seems the best to me. He's right in that imposing the number above the profile image implies association with the user (and not association with something else, such as the current challenge).

**Comment by BKinahan** [comment]
I could definitely get behind a video-game-style increase in the base score for brownies, so long as users' current point totals and the other ways of getting points are scaled up to match 👍

**Comment by raisedadead** [comment]
@BKinahan nice catch, I see what you mean. 

/cc @BerkeleyTrue this is a good point to consider, which means the current user's points have to be adjusted indeed if we do change the points award scheme including those from the bot.

**Comment by BerkeleyTrue** [comment]
@BKinahan @raisedadead Yes this is the plan.

**Comment by chuckadams** [comment]
An overlay on the portrait plus some score increase notification would probably serve to reduce the confusion.  I remain unconvinced that 80's video games are an ideal model for gamification, but that's another story.

**Comment by chuckadams** [comment]
I implemented the portrait overlay on my own branch, and frankly all it does is uglify the portrait picture without clearing up the purpose of the number.  Since the original idea is a no-go and the proposed fix isn't likely going anywhere, I'll just drop the whole thing.

**Comment by raisedadead** [comment]
Hey @chuckadams can post a few screenshots of how it looks? I think we should be resolving this with some suggestions if possible.
