### ISSUE TITLE
Update tests for Delete Properties from a JavaScript Object

### ISSUE THREAD

**Issue by Landoghini** [FreeCodeCamp/FreeCodeCamp#9434]
Challenge [Delete Properties from a JavaScript Object](https://www.freecodecamp.com/challenges/delete-properties-from-a-javascript-object#?solution=%0A%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%2C%0A%20%20%22bark%22%3A%20%22bow-wow%22%0A%7D%3B%0A%0Adelete%20ourDog.bark%3B%0A%0A%2F%2F%20Setup%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Happy%20Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%2C%0A%20%20%22bark%22%3A%20%22woof%22%0A%7D%3B%0AmyDog-%3D%22tails%22%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"],
  "bark": "bow-wow"
};

delete ourDog.bark;

// Setup
var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"],
  "bark": "woof"
};
myDog-="tails";
// Only change code below this line.



```

**Comment by raisedadead** [comment]
The tests are checking if a property of myDogs is undefined, while not checking if the object has been mutated.

The regex check is not a good metric to catch this.

**Comment by raisedadead** [comment]
First timer issues are limited to basic typo or, small changes.

All contributors are expected to check for possible edge cases, missing cases etc. Definitely not a first timer's bug. When we have test cases causing a bug, they should be taken care of with utmost carefulness, because false positives like in this example can mean incorrect understanding 

Nevertheless, thanks for the condition check, however, I can't say if this is the only case we need to handle. Will update.

**Comment by hongvy** [comment]
ảo vãi .theo ảo luôn .thả sóng luôn

**Comment by hongvy** [comment]
0902222819
