### ISSUE TITLE
Broken wiki link in "Wherefore art thou"

### ISSUE THREAD

**Issue by jurijuri** [FreeCodeCamp/FreeCodeCamp#9497]
#### Challenge Name

[Wherefore Art Thou](https://www.freecodecamp.com/challenges/wherefore-art-thou)

#### Issue Description

I noticed the link to the wiki page for "Wherefore Art Thou" is busted - it returns a 404. (Maybe it was the name change - the wiki is still titled ["Where Art Thou."](https://www.freecodecamp.com/wiki/en/algorithm-where-art-thou/))

Thanks!

**Comment by erictleung** [comment]
@jurijuri thanks for catching this. Yes, it appears that the Wiki sidebar looks for the same title as the challenge. The [Wiki page](https://github.com/FreeCodeCamp/wiki/blob/34fd38068d9855d8ab98093521cad449a8b7fc10/Algorithm-Where-Art-Thou.md) needs to be changed so that the file name is `Algorithm-Wherefore-Art-Thou.md` and that should fix the problem.

The corresponding function name and title should also be changed.

To contributors: 
Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by Manish-Giri** [comment]
@erictleung I'll take this one!

**Comment by raisedadead** [comment]
@Manish-Giri when you do make sure you add a Closes `FreeCodeCamp/FreeCodeCamp#9497` tag in the PR to close this on a merge.
