### ISSUE TITLE
run(ctrl+enter) is not working in this challenge

### ISSUE THREAD

**Issue by lordzuko** [FreeCodeCamp/FreeCodeCamp#9523]
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    ("button").addClass("animated");
    (".btn").addClass("shake");
    ("#target1").addClass("btn-primary");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@lordzuko thanks for the issue but the problem is that your code is incorrect and causing unintended consequences. Please reread the instructions carefully to solve your problem:

> Now you know three ways of targeting elements: by type: `$("button")`, by class: `$(".btn")`, and by id `$("#target1")`.

In the future if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by lordzuko** [comment]
@erictleung thanks for quick reply. I get the syntax was wrong, but for the should not the platform indicate the errors after all it's for the beginners to start with. Someone like us can easily get that there was javascript error, but in my opinion the error should have been shown there. 

I hope you are getting the point I am raising here !!

**Comment by erictleung** [comment]
@lordzuko thanks for the feedback. It wasn't clear from the original post that you were bringing up constructive criticism rather than a coding issue.

I agree that it can be frustrating. For now, when something weird like this happens, you can open up your browser's developer tools and will see the issue. Somewhere in the curriculum, there is an explanation on how to open these. It'll tell you the error.
