### ISSUE TITLE
Removed only the ">" and "<" characters leaving the "-". Still able to pass all tests.

### ISSUE THREAD

**Issue by dkat90** [FreeCodeCamp/FreeCodeCamp#9531]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
--

```

**Comment by erictleung** [comment]
@dkat90 thanks for the issue but I don't think there's any issue. The `--` are no longer comments so you have successfully uncommented the HTML asked for by the tests. You can be sure of this because those HTML elements show up in the phone emulator. The `--` are just evaluated as plain HTML at this point. 

![image](https://cloud.githubusercontent.com/assets/2754821/16550844/3f27dff8-4165-11e6-9caa-7d6eda3b23f6.png)

 So I don't see any issue. Thanks for your concern though! Happy coding!
