### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by killerdevildog11** [FreeCodeCamp/FreeCodeCamp#9535]
something wrong with the change password on the site I changed my password with the link sent to my email with out filling out confirm password textbox. I only typed my new password in the first textbox asking for the new password and pressing enter.

**Comment by erictleung** [comment]
@killerdevildog11 sorry you're having issues with changing your password. After going through those steps, did your password change? The "Confirm Password" textbox needs to be filled out so that you are sure you want your new password to be like that. Please fill out both textboxes to change your password. If you're still having issues, please update us here.

**Comment by raisedadead** [comment]
Closing as stale. Please comment on this thread if you are still facing any issues.
