### ISSUE TITLE
how-to-npm: issues adding dist-tag & verify skip not working either

### ISSUE THREAD

**Issue by amirghafouri** [FreeCodeCamp/FreeCodeCamp#9558]
I am aware that this was an issue in the past and have reviewed those conversations, specifically denmch's posts on May 30, 2015

I have completed all of jlord's git-it and some of learn-you-node without any problems

#### Challenge Name
Manage Packages with npm

https://www.freecodecamp.com/challenges/manage-packages-with-npm (#13)

#### Issue Description
On step 11 of how-to-npm

#### Browser Information

* Browser Name: Google Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: desktop

#### Your Code

I've tried

`aghafour:~/workspace/how-to-npm (master) $ npm dist-tag add fcc-learning@1.0.1 [buggy]`

which gives

```
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "dist-tag" "add" "fcc-learning@1.0.1" "[buggy]"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 missing : -/package/fcc-learning/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/how-to-npm/npm-debug.log

```
I've also tried variations of the initial command, the corresponding dist-tag ls command (which returns same errors), going back and redoing the publish and republish levels, making sure that the version I'm trying to do isn't the latest, and adding a "dist-tags" property of "buggy" to my package.json object (total hail mary based off the `ERR! 404 missing:` from above)

`how-to-npm verify skip` isn't working either. Can anyone help me?

**Comment by Bouncey** [comment]
+1 on this. I couldn't get it working. I ended up having to skip it with a view of raising an issue, but I never got round to it.

**Comment by dhcodes** [comment]
As a follow-up, I don't see this as an issue with FCC so much as poor wording from how-to-npm and possibly an issue on their end. Luckily, there are many github issues about this that led me to the eventual solution so read-search-ask does get you there assuming you can find the right discussions on github.

**Comment by Bouncey** [comment]
Great write up @dhcodes Very helpful, thanks!

**Comment by EdwardThawne** [comment]
edwardthawne:~/workspace $ npm dist-tag ls
npm ERR! dist-tag ls Couldn't get dist-tag data for chat-example
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "dist-tag" "ls"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code E404

npm ERR! 404 missing : -/package/chat-example/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by fellfromhell** [comment]
Followed the solution that @dhcodes described.
Then ran npm-dist-tag ls
it shows the test tag applied to an unpublished package and version 1.0.8
how-to-npm verify still fails
Added a dist-tag to version 1.0.6
then ran how-to-npm verify to pass
Please see my output below

p3nski:~/workspace/howtonpm (master) $ npm dist-tag ls
latest: 1.0.7
test: 1.0.8
p3nski:~/workspace/howtonpm (master) $ npm dist-tag add @fellfromhell/howtonpm@1.0.6 test
+test: @fellfromhell/howtonpm@1.0.6
p3nski:~/workspace/howtonpm (master) $ how-to-npm verify
Congratulations!  You've added a dist-tag!

This is a handy way to manage releases.  For example, the npm project
itself publishes each new version as 'next' (instead of 'latest') so
that beta users can test it out before it becomes the default.

Run `how-to-npm` to move on to the next exercise.

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@     YOUR SOLUTION IS CORRECT!     @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by srichakradhar** [comment]
for me, it shows
```
srichakradhar:~/workspace/npm2 (new) $ npm dist-tag add @chuck/chaakage@1.0.2 dev
npm WARN dist-tag add dev is already set to version 1.0.2
srichakradhar:~/workspace/npm2 (new) $ npm dist-tag ls
latest: 1.0.1
srichakradhar:~/workspace/npm2 (new) $ npm ls
@chuck/npm2@1.0.2 /home/ubuntu/workspace/npm2
└── @linclark/pkg@1.0.2
```
why do I get the warning and still not see the tags!?

**Comment by kerfax2232** [comment]
I also had the same issue.  tbh, I didn't try dhcodes' solution partially because I feel like this should either be fixed or not included in the lesson with such a difficult to use tutorial.  I'm moving along and will hopefully just figure this out over time.
