### ISSUE TITLE
Tests are not clearly visible

### ISSUE THREAD

**Issue by arun1595** [FreeCodeCamp/FreeCodeCamp#9577]
#### Challenge Name

[Pig Latin](https://www.freecodecamp.com/challenges/pig-latin)

#### Issue Description

The content in the tests, particularly the input parameters passed to the function are not fully visible. See the screenshot

![parameters](https://cloud.githubusercontent.com/assets/7039523/16597710/fabb8e8c-4317-11e6-81ba-2a14de713e06.png)

#### Browser Information

* Browser Name, Version: Google Chrome 51.0.2704.106
* Operating System: Ubuntu 16.04 LTS

The problem is because the string is long and can't fit into the container.
Suggested fix:
```
code{
word-wrap:break-word;
white-space:pre-wrap;
}
```
We can also use `wbr` to specify word-breaks.

Working version:
![fix](https://cloud.githubusercontent.com/assets/7039523/16598014/7e457366-4319-11e6-8311-8a31e239b9c7.png)

**Comment by BKinahan** [comment]
This (and other similar issues) should be solved by a recently merged pull request #9247 

This challenge's tests will look like this after the change goes live:
<img width="509" alt="screen shot 2016-07-05 at 20 8 57" src="https://cloud.githubusercontent.com/assets/15965601/16598306/c3da0388-42ec-11e6-8f3b-977ca0815408.png">

I don't think word breaks are the best solution since they may suggest to some users that an argument contains a space at the break point, but hopefully the wider column will be sufficient for long function name/argument value combinations.

**Comment by erictleung** [comment]
@arun1595 thanks for the issue but this has been brought up before in #8390. Feel free to bring the discussion over there. I don't think we came up with a conclusion on what to do but if #9247 fixes this, then we can close that too once it is pushed to the live site. Closing this as a duplicate. Happy coding!
