### ISSUE TITLE
Correct solution won't pass on Storinv Values with the Assignment Operator

### ISSUE THREAD

**Issue by solo800** [FreeCodeCamp/FreeCodeCamp#9590]
Storing Values with the Assignment Operator
https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator\

Correct answer does not work.
Add the following code to the code editor
```
// Setup
var a;
var b = 2;

// Only change code below this line

b += 5;
a = b;
```
Click run tests and all tasks are marked as complete except the final "a should be assigned to b with ="
Chrome Incognito mode, 51.0.2704.103 (64-bit)
Max Book OS X El Capitan 10.11.5

```js
// Setup
var a;
var b = 2;

// Only change code below this line

b += 5;
a = b;
```

<img width="637" alt="screen shot 2016-07-06 at 4 16 23 pm" src="https://cloud.githubusercontent.com/assets/5925213/16637619/312d4bc2-4395-11e6-9bdd-0408459b3fc8.png">

**Comment by erictleung** [comment]
@solo800 the instructions may clear things up for you.

> Assign the contents of `a` to variable `b`.

Also, the instructions don't ask for adding 5 to `b` so that will also help in solving the challenge.

If you get stuck with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by solo800** [comment]
Ah, I read it the other way around assign a to variable b, whoops.

**Comment by nellee24** [comment]
// Setup
var a;
var b = 2;

// Only change code below this line
a = 5 + b;
b = a;

try this :)
