### ISSUE TITLE
Replace How-To-NPM 

### ISSUE THREAD

**Issue by jondcoleman** [FreeCodeCamp/FreeCodeCamp#9600]
Nearly every day, multiple users are having issues with How-To-NPM and asking for help in the HelpBackEnd chat room.

In my opinion, the tutorial is of questionable value at the point in the course where it is introduced -- particularly the second half of the tutorial which is about publishing NPM packages.  At this point in the course, campers aren't going to be publishing NPM packages, nor is it required at any point in the course.

Given the frequent issues with the tutorial and the limited value provided, I'd like to propose that How-To-NPM be removed and maybe replaced with a simpler tutorial mainly around using NPM packages in a project rather than publishing NPM packages.  Maybe this is a fork of How-To-NPM which removes steps 8 and following or maybe it's a different tutorial all together.

**Comment by raisedadead** [comment]
The [how-to-npm](https://github.com/npm/how-to-npm) repo is mostly not getting the love it deserves, how ever we have seen that the workshopper does work on C9.io when you create a blank ubuntu workspace (not the nodejs workspace).

Then manually installing stuff, lets you work with this workshopper. But the trouble is not worth for a newbie.

Not sure if we should be forking and maintaining a whole workshopper. I personally have never liked those in the first place. Rather if we could have any alternate approaches to teach the commands/concepts it would be much greater effort.

Thoughts @FreeCodeCamp/issue-moderators ?

**Comment by Bouncey** [comment]
Can we write our own challenges using something like [this bash emulator](https://github.com/haydenbleasel/bash)?

**Comment by raisedadead** [comment]
Yeah, we could. Why not? Something on the lines of https://try.github.io/ should be a good, but this does involve a ton of work.

**Comment by Bouncey** [comment]
@raisedadead but it would also give us control over the content and the ability to resolve issues faster

**Comment by raisedadead** [comment]
Agreed.

**Comment by N0bl3** [comment]
I think that in order to make real apps like dynamic apps challenges, they should be able to write some npm scripts or at least know how to read them because they should not rely only on grunt or gulp tools (most tutorials online) and copy pasting for automating tasks.

As there is no tutorial on grunt or gulp on the official path, we should keep NPM for now. Besides it is the most reliable tool of them three but that's another topic.

I'm not saying we should keep the current how to NPM as it is but rather i want to insist on the value of being able to handle npm and that how-to-npm even if difficult to achieve at first time is an entry point to the real world of developers.

Without writing our own challenges, we could add some intermediary steps in which some explanations are given where we feel it is necessary.
What do you think?

**Comment by jondcoleman** [comment]
@N0bl3 thanks for your comment.

Yeah, I agree that npm is valuable and necessary to teach.  What I don't think is valuable is teaching campers how to publish their own npm packages.

And I think there could be a better format than the current tutorial.

**Comment by BerkeleyTrue** [comment]
> What I don't think is valuable is teaching campers how to publish their own npm packages.

Agreed.

**Comment by N0bl3** [comment]
i also think the format is not ideal because most people arriving at this level doesn't know about npm insides (nor outsides except npm i).

**Comment by systimotic** [comment]
Hi all! I very much agree with what is being said in this challenge.
This is being addressed in the curriculum expansion. More info here: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44
I'm closing this issue, because I think it's best to continue the discussion there. If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!
