### ISSUE TITLE
Cannot run tests on challenge symmetric difference

### ISSUE THREAD

**Issue by mallegrini** [FreeCodeCamp/freecodecamp#962]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue.

Regardless of what I write in the code editor the message I get when I hit 'run code' button is always the same:
Program Execution Failure
No user tests were run.

Even with the default starting  solution. 

Thanks
Mauro

**Comment by brandenbyers** [comment]
Confirmed. The default code block fails to run the tests as-is. It has been a long while since I have looked at how the editor is executing these tests.

@terakilobyte do you have any idea why the `Program Execution Failure`?

Interestingly, if I change the code block to read like this:

```
function sym(args) {
  return [ 3, 5, 4 ];
}

sym([1, 2, 3], [5, 2, 1, 4]);
```

...the tests will run but it also returns this under the run button: `{"__flags":{"object":[3,5,4]}}`

![screen shot 2015-06-19 at 12 05 51 am](https://cloud.githubusercontent.com/assets/7098232/8247495/9db8839e-1617-11e5-9c49-bf8aa4ff8462.png)

**Comment by tourn171** [comment]
I as well am having issues with this. I am receiving   
  
{"__flags":{"object":[3,5,4]}}  
  
on the default and  
  
assert.deepEqual(sym([1, 2, 5], [2, 3, 5], [3, 4, 5]), [1, 4, 5], 'should return the symmetric difference of the given arrays');
should return the symmetric difference of the given arrays: expected [ 1, 4 ] to deeply equal [ 1, 4, 5 ]  
  
on the actual tests.

**Comment by Davidrums** [comment]
somehow the tests will only run if you return [3,5,4].

possibly do a `arr1.sort().join("")===arr1.sort().join("")` in stead of deep equals so that order of elements doesn't matter (that's what is breaking the tests I think)

**Comment by Davidrums** [comment]
@terakilobyte @brandenbyers found it in pagesource :P 

`var tests = ["expect(sym([1, 2, 3], [5, 2, 1, 4])).to.eqls([3, 5, 4])","assert.deepEqual(sym([1, 2, 5], [2, 3, 5], [3, 4, 5]), [1, 4, 5], 'should return the symmetric difference of the given arrays');","assert.deepEqual(sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]), [1, 4, 5], 'should return an array of unique values');","assert.deepEqual(sym([1, 1]), [1], 'should return an array of unique values');"];`

i suspect it's the `expect` in stead of the `assert.deepEqual`

**Comment by brandenbyers** [comment]
@davidrums good catch. That `expect` should have `to.equals` and not `to.eqls`. I can get that later today.
