### ISSUE TITLE
"Not enough disk space"

### ISSUE THREAD

**Issue by GregoryGoncalves** [FreeCodeCamp/FreeCodeCamp#9634]
Challenge [Store Data in MongoDB](https://www.freecodecamp.com/challenges/store-data-in-mongodb) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

If you follow the tutorial directly, in the step called "Connect" it will ask you to start a server  using the command "mongod --port 27017 --dbpath=./data". Doing that will get you this error: http://i.imgur.com/cGy0iRP.png saying there isn't enough disk space avaiable. For this operation to work, you must attach "--smallfiles" to the mongod command.

**Comment by raisedadead** [comment]
Yup, we should add that param as a hint in the challenge it self.

**Comment by BKinahan** [comment]
The tutorial does prompt you to use the command `mongod --port 27017 --dbpath=./data` but the FCC instructions include `Whenever you run a command that includes mongod on c9.io, use ./mongod instead.` (Step 13)

`./mongod` uses the command and arguments set up in that file by using the instructions linked to in Step 11 of the FCC instructions (here: https://community.c9.io/t/setting-up-mongodb/1717) One of those arguments is the `--nojournal` flag, which prevents journaling and avoids the disk space problem.

However, the use of this command alias means that following the learnyoumongo instructions to run `mongod --port 27017 --dbpath=./data` results in a double-use of the `--dbpath` option. Whether the user can figure out that they should remove that option and run `mongod --port 27017` without it and whether this process is convoluted enough to warrant not using `learnyoumongo` is up for discussion.

**Comment by raisedadead** [comment]
/cc @FreeCodeCamp/issue-moderators thoughts?

I am not sure why should be prompting campers to use no standard formats (especially at the beginning).

**Comment by GregoryGoncalves** [comment]
I see, i didn't notice the `./mongod` part. It could at least be mentioned in the tutorial that "if you have a problem with disk space, use X". The difference between `/mongod` and `./mongod` is minimal, and when you have a disk space problem, it's quite a big leap to think that `./mongod` will be the solution, specially if you didn't even notice.

**Comment by BKinahan** [comment]
How about amending Step 13 to something like:
>Whenever you run a command that includes `mongod` on c9.io, use `./mongod` instead.
Together with the commands used in Step 11, this adds additional parameters to the `mongod` command to allow MongoDB to run in the C9 environment.

Additional notes in the following steps relating to the specific lessons of `learnyounode` can indicate when duplicate parameters should be removed from the command described in the lesson, e.g. for Step 18:
> Complete "Connect"
Note: Use the command `mongod --port 27017` in place of `mongod --port 27017 --dbpath=./data` to avoid a duplicate parameter error, as `--dbpath=./data` is already included in the `./mongod` command.

There is of course a balance between brevity and clarity to be struck here. If many such notes are required, the instructions will become quite long indeed.

It also assumes the user will refer back to the Challenge instructions regularly rather than going through `learnyounode` and assuming all the necessary information is there (which it should be but of course isn't, and cannot be unless a custom workshop is written for the C9 environment).

**Comment by GregoryGoncalves** [comment]
I think a simple warning would suffice, something that people will notice as important the first time they reach the mongodb guide. My experience was that i just ignored the FCC steps after running `learnyoumongo` on c9, since in the git tutorial i didn't need to go back to codecamp. This error is an exception, i believe the message should also be exceptional, otherwise most people won't even notice it's there.

**Comment by Grantlyk** [comment]
I have taken the liberty of implementing the changes suggested by @BKinahan
