### ISSUE TITLE
I need to apply bounce property on both left and right well's using nth-child... I m not getting it.

### ISSUE THREAD

**Issue by jpathan** [FreeCodeCamp/FreeCodeCamp#9641]
Challenge [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target1%22).prop(%22disabled%22%2C%20true)%3B%0A%20%20%20%20%24(%22%23target4%22).remove()%3B%0A%20%20%20%20%24(%22%23target2%22).appendTo(%22%23right-well%22)%3B%0A%20%20%20%20%24(%22%23target5%22).clone().appendTo(%22%23left-well%22)%3B%0A%20%20%20%20%24(%22%23target1%22).parent().css(%22background-color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23right-well%22).children().css(%22color%22%2C%20%22orange%22)%3B%0A%20%20%20%20%24(%22%23left-well%3Anth-child(1)%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well:nth-child(1)").addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by clothesclothes439** [comment]
that is very good, thanks

**Comment by abhisekp** [comment]
@jpathan 
### The Instruction
> Make the second child **in each of your `well`** elements `bounce`. 
You must **target the children of element with the `target` class**.

i.e. you must target the `target` class and only select the 2nd of the `target` class.

----

Please verify with the community in [![FreeCodeCamp/Help](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/Help_⮭-006400.svg?style=flat-square&maxAge=2592000)](https://gitter.im/FreeCodeCamp/Help)  room before filing an issue.

**Comment by jpathan** [comment]
Thank you so much…I got it

**Comment by akorede12** [comment]
how did you get it, I'm confused

**Comment by fuecisla** [comment]
@akorede12 You did not get it because it is not well explained, at all. It is not intuitive. We are supposed to "Target a Specific Child of **an Element** Using jQuery" so obviously you would be expecting to point to **one element** and then to its child. However the example tells you to:

> Make the second child in each of your well elements bounce. You must target the children of element with the **target** class.

 if you follow their instructions you are NOT targeting the a specific child (nth-child) of an element (the well elements), you are targeting the nth-child of **ALL** the elements **of a given class** (the class target). In fact, if you want to target the nth-child of **a given element** you will need to use the ID of such element (not its class). Of course, you could use the class if there is only one element with class target. But that would be a poor solution, because that is not why classes were meant for.

Please, let me know if I am wrong or misunderstood what your problem was with this challenge.

**Comment by akorede12** [comment]
Thank you, I've already figured it out, but still thanks

On Wednesday, 3 August 2016, Borja <notifications@github.com> wrote:
> @akorede12 You did not get it because it is not well explained, at all.
It is not intuitive. We are supposed to "Target a Specific Child of an
Element Using jQuery" so obviously you would be expecting to point to one
element and then to its child. However the example tells you to do
something different:
>
> Make the second child in each of your well elements bounce. You must
target the children of elements with the target class.
>
> If you follow their instructions you are NOT targeting a specific child
(nth-child) of a single element you are targeting the nth-child of ALL the
elements that have children of a given class (the class target). How can
you target the nth child of a parent element?? No idea (my guess is by
using the id).
>
> I think that the example is to blame, but only partially. JS is not so
intuitive because:
> 1. You would expect to find the children by a reference to who are their
parents (their name or at least the parents class).
> 2. However, at least in this example, JS only uses the parents to
identify find second child.
>
> In other words, this example does not teach you to find the second boy of
all the parents called "Smith" or of an specific family. It shows you to
find the second blond boy of all the families that have blond boys.
>
> Please, let me know if I am wrong or misunderstood what your problem was
with this challenge.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/ZiA5mmBxCCq91ELF6DJw1ztSA-ULZT6rPjDazpCS80lXkt2_D3oUetVrBmriKjCU_UFICtkj8fOEHqsaNTnDREAy0-VNYZG5K8mi6qwGqzBUJJgczSm4eCksfEFQfTkwpsPr1DItHcRgAG_0iA-LJm2tKySeeQ=s0-d-e1-ft#https://github.com/notifications/beacon/ATaXte9hO13qZtrpYYf48FD8rhap9RWTks5qcK_AgaJpZM4JIomj.gif>
