### ISSUE TITLE
target="_blank" leaves redirect open to phishing scams

### ISSUE THREAD

**Issue by eclecticexistential** [FreeCodeCamp/FreeCodeCamp#9656]
While working on making a tribute page here:
[https://www.freecodecamp.com/challenges/build-a-tribute-page](https://www.freecodecamp.com/challenges/build-a-tribute-page)

I noticed that the a href='s would work with or without the target="_blank" code. 
Googled it's purpose, found this:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Alex suggested using this line instead:
rel="noopener noreferrer" 
to avoid phishing scams.

Hope this helps.

**Comment by raisedadead** [comment]
Yup, this can be one of the interesting new challenge topics for the info sec challenges.
/cc @Greenheart would you take this up in the discussion.

**Comment by Greenheart** [comment]
@eclecticexistential @raisedadead Thank you both, this would definitely fit in a challenge! :smile: The only thing we need is some kind of best practice that we could teach.

I've read that `rel="noopener noreferrer"` also removes the referrer HTTP header which will stop friendly sites from seeing traffic from you - **which is a high price just to protect your users from a few malicious sites**. This was discussed in [#8460](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8460) where they basically concluded that `rel="noopener noreferrer"` only should be used when pointing to untrusted sites.

### Conclusion:
* This issue can be closed since the links in question point to trusted sites (Codepen, Wikipedia).

**Comment by atjonathan** [comment]
Yeh we went through this as greenheart said and made sure links were trusted. Thanks @greenheart :smile:
