### ISSUE TITLE
Bug,can't pass exam

### ISSUE THREAD

**Issue by Wilson-lambda** [FreeCodeCamp/FreeCodeCamp#9689]
Challenge [Finders Keepers](https://www.freecodecamp.com/challenges/finders-keepers#?solution=%0Afunction%20findElement(arr%2C%20func)%20%7B%0A%20%20var%20a%3D%20arr.filter(func)%3B%0A%20%20return%20a.length%3D%3D%3D0%3Fundefined%3Aa%3B%0A%7D%0A%0Avar%20b%3DfindElement(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(num)%7B%20return%20num%20%25%202%20%3D%3D%3D%200%3B%20%7D)%3B%0Aconsole.log(b)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function findElement(arr, func) {
  var a= arr.filter(func);
  return a.length===0?undefined:a;
}

var b=findElement([1, 3, 5, 8, 9, 10], function(num) { return num % 2 === 0; }) //should return 8.
console.log(b);

```
# it is bug,10 also is answer;

**Comment by dhcodes** [comment]
@Wilson-lambda I'm not sure the tests will pass if you modify the function at the bottom because I believe that is used for tests. I reset the code and used your findElement function and returned [8,10] for the first test. As you say, 10 does meet the criteria of being divisible by 2 with no remainder but the instructions say:

> Create a function that looks through an array (first argument) and returns the **first element in the array** that passes a truth test

So in that case, you'll only want to return 8. Try asking in the [FCC Help Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) on Gitter if you need assistance.

**Comment by raisedadead** [comment]
@Wilson-lambda: 
Your code is incorrect. Please review the instructions, as always please confirm issues in the Chat room as before reporting. 

@dhcodes thanks for the comment.

**Comment by theador0691** [comment]
I personally the instructions should be re-written to include all numbers that pass the test.
