### ISSUE TITLE
Bootstrap Lesson Issue

### ISSUE THREAD

**Issue by highestflyingeagle** [FreeCodeCamp/FreeCodeCamp#9750]
#### Issue Description

Lesson 81 - The instructions say to "Add Bootstrap's btn-block," but the problem I have with this set of instruction is that it does not give an example, like other Lessons have provided. I had to look online to find the answer and the answer would be impossible to find if I had to rely on just the instructions. The purpose of this is to teach people people how to code, not frustrate the hell out of them and almost make them quit. From about Lesson 78 to 81, there has been NO EXAMPLES OF HOW TO BOOTSTRAP. Maybe you should add this to your Lessons. Thank you.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by dwd2010** [comment]
you need to write problem on issue. not on the title.

**Comment by qmikew1** [comment]
Assuming we're talking about challenge [Create a Block Element Bootstrap Button](https://www.freecodecamp.com/challenges/create-a-block-element-bootstrap-button) - It does give an example on usage. Sometimes providing a screenshot is helpful (when opening an issue) because anything can happen between serving a page and the device/browser/assets (you name it) it's being rendered. The frustration aspect comes across pretty clearly, but bouncing questions off people in say in [help](https://gitter.im/FreeCodeCamp/Help) can really, well, help. If you don't see something similar in screenshot, then yes that could be a potential bug - If you do, then this would be something more appropriate, again, for [help](https://gitter.im/FreeCodeCamp/Help) and not in an issue.
![selection_074](https://cloud.githubusercontent.com/assets/13352783/16895192/e86fbff6-4b3b-11e6-942b-1fd5d6b71bb6.png)

**Comment by erictleung** [comment]
@highestflyingeagle thanks for the issue. However, can you clarify your difficulties on which challenge names in particular you're having issues with? We take feedback on our curriculum seriously but from your description, it is not clear on how we should act.

Additionally, what @qmikew1 suggests appears to resolve your issue. The example shown clearly shows how to apply a Bootstrap class to an HTML element.

**Comment by erictleung** [comment]
@highestflyingeagle closing as stale. Please take a look at the comments above if you're still having issues. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
