### ISSUE TITLE
fourth condition does not work

### ISSUE THREAD

**Issue by J0nibek** [FreeCodeCamp/FreeCodeCamp#9752]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=var%20arr2%20%3D%20%5B%5D%3B%0A%0Afunction%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%0A%20%20%0A%20for%20(var%20i%3D0%3B%20i%3Carr.length%2Fsize%3B%20i%2B%2B)%0A%20%0A%7B%0A%20%20%0A%20arr2%20%5Bi%5D%20%3D%20arr.slice(size*i%2C%20size*(i%2B1))%3B%0A%20%0A%7D%0A%20%20%20%0A%20return%20(arr2)%3B%0A%0A%7D%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%5D%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr2 = [];

function chunkArrayInGroups(arr, size) {

  
 for (var i=0; i<arr.length/size; i++)
 
{
  
 arr2 [i] = arr.slice(size*i, size*(i+1));
 
}
   
 return (arr2);

}

chunkArrayInGroups([0, 1, 2, 3, 4, 5], 4);

```

**Comment by erictleung** [comment]
@J0nibek thanks for the issue but if you get stuck with a challenge future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). The problem you're running into is that we run our tests using only your function. You've declared a global variable your function modifies so that is what is causing problems. Put your global variable within your function and your code should work. Happy coding!
