### ISSUE TITLE
Global Scope and Functions

### ISSUE THREAD

**Issue by quicksilver774** [FreeCodeCamp/FreeCodeCamp#9755]
Global Scope and Functions

https://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%0A%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20oopsGlobal%20%3D%205%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A

#### Issue Description

You just have to go to the Global Scope and Functions Challenge,
It says "Variables which are used without the var keyword are automatically created in the global scope"
But the instructions then say, 
" Declare a global variable myGlobal outside of any function. Initialize it to have a value of 10", so i declare it not using the var keyword.

But the problem is one of the steps says
"myGlobal should be declared using the var keyword"

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by adamisntdead** [comment]
If you write a variable inside a function without a `var`, its assigned global scope. if you leave a variable, declated with a `var` (example: `var banter;`), not inside any function, It also has global scope. See [here](https://msdn.microsoft.com/library/bzt2dkta(v=vs.94).aspx)

**Comment by erictleung** [comment]
@quicksilver774 thanks for the feedback. Although this may be a little confusing, the part of the instructions you left out make sense.

> This can create unintended consequences elsewhere in your code or when running a function again. **You should always declare your variables with `var`.**

We want you to always declare variables with `var` so that is why the test asks you to do so.

To make it easier and less confusing, we can change [this line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9b5c00fcb55c04ffd60357bf84deae01168bb70/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2206) to

```
"Using <code>var</code>, declare a <code>global</code> variable <code>myGlobal</code> outside of any function. Initialize it to have a value of <code>10</code>",
```

so that it reads

>Using `var`, declare a `global` variable `myGlobal` outside of any function. Initialize it to have a value of `10`

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled `first-timers-only` so only those who have not contributed to the main Free Code Camp repository can fix this issue. Thank you.

**Comment by jaikamat** [comment]
Hey @erictleung, I'd like to take this issue if that's alright!

**Comment by erictleung** [comment]
@jaikamat go for it!

**Comment by erictleung** [comment]
PR #9763 resolves this issue. Happy coding all!

**Comment by quicksilver774** [comment]
The second way makes more sense to me. Thanks!!
