### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by emily04** [FreeCodeCamp/FreeCodeCamp#9756]
#### Challenge Name
https://www.freecodecamp.com/challenges/accessing-nested-objects

#### Issue Description
In the paragraph with instructions, the highlight term styling extends beyond where it should be, starting with the word "gloveBoxContents." It continues into other line breaks and into the subsequent pop-up window (run tests, reset, bug). The screenshots included here are from "night mode" but the problem occurs in the default setting colors as well.

#### Screenshots
![nested-obj-styling-screenshot](https://cloud.githubusercontent.com/assets/19827006/16897698/dbe036ce-4b7e-11e6-8485-6f3124ed569a.PNG)
![nested-obj-styling-screenshot2](https://cloud.githubusercontent.com/assets/19827006/16897700/dbe2a738-4b7e-11e6-8020-536908ac6160.PNG)
![nested-obj-styling-screenshot3](https://cloud.githubusercontent.com/assets/19827006/16897699/dbe1419a-4b7e-11e6-8b6a-38bfacc4f2b0.PNG)
![nested-obj-styling-screenshot4](https://cloud.githubusercontent.com/assets/19827006/16897701/dbe34968-4b7e-11e6-895e-945aa2a0e7ef.PNG)

**Comment by erictleung** [comment]
@emily04 thanks for catching this. I guess this challenge was updated recently. 

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9b5c00fcb55c04ffd60357bf84deae01168bb70/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4399) needs to be fixed to have the correct closing `</code>` tag on `gloveBoxContents`. Contributors will just need to add a forward slash `/` in the correct place.

```
...property to the <code>gloveBoxContents</code> variable.....
```

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled `first-timers-only` so only those who have not contributed to the main Free Code Camp repository can fix this issue. Thank you.

**Comment by benschac** [comment]
Hi @erictleung I'm a first timer and would like to tackle this issue.  Let me know if I can grab it!  Thanks!

**Comment by erictleung** [comment]
@benschac go for it! 👍  Please remember to read the contributing guidelines I've linked above on how to format a PR correctly and test your changes (if possible). Thanks!

**Comment by benschac** [comment]
Just want to make sure, do I need to be assigned to the ticket? Is there a waffle.io board I need to be apart of?

**Comment by alayek** [comment]
@benschac at the moment, GitHub lets you assign issues if and if and only if you are part of the collaborators group, so we cannot officially display your screenname as assigned.

However, to all collaborators, for intents and purposes, you are assigned! Take your time and make it a good commit. There is no hurry. If you need help, feel free to reach out to any of us.

Hope that helps :smile: :+1:
