### ISSUE TITLE
Trying to upload project from Github

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#9770]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is the link I am trying to upload: https://interglobalmedia.github.io/simpleweather/

I was uploading from Github before successfully (and I have the green checkmarks to prove it), but now when I click on my project links, I am redirected to the FCC project page. How can this be fixed? I don't use Codepen. Thanks!

**Comment by erictleung** [comment]
@interglobalmedia thanks for the issue. When you say you are "redirected to the FCC project page," are you clicking on the "View Project link on your FreeCodeCamp profile page? If so, I'm correctly directed to your weather app that's on GitHub.

**Comment by alayek** [comment]
@interglobalmedia thanks for filing this issue. Are you talking about the project link under your [FreeCodeCamp portfolio](https://www.freecodecamp.com/interglobalmedia)? Because it seems to point to your GitHub page deployment, which has your project.

Which means the URL you submitted at FreeCodeCamp for that project, is saved in our database accordingly.

Maybe you can provide some screenshot to explain which issue you are facing? I didn't understand what you mean by 
> I was uploading from Github before successfully

**Comment by interglobalmedia** [comment]
I don't know where my head is at today. I clicked on the wrong link. To left instead of to right. Thanks alayek!

**Comment by alayek** [comment]
Oh glad to hear! It's alright.

I am closing this issue for now. If you face any issue regarding this. feel free to reopen this.
