### ISSUE TITLE
Bonfire: Convert HTML Entities - Need more tests

### ISSUE THREAD

**Issue by vzhikness** [FreeCodeCamp/freecodecamp#979]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue.

This bonfire needs more tests. It's too easy to get them passed.

Now it checks only &. I would add tests for <, >, ", '.

**Comment by brandenbyers** [comment]
Agreed. I can add more tests to this one.

However, we also need to properly display the test cases so that the user understands what the test is asking. Currently, the test case reads like this: `expected 'Dolce & Gabbana' to equal 'Dolce & Gabbana'` whereas what we need is something like this: `expected 'Dolce & Gabbana' to equal 'Dolce &amp; Gabbana'

![screen shot 2015-06-19 at 12 13 58 am](https://cloud.githubusercontent.com/assets/7098232/8247560/d0bec446-1618-11e5-95e0-e8a372906d2b.png)

Any have ideas on how to accomplish this?

**Comment by kurzninja** [comment]
This was solved in a recent commit. This issue should be closed.

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production as well!
