### ISSUE TITLE
Case check not done for the result

### ISSUE THREAD

**Issue by Akshit-p** [FreeCodeCamp/FreeCodeCamp#9806]
#### Challenge Name
Manipulate Arrays With unshift

https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift

#### Issue Description

The code doesn't check for the case entered for the array output. 

#### Browser Information

* Google Chrome, Version:  51.0.2704.106 m
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/13155357/16984184/4b083762-4e96-11e6-8305-c2fb78b1605f.png)

**Comment by BKinahan** [comment]
The test isn't very picky about the contents, is it? Even `myArray.unshift(['paul','35']);` passes, with the string `'35'` rather than the number `35`.

The important part is that `unshift` is used correctly, which the test does check for. Still, the value indicated as correct for `myArray` probably should more closely match what is actually tested for.

**Comment by Akshit-p** [comment]
I totally understand that but if the Cases are checked for most of the results then why not this, sure this one is odd but consistency is key. Thanks though

**Comment by BKinahan** [comment]
@Akshit-p Oh, I'm not disagreeing with you, just adding more information 😄 

I think the test for this challenge should be changed to remove the `toLowerCase()`, but I also think tests in all four of the challenges should use strict number comparison to ensure users are entering the correct values.
