### ISSUE TITLE
Odd menu behaviors while on Map in mobile

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9822]
#### Issue Description

While on mobile (real or simulated), Map behavior is odd.

_While on desktop emulated mobile_, menu hides the Free Code Camp logo and ability to close the menu while on Map.

_While on Map on an Android mobile device_, just clicking the Menu button will create this odd "menu" shown in the screenshot below. The menu is first drawn out normally, but just as the menu finished loading, the below screenshot is shown. This oddity will disappear if you click on the menu button again.
#### Browser Information

**Desktop Error**
- Browser Name, Version: Chrome
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop (emulating Mobile)

**Mobile Error**
- Browser Name, Version: Chrome
- Operating System: Android
- Mobile, Desktop, or Tablet: Mobile
#### Screenshot

**Simulated mobile:**

![map](https://cloud.githubusercontent.com/assets/2754821/17007625/28d03646-4e9f-11e6-907e-7168c13af37c.gif)

**Real Android mobile:**

![screenshot_20160720-171936](https://cloud.githubusercontent.com/assets/2754821/17007652/661d9a3e-4e9f-11e6-9cdd-87690120beff.png)

**Comment by Bouncey** [comment]
And for iOS.  

![image](https://cloud.githubusercontent.com/assets/18572518/17238966/39d88ad2-5558-11e6-80e9-026fdd575c12.png)

**Comment by bishoo** [comment]
Ok

بتاريخ ٢٩‏/٠٧‏/٢٠١٦ ٨:٤٨ ص، كتب "Stuart Taylor" <notifications@github.com>:

**Comment by guypy** [comment]
Is this issue still relevant? I'd be happy to fix it, it's my first time contributing to open source.

**Comment by atjonathan** [comment]
@guypy, I believe the issue @Bouncey pointed out is still relevant! Good luck!

**Comment by Bouncey** [comment]
@erictleung I cannot replicate on the emulated mobile view (my phone took a swim over the weekend so I cannot check that view). 

Is this still an issue?

**Comment by systimotic** [comment]
I just tested this on `Chrome for Android 54.0.2840.65`. Here are some details as to what I can and cannot reproduce:
- I can reproduce the map view @Bouncey shared before. This is what I see when navigating to the map, but only when I'm currently on a challenge. If I'm on a page that isn't a challenge, I get the full page map, which works fine.
- I can't reproduce either of the views originally reported by @erictleung.
- When I browse from one React page to another, the menu doesn't close.
- When I collapse all challenges, the top two sections disappear.
- If I'm on a challenge and click the 'Chat' link, it opens with about 30% width, so that only one character is displayed per line.

**Comment by marhyorh** [comment]
@systimotic I fixed them while dealing with other issues
>> https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10899 and 
>> https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10902
