### ISSUE TITLE
Incorrect Test expectation for Confirm the Ending Challenge

### ISSUE THREAD

**Issue by jlheard** [FreeCodeCamp/FreeCodeCamp#9834]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20match%3B%0A%20%20if(target.length%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20match%20%3D%20target%20%3D%3D%20str.substring(str.length-1%2C%20str.length)%3B%20%20%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20var%20words%20%3D%20str.split(%22%20%22)%3B%0A%20%20%20%20var%20lastWord%20%3D%20words%5Bwords.length-1%5D%3B%0A%20%20%20%20match%20%3D%20target%20%3D%3D%3D%20lastWord%3B%0A%20%20%7D%0A%20%20return%20match%3B%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

1. Added console log statements to check the work, and I see that me and name do not match and should be false, but the test is expecting it to be true. 

If I understand the challenge correctly, it's to make sure that the last letter or word in the string matches the target respectively.  The last word of the string "He has to give me a new **name**" is **name**, and the target is "**me**".  **me** and **name** do not match so the test, _confirmEnding("He has to give me a new **name**", "**me**") should return **true**_, should actually return **false**; correct?

<img width="1411" alt="screen shot 2016-07-21 at 2 03 09 pm" src="https://cloud.githubusercontent.com/assets/1328792/17033390/ee4cf998-4f4b-11e6-8ede-2d4527225e18.png">

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var match;
  if(target.length === 1) {
    match = target == str.substring(str.length-1, str.length);    
  } else {
    var words = str.split(" ");
    var lastWord = words[words.length-1];
    match = target === lastWord;
  }
  return match;
}

confirmEnding("Bastian", "n");

```

**Comment by BKinahan** [comment]
The string `"name"` ends with the string `"me"`, so this is true for the complete string `"He has to give me a new name"` also. Note that a string is a sequence of (zero or more) characters, rather than necessarily being one character or a full word.

This misunderstanding recurs from time to time, eg #9021, #9694 and others. Maybe this justifies a clarification in the instructions.

**Comment by jlheard** [comment]
OK I see. I'll just use regexp. thanks.

**Comment by BKinahan** [comment]
@jlheard This was my search: https://github.com/FreeCodeCamp/FreeCodeCamp/issues?utf8=%E2%9C%93&q=is%3Aissue%20confirm%20

The default issue search includes `is:open` and that must be changed to `is:closed` to match only closed issues or removed to match all issues. 

The other issues about this are closed, because they were correctly judged not to be caused by a bug. I'm in favor of keeping this one open for discussion to figure out if it's worth amending the instructions to make them clearer, since the misunderstanding comes up every now and then.

**Comment by jlheard** [comment]
@BKinahan OK, perhaps if the test was changed from:

confirmEnding("He has to give me a new name", "me") should return true 

to

confirmEnding("Opensesame", "me") should return true

would make it more clear?

**Comment by BKinahan** [comment]
@jlheard You know, that's something I hadn't considered before. I didn't realize the confusion was coming from the fact that the word `"me"` appears earlier in the string, so thanks for pointing that out! 😄 

I like the idea for using the phrase "Open sesame" (with title case to match the other tests rather than camelCase). It might be good to replace these two tests:
>`confirmEnding("He has to give me a new name", "me")` should return true.
>`confirmEnding("He has to give me a new name", "na")` should return false.

with:

>`confirmEnding("Open sesame", "same")` should return true.
>`confirmEnding("Open sesame", "pen")` should return false.

They test for similar conditions but should be much clearer without that ambiguity about an earlier-appearing string recurring at the end.

**Comment by erictleung** [comment]
@jlheard thanks for the issue. I also didn't know where the confusion was coming from.

@BKinahan I like your suggested changes to those two tests :+1:
