### ISSUE TITLE
Error in the text on FreeCodeCamp..!?

### ISSUE THREAD

**Issue by hasanshahoud** [FreeCodeCamp/FreeCodeCamp#9844]
Please pay **attention** on the red box I selected it on the picture ,,
inside the text you wrote it already it should including the word "**true**" in the  quotes,,?

Greetings, Hasan

https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery

![disable an element using jquery free code camp](https://cloud.githubusercontent.com/assets/20051470/17055620/3fbd3f78-500e-11e6-9076-d1ee7285d8e5.png)

**Comment by raisedadead** [comment]
@hasanshahoud:

Hi Hasan,

Thanks for reporting, first of all the challenge link you mentioned above is different than that of the screenshot. I think you are referring to https://www.freecodecamp.com/challenges/disable-an-element-using-jquery in the screenshot.

Also the code is there because you might have accidentaly visited someone else's link or maybe you have already attempted the challenge earlier, due to which the code is saved in your local browser cache.

A simple Reset (Button below the Run Tests) and refresh should clean the code.
Happy coding.

**Comment by hasanshahoud** [comment]
@raisedadead 
that's right the link was wrong and I edited now ..thanks
and you can try yourself and push the button it does't work , i tried before..
and hope they fix it soon..

**Comment by raisedadead** [comment]
Do you mean the "reset" button does not work or the "run tests" don't work?
