### ISSUE TITLE
JS: "Manipulating Complex Objects": missing comma in line 12 

### ISSUE THREAD

**Issue by Ailokin** [FreeCodeCamp/FreeCodeCamp#9858]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%0A%20%20%7B%0A%20%20%20%20artist%3A%20%22U2%22%2C%0A%20%20%20%20title%3A%20%22October%20Sky%22%2C%0A%20%20%20%20release_year%3A%201982%2C%0A%20%20%20%20formats%3A%20%5B%0A%20%20%20%20%20%20%22LP%22%2C%0A%20%20%20%20%20%20%22Cassette%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The code as appears below (my final answer) works; but the FCC user must add the comma above the "//Add record here" line: this is misleading since usually FCC problems direct the user to just change certain parts of the code; however, here the user must add a comma to the FCC code outside the part the user is directed to change (which leads to wasted time and fruitless head-scratching).

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
  // Add record here
  
  {
    artist: "U2",
    title: "October Sky",
    release_year: 1982,
    formats: [
      "LP",
      "Cassette"
    ]
  }
];


```

**Comment by BKinahan** [comment]
A user can add a comma *after* the `// Add record here` line, but it will raise a pair of comma warnings in the linter..

However, I wouldn't say that the comma is missing from the seed code since it represents `myMusic` as an array with a single item to which someone might add objects as the music collection grows. Similarly, we wouldn't ask a user to add the number `5` to the end of an array and show them 
`var myArray = [0,1,2,3,4,];`. The challenge should ensure an understanding of the data structure and not simply require the user to perform a copy/paste.

If the placement of the `// Add record here` line is causing confusion, is there somewhere it can go that provides more clarity? If it were above the first object in the array, it would probably be more confusing and lead users to attempt to add artist information etc. within the existing object. Perhaps the comment line could be amended to reinforce the note near the end of the instructions regarding comma placement, but that might be a bit much.

**Comment by raisedadead** [comment]
@BKinahan I don't think its necessary to clarify more than the instructions already have. True that at many places we have mentioned in the to edit code only in certain areas of the seed code like 

`// only change the code below this line`

but that doesn't mean campers get very comfortable and start not reading what the instructions or the comments say. This is a good case to break that zone, IMHO.

Because at the end of the say as a camper I am not just typing in code but I am learning, and paying attention to details is one quality to be learned.

@Ailokin thanks for reporting, but I feel that any further clarification for the placement of comma would be spoon feeding.

**Comment by clewman** [comment]
I couldn't figure out why my code wasn't working. Found this, added the comma as you suggested, and it works. Maybe we're not supposed to need the comma, but FCC won't pass you unless it's there. So, it IS a bug, especially because it's above the line.

**Comment by seunzone** [comment]
Carefully watch the way I place the commas. I had same issue and discovered also that the commas has to be well placed:
`var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
  // Add record here
   { 
"artist": "Fela Kuti",
"title": "Happy Boy",
"release_year": 2017,
"formats": [
"mp3",
"cd",
"tape"
]
}
];
`

**Comment by bebosh** [comment]
I Had the same problem, but after @raisedadead commen i figured out to look better at the suggestions (in this case the json link). Thanks!
