### ISSUE TITLE
Embedded Images Not Displaying

### ISSUE THREAD

**Issue by Icey88** [FreeCodeCamp/FreeCodeCamp#9876]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Issue is to do with the example webpage (https://codepen.io/FreeCodeCamp/full/YqLyXB/).

Images return what looks like a cpanel 404 error when trying to view images.

Example:
http://qlip.in/sites/default/files/qlip.png

**Comment by raisedadead** [comment]
@Icey88 thanks for reporting. 

The example was originally made by @hallaathrad and seems the content images are now offline. 
Looking into it.

**Comment by hallaathrad** [comment]
Hey all... Didn't see this until now. Gitter is acting up.
@raisedadead please hit me up over private so I can go into FCC's codepen and fix it.
The problem originated from my server migration last week.

hahaha I knew having my portfolio in someone else's codepen would turn into a problem since I don't get to personally edit it. 
That's why we wanted it on my own codepen to begin with. Who changed it again? when?
Never mind, just hit me up over the weekend and we'll get it fixed.

**Comment by hallaathrad** [comment]
Thanks I've replaced the links to the new server and it all should be fine now 👍

Fixed. Closing happily :)

**Comment by raisedadead** [comment]
Thanks a ton @hallaathrad !
