### ISSUE TITLE
Doesn't assign the numbers

### ISSUE THREAD

**Issue by er-n35t** [FreeCodeCamp/FreeCodeCamp#9926]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.

it still throws following errors: 
- "a should be defined and have a value of 6"
- "b should be defined and have a value of 15"

My code:
```javascript

// Initialize these three variables
var a = 6;
var b = 15;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by SparklesPancake** [comment]
Hi er-n35t,

I haven't learned much JS yet, but I believe the first line is to initialize the variable and not to assign values.

I tried the following and it worked for me:

var a;
var b;
var c;

a = 5;
b = 10;
c = "I am a";

**Comment by Jaskaranbir** [comment]
@er-n35t You are assigning wrong values. I suggest you read `Instructions` for the challenge. The correct values are mentioned there (which are `5` and `10` respectively instead of `6` and `5`). Although that being said, The challenge seems to have a bug with showing incorrect conditions for passing test :D

@SparklesPancake It does not make a difference. Its essentially same as how @er-n35t defined variables. :)

**Comment by erictleung** [comment]
@er-n35t as @Jaskaranbir has pointed out, please re-read the instructions

> Initialize the three variables `a`, `b`, and `c` with `5`, `10`, and `"I am a"` respectively so that they will not be undefined.

Those instructions are for the variables underneath the comment `// Initialize these three variables`. As the comment `// Do not change code below this line` suggest, do not change the code below that line in the editor.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
