### ISSUE TITLE
TypeError in Find the Longest Word in a String

### ISSUE THREAD

**Issue by woohooAgain** [FreeCodeCamp/FreeCodeCamp#9939]
#### Find the Longest Word in a String

https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=function%20findLongestWord(str)%20%7B%0A%20%20var%20unordArr%20%3D%20str.split('%20')%3B%0A%20%20var%20ordArr%20%3D%20unordArr.map(str.length)%3B%0A%20%20ordArr.sort(function(a%2Cb)%7B%0A%20%20%20%20return%20a%20-%20b%3B%0A%20%20%7D)%3B%0A%20%20var%20longest%20%3D%20ordArr.pop()%3B%0A%20%20return%20longest%3B%0A%7D%0A%0AfindLongestWord(%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22)%3B

#### Issue Description
Suddenly instead of returning any values I got a permanent output "TypeError: 44 is not a function.

#### Browser Information

* Browser Name, Version: Google Chrome 51.0.2704.103 m (64-bit) 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
`function findLongestWord(str) {
  var arr = str.split(' ');
  var ordArr = arr.map(str.length);
  ordArr.sort(function(a,b){
    return (a - b);
  });
  var longest = ordArr.pop();
  return longest;
}

findLongestWord("The quick brown fox jumped over the lazy dog");`

#### Screenshot

![default](https://cloud.githubusercontent.com/assets/17934308/17227187/caa2f90a-5515-11e6-9e18-7119e95ba24d.PNG)

**Comment by oalhait** [comment]
You're getting a weird TypeError because you have the call to findLongestWord at the end, which messes up the code tester. I removed the last line, and the TypeError disappeared. 

I also played around with your code a little bit, and you're getting the right idea, but you're overthinking it a little bit. Instead of using a sort function (which is time consuming), consider using a simple for loop to find the longest length, like so: 
```javascript
function findLongestWord(str) {
  var arr = str.split(' ');
  var bestLength = 0;
  for(var i = 0; i < arr.length; i++) {
    if(bestLength < arr[i].length) {
      bestLength = arr[i].length;
    }
  }
  return bestLength;
}
```

Hope this helped! Let me know if you have any more questions.

**Comment by erictleung** [comment]
@woohooAgain the issue is with your `.map` method. Check what value you get when you do `str.length` on the test string.

```js
"The quick brown fox jumped over the lazy dog".length;
```

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues are not for coding help. Happy coding!
