### ISSUE TITLE
Adding second img

### ISSUE THREAD

**Issue by mafunk92** [FreeCodeCamp/freecodecamp#998]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The second goal for adding a second image is not getting cleared when I add : 
```
<img src='http://bit.ly/fcc-kittens2'/> or
<img class='img-responsive' src='http://bit.ly/fcc-kittens2'/>
```
![screenshot 2015-06-19 at 11 53 36 am](https://cloud.githubusercontent.com/assets/7672276/8260646/e1d44ca4-1679-11e5-8974-c9ed82a56021.png)

![screenshot 2015-06-19 at 11 55 31 am](https://cloud.githubusercontent.com/assets/7672276/8260690/2d025806-167a-11e5-953b-ec1b7ea4169f.png)

**Comment by QuincyLarson** [comment]
The code you shared works fine for me. Which version of Chrome are you using?

**Comment by digitaldak** [comment]
Hope I can explain this well enough, but I was tried a few things when I saw this issue on the waffle board.

```<img src='http://bit.ly/fcc-kittens2'/>``` will fail because the test is checking to find it, the src link, first and then cascade checks for the css class required as well. I can see if you put the css class on the first image tag and put the above line in it will show the first test passed but the second will fail because the css class isn't chain found from the src find as it isn't on the source.

![waypoint-mobile-responsive-images-part1](https://cloud.githubusercontent.com/assets/3256176/8270257/09d628a4-178c-11e5-90ef-7e1882de3cdc.png)


That said, the second one( ```<img class='img-responsive' src='http://bit.ly/fcc-kittens2'/>```) will also fail the second test for some reason. I haven't figured out how yet but I'm working through the test to see if I can do it.
So far to repeat it, add the css class to the first img tag:
```<a href='#'><img class='smaller-image thick-green-border img-responsive' src='https://bit.ly/fcc-kittens'/></a>```

And then add the second img as shown above:
```
<a href='#'><img class='smaller-image thick-green-border img-responsive' src='https://bit.ly/fcc-kittens'/></a>
<img class='img-responsive' src='http://bit.ly/fcc-kittens2'/>
```
That will show the first test pass (because the first test is only looking for the css class and will pass on the wrong element), but the second test will fail still until you remove the ```img-responsive``` from the first img.
![waypoint-mobile-responsive-images-part2](https://cloud.githubusercontent.com/assets/3256176/8270258/14de01d6-178c-11e5-96d4-7de2b0bbf0af.png)

The only reason i suspect this may be the cause is you can't see the first img tag in his example so that just seemed like a good thing to try as it said it already detected the img-responsive somewhere, logic says the first img tag.

Hope thats Qunicy & team.

**Comment by digitaldak** [comment]
Actually it makes sense how why the second test fails, because the text it's looking for is being applied to the element found by checking the src, with the first img having the wrong link it will auto fail the second test. By removing the class the second img gets picked up and instantly passes.

The tests should probably also include a new test to check for the # of img tags to ensure there is more than one.
For example:
![waypoint-mobile-responsive-images-part3](https://cloud.githubusercontent.com/assets/3256176/8270288/9e158cca-178d-11e5-81ab-940b89e774e8.png)

**Comment by jayGorio** [comment]
This worked for me. First i need to copy the first img together with all of its class. Then paste it for the second image. Then remove the first img-responsive class in the first img
  
![bootcamp](https://cloud.githubusercontent.com/assets/11474751/9102297/1ae13600-3c23-11e5-82bf-204cf9d90b06.PNG)
